Doc: IGLib with source files: IG.Num.AnalysisResultsExtensions Class Reference
IG.Num.AnalysisResultsExtensions Class Reference
Extension methods for analysis results classes.
Static Public Member Functions
static string ToString (IAnalysisResults anres)
Returns a string representation of the current analysis results object in a standard IGLib form. Extension method for IAnalysisResults.
static string ToStringMath (IAnalysisResults anres)
Returns a string representation of the current analysis results object in a standard IGLib form (Mathematica-like format but with C representation of numbers). Extension method for IAnalysisResults.
static string ToStringMathRequest (this IAnalysisResults anres)
Returns a string representation of the current analysis request object in a standard IGLib form (Mathematica-like format but with C representation of numbers). Extension method for IAnalysisResults.
static void SaveRequestMath (this IAnalysisResults anres, string filePath)
Saves the current analysis request to a file. If the file already exists then it is overwritten. Extension method for IAnalysisResults.
static void SaveRequestMath (this IAnalysisResults anres, string filePath, bool append)
Saves the current analysis request to a file. Extension method for IAnalysisResults.
static void SaveMath (this IAnalysisResults anres, string filePath)
Saves the current analysis results to a file. If the file already exists then it is overwritten. Extension method for IAnalysisResults.
static void SaveMath (this IAnalysisResults anres, string filePath, bool append)
Saves the current analysis results to a file. Extension method for IAnalysisResults.
Detailed Description
Extension methods for analysis results classes.
$A Igor Apr11;
Definition at line 18 of file AnalysisResults.cs.
Member Function Documentation
ToString()
static string IG.Num.AnalysisResultsExtensions.ToString (IAnalysisResults anres) inline static
Returns a string representation of the current analysis results object in a standard IGLib form. Extension method for IAnalysisResults.
Parameters
anres Object whose string representation is returned.
Definition at line 24 of file AnalysisResults.cs.
References IG.Num.AnalysisResults.ToString().
ToStringMath()
static string IG.Num.AnalysisResultsExtensions.ToStringMath (IAnalysisResults anres) inline static
Returns a string representation of the current analysis results object in a standard IGLib form (Mathematica-like format but with C representation of numbers). Extension method for IAnalysisResults.
Parameters
anres Object whose string representation is returned.
Definition at line 34 of file AnalysisResults.cs.
References IG.Num.AnalysisResults.ToStringMath().
ToStringMathRequest()
static string IG.Num.AnalysisResultsExtensions.ToStringMathRequest (this IAnalysisResults anres) inline static
Returns a string representation of the current analysis request object in a standard IGLib form (Mathematica-like format but with C representation of numbers). Extension method for IAnalysisResults.
Parameters
anres Object whose string representation is returned.
Definition at line 44 of file AnalysisResults.cs.
References IG.Num.AnalysisResults.ToStringRequestMath().
SaveRequestMath() [1/2]
static void IG.Num.AnalysisResultsExtensions.SaveRequestMath (this IAnalysisResults anres, string filePath) inline static
Saves the current analysis request to a file. If the file already exists then it is overwritten. Extension method for IAnalysisResults.
Parameters
anres Object from which analysis request is saved.
filePath Path to the file where analysis request is stored.
Definition at line 56 of file AnalysisResults.cs.
References IG.Num.AnalysisResults.SaveRequestMath().
SaveRequestMath() [2/2]
static void IG.Num.AnalysisResultsExtensions.SaveRequestMath (this IAnalysisResults anres, string filePath, bool append) inline static
Saves the current analysis request to a file. Extension method for IAnalysisResults.
Parameters
anres Object from which analysis request is saved.
filePath Path to the file where analysis request is stored.
append If true then contents are appended to the end of the file if the file already exists.
Definition at line 67 of file AnalysisResults.cs.
References IG.Num.AnalysisResults.SaveRequestMath().
SaveMath() [1/2]
static void IG.Num.AnalysisResultsExtensions.SaveMath (this IAnalysisResults anres, string filePath) inline static
Saves the current analysis results to a file. If the file already exists then it is overwritten. Extension method for IAnalysisResults.
Parameters
anres Object from which analysis results are saved.
filePath Path to the file where analysis results are stored.
Definition at line 78 of file AnalysisResults.cs.
References IG.Num.AnalysisResults.SaveMath().
SaveMath() [2/2]
static void IG.Num.AnalysisResultsExtensions.SaveMath (this IAnalysisResults anres, string filePath, bool append) inline static
Saves the current analysis results to a file. Extension method for IAnalysisResults.
Parameters
anres Object from which analysis results are saved.
filePath Path to the file where analysis results are stored.
append If true then contents are appended to the end of the file if the file already exists.
Definition at line 89 of file AnalysisResults.cs.
References IG.Num.AnalysisResults.SaveMath().
The documentation for this class was generated from the following file:
iglib/igbase/optimization/AnalysisResults.cs