Doc: IGLib with source files: IGLib.Core.CollectionTypeConverter Class Reference
IGLib.Core.CollectionTypeConverter Class Reference
A type converter that supports conversion between basic types and a wide range of collection types, including jagged arrays, rectangular arrays, generic lists, and enumerable sequences. Supports element-wise type conversion and flattening where appropriate.
Public Member Functions
override object ConvertToType (object value, Type targetType)
Converts a value to the specified target type, supporting collections. Conversion is bsed on the actual type of value and the specified target type (targetType). See the class description for more details.
Public Member Functions inherited from IGLib.Core.BasicTypeConverter
T ConvertToType< T > (object value)
Converts the specified value to the specified target type.
void ConvertToType< T > (object value, out T result)
Converts the specified value to the specified target type.
Private Member Functions
object ConvertFromJaggedArray (Array sourceArray, Type targetType)
Converts a jagged array to a 1D array, List<T>, or other flat collection.
void PopulateJaggedArrayWithConversion (object target, object source, Type leafTargetType)
Recursively converts and assigns values from source jagged array to target jagged array.
IEnumerable< object > FlattenJaggedArray (Array array)
Recursively flattens a jagged array into a linear sequence.
object ConvertJaggedToRectangular (Array sourceArray, Type targetType)
Converts a uniform jagged array to a rectangular array if shapes match.
bool IsUniformJaggedArray (Array array)
Checks if all subarrays at each level of a jagged array have equal lengths.
List< int > GetJaggedArrayShape (Array array)
Infers the shape (lengths at each level) of a uniform jagged array.
object ConvertRectangularToJagged (Array sourceArray, Type targetType)
Converts a rectangular array to a jagged array with matching shape and converted values.
Array CreateJaggedArray (Type elementType, int[] dims, int level)
Creates an empty jagged array of the given shape and element type.
void PopulateJaggedArray (object target, List< object > values, Type elementType, ref int index)
Populates a jagged array with converted values from a flat list.
object ConvertEnumerable (object value, Type targetType)
Converts any enumerable collection to a target collection type.
object ConvertRectangularArray (object value, Type targetArrayType)
Converts rectangular arrays to other arrays or flat collections.
IEnumerable< object > FlattenRectangularArray (Array sourceArray)
Flattens a rectangular array to an IEnumerable of its elements.
Static Private Member Functions
static bool ImplementsGenericInterface (Type candidateType, Type genericInterface)
Checks if a type is or implements a specific generic interface (e.g., IEnumerable<>).
static bool IsJaggedArray (Type type)
Determines if the array is jagged (array of arrays).
static Type GetElementType (Type type)
Gets the element type of a collection or array.
static Type GetJaggedArrayLeafElementType (Type type)
Recursively gets the leaf element type of a jagged array (e.g., int from int[][][]).
Additional Inherited Members
Static Public Member Functions inherited from IGLib.Core.BasicTypeConverter
static bool IsNullableType (Type type)
Determines whether the specified type is nullable.
Static Public Attributes inherited from IGLib.Core.BasicTypeConverter
const bool DefaultOutputFullTypeNames = false
Default value of OutputFullTypeNames.
const string NullTypeString = "[[null type]]"
Protected Member Functions inherited from IGLib.Core.BasicTypeConverter
string TypeName (Type type)
Returns name of the specified type type , dependent on the property OutputFullTypeNames: if it is true then the full type name is returned (obtained by Type.FullName), otherwise the short name is returned (obtained by Type.Name).
Properties inherited from IGLib.Core.BasicTypeConverter
bool OutputFullTypeNames = DefaultOutputFullTypeNames [get, set]
Whether to take full type names in exception messages and elsewhere.
Detailed Description
A type converter that supports conversion between basic types and a wide range of collection types, including jagged arrays, rectangular arrays, generic lists, and enumerable sequences. Supports element-wise type conversion and flattening where appropriate.
This class extends the BasicTypeConverter with additional capabilities for array-like objects. The class is is trimming-safe and Blazor/AOT-friendly.
Capabilities:
* All capabilities of BasicTypeConverter (e.g. conversion of types that implement IConvertible interface), like int <=> double, etc., double <=> string, etc., derived class => base class.
* Various array-like conversios, with element-wise type conversions supported by BasicTypeConverter, if necessary:
* 1D <=> 1D (TSource[], List{TSource}, IEnumerable{TSource} <=> TTarget[], List{TTarget}, IEnumerable{TTarget})
* Multidimensional => 1D conversions (TSource[,,...], TSource[][]... <=> TTarget[], List{TTarget}), IEnumerable{TTarget}, IList{TTarget}
* Multidimensional <=> Multidimensional (only for rank and dimensions matching exactly)
Definition at line 22 of file CollectionTypeConverter.cs.
Member Function Documentation
ConvertToType()
override object IGLib.Core.CollectionTypeConverter.ConvertToType (object value, Type targetType) inline virtual
Converts a value to the specified target type, supporting collections. Conversion is bsed on the actual type of value and the specified target type (targetType). See the class description for more details.
Takes a value of type object, identifies its actual type, converts it to the type compatible with the specified desired target type, and returns the converted value as object.
Parameters
value The input object to be converted.
targetType The desired target type.
Returns
The converted object compatible with the target type.
Reimplemented from IGLib.Core.BasicTypeConverter.
Reimplemented in IGLib.CoreExtended.ReflectionTypeConverter.
Definition at line 35 of file CollectionTypeConverter.cs.
References IGLib.Core.CollectionTypeConverter.ConvertEnumerable(), IGLib.Core.CollectionTypeConverter.ConvertFromJaggedArray(), IGLib.Core.CollectionTypeConverter.ConvertRectangularArray(), IGLib.Core.CollectionTypeConverter.ConvertRectangularToJagged(), IGLib.Core.CollectionTypeConverter.ImplementsGenericInterface(), and IGLib.Core.CollectionTypeConverter.IsJaggedArray().
Referenced by IGLib.Core.CollectionTypeConverter.ConvertEnumerable(), IGLib.Core.CollectionTypeConverter.ConvertFromJaggedArray(), IGLib.Core.CollectionTypeConverter.ConvertJaggedToRectangular(), IGLib.Core.CollectionTypeConverter.ConvertRectangularArray(), IGLib.Core.CollectionTypeConverter.PopulateJaggedArray(), and IGLib.Core.CollectionTypeConverter.PopulateJaggedArrayWithConversion().
ImplementsGenericInterface()
static bool IGLib.Core.CollectionTypeConverter.ImplementsGenericInterface (Type candidateType, Type genericInterface) inline static private
Checks if a type is or implements a specific generic interface (e.g., IEnumerable<>).
Parameters
candidateType The type to check.
genericInterface The generic interface definition, e.g., typeof(IEnumerable<>).
Returns
True if the type is or implements the given generic interface.
Definition at line 91 of file CollectionTypeConverter.cs.
Referenced by IGLib.Core.CollectionTypeConverter.ConvertEnumerable(), IGLib.Core.CollectionTypeConverter.ConvertFromJaggedArray(), IGLib.Core.CollectionTypeConverter.ConvertRectangularArray(), and IGLib.Core.CollectionTypeConverter.ConvertToType().
ConvertFromJaggedArray()
object IGLib.Core.CollectionTypeConverter.ConvertFromJaggedArray (Array sourceArray, Type targetType) inline private
Converts a jagged array to a 1D array, List<T>, or other flat collection.
Parameters
sourceArray The jagged array to flatten and convert.
targetType The type of collection to convert to.
Returns
The flattened collection converted to the target type.
Definition at line 106 of file CollectionTypeConverter.cs.
References IGLib.Core.CollectionTypeConverter.ConvertJaggedToRectangular(), IGLib.Core.CollectionTypeConverter.ConvertToType(), IGLib.Core.CollectionTypeConverter.CreateJaggedArray(), IGLib.Core.CollectionTypeConverter.FlattenJaggedArray(), IGLib.Core.CollectionTypeConverter.GetElementType(), IGLib.Core.CollectionTypeConverter.GetJaggedArrayLeafElementType(), IGLib.Core.CollectionTypeConverter.GetJaggedArrayShape(), IGLib.Core.CollectionTypeConverter.ImplementsGenericInterface(), IGLib.Core.CollectionTypeConverter.IsJaggedArray(), and IGLib.Core.CollectionTypeConverter.PopulateJaggedArrayWithConversion().
Referenced by IGLib.Core.CollectionTypeConverter.ConvertToType().
PopulateJaggedArrayWithConversion()
void IGLib.Core.CollectionTypeConverter.PopulateJaggedArrayWithConversion (object target, object source, Type leafTargetType) inline private
Recursively converts and assigns values from source jagged array to target jagged array.
Definition at line 155 of file CollectionTypeConverter.cs.
References IGLib.Core.CollectionTypeConverter.ConvertToType().
Referenced by IGLib.Core.CollectionTypeConverter.ConvertFromJaggedArray().
FlattenJaggedArray()
IEnumerable<object> IGLib.Core.CollectionTypeConverter.FlattenJaggedArray (Array array) inline private
Recursively flattens a jagged array into a linear sequence.
Parameters
array The jagged array to flatten.
Returns
A flattened sequence of all inner elements.
Definition at line 182 of file CollectionTypeConverter.cs.
Referenced by IGLib.Core.CollectionTypeConverter.ConvertFromJaggedArray(), and IGLib.Core.CollectionTypeConverter.ConvertJaggedToRectangular().
IsJaggedArray()
static bool IGLib.Core.CollectionTypeConverter.IsJaggedArray (Type type) inline static private
Determines if the array is jagged (array of arrays).
Parameters
type The array type to inspect.
Returns
True if jagged; otherwise false.
Definition at line 203 of file CollectionTypeConverter.cs.
Referenced by IGLib.Core.CollectionTypeConverter.ConvertFromJaggedArray(), and IGLib.Core.CollectionTypeConverter.ConvertToType().
GetElementType()
static Type IGLib.Core.CollectionTypeConverter.GetElementType (Type type) inline static private
Gets the element type of a collection or array.
Parameters
type The type to examine.
Returns
The element type, or null if not found.
Definition at line 213 of file CollectionTypeConverter.cs.
Referenced by IGLib.Core.CollectionTypeConverter.ConvertEnumerable(), IGLib.Core.CollectionTypeConverter.ConvertFromJaggedArray(), and IGLib.Core.CollectionTypeConverter.ConvertRectangularArray().
ConvertJaggedToRectangular()
object IGLib.Core.CollectionTypeConverter.ConvertJaggedToRectangular (Array sourceArray, Type targetType) inline private
Converts a uniform jagged array to a rectangular array if shapes match.
Parameters
sourceArray The jagged array with uniform shape.
targetType The rectangular array type to convert to.
Returns
A rectangular array with converted elements.
Definition at line 236 of file CollectionTypeConverter.cs.
References IGLib.Core.CollectionTypeConverter.ConvertToType(), IGLib.Core.CollectionTypeConverter.FlattenJaggedArray(), IGLib.Core.CollectionTypeConverter.GetJaggedArrayShape(), and IGLib.Core.CollectionTypeConverter.IsUniformJaggedArray().
Referenced by IGLib.Core.CollectionTypeConverter.ConvertFromJaggedArray().
IsUniformJaggedArray()
bool IGLib.Core.CollectionTypeConverter.IsUniformJaggedArray (Array array) inline private
Checks if all subarrays at each level of a jagged array have equal lengths.
Parameters
array The jagged array to validate.
Returns
True if the shape is uniform; otherwise false.
Definition at line 271 of file CollectionTypeConverter.cs.
Referenced by IGLib.Core.CollectionTypeConverter.ConvertJaggedToRectangular().
GetJaggedArrayShape()
List<int> IGLib.Core.CollectionTypeConverter.GetJaggedArrayShape (Array array) inline private
Infers the shape (lengths at each level) of a uniform jagged array.
Parameters
array The jagged array.
Returns
A list of dimensions per level.
Definition at line 308 of file CollectionTypeConverter.cs.
Referenced by IGLib.Core.CollectionTypeConverter.ConvertFromJaggedArray(), and IGLib.Core.CollectionTypeConverter.ConvertJaggedToRectangular().
ConvertRectangularToJagged()
object IGLib.Core.CollectionTypeConverter.ConvertRectangularToJagged (Array sourceArray, Type targetType) inline private
Converts a rectangular array to a jagged array with matching shape and converted values.
Parameters
sourceArray The rectangular array to convert.
targetType The target jagged array type.
Returns
The jagged array filled with values.
Definition at line 328 of file CollectionTypeConverter.cs.
References IGLib.Core.CollectionTypeConverter.CreateJaggedArray(), IGLib.Core.CollectionTypeConverter.FlattenRectangularArray(), IGLib.Core.CollectionTypeConverter.GetJaggedArrayLeafElementType(), and IGLib.Core.CollectionTypeConverter.PopulateJaggedArray().
Referenced by IGLib.Core.CollectionTypeConverter.ConvertToType().
GetJaggedArrayLeafElementType()
static Type IGLib.Core.CollectionTypeConverter.GetJaggedArrayLeafElementType (Type type) inline static private
Recursively gets the leaf element type of a jagged array (e.g., int from int[][][]).
Definition at line 345 of file CollectionTypeConverter.cs.
Referenced by IGLib.Core.CollectionTypeConverter.ConvertFromJaggedArray(), and IGLib.Core.CollectionTypeConverter.ConvertRectangularToJagged().
CreateJaggedArray()
Array IGLib.Core.CollectionTypeConverter.CreateJaggedArray (Type elementType, int[] dims, int level) inline private
Creates an empty jagged array of the given shape and element type.
Parameters
elementType The leaf type of the array.
dims The shape (lengths) of the array at each level.
level The current depth level.
Returns
A jagged array with the specified structure.
Definition at line 359 of file CollectionTypeConverter.cs.
Referenced by IGLib.Core.CollectionTypeConverter.ConvertFromJaggedArray(), and IGLib.Core.CollectionTypeConverter.ConvertRectangularToJagged().
PopulateJaggedArray()
void IGLib.Core.CollectionTypeConverter.PopulateJaggedArray (object target, List< object > values, Type elementType, ref int index) inline private
Populates a jagged array with converted values from a flat list.
Parameters
target The jagged array to fill.
values The flat list of values.
elementType The final (leaf) element type.
index A ref index tracking position in the flat list.
Returns
Nothing (fills array in-place).
Definition at line 387 of file CollectionTypeConverter.cs.
References IGLib.Core.CollectionTypeConverter.ConvertToType().
Referenced by IGLib.Core.CollectionTypeConverter.ConvertRectangularToJagged().
ConvertEnumerable()
object IGLib.Core.CollectionTypeConverter.ConvertEnumerable (object value, Type targetType) inline private
Converts any enumerable collection to a target collection type.
Parameters
value The source enumerable object.
targetType The desired target collection type.
Returns
A new collection with converted elements.
Definition at line 414 of file CollectionTypeConverter.cs.
References IGLib.Core.CollectionTypeConverter.ConvertToType(), IGLib.Core.CollectionTypeConverter.GetElementType(), and IGLib.Core.CollectionTypeConverter.ImplementsGenericInterface().
Referenced by IGLib.Core.CollectionTypeConverter.ConvertToType().
ConvertRectangularArray()
object IGLib.Core.CollectionTypeConverter.ConvertRectangularArray (object value, Type targetArrayType) inline private
Converts rectangular arrays to other arrays or flat collections.
Parameters
value The rectangular source array.
targetArrayType The target array or collection type.
Returns
The converted collection or array.
Definition at line 452 of file CollectionTypeConverter.cs.
References IGLib.Core.CollectionTypeConverter.ConvertToType(), IGLib.Core.CollectionTypeConverter.FlattenRectangularArray(), IGLib.Core.CollectionTypeConverter.GetElementType(), and IGLib.Core.CollectionTypeConverter.ImplementsGenericInterface().
Referenced by IGLib.Core.CollectionTypeConverter.ConvertToType().
FlattenRectangularArray()
IEnumerable<object> IGLib.Core.CollectionTypeConverter.FlattenRectangularArray (Array sourceArray) inline private
Flattens a rectangular array to an IEnumerable of its elements.
Parameters
sourceArray Rectangular array to flatten.
Returns
Flattened sequence of array elements.
Definition at line 507 of file CollectionTypeConverter.cs.
Referenced by IGLib.Core.CollectionTypeConverter.ConvertRectangularArray(), and IGLib.Core.CollectionTypeConverter.ConvertRectangularToJagged().
The documentation for this class was generated from the following file:
IGLibGraphics3D/src/IGLib.Graphics3D/other/TypeConversion/CollectionTypeConverter.cs