Doc: IGLib with source files: JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.PPScopeState Class Reference
JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.PPScopeState Class Reference
Public Types
enum JsonScope { JsonScope.Object, JsonScope.Array }
Public Member Functions
void PushObjectContextOntoStack ()
JsonScope PopJsonType ()
void PushJsonArrayType ()
Properties
bool IsTopTypeArray [get]
int ScopeDepth [get]
Private Attributes
readonly Stack< JsonScope > _jsonScopeStack = new Stack<JsonScope>()
Detailed Description
Definition at line 9 of file PPScopeState.cs.
Member Enumeration Documentation
JsonScope
enum JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.PPScopeState.JsonScope strong
Enumerator
Object
Array
Definition at line 15 of file PPScopeState.cs.
Member Function Documentation
PushObjectContextOntoStack()
void JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.PPScopeState.PushObjectContextOntoStack () inline
Definition at line 50 of file PPScopeState.cs.
References JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.PPScopeState._jsonScopeStack.
Referenced by JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.EnterObjectScope().
PopJsonType()
JsonScope JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.PPScopeState.PopJsonType () inline
Returns
Definition at line 59 of file PPScopeState.cs.
References JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.PPScopeState._jsonScopeStack.
Referenced by JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.CloseCurrentScope().
PushJsonArrayType()
void JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.PPScopeState.PushJsonArrayType () inline
Definition at line 67 of file PPScopeState.cs.
References JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.PPScopeState._jsonScopeStack.
Referenced by JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.EnterArrayScope().
Member Data Documentation
_jsonScopeStack
readonly Stack<JsonScope> JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.PPScopeState._jsonScopeStack = new Stack<JsonScope>() private
Definition at line 24 of file PPScopeState.cs.
Referenced by JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.PPScopeState.PopJsonType(), JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.PPScopeState.PushJsonArrayType(), and JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.PPScopeState.PushObjectContextOntoStack().
Property Documentation
IsTopTypeArray
bool JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.PPScopeState.IsTopTypeArray get
Definition at line 30 of file PPScopeState.cs.
ScopeDepth
int JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.PPScopeState.ScopeDepth get
Definition at line 41 of file PPScopeState.cs.
Referenced by JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.BuildContextIndents().
The documentation for this class was generated from the following file:
iglib/igbase/data/serialization/json/JsonPrettyPrinterInternals/PPScopeState.cs