Doc: IGLib with source files: IG.Num.M Class Reference
IG.Num.M Class Reference
Defines some mathematical functions to be used in derived and other classes.
Static Public Member Functions
static void Swap (ref double a, ref double b)
Swaps values of the two specified variables of type double.
static void Swap (ref int a, ref int b)
Swaps values of the two specified variables of type int.
static void Swap (ref string a, ref string b)
Swaps values of the two specified variables of type string.
static double abs (double a)
Absolute value.
static double sign (double a)
Returns a value indicating the sign of a number.
static double ceil (double a)
Returns the smallest integral value that is greater than or equal to the specified decimal number.
static double floor (double a)
Returns the largest integer less than or equal to the specified number.
static double trunc (double a)
Calculates the integral part of a specified number.
static double min (double a, double b)
Smallest of two numbers.
static double max (double a, double b)
Largest of two numbers.
static double min (double a, double b, double c)
Smallest of three numbers.
static double max (double a, double b, double c)
Largest of three numbers.
static double min (double a, double b, double c, double d)
Smallest of four numbers.
static double max (double a, double b, double c, double d)
Largest of four numbers.
static double min (double a, double b, double c, double d, double e)
Smallest of five numbers.
static double max (double a, double b, double c, double d, double e)
Largest of five numbers.
static double min (double a, double b, double c, double d, double e, double f)
Smallest of six numbers.
static double max (double a, double b, double c, double d, double e, double f)
Largest of six numbers.
static double min (params double[] numbers)
Minimal of the specified values.
static double max (params double[] numbers)
Maximal of the specified values.
static double sum (params double[] numbers)
Sum of the specified values.
static double prod (params double[] numbers)
Product of the specified values.
static double pow (double a, double b)
Returns a specified number raised to the specified power.
static double sqr (double a)
Returns the square of a specified number.
static double cube (double a)
Returns the square of a specified number.
static double pow2 (double x)
Square.
static double pow3 (double x)
3rd power.
static double pow4 (double x)
4th power.
static double pow5 (double x)
5th power.
static double pow6 (double x)
6th power.
static double sqrt (double a)
Returns the square root of a specified number.
static double root2 (double a)
Returns the square root of a specified number.
static double root3 (double a)
Returns the cubic root of a specified number.
static double rand ()
Returns a uniformly distributed random number greater than or equal to 0.0, and less or equal than 1.0.
static double rand (double min, double max)
Returns a uniformly distributed random number greater than or equal to min, and less or equal than max.
static double randgauss (double mean, double standardDeviation)
Returns a Gaussian distributed random number with the specified mean and standard deviation.
static double exp (double a)
Returns e raised to the specified power.
static double log (double a)
Returns the natural (base e) logarithm of a specified number.
static double ln (double a)
Returns the natural (base e) logarithm of a specified number.
static double log10 (double a)
Returns the base 10 logarithm of a specified number.
static double lg (double a)
Returns the base 10 logarithm of a specified number.
static double log2 (double a)
Returns the base 2 logarithm of a specified number.
static double log (double a, double logBase)
Returns the logarithm of a specified number in a specified base.
static double deg (double x)
Converts angle in radians to angle in degrees and returns it.
static double rad (double x)
Converts angle in degrees to angle in radians and returns it.
static double sin (double a)
Returns the sine of the specified angle.
static double cos (double a)
Returns the cosine of the specified angle.
static double tg (double a)
Returns the tangent of the specified angle.
static double ctg (double x)
Returns cotangent of the specified angle.
static double arccos (double a)
Returns the angle whose cosine is the specified number.
static double arcsin (double a)
Returns the angle whose sine is the specified number.
static double arctg (double a)
Returns the angle whose tangent is the specified number.
static double arcctg (double x)
Arc cotangent, inverse of 1/tan(x).
static double arctg2 (double a, double b)
Returns the angle whose tangent is the quotient of two specified numbers.
static double Sinh (double a)
Returns the hyperbolic sine of the specified angle.
static double sinh (double a)
Returns the hyperbolic sine of the specified angle.
static double sh (double a)
Returns the hyperbolic sine of the specified angle.
static double ch (double a)
Returns the hyperbolic cosine of the specified angle.
static double th (double a)
Returns the hyperbolic tangent of the specified angle.
static double cth (double x)
Hyperblic cotangent, 1/Math.Tanh.
static double arsh (double x)
Inverse hyperbolic sine.
static double arch (double x)
Inverse hyperbolic cosine.
static double arth (double x)
Inverse hyperbolic tangent.
static double arcth (double x)
Inverse hyperbolic cotangent.
static bool CheckFactorialsArray ()
Tests ehether the factoirals in the hard-coded array (factorials64) of factorials are correct; Throws ArgumentException if any of them is incorrect.
static void TestFactorials ()
Writes to the console all factorials that can be calculatet.
static void TestFactorials (int max)
Writes to the console the first n factorials.
static long fac (int factor)
Returns factorial of the specified number.
static long facCalculated (long n)
Returns factorial of the specified number - less efficient approac, but does not rely on hard coded array.
static long fallingPower (long n, long p)
Calculates and returns the falling power of the specified number.
static long binomial (long n, long k)
Returns binomial coefficient n over k .
static void TestBinomialCoefficients ()
Writes the first few binomial coefficients to the console.
static void TestBinomialCoefficients (int nMax)
Writes binomial coefficients up to the specified number to the console.
static double Sum (params double[] sampleElements)
Calculates and returns sum of its arguments (or elements of the specified double array).
static double Sum (IEnumerable< double > sample)
Calculates and returns sum of elemennts the specified sample.
static double Product (params double[] sampleElements)
Calculates and returns proudct of its arguments (or elements of the specified double array).
static double Product (IEnumerable< double > sample)
Calculates and returns product of ellements of the specified sample.
static double Mean (params double[] sampleElements)
Calculates and returns mean value of its arguments (or elements of the specified double array).
static double Mean (IEnumerable< double > sample)
Returns mean value of the specified sample.
static double Average (params double[] sampleElements)
The same as Mean(double[])
static double Average (IEnumerable< double > sample)
The same as Mean(IEnumerable<double>)
static double StandardDeviation (params double[] sampleElements)
Calculates and returns mean value of its arguments (or elements of the specified double array).
static double StandardDeviation (IEnumerable< double > sample)
Returns estimation of the standard deviation of a random value based on the specified sample.
Properties
static double e [get]
Natural logarithmic base.
static double pi [get]
Ratio of the circumference of a circle to its diameter.
static double zero [get]
Zero (value 0.0).
static double one [get]
One (value 1.0).
Static Private Attributes
static Int64[] factorials64
Array of all factorials that do not produce overflow.
static bool factorialsArrayChecked = false
Whether or not factorials array has been tested.
Detailed Description
Defines some mathematical functions to be used in derived and other classes.
* Standard mathematical functions and constants with short names are implemented, e.g. sin() instesd of Math.Sin().
** These functions are public and static such that they can be used out of the derived classes, too.
*** In particular, some script classes derive from this one, in order to use simple-named mathematical functions.
** Some functions are defined with several names, in order to reduce probability of errors in scripts.
Definition at line 74 of file UtilMath.cs.
Member Function Documentation
Swap() [1/3]
static void IG.Num.M.Swap (ref double a, ref double b) inline static
Swaps values of the two specified variables of type double.
Parameters
a First variable.
b Second variable.
Definition at line 104 of file UtilMath.cs.
References IG.Num.s.
Referenced by IG.Num.InputOutputElementDefinition.GetDistortedBounds().
Swap() [2/3]
static void IG.Num.M.Swap (ref int a, ref int b) inline static
Swaps values of the two specified variables of type int.
Parameters
a First variable.
b Second variable.
Definition at line 114 of file UtilMath.cs.
References IG.Num.s.
Swap() [3/3]
static void IG.Num.M.Swap (ref string a, ref string b) inline static
Swaps values of the two specified variables of type string.
Parameters
a First variable.
b Second variable.
Definition at line 124 of file UtilMath.cs.
References IG.Num.s.
abs()
static double IG.Num.M.abs (double a) inline static
Absolute value.
Definition at line 139 of file UtilMath.cs.
sign()
static double IG.Num.M.sign (double a) inline static
Returns a value indicating the sign of a number.
Definition at line 143 of file UtilMath.cs.
ceil()
static double IG.Num.M.ceil (double a) inline static
Returns the smallest integral value that is greater than or equal to the specified decimal number.
Definition at line 152 of file UtilMath.cs.
floor()
static double IG.Num.M.floor (double a) inline static
Returns the largest integer less than or equal to the specified number.
Definition at line 156 of file UtilMath.cs.
trunc()
static double IG.Num.M.trunc (double a) inline static
Calculates the integral part of a specified number.
Definition at line 160 of file UtilMath.cs.
min() [1/6]
static double IG.Num.M.min (double a, double b) inline static
Smallest of two numbers.
Definition at line 169 of file UtilMath.cs.
Referenced by IG.Num.M.rand(), and IG.Num.MExt.Rand().
max() [1/6]
static double IG.Num.M.max (double a, double b) inline static
Largest of two numbers.
Definition at line 172 of file UtilMath.cs.
Referenced by IG.Num.M.rand(), IG.Num.MExt.Rand(), and IG.Num.M.TestFactorials().
min() [2/6]
static double IG.Num.M.min (double a, double b, double c) inline static
Smallest of three numbers.
Definition at line 175 of file UtilMath.cs.
max() [2/6]
static double IG.Num.M.max (double a, double b, double c) inline static
Largest of three numbers.
Definition at line 182 of file UtilMath.cs.
min() [3/6]
static double IG.Num.M.min (double a, double b, double c, double d) inline static
Smallest of four numbers.
Definition at line 189 of file UtilMath.cs.
max() [3/6]
static double IG.Num.M.max (double a, double b, double c, double d) inline static
Largest of four numbers.
Definition at line 197 of file UtilMath.cs.
min() [4/6]
static double IG.Num.M.min (double a, double b, double c, double d, double e) inline static
Smallest of five numbers.
Definition at line 205 of file UtilMath.cs.
References IG.Num.M.e.
max() [4/6]
static double IG.Num.M.max (double a, double b, double c, double d, double e) inline static
Largest of five numbers.
Definition at line 214 of file UtilMath.cs.
References IG.Num.M.e.
min() [5/6]
static double IG.Num.M.min (double a, double b, double c, double d, double e, double f) inline static
Smallest of six numbers.
Definition at line 223 of file UtilMath.cs.
References IG.Num.M.e.
max() [5/6]
static double IG.Num.M.max (double a, double b, double c, double d, double e, double f) inline static
Largest of six numbers.
Definition at line 233 of file UtilMath.cs.
References IG.Num.M.e.
min() [6/6]
static double IG.Num.M.min (params double[] numbers) inline static
Minimal of the specified values.
Definition at line 243 of file UtilMath.cs.
max() [6/6]
static double IG.Num.M.max (params double[] numbers) inline static
Maximal of the specified values.
Definition at line 263 of file UtilMath.cs.
sum()
static double IG.Num.M.sum (params double[] numbers) inline static
Sum of the specified values.
Definition at line 288 of file UtilMath.cs.
prod()
static double IG.Num.M.prod (params double[] numbers) inline static
Product of the specified values.
Definition at line 307 of file UtilMath.cs.
pow()
static double IG.Num.M.pow (double a, double b) inline static
Returns a specified number raised to the specified power.
Definition at line 331 of file UtilMath.cs.
Referenced by IG.Num.ExampleMathClass.f(), IG.Num.ExampleMathClass.Nested.f(), IG.Num.Func3d2dExamples.KleinBottle.f1(), IG.Num.Func3d2dExamples.SnailShell1.f1(), IG.Num.Func3d2dExamples.SnailShell1Streched.f1(), IG.Num.Func3d2dExamples.KleinBottle.f2(), IG.Num.Func3d2dExamples.SnailShell1.f2(), IG.Num.Func3d2dExamples.SnailShell1Streched.f2(), IG.Num.Func3d2dExamples.SnailShell1.f3(), and IG.Script.ScritpScalarFunctionExample.Container.Function.ReferenceValue().
sqr()
static double IG.Num.M.sqr (double a) inline static
Returns the square of a specified number.
Definition at line 335 of file UtilMath.cs.
cube()
static double IG.Num.M.cube (double a) inline static
Returns the square of a specified number.
Definition at line 339 of file UtilMath.cs.
pow2()
static double IG.Num.M.pow2 (double x) inline static
Square.
Definition at line 343 of file UtilMath.cs.
Referenced by IG.Num.M.arch(), IG.Num.MExt.Arcosh(), IG.Num.M.arsh(), and IG.Num.MExt.Arsinh().
pow3()
static double IG.Num.M.pow3 (double x) inline static
3rd power.
Definition at line 346 of file UtilMath.cs.
pow4()
static double IG.Num.M.pow4 (double x) inline static
4th power.
Definition at line 349 of file UtilMath.cs.
pow5()
static double IG.Num.M.pow5 (double x) inline static
5th power.
Definition at line 352 of file UtilMath.cs.
pow6()
static double IG.Num.M.pow6 (double x) inline static
6th power.
Definition at line 355 of file UtilMath.cs.
sqrt()
static double IG.Num.M.sqrt (double a) inline static
Returns the square root of a specified number.
Definition at line 358 of file UtilMath.cs.
Referenced by IG.Num.Func3d2dExamples.HyperboloidParametric.f1(), and IG.Num.Func3d2dExamples.HyperboloidParametric.f2().
root2()
static double IG.Num.M.root2 (double a) inline static
Returns the square root of a specified number.
Definition at line 361 of file UtilMath.cs.
root3()
static double IG.Num.M.root3 (double a) inline static
Returns the cubic root of a specified number.
Definition at line 364 of file UtilMath.cs.
rand() [1/2]
static double IG.Num.M.rand () inline static
Returns a uniformly distributed random number greater than or equal to 0.0, and less or equal than 1.0.
Definition at line 373 of file UtilMath.cs.
References IG.Num.RandomGenerator.Global, and IG.Num.IRandomGenerator.NextDoubleInclusive().
rand() [2/2]
static double IG.Num.M.rand (double min, double max) inline static
Returns a uniformly distributed random number greater than or equal to min, and less or equal than max.
Definition at line 380 of file UtilMath.cs.
References IG.Num.RandomGenerator.Global, IG.Num.M.max(), IG.Num.M.min(), and IG.Num.IRandomGenerator.NextDoubleInclusive().
randgauss()
static double IG.Num.M.randgauss (double mean, double standardDeviation) inline static
Returns a Gaussian distributed random number with the specified mean and standard deviation.
Parameters
mean Mean value of the distribution.
standardDeviation Standard deviation of the distribution.
Definition at line 389 of file UtilMath.cs.
References IG.Num.RandomGaussian.Global, and IG.Num.RandomGaussian.NextGaussian().
exp()
static double IG.Num.M.exp (double a) inline static
Returns e raised to the specified power.
Definition at line 404 of file UtilMath.cs.
Referenced by IG.Num.Func3d2dExamples.SnailShell1Streched.f1(), IG.Num.Func3d2dExamples.SnailShell1Streched.f2(), and IG.Num.Func3d2dExamples.SnailShell1Streched.f3().
log() [1/2]
static double IG.Num.M.log (double a) inline static
Returns the natural (base e) logarithm of a specified number.
Definition at line 408 of file UtilMath.cs.
ln()
static double IG.Num.M.ln (double a) inline static
Returns the natural (base e) logarithm of a specified number.
Definition at line 412 of file UtilMath.cs.
log10()
static double IG.Num.M.log10 (double a) inline static
Returns the base 10 logarithm of a specified number.
Definition at line 416 of file UtilMath.cs.
lg()
static double IG.Num.M.lg (double a) inline static
Returns the base 10 logarithm of a specified number.
Definition at line 420 of file UtilMath.cs.
log2()
static double IG.Num.M.log2 (double a) inline static
Returns the base 2 logarithm of a specified number.
Definition at line 424 of file UtilMath.cs.
log() [2/2]
static double IG.Num.M.log (double a, double logBase) inline static
Returns the logarithm of a specified number in a specified base.
Parameters
a Number whose logarithm is returned.
logBase Base of the logarithm.
Definition at line 430 of file UtilMath.cs.
deg()
static double IG.Num.M.deg (double x) inline static
Converts angle in radians to angle in degrees and returns it.
Definition at line 439 of file UtilMath.cs.
rad()
static double IG.Num.M.rad (double x) inline static
Converts angle in degrees to angle in radians and returns it.
Definition at line 442 of file UtilMath.cs.
sin()
static double IG.Num.M.sin (double a) inline static
Returns the sine of the specified angle.
Definition at line 450 of file UtilMath.cs.
Referenced by IG.Num.ExampleMathClass.f(), IG.Num.ExampleMathClass.Nested.f(), IG.Num.Func3d2dExamples.HyperboloidParametricPlus.f1(), IG.Num.Func3d2dExamples.HyperboloidParametricMinus.f1(), IG.Num.Func3d2dExamples.TorusHorizontal.f1(), IG.Num.Func3d2dExamples.UmbilicTorus.f1(), IG.Num.Func3d2dExamples.KleinBottle.f1(), IG.Num.Func3d2dExamples.KleinBottle1.f1(), IG.Num.Func3d2dExamples.KleinBottle2.f1(), IG.Num.Func3d2dExamples.CylinderParametric.f2(), IG.Num.Func3d2dExamples.EllipsoidParametric.f2(), IG.Num.Func3d2dExamples.HyperboloidTwosheetedUpperParametric.f2(), IG.Num.Func3d2dExamples.HyperboloidTwosheetedLowerParametric.f2(), IG.Num.Func3d2dExamples.HyperboloidParametric.f2(), IG.Num.Func3d2dExamples.HyperboloidParametric2.f2(), IG.Num.Func3d2dExamples.HyperboloidParametricPlus.f2(), IG.Num.Func3d2dExamples.HyperboloidParametricMinus.f2(), IG.Num.Func3d2dExamples.Torus.f2(), IG.Num.Func3d2dExamples.TorusVertical.f2(), IG.Num.Func3d2dExamples.MobiusStrip.f2(), IG.Num.Func3d2dExamples.KleinBottle.f2(), IG.Num.Func3d2dExamples.KleinBottle1.f2(), IG.Num.Func3d2dExamples.KleinBottle2.f2(), IG.Num.Func3d2dExamples.SnailConicSpiral_ToCheck.f2(), IG.Num.Func3d2dExamples.SnailShell1.f2(), IG.Num.Func3d2dExamples.SnailShell1Streched.f2(), IG.Num.Func3d2dExamples.EllipsoidParametric.f3(), IG.Num.Func3d2dExamples.Torus.f3(), IG.Num.Func3d2dExamples.TorusHorizontal.f3(), IG.Num.Func3d2dExamples.TorusVertical.f3(), IG.Num.Func3d2dExamples.MobiusStrip.f3(), IG.Num.Func3d2dExamples.UmbilicTorus.f3(), IG.Num.Func3d2dExamples.KleinBottle.f3(), IG.Num.Func3d2dExamples.KleinBottle1.f3(), IG.Num.Func3d2dExamples.KleinBottle2.f3(), IG.Num.Func3d2dExamples.SnailConicSpiral_ToCheck.f3(), IG.Num.Func3d2dExamples.SnailShell1.f3(), IG.Num.Func3d2dExamples.SnailShell1Streched.f3(), and IG.Script.ScritpRealFunctionExample.Container.Function.RefSecondDerivative().
cos()
static double IG.Num.M.cos (double a) inline static
Returns the cosine of the specified angle.
Definition at line 454 of file UtilMath.cs.
Referenced by IG.Num.Func3d2dExamples.CylinderParametric.f1(), IG.Num.Func3d2dExamples.EllipsoidParametric.f1(), IG.Num.Func3d2dExamples.HyperboloidTwosheetedUpperParametric.f1(), IG.Num.Func3d2dExamples.HyperboloidTwosheetedLowerParametric.f1(), IG.Num.Func3d2dExamples.HyperboloidParametric.f1(), IG.Num.Func3d2dExamples.HyperboloidParametric2.f1(), IG.Num.Func3d2dExamples.HyperboloidParametricPlus.f1(), IG.Num.Func3d2dExamples.HyperboloidParametricMinus.f1(), IG.Num.Func3d2dExamples.Torus.f1(), IG.Num.Func3d2dExamples.TorusHorizontal.f1(), IG.Num.Func3d2dExamples.TorusVertical.f1(), IG.Num.Func3d2dExamples.MobiusStrip.f1(), IG.Num.Func3d2dExamples.UmbilicTorus.f1(), IG.Num.Func3d2dExamples.KleinBottle.f1(), IG.Num.Func3d2dExamples.KleinBottle1.f1(), IG.Num.Func3d2dExamples.KleinBottle2.f1(), IG.Num.Func3d2dExamples.SnailConicSpiral_ToCheck.f1(), IG.Num.Func3d2dExamples.SnailShell1.f1(), IG.Num.Func3d2dExamples.SnailShell1Streched.f1(), IG.Num.Func3d2dExamples.EllipsoidParametric.f2(), IG.Num.Func3d2dExamples.HyperboloidParametricPlus.f2(), IG.Num.Func3d2dExamples.HyperboloidParametricMinus.f2(), IG.Num.Func3d2dExamples.Torus.f2(), IG.Num.Func3d2dExamples.TorusHorizontal.f2(), IG.Num.Func3d2dExamples.MobiusStrip.f2(), IG.Num.Func3d2dExamples.UmbilicTorus.f2(), IG.Num.Func3d2dExamples.KleinBottle.f2(), IG.Num.Func3d2dExamples.KleinBottle1.f2(), IG.Num.Func3d2dExamples.KleinBottle2.f2(), IG.Num.Func3d2dExamples.SnailConicSpiral_ToCheck.f2(), IG.Num.Func3d2dExamples.SnailShell1.f2(), IG.Num.Func3d2dExamples.SnailShell1Streched.f2(), IG.Num.Func3d2dExamples.TorusVertical.f3(), IG.Num.Func3d2dExamples.KleinBottle.f3(), IG.Num.Func3d2dExamples.KleinBottle1.f3(), IG.Num.Func3d2dExamples.KleinBottle2.f3(), and IG.Script.ScritpRealFunctionExample.Container.Function.RefDerivative().
tg()
static double IG.Num.M.tg (double a) inline static
Returns the tangent of the specified angle.
Definition at line 458 of file UtilMath.cs.
ctg()
static double IG.Num.M.ctg (double x) inline static
Returns cotangent of the specified angle.
Definition at line 462 of file UtilMath.cs.
arccos()
static double IG.Num.M.arccos (double a) inline static
Returns the angle whose cosine is the specified number.
Definition at line 470 of file UtilMath.cs.
arcsin()
static double IG.Num.M.arcsin (double a) inline static
Returns the angle whose sine is the specified number.
Definition at line 473 of file UtilMath.cs.
arctg()
static double IG.Num.M.arctg (double a) inline static
Returns the angle whose tangent is the specified number.
Definition at line 477 of file UtilMath.cs.
arcctg()
static double IG.Num.M.arcctg (double x) inline static
Arc cotangent, inverse of 1/tan(x).
Definition at line 481 of file UtilMath.cs.
arctg2()
static double IG.Num.M.arctg2 (double a, double b) inline static
Returns the angle whose tangent is the quotient of two specified numbers.
Definition at line 484 of file UtilMath.cs.
Sinh()
static double IG.Num.M.Sinh (double a) inline static
Returns the hyperbolic sine of the specified angle.
Definition at line 493 of file UtilMath.cs.
sinh()
static double IG.Num.M.sinh (double a) inline static
Returns the hyperbolic sine of the specified angle.
Definition at line 497 of file UtilMath.cs.
Referenced by IG.Num.Func3d2dExamples.HyperboloidTwosheetedUpperParametric.f1(), IG.Num.Func3d2dExamples.HyperboloidTwosheetedLowerParametric.f1(), IG.Num.Func3d2dExamples.HyperboloidTwosheetedUpperParametric.f2(), and IG.Num.Func3d2dExamples.HyperboloidTwosheetedLowerParametric.f2().
sh()
static double IG.Num.M.sh (double a) inline static
Returns the hyperbolic sine of the specified angle.
Definition at line 501 of file UtilMath.cs.
Referenced by IG.Num.Func3d2dExamples.HyperboloidParametric2.f3().
ch()
static double IG.Num.M.ch (double a) inline static
Returns the hyperbolic cosine of the specified angle.
Definition at line 505 of file UtilMath.cs.
Referenced by IG.Num.Func3d2dExamples.HyperboloidParametric2.f1(), IG.Num.Func3d2dExamples.HyperboloidParametric2.f2(), IG.Num.Func3d2dExamples.HyperboloidTwosheetedUpperParametric.f3(), and IG.Num.Func3d2dExamples.HyperboloidTwosheetedLowerParametric.f3().
th()
static double IG.Num.M.th (double a) inline static
Returns the hyperbolic tangent of the specified angle.
Definition at line 509 of file UtilMath.cs.
cth()
static double IG.Num.M.cth (double x) inline static
Hyperblic cotangent, 1/Math.Tanh.
Definition at line 513 of file UtilMath.cs.
arsh()
static double IG.Num.M.arsh (double x) inline static
Inverse hyperbolic sine.
Definition at line 521 of file UtilMath.cs.
References IG.Num.M.pow2().
Referenced by IG.Num.Func.Cubic.Zeros().
arch()
static double IG.Num.M.arch (double x) inline static
Inverse hyperbolic cosine.
Definition at line 524 of file UtilMath.cs.
References IG.Num.M.pow2().
Referenced by IG.Num.Func.Cubic.Zeros().
arth()
static double IG.Num.M.arth (double x) inline static
Inverse hyperbolic tangent.
Definition at line 527 of file UtilMath.cs.
arcth()
static double IG.Num.M.arcth (double x) inline static
Inverse hyperbolic cotangent.
Definition at line 530 of file UtilMath.cs.
CheckFactorialsArray()
static bool IG.Num.M.CheckFactorialsArray () inline static
Tests ehether the factoirals in the hard-coded array (factorials64) of factorials are correct; Throws ArgumentException if any of them is incorrect.
Returns
true if test is successful.
Definition at line 553 of file UtilMath.cs.
References IG.Num.M.facCalculated(), and IG.Num.M.factorials64.
Referenced by IG.Num.M.fac().
TestFactorials() [1/2]
static void IG.Num.M.TestFactorials () inline static
Writes to the console all factorials that can be calculatet.
Definition at line 566 of file UtilMath.cs.
TestFactorials() [2/2]
static void IG.Num.M.TestFactorials (int max) inline static
Writes to the console the first n factorials.
Parameters
max Largest number whose factorial will be calculated.
Definition at line 574 of file UtilMath.cs.
References IG.Num.M.fac(), IG.Num.M.facCalculated(), IG.Num.M.factorials64, and IG.Num.M.max().
fac()
static long IG.Num.M.fac (int factor) inline static
Returns factorial of the specified number.
Definition at line 592 of file UtilMath.cs.
References IG.Num.M.CheckFactorialsArray(), IG.Num.M.factorials64, and IG.Num.M.factorialsArrayChecked.
Referenced by IG.Num.MExt.Factorial(), IG.Num.MExt.factorial(), and IG.Num.M.TestFactorials().
facCalculated()
static long IG.Num.M.facCalculated (long n) inline static
Returns factorial of the specified number - less efficient approac, but does not rely on hard coded array.
Definition at line 601 of file UtilMath.cs.
Referenced by IG.Num.M.CheckFactorialsArray(), and IG.Num.M.TestFactorials().
fallingPower()
static long IG.Num.M.fallingPower (long n, long p) inline static
Calculates and returns the falling power of the specified number.
Parameters
n
p
See http://en.wikipedia.org/wiki/Falling_power
Definition at line 614 of file UtilMath.cs.
binomial()
static long IG.Num.M.binomial (long n, long k) inline static
Returns binomial coefficient n over k .
Parameters
n
k
Definition at line 624 of file UtilMath.cs.
Referenced by IG.Num.MExt.BinomialCoefficient(), and IG.Num.M.TestBinomialCoefficients().
TestBinomialCoefficients() [1/2]
static void IG.Num.M.TestBinomialCoefficients () inline static
Writes the first few binomial coefficients to the console.
Definition at line 640 of file UtilMath.cs.
TestBinomialCoefficients() [2/2]
static void IG.Num.M.TestBinomialCoefficients (int nMax) inline static
Writes binomial coefficients up to the specified number to the console.
Parameters
nMax Maximal enumerator until which coefficients are written.
Definition at line 647 of file UtilMath.cs.
References IG.Num.M.binomial().
Sum() [1/2]
static double IG.Num.M.Sum (params double[] sampleElements) inline static
Calculates and returns sum of its arguments (or elements of the specified double array).
Parameters
sampleElements Either array of double numbers or multiple number parameters whose mean value is calculated.
Definition at line 673 of file UtilMath.cs.
Sum() [2/2]
static double IG.Num.M.Sum (IEnumerable< double > sample) inline static
Calculates and returns sum of elemennts the specified sample.
Parameters
sample Collection containing observations within the sample.
Definition at line 681 of file UtilMath.cs.
Product() [1/2]
static double IG.Num.M.Product (params double[] sampleElements) inline static
Calculates and returns proudct of its arguments (or elements of the specified double array).
Parameters
sampleElements Either array of double numbers or multiple number parameters whose mean value is calculated.
Definition at line 698 of file UtilMath.cs.
Product() [2/2]
static double IG.Num.M.Product (IEnumerable< double > sample) inline static
Calculates and returns product of ellements of the specified sample.
Parameters
sample Collection containing observations within the sample.
Definition at line 706 of file UtilMath.cs.
Mean() [1/2]
static double IG.Num.M.Mean (params double[] sampleElements) inline static
Calculates and returns mean value of its arguments (or elements of the specified double array).
Parameters
sampleElements Either array of double numbers or multiple number parameters whose mean value is calculated.
Exceptions
ArgumentException When number of elements is 0 or null argument is specified.
Definition at line 724 of file UtilMath.cs.
Referenced by IG.Num.M.Average(), and IG.Num.M.StandardDeviation().
Mean() [2/2]
static double IG.Num.M.Mean (IEnumerable< double > sample) inline static
Returns mean value of the specified sample.
Parameters
sample Collection containing observations within the sample.
Exceptions
ArgumentException When number of elements is 0 or null argument is specified.
Definition at line 733 of file UtilMath.cs.
Average() [1/2]
static double IG.Num.M.Average (params double[] sampleElements) inline static
The same as Mean(double[])
Mean(double[])
Exceptions
ArgumentException When number of elements is 0 or null argument is specified.
Definition at line 755 of file UtilMath.cs.
References IG.Num.M.Mean().
Average() [2/2]
static double IG.Num.M.Average (IEnumerable< double > sample) inline static
The same as Mean(IEnumerable<double>)
See also
Mean(IEnumerable<double>)
Definition at line 762 of file UtilMath.cs.
References IG.Num.M.Mean().
StandardDeviation() [1/2]
static double IG.Num.M.StandardDeviation (params double[] sampleElements) inline static
Calculates and returns mean value of its arguments (or elements of the specified double array).
Parameters
sampleElements Either array of double numbers or multiple number parameters whose standard deviation estimate is calculated.
Exceptions
ArgumentException When number of elements or parameters is less than 2 or null argumennt is specified.
Definition at line 771 of file UtilMath.cs.
StandardDeviation() [2/2]
static double IG.Num.M.StandardDeviation (IEnumerable< double > sample) inline static
Returns estimation of the standard deviation of a random value based on the specified sample.
Parameters
sample Collection containing all observations of the sample.
Exceptions
ArgumentException When number of elements is less than 2 or null argumennt is specified.
Definition at line 780 of file UtilMath.cs.
References IG.Num.M.Mean().
Member Data Documentation
factorials64
Int64 [] IG.Num.M.factorials64 static private
Initial value:
= { 1, 1, 2, 6, 24, 120, 720, 5040, 40320,
                                       362880, 3628800, 39916800, 479001600, 6227020800, 87178291200,
                                       1307674368000, 20922789888000, 355687428096000, 6402373705728000,
                                       121645100408832000, 2432902008176640000 }
Array of all factorials that do not produce overflow.
Definition at line 541 of file UtilMath.cs.
Referenced by IG.Num.M.CheckFactorialsArray(), IG.Num.M.fac(), and IG.Num.M.TestFactorials().
factorialsArrayChecked
bool IG.Num.M.factorialsArrayChecked = false static private
Whether or not factorials array has been tested.
Definition at line 548 of file UtilMath.cs.
Referenced by IG.Num.M.fac().
Property Documentation
e
double IG.Num.M.e static get
Natural logarithmic base.
Definition at line 82 of file UtilMath.cs.
Referenced by IG.Num.ExampleMathClass.f(), IG.Num.ExampleMathClass.Nested.f(), IG.Num.M.max(), IG.Num.MExt.Max(), IG.Num.M.min(), and IG.Num.MExt.Min().
pi
double IG.Num.M.pi static get
Ratio of the circumference of a circle to its diameter.
Definition at line 86 of file UtilMath.cs.
Referenced by IG.Num.Func3d2dExamples.CylinderParametric.CylinderParametric(), IG.Num.Func3d2dExamples.EllipsoidParametric.EllipsoidParametric(), IG.Num.Func3d2dExamples.SnailConicSpiral_ToCheck.f1(), IG.Num.Func3d2dExamples.SnailShell1Streched.f1(), IG.Num.Func3d2dExamples.SnailConicSpiral_ToCheck.f2(), IG.Num.Func3d2dExamples.SnailShell1Streched.f2(), IG.Num.Func3d2dExamples.SnailConicSpiral_ToCheck.f3(), IG.Num.Func3d2dExamples.SnailShell1Streched.f3(), IG.Num.Func3d2dExamples.HyperboloidParametric.HyperboloidParametric(), IG.Num.Func3d2dExamples.HyperboloidParametric2.HyperboloidParametric2(), IG.Num.Func3d2dExamples.HyperboloidParametricMinus.HyperboloidParametricMinus(), IG.Num.Func3d2dExamples.HyperboloidParametricPlus.HyperboloidParametricPlus(), IG.Num.Func3d2dExamples.HyperboloidTwosheetedLowerParametric.HyperboloidTwosheetedLowerParametric(), IG.Num.Func3d2dExamples.HyperboloidTwosheetedUpperParametric.HyperboloidTwosheetedUpperParametric(), IG.Num.Func3d2dExamples.KleinBottle.KleinBottle(), IG.Num.Func3d2dExamples.KleinBottle1.KleinBottle1(), IG.Num.Func3d2dExamples.KleinBottle2.KleinBottle2(), IG.Num.Func3d2dExamples.MobiusStrip.MobiusStrip(), IG.Num.Func3d2dExamples.SnailConicSpiral_ToCheck.SnailConicSpiral_ToCheck(), IG.Num.Func3d2dExamples.SnailShell1.SnailShell1(), IG.Num.Func3d2dExamples.SnailShell1Streched.SnailShell1Streched(), IG.Num.Func3d2dExamples.Torus.Torus(), IG.Num.Func3d2dExamples.TorusHorizontal.TorusHorizontal(), and IG.Num.Func3d2dExamples.UmbilicTorus.UmbilicTorus().
zero
double IG.Num.M.zero static get
Zero (value 0.0).
Definition at line 90 of file UtilMath.cs.
Referenced by IG.Num.ExampleMathClass.f(), IG.Num.ExampleMathClass.Nested.f(), IG.Script.ScritpRealFunctionExample.Container.Function.RefDerivative(), IG.Script.ScritpScalarFunctionExample.Container.Function.ReferenceGradientPlain(), IG.Script.ScritpScalarFunctionExample.Container.Function.ReferenceHessianPlain(), IG.Script.ScritpScalarFunctionExample.Container.Function.ReferenceValue(), IG.Script.ScritpRealFunctionExample.Container.Function.RefSecondDerivative(), and IG.Script.ScritpRealFunctionExample.Container.Function.RefValue().
one
double IG.Num.M.one static get
One (value 1.0).
Definition at line 94 of file UtilMath.cs.
The documentation for this class was generated from the following file:
IGLibCore/src/IGLib.Core/MathUtils/UtilMath.cs