Doc: IGLib with source files: IGLib.Gr3D.ConicalCurve3DParameterizationFromPolarWithBounds Class Reference
IGLib.Gr3D.ConicalCurve3DParameterizationFromPolarWithBounds Class Reference abstract
Cartesion parameterization of a curve in 3D. Beside the Curve and (optional) CurveDerivative, it also contains bounds on parameter, StartParameter and EndParameter as part of the class.
Public Member Functions
ConicalCurve3DParameterizationFromPolarWithBounds (double alpha, bool isDefinedForNegativePhi=false)
abstract double CurvePolar (double t)
Planar curve (in XY plane) in polar form (of the form r = r(φ)).
abstract double CurveDerivativePolar (double t)
Derivative of the planar curve (in XY plane) of form r = r(φ) with respect to polar angle.
virtual vec3 Curve (double t)
3D vector function of scalar argument, which represents a parameterization of the curve in 3D Euclidean space. Properties StartParameter and EndParameter determine the typical starting and end parameter values for use cases like plotting the curve.
virtual vec3 CurveDerivative (double t)
3D vector function of scalar argument, which represents the derivative of Curve with respect to parameter. In each point on curve (for each parameter value), this defines a tangent on the curve (or speed vector), with its size representing the velocity.You can use Derivative Calculator
Public Attributes
virtual bool HasDerivative => HasDerivativePolar
Properties
double alpha [get]
Slope of the cone around which the conical curve is wound (tangent of the angle between the slope of the conee and the XY plane).
bool IsNegativePhiOnMirrorCone [get]
If true then the curve for negative azimuth angles φ extends to wrap arround the mirror cone of the original cone. This is true e.g. for Archimedean and Fermat's spirals, but not for the logarithmic or hypervolic spirals as the base curve.
abstract bool HasDerivativePolar [get]
abstract double StartParameter [get]
abstract double EndParameter [get]
Properties inherited from IGLib.Gr3D.ICurve2DPolarParameterization
bool HasDerivativePolar [get]
Whether the derivative CurveDerivativePolar(double) is defined or not. If false then CurveDerivativePolar(double) cannot be used.
double StartParameter [get]
Typical starting value of the parameter φ of the parametric curve that represents the curve. Interval from StartParameter to EndParameter should produce a meaningful / representative curve section.
double EndParameter [get]
Typical end value of the parameter φ of the parametric curve that represents the curve. Interval from StartParameter to EndParameter should produce a meaningful / representative curve section.
Properties inherited from IGLib.Gr3D.ICurve3DParameterizationWithBounds
bool HasDerivative [get]
Whether derivative is defined or not. If false then CurveDerivative(double) cannot be used to calculate tangents on the curve.
double StartParameter [get]
Typical starting value of the parameter of the parametric curve that represents the curve. Interval from StartParameter to EndParameter should, for mathematical knots, produce a closed curve.
double EndParameter [get]
Typical end value of the parameter of the parametric curve that represents the curve. Interval from StartParameter to EndParameter should, for mathematical knots, produce a closed curve.
Detailed Description
Cartesion parameterization of a curve in 3D. Beside the Curve and (optional) CurveDerivative, it also contains bounds on parameter, StartParameter and EndParameter as part of the class.
StartParameter and EndParameter usually denote bounds on curve parameter that are used by default when the curve is tabulated, plotted, for meshes or for numerical calculations (i.e. lengths or urfaces or volumes where the curve is involved). Sometimes, these properties can also represent the range of parameter values for which the curve is defined, though rarely. More often, they represent some characteristic or natural range for the curve in question, and sometimes theey are not used at all (the convention is to set both to 0 in such cases). For mathematical knots (slosed ones), these properties are usually set to such values that the represented curves exactly closes eginning with its end when parameter runs from StartParameter and EndParameter.
Definition at line 21 of file ConicalCurve3DParameterizationFromPolarWithBounds.cs.
Constructor & Destructor Documentation
ConicalCurve3DParameterizationFromPolarWithBounds()
IGLib.Gr3D.ConicalCurve3DParameterizationFromPolarWithBounds.ConicalCurve3DParameterizationFromPolarWithBounds (double alpha, bool isDefinedForNegativePhi = false) inline
Definition at line 25 of file ConicalCurve3DParameterizationFromPolarWithBounds.cs.
References IGLib.Gr3D.ConicalCurve3DParameterizationFromPolarWithBounds.alpha, and IGLib.Gr3D.ConicalCurve3DParameterizationFromPolarWithBounds.IsNegativePhiOnMirrorCone.
Member Function Documentation
CurvePolar()
abstract double IGLib.Gr3D.ConicalCurve3DParameterizationFromPolarWithBounds.CurvePolar (double t) pure virtual
Planar curve (in XY plane) in polar form (of the form r = r(φ)).
Implements IGLib.Gr3D.ICurve2DPolarParameterization.
Implemented in IGLib.Gr3D.ConicalSpiralLogarithmic3D, IGLib.Gr3D.ConicalSpiralFermats3D, IGLib.Gr3D.ConicalSpiralHyperbolic3D, and IGLib.Gr3D.ConicalSpiralArchimedean3D.
Referenced by IGLib.Gr3D.ConicalCurve3DParameterizationFromPolarWithBounds.Curve(), and IGLib.Gr3D.ConicalCurve3DParameterizationFromPolarWithBounds.CurveDerivative().
CurveDerivativePolar()
abstract double IGLib.Gr3D.ConicalCurve3DParameterizationFromPolarWithBounds.CurveDerivativePolar (double t) pure virtual
Derivative of the planar curve (in XY plane) of form r = r(φ) with respect to polar angle.
Implements IGLib.Gr3D.ICurve2DPolarParameterization.
Implemented in IGLib.Gr3D.ConicalSpiralFermats3D, IGLib.Gr3D.ConicalSpiralLogarithmic3D, IGLib.Gr3D.ConicalSpiralHyperbolic3D, and IGLib.Gr3D.ConicalSpiralArchimedean3D.
Referenced by IGLib.Gr3D.ConicalCurve3DParameterizationFromPolarWithBounds.CurveDerivative().
Curve()
virtual vec3 IGLib.Gr3D.ConicalCurve3DParameterizationFromPolarWithBounds.Curve (double t) inline virtual
3D vector function of scalar argument, which represents a parameterization of the curve in 3D Euclidean space. Properties StartParameter and EndParameter determine the typical starting and end parameter values for use cases like plotting the curve.
Implements IGLib.Gr3D.ICurve3DParameterizationWithBounds.
Definition at line 63 of file ConicalCurve3DParameterizationFromPolarWithBounds.cs.
References IGLib.Gr3D.ConicalCurve3DParameterizationFromPolarWithBounds.alpha, IGLib.Gr3D.ConicalCurve3DParameterizationFromPolarWithBounds.CurvePolar(), IGLib.Gr3D.ConicalCurve3DParameterizationFromPolarWithBounds.IsNegativePhiOnMirrorCone, IG.Num.vec3.x, IG.Num.vec3.y, and IG.Num.vec3.z.
CurveDerivative()
virtual vec3 IGLib.Gr3D.ConicalCurve3DParameterizationFromPolarWithBounds.CurveDerivative (double t) inline virtual
3D vector function of scalar argument, which represents the derivative of Curve with respect to parameter. In each point on curve (for each parameter value), this defines a tangent on the curve (or speed vector), with its size representing the velocity.You can use Derivative Calculator
Implements IGLib.Gr3D.ICurve3DParameterizationWithBounds.
Definition at line 82 of file ConicalCurve3DParameterizationFromPolarWithBounds.cs.
References IGLib.Gr3D.ConicalCurve3DParameterizationFromPolarWithBounds.alpha, IGLib.Gr3D.ConicalCurve3DParameterizationFromPolarWithBounds.CurveDerivativePolar(), IGLib.Gr3D.ConicalCurve3DParameterizationFromPolarWithBounds.CurvePolar(), and IGLib.Gr3D.ConicalCurve3DParameterizationFromPolarWithBounds.HasDerivative.
Member Data Documentation
HasDerivative
virtual bool IGLib.Gr3D.ConicalCurve3DParameterizationFromPolarWithBounds.HasDerivative => HasDerivativePolar
Definition at line 100 of file ConicalCurve3DParameterizationFromPolarWithBounds.cs.
Referenced by IGLib.Gr3D.ConicalCurve3DParameterizationFromPolarWithBounds.CurveDerivative().
Property Documentation
alpha
double IGLib.Gr3D.ConicalCurve3DParameterizationFromPolarWithBounds.alpha get
Slope of the cone around which the conical curve is wound (tangent of the angle between the slope of the conee and the XY plane).
Definition at line 33 of file ConicalCurve3DParameterizationFromPolarWithBounds.cs.
Referenced by IGLib.Gr3D.ConicalCurve3DParameterizationFromPolarWithBounds.ConicalCurve3DParameterizationFromPolarWithBounds(), IGLib.Gr3D.ConicalCurve3DParameterizationFromPolarWithBounds.Curve(), and IGLib.Gr3D.ConicalCurve3DParameterizationFromPolarWithBounds.CurveDerivative().
IsNegativePhiOnMirrorCone
bool IGLib.Gr3D.ConicalCurve3DParameterizationFromPolarWithBounds.IsNegativePhiOnMirrorCone get
If true then the curve for negative azimuth angles φ extends to wrap arround the mirror cone of the original cone. This is true e.g. for Archimedean and Fermat's spirals, but not for the logarithmic or hypervolic spirals as the base curve.
Definition at line 38 of file ConicalCurve3DParameterizationFromPolarWithBounds.cs.
Referenced by IGLib.Gr3D.ConicalCurve3DParameterizationFromPolarWithBounds.ConicalCurve3DParameterizationFromPolarWithBounds(), and IGLib.Gr3D.ConicalCurve3DParameterizationFromPolarWithBounds.Curve().
HasDerivativePolar
abstract bool IGLib.Gr3D.ConicalCurve3DParameterizationFromPolarWithBounds.HasDerivativePolar get
Definition at line 49 of file ConicalCurve3DParameterizationFromPolarWithBounds.cs.
StartParameter
abstract double IGLib.Gr3D.ConicalCurve3DParameterizationFromPolarWithBounds.StartParameter get
Definition at line 52 of file ConicalCurve3DParameterizationFromPolarWithBounds.cs.
EndParameter
abstract double IGLib.Gr3D.ConicalCurve3DParameterizationFromPolarWithBounds.EndParameter get
Definition at line 55 of file ConicalCurve3DParameterizationFromPolarWithBounds.cs.
The documentation for this class was generated from the following file:
IGLibGraphics3D/src/IGLib.Graphics3D/Graphics3D/MathObjects/CurvesAndKnots/ConicalCurve3DParameterizationFromPolarWithBounds.cs