Doc: IGLib with source files: IG.Lib.StringTable Class Reference
IG.Lib.StringTable Class Reference
2D tables of data represented by strings. Maps to CSV files.
Public Member Functions
StringTable (bool readOnly)
Constructs a new string table, a data structure compatible with CSV file format.
StringTable ()
Constructs a new string table, a data structure compatible with CSV file format.
void SetElement (int rowNumber, int columnNumber, string element)
Sets element at the specified position to the specified value.
void SetElement< ElementType > (int rowNumber, int columnNumber, ElementType elementValue)
Sets element at the specified position to the string representation of the specified value.
ElementType GetElement< ElementType > (int rowNumber, int columnNumber)
Returns the element of the specified type at the specified position.
bool TryGetElement< ElementType > (int rowNumber, int columnNumber, ref ElementType elementValue)
Tries to obtain a value of the specified type at the specified position, and returns a flag indicating whether parsing the value from a string was successful (and the element existed).
bool IsDefined< ElementType > (int rowNumber, int columnNumber)
Returns a flag indicating whether the specified position contains a valid string representation of a element of the specified type.
bool IsDefined (int rowNumber, int columnNumber)
Returns a flag telling whether the specified element is defined (it exists in the data table) or not.
bool IsNotNullOrEmpty (int rowNumber, int columnNumber)
Returns a flag telling whether the specified element is defined (it exists in the data table) and is at the same time not null or empty string.
string GetElementOrNull (int rowNumber, int columnNumber, out bool isDefined)
Returns the specified element on the data table or null if that element is not defined, and notifies the caller through isDefined whether the element is defined or not.
string GetElementOrNull (int rowNumber, int columnNumber)
Returns the specified element on the data table or null if that element is not defined.
int FirstNonemptyRow (int startRow)
Returns index of the first non-empty row from the specified row on (inclusively), or -1 if there is no such row.
int FirstNonemptyRow ()
Returns index of the first non-empty row of the table, or -1 if there is no such row.
int FirstNonemptyColumn (int rowNum, int startColumn)
Returns number of the first non-empty cell in the specified row, from the specified starting column on (inclusively), or -1 if there is no suuch column.
int FirstNonemptyColumn (int rowNum)
Returns number of the first non-empty cell in the specified row.
void Clear ()
Clears the data table.
void AddRow ()
Adds a new row at the end of the data table.
void AddRow (params string[] elements)
Adds a new row at the end of the data table.
void AddRow< ElementType > (params ElementType[] elements)
Adds (appends) a new row with the specified elements at the end of the table.
void AddElement (int rowNum, string value)
Adds a new element at the end of the specified row of te data table.
void AddElement (string value)
Adds (appends) the speecified element at the end of the table, i.e. at the end of the last row.
void AddElement< ElementType > (int rowNum, ElementType value)
Adds string representation of a new element of the specified type at the end of the specified row of te data table.
void AddElement< ElementType > (ElementType value)
Adds (appends) string representatin of the speecified element at the end of the table, i.e. at the end of the last row.
void AddElements (int rowNum, params string[] values)
Adds the specified elements at the end of the specified row of te data table.
void AddElements< ElementType > (int rowNum, params ElementType[] values)
Adds string representations of the specified elements of the specified type at the end of the specified row of te data table.
void AddElements (params string[] values)
Adds (appends) the specified elements at the end of the table, i.e. at the end of the last row.
void AddElements< ElementType > (params ElementType[] values)
Adds (appends) string representations of the specified elements of the specified type at the end of the table, i.e. at the end of the last row.
void SetNumRows (int numRows)
Change the number of rows in the data table to the specified number.
void SetNumColumns (int rowNum, int numColumns)
Changes the number of columns of the specified row to the specified number.
void ClearRow (int rowNum)
Clears the specified row in the data table.
int NumColumns (int rowNum)
Returns the number of elements (columns) of the specified row.
bool IsInt (int rowNumber, int columnNumber)
Returns a flag specified whether the specified element of the data table exists and represents an integer.
int GetInt (int rowNumber, int columnNumber)
Returns an integer value of the element at the specified position of the data table, if it is defined, or throws an exception.
bool TryGetInt (int rowNumber, int columnNumber, out int value)
Safely gets the integer value at the specified position of the data table, if it is defined, and notifies the caller whether it is defined.
void GetIntSafe (int rowNumber, int columnNumber, out int value, out bool isElementDefined, out bool isElementNotNullOrEmpty, out bool isInt)
Safely gets the integer value at the specified position of the data table, if it is defined, and notifies the caller on the status.
bool IsDouble (int rowNumber, int columnNumber)
Returns a flag specified whether the specified element of the data table exists and represents a number (of type double).
double GetDouble (int rowNumber, int columnNumber)
Returns a double value of the element at the specified position of the data table, if such element is defined and represents a number, or throws an exception otherwise.
bool TryGetDouble (int rowNumber, int columnNumber, out double value)
Safely gets the double value at the specified position of the data table, if it is defined, and notifies the caller whether it is defined.
void GetDoubleSafe (int rowNumber, int columnNumber, out double value, out bool isElementDefined, out bool isElementNotNullOrEmpty, out bool isDouble)
Safely gets the numerical value (of type double) at the specified position of the data table, if it is defined, and notifies the caller about the status.
void LoadCsv (string filePath, string separator)
Loads the specified CSV file. Reads contents of the file into the data table of the current object.
void LoadCsv (string filePath)
Loads the specified CSV file. Reads contents of the file into the data table of the current object.
override string ToString ()
Converts the current string table to a string in CSV form and returns the string.
void SaveCsv (string filePath, string separator, bool append)
Saves the data of the current object to the specified CSV file.
void SaveCsv (string filePath, string separator)
Saves the data of the current object into a CSV file. If the file already exists then its contents are overwritten.
void SaveCsv (string filePath, bool append)
Saves the data of the current object into a CSV file. Constant UtilCsv.DefaultCsvSeparator is assumed to be a separator for the CSV format.
void SaveCsv (string filePath)
Saves the data of the current object values into a CSV file. If the file already exists then its contents are overwritten. Constant UtilCsv.DefaultCsvSeparator is assumed to be a separator for the CSV format.
Static Public Member Functions
static void ExampleWriteCsv (string filePath)
Creates a simple string table and saves it to a CSV file.
Static Public Attributes
static int DefaultOutputLevel = 0
Dafault output level for object of the StringTable and derived classes.
const string DefaultCsvSeparator = ","
The default separator in the CSV files - comma (",").
Protected Attributes
readonly object _lock = new object()
int _outputLevel = DefaultOutputLevel
List< List< string > > _data = new List<List<string>>()
bool _isReadOnly = false
bool _isAutoExtend = true
string _csvSeparator = UtilCsv.CsvSeparator
Properties
object Lock [get]
Object used for thread locking.
int OutputLevel [get, set]
Output level, specifies the level of descriptive output on console during the operation.
List< List< string > > Data [get]
Data behind the table - list of lists of strings.
bool IsReadOnly [get, set]
Whether or not data table is read only.
bool IsAutoExtend [get, set]
Whether or not data storage automatically extends when a value is set on the position that is out of range.
string this[int rowNumber, int columnNumber] [get, set]
Index operator, gets or sets the specific element of the data table specified by row and column number.
string[][] Table [get, set]
Gets or sets copy of the data table in form of 2D jagged array.
int NumRows [get]
Gets number of rows in the data table.
int MaxNumColumns [get]
Returns the maximal number of columns in any row.
bool IsRectangular [get]
Returns true if data table is rectangular (i.e. all rows have equal number of elements) or not.
string CsvSeparator [get, set]
Separator used in CSV files that this class loads data from or writes data to.
Properties inherited from IG.Lib.ILockable
object Lock [get]
Detailed Description
2D tables of data represented by strings. Maps to CSV files.
Data access operations are thread safe.
$A Igor xx;
Definition at line 39 of file StringTable.cs.
Constructor & Destructor Documentation
StringTable() [1/2]
IG.Lib.StringTable.StringTable (bool readOnly) inline
Constructs a new string table, a data structure compatible with CSV file format.
Parameters
readOnly Whether the created object is read only or not.
Definition at line 44 of file StringTable.cs.
References IG.Lib.StringTable.IsReadOnly.
StringTable() [2/2]
IG.Lib.StringTable.StringTable () inline
Constructs a new string table, a data structure compatible with CSV file format.
Definition at line 50 of file StringTable.cs.
Referenced by IG.Lib.StringTable.ExampleWriteCsv().
Member Function Documentation
SetElement()
void IG.Lib.StringTable.SetElement (int rowNumber, int columnNumber, string element) inline
Sets element at the specified position to the specified value.
Parameters
rowNumber Row index of the element to be set.
columnNumber Column index of the element to be set.
element Element to be set.
Definition at line 207 of file StringTable.cs.
Referenced by IG.Lib.StringTable.SetElement< ElementType >().
SetElement< ElementType >()
void IG.Lib.StringTable.SetElement< ElementType > (int rowNumber, int columnNumber, ElementType elementValue) inline
Sets element at the specified position to the string representation of the specified value.
Parameters
rowNumber Row index of the element to be set.
columnNumber Column index of the element to be set.
elementValue Value whose string representation is to be set.
Definition at line 216 of file StringTable.cs.
References IG.Lib.StringTable.SetElement().
GetElement< ElementType >()
ElementType IG.Lib.StringTable.GetElement< ElementType > (int rowNumber, int columnNumber) inline
Returns the element of the specified type at the specified position.
Element is parrsed from the string element. Exception is thrown if the element doed not exist or parsing fails.
Template Parameters
ElementType Type of the element to be returned.
Parameters
rowNumber Row index of the element.
columnNumber Column index of the element.
Returns
Object (of simple type) parsed from the element at the speciffied position.
Definition at line 238 of file StringTable.cs.
References IG.Lib.Util.Parse().
Referenced by IG.Lib.StringTable.TryGetElement< ElementType >().
TryGetElement< ElementType >()
bool IG.Lib.StringTable.TryGetElement< ElementType > (int rowNumber, int columnNumber, ref ElementType elementValue) inline
Tries to obtain a value of the specified type at the specified position, and returns a flag indicating whether parsing the value from a string was successful (and the element existed).
Value (of the specified type) of the specified element is returned through a ref parameter.
Template Parameters
ElementType Type of the element to be extracted.
Parameters
rowNumber Row index of the element.
columnNumber Column index of the element.
elementValue Argument through which the value is returned.
Returns
Value of the specified element.
Definition at line 251 of file StringTable.cs.
References IG.Lib.StringTable.GetElement< ElementType >().
Referenced by IG.Lib.StringTable.IsDefined< ElementType >().
IsDefined< ElementType >()
bool IG.Lib.StringTable.IsDefined< ElementType > (int rowNumber, int columnNumber) inline
Returns a flag indicating whether the specified position contains a valid string representation of a element of the specified type.
Template Parameters
ElementType Element type.
Parameters
rowNumber Row index of the element.
columnNumber Column index of the element.
Returns
true if the specified position contains a valid non-null element of the specified type, false otherwise.
Definition at line 269 of file StringTable.cs.
References IG.Lib.StringTable.TryGetElement< ElementType >().
IsDefined()
bool IG.Lib.StringTable.IsDefined (int rowNumber, int columnNumber) inline
Returns a flag telling whether the specified element is defined (it exists in the data table) or not.
If the specified element is null, true is returned. Use IsNotNullOrEmpty method to check also if the element is not null or empty string.
Parameters
rowNumber Row number of the element checked.
columnNumber Column number of the element checked.
Definition at line 281 of file StringTable.cs.
References IG.Lib.StringTable._data, and IG.Lib.StringTable.Lock.
Referenced by IG.Num.SampledDataCsv.CheckIfDataColumnsDefined().
IsNotNullOrEmpty()
bool IG.Lib.StringTable.IsNotNullOrEmpty (int rowNumber, int columnNumber) inline
Returns a flag telling whether the specified element is defined (it exists in the data table) and is at the same time not null or empty string.
Parameters
rowNumber Row number of the element checked.
columnNumber Column number of the element checked.
Definition at line 306 of file StringTable.cs.
References IG.Lib.StringTable._data, and IG.Lib.StringTable.Lock.
Referenced by IG.Num.SampledDataCsv.ReadDoubleData(), and IG.Num.SampledDataCsv.ReadIntData().
GetElementOrNull() [1/2]
string IG.Lib.StringTable.GetElementOrNull (int rowNumber, int columnNumber, out bool isDefined) inline
Returns the specified element on the data table or null if that element is not defined, and notifies the caller through isDefined whether the element is defined or not.
Parameters
rowNumber Row number of the element checked.
columnNumber Column number of the element checked.
isDefined Specifies, on return, whether the specified element is defined (it exists in the data table).
Definition at line 333 of file StringTable.cs.
References IG.Lib.StringTable._data, and IG.Lib.StringTable.Lock.
Referenced by IG.Lib.StringTable.GetElementOrNull().
GetElementOrNull() [2/2]
string IG.Lib.StringTable.GetElementOrNull (int rowNumber, int columnNumber) inline
Returns the specified element on the data table or null if that element is not defined.
Use another overload to also notify the caller whether the element is defined or not.
Parameters
rowNumber Row number of the element checked.
columnNumber Column number of the element checked.
Definition at line 361 of file StringTable.cs.
References IG.Lib.StringTable.GetElementOrNull().
FirstNonemptyRow() [1/2]
int IG.Lib.StringTable.FirstNonemptyRow (int startRow) inline
Returns index of the first non-empty row from the specified row on (inclusively), or -1 if there is no such row.
Parameters
startRow Row where search starts.
Definition at line 370 of file StringTable.cs.
References IG.Lib.StringTable._data, and IG.Lib.StringTable.Lock.
FirstNonemptyRow() [2/2]
int IG.Lib.StringTable.FirstNonemptyRow () inline
Returns index of the first non-empty row of the table, or -1 if there is no such row.
Definition at line 385 of file StringTable.cs.
FirstNonemptyColumn() [1/2]
int IG.Lib.StringTable.FirstNonemptyColumn (int rowNum, int startColumn) inline
Returns number of the first non-empty cell in the specified row, from the specified starting column on (inclusively), or -1 if there is no suuch column.
Parameters
rowNum Index of row in which nonemnty cell is searched for.
startColumn Starting column from which on (inclusively) a nonempty cell is searched.
Definition at line 394 of file StringTable.cs.
References IG.Lib.StringTable._data, and IG.Lib.StringTable.Lock.
Referenced by IG.Num.SampledDataCsv.FindFirstDataCell(), IG.Lib.StringTable.FirstNonemptyColumn(), IG.Num.SampledDataCsv.GetDataColumnDefinitionsFromData(), IG.Num.SampledDataCsv.ReadElementIndices(), IG.Num.SampledDataCsv.ReadElementTypes(), IG.Num.SampledDataCsv.ReadSingleInt(), IG.Num.SampledDataCsv.RestoreData(), and IG.Num.SampledDataCsv.RestoreDefinition().
FirstNonemptyColumn() [2/2]
int IG.Lib.StringTable.FirstNonemptyColumn (int rowNum) inline
Returns number of the first non-empty cell in the specified row.
Parameters
rowNum Index of row in which nonemnty cell is searched for.
Definition at line 412 of file StringTable.cs.
References IG.Lib.StringTable.FirstNonemptyColumn().
Clear()
void IG.Lib.StringTable.Clear () inline
Clears the data table.
Definition at line 418 of file StringTable.cs.
References IG.Lib.StringTable._data, IG.Lib.StringTable._isReadOnly, and IG.Lib.StringTable.Lock.
Referenced by IG.Num.SampledDataCsv.StoreData(), IG.Num.SampledDataCsv.StoreDefinition(), and IG.Num.SampledDataCsv.StoreDefinitionAndData().
AddRow() [1/2]
void IG.Lib.StringTable.AddRow () inline
Adds a new row at the end of the data table.
Throws exception if the data table is read only.
Definition at line 430 of file StringTable.cs.
References IG.Lib.StringTable._data, IG.Lib.StringTable._isReadOnly, and IG.Lib.StringTable.Lock.
Referenced by IG.Lib.StringTable.AddRow(), IG.Lib.StringTable.AddRow< ElementType >(), and IG.Lib.StringTable.ExampleWriteCsv().
AddRow() [2/2]
void IG.Lib.StringTable.AddRow (params string[] elements) inline
Adds a new row at the end of the data table.
Throws exception if the data table is read only.
Definition at line 444 of file StringTable.cs.
References IG.Lib.StringTable.AddElements(), IG.Lib.StringTable.AddRow(), and IG.Lib.StringTable.Lock.
AddRow< ElementType >()
void IG.Lib.StringTable.AddRow< ElementType > (params ElementType[] elements) inline
Adds (appends) a new row with the specified elements at the end of the table.
Template Parameters
ElementType Type of elements to be added to the newly created row.
Parameters
elements Elements to ne added to the new row.
Throws exception if the data table is read only.
Definition at line 457 of file StringTable.cs.
References IG.Lib.StringTable.AddElements(), IG.Lib.StringTable.AddRow(), and IG.Lib.StringTable.Lock.
AddElement() [1/2]
void IG.Lib.StringTable.AddElement (int rowNum, string value) inline
Adds a new element at the end of the specified row of te data table.
Parameters
rowNum Sequential number of the row to which the element is added.
value Value of the element that is added.
Throws exception if the data table is read only, or if the specified row does not exist and the data table is not extensible.
Definition at line 472 of file StringTable.cs.
References IG.Lib.StringTable._data, IG.Lib.StringTable._isReadOnly, IG.Lib.StringTable.Lock, IG.Lib.StringTable.NumRows, and IG.Lib.StringTable.SetNumRows().
Referenced by IG.Lib.StringTable.AddElement(), IG.Lib.StringTable.AddElement< ElementType >(), and IG.Lib.StringTable.AddElements().
AddElement() [2/2]
void IG.Lib.StringTable.AddElement (string value) inline
Adds (appends) the speecified element at the end of the table, i.e. at the end of the last row.
Parameters
value Value to be added to the table.
Definition at line 486 of file StringTable.cs.
References IG.Lib.StringTable._data, and IG.Lib.StringTable.AddElement().
AddElement< ElementType >() [1/2]
void IG.Lib.StringTable.AddElement< ElementType > (int rowNum, ElementType value) inline
Adds string representation of a new element of the specified type at the end of the specified row of te data table.
Parameters
rowNum Sequential number of the row to which the element is added.
value Value of the element that is added.
Throws exception if the data table is read only, or if the specified row does not exist and the data table is not extensible.
Definition at line 498 of file StringTable.cs.
References IG.Lib.StringTable.AddElement().
Referenced by IG.Lib.StringTable.AddElements< ElementType >().
AddElement< ElementType >() [2/2]
void IG.Lib.StringTable.AddElement< ElementType > (ElementType value) inline
Adds (appends) string representatin of the speecified element at the end of the table, i.e. at the end of the last row.
Parameters
value Value to be added to the table.
Definition at line 509 of file StringTable.cs.
References IG.Lib.StringTable._data, and IG.Lib.StringTable.AddElement().
AddElements() [1/2]
void IG.Lib.StringTable.AddElements (int rowNum, params string[] values) inline
Adds the specified elements at the end of the specified row of te data table.
Parameters
rowNum Sequential number of the row to which the elements are added.
values Array of values of the elements that are added.
Throws exception if the data table is read only, or if the specified row does not exist and the data table is not extensible.
Definition at line 520 of file StringTable.cs.
References IG.Lib.StringTable.AddElement(), and IG.Lib.StringTable.Lock.
Referenced by IG.Lib.StringTable.AddElements(), IG.Lib.StringTable.AddElements< ElementType >(), IG.Lib.StringTable.AddRow(), IG.Lib.StringTable.AddRow< ElementType >(), and IG.Lib.StringTable.ExampleWriteCsv().
AddElements< ElementType >() [1/2]
void IG.Lib.StringTable.AddElements< ElementType > (int rowNum, params ElementType[] values) inline
Adds string representations of the specified elements of the specified type at the end of the specified row of te data table.
Template Parameters
ElementType Type of elements to be added.
Parameters
rowNum Sequential number of the row to which the elements are added.
values Array of values of the elements that are added.
Throws exception if the data table is read only, or if the specified row does not exist and the data table is not extensible.
Definition at line 542 of file StringTable.cs.
References IG.Lib.StringTable.AddElement< ElementType >(), and IG.Lib.StringTable.Lock.
AddElements() [2/2]
void IG.Lib.StringTable.AddElements (params string[] values) inline
Adds (appends) the specified elements at the end of the table, i.e. at the end of the last row.
Parameters
values Array of values of the elements that are added.
Throws exception if the data table is read only, or if the specified row does not exist and the data table is not extensible.
Definition at line 561 of file StringTable.cs.
References IG.Lib.StringTable._data, and IG.Lib.StringTable.AddElements().
AddElements< ElementType >() [2/2]
void IG.Lib.StringTable.AddElements< ElementType > (params ElementType[] values) inline
Adds (appends) string representations of the specified elements of the specified type at the end of the table, i.e. at the end of the last row.
Parameters
values Array of values of the elements that are added.
Throws exception if the data table is read only, or if the specified row does not exist and the data table is not extensible.
Definition at line 571 of file StringTable.cs.
References IG.Lib.StringTable._data, and IG.Lib.StringTable.AddElements().
SetNumRows()
void IG.Lib.StringTable.SetNumRows (int numRows) inline
Change the number of rows in the data table to the specified number.
Parameters
numRows New number of rows.
Throws exception if the data table is read only.
If the current number of rows is smaller than the one specified, then new empty (but allocated) rows are added. If the number is greater then the redundant rows are removed.
Definition at line 582 of file StringTable.cs.
References IG.Lib.StringTable._data, IG.Lib.StringTable._isReadOnly, and IG.Lib.StringTable.Lock.
Referenced by IG.Lib.StringTable.AddElement(), and IG.Lib.StringTable.SetNumColumns().
SetNumColumns()
void IG.Lib.StringTable.SetNumColumns (int rowNum, int numColumns) inline
Changes the number of columns of the specified row to the specified number.
Parameters
rowNum Row number where number of columns is changed.
numColumns New numbef of columns in the specified row.
Throws exception if the data table is read only.
If the current number of rows is smaller than the specified row number, then new empty (but allocated) rows are added. Cells that are eventually added are set to null.
Definition at line 605 of file StringTable.cs.
References IG.Lib.StringTable._data, IG.Lib.StringTable._isReadOnly, IG.Lib.StringTable.Lock, IG.Lib.StringTable.NumRows, and IG.Lib.StringTable.SetNumRows().
ClearRow()
void IG.Lib.StringTable.ClearRow (int rowNum) inline
Clears the specified row in the data table.
Parameters
rowNum Number of the row to be cleared.
Throws exception if the data table is read only, or if the row number is out of range and the data table is not automatically extendable.
Definition at line 626 of file StringTable.cs.
References IG.Lib.StringTable._data, IG.Lib.StringTable._isAutoExtend, IG.Lib.StringTable._isReadOnly, IG.Lib.StringTable.Lock, and IG.Lib.StringTable.NumRows.
NumColumns()
int IG.Lib.StringTable.NumColumns (int rowNum) inline
Returns the number of elements (columns) of the specified row.
Parameters
rowNum Specifies for which row number of columns is returned.
Definition at line 741 of file StringTable.cs.
References IG.Lib.StringTable._data, and IG.Lib.StringTable.Lock.
IsInt()
bool IG.Lib.StringTable.IsInt (int rowNumber, int columnNumber) inline
Returns a flag specified whether the specified element of the data table exists and represents an integer.
If the element does not exist then false is returned.
Parameters
rowNumber Row number of the data table element.
columnNumber Column number of the data table element.
Definition at line 794 of file StringTable.cs.
References IG.Lib.StringTable._data, and IG.Lib.StringTable.Lock.
Referenced by IG.Num.SampledDataCsv.GetDataColumnDefinitionsFromData(), IG.Num.SampledDataCsv.ReadElementIndices(), and IG.Num.SampledDataCsv.ReadSingleInt().
GetInt()
int IG.Lib.StringTable.GetInt (int rowNumber, int columnNumber) inline
Returns an integer value of the element at the specified position of the data table, if it is defined, or throws an exception.
Parameters
rowNumber Row number of the data table element.
columnNumber Column number of the data table element.
Returns
Integer value of the specified element, if the element exists and can be converted to an integer (otherwise, an exception is thrown).
Definition at line 830 of file StringTable.cs.
References IG.Lib.StringTable.GetIntSafe(), IG.Lib.StringTable.Lock, and IG.Lib.StringTable.TryGetInt().
Referenced by IG.Num.SampledDataCsv.ReadElementIndices(), IG.Num.SampledDataCsv.ReadIntData(), and IG.Num.SampledDataCsv.ReadSingleInt().
TryGetInt()
bool IG.Lib.StringTable.TryGetInt (int rowNumber, int columnNumber, out int value) inline
Safely gets the integer value at the specified position of the data table, if it is defined, and notifies the caller whether it is defined.
Parameters
rowNumber Row number of the data table element.
columnNumber Column number of the data table element.
value Holds on return the corresponding integer value of the specified element, if defined, or default integer value (i.e. 0) otherwise.
Returns
Flag indicating whether the elemet at the specified position actually represents an integer.
Definition at line 863 of file StringTable.cs.
References IG.Lib.StringTable._data, and IG.Lib.StringTable.Lock.
Referenced by IG.Lib.StringTable.GetInt().
GetIntSafe()
void IG.Lib.StringTable.GetIntSafe (int rowNumber, int columnNumber, out int value, out bool isElementDefined, out bool isElementNotNullOrEmpty, out bool isInt) inline
Safely gets the integer value at the specified position of the data table, if it is defined, and notifies the caller on the status.
Parameters
rowNumber Row number of the data table element.
columnNumber Column number of the data table element.
value Holds on return the corresponding integer value of the specified element, if defined, or default integer value (i.e. 0) otherwise.
isElementDefined Notifies whether the specified element is defined or not.
isElementNotNullOrEmpty Notifies whether the element at the specified position is not null or empty string.
isInt Notifies whether the elemet at the specified position actually represents an integer.
Definition at line 903 of file StringTable.cs.
References IG.Lib.StringTable._data, and IG.Lib.StringTable.Lock.
Referenced by IG.Lib.StringTable.GetInt().
IsDouble()
bool IG.Lib.StringTable.IsDouble (int rowNumber, int columnNumber) inline
Returns a flag specified whether the specified element of the data table exists and represents a number (of type double).
If the element does not exist then false is returned.
Parameters
rowNumber Row number of the data table element.
columnNumber Column number of the data table element.
Definition at line 946 of file StringTable.cs.
References IG.Lib.StringTable._data, and IG.Lib.StringTable.Lock.
Referenced by IG.Num.SampledDataCsv.GetDataColumnDefinitionsFromData(), and IG.Num.SampledDataCsv.RestoreData().
GetDouble()
double IG.Lib.StringTable.GetDouble (int rowNumber, int columnNumber) inline
Returns a double value of the element at the specified position of the data table, if such element is defined and represents a number, or throws an exception otherwise.
Parameters
rowNumber Row number of the data table element.
columnNumber Column number of the data table element.
Returns
Double value of the specified element, if the element exists and can be converted to an double (otherwise, an exception is thrown).
Definition at line 982 of file StringTable.cs.
References IG.Lib.StringTable.GetDoubleSafe(), IG.Lib.StringTable.Lock, and IG.Lib.StringTable.TryGetDouble().
Referenced by IG.Num.SampledDataCsv.ReadDoubleData().
TryGetDouble()
bool IG.Lib.StringTable.TryGetDouble (int rowNumber, int columnNumber, out double value) inline
Safely gets the double value at the specified position of the data table, if it is defined, and notifies the caller whether it is defined.
Parameters
rowNumber Row number of the data table element.
columnNumber Column number of the data table element.
value Holds on return the corresponding double value of the specified element, if defined, or default double value (i.e. 0) otherwise.
Returns
Flag indicating whether the elemet at the specified position actually represents a double.
Definition at line 1015 of file StringTable.cs.
References IG.Lib.StringTable._data, and IG.Lib.StringTable.Lock.
Referenced by IG.Lib.StringTable.GetDouble().
GetDoubleSafe()
void IG.Lib.StringTable.GetDoubleSafe (int rowNumber, int columnNumber, out double value, out bool isElementDefined, out bool isElementNotNullOrEmpty, out bool isDouble) inline
Safely gets the numerical value (of type double) at the specified position of the data table, if it is defined, and notifies the caller about the status.
Parameters
rowNumber Row number of the data table element.
columnNumber Column number of the data table element.
value Holds on return the corresponding double value of the specified element, if defined, or default double value (i.e. 0.0) otherwise.
isElementDefined Notifies whether the specified element is defined or not.
isElementNotNullOrEmpty Notifies whether the element at the specified position is not null or empty string.
isDouble Notifies whether the elemet at the specified position actually represents a number of type double.
Definition at line 1055 of file StringTable.cs.
References IG.Lib.StringTable._data, and IG.Lib.StringTable.Lock.
Referenced by IG.Lib.StringTable.GetDouble().
LoadCsv() [1/2]
void IG.Lib.StringTable.LoadCsv (string filePath, string separator) inline
Loads the specified CSV file. Reads contents of the file into the data table of the current object.
Parameters
filePath Path to the CSV file that is read and parsed.
separator Separator that is used in the CSV file. If not specified (null or empty string) then Constant UtilCsv.DefaultCsvSeparator is assumed.
Definition at line 1110 of file StringTable.cs.
References IG.Lib.StringTable.CsvSeparator, IG.Lib.UtilCsv.LoadCsv(), IG.Lib.StringTable.Lock, and IG.Lib.StringTable.Table.
Referenced by IG.Lib.StringTable.LoadCsv(), IG.Num.SampledDataCsv.LoadData(), IG.Num.SampledDataCsv.LoadDefinition(), and IG.Num.SampledDataCsv.LoadDefinitionAndData().
LoadCsv() [2/2]
void IG.Lib.StringTable.LoadCsv (string filePath) inline
Loads the specified CSV file. Reads contents of the file into the data table of the current object.
The value of the CsvSeparator property is used as separator.
Parameters
filePath Path to the CSV file that is read and parsed.
Definition at line 1126 of file StringTable.cs.
References IG.Lib.StringTable.CsvSeparator, and IG.Lib.StringTable.LoadCsv().
ToString()
override string IG.Lib.StringTable.ToString () inline
Converts the current string table to a string in CSV form and returns the string.
Definition at line 1133 of file StringTable.cs.
References IG.Lib.StringTable._csvSeparator, IG.Lib.StringTable.Table, and IG.Lib.UtilCsv.ToCsvString().
Referenced by IG.Num.SampledDataCsv.GetPositionString().
SaveCsv() [1/4]
void IG.Lib.StringTable.SaveCsv (string filePath, string separator, bool append) inline
Saves the data of the current object to the specified CSV file.
Parameters
filePath Path to the file into which data is written.
separator Separator that is used in CSV format.
append If true then the CSV string is appended to the existent file if the file already exists. Otherwise, existend files are overwritten.
Definition at line 1146 of file StringTable.cs.
References IG.Lib.StringTable.Lock, IG.Lib.UtilCsv.SaveCsv(), and IG.Lib.StringTable.Table.
Referenced by IG.Lib.StringTable.ExampleWriteCsv(), IG.Lib.StringTable.SaveCsv(), IG.Num.SampledDataCsv.SaveData(), IG.Num.SampledDataCsv.SaveDefinition(), and IG.Num.SampledDataCsv.SaveDefinitionAndData().
SaveCsv() [2/4]
void IG.Lib.StringTable.SaveCsv (string filePath, string separator) inline
Saves the data of the current object into a CSV file. If the file already exists then its contents are overwritten.
Parameters
filePath Path to the file into which contents is written.
separator Separator that is used in CSV format.
Definition at line 1160 of file StringTable.cs.
References IG.Lib.StringTable.SaveCsv().
SaveCsv() [3/4]
void IG.Lib.StringTable.SaveCsv (string filePath, bool append) inline
Saves the data of the current object into a CSV file. Constant UtilCsv.DefaultCsvSeparator is assumed to be a separator for the CSV format.
Parameters
filePath Path to the file into which contents is written.
append If true then the CSV string is appended to the existent file if the file already exists. Otherwise, existend files are overwritten.
Definition at line 1170 of file StringTable.cs.
References IG.Lib.StringTable.CsvSeparator, and IG.Lib.StringTable.SaveCsv().
SaveCsv() [4/4]
void IG.Lib.StringTable.SaveCsv (string filePath) inline
Saves the data of the current object values into a CSV file. If the file already exists then its contents are overwritten. Constant UtilCsv.DefaultCsvSeparator is assumed to be a separator for the CSV format.
Parameters
filePath Path to the file into which contents is written.
Definition at line 1179 of file StringTable.cs.
References IG.Lib.StringTable.CsvSeparator, and IG.Lib.StringTable.SaveCsv().
ExampleWriteCsv()
static void IG.Lib.StringTable.ExampleWriteCsv (string filePath) inline static
Creates a simple string table and saves it to a CSV file.
Parameters
filePath Path to the file where CSV is stored.
Definition at line 1191 of file StringTable.cs.
References IG.Lib.StringTable.AddElements(), IG.Lib.StringTable.AddRow(), IG.Num.RandomGenerator.Global, IG.Num.IRandomGenerator.NextDouble(), IG.Lib.StringTable.SaveCsv(), and IG.Lib.StringTable.StringTable().
Member Data Documentation
_lock
readonly object IG.Lib.StringTable._lock = new object() protected
Definition at line 57 of file StringTable.cs.
DefaultOutputLevel
int IG.Lib.StringTable.DefaultOutputLevel = 0 static
Dafault output level for object of the StringTable and derived classes.
Definition at line 68 of file StringTable.cs.
_outputLevel
int IG.Lib.StringTable._outputLevel = DefaultOutputLevel protected
Definition at line 70 of file StringTable.cs.
_data
List<List<string> > IG.Lib.StringTable._data = new List<List<string>>() protected
Definition at line 82 of file StringTable.cs.
Referenced by IG.Lib.StringTable.AddElement(), IG.Lib.StringTable.AddElement< ElementType >(), IG.Lib.StringTable.AddElements(), IG.Lib.StringTable.AddElements< ElementType >(), IG.Lib.StringTable.AddRow(), IG.Lib.StringTable.Clear(), IG.Lib.StringTable.ClearRow(), IG.Lib.StringTable.FirstNonemptyColumn(), IG.Lib.StringTable.FirstNonemptyRow(), IG.Lib.StringTable.GetDoubleSafe(), IG.Lib.StringTable.GetElementOrNull(), IG.Lib.StringTable.GetIntSafe(), IG.Lib.StringTable.IsDefined(), IG.Lib.StringTable.IsDouble(), IG.Lib.StringTable.IsInt(), IG.Lib.StringTable.IsNotNullOrEmpty(), IG.Lib.StringTable.NumColumns(), IG.Lib.StringTable.SetNumColumns(), IG.Lib.StringTable.SetNumRows(), IG.Lib.StringTable.TryGetDouble(), and IG.Lib.StringTable.TryGetInt().
_isReadOnly
bool IG.Lib.StringTable._isReadOnly = false protected
Definition at line 91 of file StringTable.cs.
Referenced by IG.Lib.StringTable.AddElement(), IG.Lib.StringTable.AddRow(), IG.Lib.StringTable.Clear(), IG.Lib.StringTable.ClearRow(), IG.Lib.StringTable.SetNumColumns(), and IG.Lib.StringTable.SetNumRows().
_isAutoExtend
bool IG.Lib.StringTable._isAutoExtend = true protected
Definition at line 100 of file StringTable.cs.
Referenced by IG.Lib.StringTable.ClearRow().
DefaultCsvSeparator
const string IG.Lib.StringTable.DefaultCsvSeparator = "," static
The default separator in the CSV files - comma (",").
Definition at line 1095 of file StringTable.cs.
_csvSeparator
string IG.Lib.StringTable._csvSeparator = UtilCsv.CsvSeparator protected
Definition at line 1097 of file StringTable.cs.
Referenced by IG.Lib.StringTable.ToString().
Property Documentation
Lock
object IG.Lib.StringTable.Lock get
Object used for thread locking.
Definition at line 61 of file StringTable.cs.
Referenced by IG.Lib.StringTable.AddElement(), IG.Lib.StringTable.AddElements(), IG.Lib.StringTable.AddElements< ElementType >(), IG.Lib.StringTable.AddRow(), IG.Lib.StringTable.AddRow< ElementType >(), IG.Num.SampledDataCsv.CheckIfDataColumnsDefined(), IG.Lib.StringTable.Clear(), IG.Num.SampledDataCsv.ClearDataColumnDefinitions(), IG.Lib.StringTable.ClearRow(), IG.Num.SampledDataCsv.FindFirstDataCell(), IG.Lib.StringTable.FirstNonemptyColumn(), IG.Lib.StringTable.FirstNonemptyRow(), IG.Num.SampledDataCsv.GetDataColumnDefinitionsFromData(), IG.Lib.StringTable.GetDouble(), IG.Lib.StringTable.GetDoubleSafe(), IG.Lib.StringTable.GetElementOrNull(), IG.Num.SampledDataCsv.GetInputElementDefinition(), IG.Lib.StringTable.GetInt(), IG.Lib.StringTable.GetIntSafe(), IG.Num.SampledDataCsv.GetOutputElementDefinition(), IG.Lib.StringTable.IsDefined(), IG.Lib.StringTable.IsDouble(), IG.Lib.StringTable.IsInt(), IG.Lib.StringTable.IsNotNullOrEmpty(), IG.Lib.StringTable.LoadCsv(), IG.Lib.StringTable.NumColumns(), IG.Num.SampledDataCsv.ReadDoubleData(), IG.Num.SampledDataCsv.ReadElementDefaultValues(), IG.Num.SampledDataCsv.ReadElementDescriptions(), IG.Num.SampledDataCsv.ReadElementDiscretizationSteps(), IG.Num.SampledDataCsv.ReadElementIndices(), IG.Num.SampledDataCsv.ReadElementMaximalValues(), IG.Num.SampledDataCsv.ReadElementMinimalValues(), IG.Num.SampledDataCsv.ReadElementNames(), IG.Num.SampledDataCsv.ReadElementNumSamplingPoints(), IG.Num.SampledDataCsv.ReadElementOptimizationIndices(), IG.Num.SampledDataCsv.ReadElementScalingLengths(), IG.Num.SampledDataCsv.ReadElementTargetValues(), IG.Num.SampledDataCsv.ReadElementTitles(), IG.Num.SampledDataCsv.ReadElementTypes(), IG.Num.SampledDataCsv.ReadIntData(), IG.Num.SampledDataCsv.ReadStringData(), IG.Num.SampledDataCsv.RestoreData(), IG.Lib.StringTable.SaveCsv(), IG.Num.SampledDataCsv.SaveData(), IG.Num.SampledDataCsv.SaveDefinition(), IG.Num.SampledDataCsv.SaveDefinitionAndData(), IG.Lib.StringTable.SetNumColumns(), IG.Lib.StringTable.SetNumRows(), IG.Num.SampledDataCsv.StoreDefinition(), IG.Lib.StringTable.TryGetDouble(), IG.Lib.StringTable.TryGetInt(), and IG.Num.SampledDataCsv.UpdateDataColumnDefinitions().
OutputLevel
int IG.Lib.StringTable.OutputLevel get set
Output level, specifies the level of descriptive output on console during the operation.
Definition at line 74 of file StringTable.cs.
Referenced by IG.Script.ScriptAppBase.DataStructuresFunctionTestCsvReadDefinitionAndData(), IG.Script.ScriptAppBase.DataStructuresFunctionTestCsvWriteDefinitionAndData(), IG.Num.SampledDataCsv.ReadElementIndices(), IG.Num.SampledDataCsv.ReadElementTypes(), IG.Num.SampledDataCsv.RestoreData(), and IG.Num.SampledDataCsv.RestoreDefinition().
Data
List<List<string> > IG.Lib.StringTable.Data get protected
Data behind the table - list of lists of strings.
Definition at line 86 of file StringTable.cs.
IsReadOnly
bool IG.Lib.StringTable.IsReadOnly get set
Whether or not data table is read only.
Definition at line 95 of file StringTable.cs.
Referenced by IG.Lib.CsvData.CsvData(), IG.Num.SampledDataCsv.SampledDataCsv(), and IG.Lib.StringTable.StringTable().
IsAutoExtend
bool IG.Lib.StringTable.IsAutoExtend get set
Whether or not data storage automatically extends when a value is set on the position that is out of range.
Definition at line 104 of file StringTable.cs.
Referenced by IG.Num.SampledDataCsv.SampledDataCsv().
this[int rowNumber, int columnNumber]
string IG.Lib.StringTable.this[int rowNumber, int columnNumber] get set
Index operator, gets or sets the specific element of the data table specified by row and column number.
Handling situation when row or column number is out of range:
If IsAutoExtend then getter returns null and setter extends the table as needed.
Otherwise, IndexOutOfRangeException exception is thrown.
Parameters
rowNumber Row number of the element (zero-based).
columnNumber Column number of the element (zero-based).
Definition at line 116 of file StringTable.cs.
Table
string [][] IG.Lib.StringTable.Table get set
Gets or sets copy of the data table in form of 2D jagged array.
Definition at line 645 of file StringTable.cs.
Referenced by IG.Lib.StringTable.LoadCsv(), IG.Lib.StringTable.SaveCsv(), and IG.Lib.StringTable.ToString().
NumRows
int IG.Lib.StringTable.NumRows get
Gets number of rows in the data table.
Definition at line 707 of file StringTable.cs.
Referenced by IG.Lib.StringTable.AddElement(), IG.Lib.StringTable.ClearRow(), IG.Num.SampledDataCsv.RestoreDefinition(), and IG.Lib.StringTable.SetNumColumns().
MaxNumColumns
int IG.Lib.StringTable.MaxNumColumns get
Returns the maximal number of columns in any row.
Definition at line 719 of file StringTable.cs.
IsRectangular
bool IG.Lib.StringTable.IsRectangular get
Returns true if data table is rectangular (i.e. all rows have equal number of elements) or not.
Table without rows or with one row is considered rectangular.
Table with all rows empty or null is considered rectangular.
Definition at line 760 of file StringTable.cs.
CsvSeparator
string IG.Lib.StringTable.CsvSeparator get set
Separator used in CSV files that this class loads data from or writes data to.
Property is used by ethods that deal with CSV files and do not have separator as.
Definition at line 1102 of file StringTable.cs.
Referenced by IG.Lib.StringTable.LoadCsv(), and IG.Lib.StringTable.SaveCsv().
The documentation for this class was generated from the following file:
iglib/igbase/0guests/Tako78/datastructures/StringTable.cs