Doc: IGLib with source files: IG.Lib.ThreadPulser Class Reference
IG.Lib.ThreadPulser Class Reference
Launches (immediately upon creation) a thread that performs pulsing on its object. PulseAll is perfomed on its Lock object every time the object is pulsed from another thread. This object acts as kind of proxy for pulsing and provides the object used for locking and pulsing.
Public Member Functions
virtual void PrepareForPulsing ()
Performs evantual preparation of data before pulsing is performed.
void TriggerPulsing ()
Triggers pulsing performed by this object's thread.
Protected Member Functions
virtual void ThreadMethod ()
Properties
bool PrintNotes [get, set]
If true then various events and actions will be notified by console output (for testing purposes only!).
Thread ThreadObject [get, protected set]
object TriggerLock [get]
Object used to trigger pulsing and for related locking. Whenever Monitor.Pulse() is performed on this object, the main thread of the current object will perform Monitor.Pulse(PulsingLock).
Private Member Functions
void PulseThread ()
Private Attributes
bool _printNotes = false
Thread _thread
object _triggerLock = new object()
Detailed Description
Launches (immediately upon creation) a thread that performs pulsing on its object. PulseAll is perfomed on its Lock object every time the object is pulsed from another thread. This object acts as kind of proxy for pulsing and provides the object used for locking and pulsing.
Definition at line 33 of file WaitConditionFile.cs.
Member Function Documentation
PulseThread()
void IG.Lib.ThreadPulser.PulseThread () inline private
Definition at line 35 of file WaitConditionFile.cs.
References IG.Lib.ThreadPulser.ThreadObject.
PrepareForPulsing()
virtual void IG.Lib.ThreadPulser.PrepareForPulsing () inline virtual
Performs evantual preparation of data before pulsing is performed.
Definition at line 78 of file WaitConditionFile.cs.
Referenced by IG.Lib.ThreadPulser.ThreadMethod().
TriggerPulsing()
void IG.Lib.ThreadPulser.TriggerPulsing () inline
Triggers pulsing performed by this object's thread.
Definition at line 83 of file WaitConditionFile.cs.
References IG.Lib.ThreadPulser.PrintNotes, and IG.Lib.ThreadPulser.TriggerLock.
Referenced by IG.Lib.WaitFileEventBase.TriggerConditionCheck().
ThreadMethod()
virtual void IG.Lib.ThreadPulser.ThreadMethod () inline protected virtual
Definition at line 93 of file WaitConditionFile.cs.
References IG.Lib.ThreadPulser.PrepareForPulsing(), IG.Lib.ThreadPulser.PrintNotes, and IG.Lib.ThreadPulser.TriggerLock.
Member Data Documentation
_printNotes
bool IG.Lib.ThreadPulser._printNotes = false private
Definition at line 43 of file WaitConditionFile.cs.
_thread
Thread IG.Lib.ThreadPulser._thread private
Definition at line 52 of file WaitConditionFile.cs.
_triggerLock
object IG.Lib.ThreadPulser._triggerLock = new object() private
Definition at line 70 of file WaitConditionFile.cs.
Property Documentation
PrintNotes
bool IG.Lib.ThreadPulser.PrintNotes get set
If true then various events and actions will be notified by console output (for testing purposes only!).
Definition at line 47 of file WaitConditionFile.cs.
Referenced by IG.Lib.ThreadPulser.ThreadMethod(), IG.Lib.ThreadPulser.TriggerPulsing(), and IG.Lib.WaitFileEventBase.WaitFileEventBase().
ThreadObject
Thread IG.Lib.ThreadPulser.ThreadObject get protected set
Definition at line 55 of file WaitConditionFile.cs.
Referenced by IG.Lib.ThreadPulser.PulseThread().
TriggerLock
object IG.Lib.ThreadPulser.TriggerLock get
Object used to trigger pulsing and for related locking. Whenever Monitor.Pulse() is performed on this object, the main thread of the current object will perform Monitor.Pulse(PulsingLock).
Definition at line 75 of file WaitConditionFile.cs.
Referenced by IG.Lib.ThreadPulser.ThreadMethod(), and IG.Lib.ThreadPulser.TriggerPulsing().
The documentation for this class was generated from the following file:
iglib/igbase/0unsorted/WaitConditionFile.cs