Doc: IGLib with source files: IG.Num.Func3d2dBase Class Reference
IG.Num.Func3d2dBase Class Reference abstract
Base class for 3D vector functions of 2 variables (base for implementation of IFunc3d2d interface).
Classes
class ComponentFunction1
Class that represents a scalar function of 2 variables that is the first component of the specified 3D vector function of 2 variables.
class ComponentFunction2
Class that represents a scalar function of 2 variables that is the first component of the specified 3D vector function of 2 variables.
class ComponentFunction3
Class that represents a scalar function of 2 variables that is the third component of the specified 3D vector function of 2 variables.
class ComponentFunctionBase
Base function for component functions, provides internal variable for vector function.
Public Member Functions
abstract double Value1 (double x, double y)
Calculates and returns value of the first component of the current function.
abstract double Value2 (double x, double y)
Calculates and returns value of the second component of the current function.
abstract double Value3 (double x, double y)
Calculates and returns value of the third component of the current function.
virtual double Value1 (vec2 parameters)
Calculates and returns value of the first component of the current function.
virtual double Value2 (vec2 parameters)
Calculates and returns value of the second component of the current function.
virtual double Value3 (vec2 parameters)
Calculates and returns value of the third component of the current function.
abstract void Gradient1 (double x, double y, out double gradx, out double grady)
Calculates gradient of the first component of the current function and returns its components through the specified output variables.
abstract void Gradient2 (double x, double y, out double gradx, out double grady)
Calculates gradient of the second component of the current function and returns its components through the specified output variables.
abstract void Gradient3 (double x, double y, out double gradx, out double grady)
Calculates gradient of the third component of the current function and returns its components through the specified output variables.
virtual vec2 Gradient1 (vec2 parameters)
Calculates and returns gradient of the first component of the current function.
virtual vec2 Gradient2 (vec2 parameters)
Calculates and returns gradient of the second component of the current function.
virtual vec2 Gradient3 (vec2 parameters)
Calculates and returns gradient of the third component of the current function.
abstract void Hessian1 (double x, double y, out double dxx, out double dyy, out double dxy)
Calculates Hessian of the first component of the current function and returns its component through the specified output variables.
abstract void Hessian2 (double x, double y, out double dxx, out double dyy, out double dxy)
Calculates Hessian of the second component of the current function and returns its component through the specified output variables.
abstract void Hessian3 (double x, double y, out double dxx, out double dyy, out double dxy)
Calculates Hessian of the third component of the current function and returns its component through the specified output variables.
virtual mat2 Hessian1 (vec2 parameters)
Calculates and returns Hessian of the first component of the current function and returns it (in the form of a mat2 struct).
virtual mat2 Hessian2 (vec2 parameters)
Calculates and returns Hessian of the second component of the current function and returns it (in the form of a mat2 struct).
virtual mat2 Hessian3 (vec2 parameters)
Calculates and returns Hessian of the third component of the current function and returns it (in the form of a mat2 struct).
Static Public Member Functions
static void Example ()
Example of use of a 2D function.
Protected Member Functions
Func3d2dBase ()
Static Protected Member Functions
static void TestFunction (IFunc2d f)
Demonstrates use of a 2D function by printing to the console 5 values and gradients of the function on the line connecting the two points (0, 0, 0) and (1, 1, 1).
static void TestFunction (IFunc2d f, double xmin, double xmax, double ymin, double ymax, int numPoints)
Demonstrates use of a 2D function by printing to the console some values and gradients of the function on the line connecting the two specified points.
Properties
virtual bool ValueDefined [get, protected set]
Whether calculation of function value is defined. Defaulet is true.
virtual bool GradientDefined [get, protected set]
Whether calculation of functio ngradient is defined. Default is false.
virtual bool HessianDefined [get, protected set]
Whether calculation of function Hessian is defined. Default is false.
int NumParam [get]
Gets number of parameters.
int NumValues [get]
Gets number of components of the current vector function.
virtual Func2dBase Component1 [get]
Returns the scalar function that represents the first component of the current 3D vector function of 2 variables.
virtual Func2dBase Component2 [get]
Returns the scalar function that represents the second component of the current 3D vector function of 2 variables.
virtual Func2dBase Component3 [get]
Returns the scalar function that represents the third component of the current 3D vector function of 2 variables.
Properties inherited from IG.Num.IFunc3d2d
bool ValueDefined [get]
Whether calculation of function value is defined.
bool GradientDefined [get]
Whether calculation of function ngradient is defined.
bool HessianDefined [get]
Whether calculation of function Hessian is defined.
Func2dBase Component1 [get]
Returns the scalar function that represents the first component of the current 3D vector function of 2 variables.
Func2dBase Component2 [get]
Returns the scalar function that represents the second component of the current 3D vector function of 2 variables.
Func2dBase Component3 [get]
Returns the scalar function that represents the third component of the current 3D vector function of 2 variables.
Private Attributes
bool _valueDefined = true
bool _gradientDefined = false
bool _hessianDefined = false
Func2dBase _comp1
Func2dBase _comp2
Func2dBase _comp3
Detailed Description
Base class for 3D vector functions of 2 variables (base for implementation of IFunc3d2d interface).
$A Igor Oct09;
Definition at line 238 of file Function3d2d.cs.
Constructor & Destructor Documentation
Func3d2dBase()
IG.Num.Func3d2dBase.Func3d2dBase () inline protected
Definition at line 241 of file Function3d2d.cs.
Member Function Documentation
Value1() [1/2]
abstract double IG.Num.Func3d2dBase.Value1 (double x, double y) pure virtual
Calculates and returns value of the first component of the current function.
Parameters
x First parameter.
y Second parameter.
Implements IG.Num.IFunc3d2d.
Implemented in IG.Num.Func3d2dExamples.ParametricSurface.
Referenced by IG.Num.Func3d2dBase.Value1().
Value2() [1/2]
abstract double IG.Num.Func3d2dBase.Value2 (double x, double y) pure virtual
Calculates and returns value of the second component of the current function.
Parameters
x First parameter.
y Second parameter.
Implements IG.Num.IFunc3d2d.
Implemented in IG.Num.Func3d2dExamples.ParametricSurface.
Referenced by IG.Num.Func3d2dBase.Value2().
Value3() [1/2]
abstract double IG.Num.Func3d2dBase.Value3 (double x, double y) pure virtual
Calculates and returns value of the third component of the current function.
Parameters
x First parameter.
y Second parameter.
Implements IG.Num.IFunc3d2d.
Implemented in IG.Num.Func3d2dExamples.ParametricSurface.
Referenced by IG.Num.Func3d2dBase.Value3().
Value1() [2/2]
virtual double IG.Num.Func3d2dBase.Value1 (vec2 parameters) inline virtual
Calculates and returns value of the first component of the current function.
Parameters
parameters Vector of function parameters (in form of the Value) struct.
Returns
Function value.
Implements IG.Num.IFunc3d2d.
Definition at line 297 of file Function3d2d.cs.
References IG.Num.Func3d2dBase.Value1(), IG.Num.vec2.x, and IG.Num.vec2.y.
Value2() [2/2]
virtual double IG.Num.Func3d2dBase.Value2 (vec2 parameters) inline virtual
Calculates and returns value of the second component of the current function.
Parameters
parameters Vector of function parameters (in form of the Value) struct.
Returns
Function value.
Implements IG.Num.IFunc3d2d.
Definition at line 305 of file Function3d2d.cs.
References IG.Num.Func3d2dBase.Value2(), IG.Num.vec2.x, and IG.Num.vec2.y.
Value3() [2/2]
virtual double IG.Num.Func3d2dBase.Value3 (vec2 parameters) inline virtual
Calculates and returns value of the third component of the current function.
Parameters
parameters Vector of function parameters (in form of the Value) struct.
Returns
Function value.
Implements IG.Num.IFunc3d2d.
Definition at line 313 of file Function3d2d.cs.
References IG.Num.Func3d2dBase.Value3(), IG.Num.vec2.x, and IG.Num.vec2.y.
Gradient1() [1/2]
abstract void IG.Num.Func3d2dBase.Gradient1 (double x, double y, out double gradx, out double grady) pure virtual
Calculates gradient of the first component of the current function and returns its components through the specified output variables.
Parameters
x First parameter.
y Second parameter.
gradx First component of the returned gradient.
grady Second component of the returned gradient.
Implements IG.Num.IFunc3d2d.
Implemented in IG.Num.Func3d2dBaseNoGradient.
Referenced by IG.Num.Func3d2dBase.Gradient1().
Gradient2() [1/2]
abstract void IG.Num.Func3d2dBase.Gradient2 (double x, double y, out double gradx, out double grady) pure virtual
Calculates gradient of the second component of the current function and returns its components through the specified output variables.
Parameters
x First parameter.
y Second parameter.
gradx First component of the returned gradient.
grady Second component of the returned gradient.
Implements IG.Num.IFunc3d2d.
Implemented in IG.Num.Func3d2dBaseNoGradient.
Referenced by IG.Num.Func3d2dBase.Gradient2().
Gradient3() [1/2]
abstract void IG.Num.Func3d2dBase.Gradient3 (double x, double y, out double gradx, out double grady) pure virtual
Calculates gradient of the third component of the current function and returns its components through the specified output variables.
Parameters
x First parameter.
y Second parameter.
gradx First component of the returned gradient.
grady Second component of the returned gradient.
Implements IG.Num.IFunc3d2d.
Implemented in IG.Num.Func3d2dBaseNoGradient.
Referenced by IG.Num.Func3d2dBase.Gradient3().
Gradient1() [2/2]
virtual vec2 IG.Num.Func3d2dBase.Gradient1 (vec2 parameters) inline virtual
Calculates and returns gradient of the first component of the current function.
Parameters
parameters Vector of parameters (in form of the vec2 struct)
<returnreturns>Gradient of the current 2D scalar function (in form of the vec2 struct)</returnreturns>
Implements IG.Num.IFunc3d2d.
Definition at line 345 of file Function3d2d.cs.
References IG.Num.Func3d2dBase.Gradient1(), IG.Num.vec2.x, and IG.Num.vec2.y.
Gradient2() [2/2]
virtual vec2 IG.Num.Func3d2dBase.Gradient2 (vec2 parameters) inline virtual
Calculates and returns gradient of the second component of the current function.
Parameters
parameters Vector of parameters (in form of the vec2 struct)
<returnreturns>Gradient of the current 2D scalar function (in form of the vec2 struct)</returnreturns>
Implements IG.Num.IFunc3d2d.
Definition at line 355 of file Function3d2d.cs.
References IG.Num.Func3d2dBase.Gradient2(), IG.Num.vec2.x, and IG.Num.vec2.y.
Gradient3() [2/2]
virtual vec2 IG.Num.Func3d2dBase.Gradient3 (vec2 parameters) inline virtual
Calculates and returns gradient of the third component of the current function.
Parameters
parameters Vector of parameters (in form of the vec2 struct)
<returnreturns>Gradient of the current 2D scalar function (in form of the vec2 struct)</returnreturns>
Implements IG.Num.IFunc3d2d.
Definition at line 365 of file Function3d2d.cs.
References IG.Num.Func3d2dBase.Gradient3(), IG.Num.vec2.x, and IG.Num.vec2.y.
Hessian1() [1/2]
abstract void IG.Num.Func3d2dBase.Hessian1 (double x, double y, out double dxx, out double dyy, out double dxy) pure virtual
Calculates Hessian of the first component of the current function and returns its component through the specified output variables.
Parameters
x First parameter.
y Second parameter.
dxx Component 1-1 of the calculated Hessian.
dyy Component 2-2 of the calculated Hessian.
dxy Component 1-2 of the calculated Hessian.
Implements IG.Num.IFunc3d2d.
Implemented in IG.Num.Func3d2dBaseNoGradient, and IG.Num.Func3d2dBaseNoHessian.
Referenced by IG.Num.Func3d2dBase.Hessian1().
Hessian2() [1/2]
abstract void IG.Num.Func3d2dBase.Hessian2 (double x, double y, out double dxx, out double dyy, out double dxy) pure virtual
Calculates Hessian of the second component of the current function and returns its component through the specified output variables.
Parameters
x First parameter.
y Second parameter.
dxx Component 1-1 of the calculated Hessian.
dyy Component 2-2 of the calculated Hessian.
dxy Component 1-2 of the calculated Hessian.
Implements IG.Num.IFunc3d2d.
Implemented in IG.Num.Func3d2dBaseNoGradient, and IG.Num.Func3d2dBaseNoHessian.
Referenced by IG.Num.Func3d2dBase.Hessian2().
Hessian3() [1/2]
abstract void IG.Num.Func3d2dBase.Hessian3 (double x, double y, out double dxx, out double dyy, out double dxy) pure virtual
Calculates Hessian of the third component of the current function and returns its component through the specified output variables.
Parameters
x First parameter.
y Second parameter.
dxx Component 1-1 of the calculated Hessian.
dyy Component 2-2 of the calculated Hessian.
dxy Component 1-2 of the calculated Hessian.
Implements IG.Num.IFunc3d2d.
Implemented in IG.Num.Func3d2dBaseNoGradient, and IG.Num.Func3d2dBaseNoHessian.
Referenced by IG.Num.Func3d2dBase.Hessian3().
Hessian1() [2/2]
virtual mat2 IG.Num.Func3d2dBase.Hessian1 (vec2 parameters) inline virtual
Calculates and returns Hessian of the first component of the current function and returns it (in the form of a mat2 struct).
Implements IG.Num.IFunc3d2d.
Definition at line 404 of file Function3d2d.cs.
References IG.Num.Func3d2dBase.Hessian1(), IG.Num.vec2.x, and IG.Num.vec2.y.
Hessian2() [2/2]
virtual mat2 IG.Num.Func3d2dBase.Hessian2 (vec2 parameters) inline virtual
Calculates and returns Hessian of the second component of the current function and returns it (in the form of a mat2 struct).
Implements IG.Num.IFunc3d2d.
Definition at line 416 of file Function3d2d.cs.
References IG.Num.Func3d2dBase.Hessian2(), IG.Num.vec2.x, and IG.Num.vec2.y.
Hessian3() [2/2]
virtual mat2 IG.Num.Func3d2dBase.Hessian3 (vec2 parameters) inline virtual
Calculates and returns Hessian of the third component of the current function and returns it (in the form of a mat2 struct).
Implements IG.Num.IFunc3d2d.
Definition at line 428 of file Function3d2d.cs.
References IG.Num.Func3d2dBase.Hessian3(), IG.Num.vec2.x, and IG.Num.vec2.y.
TestFunction() [1/2]
static void IG.Num.Func3d2dBase.TestFunction (IFunc2d f) inline static protected
Demonstrates use of a 2D function by printing to the console 5 values and gradients of the function on the line connecting the two points (0, 0, 0) and (1, 1, 1).
Parameters
f Function whose values and gradients are evaluated and printed.
Definition at line 637 of file Function3d2d.cs.
Referenced by IG.Num.Func3d2dBase.Example().
TestFunction() [2/2]
static void IG.Num.Func3d2dBase.TestFunction (IFunc2d f, double xmin, double xmax, double ymin, double ymax, int numPoints) inline static protected
Demonstrates use of a 2D function by printing to the console some values and gradients of the function on the line connecting the two specified points.
Parameters
f Function whose values and gradients are evaluated and printed.
xmin Min. x.
xmax Max. x.
ymin Min. y.
ymax Max. y.
numPoints Number of points in which function values and gradients are printed.
Definition at line 655 of file Function3d2d.cs.
References IG.Num.IFunc2d.Gradient(), IG.Num.IFunc2d.GradientDefined, IG.Num.IFunc2d.Value(), and IG.Num.IFunc2d.ValueDefined.
Example()
static void IG.Num.Func3d2dBase.Example () inline static
Example of use of a 2D function.
Definition at line 681 of file Function3d2d.cs.
References IG.Num.Func3d2dBase.TestFunction().
Member Data Documentation
_valueDefined
bool IG.Num.Func3d2dBase._valueDefined = true private
Definition at line 246 of file Function3d2d.cs.
_gradientDefined
bool IG.Num.Func3d2dBase._gradientDefined = false private
Definition at line 256 of file Function3d2d.cs.
_hessianDefined
bool IG.Num.Func3d2dBase._hessianDefined = false private
Definition at line 266 of file Function3d2d.cs.
_comp1
Func2dBase IG.Num.Func3d2dBase._comp1 private
Definition at line 449 of file Function3d2d.cs.
_comp2
Func2dBase IG.Num.Func3d2dBase._comp2 private
Definition at line 449 of file Function3d2d.cs.
_comp3
Func2dBase IG.Num.Func3d2dBase._comp3 private
Definition at line 449 of file Function3d2d.cs.
Property Documentation
ValueDefined
virtual bool IG.Num.Func3d2dBase.ValueDefined get protected set
Whether calculation of function value is defined. Defaulet is true.
Definition at line 251 of file Function3d2d.cs.
GradientDefined
virtual bool IG.Num.Func3d2dBase.GradientDefined get protected set
Whether calculation of functio ngradient is defined. Default is false.
Definition at line 261 of file Function3d2d.cs.
HessianDefined
virtual bool IG.Num.Func3d2dBase.HessianDefined get protected set
Whether calculation of function Hessian is defined. Default is false.
Definition at line 271 of file Function3d2d.cs.
NumParam
int IG.Num.Func3d2dBase.NumParam get
Gets number of parameters.
Definition at line 441 of file Function3d2d.cs.
NumValues
int IG.Num.Func3d2dBase.NumValues get
Gets number of components of the current vector function.
Definition at line 445 of file Function3d2d.cs.
Component1
virtual Func2dBase IG.Num.Func3d2dBase.Component1 get
Returns the scalar function that represents the first component of the current 3D vector function of 2 variables.
Definition at line 452 of file Function3d2d.cs.
Component2
virtual Func2dBase IG.Num.Func3d2dBase.Component2 get
Returns the scalar function that represents the second component of the current 3D vector function of 2 variables.
Definition at line 462 of file Function3d2d.cs.
Component3
virtual Func2dBase IG.Num.Func3d2dBase.Component3 get
Returns the scalar function that represents the third component of the current 3D vector function of 2 variables.
Definition at line 472 of file Function3d2d.cs.
The documentation for this class was generated from the following file:
iglib/igbase/numeric/geometry/Function3d2d.cs