Doc: IGLib with source files: IGLib.Core.Tests.ToStringTypeConverterViaJsonBenchmarkTests Class Reference
IGLib.Core.Tests.ToStringTypeConverterViaJsonBenchmarkTests Class Reference
Benchmark tests for ToStringTypeConverterViaJson (memory size and speed).
Classes
class InitOnlyClass
Used in serialization / deserialization benchmark tests.
class NestedLevel
Public Member Functions
ToStringTypeConverterViaJsonBenchmarkTests (ITestOutputHelper output)
Calling base constructor initializes things like TestBase<TestClass>.Output and TestBase<TestClass>.Output properties that enable writing on tests' output.
void DeeplyNestedObject_ShouldRoundTrip (int numLevels)
void Json_InitOnlyRecord_ShouldRoundTripCorrectly ()
void Json_InitOnlyRecord_Serialize_Performance_And_Size_Benchmark ()
void Json_InitOnlyRecord_Deserialize_Performance_And_Size_Benchmark ()
void Json_InitOnlyClass_ShouldRoundTripCorrectly ()
void Json_InitOnlyClas_Serialize_Performance_And_Size_Benchmark ()
void Json_InitOnlyClas_Deserialize_Performance_And_Size_Benchmark ()
void Json_InitOnlyClas_WithReferenceHandler_Serialize_Performance_And_Size_Benchmark ()
void Json_InitOnlyClas_WithReferenceHandler_Deserialize_Performance_And_Size_Benchmark ()
Public Member Functions inherited from IGLib.Core.Tests.TypeConverterTestsBase< ToStringTypeConverterViaJsonBenchmarkTests >
TypeConverterTestsBase (ITestOutputHelper output)
Calling base constructor initializes things like TestBase<TestClass>.Output and TestBase<TestClass>.Output properties that enable writing on tests' output.
Static Public Attributes
const int DefaultMaxNestingLevels = 64
The default maximum nesting levels of the JSON serialization (the property of .NET JSON serialization).
Protected Member Functions
record InitOnlyRecord (string Name, int Id)
Used in serialization / deserialization benchmark tests.
Protected Member Functions inherited from IGLib.Core.Tests.TypeConverterTestsBase< ToStringTypeConverterViaJsonBenchmarkTests >
void TypeConverter_Speed_ConversionToObjectAndBackTest< OriginalType > (ITypeConverter typeConverter, int numExecutions, double minExecutionsPerSecond, OriginalType original, bool restoreObjectBackToValue=true, bool doOutputInReferenceTest=false)
Like TypeConverter_Speed_ConversionToObjectAndBackTest<OriginalType, TargetType, RestoredType>(ITypeConverter, int, double, OriginalType, TargetType, RestoredType, bool), but with target type and the type of restored variable both equal to type of the original variable, and also the expected assiged object value and the restored value being equal to the original value.
Protected Attributes
readonly ToStringTypeConverterViaJson toJson = new()
readonly FromStringTypeConverterViaJson fromJson = new()
Protected Attributes inherited from IGLib.Core.Tests.TypeConverterTestsBase< ToStringTypeConverterViaJsonBenchmarkTests >
CommonType Coverted
Like TypeConverter_ConversionToObjectAndBackTest<OriginalType, TargetType, RestoredType>(OriginalType, RestoredType), but with target type and the type of restored variable both equal to type of the original variable, and also the expected assigned object value and the expected restored value being equal to the original value.
TargetType Converted
Performs test of conversion via ITypeConverter from a value of type OriginalType to a value of the target type TargetType to be assigned to a variable of type object, and then converts this value to type RestoredType and copies (restores) it to a variable of that type.
Detailed Description
Benchmark tests for ToStringTypeConverterViaJson (memory size and speed).
Definition at line 20 of file ToStringTypeConverterViaJsonBenchmarkTests.cs.
Constructor & Destructor Documentation
ToStringTypeConverterViaJsonBenchmarkTests()
IGLib.Core.Tests.ToStringTypeConverterViaJsonBenchmarkTests.ToStringTypeConverterViaJsonBenchmarkTests (ITestOutputHelper output) inline
Calling base constructor initializes things like TestBase<TestClass>.Output and TestBase<TestClass>.Output properties that enable writing on tests' output.
Parameters
output This parameter will be provided to constructor (injected via constructor) by the test framework. I is also stored to Console property, such that test code can use RoslynScriptingApiExamplesTests.Console.WriteLine(string) method to generate test output.
Definition at line 29 of file ToStringTypeConverterViaJsonBenchmarkTests.cs.
Member Function Documentation
InitOnlyRecord()
record IGLib.Core.Tests.ToStringTypeConverterViaJsonBenchmarkTests.InitOnlyRecord (string Name, int Id) inline protected
Used in serialization / deserialization benchmark tests.
Definition at line 64 of file ToStringTypeConverterViaJsonBenchmarkTests.cs.
Referenced by IGLib.Core.Tests.ToStringTypeConverterViaJsonBenchmarkTests.Json_InitOnlyRecord_Deserialize_Performance_And_Size_Benchmark(), IGLib.Core.Tests.ToStringTypeConverterViaJsonBenchmarkTests.Json_InitOnlyRecord_Serialize_Performance_And_Size_Benchmark(), and IGLib.Core.Tests.ToStringTypeConverterViaJsonBenchmarkTests.Json_InitOnlyRecord_ShouldRoundTripCorrectly().
DeeplyNestedObject_ShouldRoundTrip()
void IGLib.Core.Tests.ToStringTypeConverterViaJsonBenchmarkTests.DeeplyNestedObject_ShouldRoundTrip (int numLevels) inline
Definition at line 99 of file ToStringTypeConverterViaJsonBenchmarkTests.cs.
References IGLib.Core.Tests.ToStringTypeConverterViaJsonBenchmarkTests.NestedLevel.Inner, and IGLib.Core.Tests.ToStringTypeConverterViaJsonBenchmarkTests.NestedLevel.Name.
Json_InitOnlyRecord_ShouldRoundTripCorrectly()
void IGLib.Core.Tests.ToStringTypeConverterViaJsonBenchmarkTests.Json_InitOnlyRecord_ShouldRoundTripCorrectly () inline
Definition at line 127 of file ToStringTypeConverterViaJsonBenchmarkTests.cs.
References IGLib.Core.Tests.ToStringTypeConverterViaJsonBenchmarkTests.InitOnlyRecord().
Json_InitOnlyRecord_Serialize_Performance_And_Size_Benchmark()
void IGLib.Core.Tests.ToStringTypeConverterViaJsonBenchmarkTests.Json_InitOnlyRecord_Serialize_Performance_And_Size_Benchmark () inline
Definition at line 141 of file ToStringTypeConverterViaJsonBenchmarkTests.cs.
References IGLib.Core.Tests.ToStringTypeConverterViaJsonBenchmarkTests.InitOnlyRecord().
Json_InitOnlyRecord_Deserialize_Performance_And_Size_Benchmark()
void IGLib.Core.Tests.ToStringTypeConverterViaJsonBenchmarkTests.Json_InitOnlyRecord_Deserialize_Performance_And_Size_Benchmark () inline
Definition at line 187 of file ToStringTypeConverterViaJsonBenchmarkTests.cs.
References IGLib.Core.Tests.ToStringTypeConverterViaJsonBenchmarkTests.InitOnlyRecord().
Json_InitOnlyClass_ShouldRoundTripCorrectly()
void IGLib.Core.Tests.ToStringTypeConverterViaJsonBenchmarkTests.Json_InitOnlyClass_ShouldRoundTripCorrectly () inline
Definition at line 238 of file ToStringTypeConverterViaJsonBenchmarkTests.cs.
Json_InitOnlyClas_Serialize_Performance_And_Size_Benchmark()
void IGLib.Core.Tests.ToStringTypeConverterViaJsonBenchmarkTests.Json_InitOnlyClas_Serialize_Performance_And_Size_Benchmark () inline
Definition at line 253 of file ToStringTypeConverterViaJsonBenchmarkTests.cs.
Json_InitOnlyClas_Deserialize_Performance_And_Size_Benchmark()
void IGLib.Core.Tests.ToStringTypeConverterViaJsonBenchmarkTests.Json_InitOnlyClas_Deserialize_Performance_And_Size_Benchmark () inline
Definition at line 298 of file ToStringTypeConverterViaJsonBenchmarkTests.cs.
Json_InitOnlyClas_WithReferenceHandler_Serialize_Performance_And_Size_Benchmark()
void IGLib.Core.Tests.ToStringTypeConverterViaJsonBenchmarkTests.Json_InitOnlyClas_WithReferenceHandler_Serialize_Performance_And_Size_Benchmark () inline
Definition at line 349 of file ToStringTypeConverterViaJsonBenchmarkTests.cs.
Json_InitOnlyClas_WithReferenceHandler_Deserialize_Performance_And_Size_Benchmark()
void IGLib.Core.Tests.ToStringTypeConverterViaJsonBenchmarkTests.Json_InitOnlyClas_WithReferenceHandler_Deserialize_Performance_And_Size_Benchmark () inline
Definition at line 400 of file ToStringTypeConverterViaJsonBenchmarkTests.cs.
Member Data Documentation
toJson
readonly ToStringTypeConverterViaJson IGLib.Core.Tests.ToStringTypeConverterViaJsonBenchmarkTests.toJson = new() protected
Definition at line 33 of file ToStringTypeConverterViaJsonBenchmarkTests.cs.
fromJson
readonly FromStringTypeConverterViaJson IGLib.Core.Tests.ToStringTypeConverterViaJsonBenchmarkTests.fromJson = new() protected
Definition at line 34 of file ToStringTypeConverterViaJsonBenchmarkTests.cs.
DefaultMaxNestingLevels
const int IGLib.Core.Tests.ToStringTypeConverterViaJsonBenchmarkTests.DefaultMaxNestingLevels = 64 static
The default maximum nesting levels of the JSON serialization (the property of .NET JSON serialization).
Definition at line 54 of file ToStringTypeConverterViaJsonBenchmarkTests.cs.
The documentation for this class was generated from the following file:
IGLibGraphics3D/tests/IGLib.Graphics3D.Tests/other/TypeConversion/SpecificConverters/ToStringTypeConverterViaJsonBenchmarkTests.cs