Doc: IGLib with source files: IG.Num.FieldCollection< TField, TElement > Class Template Reference
IG.Num.FieldCollection< TField, TElement > Class Template Reference
Collection of fields of the same type. Fields are identified by their names.
Public Member Functions
FieldCollection ()
Constructor.
virtual TField CreateField (int numElements, string name, string description)
Creates a new field of specified length and with specified name and description (the latter two can be null).
string[] GetFieldNames ()
Returns names of all the fields contained in the current field collection.
virtual void AddField (int numElements, string fieldName, string fieldDescription)
Creates a new field of the specified length and adds it to the current collection.
void AddField (TField field, string name)
Adds the specified to the collection under a specified name.
void AddField (TField field)
Adds the specified field to the urrent field collection.
void RemoveField (string fieldName)
Removed the field with the specified name from the current field collection.
Static Public Attributes
const string DefaultFieldNameConst = "default"
Protected Member Functions
void NullifyActiveField ()
Sets the variable holding currently active field to null.
Properties
string DefauletFieldName [get]
Gets name that is used for automatically created fields.
SortedList< string, TField > Fields [get]
string ActiveFieldName [get, set]
Gets or sets name of the active field.
TField ActiveField [get]
Gets the currently active field.
TField this[string fieldName] [get]
Gets the field that has a specified name.
TField this[int index] [get]
Get the field that corresponds to the specified index.
int Count [get]
Gets the number of fields contained in the collection.
Private Attributes
SortedList< string, TField > _fields = new SortedList<string, TField>()
string _activeFieldName
TField _activeField
Detailed Description
Collection of fields of the same type. Fields are identified by their names.
In principle, contained fields can be of different dimensions.
Template Parameters
TField Type of fields contained in the collection.
TElement Type of elements of the fields that can be contained in the collection.
Completely generic definition was introduced in 2009. Before that, several types were used for specific field collections.
$A Igor Apr09;
Type Constraints
TField : Field<TElement>
TField : new()
Definition at line 140 of file FieldCollectionGeneric.cs.
Constructor & Destructor Documentation
FieldCollection()
IG.Num.FieldCollection< TField, TElement >.FieldCollection () inline
Constructor.
Definition at line 151 of file FieldCollectionGeneric.cs.
Member Function Documentation
CreateField()
virtual TField IG.Num.FieldCollection< TField, TElement >.CreateField (int numElements, string name, string description) inline virtual
Creates a new field of specified length and with specified name and description (the latter two can be null).
Parameters
numElements Field length (number of elements).
name Field name (can be null).
description Description of the field (can be null).
Reimplemented in IG.Num.FieldCollection2d< TField, TElement >, and IG.Num.FieldCollection3d< TField, TElement >.
Definition at line 158 of file FieldCollectionGeneric.cs.
Referenced by IG.Num.FieldCollection< TTensorField, TTensor >.AddField().
NullifyActiveField()
void IG.Num.FieldCollection< TField, TElement >.NullifyActiveField () inline protected
Sets the variable holding currently active field to null.
If active field name is specified then active field will still be correctly obtained (lazy evaluation).
Definition at line 214 of file FieldCollectionGeneric.cs.
Referenced by IG.Num.FieldCollection< TTensorField, TTensor >.AddField(), and IG.Num.FieldCollection< TTensorField, TTensor >.RemoveField().
GetFieldNames()
string [] IG.Num.FieldCollection< TField, TElement >.GetFieldNames () inline
Returns names of all the fields contained in the current field collection.
Definition at line 221 of file FieldCollectionGeneric.cs.
AddField() [1/3]
virtual void IG.Num.FieldCollection< TField, TElement >.AddField (int numElements, string fieldName, string fieldDescription) inline virtual
Creates a new field of the specified length and adds it to the current collection.
Parameters
numElements Length of the field that is created and added (number of elements).
fieldName Name of the field. In principle, it should be different tan null.
fieldDescription Optional description of the field. It can be null.
Reimplemented in IG.Num.FieldCollection2d< TField, TElement >, and IG.Num.FieldCollection3d< TField, TElement >.
Definition at line 254 of file FieldCollectionGeneric.cs.
Referenced by IG.Num.FieldCollection< TTensorField, TTensor >.AddField(), IG.Num.UnstructuredMesh1d< vec3, Field< int >, int, Field< double >, double, Field< vec3 >, vec3, Field< mat3 >, mat3 >.AddIndexField(), IG.Num.UnstructuredMesh3d< TCoord, TIndexField, TIndex, TScalarField, TScalar, TVectorField, TVector, TTensorField, TTensor >.AddIndexField(), IG.Num.UnstructuredMesh2d< TCoord, TIndexField, TIndex, TScalarField, TScalar, TVectorField, TVector, TTensorField, TTensor >.AddIndexField(), IG.Num.UnstructuredMesh3d< TCoord, TIndexField, TIndex, TScalarField, TScalar, TVectorField, TVector, TTensorField, TTensor >.AddScalarField(), IG.Num.UnstructuredMesh1d< vec3, Field< int >, int, Field< double >, double, Field< vec3 >, vec3, Field< mat3 >, mat3 >.AddScalarField(), IG.Num.UnstructuredMesh2d< TCoord, TIndexField, TIndex, TScalarField, TScalar, TVectorField, TVector, TTensorField, TTensor >.AddScalarField(), IG.Num.UnstructuredMesh2d< TCoord, TIndexField, TIndex, TScalarField, TScalar, TVectorField, TVector, TTensorField, TTensor >.AddTensorField(), IG.Num.UnstructuredMesh3d< TCoord, TIndexField, TIndex, TScalarField, TScalar, TVectorField, TVector, TTensorField, TTensor >.AddTensorField(), IG.Num.UnstructuredMesh1d< vec3, Field< int >, int, Field< double >, double, Field< vec3 >, vec3, Field< mat3 >, mat3 >.AddTensorField(), IG.Num.UnstructuredMesh2d< TCoord, TIndexField, TIndex, TScalarField, TScalar, TVectorField, TVector, TTensorField, TTensor >.AddVectorField(), IG.Num.UnstructuredMesh3d< TCoord, TIndexField, TIndex, TScalarField, TScalar, TVectorField, TVector, TTensorField, TTensor >.AddVectorField(), and IG.Num.UnstructuredMesh1d< vec3, Field< int >, int, Field< double >, double, Field< vec3 >, vec3, Field< mat3 >, mat3 >.AddVectorField().
AddField() [2/3]
void IG.Num.FieldCollection< TField, TElement >.AddField (TField field, string name) inline
Adds the specified to the collection under a specified name.
If the field already has a name then its name is replaced by the specified name, unlsee the specified name is null.
Parameters
field Field to be added to the collection.
name Name under which the field is added to the current collection.
Definition at line 264 of file FieldCollectionGeneric.cs.
AddField() [3/3]
void IG.Num.FieldCollection< TField, TElement >.AddField (TField field) inline
Adds the specified field to the urrent field collection.
Parameters
field Field to be added.
Definition at line 275 of file FieldCollectionGeneric.cs.
RemoveField()
void IG.Num.FieldCollection< TField, TElement >.RemoveField (string fieldName) inline
Removed the field with the specified name from the current field collection.
Parameters
fieldName Name of the field to be removed.
Definition at line 291 of file FieldCollectionGeneric.cs.
Referenced by IG.Num.UnstructuredMesh1d< vec3, Field< int >, int, Field< double >, double, Field< vec3 >, vec3, Field< mat3 >, mat3 >.RemoveIndexField(), IG.Num.UnstructuredMesh2d< TCoord, TIndexField, TIndex, TScalarField, TScalar, TVectorField, TVector, TTensorField, TTensor >.RemoveIndexField(), IG.Num.UnstructuredMesh3d< TCoord, TIndexField, TIndex, TScalarField, TScalar, TVectorField, TVector, TTensorField, TTensor >.RemoveIndexField(), IG.Num.UnstructuredMesh3d< TCoord, TIndexField, TIndex, TScalarField, TScalar, TVectorField, TVector, TTensorField, TTensor >.RemoveScalarField(), IG.Num.UnstructuredMesh2d< TCoord, TIndexField, TIndex, TScalarField, TScalar, TVectorField, TVector, TTensorField, TTensor >.RemoveScalarField(), IG.Num.UnstructuredMesh1d< vec3, Field< int >, int, Field< double >, double, Field< vec3 >, vec3, Field< mat3 >, mat3 >.RemoveScalarField(), IG.Num.UnstructuredMesh2d< TCoord, TIndexField, TIndex, TScalarField, TScalar, TVectorField, TVector, TTensorField, TTensor >.RemoveTensorField(), IG.Num.UnstructuredMesh3d< TCoord, TIndexField, TIndex, TScalarField, TScalar, TVectorField, TVector, TTensorField, TTensor >.RemoveTensorField(), IG.Num.UnstructuredMesh1d< vec3, Field< int >, int, Field< double >, double, Field< vec3 >, vec3, Field< mat3 >, mat3 >.RemoveTensorField(), IG.Num.UnstructuredMesh2d< TCoord, TIndexField, TIndex, TScalarField, TScalar, TVectorField, TVector, TTensorField, TTensor >.RemoveVectorField(), IG.Num.UnstructuredMesh3d< TCoord, TIndexField, TIndex, TScalarField, TScalar, TVectorField, TVector, TTensorField, TTensor >.RemoveVectorField(), and IG.Num.UnstructuredMesh1d< vec3, Field< int >, int, Field< double >, double, Field< vec3 >, vec3, Field< mat3 >, mat3 >.RemoveVectorField().
Member Data Documentation
DefaultFieldNameConst
const string IG.Num.FieldCollection< TField, TElement >.DefaultFieldNameConst = "default" static
Definition at line 144 of file FieldCollectionGeneric.cs.
_fields
SortedList<string, TField> IG.Num.FieldCollection< TField, TElement >._fields = new SortedList<string, TField>() private
Definition at line 170 of file FieldCollectionGeneric.cs.
Referenced by IG.Num.FieldCollection< TTensorField, TTensor >.AddField(), IG.Num.FieldCollection< TTensorField, TTensor >.GetFieldNames(), and IG.Num.FieldCollection< TTensorField, TTensor >.RemoveField().
_activeFieldName
string IG.Num.FieldCollection< TField, TElement >._activeFieldName private
Definition at line 177 of file FieldCollectionGeneric.cs.
Referenced by IG.Num.FieldCollection< TTensorField, TTensor >.AddField(), and IG.Num.FieldCollection< TTensorField, TTensor >.RemoveField().
_activeField
TField IG.Num.FieldCollection< TField, TElement >._activeField private
Definition at line 195 of file FieldCollectionGeneric.cs.
Referenced by IG.Num.FieldCollection< TTensorField, TTensor >.NullifyActiveField().
Property Documentation
DefauletFieldName
string IG.Num.FieldCollection< TField, TElement >.DefauletFieldName get
Gets name that is used for automatically created fields.
Definition at line 148 of file FieldCollectionGeneric.cs.
Fields
SortedList<string, TField> IG.Num.FieldCollection< TField, TElement >.Fields get protected
Definition at line 173 of file FieldCollectionGeneric.cs.
ActiveFieldName
string IG.Num.FieldCollection< TField, TElement >.ActiveFieldName get set
Gets or sets name of the active field.
Active field will be accessed throughthe ActiveField property. When setting name of the active field, that property is not assigned, but it gets assigned on the first get access.
Definition at line 184 of file FieldCollectionGeneric.cs.
Referenced by IG.Num.FieldCollection< TTensorField, TTensor >.AddField().
ActiveField
TField IG.Num.FieldCollection< TField, TElement >.ActiveField get
Gets the currently active field.
Definition at line 199 of file FieldCollectionGeneric.cs.
this[string fieldName]
TField IG.Num.FieldCollection< TField, TElement >.this[string fieldName] get
Gets the field that has a specified name.
Parameters
fieldName Name of the field to be returned.
Definition at line 229 of file FieldCollectionGeneric.cs.
this[int index]
TField IG.Num.FieldCollection< TField, TElement >.this[int index] get
Get the field that corresponds to the specified index.
This is seldom used, usually fields will be accessed through field names.
Warning: when adding fields, index of a field may change, therefore this kind of access should only be used wen there is no adding or removing of fields.
Parameters
index Index of the field.
Definition at line 239 of file FieldCollectionGeneric.cs.
Count
int IG.Num.FieldCollection< TField, TElement >.Count get
Gets the number of fields contained in the collection.
Definition at line 245 of file FieldCollectionGeneric.cs.
The documentation for this class was generated from the following file:
iglib/igbase/numeric/geometry/meshing/FieldCollectionGeneric.cs