Doc: IGLib with source files: IGLib.Core.SingleSourceTypeConverterBase< TSource > Class Template Reference
IGLib.Core.SingleSourceTypeConverterBase< TSource > Class Template Reference abstract
Public Member Functions
abstract object Convert (object source, Type targetType)
bool TryConvert (object source, out object target, Type TargetType)
abstract TTarget ConvertTyped< TTarget > (TSource source)
virtual bool TryConvertTyped< TTarget > (TSource source, out TTarget target)
Public Member Functions inherited from IGLib.Core.ISingleSourceTypeConverter< TSource >
TargetType ConvertTyped< TargetType > (SourceType source)
bool TryConvertTyped< TargetType > (SourceType source, out TargetType target)
object Convert (object source, Type targetType)
bool TryConvert (object source, out object target, Type targetType)
Properties
Type SourceType = typeof(TSource) [get]
Properties inherited from IGLib.Core.ISingleSourceTypeConverter< TSource >
Type SourceType [get]
Detailed Description
Definition at line 7 of file SingleSourceTypeConverterBaseGeneric.cs.
Member Function Documentation
Convert()
abstract object IGLib.Core.SingleSourceTypeConverterBase< TSource >.Convert (object source, Type targetType) pure virtual
Referenced by IGLib.Core.SingleSourceTypeConverterBase< TSource >.TryConvert().
TryConvert()
bool IGLib.Core.SingleSourceTypeConverterBase< TSource >.TryConvert (object source, out object target, Type TargetType) inline
Definition at line 14 of file SingleSourceTypeConverterBaseGeneric.cs.
References IGLib.Core.SingleSourceTypeConverterBase< TSource >.Convert().
ConvertTyped< TTarget >()
abstract TTarget IGLib.Core.SingleSourceTypeConverterBase< TSource >.ConvertTyped< TTarget > (TSource source) pure virtual
Referenced by IGLib.Core.SingleSourceTypeConverterBase< TSource >.TryConvertTyped< TTarget >().
TryConvertTyped< TTarget >()
virtual bool IGLib.Core.SingleSourceTypeConverterBase< TSource >.TryConvertTyped< TTarget > (TSource source, out TTarget target) inline virtual
Definition at line 30 of file SingleSourceTypeConverterBaseGeneric.cs.
References IGLib.Core.SingleSourceTypeConverterBase< TSource >.ConvertTyped< TTarget >().
Property Documentation
SourceType
Type IGLib.Core.SingleSourceTypeConverterBase< TSource >.SourceType = typeof(TSource) get
Definition at line 10 of file SingleSourceTypeConverterBaseGeneric.cs.
The documentation for this class was generated from the following file:
IGLibGraphics3D/src/IGLib.Graphics3D/other/TypeConversion/SingleConverters/SingleSourceTypeConverterBaseGeneric.cs