Doc: IGLib with source files: IG.Num.Func3d2dExamples.ParametricSurface Class Reference
IG.Num.Func3d2dExamples.ParametricSurface Class Reference abstract
Base class for easy definition of parametric surfaces intended for plotting.
Public Member Functions
void SetBounds (double minX, double maxX, double minY, double maxY)
Sets the bounds.
void SetNumPoints (int numX, int numY)
Sets recommended number of plot points along parameter curves.
override double Value1 (double x, double y)
Calculates and returns value of the first component of the current function.
override double Value2 (double x, double y)
Calculates and returns value of the second component of the current function.
override double Value3 (double x, double y)
Calculates and returns value of the third component of the current function.
Public Member Functions inherited from IG.Num.Func3d2dBaseNoGradient
override void Gradient1 (double x, double y, out double gradx, out double grady)
Function for calculating gradient of the first component of vector function, just throws the NotImplementedException exception.
override void Gradient2 (double x, double y, out double gradx, out double grady)
Function for calculating gradient of the second component of vector function, just throws the NotImplementedException exception.
override void Gradient3 (double x, double y, out double gradx, out double grady)
Function for calculating gradient of the third component of vector function, just throws the NotImplementedException exception.
override void Hessian1 (double x, double y, out double dxx, out double dyy, out double dxy)
Function for calculating Hessian of the first component, just throws the NotImplementedException exception.
override void Hessian2 (double x, double y, out double dxx, out double dyy, out double dxy)
Function for calculating Hessian of the second component, just throws the NotImplementedException exception.
override void Hessian3 (double x, double y, out double dxx, out double dyy, out double dxy)
Function for calculating Hessian of the third component, just throws the NotImplementedException exception.
Public Member Functions inherited from IG.Num.Func3d2dBase
virtual double Value1 (vec2 parameters)
Calculates and returns value of the first component of the current function.
virtual double Value2 (vec2 parameters)
Calculates and returns value of the second component of the current function.
virtual double Value3 (vec2 parameters)
Calculates and returns value of the third component of the current function.
virtual vec2 Gradient1 (vec2 parameters)
Calculates and returns gradient of the first component of the current function.
virtual vec2 Gradient2 (vec2 parameters)
Calculates and returns gradient of the second component of the current function.
virtual vec2 Gradient3 (vec2 parameters)
Calculates and returns gradient of the third component of the current function.
virtual mat2 Hessian1 (vec2 parameters)
Calculates and returns Hessian of the first component of the current function and returns it (in the form of a mat2 struct).
virtual mat2 Hessian2 (vec2 parameters)
Calculates and returns Hessian of the second component of the current function and returns it (in the form of a mat2 struct).
virtual mat2 Hessian3 (vec2 parameters)
Calculates and returns Hessian of the third component of the current function and returns it (in the form of a mat2 struct).
Protected Member Functions
ParametricSurface ()
Base class for classes that define various parametric surfaces.
ParametricSurface (double minX, double maxX, double minY, double maxY)
Base class for classes that define various parametric surfaces.
abstract double f1 (double u, double v)
abstract double f2 (double u, double v)
abstract double f3 (double u, double v)
Protected Member Functions inherited from IG.Num.Func3d2dBaseNoGradient
Func3d2dBaseNoGradient ()
Protected Member Functions inherited from IG.Num.Func3d2dBase
Func3d2dBase ()
Properties
double MinX [get, set]
Minimal value of the first parameter.
double MaxX [get, set]
Maximal value of the first parameter.
double MinY [get, set]
Minimal value of the second parameter.
double MaxY [get, set]
Maximal value of the second parameter.
int NumX [get, set]
Recommended number of points along the first parameter used to plot the surface.
int NumY [get, set]
Recommended number of points along the second parameter used to plot the surface.
Properties inherited from IG.Num.Func3d2dBase
virtual bool ValueDefined [get, protected set]
Whether calculation of function value is defined. Defaulet is true.
virtual bool GradientDefined [get, protected set]
Whether calculation of functio ngradient is defined. Default is false.
virtual bool HessianDefined [get, protected set]
Whether calculation of function Hessian is defined. Default is false.
int NumParam [get]
Gets number of parameters.
int NumValues [get]
Gets number of components of the current vector function.
virtual Func2dBase Component1 [get]
Returns the scalar function that represents the first component of the current 3D vector function of 2 variables.
virtual Func2dBase Component2 [get]
Returns the scalar function that represents the second component of the current 3D vector function of 2 variables.
virtual Func2dBase Component3 [get]
Returns the scalar function that represents the third component of the current 3D vector function of 2 variables.
Properties inherited from IG.Num.IFunc3d2d
bool ValueDefined [get]
Whether calculation of function value is defined.
bool GradientDefined [get]
Whether calculation of function ngradient is defined.
bool HessianDefined [get]
Whether calculation of function Hessian is defined.
Func2dBase Component1 [get]
Returns the scalar function that represents the first component of the current 3D vector function of 2 variables.
Func2dBase Component2 [get]
Returns the scalar function that represents the second component of the current 3D vector function of 2 variables.
Func2dBase Component3 [get]
Returns the scalar function that represents the third component of the current 3D vector function of 2 variables.
Private Attributes
double _minX = -1
double _maxX = 1
double _minY = -1
double _maxY = 1
int _numx = 20
int _numy = 20
Additional Inherited Members
Static Public Member Functions inherited from IG.Num.Func3d2dBase
static void Example ()
Example of use of a 2D function.
Static Protected Member Functions inherited from IG.Num.Func3d2dBase
static void TestFunction (IFunc2d f)
Demonstrates use of a 2D function by printing to the console 5 values and gradients of the function on the line connecting the two points (0, 0, 0) and (1, 1, 1).
static void TestFunction (IFunc2d f, double xmin, double xmax, double ymin, double ymax, int numPoints)
Demonstrates use of a 2D function by printing to the console some values and gradients of the function on the line connecting the two specified points.
Detailed Description
Base class for easy definition of parametric surfaces intended for plotting.
$A Igor Oct09;
Definition at line 708 of file Function3d2d.cs.
Constructor & Destructor Documentation
ParametricSurface() [1/2]
IG.Num.Func3d2dExamples.ParametricSurface.ParametricSurface () inline protected
Base class for classes that define various parametric surfaces.
Definition at line 712 of file Function3d2d.cs.
ParametricSurface() [2/2]
IG.Num.Func3d2dExamples.ParametricSurface.ParametricSurface (double minX, double maxX, double minY, double maxY) inline protected
Base class for classes that define various parametric surfaces.
Definition at line 716 of file Function3d2d.cs.
References IG.Num.Func3d2dExamples.ParametricSurface.MaxX, IG.Num.Func3d2dExamples.ParametricSurface.MaxY, IG.Num.Func3d2dExamples.ParametricSurface.MinX, and IG.Num.Func3d2dExamples.ParametricSurface.MinY.
Member Function Documentation
SetBounds()
void IG.Num.Func3d2dExamples.ParametricSurface.SetBounds (double minX, double maxX, double minY, double maxY) inline
Sets the bounds.
Parameters
minX Lower bound of the first parameter.
maxX Upper bound of the first parameter.
minY Lower bound of the first parameter.
maxY Upper bound of the second parameter.
Definition at line 756 of file Function3d2d.cs.
References IG.Num.Func3d2dExamples.ParametricSurface.MaxX, IG.Num.Func3d2dExamples.ParametricSurface.MaxY, IG.Num.Func3d2dExamples.ParametricSurface.MinX, and IG.Num.Func3d2dExamples.ParametricSurface.MinY.
Referenced by IG.Num.Func3d2dExamples.EnneperSurface.EnneperSurface(), IG.Num.Func3d2dExamples.KleinBottle.KleinBottle(), IG.Num.Func3d2dExamples.KleinBottle1.KleinBottle1(), IG.Num.Func3d2dExamples.KleinBottle2.KleinBottle2(), IG.Num.Func3d2dExamples.MobiusStrip.MobiusStrip(), IG.Num.Func3d2dExamples.SnailConicSpiral_ToCheck.SnailConicSpiral_ToCheck(), IG.Num.Func3d2dExamples.SnailShell1Streched.SnailShell1Streched(), IG.Num.Func3d2dExamples.Torus.Torus(), IG.Num.Func3d2dExamples.TorusHorizontal.TorusHorizontal(), and IG.Num.Func3d2dExamples.UmbilicTorus.UmbilicTorus().
SetNumPoints()
void IG.Num.Func3d2dExamples.ParametricSurface.SetNumPoints (int numX, int numY) inline
Sets recommended number of plot points along parameter curves.
Parameters
numX Recommended number of plot points alog the first parameter.
numY Recommended number of plot points alog the second parameter.
Definition at line 765 of file Function3d2d.cs.
References IG.Num.Func3d2dExamples.ParametricSurface.NumX, and IG.Num.Func3d2dExamples.ParametricSurface.NumY.
Referenced by IG.Num.Func3d2dExamples.EnneperSurface.EnneperSurface(), IG.Num.Func3d2dExamples.KleinBottle.KleinBottle(), IG.Num.Func3d2dExamples.KleinBottle1.KleinBottle1(), IG.Num.Func3d2dExamples.KleinBottle2.KleinBottle2(), IG.Num.Func3d2dExamples.MobiusStrip.MobiusStrip(), IG.Num.Func3d2dExamples.SnailConicSpiral_ToCheck.SnailConicSpiral_ToCheck(), IG.Num.Func3d2dExamples.SnailShell1Streched.SnailShell1Streched(), IG.Num.Func3d2dExamples.Torus.Torus(), IG.Num.Func3d2dExamples.TorusHorizontal.TorusHorizontal(), and IG.Num.Func3d2dExamples.UmbilicTorus.UmbilicTorus().
f1()
abstract double IG.Num.Func3d2dExamples.ParametricSurface.f1 (double u, double v) protected pure virtual
Implemented in IG.Num.Func3d2dExamples.SnailShell1Streched, IG.Num.Func3d2dExamples.SnailShell1, IG.Num.Func3d2dExamples.SnailConicSpiral_ToCheck, IG.Num.Func3d2dExamples.KleinBottle2, IG.Num.Func3d2dExamples.KleinBottle1, IG.Num.Func3d2dExamples.KleinBottle, IG.Num.Func3d2dExamples.UmbilicTorus, IG.Num.Func3d2dExamples.EnneperSurface, IG.Num.Func3d2dExamples.TorusVertical, IG.Num.Func3d2dExamples.TorusHorizontal, IG.Num.Func3d2dExamples.Torus, IG.Num.Func3d2dExamples.HyperboloidParametricMinus, IG.Num.Func3d2dExamples.HyperboloidParametricPlus, IG.Num.Func3d2dExamples.HyperboloidParametric2, IG.Num.Func3d2dExamples.HyperboloidParametric, IG.Num.Func3d2dExamples.HyperboloidTwosheetedLowerParametric, IG.Num.Func3d2dExamples.HyperboloidTwosheetedUpperParametric, IG.Num.Func3d2dExamples.EllipsoidParametric, IG.Num.Func3d2dExamples.CylinderParametric, IG.Num.Func3d2dExamples.Surface, and IG.Num.Func3d2dExamples.MobiusStrip.
Referenced by IG.Num.Func3d2dExamples.ParametricSurface.Value1().
f2()
abstract double IG.Num.Func3d2dExamples.ParametricSurface.f2 (double u, double v) protected pure virtual
Implemented in IG.Num.Func3d2dExamples.SnailShell1Streched, IG.Num.Func3d2dExamples.SnailShell1, IG.Num.Func3d2dExamples.SnailConicSpiral_ToCheck, IG.Num.Func3d2dExamples.KleinBottle2, IG.Num.Func3d2dExamples.KleinBottle1, IG.Num.Func3d2dExamples.KleinBottle, IG.Num.Func3d2dExamples.UmbilicTorus, IG.Num.Func3d2dExamples.EnneperSurface, IG.Num.Func3d2dExamples.TorusVertical, IG.Num.Func3d2dExamples.TorusHorizontal, IG.Num.Func3d2dExamples.Torus, IG.Num.Func3d2dExamples.HyperboloidParametricMinus, IG.Num.Func3d2dExamples.HyperboloidParametricPlus, IG.Num.Func3d2dExamples.HyperboloidParametric2, IG.Num.Func3d2dExamples.HyperboloidParametric, IG.Num.Func3d2dExamples.HyperboloidTwosheetedLowerParametric, IG.Num.Func3d2dExamples.HyperboloidTwosheetedUpperParametric, IG.Num.Func3d2dExamples.EllipsoidParametric, IG.Num.Func3d2dExamples.CylinderParametric, IG.Num.Func3d2dExamples.Surface, and IG.Num.Func3d2dExamples.MobiusStrip.
Referenced by IG.Num.Func3d2dExamples.ParametricSurface.Value2().
f3()
abstract double IG.Num.Func3d2dExamples.ParametricSurface.f3 (double u, double v) protected pure virtual
Implemented in IG.Num.Func3d2dExamples.Paraboloid, IG.Num.Func3d2dExamples.HyperbolicParaboloid, IG.Num.Func3d2dExamples.SaddleXY, IG.Num.Func3d2dExamples.SnailShell1Streched, IG.Num.Func3d2dExamples.SnailShell1, IG.Num.Func3d2dExamples.SnailConicSpiral_ToCheck, IG.Num.Func3d2dExamples.KleinBottle2, IG.Num.Func3d2dExamples.KleinBottle1, IG.Num.Func3d2dExamples.KleinBottle, IG.Num.Func3d2dExamples.UmbilicTorus, IG.Num.Func3d2dExamples.EnneperSurface, IG.Num.Func3d2dExamples.TorusVertical, IG.Num.Func3d2dExamples.TorusHorizontal, IG.Num.Func3d2dExamples.Torus, IG.Num.Func3d2dExamples.HyperboloidParametricMinus, IG.Num.Func3d2dExamples.HyperboloidParametricPlus, IG.Num.Func3d2dExamples.HyperboloidParametric2, IG.Num.Func3d2dExamples.HyperboloidParametric, IG.Num.Func3d2dExamples.HyperboloidTwosheetedLowerParametric, IG.Num.Func3d2dExamples.HyperboloidTwosheetedUpperParametric, IG.Num.Func3d2dExamples.EllipsoidParametric, IG.Num.Func3d2dExamples.CylinderParametric, and IG.Num.Func3d2dExamples.MobiusStrip.
Referenced by IG.Num.Func3d2dExamples.ParametricSurface.Value3().
Value1()
override double IG.Num.Func3d2dExamples.ParametricSurface.Value1 (double x, double y) inline
Calculates and returns value of the first component of the current function.
Parameters
x First parameter.
y Second parameter.
Implements IG.Num.IFunc3d2d.
Definition at line 777 of file Function3d2d.cs.
References IG.Num.Func3d2dExamples.ParametricSurface.f1().
Value2()
override double IG.Num.Func3d2dExamples.ParametricSurface.Value2 (double x, double y) inline
Calculates and returns value of the second component of the current function.
Parameters
x First parameter.
y Second parameter.
Implements IG.Num.IFunc3d2d.
Definition at line 785 of file Function3d2d.cs.
References IG.Num.Func3d2dExamples.ParametricSurface.f2().
Value3()
override double IG.Num.Func3d2dExamples.ParametricSurface.Value3 (double x, double y) inline
Calculates and returns value of the third component of the current function.
Parameters
x First parameter.
y Second parameter.
Implements IG.Num.IFunc3d2d.
Definition at line 793 of file Function3d2d.cs.
References IG.Num.Func3d2dExamples.ParametricSurface.f3().
Member Data Documentation
_minX
double IG.Num.Func3d2dExamples.ParametricSurface._minX = -1 private
Definition at line 724 of file Function3d2d.cs.
_maxX
double IG.Num.Func3d2dExamples.ParametricSurface._maxX = 1 private
Definition at line 724 of file Function3d2d.cs.
_minY
double IG.Num.Func3d2dExamples.ParametricSurface._minY = -1 private
Definition at line 724 of file Function3d2d.cs.
_maxY
double IG.Num.Func3d2dExamples.ParametricSurface._maxY = 1 private
Definition at line 724 of file Function3d2d.cs.
_numx
int IG.Num.Func3d2dExamples.ParametricSurface._numx = 20 private
Definition at line 725 of file Function3d2d.cs.
_numy
int IG.Num.Func3d2dExamples.ParametricSurface._numy = 20 private
Definition at line 725 of file Function3d2d.cs.
Property Documentation
MinX
double IG.Num.Func3d2dExamples.ParametricSurface.MinX get set
Minimal value of the first parameter.
Definition at line 729 of file Function3d2d.cs.
Referenced by IG.Num.Func3d2dExamples.CylinderParametric.CylinderParametric(), IG.Num.Func3d2dExamples.EllipsoidParametric.EllipsoidParametric(), IG.Num.Func3d2dExamples.HyperboloidParametric.HyperboloidParametric(), IG.Num.Func3d2dExamples.HyperboloidParametric2.HyperboloidParametric2(), IG.Num.Func3d2dExamples.HyperboloidParametricMinus.HyperboloidParametricMinus(), IG.Num.Func3d2dExamples.HyperboloidParametricPlus.HyperboloidParametricPlus(), IG.Num.Func3d2dExamples.HyperboloidTwosheetedLowerParametric.HyperboloidTwosheetedLowerParametric(), IG.Num.Func3d2dExamples.HyperboloidTwosheetedUpperParametric.HyperboloidTwosheetedUpperParametric(), IG.Num.Func3d2dExamples.ParametricSurface.ParametricSurface(), IG.Num.Func3d2dExamples.ParametricSurface.SetBounds(), and IG.Num.Func3d2dExamples.SnailShell1.SnailShell1().
MaxX
double IG.Num.Func3d2dExamples.ParametricSurface.MaxX get set
Maximal value of the first parameter.
Definition at line 733 of file Function3d2d.cs.
Referenced by IG.Num.Func3d2dExamples.CylinderParametric.CylinderParametric(), IG.Num.Func3d2dExamples.EllipsoidParametric.EllipsoidParametric(), IG.Num.Func3d2dExamples.HyperboloidParametric.HyperboloidParametric(), IG.Num.Func3d2dExamples.HyperboloidParametric2.HyperboloidParametric2(), IG.Num.Func3d2dExamples.HyperboloidParametricMinus.HyperboloidParametricMinus(), IG.Num.Func3d2dExamples.HyperboloidParametricPlus.HyperboloidParametricPlus(), IG.Num.Func3d2dExamples.HyperboloidTwosheetedLowerParametric.HyperboloidTwosheetedLowerParametric(), IG.Num.Func3d2dExamples.HyperboloidTwosheetedUpperParametric.HyperboloidTwosheetedUpperParametric(), IG.Num.Func3d2dExamples.ParametricSurface.ParametricSurface(), IG.Num.Func3d2dExamples.ParametricSurface.SetBounds(), and IG.Num.Func3d2dExamples.SnailShell1.SnailShell1().
MinY
double IG.Num.Func3d2dExamples.ParametricSurface.MinY get set
Minimal value of the second parameter.
Definition at line 737 of file Function3d2d.cs.
Referenced by IG.Num.Func3d2dExamples.CylinderParametric.CylinderParametric(), IG.Num.Func3d2dExamples.EllipsoidParametric.EllipsoidParametric(), IG.Num.Func3d2dExamples.HyperboloidParametric.HyperboloidParametric(), IG.Num.Func3d2dExamples.HyperboloidParametric2.HyperboloidParametric2(), IG.Num.Func3d2dExamples.HyperboloidParametricMinus.HyperboloidParametricMinus(), IG.Num.Func3d2dExamples.HyperboloidParametricPlus.HyperboloidParametricPlus(), IG.Num.Func3d2dExamples.HyperboloidTwosheetedLowerParametric.HyperboloidTwosheetedLowerParametric(), IG.Num.Func3d2dExamples.HyperboloidTwosheetedUpperParametric.HyperboloidTwosheetedUpperParametric(), IG.Num.Func3d2dExamples.ParametricSurface.ParametricSurface(), IG.Num.Func3d2dExamples.ParametricSurface.SetBounds(), and IG.Num.Func3d2dExamples.SnailShell1.SnailShell1().
MaxY
double IG.Num.Func3d2dExamples.ParametricSurface.MaxY get set
Maximal value of the second parameter.
Definition at line 741 of file Function3d2d.cs.
Referenced by IG.Num.Func3d2dExamples.CylinderParametric.CylinderParametric(), IG.Num.Func3d2dExamples.EllipsoidParametric.EllipsoidParametric(), IG.Num.Func3d2dExamples.HyperboloidParametric.HyperboloidParametric(), IG.Num.Func3d2dExamples.HyperboloidParametric2.HyperboloidParametric2(), IG.Num.Func3d2dExamples.HyperboloidParametricMinus.HyperboloidParametricMinus(), IG.Num.Func3d2dExamples.HyperboloidParametricPlus.HyperboloidParametricPlus(), IG.Num.Func3d2dExamples.HyperboloidTwosheetedLowerParametric.HyperboloidTwosheetedLowerParametric(), IG.Num.Func3d2dExamples.HyperboloidTwosheetedUpperParametric.HyperboloidTwosheetedUpperParametric(), IG.Num.Func3d2dExamples.ParametricSurface.ParametricSurface(), IG.Num.Func3d2dExamples.ParametricSurface.SetBounds(), and IG.Num.Func3d2dExamples.SnailShell1.SnailShell1().
NumX
int IG.Num.Func3d2dExamples.ParametricSurface.NumX get set
Recommended number of points along the first parameter used to plot the surface.
Definition at line 745 of file Function3d2d.cs.
Referenced by IG.Num.Func3d2dExamples.ParametricSurface.SetNumPoints(), and IG.Num.Func3d2dExamples.SnailShell1.SnailShell1().
NumY
int IG.Num.Func3d2dExamples.ParametricSurface.NumY get set
Recommended number of points along the second parameter used to plot the surface.
Definition at line 749 of file Function3d2d.cs.
Referenced by IG.Num.Func3d2dExamples.ParametricSurface.SetNumPoints(), and IG.Num.Func3d2dExamples.SnailShell1.SnailShell1().
The documentation for this class was generated from the following file:
iglib/igbase/numeric/geometry/Function3d2d.cs