Doc: IGLib with source files: IG.Neural.DataMapperSimple Class Reference
IG.Neural.DataMapperSimple Class Reference
Public Member Functions
DataMapperSimple (MappingDefinition definition, InputOutputDataDefiniton dataDefinition)
DataMapperSimple (string mappingDefinitionFilePath, string dataDefinitionPath)
override void MapInput (IVector reducedInput, ref IVector originalInput)
Transfer elements from reducedInput vector to original output vector using mapping data for reference. Elements that are not defined in reducedInput vector are copied from definitiondata.
override void MapOutput (IVector originalOutput, ref IVector reducedOutput)
Transfer elements from originalOutput vector to original output vector using mapping data for reference. Only defined elements are copied in reducedOutput vector.
Public Member Functions inherited from IG.Neural.DataMapperIdentity
DataMapperIdentity ()
Protected Member Functions
DataMapperSimple ()
Properties
MappingDefinition MappingDefinition [get, protected set]
InputOutputDataDefiniton DataDefinition [get, protected set]
Private Attributes
MappingDefinition _mappingDefinition
InputOutputDataDefiniton _dataDefinition
Detailed Description
Definition at line 987 of file NeuralMapData.cs.
Constructor & Destructor Documentation
DataMapperSimple() [1/3]
IG.Neural.DataMapperSimple.DataMapperSimple () inline protected
Definition at line 990 of file NeuralMapData.cs.
References IG.Neural.DataMapperSimple.DataDefinition.
DataMapperSimple() [2/3]
IG.Neural.DataMapperSimple.DataMapperSimple (MappingDefinition definition, InputOutputDataDefiniton dataDefinition) inline
Parameters
definition Data that defines how input and output mappings are performed. If null then identity mapping is performed.
dataDefinition Definition data.
$A Igor Jul 19; tako78 Jul 19
Definition at line 1005 of file NeuralMapData.cs.
References IG.Neural.DataMapperSimple.DataDefinition.
DataMapperSimple() [3/3]
IG.Neural.DataMapperSimple.DataMapperSimple (string mappingDefinitionFilePath, string dataDefinitionPath) inline
Parameters
mappingDefinitionFilePath JSON file containing data that defines how input and output mappings are performed. If null then identity mapping is performed.
dataDefinitionPath JSON file containing data definitions.
Exceptions
NotImplementedException When file path is not specified or file does not exist.
$A Igor Jul 19; tako78 Jul 19
Definition at line 1021 of file NeuralMapData.cs.
References IG.Neural.DataMapperSimple.DataDefinition, IG.Neural.MappingDefinition.LoadJson(), and IG.Num.InputOutputDataDefiniton.LoadJson().
Member Function Documentation
MapInput()
override void IG.Neural.DataMapperSimple.MapInput (IVector reducedInput, ref IVector originalInput) inline
Transfer elements from reducedInput vector to original output vector using mapping data for reference. Elements that are not defined in reducedInput vector are copied from definitiondata.
Parameters
reducedInput Reduced elements.
originalInput Original elements for neural network testing.
$A Igor Jul 19; tako78 Jul 19
Implements IG.Neural.IDataMapper.
Definition at line 1108 of file NeuralMapData.cs.
References IG.Neural.MappingDefinition.CheckInputNameConsistency, IG.Neural.MappingDefinition.CheckInputUniqueness, IG.Neural.DataMapperSimple.DataDefinition, IG.Num.InputElementDefinition.DefaultValue, IG.Num.InputOutputDataDefiniton.GetInputElement(), IG.Neural.MappingDefinition.GetMapInputElement(), IG.Num.InputOutputDataDefiniton.InputLength, IG.Neural.MappingDefinition.MappedInputLength, and IG.Neural.MappingDefinitionElement.OriginalElementIndex.
MapOutput()
override void IG.Neural.DataMapperSimple.MapOutput (IVector originalOutput, ref IVector reducedOutput) inline
Transfer elements from originalOutput vector to original output vector using mapping data for reference. Only defined elements are copied in reducedOutput vector.
Parameters
originalOutput Original elements from neural network.
reducedOutput Reduced elements.
$A Igor Jul 19; tako78 Jul 19
Implements IG.Neural.IDataMapper.
Definition at line 1177 of file NeuralMapData.cs.
References IG.Neural.MappingDefinition.CheckOutputNameConsistency, IG.Neural.MappingDefinition.CheckOutputUniqueness, IG.Neural.MappingDefinition.GetMapOutputElement(), IG.Num.IVector< T >.Length, IG.Neural.MappingDefinition.MappedOutputLength, and IG.Neural.MappingDefinitionElement.OriginalElementIndex.
Member Data Documentation
_mappingDefinition
MappingDefinition IG.Neural.DataMapperSimple._mappingDefinition private
Definition at line 1051 of file NeuralMapData.cs.
_dataDefinition
InputOutputDataDefiniton IG.Neural.DataMapperSimple._dataDefinition private
Definition at line 1077 of file NeuralMapData.cs.
Property Documentation
MappingDefinition
MappingDefinition IG.Neural.DataMapperSimple.MappingDefinition get protected set
Definition at line 1058 of file NeuralMapData.cs.
DataDefinition
InputOutputDataDefiniton IG.Neural.DataMapperSimple.DataDefinition get protected set
Definition at line 1084 of file NeuralMapData.cs.
Referenced by IG.Neural.DataMapperSimple.DataMapperSimple(), and IG.Neural.DataMapperSimple.MapInput().
The documentation for this class was generated from the following file:
iglib/igbase/numeric/approximation/neural/testneural/NeuralMapData.cs