Doc: IGLib with source files: IG.Net.PortScannerSimple.PortList Class Reference
IG.Net.PortScannerSimple.PortList Class Reference
Public Member Functions
PortList (int start, int stop)
PortList ()
bool hasMore ()
int getNext ()
Private Attributes
int start
int stop
int ptr
Detailed Description
Definition at line 136 of file PortScannerSimple.cs.
Constructor & Destructor Documentation
PortList() [1/2]
IG.Net.PortScannerSimple.PortList.PortList (int start, int stop) inline
Definition at line 142 of file PortScannerSimple.cs.
References IG.Net.PortScannerSimple.PortList.start, and IG.Net.PortScannerSimple.PortList.stop.
PortList() [2/2]
IG.Net.PortScannerSimple.PortList.PortList () inline
Definition at line 148 of file PortScannerSimple.cs.
Member Function Documentation
hasMore()
bool IG.Net.PortScannerSimple.PortList.hasMore () inline
Definition at line 152 of file PortScannerSimple.cs.
References IG.Net.PortScannerSimple.PortList.ptr, and IG.Net.PortScannerSimple.PortList.stop.
Referenced by IG.Net.PortScannerSimple.PortList.getNext().
getNext()
int IG.Net.PortScannerSimple.PortList.getNext () inline
Definition at line 156 of file PortScannerSimple.cs.
References IG.Net.PortScannerSimple.PortList.hasMore(), and IG.Net.PortScannerSimple.PortList.ptr.
Referenced by IG.Net.PortScannerSimple.run().
Member Data Documentation
start
int IG.Net.PortScannerSimple.PortList.start private
Definition at line 138 of file PortScannerSimple.cs.
Referenced by IG.Net.PortScannerSimple.PortList.PortList().
stop
int IG.Net.PortScannerSimple.PortList.stop private
Definition at line 139 of file PortScannerSimple.cs.
Referenced by IG.Net.PortScannerSimple.PortList.hasMore(), and IG.Net.PortScannerSimple.PortList.PortList().
ptr
int IG.Net.PortScannerSimple.PortList.ptr private
Definition at line 140 of file PortScannerSimple.cs.
Referenced by IG.Net.PortScannerSimple.PortList.getNext(), and IG.Net.PortScannerSimple.PortList.hasMore().
The documentation for this class was generated from the following file:
iglib/igbase/utilities/networking/PortScannerSimple/PortScannerSimple.cs