Doc: IGLib with source files: IGLib.Gr3D.TubularSurface_01 Class Reference
IGLib.Gr3D.TubularSurface_01 Class Reference
Static Public Member Functions
static vec3 Curve (double t)
static List<(vec3 T, vec3 N, vec3 B)> ComputeFrames (double[] tValues)
Static Private Member Functions
static vec3 Tangent (double t)
Detailed Description
Definition at line 12 of file TubularSurface_01.cs.
Member Function Documentation
Curve()
static vec3 IGLib.Gr3D.TubularSurface_01.Curve (double t) static
Referenced by IGLib.Gr3D.TubularSurfaceExamples.Example_01().
Tangent()
static vec3 IGLib.Gr3D.TubularSurface_01.Tangent (double t) static private
Referenced by IGLib.Gr3D.TubularSurface_01.ComputeFrames().
ComputeFrames()
static List<(vec3 T, vec3 N, vec3 B)> IGLib.Gr3D.TubularSurface_01.ComputeFrames (double[] tValues) inline static
Definition at line 21 of file TubularSurface_01.cs.
References IG.Num.vec3.Add(), IG.Num.vec3.Cross(), IG.Num.vec3.Dot(), IG.Num.vec3.Normalize(), and IGLib.Gr3D.TubularSurface_01.Tangent().
Referenced by IGLib.Gr3D.TubularSurfaceExamples.Example_01().
The documentation for this class was generated from the following file:
IGLibGraphics3D/src/IGLib.Graphics3D/Graphics3D/Historical/TubularSurface_01.cs