Doc: IGLib with source files: IG.App.ApplicationIgShellBase Class Reference
IG.App.ApplicationIgShellBase Class Reference
Application class for the IGLib's shell application.
Public Member Functions
ApplicationIgShellBase ()
override void Run (string[] args)
Entry method of the application.
override void LaunchInitNotice ()
Launches initialization notice.
Public Member Functions inherited from IG.Lib.ApplicationBase
ApplicationBase (string programName, int version, int subVersion)
Constructs a new application object.
ApplicationBase (string programName, int version, int subVersion, string release)
Constructs a new application object.
ApplicationBase (string programName, int version, int subVersion, int subSubVersion, string release)
Initializes the global data for the current program.
ApplicationBase (string programName, string codeName, int version, int subVersion, string release)
Initializes the global data for the current program.
ApplicationBase (string programName, string codeName, int version, int subVersion, int subSubVersion, string release)
Constructs a new application object.
void SetCommandlineArguments (string[] args)
Sets command-line arguments of the application.
virtual void ParseCommandlineArguments (string[] args)
Parses command-line arguments and eventually sets various internal variables according to their values.
void AddModule (Module m)
Adds the specified module to the application's list of modules.
void RemoveModule (Module m)
Removes the specified module to the application's list of modules.
override string ToString ()
Public Member Functions inherited from IG.Lib.Module
Module (string moduleName, int version, int subVersion)
Module (string moduleName, int version, int subVersion, string release)
Module (string moduleName, int version, int subVersion, int subSubVersion, string release)
Initializes the global data for the current module.
Module (string moduleName, string codeName, int version, int subVersion, string release)
Module (string moduleName, string codeName, int version, int subVersion, int subSubVersion, string release)
DateTime CalculateCreationTime ()
Calculates program creation time of the current executable (the entry assembly) and returns it.
DateTime CalculateCreationTime (Type type)
Calculates creation time of the assembly containing the specified class and returns it.
virtual bool CheckSoftwareRootValidity (string rootpath)
Verifies whether the specified directory is a valid software root directory. Global is verified by the standard identtification file that was put into the directory at its creation.
string ToStringShort ()
Retrurns a short string containing very basic information about the application or module.
override string ToString ()
Returns a string containing basic data of the module or application.
virtual List< String > NoticeShort ()
Returns a list of text lines introducing the module or application in a condensed way.
virtual List< String > Notice ()
Returns a list of text lines introducing the module or application in.
virtual List< String > Notice (bool useCodename, bool printVersion, bool printRelease, bool printAuthor, bool printAuthorAddress, bool printWebPage, bool printEmail)
Returns a list of text lines introducing the module or application.
Static Public Member Functions
static void Init ()
Initializes global application data for the current class of application.
Static Public Member Functions inherited from IG.Lib.Module
static string DecorationFrameAsterisk (List< string > lines, int indent, int padLeft, int padRight, int padTop, int padBottom)
Returns a string containing the specified text lines in a single frame made of asterisks.
static string DecorationFrameDoubleAsterisk (List< string > lines, int indent, int padLeft, int padRight, int padTop, int padBottom)
Returns a string containing the specified text lines in a double frame made of asterisks.
static string DecorationFrame (List< string > lines, int indent, int padLeft, int padRight, int padTop, int padBottom, char frameChar, int thickness)
Returns a string containing the specified text lines in a frame made of one or more layers of equal characters.
static string DecorationFrameDashed (List< string > lines, int indent, int padLeft, int padRight, int padTop, int padBottom)
Returns a string containing the specified text lines in a frame made of a single layers of dashes ('-') and vertical bars ('|').
static string DecorationFrameDoubleDashed (List< string > lines, int indent, int padLeft, int padRight, int padTop, int padBottom)
Returns a string containing the specified text lines in a frame made of a double layers of dashes ('-') and vertical bars ('|').
static void AddDefaultAssembliesExtShellApp ()
Appends list of assemblies for dynamic testing of software in the ExtShellApp project.
static void AddDefaultAssembliesExtNeuralApp ()
Appends list of assemblies for dynamic testing of software in the ExtNeuralApp project.
static void AddDefaultAssembliesExtShellAppExt ()
Appends list of assemblies for dynamic testing of software in the ExtShellAppExt project.
Protected Member Functions
override void ModuleInitializationBefore ()
Pre-initialization stage.
override void ModuleInitializationAfter ()
A method called after other initializaton parts of the module.
Protected Member Functions inherited from IG.Lib.ApplicationBase
int FindModuleIndex (Module m)
Protected Member Functions inherited from IG.Lib.Module
virtual void ModuleInitializationCore (string name, string codeName, int version, int subVersion, int subSubVersion, string release)
Performs the core initialization step of the program or module.
void ModuleInitialization (string moduleName, string codeName, int version, int subVersion, int subSubVersion, string release)
Performs complete initialization of the program or module, including the pre-initialization, core initializattion and post-initialization steps.
virtual string ToCodeName (string Name)
Converts a module or program name to a valid code name.
Additional Inherited Members
Public Attributes inherited from IG.Lib.ApplicationBase
int _numCommandlineArguments
Public Attributes inherited from IG.Lib.Module
XmlDocument Data =null
String Email = null
String[] Authors = null
bool _expires = true
Static Public Attributes inherited from IG.Lib.Module
const string DefaultModuleName = "Test Library"
const int DefaultVersion = 0
Static Protected Member Functions inherited from IG.Lib.ApplicationBase
static void InitApp ()
Initializes the global application data. This should be called in derived class' Init().
Static Protected Member Functions inherited from IG.Lib.Module
static int MaxLength (List< string > lines)
Maximal length of any line in the specified list.
static string MultiCharacter (char ch, int num)
Returns a string containing the specified number of specified (equal) characters.
Protected Attributes inherited from IG.Lib.ApplicationBase
string[] _commandLineArguments
List< Module > _modules = new List<Module>()
Protected Attributes inherited from IG.Lib.Module
object _lock = new object()
string _IGHomeEnv = null
string[] _IGHomeEnvList
bool _isModule = false
string _Name = "IG's Test Program"
int _version = 0
int _NumVersionDigits =2
bool _useSubVersion = true
DateTime _StartTime = DateTime.Now
TimeSpan _ValidityPeriod =new TimeSpan(100*366,0,0,0,0)
string _Directory = null
string _modulesDir = "modules"
string _applicationsDir = "applications"
IReporter _reporter = DefaultReporter
Static Protected Attributes inherited from IG.Lib.ApplicationBase
static object lockGlobal = new Object()
Global application data lock.
static ApplicationBase _global = new ApplicationBase(DefaultApplicationName, DefaultVersion, DefaultSubVersion)
static bool _initializedGlobal = false
Static Protected Attributes inherited from IG.Lib.Module
const int DD = 06
static IReporter _defaultReporter = null
Properties inherited from IG.Lib.ApplicationBase
string[] CommandlineArguments [get, protected set]
Command-line arguments.
int NumCommandlineArguments [get, private set]
Number of command-line arguments.
static ApplicationBase Global [get, protected set]
Gets the global instance of the App class, representing the current program.
static bool InitializedGlobal [get, protected set]
Gets a true/false value telling whether the global application data is initialized or not.
static IReporter Rep [get, set]
Application's reporter.
Properties inherited from IG.Lib.Module
object Lock [get]
Object's lock (implementation of ILockable).
string IGHomeEnv [get, protected set]
Environment variable that holds the software root directory.
string[] IGHomeEnvList [get, protected set]
Possible names for environment variable that holds the software root directory.
virtual string IGHomeIdFile [get, protected set]
Name of the software root identification file This file must be contained immediately in the software root directory. Its contents is checked in order to see whether a certain directory is actually the software root directory.
virtual string IGHomeIdFileString [get, protected set]
Name of the software root identification file This file must be contained immediately in the software root directory. Its contents is checked in order to see whether a certain directory is actually the software root directory.
string AuthorFullName [get]
Gets a treue/false value telling whether the global program data is initialized or not.
string AuthorAddress [get]
Gets complete developer's address (combination of individual address lines).
virtual bool IsApplication [get, protected set]
Whether the current object represents an application.
virtual bool IsModule [get, protected set]
Whether the current object represents a module (not an application).
virtual string Name [get, set]
Gets or sets the full name of the program.
string CodeName [get, set]
Gets or sets code name of the program.
int Version [get, set]
Gets or sets the main version number of the program.
int SubVersion [get, set]
Gets or sets the subversion number of the program.
int SubSubVersion [get, set]
Gets or sets the sub-subversion number of the program.
string Release [get, set]
Gets or sets the release specification of the program (e.g. "alpha", "beta", "release"...).
virtual DateTime StartTime [get, private set]
Gets The starting time of the program (time when program data was initialized).
DateTime CreationTime [get, protected set]
Gets or sets craation time of the program.
virtual bool Expires [get, set]
Gets or sets the flag telling whether the program expires.
TimeSpan ValidityPeriod [get, set]
Gets or sets the validity period length for the program.
TimeSpan ExpireWarnPeriod [get, set]
Gets or sets the length of the expiration warning period. This is the period of time between expiration of the software and time when the software actually stops working. If not set, 0 is taken.
DateTime ExpireTime [get, set]
Gets or sets the expiration time of the program. Property is automatically updated if the validity period is changed.
DateTime ExpireFinalTime [get, set]
Gets or sets the time when program will stop functioning completely.
bool HasExpired [get]
Gets the indicatin whether the program has expired.
bool HasExpiredFinal [get]
Gets the indicatin whether the program has stopped being functional because of expiration. This happens after final expiration time has reach, which follows a certain period after the regular expiration time.
int DaysTillExpire [get]
Gets the number of days until the expiration of the program or module (0 or negative if already expired).
int DaysTillExpireFinal [get]
Gets the number of days until the final expiration of the program or module, when the software will stop functioning (0 or negative if already expired).
int NumVersionDigits [get, set]
Number of digits that are output in version strings.
bool UseSubVersion [get, set]
Whether or not subversion number is used.
bool UseSubSubVersion [get, set]
Whether or not sub-subversion number is used.
string VersionString [get]
Gets the string that represents program version.
string DirectoryVersionString [get]
Gets the string representation of program version to be used in directory and file names. Sub-subversion is not included in the string.
string User [get, set]
Gets name of the user of the program.
virtual String SoftwareParentDirectory [get]
Gets the directory containing individual module or application directories.
virtual string BaseDirectory [get, set]
Gets or sets the program directory (containing all version directories, user directories, etc.). Setting of program directory should normally be left to the system.
virtual string VersionDirectory [get, set]
Gets or sets the program'result specific version directory. Setting of this directory should normally be left to the system.
virtual string UserDirectory [get, set]
Gets or sets the spedcific user'result directory for the current version of the progrm. Setting of this directory should normally be left to the system.
virtual string SessionDirectory [get, set]
Gets or sets the current session'result directory. Setting of this directory should normally be left to the system.
virtual string SoftwareRoot [get, protected set]
Gets or sets the software root directory. Setting it should normally be left to the system.
IReporter Reporter [get, set]
static IReporter DefaultReporter [get]
Returns the curent global Application reporter.
static DateTime AnnDllTestLimit [get]
static bool IsAnnDllTestMode [get]
Whether dynamic testing of software is on (helps in agile software development).
static bool LoadableScriptShellIsLoadableDefault [get]
Basic procedure for calculation of the flag LoadableScriptShellIsLoadable.
static bool LoadableScriptShellIsRunnableDefault [get]
Basic procedure for calculation of the flag LoadableScriptShellIsRunnable.
Properties inherited from IG.Lib.ILockable
object Lock [get]
Detailed Description
Application class for the IGLib's shell application.
Definition at line 10 of file ApplicationIgShellBase.cs.
Constructor & Destructor Documentation
ApplicationIgShellBase()
IG.App.ApplicationIgShellBase.ApplicationIgShellBase () inline
Definition at line 13 of file ApplicationIgShellBase.cs.
Referenced by IG.App.ApplicationIgShellBase.Init().
Member Function Documentation
Run()
override void IG.App.ApplicationIgShellBase.Run (string[] args) inline virtual
Entry method of the application.
Parameters
args List of arguments of the entry method.
Reimplemented from IG.Lib.ApplicationBase.
Definition at line 23 of file ApplicationIgShellBase.cs.
References IG.Lib.UtilSystem.GetCurrentProcessExecutableName(), and IG.Lib.ILoadableScript.Run().
ModuleInitializationBefore()
override void IG.App.ApplicationIgShellBase.ModuleInitializationBefore () inline protected virtual
Pre-initialization stage.
Reimplemented from IG.Lib.ApplicationBase.
Definition at line 73 of file ApplicationIgShellBase.cs.
References IG.Lib.Module.AuthorAddress1, IG.Lib.Module.AuthorAddress2, IG.Lib.Module.AuthorAddress3, IG.Lib.Module.AuthorFirstName, and IG.Lib.Module.Expires.
ModuleInitializationAfter()
override void IG.App.ApplicationIgShellBase.ModuleInitializationAfter () inline protected virtual
A method called after other initializaton parts of the module.
This method is called after ModuleInitializationBefore and before ModuleInitializationCore.
The method should not be called explicitly in derived classes. Instead, it is called from ModuleInitialization.
Override this method in derived classes.
Reimplemented from IG.Lib.Module.
Definition at line 83 of file ApplicationIgShellBase.cs.
References IG.App.ApplicationIgShellBase.LaunchInitNotice().
LaunchInitNotice()
override void IG.App.ApplicationIgShellBase.LaunchInitNotice () inline virtual
Launches initialization notice.
Reimplemented from IG.Lib.Module.
Definition at line 95 of file ApplicationIgShellBase.cs.
References IG.Lib.Module.DecorationFrameDashed(), and IG.Lib.Module.NoticeShort().
Referenced by IG.App.ApplicationIgShellBase.ModuleInitializationAfter().
Init()
static void IG.App.ApplicationIgShellBase.Init () inline static
Initializes global application data for the current class of application.
Definition at line 118 of file ApplicationIgShellBase.cs.
References IG.App.ApplicationIgShellBase.ApplicationIgShellBase(), IG.Lib.ApplicationBase.Global, IG.Lib.ApplicationBase.InitApp(), IG.Lib.ApplicationBase.InitializedGlobal, and IG.Lib.ApplicationBase.lockGlobal.
The documentation for this class was generated from the following file:
iglib/igbase/application/igshell/ApplicationIgShellBase.cs