Doc: IGLib with source files: IGLib.CoreExtended.ReflectionTypeConverter Class Reference
IGLib.CoreExtended.ReflectionTypeConverter Class Reference
A type converter that supports implicit/explicit conversion operators via reflection, including base class and interface fallback and optional caching.
Public Member Functions
virtual object ConvertToType (object value, Type targetType, bool allowSourceBaseConversions=true, bool allowInterfaceConversions=true)
override object ConvertToType (object value, Type targetType)
Converts a value to the specified target type, supporting collections. Conversion is bsed on the actual type of value and the specified target type (targetType). See the class description for more details.
Public Member Functions inherited from IGLib.Core.BasicTypeConverter
T ConvertToType< T > (object value)
Converts the specified value to the specified target type.
void ConvertToType< T > (object value, out T result)
Converts the specified value to the specified target type.
Private Member Functions
Func< object, object > TryFindOperatorConverter (Type sourceType, Type targetType, bool allowSourceBaseConversions, bool allowInterfaceConversions)
Func< object, object > FindOperatorMethod (Type definingType, Type sourceType, Type targetType)
Static Private Attributes
static readonly Dictionary<(Type Source, Type Target), Func< object, object > > _conversionCache = new()
Additional Inherited Members
Static Public Member Functions inherited from IGLib.Core.BasicTypeConverter
static bool IsNullableType (Type type)
Determines whether the specified type is nullable.
Static Public Attributes inherited from IGLib.Core.BasicTypeConverter
const bool DefaultOutputFullTypeNames = false
Default value of OutputFullTypeNames.
const string NullTypeString = "[[null type]]"
Protected Member Functions inherited from IGLib.Core.BasicTypeConverter
string TypeName (Type type)
Returns name of the specified type type , dependent on the property OutputFullTypeNames: if it is true then the full type name is returned (obtained by Type.FullName), otherwise the short name is returned (obtained by Type.Name).
Properties inherited from IGLib.Core.BasicTypeConverter
bool OutputFullTypeNames = DefaultOutputFullTypeNames [get, set]
Whether to take full type names in exception messages and elsewhere.
Detailed Description
A type converter that supports implicit/explicit conversion operators via reflection, including base class and interface fallback and optional caching.
Definition at line 18 of file ReflectionTypeConverter.cs.
Member Function Documentation
ConvertToType() [1/2]
virtual object IGLib.CoreExtended.ReflectionTypeConverter.ConvertToType (object value, Type targetType, bool allowSourceBaseConversions = true, bool allowInterfaceConversions = true) inline virtual
Definition at line 22 of file ReflectionTypeConverter.cs.
References IGLib.CoreExtended.ReflectionTypeConverter._conversionCache, and IGLib.CoreExtended.ReflectionTypeConverter.TryFindOperatorConverter().
Referenced by IGLib.CoreExtended.ReflectionTypeConverter.ConvertToType().
ConvertToType() [2/2]
override object IGLib.CoreExtended.ReflectionTypeConverter.ConvertToType (object value, Type targetType) inline virtual
Converts a value to the specified target type, supporting collections. Conversion is bsed on the actual type of value and the specified target type (targetType). See the class description for more details.
Takes a value of type object, identifies its actual type, converts it to the type compatible with the specified desired target type, and returns the converted value as object.
Parameters
value The input object to be converted.
targetType The desired target type.
Returns
The converted object compatible with the target type.
Reimplemented from IGLib.Core.CollectionTypeConverter.
Definition at line 70 of file ReflectionTypeConverter.cs.
References IGLib.CoreExtended.ReflectionTypeConverter.ConvertToType().
TryFindOperatorConverter()
Func<object, object> IGLib.CoreExtended.ReflectionTypeConverter.TryFindOperatorConverter (Type sourceType, Type targetType, bool allowSourceBaseConversions, bool allowInterfaceConversions) inline private
Definition at line 75 of file ReflectionTypeConverter.cs.
References IGLib.CoreExtended.ReflectionTypeConverter.FindOperatorMethod().
Referenced by IGLib.CoreExtended.ReflectionTypeConverter.ConvertToType().
FindOperatorMethod()
Func<object, object> IGLib.CoreExtended.ReflectionTypeConverter.FindOperatorMethod (Type definingType, Type sourceType, Type targetType) inline private
Definition at line 121 of file ReflectionTypeConverter.cs.
Referenced by IGLib.CoreExtended.ReflectionTypeConverter.TryFindOperatorConverter().
Member Data Documentation
_conversionCache
readonly Dictionary<(Type Source, Type Target), Func<object, object> > IGLib.CoreExtended.ReflectionTypeConverter._conversionCache = new() static private
Definition at line 20 of file ReflectionTypeConverter.cs.
Referenced by IGLib.CoreExtended.ReflectionTypeConverter.ConvertToType().
The documentation for this class was generated from the following file:
IGLibGraphics3D/src/IGLib.Graphics3D/other/TypeConversionExtended/ReflectionTypeConverter.cs