Doc: IGLib with source files: IG.Lib.ReporterBase.TWClass Class Reference
IG.Lib.ReporterBase.TWClass Class Reference
A class for storing TextWriters and some data associated with them (such as the name of the file from which a TextWriter was created), which enables searching on basis of this data.
Public Member Functions
TWClass (ReporterBase R)
Public constructor, requires the Reporter object on which this object is installed.
void ClearWriter ()
bool SetWriter (TextWriter writer, bool writeintro, bool disposewriter)
Sets the basic text writer to which reporting is performed, but overrides the writeintro property by the 'writeintro' argument.
bool SetWriter (Stream stream, bool writeintro, bool disposewriter)
Creates a TextWriter upon the stream and sets it as the basic TextWriter to which reporting is performed. Overrides the writeintro property by the 'writeintro' argument.
bool SetWriter (string filename, bool append, bool writeintro, bool disposewriter)
Creates a TextWriter upon a file and sets it as the text writer to which reporting is also performed. The caller specifies whether to overwrite the file or to append to it, and whether the introductory text is written before reporting to the file begins.
Public Attributes
TextWriter Writer = null
Properties
string filename [get, protected set]
Stream stream [get, protected set]
Private Member Functions
TWClass ()
Private Attributes
bool DisposeWriter = false
string _filename = null
Stream _stream = null
ReporterBase rep = null
Detailed Description
A class for storing TextWriters and some data associated with them (such as the name of the file from which a TextWriter was created), which enables searching on basis of this data.
Definition at line 3569 of file ReporterMsg.cs.
Constructor & Destructor Documentation
TWClass() [1/2]
IG.Lib.ReporterBase.TWClass.TWClass () inline private
Definition at line 3585 of file ReporterMsg.cs.
TWClass() [2/2]
IG.Lib.ReporterBase.TWClass.TWClass (ReporterBase R) inline
Public constructor, requires the Reporter object on which this object is installed.
Parameters
R Reporter object on which the created instance is installed.
Definition at line 3589 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.TWClass.rep.
Member Function Documentation
ClearWriter()
void IG.Lib.ReporterBase.TWClass.ClearWriter () inline
Definition at line 3596 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.TWClass.DisposeWriter, IG.Lib.ReporterBase.TWClass.filename, IG.Lib.ReporterBase.TWClass.stream, and IG.Lib.ReporterBase.TWClass.Writer.
Referenced by IG.Lib.ReporterBase.RemoveTextLoggers(), IG.Lib.ReporterBase.RemoveTextWriters(), and IG.Lib.ReporterBase.RemoveTW().
SetWriter() [1/3]
bool IG.Lib.ReporterBase.TWClass.SetWriter (TextWriter writer, bool writeintro, bool disposewriter) inline
Sets the basic text writer to which reporting is performed, but overrides the writeintro property by the 'writeintro' argument.
Parameters
writer Textwriter to which reporting will be performed.
writeintro Overrides the class' writeintro property (if true then introductory text is printed, regardless of the value of the property). If the introductory text is printed then the standard method is used, taking into account the introtext and programname properties.
disposewriter Indicates whether the TextWriter should be disposed when not used any more. Default is false when specifying a textwriter.
Returns
True if a new writer has been successfully set and is ready to use, false otherwise.
Definition at line 3621 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.TWClass.DisposeWriter, IG.Lib.ReporterBase.TWClass.rep, IG.Lib.ReporterBase.TextWriterPrintIntro(), and IG.Lib.ReporterBase.TWClass.Writer.
Referenced by IG.Lib.ReporterBase.AddTW(), and IG.Lib.ReporterBase.TWClass.SetWriter().
SetWriter() [2/3]
bool IG.Lib.ReporterBase.TWClass.SetWriter (Stream stream, bool writeintro, bool disposewriter) inline
Creates a TextWriter upon the stream and sets it as the basic TextWriter to which reporting is performed. Overrides the writeintro property by the 'writeintro' argument.
Parameters
stream Textwriter to which reporting will be performed.
writeintro Overrides the class' writeintro property (if true then introductory text is printed, regardless of the value of the property). If the introductory text is printed then the standard method is used, taking into account the introtext and programname properties.
disposewriter Indicates whether the TextWriter should be disposed when not used any more. Default is false when specifying a stream.
Returns
True if a new writer has been successfully set and is ready to use, false otherwise.
Definition at line 3656 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.TWClass.rep, IG.Lib.ReporterBase.ReserveReportError(), IG.Lib.ReporterBase.TWClass.SetWriter(), and IG.Lib.ReporterBase.TWClass.stream.
SetWriter() [3/3]
bool IG.Lib.ReporterBase.TWClass.SetWriter (string filename, bool append, bool writeintro, bool disposewriter) inline
Creates a TextWriter upon a file and sets it as the text writer to which reporting is also performed. The caller specifies whether to overwrite the file or to append to it, and whether the introductory text is written before reporting to the file begins.
Parameters
filename Name of the file to which reporting will be performed.
append If false then eventual existing contents of the file are overwritten. Otherwise, new text is appended at the end of the file.
writeintro Overrides the class' writeintro property (if true then introductory text is printed, regardless of the value of the property). If the introductory text is printed then the standard method is used, taking into account the introtext and programname properties.
disposewriter Indicates whether the TextWriter should be disposed when not used any more. Default is true when specifying a file name.
Returns
True if a new writer has been successfully set and is ready to use, false otherwise.
Definition at line 3687 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.TWClass.DisposeWriter, IG.Lib.ReporterBase.TWClass.filename, IG.Lib.ReporterBase.TWClass.rep, IG.Lib.ReporterBase.ReserveReportError(), and IG.Lib.ReporterBase.TWClass.SetWriter().
Member Data Documentation
Writer
TextWriter IG.Lib.ReporterBase.TWClass.Writer = null
Definition at line 3571 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.TWClass.ClearWriter(), IG.Lib.ReporterBase.FindTW(), and IG.Lib.ReporterBase.TWClass.SetWriter().
DisposeWriter
bool IG.Lib.ReporterBase.TWClass.DisposeWriter = false private
Definition at line 3572 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.TWClass.ClearWriter(), and IG.Lib.ReporterBase.TWClass.SetWriter().
_filename
string IG.Lib.ReporterBase.TWClass._filename = null private
Definition at line 3575 of file ReporterMsg.cs.
_stream
Stream IG.Lib.ReporterBase.TWClass._stream = null private
Definition at line 3576 of file ReporterMsg.cs.
rep
ReporterBase IG.Lib.ReporterBase.TWClass.rep = null private
Definition at line 3583 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.TWClass.SetWriter(), and IG.Lib.ReporterBase.TWClass.TWClass().
Property Documentation
filename
string IG.Lib.ReporterBase.TWClass.filename get protected set
Definition at line 3578 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.TWClass.ClearWriter(), IG.Lib.ReporterBase.FindTW(), and IG.Lib.ReporterBase.TWClass.SetWriter().
stream
Stream IG.Lib.ReporterBase.TWClass.stream get protected set
Definition at line 3579 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.TWClass.ClearWriter(), IG.Lib.ReporterBase.FindTW(), and IG.Lib.ReporterBase.TWClass.SetWriter().
The documentation for this class was generated from the following file:
iglib/igbase/reporter/ReporterMsg.cs