Doc: IGLib with source files: IG.Reflection.DerivedTypesRgistryBasic< BaseType > Class Template Reference
IG.Reflection.DerivedTypesRgistryBasic< BaseType > Class Template Reference
Registry of types with a common base type, similar to DerivedTypesRegistry<BaseType, TypeInfoBase>, with the simple type info class TypeInfoBase and with added registration method based on type (RegisterDerivedType<TypeToRegister>). Each type in is registered with a type info object (of type TypeInfoBase and can be registered under differeent names (typically, simple type names and qualified names).
Public Member Functions
DerivedTypesRgistryBasic ()
virtual void RegisterDerivedType< TypeToRegister > ()
Registeers the type (TypeToRegister) under its simple, fully specified and assembly specified names by calling the DerivedTypesRegistry<BaseType, TypeInfoBase>.Register(TypeInfoBase).
Public Member Functions inherited from IG.Reflection.DerivedTypesRegistry< BaseType, TypeInfoBase >
DerivedTypesRegistry ()
virtual void Register (string typeName, InfoType typeData)
Registers the type information typeData under the name typeName .
virtual void Register (InfoType typeData)
Registeers the specified type information (typeData) under the registered type's (TypeInfoBase.ClassType) simple, fully qualidfied and assembly qualified names by calling the Register(string, InfoType)
virtual InfoType GetTypeData (string typeName, bool throwIfCannotCreate=true)
Tries to resolve and return the type data object that corresponds to the specified type name (typeName).
virtual Type GetType (string derivedTypeName, bool tryGetIfNotRegistered=false, bool throwIfCannotResolve=true)
Tries to resolve and return the type that corresponds to the specified type name (derivedTypeName).
virtual BaseType CreateInstance (string derivedTypeName, bool throwIfCannotCreate=true)
Attempts to create and return an instance of the type specified by its name (derivedTypeName). It first calls GetType(string, bool, bool) to get the type corresponding to derivedTypeName , then it uses reflection to invoke parameter-less constructor to create an instance. If parameterless constructor is also defined on the type then the method fails.
Protected Member Functions
virtual TypeInfoBase CreateTypeData (Type classType)
Creates the type info object of type TypeInfoBase for the specified Type classType .
Additional Inherited Members
Properties inherited from IG.Reflection.DerivedTypesRegistry< BaseType, TypeInfoBase >
virtual object Lock [get]
Dictionary< string, InfoType > DerivedTypeNames [get]
Properties inherited from IG.Lib.ILockable
object Lock [get]
Detailed Description
Registry of types with a common base type, similar to DerivedTypesRegistry<BaseType, TypeInfoBase>, with the simple type info class TypeInfoBase and with added registration method based on type (RegisterDerivedType<TypeToRegister>). Each type in is registered with a type info object (of type TypeInfoBase and can be registered under differeent names (typically, simple type names and qualified names).
Template Parameters
BaseType Base type for types that can be registered in the current registry. Registered types must derive from this type.
Definition at line 21 of file DerivedTypesRgistryBasic.cs.
Constructor & Destructor Documentation
DerivedTypesRgistryBasic()
IG.Reflection.DerivedTypesRgistryBasic< BaseType >.DerivedTypesRgistryBasic () inline
Definition at line 25 of file DerivedTypesRgistryBasic.cs.
Member Function Documentation
CreateTypeData()
virtual TypeInfoBase IG.Reflection.DerivedTypesRgistryBasic< BaseType >.CreateTypeData (Type classType) inline protected virtual
Creates the type info object of type TypeInfoBase for the specified Type classType .
This method is used by the RegisterDerivedType<TypeToRegister> to create the type info object used in registration.
Parameters
classType
Definition at line 33 of file DerivedTypesRgistryBasic.cs.
Referenced by IG.Reflection.DerivedTypesRgistryBasic< BaseType >.RegisterDerivedType< TypeToRegister >().
RegisterDerivedType< TypeToRegister >()
virtual void IG.Reflection.DerivedTypesRgistryBasic< BaseType >.RegisterDerivedType< TypeToRegister > () inline virtual
Registeers the type (TypeToRegister) under its simple, fully specified and assembly specified names by calling the DerivedTypesRegistry<BaseType, TypeInfoBase>.Register(TypeInfoBase).
Template Parameters
TypeToRegister Type that is registered, must be assignable to BaseType .
Type Constraints
TypeToRegister : BaseType
Definition at line 41 of file DerivedTypesRgistryBasic.cs.
References IG.Reflection.DerivedTypesRgistryBasic< BaseType >.CreateTypeData(), and IG.Reflection.DerivedTypesRegistry< BaseType, TypeInfoBase >.Register().
The documentation for this class was generated from the following file:
iglib/igbase/types_reflection/TypeRegistry/DerivedTypesRgistryBasic.cs