Doc: IGLib with source files: IGLib.Core.Extended.TypeConversionHelper Class Reference
IGLib.Core.Extended.TypeConversionHelper Class Reference
Public Member Functions
TypeConversionHelper ()
object ConvertToType (object value, Type targetType, bool enableNullableHandling=true, bool enableCollectionConversion=false)
Static Public Attributes
static TypeConversionHelper Instance => _instance.Value
static TypeConversionHelper TypeConversionHelperInstance => Instance
Protected Attributes
readonly ConcurrentDictionary<(Type SourceType, Type TargetType), MethodInfo > _castMethodCache = new()
Used to cache MethodInfo objects used for type conversions.
Private Member Functions
object ConvertCollections (object value, Type sourceType, Type targetType, bool enableNullableHandling, bool enableCollectionConversion)
Static Private Member Functions
static bool IsEnumerableButNotString (Type type)
static Type GetEnumerableElementType (Type enumerableType)
Static Private Attributes
static readonly Lazy< TypeConversionHelper > _instance = new(() => new TypeConversionHelper())
Detailed Description
This class is OBSOLETE and is replaced by chasses that implement ITypeConverter. The class will be kept for some time for reference. You can remove it at least in Nov '25, possibly before (if you know it is not useful any more).
Handles type conversionss where the source type is inferred from the source object and the target type is specifyed by the Type object rather than generic type parameter.
Definition at line 19 of file TypeConversionHelperObsolete.cs.
Constructor & Destructor Documentation
TypeConversionHelper()
IGLib.Core.Extended.TypeConversionHelper.TypeConversionHelper () inline
Definition at line 32 of file TypeConversionHelperObsolete.cs.
Member Function Documentation
ConvertToType()
object IGLib.Core.Extended.TypeConversionHelper.ConvertToType (object value, Type targetType, bool enableNullableHandling = true, bool enableCollectionConversion = false) inline
Definition at line 35 of file TypeConversionHelperObsolete.cs.
References IGLib.Core.Extended.TypeConversionHelper._castMethodCache, IGLib.Core.Extended.TypeConversionHelper.ConvertCollections(), and IGLib.Core.Extended.TypeConversionHelper.IsEnumerableButNotString().
Referenced by IGLib.Core.Extended.TypeConversionHelper.ConvertCollections(), and IGLib.Core.Tests.TypeConversionHelperTestsObsolete.TypeConversionHelper_ConversionToObjectAndBackTest< OriginalType, TargetType, RestoredType >().
IsEnumerableButNotString()
static bool IGLib.Core.Extended.TypeConversionHelper.IsEnumerableButNotString (Type type) inline static private
Definition at line 103 of file TypeConversionHelperObsolete.cs.
Referenced by IGLib.Core.Extended.TypeConversionHelper.ConvertToType().
ConvertCollections()
object IGLib.Core.Extended.TypeConversionHelper.ConvertCollections (object value, Type sourceType, Type targetType, bool enableNullableHandling, bool enableCollectionConversion) inline private
Definition at line 108 of file TypeConversionHelperObsolete.cs.
References IGLib.Core.Extended.TypeConversionHelper.ConvertToType(), and IGLib.Core.Extended.TypeConversionHelper.GetEnumerableElementType().
Referenced by IGLib.Core.Extended.TypeConversionHelper.ConvertToType().
GetEnumerableElementType()
static Type IGLib.Core.Extended.TypeConversionHelper.GetEnumerableElementType (Type enumerableType) inline static private
Definition at line 147 of file TypeConversionHelperObsolete.cs.
Referenced by IGLib.Core.Extended.TypeConversionHelper.ConvertCollections().
Member Data Documentation
_instance
readonly Lazy<TypeConversionHelper> IGLib.Core.Extended.TypeConversionHelper._instance = new(() => new TypeConversionHelper()) static private
Definition at line 22 of file TypeConversionHelperObsolete.cs.
Instance
TypeConversionHelper IGLib.Core.Extended.TypeConversionHelper.Instance => _instance.Value static
Definition at line 23 of file TypeConversionHelperObsolete.cs.
TypeConversionHelperInstance
TypeConversionHelper IGLib.Core.Extended.TypeConversionHelper.TypeConversionHelperInstance => Instance static
Definition at line 26 of file TypeConversionHelperObsolete.cs.
_castMethodCache
readonly ConcurrentDictionary<(Type SourceType, Type TargetType), MethodInfo> IGLib.Core.Extended.TypeConversionHelper._castMethodCache = new() protected
Used to cache MethodInfo objects used for type conversions.
Definition at line 30 of file TypeConversionHelperObsolete.cs.
Referenced by IGLib.Core.Extended.TypeConversionHelper.ConvertToType().
The documentation for this class was generated from the following file:
IGLibGraphics3D/src/IGLib.Graphics3D/other/TypeConversion/TypeConversionHelperObsolete.cs