Doc: IGLib with source files: IG.Lib.UtilStr Class Reference
IG.Lib.UtilStr Class Reference
Various string operations, random strings, random characters, etc.
Static Public Member Functions
static bool ArraysEqual< ElementType > (ElementType[] originals, ElementType[] compared)
Returns true if the specified arrays are equal (i.e. all corresponding values are equal or both arrays are null), false if not.
static bool StringArraysEqual (string[] originals, string[] compared)
Returns true if the specified string arrays are equal (i.e. all corresponding values are equal or both arrays are null), false if not.
static string[] GetParametersArrayPlain (string listString)
Returns a string array of parameters represented by the specified comma separated list in string form.
static string GetParametersStringPlain (string[] parameters)
Returns a string representation of the list of parameters, separated by commas but not embedded in any braces.
static string[] GetLines (string linesString, bool doTrim=true)
Returns a string array of parameters represented by the specified comma separated list in string form.
static string GetLinesStringPlain (string[] lines)
Returns a string representation of the list of lines, separated by newlines.
static string GetCommandLine (string CommandName, string[] CommandArguments)
Assembles and returns the commandline string that corresponds to the specified command name and arguments.
static string GetCommandLine (string[] commandNameAndArguments)
Assembles and returns the commandline string that corresponds to the specified command name and arguments.
static string[] GetArgumentsArray (string commandLine)
Parses a command line and extracts arguments from it. Arguments can be separated according to usual rules for command-line arguments: spaces are separators, there can be arbitraty number of spaces, and if we want an argument to contain spaces, we must enclose it in double quotes. Command line can also contain the command name followed by arguments. In this case it is treated in the same way, and command can be obtained simply as the first string in the returned array.
static void GetArguments (string commandLine, ref List< string > ret)
Parses a command line and extracts arguments from it. Arguments can be separated according to usual rules for command-line arguments: spaces are separators, there can be arbitraty number of spaces, and if we want an argument to contain spaces, we must enclose it in double quotes. Command line can also contain the command name followed by arguments. In this case it is treated in the same way, and command can be obtained simply as the first string in the returned array.
static string RandomUnicodeString (int stringLength, IRandomGenerator rndgen=null)
Creates and returns a valid random unicode string. All possible uncode characters may be contained in the generated string, EXCEPT the surogate characters in the range 0xD800-0xDFFF.
static string RandomUnicodeString (int stringLength, bool excludeSurrogates=true, IRandomGenerator rndgen=null)
Creates and returns a valid random unicode string. All legal uncode characters may be contained in the generated string.
static char RandomCharCapitalLetter (IRandomGenerator rndgen=null)
Returns a random character that is a capital letter (A-Z)
static char RandomCharSmallLetter (IRandomGenerator rndgen=null)
Returns a random character that is a small letter (a-z)
static char RandomCharNumeric (IRandomGenerator rndgen=null)
Returns a random numeric character (0-9)
static char RandomChar (CharType typeflags, IRandomGenerator rndgen=null)
Returns a random character whose type is specified by type flags. Type flags can be combined by bitwise operations.
static char RandomChar (IRandomGenerator rndgen=null)
Returns a random character that is either a capital letter (A-Y) or a small letter (a-z). Type flags can be combined by bitwise operations.
static string RandomString (int length, CharType flags, bool firstletter, IRandomGenerator rndgen=null)
Returns a randomly generated string of a specified length whose characters are of specified type(result). It can also be specified that the first character is a letter.
static string RandomString (int length, CharType flags, IRandomGenerator rndgen=null)
Returns a randomly generated string of a specified length whose characters are of specified type(result).
static string RandomString (int length, bool firstletter, IRandomGenerator rndgen=null)
Returns a randomly generated string composed of alphanumeric characters. It can be specified that the first character is a letter.
static string RandomString (int length, IRandomGenerator rndgen=null)
Returns a randomly generated string of a specified length containing alphanumeric characters. The first character is a letter.
static string RandomString (IRandomGenerator rndgen=null)
Returns a randomly generated string of a random length containing alphanumeric characters. The first character is a letter. Length is between 1 and the value specified by the MaxStringLength property.
static string RandomString (int stringLength, string allowedChars=null, IRandomGenerator rndgen=null)
Creates and returns a random string consisting of only the letters contained in the specified string.
static bool IsAscii (char ch)
Returns true if the specified character is an ASCII characters, and false otherwise.
static bool IsAsciiLetter (char ch)
Returns true if the specified character is an ASCII letter, and false otherwise.
static bool IsAsciiDigit (char ch)
Returns true if the specified character is an ASCII digit, and false otherwise.
static bool IsAsciiLetterOrDigit (char ch)
Returns true if the specified character is either an ASCII letter or an ASCII digit, and false otherwise.
static bool IsVarName (char[] str)
Returns true if the string corresponding to the specified array of characters is a legal standard representation of a variable name, and false otherwise.
static bool IsVariableName (string str)
Returns true if the specified string is a legal standard representation of a variable name, and false otherwise.
static bool IsAsciiString (char[] str)
Returns true if the string corresponding to the specified array of characters is an ASCII string (i.e. it contains only ASCII characters - from 0 to 255), and false otherwise.
static bool IsAsciiString (string str)
Returns true if the string specified string is an ASCII string (i.e. it contains only ASCII characters - from 0 to 255), and false otherwise.
static bool ToBoolean (string strsetting)
Converts a string representation of a boolean setting to boolean.
static bool IsBoolean (string str)
Returns a boolean value indicating whether the specified string can represent a boolean value.
static long ToInt (string strsetting)
Converts a string representation of an integer setting to an integer value. If the setting is not defined then 0 is returned.
static long ToInt (string strsetting, long defaultvalue)
Converts a string representation of an integer setting to an integer value.
static bool IsInt (string str)
Returns a boolean value indicating whether the specified string is a valid representation of an integer number.
static double ToDouble (string strsetting)
Converts a string representation of a double setting to an integer value. If the setting is not defined then 0 is returned.
static double ToDouble (string strsetting, long defaultvalue)
Converts a string representation of a double value to a number of type double.
static bool IsDouble (string str)
Returns a boolean value indicating whether the specified string is a valid representation of a number (of type double).
static string Load (string filePath)
Loads complete file contents into a stiring and returnes that string.
static void Load (string filePath, ref string readString)
Loads complete file contents into the specified stiring.
static void Save (string str, string filePath, bool append)
Saves the specified string to a specified file. If the specified file does not exists then it is created anew if possible. A boolean argument specifis whether to overwrite existing files or to append the string at the end of the file.
static void Save (string str, string filePath)
Saves the specified string to a specified file. If the file already exists then is content is overwritten. If the file does not yet exist then it is created anew.
static void Append (string str, string filePath)
Saves the specified string to a specified file. If the file already exists then string is appended at the end of the current file contents. If the file does not yet exist then it is created anew.
Static Public Member Functions inherited from IG.Lib.UtilCsv
static bool CsvIsEmptyRow (string[][] values, int rowIndex)
Returns true if the specified line in a 2D jagged array of string cell values (arranged in rows) is empty or does not exist, otherwise false is returned.
static string CsvGetValue (string[][] values, int rowIndex, int columnIndex)
Returns the value of the specified cell of a 2D jagged array of string cell values (arranged in rows) at the specified row and column, or null if such a value does not exist.
static int CsvColumnIndex (string[][] values, string fieldName)
Returns index of thr column that contains data with the specified name in a 2D jagged array of values. It is assumed that the first non-empty row (subarray) contains names of data columns. -1 is returned if the column with the specified field name is not found. Column (or field) names are assumed to be case insensitive.
static int CsvColumnIndex (string[][] values, string fieldName, bool caseSensitive)
Returns index of thr column that contains data with the specified name in a 2D jagged array of values. It is assumed that the first non-empty row (subarray) contains names of data columns. -1 is returned if the column with the specified field name is not found.
static string[][] FromCsvString (string csvString)
Converts a CSV string to a 2D jagged array of string values and returns it. Constant UtilCsv.DefaultCsvSeparator) is assumed to be a separator in the CSV format.
static string[][] FromCsvString (string csvString, string separator)
Converts a CSV string to a 2D jagged array of string values and returns it.
static string ToCsvString (string[][] values, string separator)
Convertsa a 2D jagged array of string values to a string in CSV format.
static string[][] LoadCsv (string filePath, string separator)
Reads contents of a CSV file and returns a 2D jagged array of strigg values contained in the file.
static string[][] LoadCsv (string filePath)
Reads contents of a CSV file and returns a 2D jagged array of strigg values contained in the file. Constant UtilCsv.DefaultCsvSeparator is assumed as separator in the CSV file.
static void SaveCsv (string filePath, string[][] values, string separator, bool append)
Saves a 2D jagged array of string cell values into a CSV file.
static void SaveCsv (string filePath, string[][] values, string separator)
Saves a 2D jagged array of string cell values into a CSV file. If the file already exists then its contents are overwritten.
static void SaveCsv (string filePath, string[][] values, bool append)
Saves a 2D jagged array of string cell values into a CSV file. Constant UtilCsv.DefaultCsvSeparator is assumed to be a separator for the CSV format.
static void SaveCsv (string filePath, string[][] values)
Saves a 2D jagged array of string cell values into a CSV file. If the file already exists then its contents are overwritten. Constant UtilCsv.DefaultCsvSeparator is assumed to be a separator for the CSV format.
static bool TestCsvStringConversion (string[][] values, string separator, bool printResults)
Tests conversion of a 2D jagged array of string values to a CSV formatted string and back. Returns true if the array restored by conversion of the original array to a CSV string and back from a CSV string to a jagged array is the same (within inevitable ambiguities of the CSV format) as the original array.
static void ExampleCsv ()
Example of using CSV format utilities.
Properties
static int MaxStringLength [get, set]
Get or sets maximal length for generated strings (must be GREATER THAN 0).
Properties inherited from IG.Lib.UtilCsv
static string CsvSeparator [get, set]
Static Private Member Functions
static void GetArguments (string commandLine, ref List< string > ret, ref List< string > aux)
Parses a command line and extracts arguments from it. Arguments can be separated according to usual rules for command-line arguments: spaces are separators, there can be arbitraty number of spaces, and if we want an argument to contain spaces, we must enclose it in double quotes. Command line can also contain the command name followed by arguments. In this case it is treated in the same way, and command can be obtained simply as the first string in the returned array.
Static Private Attributes
static int _maxStringLength = 100
Additional Inherited Members
Static Public Attributes inherited from IG.Lib.UtilCsv
const string DefaultCsvSeparator = ","
The default separator in the CSV files - comma (",").
static string _csvSeparator = DefaultCsvSeparator
Static Protected Member Functions inherited from IG.Lib.UtilCsv
static string TableToString (string[][] values, string valueSeparator)
Returns a string that represents a table of string values. Each value is embedded in double quotes, values are separated by commas, and tables of values are separated by newlines.
Detailed Description
Various string operations, random strings, random characters, etc.
$A Igor xx;
Definition at line 22 of file UtilString.cs.
Member Function Documentation
ArraysEqual< ElementType >()
static bool IG.Lib.UtilStr.ArraysEqual< ElementType > (ElementType[] originals, ElementType[] compared) inline static
Returns true if the specified arrays are equal (i.e. all corresponding values are equal or both arrays are null), false if not.
Parameters
originals First array of strings to be compared.
compared Second array of strings to be compared.
Type Constraints
ElementType : IComparable<ElementType>
Definition at line 44 of file UtilString.cs.
References IG.Lib.Default.
StringArraysEqual()
static bool IG.Lib.UtilStr.StringArraysEqual (string[] originals, string[] compared) inline static
Returns true if the specified string arrays are equal (i.e. all corresponding values are equal or both arrays are null), false if not.
Parameters
originals First array of strings to be compared.
compared Second array of strings to be compared.
Definition at line 72 of file UtilString.cs.
GetParametersArrayPlain()
static string [] IG.Lib.UtilStr.GetParametersArrayPlain (string listString) inline static
Returns a string array of parameters represented by the specified comma separated list in string form.
Parameters
listString List of parameters in string form, comma separated and with possible whitespaces between them.
Returns
Definition at line 101 of file UtilString.cs.
GetParametersStringPlain()
static string IG.Lib.UtilStr.GetParametersStringPlain (string[] parameters) inline static
Returns a string representation of the list of parameters, separated by commas but not embedded in any braces.
Parameters
parameters Array of parameters from which a comma separated list string is formed.
Definition at line 119 of file UtilString.cs.
Referenced by IG.Lib.ScalarFunctionLoader.GetParametersPlainListString().
GetLines()
static string [] IG.Lib.UtilStr.GetLines (string linesString, bool doTrim = true) inline static
Returns a string array of parameters represented by the specified comma separated list in string form.
Parameters
linesString List of parameters in string form, comma separated and with possible whitespaces between them.
doTrim Specifies whether parameter names should be trimmed.
Definition at line 138 of file UtilString.cs.
GetLinesStringPlain()
static string IG.Lib.UtilStr.GetLinesStringPlain (string[] lines) inline static
Returns a string representation of the list of lines, separated by newlines.
Parameters
lines Array of parameters from which a comma separated list string is formed.
Definition at line 159 of file UtilString.cs.
GetCommandLine() [1/2]
static string IG.Lib.UtilStr.GetCommandLine (string CommandName, string[] CommandArguments) inline static
Assembles and returns the commandline string that corresponds to the specified command name and arguments.
Parameters
CommandName Command name.
CommandArguments Array of command arguments.
Definition at line 185 of file UtilString.cs.
Referenced by IG.Lib.CommandLineApplicationInterpreter.CmdPipeClientGetServerResponse(), and IG.Lib.CommandLineJobContainer.CommandLine().
GetCommandLine() [2/2]
static string IG.Lib.UtilStr.GetCommandLine (string[] commandNameAndArguments) inline static
Assembles and returns the commandline string that corresponds to the specified command name and arguments.
Parameters
commandNameAndArguments Array containing command names (0-th element) and its arguments.
Definition at line 202 of file UtilString.cs.
GetArgumentsArray()
static string [] IG.Lib.UtilStr.GetArgumentsArray (string commandLine) inline static
Parses a command line and extracts arguments from it. Arguments can be separated according to usual rules for command-line arguments: spaces are separators, there can be arbitraty number of spaces, and if we want an argument to contain spaces, we must enclose it in double quotes. Command line can also contain the command name followed by arguments. In this case it is treated in the same way, and command can be obtained simply as the first string in the returned array.
Parameters
commandLine Command line that is split to individual arguments. Command line can also contain a command, which is treated equally.
Returns
An array of arguments.
Definition at line 226 of file UtilString.cs.
References IG.Lib.UtilStr.GetArguments().
Referenced by IG.Lib.CommandLineApplicationInterpreter.GetArguments(), and IG.Lib.CommandStackFrameBase.IsEventualListedCommand().
GetArguments() [1/2]
static void IG.Lib.UtilStr.GetArguments (string commandLine, ref List< string > ret) inline static
Parses a command line and extracts arguments from it. Arguments can be separated according to usual rules for command-line arguments: spaces are separators, there can be arbitraty number of spaces, and if we want an argument to contain spaces, we must enclose it in double quotes. Command line can also contain the command name followed by arguments. In this case it is treated in the same way, and command can be obtained simply as the first string in the returned array.
Parameters
commandLine Command line that is split to individual arguments. Command line can also contain a command, which is treated equally.
ret List in which the parsed arguments are stored.
Definition at line 246 of file UtilString.cs.
Referenced by IG.Lib.UtilStr.GetArgumentsArray().
GetArguments() [2/2]
static void IG.Lib.UtilStr.GetArguments (string commandLine, ref List< string > ret, ref List< string > aux) inline static private
Parses a command line and extracts arguments from it. Arguments can be separated according to usual rules for command-line arguments: spaces are separators, there can be arbitraty number of spaces, and if we want an argument to contain spaces, we must enclose it in double quotes. Command line can also contain the command name followed by arguments. In this case it is treated in the same way, and command can be obtained simply as the first string in the returned array.
Parameters
commandLine Command line that is split to individual arguments. Command line can also contain a command, which is treated equally.
ret List in which the parsed arguments are stored.
aux Auxiliary list for storing intermediate results.
Definition at line 262 of file UtilString.cs.
RandomUnicodeString() [1/2]
static string IG.Lib.UtilStr.RandomUnicodeString (int stringLength, IRandomGenerator rndgen = null) inline static
Creates and returns a valid random unicode string. All possible uncode characters may be contained in the generated string, EXCEPT the surogate characters in the range 0xD800-0xDFFF.
Unicode surrogate characters in the range 0xD800-0xDFFF (55296-57343) are not valid on their own. They must appear as a pair (0xD800-0xDBFF first, 0xDC00-0xDFFF second) in order to be valid (in the UTF-16 encoding scheme). Alone, they will be treated as invalid characters and decoded to 0xFFFD (65533). C# uses UTF-16 to represent its strings.
See also: http://stackoverflow.com/questions/12127843/generating-a-random-string
Parameters
stringLength Length of the returned string.
rndgen Random generator used. If null or unspecified then global random generator is used.
Definition at line 316 of file UtilString.cs.
RandomUnicodeString() [2/2]
static string IG.Lib.UtilStr.RandomUnicodeString (int stringLength, bool excludeSurrogates = true, IRandomGenerator rndgen = null) inline static
Creates and returns a valid random unicode string. All legal uncode characters may be contained in the generated string.
If surrogates are not excluded then it is not guaranteed that the returned string is og prescribed length.
Unicode surrogate characters in the range 0xD800-0xDFFF (55296-57343) are not valid on their own. They must appear as a pair (0xD800-0xDBFF first, 0xDC00-0xDFFF second) in order to be valid (in the UTF-16 encoding scheme). Alone, they will be treated as invalid characters and decoded to 0xFFFD (65533). C# uses UTF-16 to represent its strings.
See also: http://stackoverflow.com/questions/12127843/generating-a-random-string
Parameters
stringLength Length of the returned string.
excludeSurrogates If true then surrogate characters will not be included in the generated string.
rndgen Random generator used. If null or unspecified then global random generator is used.
Definition at line 332 of file UtilString.cs.
References IG.Num.RandomGenerator.Global.
RandomCharCapitalLetter()
static char IG.Lib.UtilStr.RandomCharCapitalLetter (IRandomGenerator rndgen = null) inline static
Returns a random character that is a capital letter (A-Z)
Parameters
rndgen Randomg generator used. If null or unspecified then global random generator is used.
Definition at line 368 of file UtilString.cs.
References IG.Num.RandomGenerator.Global.
Referenced by IG.Lib.UtilStr.RandomChar().
RandomCharSmallLetter()
static char IG.Lib.UtilStr.RandomCharSmallLetter (IRandomGenerator rndgen = null) inline static
Returns a random character that is a small letter (a-z)
Parameters
rndgen Random generator used. If null or unspecified then global random generator is used.
Definition at line 377 of file UtilString.cs.
References IG.Num.RandomGenerator.Global.
Referenced by IG.Lib.UtilStr.RandomChar().
RandomCharNumeric()
static char IG.Lib.UtilStr.RandomCharNumeric (IRandomGenerator rndgen = null) inline static
Returns a random numeric character (0-9)
Parameters
rndgen Random generator used. If null or unspecified then global random generator is used.
Definition at line 386 of file UtilString.cs.
References IG.Num.RandomGenerator.Global.
Referenced by IG.Lib.UtilStr.RandomChar().
RandomChar() [1/2]
static char IG.Lib.UtilStr.RandomChar (CharType typeflags, IRandomGenerator rndgen = null) inline static
Returns a random character whose type is specified by type flags. Type flags can be combined by bitwise operations.
Parameters
typeflags Flags specifying the permitted types of the returned character.
rndgen Random generator used. If null or unspecified then global random generator is used.
Returns
The randomly generated character.
Definition at line 399 of file UtilString.cs.
References IG.Num.RandomGenerator.Global, IG.Lib.UtilStr.RandomCharCapitalLetter(), IG.Lib.UtilStr.RandomCharNumeric(), and IG.Lib.UtilStr.RandomCharSmallLetter().
Referenced by IG.Lib.UtilStr.RandomChar(), IG.Lib.UtilStr.RandomString(), and IG.Lib.UtilConsole.ReadPwdBasic().
RandomChar() [2/2]
static char IG.Lib.UtilStr.RandomChar (IRandomGenerator rndgen = null) inline static
Returns a random character that is either a capital letter (A-Y) or a small letter (a-z). Type flags can be combined by bitwise operations.
Parameters
rndgen Random generator used. If null or unspecified then global random generator is used.
Returns
The randomly generated character.
Definition at line 457 of file UtilString.cs.
References IG.Num.RandomGenerator.Global, and IG.Lib.UtilStr.RandomChar().
RandomString() [1/6]
static string IG.Lib.UtilStr.RandomString (int length, CharType flags, bool firstletter, IRandomGenerator rndgen = null) inline static
Returns a randomly generated string of a specified length whose characters are of specified type(result). It can also be specified that the first character is a letter.
Parameters
length Length of the string.
flags Flags that determine permitted types of characters contained in the string.
firstletter If true then first character of the generated string will be a letter. Warning: when the value is true, make sure that either capital or small letters are permitted character type.
rndgen Random generator used. If null or unspecified then global random generator is used.
Returns
The generated random string.
Definition at line 472 of file UtilString.cs.
References IG.Lib.UtilStr.RandomChar().
Referenced by IG.Lib.UtilConsole.Examples(), and IG.Lib.UtilStr.RandomString().
RandomString() [2/6]
static string IG.Lib.UtilStr.RandomString (int length, CharType flags, IRandomGenerator rndgen = null) inline static
Returns a randomly generated string of a specified length whose characters are of specified type(result).
Parameters
length Length of the string. It is not guaranteed that the first character is a letter.
flags Flags that determine permitted types of characters contained in the string.
rndgen Random generator used. If null or unspecified then global random generator is used.
Returns
The generated random string.
Definition at line 491 of file UtilString.cs.
References IG.Lib.UtilStr.RandomString().
RandomString() [3/6]
static string IG.Lib.UtilStr.RandomString (int length, bool firstletter, IRandomGenerator rndgen = null) inline static
Returns a randomly generated string composed of alphanumeric characters. It can be specified that the first character is a letter.
Parameters
length Length of the string.
firstletter If true then first character of the generated string will be a letter.
rndgen Random generator used. If null or unspecified then global random generator is used.
Returns
The generated random string.
Definition at line 502 of file UtilString.cs.
References IG.Lib.UtilStr.RandomString().
RandomString() [4/6]
static string IG.Lib.UtilStr.RandomString (int length, IRandomGenerator rndgen = null) inline static
Returns a randomly generated string of a specified length containing alphanumeric characters. The first character is a letter.
Parameters
length Length of the string.
rndgen Random generator used. If null or unspecified then global random generator is used.
Returns
The generated random string.
Definition at line 513 of file UtilString.cs.
References IG.Lib.UtilStr.RandomString().
RandomString() [5/6]
static string IG.Lib.UtilStr.RandomString (IRandomGenerator rndgen = null) inline static
Returns a randomly generated string of a random length containing alphanumeric characters. The first character is a letter. Length is between 1 and the value specified by the MaxStringLength property.
Parameters
rndgen Random generator used. If null or unspecified then global random generator is used.
Returns
The generated random string.
Definition at line 525 of file UtilString.cs.
References IG.Num.RandomGenerator.Global, IG.Lib.UtilStr.MaxStringLength, IG.Num.IRandomGenerator.Next(), and IG.Lib.UtilStr.RandomString().
RandomString() [6/6]
static string IG.Lib.UtilStr.RandomString (int stringLength, string allowedChars = null, IRandomGenerator rndgen = null) inline static
Creates and returns a random string consisting of only the letters contained in the specified string.
Cryptographically secure random numbers are used to select characters for the password from the array of allowed characters.
Parameters
stringLength Length of the generated password.
allowedChars String containing allowed characters of the returned string.
By default (if parameter is null or empty string), these are digits and lower- and upper- case English letters.
Parameters
rndgen Random generator used. If null or unspecified then global random generator is used.
Returns
A random password of specified length.
Definition at line 542 of file UtilString.cs.
IsAscii()
static bool IG.Lib.UtilStr.IsAscii (char ch) inline static
Returns true if the specified character is an ASCII characters, and false otherwise.
Characters that qualify: from 0 to 255.
Parameters
ch Character that is querried.
Definition at line 565 of file UtilString.cs.
Referenced by IG.Lib.UtilStr.IsAsciiString().
IsAsciiLetter()
static bool IG.Lib.UtilStr.IsAsciiLetter (char ch) inline static
Returns true if the specified character is an ASCII letter, and false otherwise.
Characters that qualify: from 'a' to 'z' and from 'A' to 'Z'.
Parameters
ch Character that is querried.
Definition at line 572 of file UtilString.cs.
Referenced by IG.Lib.UtilStr.IsVarName().
IsAsciiDigit()
static bool IG.Lib.UtilStr.IsAsciiDigit (char ch) inline static
Returns true if the specified character is an ASCII digit, and false otherwise.
Characters that qualify: from '0' to '9'.
Parameters
ch Character that is querried.
Definition at line 580 of file UtilString.cs.
IsAsciiLetterOrDigit()
static bool IG.Lib.UtilStr.IsAsciiLetterOrDigit (char ch) inline static
Returns true if the specified character is either an ASCII letter or an ASCII digit, and false otherwise.
Characters that qualify: from 'a' to 'z', from 'A' to 'Z' and from '0' to '9'.
Parameters
ch Character that is querried.
Definition at line 589 of file UtilString.cs.
Referenced by IG.Lib.UtilStr.IsVarName().
IsVarName()
static bool IG.Lib.UtilStr.IsVarName (char[] str) inline static
Returns true if the string corresponding to the specified array of characters is a legal standard representation of a variable name, and false otherwise.
Parameters
str Array representation of the string that is queried.
Definition at line 603 of file UtilString.cs.
References IG.Lib.UtilStr.IsAsciiLetter(), and IG.Lib.UtilStr.IsAsciiLetterOrDigit().
Referenced by IG.Lib.UtilStr.IsVariableName().
IsVariableName()
static bool IG.Lib.UtilStr.IsVariableName (string str) inline static
Returns true if the specified string is a legal standard representation of a variable name, and false otherwise.
Parameters
str String that is queried.
Definition at line 628 of file UtilString.cs.
References IG.Lib.UtilStr.IsVarName().
Referenced by IG.Num.InputOutputDataDefiniton.GetElementNameParameters().
IsAsciiString() [1/2]
static bool IG.Lib.UtilStr.IsAsciiString (char[] str) inline static
Returns true if the string corresponding to the specified array of characters is an ASCII string (i.e. it contains only ASCII characters - from 0 to 255), and false otherwise.
True is returned for null or empty strings.
Parameters
str Array representation of the string that is queried.
Definition at line 640 of file UtilString.cs.
References IG.Lib.UtilStr.IsAscii().
Referenced by IG.Lib.UtilStr.IsAsciiString().
IsAsciiString() [2/2]
static bool IG.Lib.UtilStr.IsAsciiString (string str) inline static
Returns true if the string specified string is an ASCII string (i.e. it contains only ASCII characters - from 0 to 255), and false otherwise.
Parameters
str String that is queried.
Definition at line 662 of file UtilString.cs.
References IG.Lib.UtilStr.IsAsciiString().
ToBoolean()
static bool IG.Lib.UtilStr.ToBoolean (string strsetting) inline static
Converts a string representation of a boolean setting to boolean.
Strings "true", "yes" and "on" (regardless of capitalization) or non-zero integer representations result to true, "false", "no", "off" or zero integer representations result in false.
Parameters
strsetting String representation of the specific setting.
Exceptions
InvalidDataException if the string is not one of recognized representation of a boolean.
Returns
Boolean value corresponding to the setting.
Definition at line 682 of file UtilString.cs.
Referenced by IG.Crypto.CryptoManager.AppGetFileHash(), IG.Script.ScriptAppBase.CryptoFunctionGetFileHash_OLD_TO_DELETE(), IG.Num.AnalysisResults.GetAnalysisRequest(), IG.Num.AnalysisResults.GetAnalysisResult(), IG.Lib.SettingsReaderBase.GetBooleanSetting(), and IG.Lib.UtilStr.IsBoolean().
IsBoolean()
static bool IG.Lib.UtilStr.IsBoolean (string str) inline static
Returns a boolean value indicating whether the specified string can represent a boolean value.
Strings "true", "yes" and "on" (regardless of capitalization) or non-zero integer representations result to true, "false", "no", "off" or zero integer representations result in false.
This method is NOT CONSISTENT with bool.TryParse but with UtilStr.ToBoolean.
Parameters
str String that is checked if it can represent a boolean value.
Returns
Definition at line 724 of file UtilString.cs.
References IG.Lib.UtilStr.ToBoolean().
ToInt() [1/2]
static long IG.Lib.UtilStr.ToInt (string strsetting) inline static
Converts a string representation of an integer setting to an integer value. If the setting is not defined then 0 is returned.
Parameters
strsetting String representation of the specific setting.
Returns
Long integer value corresponding to the setting.
Definition at line 743 of file UtilString.cs.
Referenced by IG.Lib.SettingsReaderBase.GetIntegerSetting().
ToInt() [2/2]
static long IG.Lib.UtilStr.ToInt (string strsetting, long defaultvalue) inline static
Converts a string representation of an integer setting to an integer value.
Parameters
strsetting String representation of the specific setting.
defaultvalue Default value returned in the case that the setting is not defined.
Returns
Long integer value corresponding to the setting.
Definition at line 752 of file UtilString.cs.
IsInt()
static bool IG.Lib.UtilStr.IsInt (string str) inline static
Returns a boolean value indicating whether the specified string is a valid representation of an integer number.
Parameters
str String that is checked.
Definition at line 763 of file UtilString.cs.
ToDouble() [1/2]
static double IG.Lib.UtilStr.ToDouble (string strsetting) inline static
Converts a string representation of a double setting to an integer value. If the setting is not defined then 0 is returned.
Parameters
strsetting String representation of the value.
Returns
Long integer value corresponding to the setting.
Definition at line 773 of file UtilString.cs.
ToDouble() [2/2]
static double IG.Lib.UtilStr.ToDouble (string strsetting, long defaultvalue) inline static
Converts a string representation of a double value to a number of type double.
Parameters
strsetting String representation of the value.
defaultvalue Default value returned in the case that the string is null or empty.
Returns
Long integer value corresponding to the setting.
Definition at line 782 of file UtilString.cs.
IsDouble()
static bool IG.Lib.UtilStr.IsDouble (string str) inline static
Returns a boolean value indicating whether the specified string is a valid representation of a number (of type double).
Parameters
str String that is checked.
Definition at line 794 of file UtilString.cs.
Load() [1/2]
static string IG.Lib.UtilStr.Load (string filePath) inline static
Loads complete file contents into a stiring and returnes that string.
Parameters
filePath Path to the file that is red into a string.
Definition at line 808 of file UtilString.cs.
Referenced by IG.Lib.UtilStr.Load(), and IG.Lib.UtilCsv.LoadCsv().
Load() [2/2]
static void IG.Lib.UtilStr.Load (string filePath, ref string readString) inline static
Loads complete file contents into the specified stiring.
Parameters
filePath Path to the file that is red into a string.
readString String variable where file contents is stored.
Definition at line 822 of file UtilString.cs.
References IG.Lib.UtilStr.Load().
Save() [1/2]
static void IG.Lib.UtilStr.Save (string str, string filePath, bool append) inline static
Saves the specified string to a specified file. If the specified file does not exists then it is created anew if possible. A boolean argument specifis whether to overwrite existing files or to append the string at the end of the file.
Parameters
str String to be saved to a file.
filePath Path to the file where string is to be saved.
append If true then the string is appended at the end of the file in the case that the file already exists. If false then the file is overwritten in the case taht it already exists.
Definition at line 835 of file UtilString.cs.
Referenced by IG.Lib.UtilStr.Append(), IG.Lib.UtilStr.Save(), and IG.Lib.UtilCsv.SaveCsv().
Save() [2/2]
static void IG.Lib.UtilStr.Save (string str, string filePath) inline static
Saves the specified string to a specified file. If the file already exists then is content is overwritten. If the file does not yet exist then it is created anew.
Parameters
str String to be written to a file.
filePath Path to the file where string is written.
Definition at line 848 of file UtilString.cs.
References IG.Lib.UtilStr.Save().
Append()
static void IG.Lib.UtilStr.Append (string str, string filePath) inline static
Saves the specified string to a specified file. If the file already exists then string is appended at the end of the current file contents. If the file does not yet exist then it is created anew.
Parameters
str String to be written to a file.
filePath Path to the file where string is written.
Definition at line 856 of file UtilString.cs.
References IG.Lib.UtilStr.Save().
Member Data Documentation
_maxStringLength
int IG.Lib.UtilStr._maxStringLength = 100 static private
Definition at line 26 of file UtilString.cs.
Property Documentation
MaxStringLength
int IG.Lib.UtilStr.MaxStringLength static get set
Get or sets maximal length for generated strings (must be GREATER THAN 0).
Definition at line 30 of file UtilString.cs.
Referenced by IG.Lib.UtilStr.RandomString().
The documentation for this class was generated from the following file:
iglib/igbase/utilities/UtilString.cs