Doc: IGLib with source files: LearnCs.Lib.NumberOperationsComplex Class Reference
LearnCs.Lib.NumberOperationsComplex Class Reference
Implementation of INumberOperations<ElementType> for type Complex.
Public Member Functions
Complex AddNumbers (Complex a, Complex b)
Complex SubtractNumbers (Complex a, Complex b)
Complex MultiplyNumbers (Complex a, Complex b)
Complex DivideNumbers (Complex a, Complex b)
Complex GetModulusNumber (Complex a, Complex b)
bool AreEqual (Complex a, Complex b)
Complex NegativeNumber (Complex a)
Complex ConjugateNumber (Complex a)
Complex Absolute (Complex a)
Complex AbsoluteSquare (Complex a)
Complex Sqrt (Complex a)
Complex Root (Complex a, int n)
Complex Pow (Complex a, int n)
Public Member Functions inherited from LearnCs.Lib.INumberOperations< Complex >
NumberType AddNumbers (NumberType a, NumberType b)
Calculates and returns sum of parameters a and b .
NumberType SubtractNumbers (NumberType a, NumberType b)
Calculates and returns difference of parameters a and b .
NumberType MultiplyNumbers (NumberType a, NumberType b)
Calculates and returns product of parameters a and b .
NumberType DivideNumbers (NumberType a, NumberType b)
Calculates and returns quotient of parameters a and b .
NumberType GetModulusNumber (NumberType a, NumberType b)
Calculates and returns modulus of division of parameters a and b . This operation has an important meaning for integer types, while for floating-pont and complex types it always returns 0.
bool AreEqual (NumberType a, NumberType b)
Returns if number a is equal to number b, false otherwise.
NumberType NegativeNumber (NumberType a)
Returns negative value of parameter a .
NumberType ConjugateNumber (NumberType a)
Returns conjugate value of parameter a . This operation has an important meaning for complex numbers (e.g., NumberType = Complex), while for usual number types it returns the parameter itself (it is identity).
NumberType Absolute (NumberType a)
Returns magnitude, or absolute value, of a
NumberType AbsoluteSquare (NumberType a)
Returns square of the absolute value of a .
Returns
Square of absolute value (magnitude) of a .
NumberType Sqrt (NumberType a)
Returns square root of a .
Returns
Square root of a .
NumberType Root (NumberType a, int n)
Returns n-th root (root with index n) of a .
Returns
Root with index n of a .
NumberType Pow (NumberType a, int n)
Returns a raised to the integer power n .
Returns
a raised to n .
Properties
static NumberOperationsComplex Instance = new NumberOperationsComplex() [get]
Gets a global instance of NumberOperationsComplex that can be used anywhere it is needed. Because the class is thread safe, this same instance can be used in any number of places.
Detailed Description
Implementation of INumberOperations<ElementType> for type Complex.
Definition at line 13 of file NumberOperationsComplex.cs.
Member Function Documentation
AddNumbers()
Complex LearnCs.Lib.NumberOperationsComplex.AddNumbers (Complex a, Complex b) inline
Definition at line 17 of file NumberOperationsComplex.cs.
SubtractNumbers()
Complex LearnCs.Lib.NumberOperationsComplex.SubtractNumbers (Complex a, Complex b) inline
Definition at line 23 of file NumberOperationsComplex.cs.
MultiplyNumbers()
Complex LearnCs.Lib.NumberOperationsComplex.MultiplyNumbers (Complex a, Complex b) inline
Definition at line 29 of file NumberOperationsComplex.cs.
DivideNumbers()
Complex LearnCs.Lib.NumberOperationsComplex.DivideNumbers (Complex a, Complex b) inline
Definition at line 35 of file NumberOperationsComplex.cs.
GetModulusNumber()
Complex LearnCs.Lib.NumberOperationsComplex.GetModulusNumber (Complex a, Complex b) inline
Definition at line 41 of file NumberOperationsComplex.cs.
AreEqual()
bool LearnCs.Lib.NumberOperationsComplex.AreEqual (Complex a, Complex b) inline
Definition at line 47 of file NumberOperationsComplex.cs.
NegativeNumber()
Complex LearnCs.Lib.NumberOperationsComplex.NegativeNumber (Complex a) inline
Definition at line 53 of file NumberOperationsComplex.cs.
ConjugateNumber()
Complex LearnCs.Lib.NumberOperationsComplex.ConjugateNumber (Complex a) inline
Definition at line 59 of file NumberOperationsComplex.cs.
References LearnCs.Lib.Complex.Conjugate.
Absolute()
Complex LearnCs.Lib.NumberOperationsComplex.Absolute (Complex a) inline
Definition at line 65 of file NumberOperationsComplex.cs.
References LearnCs.Lib.Complex.AbsoluteValue.
AbsoluteSquare()
Complex LearnCs.Lib.NumberOperationsComplex.AbsoluteSquare (Complex a) inline
Definition at line 71 of file NumberOperationsComplex.cs.
Sqrt()
Complex LearnCs.Lib.NumberOperationsComplex.Sqrt (Complex a) inline
Definition at line 77 of file NumberOperationsComplex.cs.
References LearnCs.Lib.Complex.Pow().
Root()
Complex LearnCs.Lib.NumberOperationsComplex.Root (Complex a, int n) inline
Definition at line 83 of file NumberOperationsComplex.cs.
References LearnCs.Lib.Complex.Pow().
Pow()
Complex LearnCs.Lib.NumberOperationsComplex.Pow (Complex a, int n) inline
Definition at line 89 of file NumberOperationsComplex.cs.
References LearnCs.Lib.Complex.Pow().
Property Documentation
Instance
NumberOperationsComplex LearnCs.Lib.NumberOperationsComplex.Instance = new NumberOperationsComplex() static get
Gets a global instance of NumberOperationsComplex that can be used anywhere it is needed. Because the class is thread safe, this same instance can be used in any number of places.
Definition at line 96 of file NumberOperationsComplex.cs.
The documentation for this class was generated from the following file:
IGLibCore/tests/IGLib.TestBase/SampleClasses/NumberOperationsComplex.cs