Doc: IGLib with source files: IG.Num.RandomGaussian Class Reference
IG.Num.RandomGaussian Class Reference
Gaussian random number generator.
Public Member Functions
RandomGaussian (IRandomGenerator random=null)
double NextGaussian (double mean=0, double sigma=1)
Obtains normally (Gaussian) distributed random numbers, using the Box-Muller transformation. This transformation takes two uniformly distributed deviates within the unit circle, and transforms them into two independently distributed normal deviates.
Static Protected Attributes
static object _lockStatic = new object()
static RandomGaussian _global
Properties
static RandomGaussian Global [get]
Global Gaussian random generator.
Private Member Functions
void Test ()
Private Attributes
bool _hasDeviate
double _storedDeviate
readonly IRandomGenerator _random
Detailed Description
Gaussian random number generator.
Definition at line 17 of file RandomGaussian.cs.
Constructor & Destructor Documentation
RandomGaussian()
IG.Num.RandomGaussian.RandomGaussian (IRandomGenerator random = null) inline
Definition at line 24 of file RandomGaussian.cs.
References IG.Num.RandomGaussian._random.
Member Function Documentation
Test()
void IG.Num.RandomGaussian.Test () inline private
Definition at line 19 of file RandomGaussian.cs.
References IG.Num.RandomGenerator.Global.
NextGaussian()
double IG.Num.RandomGaussian.NextGaussian (double mean = 0, double sigma = 1) inline
Obtains normally (Gaussian) distributed random numbers, using the Box-Muller transformation. This transformation takes two uniformly distributed deviates within the unit circle, and transforms them into two independently distributed normal deviates.
Parameters
mean The mean of the distribution. Default is zero.
sigma The standard deviation of the distribution. Default is one.
Returns
Definition at line 65 of file RandomGaussian.cs.
References IG.Num.RandomGaussian._hasDeviate, IG.Num.RandomGaussian._random, IG.Num.RandomGaussian._storedDeviate, and IG.Num.IRandomGenerator.NextDouble().
Referenced by IG.Num.M.randgauss(), and IG.Num.MExt.RandGauss().
Member Data Documentation
_lockStatic
object IG.Num.RandomGaussian._lockStatic = new object() static protected
Definition at line 31 of file RandomGaussian.cs.
_global
RandomGaussian IG.Num.RandomGaussian._global static protected
Definition at line 33 of file RandomGaussian.cs.
_hasDeviate
bool IG.Num.RandomGaussian._hasDeviate private
Definition at line 52 of file RandomGaussian.cs.
Referenced by IG.Num.RandomGaussian.NextGaussian().
_storedDeviate
double IG.Num.RandomGaussian._storedDeviate private
Definition at line 53 of file RandomGaussian.cs.
Referenced by IG.Num.RandomGaussian.NextGaussian().
_random
readonly IRandomGenerator IG.Num.RandomGaussian._random private
Definition at line 54 of file RandomGaussian.cs.
Referenced by IG.Num.RandomGaussian.NextGaussian(), and IG.Num.RandomGaussian.RandomGaussian().
Property Documentation
Global
RandomGaussian IG.Num.RandomGaussian.Global static get
Global Gaussian random generator.
Definition at line 37 of file RandomGaussian.cs.
Referenced by IG.Num.M.randgauss(), and IG.Num.MExt.RandGauss().
The documentation for this class was generated from the following file:
IGLibCore/src/IGLib.Core/MathUtils/RandomGaussian.cs