Doc: IGLib with source files: IGLib.Testing.Tests.SpeedTests Class Reference
IGLib.Testing.Tests.SpeedTests Class Reference
Public Member Functions
SpeedTests (ITestOutputHelper output)
This constructor, when called by the test framework, will bring in an object of type ITestOutputHelper, which will be used to write on the tests' output, accessed through the base class's Output property.
void StandardSpeedTestGeometricSeries_HpLaptop24 ()
Performs the stanard speed test with calculation of a finite geometric series, with standard parameters, and reports the resutlrs.
void StandardSpeedTestGeometricSeries_DirectElementCalculation_HpLaptop24 ()
Performs the stanard speed test with calculation of a finite geometric series, with standard parameters, with direct calculation of elements of geometric series (using Math.Pow, which is slower than accummulating the powers of the quotient), and reports the resutlrs.
void Legacy_StandardSpeedTestGeometricSeries_OLD ()
Performs the stanard speed test with calculation of a finite geometric series, with standard parameters, and reports the resutlrs.
void Legacy_StandardSpeedTestGeometricSeries_DirectElementCalculation_OLD ()
Performs the stanard speed test with calculation of a finite geometric series, with standard parameters, but with directly calculating each term by using Math.Pow(double, double) rather than accumulating sequence elements iteratively.
Public Member Functions inherited from IGLib.Tests.Base.TestBase< SpeedTests >
TestBase (ITestOutputHelper output, bool assignConsole=true)
Additional Inherited Members
Protected Attributes inherited from IGLib.Tests.Base.TestBase< SpeedTests >
string ExportPathIGLibTemporary
Static Protected Attributes inherited from IGLib.Tests.Base.TestBase< SpeedTests >
const string DefaultExportPathIGLib
Default export path for tests that generate output. Specified relative to the currennt directory of test execution, which is usually a subdirectory of the [ProjectDir]/bin/ .
Properties inherited from IGLib.Tests.Base.TestBase< SpeedTests >
string ExportPathIGLib [get, set]
Export path for tests that generate output files. This is set to IGLibDefaultExportPath by default (good for most cases), but this can be overridden in test class's constructor.
ITestOutputHelper Output [get, set]
Enables writing to tests' output. Provided by the framework (injected via constructor).
static ITestOutputHelper Console [get, set]
This property makes possible to use the name Console instead of Output in test method of this class, such that code can be directly copied to console applications while output is still visible in tests' output. Unfortunately, you cannot use Console.Write(...) because the ITestOutputHelper does not have it.
LoggerFactory LoggerFactory [get, set]
Detailed Description
This test class performs various speed tests, which give some indication of the current host machine's performance.
This test class inherits from TestBase<ExampleTestClass>, from which it inherits properties TestBase<TestClass>.Output and its alias TestBase<TestClass>.Console of type ITestOutputHelper, which can be used to write on test's output. Only the simple ITestOutputHelper.WriteLine(string) and ITestOutputHelper.WriteLine(string, object[]) methods are available for writing to test Output.
Definition at line 26 of file SpeedTests.cs.
Constructor & Destructor Documentation
SpeedTests()
IGLib.Testing.Tests.SpeedTests.SpeedTests (ITestOutputHelper output) inline
This constructor, when called by the test framework, will bring in an object of type ITestOutputHelper, which will be used to write on the tests' output, accessed through the base class's Output property.
Definition at line 32 of file SpeedTests.cs.
Member Function Documentation
StandardSpeedTestGeometricSeries_HpLaptop24()
void IGLib.Testing.Tests.SpeedTests.StandardSpeedTestGeometricSeries_HpLaptop24 () inline
Performs the stanard speed test with calculation of a finite geometric series, with standard parameters, and reports the resutlrs.
Definition at line 47 of file SpeedTests.cs.
References IGLib.Tests.Base.TestBase< SpeedTests >.Console, and IGLib.Tests.UtilSpeedTesting.StandardSpeedTestGeometricSeries_HpLaptop24().
StandardSpeedTestGeometricSeries_DirectElementCalculation_HpLaptop24()
void IGLib.Testing.Tests.SpeedTests.StandardSpeedTestGeometricSeries_DirectElementCalculation_HpLaptop24 () inline
Performs the stanard speed test with calculation of a finite geometric series, with standard parameters, with direct calculation of elements of geometric series (using Math.Pow, which is slower than accummulating the powers of the quotient), and reports the resutlrs.
Definition at line 63 of file SpeedTests.cs.
References IGLib.Tests.Base.TestBase< SpeedTests >.Console, and IGLib.Tests.UtilSpeedTesting.StandardSpeedTestGeometricSeries_DirectElementCalculation_HpLaptop24().
Legacy_StandardSpeedTestGeometricSeries_OLD()
void IGLib.Testing.Tests.SpeedTests.Legacy_StandardSpeedTestGeometricSeries_OLD () inline
Performs the stanard speed test with calculation of a finite geometric series, with standard parameters, and reports the resutlrs.
This test can be deleted (it already has a replacement).
Definition at line 91 of file SpeedTests.cs.
References IGLib.Tests.Base.TestBase< SpeedTests >.Console, IGLib.Tests.UtilSpeedTesting.GeometricSeriesAnalytical(), and IGLib.Tests.UtilSpeedTesting.GeometricSeriesNumerical().
Legacy_StandardSpeedTestGeometricSeries_DirectElementCalculation_OLD()
void IGLib.Testing.Tests.SpeedTests.Legacy_StandardSpeedTestGeometricSeries_DirectElementCalculation_OLD () inline
Performs the stanard speed test with calculation of a finite geometric series, with standard parameters, but with directly calculating each term by using Math.Pow(double, double) rather than accumulating sequence elements iteratively.
This test can be deleted (it already has a replacement).
Definition at line 134 of file SpeedTests.cs.
References IGLib.Tests.Base.TestBase< SpeedTests >.Console, IGLib.Tests.UtilSpeedTesting.GeometricSeriesAnalytical(), and IGLib.Tests.UtilSpeedTesting.GeometricSeriesNumerical_DirectElementCalculation().
The documentation for this class was generated from the following file:
IGLibCore/tests/IGLib.Core.Tests/Testing/SpeedTests.cs