Doc: IGLib with source files: IGLib.Gr3D.MeshExportExtensions_02 Class Reference
IGLib.Gr3D.MeshExportExtensions_02 Class Reference
Static Public Member Functions
static void ExportToObj (this StructuredMesh3D_02 mesh, string objFilePath, string materialName="defaultMaterial", string mtlFilePath=null)
Exports the mesh to an OBJ file with an optional MTL file for materials.
static void ExportToStl (this StructuredMesh3D_02 mesh, string stlFilePath)
Exports the mesh to a binary STL file.
Static Private Member Functions
static void ExportMaterialFile (string mtlFilePath, string materialName)
Creates a simple MTL file for OBJ materials.
static void WriteTriangle (BinaryWriter writer, vec3 v1, vec3 v2, vec3 v3)
Writes a single triangle to the STL file.
Detailed Description
Definition at line 11 of file MeshExportExtensions_02.cs.
Member Function Documentation
ExportToObj()
static void IGLib.Gr3D.MeshExportExtensions_02.ExportToObj (this StructuredMesh3D_02 mesh, string objFilePath, string materialName = "defaultMaterial", string mtlFilePath = null) inline static
Exports the mesh to an OBJ file with an optional MTL file for materials.
Definition at line 16 of file MeshExportExtensions_02.cs.
References IGLib.Gr3D.MeshExportExtensions_02.ExportMaterialFile(), IGLib.Gr3D.StructuredMesh3D_02.Nodes, IGLib.Gr3D.StructuredMesh3D_02.NumPoints1, and IGLib.Gr3D.StructuredMesh3D_02.NumPoints2.
ExportMaterialFile()
static void IGLib.Gr3D.MeshExportExtensions_02.ExportMaterialFile (string mtlFilePath, string materialName) inline static private
Creates a simple MTL file for OBJ materials.
Definition at line 61 of file MeshExportExtensions_02.cs.
Referenced by IGLib.Gr3D.MeshExportExtensions_02.ExportToObj().
ExportToStl()
static void IGLib.Gr3D.MeshExportExtensions_02.ExportToStl (this StructuredMesh3D_02 mesh, string stlFilePath) inline static
Exports the mesh to a binary STL file.
Definition at line 78 of file MeshExportExtensions_02.cs.
References IGLib.Gr3D.StructuredMesh3D_02.GetQuadrilateral(), IGLib.Gr3D.StructuredMesh3D_02.NumPoints1, IGLib.Gr3D.StructuredMesh3D_02.NumPoints2, and IGLib.Gr3D.MeshExportExtensions_02.WriteTriangle().
WriteTriangle()
static void IGLib.Gr3D.MeshExportExtensions_02.WriteTriangle (BinaryWriter writer, vec3 v1, vec3 v2, vec3 v3) inline static private
Writes a single triangle to the STL file.
Definition at line 105 of file MeshExportExtensions_02.cs.
References IG.Num.vec3.Cross(), IG.Num.vec3.Normalize(), IG.Num.vec3.x, IG.Num.vec3.y, and IG.Num.vec3.z.
Referenced by IGLib.Gr3D.MeshExportExtensions_02.ExportToStl().
The documentation for this class was generated from the following file:
IGLibGraphics3D/src/IGLib.Graphics3D/Graphics3D/Historical/MeshExportExtensions_02.cs