Doc: IGLib with source files: IG.Num.MExt Class Reference
IG.Num.MExt Class Reference
Defines some mathematical functions to be used in derived classes. In addition to functions defined in the M class, functions are defined under other names, and some additional functions are also defined.
Static Public Member Functions
static double Abs (double a)
Absolute value.
static double Sign (double a)
Returns a value indicating the sign of a number.
static double sgn (double a)
Returns a value indicating the sign of a number.
static double Ceiling (double a)
Returns the smallest integral value that is greater than or equal to the specified decimal number.
static double ceiling (double a)
Returns the smallest integral value that is greater than or equal to the specified decimal number.
static double Floor (double a)
Returns the largest integer less than or equal to the specified number.
static double Truncate (double a)
Calculates the integral part of a specified double-precision floating-point number.
static double truncate (double a)
Calculates the integral part of a specified number.
static double Min (double a, double b)
Smallest of two numbers.
static double Max (double a, double b)
Largest of two numbers.
static double Min (double a, double b, double c)
Smallest of three numbers.
static double Max (double a, double b, double c)
Largest of three numbers.
static double Min (double a, double b, double c, double d)
Smallest of four numbers.
static double Max (double a, double b, double c, double d)
Largest of four numbers.
static double Min (double a, double b, double c, double d, double e)
Smallest of five numbers.
static double Max (double a, double b, double c, double d, double e)
Largest of five numbers.
static double Min (double a, double b, double c, double d, double e, double f)
Smallest of six numbers.
static double Max (double a, double b, double c, double d, double e, double f)
Largest of six numbers.
static double Min (params double[] numbers)
Minimal of the specified values.
static double Max (params double[] numbers)
Maximal of the specified values.
static double product (params double[] numbers)
Product of the specified values.
static double Pow (double a, double b)
Returns a specified number raised to the specified power.
static double Sqr (double a)
Returns the square of a specified number.
static double Cube (double a)
Returns the square of a specified number.
static double Pow2 (double x)
Square.
static double Pow3 (double x)
3rd power.
static double Pow4 (double x)
4th power.
static double Pow5 (double x)
5th power.
static double Pow6 (double x)
6th power.
static double Sqrt (double a)
Returns the square root of a specified number.
static double Root2 (double a)
Returns the square root of a specified number.
static double Root3 (double a)
Returns the cubic root of a specified number.
static double Rand ()
Returns a uniformly distributed random number greater than or equal to 0.0, and less or equal than 1.0.
static double Rand (double min, double max)
Returns a uniformly distributed random number greater than or equal to min, and less or equal than max.
static double RandGauss (double mean, double standardDeviation)
Returns a Gaussian distributed random number with the specified mean and standard deviation.
static double Exp (double a)
Returns e raised to the specified power.
static double Log (double a)
Returns the natural (base e) logarithm of a specified number.
static double Log10 (double a)
Returns the base 10 logarithm of a specified number.
static double Log2 (double a)
Returns the base 2 logarithm of a specified number.
static double Log (double a, double logBase)
Returns the logarithm of a specified number in a specified base.
static double Degrees (double x)
Converts angle in radians to angle in degrees and returns it.
static double Radians (double x)
Converts angle in degrees to angle in radians and returns it.
static double Sin (double a)
Returns the sine of the specified angle.
static double Cos (double a)
Returns the cosine of the specified angle.
static double Tan (double a)
Returns the tangent of the specified angle.
static double tan (double a)
Returns the tangent of the specified angle.
static double Cot (double x)
Returns cotangent of the specified angle.
static double Acos (double a)
Returns the angle whose cosine is the specified number.
static double acos (double a)
Returns the angle whose cosine is the specified number.
static double Asin (double a)
Returns the angle whose sine is the specified number.
static double asin (double a)
Returns the angle whose sine is the specified number.
static double Atan (double a)
Returns the angle whose tangent is the specified number.
static double atan (double a)
Returns the angle whose tangent is the specified number.
static double arctan (double a)
Returns the angle whose tangent is the specified number.
static double Acot (double x)
Arc cotangent, inverse of 1/tan(x).
static double acot (double x)
Arc cotangent, inverse of 1/tan(x).
static double ArcCot (double x)
Arc cotangent, inverse of 1/tan(x).
static double arccot (double x)
Arc cotangent, inverse of 1/tan(x).
static double Atan2 (double a, double b)
Returns the angle whose tangent is the quotient of two specified numbers.
static double atan2 (double a, double b)
Returns the angle whose tangent is the quotient of two specified numbers.
static double arctan2 (double a, double b)
Returns the angle whose tangent is the quotient of two specified numbers.
static double Cosh (double a)
Returns the hyperbolic cosine of the specified angle.
static double cosh (double a)
Returns the hyperbolic cosine of the specified angle.
static double Tanh (double a)
Returns the hyperbolic tangent of the specified angle.
static double tanh (double a)
Returns the hyperbolic tangent of the specified angle.
static double Coth (double x)
Hyperblic cotangent, 1/Math.Tanh.
static double coth (double x)
Hyperblic cotangent, 1/Math.Tanh.
static double Arsinh (double x)
Inverse hyperbolic sine.
static double Arcosh (double x)
Inverse hyperbolic cosine.
static double Artanh (double x)
Inverse hyperbolic tangent.
static double Arcoth (double x)
Inverse hyperbolic cotangent.
static long Factorial (int factor)
Returns factorial of the specified number.
static long factorial (int factor)
Returns factorial of the specified number.
static long BinomialCoefficient (long n, long k)
Returns binomial coefficient n over k .
static double Abs (double a)
Absolute value.
static double Sign (double a)
Returns a value indicating the sign of a number.
static double sgn (double a)
Returns a value indicating the sign of a number.
static double Ceiling (double a)
Returns the smallest integral value that is greater than or equal to the specified decimal number.
static double ceiling (double a)
Returns the smallest integral value that is greater than or equal to the specified decimal number.
static double Floor (double a)
Returns the largest integer less than or equal to the specified number.
static double Truncate (double a)
Calculates the integral part of a specified double-precision floating-point number.
static double truncate (double a)
Calculates the integral part of a specified number.
static double Min (double a, double b)
Smallest of two numbers.
static double Max (double a, double b)
Largest of two numbers.
static double Min (double a, double b, double c)
Smallest of three numbers.
static double Max (double a, double b, double c)
Largest of three numbers.
static double Min (double a, double b, double c, double d)
Smallest of four numbers.
static double Max (double a, double b, double c, double d)
Largest of four numbers.
static double Min (double a, double b, double c, double d, double e)
Smallest of five numbers.
static double Max (double a, double b, double c, double d, double e)
Largest of five numbers.
static double Min (double a, double b, double c, double d, double e, double f)
Smallest of six numbers.
static double Max (double a, double b, double c, double d, double e, double f)
Largest of six numbers.
static double Min (params double[] numbers)
Minimal of the specified values.
static double Max (params double[] numbers)
Maximal of the specified values.
static double Sum (params double[] numbers)
Sum of the specified values.
static double Product (params double[] numbers)
Product of the specified values.
static double product (params double[] numbers)
Product of the specified values.
static double Pow (double a, double b)
Returns a specified number raised to the specified power.
static double Sqr (double a)
Returns the square of a specified number.
static double Cube (double a)
Returns the square of a specified number.
static double Pow2 (double x)
Square.
static double Pow3 (double x)
3rd power.
static double Pow4 (double x)
4th power.
static double Pow5 (double x)
5th power.
static double Pow6 (double x)
6th power.
static double Sqrt (double a)
Returns the square root of a specified number.
static double Root2 (double a)
Returns the square root of a specified number.
static double Root3 (double a)
Returns the cubic root of a specified number.
static double Rand ()
Returns a uniformly distributed random number greater than or equal to 0.0, and less or equal than 1.0.
static double Rand (double min, double max)
Returns a uniformly distributed random number greater than or equal to min, and less or equal than max.
static double RandGauss (double mean, double standardDeviation)
Returns a Gaussian distributed random number with the specified mean and standard deviation.
static double Exp (double a)
Returns e raised to the specified power.
static double Log (double a)
Returns the natural (base e) logarithm of a specified number.
static double Log10 (double a)
Returns the base 10 logarithm of a specified number.
static double Log2 (double a)
Returns the base 2 logarithm of a specified number.
static double Log (double a, double logBase)
Returns the logarithm of a specified number in a specified base.
static double Degrees (double x)
Converts angle in radians to angle in degrees and returns it.
static double Radians (double x)
Converts angle in degrees to angle in radians and returns it.
static double Sin (double a)
Returns the sine of the specified angle.
static double Cos (double a)
Returns the cosine of the specified angle.
static double Tan (double a)
Returns the tangent of the specified angle.
static double tan (double a)
Returns the tangent of the specified angle.
static double Cot (double x)
Returns cotangent of the specified angle.
static double Acos (double a)
Returns the angle whose cosine is the specified number.
static double acos (double a)
Returns the angle whose cosine is the specified number.
static double Asin (double a)
Returns the angle whose sine is the specified number.
static double asin (double a)
Returns the angle whose sine is the specified number.
static double Atan (double a)
Returns the angle whose tangent is the specified number.
static double atan (double a)
Returns the angle whose tangent is the specified number.
static double arctan (double a)
Returns the angle whose tangent is the specified number.
static double Acot (double x)
Arc cotangent, inverse of 1/tan(x).
static double acot (double x)
Arc cotangent, inverse of 1/tan(x).
static double ArcCot (double x)
Arc cotangent, inverse of 1/tan(x).
static double arccot (double x)
Arc cotangent, inverse of 1/tan(x).
static double Atan2 (double a, double b)
Returns the angle whose tangent is the quotient of two specified numbers.
static double atan2 (double a, double b)
Returns the angle whose tangent is the quotient of two specified numbers.
static double arctan2 (double a, double b)
Returns the angle whose tangent is the quotient of two specified numbers.
static double Cosh (double a)
Returns the hyperbolic cosine of the specified angle.
static double cosh (double a)
Returns the hyperbolic cosine of the specified angle.
static double Tanh (double a)
Returns the hyperbolic tangent of the specified angle.
static double tanh (double a)
Returns the hyperbolic tangent of the specified angle.
static double Coth (double x)
Hyperblic cotangent, 1/Math.Tanh.
static double coth (double x)
Hyperblic cotangent, 1/Math.Tanh.
static double Arsinh (double x)
Inverse hyperbolic sine.
static double Arcosh (double x)
Inverse hyperbolic cosine.
static double Artanh (double x)
Inverse hyperbolic tangent.
static double Arcoth (double x)
Inverse hyperbolic cotangent.
static long Factorial (int factor)
Returns factorial of the specified number.
static long factorial (int factor)
Returns factorial of the specified number.
static long BinomialCoefficient (long n, long k)
Returns binomial coefficient n over k .
Static Public Member Functions inherited from IG.Num.M
static void Swap (ref double a, ref double b)
Swaps values of the two specified variables of type double.
static void Swap (ref int a, ref int b)
Swaps values of the two specified variables of type int.
static void Swap (ref string a, ref string b)
Swaps values of the two specified variables of type string.
static double abs (double a)
Absolute value.
static double sign (double a)
Returns a value indicating the sign of a number.
static double ceil (double a)
Returns the smallest integral value that is greater than or equal to the specified decimal number.
static double floor (double a)
Returns the largest integer less than or equal to the specified number.
static double trunc (double a)
Calculates the integral part of a specified number.
static double min (double a, double b)
Smallest of two numbers.
static double max (double a, double b)
Largest of two numbers.
static double min (double a, double b, double c)
Smallest of three numbers.
static double max (double a, double b, double c)
Largest of three numbers.
static double min (double a, double b, double c, double d)
Smallest of four numbers.
static double max (double a, double b, double c, double d)
Largest of four numbers.
static double min (double a, double b, double c, double d, double e)
Smallest of five numbers.
static double max (double a, double b, double c, double d, double e)
Largest of five numbers.
static double min (double a, double b, double c, double d, double e, double f)
Smallest of six numbers.
static double max (double a, double b, double c, double d, double e, double f)
Largest of six numbers.
static double min (params double[] numbers)
Minimal of the specified values.
static double max (params double[] numbers)
Maximal of the specified values.
static double sum (params double[] numbers)
Sum of the specified values.
static double prod (params double[] numbers)
Product of the specified values.
static double pow (double a, double b)
Returns a specified number raised to the specified power.
static double sqr (double a)
Returns the square of a specified number.
static double cube (double a)
Returns the square of a specified number.
static double pow2 (double x)
Square.
static double pow3 (double x)
3rd power.
static double pow4 (double x)
4th power.
static double pow5 (double x)
5th power.
static double pow6 (double x)
6th power.
static double sqrt (double a)
Returns the square root of a specified number.
static double root2 (double a)
Returns the square root of a specified number.
static double root3 (double a)
Returns the cubic root of a specified number.
static double rand ()
Returns a uniformly distributed random number greater than or equal to 0.0, and less or equal than 1.0.
static double rand (double min, double max)
Returns a uniformly distributed random number greater than or equal to min, and less or equal than max.
static double randgauss (double mean, double standardDeviation)
Returns a Gaussian distributed random number with the specified mean and standard deviation.
static double exp (double a)
Returns e raised to the specified power.
static double log (double a)
Returns the natural (base e) logarithm of a specified number.
static double ln (double a)
Returns the natural (base e) logarithm of a specified number.
static double log10 (double a)
Returns the base 10 logarithm of a specified number.
static double lg (double a)
Returns the base 10 logarithm of a specified number.
static double log2 (double a)
Returns the base 2 logarithm of a specified number.
static double log (double a, double logBase)
Returns the logarithm of a specified number in a specified base.
static double deg (double x)
Converts angle in radians to angle in degrees and returns it.
static double rad (double x)
Converts angle in degrees to angle in radians and returns it.
static double sin (double a)
Returns the sine of the specified angle.
static double cos (double a)
Returns the cosine of the specified angle.
static double tg (double a)
Returns the tangent of the specified angle.
static double ctg (double x)
Returns cotangent of the specified angle.
static double arccos (double a)
Returns the angle whose cosine is the specified number.
static double arcsin (double a)
Returns the angle whose sine is the specified number.
static double arctg (double a)
Returns the angle whose tangent is the specified number.
static double arcctg (double x)
Arc cotangent, inverse of 1/tan(x).
static double arctg2 (double a, double b)
Returns the angle whose tangent is the quotient of two specified numbers.
static double Sinh (double a)
Returns the hyperbolic sine of the specified angle.
static double sinh (double a)
Returns the hyperbolic sine of the specified angle.
static double sh (double a)
Returns the hyperbolic sine of the specified angle.
static double ch (double a)
Returns the hyperbolic cosine of the specified angle.
static double th (double a)
Returns the hyperbolic tangent of the specified angle.
static double cth (double x)
Hyperblic cotangent, 1/Math.Tanh.
static double arsh (double x)
Inverse hyperbolic sine.
static double arch (double x)
Inverse hyperbolic cosine.
static double arth (double x)
Inverse hyperbolic tangent.
static double arcth (double x)
Inverse hyperbolic cotangent.
static bool CheckFactorialsArray ()
Tests ehether the factoirals in the hard-coded array (factorials64) of factorials are correct; Throws ArgumentException if any of them is incorrect.
static void TestFactorials ()
Writes to the console all factorials that can be calculatet.
static void TestFactorials (int max)
Writes to the console the first n factorials.
static long fac (int factor)
Returns factorial of the specified number.
static long facCalculated (long n)
Returns factorial of the specified number - less efficient approac, but does not rely on hard coded array.
static long fallingPower (long n, long p)
Calculates and returns the falling power of the specified number.
static long binomial (long n, long k)
Returns binomial coefficient n over k .
static void TestBinomialCoefficients ()
Writes the first few binomial coefficients to the console.
static void TestBinomialCoefficients (int nMax)
Writes binomial coefficients up to the specified number to the console.
static double Sum (params double[] sampleElements)
Calculates and returns sum of its arguments (or elements of the specified double array).
static double Sum (IEnumerable< double > sample)
Calculates and returns sum of elemennts the specified sample.
static double Product (params double[] sampleElements)
Calculates and returns proudct of its arguments (or elements of the specified double array).
static double Product (IEnumerable< double > sample)
Calculates and returns product of ellements of the specified sample.
static double Mean (params double[] sampleElements)
Calculates and returns mean value of its arguments (or elements of the specified double array).
static double Mean (IEnumerable< double > sample)
Returns mean value of the specified sample.
static double Average (params double[] sampleElements)
The same as Mean(double[])
static double Average (IEnumerable< double > sample)
The same as Mean(IEnumerable<double>)
static double StandardDeviation (params double[] sampleElements)
Calculates and returns mean value of its arguments (or elements of the specified double array).
static double StandardDeviation (IEnumerable< double > sample)
Returns estimation of the standard deviation of a random value based on the specified sample.
Properties
static double E [get]
Natural logarithmic base.
static double Pi [get]
Ratio of the circumference of a circle to its diameter.
static double Zero [get]
Zero (value 0.0).
static double One [get]
One (value 1.0).
Properties inherited from IG.Num.M
static double e [get]
Natural logarithmic base.
static double pi [get]
Ratio of the circumference of a circle to its diameter.
static double zero [get]
Zero (value 0.0).
static double one [get]
One (value 1.0).
Detailed Description
Defines some mathematical functions to be used in derived classes. In addition to functions defined in the M class, functions are defined under other names, and some additional functions are also defined.
* Standard mathematical functions and constants with short names are implemented, e.g. sin() instesd of Math.Sin().
** These functions are static such that they can be used out of the derived classes, too.
*** In particular, some script classes derive from this one, in order to use simple-named mathematical functions.
** Some functions are defined with several names, in order to reduce probability of errors in scripts.
Definition at line 813 of file UtilMath.cs.
Member Function Documentation
Abs() [1/2]
static double IG.Num.MExt.Abs (double a) inline static
Absolute value.
Definition at line 842 of file UtilMath.cs.
Sign() [1/2]
static double IG.Num.MExt.Sign (double a) inline static
Returns a value indicating the sign of a number.
Definition at line 846 of file UtilMath.cs.
sgn() [1/2]
static double IG.Num.MExt.sgn (double a) inline static
Returns a value indicating the sign of a number.
Definition at line 850 of file UtilMath.cs.
Ceiling() [1/2]
static double IG.Num.MExt.Ceiling (double a) inline static
Returns the smallest integral value that is greater than or equal to the specified decimal number.
Definition at line 859 of file UtilMath.cs.
ceiling() [1/2]
static double IG.Num.MExt.ceiling (double a) inline static
Returns the smallest integral value that is greater than or equal to the specified decimal number.
Definition at line 863 of file UtilMath.cs.
Floor() [1/2]
static double IG.Num.MExt.Floor (double a) inline static
Returns the largest integer less than or equal to the specified number.
Definition at line 867 of file UtilMath.cs.
Truncate() [1/2]
static double IG.Num.MExt.Truncate (double a) inline static
Calculates the integral part of a specified double-precision floating-point number.
Definition at line 871 of file UtilMath.cs.
truncate() [1/2]
static double IG.Num.MExt.truncate (double a) inline static
Calculates the integral part of a specified number.
Definition at line 875 of file UtilMath.cs.
Min() [1/12]
static double IG.Num.MExt.Min (double a, double b) inline static
Smallest of two numbers.
Definition at line 884 of file UtilMath.cs.
Max() [1/12]
static double IG.Num.MExt.Max (double a, double b) inline static
Largest of two numbers.
Definition at line 887 of file UtilMath.cs.
Min() [2/12]
static double IG.Num.MExt.Min (double a, double b, double c) inline static
Smallest of three numbers.
Definition at line 890 of file UtilMath.cs.
Max() [2/12]
static double IG.Num.MExt.Max (double a, double b, double c) inline static
Largest of three numbers.
Definition at line 897 of file UtilMath.cs.
Min() [3/12]
static double IG.Num.MExt.Min (double a, double b, double c, double d) inline static
Smallest of four numbers.
Definition at line 904 of file UtilMath.cs.
Max() [3/12]
static double IG.Num.MExt.Max (double a, double b, double c, double d) inline static
Largest of four numbers.
Definition at line 912 of file UtilMath.cs.
Min() [4/12]
static double IG.Num.MExt.Min (double a, double b, double c, double d, double e) inline static
Smallest of five numbers.
Definition at line 920 of file UtilMath.cs.
References IG.Num.M.e.
Max() [4/12]
static double IG.Num.MExt.Max (double a, double b, double c, double d, double e) inline static
Largest of five numbers.
Definition at line 929 of file UtilMath.cs.
References IG.Num.M.e.
Min() [5/12]
static double IG.Num.MExt.Min (double a, double b, double c, double d, double e, double f) inline static
Smallest of six numbers.
Definition at line 938 of file UtilMath.cs.
References IG.Num.M.e.
Max() [5/12]
static double IG.Num.MExt.Max (double a, double b, double c, double d, double e, double f) inline static
Largest of six numbers.
Definition at line 948 of file UtilMath.cs.
References IG.Num.M.e.
Min() [6/12]
static double IG.Num.MExt.Min (params double[] numbers) inline static
Minimal of the specified values.
Definition at line 958 of file UtilMath.cs.
Max() [6/12]
static double IG.Num.MExt.Max (params double[] numbers) inline static
Maximal of the specified values.
Definition at line 978 of file UtilMath.cs.
product() [1/2]
static double IG.Num.MExt.product (params double[] numbers) inline static
Product of the specified values.
Definition at line 1041 of file UtilMath.cs.
Pow() [1/2]
static double IG.Num.MExt.Pow (double a, double b) inline static
Returns a specified number raised to the specified power.
Definition at line 1065 of file UtilMath.cs.
Sqr() [1/2]
static double IG.Num.MExt.Sqr (double a) inline static
Returns the square of a specified number.
Definition at line 1069 of file UtilMath.cs.
Cube() [1/2]
static double IG.Num.MExt.Cube (double a) inline static
Returns the square of a specified number.
Definition at line 1073 of file UtilMath.cs.
Pow2() [1/2]
static double IG.Num.MExt.Pow2 (double x) inline static
Square.
Definition at line 1077 of file UtilMath.cs.
Pow3() [1/2]
static double IG.Num.MExt.Pow3 (double x) inline static
3rd power.
Definition at line 1080 of file UtilMath.cs.
Pow4() [1/2]
static double IG.Num.MExt.Pow4 (double x) inline static
4th power.
Definition at line 1083 of file UtilMath.cs.
Pow5() [1/2]
static double IG.Num.MExt.Pow5 (double x) inline static
5th power.
Definition at line 1086 of file UtilMath.cs.
Pow6() [1/2]
static double IG.Num.MExt.Pow6 (double x) inline static
6th power.
Definition at line 1089 of file UtilMath.cs.
Sqrt() [1/2]
static double IG.Num.MExt.Sqrt (double a) inline static
Returns the square root of a specified number.
Definition at line 1092 of file UtilMath.cs.
Root2() [1/2]
static double IG.Num.MExt.Root2 (double a) inline static
Returns the square root of a specified number.
Definition at line 1095 of file UtilMath.cs.
Root3() [1/2]
static double IG.Num.MExt.Root3 (double a) inline static
Returns the cubic root of a specified number.
Definition at line 1098 of file UtilMath.cs.
Rand() [1/4]
static double IG.Num.MExt.Rand () inline static
Returns a uniformly distributed random number greater than or equal to 0.0, and less or equal than 1.0.
Definition at line 1108 of file UtilMath.cs.
References IG.Num.RandomGenerator.Global, and IG.Num.IRandomGenerator.NextDoubleInclusive().
Rand() [2/4]
static double IG.Num.MExt.Rand (double min, double max) inline static
Returns a uniformly distributed random number greater than or equal to min, and less or equal than max.
Definition at line 1115 of file UtilMath.cs.
References IG.Num.RandomGenerator.Global, IG.Num.M.max(), IG.Num.M.min(), and IG.Num.IRandomGenerator.NextDoubleInclusive().
RandGauss() [1/2]
static double IG.Num.MExt.RandGauss (double mean, double standardDeviation) inline static
Returns a Gaussian distributed random number with the specified mean and standard deviation.
Parameters
mean Mean value of the distribution.
standardDeviation Standard deviation of the distribution.
Definition at line 1124 of file UtilMath.cs.
References IG.Num.RandomGaussian.Global, and IG.Num.RandomGaussian.NextGaussian().
Exp() [1/2]
static double IG.Num.MExt.Exp (double a) inline static
Returns e raised to the specified power.
Definition at line 1135 of file UtilMath.cs.
Log() [1/4]
static double IG.Num.MExt.Log (double a) inline static
Returns the natural (base e) logarithm of a specified number.
Definition at line 1139 of file UtilMath.cs.
Log10() [1/2]
static double IG.Num.MExt.Log10 (double a) inline static
Returns the base 10 logarithm of a specified number.
Definition at line 1143 of file UtilMath.cs.
Log2() [1/2]
static double IG.Num.MExt.Log2 (double a) inline static
Returns the base 2 logarithm of a specified number.
Definition at line 1147 of file UtilMath.cs.
Log() [2/4]
static double IG.Num.MExt.Log (double a, double logBase) inline static
Returns the logarithm of a specified number in a specified base.
Parameters
a Number whose logarithm is returned.
logBase Base of the logarithm.
Definition at line 1153 of file UtilMath.cs.
Degrees() [1/2]
static double IG.Num.MExt.Degrees (double x) inline static
Converts angle in radians to angle in degrees and returns it.
Definition at line 1162 of file UtilMath.cs.
Radians() [1/2]
static double IG.Num.MExt.Radians (double x) inline static
Converts angle in degrees to angle in radians and returns it.
Definition at line 1165 of file UtilMath.cs.
Sin() [1/2]
static double IG.Num.MExt.Sin (double a) inline static
Returns the sine of the specified angle.
Definition at line 1173 of file UtilMath.cs.
Cos() [1/2]
static double IG.Num.MExt.Cos (double a) inline static
Returns the cosine of the specified angle.
Definition at line 1177 of file UtilMath.cs.
Tan() [1/2]
static double IG.Num.MExt.Tan (double a) inline static
Returns the tangent of the specified angle.
Definition at line 1181 of file UtilMath.cs.
tan() [1/2]
static double IG.Num.MExt.tan (double a) inline static
Returns the tangent of the specified angle.
Definition at line 1185 of file UtilMath.cs.
Cot() [1/2]
static double IG.Num.MExt.Cot (double x) inline static
Returns cotangent of the specified angle.
Definition at line 1189 of file UtilMath.cs.
Acos() [1/2]
static double IG.Num.MExt.Acos (double a) inline static
Returns the angle whose cosine is the specified number.
Definition at line 1197 of file UtilMath.cs.
acos() [1/2]
static double IG.Num.MExt.acos (double a) inline static
Returns the angle whose cosine is the specified number.
Definition at line 1201 of file UtilMath.cs.
Asin() [1/2]
static double IG.Num.MExt.Asin (double a) inline static
Returns the angle whose sine is the specified number.
Definition at line 1205 of file UtilMath.cs.
asin() [1/2]
static double IG.Num.MExt.asin (double a) inline static
Returns the angle whose sine is the specified number.
Definition at line 1209 of file UtilMath.cs.
Atan() [1/2]
static double IG.Num.MExt.Atan (double a) inline static
Returns the angle whose tangent is the specified number.
Definition at line 1213 of file UtilMath.cs.
atan() [1/2]
static double IG.Num.MExt.atan (double a) inline static
Returns the angle whose tangent is the specified number.
Definition at line 1217 of file UtilMath.cs.
arctan() [1/2]
static double IG.Num.MExt.arctan (double a) inline static
Returns the angle whose tangent is the specified number.
Definition at line 1221 of file UtilMath.cs.
Acot() [1/2]
static double IG.Num.MExt.Acot (double x) inline static
Arc cotangent, inverse of 1/tan(x).
Definition at line 1225 of file UtilMath.cs.
acot() [1/2]
static double IG.Num.MExt.acot (double x) inline static
Arc cotangent, inverse of 1/tan(x).
Definition at line 1228 of file UtilMath.cs.
ArcCot() [1/2]
static double IG.Num.MExt.ArcCot (double x) inline static
Arc cotangent, inverse of 1/tan(x).
Definition at line 1231 of file UtilMath.cs.
arccot() [1/2]
static double IG.Num.MExt.arccot (double x) inline static
Arc cotangent, inverse of 1/tan(x).
Definition at line 1234 of file UtilMath.cs.
Atan2() [1/2]
static double IG.Num.MExt.Atan2 (double a, double b) inline static
Returns the angle whose tangent is the quotient of two specified numbers.
Definition at line 1237 of file UtilMath.cs.
atan2() [1/2]
static double IG.Num.MExt.atan2 (double a, double b) inline static
Returns the angle whose tangent is the quotient of two specified numbers.
Definition at line 1241 of file UtilMath.cs.
arctan2() [1/2]
static double IG.Num.MExt.arctan2 (double a, double b) inline static
Returns the angle whose tangent is the quotient of two specified numbers.
Definition at line 1245 of file UtilMath.cs.
Cosh() [1/2]
static double IG.Num.MExt.Cosh (double a) inline static
Returns the hyperbolic cosine of the specified angle.
Definition at line 1262 of file UtilMath.cs.
cosh() [1/2]
static double IG.Num.MExt.cosh (double a) inline static
Returns the hyperbolic cosine of the specified angle.
Definition at line 1266 of file UtilMath.cs.
Tanh() [1/2]
static double IG.Num.MExt.Tanh (double a) inline static
Returns the hyperbolic tangent of the specified angle.
Definition at line 1270 of file UtilMath.cs.
tanh() [1/2]
static double IG.Num.MExt.tanh (double a) inline static
Returns the hyperbolic tangent of the specified angle.
Definition at line 1274 of file UtilMath.cs.
Coth() [1/2]
static double IG.Num.MExt.Coth (double x) inline static
Hyperblic cotangent, 1/Math.Tanh.
Definition at line 1278 of file UtilMath.cs.
coth() [1/2]
static double IG.Num.MExt.coth (double x) inline static
Hyperblic cotangent, 1/Math.Tanh.
Definition at line 1281 of file UtilMath.cs.
Arsinh() [1/2]
static double IG.Num.MExt.Arsinh (double x) inline static
Inverse hyperbolic sine.
Definition at line 1289 of file UtilMath.cs.
References IG.Num.M.pow2().
Arcosh() [1/2]
static double IG.Num.MExt.Arcosh (double x) inline static
Inverse hyperbolic cosine.
Definition at line 1292 of file UtilMath.cs.
References IG.Num.M.pow2().
Artanh() [1/2]
static double IG.Num.MExt.Artanh (double x) inline static
Inverse hyperbolic tangent.
Definition at line 1295 of file UtilMath.cs.
Arcoth() [1/2]
static double IG.Num.MExt.Arcoth (double x) inline static
Inverse hyperbolic cotangent.
Definition at line 1298 of file UtilMath.cs.
Factorial() [1/2]
static long IG.Num.MExt.Factorial (int factor) inline static
Returns factorial of the specified number.
Definition at line 1308 of file UtilMath.cs.
References IG.Num.M.fac().
factorial() [1/2]
static long IG.Num.MExt.factorial (int factor) inline static
Returns factorial of the specified number.
Definition at line 1314 of file UtilMath.cs.
References IG.Num.M.fac().
BinomialCoefficient() [1/2]
static long IG.Num.MExt.BinomialCoefficient (long n, long k) inline static
Returns binomial coefficient n over k .
Parameters
n
k
Definition at line 1322 of file UtilMath.cs.
References IG.Num.M.binomial().
Abs() [2/2]
static double IG.Num.MExt.Abs (double a) inline static
Absolute value.
Definition at line 788 of file UtilMath.cs.
Sign() [2/2]
static double IG.Num.MExt.Sign (double a) inline static
Returns a value indicating the sign of a number.
Definition at line 792 of file UtilMath.cs.
sgn() [2/2]
static double IG.Num.MExt.sgn (double a) inline static
Returns a value indicating the sign of a number.
Definition at line 796 of file UtilMath.cs.
Ceiling() [2/2]
static double IG.Num.MExt.Ceiling (double a) inline static
Returns the smallest integral value that is greater than or equal to the specified decimal number.
Definition at line 805 of file UtilMath.cs.
ceiling() [2/2]
static double IG.Num.MExt.ceiling (double a) inline static
Returns the smallest integral value that is greater than or equal to the specified decimal number.
Definition at line 809 of file UtilMath.cs.
Floor() [2/2]
static double IG.Num.MExt.Floor (double a) inline static
Returns the largest integer less than or equal to the specified number.
Definition at line 813 of file UtilMath.cs.
Truncate() [2/2]
static double IG.Num.MExt.Truncate (double a) inline static
Calculates the integral part of a specified double-precision floating-point number.
Definition at line 817 of file UtilMath.cs.
truncate() [2/2]
static double IG.Num.MExt.truncate (double a) inline static
Calculates the integral part of a specified number.
Definition at line 821 of file UtilMath.cs.
Min() [7/12]
static double IG.Num.MExt.Min (double a, double b) inline static
Smallest of two numbers.
Definition at line 830 of file UtilMath.cs.
Max() [7/12]
static double IG.Num.MExt.Max (double a, double b) inline static
Largest of two numbers.
Definition at line 833 of file UtilMath.cs.
Min() [8/12]
static double IG.Num.MExt.Min (double a, double b, double c) inline static
Smallest of three numbers.
Definition at line 836 of file UtilMath.cs.
Max() [8/12]
static double IG.Num.MExt.Max (double a, double b, double c) inline static
Largest of three numbers.
Definition at line 843 of file UtilMath.cs.
Min() [9/12]
static double IG.Num.MExt.Min (double a, double b, double c, double d) inline static
Smallest of four numbers.
Definition at line 850 of file UtilMath.cs.
Max() [9/12]
static double IG.Num.MExt.Max (double a, double b, double c, double d) inline static
Largest of four numbers.
Definition at line 858 of file UtilMath.cs.
Min() [10/12]
static double IG.Num.MExt.Min (double a, double b, double c, double d, double e) inline static
Smallest of five numbers.
Definition at line 866 of file UtilMath.cs.
References IG.Num.M.e.
Max() [10/12]
static double IG.Num.MExt.Max (double a, double b, double c, double d, double e) inline static
Largest of five numbers.
Definition at line 875 of file UtilMath.cs.
References IG.Num.M.e.
Min() [11/12]
static double IG.Num.MExt.Min (double a, double b, double c, double d, double e, double f) inline static
Smallest of six numbers.
Definition at line 884 of file UtilMath.cs.
References IG.Num.M.e.
Max() [11/12]
static double IG.Num.MExt.Max (double a, double b, double c, double d, double e, double f) inline static
Largest of six numbers.
Definition at line 894 of file UtilMath.cs.
References IG.Num.M.e.
Min() [12/12]
static double IG.Num.MExt.Min (params double[] numbers) inline static
Minimal of the specified values.
Definition at line 904 of file UtilMath.cs.
Max() [12/12]
static double IG.Num.MExt.Max (params double[] numbers) inline static
Maximal of the specified values.
Definition at line 924 of file UtilMath.cs.
Sum()
static double IG.Num.MExt.Sum (params double[] numbers) inline static
Sum of the specified values.
Definition at line 949 of file UtilMath.cs.
Product()
static double IG.Num.MExt.Product (params double[] numbers) inline static
Product of the specified values.
Definition at line 968 of file UtilMath.cs.
product() [2/2]
static double IG.Num.MExt.product (params double[] numbers) inline static
Product of the specified values.
Definition at line 987 of file UtilMath.cs.
Pow() [2/2]
static double IG.Num.MExt.Pow (double a, double b) inline static
Returns a specified number raised to the specified power.
Definition at line 1011 of file UtilMath.cs.
Sqr() [2/2]
static double IG.Num.MExt.Sqr (double a) inline static
Returns the square of a specified number.
Definition at line 1015 of file UtilMath.cs.
Cube() [2/2]
static double IG.Num.MExt.Cube (double a) inline static
Returns the square of a specified number.
Definition at line 1019 of file UtilMath.cs.
Pow2() [2/2]
static double IG.Num.MExt.Pow2 (double x) inline static
Square.
Definition at line 1023 of file UtilMath.cs.
Pow3() [2/2]
static double IG.Num.MExt.Pow3 (double x) inline static
3rd power.
Definition at line 1026 of file UtilMath.cs.
Pow4() [2/2]
static double IG.Num.MExt.Pow4 (double x) inline static
4th power.
Definition at line 1029 of file UtilMath.cs.
Pow5() [2/2]
static double IG.Num.MExt.Pow5 (double x) inline static
5th power.
Definition at line 1032 of file UtilMath.cs.
Pow6() [2/2]
static double IG.Num.MExt.Pow6 (double x) inline static
6th power.
Definition at line 1035 of file UtilMath.cs.
Sqrt() [2/2]
static double IG.Num.MExt.Sqrt (double a) inline static
Returns the square root of a specified number.
Definition at line 1038 of file UtilMath.cs.
Root2() [2/2]
static double IG.Num.MExt.Root2 (double a) inline static
Returns the square root of a specified number.
Definition at line 1041 of file UtilMath.cs.
Root3() [2/2]
static double IG.Num.MExt.Root3 (double a) inline static
Returns the cubic root of a specified number.
Definition at line 1044 of file UtilMath.cs.
Rand() [3/4]
static double IG.Num.MExt.Rand () inline static
Returns a uniformly distributed random number greater than or equal to 0.0, and less or equal than 1.0.
Definition at line 1054 of file UtilMath.cs.
References IG.Num.RandomGenerator.Global, and IG.Num.IRandomGenerator.NextDoubleInclusive().
Rand() [4/4]
static double IG.Num.MExt.Rand (double min, double max) inline static
Returns a uniformly distributed random number greater than or equal to min, and less or equal than max.
Definition at line 1061 of file UtilMath.cs.
References IG.Num.RandomGenerator.Global, IG.Num.M.max(), IG.Num.M.min(), and IG.Num.IRandomGenerator.NextDoubleInclusive().
RandGauss() [2/2]
static double IG.Num.MExt.RandGauss (double mean, double standardDeviation) inline static
Returns a Gaussian distributed random number with the specified mean and standard deviation.
Parameters
mean Mean value of the distribution.
standardDeviation Standard deviation of the distribution.
Definition at line 1070 of file UtilMath.cs.
References IG.Num.RandomGaussian.Global, and IG.Num.RandomGaussian.NextGaussian().
Exp() [2/2]
static double IG.Num.MExt.Exp (double a) inline static
Returns e raised to the specified power.
Definition at line 1081 of file UtilMath.cs.
Log() [3/4]
static double IG.Num.MExt.Log (double a) inline static
Returns the natural (base e) logarithm of a specified number.
Definition at line 1085 of file UtilMath.cs.
Log10() [2/2]
static double IG.Num.MExt.Log10 (double a) inline static
Returns the base 10 logarithm of a specified number.
Definition at line 1089 of file UtilMath.cs.
Log2() [2/2]
static double IG.Num.MExt.Log2 (double a) inline static
Returns the base 2 logarithm of a specified number.
Definition at line 1093 of file UtilMath.cs.
Log() [4/4]
static double IG.Num.MExt.Log (double a, double logBase) inline static
Returns the logarithm of a specified number in a specified base.
Parameters
a Number whose logarithm is returned.
logBase Base of the logarithm.
Definition at line 1099 of file UtilMath.cs.
Degrees() [2/2]
static double IG.Num.MExt.Degrees (double x) inline static
Converts angle in radians to angle in degrees and returns it.
Definition at line 1108 of file UtilMath.cs.
Radians() [2/2]
static double IG.Num.MExt.Radians (double x) inline static
Converts angle in degrees to angle in radians and returns it.
Definition at line 1111 of file UtilMath.cs.
Sin() [2/2]
static double IG.Num.MExt.Sin (double a) inline static
Returns the sine of the specified angle.
Definition at line 1119 of file UtilMath.cs.
Cos() [2/2]
static double IG.Num.MExt.Cos (double a) inline static
Returns the cosine of the specified angle.
Definition at line 1123 of file UtilMath.cs.
Tan() [2/2]
static double IG.Num.MExt.Tan (double a) inline static
Returns the tangent of the specified angle.
Definition at line 1127 of file UtilMath.cs.
tan() [2/2]
static double IG.Num.MExt.tan (double a) inline static
Returns the tangent of the specified angle.
Definition at line 1131 of file UtilMath.cs.
Cot() [2/2]
static double IG.Num.MExt.Cot (double x) inline static
Returns cotangent of the specified angle.
Definition at line 1135 of file UtilMath.cs.
Acos() [2/2]
static double IG.Num.MExt.Acos (double a) inline static
Returns the angle whose cosine is the specified number.
Definition at line 1143 of file UtilMath.cs.
acos() [2/2]
static double IG.Num.MExt.acos (double a) inline static
Returns the angle whose cosine is the specified number.
Definition at line 1147 of file UtilMath.cs.
Asin() [2/2]
static double IG.Num.MExt.Asin (double a) inline static
Returns the angle whose sine is the specified number.
Definition at line 1151 of file UtilMath.cs.
asin() [2/2]
static double IG.Num.MExt.asin (double a) inline static
Returns the angle whose sine is the specified number.
Definition at line 1155 of file UtilMath.cs.
Atan() [2/2]
static double IG.Num.MExt.Atan (double a) inline static
Returns the angle whose tangent is the specified number.
Definition at line 1159 of file UtilMath.cs.
atan() [2/2]
static double IG.Num.MExt.atan (double a) inline static
Returns the angle whose tangent is the specified number.
Definition at line 1163 of file UtilMath.cs.
arctan() [2/2]
static double IG.Num.MExt.arctan (double a) inline static
Returns the angle whose tangent is the specified number.
Definition at line 1167 of file UtilMath.cs.
Acot() [2/2]
static double IG.Num.MExt.Acot (double x) inline static
Arc cotangent, inverse of 1/tan(x).
Definition at line 1171 of file UtilMath.cs.
acot() [2/2]
static double IG.Num.MExt.acot (double x) inline static
Arc cotangent, inverse of 1/tan(x).
Definition at line 1174 of file UtilMath.cs.
ArcCot() [2/2]
static double IG.Num.MExt.ArcCot (double x) inline static
Arc cotangent, inverse of 1/tan(x).
Definition at line 1177 of file UtilMath.cs.
arccot() [2/2]
static double IG.Num.MExt.arccot (double x) inline static
Arc cotangent, inverse of 1/tan(x).
Definition at line 1180 of file UtilMath.cs.
Atan2() [2/2]
static double IG.Num.MExt.Atan2 (double a, double b) inline static
Returns the angle whose tangent is the quotient of two specified numbers.
Definition at line 1183 of file UtilMath.cs.
atan2() [2/2]
static double IG.Num.MExt.atan2 (double a, double b) inline static
Returns the angle whose tangent is the quotient of two specified numbers.
Definition at line 1187 of file UtilMath.cs.
arctan2() [2/2]
static double IG.Num.MExt.arctan2 (double a, double b) inline static
Returns the angle whose tangent is the quotient of two specified numbers.
Definition at line 1191 of file UtilMath.cs.
Cosh() [2/2]
static double IG.Num.MExt.Cosh (double a) inline static
Returns the hyperbolic cosine of the specified angle.
Definition at line 1208 of file UtilMath.cs.
cosh() [2/2]
static double IG.Num.MExt.cosh (double a) inline static
Returns the hyperbolic cosine of the specified angle.
Definition at line 1212 of file UtilMath.cs.
Tanh() [2/2]
static double IG.Num.MExt.Tanh (double a) inline static
Returns the hyperbolic tangent of the specified angle.
Definition at line 1216 of file UtilMath.cs.
tanh() [2/2]
static double IG.Num.MExt.tanh (double a) inline static
Returns the hyperbolic tangent of the specified angle.
Definition at line 1220 of file UtilMath.cs.
Coth() [2/2]
static double IG.Num.MExt.Coth (double x) inline static
Hyperblic cotangent, 1/Math.Tanh.
Definition at line 1224 of file UtilMath.cs.
coth() [2/2]
static double IG.Num.MExt.coth (double x) inline static
Hyperblic cotangent, 1/Math.Tanh.
Definition at line 1227 of file UtilMath.cs.
Arsinh() [2/2]
static double IG.Num.MExt.Arsinh (double x) inline static
Inverse hyperbolic sine.
Definition at line 1235 of file UtilMath.cs.
References IG.Num.M.pow2().
Arcosh() [2/2]
static double IG.Num.MExt.Arcosh (double x) inline static
Inverse hyperbolic cosine.
Definition at line 1238 of file UtilMath.cs.
References IG.Num.M.pow2().
Artanh() [2/2]
static double IG.Num.MExt.Artanh (double x) inline static
Inverse hyperbolic tangent.
Definition at line 1241 of file UtilMath.cs.
Arcoth() [2/2]
static double IG.Num.MExt.Arcoth (double x) inline static
Inverse hyperbolic cotangent.
Definition at line 1244 of file UtilMath.cs.
Factorial() [2/2]
static long IG.Num.MExt.Factorial (int factor) inline static
Returns factorial of the specified number.
Definition at line 1254 of file UtilMath.cs.
References IG.Num.M.fac().
factorial() [2/2]
static long IG.Num.MExt.factorial (int factor) inline static
Returns factorial of the specified number.
Definition at line 1260 of file UtilMath.cs.
References IG.Num.M.fac().
BinomialCoefficient() [2/2]
static long IG.Num.MExt.BinomialCoefficient (long n, long k) inline static
Returns binomial coefficient n over k .
Parameters
n
k
Definition at line 1268 of file UtilMath.cs.
References IG.Num.M.binomial().
Property Documentation
E
static double IG.Num.MExt.E static get
Natural logarithmic base.
Definition at line 820 of file UtilMath.cs.
Pi
static double IG.Num.MExt.Pi static get
Ratio of the circumference of a circle to its diameter.
Definition at line 824 of file UtilMath.cs.
Zero
static double IG.Num.MExt.Zero static get
Zero (value 0.0).
Definition at line 828 of file UtilMath.cs.
One
static double IG.Num.MExt.One static get
One (value 1.0).
Definition at line 832 of file UtilMath.cs.
The documentation for this class was generated from the following file:
IGLibCore/src/IGLib.Core/MathUtils/UtilMath.cs