Doc: IGLib with source files: IG.Gr.GraphicObject Class Reference
IG.Gr.GraphicObject Class Reference
Graphic object, a tree - like collection of graphic primitives.
Public Member Functions
virtual void Add (GraphicPrimitive primitive)
Adds a graphic primitive to the object.
virtual void Add (GraphicObject grobject)
Adds a child graphic object to the current objects.
virtual GraphicObject GetDirectChildObject (int i)
Returns tha direct child object No. i.
virtual void AddChildObject (GraphicObject grobject)
Adds a child object to the graphic object.
virtual GraphicPrimitive GetDirectPrimitive (int i)
Returns the primitive No. i that is directly contained on this graphic object. Primitives contained in descendant objects are excluded.
Properties
virtual GraphicObject Parent [get, set]
Gets the parent object of this object (if there exists).
virtual int NumDirectChildObjects [get]
Gets the number of child objects of the current element (descendants of higher leval are excluded).
virtual int NumObjects [get]
Gets the total number of descendant objects.
virtual int NumDirectPrimitives [get]
Gets the number of graphic primitives directly contained in this object. This does NOT include the primitive contained in descendant objects.
virtual int NumPrimitives [get]
Gets the total number of graphic primitives contained in this object, which includes primitives of all descendant graphic objects.
virtual GrPrimitiveSettings Settings [get, protected set]
Gets the primitive's internal graphic properties (such as color, etc.)
virtual GrPrimitiveSettings EffectiveSettings [get]
Private Attributes
GraphicObject _parent = null
List< GraphicObject > _childobjects = new List<GraphicObject>()
List< GraphicPrimitive > _primitives = new List<GraphicPrimitive>()
GrPrimitiveSettings _settings = null
Detailed Description
Graphic object, a tree - like collection of graphic primitives.
Definition at line 151 of file GrObjects.cs.
Member Function Documentation
Add() [1/2]
virtual void IG.Gr.GraphicObject.Add (GraphicPrimitive primitive) inline virtual
Adds a graphic primitive to the object.
Definition at line 174 of file GrObjects.cs.
References IG.Gr.GraphicObject._primitives.
Add() [2/2]
virtual void IG.Gr.GraphicObject.Add (GraphicObject grobject) inline virtual
Adds a child graphic object to the current objects.
Parameters
grobject Graphic object that is added as a child object.
Definition at line 181 of file GrObjects.cs.
References IG.Gr.GraphicObject._childobjects.
GetDirectChildObject()
virtual GraphicObject IG.Gr.GraphicObject.GetDirectChildObject (int i) inline virtual
Returns tha direct child object No. i.
Parameters
i Index of the child object to return.
Returns
The direct child object No i.
Exceptions
IndexOutOfRangeException When index is out of range.
Definition at line 209 of file GrObjects.cs.
References IG.Gr.GraphicObject._childobjects.
AddChildObject()
virtual void IG.Gr.GraphicObject.AddChildObject (GraphicObject grobject) inline virtual
Adds a child object to the graphic object.
Definition at line 218 of file GrObjects.cs.
References IG.Gr.GraphicObject._childobjects.
GetDirectPrimitive()
virtual GraphicPrimitive IG.Gr.GraphicObject.GetDirectPrimitive (int i) inline virtual
Returns the primitive No. i that is directly contained on this graphic object. Primitives contained in descendant objects are excluded.
Parameters
i Zero-based index of the primitive.
Returns
The specified primitive that is directly contained in the current graphic object.
Exceptions
ArgumentOutOfRangeException When index is out of range.
Definition at line 247 of file GrObjects.cs.
References IG.Gr.GraphicObject._primitives.
Member Data Documentation
_parent
GraphicObject IG.Gr.GraphicObject._parent = null private
Definition at line 156 of file GrObjects.cs.
_childobjects
List<GraphicObject> IG.Gr.GraphicObject._childobjects = new List<GraphicObject>() private
Definition at line 159 of file GrObjects.cs.
Referenced by IG.Gr.GraphicObject.Add(), IG.Gr.GraphicObject.AddChildObject(), and IG.Gr.GraphicObject.GetDirectChildObject().
_primitives
List<GraphicPrimitive> IG.Gr.GraphicObject._primitives = new List<GraphicPrimitive>() private
Definition at line 161 of file GrObjects.cs.
Referenced by IG.Gr.GraphicObject.Add(), and IG.Gr.GraphicObject.GetDirectPrimitive().
_settings
GrPrimitiveSettings IG.Gr.GraphicObject._settings = null private
Definition at line 259 of file GrObjects.cs.
Property Documentation
Parent
virtual GraphicObject IG.Gr.GraphicObject.Parent get set
Gets the parent object of this object (if there exists).
Definition at line 168 of file GrObjects.cs.
NumDirectChildObjects
virtual int IG.Gr.GraphicObject.NumDirectChildObjects get
Gets the number of child objects of the current element (descendants of higher leval are excluded).
Definition at line 189 of file GrObjects.cs.
NumObjects
virtual int IG.Gr.GraphicObject.NumObjects get
Gets the total number of descendant objects.
Definition at line 193 of file GrObjects.cs.
NumDirectPrimitives
virtual int IG.Gr.GraphicObject.NumDirectPrimitives get
Gets the number of graphic primitives directly contained in this object. This does NOT include the primitive contained in descendant objects.
Definition at line 227 of file GrObjects.cs.
NumPrimitives
virtual int IG.Gr.GraphicObject.NumPrimitives get
Gets the total number of graphic primitives contained in this object, which includes primitives of all descendant graphic objects.
Definition at line 232 of file GrObjects.cs.
Settings
virtual GrPrimitiveSettings IG.Gr.GraphicObject.Settings get protected set
Gets the primitive's internal graphic properties (such as color, etc.)
Definition at line 263 of file GrObjects.cs.
EffectiveSettings
virtual GrPrimitiveSettings IG.Gr.GraphicObject.EffectiveSettings get
Definition at line 271 of file GrObjects.cs.
The documentation for this class was generated from the following file:
iglib/igbase/graphics/GrObjects.cs