Doc: IGLib with source files: IGLib.Gr3D.TubularMeshGenerator_03 Class Reference
IGLib.Gr3D.TubularMeshGenerator_03 Class Reference
Static Public Member Functions
static StructuredMesh3D_03 Generate (Func< double, vec3 > curve, double tStart, double tEnd, double radius, int numT, int numTheta)
Detailed Description
Definition at line 11 of file TubularMeshGenerator_03.cs.
Member Function Documentation
Generate()
static StructuredMesh3D_03 IGLib.Gr3D.TubularMeshGenerator_03.Generate (Func< double, vec3 > curve, double tStart, double tEnd, double radius, int numT, int numTheta) inline static
Definition at line 13 of file TubularMeshGenerator_03.cs.
References IG.Num.vec3.Cross(), IGLib.Gr3D.StructuredMesh3D_03.NodeNormals, IGLib.Gr3D.StructuredMesh3D_03.Nodes, IG.Num.vec3.Normalize(), IGLib.Gr3D.StructuredMesh3D_03.Params1, IGLib.Gr3D.StructuredMesh3D_03.Params2, and IG.Num.vec3.z.
Referenced by IGLib.Gr3D.TubularSurfaceExamples.Example_03().
The documentation for this class was generated from the following file:
IGLibGraphics3D/src/IGLib.Graphics3D/Graphics3D/Historical/TubularMeshGenerator_03.cs