Doc: IGLib with source files: IG.Lib.HtmlWriter Class Reference
IG.Lib.HtmlWriter Class Reference
Generates and composes a HTML document.
Public Member Functions
HtmlWriter (string filePath)
Creates a new HTML generator and connests it with the specified file.
HtmlWriter (string filePath, string cssPath)
Creates a new HTML generator and connests it with the specified file.
string GetIndent ()
Returns indentation string for the current indentation level.
int GetIndentLevel ()
Returns current indentation level of the document.
void AddDocumentComment (string commentText)
Adds another commet to the document that will be written in the document head.
string[] GetDocumentComments ()
Returns an array of comments of the document that will be written in the document head.
void AddSingleKeyWord (string keyword)
Adds a keyword to the document (keywords are written as meta tag).
void AddKeywords (params string[] keywords)
Adds the specified keywords to the document (keywords are written as meta tag).
string[] GetKeywords ()
Returns an array of current keywords on the document.
void CloseWriter ()
Closes the text writer used for assembling the HTML document.
void BeginDocument ()
Begins the HTML document.
void EndDocument ()
Ends the HTML document. After this method is called, writing is not possible any more.
void AppendPlainText (string text)
Adds plain text to HTML (without any markup, indentation or newlines, unless contained in the text string).
void AddPlainTextLine (string text)
Adds a line of plain text to HTML (without any markup, unless contained in the text string), indented and with newline fillowed.
void BeginTag (string tagName)
Adds the specified tag to the document.
void BeginTag (string tagName, params string[] attributeNameValuePairs)
Adds the specified tag to the document.
void BeginTagWithText (string tagName, string text)
Adds the specified tag containing the specified text to the document.
void BeginTagWithText (string tagName, string text, params string[] attributeNameValuePairs)
Adds the specified tag containing the specified text to the document.
void EndTag (string tagName)
Adds the specified tag containing the specified text to the document.
void BeginSection (params string[] attributeNameValuePairs)
Begins a new section.
void EndSection ()
Ends a section.
void AddNewLine ()
Adds a newline to HTML.
void AppendAttributes (string[] attributeNameValuePairs)
Writes definition of the specified attriutes of a HTML element to the HTML document.
void AddTag (string tagName, string text, bool withLineBreak)
Adds the specified tag containing the specified text to the document.
void AddTag (string tagName, string text)
Adds the specified tag containing the specified text to the document.
void AddTag (string tagName, string text, params string[] attributeNameValuePairs)
Adds the specified tag containing the specified text to the document.
void AddTag (string tagName, string text, bool withLineBreak, params string[] attributeNameValuePairs)
Adds the specified tag containing the specified text to the document.
void AddParagraph (string paragraphText, string[] attributeNameValuePairs)
Adds a new paragraph with the specified text to the HTML document.
void AddParagraph (string paragraphText)
Adds a new paragraph with the specified text to the HTML document.
void AddHeading1 (string headingText, params string[] attributeNameValuePairs)
Adds a new level 1 heading with the specified text to the HTML document.
void AddHeading1 (string headingText)
Adds a new level 1 heading with the specified text to the HTML document.
void AddHeading2 (string headingText, params string[] attributeNameValuePairs)
Adds a new level 2 heading with the specified text to the HTML document.
void AddHeading2 (string headingText)
Adds a new level 2 heading with the specified text to the HTML document.
void AddHeading3 (string headingText, params string[] attributeNameValuePairs)
Adds a new level 3 heading with the specified text to the HTML document.
void AddHeading3 (string headingText)
Adds a new level 3 heading with the specified text to the HTML document.
void AddHeading4 (string headingText, params string[] attributeNameValuePairs)
Adds a new level 4 heading with the specified text to the HTML document.
void AddHeading4 (string headingText)
Adds a new level 4 heading with the specified text to the HTML document.
void AddImage (string imageLink, string altText, string captionText, int width, int height, int originalWidth, int originalHeight, bool constrainRatio)
Adds a linked image to the HTML document with specified custom size different than the original size.
void AddImage (string imageLink, string altText, string captionText, int width, int height, bool defineSize)
Adds a linked image to the HTML document.
void Dispose ()
Implementation of IDisposable interface.
Static Public Member Functions
static void Example (string htmlDocumentPath, string styleSheetPath, string imagePath1, string imagePath2)
Writes an example HTML document.
Public Attributes
int IndentSpaces = 2
Number of spaces used in each level of indentation)
string ImageCaption = "Figure"
Protected Member Functions
string GetIndent (int level)
Returns indentation string for the specified indentation level.
virtual void WriteDocumentTitle ()
Adds the title meta tag to the document.
virtual void WriteDocumentStyle ()
Adds the style tag to the document.
virtual void WriteCssPath ()
virtual void WriteDocumentComments ()
Writes document comments.
virtual void WriteMetaTagGeneral (params string[] attributeNameValuePairs)
Wirtes the meta tag with specified pairs of field names and corresponding values.
virtual void WriteMetaContent ()
Adds a contenbt meta tag.
virtual void WriteMetaTag (string name, string content)
Adds a meta tag with specified values of the name and content fields.
virtual void WriteMetaAuthor ()
Writes the author meta tag to the document.
virtual void WriteMetaDescription ()
Adds the audescription meta tag to the document.
virtual void WriteMetaKeywords ()
Adds the keywords meta tag to the document.
bool IsAttributesDefined (string[] attributeNameValuePairs)
Returns true if the specified array of attribute name-value pairs defines any attributes, false otherwise.
void AddImageCaption (string captionText)
Adds Image caption to the current HTML document.
virtual void Dispose (bool disposing)
Does the job of freeing resources.
Protected Attributes
bool _headWritten = false
bool _tailWritten = false
string _filePath
int IndentLevel = 0
Current level of indentation.
string _cssPath
string _styleString
string _documentTitle = "Generated HTML Document"
string _documentAuthor = "IGLIb (by Igor Gresovnik)"
string _documentDescription = "This document was programatically generated by IGLib (Investigative Generic Library), http://www2.arnes.si/~ljc3m2/igor/iglib/"
List< string > _documentComments
List< string > _keywords
TextWriter _writer
bool _lockBeginDocument = false
Properties
string ConstAttributeClass [get]
The class attribute. Specifies one or more classnames for an element (refers to a class in a style sheet).
string ConstAttributeId [get]
The id attribute. Specifies a unique id for an element.
string ConstAttributeStyle [get]
The style attribute. Specifies an inline CSS style for an element.
string ConstAttributeTitle [get]
The style attribute. Specifies extra information about an element.
string ConstAttributeTextDirection [get]
The text direction attribute. Specifies text direction for the content in an element.
string ConstAttributeLanguage [get]
The language attribute. Specifies the language of the element's content.
string ConstAttributeLanguageXml [get]
The xml language attribute. Specifies the language of the element's content (for XHTML documents).
string ConstAttributeShortcutKey [get]
The shortcut key attribute. Specifies a shortcut key to activate/focus an element.
string ConstAttributeTabIndex [get]
The tab index attribute. Specifies the tabbing order of an element.
string FilePath [get, protected set]
Path to file containing the generator.
string CssPath [get, set]
Path to the associated CSS file (Cascaded Style Sheets).
string DocumentStyle [get, set]
CSS string with internal style definitions.
virtual string DocumentTitle [get, set]
virtual string DocumentAuthor [get, set]
virtual string DocumentDescription [get, set]
TextWriter Writer [get]
Text writer used for writing on the document.
Private Member Functions
HtmlWriter ()
Prevent argument-less constructor.
~HtmlWriter ()
Private Attributes
int _sectionLevel = 0
int _imageNum = 0
bool disposed = false
Detailed Description
Generates and composes a HTML document.
Each object of this class can be used for generation of only one HTML document.
$A Igor xx Feb12;
Definition at line 54 of file HtmlWriter.cs.
Constructor & Destructor Documentation
HtmlWriter() [1/3]
IG.Lib.HtmlWriter.HtmlWriter () inline private
Prevent argument-less constructor.
Definition at line 60 of file HtmlWriter.cs.
Referenced by IG.Lib.HtmlWriter.Example().
HtmlWriter() [2/3]
IG.Lib.HtmlWriter.HtmlWriter (string filePath) inline
Creates a new HTML generator and connests it with the specified file.
Parameters
filePath Path to the HTML file that is created.
Definition at line 64 of file HtmlWriter.cs.
HtmlWriter() [3/3]
IG.Lib.HtmlWriter.HtmlWriter (string filePath, string cssPath) inline
Creates a new HTML generator and connests it with the specified file.
Parameters
filePath Path to the HTML file that is created.
cssPath Path (usually relative) to the CSS (Cascading Style Sheets) file.
Definition at line 71 of file HtmlWriter.cs.
References IG.Lib.HtmlWriter.CssPath, and IG.Lib.HtmlWriter.FilePath.
~HtmlWriter()
IG.Lib.HtmlWriter.~HtmlWriter () inline private
Definition at line 859 of file HtmlWriter.cs.
References IG.Lib.HtmlWriter.Dispose().
Member Function Documentation
GetIndent() [1/2]
string IG.Lib.HtmlWriter.GetIndent (int level) inline protected
Returns indentation string for the specified indentation level.
Parameters
level Level of indentation for which indentation string is returned.
Definition at line 135 of file HtmlWriter.cs.
References IG.Lib.HtmlWriter.IndentSpaces.
GetIndent() [2/2]
string IG.Lib.HtmlWriter.GetIndent () inline
Returns indentation string for the current indentation level.
Level is increased or decreased automatically with respect to what is done with the document.
Definition at line 150 of file HtmlWriter.cs.
References IG.Lib.HtmlWriter.IndentLevel.
Referenced by IG.Lib.HtmlWriter.AddImage(), IG.Lib.HtmlWriter.AddImageCaption(), IG.Lib.HtmlWriter.AddNewLine(), IG.Lib.HtmlWriter.AddPlainTextLine(), IG.Lib.HtmlWriter.AddTag(), IG.Lib.HtmlWriter.BeginTagWithText(), IG.Lib.HtmlWriter.EndTag(), IG.Lib.HtmlWriter.WriteCssPath(), IG.Lib.HtmlWriter.WriteDocumentComments(), IG.Lib.HtmlWriter.WriteDocumentStyle(), IG.Lib.HtmlWriter.WriteDocumentTitle(), and IG.Lib.HtmlWriter.WriteMetaTagGeneral().
GetIndentLevel()
int IG.Lib.HtmlWriter.GetIndentLevel () inline
Returns current indentation level of the document.
Definition at line 154 of file HtmlWriter.cs.
References IG.Lib.HtmlWriter.IndentLevel.
AddDocumentComment()
void IG.Lib.HtmlWriter.AddDocumentComment (string commentText) inline
Adds another commet to the document that will be written in the document head.
Must be called before the document head is written, otherwise the comment will not be written.
Parameters
commentText Text of the comment to be added.
Definition at line 205 of file HtmlWriter.cs.
References IG.Lib.HtmlWriter._documentComments.
GetDocumentComments()
string [] IG.Lib.HtmlWriter.GetDocumentComments () inline
Returns an array of comments of the document that will be written in the document head.
Definition at line 216 of file HtmlWriter.cs.
References IG.Lib.HtmlWriter._documentComments.
Referenced by IG.Lib.HtmlWriter.WriteDocumentComments().
AddSingleKeyWord()
void IG.Lib.HtmlWriter.AddSingleKeyWord (string keyword) inline
Adds a keyword to the document (keywords are written as meta tag).
Must be called before the document head is written, otherwise the keyword will not be written.
Parameters
keyword Keyword to be added to the document.
Definition at line 230 of file HtmlWriter.cs.
References IG.Lib.HtmlWriter._keywords.
Referenced by IG.Lib.HtmlWriter.AddKeywords().
AddKeywords()
void IG.Lib.HtmlWriter.AddKeywords (params string[] keywords) inline
Adds the specified keywords to the document (keywords are written as meta tag).
Must be called before the document head is written, otherwise the keyword will not be written.
Parameters
keywords Keywords to be added.
Definition at line 243 of file HtmlWriter.cs.
References IG.Lib.HtmlWriter.AddSingleKeyWord().
Referenced by IG.Lib.HtmlWriter.Example().
GetKeywords()
string [] IG.Lib.HtmlWriter.GetKeywords () inline
Returns an array of current keywords on the document.
Definition at line 251 of file HtmlWriter.cs.
References IG.Lib.HtmlWriter._keywords.
Referenced by IG.Lib.HtmlWriter.WriteMetaKeywords().
CloseWriter()
void IG.Lib.HtmlWriter.CloseWriter () inline
Closes the text writer used for assembling the HTML document.
Definition at line 288 of file HtmlWriter.cs.
References IG.Lib.HtmlWriter._writer.
Referenced by IG.Lib.HtmlWriter.Dispose(), and IG.Lib.HtmlWriter.Example().
WriteDocumentTitle()
virtual void IG.Lib.HtmlWriter.WriteDocumentTitle () inline protected virtual
Adds the title meta tag to the document.
Must be called within the method for writing document head.
Definition at line 299 of file HtmlWriter.cs.
References IG.Lib.HtmlWriter._headWritten, IG.Lib.HtmlWriter.AppendPlainText(), IG.Lib.HtmlWriter.DocumentTitle, and IG.Lib.HtmlWriter.GetIndent().
Referenced by IG.Lib.HtmlWriter.BeginDocument().
WriteDocumentStyle()
virtual void IG.Lib.HtmlWriter.WriteDocumentStyle () inline protected virtual
Adds the style tag to the document.
Must be called within the method for writing document head.
Definition at line 308 of file HtmlWriter.cs.
References IG.Lib.HtmlWriter._headWritten, IG.Lib.HtmlWriter.AppendPlainText(), IG.Lib.HtmlWriter.DocumentStyle, and IG.Lib.HtmlWriter.GetIndent().
Referenced by IG.Lib.HtmlWriter.BeginDocument().
WriteCssPath()
virtual void IG.Lib.HtmlWriter.WriteCssPath () inline protected virtual
Definition at line 316 of file HtmlWriter.cs.
References IG.Lib.HtmlWriter._headWritten, IG.Lib.HtmlWriter.AppendPlainText(), IG.Lib.HtmlWriter.CssPath, and IG.Lib.HtmlWriter.GetIndent().
Referenced by IG.Lib.HtmlWriter.BeginDocument().
WriteDocumentComments()
virtual void IG.Lib.HtmlWriter.WriteDocumentComments () inline protected virtual
Writes document comments.
Must be called within the method for writing document head.
Definition at line 329 of file HtmlWriter.cs.
References IG.Lib.HtmlWriter._headWritten, IG.Lib.HtmlWriter.AppendPlainText(), IG.Lib.HtmlWriter.GetDocumentComments(), and IG.Lib.HtmlWriter.GetIndent().
Referenced by IG.Lib.HtmlWriter.BeginDocument().
WriteMetaTagGeneral()
virtual void IG.Lib.HtmlWriter.WriteMetaTagGeneral (params string[] attributeNameValuePairs) inline protected virtual
Wirtes the meta tag with specified pairs of field names and corresponding values.
Must be called within the method for writing document head.
Parameters
attributeNameValuePairs Pairs of attribute names and values that will comprise the meta tag.
Definition at line 348 of file HtmlWriter.cs.
References IG.Lib.HtmlWriter._headWritten, IG.Lib.HtmlWriter.AppendAttributes(), IG.Lib.HtmlWriter.AppendPlainText(), IG.Lib.HtmlWriter.GetIndent(), and IG.Lib.HtmlWriter.IsAttributesDefined().
Referenced by IG.Lib.HtmlWriter.WriteMetaContent(), and IG.Lib.HtmlWriter.WriteMetaTag().
WriteMetaContent()
virtual void IG.Lib.HtmlWriter.WriteMetaContent () inline protected virtual
Adds a contenbt meta tag.
Must be called within the method for writing document head.
Definition at line 364 of file HtmlWriter.cs.
References IG.Lib.HtmlWriter.WriteMetaTagGeneral().
Referenced by IG.Lib.HtmlWriter.BeginDocument().
WriteMetaTag()
virtual void IG.Lib.HtmlWriter.WriteMetaTag (string name, string content) inline protected virtual
Adds a meta tag with specified values of the name and content fields.
Must be called within the method for writing document head.
Parameters
name Name of the meta tag.
content Content of the meta tag.
Definition at line 373 of file HtmlWriter.cs.
References IG.Lib.HtmlWriter.WriteMetaTagGeneral().
Referenced by IG.Lib.HtmlWriter.WriteMetaAuthor(), IG.Lib.HtmlWriter.WriteMetaDescription(), and IG.Lib.HtmlWriter.WriteMetaKeywords().
WriteMetaAuthor()
virtual void IG.Lib.HtmlWriter.WriteMetaAuthor () inline protected virtual
Writes the author meta tag to the document.
Must be called within the method for writing document head.
Definition at line 381 of file HtmlWriter.cs.
References IG.Lib.HtmlWriter.DocumentAuthor, and IG.Lib.HtmlWriter.WriteMetaTag().
Referenced by IG.Lib.HtmlWriter.BeginDocument().
WriteMetaDescription()
virtual void IG.Lib.HtmlWriter.WriteMetaDescription () inline protected virtual
Adds the audescription meta tag to the document.
Must be called within the method for writing document head.
Definition at line 386 of file HtmlWriter.cs.
References IG.Lib.HtmlWriter.DocumentDescription, and IG.Lib.HtmlWriter.WriteMetaTag().
Referenced by IG.Lib.HtmlWriter.BeginDocument().
WriteMetaKeywords()
virtual void IG.Lib.HtmlWriter.WriteMetaKeywords () inline protected virtual
Adds the keywords meta tag to the document.
Must be called within the method for writing document head.
Definition at line 392 of file HtmlWriter.cs.
References IG.Lib.HtmlWriter.GetKeywords(), and IG.Lib.HtmlWriter.WriteMetaTag().
Referenced by IG.Lib.HtmlWriter.BeginDocument().
BeginDocument()
void IG.Lib.HtmlWriter.BeginDocument () inline
Begins the HTML document.
Adds HTML head if necessary.
Definition at line 416 of file HtmlWriter.cs.
References IG.Lib.HtmlWriter._headWritten, IG.Lib.HtmlWriter._lockBeginDocument, IG.Lib.HtmlWriter.AppendPlainText(), IG.Lib.HtmlWriter.IndentLevel, IG.Lib.HtmlWriter.WriteCssPath(), IG.Lib.HtmlWriter.WriteDocumentComments(), IG.Lib.HtmlWriter.WriteDocumentStyle(), IG.Lib.HtmlWriter.WriteDocumentTitle(), IG.Lib.HtmlWriter.WriteMetaAuthor(), IG.Lib.HtmlWriter.WriteMetaContent(), IG.Lib.HtmlWriter.WriteMetaDescription(), and IG.Lib.HtmlWriter.WriteMetaKeywords().
EndDocument()
void IG.Lib.HtmlWriter.EndDocument () inline
Ends the HTML document. After this method is called, writing is not possible any more.
Definition at line 459 of file HtmlWriter.cs.
References IG.Lib.HtmlWriter._sectionLevel, IG.Lib.HtmlWriter._tailWritten, IG.Lib.HtmlWriter.AppendPlainText(), and IG.Lib.HtmlWriter.EndSection().
Referenced by IG.Lib.HtmlWriter.Example().
AppendPlainText()
void IG.Lib.HtmlWriter.AppendPlainText (string text) inline
Adds plain text to HTML (without any markup, indentation or newlines, unless contained in the text string).
Parameters
text Text to be added.
Definition at line 481 of file HtmlWriter.cs.
References IG.Lib.HtmlWriter.Writer.
Referenced by IG.Lib.HtmlWriter.AddImage(), IG.Lib.HtmlWriter.AddImageCaption(), IG.Lib.HtmlWriter.AddNewLine(), IG.Lib.HtmlWriter.AddTag(), IG.Lib.HtmlWriter.AppendAttributes(), IG.Lib.HtmlWriter.BeginDocument(), IG.Lib.HtmlWriter.BeginTagWithText(), IG.Lib.HtmlWriter.EndDocument(), IG.Lib.HtmlWriter.EndTag(), IG.Lib.HtmlWriter.WriteCssPath(), IG.Lib.HtmlWriter.WriteDocumentComments(), IG.Lib.HtmlWriter.WriteDocumentStyle(), IG.Lib.HtmlWriter.WriteDocumentTitle(), and IG.Lib.HtmlWriter.WriteMetaTagGeneral().
AddPlainTextLine()
void IG.Lib.HtmlWriter.AddPlainTextLine (string text) inline
Adds a line of plain text to HTML (without any markup, unless contained in the text string), indented and with newline fillowed.
Parameters
text Text to be added.
Definition at line 489 of file HtmlWriter.cs.
References IG.Lib.HtmlWriter.GetIndent(), and IG.Lib.HtmlWriter.Writer.
Referenced by IG.Lib.HtmlWriter.Example().
BeginTag() [1/2]
void IG.Lib.HtmlWriter.BeginTag (string tagName) inline
Adds the specified tag to the document.
Parameters
tagName Tag name.
Definition at line 498 of file HtmlWriter.cs.
References IG.Lib.HtmlWriter.BeginTagWithText().
Referenced by IG.Lib.HtmlWriter.BeginSection().
BeginTag() [2/2]
void IG.Lib.HtmlWriter.BeginTag (string tagName, params string[] attributeNameValuePairs) inline
Adds the specified tag to the document.
Parameters
tagName Tag name.
attributeNameValuePairs Pairs of attribute names and values that will be added to the tag.
Definition at line 506 of file HtmlWriter.cs.
References IG.Lib.HtmlWriter.BeginTagWithText().
BeginTagWithText() [1/2]
void IG.Lib.HtmlWriter.BeginTagWithText (string tagName, string text) inline
Adds the specified tag containing the specified text to the document.
Parameters
tagName Tag name.
text Tag text.
Definition at line 514 of file HtmlWriter.cs.
Referenced by IG.Lib.HtmlWriter.BeginTag().
BeginTagWithText() [2/2]
void IG.Lib.HtmlWriter.BeginTagWithText (string tagName, string text, params string[] attributeNameValuePairs) inline
Adds the specified tag containing the specified text to the document.
Parameters
tagName Tag name.
text Tag text.
attributeNameValuePairs Pairs of attribute names and values that will be added to the tag.
Definition at line 523 of file HtmlWriter.cs.
References IG.Lib.HtmlWriter.AppendAttributes(), IG.Lib.HtmlWriter.AppendPlainText(), IG.Lib.HtmlWriter.GetIndent(), IG.Lib.HtmlWriter.IndentLevel, and IG.Lib.HtmlWriter.Writer.
EndTag()
void IG.Lib.HtmlWriter.EndTag (string tagName) inline
Adds the specified tag containing the specified text to the document.
Parameters
tagName Tag name.
Definition at line 535 of file HtmlWriter.cs.
References IG.Lib.HtmlWriter.AppendPlainText(), IG.Lib.HtmlWriter.GetIndent(), and IG.Lib.HtmlWriter.IndentLevel.
Referenced by IG.Lib.HtmlWriter.EndSection().
BeginSection()
void IG.Lib.HtmlWriter.BeginSection (params string[] attributeNameValuePairs) inline
Begins a new section.
Parameters
attributeNameValuePairs Eventual attributes (in form of attribute name - value pairs).
Definition at line 547 of file HtmlWriter.cs.
References IG.Lib.HtmlWriter._sectionLevel, and IG.Lib.HtmlWriter.BeginTag().
Referenced by IG.Lib.HtmlWriter.Example().
EndSection()
void IG.Lib.HtmlWriter.EndSection () inline
Ends a section.
Definition at line 556 of file HtmlWriter.cs.
References IG.Lib.HtmlWriter._sectionLevel, and IG.Lib.HtmlWriter.EndTag().
Referenced by IG.Lib.HtmlWriter.EndDocument(), and IG.Lib.HtmlWriter.Example().
AddNewLine()
void IG.Lib.HtmlWriter.AddNewLine () inline
Adds a newline to HTML.
Definition at line 568 of file HtmlWriter.cs.
References IG.Lib.HtmlWriter.AppendPlainText(), and IG.Lib.HtmlWriter.GetIndent().
Referenced by IG.Lib.HtmlWriter.Example().
IsAttributesDefined()
bool IG.Lib.HtmlWriter.IsAttributesDefined (string[] attributeNameValuePairs) inline protected
Returns true if the specified array of attribute name-value pairs defines any attributes, false otherwise.
Parameters
attributeNameValuePairs Pairs of attribute names and values to be added to some tag.
Returns
true if the specified array of attribute name-value pairs means that any attributes are defined, false otherwise.
Definition at line 577 of file HtmlWriter.cs.
Referenced by IG.Lib.HtmlWriter.AppendAttributes(), and IG.Lib.HtmlWriter.WriteMetaTagGeneral().
AppendAttributes()
void IG.Lib.HtmlWriter.AppendAttributes (string[] attributeNameValuePairs) inline
Writes definition of the specified attriutes of a HTML element to the HTML document.
Parameters
attributeNameValuePairs Pairs of attribute names and values that will be added to the html element.
Definition at line 587 of file HtmlWriter.cs.
References IG.Lib.HtmlWriter.AppendPlainText(), and IG.Lib.HtmlWriter.IsAttributesDefined().
Referenced by IG.Lib.HtmlWriter.AddTag(), IG.Lib.HtmlWriter.BeginTagWithText(), and IG.Lib.HtmlWriter.WriteMetaTagGeneral().
AddTag() [1/4]
void IG.Lib.HtmlWriter.AddTag (string tagName, string text, bool withLineBreak) inline
Adds the specified tag containing the specified text to the document.
Parameters
tagName Tag name.
text Tag text.
withLineBreak Whether line break is added or not.
Definition at line 615 of file HtmlWriter.cs.
Referenced by IG.Lib.HtmlWriter.AddHeading1(), IG.Lib.HtmlWriter.AddHeading2(), IG.Lib.HtmlWriter.AddHeading3(), IG.Lib.HtmlWriter.AddHeading4(), IG.Lib.HtmlWriter.AddParagraph(), and IG.Lib.HtmlWriter.AddTag().
AddTag() [2/4]
void IG.Lib.HtmlWriter.AddTag (string tagName, string text) inline
Adds the specified tag containing the specified text to the document.
Tag has no attributes. Line break is not added.
Parameters
tagName Tag name.
text Tag text.
Definition at line 624 of file HtmlWriter.cs.
References IG.Lib.HtmlWriter.AddTag().
AddTag() [3/4]
void IG.Lib.HtmlWriter.AddTag (string tagName, string text, params string[] attributeNameValuePairs) inline
Adds the specified tag containing the specified text to the document.
Line breakis not added.
Parameters
tagName Tag name.
text Tag text.
attributeNameValuePairs Pairs of attribute names and values that will be added to the tag.
Definition at line 634 of file HtmlWriter.cs.
References IG.Lib.HtmlWriter.AddTag().
AddTag() [4/4]
void IG.Lib.HtmlWriter.AddTag (string tagName, string text, bool withLineBreak, params string[] attributeNameValuePairs) inline
Adds the specified tag containing the specified text to the document.
Parameters
tagName Tag name.
text Tag text.
withLineBreak Whether line break is added or not.
attributeNameValuePairs Pairs of attribute names and values that will be added to the tag.
Definition at line 645 of file HtmlWriter.cs.
References IG.Lib.HtmlWriter.AppendAttributes(), IG.Lib.HtmlWriter.AppendPlainText(), IG.Lib.HtmlWriter.GetIndent(), and IG.Lib.HtmlWriter.Writer.
AddParagraph() [1/2]
void IG.Lib.HtmlWriter.AddParagraph (string paragraphText, string[] attributeNameValuePairs) inline
Adds a new paragraph with the specified text to the HTML document.
Parameters
paragraphText Text of the paragraph.
attributeNameValuePairs Pairs of attribute names and values that will be added to the tag.
Definition at line 666 of file HtmlWriter.cs.
References IG.Lib.HtmlWriter.AddTag().
Referenced by IG.Lib.HtmlWriter.AddParagraph(), and IG.Lib.HtmlWriter.Example().
AddParagraph() [2/2]
void IG.Lib.HtmlWriter.AddParagraph (string paragraphText) inline
Adds a new paragraph with the specified text to the HTML document.
The added HTML element has no attributes.
Parameters
paragraphText Text of the paragraph.
Definition at line 674 of file HtmlWriter.cs.
References IG.Lib.HtmlWriter.AddParagraph().
AddHeading1() [1/2]
void IG.Lib.HtmlWriter.AddHeading1 (string headingText, params string[] attributeNameValuePairs) inline
Adds a new level 1 heading with the specified text to the HTML document.
Parameters
headingText Text of the heading.
attributeNameValuePairs Pairs of attribute names and values that will be added to the tag.
Definition at line 682 of file HtmlWriter.cs.
References IG.Lib.HtmlWriter.AddTag().
Referenced by IG.Lib.HtmlWriter.AddHeading1(), and IG.Lib.HtmlWriter.Example().
AddHeading1() [2/2]
void IG.Lib.HtmlWriter.AddHeading1 (string headingText) inline
Adds a new level 1 heading with the specified text to the HTML document.
The added HTML element has no attributes.
Parameters
headingText Text of the heading.
Definition at line 690 of file HtmlWriter.cs.
References IG.Lib.HtmlWriter.AddHeading1().
AddHeading2() [1/2]
void IG.Lib.HtmlWriter.AddHeading2 (string headingText, params string[] attributeNameValuePairs) inline
Adds a new level 2 heading with the specified text to the HTML document.
Parameters
headingText Text of the heading.
attributeNameValuePairs Pairs of attribute names and values that will be added to the tag.
Definition at line 698 of file HtmlWriter.cs.
References IG.Lib.HtmlWriter.AddTag().
Referenced by IG.Lib.HtmlWriter.AddHeading2(), and IG.Lib.HtmlWriter.Example().
AddHeading2() [2/2]
void IG.Lib.HtmlWriter.AddHeading2 (string headingText) inline
Adds a new level 2 heading with the specified text to the HTML document.
The added HTML element has no attributes.
Parameters
headingText Text of the heading.
Definition at line 706 of file HtmlWriter.cs.
References IG.Lib.HtmlWriter.AddHeading2().
AddHeading3() [1/2]
void IG.Lib.HtmlWriter.AddHeading3 (string headingText, params string[] attributeNameValuePairs) inline
Adds a new level 3 heading with the specified text to the HTML document.
Parameters
headingText Text of the heading.
attributeNameValuePairs Pairs of attribute names and values that will be added to the tag.
Definition at line 714 of file HtmlWriter.cs.
References IG.Lib.HtmlWriter.AddTag().
Referenced by IG.Lib.HtmlWriter.AddHeading3().
AddHeading3() [2/2]
void IG.Lib.HtmlWriter.AddHeading3 (string headingText) inline
Adds a new level 3 heading with the specified text to the HTML document.
The added HTML element has no attributes.
Parameters
headingText Text of the heading.
Definition at line 722 of file HtmlWriter.cs.
References IG.Lib.HtmlWriter.AddHeading3().
AddHeading4() [1/2]
void IG.Lib.HtmlWriter.AddHeading4 (string headingText, params string[] attributeNameValuePairs) inline
Adds a new level 4 heading with the specified text to the HTML document.
Parameters
headingText Text of the heading.
attributeNameValuePairs Pairs of attribute names and values that will be added to the tag.
Definition at line 730 of file HtmlWriter.cs.
References IG.Lib.HtmlWriter.AddTag().
Referenced by IG.Lib.HtmlWriter.AddHeading4().
AddHeading4() [2/2]
void IG.Lib.HtmlWriter.AddHeading4 (string headingText) inline
Adds a new level 4 heading with the specified text to the HTML document.
The added HTML element has no attributes.
Parameters
headingText Text of the heading.
Definition at line 738 of file HtmlWriter.cs.
References IG.Lib.HtmlWriter.AddHeading4().
AddImage() [1/2]
void IG.Lib.HtmlWriter.AddImage (string imageLink, string altText, string captionText, int width, int height, int originalWidth, int originalHeight, bool constrainRatio) inline
Adds a linked image to the HTML document with specified custom size different than the original size.
It is possible to constraint height/width ratio to the original one, in this case the original width and height must be specified.
Parameters
imageLink Link to the image. Must not be null or empty string.
altText Alternative text to be displayed when image is not shown.
captionText Text below the image.
width Width of the image in pixels. Takes effect when size is defined.
height Height of the image in pixels. Takes effect when size is defined.
originalWidth Original image width. Must be specified only if the ratio is constrained (i.e. if constrainRatio = true)
originalHeight Original image height. Must be specified only if the ratio is constrained (i.e. if constrainRatio = true)
constrainRatio If true then ratio between width and height is kept the same as in the original. In this case, original width and height must be specified, too.
When ratio between image width and height is not constrained to the original ratio of the image (constrainRatio = false) both width and height must be greater than 0 and they represent image dimensions in rendered HTML.
When ratio between image width and height is constrained to the original ratio of the image (constrainRatio = true), either the specified width or height may be less or equal to 0. In this case the remaining dimension is calculatd from the specified one in such a way that original ratio between width and height is preserved.
When ratio between image width and height is constrained to the original ratio of the image (constrainRatio = true) and both image width and height are specified,
Definition at line 769 of file HtmlWriter.cs.
Referenced by IG.Lib.HtmlWriter.Example().
AddImage() [2/2]
void IG.Lib.HtmlWriter.AddImage (string imageLink, string altText, string captionText, int width, int height, bool defineSize) inline
Adds a linked image to the HTML document.
Parameters
imageLink Link to the image. Must not be null or empty string.
altText Alternative text to be displayed when image is not shown.
captionText Text below the image.
width Width of the image in pixels. Takes effect when defineSize =true.
height Width of the image in pixels. Takes effect when defineSize =true.
defineSize Whether size (in pixels) of the displayed image is defined or not.
Definition at line 815 of file HtmlWriter.cs.
References IG.Lib.HtmlWriter.AddImageCaption(), IG.Lib.HtmlWriter.AppendPlainText(), and IG.Lib.HtmlWriter.GetIndent().
AddImageCaption()
void IG.Lib.HtmlWriter.AddImageCaption (string captionText) inline protected
Adds Image caption to the current HTML document.
Parameters
captionText Caption text.
Definition at line 844 of file HtmlWriter.cs.
References IG.Lib.HtmlWriter._imageNum, IG.Lib.HtmlWriter.AppendPlainText(), IG.Lib.HtmlWriter.GetIndent(), and IG.Lib.HtmlWriter.ImageCaption.
Referenced by IG.Lib.HtmlWriter.AddImage().
Dispose() [1/2]
void IG.Lib.HtmlWriter.Dispose () inline
Implementation of IDisposable interface.
Definition at line 868 of file HtmlWriter.cs.
Referenced by IG.Lib.HtmlWriter.~HtmlWriter().
Dispose() [2/2]
virtual void IG.Lib.HtmlWriter.Dispose (bool disposing) inline protected virtual
Does the job of freeing resources.
This method can be eventually overridden in derived classes (if they use other resources that must be freed - in addition to such resources of the current class). In the case of overriding this method, you should usually call the base. See disposing . in the overriding method.
Parameters
disposing Tells whether the method has been called form Dispose() method.
Definition at line 880 of file HtmlWriter.cs.
References IG.Lib.HtmlWriter.CloseWriter(), and IG.Lib.HtmlWriter.disposed.
Example()
static void IG.Lib.HtmlWriter.Example (string htmlDocumentPath, string styleSheetPath, string imagePath1, string imagePath2) inline static
Writes an example HTML document.
Parameters
htmlDocumentPath Path to the created HTML document.
styleSheetPath Path to StyleSheet (CSS file).
imagePath1 Path to the first image included (can be null).
imagePath2 Path to the second image included (can be null).
Definition at line 907 of file HtmlWriter.cs.
References IG.Lib.HtmlWriter.AddHeading1(), IG.Lib.HtmlWriter.AddHeading2(), IG.Lib.HtmlWriter.AddImage(), IG.Lib.HtmlWriter.AddKeywords(), IG.Lib.HtmlWriter.AddNewLine(), IG.Lib.HtmlWriter.AddParagraph(), IG.Lib.HtmlWriter.AddPlainTextLine(), IG.Lib.HtmlWriter.BeginSection(), IG.Lib.HtmlWriter.CloseWriter(), IG.Lib.HtmlWriter.ConstAttributeClass, IG.Lib.HtmlWriter.ConstAttributeId, IG.Lib.HtmlWriter.DocumentStyle, IG.Lib.HtmlWriter.DocumentTitle, IG.Lib.HtmlWriter.EndDocument(), IG.Lib.HtmlWriter.EndSection(), IG.Lib.HtmlWriter.HtmlWriter(), and IG.Lib.UtilSystem.OpenFileInDefaultBrowser().
Member Data Documentation
_headWritten
bool IG.Lib.HtmlWriter._headWritten = false protected
Definition at line 112 of file HtmlWriter.cs.
Referenced by IG.Lib.HtmlWriter.BeginDocument(), IG.Lib.HtmlWriter.WriteCssPath(), IG.Lib.HtmlWriter.WriteDocumentComments(), IG.Lib.HtmlWriter.WriteDocumentStyle(), IG.Lib.HtmlWriter.WriteDocumentTitle(), and IG.Lib.HtmlWriter.WriteMetaTagGeneral().
_tailWritten
bool IG.Lib.HtmlWriter._tailWritten = false protected
Definition at line 114 of file HtmlWriter.cs.
Referenced by IG.Lib.HtmlWriter.EndDocument().
_filePath
string IG.Lib.HtmlWriter._filePath protected
Definition at line 116 of file HtmlWriter.cs.
IndentSpaces
int IG.Lib.HtmlWriter.IndentSpaces = 2
Number of spaces used in each level of indentation)
Definition at line 128 of file HtmlWriter.cs.
Referenced by IG.Lib.HtmlWriter.GetIndent().
IndentLevel
int IG.Lib.HtmlWriter.IndentLevel = 0 protected
Current level of indentation.
Definition at line 131 of file HtmlWriter.cs.
Referenced by IG.Lib.HtmlWriter.BeginDocument(), IG.Lib.HtmlWriter.BeginTagWithText(), IG.Lib.HtmlWriter.EndTag(), IG.Lib.HtmlWriter.GetIndent(), and IG.Lib.HtmlWriter.GetIndentLevel().
_cssPath
string IG.Lib.HtmlWriter._cssPath protected
Definition at line 157 of file HtmlWriter.cs.
_styleString
string IG.Lib.HtmlWriter._styleString protected
Definition at line 167 of file HtmlWriter.cs.
_documentTitle
string IG.Lib.HtmlWriter._documentTitle = "Generated HTML Document" protected
Definition at line 176 of file HtmlWriter.cs.
_documentAuthor
string IG.Lib.HtmlWriter._documentAuthor = "IGLIb (by Igor Gresovnik)" protected
Definition at line 184 of file HtmlWriter.cs.
_documentDescription
string IG.Lib.HtmlWriter._documentDescription = "This document was programatically generated by IGLib (Investigative Generic Library), http://www2.arnes.si/~ljc3m2/igor/iglib/" protected
Definition at line 192 of file HtmlWriter.cs.
_documentComments
List<string> IG.Lib.HtmlWriter._documentComments protected
Definition at line 200 of file HtmlWriter.cs.
Referenced by IG.Lib.HtmlWriter.AddDocumentComment(), and IG.Lib.HtmlWriter.GetDocumentComments().
_keywords
List<string> IG.Lib.HtmlWriter._keywords protected
Definition at line 225 of file HtmlWriter.cs.
Referenced by IG.Lib.HtmlWriter.AddSingleKeyWord(), and IG.Lib.HtmlWriter.GetKeywords().
_writer
TextWriter IG.Lib.HtmlWriter._writer protected
Definition at line 263 of file HtmlWriter.cs.
Referenced by IG.Lib.HtmlWriter.CloseWriter().
_lockBeginDocument
bool IG.Lib.HtmlWriter._lockBeginDocument = false protected
Definition at line 412 of file HtmlWriter.cs.
Referenced by IG.Lib.HtmlWriter.BeginDocument().
_sectionLevel
int IG.Lib.HtmlWriter._sectionLevel = 0 private
Definition at line 543 of file HtmlWriter.cs.
Referenced by IG.Lib.HtmlWriter.BeginSection(), IG.Lib.HtmlWriter.EndDocument(), and IG.Lib.HtmlWriter.EndSection().
_imageNum
int IG.Lib.HtmlWriter._imageNum = 0 private
Definition at line 838 of file HtmlWriter.cs.
Referenced by IG.Lib.HtmlWriter.AddImageCaption().
ImageCaption
string IG.Lib.HtmlWriter.ImageCaption = "Figure"
Definition at line 840 of file HtmlWriter.cs.
Referenced by IG.Lib.HtmlWriter.AddImageCaption().
disposed
bool IG.Lib.HtmlWriter.disposed = false private
Definition at line 865 of file HtmlWriter.cs.
Referenced by IG.Lib.HtmlWriter.Dispose().
Property Documentation
ConstAttributeClass
string IG.Lib.HtmlWriter.ConstAttributeClass get
The class attribute. Specifies one or more classnames for an element (refers to a class in a style sheet).
Definition at line 83 of file HtmlWriter.cs.
Referenced by IG.Lib.HtmlWriter.Example().
ConstAttributeId
string IG.Lib.HtmlWriter.ConstAttributeId get
The id attribute. Specifies a unique id for an element.
Definition at line 86 of file HtmlWriter.cs.
Referenced by IG.Lib.HtmlWriter.Example().
ConstAttributeStyle
string IG.Lib.HtmlWriter.ConstAttributeStyle get
The style attribute. Specifies an inline CSS style for an element.
Definition at line 89 of file HtmlWriter.cs.
ConstAttributeTitle
string IG.Lib.HtmlWriter.ConstAttributeTitle get
The style attribute. Specifies extra information about an element.
Definition at line 92 of file HtmlWriter.cs.
ConstAttributeTextDirection
string IG.Lib.HtmlWriter.ConstAttributeTextDirection get
The text direction attribute. Specifies text direction for the content in an element.
Definition at line 95 of file HtmlWriter.cs.
ConstAttributeLanguage
string IG.Lib.HtmlWriter.ConstAttributeLanguage get
The language attribute. Specifies the language of the element's content.
Definition at line 98 of file HtmlWriter.cs.
ConstAttributeLanguageXml
string IG.Lib.HtmlWriter.ConstAttributeLanguageXml get
The xml language attribute. Specifies the language of the element's content (for XHTML documents).
Definition at line 101 of file HtmlWriter.cs.
ConstAttributeShortcutKey
string IG.Lib.HtmlWriter.ConstAttributeShortcutKey get
The shortcut key attribute. Specifies a shortcut key to activate/focus an element.
Definition at line 104 of file HtmlWriter.cs.
ConstAttributeTabIndex
string IG.Lib.HtmlWriter.ConstAttributeTabIndex get
The tab index attribute. Specifies the tabbing order of an element.
Definition at line 107 of file HtmlWriter.cs.
FilePath
string IG.Lib.HtmlWriter.FilePath get protected set
Path to file containing the generator.
Definition at line 120 of file HtmlWriter.cs.
Referenced by IG.Lib.HtmlWriter.HtmlWriter().
CssPath
string IG.Lib.HtmlWriter.CssPath get set
Path to the associated CSS file (Cascaded Style Sheets).
Must be set before the document head is written, otherwise it will have no effect.
Definition at line 162 of file HtmlWriter.cs.
Referenced by IG.Lib.HtmlWriter.HtmlWriter(), and IG.Lib.HtmlWriter.WriteCssPath().
DocumentStyle
string IG.Lib.HtmlWriter.DocumentStyle get set
CSS string with internal style definitions.
Definition at line 171 of file HtmlWriter.cs.
Referenced by IG.Lib.HtmlWriter.Example(), and IG.Lib.HtmlWriter.WriteDocumentStyle().
DocumentTitle
virtual string IG.Lib.HtmlWriter.DocumentTitle get set
Definition at line 179 of file HtmlWriter.cs.
Referenced by IG.Lib.HtmlWriter.Example(), and IG.Lib.HtmlWriter.WriteDocumentTitle().
DocumentAuthor
virtual string IG.Lib.HtmlWriter.DocumentAuthor get set
Definition at line 187 of file HtmlWriter.cs.
Referenced by IG.Lib.HtmlWriter.WriteMetaAuthor().
DocumentDescription
virtual string IG.Lib.HtmlWriter.DocumentDescription get set
Definition at line 195 of file HtmlWriter.cs.
Referenced by IG.Lib.HtmlWriter.WriteMetaDescription().
Writer
TextWriter IG.Lib.HtmlWriter.Writer get
Text writer used for writing on the document.
Lazy evaluation, automatically opened when first needed.
Definition at line 268 of file HtmlWriter.cs.
Referenced by IG.Lib.HtmlWriter.AddPlainTextLine(), IG.Lib.HtmlWriter.AddTag(), IG.Lib.HtmlWriter.AppendPlainText(), and IG.Lib.HtmlWriter.BeginTagWithText().
The documentation for this class was generated from the following file:
iglib/igbase/data/presentation/HtmlWriter.cs