Doc: IGLib with source files: IGLib.Parsing.CommandLineParserSimple Class Reference
IGLib.Parsing.CommandLineParserSimple Class Reference
Static Public Member Functions
static IEnumerable< string > SplitCommandLine (string commandLine)
static void Test (string cmdLine, params string[] args)
static void PerformSomeTests ()
Detailed Description
Implementation that follows this:
https://stackoverflow.com/questions/298830/split-string-containing-command-line-parameters-into-string-in-c-sharp
Definition at line 61 of file CommandLineParserSimple.cs.
Member Function Documentation
SplitCommandLine()
static IEnumerable<string> IGLib.Parsing.CommandLineParserSimple.SplitCommandLine (string commandLine) inline static
Definition at line 65 of file CommandLineParserSimple.cs.
Referenced by IGLib.Parsing.CommandLineParserSimple.Test().
Test()
static void IGLib.Parsing.CommandLineParserSimple.Test (string cmdLine, params string[] args) inline static
Definition at line 80 of file CommandLineParserSimple.cs.
References IGLib.Parsing.CommandLineParserSimple.SplitCommandLine().
Referenced by IGLib.Parsing.CommandLineParserSimple.PerformSomeTests().
PerformSomeTests()
static void IGLib.Parsing.CommandLineParserSimple.PerformSomeTests () inline static
Definition at line 90 of file CommandLineParserSimple.cs.
References IGLib.Parsing.CommandLineParserSimple.Test().
The documentation for this class was generated from the following file:
IGLibCore/src/IGLib.Core/Parsing/CommansLineParsing/CommandLineParserSimple.cs