Doc: IGLib with source files: IG.Lib.SerializerBase.SerializationTestClass Class Reference
IG.Lib.SerializerBase.SerializationTestClass Class Reference
Test class for testing serialization.
Public Member Functions
SerializationTestClass ()
SerializationTestClass (string objectName)
override string ToString ()
virtual void InitTestObject (int d1, int d2, int dim3d1, int dim3d2, int dim3d3)
Initializes the test object.
Static Public Member Functions
static SerializationTestClass CreateTestObject ()
static SerializationTestClass CreateTestObject (int d1, int d2, int dim3d1, int dim3d2, int dim3d3)
Creates an object for testing serialization.
Protected Member Functions
virtual void InitTestArray3D (int d1, int d2, int d3)
Initializes the 3D array on test object.
Properties
virtual string ObjectName [get, set]
virtual string ObjectNameModified [get, set]
virtual double DNum [get, set]
virtual bool BFlag [get, set]
virtual SerializationTestArrayMember SingleElement [get, set]
virtual SerializationTestArrayMember[] Array1D [get, set]
virtual SerializationTestArrayMember[][] JaggedArray2D [get, set]
double[][][] ZArray3D [get, set]
Three dimensional array of doubles.
Properties inherited from IG.Lib.SerializerBase.ISerializationTestClass
string ObjectName [get, set]
string ObjectNameModified [get, set]
double DNum [get, set]
SerializationTestArrayMember SingleElement [get, set]
SerializationTestArrayMember[] Array1D [get, set]
SerializationTestArrayMember[][] JaggedArray2D [get, set]
Private Attributes
string _objectName
string _objectNameModified
double _dnum
bool _bflag
SerializationTestArrayMember _singleElement
SerializationTestArrayMember[] _testArray
SerializationTestArrayMember[][] _testJaggedArray2d
SerializationTestArrayMember[,] _rectangularArray2d
double[][][] _array3D
Detailed Description
Test class for testing serialization.
$A Igor Jun10;
Definition at line 720 of file SerializerBase.cs.
Constructor & Destructor Documentation
SerializationTestClass() [1/2]
IG.Lib.SerializerBase.SerializationTestClass.SerializationTestClass () inline
Definition at line 723 of file SerializerBase.cs.
Referenced by IG.Lib.SerializerBase.SerializationTestClass.CreateTestObject().
SerializationTestClass() [2/2]
IG.Lib.SerializerBase.SerializationTestClass.SerializationTestClass (string objectName) inline
Definition at line 728 of file SerializerBase.cs.
References IG.Lib.SerializerBase.SerializationTestClass.ObjectName.
Member Function Documentation
ToString()
override string IG.Lib.SerializerBase.SerializationTestClass.ToString () inline
Definition at line 787 of file SerializerBase.cs.
References IG.Lib.SerializerBase.SerializationTestClass.Array1D, IG.Lib.SerializerBase.SerializationTestClass.DNum, IG.Lib.SerializerBase.SerializationTestClass.JaggedArray2D, IG.Lib.SerializerBase.SerializationTestClass.ObjectName, IG.Lib.SerializerBase.SerializationTestClass.ObjectNameModified, IG.Lib.SerializerBase.SerializationTestClass.SingleElement, and IG.Lib.SerializerBase.SerializationTestArrayMember.ToString().
InitTestArray3D()
virtual void IG.Lib.SerializerBase.SerializationTestClass.InitTestArray3D (int d1, int d2, int d3) inline protected virtual
Initializes the 3D array on test object.
Parameters
d1 First dimension.
d2 Second dimension.
d3 Third dimension.
Definition at line 872 of file SerializerBase.cs.
References IG.Lib.SerializerBase.SerializationTestClass.ZArray3D.
Referenced by IG.Lib.SerializerBase.SerializationTestClass.InitTestObject().
InitTestObject()
virtual void IG.Lib.SerializerBase.SerializationTestClass.InitTestObject (int d1, int d2, int dim3d1, int dim3d2, int dim3d3) inline virtual
Initializes the test object.
Parameters
d1 First dimension for 2D arrays of objects.
d2 Second dimension for 2D arrays of objects.
dim3d1 First dimension for 3D plain array.
dim3d2 Second dimension for 3D plain arrray.
dim3d3 Third dimension for 3D plain array.
Definition at line 894 of file SerializerBase.cs.
References IG.Lib.SerializerBase.SerializationTestClass.Array1D, IG.Lib.SerializerBase.SerializationTestClass.DNum, IG.Lib.SerializerBase.SerializationTestArrayMember.Index1, IG.Lib.SerializerBase.SerializationTestArrayMember.Index2, IG.Lib.SerializerBase.SerializationTestClass.InitTestArray3D(), IG.Lib.SerializerBase.SerializationTestClass.JaggedArray2D, and IG.Lib.SerializerBase.SerializationTestClass.SingleElement.
Referenced by IG.Lib.SerializerBase.SerializationTestClass.CreateTestObject().
CreateTestObject() [1/2]
static SerializationTestClass IG.Lib.SerializerBase.SerializationTestClass.CreateTestObject () inline static
Definition at line 943 of file SerializerBase.cs.
Referenced by IG.Lib.SerializerBase.TestSerializationAll(), and IG.Lib.SerializerBase.TestSerializationJSON().
CreateTestObject() [2/2]
static SerializationTestClass IG.Lib.SerializerBase.SerializationTestClass.CreateTestObject (int d1, int d2, int dim3d1, int dim3d2, int dim3d3) inline static
Creates an object for testing serialization.
Parameters
d1 First dimension for 2D arrays of objects.
d2 Second dimension for 2D arrays of objects.
dim3d1 First dimension for 3D plain array.
dim3d2 Second dimension for 3D plain arrray.
dim3d3 Third dimension for 3D plain array.
Returns
Object of class SerializationTestClass that can be used to test serialization.
Definition at line 955 of file SerializerBase.cs.
References IG.Lib.SerializerBase.SerializationTestClass.InitTestObject(), and IG.Lib.SerializerBase.SerializationTestClass.SerializationTestClass().
Member Data Documentation
_objectName
string IG.Lib.SerializerBase.SerializationTestClass._objectName private
Definition at line 733 of file SerializerBase.cs.
_objectNameModified
string IG.Lib.SerializerBase.SerializationTestClass._objectNameModified private
Definition at line 735 of file SerializerBase.cs.
_dnum
double IG.Lib.SerializerBase.SerializationTestClass._dnum private
Definition at line 737 of file SerializerBase.cs.
_bflag
bool IG.Lib.SerializerBase.SerializationTestClass._bflag private
Definition at line 739 of file SerializerBase.cs.
_singleElement
SerializationTestArrayMember IG.Lib.SerializerBase.SerializationTestClass._singleElement private
Definition at line 753 of file SerializerBase.cs.
_testArray
SerializationTestArrayMember [] IG.Lib.SerializerBase.SerializationTestClass._testArray private
Definition at line 755 of file SerializerBase.cs.
_testJaggedArray2d
SerializationTestArrayMember [][] IG.Lib.SerializerBase.SerializationTestClass._testJaggedArray2d private
Definition at line 757 of file SerializerBase.cs.
_rectangularArray2d
SerializationTestArrayMember [,] IG.Lib.SerializerBase.SerializationTestClass._rectangularArray2d private
Definition at line 762 of file SerializerBase.cs.
_array3D
double [][][] IG.Lib.SerializerBase.SerializationTestClass._array3D private
Definition at line 778 of file SerializerBase.cs.
Property Documentation
ObjectName
virtual string IG.Lib.SerializerBase.SerializationTestClass.ObjectName get set
Definition at line 742 of file SerializerBase.cs.
Referenced by IG.Lib.SerializerBase.SerializationTestClass.SerializationTestClass(), and IG.Lib.SerializerBase.SerializationTestClass.ToString().
ObjectNameModified
virtual string IG.Lib.SerializerBase.SerializationTestClass.ObjectNameModified get set
Definition at line 745 of file SerializerBase.cs.
Referenced by IG.Lib.SerializerBase.SerializationTestClass.ToString().
DNum
virtual double IG.Lib.SerializerBase.SerializationTestClass.DNum get set
Definition at line 748 of file SerializerBase.cs.
Referenced by IG.Lib.SerializerBase.SerializationTestClass.InitTestObject(), and IG.Lib.SerializerBase.SerializationTestClass.ToString().
BFlag
virtual bool IG.Lib.SerializerBase.SerializationTestClass.BFlag get set
Definition at line 751 of file SerializerBase.cs.
SingleElement
virtual SerializationTestArrayMember IG.Lib.SerializerBase.SerializationTestClass.SingleElement get set
Definition at line 765 of file SerializerBase.cs.
Referenced by IG.Lib.SerializerBase.SerializationTestClass.InitTestObject(), and IG.Lib.SerializerBase.SerializationTestClass.ToString().
Array1D
virtual SerializationTestArrayMember [] IG.Lib.SerializerBase.SerializationTestClass.Array1D get set
Definition at line 768 of file SerializerBase.cs.
Referenced by IG.Lib.SerializerBase.SerializationTestClass.InitTestObject(), and IG.Lib.SerializerBase.SerializationTestClass.ToString().
JaggedArray2D
virtual SerializationTestArrayMember [][] IG.Lib.SerializerBase.SerializationTestClass.JaggedArray2D get set
Definition at line 771 of file SerializerBase.cs.
Referenced by IG.Lib.SerializerBase.SerializationTestClass.InitTestObject(), and IG.Lib.SerializerBase.SerializationTestClass.ToString().
ZArray3D
double [][][] IG.Lib.SerializerBase.SerializationTestClass.ZArray3D get set
Three dimensional array of doubles.
Definition at line 782 of file SerializerBase.cs.
Referenced by IG.Lib.SerializerBase.SerializationTestClass.InitTestArray3D().
The documentation for this class was generated from the following file:
iglib/igbase/data/serialization/SerializerBase.cs