Doc: IGLib with source files: IG.Num.RandomGeneratorSystem Class Reference
IG.Num.RandomGeneratorSystem Class Reference
Generator of uniformly distributed random numbers. Based on system random generator. WARNING: Instance members are not guaranteed to be thread safe!
Public Member Functions
RandomGeneratorSystem ()
Initializes a new instance of random generator, using a time-dependent default seed value.
RandomGeneratorSystem (int seed)
Initializes a new instance of random generator, using the specified seed value.
override double NextDouble ()
A double-precision floating point number greater than or equal to 0.0, and LESS THAN 1.0.
virtual double NextDouble (double maxValue)
A double-precision floating point number greater than or equal to 0.0, and LESS than the specified maximum.
virtual double NextDouble (double minValue, double maxValue)
A double-precision floating point number greater than or equal to the specified minimum, and LESS THAN the specified maximum.
virtual double NextDoubleInclusive ()
A double-precision floating point number greater than or equal to 0.0, and LESS OR EQUAL than 1.0.
virtual double NextDoubleInclusive (double maxValue)
A double-precision floating point number greater than or equal to 0.0, and LESS OR EQUAL than the specified maximum.
virtual double NextDoubleInclusive (double minValue, double maxValue)
A double-precision floating point number greater than or equal to the specified minimum, and LESS OR EQUAL than the specified maximum.
override int Next ()
Returns a nonnegative random number.
override int Next (int maxValue)
Returns a nonnegative random number LESS THAN the specified maximum.
override int Next (int minValue, int maxValue)
Returns a random number within a specified range (lower bound inclusive, UPPER BOUND EXCLUSIVE).
virtual int NextInclusive (int maxValue)
Returns a nonnegative random number LESS OR EQUAL the specified maximum.
virtual int NextInclusive (int minValue, int maxValue)
Returns a random number within a specified range (lower bound inclusive, upper bound INCLUSIVE).
override void NextBytes (byte[] buffer)
Fills the elements of a specified array of bytes with random numbers.
Detailed Description
Generator of uniformly distributed random numbers. Based on system random generator. WARNING: Instance members are not guaranteed to be thread safe!
Definition at line 304 of file Random.cs.
Constructor & Destructor Documentation
RandomGeneratorSystem() [1/2]
IG.Num.RandomGeneratorSystem.RandomGeneratorSystem () inline
Initializes a new instance of random generator, using a time-dependent default seed value.
Definition at line 310 of file Random.cs.
RandomGeneratorSystem() [2/2]
IG.Num.RandomGeneratorSystem.RandomGeneratorSystem (int seed) inline
Initializes a new instance of random generator, using the specified seed value.
Parameters
seed A number used to calculate a starting value for the pseudo-random number sequence. If a negative number is specified, the absolute value of the number is used.
Definition at line 316 of file Random.cs.
Member Function Documentation
NextDouble() [1/3]
override double IG.Num.RandomGeneratorSystem.NextDouble () inline
A double-precision floating point number greater than or equal to 0.0, and LESS THAN 1.0.
Returns
A double-precision floating point number greater than or equal to 0.0, and less than 1.0.
Implements IG.Num.IRandomGenerator.
Definition at line 327 of file Random.cs.
Referenced by IG.Num.RandomGeneratorSystem.NextDouble(), and IG.Num.RandomGeneratorSystem.NextDoubleInclusive().
NextDouble() [2/3]
virtual double IG.Num.RandomGeneratorSystem.NextDouble (double maxValue) inline virtual
A double-precision floating point number greater than or equal to 0.0, and LESS than the specified maximum.
Returns
A double-precision floating point number greater than or equal to 0.0, and LESS THAN THE SPECIFIED MAXIMUM.
Implements IG.Num.IRandomGenerator.
Reimplemented in IG.Num.RandGeneratorThreadSafe.
Definition at line 336 of file Random.cs.
References IG.Num.RandomGeneratorSystem.NextDouble().
NextDouble() [3/3]
virtual double IG.Num.RandomGeneratorSystem.NextDouble (double minValue, double maxValue) inline virtual
A double-precision floating point number greater than or equal to the specified minimum, and LESS THAN the specified maximum.
Returns
A double-precision floating point number greater than or equal to the specified minimum, and LESS than the specified maximum.
Implements IG.Num.IRandomGenerator.
Reimplemented in IG.Num.RandGeneratorThreadSafe.
Definition at line 348 of file Random.cs.
References IG.Num.RandomGeneratorSystem.NextDouble().
NextDoubleInclusive() [1/3]
virtual double IG.Num.RandomGeneratorSystem.NextDoubleInclusive () inline virtual
A double-precision floating point number greater than or equal to 0.0, and LESS OR EQUAL than 1.0.
Returns
A double-precision floating point number greater than or equal to 0.0, and less than 1.0.
Implements IG.Num.IRandomGenerator.
Reimplemented in IG.Num.RandGeneratorThreadSafe.
Definition at line 359 of file Random.cs.
References IG.Num.RandomGeneratorSystem.NextDouble().
Referenced by IG.Num.RandomGeneratorSystem.NextDoubleInclusive().
NextDoubleInclusive() [2/3]
virtual double IG.Num.RandomGeneratorSystem.NextDoubleInclusive (double maxValue) inline virtual
A double-precision floating point number greater than or equal to 0.0, and LESS OR EQUAL than the specified maximum.
Returns
A double-precision floating point number greater than or equal to 0.0, and LESS OR EQUAL THAN THE SPECIFIED MAXIMUM.
Implements IG.Num.IRandomGenerator.
Reimplemented in IG.Num.RandGeneratorThreadSafe.
Definition at line 371 of file Random.cs.
References IG.Num.RandomGeneratorSystem.NextDoubleInclusive().
NextDoubleInclusive() [3/3]
virtual double IG.Num.RandomGeneratorSystem.NextDoubleInclusive (double minValue, double maxValue) inline virtual
A double-precision floating point number greater than or equal to the specified minimum, and LESS OR EQUAL than the specified maximum.
Returns
A double-precision floating point number greater than or equal to the specified minimum, and LESS OR EQUAL than the specified maximum.
Implements IG.Num.IRandomGenerator.
Reimplemented in IG.Num.RandGeneratorThreadSafe.
Definition at line 383 of file Random.cs.
References IG.Num.RandomGeneratorSystem.NextDoubleInclusive().
Next() [1/3]
override int IG.Num.RandomGeneratorSystem.Next () inline
Returns a nonnegative random number.
Returns
A 32-bit signed integer greater than or equal to zero and less than MaxValue.
Implements IG.Num.IRandomGenerator.
Definition at line 393 of file Random.cs.
Referenced by IG.Num.RandomGeneratorSystem.NextInclusive().
Next() [2/3]
override int IG.Num.RandomGeneratorSystem.Next (int maxValue) inline
Returns a nonnegative random number LESS THAN the specified maximum.
Parameters
maxValue The EXCLUSIVE upper bound of the random number to be generated. Must be greater than or equal to zero.
Returns
A 32-bit signed integer greater than or equal to zero, and LESS THAN maxValue. If maxValue equals zero, maxValue is returned.
Implements IG.Num.IRandomGenerator.
Definition at line 403 of file Random.cs.
Next() [3/3]
override int IG.Num.RandomGeneratorSystem.Next (int minValue, int maxValue) inline
Returns a random number within a specified range (lower bound inclusive, UPPER BOUND EXCLUSIVE).
Parameters
minValue The inclusive lower bound of the random number returned.
maxValue The EXCLUSIVE UPPER BOUND of the random number returned. Must be greater than or equal to minValue.
Returns
A 32-bit signed integer greater than or equal to minValue and less than maxValue. If minValue equals maxValue, minValue is returned.
Implements IG.Num.IRandomGenerator.
Definition at line 415 of file Random.cs.
NextInclusive() [1/2]
virtual int IG.Num.RandomGeneratorSystem.NextInclusive (int maxValue) inline virtual
Returns a nonnegative random number LESS OR EQUAL the specified maximum.
Parameters
maxValue The INCLUSIVE upper bound of the random number to be generated. Must be greater than or equal to zero.
Returns
A 32-bit signed integer greater than or equal to zero, and LESS OR EQUAL than maxValue. If maxValue equals zero, maxValue is returned.
Implements IG.Num.IRandomGenerator.
Reimplemented in IG.Num.RandGeneratorThreadSafe.
Definition at line 425 of file Random.cs.
NextInclusive() [2/2]
virtual int IG.Num.RandomGeneratorSystem.NextInclusive (int minValue, int maxValue) inline virtual
Returns a random number within a specified range (lower bound inclusive, upper bound INCLUSIVE).
Parameters
minValue he inclusive lower bound of the random number returned.
maxValue The INCLUSIVE upper bound of the random number returned. Must be greater than or equal to minValue.
Returns
A 32-bit signed integer greater than or equal to minValue and LESS OR EQUAL than maxValue. If minValue equals maxValue, minValue is returned.
Implements IG.Num.IRandomGenerator.
Reimplemented in IG.Num.RandGeneratorThreadSafe.
Definition at line 440 of file Random.cs.
References IG.Num.RandomGeneratorSystem.Next().
NextBytes()
override void IG.Num.RandomGeneratorSystem.NextBytes (byte[] buffer) inline
Fills the elements of a specified array of bytes with random numbers.
Parameters
buffer An array of bytes to contain random numbers.
Implements IG.Num.IRandomGenerator.
Definition at line 450 of file Random.cs.
The documentation for this class was generated from the following file:
IGLibCore/src/IGLib.Core/MathUtils/Random.cs