Doc: IGLib with source files: IG.Num.VectorFunctionRequestDTO Class Reference
IG.Num.VectorFunctionRequestDTO Class Reference
DTO (Data Transfer Objects) for storing contents of vector function evaluation request.
Public Member Functions
VectorFunctionRequestDTO ()
Default constructor.
override VectorFunctionResults CreateObject ()
Creates and returns a new vector function evaluation request object.
Public Member Functions inherited from IG.Lib.SerializationDtoBase< VectorFunctionResults, VectorFunctionResults >
SerializationDtoBase ()
virtual bool GetNull ()
Returns a flag indicating whether the object represented by the current DTO is null.
virtual void SetNull (bool isNull)
Sets a flag indicating whether the object represented by the current DTO is null.
virtual void CopyFromBase (BaseType obj)
Copies data to the current DTO from an object of type BaseType.
virtual void CopyToBase (ref BaseType obj)
Copies data from the current DTO to an object of the base type. Object is created anew if necessary by using the CreateObject() method.
virtual void CopyFrom (Type obj)
Copies data to the current DTO from an object of type Type.
virtual void CopyTo (ref Type obj)
Copies data from the current DTO to an object of type Type. Object is created anew if necessary by using the CreateObject() method.
virtual void CopyFromObject (object obj)
Copies data to the current DTO from an object of type object. The necessary casts are performed.
virtual void CopyToObject (ref object obj)
Copies data from the current DTO to an object of type object. Object is created anew if necessary by using the CreateObject() method. The necessary casts are performed.
override string ToString ()
Creates and returns string representation of the current DTO (data transfer object).
Public Attributes
int NumParameters
Number of parameters of an optimization problem.
int NumFunctons
Number of components (functions) of vector functon.
bool ReqValues = false
Indicates whether calculation of functions is/was requested.
bool ReqGradients = false
Indicates whether calculation of function gradients is/was requested.
bool ReqHessians = false
Indicates whether calculation of functions' Hessians is/was requested.
VectorDtoBase Parameters
Protected Member Functions
override void CopyFromPlain (VectorFunctionResults vectorFunctionRes)
Copies data to the current DTO from an vector function results object.
override void CopyToPlain (ref VectorFunctionResults vectorFunctionRes)
Copies data from the current DTO to a vector object.
Protected Member Functions inherited from IG.Lib.SerializationDtoBase< VectorFunctionResults, VectorFunctionResults >
abstract void CopyFromPlain (BaseType obj)
Copies contents of the specified object to the current DTO (Data Transfer Object).
abstract void CopyToPlain (ref BaseType obj)
Copies contents of the current DTO (Data Transfer Object) to the specified object.
Additional Inherited Members
Protected Attributes inherited from IG.Lib.SerializationDtoBase< VectorFunctionResults, VectorFunctionResults >
bool _isNull
Properties inherited from IG.Lib.SerializationDtoBase< VectorFunctionResults, VectorFunctionResults >
object Lock [get]
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
Detailed Description
DTO (Data Transfer Objects) for storing contents of vector function evaluation request.
$A Igor May0;
Definition at line 24 of file VectorFunctionResultsDto.cs.
Constructor & Destructor Documentation
VectorFunctionRequestDTO()
IG.Num.VectorFunctionRequestDTO.VectorFunctionRequestDTO () inline
Default constructor.
Definition at line 30 of file VectorFunctionResultsDto.cs.
Member Function Documentation
CreateObject()
override VectorFunctionResults IG.Num.VectorFunctionRequestDTO.CreateObject () inline virtual
Creates and returns a new vector function evaluation request object.
Implements IG.Lib.SerializationDtoBase< VectorFunctionResults, VectorFunctionResults >.
Definition at line 60 of file VectorFunctionResultsDto.cs.
CopyFromPlain()
override void IG.Num.VectorFunctionRequestDTO.CopyFromPlain (VectorFunctionResults vectorFunctionRes) inline protected
Copies data to the current DTO from an vector function results object.
Parameters
vectorFunctionRes Vector function results object from which data is copied.
Definition at line 67 of file VectorFunctionResultsDto.cs.
References IG.Lib.SerializationDtoBase< Type, BaseType >.CopyFrom(), IG.Num.VectorFunctionResults.NumFunctions, IG.Num.VectorFunctionResults.NumParameters, IG.Num.VectorFunctionResults.Parameters, IG.Num.VectorFunctionResults.ReqGradients, IG.Num.VectorFunctionResults.ReqHessians, IG.Num.VectorFunctionResults.ReqValues, and IG.Lib.SerializationDtoBase< VectorFunctionResults, VectorFunctionResults >.SetNull().
CopyToPlain()
override void IG.Num.VectorFunctionRequestDTO.CopyToPlain (ref VectorFunctionResults vectorFunctionRes) inline protected
Copies data from the current DTO to a vector object.
Parameters
vectorFunctionRes Analysis results object that data is copied to.
Definition at line 93 of file VectorFunctionResultsDto.cs.
References IG.Lib.SerializationDtoBase< Type, BaseType >.CopyTo(), IG.Lib.SerializationDtoBase< VectorFunctionResults, VectorFunctionResults >.GetNull(), IG.Num.VectorFunctionRequestDTO.NumFunctons, IG.Num.VectorFunctionRequestDTO.NumParameters, IG.Num.VectorFunctionRequestDTO.Parameters, IG.Num.VectorFunctionRequestDTO.ReqGradients, IG.Num.VectorFunctionRequestDTO.ReqHessians, and IG.Num.VectorFunctionRequestDTO.ReqValues.
Member Data Documentation
NumParameters
int IG.Num.VectorFunctionRequestDTO.NumParameters
Number of parameters of an optimization problem.
Definition at line 38 of file VectorFunctionResultsDto.cs.
Referenced by IG.Num.VectorFunctionRequestDTO.CopyToPlain().
NumFunctons
int IG.Num.VectorFunctionRequestDTO.NumFunctons
Number of components (functions) of vector functon.
Definition at line 41 of file VectorFunctionResultsDto.cs.
Referenced by IG.Num.VectorFunctionRequestDTO.CopyToPlain().
ReqValues
bool IG.Num.VectorFunctionRequestDTO.ReqValues = false
Indicates whether calculation of functions is/was requested.
Definition at line 44 of file VectorFunctionResultsDto.cs.
Referenced by IG.Num.VectorFunctionRequestDTO.CopyToPlain().
ReqGradients
bool IG.Num.VectorFunctionRequestDTO.ReqGradients = false
Indicates whether calculation of function gradients is/was requested.
Definition at line 47 of file VectorFunctionResultsDto.cs.
Referenced by IG.Num.VectorFunctionRequestDTO.CopyToPlain().
ReqHessians
bool IG.Num.VectorFunctionRequestDTO.ReqHessians = false
Indicates whether calculation of functions' Hessians is/was requested.
Definition at line 50 of file VectorFunctionResultsDto.cs.
Referenced by IG.Num.VectorFunctionRequestDTO.CopyToPlain().
Parameters
VectorDtoBase IG.Num.VectorFunctionRequestDTO.Parameters
Definition at line 52 of file VectorFunctionResultsDto.cs.
Referenced by IG.Num.VectorFunctionRequestDTO.CopyToPlain().
The documentation for this class was generated from the following file:
iglib/igbase/data/serialization/dtos/VectorFunctionResultsDto.cs