Doc: IGLib with source files: IG.Num.MatrixExtensions Class Reference
IG.Num.MatrixExtensions Class Reference
Extension methods for IMatrix interface.
Static Public Member Functions
static string ToStringReadable (this IMatrix mat, int accuracy=4, int padding=8)
Easily readable string form of a matrix, accuracy and padding can be set.
static string ToStringMath (this IMatrix mat)
Returns string representation of the current matrix in the standard IGLib form. Rows and elements are printed in comma separated lists in curly brackets. Extension method for IMatrix interface.
static string ToString (this IMatrix mat, string elementFormat)
Returns string representation of the current matrix in the standard IGLib form, with the specified
format for elements of the matrix. Rows and elements are printed in comma separated lists in curly brackets. Extension method for IMatrix interface.
static string ToStringMath (this IMatrix mat, string elementFormat)
Returns string representation of the current matrix in the standard IGLib form, with the specified
format for elements of the matrix. Rows and elements are printed in comma separated lists in curly brackets. Extension method for IMatrix interface.
static string ToStringNewlines (IMatrix mat)
Returns a string representation of the current matrix with newlines inserted after each row. Rows and elements are printed in comma separated lists in curly brackets. Extension nethod for IMatrix interface.
static string ToStringNewlines (IMatrix mat, string elementFormat)
Returns a string representation of the current matrix with newlines inserted after each row, with the specified format for elements of the matrix. Rows and elements are printed in comma separated lists in curly brackets. Extension nethod for IMatrix interface.
static string ToStringMath1 (IMatrix mat)
Returns string representation of the current matrix in the standard IGLib form (Mathematica-like format but with C representation of numbers). Rows and elements are printed in comma separated lists in curly brackets. Extension nethod for IMatrix interface.
Detailed Description
Extension methods for IMatrix interface.
$A Igor Apr11;
Definition at line 237 of file MatrixBase.cs.
Member Function Documentation
ToStringReadable()
static string IG.Num.MatrixExtensions.ToStringReadable (this IMatrix mat, int accuracy = 4, int padding = 8) inline static
Easily readable string form of a matrix, accuracy and padding can be set.
Parameters
mat Matrix to be changed to a string.
accuracy Accuracy of matrix elments representations.
padding Paddind of matrix elements.
Returns
A readable string representation in tabular form.
Definition at line 247 of file MatrixBase.cs.
References IG.Num.MatrixBase.ToStringReadable().
ToStringMath() [1/2]
static string IG.Num.MatrixExtensions.ToStringMath (this IMatrix mat) inline static
Returns string representation of the current matrix in the standard IGLib form. Rows and elements are printed in comma separated lists in curly brackets. Extension method for IMatrix interface.
Parameters
mat Matrix whose string representation is returned.
Definition at line 257 of file MatrixBase.cs.
References IG.Num.MatrixBase.ToStringMath().
ToString()
static string IG.Num.MatrixExtensions.ToString (this IMatrix mat, string elementFormat) inline static
Returns string representation of the current matrix in the standard IGLib form, with the specified
format for elements of the matrix. Rows and elements are printed in comma separated lists in curly brackets. Extension method for IMatrix interface.
Parameters
mat Matrix whose string representation is returned.
elementFormat Elsment format.
Definition at line 268 of file MatrixBase.cs.
References IG.Num.MatrixBase.ToString().
ToStringMath() [2/2]
static string IG.Num.MatrixExtensions.ToStringMath (this IMatrix mat, string elementFormat) inline static
Returns string representation of the current matrix in the standard IGLib form, with the specified
format for elements of the matrix. Rows and elements are printed in comma separated lists in curly brackets. Extension method for IMatrix interface.
Parameters
mat Matrix whose string representation is returned.
elementFormat Element format.
Definition at line 279 of file MatrixBase.cs.
References IG.Num.MatrixBase.ToStringMath().
ToStringNewlines() [1/2]
static string IG.Num.MatrixExtensions.ToStringNewlines (IMatrix mat) inline static
Returns a string representation of the current matrix with newlines inserted after each row. Rows and elements are printed in comma separated lists in curly brackets. Extension nethod for IMatrix interface.
Parameters
mat Matrix whose string representation is returned.
Definition at line 289 of file MatrixBase.cs.
References IG.Num.MatrixBase.ToStringNewlines().
ToStringNewlines() [2/2]
static string IG.Num.MatrixExtensions.ToStringNewlines (IMatrix mat, string elementFormat) inline static
Returns a string representation of the current matrix with newlines inserted after each row, with the specified format for elements of the matrix. Rows and elements are printed in comma separated lists in curly brackets. Extension nethod for IMatrix interface.
Parameters
mat Matrix whose string representation is returned.
elementFormat Format specification for individual elemeents.
Definition at line 300 of file MatrixBase.cs.
References IG.Num.MatrixBase.ToStringNewlines().
ToStringMath1()
static string IG.Num.MatrixExtensions.ToStringMath1 (IMatrix mat) inline static
Returns string representation of the current matrix in the standard IGLib form (Mathematica-like format but with C representation of numbers). Rows and elements are printed in comma separated lists in curly brackets. Extension nethod for IMatrix interface.
Parameters
mat Matrix whose string representation is returned.
Definition at line 311 of file MatrixBase.cs.
References IG.Num.MatrixBase.ToStringMath().
The documentation for this class was generated from the following file:
iglib/igbase/numeric/MatrixBase.cs