Doc: IGLib with source files: IG.Crypto.CryptoParameters Class Reference
IG.Crypto.CryptoParameters Class Reference
This class contains key parameters of the cryptographic operations performed on some item.
Public Member Functions
CryptoParameters ()
void Reset ()
Resets the state.
bool IsFlagsSet (params CryptoFlags[] whichFlags)
Returns true if ALL the specified flags are set, or false if some of them are unset.
bool IsAnyFlagSet (params CryptoFlags[] whichFlags)
Returns true if any of the specified flags is set, or false if none of them is set.
void SetFlags (params CryptoFlags[] whichFlags)
Sets the specified flags.
void ClearFlags (CryptoFlags firstFlags, params CryptoFlags[] whichFlags)
Clears the specified flags.
void ClearAllFlags ()
Clears all flags.
Properties
CryptoFlags Flags [get, private set]
Flags for cryptographic operations performed.
Private Attributes
CryptoFlags _flags = CryptoFlags.None
Detailed Description
This class contains key parameters of the cryptographic operations performed on some item.
Class also handles some tasks that enable consisstent performance of operations, such as writing and reading cryptographic heads of encrypted files and data.
This is the base class for
$A Igor May15;
Definition at line 158 of file UtilCryptoAux.cs.
Constructor & Destructor Documentation
CryptoParameters()
IG.Crypto.CryptoParameters.CryptoParameters () inline
Definition at line 160 of file UtilCryptoAux.cs.
Member Function Documentation
Reset()
void IG.Crypto.CryptoParameters.Reset () inline
Resets the state.
Definition at line 164 of file UtilCryptoAux.cs.
References IG.Crypto.CryptoParameters.Flags.
IsFlagsSet()
bool IG.Crypto.CryptoParameters.IsFlagsSet (params CryptoFlags[] whichFlags) inline
Returns true if ALL the specified flags are set, or false if some of them are unset.
Parameters
whichFlags Specifies which flags are queried. A set of one or more values can be specified, of which each one can be an orred combination of flags to be queried.
Definition at line 180 of file UtilCryptoAux.cs.
References IG.Crypto.CryptoParameters.Flags.
Referenced by IG.Crypto.CryptoManager.ParseCommandlineParameters().
IsAnyFlagSet()
bool IG.Crypto.CryptoParameters.IsAnyFlagSet (params CryptoFlags[] whichFlags) inline
Returns true if any of the specified flags is set, or false if none of them is set.
Parameters
whichFlags Specifies which flags are queried. A set of one or more values can be specified, of which each one can be an orred combination of flags to be queried.
Definition at line 193 of file UtilCryptoAux.cs.
References IG.Crypto.CryptoParameters.Flags.
SetFlags()
void IG.Crypto.CryptoParameters.SetFlags (params CryptoFlags[] whichFlags) inline
Sets the specified flags.
Parameters
whichFlags Specifies which flags are set. A single flag can be specified such as CryptoFlags.Hashing, or an orred combination of flags to be set.
Definition at line 206 of file UtilCryptoAux.cs.
References IG.Crypto.CryptoParameters.Flags.
Referenced by IG.Crypto.CryptoManager.AppAddCertificate(), IG.Crypto.CryptoManager.AppAsymExportKey(), IG.Crypto.CryptoManager.AppAsymKeyInfo(), IG.Crypto.CryptoManager.AppCertInfo(), IG.Crypto.CryptoManager.AppCertStoreInfo(), IG.Crypto.CryptoManager.AppCheckSum(), IG.Crypto.CryptoManager.AppEncryptSymmetricAll(), IG.Crypto.CryptoManager.AppGetFileHash(), IG.Crypto.CryptoManager.AppKeyGenerationAll(), and IG.Crypto.CryptoManager.AppRemoveCertificate().
ClearFlags()
void IG.Crypto.CryptoParameters.ClearFlags (CryptoFlags firstFlags, params CryptoFlags[] whichFlags) inline
Clears the specified flags.
Parameters
firstFlags The same as whichFlags . This argument is actually the first of flags that are taken into account, ensuring that at least one value is specified in the call with variable number of arguments.
whichFlags Specifies which flags are cleared. A set of one or more values can be specified, of which each one can be an orred combination of flags to be set.
Definition at line 220 of file UtilCryptoAux.cs.
References IG.Crypto.CryptoParameters.Flags.
ClearAllFlags()
void IG.Crypto.CryptoParameters.ClearAllFlags () inline
Clears all flags.
Definition at line 230 of file UtilCryptoAux.cs.
References IG.Crypto.CryptoParameters.Flags.
Referenced by IG.Crypto.CryptoManager.AppAddCertificate(), IG.Crypto.CryptoManager.AppAsymExportKey(), IG.Crypto.CryptoManager.AppAsymKeyInfo(), IG.Crypto.CryptoManager.AppCertInfo(), IG.Crypto.CryptoManager.AppCertStoreInfo(), IG.Crypto.CryptoManager.AppCheckSum(), IG.Crypto.CryptoManager.AppCleanFiles(), IG.Crypto.CryptoManager.AppConvert(), IG.Crypto.CryptoManager.AppEncryptSymmetricAll(), IG.Crypto.CryptoManager.AppGetFileHash(), IG.Crypto.CryptoManager.AppKeyGenerationAll(), and IG.Crypto.CryptoManager.AppRemoveCertificate().
Member Data Documentation
_flags
CryptoFlags IG.Crypto.CryptoParameters._flags = CryptoFlags.None private
Definition at line 171 of file UtilCryptoAux.cs.
Property Documentation
Flags
CryptoFlags IG.Crypto.CryptoParameters.Flags get private set
Flags for cryptographic operations performed.
Warning: don't set the whole flags direcryl, only individual flags should be set!
CryptoFlags.
Definition at line 175 of file UtilCryptoAux.cs.
Referenced by IG.Crypto.CryptoParameters.ClearAllFlags(), IG.Crypto.CryptoParameters.ClearFlags(), IG.Crypto.CryptoParameters.IsAnyFlagSet(), IG.Crypto.CryptoParameters.IsFlagsSet(), IG.Crypto.CryptoParameters.Reset(), and IG.Crypto.CryptoParameters.SetFlags().
The documentation for this class was generated from the following file:
iglib/igbase/utilities/UtilCryptoAux.cs