Doc: IGLib with source files: IG.Net.PortScannerSimple Class Reference
IG.Net.PortScannerSimple Class Reference
Simple TCP port scanner, multi-threaded.
Classes
class PortList
Public Member Functions
PortScannerSimple (string host, int portStart, int portStop)
PortScannerSimple (string host)
PortScannerSimple ()
void start (int threadCtr)
void run ()
Static Public Member Functions
static void Run (string[] args)
static void printUsage ()
Private Attributes
string host
PortList portList
Detailed Description
Simple TCP port scanner, multi-threaded.
Basic idea taken from this project: https://github.com/munirusman/Simple-TCP-Port-Scanner/tree/master/PortScanner
by Munir Usman
$A Munir_Usman xx; Igor Apr18;
Definition at line 21 of file PortScannerSimple.cs.
Constructor & Destructor Documentation
PortScannerSimple() [1/3]
IG.Net.PortScannerSimple.PortScannerSimple (string host, int portStart, int portStop) inline
Definition at line 26 of file PortScannerSimple.cs.
References IG.Net.PortScannerSimple.host.
PortScannerSimple() [2/3]
IG.Net.PortScannerSimple.PortScannerSimple (string host) inline
Definition at line 32 of file PortScannerSimple.cs.
PortScannerSimple() [3/3]
IG.Net.PortScannerSimple.PortScannerSimple () inline
Definition at line 37 of file PortScannerSimple.cs.
Referenced by IG.Net.PortScannerSimple.Run().
Member Function Documentation
start()
void IG.Net.PortScannerSimple.start (int threadCtr) inline
Definition at line 42 of file PortScannerSimple.cs.
References IG.Net.PortScannerSimple.run().
Referenced by IG.Net.PortScannerSimple.Run().
run()
void IG.Net.PortScannerSimple.run () inline
Definition at line 52 of file PortScannerSimple.cs.
References IG.Net.PortScannerSimple.PortList.getNext(), IG.Net.PortScannerSimple.host, and IG.Net.PortScannerSimple.portList.
Referenced by IG.Net.PortScannerSimple.start().
Run()
static void IG.Net.PortScannerSimple.Run (string[] args) inline static
Definition at line 80 of file PortScannerSimple.cs.
References IG.Net.PortScannerSimple.host, IG.Net.PortScannerSimple.PortScannerSimple(), IG.Net.PortScannerSimple.printUsage(), and IG.Net.PortScannerSimple.start().
printUsage()
static void IG.Net.PortScannerSimple.printUsage () inline static
Definition at line 124 of file PortScannerSimple.cs.
Referenced by IG.Net.PortScannerSimple.Run().
Member Data Documentation
host
string IG.Net.PortScannerSimple.host private
Definition at line 23 of file PortScannerSimple.cs.
Referenced by IG.Net.PortScannerSimple.PortScannerSimple(), IG.Net.PortScannerSimple.run(), and IG.Net.PortScannerSimple.Run().
portList
PortList IG.Net.PortScannerSimple.portList private
Definition at line 24 of file PortScannerSimple.cs.
Referenced by IG.Net.PortScannerSimple.run().
The documentation for this class was generated from the following file:
iglib/igbase/utilities/networking/PortScannerSimple/PortScannerSimple.cs