Doc: IGLib with source files: IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests Class Reference
IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests Class Reference
These tests create and export meshes for tubular surfaces created from 3D parametric curves, including various knot parameterizations, knot groups (torus knots, Lissajous knots, cylindrical billiard knots), selected individual konts, etc. Regions are arranged by the type of the exported curve or knot.
Public Member Functions
TubularSurfaceExportExamplesTests (ITestOutputHelper output)
Calling base constructor initializes things like Output property to write on tests' output.
Public Member Functions inherited from IGLib.Tests.Base.TestBase< TubularSurfaceExportExamplesTests >
TestBase (ITestOutputHelper output, bool assignConsole=true)
Protected Member Functions
void Example00_CreateAndExportTubularSurfaceTest (int numLongitudinal, int numTransverse, double radius)
Creates the first test of tubular surface generation and export, using a custom parameterization of a helix curve as example.
void Example01_ExportTrefoilKnot3DTube (int numLongitudinal, int numTransverse, double radius)
Creeates a tubular surface mesh from a trefoil knot parameterization, TrefoilKnot3D, in different ways, and exports it for viewing in Blender or similar.
void Example02_ExportHelixCurve3DTube (int numLongitudinal, int numTransverse, double radius, double a=1.0, double b=0.2, bool righthanded=true)
Creeates a tubular surface mesh from a helix parameterization, HelixCurve3D, in different ways, and exports it for viewing in Blender or similar.
void Example03_ExportGrannyKnot3DTube (int numLongitudinal, int numTransverse, double radius)
Creeates a tubular surface mesh from a Granny knot parameterization, GrannyKnot3D, in different ways, and exports it for viewing in Blender or similar.
void Example04_ExportLissajousKnot3DTube (int numLongitudinal, int numTransverse, double radius, int n1=3, int n2=4, int n3=7, double fi1=0, double fi2=0)
Creeates a tubular surface mesh from a Lissajous knot parameterization, LissajousKnot3D, in different ways, and exports it for viewing in Blender or similar.
void Example11_1_ExportConicalSpiralArchimedian3DTube (int numLongitudinal, int numTransverse, double radius, double alpha=1.5, double a=1.0)
Creeates a tubular surface mesh from a helix parameterization, HelixCurve3D.
void Example11_2_ExportConicalSpiralLogarithmic3DTube (int numLongitudinal, int numTransverse, double radius, double alpha=1.5, double a=1.0, double k=0.01)
Creeates a tubular surface mesh from a helix parameterization, HelixCurve3D.
void Example11_3_ExportConicalSpiralFermats3DTube (int numLongitudinal, int numTransverse, double radius, double alpha=1.5, double a=1.0)
Creeates a tubular surface mesh from a helix parameterization, HelixCurve3D.
void Example11_4_ExportConicalSpiralHyperbolic3DTube (int numLongitudinal, int numTransverse, double radius, double alpha=1.5, double a=1.0)
Creeates a tubular surface mesh from a helix parameterization, HelixCurve3D.
void Example50_ExportTorusKnot (int numLongitudinal, int numTransverse, double radius, int p, int q)
Creates the first test of tubular surface generation and export.
void Example51_ExportLissajousKnot (int numLongitudinal, int numTransverse, double radius, int n1=3, int n2=4, int n3=7, double fi1=0, double fi2=0)
Creates the first test of tubular surface generation and export.
void Example52_0_ExportCylindricalBilliardKnot (int numLongitudinal, int numTransverse, double radius, int N, int P, double A=1.0)
Generates and exports (as .obj) tubular surface created form smooth parameterizaion of cylindric billiard knot.
void Example52_1_ExportCylindricalBilliardKnot_WrongParameterization (int numLongitudinal, int numTransverse, double radius, int N, int P, double A=1.0)
Generates and exports (as .obj) tubular surface created form smooth parameterizaion of cylindric billiard knot (wrong, but the wrong parameterization should be kept because it produces interesting curves). The other parameterization and its corresponding test will be kept.
Properties
MaterialProperties MaterialSurfaceLightSkyBlue [get]
Surface material: LightSkyBlue (#87CEFA)
MaterialProperties MaterialWireframeDarkRed [get]
Wireframe material: DarkRed (#8B0000)
Properties inherited from IGLib.Tests.Base.TestBase< TubularSurfaceExportExamplesTests >
string ExportPathIGLib [get, set]
Export path for tests that generate output files. This is set to IGLibDefaultExportPath by default (good for most cases), but this can be overridden in test class's constructor.
ITestOutputHelper Output [get, set]
Enables writing to tests' output. Provided by the framework (injected via constructor).
static ITestOutputHelper Console [get, set]
This property makes possible to use the name Console instead of Output in test method of this class, such that code can be directly copied to console applications while output is still visible in tests' output. Unfortunately, you cannot use Console.Write(...) because the ITestOutputHelper does not have it.
LoggerFactory LoggerFactory [get, set]
Additional Inherited Members
Protected Attributes inherited from IGLib.Tests.Base.TestBase< TubularSurfaceExportExamplesTests >
string ExportPathIGLibTemporary
Static Protected Attributes inherited from IGLib.Tests.Base.TestBase< TubularSurfaceExportExamplesTests >
const string DefaultExportPathIGLib
Default export path for tests that generate output. Specified relative to the currennt directory of test execution, which is usually a subdirectory of the [ProjectDir]/bin/ .
Detailed Description
These tests create and export meshes for tubular surfaces created from 3D parametric curves, including various knot parameterizations, knot groups (torus knots, Lissajous knots, cylindrical billiard knots), selected individual konts, etc. Regions are arranged by the type of the exported curve or knot.
Definition at line 23 of file TubularSurfaceExportExamplesTests.cs.
Constructor & Destructor Documentation
TubularSurfaceExportExamplesTests()
IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests.TubularSurfaceExportExamplesTests (ITestOutputHelper output) inline
Calling base constructor initializes things like Output property to write on tests' output.
Parameters
output This parameter will be provided to constructor (injected via constructor) by the test framework. I is also stored to Console property, such that test code can use RoslynScriptingApiExamplesTests.Console.WriteLine(string) method to generate test output.
Definition at line 32 of file TubularSurfaceExportExamplesTests.cs.
Member Function Documentation
Example00_CreateAndExportTubularSurfaceTest()
void IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests.Example00_CreateAndExportTubularSurfaceTest (int numLongitudinal, int numTransverse, double radius) inline protected
Creates the first test of tubular surface generation and export, using a custom parameterization of a helix curve as example.
Definition at line 74 of file TubularSurfaceExportExamplesTests.cs.
References IGLib.Tests.Base.TestBase< TubularSurfaceExportExamplesTests >.Console, IGLib.Gr3D.MeshExportExtensions.ExportMaterial(), IGLib.Tests.Base.TestBase< TubularSurfaceExportExamplesTests >.ExportPathIGLib, IGLib.Gr3D.TubularMeshGenerator.GenerateMesh(), IGLib.Gr3D.TubularMeshGenerator.Global, IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests.MaterialSurfaceLightSkyBlue, and IGLib.Tests.Base.TestBase< TubularSurfaceExportExamplesTests >.Output.
Example01_ExportTrefoilKnot3DTube()
void IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests.Example01_ExportTrefoilKnot3DTube (int numLongitudinal, int numTransverse, double radius) inline protected
Creeates a tubular surface mesh from a trefoil knot parameterization, TrefoilKnot3D, in different ways, and exports it for viewing in Blender or similar.
With trefoil knot, mesh abnormalitis when using the Frenet frame are not shown because the curve's second derivative does not change direction (it s actually constant).
Definition at line 128 of file TubularSurfaceExportExamplesTests.cs.
References IGLib.Tests.Base.TestBase< TubularSurfaceExportExamplesTests >.Console, IGLib.Gr3D.MeshExportExtensions.ExportMaterial(), IGLib.Tests.Base.TestBase< TubularSurfaceExportExamplesTests >.ExportPathIGLib, IGLib.Gr3D.TubularMeshGenerator.GenerateMesh(), IGLib.Gr3D.TubularMeshGenerator.GenerateMeshByFrenet(), IGLib.Gr3D.TubularMeshGenerator.Global, IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests.MaterialSurfaceLightSkyBlue, and IGLib.Tests.Base.TestBase< TubularSurfaceExportExamplesTests >.Output.
Example02_ExportHelixCurve3DTube()
void IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests.Example02_ExportHelixCurve3DTube (int numLongitudinal, int numTransverse, double radius, double a = 1.0, double b = 0.2, bool righthanded = true) inline protected
Creeates a tubular surface mesh from a helix parameterization, HelixCurve3D, in different ways, and exports it for viewing in Blender or similar.
With helix curve, mesh abnormalitis when using the Frenet frame are not shown because the curve's second derivative does not change direction (it s actually constant).
Definition at line 285 of file TubularSurfaceExportExamplesTests.cs.
References IGLib.Tests.Base.TestBase< TubularSurfaceExportExamplesTests >.Console, IGLib.Gr3D.MeshExportExtensions.ExportMaterial(), IGLib.Tests.Base.TestBase< TubularSurfaceExportExamplesTests >.ExportPathIGLib, IGLib.Gr3D.TubularMeshGenerator.GenerateMesh(), IGLib.Gr3D.TubularMeshGenerator.GenerateMeshByFrenet(), IGLib.Gr3D.TubularMeshGenerator.Global, IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests.MaterialSurfaceLightSkyBlue, and IGLib.Tests.Base.TestBase< TubularSurfaceExportExamplesTests >.Output.
Example03_ExportGrannyKnot3DTube()
void IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests.Example03_ExportGrannyKnot3DTube (int numLongitudinal, int numTransverse, double radius) inline protected
Creeates a tubular surface mesh from a Granny knot parameterization, GrannyKnot3D, in different ways, and exports it for viewing in Blender or similar.
With Granny knot, mesh abnormalitis when using the Frenet frame are not shown because the curve's second derivative does not change direction (it s actually constant).
Definition at line 437 of file TubularSurfaceExportExamplesTests.cs.
References IGLib.Tests.Base.TestBase< TubularSurfaceExportExamplesTests >.Console, IGLib.Gr3D.MeshExportExtensions.ExportMaterial(), IGLib.Tests.Base.TestBase< TubularSurfaceExportExamplesTests >.ExportPathIGLib, IGLib.Gr3D.TubularMeshGenerator.GenerateMesh(), IGLib.Gr3D.TubularMeshGenerator.GenerateMeshByFrenet(), IGLib.Gr3D.TubularMeshGenerator.Global, IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests.MaterialSurfaceLightSkyBlue, and IGLib.Tests.Base.TestBase< TubularSurfaceExportExamplesTests >.Output.
Example04_ExportLissajousKnot3DTube()
void IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests.Example04_ExportLissajousKnot3DTube (int numLongitudinal, int numTransverse, double radius, int n1 = 3, int n2 = 4, int n3 = 7, double fi1 = 0, double fi2 = 0) inline protected
Creeates a tubular surface mesh from a Lissajous knot parameterization, LissajousKnot3D, in different ways, and exports it for viewing in Blender or similar.
With Lissajous exported knot, mesh abnormalitis when using the Frenet frame are shown.
Definition at line 587 of file TubularSurfaceExportExamplesTests.cs.
References IGLib.Tests.Base.TestBase< TubularSurfaceExportExamplesTests >.Console, IGLib.Gr3D.MeshExportExtensions.ExportMaterial(), IGLib.Tests.Base.TestBase< TubularSurfaceExportExamplesTests >.ExportPathIGLib, IGLib.Gr3D.TubularMeshGenerator.GenerateMesh(), IGLib.Gr3D.TubularMeshGenerator.GenerateMeshByFrenet(), IGLib.Gr3D.TubularMeshGenerator.Global, IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests.MaterialSurfaceLightSkyBlue, and IGLib.Tests.Base.TestBase< TubularSurfaceExportExamplesTests >.Output.
Example11_1_ExportConicalSpiralArchimedian3DTube()
void IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests.Example11_1_ExportConicalSpiralArchimedian3DTube (int numLongitudinal, int numTransverse, double radius, double alpha = 1.5, double a = 1.0) inline protected
Creeates a tubular surface mesh from a helix parameterization, HelixCurve3D.
Definition at line 754 of file TubularSurfaceExportExamplesTests.cs.
References IGLib.Tests.Base.TestBase< TubularSurfaceExportExamplesTests >.Console, IGLib.Gr3D.MeshExportExtensions.ExportMaterial(), IGLib.Tests.Base.TestBase< TubularSurfaceExportExamplesTests >.ExportPathIGLib, IGLib.Gr3D.TubularMeshGenerator.GenerateMesh(), IGLib.Gr3D.TubularMeshGenerator.Global, IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests.MaterialSurfaceLightSkyBlue, and IGLib.Tests.Base.TestBase< TubularSurfaceExportExamplesTests >.Output.
Example11_2_ExportConicalSpiralLogarithmic3DTube()
void IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests.Example11_2_ExportConicalSpiralLogarithmic3DTube (int numLongitudinal, int numTransverse, double radius, double alpha = 1.5, double a = 1.0, double k = 0.01) inline protected
Creeates a tubular surface mesh from a helix parameterization, HelixCurve3D.
Definition at line 809 of file TubularSurfaceExportExamplesTests.cs.
References IGLib.Tests.Base.TestBase< TubularSurfaceExportExamplesTests >.Console, IGLib.Gr3D.MeshExportExtensions.ExportMaterial(), IGLib.Tests.Base.TestBase< TubularSurfaceExportExamplesTests >.ExportPathIGLib, IGLib.Gr3D.TubularMeshGenerator.GenerateMesh(), IGLib.Gr3D.TubularMeshGenerator.Global, IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests.MaterialSurfaceLightSkyBlue, and IGLib.Tests.Base.TestBase< TubularSurfaceExportExamplesTests >.Output.
Example11_3_ExportConicalSpiralFermats3DTube()
void IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests.Example11_3_ExportConicalSpiralFermats3DTube (int numLongitudinal, int numTransverse, double radius, double alpha = 1.5, double a = 1.0) inline protected
Creeates a tubular surface mesh from a helix parameterization, HelixCurve3D.
Definition at line 864 of file TubularSurfaceExportExamplesTests.cs.
References IGLib.Tests.Base.TestBase< TubularSurfaceExportExamplesTests >.Console, IGLib.Gr3D.MeshExportExtensions.ExportMaterial(), IGLib.Tests.Base.TestBase< TubularSurfaceExportExamplesTests >.ExportPathIGLib, IGLib.Gr3D.TubularMeshGenerator.GenerateMesh(), IGLib.Gr3D.TubularMeshGenerator.Global, IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests.MaterialSurfaceLightSkyBlue, and IGLib.Tests.Base.TestBase< TubularSurfaceExportExamplesTests >.Output.
Example11_4_ExportConicalSpiralHyperbolic3DTube()
void IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests.Example11_4_ExportConicalSpiralHyperbolic3DTube (int numLongitudinal, int numTransverse, double radius, double alpha = 1.5, double a = 1.0) inline protected
Creeates a tubular surface mesh from a helix parameterization, HelixCurve3D.
Definition at line 919 of file TubularSurfaceExportExamplesTests.cs.
References IGLib.Tests.Base.TestBase< TubularSurfaceExportExamplesTests >.Console, IGLib.Gr3D.MeshExportExtensions.ExportMaterial(), IGLib.Tests.Base.TestBase< TubularSurfaceExportExamplesTests >.ExportPathIGLib, IGLib.Gr3D.TubularMeshGenerator.GenerateMesh(), IGLib.Gr3D.TubularMeshGenerator.Global, IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests.MaterialSurfaceLightSkyBlue, and IGLib.Tests.Base.TestBase< TubularSurfaceExportExamplesTests >.Output.
Example50_ExportTorusKnot()
void IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests.Example50_ExportTorusKnot (int numLongitudinal, int numTransverse, double radius, int p, int q) inline protected
Creates the first test of tubular surface generation and export.
Definition at line 1001 of file TubularSurfaceExportExamplesTests.cs.
References IGLib.Tests.Base.TestBase< TubularSurfaceExportExamplesTests >.Console, IGLib.Gr3D.MeshExportExtensions.ExportMaterial(), IGLib.Tests.Base.TestBase< TubularSurfaceExportExamplesTests >.ExportPathIGLib, IGLib.Gr3D.TubularMeshGenerator.GenerateMesh(), IGLib.Gr3D.TubularMeshGenerator.Global, IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests.MaterialSurfaceLightSkyBlue, and IGLib.Tests.Base.TestBase< TubularSurfaceExportExamplesTests >.Output.
Example51_ExportLissajousKnot()
void IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests.Example51_ExportLissajousKnot (int numLongitudinal, int numTransverse, double radius, int n1 = 3, int n2 = 4, int n3 = 7, double fi1 = 0, double fi2 = 0) inline protected
Creates the first test of tubular surface generation and export.
Definition at line 1062 of file TubularSurfaceExportExamplesTests.cs.
References IGLib.Tests.Base.TestBase< TubularSurfaceExportExamplesTests >.Console, IGLib.Gr3D.MeshExportExtensions.ExportMaterial(), IGLib.Tests.Base.TestBase< TubularSurfaceExportExamplesTests >.ExportPathIGLib, IGLib.Gr3D.TubularMeshGenerator.GenerateMesh(), IGLib.Gr3D.TubularMeshGenerator.Global, IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests.MaterialSurfaceLightSkyBlue, and IGLib.Tests.Base.TestBase< TubularSurfaceExportExamplesTests >.Output.
Example52_0_ExportCylindricalBilliardKnot()
void IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests.Example52_0_ExportCylindricalBilliardKnot (int numLongitudinal, int numTransverse, double radius, int N, int P, double A = 1.0) inline protected
Generates and exports (as .obj) tubular surface created form smooth parameterizaion of cylindric billiard knot.
IMPORTANT: The parameterization used here is still wrong and it needs to be corrected. The other method with the _WrongParameterization suffix should ALSO BE KEPT because it produces interesting curves)
Definition at line 1126 of file TubularSurfaceExportExamplesTests.cs.
References IG.Num.A, IGLib.Tests.Base.TestBase< TubularSurfaceExportExamplesTests >.Console, IGLib.Gr3D.MeshExportExtensions.ExportMaterial(), IGLib.Tests.Base.TestBase< TubularSurfaceExportExamplesTests >.ExportPathIGLib, IGLib.Gr3D.TubularMeshGenerator.GenerateMesh(), IGLib.Gr3D.TubularMeshGenerator.Global, IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests.MaterialSurfaceLightSkyBlue, and IGLib.Tests.Base.TestBase< TubularSurfaceExportExamplesTests >.Output.
Example52_1_ExportCylindricalBilliardKnot_WrongParameterization()
void IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests.Example52_1_ExportCylindricalBilliardKnot_WrongParameterization (int numLongitudinal, int numTransverse, double radius, int N, int P, double A = 1.0) inline protected
Generates and exports (as .obj) tubular surface created form smooth parameterizaion of cylindric billiard knot (wrong, but the wrong parameterization should be kept because it produces interesting curves). The other parameterization and its corresponding test will be kept.
Definition at line 1186 of file TubularSurfaceExportExamplesTests.cs.
References IG.Num.A, IGLib.Tests.Base.TestBase< TubularSurfaceExportExamplesTests >.Console, IGLib.Gr3D.MeshExportExtensions.ExportMaterial(), IGLib.Tests.Base.TestBase< TubularSurfaceExportExamplesTests >.ExportPathIGLib, IGLib.Gr3D.TubularMeshGenerator.GenerateMesh(), IGLib.Gr3D.TubularMeshGenerator.Global, IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests.MaterialSurfaceLightSkyBlue, and IGLib.Tests.Base.TestBase< TubularSurfaceExportExamplesTests >.Output.
Property Documentation
MaterialSurfaceLightSkyBlue
MaterialProperties IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests.MaterialSurfaceLightSkyBlue get protected
Initial value:
= new MaterialProperties
        {
            Name = "SurfaceLightSkyBlue",
            DiffuseColor = new vec3(135 / 255.0, 206 / 255.0, 250 / 255.0),
            AmbientColor = new vec3(0.2, 0.2, 0.3),
            SpecularColor = new vec3(1, 1, 1),
            Shininess = 80,
            Transparency = 1
        }
Surface material: LightSkyBlue (#87CEFA)
Definition at line 39 of file TubularSurfaceExportExamplesTests.cs.
Referenced by IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests.Example00_CreateAndExportTubularSurfaceTest(), IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests.Example01_ExportTrefoilKnot3DTube(), IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests.Example02_ExportHelixCurve3DTube(), IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests.Example03_ExportGrannyKnot3DTube(), IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests.Example04_ExportLissajousKnot3DTube(), IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests.Example11_1_ExportConicalSpiralArchimedian3DTube(), IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests.Example11_2_ExportConicalSpiralLogarithmic3DTube(), IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests.Example11_3_ExportConicalSpiralFermats3DTube(), IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests.Example11_4_ExportConicalSpiralHyperbolic3DTube(), IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests.Example50_ExportTorusKnot(), IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests.Example51_ExportLissajousKnot(), IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests.Example52_0_ExportCylindricalBilliardKnot(), and IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests.Example52_1_ExportCylindricalBilliardKnot_WrongParameterization().
MaterialWireframeDarkRed
MaterialProperties IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests.MaterialWireframeDarkRed get protected
Initial value:
= new MaterialProperties
        {
            Name = "WireframeDarkRed",
            DiffuseColor = new vec3(139 / 255.0, 0, 0),
            AmbientColor = new vec3(0.1, 0.0, 0.0),
            SpecularColor = new vec3(0.5, 0.5, 0.5),
            Shininess = 10,
            Transparency = 1
        }
Wireframe material: DarkRed (#8B0000)
Definition at line 50 of file TubularSurfaceExportExamplesTests.cs.
The documentation for this class was generated from the following file:
IGLibGraphics3D/tests/IGLib.Graphics3D.Tests/TubularSurfaces/TubularSurfaceExportExamplesTests.cs