Doc: IGLib with source files: IG.Lib.XmlUtilityBase Class Reference
IG.Lib.XmlUtilityBase Class Reference
Base class for various utilities operating on XmlDocumnt.
Public Member Functions
virtual void Load (string filename)
virtual void LoadXml (string docstr)
Static Public Member Functions
static string GetDefaultNameSpaceUri (XmlElement element)
Gets the default namespace URI if defined, for the specified Xml element.
static string GetDefaultNameSpaceUri (XmlDocument doc)
Gets the default namespace URI of teh Xml document.
static string GetDefaultNameSpaceUri (XmlNode node)
Returns the default namespace URI that applies to the specified Xml node.
static string GetNameSpaceUri (XmlDocument doc, string prefix)
Returns the namespace URI associated with a specific prefix that applies to the specified Xml document.
static string GetNameSpaceUri (XmlNode node, string prefix)
Returns the namespace URI associated with a specific prefix that applies to the specified Xml document.
Public Attributes
string DefaultNameSpace = null
string DefaultNameSpacePrefix = "defaultnsprefix"
Protected Member Functions
bool ContainedInDocument (XmlNode node, XmlDocument doc)
Returns true if an Xml node is contained in the specified Xml document (false if any is null).
bool ContainedInNode (XmlNode node, XmlNode container)
Returns null if an XML node (first argument) is contained in the specified note (second argument). The node can be contained in another node at an arbitrary depth for the function to return true. If any of the _gridCoordinates is null then the function returns false.
Properties
virtual IG.Lib.IReporter R [get]
Reporter for this class.
virtual bool HasDefaultNameSpace [get, protected set]
string FileName [get, protected set]
virtual XmlDocument Doc [get, set]
Xml document that represents the message.
XmlNode Root [get, private set]
Root node of the current document.
Static Private Member Functions
static string GetNamespaceAttributeName (string prefix)
static string GetNameSpaceUri0 (XmlElement element, string NamespaceAttributeName)
Gets the namespace URI introduced by a particular attribute, if defined, for the specified Xml element.
static string GetNameSpaceUri (XmlElement element, string prefix)
Returns the namespace URI associated with a specific prefix that applies to the specified Xml element. URI information is obtained from the corresponding attribute of the specified node and eventually its parent _gridCoordinates.
Private Attributes
bool _hasDefaultNameSpace = false
string _filename = null
XmlDocument _doc = null
XmlNode _root = null
Static Private Attributes
const string XmlNsAttribute = "xmlns"
Detailed Description
Base class for various utilities operating on XmlDocumnt.
Definition at line 853 of file XmlUtilities.cs.
Member Function Documentation
GetDefaultNameSpaceUri() [1/3]
static string IG.Lib.XmlUtilityBase.GetDefaultNameSpaceUri (XmlElement element) inline static
Gets the default namespace URI if defined, for the specified Xml element.
Parameters
element
Definition at line 882 of file XmlUtilities.cs.
References IG.Lib.XmlUtilityBase.XmlNsAttribute.
Referenced by IG.Lib.XmlUtilityBase.GetDefaultNameSpaceUri(), and IG.Lib.XmlUtilityBase.GetNameSpaceUri().
GetDefaultNameSpaceUri() [2/3]
static string IG.Lib.XmlUtilityBase.GetDefaultNameSpaceUri (XmlDocument doc) inline static
Gets the default namespace URI of teh Xml document.
Parameters
doc Xml document to which the default namespace might apply.
Returns
Tha default namespace URI that applies to the document, or null if there is no such namespace.
Definition at line 912 of file XmlUtilities.cs.
References IG.Lib.XmlUtilityBase.GetDefaultNameSpaceUri().
GetDefaultNameSpaceUri() [3/3]
static string IG.Lib.XmlUtilityBase.GetDefaultNameSpaceUri (XmlNode node) inline static
Returns the default namespace URI that applies to the specified Xml node.
Parameters
node Xml node to which namespace URI applies.
Returns
The defaulut namespace URI atht applies to the node, or null if there is no default namespace.
Definition at line 927 of file XmlUtilities.cs.
References IG.Lib.XmlUtilityBase.GetDefaultNameSpaceUri().
GetNamespaceAttributeName()
static string IG.Lib.XmlUtilityBase.GetNamespaceAttributeName (string prefix) inline static private
Definition at line 942 of file XmlUtilities.cs.
References IG.Lib.XmlUtilityBase.XmlNsAttribute.
Referenced by IG.Lib.XmlUtilityBase.GetNameSpaceUri().
GetNameSpaceUri0()
static string IG.Lib.XmlUtilityBase.GetNameSpaceUri0 (XmlElement element, string NamespaceAttributeName) inline static private
Gets the namespace URI introduced by a particular attribute, if defined, for the specified Xml element.
Parameters
element Element for which rhe specific namespace URI is searched for.
NamespaceAttributeName Attribute name that introduces that namespace.
Definition at line 951 of file XmlUtilities.cs.
Referenced by IG.Lib.XmlUtilityBase.GetNameSpaceUri().
GetNameSpaceUri() [1/3]
static string IG.Lib.XmlUtilityBase.GetNameSpaceUri (XmlElement element, string prefix) inline static private
Returns the namespace URI associated with a specific prefix that applies to the specified Xml element. URI information is obtained from the corresponding attribute of the specified node and eventually its parent _gridCoordinates.
Parameters
element Element for which namespace URI is searched for.
prefix Prefix for which teh namespace is searched for. If null or empty string then a default namespace URI is searched for.
Returns
The namespace URI corresponding to the specified prefix at the level of a specified element, or null if the particular namespace URI is not defined.
Definition at line 986 of file XmlUtilities.cs.
References IG.Lib.XmlUtilityBase.GetDefaultNameSpaceUri(), IG.Lib.XmlUtilityBase.GetNamespaceAttributeName(), and IG.Lib.XmlUtilityBase.GetNameSpaceUri0().
Referenced by IG.Lib.XmlUtilityBase.GetNameSpaceUri().
GetNameSpaceUri() [2/3]
static string IG.Lib.XmlUtilityBase.GetNameSpaceUri (XmlDocument doc, string prefix) inline static
Returns the namespace URI associated with a specific prefix that applies to the specified Xml document.
Parameters
doc Xml document to which namespace URI applies.
prefix Prefix.
Returns
The namespace URI if found, null otherwise.
Definition at line 1002 of file XmlUtilities.cs.
References IG.Lib.XmlUtilityBase.GetNameSpaceUri().
GetNameSpaceUri() [3/3]
static string IG.Lib.XmlUtilityBase.GetNameSpaceUri (XmlNode node, string prefix) inline static
Returns the namespace URI associated with a specific prefix that applies to the specified Xml document.
Parameters
node Xml node to which namespace URI applies.
prefix Prefix.
Returns
The namespace URI if found, null otherwise.
Definition at line 1018 of file XmlUtilities.cs.
References IG.Lib.XmlUtilityBase.GetNameSpaceUri().
Load()
virtual void IG.Lib.XmlUtilityBase.Load (string filename) inline virtual
Definition at line 1068 of file XmlUtilities.cs.
References IG.Lib.IReporterBase.Depth, IG.Lib.XmlUtilityBase.Doc, IG.Lib.XmlUtilityBase.FileName, IG.Lib.XmlUtilityBase.R, IG.Lib.IReporterBase.ReportInfo(), and IG.Lib.IReporterBase.TreatInfo.
LoadXml()
virtual void IG.Lib.XmlUtilityBase.LoadXml (string docstr) inline virtual
Definition at line 1091 of file XmlUtilities.cs.
References IG.Lib.IReporterBase.Depth, IG.Lib.XmlUtilityBase.Doc, IG.Lib.XmlUtilityBase.FileName, IG.Lib.XmlUtilityBase.R, IG.Lib.IReporterBase.ReportInfo(), and IG.Lib.IReporterBase.TreatInfo.
ContainedInDocument()
bool IG.Lib.XmlUtilityBase.ContainedInDocument (XmlNode node, XmlDocument doc) inline protected
Returns true if an Xml node is contained in the specified Xml document (false if any is null).
Definition at line 1172 of file XmlUtilities.cs.
Referenced by IG.Lib.XmlParser.MoveTo().
ContainedInNode()
bool IG.Lib.XmlUtilityBase.ContainedInNode (XmlNode node, XmlNode container) inline protected
Returns null if an XML node (first argument) is contained in the specified note (second argument). The node can be contained in another node at an arbitrary depth for the function to return true. If any of the _gridCoordinates is null then the function returns false.
Parameters
node Node that might be contained in another node.
container The node that might contain another node.
Returns
true if container contains node, false othwrwise.
Definition at line 1195 of file XmlUtilities.cs.
Referenced by IG.Lib.XmlBuilder.RemoveNode().
Member Data Documentation
_hasDefaultNameSpace
bool IG.Lib.XmlUtilityBase._hasDefaultNameSpace = false private
Definition at line 863 of file XmlUtilities.cs.
DefaultNameSpace
string IG.Lib.XmlUtilityBase.DefaultNameSpace = null
Definition at line 872 of file XmlUtilities.cs.
DefaultNameSpacePrefix
string IG.Lib.XmlUtilityBase.DefaultNameSpacePrefix = "defaultnsprefix"
Definition at line 874 of file XmlUtilities.cs.
XmlNsAttribute
const string IG.Lib.XmlUtilityBase.XmlNsAttribute = "xmlns" static private
Definition at line 878 of file XmlUtilities.cs.
Referenced by IG.Lib.XmlUtilityBase.GetDefaultNameSpaceUri(), and IG.Lib.XmlUtilityBase.GetNamespaceAttributeName().
_filename
string IG.Lib.XmlUtilityBase._filename = null private
Definition at line 1114 of file XmlUtilities.cs.
_doc
XmlDocument IG.Lib.XmlUtilityBase._doc = null private
Definition at line 1128 of file XmlUtilities.cs.
_root
XmlNode IG.Lib.XmlUtilityBase._root = null private
Definition at line 1148 of file XmlUtilities.cs.
Property Documentation
R
virtual IG.Lib.IReporter IG.Lib.XmlUtilityBase.R get
Reporter for this class.
Definition at line 857 of file XmlUtilities.cs.
Referenced by IG.Lib.XmlBuilder.AppendChild(), IG.Lib.XmlBuilder.CreateNode(), IG.Lib.XmlBuilder.InsertAfter(), IG.Lib.XmlBuilder.InsertBefore(), IG.Lib.XmlUtilityBase.Load(), IG.Lib.XmlUtilityBase.LoadXml(), IG.Lib.XmlParser.MoveTo(), IG.Lib.XmlBuilder.PrependChild(), IG.Lib.XmlBuilder.RemoveNode(), IG.Lib.XmlBuilder.SetAttribute(), IG.Lib.XmlBuilder.SetInnerText(), IG.Lib.XmlParser.SetMark(), and IG.Lib.XmlBuilder.SetValue().
HasDefaultNameSpace
virtual bool IG.Lib.XmlUtilityBase.HasDefaultNameSpace get protected set
Definition at line 867 of file XmlUtilities.cs.
FileName
string IG.Lib.XmlUtilityBase.FileName get protected set
Definition at line 1117 of file XmlUtilities.cs.
Referenced by IG.Lib.XmlUtilityBase.Load(), and IG.Lib.XmlUtilityBase.LoadXml().
Doc
virtual XmlDocument IG.Lib.XmlUtilityBase.Doc get set
Xml document that represents the message.
Definition at line 1132 of file XmlUtilities.cs.
Referenced by IG.Lib.XmlUtilityBase.Load(), and IG.Lib.XmlUtilityBase.LoadXml().
Root
XmlNode IG.Lib.XmlUtilityBase.Root get private set
Root node of the current document.
Definition at line 1151 of file XmlUtilities.cs.
Referenced by IG.Lib.XmlParser.GetNode(), and IG.Lib.XmlParser.GoToRoot().
The documentation for this class was generated from the following file:
iglib/igbase/0unsorted/XmlUtilities.cs