Doc: IGLib with source files: IG.Num.IFunc3d Interface Reference
IG.Num.IFunc3d Interface Reference
Represents scalar functions of 2 variables.
Public Member Functions
double Value (double x, double y, double z)
Calculates and returns value of the current 3D scalar function.
double Value (vec3 parameters)
Calculates and returns value of the current 3D scalar function.
void Gradient (double x, double y, double z, out double gradx, out double grady, out double gradz)
Calculates gradient of the current 3D scalar function and returns its components through the specified output variables.
vec3 Gradient (vec3 parameters)
Calculates and returns gradient of the current 3D scalar function.
void Hessian (double x, double y, double z, out double dxx, out double dyy, out double dzz, out double dxy, out double dxz, out double dyz)
Calculates Hessian of the current 3D scalar function and returns its component through the specified output variables.
mat3 Hessian (vec3 parameters)
Calculates and returns Hessian of the current 3D scalar function and returns it (in the form of a mat3 struct).
Properties
bool ValueDefined [get]
Whether calculation of function value is defined.
bool GradientDefined [get]
Whether calculation of function ngradient is defined.
bool HessianDefined [get]
Whether calculation of function Hessian is defined.
Detailed Description
Represents scalar functions of 2 variables.
$A Igor Apr09;
Definition at line 17 of file Function3d.cs.
Member Function Documentation
Value() [1/2]
double IG.Num.IFunc3d.Value (double x, double y, double z)
Calculates and returns value of the current 3D scalar function.
Parameters
x First parameter.
y Second parameter.
z Third parameter.
Implemented in IG.Num.Func3dExamples.Func3dXYZ, IG.Num.Func3dVectorFormBase, and IG.Num.Func3dBase.
Referenced by IG.Num.Field< TCoord >.MapCoordinatesPlain(), IG.Num.Field< TCoord >.MapCoordinatesToScalarsPlain(), and IG.Num.Func3dBase.TestFunction().
Value() [2/2]
double IG.Num.IFunc3d.Value (vec3 parameters)
Calculates and returns value of the current 3D scalar function.
Parameters
parameters Vector of function parameters (in form of the vec3) struct.
Returns
Function value.
Implemented in IG.Num.Func3dQuadratic, IG.Num.Func3dLinear, IG.Num.Func3dVectorFormBase, and IG.Num.Func3dBase.
Gradient() [1/2]
void IG.Num.IFunc3d.Gradient (double x, double y, double z, out double gradx, out double grady, out double gradz)
Calculates gradient of the current 3D scalar function and returns its components through the specified output variables.
Parameters
x First parameter.
y Second parameter.
z Third parameter.
gradx First component of the returned gradient.
grady Second component of the returned gradient.
gradz Third component of the returned gradient.
Implemented in IG.Num.Func3dExamples.Func3dXYZ, IG.Num.Func3dVectorFormBase, IG.Num.Func3dBase, and IG.Num.Func3dBaseNoGradient.
Referenced by IG.Num.Func3dBase.TestFunction().
Gradient() [2/2]
vec3 IG.Num.IFunc3d.Gradient (vec3 parameters)
Calculates and returns gradient of the current 3D scalar function.
Parameters
parameters Vector of parameters (in form of the vec3 struct)
<returnreturns>Gradient of the current 3D scalar function (in form of the vec3 struct)</returnreturns>
Implemented in IG.Num.Func3dQuadratic, IG.Num.Func3dLinear, IG.Num.Func3dVectorFormBase, and IG.Num.Func3dBase.
Hessian() [1/2]
void IG.Num.IFunc3d.Hessian (double x, double y, double z, out double dxx, out double dyy, out double dzz, out double dxy, out double dxz, out double dyz)
Calculates Hessian of the current 3D scalar function and returns its component through the specified output variables.
Parameters
x First parameter.
y Second parameter.
z Third parameter.
dxx Component 1-1 of the calculated Hessian.
dyy Component 2-2 of the calculated Hessian.
dzz Component 3-3 of the calculated Hessian.
dxy Component 1-2 of the calculated Hessian.
dxz Component 1-3 of the calculated Hessian.
dyz Component 2-3 of the calculated Hessian.
Implemented in IG.Num.Func3dVectorFormBase, IG.Num.Func3dBase, IG.Num.Func3dBaseNoGradient, and IG.Num.Func3dBaseNoHessian.
Hessian() [2/2]
mat3 IG.Num.IFunc3d.Hessian (vec3 parameters)
Calculates and returns Hessian of the current 3D scalar function and returns it (in the form of a mat3 struct).
Implemented in IG.Num.Func3dQuadratic, IG.Num.Func3dLinear, IG.Num.Func3dVectorFormBase, and IG.Num.Func3dBase.
Property Documentation
ValueDefined
bool IG.Num.IFunc3d.ValueDefined get
Whether calculation of function value is defined.
Definition at line 21 of file Function3d.cs.
Referenced by IG.Num.Func3dBase.TestFunction().
GradientDefined
bool IG.Num.IFunc3d.GradientDefined get
Whether calculation of function ngradient is defined.
Definition at line 24 of file Function3d.cs.
Referenced by IG.Num.Func3dBase.TestFunction().
HessianDefined
bool IG.Num.IFunc3d.HessianDefined get
Whether calculation of function Hessian is defined.
Definition at line 27 of file Function3d.cs.
The documentation for this interface was generated from the following file:
iglib/igbase/numeric/geometry/Function3d.cs