Doc: IGLib with source files: IG.Lib.ApplicationCommandlineBase Class Reference
IG.Lib.ApplicationCommandlineBase Class Reference abstract
Base class for main application classes that have the main method of the application based on command line interpreter.
Public Member Functions
ApplicationCommandlineBase ()
Constructor.
virtual void AddDefaultAssemblies ()
Adds assemblies to be automatically referenced by loaded scripts.
abstract void TestMain (string[] args)
Runs tests from scripts according to hard-coded settings.
virtual void AplicationMain (string[] args)
Default main method for the current application.
Public Attributes
string OptDir
Optimization directory that contains data and message files of optimization server.
Protected Member Functions
virtual void SetUserName (string userName)
Sets name of the current user. This method is provided to enable testing code under another user name. Setting to null anihilates effect of previous calls.
abstract CommandLineApplicationInterpreter CreateInterpreter ()
Creates and returns application's command-line interpreter.
int GetScriptNumArguments ()
Returns the number of script run method's arguments (i.e. arguments that are stored in DirectArguments and InterpreterArguments). If there are different numbers of
virtual void SetScriptNumArguments (int numArguments)
Sets the number of script run method's arguments to the specified number. Reallocates argument arrays if necessary.
virtual void SetScriptArgument (int whichArgument, string argumentValue)
Sets the specified script argument; updates array of arguments for running script directly as well as arguments for running script through interpreter.
virtual string GetScriptArgument (int whichArgument)
Gets the specified string arguments, as it is currently set.
Protected Attributes
string ConstRunInteractive = "Interactive"
Interpreter command for running in interactive mode.
string ConstRunScript = "RunScript"
Interpreter command for running dynamic scripts.
string ScriptLocation = null
Location of the script to be loaded.
string ScriptGroupChoice
Main selector for script that is run.
string _scriptChoice
Type _scriptType
string ScriptAction
Selector for script action.
string[] DirectArguments = null
Script arguments used when script is run directly by creating a script object.
string[] InterpreterArguments = null
Interpreter arguments used when script is run through interpreter.
string DefaultActiveDir
Default active directory. The current directory will be set to this directory.
ILoadableScript _scriptToRun
bool RunThroughInterpreter = false
Whether script is loaded and run through interpreter (alternative is direct construction of script class).
string _userNameLowerCase = null
CommandLineApplicationInterpreter TestInterpreter
Application interpreter for running test scripts.
Static Protected Attributes
const string ConstScriptTests = "ScriptTests"
Selecting constant fot TEST script.
const string ConstScriptCustomApp = "ScriptCustomApp"
Selecting constant fot CUSTOM script.
const string ConstInteractive = "Interactive"
Selecting constant for interactive run.
Properties
string ScriptChoice [get, set]
Name of the selected script type that is run.
Type ScriptType [get, set]
Selected type of the script to be run.
ILoadableScript ScriptToRun [get, set]
Script to be run.
virtual string UserNameLowerCase [get]
Gets name of the current user with all letters converted to lower case (in order to avoid ambiguities).
virtual bool IsUserIgor [get]
Returns true if the current user logged on the computer is Igor, or false otherwise.
virtual bool IsUserTadej [get]
Returns true if the current user logged on the computer is Tadej, or false otherwise.
Detailed Description
Base class for main application classes that have the main method of the application based on command line interpreter.
Dhis class represent the base for standard scheme for IGLib-based applications that include command-line interpreter and eventually a number of tests whose selection is hard-coded and which are performed when application command-line arguments are not specified.
$A Igor xx Nov09;
Definition at line 15 of file ApplicationCommandLineBase.cs.
Constructor & Destructor Documentation
ApplicationCommandlineBase()
IG.Lib.ApplicationCommandlineBase.ApplicationCommandlineBase () inline
Constructor.
Definition at line 19 of file ApplicationCommandLineBase.cs.
References IG.Lib.ApplicationCommandlineBase.AddDefaultAssemblies(), IG.Lib.ApplicationCommandlineBase.CreateInterpreter(), and IG.Lib.ApplicationCommandlineBase.TestInterpreter.
Member Function Documentation
SetUserName()
virtual void IG.Lib.ApplicationCommandlineBase.SetUserName (string userName) inline protected virtual
Sets name of the current user. This method is provided to enable testing code under another user name. Setting to null anihilates effect of previous calls.
After call to this method, user name can be set to null in order to retrieve the true user logged in for subsequent operations.
Warning: you should use this only exceptionally, e.g. for testing, and only in testing or demo sections of code.
Parameters
userName Name of the user to be set. Null annihilates previous calls and causes that system provided user name is returned by subsequent queries.
Definition at line 154 of file ApplicationCommandLineBase.cs.
References IG.Lib.UtilSystem.SetUsername().
CreateInterpreter()
abstract CommandLineApplicationInterpreter IG.Lib.ApplicationCommandlineBase.CreateInterpreter () protected pure virtual
Creates and returns application's command-line interpreter.
Implemented in IG.Lib.LoadableScriptBase.StoredScriptSettings, and IG.Lib.ShellApplication< InterpreterType >.
Referenced by IG.Lib.ApplicationCommandlineBase.ApplicationCommandlineBase().
AddDefaultAssemblies()
virtual void IG.Lib.ApplicationCommandlineBase.AddDefaultAssemblies () inline virtual
Adds assemblies to be automatically referenced by loaded scripts.
Reimplemented in IG.Lib.ShellApplication< InterpreterType >.
Definition at line 199 of file ApplicationCommandLineBase.cs.
References IG.Lib.ScriptLoaderBase.AddDefaultAssemblies().
Referenced by IG.Lib.ApplicationCommandlineBase.ApplicationCommandlineBase().
GetScriptNumArguments()
int IG.Lib.ApplicationCommandlineBase.GetScriptNumArguments () inline protected
Returns the number of script run method's arguments (i.e. arguments that are stored in DirectArguments and InterpreterArguments). If there are different numbers of
Definition at line 207 of file ApplicationCommandLineBase.cs.
References IG.Lib.ApplicationCommandlineBase.DirectArguments, and IG.Lib.ApplicationCommandlineBase.InterpreterArguments.
Referenced by IG.Lib.ApplicationCommandlineBase.SetScriptArgument().
SetScriptNumArguments()
virtual void IG.Lib.ApplicationCommandlineBase.SetScriptNumArguments (int numArguments) inline protected virtual
Sets the number of script run method's arguments to the specified number. Reallocates argument arrays if necessary.
Number of arguments includes script run command and command selector for script's internal interpreter, i.e. this number is 2 greater than the number of pure arguments.
For arguments for running script through interpreter, actual number of arguments is 2 greater because it includes command for script loading/running + script location.
Parameters
numArguments
Definition at line 227 of file ApplicationCommandLineBase.cs.
References IG.Lib.ApplicationCommandlineBase.DirectArguments, and IG.Lib.ApplicationCommandlineBase.InterpreterArguments.
Referenced by IG.Lib.ApplicationCommandlineBase.SetScriptArgument().
SetScriptArgument()
virtual void IG.Lib.ApplicationCommandlineBase.SetScriptArgument (int whichArgument, string argumentValue) inline protected virtual
Sets the specified script argument; updates array of arguments for running script directly as well as arguments for running script through interpreter.
Parameters
whichArgument Index of argument in the array of arguments that is actually passed to the script (in the case of running through interpreter, this means without interpreter command for running dynamic scripts and without script location). The 0-th argument is typically (but not always) reserved for action selection.
argumentValue Value of the specified argument to be set.
$A Igor Nov09 Dec11;
Definition at line 261 of file ApplicationCommandLineBase.cs.
References IG.Lib.ApplicationCommandlineBase.DirectArguments, IG.Lib.ApplicationCommandlineBase.GetScriptNumArguments(), IG.Lib.ApplicationCommandlineBase.InterpreterArguments, and IG.Lib.ApplicationCommandlineBase.SetScriptNumArguments().
GetScriptArgument()
virtual string IG.Lib.ApplicationCommandlineBase.GetScriptArgument (int whichArgument) inline protected virtual
Gets the specified string arguments, as it is currently set.
Parameters
whichArgument Index of the obtained argument in the array of arguments to be passed to the script (in the case of running through interpreter, this means without interpreter command for running dynamic scripts and without script location). The 0-th argument is typically (but not always) reserved for action selection.
Definition at line 282 of file ApplicationCommandLineBase.cs.
References IG.Lib.ApplicationCommandlineBase.DirectArguments.
TestMain()
abstract void IG.Lib.ApplicationCommandlineBase.TestMain (string[] args) pure virtual
Runs tests from scripts according to hard-coded settings.
Standard form of test applications for functionality based on IGLib.
Parameters
args Command-line argumets passed when the application is run.
Standard scheme for IGLib-based test applications has been adopted in December 2011.
$A Igor xx Nov09 Dec11;
Implemented in IG.Lib.LoadableScriptBase.StoredScriptSettings, and IG.Lib.ShellApplication< InterpreterType >.
Referenced by IG.Lib.ApplicationCommandlineBase.AplicationMain().
AplicationMain()
virtual void IG.Lib.ApplicationCommandlineBase.AplicationMain (string[] args) inline virtual
Default main method for the current application.
Parameters
args Command-line argumets passed when the application is run.
Standard scheme for IGLib-based test applications has been adopted in December 2011.
$A Igor xx Nov09 Dec11;
Reimplemented in IG.Lib.ShellApplication< InterpreterType >.
Definition at line 298 of file ApplicationCommandLineBase.cs.
References IG.Lib.CommandLineApplicationInterpreter.MainThread, IG.Lib.CommandLineApplicationInterpreter.Run(), IG.Lib.ApplicationCommandlineBase.TestInterpreter, IG.Lib.ApplicationCommandlineBase.TestMain(), and IG.Lib.CommandLineApplicationInterpreter.WarnCommandReplacement.
Member Data Documentation
ConstScriptTests
const string IG.Lib.ApplicationCommandlineBase.ConstScriptTests = "ScriptTests" static protected
Selecting constant fot TEST script.
Test scripts typically include several example methods, which can be selected by the first command-line argument.
Definition at line 33 of file ApplicationCommandLineBase.cs.
ConstScriptCustomApp
const string IG.Lib.ApplicationCommandlineBase.ConstScriptCustomApp = "ScriptCustomApp" static protected
Selecting constant fot CUSTOM script.
Definition at line 36 of file ApplicationCommandLineBase.cs.
ConstInteractive
const string IG.Lib.ApplicationCommandlineBase.ConstInteractive = "Interactive" static protected
Selecting constant for interactive run.
Definition at line 39 of file ApplicationCommandLineBase.cs.
ConstRunInteractive
string IG.Lib.ApplicationCommandlineBase.ConstRunInteractive = "Interactive" protected
Interpreter command for running in interactive mode.
Definition at line 42 of file ApplicationCommandLineBase.cs.
ConstRunScript
string IG.Lib.ApplicationCommandlineBase.ConstRunScript = "RunScript" protected
Interpreter command for running dynamic scripts.
Definition at line 46 of file ApplicationCommandLineBase.cs.
ScriptLocation
string IG.Lib.ApplicationCommandlineBase.ScriptLocation = null protected
Location of the script to be loaded.
Definition at line 49 of file ApplicationCommandLineBase.cs.
ScriptGroupChoice
string IG.Lib.ApplicationCommandlineBase.ScriptGroupChoice protected
Main selector for script that is run.
Definition at line 52 of file ApplicationCommandLineBase.cs.
Referenced by IG.Lib.ShellApplication< CommandLineApplicationInterpreter >.TestMain().
_scriptChoice
string IG.Lib.ApplicationCommandlineBase._scriptChoice protected
Definition at line 54 of file ApplicationCommandLineBase.cs.
_scriptType
Type IG.Lib.ApplicationCommandlineBase._scriptType protected
Definition at line 84 of file ApplicationCommandLineBase.cs.
ScriptAction
string IG.Lib.ApplicationCommandlineBase.ScriptAction protected
Selector for script action.
Definition at line 105 of file ApplicationCommandLineBase.cs.
Referenced by IG.Lib.ShellApplication< CommandLineApplicationInterpreter >.TestMain().
DirectArguments
string [] IG.Lib.ApplicationCommandlineBase.DirectArguments = null protected
Script arguments used when script is run directly by creating a script object.
Definition at line 108 of file ApplicationCommandLineBase.cs.
Referenced by IG.Lib.ApplicationCommandlineBase.GetScriptArgument(), IG.Lib.ApplicationCommandlineBase.GetScriptNumArguments(), IG.Lib.ApplicationCommandlineBase.SetScriptArgument(), and IG.Lib.ApplicationCommandlineBase.SetScriptNumArguments().
InterpreterArguments
string [] IG.Lib.ApplicationCommandlineBase.InterpreterArguments = null protected
Interpreter arguments used when script is run through interpreter.
Definition at line 111 of file ApplicationCommandLineBase.cs.
Referenced by IG.Lib.ApplicationCommandlineBase.GetScriptNumArguments(), IG.Lib.ApplicationCommandlineBase.SetScriptArgument(), and IG.Lib.ApplicationCommandlineBase.SetScriptNumArguments().
DefaultActiveDir
string IG.Lib.ApplicationCommandlineBase.DefaultActiveDir protected
Default active directory. The current directory will be set to this directory.
Definition at line 114 of file ApplicationCommandLineBase.cs.
Referenced by IG.Lib.ShellApplication< CommandLineApplicationInterpreter >.ShellApplication(), and IG.Lib.ShellApplication< CommandLineApplicationInterpreter >.TestMain().
OptDir
string IG.Lib.ApplicationCommandlineBase.OptDir
Optimization directory that contains data and message files of optimization server.
Definition at line 117 of file ApplicationCommandLineBase.cs.
Referenced by IG.Lib.ShellApplication< CommandLineApplicationInterpreter >.ShellApplication(), and IG.Lib.ShellApplication< CommandLineApplicationInterpreter >.TestMain().
_scriptToRun
ILoadableScript IG.Lib.ApplicationCommandlineBase._scriptToRun protected
Definition at line 119 of file ApplicationCommandLineBase.cs.
RunThroughInterpreter
bool IG.Lib.ApplicationCommandlineBase.RunThroughInterpreter = false protected
Whether script is loaded and run through interpreter (alternative is direct construction of script class).
Definition at line 142 of file ApplicationCommandLineBase.cs.
Referenced by IG.Lib.ShellApplication< CommandLineApplicationInterpreter >.TestMain().
_userNameLowerCase
string IG.Lib.ApplicationCommandlineBase._userNameLowerCase = null protected
Definition at line 144 of file ApplicationCommandLineBase.cs.
TestInterpreter
CommandLineApplicationInterpreter IG.Lib.ApplicationCommandlineBase.TestInterpreter protected
Application interpreter for running test scripts.
Definition at line 183 of file ApplicationCommandLineBase.cs.
Referenced by IG.Lib.ApplicationCommandlineBase.AplicationMain(), IG.Lib.ShellApplication< CommandLineApplicationInterpreter >.AplicationMain(), IG.Lib.ApplicationCommandlineBase.ApplicationCommandlineBase(), and IG.Lib.ShellApplication< CommandLineApplicationInterpreter >.TestMain().
Property Documentation
ScriptChoice
string IG.Lib.ApplicationCommandlineBase.ScriptChoice get set protected
Name of the selected script type that is run.
If ScriptType is defined then this property is defined in accordance with it.
Definition at line 59 of file ApplicationCommandLineBase.cs.
Referenced by IG.Lib.ShellApplication< CommandLineApplicationInterpreter >.TestMain().
ScriptType
Type IG.Lib.ApplicationCommandlineBase.ScriptType get set protected
Selected type of the script to be run.
Definition at line 88 of file ApplicationCommandLineBase.cs.
ScriptToRun
ILoadableScript IG.Lib.ApplicationCommandlineBase.ScriptToRun get set protected
Script to be run.
Definition at line 123 of file ApplicationCommandLineBase.cs.
UserNameLowerCase
virtual string IG.Lib.ApplicationCommandlineBase.UserNameLowerCase get
Gets name of the current user with all letters converted to lower case (in order to avoid ambiguities).
Definition at line 162 of file ApplicationCommandLineBase.cs.
IsUserIgor
virtual bool IG.Lib.ApplicationCommandlineBase.IsUserIgor get
Returns true if the current user logged on the computer is Igor, or false otherwise.
Definition at line 171 of file ApplicationCommandLineBase.cs.
IsUserTadej
virtual bool IG.Lib.ApplicationCommandlineBase.IsUserTadej get
Returns true if the current user logged on the computer is Tadej, or false otherwise.
Definition at line 177 of file ApplicationCommandLineBase.cs.
The documentation for this class was generated from the following file:
iglib/igbase/interpreters/ApplicationCommandLineBase.cs