Doc: IGLib with source files: IGLib.Testing.Tests.UtilSpeedTestingTests Class Reference
IGLib.Testing.Tests.UtilSpeedTestingTests Class Reference
Public Member Functions
UtilSpeedTestingTests (ITestOutputHelper output)
This constructor, when called by the test framework, will bring in an object of type ITestOutputHelper, which will be used to write on the tests' output, accessed through the base class's Output property.
void UtilSpeedTesting_ArithmeticSeriesAnalyticalMethodIsCorrect (int n, double a0, double d, double tolerance)
Verifies that finite arithmetic series calculaed analytically is correct.
void UtilSpeedTesting_ArithmeticSeriesNumericalMatchesAnalyticalResult (int n, double a0, double d, double tolerance)
Verifies that finite arithmetic series calculaed numerically matches the result calculatec by analytic formula.
void UtilSpeedTesting_GeometricSeriesAnalyticalMethodIsCorrect (int n, double a0, double k, double tolerance)
Verifies that finite geometric series calculaed analytically is correct.
void UtilSpeedTesting_GeometricSeriesNumericalMatchesAnalyticalResult (int n, double a0, double k, double tolerance)
Verifies that finite geometric series calculaed numerically matches the result calculatec by an analytic formula. Numerical calculation is performed by UtilSpeedTesting.GeometricSeriesNumerical(int, double, double)
void UtilSpeedTesting_GeometricSeriesNumerical_DirectElementCalculation_MatchesAnalyticalResult (int n, double a0, double k, double tolerance)
Verifies that finite geometric series calculaed numerically matches the result calculatec by an analytic formula. Numerical calculation is performed by UtilSpeedTesting.GeometricSeriesNumerical(int, double, double)
void StandardSpeedTestPreparationGeometric_ComparingDifferentNumbersOfExecutioin (int n, double a0, double k, double tolerance)
Performs calculation of geometric series at the same parameters as UtilSpeedTesting.StandardSpeedTestGeometricSeriesBasic(bool), except that calculation is performed with different numbers of terms, in order to find the suitable parameter for standard tests.
Public Member Functions inherited from IGLib.Tests.Base.TestBase< UtilSpeedTestingTests >
TestBase (ITestOutputHelper output, bool assignConsole=true)
Protected Member Functions
void SpeedTestInfo_TwoParameterConstructorWorksCorrectly ()
void SpeedTestInfo_ParameterlessConstructorWorksCorrectly ()
void SpeedTestInfoGeneric_TwoParameterConstructorWorksCorrectly ()
void SpeedTestInfoGeneric_ParameterlessConstructorWorksCorrectly ()
void SpeedTestInfo_WorksCorrectlyUnderNormalConditions ()
Tests the 2 parameter constructor and majority of properties of the \ SpeedTestInfo class (which inherits from SpeedTestInfo<double>).
double DummySpeedTest (out SpeedTestInfo testInfo, Exception exception=null, bool throwBeforeResultsObtained=false, bool throwAfterResultsObtained=false, bool executeActualTest=false)
Provides a dummy speed test method that can be used in testing of SpeedTestInfo class.
void SpeedTestInfo_BehaviorWhenExceptionThrownBeforeObtainingResultsIsCorrect ()
void SpeedTestInfo_BehaviorWhenExceptionThrownAfterObtainingResultsIsCorrect ()
Properties
bool PerformActualCalculationInSpeedTestInfo = false [get]
Properties inherited from IGLib.Tests.Base.TestBase< UtilSpeedTestingTests >
string ExportPathIGLib [get, set]
Export path for tests that generate output files. This is set to IGLibDefaultExportPath by default (good for most cases), but this can be overridden in test class's constructor.
ITestOutputHelper Output [get, set]
Enables writing to tests' output. Provided by the framework (injected via constructor).
static ITestOutputHelper Console [get, set]
This property makes possible to use the name Console instead of Output in test method of this class, such that code can be directly copied to console applications while output is still visible in tests' output. Unfortunately, you cannot use Console.Write(...) because the ITestOutputHelper does not have it.
LoggerFactory LoggerFactory [get, set]
Additional Inherited Members
Protected Attributes inherited from IGLib.Tests.Base.TestBase< UtilSpeedTestingTests >
string ExportPathIGLibTemporary
Static Protected Attributes inherited from IGLib.Tests.Base.TestBase< UtilSpeedTestingTests >
const string DefaultExportPathIGLib
Default export path for tests that generate output. Specified relative to the currennt directory of test execution, which is usually a subdirectory of the [ProjectDir]/bin/ .
Detailed Description
This test class provides unit tests for speed testing utilities, especially from the UtilSpeedTesting class. These can be used to test speed of a computer for certain kind of operations (integer, floating point, memory allocation, etc.) under specific conditions (single / multi-threaded computation, etc.)
This test class inherits from TestBase<ExampleTestClass>, from which it inherits properties TestBase<TestClass>.Output and its alias TestBase<TestClass>.Console of type ITestOutputHelper, which can be used to write on test's output. Only the simple ITestOutputHelper.WriteLine(string) and ITestOutputHelper.WriteLine(string, object[]) methods are available for writing to test Output.
Definition at line 29 of file UtilSpeedTestingTests.cs.
Constructor & Destructor Documentation
UtilSpeedTestingTests()
IGLib.Testing.Tests.UtilSpeedTestingTests.UtilSpeedTestingTests (ITestOutputHelper output) inline
This constructor, when called by the test framework, will bring in an object of type ITestOutputHelper, which will be used to write on the tests' output, accessed through the base class's Output property.
Definition at line 35 of file UtilSpeedTestingTests.cs.
Member Function Documentation
SpeedTestInfo_TwoParameterConstructorWorksCorrectly()
void IGLib.Testing.Tests.UtilSpeedTestingTests.SpeedTestInfo_TwoParameterConstructorWorksCorrectly () inline protected
Definition at line 48 of file UtilSpeedTestingTests.cs.
SpeedTestInfo_ParameterlessConstructorWorksCorrectly()
void IGLib.Testing.Tests.UtilSpeedTestingTests.SpeedTestInfo_ParameterlessConstructorWorksCorrectly () inline protected
Definition at line 59 of file UtilSpeedTestingTests.cs.
SpeedTestInfoGeneric_TwoParameterConstructorWorksCorrectly()
void IGLib.Testing.Tests.UtilSpeedTestingTests.SpeedTestInfoGeneric_TwoParameterConstructorWorksCorrectly () inline protected
Definition at line 70 of file UtilSpeedTestingTests.cs.
SpeedTestInfoGeneric_ParameterlessConstructorWorksCorrectly()
void IGLib.Testing.Tests.UtilSpeedTestingTests.SpeedTestInfoGeneric_ParameterlessConstructorWorksCorrectly () inline protected
Definition at line 81 of file UtilSpeedTestingTests.cs.
SpeedTestInfo_WorksCorrectlyUnderNormalConditions()
void IGLib.Testing.Tests.UtilSpeedTestingTests.SpeedTestInfo_WorksCorrectlyUnderNormalConditions () inline protected
Tests the 2 parameter constructor and majority of properties of the \ SpeedTestInfo class (which inherits from SpeedTestInfo<double>).
Definition at line 94 of file UtilSpeedTestingTests.cs.
References IGLib.Testing.Tests.UtilSpeedTestingTests.PerformActualCalculationInSpeedTestInfo.
DummySpeedTest()
double IGLib.Testing.Tests.UtilSpeedTestingTests.DummySpeedTest (out SpeedTestInfo testInfo, Exception exception = null, bool throwBeforeResultsObtained = false, bool throwAfterResultsObtained = false, bool executeActualTest = false) inline protected
Provides a dummy speed test method that can be used in testing of SpeedTestInfo class.
Parameters
testInfo Output parameter - info object created by the speed test executing function.
exception Exception that will be thrown at the prescribed location within this method If null then InvalidOperationException with a default message is assigned to this parameter..
throwBeforeResultsObtained If true then exception is thrown before the results are obtained by from the (dummy / imaginary) test.
throwAfterResultsObtained If true then exception is thrown after the results are obtained and assigned to testInfo .
executeActualTest If true then actual test is executed, otherwise the test result and duration are just assigned (values are selected such that they make sense).
Returns
The speed factor calculated form the test.
Definition at line 185 of file UtilSpeedTestingTests.cs.
Referenced by IGLib.Testing.Tests.UtilSpeedTestingTests.SpeedTestInfo_BehaviorWhenExceptionThrownAfterObtainingResultsIsCorrect(), and IGLib.Testing.Tests.UtilSpeedTestingTests.SpeedTestInfo_BehaviorWhenExceptionThrownBeforeObtainingResultsIsCorrect().
SpeedTestInfo_BehaviorWhenExceptionThrownBeforeObtainingResultsIsCorrect()
void IGLib.Testing.Tests.UtilSpeedTestingTests.SpeedTestInfo_BehaviorWhenExceptionThrownBeforeObtainingResultsIsCorrect () inline protected
Definition at line 258 of file UtilSpeedTestingTests.cs.
References IGLib.Testing.Tests.UtilSpeedTestingTests.DummySpeedTest().
SpeedTestInfo_BehaviorWhenExceptionThrownAfterObtainingResultsIsCorrect()
void IGLib.Testing.Tests.UtilSpeedTestingTests.SpeedTestInfo_BehaviorWhenExceptionThrownAfterObtainingResultsIsCorrect () inline protected
Definition at line 288 of file UtilSpeedTestingTests.cs.
References IGLib.Testing.Tests.UtilSpeedTestingTests.DummySpeedTest().
UtilSpeedTesting_ArithmeticSeriesAnalyticalMethodIsCorrect()
void IGLib.Testing.Tests.UtilSpeedTestingTests.UtilSpeedTesting_ArithmeticSeriesAnalyticalMethodIsCorrect (int n, double a0, double d, double tolerance) inline
Verifies that finite arithmetic series calculaed analytically is correct.
Test is based on the separate built-in analytical calculation of the expected result in this method. For double verification, the test UtilSpeedTesting_ArithmeticSeriesNumericalMatchesAnalyticalResult compares results of the method for analytical calculation of the finite arithmetic series with the method for numerical calculation, which reduces the possibility of wrong implementation to the minimum.
The tested method will be used to chack correctness in other tests.
Parameters
n Number of elements of the sum.
a0 The first element of the sum.
k The constant difference between the next element of the sequence and the previous element.
tolerance The tolerance, allowed discrepancy between both results to account fo rounding errors.
Definition at line 341 of file UtilSpeedTestingTests.cs.
References IGLib.Tests.UtilSpeedTesting.ArithmeticSeriesAnalytical(), and IGLib.Tests.Base.TestBase< UtilSpeedTestingTests >.Console.
UtilSpeedTesting_ArithmeticSeriesNumericalMatchesAnalyticalResult()
void IGLib.Testing.Tests.UtilSpeedTestingTests.UtilSpeedTesting_ArithmeticSeriesNumericalMatchesAnalyticalResult (int n, double a0, double d, double tolerance) inline
Verifies that finite arithmetic series calculaed numerically matches the result calculatec by analytic formula.
Parameters
n Number of elements of the sum.
a0 The first element of the sum.
d The constant difference between the next element of the sequence and the previous element.
tolerance The tolerance, allowed discrepancy between both results to account fo rounding errors.
Definition at line 373 of file UtilSpeedTestingTests.cs.
References IGLib.Tests.UtilSpeedTesting.ArithmeticSeriesAnalytical(), IGLib.Tests.UtilSpeedTesting.ArithmeticSeriesNumerical(), and IGLib.Tests.Base.TestBase< UtilSpeedTestingTests >.Console.
UtilSpeedTesting_GeometricSeriesAnalyticalMethodIsCorrect()
void IGLib.Testing.Tests.UtilSpeedTestingTests.UtilSpeedTesting_GeometricSeriesAnalyticalMethodIsCorrect (int n, double a0, double k, double tolerance) inline
Verifies that finite geometric series calculaed analytically is correct.
Test is based on the separate built-in analytical calculation of the expected result by this method. For double verification, the test UtilSpeedTesting_GeometricSeriesNumericalMatchesAnalyticalResult(int, double, double, double) compares results of the method for analytical calculation of the finite arithmetic series with the method for numerical calculation, which reduces the possibility of wrong implementation.
The tested method will be used to chack correctness in other tests.
Parameters
n Number of elements of the sum.
a0 The first element of the sum.
d The constant quotient between the next element of the sequence and the current element.
tolerance The tolerance, allowed discrepancy between both results, to account for rounding errors.
Definition at line 408 of file UtilSpeedTestingTests.cs.
References IGLib.Tests.Base.TestBase< UtilSpeedTestingTests >.Console, and IGLib.Tests.UtilSpeedTesting.GeometricSeriesAnalytical().
UtilSpeedTesting_GeometricSeriesNumericalMatchesAnalyticalResult()
void IGLib.Testing.Tests.UtilSpeedTestingTests.UtilSpeedTesting_GeometricSeriesNumericalMatchesAnalyticalResult (int n, double a0, double k, double tolerance) inline
Verifies that finite geometric series calculaed numerically matches the result calculatec by an analytic formula. Numerical calculation is performed by UtilSpeedTesting.GeometricSeriesNumerical(int, double, double)
Parameters
n Number of elements of the sum.
a0 The first element of the sum.
k The constant quotient between the next element of the sequence and the current element.
tolerance The tolerance, allowed discrepancy between both results, to account fo rounding errors.
Definition at line 446 of file UtilSpeedTestingTests.cs.
References IGLib.Tests.Base.TestBase< UtilSpeedTestingTests >.Console, IGLib.Tests.UtilSpeedTesting.GeometricSeriesAnalytical(), and IGLib.Tests.UtilSpeedTesting.GeometricSeriesNumerical().
UtilSpeedTesting_GeometricSeriesNumerical_DirectElementCalculation_MatchesAnalyticalResult()
void IGLib.Testing.Tests.UtilSpeedTestingTests.UtilSpeedTesting_GeometricSeriesNumerical_DirectElementCalculation_MatchesAnalyticalResult (int n, double a0, double k, double tolerance) inline
Verifies that finite geometric series calculaed numerically matches the result calculatec by an analytic formula. Numerical calculation is performed by UtilSpeedTesting.GeometricSeriesNumerical(int, double, double)
Parameters
n Number of elements of the sum.
a0 The first element of the sum.
k The constant quotient between the next element of the sequence and the current element.
tolerance The tolerance, allowed discrepancy between both results, to account fo rounding errors.
Definition at line 481 of file UtilSpeedTestingTests.cs.
References IGLib.Tests.Base.TestBase< UtilSpeedTestingTests >.Console, IGLib.Tests.UtilSpeedTesting.GeometricSeriesAnalytical(), and IGLib.Tests.UtilSpeedTesting.GeometricSeriesNumerical_DirectElementCalculation().
StandardSpeedTestPreparationGeometric_ComparingDifferentNumbersOfExecutioin()
void IGLib.Testing.Tests.UtilSpeedTestingTests.StandardSpeedTestPreparationGeometric_ComparingDifferentNumbersOfExecutioin (int n, double a0, double k, double tolerance) inline
Performs calculation of geometric series at the same parameters as UtilSpeedTesting.StandardSpeedTestGeometricSeriesBasic(bool), except that calculation is performed with different numbers of terms, in order to find the suitable parameter for standard tests.
Parameters
n Number of elements of the sum.
a0 The first element of the sum.
k The constant quotient between the next element of the sequence and the current element.
tolerance The tolerance, allowed discrepancy between both results, to account fo rounding errors.
Definition at line 528 of file UtilSpeedTestingTests.cs.
References IGLib.Tests.Base.TestBase< UtilSpeedTestingTests >.Console, IGLib.Tests.UtilSpeedTesting.GeometricSeriesAnalytical(), and IGLib.Tests.UtilSpeedTesting.GeometricSeriesNumerical().
Property Documentation
PerformActualCalculationInSpeedTestInfo
bool IGLib.Testing.Tests.UtilSpeedTestingTests.PerformActualCalculationInSpeedTestInfo = false get private
Definition at line 44 of file UtilSpeedTestingTests.cs.
Referenced by IGLib.Testing.Tests.UtilSpeedTestingTests.SpeedTestInfo_WorksCorrectlyUnderNormalConditions().
The documentation for this class was generated from the following file:
IGLibCore/tests/IGLib.Core.Tests/Testing/UtilSpeedTestingTests.cs