Doc: IGLib with source files: IGLib.Core.SingleTargetTypeConverterBase< TTarget > Class Template Reference
IGLib.Core.SingleTargetTypeConverterBase< TTarget > Class Template Reference abstract
Public Member Functions
abstract object Convert (object source)
bool TryConvert (object source, out object target)
abstract TTarget ConvertTyped< TSource > (TSource source)
virtual bool TryConvertTyped< TSource > (TSource source, out TTarget target)
Public Member Functions inherited from IGLib.Core.ISingleTargetTypeConverter< TTarget >
TargetType ConvertTyped< SourceType > (SourceType source)
bool TryConvertTyped< SourceType > (SourceType source, out TargetType target)
object Convert (object source)
bool TryConvert (object source, out object target)
Properties
Type TargetType = typeof(TTarget) [get]
Properties inherited from IGLib.Core.ISingleTargetTypeConverter< TTarget >
Type TargetType [get]
Detailed Description
Definition at line 7 of file SingleTargetTypeConverterBaseGeneric.cs.
Member Function Documentation
Convert()
abstract object IGLib.Core.SingleTargetTypeConverterBase< TTarget >.Convert (object source) pure virtual
Referenced by IGLib.Core.SingleTargetTypeConverterBase< TTarget >.TryConvert().
TryConvert()
bool IGLib.Core.SingleTargetTypeConverterBase< TTarget >.TryConvert (object source, out object target) inline
Definition at line 14 of file SingleTargetTypeConverterBaseGeneric.cs.
References IGLib.Core.SingleTargetTypeConverterBase< TTarget >.Convert().
ConvertTyped< TSource >()
abstract TTarget IGLib.Core.SingleTargetTypeConverterBase< TTarget >.ConvertTyped< TSource > (TSource source) pure virtual
Referenced by IGLib.Core.SingleTargetTypeConverterBase< TTarget >.TryConvertTyped< TSource >().
TryConvertTyped< TSource >()
virtual bool IGLib.Core.SingleTargetTypeConverterBase< TTarget >.TryConvertTyped< TSource > (TSource source, out TTarget target) inline virtual
Definition at line 30 of file SingleTargetTypeConverterBaseGeneric.cs.
References IGLib.Core.SingleTargetTypeConverterBase< TTarget >.ConvertTyped< TSource >().
Property Documentation
TargetType
Type IGLib.Core.SingleTargetTypeConverterBase< TTarget >.TargetType = typeof(TTarget) get
Definition at line 10 of file SingleTargetTypeConverterBaseGeneric.cs.
The documentation for this class was generated from the following file:
IGLibGraphics3D/src/IGLib.Graphics3D/other/TypeConversion/SingleConverters/SingleTargetTypeConverterBaseGeneric.cs