Doc: IGLib with source files: IGLib.Core.Tests.BasicTypeConverterTests Class Reference
IGLib.Core.Tests.BasicTypeConverterTests Class Reference
Tests of the basic type converter (BasicTypeConverter, implementation of the ITypeConverter interface).
Public Member Functions
BasicTypeConverterTests (ITestOutputHelper output)
Calling base constructor initializes things like TestBase<TestClass>.Output and TestBase<TestClass>.Output properties that enable writing on tests' output.
Public Member Functions inherited from IGLib.Core.Tests.TypeConverterTestsBase< BasicTypeConverterTests >
TypeConverterTestsBase (ITestOutputHelper output)
Calling base constructor initializes things like TestBase<TestClass>.Output and TestBase<TestClass>.Output properties that enable writing on tests' output.
Protected Member Functions
virtual void SpecificTypeConverter_RoundTripConversion_IntToIntObjectToInt_IsCorrect ()
virtual void SpecificTypeConverter_RoundTripConversion_IntToDoubleObjectToDouble_IsCorrect ()
virtual void SpecificTypeConverter_RoundTripConversion_IntToDoubleObjectToInt_IsCorrect ()
virtual void SpecificTypeConverter_RoundTripConversion_DoubleToDoubleObjectToDouble_IsCorrect ()
virtual void SpecificTypeConverter_RoundTripConversion_IntegerDoubleToIntObjectToInt_IsCorrect ()
virtual void SpecificTypeConverter_RoundTripConversion_NonintegerDoubleToIntObjectToInt_IsCorrect ()
virtual void SpecificTypeConverter_RoundTripConversion_OwerflowDoubleToIntObjectToInt_IsCorrect ()
virtual void SpecificTypeConverter_RoundTripConversion_NonintegerDoubleToIntObjectToDouble_IsCorrect ()
virtual void SpecificTypeConverter_RoundTripConversion_DoubleToStringObjectToDouble_IsCorrect ()
virtual void SpecificTypeConverter_RoundTripConversion_StringToDoubleObjectToString_IsCorrect ()
virtual void SpecificTypeConverter_RoundTripConversion_StringWithUnderscoresToDoubleObjectToDouble_IsCorrect ()
virtual void SpecificTypeConverter_RoundTripConversion_DoubleStringToDoubleObjectToInt_IsCorrect ()
virtual void SpecificTypeConverter_RoundTripConversion_DoubleToStringObjectToString_IsCorrect ()
virtual void SpecificTypeConverter_RoundTripConversion_ClassToClassObjectToClass_IsCorrect ()
virtual void SpecificTypeConverter_RoundTripConversion_DerivedClassToBaseClassObjectToBaseClass_IsCorrect ()
virtual void SpecificTypeConverter_Speed_RoundTripConversion_IntToIntObjectToInt_IsCorrect ()
virtual void SpecificTypeConverter_Speed_RoundTripConversion_IntToDoubleObjectToInt_IsCorrect ()
virtual void SpecificTypeConverter_Speed_RoundTripConversion_DoubleToIntObjectToDouble_IsCorrect ()
virtual void SpecificTypeConverter_Speed_RoundTripConversion_DoubleToStringObjectToDouble_IsCorrect ()
virtual void SpecificTypeConverter_Speed_RoundTripConversion_DerivedClassToBaseClassObjectToBaseClass_IsCorrect ()
Protected Member Functions inherited from IGLib.Core.Tests.TypeConverterTestsBase< BasicTypeConverterTests >
void TypeConverter_Speed_ConversionToObjectAndBackTest< OriginalType > (ITypeConverter typeConverter, int numExecutions, double minExecutionsPerSecond, OriginalType original, bool restoreObjectBackToValue=true, bool doOutputInReferenceTest=false)
Like TypeConverter_Speed_ConversionToObjectAndBackTest<OriginalType, TargetType, RestoredType>(ITypeConverter, int, double, OriginalType, TargetType, RestoredType, bool), but with target type and the type of restored variable both equal to type of the original variable, and also the expected assiged object value and the restored value being equal to the original value.
Properties
virtual ITypeConverter TypeConverter = new BasicTypeConverter() [get]
The type converter that is under test.
virtual int NumExecutions = 1_000 [get]
Number of executions in speed tests.
virtual double MinPerSecond = 10_000 [get]
Minimum required number of executions per second in speed tests.
Additional Inherited Members
Protected Attributes inherited from IGLib.Core.Tests.TypeConverterTestsBase< BasicTypeConverterTests >
CommonType Coverted
Like TypeConverter_ConversionToObjectAndBackTest<OriginalType, TargetType, RestoredType>(OriginalType, RestoredType), but with target type and the type of restored variable both equal to type of the original variable, and also the expected assigned object value and the expected restored value being equal to the original value.
TargetType Converted
Performs test of conversion via ITypeConverter from a value of type OriginalType to a value of the target type TargetType to be assigned to a variable of type object, and then converts this value to type RestoredType and copies (restores) it to a variable of that type.
Detailed Description
Tests of the basic type converter (BasicTypeConverter, implementation of the ITypeConverter interface).
Definition at line 20 of file BasicTypeConverterTests.cs.
Constructor & Destructor Documentation
BasicTypeConverterTests()
IGLib.Core.Tests.BasicTypeConverterTests.BasicTypeConverterTests (ITestOutputHelper output) inline
Calling base constructor initializes things like TestBase<TestClass>.Output and TestBase<TestClass>.Output properties that enable writing on tests' output.
Parameters
output This parameter will be provided to constructor (injected via constructor) by the test framework. I is also stored to Console property, such that test code can use RoslynScriptingApiExamplesTests.Console.WriteLine(string) method to generate test output.
Definition at line 29 of file BasicTypeConverterTests.cs.
Member Function Documentation
SpecificTypeConverter_RoundTripConversion_IntToIntObjectToInt_IsCorrect()
virtual void IGLib.Core.Tests.BasicTypeConverterTests.SpecificTypeConverter_RoundTripConversion_IntToIntObjectToInt_IsCorrect () inline protected virtual
Definition at line 48 of file BasicTypeConverterTests.cs.
References IGLib.Core.Tests.BasicTypeConverterTests.TypeConverter.
SpecificTypeConverter_RoundTripConversion_IntToDoubleObjectToDouble_IsCorrect()
virtual void IGLib.Core.Tests.BasicTypeConverterTests.SpecificTypeConverter_RoundTripConversion_IntToDoubleObjectToDouble_IsCorrect () inline protected virtual
Definition at line 54 of file BasicTypeConverterTests.cs.
References IGLib.Core.Tests.BasicTypeConverterTests.TypeConverter.
SpecificTypeConverter_RoundTripConversion_IntToDoubleObjectToInt_IsCorrect()
virtual void IGLib.Core.Tests.BasicTypeConverterTests.SpecificTypeConverter_RoundTripConversion_IntToDoubleObjectToInt_IsCorrect () inline protected virtual
Definition at line 60 of file BasicTypeConverterTests.cs.
References IGLib.Core.Tests.BasicTypeConverterTests.TypeConverter.
SpecificTypeConverter_RoundTripConversion_DoubleToDoubleObjectToDouble_IsCorrect()
virtual void IGLib.Core.Tests.BasicTypeConverterTests.SpecificTypeConverter_RoundTripConversion_DoubleToDoubleObjectToDouble_IsCorrect () inline protected virtual
Definition at line 68 of file BasicTypeConverterTests.cs.
References IGLib.Core.Tests.BasicTypeConverterTests.TypeConverter.
SpecificTypeConverter_RoundTripConversion_IntegerDoubleToIntObjectToInt_IsCorrect()
virtual void IGLib.Core.Tests.BasicTypeConverterTests.SpecificTypeConverter_RoundTripConversion_IntegerDoubleToIntObjectToInt_IsCorrect () inline protected virtual
Definition at line 74 of file BasicTypeConverterTests.cs.
References IGLib.Core.Tests.BasicTypeConverterTests.TypeConverter.
SpecificTypeConverter_RoundTripConversion_NonintegerDoubleToIntObjectToInt_IsCorrect()
virtual void IGLib.Core.Tests.BasicTypeConverterTests.SpecificTypeConverter_RoundTripConversion_NonintegerDoubleToIntObjectToInt_IsCorrect () inline protected virtual
Definition at line 80 of file BasicTypeConverterTests.cs.
References IGLib.Core.Tests.BasicTypeConverterTests.TypeConverter.
SpecificTypeConverter_RoundTripConversion_OwerflowDoubleToIntObjectToInt_IsCorrect()
virtual void IGLib.Core.Tests.BasicTypeConverterTests.SpecificTypeConverter_RoundTripConversion_OwerflowDoubleToIntObjectToInt_IsCorrect () inline protected virtual
Definition at line 88 of file BasicTypeConverterTests.cs.
References IGLib.Core.Tests.BasicTypeConverterTests.TypeConverter.
SpecificTypeConverter_RoundTripConversion_NonintegerDoubleToIntObjectToDouble_IsCorrect()
virtual void IGLib.Core.Tests.BasicTypeConverterTests.SpecificTypeConverter_RoundTripConversion_NonintegerDoubleToIntObjectToDouble_IsCorrect () inline protected virtual
Definition at line 115 of file BasicTypeConverterTests.cs.
References IGLib.Core.Tests.BasicTypeConverterTests.TypeConverter.
SpecificTypeConverter_RoundTripConversion_DoubleToStringObjectToDouble_IsCorrect()
virtual void IGLib.Core.Tests.BasicTypeConverterTests.SpecificTypeConverter_RoundTripConversion_DoubleToStringObjectToDouble_IsCorrect () inline protected virtual
Definition at line 123 of file BasicTypeConverterTests.cs.
References IGLib.Core.Tests.BasicTypeConverterTests.TypeConverter.
SpecificTypeConverter_RoundTripConversion_StringToDoubleObjectToString_IsCorrect()
virtual void IGLib.Core.Tests.BasicTypeConverterTests.SpecificTypeConverter_RoundTripConversion_StringToDoubleObjectToString_IsCorrect () inline protected virtual
Definition at line 129 of file BasicTypeConverterTests.cs.
References IGLib.Core.Tests.BasicTypeConverterTests.TypeConverter.
SpecificTypeConverter_RoundTripConversion_StringWithUnderscoresToDoubleObjectToDouble_IsCorrect()
virtual void IGLib.Core.Tests.BasicTypeConverterTests.SpecificTypeConverter_RoundTripConversion_StringWithUnderscoresToDoubleObjectToDouble_IsCorrect () inline protected virtual
Definition at line 136 of file BasicTypeConverterTests.cs.
References IGLib.Core.Tests.BasicTypeConverterTests.TypeConverter.
SpecificTypeConverter_RoundTripConversion_DoubleStringToDoubleObjectToInt_IsCorrect()
virtual void IGLib.Core.Tests.BasicTypeConverterTests.SpecificTypeConverter_RoundTripConversion_DoubleStringToDoubleObjectToInt_IsCorrect () inline protected virtual
Definition at line 165 of file BasicTypeConverterTests.cs.
References IGLib.Core.Tests.BasicTypeConverterTests.TypeConverter.
SpecificTypeConverter_RoundTripConversion_DoubleToStringObjectToString_IsCorrect()
virtual void IGLib.Core.Tests.BasicTypeConverterTests.SpecificTypeConverter_RoundTripConversion_DoubleToStringObjectToString_IsCorrect () inline protected virtual
Definition at line 171 of file BasicTypeConverterTests.cs.
References IGLib.Core.Tests.BasicTypeConverterTests.TypeConverter.
SpecificTypeConverter_RoundTripConversion_ClassToClassObjectToClass_IsCorrect()
virtual void IGLib.Core.Tests.BasicTypeConverterTests.SpecificTypeConverter_RoundTripConversion_ClassToClassObjectToClass_IsCorrect () inline protected virtual
Definition at line 177 of file BasicTypeConverterTests.cs.
References IGLib.Core.Tests.BasicTypeConverterTests.TypeConverter.
SpecificTypeConverter_RoundTripConversion_DerivedClassToBaseClassObjectToBaseClass_IsCorrect()
virtual void IGLib.Core.Tests.BasicTypeConverterTests.SpecificTypeConverter_RoundTripConversion_DerivedClassToBaseClassObjectToBaseClass_IsCorrect () inline protected virtual
Definition at line 184 of file BasicTypeConverterTests.cs.
References IGLib.Core.Tests.BasicTypeConverterTests.TypeConverter.
SpecificTypeConverter_Speed_RoundTripConversion_IntToIntObjectToInt_IsCorrect()
virtual void IGLib.Core.Tests.BasicTypeConverterTests.SpecificTypeConverter_Speed_RoundTripConversion_IntToIntObjectToInt_IsCorrect () inline protected virtual
Definition at line 202 of file BasicTypeConverterTests.cs.
References IGLib.Core.Tests.BasicTypeConverterTests.MinPerSecond, IGLib.Core.Tests.BasicTypeConverterTests.NumExecutions, and IGLib.Core.Tests.BasicTypeConverterTests.TypeConverter.
SpecificTypeConverter_Speed_RoundTripConversion_IntToDoubleObjectToInt_IsCorrect()
virtual void IGLib.Core.Tests.BasicTypeConverterTests.SpecificTypeConverter_Speed_RoundTripConversion_IntToDoubleObjectToInt_IsCorrect () inline protected virtual
Definition at line 209 of file BasicTypeConverterTests.cs.
References IGLib.Core.Tests.BasicTypeConverterTests.MinPerSecond, IGLib.Core.Tests.BasicTypeConverterTests.NumExecutions, and IGLib.Core.Tests.BasicTypeConverterTests.TypeConverter.
SpecificTypeConverter_Speed_RoundTripConversion_DoubleToIntObjectToDouble_IsCorrect()
virtual void IGLib.Core.Tests.BasicTypeConverterTests.SpecificTypeConverter_Speed_RoundTripConversion_DoubleToIntObjectToDouble_IsCorrect () inline protected virtual
Definition at line 216 of file BasicTypeConverterTests.cs.
References IGLib.Core.Tests.BasicTypeConverterTests.MinPerSecond, IGLib.Core.Tests.BasicTypeConverterTests.NumExecutions, and IGLib.Core.Tests.BasicTypeConverterTests.TypeConverter.
SpecificTypeConverter_Speed_RoundTripConversion_DoubleToStringObjectToDouble_IsCorrect()
virtual void IGLib.Core.Tests.BasicTypeConverterTests.SpecificTypeConverter_Speed_RoundTripConversion_DoubleToStringObjectToDouble_IsCorrect () inline protected virtual
Definition at line 223 of file BasicTypeConverterTests.cs.
References IGLib.Core.Tests.BasicTypeConverterTests.MinPerSecond, IGLib.Core.Tests.BasicTypeConverterTests.NumExecutions, and IGLib.Core.Tests.BasicTypeConverterTests.TypeConverter.
SpecificTypeConverter_Speed_RoundTripConversion_DerivedClassToBaseClassObjectToBaseClass_IsCorrect()
virtual void IGLib.Core.Tests.BasicTypeConverterTests.SpecificTypeConverter_Speed_RoundTripConversion_DerivedClassToBaseClassObjectToBaseClass_IsCorrect () inline protected virtual
Definition at line 230 of file BasicTypeConverterTests.cs.
References IGLib.Core.Tests.BasicTypeConverterTests.MinPerSecond, IGLib.Core.Tests.BasicTypeConverterTests.NumExecutions, and IGLib.Core.Tests.BasicTypeConverterTests.TypeConverter.
Property Documentation
TypeConverter
virtual ITypeConverter IGLib.Core.Tests.BasicTypeConverterTests.TypeConverter = new BasicTypeConverter() get protected
The type converter that is under test.
Definition at line 34 of file BasicTypeConverterTests.cs.
Referenced by IGLib.Core.Tests.BasicTypeConverterTests.SpecificTypeConverter_RoundTripConversion_ClassToClassObjectToClass_IsCorrect(), IGLib.Core.Tests.BasicTypeConverterTests.SpecificTypeConverter_RoundTripConversion_DerivedClassToBaseClassObjectToBaseClass_IsCorrect(), IGLib.Core.Tests.BasicTypeConverterTests.SpecificTypeConverter_RoundTripConversion_DoubleStringToDoubleObjectToInt_IsCorrect(), IGLib.Core.Tests.BasicTypeConverterTests.SpecificTypeConverter_RoundTripConversion_DoubleToDoubleObjectToDouble_IsCorrect(), IGLib.Core.Tests.BasicTypeConverterTests.SpecificTypeConverter_RoundTripConversion_DoubleToStringObjectToDouble_IsCorrect(), IGLib.Core.Tests.BasicTypeConverterTests.SpecificTypeConverter_RoundTripConversion_DoubleToStringObjectToString_IsCorrect(), IGLib.Core.Tests.BasicTypeConverterTests.SpecificTypeConverter_RoundTripConversion_IntegerDoubleToIntObjectToInt_IsCorrect(), IGLib.Core.Tests.BasicTypeConverterTests.SpecificTypeConverter_RoundTripConversion_IntToDoubleObjectToDouble_IsCorrect(), IGLib.Core.Tests.BasicTypeConverterTests.SpecificTypeConverter_RoundTripConversion_IntToDoubleObjectToInt_IsCorrect(), IGLib.Core.Tests.BasicTypeConverterTests.SpecificTypeConverter_RoundTripConversion_IntToIntObjectToInt_IsCorrect(), IGLib.Core.Tests.BasicTypeConverterTests.SpecificTypeConverter_RoundTripConversion_NonintegerDoubleToIntObjectToDouble_IsCorrect(), IGLib.Core.Tests.BasicTypeConverterTests.SpecificTypeConverter_RoundTripConversion_NonintegerDoubleToIntObjectToInt_IsCorrect(), IGLib.Core.Tests.BasicTypeConverterTests.SpecificTypeConverter_RoundTripConversion_OwerflowDoubleToIntObjectToInt_IsCorrect(), IGLib.Core.Tests.BasicTypeConverterTests.SpecificTypeConverter_RoundTripConversion_StringToDoubleObjectToString_IsCorrect(), IGLib.Core.Tests.BasicTypeConverterTests.SpecificTypeConverter_RoundTripConversion_StringWithUnderscoresToDoubleObjectToDouble_IsCorrect(), IGLib.Core.Tests.BasicTypeConverterTests.SpecificTypeConverter_Speed_RoundTripConversion_DerivedClassToBaseClassObjectToBaseClass_IsCorrect(), IGLib.Core.Tests.BasicTypeConverterTests.SpecificTypeConverter_Speed_RoundTripConversion_DoubleToIntObjectToDouble_IsCorrect(), IGLib.Core.Tests.BasicTypeConverterTests.SpecificTypeConverter_Speed_RoundTripConversion_DoubleToStringObjectToDouble_IsCorrect(), IGLib.Core.Tests.BasicTypeConverterTests.SpecificTypeConverter_Speed_RoundTripConversion_IntToDoubleObjectToInt_IsCorrect(), and IGLib.Core.Tests.BasicTypeConverterTests.SpecificTypeConverter_Speed_RoundTripConversion_IntToIntObjectToInt_IsCorrect().
NumExecutions
virtual int IGLib.Core.Tests.BasicTypeConverterTests.NumExecutions = 1_000 get protected
Number of executions in speed tests.
Definition at line 37 of file BasicTypeConverterTests.cs.
Referenced by IGLib.Core.Tests.BasicTypeConverterTests.SpecificTypeConverter_Speed_RoundTripConversion_DerivedClassToBaseClassObjectToBaseClass_IsCorrect(), IGLib.Core.Tests.BasicTypeConverterTests.SpecificTypeConverter_Speed_RoundTripConversion_DoubleToIntObjectToDouble_IsCorrect(), IGLib.Core.Tests.BasicTypeConverterTests.SpecificTypeConverter_Speed_RoundTripConversion_DoubleToStringObjectToDouble_IsCorrect(), IGLib.Core.Tests.BasicTypeConverterTests.SpecificTypeConverter_Speed_RoundTripConversion_IntToDoubleObjectToInt_IsCorrect(), and IGLib.Core.Tests.BasicTypeConverterTests.SpecificTypeConverter_Speed_RoundTripConversion_IntToIntObjectToInt_IsCorrect().
MinPerSecond
virtual double IGLib.Core.Tests.BasicTypeConverterTests.MinPerSecond = 10_000 get protected
Minimum required number of executions per second in speed tests.
Definition at line 43 of file BasicTypeConverterTests.cs.
Referenced by IGLib.Core.Tests.BasicTypeConverterTests.SpecificTypeConverter_Speed_RoundTripConversion_DerivedClassToBaseClassObjectToBaseClass_IsCorrect(), IGLib.Core.Tests.BasicTypeConverterTests.SpecificTypeConverter_Speed_RoundTripConversion_DoubleToIntObjectToDouble_IsCorrect(), IGLib.Core.Tests.BasicTypeConverterTests.SpecificTypeConverter_Speed_RoundTripConversion_DoubleToStringObjectToDouble_IsCorrect(), IGLib.Core.Tests.BasicTypeConverterTests.SpecificTypeConverter_Speed_RoundTripConversion_IntToDoubleObjectToInt_IsCorrect(), and IGLib.Core.Tests.BasicTypeConverterTests.SpecificTypeConverter_Speed_RoundTripConversion_IntToIntObjectToInt_IsCorrect().
The documentation for this class was generated from the following file:
IGLibGraphics3D/tests/IGLib.Graphics3D.Tests/other/TypeConversion/BasicTypeConverterTests.cs