Doc: IGLib with source files: IG.Num.SpeedTestCpu Class Reference
IG.Num.SpeedTestCpu Class Reference
Various utilities for testing computational speed of the current system.
Static Public Member Functions
static double TestComputationalTimesQR (int numEq, int outLevel)
Test of QR decomposition. Writes times necessary for all steps.
static double TestComputationalTimesQR (int numEq, int outLevel, bool testProduct)
Test of QR decomposition, also measures time necessary fo rindividual operations.
static double TestComputationalTimesLU (int numEq, int outLevel)
Test of LU decomposition.
static double TestComputationalTimesLU (int numEq, int outLevel, bool testProduct)
Test of LU decomposition.
static double TestComputationalTimesCholesky (int numEq, int outLevel)
Test of Cholesky decomposition, also measures time necessary fo rindividual operations.
static double TestComputationalTimesCholesky (int numEq, int outLevel, bool testProduct)
Test of Cholesky decomposition, also measures time necessary fo rindividual operations.
static double TestComputationalTimesLU_IGLib (int numEq, int outLevel, bool testProduct=false)
Test of LU decomposition.
static double TestComputationalTimesQR_IGLib (int numEq, int outLevel, bool testProduct=false)
Test of QR decomposition, also measures time necessary fo rindividual operations.
static double TestComputationalTimesCholesky_IGLib (int numEq, int outLevel, bool testProduct=false)
Test of Cholesky decomposition, also measures time necessary fo rindividual operations.
static double TestComputationalTimesLU_Base (int numEq, int outLevel, bool testProduct=false)
Test of LU decomposition.
static double TestComputationalTimesCholesky_Base (int numEq, int outLevel, bool testProduct=false)
Test of Cholesky decomposition, also measures time necessary fo rindividual operations.
static double TestComputationalTimesLdlt_Base (int numEq, int outLevel, bool testProduct=false)
Test of Ldlt decomposition, also measures time necessary fo rindividual operations.
static void ExampleMathNetNumericsLU ()
Example of how to use LU decomposition from Math.NET numerics.
static void ExampleMathNetNumericsQR ()
Example of how to use QR decomposition from Math.NET numerics.
static void ExampleMathNetNumericsEVD ()
Example of how to use EVD (eigenvalue decomposition) from Math.NET Numerics.
static void ExampleMathNetNumericsSVD ()
Example of how to use SVD (singular value decomposition) from Math.NET numerics.
static void ExampleMathNetNumericsCholesky ()
Example of how to use Choleski decomposition from Math.NET Numerics.
Detailed Description
Various utilities for testing computational speed of the current system.
$A Igor xx Feb08;
Definition at line 31 of file TestSpeed.cs.
Member Function Documentation
TestComputationalTimesQR() [1/2]
static double IG.Num.SpeedTestCpu.TestComputationalTimesQR (int numEq, int outLevel) inline static
Test of QR decomposition. Writes times necessary for all steps.
Parameters
numEq Number of equations to be solved with decomposition.
Parameters
outLevel Level of output.
Returns
Total time spent for all operations.
Definition at line 41 of file TestSpeed.cs.
References IG.Num.SpeedTestCpu.TestComputationalTimesQR_IGLib().
Referenced by IG.Lib.CommandLineApplicationInterpreter.TestComputationalTimesQR().
TestComputationalTimesQR() [2/2]
static double IG.Num.SpeedTestCpu.TestComputationalTimesQR (int numEq, int outLevel, bool testProduct) inline static
Test of QR decomposition, also measures time necessary fo rindividual operations.
Parameters
outLevel Level of output.
numEq Number of equations to be solved with decomposition.
testProduct If true then it is tested if the product of factors gives the original matrix. Otherwise, this test is skipped.
Returns
Total wallclock time (in seconds) spent for the test.
Definition at line 53 of file TestSpeed.cs.
References IG.Num.SpeedTestCpu.TestComputationalTimesQR_IGLib().
TestComputationalTimesLU() [1/2]
static double IG.Num.SpeedTestCpu.TestComputationalTimesLU (int numEq, int outLevel) inline static
Test of LU decomposition.
Parameters
outLevel Level of output.
numEq Number of equations to be solved with decomposition.
Returns
Total wallclock time (in seconds) spent for the test.
Definition at line 63 of file TestSpeed.cs.
References IG.Num.SpeedTestCpu.TestComputationalTimesLU_IGLib().
Referenced by IG.Lib.CommandLineApplicationInterpreter.TestComputationalTimesLU().
TestComputationalTimesLU() [2/2]
static double IG.Num.SpeedTestCpu.TestComputationalTimesLU (int numEq, int outLevel, bool testProduct) inline static
Test of LU decomposition.
Parameters
outLevel Level of output.
numEq Number of equations to be solved with decomposition.
testProduct If true then it is tested if the product of factors gives the original matrix. Otherwise, this test is skipped.
Returns
Total wallclock time (in seconds) spent for the test.
Definition at line 74 of file TestSpeed.cs.
References IG.Num.SpeedTestCpu.TestComputationalTimesLU_IGLib().
TestComputationalTimesCholesky() [1/2]
static double IG.Num.SpeedTestCpu.TestComputationalTimesCholesky (int numEq, int outLevel) inline static
Test of Cholesky decomposition, also measures time necessary fo rindividual operations.
Parameters
outLevel Level of output.
numEq Number of equations to be solved with decomposition.
Returns
Total wallclock time (in seconds) spent for the test.
Definition at line 84 of file TestSpeed.cs.
References IG.Num.SpeedTestCpu.TestComputationalTimesCholesky_IGLib().
TestComputationalTimesCholesky() [2/2]
static double IG.Num.SpeedTestCpu.TestComputationalTimesCholesky (int numEq, int outLevel, bool testProduct) inline static
Test of Cholesky decomposition, also measures time necessary fo rindividual operations.
Parameters
outLevel Level of output.
numEq Number of equations to be solved with decomposition.
testProduct If true then it is tested if the product of factors gives the original matrix. Otherwise, this test is skipped.
Returns
Total wallclock time (in seconds) spent for the test.
Definition at line 95 of file TestSpeed.cs.
References IG.Num.SpeedTestCpu.TestComputationalTimesCholesky_IGLib().
TestComputationalTimesLU_IGLib()
static double IG.Num.SpeedTestCpu.TestComputationalTimesLU_IGLib (int numEq, int outLevel, bool testProduct = false) inline static
Test of LU decomposition.
Parameters
outLevel Level of output.
numEq Number of equations to be solved with decomposition.
testProduct If true then it is tested if the product of factors gives the original matrix. Otherwise, this test is skipped.
Returns
Total wallclock time (in seconds) spent for the test.
Definition at line 118 of file TestSpeed.cs.
References IG.Num.A, IG.Lib.StopWatch1.CpuTime, IG.Num.LUDecomposition.GetProduct(), IG.Num.MatrixBase.Multiply(), IG.Num.Vector.Random(), IG.Num.Matrix.Random(), IG.Num.LinearSolverBase.Solve(), IG.Lib.StopWatch1.Start(), IG.Lib.StopWatch1.Stop(), IG.Num.VectorBase.Subtract(), IG.Num.MatrixBase.Subtract(), IG.Lib.StopWatch1.Time, IG.Lib.StopWatch1.TotalCpuTime, and IG.Lib.StopWatch1.TotalTime.
Referenced by IG.Num.SpeedTestCpu.TestComputationalTimesLU().
TestComputationalTimesQR_IGLib()
static double IG.Num.SpeedTestCpu.TestComputationalTimesQR_IGLib (int numEq, int outLevel, bool testProduct = false) inline static
Test of QR decomposition, also measures time necessary fo rindividual operations.
Parameters
outLevel Level of output.
numEq Number of equations to be solved with decomposition.
testProduct If true then it is tested if the product of factors gives the original matrix. Otherwise, this test is skipped.
Returns
Total wallclock time (in seconds) spent for the test.
Definition at line 251 of file TestSpeed.cs.
References IG.Num.A, IG.Lib.StopWatch1.CpuTime, IG.Num.QRDecomposition.GetProduct(), IG.Num.MatrixBase.Multiply(), IG.Num.Vector.Random(), IG.Num.Matrix.Random(), IG.Num.LinearSolverBase.Solve(), IG.Lib.StopWatch1.Start(), IG.Lib.StopWatch1.Stop(), IG.Num.VectorBase.Subtract(), IG.Num.MatrixBase.Subtract(), IG.Lib.StopWatch1.Time, IG.Lib.StopWatch1.TotalCpuTime, and IG.Lib.StopWatch1.TotalTime.
Referenced by IG.Num.SpeedTestCpu.TestComputationalTimesQR().
TestComputationalTimesCholesky_IGLib()
static double IG.Num.SpeedTestCpu.TestComputationalTimesCholesky_IGLib (int numEq, int outLevel, bool testProduct = false) inline static
Test of Cholesky decomposition, also measures time necessary fo rindividual operations.
Parameters
outLevel Level of output.
numEq Number of equations to be solved with decomposition.
testProduct If true then it is tested if the product of factors gives the original matrix. Otherwise, this test is skipped.
Returns
Total wallclock time (in seconds) spent for the test.
Definition at line 379 of file TestSpeed.cs.
References IG.Num.A, IG.Lib.StopWatch1.CpuTime, IG.Num.CholeskyDecomposition.GetProduct(), IG.Num.MatrixBase.Multiply(), IG.Num.Vector.Random(), IG.Num.MatrixBase.SetRandomPositiveDiagonallyDominantSymmetric(), IG.Num.LinearSolverBase.Solve(), IG.Lib.StopWatch1.Start(), IG.Lib.StopWatch1.Stop(), IG.Num.VectorBase.Subtract(), IG.Num.MatrixBase.Subtract(), IG.Lib.StopWatch1.Time, IG.Lib.StopWatch1.TotalCpuTime, and IG.Lib.StopWatch1.TotalTime.
Referenced by IG.Num.SpeedTestCpu.TestComputationalTimesCholesky().
TestComputationalTimesLU_Base()
static double IG.Num.SpeedTestCpu.TestComputationalTimesLU_Base (int numEq, int outLevel, bool testProduct = false) inline static
Test of LU decomposition.
Parameters
outLevel Level of output.
numEq Number of equations to be solved with decomposition.
testProduct If true then it is tested if the product of factors gives the original matrix. Otherwise, this test is skipped.
Returns
Total wallclock time (in seconds) spent for the test.
Definition at line 504 of file TestSpeed.cs.
References IG.Num.A, IG.Lib.StopWatch1.CpuTime, IG.Num.MatrixBase.LuDecompose(), IG.Num.MatrixBase.LuExtractLower(), IG.Num.MatrixBase.LuExtractUpper(), IG.Num.MatrixBase.LuSolve(), IG.Num.MatrixBase.Multiply(), IG.Num.Vector.Random(), IG.Num.Matrix.Random(), IG.Lib.StopWatch1.Start(), IG.Lib.StopWatch1.Stop(), IG.Num.VectorBase.Subtract(), IG.Num.MatrixBase.Subtract(), IG.Lib.StopWatch1.Time, IG.Lib.StopWatch1.TotalCpuTime, IG.Lib.StopWatch1.TotalTime, and IG.Num.MatrixBase.UnPermute().
TestComputationalTimesCholesky_Base()
static double IG.Num.SpeedTestCpu.TestComputationalTimesCholesky_Base (int numEq, int outLevel, bool testProduct = false) inline static
Test of Cholesky decomposition, also measures time necessary fo rindividual operations.
Parameters
outLevel Level of output.
numEq Number of equations to be solved with decomposition.
testProduct If true then it is tested if the product of factors gives the original matrix. Otherwise, this test is skipped.
Returns
Total wallclock time (in seconds) spent for the test.
Definition at line 646 of file TestSpeed.cs.
References IG.Num.A, IG.Num.MatrixBase.CholeskyDecompose(), IG.Num.MatrixBase.CholeskyExtractLower(), IG.Num.MatrixBase.CholeskyExtractUpper(), IG.Num.MatrixBase.CholeskySolve(), IG.Lib.StopWatch1.CpuTime, IG.Num.MatrixBase.Multiply(), IG.Num.Vector.Random(), IG.Num.MatrixBase.SetRandomPositiveDiagonallyDominantSymmetric(), IG.Lib.StopWatch1.Start(), IG.Lib.StopWatch1.Stop(), IG.Num.VectorBase.Subtract(), IG.Num.MatrixBase.Subtract(), IG.Lib.StopWatch1.Time, IG.Lib.StopWatch1.TotalCpuTime, and IG.Lib.StopWatch1.TotalTime.
TestComputationalTimesLdlt_Base()
static double IG.Num.SpeedTestCpu.TestComputationalTimesLdlt_Base (int numEq, int outLevel, bool testProduct = false) inline static
Test of Ldlt decomposition, also measures time necessary fo rindividual operations.
Parameters
outLevel Level of output.
numEq Number of equations to be solved with decomposition.
testProduct If true then it is tested if the product of factors gives the original matrix. Otherwise, this test is skipped.
Returns
Total wallclock time (in seconds) spent for the test.
Definition at line 772 of file TestSpeed.cs.
References IG.Num.A, IG.Lib.StopWatch1.CpuTime, IG.Num.MatrixBase.LdltDecompose(), IG.Num.MatrixBase.LdltExtractLower(), IG.Num.MatrixBase.LdltExtractUpper(), IG.Num.MatrixBase.LdltSolve(), IG.Num.MatrixBase.Multiply(), IG.Num.Vector.Random(), IG.Num.MatrixBase.SetRandomPositiveDiagonallyDominantSymmetric(), IG.Lib.StopWatch1.Start(), IG.Lib.StopWatch1.Stop(), IG.Num.VectorBase.Subtract(), IG.Num.MatrixBase.Subtract(), IG.Lib.StopWatch1.Time, IG.Lib.StopWatch1.TotalCpuTime, and IG.Lib.StopWatch1.TotalTime.
ExampleMathNetNumericsLU()
static void IG.Num.SpeedTestCpu.ExampleMathNetNumericsLU () inline static
Example of how to use LU decomposition from Math.NET numerics.
See also:
LU decomposition: http://en.wikipedia.org/wiki/LU_decomposition
Invertible matrix: http://en.wikipedia.org/wiki/Invertible_matrix
Definition at line 904 of file TestSpeed.cs.
ExampleMathNetNumericsQR()
static void IG.Num.SpeedTestCpu.ExampleMathNetNumericsQR () inline static
Example of how to use QR decomposition from Math.NET numerics.
http://en.wikipedia.org/wiki/QR_decomposition QR decomposition
Definition at line 972 of file TestSpeed.cs.
ExampleMathNetNumericsEVD()
static void IG.Num.SpeedTestCpu.ExampleMathNetNumericsEVD () inline static
Example of how to use EVD (eigenvalue decomposition) from Math.NET Numerics.
http://en.wikipedia.org/wiki/Eigenvalue,_eigenvector_and_eigenspace EVD decomposition
Definition at line 1038 of file TestSpeed.cs.
ExampleMathNetNumericsSVD()
static void IG.Num.SpeedTestCpu.ExampleMathNetNumericsSVD () inline static
Example of how to use SVD (singular value decomposition) from Math.NET numerics.
http://en.wikipedia.org/wiki/Singular_value_decomposition SVD decomposition
Definition at line 1160 of file TestSpeed.cs.
ExampleMathNetNumericsCholesky()
static void IG.Num.SpeedTestCpu.ExampleMathNetNumericsCholesky () inline static
Example of how to use Choleski decomposition from Math.NET Numerics.
http://en.wikipedia.org/wiki/Cholesky_decomposition
Definition at line 1276 of file TestSpeed.cs.
The documentation for this class was generated from the following file:
iglib/igbase/numeric/tests/TestSpeed.cs