Doc: IGLib with source files: IG.Num.ScalarFunctionUntransformedBase Class Reference
IG.Num.ScalarFunctionUntransformedBase Class Reference abstract
Base class for defining scalar functions without possibility of affine transformation of parameters.
Public Member Functions
virtual void Evaluate (IScalarFunctionResults data)
Evaluates whatever needs to be evaluated and stores the results on the specified storage object.
abstract double Value (IVector parameters)
Returns the value of this function at the specified parameter.
abstract void GradientPlain (IVector parameters, IVector gradient)
Calculates first order derivatives (gradient) of this function at the specified parameters. WARNING: Plain function, does not check consistency of arguments.
virtual void Gradient (IVector parameters, ref IVector gradient)
Calculates first order derivatives (gradient) of this function at the specified parameters.
abstract void HessianPlain (IVector parameters, IMatrix hessian)
Calculates the second derivative (Hessian matrix) of this function at the specified parameters. WARNING: Plain function, does not check consistency of arguments.
virtual void Hessian (IVector parameters, ref IMatrix hessian)
Calculates the second derivative (Hessian matrix) of this function at the specified parameters.
virtual void NumericalGradientForwardPlain (IVector x, IVector stepSizes, IVector gradient)
Calculates numerical derivatives (gradient) of this function. Forward difference formula is normally used.
void NumericalGradientForward (IVector x, IVector stepSizes, ref IVector gradient)
Calculates numerical derivatives (gradient) of this function. Forward difference formula is normally used.
void NumericalGradientForward (IVector x, double stepSize, ref IVector gradient)
Calculates numerical derivatives (gradient) of this function. Forward difference formula is used.
virtual void NumericalGradientCentralPlain (IVector x, IVector stepSizes, IVector gradient)
Calculates numerical derivatives (gradient) of this function. Forward difference formula is normally used.
void NumericalGradientCentral (IVector x, IVector stepSizes, ref IVector gradient)
Calculates numerical derivatives (gradient) of this function. Forward difference formula is normally used.
void NumericalGradientCentral (IVector x, double stepSize, ref IVector gradient)
Calculates numerical derivatives (gradient) of this function. Forward difference formula is normally used.
virtual void NumericalHessianForwardPlain (IVector x, IVector stepSizes, IVector aux, IMatrix hessian)
Calculates numerical second derivatives (Hessian) of this function. Forward difference formula is normally used. WARNING: Dimensions of vector arguments must match. This function does not check for consistency of argument dimensions. REMARK: Vector x is changed during operation, but is set to initial value before function returns (unless an exception is thrown).
virtual void NumericalHessianForward (IVector x, IVector stepSizes, ref IVector aux, ref IMatrix hessian)
Calculates numerical second derivatives (Hessian) of this function. Forward difference formula is normally used. REMARK: if auxiliary vector or result matrix don't have correct dimensions or they are not allocated, then allocation is performed first. REMARK: Vector x is changed during operation, but is set to initial value before function returns (unless an exception is thrown).
virtual void NumericalHessianForward (IVector x, double stepSize, ref IVector aux, ref IMatrix hessian)
Calculates numerical second derivatives (Hessian) of this function. Forward difference formula is normally used. REMARK: if auxiliary vector or result matrix don't have correct dimensions or they are not allocated, then allocation is performed first. REMARK: Vector x is changed during operation, but is set to initial value before function returns (unless an exception is thrown).
virtual void NumericalHessianCentralPlain (IVector x, IVector stepSizes, IVector aux1, IVector aux2, IMatrix hessian)
Calculates numerical second derivatives (Hessian) of this function. Forward difference formula is normally used. WARNING: Dimensions of vector arguments must match. This function does not check for consistency of argument dimensions. REMARK: Vector x is changed during operation, but is set to initial value before function returns (unless an exception is thrown).
virtual void NumericalHessianCentral (IVector x, IVector stepSizes, ref IVector aux1, ref IVector aux2, ref IMatrix hessian)
Calculates numerical second derivatives (Hessian) of this function. Forward difference formula is normally used. REMARK: if auxiliary vector or result matrix don't have correct dimensions or they are not allocated, then allocation is performed first. REMARK: Vector x is changed during operation, but is set to initial value before function returns (unless an exception is thrown).
virtual void NumericalHessianCentral (IVector x, double stepSize, ref IVector aux1, ref IVector aux2, ref IMatrix hessian)
Calculates numerical second derivatives (Hessian) of this function. Forward difference formula is normally used. REMARK: if auxiliary vector or result matrix don't have correct dimensions or they are not allocated, then allocation is performed first. REMARK: Vector x is changed during operation, but is set to initial value before function returns (unless an exception is thrown).
virtual void NumericalHessianCentralPlain (IVector x, IVector stepSizes, IVector aux1, IVector aux2, IMatrix hessian, bool useAnalyticalGradient)
Calculates numerical second derivatives (Hessian) of this function by the central difference formula. WARNING: Dimensions of vector arguments must match. This function does not check for consistency of argument dimensions. REMARK: Vector x is changed during operation, but is set to initial value before function returns (unless an exception is thrown).
virtual void NumericalHessianCentral (IVector x, IVector stepSizes, ref IVector aux1, ref IVector aux2, ref IMatrix hessian, bool useAnalyticalGradient)
Calculates numerical second derivatives (Hessian) of this function by the central difference formula. REMARK: if auxiliary vector or result matrix don't have correct dimensions or they are not allocated, then allocation is performed first. REMARK: Vector x is changed during operation, but is set to initial value before function returns (unless an exception is thrown).
virtual void NumericalHessianCentral (IVector x, double stepSize, ref IVector aux1, ref IVector aux2, ref IMatrix hessian, bool useAnalyticalGradient)
Calculates numerical second derivatives (Hessian) of this function. Forward difference formula is normally used. REMARK: if auxiliary vector or result matrix don't have correct dimensions or they are not allocated, then allocation is performed first. REMARK: Vector x is changed during operation, but is set to initial value before function returns (unless an exception is thrown).
void TestSpeed (IVector parameters, int numEvaluations, bool randomPerturbations, double relativePerturbationSize, bool calcValue, bool calcGradient, bool calcHessian, bool writeLastResult)
Tests speed of evaluation of the current scalar function and writes results to the console.
void TestGradient (IVector parameters, IVector stepSizes, int stepReductionFactor, int numStepReductions, bool checkNumerical, bool writeErrorComponents, bool writeGradientComponents)
Tests the calculation of gradients of the current scalar function.
void TestGradient (IVector parameters, IVector stepSizes, int stepReductionFactor, int numStepReductions, bool checkNumerical, bool writeErrorComponents, bool writeGradientComponents, bool useCentralDifference)
Tests the calculation of gradients of the current scalar function.
void TestHessian (IVector parameters, IVector stepSizes, int stepReductionFactor, int numStepReductions, bool checkNumerical, bool writeErrorComponents, bool writeHessianComponents)
Tests the calculation of Hessians of the current scalar function.
void TestHessian (IVector parameters, IVector stepSizes, int stepReductionFactor, int numStepReductions, bool checkNumerical, bool writeErrorComponents, bool writeHessianComponents, bool useCentralDifference)
Tests the calculation of Hessians of the current scalar function.
void Test (IVector from, IVector to, int numProbes, IVector stepSizes, double tolerance, bool testDerivatives, bool testSecondDerivatives, bool printDifferences, bool printResults)
Performs numerical tests on the function, with output written to the console. Derivatives and second derivatives are tested and compared to numerical derivatives.
void Test (IVector from, IVector to, int numProbes, IVector stepSizes, double tolerance)
Performs numerical tests on the function, with output written to the console. Derivatives and second derivatives are tested and compared to numerical derivatives. This method tests first and second order derivatives, prints differences between analytical and numerical values to the console, and prints reports where absolute differences exceed rolerance.
void Test (IVector from, IVector to, int numProbes, double stepSize, double tolerance, bool testDerivatives, bool testSecondDerivatives, bool printDifferences, bool printResults)
Performs numerical tests on the function, with output written to the console. Derivatives and second derivatives are tested and compared to numerical derivatives.
void Test (IVector from, IVector to, int numProbes, double stepSize, double tolerance)
Performs numerical tests on the function, with output written to the console. Derivatives and second derivatives are tested and compared to numerical derivatives.
Protected Attributes
string _name
string _description
Properties
virtual string Name [get, set]
Returns a short name of thecurrent function.
virtual string Description [get, set]
Returns a short description of the current function.
abstract bool ValueDefined [get, protected set]
Tells whether value of the function is defined by implementation.
abstract bool GradientDefined [get, protected set]
Tells whether the first derivative is defined for this function (by implementation, not mathematically)
abstract bool HessianDefined [get, protected set]
Tells whether the second derivative is defined for this function (by implementation, not mathematically)
Properties inherited from IG.Num.IScalarFunctionUntransformed
string Name [get]
Returns a short name of the function.
string Description [get]
Returns a short description of the function.
bool ValueDefined [get]
Tells whether value of the function is defined by implementation.
bool GradientDefined [get]
Tells whether the first derivative is defined for this function (by implementation, not mathematically)
bool HessianDefined [get]
Tells whether the second derivative is defined for this function (by implementation, not mathematically)
Detailed Description
Base class for defining scalar functions without possibility of affine transformation of parameters.
More or less all scalar functions should derive from this class.
$A Igor xx May10 Dec10; TODO: implement ICloneable
Definition at line 19 of file FunctionScalarUntransformedBase.cs.
Member Function Documentation
Evaluate()
virtual void IG.Num.ScalarFunctionUntransformedBase.Evaluate (IScalarFunctionResults data) inline virtual
Evaluates whatever needs to be evaluated and stores the results on the specified storage object.
Parameters
data Evaluation data object where results of calculation are stored. It also contains flags taht specify what needs to be calculated, and resulting flags specifying what has been calculated.
Implements IG.Num.IScalarFunctionUntransformed.
Definition at line 60 of file FunctionScalarUntransformedBase.cs.
References IG.Num.IScalarFunctionResults.Calculated, IG.Num.IScalarFunctionResults.CalculatedGradient, IG.Num.IScalarFunctionResults.CalculatedHessian, IG.Num.IScalarFunctionResults.CalculatedValue, IG.Num.IMatrix< ComponentType >.ColumnCount, IG.Num.IScalarFunctionResults.ErrorCode, IG.Num.IScalarFunctionResults.ErrorString, IG.Num.IVector< T >.GetNew(), IG.Num.IVector< T >.GetNewMatrix(), IG.Num.IScalarFunctionResults.Gradient, IG.Num.ScalarFunctionUntransformedBase.Gradient(), IG.Num.ScalarFunctionUntransformedBase.GradientDefined, IG.Num.IScalarFunctionResults.Hessian, IG.Num.ScalarFunctionUntransformedBase.Hessian(), IG.Num.ScalarFunctionUntransformedBase.HessianDefined, IG.Num.IVector< T >.Length, IG.Num.ScalarFunctionUntransformedBase.Name, IG.Num.IScalarFunctionResults.Parameters, IG.Num.IScalarFunctionResults.ReqGradient, IG.Num.IScalarFunctionResults.ReqHessian, IG.Num.IScalarFunctionResults.ReqValue, IG.Num.IMatrix< ComponentType >.RowCount, IG.Num.IScalarFunctionResults.SetGradientReference(), IG.Num.IScalarFunctionResults.SetHessianReference(), IG.Num.IScalarFunctionResults.Value, IG.Num.ScalarFunctionUntransformedBase.Value(), and IG.Num.ScalarFunctionUntransformedBase.ValueDefined.
Value()
abstract double IG.Num.ScalarFunctionUntransformedBase.Value (IVector parameters) pure virtual
Returns the value of this function at the specified parameter.
Implements IG.Num.IScalarFunctionUntransformed.
Implemented in IG.Num.ScalarFunctionRadialUntransformed, IG.Num.ScalarFunctionBase, IG.Num.ScalarFunctionQuadratic, IG.Num.Func3dBase, IG.Num.ScalarFunctionLinear, IG.Num.Func2dBase, and IG.Num.ScalarFunctionConstant.
Referenced by IG.Num.ScalarFunctionUntransformedBase.Evaluate(), IG.Num.ScalarFunctionUntransformedBase.NumericalGradientCentralPlain(), IG.Num.ScalarFunctionUntransformedBase.NumericalGradientForwardPlain(), IG.Num.ScalarFunctionUntransformedBase.NumericalHessianForwardPlain(), and IG.Num.ScalarFunctionUntransformedBase.TestSpeed().
GradientPlain()
abstract void IG.Num.ScalarFunctionUntransformedBase.GradientPlain (IVector parameters, IVector gradient) pure virtual
Calculates first order derivatives (gradient) of this function at the specified parameters. WARNING: Plain function, does not check consistency of arguments.
Parameters
parameters Vector of parameters where derivatives are evaluated.
gradient Vector where first order derivatives (the gradient) are stored.
Implements IG.Num.IScalarFunctionUntransformed.
Implemented in IG.Num.ScalarFunctionRadialUntransformed, IG.Num.ScalarFunctionBase, IG.Num.ScalarFunctionQuadratic, IG.Num.Func3dBase, IG.Num.ScalarFunctionLinear, IG.Num.Func2dBase, and IG.Num.ScalarFunctionConstant.
Referenced by IG.Num.ScalarFunctionUntransformedBase.Gradient(), and IG.Num.ScalarFunctionUntransformedBase.NumericalHessianCentralPlain().
Gradient()
virtual void IG.Num.ScalarFunctionUntransformedBase.Gradient (IVector parameters, ref IVector gradient) inline virtual
Calculates first order derivatives (gradient) of this function at the specified parameters.
Parameters
parameters Vector of parameters where derivatives are evaluated.
gradient Vector where first order derivatives (gradient) are stored. Passed by reference.
Implements IG.Num.IScalarFunctionUntransformed.
Definition at line 194 of file FunctionScalarUntransformedBase.cs.
References IG.Num.IVector< T >.GetNew(), IG.Num.ScalarFunctionUntransformedBase.GradientPlain(), IG.Num.IVector< T >.Length, and IG.Num.ScalarFunctionUntransformedBase.Name.
Referenced by IG.Num.ScalarFunctionUntransformedBase.Evaluate(), IG.Lib.ScalarFunctionLoader.Example(), IG.Num.ScalarFunctionUntransformedBase.Test(), IG.Num.ScalarFunctionUntransformedBase.TestGradient(), and IG.Num.ScalarFunctionUntransformedBase.TestSpeed().
HessianPlain()
abstract void IG.Num.ScalarFunctionUntransformedBase.HessianPlain (IVector parameters, IMatrix hessian) pure virtual
Calculates the second derivative (Hessian matrix) of this function at the specified parameters. WARNING: Plain function, does not check consistency of arguments.
Parameters
parameters Vector of parameters where derivatives are evaluated.
hessian Matrix where second derivatives (Hessian matrix) are stored.
Implements IG.Num.IScalarFunctionUntransformed.
Implemented in IG.Num.ScalarFunctionRadialUntransformed, IG.Num.ScalarFunctionBase, IG.Num.ScalarFunctionQuadratic, IG.Num.Func3dBase, IG.Num.ScalarFunctionLinear, IG.Num.Func2dBase, and IG.Num.ScalarFunctionConstant.
Referenced by IG.Num.ScalarFunctionUntransformedBase.Hessian().
Hessian()
virtual void IG.Num.ScalarFunctionUntransformedBase.Hessian (IVector parameters, ref IMatrix hessian) inline virtual
Calculates the second derivative (Hessian matrix) of this function at the specified parameters.
Parameters
parameters Vector of parameters where derivatives are evaluated.
hessian Matrix where second derivatives (Hessian matrix) are stored. Passed by reference.
Implements IG.Num.IScalarFunctionUntransformed.
Definition at line 218 of file FunctionScalarUntransformedBase.cs.
References IG.Num.IVector< T >.GetNewMatrix(), IG.Num.ScalarFunctionUntransformedBase.HessianPlain(), IG.Num.IVector< T >.Length, and IG.Num.ScalarFunctionUntransformedBase.Name.
Referenced by IG.Num.ScalarFunctionUntransformedBase.Evaluate(), IG.Lib.ScalarFunctionLoader.Example(), IG.Num.ScalarFunctionUntransformedBase.Test(), IG.Num.ScalarFunctionUntransformedBase.TestHessian(), and IG.Num.ScalarFunctionUntransformedBase.TestSpeed().
NumericalGradientForwardPlain()
virtual void IG.Num.ScalarFunctionUntransformedBase.NumericalGradientForwardPlain (IVector x, IVector stepSizes, IVector gradient) inline virtual
Calculates numerical derivatives (gradient) of this function. Forward difference formula is normally used.
WARNING: Dimensions of vector arguments must match. This function does not check for consistency of argument dimensions.
REMARK: Vector x is changed during operation, but is set to initial value before function returns (unless an exception is thrown).
Parameters
x Point at which derivative is calculated.
stepSizes Step size for numerical differentiation.
gradient Vector where calculated derivatives (function gradient) are stored.
Definition at line 250 of file FunctionScalarUntransformedBase.cs.
References IG.Num.IVector< T >.Length, IG.Num.ScalarFunctionUntransformedBase.Name, IG.Num.ScalarFunctionUntransformedBase.Value(), and IG.Num.ScalarFunctionUntransformedBase.ValueDefined.
Referenced by IG.Num.ScalarFunctionUntransformedBase.NumericalGradientForward().
NumericalGradientForward() [1/2]
void IG.Num.ScalarFunctionUntransformedBase.NumericalGradientForward (IVector x, IVector stepSizes, ref IVector gradient) inline
Calculates numerical derivatives (gradient) of this function. Forward difference formula is normally used.
If result vector doesn't have correct dimensions or it is not allocated, then allocation is performed first.
Vector x is changed during operation, but is set to initial value before function returns (unless an exception is thrown).
Parameters
x Point (vector of parameters) at which gradient is calculated.
stepSizes Step sizes for numerical differentiation.
gradient Vector where the calculated gradient is stored.
Definition at line 274 of file FunctionScalarUntransformedBase.cs.
References IG.Num.IVector< T >.GetNew(), IG.Num.IVector< T >.Length, IG.Num.ScalarFunctionUntransformedBase.Name, and IG.Num.ScalarFunctionUntransformedBase.NumericalGradientForwardPlain().
Referenced by IG.Num.ScalarFunctionUntransformedBase.NumericalGradientForward(), IG.Num.ScalarFunctionUntransformedBase.Test(), and IG.Num.ScalarFunctionUntransformedBase.TestGradient().
NumericalGradientForward() [2/2]
void IG.Num.ScalarFunctionUntransformedBase.NumericalGradientForward (IVector x, double stepSize, ref IVector gradient) inline
Calculates numerical derivatives (gradient) of this function. Forward difference formula is used.
Warning: This method internally allocates a new vector where step sizes are stored.
If result vector doesn't have correct dimensions or it is not allocated, then allocation is performed first.
Vector x is changed during operation, but is set to initial value before function returns (unless an exception is thrown).
Parameters
x Point (vector of parameters) at which gradient is calculated.
stepSize Step size for numerical differentiation (the same in all directions).
gradient Vector where the calculated gradient is stored.
TODO: When NumericalDerivativePlain is tested enough, replace this function in sulch a way that stepSize is used directly in a copy of that function (currently a vetor of step sizes is created where each component holds the same step size.)
Definition at line 300 of file FunctionScalarUntransformedBase.cs.
References IG.Num.IVector< T >.GetNew(), IG.Num.IVector< T >.Length, and IG.Num.ScalarFunctionUntransformedBase.NumericalGradientForward().
NumericalGradientCentralPlain()
virtual void IG.Num.ScalarFunctionUntransformedBase.NumericalGradientCentralPlain (IVector x, IVector stepSizes, IVector gradient) inline virtual
Calculates numerical derivatives (gradient) of this function. Forward difference formula is normally used.
Warning: Dimensions of vector arguments must match. This function does not check for consistency of argument dimensions.
Remark: Vector x is changed during operation, but is set to initial value before function returns (unless an exception is thrown).
Parameters
x Point at which derivative is calculated.
stepSizes Step size for numerical differentiation.
gradient Vector where calculated derivatives (function gradient) are stored.
Definition at line 318 of file FunctionScalarUntransformedBase.cs.
References IG.Num.IVector< T >.Length, IG.Num.ScalarFunctionUntransformedBase.Name, IG.Num.ScalarFunctionUntransformedBase.Value(), and IG.Num.ScalarFunctionUntransformedBase.ValueDefined.
Referenced by IG.Num.ScalarFunctionUntransformedBase.NumericalGradientCentral(), and IG.Num.ScalarFunctionUntransformedBase.NumericalHessianCentralPlain().
NumericalGradientCentral() [1/2]
void IG.Num.ScalarFunctionUntransformedBase.NumericalGradientCentral (IVector x, IVector stepSizes, ref IVector gradient) inline
Calculates numerical derivatives (gradient) of this function. Forward difference formula is normally used.
If result vector doesn't have correct dimensions or it is not allocated, then allocation is performed first.
Vector x is changed during operation, but is set to initial value before function returns (unless an exception is thrown).
Parameters
x Point (vector of parameters) at which gradient is calculated.
stepSizes Step sizes for numerical differentiation.
gradient Vector where the calculated gradient is stored.
Definition at line 345 of file FunctionScalarUntransformedBase.cs.
References IG.Num.IVector< T >.GetNew(), IG.Num.IVector< T >.Length, IG.Num.ScalarFunctionUntransformedBase.Name, and IG.Num.ScalarFunctionUntransformedBase.NumericalGradientCentralPlain().
Referenced by IG.Num.ScalarFunctionUntransformedBase.NumericalGradientCentral(), and IG.Num.ScalarFunctionUntransformedBase.TestGradient().
NumericalGradientCentral() [2/2]
void IG.Num.ScalarFunctionUntransformedBase.NumericalGradientCentral (IVector x, double stepSize, ref IVector gradient) inline
Calculates numerical derivatives (gradient) of this function. Forward difference formula is normally used.
Warning: This method internally allocates a new vector where step sizes are stored.
If the result vector doesn't have correct dimensions or it is not allocated, then allocation is performed first.
Vector x is changed during operation, but is set to initial value before function returns (unless an exception is thrown).
Parameters
x Point (vector of parameters) at which gradient is calculated.
stepSize Step size for numerical differentiation (the same in all directions).
gradient Vector where the calculated gradient is stored.
TODO: When NumericalDerivativePlain is tested enough, replace this function in sulch a way that stepSize is used directly in a copy of that function (currently a vetor of step sizes is created where each component holds the same step size.)
Definition at line 371 of file FunctionScalarUntransformedBase.cs.
References IG.Num.IVector< T >.GetNew(), IG.Num.IVector< T >.Length, and IG.Num.ScalarFunctionUntransformedBase.NumericalGradientCentral().
NumericalHessianForwardPlain()
virtual void IG.Num.ScalarFunctionUntransformedBase.NumericalHessianForwardPlain (IVector x, IVector stepSizes, IVector aux, IMatrix hessian) inline virtual
Calculates numerical second derivatives (Hessian) of this function. Forward difference formula is normally used. WARNING: Dimensions of vector arguments must match. This function does not check for consistency of argument dimensions. REMARK: Vector x is changed during operation, but is set to initial value before function returns (unless an exception is thrown).
Parameters
x Point (vector of parameters) at which derivative is calculated.
aux Auxiliary storage vector, must be of the same dimension as vector of parameters.
stepSizes Step size for numerical differentiation.
hessian Matrix where calculated second derivatives (function Hessian) are stored.
Definition at line 388 of file FunctionScalarUntransformedBase.cs.
References IG.Num.IVector< T >.Length, IG.Num.ScalarFunctionUntransformedBase.Name, IG.Num.ScalarFunctionUntransformedBase.Value(), and IG.Num.ScalarFunctionUntransformedBase.ValueDefined.
Referenced by IG.Num.ScalarFunctionUntransformedBase.NumericalHessianForward().
NumericalHessianForward() [1/2]
virtual void IG.Num.ScalarFunctionUntransformedBase.NumericalHessianForward (IVector x, IVector stepSizes, ref IVector aux, ref IMatrix hessian) inline virtual
Calculates numerical second derivatives (Hessian) of this function. Forward difference formula is normally used. REMARK: if auxiliary vector or result matrix don't have correct dimensions or they are not allocated, then allocation is performed first. REMARK: Vector x is changed during operation, but is set to initial value before function returns (unless an exception is thrown).
Parameters
x Point (vector of parameters) at which derivative is calculated.
aux Auxiliary storage vector, must be of the same dimension as vector of parameters.
stepSizes Step size for numerical differentiation.
hessian Matrix where calculated second derivatives (function Hessian) are stored.
Definition at line 445 of file FunctionScalarUntransformedBase.cs.
References IG.Num.IVector< T >.GetNew(), IG.Num.IVector< T >.GetNewMatrix(), IG.Num.IVector< T >.Length, IG.Num.ScalarFunctionUntransformedBase.Name, and IG.Num.ScalarFunctionUntransformedBase.NumericalHessianForwardPlain().
Referenced by IG.Num.ScalarFunctionUntransformedBase.NumericalHessianForward(), IG.Num.ScalarFunctionUntransformedBase.Test(), and IG.Num.ScalarFunctionUntransformedBase.TestHessian().
NumericalHessianForward() [2/2]
virtual void IG.Num.ScalarFunctionUntransformedBase.NumericalHessianForward (IVector x, double stepSize, ref IVector aux, ref IMatrix hessian) inline virtual
Calculates numerical second derivatives (Hessian) of this function. Forward difference formula is normally used. REMARK: if auxiliary vector or result matrix don't have correct dimensions or they are not allocated, then allocation is performed first. REMARK: Vector x is changed during operation, but is set to initial value before function returns (unless an exception is thrown).
Parameters
x Point (vector of parameters) at which derivative is calculated.
aux Auxiliary storage vector, must be of the same dimension as vector of parameters.
stepSize Step size for numerical differentiation (the same in all directions).
hessian Matrix where calculated second derivatives (function Hessian) are stored.
TODO: When NumericalSecondDerivativePlain is tested enough, replace this function in sulch a way that stepSize is used directly in a copy of that function (currently a vetor of step sizes is created where each component holds the same step size.)
Definition at line 474 of file FunctionScalarUntransformedBase.cs.
References IG.Num.IVector< T >.GetNew(), IG.Num.IVector< T >.Length, and IG.Num.ScalarFunctionUntransformedBase.NumericalHessianForward().
NumericalHessianCentralPlain() [1/2]
virtual void IG.Num.ScalarFunctionUntransformedBase.NumericalHessianCentralPlain (IVector x, IVector stepSizes, IVector aux1, IVector aux2, IMatrix hessian) inline virtual
Calculates numerical second derivatives (Hessian) of this function. Forward difference formula is normally used. WARNING: Dimensions of vector arguments must match. This function does not check for consistency of argument dimensions. REMARK: Vector x is changed during operation, but is set to initial value before function returns (unless an exception is thrown).
Parameters
x Point (vector of parameters) at which derivative is calculated.
aux1 Auxiliary storage vector, must be of the same dimension as vector of parameters.
aux2 Another auxiliary storage vector, must be of the same dimension as vector of parameters.
stepSizes Step size for numerical differentiation.
hessian Matrix where calculated second derivatives (function Hessian) are stored.
Definition at line 492 of file FunctionScalarUntransformedBase.cs.
Referenced by IG.Num.ScalarFunctionUntransformedBase.NumericalHessianCentral().
NumericalHessianCentral() [1/4]
virtual void IG.Num.ScalarFunctionUntransformedBase.NumericalHessianCentral (IVector x, IVector stepSizes, ref IVector aux1, ref IVector aux2, ref IMatrix hessian) inline virtual
Calculates numerical second derivatives (Hessian) of this function. Forward difference formula is normally used. REMARK: if auxiliary vector or result matrix don't have correct dimensions or they are not allocated, then allocation is performed first. REMARK: Vector x is changed during operation, but is set to initial value before function returns (unless an exception is thrown).
Parameters
x Point (vector of parameters) at which derivative is calculated.
aux1 Auxiliary storage vector, must be of the same dimension as vector of parameters.
aux2 Another auxiliary storage vector, must be of the same dimension as vector of parameters.
stepSizes Step size for numerical differentiation.
hessian Matrix where calculated second derivatives (function Hessian) are stored.
Definition at line 507 of file FunctionScalarUntransformedBase.cs.
References IG.Num.IVector< T >.GetNew(), IG.Num.IVector< T >.GetNewMatrix(), IG.Num.IVector< T >.Length, IG.Num.ScalarFunctionUntransformedBase.Name, and IG.Num.ScalarFunctionUntransformedBase.NumericalHessianCentralPlain().
Referenced by IG.Num.ScalarFunctionUntransformedBase.NumericalHessianCentral(), and IG.Num.ScalarFunctionUntransformedBase.TestHessian().
NumericalHessianCentral() [2/4]
virtual void IG.Num.ScalarFunctionUntransformedBase.NumericalHessianCentral (IVector x, double stepSize, ref IVector aux1, ref IVector aux2, ref IMatrix hessian) inline virtual
Calculates numerical second derivatives (Hessian) of this function. Forward difference formula is normally used. REMARK: if auxiliary vector or result matrix don't have correct dimensions or they are not allocated, then allocation is performed first. REMARK: Vector x is changed during operation, but is set to initial value before function returns (unless an exception is thrown).
Parameters
x Point (vector of parameters) at which derivative is calculated.
stepSize Step sizes for numerical differentiation.
aux1 Auxiliary storage vector, must be of the same dimension as vector of parameters.
aux2 The secont auxiliary storage vector, must be of the same dimension as vector of parameters.
hessian Matrix where calculated second derivatives (function Hessian) are stored.
TODO: When NumericalSecondDerivativePlain is tested enough, replace this function in sulch a way that stepSize is used directly in a copy of that function (currently a vetor of step sizes is created where each component holds the same step size.)
Definition at line 542 of file FunctionScalarUntransformedBase.cs.
References IG.Num.IVector< T >.GetNew(), IG.Num.IVector< T >.Length, and IG.Num.ScalarFunctionUntransformedBase.NumericalHessianCentral().
NumericalHessianCentralPlain() [2/2]
virtual void IG.Num.ScalarFunctionUntransformedBase.NumericalHessianCentralPlain (IVector x, IVector stepSizes, IVector aux1, IVector aux2, IMatrix hessian, bool useAnalyticalGradient) inline virtual
Calculates numerical second derivatives (Hessian) of this function by the central difference formula. WARNING: Dimensions of vector arguments must match. This function does not check for consistency of argument dimensions. REMARK: Vector x is changed during operation, but is set to initial value before function returns (unless an exception is thrown).
Parameters
x Point (vector of parameters) at which derivative is calculated.
aux1 Auxiliary storage vector, must be of the same dimension as vector of parameters.
aux2 Another auxiliary storage vector, must be of the same dimension as vector of parameters.
stepSizes Step size for numerical differentiation.
hessian Matrix where calculated second derivatives (function Hessian) are stored.
useAnalyticalGradient If true then analytical gradient are used when provided by the current function.
Definition at line 562 of file FunctionScalarUntransformedBase.cs.
References IG.Num.ScalarFunctionUntransformedBase.GradientDefined, IG.Num.ScalarFunctionUntransformedBase.GradientPlain(), IG.Num.IVector< T >.Length, IG.Num.ScalarFunctionUntransformedBase.Name, IG.Num.ScalarFunctionUntransformedBase.NumericalGradientCentralPlain(), and IG.Num.ScalarFunctionUntransformedBase.ValueDefined.
NumericalHessianCentral() [3/4]
virtual void IG.Num.ScalarFunctionUntransformedBase.NumericalHessianCentral (IVector x, IVector stepSizes, ref IVector aux1, ref IVector aux2, ref IMatrix hessian, bool useAnalyticalGradient) inline virtual
Calculates numerical second derivatives (Hessian) of this function by the central difference formula. REMARK: if auxiliary vector or result matrix don't have correct dimensions or they are not allocated, then allocation is performed first. REMARK: Vector x is changed during operation, but is set to initial value before function returns (unless an exception is thrown).
Parameters
x Point (vector of parameters) at which derivative is calculated.
aux1 Auxiliary storage vector, must be of the same dimension as vector of parameters.
aux2 Another auxiliary storage vector, must be of the same dimension as vector of parameters.
stepSizes Step size for numerical differentiation.
hessian Matrix where calculated second derivatives (function Hessian) are stored.
useAnalyticalGradient If true then analytical gradient are used when provided by the current function.
Definition at line 602 of file FunctionScalarUntransformedBase.cs.
References IG.Num.IVector< T >.GetNew(), IG.Num.IVector< T >.GetNewMatrix(), IG.Num.IVector< T >.Length, IG.Num.ScalarFunctionUntransformedBase.Name, and IG.Num.ScalarFunctionUntransformedBase.NumericalHessianCentralPlain().
NumericalHessianCentral() [4/4]
virtual void IG.Num.ScalarFunctionUntransformedBase.NumericalHessianCentral (IVector x, double stepSize, ref IVector aux1, ref IVector aux2, ref IMatrix hessian, bool useAnalyticalGradient) inline virtual
Calculates numerical second derivatives (Hessian) of this function. Forward difference formula is normally used. REMARK: if auxiliary vector or result matrix don't have correct dimensions or they are not allocated, then allocation is performed first. REMARK: Vector x is changed during operation, but is set to initial value before function returns (unless an exception is thrown).
Parameters
x Point (vector of parameters) at which derivative is calculated.
stepSize Step sizes for numerical differentiation.
aux1 Auxiliary storage vector, must be of the same dimension as vector of parameters.
aux2 The second auxiliary storage vector, must be of the same dimension as vector of parameters.
hessian Matrix where calculated second derivatives (function Hessian) are stored.
useAnalyticalGradient If true then analytical gradient are used when provided by the current function.
TODO: When NumericalSecondDerivativePlain is tested enough, replace this function in sulch a way that stepSize is used directly in a copy of that function (currently a vetor of step sizes is created where each component holds the same step size.)
Definition at line 640 of file FunctionScalarUntransformedBase.cs.
References IG.Num.IVector< T >.GetNew(), IG.Num.IVector< T >.Length, and IG.Num.ScalarFunctionUntransformedBase.NumericalHessianCentral().
TestSpeed()
void IG.Num.ScalarFunctionUntransformedBase.TestSpeed (IVector parameters, int numEvaluations, bool randomPerturbations, double relativePerturbationSize, bool calcValue, bool calcGradient, bool calcHessian, bool writeLastResult) inline
Tests speed of evaluation of the current scalar function and writes results to the console.
Parameters
parameters Central value of parameters at which function value, gradient and/or Hessian is evaluated.
numEvaluations Number of evaluations performed.
randomPerturbations Whether to use random perturbations or not.
relativePerturbationSize Relative size of random perturbations, when used.
calcValue Whether function value is calculated.
calcGradient Whether function gradient is calculated.
calcHessian Whether function Hessian is calculated.
writeLastResult Whether results of the last calculation are written to console.
The specified number of function values, gradients and/or Hessians is evaluated, and time of evaluation is reported (with average time for a single evaluation also reported).
Definition at line 666 of file FunctionScalarUntransformedBase.cs.
References IG.Num.ScalarFunctionUntransformedBase.Description, IG.Num.RandomGenerator.Global, IG.Num.ScalarFunctionUntransformedBase.Gradient(), IG.Num.ScalarFunctionUntransformedBase.GradientDefined, IG.Num.ScalarFunctionUntransformedBase.Hessian(), IG.Num.ScalarFunctionUntransformedBase.HessianDefined, IG.Num.IVector< T >.Length, IG.Num.VectorBase.Multiply(), IG.Num.ScalarFunctionUntransformedBase.Name, IG.Num.IRandomGenerator.NextDouble(), IG.Lib.StopWatch1.Start(), IG.Num.IVector< T >.ToString(), IG.Num.IMatrix< ComponentType >.ToString(), IG.Lib.StopWatch1.TotalCpuTime, IG.Lib.StopWatch1.TotalTime, IG.Num.ScalarFunctionUntransformedBase.Value(), and IG.Num.ScalarFunctionUntransformedBase.ValueDefined.
TestGradient() [1/2]
void IG.Num.ScalarFunctionUntransformedBase.TestGradient (IVector parameters, IVector stepSizes, int stepReductionFactor, int numStepReductions, bool checkNumerical, bool writeErrorComponents, bool writeGradientComponents) inline
Tests the calculation of gradients of the current scalar function.
Differentiation is performed according to the central difference formula.
Calculations of numerical and analytical gradients can be verified.
Numerical gradients can be calculated at different step szes that are iteratively reduced by the specified integer factor, which gives indication of precision.
Parameters
parameters Vector of parameters at which function gradient is calculated.
stepSizes Vector of initial step sizes used for function differentiation.
stepReductionFactor Factor greater than 1 by which step size is reduced at each iteration.
numStepReductions Number of step size reductions.
checkNumerical Whether check is also made only on basis of numerical values.
writeErrorComponents Whether gradient errors (and differences between results at different step sizes in the case of pure numerical check) in component-wise form are also written to the console (if fallse, only norms are written).
writeGradientComponents Whether gradients (calculated and analytical) are written in component-wise form.
Definition at line 772 of file FunctionScalarUntransformedBase.cs.
TestGradient() [2/2]
void IG.Num.ScalarFunctionUntransformedBase.TestGradient (IVector parameters, IVector stepSizes, int stepReductionFactor, int numStepReductions, bool checkNumerical, bool writeErrorComponents, bool writeGradientComponents, bool useCentralDifference) inline
Tests the calculation of gradients of the current scalar function.
Calculations of numerical and analytical gradients can be verified.
Numerical gradients can be calculated at different step szes that are iteratively reduced by the specified integer factor, which gives indication of precision.
Parameters
parameters Vector of parameters at which function gradient is calculated.
stepSizes Vector of initial step sizes used for function differentiation.
stepReductionFactor Factor greater than 1 by which step size is reduced at each iteration.
numStepReductions Number of step size reductions.
checkNumerical Whether check is also made only on basis of numerical values.
writeErrorComponents Whether gradient errors (and differences between results at different step sizes in the case of pure numerical check) in component-wise form are also written to the console (if fallse, only norms are written).
writeGradientComponents Whether gradients (calculated and analytical) are written in component-wise form.
useCentralDifference Whether the more precise but also more time consuming central difference scheme is used for numerical differentiation.
Definition at line 795 of file FunctionScalarUntransformedBase.cs.
References IG.Num.ScalarFunctionUntransformedBase.Description, IG.Num.IVector< T >.GetCopy(), IG.Num.ScalarFunctionUntransformedBase.Gradient(), IG.Num.ScalarFunctionUntransformedBase.GradientDefined, IG.Num.IVector< T >.Length, IG.Num.VectorBase.Multiply(), IG.Num.ScalarFunctionUntransformedBase.Name, IG.Num.ScalarFunctionUntransformedBase.NumericalGradientCentral(), IG.Num.ScalarFunctionUntransformedBase.NumericalGradientForward(), IG.Num.IVector< T >.SetConstant(), IG.Num.VectorBase.Subtract(), and IG.Num.IVector< T >.ToString().
TestHessian() [1/2]
void IG.Num.ScalarFunctionUntransformedBase.TestHessian (IVector parameters, IVector stepSizes, int stepReductionFactor, int numStepReductions, bool checkNumerical, bool writeErrorComponents, bool writeHessianComponents) inline
Tests the calculation of Hessians of the current scalar function.
Calculations of numerical and analytical Hessians can be verified.
Numerical Hessians can be calculated at different step szes that are iteratively reduced by the specified integer factor, which gives indication of precision.
Parameters
parameters Vector of parameters at which function Hessian is calculated.
stepSizes Vector of initial step sizes used for function differentiation.
stepReductionFactor Factor greater than 1 by which step size is reduced at each iteration.
numStepReductions Number of step size reductions.
checkNumerical Whether check is also made only on basis of numerical values.
writeErrorComponents Whether Hessian errors (and differences between results at different step sizes in the case of pure numerical check) in component-wise form are also written to the console (if fallse, only norms are written).
writeHessianComponents Whether Hessians (calculated and analytical) are written in component-wise form.
Definition at line 969 of file FunctionScalarUntransformedBase.cs.
TestHessian() [2/2]
void IG.Num.ScalarFunctionUntransformedBase.TestHessian (IVector parameters, IVector stepSizes, int stepReductionFactor, int numStepReductions, bool checkNumerical, bool writeErrorComponents, bool writeHessianComponents, bool useCentralDifference) inline
Tests the calculation of Hessians of the current scalar function.
Calculations of numerical and analytical Hessians can be verified.
Numerical Hessians can be calculated at different step szes that are iteratively reduced by the specified integer factor, which gives indication of precision.
Parameters
parameters Vector of parameters at which function Hessian is calculated.
stepSizes Vector of initial step sizes used for function differentiation.
stepReductionFactor Factor greater than 1 by which step size is reduced at each iteration.
numStepReductions Number of step size reductions.
checkNumerical Whether check is also made only on basis of numerical values.
writeErrorComponents Whether Hessian errors (and differences between results at different step sizes in the case of pure numerical check) in component-wise form are also written to the console (if fallse, only norms are written).
writeHessianComponents Whether Hessians (calculated and analytical) are written in component-wise form.
useCentralDifference Whether the central difference formula is used for numerial differentiation.
Definition at line 992 of file FunctionScalarUntransformedBase.cs.
References IG.Num.ScalarFunctionUntransformedBase.Description, IG.Num.IVector< T >.GetCopy(), IG.Num.ScalarFunctionUntransformedBase.Hessian(), IG.Num.ScalarFunctionUntransformedBase.HessianDefined, IG.Num.IVector< T >.Length, IG.Num.VectorBase.Multiply(), IG.Num.ScalarFunctionUntransformedBase.Name, IG.Num.ScalarFunctionUntransformedBase.NumericalHessianCentral(), IG.Num.ScalarFunctionUntransformedBase.NumericalHessianForward(), IG.Num.IMatrix< ComponentType >.SetConstant(), IG.Num.MatrixBase.Subtract(), IG.Num.IVector< T >.ToString(), and IG.Num.IMatrix< ComponentType >.ToString().
Test() [1/4]
void IG.Num.ScalarFunctionUntransformedBase.Test (IVector from, IVector to, int numProbes, IVector stepSizes, double tolerance, bool testDerivatives, bool testSecondDerivatives, bool printDifferences, bool printResults) inline
Performs numerical tests on the function, with output written to the console. Derivatives and second derivatives are tested and compared to numerical derivatives.
Parameters
from Initial parameters on which tests are performed.
to Final parameters on which tests are performed.
numProbes Number of points on which tests are performed. Points are linearly distributed between from and to.
stepSizes Step sizes for numerical differentiation.
tolerance Absolute tolerance for match between numerical and analytical values.
testDerivatives Specifies whether first order derivatives should be tested.
testSecondDerivatives Specifies whether second order derivatives should be tested.
printDifferences Specifies whether differences between numerical and analytical derivatives should be printed.
printResults Specifies whether results should be printed.
Definition at line 1168 of file FunctionScalarUntransformedBase.cs.
References IG.Num.VectorBase.Add(), IG.Num.VectorBase.Copy(), IG.Num.VectorBase.Divide(), IG.Num.IVector< T >.GetNew(), IG.Num.ScalarFunctionUntransformedBase.Gradient(), IG.Num.ScalarFunctionUntransformedBase.GradientDefined, IG.Num.ScalarFunctionUntransformedBase.Hessian(), IG.Num.ScalarFunctionUntransformedBase.HessianDefined, IG.Num.IVector< T >.Length, IG.Num.VectorBase.Multiply(), IG.Num.ScalarFunctionUntransformedBase.Name, IG.Num.ScalarFunctionUntransformedBase.NumericalGradientForward(), IG.Num.ScalarFunctionUntransformedBase.NumericalHessianForward(), IG.Num.VectorBase.Subtract(), and IG.Num.MatrixBase.Subtract().
Referenced by IG.Num.ScalarFunctionUntransformedBase.Test().
Test() [2/4]
void IG.Num.ScalarFunctionUntransformedBase.Test (IVector from, IVector to, int numProbes, IVector stepSizes, double tolerance) inline
Performs numerical tests on the function, with output written to the console. Derivatives and second derivatives are tested and compared to numerical derivatives. This method tests first and second order derivatives, prints differences between analytical and numerical values to the console, and prints reports where absolute differences exceed rolerance.
Parameters
from Initial parameters on which tests are performed.
to Final parameters on which tests are performed.
numProbes Number of points on which tests are performed. Points are linearly distributed between from and to.
stepSizes Step sizes for numerical differentiation.
tolerance Absolute tolerance for match between numerical and analytical values.
Definition at line 1311 of file FunctionScalarUntransformedBase.cs.
References IG.Num.ScalarFunctionUntransformedBase.Test().
Test() [3/4]
void IG.Num.ScalarFunctionUntransformedBase.Test (IVector from, IVector to, int numProbes, double stepSize, double tolerance, bool testDerivatives, bool testSecondDerivatives, bool printDifferences, bool printResults) inline
Performs numerical tests on the function, with output written to the console. Derivatives and second derivatives are tested and compared to numerical derivatives.
Parameters
from Initial parameters on which tests are performed.
to Final parameters on which tests are performed.
numProbes Number of points on which tests are performed. Points are linearly distributed between from and to.
stepSize Step size for numerical differentiation (the same in all directions).
tolerance Absolute tolerance for match between numerical and analytical values.
testDerivatives Specifies whether first order derivatives should be tested.
testSecondDerivatives Specifies whether second order derivatives should be tested.
printDifferences Specifies whether differences between numerical and analytical derivatives should be printed.
printResults Specifies whether results should be printed.
Definition at line 1329 of file FunctionScalarUntransformedBase.cs.
References IG.Num.IVector< T >.GetNew(), IG.Num.IVector< T >.Length, and IG.Num.ScalarFunctionUntransformedBase.Test().
Test() [4/4]
void IG.Num.ScalarFunctionUntransformedBase.Test (IVector from, IVector to, int numProbes, double stepSize, double tolerance) inline
Performs numerical tests on the function, with output written to the console. Derivatives and second derivatives are tested and compared to numerical derivatives.
Parameters
from Initial parameters on which tests are performed.
to Final parameters on which tests are performed.
numProbes Number of points on which tests are performed. Points are linearly distributed between from and to.
stepSize Step size for numerical differentiation (the same in all directions).
tolerance Absolute tolerance for match between numerical and analytical values.
Definition at line 1346 of file FunctionScalarUntransformedBase.cs.
References IG.Num.ScalarFunctionUntransformedBase.Test().
Member Data Documentation
_name
string IG.Num.ScalarFunctionUntransformedBase._name protected
Definition at line 24 of file FunctionScalarUntransformedBase.cs.
Referenced by IG.Num.ScalarFunctionTransformed.SetName().
_description
string IG.Num.ScalarFunctionUntransformedBase._description protected
Definition at line 26 of file FunctionScalarUntransformedBase.cs.
Referenced by IG.Num.ScalarFunctionTransformed.SetDescription().
Property Documentation
Name
virtual string IG.Num.ScalarFunctionUntransformedBase.Name get set
Returns a short name of thecurrent function.
Definition at line 31 of file FunctionScalarUntransformedBase.cs.
Referenced by IG.Num.ScalarFunctionUntransformedBase.Evaluate(), IG.Num.ScalarFunctionUntransformedBase.Gradient(), IG.Num.ScalarFunctionUntransformedBase.Hessian(), IG.Num.ScalarFunctionUntransformedBase.NumericalGradientCentral(), IG.Num.ScalarFunctionUntransformedBase.NumericalGradientCentralPlain(), IG.Num.ScalarFunctionUntransformedBase.NumericalGradientForward(), IG.Num.ScalarFunctionUntransformedBase.NumericalGradientForwardPlain(), IG.Num.ScalarFunctionUntransformedBase.NumericalHessianCentral(), IG.Num.ScalarFunctionUntransformedBase.NumericalHessianCentralPlain(), IG.Num.ScalarFunctionUntransformedBase.NumericalHessianForward(), IG.Num.ScalarFunctionUntransformedBase.NumericalHessianForwardPlain(), IG.Num.ScalarFunctionUntransformedBase.Test(), IG.Num.ScalarFunctionUntransformedBase.TestGradient(), IG.Num.ScalarFunctionUntransformedBase.TestHessian(), and IG.Num.ScalarFunctionUntransformedBase.TestSpeed().
Description
virtual string IG.Num.ScalarFunctionUntransformedBase.Description get set
Returns a short description of the current function.
Definition at line 43 of file FunctionScalarUntransformedBase.cs.
Referenced by IG.Num.ScalarFunctionUntransformedBase.TestGradient(), IG.Num.ScalarFunctionUntransformedBase.TestHessian(), and IG.Num.ScalarFunctionUntransformedBase.TestSpeed().
ValueDefined
abstract bool IG.Num.ScalarFunctionUntransformedBase.ValueDefined get protected set
Tells whether value of the function is defined by implementation.
Definition at line 183 of file FunctionScalarUntransformedBase.cs.
Referenced by IG.Num.ScalarFunctionUntransformedBase.Evaluate(), IG.Num.ScalarFunctionUntransformedBase.NumericalGradientCentralPlain(), IG.Num.ScalarFunctionUntransformedBase.NumericalGradientForwardPlain(), IG.Num.ScalarFunctionUntransformedBase.NumericalHessianCentralPlain(), IG.Num.ScalarFunctionUntransformedBase.NumericalHessianForwardPlain(), and IG.Num.ScalarFunctionUntransformedBase.TestSpeed().
GradientDefined
abstract bool IG.Num.ScalarFunctionUntransformedBase.GradientDefined get protected set
Tells whether the first derivative is defined for this function (by implementation, not mathematically)
Definition at line 206 of file FunctionScalarUntransformedBase.cs.
Referenced by IG.Num.ScalarFunctionUntransformedBase.Evaluate(), IG.Num.ScalarFunctionUntransformedBase.NumericalHessianCentralPlain(), IG.Num.ScalarFunctionUntransformedBase.Test(), IG.Num.ScalarFunctionUntransformedBase.TestGradient(), and IG.Num.ScalarFunctionUntransformedBase.TestSpeed().
HessianDefined
abstract bool IG.Num.ScalarFunctionUntransformedBase.HessianDefined get protected set
Tells whether the second derivative is defined for this function (by implementation, not mathematically)
Definition at line 230 of file FunctionScalarUntransformedBase.cs.
Referenced by IG.Num.ScalarFunctionUntransformedBase.Evaluate(), IG.Num.ScalarFunctionUntransformedBase.Test(), IG.Num.ScalarFunctionUntransformedBase.TestHessian(), and IG.Num.ScalarFunctionUntransformedBase.TestSpeed().
The documentation for this class was generated from the following file:
iglib/igbase/numeric/FunctionScalarUntransformedBase.cs