Doc: IGLib with source files: IG.Lib.ExpressionEvaluatorJs Class Reference
IG.Lib.ExpressionEvaluatorJs Class Reference
JavaScript Evaluator with command-line interpreter.
Public Member Functions
ExpressionEvaluatorJs ()
Initializes a new JavaScript evaluator. This includes compiling the JavaScript code where evaluation is plugged in.
override void RepairCommand (ref string command)
Repairs the specified command and returns the repaired command string.
void Register ()
Registers the current object. Subsequent calls (after the first one) have no effect.
bool IsRegistered ()
Returns true if the current object is registered, false if not.
void Unregister ()
Unregisters the current object if it is currently registered. Can be performed several times, in this case only the first call may have effect.
Public Member Functions inherited from IG.Lib.ExpressionEvaluatorCompiled
ExpressionEvaluatorCompiled ()
Initializes ID and calls the main initialization method (which will typically be overridden in every subclass).
virtual object EvalToObject (string code)
Evaluates JavaScript code and returns result as object.
virtual int EvalToInteger (string code)
Evaluates (interprets) JavaScript code and returns integer result of evaluation. Code must be such that result of evaluation can be interpreted as integer.
virtual double EvalToDouble (string code)
Evaluates (interprets) JavaScript code and returns double result of evaluation. Code must be such that result of evaluation can be interpreted as double.
virtual string EvalToString (string code)
Evaluates (interprets) JavaScript code and returns string result of evaluation. Code must be such that result of evaluation can be interpreted as string.
string GetRepairedCommand (string command)
Repairs the specified command and returns the repaired command string.
virtual string Execute (string inputCode)
Executes the specified code and returns the result. Throws exception if errors occur when interpreting code. After execution, the code is appended to the complete code that has been executed up to this point.
virtual string Compile (string inputDefinitions)
Recompiles the basic script where evaluation is plugged in, with added definitions. Throws exceptions if errors occur when compiling code. After execution, user definitions are added to the base script if compilatin is successful, so that they can be used in subsequent evaluations of code.
void Reset ()
Resets the code evaluator (clears variable definitions, etc.).
virtual void PrintHelpCommandLine ()
Prints help for the command-line JavaScript interpreter to the standard output.
virtual void PrintDefinitions ()
Prints all definitions (preinstalled and user defined).
virtual void PrintCompleteCode ()
Prints the complete code that has been input up to now to the console.
virtual void SaveCompleteCode (string filePath, bool append)
Prints the complete code inserter up to this moment.
virtual void UserSaveCompleteCode (bool append)
Saves or appends the complete code evaluated up to now to a file specified by the user. User is promped for the file to which code is saved.
virtual void SaveUserDefinitions (string filePath, bool append)
Saves or appends to the specified file all valid user definitions added to the evaluator up to this point.
virtual void UserSaveUserDefinitions (bool append)
Saves or appends the all valid user definitions added to the evaluator up to this point. User is promped for the file to which definitions are saved.
virtual void CommandLine ()
Command-line utility where user can successively enter JavaScrit expressions or general portions of code, and evaluates them. Displays prompt to instruct the user, and result of operations.
Public Member Functions inherited from IG.Lib.IRegisterable< ExpressionEvaluatorJs >
void Register ()
Registers the current object. Subsequent calls (after the first one) have no effect.
bool IsRegistered ()
Returns true if the current object is registered, false if not.
void Unregister ()
Unregisters the current object if it is currently registered. Can be performed several times, in this case only the first call may have effect.
Static Public Member Functions
static void ExampleCommandLine ()
Launches command-line JavaScript interpreter.
Public Attributes
string BaseDefinitionsJsAdditional
Protected Member Functions
override void InitExpressionEvaluator ()
Contains initializations for the particular class.
Protected Member Functions inherited from IG.Lib.ExpressionEvaluatorCompiled
virtual string CompileBase ()
Compiles the base script where evaluation is plugged in, and loads the generated assembly and necessary objects.
virtual string CompileBase (string inputDefinitions)
Compiles the base script where evaluation is plugged in, and loads the generated assembly and necessary objects.
virtual string ExecuteUser (string command)
Executes the code, prints results and reports eventual errors. Also appends the code to the complete valid code that has been interpreted up to now.
virtual string CompileUser (string inputDefinitions)
Compiles the specified new definitions. If compilation is successful, the definitions are added to existing definitinos and user is notified through console. Otherwise, error is reported on console.
virtual string ExecuteUser (ref string inpDefinitions, ref string inpCode)
Compiles definitions, if any specified, and executes code, if any specified. Eventual results and errors are reported in console. After execution, code and definitions are set to null.
Protected Attributes
string _baseDefinitionsJs
string _baseDefinitionsJsExtended
Protected Attributes inherited from IG.Lib.ExpressionEvaluatorCompiled
int _outputLevel = DefaultOutputLevel
Default level of output for some of the interpreters' functionality (e.g. asynchronous command execution).
string _language = "unknown"
string _packageName = "Evaluator"
string _className = "EvaluatorClass"
string _evaluationFunctionName = "Eval"
string _inputMark = "Calc> "
char _multiLineCharacter = '\\'
string _commandLineHead
string _commandLineStopNote
string _helpCommandLineHeading
string _helpCommandLine
Static Protected Attributes
static ExpressionEvaluatorJs _evaluatorGlobal = null
Properties
override string BaseDefinitions [get, protected set]
A set of pre-defined definitions that can be used in the evaluated code.
override string ScriptBase [get]
Container for compiled code that evaluates JavaScript expressions.
ObjectRegister< ExpressionEvaluatorJs > ObjectRegister [get]
Gets object register where the current object is registered.
static ExpressionEvaluatorJs Global [get, protected set]
Global JavaScript expression evaluator. Initialized on first use.
Properties inherited from IG.Lib.ExpressionEvaluatorCompiled
int Id [get]
Returns object's Id that is unique within a given type.
int OutputLevel [get, set]
Level of output for some of the interpreter's functionality (e.g. asynchronous command execution).
object Lock [get]
Used for locking internal fields.
virtual string Language [get, protected set]
Programming language in use.
virtual string PackageName [get, protected set]
Name of the JavaScript package in which evaluated code is executed.
virtual string ClassName [get, protected set]
Name of the JavaScript class that is compiled to execute the evaluated code.
virtual string EvaluationFunctionName [get, protected set]
Name of the function used for evaluation of expressions.
virtual string BaseDefinitions [get, protected set]
A set of pre-defined definitions that can be used in the evaluated code.
string CompleteCode [get, protected set]
All valid user code inserted up to this point. Only code that compiled and executed without errors is taken into account.
virtual string UserDefinitions [get, protected set]
A set of definitions inserted by users.
virtual string NewUserDefinitions [get, set]
New user definitions that are added temporarily for testing.
virtual string Definitions [get]
All definitions (pre-defined and user-defined) that can be used in the evaluated code.
abstract string ScriptBase [get]
Container for interpreted code.
virtual string HelpCommandLine [get]
Returns textual help for JavaScript command-line interpreter.
Properties inherited from IG.Lib.ILockable
object Lock [get]
Properties inherited from IG.Lib.IIdentifiable
int Id [get]
Returns unique ID (in the scope of a given type) of the current object.
Properties inherited from IG.Lib.IRegisterable< ExpressionEvaluatorJs >
ObjectRegister< T > ObjectRegister [get]
Gets the object register where the current object can be registered.
Static Private Attributes
static ObjectRegister< ExpressionEvaluatorJs > _register
Static object that providees object register and generates IDs for this class:
static object _globalLock = new object()
Additional Inherited Members
Static Public Attributes inherited from IG.Lib.ExpressionEvaluatorCompiled
static int DefaultOutputLevel = 0
Detailed Description
JavaScript Evaluator with command-line interpreter.
$A Igor Aug10;
Definition at line 30 of file ExpressionEvaluatorJs.cs.
Constructor & Destructor Documentation
ExpressionEvaluatorJs()
IG.Lib.ExpressionEvaluatorJs.ExpressionEvaluatorJs () inline
Initializes a new JavaScript evaluator. This includes compiling the JavaScript code where evaluation is plugged in.
Definition at line 38 of file ExpressionEvaluatorJs.cs.
Member Function Documentation
InitExpressionEvaluator()
override void IG.Lib.ExpressionEvaluatorJs.InitExpressionEvaluator () inline protected virtual
Contains initializations for the particular class.
This method is called form base class' constructor.
Implements IG.Lib.ExpressionEvaluatorCompiled.
Definition at line 44 of file ExpressionEvaluatorJs.cs.
References IG.Lib.ExpressionEvaluatorCompiled._commandLineHead, IG.Lib.ExpressionEvaluatorCompiled._commandLineStopNote, IG.Lib.ExpressionEvaluatorCompiled._definitionsMark, IG.Lib.ExpressionEvaluatorCompiled._helpCommandLineHeading, IG.Lib.ExpressionEvaluatorCompiled._inputMark, IG.Lib.ExpressionEvaluatorCompiled._multilineMark, IG.Lib.ExpressionEvaluatorCompiled._resultMark, IG.Lib.ExpressionEvaluatorCompiled.ClassName, IG.Lib.ExpressionEvaluatorCompiled.CompileBase(), IG.Lib.IIdentifiable.Id, IG.Lib.ExpressionEvaluatorCompiled.Language, IG.Lib.ExpressionEvaluatorCompiled.PackageName, and IG.Lib.ExpressionEvaluatorJs.Register().
RepairCommand()
override void IG.Lib.ExpressionEvaluatorJs.RepairCommand (ref string command) inline virtual
Repairs the specified command and returns the repaired command string.
Reparations serve for easier insertion of commands and for addition of syntactic cookies.
Parameters
command Command to be repaired.
Reimplemented from IG.Lib.ExpressionEvaluatorCompiled.
Definition at line 405 of file ExpressionEvaluatorJs.cs.
Register()
void IG.Lib.ExpressionEvaluatorJs.Register () inline
Registers the current object. Subsequent calls (after the first one) have no effect.
Definition at line 467 of file ExpressionEvaluatorJs.cs.
References IG.Lib.ExpressionEvaluatorJs._register.
Referenced by IG.Lib.ExpressionEvaluatorJs.InitExpressionEvaluator().
IsRegistered()
bool IG.Lib.ExpressionEvaluatorJs.IsRegistered () inline
Returns true if the current object is registered, false if not.
Returns
Definition at line 472 of file ExpressionEvaluatorJs.cs.
References IG.Lib.ExpressionEvaluatorJs._register.
Unregister()
void IG.Lib.ExpressionEvaluatorJs.Unregister () inline
Unregisters the current object if it is currently registered. Can be performed several times, in this case only the first call may have effect.
Definition at line 477 of file ExpressionEvaluatorJs.cs.
References IG.Lib.ExpressionEvaluatorJs._register, and IG.Lib.IIdentifiable.Id.
ExampleCommandLine()
static void IG.Lib.ExpressionEvaluatorJs.ExampleCommandLine () inline static
Launches command-line JavaScript interpreter.
Definition at line 519 of file ExpressionEvaluatorJs.cs.
References IG.Lib.ExpressionEvaluatorCompiled.CommandLine(), and IG.Lib.ExpressionEvaluatorJs.Global.
Member Data Documentation
_baseDefinitionsJs
string IG.Lib.ExpressionEvaluatorJs._baseDefinitionsJs protected
Definition at line 87 of file ExpressionEvaluatorJs.cs.
Referenced by IG.Lib.ExpressionEvaluatorJint.InitExpressionEvaluator().
BaseDefinitionsJsAdditional
string IG.Lib.ExpressionEvaluatorJs.BaseDefinitionsJsAdditional
Definition at line 181 of file ExpressionEvaluatorJs.cs.
_baseDefinitionsJsExtended
string IG.Lib.ExpressionEvaluatorJs._baseDefinitionsJsExtended protected
Initial value:
= @"
     // ARRAY UTILITIES:
     //Check if an object is an array or not.
     function isarray(obj) {
        //returns true is it is an array
        if (obj.constructor.toString().indexOf(""Array"") == -1)
        return false;
        else
        return true;
    }
"
Definition at line 338 of file ExpressionEvaluatorJs.cs.
_register
ObjectRegister<ExpressionEvaluatorJs> IG.Lib.ExpressionEvaluatorJs._register static private
Initial value:
=
            new ObjectRegister<ExpressionEvaluatorJs>(1 )
Static object that providees object register and generates IDs for this class:
Definition at line 458 of file ExpressionEvaluatorJs.cs.
Referenced by IG.Lib.ExpressionEvaluatorJs.IsRegistered(), IG.Lib.ExpressionEvaluatorJs.Register(), and IG.Lib.ExpressionEvaluatorJs.Unregister().
_evaluatorGlobal
ExpressionEvaluatorJs IG.Lib.ExpressionEvaluatorJs._evaluatorGlobal = null static protected
Definition at line 485 of file ExpressionEvaluatorJs.cs.
_globalLock
object IG.Lib.ExpressionEvaluatorJs._globalLock = new object() static private
Definition at line 487 of file ExpressionEvaluatorJs.cs.
Property Documentation
BaseDefinitions
override string IG.Lib.ExpressionEvaluatorJs.BaseDefinitions get protected set
A set of pre-defined definitions that can be used in the evaluated code.
Definition at line 358 of file ExpressionEvaluatorJs.cs.
ScriptBase
override string IG.Lib.ExpressionEvaluatorJs.ScriptBase get protected
Container for compiled code that evaluates JavaScript expressions.
Definition at line 370 of file ExpressionEvaluatorJs.cs.
ObjectRegister
ObjectRegister<ExpressionEvaluatorJs> IG.Lib.ExpressionEvaluatorJs.ObjectRegister get
Gets object register where the current object is registered.
Definition at line 463 of file ExpressionEvaluatorJs.cs.
Global
ExpressionEvaluatorJs IG.Lib.ExpressionEvaluatorJs.Global static get protected set
Global JavaScript expression evaluator. Initialized on first use.
In many applications you will not need more than one evaluator and you can just use this instance.
Definition at line 494 of file ExpressionEvaluatorJs.cs.
Referenced by IG.Lib.ExpressionEvaluatorJs.ExampleCommandLine().
The documentation for this class was generated from the following file:
iglib/igbase/interpreters/ExpressionEvaluatorJs.cs