Doc: IGLib with source files: IG.Num.LUDecomposition Class Reference
IG.Num.LUDecomposition Class Reference
LU decomposition of a matrix.
Public Member Functions
LUDecomposition (Matrix_MathNetNumerics A)
Constructor.
LUDecomposition (Matrix A)
Constructor.
void GetProduct (ref IMatrix product)
Calculates the product (i.e. the original matrix of coefficients of a linear system of equations) of the current decomposition, and stores it to the specified matrix.
IMatrix GetProduct ()
Calculates and returns the product (i.e. the original matrix of coefficients of a linear system of equations) of the current decomposition.
void Inverse (ref IMatrix inv)
Calculates inverse of the decomposed matrix represented by the current object, and stores it in the specified matrix.
IMatrix Inverse ()
Calculates and returns inverse of the decomposed matrix represented by the current object.
Public Member Functions inherited from IG.Num.LinearSolverBase
virtual void Solve (IMatrix B, ref IMatrix X)
Solves A*X = B (a set of linear systems of equations), where B is the matrix whose colums are right-hand sides of equations to be solved. Solutions are stored to the specified matrix.
IMatrix Solve (IMatrix B)
Solves A*X = B (a set of linear systems of equations), where B is the matrix whose colums are right-hand sides of equations to be solved, and returns a matrix whose columns are solutions of the specified systems of equations.
virtual void Solve (IVector b, ref IVector x)
Solves a system of linear equations A*x=b, and stores the solution in the specified vector.
IVector Solve (IVector b)
Solves a system of linear equations A*x=b, and returns the solution.
Public Member Functions inherited from IG.Num.ILinearSolver
void Solve (IMatrix B, ref IMatrix X)
Solves A*X = B (a set of linear systems of equations), where B is the matrix whose colums are right-hand sides of equations to be solved. Solutions are stored to the specified matrix.
IMatrix Solve (IMatrix B)
Solves A*X = B (a set of linear systems of equations), where B is the matrix whose colums are right-hand sides of equations to be solved, and returns a matrix whose columns are solutions of the specified systems of equations.
void Solve (IVector b, ref IVector x)
Solves a system of linear equations A*x=b, and stores the solution in the specified vector.
IVector Solve (IVector b)
Solves a system of linear equations A*x=b, and returns the solution.
Protected Member Functions
override MatrixBase_MathNetNumerics SolveMathNetNumerics (IMatrix righthandSides)
Solves systems of linear equations with the specified right-hand sides and the current matrix decomposition by using the Math.Net Numerics library, and returns the result in Math.Net matrix form.
override VectorBase_MathNetNumerics SolveMathNetNumerics (IVector rightHandSides)
Solves the system of linear equations with the specified right-hand sides and the current matrix decomposition by using the Math.Net Numerics library, and returns the result in Math.Net matrix form.
Protected Attributes
int[] _pivot
double _determinant
bool _determinantCalculated = false
Protected Attributes inherited from IG.Num.LinearSolverBase
MatrixBase_MathNetNumerics _matrixSolution_MathNetNumerics
Matrix_MathNetNumerics _matrixRighthandSides_MathNetNumerics
VectorBase_MathNetNumerics _vectorSolution_MathNetNumerics
Vector_MathNetNumerics _vectorRighthandSides_MathNetNumerics
IVector auxB = null
IVector auxX = null
Properties
bool IsNonSingular [get]
Indicates whether the matrix of coefficients of a linear system is nonsingular.
Matrix L [get]
Returns the lower triangular factor.
Matrix U [get]
Returns the upper triangular factor.
int[] Pivot [get]
Returns the integer pivot permutation vector of LU decomposition.
double Determinant [get]
Returns the determinant.
Properties inherited from IG.Num.LinearSolverBase
object Lock [get]
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
Properties inherited from IG.Num.ILinearSolver
bool IsNonSingular [get]
Indicates whether the matrix of coefficients of a linear system represented by the current decomposition object, is nonsingular.
Properties inherited from IG.Lib.ILockable
object Lock [get]
Detailed Description
LU decomposition of a matrix.
Objects of this class are immutable. Decomposition is calculated at initialization, and the decomposed matrix can not be replaced later.
For an m-by-n matrix A with m >= n, the LU decomposition is an m-by-n unit lower triangular matrix L, an n-by-n upper triangular matrix U, and a permutation vector pivot of length m so that A(piv,:) = L*U. If m < n, then L is m-by-m and U is m-by-n. The LU decomposition with pivoting always exists, even if the matrix is singular, so the constructor will never fail. The primary use of the LU decomposition is in the solution of square systems of simultaneous linear equations. This will fail if IsNonSingular() returns false.
$A Igor Nov08 Apr12;
Definition at line 329 of file MatrixDecompositions.cs.
Constructor & Destructor Documentation
LUDecomposition() [1/2]
IG.Num.LUDecomposition.LUDecomposition (Matrix_MathNetNumerics A) inline
Constructor.
Parameters
A Matrix to be decomposed.
Definition at line 338 of file MatrixDecompositions.cs.
References IG.Num.LinearSolverBase._columnCount, IG.Num.A, and IG.Lib.Base.
LUDecomposition() [2/2]
IG.Num.LUDecomposition.LUDecomposition (Matrix A) inline
Constructor.
Parameters
A Matrix to be decomposed.
Definition at line 351 of file MatrixDecompositions.cs.
References IG.Num.A.
Member Function Documentation
GetProduct() [1/2]
void IG.Num.LUDecomposition.GetProduct (ref IMatrix product) inline
Calculates the product (i.e. the original matrix of coefficients of a linear system of equations) of the current decomposition, and stores it to the specified matrix.
Parameters
product Matrix where re-calculated product of the decomposed matrix is stored.
Implements IG.Num.ILinearSolver.
Definition at line 421 of file MatrixDecompositions.cs.
References IG.Lib.Base, and IG.Num.Matrix.Copy().
Referenced by IG.Num.SpeedTestCpu.TestComputationalTimesLU_IGLib().
GetProduct() [2/2]
IMatrix IG.Num.LUDecomposition.GetProduct () inline
Calculates and returns the product (i.e. the original matrix of coefficients of a linear system of equations) of the current decomposition.
Implements IG.Num.ILinearSolver.
Definition at line 431 of file MatrixDecompositions.cs.
Inverse() [1/2]
void IG.Num.LUDecomposition.Inverse (ref IMatrix inv) inline
Calculates inverse of the decomposed matrix represented by the current object, and stores it in the specified matrix.
Parameters
inv Matrix where calculated inverse is stored.
Implements IG.Num.ILinearSolver.
Definition at line 466 of file MatrixDecompositions.cs.
References IG.Lib.Base, and IG.Num.Matrix.Copy().
Inverse() [2/2]
IMatrix IG.Num.LUDecomposition.Inverse () inline
Calculates and returns inverse of the decomposed matrix represented by the current object.
Implements IG.Num.ILinearSolver.
Definition at line 475 of file MatrixDecompositions.cs.
SolveMathNetNumerics() [1/2]
override MatrixBase_MathNetNumerics IG.Num.LUDecomposition.SolveMathNetNumerics (IMatrix righthandSides) inline protected virtual
Solves systems of linear equations with the specified right-hand sides and the current matrix decomposition by using the Math.Net Numerics library, and returns the result in Math.Net matrix form.
Parameters
righthandSides Matrix that contains right-hand sides of the linear equations to be solved as its columns.
Returns
The Math.Net Numerics matrix whose columns contains solutions to the systems of linear equations whose right-hand sides are specified by yhe righthandSides parameter.
Reimplemented from IG.Num.LinearSolverBase.
Definition at line 489 of file MatrixDecompositions.cs.
References IG.Num.LinearSolverBase._matrixRighthandSides_MathNetNumerics, IG.Num.LinearSolverBase._matrixSolution_MathNetNumerics, IG.Lib.Base, IG.Num.IMatrix< ComponentType >.ColumnCount, IG.Num.Matrix.Copy(), IG.Lib.ILockable.Lock, and IG.Num.IMatrix< ComponentType >.RowCount.
SolveMathNetNumerics() [2/2]
override VectorBase_MathNetNumerics IG.Num.LUDecomposition.SolveMathNetNumerics (IVector rightHandSides) inline protected virtual
Solves the system of linear equations with the specified right-hand sides and the current matrix decomposition by using the Math.Net Numerics library, and returns the result in Math.Net matrix form.
Parameters
rightHandSides Vector of right-hand sides of the linear equations to be solved.
Returns
The Math.Net Numerics vector whose columns contains solutions to the systems of linear equations whose right-hand sides are specified by yhe rightHandSides parameter.
Reimplemented from IG.Num.LinearSolverBase.
Definition at line 514 of file MatrixDecompositions.cs.
References IG.Num.LinearSolverBase._vectorRighthandSides_MathNetNumerics, IG.Num.LinearSolverBase._vectorSolution_MathNetNumerics, IG.Lib.Base, IG.Num.VectorBase.Copy(), IG.Num.IVector< T >.Length, and IG.Lib.ILockable.Lock.
Member Data Documentation
_pivot
int [] IG.Num.LUDecomposition._pivot protected
Definition at line 393 of file MatrixDecompositions.cs.
_determinant
double IG.Num.LUDecomposition._determinant protected
Definition at line 438 of file MatrixDecompositions.cs.
_determinantCalculated
bool IG.Num.LUDecomposition._determinantCalculated = false protected
Definition at line 440 of file MatrixDecompositions.cs.
Property Documentation
IsNonSingular
bool IG.Num.LUDecomposition.IsNonSingular get
Indicates whether the matrix of coefficients of a linear system is nonsingular.
Returns
true if U, and hence A, is nonsingular.
Definition at line 361 of file MatrixDecompositions.cs.
L
Matrix IG.Num.LUDecomposition.L get
Returns the lower triangular factor.
Definition at line 372 of file MatrixDecompositions.cs.
U
Matrix IG.Num.LUDecomposition.U get
Returns the upper triangular factor.
Definition at line 384 of file MatrixDecompositions.cs.
Pivot
int [] IG.Num.LUDecomposition.Pivot get
Returns the integer pivot permutation vector of LU decomposition.
Definition at line 397 of file MatrixDecompositions.cs.
Determinant
double IG.Num.LUDecomposition.Determinant get
Returns the determinant.
Returns
det(A)
Exceptions
System.ArgumentException Matrix must be square.
Definition at line 446 of file MatrixDecompositions.cs.
The documentation for this class was generated from the following file:
iglib/igbase/numeric/MatrixDecompositions.cs