Doc: IGLib with source files: LearnCs.Lib.ComplexVector Class Reference
LearnCs.Lib.ComplexVector Class Reference
Vector whose elements are of type double.
Public Member Functions
ComplexVector ()
Only to support serialization / deserialization.
ComplexVector (int dim)
ComplexVector (Complex[] elements, bool copyElements)
ComplexVector (params Complex[] elements)
override ComplexVector CreateVector (int dim)
Static Public Member Functions
static implicit operator ComplexVector (double[] array)
Converts array of double (double[]) to a complex vector (ComplexVector).
static implicit operator ComplexVector ((double, double)[] array)
Converts array of 2-tuples of double ((double, double)[]) to a complex vector (ComplexVector).
static implicit operator ComplexVector (double[][] array)
Converts array of arrays of double (double[][]) to a complex vector (ComplexVector).
Properties
override INumberOperations< Complex > NumberOperations = NumberOperationsComplex.Instance [get]
This property can now be implemented because the concrete type of elements is known.
Detailed Description
Vector whose elements are of type double.
See: https://en.wikipedia.org/wiki/Euclidean_vector
https://en.wikipedia.org/wiki/Vector_(mathematics_and_physics)
Definition at line 14 of file ComplexVector.cs.
Constructor & Destructor Documentation
ComplexVector() [1/4]
LearnCs.Lib.ComplexVector.ComplexVector () inline
Only to support serialization / deserialization.
Definition at line 23 of file ComplexVector.cs.
Referenced by LearnCs.Lib.ComplexVector.CreateVector(), and LearnCs.Lib.ComplexVector.operator ComplexVector().
ComplexVector() [2/4]
LearnCs.Lib.ComplexVector.ComplexVector (int dim) inline
Definition at line 26 of file ComplexVector.cs.
ComplexVector() [3/4]
LearnCs.Lib.ComplexVector.ComplexVector (Complex[] elements, bool copyElements) inline
Definition at line 29 of file ComplexVector.cs.
ComplexVector() [4/4]
LearnCs.Lib.ComplexVector.ComplexVector (params Complex[] elements) inline
Definition at line 32 of file ComplexVector.cs.
Member Function Documentation
operator ComplexVector() [1/3]
static implicit LearnCs.Lib.ComplexVector.operator ComplexVector (double[] array) inline static
Converts array of double (double[]) to a complex vector (ComplexVector).
Each component of the array is converted to a complex number via implicit conversion from double to Complex.
Parameters
array
Definition at line 44 of file ComplexVector.cs.
References LearnCs.Lib.ComplexVector.ComplexVector().
operator ComplexVector() [2/3]
static implicit LearnCs.Lib.ComplexVector.operator ComplexVector ((double, double)[] array) inline static
Converts array of 2-tuples of double ((double, double)[]) to a complex vector (ComplexVector).
Each component of the array is a 2-tuple (double, double), which is converted to a complex number via implicit conversion.
Parameters
array
Definition at line 59 of file ComplexVector.cs.
References LearnCs.Lib.ComplexVector.ComplexVector().
operator ComplexVector() [3/3]
static implicit LearnCs.Lib.ComplexVector.operator ComplexVector (double array[][]) inline static
Converts array of arrays of double (double[][]) to a complex vector (ComplexVector).
Each component of the outer one-dimensional array is again a 1D array, which is converted to a complex number, thus it must have at most 2 elements (for real and imaginary part), but can have less or be null (see in Complex the operator Complex(double[]).
Parameters
array Array of arrays , each of which represents a complex number, and should not have mroe than 2 elements.
Definition at line 74 of file ComplexVector.cs.
References LearnCs.Lib.ComplexVector.ComplexVector().
CreateVector()
override ComplexVector LearnCs.Lib.ComplexVector.CreateVector (int dim) inline
Definition at line 120 of file ComplexVector.cs.
References LearnCs.Lib.ComplexVector.ComplexVector().
Property Documentation
NumberOperations
override INumberOperations<Complex> LearnCs.Lib.ComplexVector.NumberOperations = NumberOperationsComplex.Instance get protected
This property can now be implemented because the concrete type of elements is known.
Definition at line 91 of file ComplexVector.cs.
The documentation for this class was generated from the following file:
IGLibCore/tests/IGLib.TestBase/SampleClasses/ComplexVector.cs