Doc: IGLib with source files: IG.Num.OptFileManager Class Reference
IG.Num.OptFileManager Class Reference
Performs elementary operations for optimization and analysis servers and clients that exchange data and messages through files. Each such server can serve a single request at a time (single thread of execution). Client-server pair (or pairs, when both analysis and optimization are performed in this way) has (or have) a single directory for exchanging data and messages. If there is a need for analyses running in parallel, each thread must have its own directory and its own client-server pair.
Public Member Functions
OptFileManager (string directoryPath)
Creates a new optimization file server manager.
string GetPath (string relativePath)
Returns full path of the file or directory with the specified relative path within the data and messages exchange directory.
bool LockFileMutexCheckAbandoned ()
Check whether the filesystem locking mutex (property LockFileMutex) has been abandoned, and returns true if it has been (otherwise, false is returned).
virtual bool IsAnInputReady ()
Gets a flag telling whether analysis input data is ready.
virtual void WaitAnInputReady ()
Waits until analysis data is ready. REMARK: Currently this file just checks existence of the file in a loop. This should be changed in the future because it is not the best solution.
virtual void ClearAnInputReady ()
Clears the analysis data ready flag.
virtual void SetAnInputReady ()
Sets the analysis input ready flag.
virtual bool IsAnResultsReady ()
Gets a flag telling whether analysis output data is ready.
virtual void WaitAnResultsReady ()
Waits until analysis data is ready. REMARK: Currently this file just checks existence of the file in a loop. This should be changed in the future because it is not the best solution.
virtual void ClearAnResultsReady ()
Clears the analysis results ready flag.
virtual void SetAnResultsReady ()
Sets the analysis results ready flag.
virtual bool IsAnBusy ()
Gets a flag telling whether direct analysis is busy.
virtual void WaitAnReady ()
Waits until analysis is ready. REMARK: Currently this file just checks existence of the file in a loop. This should be changed in the future because it is not the best solution.
virtual void ClearAnBusy ()
Clears the analysis busy flag.
virtual void SetAnBusy ()
Sets the analysis busy flag.
void ClearMessages ()
Clears messages from the working directory.
virtual void ClientWriteAnInput (AnalysisResults anInput)
Client writes analysis input data for calculation of analysis results. Messages are set nad cleared appropriately.
virtual void ClientReadAnOutput (ref AnalysisResults anres)
Client reads analysis results. Messages are set and cleared appropriately.
virtual void ClientSendAnalysisRequest ()
Sends request to the server for calculation of analysis response.
virtual void ClientCalculateAnalysisResults (ref AnalysisResults anRes)
Calculates analysis results by using the analysis server. Writes analysis input, sends request to the server, and reads the calculated results.
virtual void ClientTestCalculateAnalysisResults (string inputFilePath, bool reqObjective, bool reqConstraints, bool reqObjectiveGradient, bool reqConstraintGradients, string outputFilePath)
Performs client-side test calculation of analysis response.
virtual void ServerAnalyse ()
Performs direct analysis (in optimization) with prescribed analysis input data, and saves results. Messages are set and cleared appropriately. This method reads analysis input from standard location, performs calculation, calculates analysis results and stores them to the standard location.
Protected Member Functions
virtual void WriteAnalysisInputMath (string filePath, AnalysisResults anpt)
Stores analysis input data to the specified file in the standard format (Mathematica-like, but with C style numbers). Does not perform any locking.
virtual void WriteAnalysisInputJson (string filePath, AnalysisResults anpt)
Stores analysis input data to the specified file in the JSON format. Does not perform any locking.
virtual void WriteAnalysisInputXml (string filePath, AnalysisResults anpt)
Stores analysis input data to the specified file in the XML format Does not perform any locking.
virtual void ReadAnalysisInputMath (string filePath, ref AnalysisResults anpt)
Reads analysis input data (request) from the specified file in the standard IGLib format, and stores the data in the specified object.
virtual void ReadAnalysisInputJson (string filePath, ref AnalysisResults anpt)
Reads analysis input data (request) from the specified file in the JSON format, and stores the data in the specified object.
virtual void ReadAnalysisInputXml (string filePath, ref AnalysisResults anpt)
Reads analysis input data (request) from the specified file in the XML format, and stores the data in the specified object.
virtual void WriteAnalysisOutputMath (string filePath, AnalysisResults anpt)
Stores analysis results to the specified file in the standard format (Mathematica-like, but with C style numbers). Does not perform any locking.
virtual void WriteAnalysisOutputJson (string filePath, AnalysisResults anpt)
Stores analysis output data to the specified file in the JSON format Does not perform any locking.
virtual void WriteAnalysisOutputXml (string filePath, AnalysisResults anpt)
Stores analysis output data to the specified file in the XML format . Does not perform any locking.
virtual void ReadAnalysisOutputMath (string filePath, ref AnalysisResults anpt)
Reads analysis output data (request) from the specified file in the standard IGLib format, and stores the data in the specified object.
virtual void ReadAnalysisOutputJson (string filePath, ref AnalysisResults anpt)
Reads analysis output data (request) from the specified file in the JSON format, and stores the data in the specified object.
virtual void ReadAnalysisOutputXml (string filePath, ref AnalysisResults anpt)
Reads analysis output data (request) from the specified file in the XML format, and stores the data in the specified object.
Protected Attributes
string _directory = null
string _anInMathFilename = OptFileConst.AnInMathFileName
string _msgAnBusyFileName = OptFileConst.MsgAnBusyFilename
string _invOptCommandFilename = OptFileConst.InvOptCommandFilename
string _lockFileMutexName = OptFileConst.LockFileMutexName
Mutex _lockFileMutex
Properties
object Lock [get]
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
string DataDirectory [get, protected set]
Directory for data and messages exchange through files.
string LockFileMutexName [get, protected set]
Name of the mutex for system-wide locking of files.
Mutex LockFileMutex [get]
Mutex for system-wide exclusive locks for file system operations related to the current class.
string AnInMathPath [get, protected set]
File path of the analysis input file in standard IGLib format. Setter takes only pure file name, without path information. If set to null then file path is set to null and will be recalculated when getter is called.
string AnInJsonPath [get, protected set]
File path of the analysis input file in Json format. Setter takes only pure file name, without path information. If set to null then file path is set to null and will be recalculated when getter is called.
string AnInXmlPath [get, protected set]
File path of the analysis input file in XML format. Setter takes only pure file name, without path information. If set to null then file path is set to null and will be recalculated when getter is called.
string AnOutMathPath [get, protected set]
File path of the analysis output file in standard IGLib format. Setter takes only pure file name, without path information. If set to null then fle path is set to null and will be recalculated when getter is called.
string AnOutJsonPath [get, protected set]
File path of the analysis output file in JSON format. Setter takes only pure file name, without path information. If set to null then file path is set to null and will be recalculated when getter is called.
string AnOutXmlPath [get, protected set]
File path of the analysis output file in XML format. Setter takes only pure file name, without path information. If set to null then file path is set to null and will be recalculated when getter is called.
string MsgAnBusyPath [get, protected set]
File path of the analysis busy flag file. Setter takes only pure file name, without path information. If set to null then path is set to null and will be recalculated when getter is called.
string MsgAnInputReadyPath [get, protected set]
File path of the analysis input data ready flag file. Setter takes only pure file name, without path information. If set to null then path is set to null and will be recalculated when getter is called.
string MsgAnResultsReadyPath [get, protected set]
File path of the analysis results ready flag file. Setter takes only pure file name, without path information. If set to null then path is set to null and will be recalculated when getter is called.
string MsgOptBusyPath [get, protected set]
File path of the optimization busy flag file. Setter takes only pure file name, without path information. If set to null then path is set to null and will be recalculated when getter is called.
string MsgOptInputReadyPath [get, protected set]
File path of the optimization input data ready flag file. Setter takes only pure file name, without path information. If set to null then path is set to null and will be recalculated when getter is called.
string MsgOptResultsReadyPath [get, protected set]
File path of the optimization resutlts ready flag file. Setter takes only pure file name, without path information. If set to null then path is set to null and will be recalculated when getter is called.
string InvOptCommandPath [get, protected set]
File path of the optimization command file for program Inverse (Inverse interface). Setter takes only pure file name, without path information. If set to null then path is set to null and will be recalculated when getter is called.
string InvAnCommandFilePath [get, protected set]
File path of the analysis command file for program Inverse (Inverse interface). Setter takes only pure file name, without path information. If set to null then path is set to null and will be recalculated when getter is called.
ISerializer SerializerJson [get]
Serializer for JSON format.
bool AnFormatMath [get, set]
Gets or sets the flag indicating whether analysis input and output is written Math format.
bool AnFormatJson [get, set]
Gets or sets the flag indicating whether analysis input and output is written JSON format.
bool AnFormatXml [get, set]
Gets or sets the flag indicating whether analysis input and output is written XML format.
AnalysisResults AnResults [get]
Analysis reaults whae analysis request data and analysis results ar stored.
virtual IAnalysis Analysis [get, set]
Properties inherited from IG.Lib.ILockable
object Lock [get]
Private Attributes
object _mainLock = new object()
string _anInMathPath = null
string _anInJsonFilename = OptFileConst.AnInJsonFilename
string _anInJsonPath = null
string _anInXmlFilename = OptFileConst.AnInXmlFileName
string _anInXmlPath = null
string _anOutMathFilename = OptFileConst.AnOutMathFilename
string _anOutMathPath = null
string _anOutJsonFilename = OptFileConst.AnOutJsonFilename
string _anOutJsonPath = null
string _anOutXmlFilename = OptFileConst.AnOutXmlFilename
string _anOutXmlPath = null
string _msgAnBusyPath = null
string _msgAnInputReadyFileName = OptFileConst.MsgAnInputReadyFilename
string _msgAnInputReadyPath = null
string _msgAnResultsReadyFileName = OptFileConst.MsgAnResultsReadyFilename
string _msgAnResultsReadyPath = null
string _msgOptBusyFilename = OptFileConst.MsgOptBusyFilename
string _msgOptBusyPath = null
string _msgOptInputReadyFilename = OptFileConst.MsgOptDataReadyFilename
string _msgOptInputReadyPath = null
string _msgOptResultsReadyFilename = OptFileConst.MsgOptResultsReadyFilename
string _msgOptResultsReadyPath = null
string _invOptCommandPath = null
string _invAnCommandFilename = OptFileConst.InvAnCommandFilename
string _invAnCommandPath = null
ISerializer _serializerJson
bool _anFormatMath = true
bool _anFormatJson = true
bool _anFormatXml = false
AnalysisResults _anResults
IAnalysis _analysis
Detailed Description
Performs elementary operations for optimization and analysis servers and clients that exchange data and messages through files. Each such server can serve a single request at a time (single thread of execution). Client-server pair (or pairs, when both analysis and optimization are performed in this way) has (or have) a single directory for exchanging data and messages. If there is a need for analyses running in parallel, each thread must have its own directory and its own client-server pair.
WARNING: This module is taken from Dragonfly opt. server and adapted for purpose of some projects. If necessary to further develop, synchronize (and possibly merge) with Dragonfly, otherwise there will be problems with consistent development of both branches.
$A Igor jul08 Mar11;
Definition at line 29 of file OptFileManager.cs.
Constructor & Destructor Documentation
OptFileManager()
IG.Num.OptFileManager.OptFileManager (string directoryPath) inline
Creates a new optimization file server manager.
Parameters
directoryPath Path to the working directory for the current manager. This is the directory where all data and commmunication (data transfer and messaging) files are located.
Definition at line 37 of file OptFileManager.cs.
References IG.Num.OptFileManager.DataDirectory.
Member Function Documentation
GetPath()
string IG.Num.OptFileManager.GetPath (string relativePath) inline
Returns full path of the file or directory with the specified relative path within the data and messages exchange directory.
Parameters
relativePath Relative path (with respect to data and messages exchange directory)
Returns
Definition at line 112 of file OptFileManager.cs.
References IG.Num.OptFileManager.DataDirectory, and IG.Num.OptFileManager.Lock.
LockFileMutexCheckAbandoned()
bool IG.Num.OptFileManager.LockFileMutexCheckAbandoned () inline
Check whether the filesystem locking mutex (property LockFileMutex) has been abandoned, and returns true if it has been (otherwise, false is returned).
After the call, mutex is no longer in abandoned state (WaitOne() will not throw an exception) if it has been before the call.
Call does not block.
Returns
true if mutex has been abandoned, false otherwise.
Definition at line 233 of file OptFileManager.cs.
References IG.Num.OptFileManager.LockFileMutex, and IG.Lib.Util.MutexCheckAbandoned().
IsAnInputReady()
virtual bool IG.Num.OptFileManager.IsAnInputReady () inline virtual
Gets a flag telling whether analysis input data is ready.
Definition at line 675 of file OptFileManager.cs.
References IG.Num.OptFileManager.LockFileMutex, and IG.Num.OptFileManager.MsgAnInputReadyPath.
Referenced by IG.Num.OptFileManager.ServerAnalyse(), and IG.Num.OptFileManager.WaitAnInputReady().
WaitAnInputReady()
virtual void IG.Num.OptFileManager.WaitAnInputReady () inline virtual
Waits until analysis data is ready. REMARK: Currently this file just checks existence of the file in a loop. This should be changed in the future because it is not the best solution.
Definition at line 707 of file OptFileManager.cs.
References IG.Num.OptFileManager.IsAnInputReady().
ClearAnInputReady()
virtual void IG.Num.OptFileManager.ClearAnInputReady () inline virtual
Clears the analysis data ready flag.
Definition at line 716 of file OptFileManager.cs.
References IG.Num.OptFileManager.LockFileMutex, and IG.Num.OptFileManager.MsgAnInputReadyPath.
Referenced by IG.Num.OptFileManager.ClearMessages(), and IG.Num.OptFileManager.ClientWriteAnInput().
SetAnInputReady()
virtual void IG.Num.OptFileManager.SetAnInputReady () inline virtual
Sets the analysis input ready flag.
Definition at line 744 of file OptFileManager.cs.
References IG.Num.OptFileManager.LockFileMutex, and IG.Num.OptFileManager.MsgAnInputReadyPath.
Referenced by IG.Num.OptFileManager.ClientWriteAnInput().
IsAnResultsReady()
virtual bool IG.Num.OptFileManager.IsAnResultsReady () inline virtual
Gets a flag telling whether analysis output data is ready.
Definition at line 770 of file OptFileManager.cs.
References IG.Num.OptFileManager.LockFileMutex, and IG.Num.OptFileManager.MsgAnResultsReadyPath.
Referenced by IG.Num.OptFileManager.ServerAnalyse(), and IG.Num.OptFileManager.WaitAnResultsReady().
WaitAnResultsReady()
virtual void IG.Num.OptFileManager.WaitAnResultsReady () inline virtual
Waits until analysis data is ready. REMARK: Currently this file just checks existence of the file in a loop. This should be changed in the future because it is not the best solution.
Definition at line 802 of file OptFileManager.cs.
References IG.Num.OptFileManager.IsAnResultsReady().
ClearAnResultsReady()
virtual void IG.Num.OptFileManager.ClearAnResultsReady () inline virtual
Clears the analysis results ready flag.
Definition at line 811 of file OptFileManager.cs.
References IG.Num.OptFileManager.LockFileMutex, and IG.Num.OptFileManager.MsgAnResultsReadyPath.
Referenced by IG.Num.OptFileManager.ClearMessages(), IG.Num.OptFileManager.ClientReadAnOutput(), and IG.Num.OptFileManager.ServerAnalyse().
SetAnResultsReady()
virtual void IG.Num.OptFileManager.SetAnResultsReady () inline virtual
Sets the analysis results ready flag.
Definition at line 839 of file OptFileManager.cs.
References IG.Num.OptFileManager.LockFileMutex, and IG.Num.OptFileManager.MsgAnResultsReadyPath.
Referenced by IG.Num.OptFileManager.ServerAnalyse().
IsAnBusy()
virtual bool IG.Num.OptFileManager.IsAnBusy () inline virtual
Gets a flag telling whether direct analysis is busy.
Definition at line 866 of file OptFileManager.cs.
References IG.Num.OptFileManager.LockFileMutex, and IG.Num.OptFileManager.MsgAnBusyPath.
Referenced by IG.Num.OptFileManager.ServerAnalyse(), and IG.Num.OptFileManager.WaitAnReady().
WaitAnReady()
virtual void IG.Num.OptFileManager.WaitAnReady () inline virtual
Waits until analysis is ready. REMARK: Currently this file just checks existence of the file in a loop. This should be changed in the future because it is not the best solution.
Definition at line 898 of file OptFileManager.cs.
References IG.Num.OptFileManager.IsAnBusy().
ClearAnBusy()
virtual void IG.Num.OptFileManager.ClearAnBusy () inline virtual
Clears the analysis busy flag.
Definition at line 907 of file OptFileManager.cs.
References IG.Num.OptFileManager.LockFileMutex, and IG.Num.OptFileManager.MsgAnBusyPath.
Referenced by IG.Num.OptFileManager.ClearMessages().
SetAnBusy()
virtual void IG.Num.OptFileManager.SetAnBusy () inline virtual
Sets the analysis busy flag.
Definition at line 935 of file OptFileManager.cs.
References IG.Num.OptFileManager.LockFileMutex, and IG.Num.OptFileManager.MsgAnBusyPath.
Referenced by IG.Num.OptFileManager.ClientWriteAnInput(), and IG.Num.OptFileManager.ServerAnalyse().
ClearMessages()
void IG.Num.OptFileManager.ClearMessages () inline
Clears messages from the working directory.
Definition at line 961 of file OptFileManager.cs.
References IG.Num.OptFileManager.ClearAnBusy(), IG.Num.OptFileManager.ClearAnInputReady(), IG.Num.OptFileManager.ClearAnResultsReady(), and IG.Num.OptFileManager.LockFileMutex.
WriteAnalysisInputMath()
virtual void IG.Num.OptFileManager.WriteAnalysisInputMath (string filePath, AnalysisResults anpt) inline protected virtual
Stores analysis input data to the specified file in the standard format (Mathematica-like, but with C style numbers). Does not perform any locking.
Parameters
filePath Full path of the file that data is written to.
anpt Analysis input data.
Definition at line 997 of file OptFileManager.cs.
References IG.Num.AnalysisResults.SaveRequestMath().
Referenced by IG.Num.OptFileManager.ClientWriteAnInput().
WriteAnalysisInputJson()
virtual void IG.Num.OptFileManager.WriteAnalysisInputJson (string filePath, AnalysisResults anpt) inline protected virtual
Stores analysis input data to the specified file in the JSON format. Does not perform any locking.
Parameters
filePath Full path of the file that data is written to.
anpt Analysis input data.
Definition at line 1006 of file OptFileManager.cs.
References IG.Lib.SerializationDtoBase< Type, BaseType >.CopyFrom(), and IG.Num.OptFileManager.Lock.
Referenced by IG.Num.OptFileManager.ClientWriteAnInput().
WriteAnalysisInputXml()
virtual void IG.Num.OptFileManager.WriteAnalysisInputXml (string filePath, AnalysisResults anpt) inline protected virtual
Stores analysis input data to the specified file in the XML format Does not perform any locking.
Parameters
filePath Full path of the file that data is written to.
anpt Analysis results.
Definition at line 1020 of file OptFileManager.cs.
Referenced by IG.Num.OptFileManager.ClientWriteAnInput().
ReadAnalysisInputMath()
virtual void IG.Num.OptFileManager.ReadAnalysisInputMath (string filePath, ref AnalysisResults anpt) inline protected virtual
Reads analysis input data (request) from the specified file in the standard IGLib format, and stores the data in the specified object.
Parameters
filePath Path to the file that data is read from.
anpt Analysis results object where the data is stored.
Definition at line 1030 of file OptFileManager.cs.
References IG.Num.AnalysisResults.LoadRequestMath().
Referenced by IG.Num.OptFileManager.ServerAnalyse().
ReadAnalysisInputJson()
virtual void IG.Num.OptFileManager.ReadAnalysisInputJson (string filePath, ref AnalysisResults anpt) inline protected virtual
Reads analysis input data (request) from the specified file in the JSON format, and stores the data in the specified object.
Parameters
filePath Path to the file that data is read from.
anpt Analysis results object where the data is stored.
Definition at line 1040 of file OptFileManager.cs.
References IG.Lib.SerializationDtoBase< Type, BaseType >.CopyTo().
Referenced by IG.Num.OptFileManager.ServerAnalyse().
ReadAnalysisInputXml()
virtual void IG.Num.OptFileManager.ReadAnalysisInputXml (string filePath, ref AnalysisResults anpt) inline protected virtual
Reads analysis input data (request) from the specified file in the XML format, and stores the data in the specified object.
Parameters
filePath Path to the file that data is read from.
anpt Analysis results object where the data is stored.
Definition at line 1050 of file OptFileManager.cs.
Referenced by IG.Num.OptFileManager.ServerAnalyse().
WriteAnalysisOutputMath()
virtual void IG.Num.OptFileManager.WriteAnalysisOutputMath (string filePath, AnalysisResults anpt) inline protected virtual
Stores analysis results to the specified file in the standard format (Mathematica-like, but with C style numbers). Does not perform any locking.
Parameters
filePath Full path of the file that data is written to.
anpt Analysis output data.
Definition at line 1061 of file OptFileManager.cs.
References IG.Num.AnalysisResults.SaveMath().
Referenced by IG.Num.OptFileManager.ServerAnalyse().
WriteAnalysisOutputJson()
virtual void IG.Num.OptFileManager.WriteAnalysisOutputJson (string filePath, AnalysisResults anpt) inline protected virtual
Stores analysis output data to the specified file in the JSON format Does not perform any locking.
Parameters
filePath Full path of the file that data is written to.
anpt Analysis results.
Definition at line 1070 of file OptFileManager.cs.
References IG.Lib.SerializationDtoBase< Type, BaseType >.CopyFrom(), and IG.Num.OptFileManager.Lock.
Referenced by IG.Num.OptFileManager.ServerAnalyse().
WriteAnalysisOutputXml()
virtual void IG.Num.OptFileManager.WriteAnalysisOutputXml (string filePath, AnalysisResults anpt) inline protected virtual
Stores analysis output data to the specified file in the XML format . Does not perform any locking.
Parameters
filePath Full path of the file that data is written to.
anpt Analysis results.
Definition at line 1084 of file OptFileManager.cs.
Referenced by IG.Num.OptFileManager.ServerAnalyse().
ReadAnalysisOutputMath()
virtual void IG.Num.OptFileManager.ReadAnalysisOutputMath (string filePath, ref AnalysisResults anpt) inline protected virtual
Reads analysis output data (request) from the specified file in the standard IGLib format, and stores the data in the specified object.
Parameters
filePath Path to the file that data is read from.
anpt Analysis results object where the data is stored.
Definition at line 1094 of file OptFileManager.cs.
References IG.Num.AnalysisResults.LoadMath().
Referenced by IG.Num.OptFileManager.ClientReadAnOutput().
ReadAnalysisOutputJson()
virtual void IG.Num.OptFileManager.ReadAnalysisOutputJson (string filePath, ref AnalysisResults anpt) inline protected virtual
Reads analysis output data (request) from the specified file in the JSON format, and stores the data in the specified object.
Parameters
filePath Path to the file that data is read from.
anpt Analysis results object where the data is stored.
Definition at line 1103 of file OptFileManager.cs.
References IG.Lib.SerializationDtoBase< Type, BaseType >.CopyTo().
Referenced by IG.Num.OptFileManager.ClientReadAnOutput().
ReadAnalysisOutputXml()
virtual void IG.Num.OptFileManager.ReadAnalysisOutputXml (string filePath, ref AnalysisResults anpt) inline protected virtual
Reads analysis output data (request) from the specified file in the XML format, and stores the data in the specified object.
Parameters
filePath Path to the file that data is read from.
anpt Analysis results object where the data is stored.
Definition at line 1113 of file OptFileManager.cs.
Referenced by IG.Num.OptFileManager.ClientReadAnOutput().
ClientWriteAnInput()
virtual void IG.Num.OptFileManager.ClientWriteAnInput (AnalysisResults anInput) inline virtual
Client writes analysis input data for calculation of analysis results. Messages are set nad cleared appropriately.
Parameters
anInput Parameters to be written.
Definition at line 1127 of file OptFileManager.cs.
References IG.Num.OptFileManager.AnFormatJson, IG.Num.OptFileManager.AnFormatMath, IG.Num.OptFileManager.AnFormatXml, IG.Num.OptFileManager.AnInJsonPath, IG.Num.OptFileManager.AnInMathPath, IG.Num.OptFileManager.AnInXmlPath, IG.Num.OptFileManager.ClearAnInputReady(), IG.Num.OptFileManager.SetAnBusy(), IG.Num.OptFileManager.SetAnInputReady(), IG.Num.OptFileManager.WriteAnalysisInputJson(), IG.Num.OptFileManager.WriteAnalysisInputMath(), and IG.Num.OptFileManager.WriteAnalysisInputXml().
Referenced by IG.Num.OptFileManager.ClientCalculateAnalysisResults().
ClientReadAnOutput()
virtual void IG.Num.OptFileManager.ClientReadAnOutput (ref AnalysisResults anres) inline virtual
Client reads analysis results. Messages are set and cleared appropriately.
Parameters
anres Object where results are written.
Definition at line 1143 of file OptFileManager.cs.
References IG.Num.OptFileManager.AnFormatJson, IG.Num.OptFileManager.AnFormatMath, IG.Num.OptFileManager.AnFormatXml, IG.Num.OptFileManager.AnOutJsonPath, IG.Num.OptFileManager.AnOutMathPath, IG.Num.OptFileManager.AnOutXmlPath, IG.Num.OptFileManager.ClearAnResultsReady(), IG.Num.OptFileManager.ReadAnalysisOutputJson(), IG.Num.OptFileManager.ReadAnalysisOutputMath(), and IG.Num.OptFileManager.ReadAnalysisOutputXml().
Referenced by IG.Num.OptFileManager.ClientCalculateAnalysisResults().
ClientSendAnalysisRequest()
virtual void IG.Num.OptFileManager.ClientSendAnalysisRequest () inline virtual
Sends request to the server for calculation of analysis response.
Definition at line 1155 of file OptFileManager.cs.
References IG.Num.OptFileManager.ServerAnalyse().
Referenced by IG.Num.OptFileManager.ClientCalculateAnalysisResults().
ClientCalculateAnalysisResults()
virtual void IG.Num.OptFileManager.ClientCalculateAnalysisResults (ref AnalysisResults anRes) inline virtual
Calculates analysis results by using the analysis server. Writes analysis input, sends request to the server, and reads the calculated results.
Parameters
anRes Analysis results object where approximation output values are stored.
Definition at line 1163 of file OptFileManager.cs.
References IG.Num.OptFileManager.ClientReadAnOutput(), IG.Num.OptFileManager.ClientSendAnalysisRequest(), and IG.Num.OptFileManager.ClientWriteAnInput().
Referenced by IG.Num.OptFileManager.ClientTestCalculateAnalysisResults().
ClientTestCalculateAnalysisResults()
virtual void IG.Num.OptFileManager.ClientTestCalculateAnalysisResults (string inputFilePath, bool reqObjective, bool reqConstraints, bool reqObjectiveGradient, bool reqConstraintGradients, string outputFilePath) inline virtual
Performs client-side test calculation of analysis response.
Parameters
inputFilePath Path to the JSON file where input parameters are read from. The file pointed at must exist.
reqObjective Flag indicating whether objective function must be calculated.
reqConstraints Flag indicating whether constraint functions must be calculated.
reqObjectiveGradient Flag indicating whether objective function gradientmust be calculated.
reqConstraintGradients Fleg indicating whether constraint function gradients must be calculated.
outputFilePath Path of a file where the calculated analysis response in JSON is written to. It can be null or empty string, in this case response is not written to a file (but it is output on console).
Definition at line 1180 of file OptFileManager.cs.
References IG.Num.OptFileManager.ClientCalculateAnalysisResults(), IG.Num.VectorBase.LoadJson(), IG.Num.AnalysisResults.Parameters, IG.Num.AnalysisResults.ReqConstraintGradients, IG.Num.AnalysisResults.ReqConstraints, IG.Num.AnalysisResults.ReqObjective, IG.Num.AnalysisResults.ReqObjectiveGradient, and IG.Num.AnalysisResults.SaveJson().
ServerAnalyse()
virtual void IG.Num.OptFileManager.ServerAnalyse () inline virtual
Performs direct analysis (in optimization) with prescribed analysis input data, and saves results. Messages are set and cleared appropriately. This method reads analysis input from standard location, performs calculation, calculates analysis results and stores them to the standard location.
Definition at line 1233 of file OptFileManager.cs.
References IG.Num.IAnalysis.Analyse(), IG.Num.OptFileManager.Analysis, IG.Num.OptFileManager.AnFormatJson, IG.Num.OptFileManager.AnFormatMath, IG.Num.OptFileManager.AnFormatXml, IG.Num.OptFileManager.AnInJsonPath, IG.Num.OptFileManager.AnInMathPath, IG.Num.OptFileManager.AnInXmlPath, IG.Num.OptFileManager.AnOutJsonPath, IG.Num.OptFileManager.AnOutMathPath, IG.Num.OptFileManager.AnOutXmlPath, IG.Num.OptFileManager.AnResults, IG.Num.OptFileManager.ClearAnResultsReady(), IG.Num.OptFileManager.IsAnBusy(), IG.Num.OptFileManager.IsAnInputReady(), IG.Num.OptFileManager.IsAnResultsReady(), IG.Num.OptFileManager.Lock, IG.Num.OptFileManager.ReadAnalysisInputJson(), IG.Num.OptFileManager.ReadAnalysisInputMath(), IG.Num.OptFileManager.ReadAnalysisInputXml(), IG.Num.AnalysisResults.ResetResults(), IG.Num.OptFileManager.SetAnBusy(), IG.Num.OptFileManager.SetAnResultsReady(), IG.Num.OptFileManager.WriteAnalysisOutputJson(), IG.Num.OptFileManager.WriteAnalysisOutputMath(), and IG.Num.OptFileManager.WriteAnalysisOutputXml().
Referenced by IG.Num.OptFileManager.ClientSendAnalysisRequest().
Member Data Documentation
_mainLock
object IG.Num.OptFileManager._mainLock = new object() private
Definition at line 43 of file OptFileManager.cs.
_directory
string IG.Num.OptFileManager._directory = null protected
Definition at line 68 of file OptFileManager.cs.
_anInMathFilename
string IG.Num.OptFileManager._anInMathFilename = OptFileConst.AnInMathFileName protected
Definition at line 130 of file OptFileManager.cs.
_anInMathPath
string IG.Num.OptFileManager._anInMathPath = null private
Definition at line 131 of file OptFileManager.cs.
_anInJsonFilename
string IG.Num.OptFileManager._anInJsonFilename = OptFileConst.AnInJsonFilename private
Definition at line 132 of file OptFileManager.cs.
_anInJsonPath
string IG.Num.OptFileManager._anInJsonPath = null private
Definition at line 133 of file OptFileManager.cs.
_anInXmlFilename
string IG.Num.OptFileManager._anInXmlFilename = OptFileConst.AnInXmlFileName private
Definition at line 134 of file OptFileManager.cs.
_anInXmlPath
string IG.Num.OptFileManager._anInXmlPath = null private
Definition at line 135 of file OptFileManager.cs.
_anOutMathFilename
string IG.Num.OptFileManager._anOutMathFilename = OptFileConst.AnOutMathFilename private
Definition at line 136 of file OptFileManager.cs.
_anOutMathPath
string IG.Num.OptFileManager._anOutMathPath = null private
Definition at line 137 of file OptFileManager.cs.
_anOutJsonFilename
string IG.Num.OptFileManager._anOutJsonFilename = OptFileConst.AnOutJsonFilename private
Definition at line 138 of file OptFileManager.cs.
_anOutJsonPath
string IG.Num.OptFileManager._anOutJsonPath = null private
Definition at line 139 of file OptFileManager.cs.
_anOutXmlFilename
string IG.Num.OptFileManager._anOutXmlFilename = OptFileConst.AnOutXmlFilename private
Definition at line 140 of file OptFileManager.cs.
_anOutXmlPath
string IG.Num.OptFileManager._anOutXmlPath = null private
Definition at line 141 of file OptFileManager.cs.
_msgAnBusyFileName
string IG.Num.OptFileManager._msgAnBusyFileName = OptFileConst.MsgAnBusyFilename protected
Definition at line 145 of file OptFileManager.cs.
_msgAnBusyPath
string IG.Num.OptFileManager._msgAnBusyPath = null private
Definition at line 146 of file OptFileManager.cs.
_msgAnInputReadyFileName
string IG.Num.OptFileManager._msgAnInputReadyFileName = OptFileConst.MsgAnInputReadyFilename private
Definition at line 147 of file OptFileManager.cs.
_msgAnInputReadyPath
string IG.Num.OptFileManager._msgAnInputReadyPath = null private
Definition at line 148 of file OptFileManager.cs.
_msgAnResultsReadyFileName
string IG.Num.OptFileManager._msgAnResultsReadyFileName = OptFileConst.MsgAnResultsReadyFilename private
Definition at line 149 of file OptFileManager.cs.
_msgAnResultsReadyPath
string IG.Num.OptFileManager._msgAnResultsReadyPath = null private
Definition at line 150 of file OptFileManager.cs.
_msgOptBusyFilename
string IG.Num.OptFileManager._msgOptBusyFilename = OptFileConst.MsgOptBusyFilename private
Definition at line 152 of file OptFileManager.cs.
_msgOptBusyPath
string IG.Num.OptFileManager._msgOptBusyPath = null private
Definition at line 153 of file OptFileManager.cs.
_msgOptInputReadyFilename
string IG.Num.OptFileManager._msgOptInputReadyFilename = OptFileConst.MsgOptDataReadyFilename private
Definition at line 154 of file OptFileManager.cs.
_msgOptInputReadyPath
string IG.Num.OptFileManager._msgOptInputReadyPath = null private
Definition at line 155 of file OptFileManager.cs.
_msgOptResultsReadyFilename
string IG.Num.OptFileManager._msgOptResultsReadyFilename = OptFileConst.MsgOptResultsReadyFilename private
Definition at line 156 of file OptFileManager.cs.
_msgOptResultsReadyPath
string IG.Num.OptFileManager._msgOptResultsReadyPath = null private
Definition at line 157 of file OptFileManager.cs.
_invOptCommandFilename
string IG.Num.OptFileManager._invOptCommandFilename = OptFileConst.InvOptCommandFilename protected
Definition at line 161 of file OptFileManager.cs.
_invOptCommandPath
string IG.Num.OptFileManager._invOptCommandPath = null private
Definition at line 162 of file OptFileManager.cs.
_invAnCommandFilename
string IG.Num.OptFileManager._invAnCommandFilename = OptFileConst.InvAnCommandFilename private
Definition at line 163 of file OptFileManager.cs.
_invAnCommandPath
string IG.Num.OptFileManager._invAnCommandPath = null private
Definition at line 164 of file OptFileManager.cs.
_lockFileMutexName
string IG.Num.OptFileManager._lockFileMutexName = OptFileConst.LockFileMutexName protected
Definition at line 181 of file OptFileManager.cs.
_lockFileMutex
Mutex IG.Num.OptFileManager._lockFileMutex protected
Definition at line 193 of file OptFileManager.cs.
_serializerJson
ISerializer IG.Num.OptFileManager._serializerJson private
Definition at line 622 of file OptFileManager.cs.
_anFormatMath
bool IG.Num.OptFileManager._anFormatMath = true private
Definition at line 627 of file OptFileManager.cs.
_anFormatJson
bool IG.Num.OptFileManager._anFormatJson = true private
Definition at line 628 of file OptFileManager.cs.
_anFormatXml
bool IG.Num.OptFileManager._anFormatXml = false private
Definition at line 629 of file OptFileManager.cs.
_anResults
AnalysisResults IG.Num.OptFileManager._anResults private
Definition at line 656 of file OptFileManager.cs.
_analysis
IAnalysis IG.Num.OptFileManager._analysis private
Definition at line 1221 of file OptFileManager.cs.
Property Documentation
Lock
object IG.Num.OptFileManager.Lock get
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
Definition at line 48 of file OptFileManager.cs.
Referenced by IG.Num.OptFileManager.GetPath(), IG.Num.OptFileManager.ServerAnalyse(), IG.Num.OptFileManager.WriteAnalysisInputJson(), and IG.Num.OptFileManager.WriteAnalysisOutputJson().
DataDirectory
string IG.Num.OptFileManager.DataDirectory get protected set
Directory for data and messages exchange through files.
Definition at line 72 of file OptFileManager.cs.
Referenced by IG.Num.OptFileManager.GetPath(), and IG.Num.OptFileManager.OptFileManager().
LockFileMutexName
string IG.Num.OptFileManager.LockFileMutexName get protected set
Name of the mutex for system-wide locking of files.
Definition at line 185 of file OptFileManager.cs.
LockFileMutex
Mutex IG.Num.OptFileManager.LockFileMutex get protected
Mutex for system-wide exclusive locks for file system operations related to the current class.
Definition at line 198 of file OptFileManager.cs.
Referenced by IG.Num.OptFileManager.ClearAnBusy(), IG.Num.OptFileManager.ClearAnInputReady(), IG.Num.OptFileManager.ClearAnResultsReady(), IG.Num.OptFileManager.ClearMessages(), IG.Num.OptFileManager.IsAnBusy(), IG.Num.OptFileManager.IsAnInputReady(), IG.Num.OptFileManager.IsAnResultsReady(), IG.Num.OptFileManager.LockFileMutexCheckAbandoned(), IG.Num.OptFileManager.SetAnBusy(), IG.Num.OptFileManager.SetAnInputReady(), and IG.Num.OptFileManager.SetAnResultsReady().
AnInMathPath
string IG.Num.OptFileManager.AnInMathPath get protected set
File path of the analysis input file in standard IGLib format. Setter takes only pure file name, without path information. If set to null then file path is set to null and will be recalculated when getter is called.
Definition at line 246 of file OptFileManager.cs.
Referenced by IG.Num.OptFileManager.ClientWriteAnInput(), and IG.Num.OptFileManager.ServerAnalyse().
AnInJsonPath
string IG.Num.OptFileManager.AnInJsonPath get protected set
File path of the analysis input file in Json format. Setter takes only pure file name, without path information. If set to null then file path is set to null and will be recalculated when getter is called.
Definition at line 273 of file OptFileManager.cs.
Referenced by IG.Num.OptFileManager.ClientWriteAnInput(), and IG.Num.OptFileManager.ServerAnalyse().
AnInXmlPath
string IG.Num.OptFileManager.AnInXmlPath get protected set
File path of the analysis input file in XML format. Setter takes only pure file name, without path information. If set to null then file path is set to null and will be recalculated when getter is called.
Definition at line 301 of file OptFileManager.cs.
Referenced by IG.Num.OptFileManager.ClientWriteAnInput(), and IG.Num.OptFileManager.ServerAnalyse().
AnOutMathPath
string IG.Num.OptFileManager.AnOutMathPath get protected set
File path of the analysis output file in standard IGLib format. Setter takes only pure file name, without path information. If set to null then fle path is set to null and will be recalculated when getter is called.
Definition at line 326 of file OptFileManager.cs.
Referenced by IG.Num.OptFileManager.ClientReadAnOutput(), and IG.Num.OptFileManager.ServerAnalyse().
AnOutJsonPath
string IG.Num.OptFileManager.AnOutJsonPath get protected set
File path of the analysis output file in JSON format. Setter takes only pure file name, without path information. If set to null then file path is set to null and will be recalculated when getter is called.
Definition at line 354 of file OptFileManager.cs.
Referenced by IG.Num.OptFileManager.ClientReadAnOutput(), and IG.Num.OptFileManager.ServerAnalyse().
AnOutXmlPath
string IG.Num.OptFileManager.AnOutXmlPath get protected set
File path of the analysis output file in XML format. Setter takes only pure file name, without path information. If set to null then file path is set to null and will be recalculated when getter is called.
Definition at line 382 of file OptFileManager.cs.
Referenced by IG.Num.OptFileManager.ClientReadAnOutput(), and IG.Num.OptFileManager.ServerAnalyse().
MsgAnBusyPath
string IG.Num.OptFileManager.MsgAnBusyPath get protected set
File path of the analysis busy flag file. Setter takes only pure file name, without path information. If set to null then path is set to null and will be recalculated when getter is called.
Definition at line 412 of file OptFileManager.cs.
Referenced by IG.Num.OptFileManager.ClearAnBusy(), IG.Num.OptFileManager.IsAnBusy(), and IG.Num.OptFileManager.SetAnBusy().
MsgAnInputReadyPath
string IG.Num.OptFileManager.MsgAnInputReadyPath get protected set
File path of the analysis input data ready flag file. Setter takes only pure file name, without path information. If set to null then path is set to null and will be recalculated when getter is called.
Definition at line 438 of file OptFileManager.cs.
Referenced by IG.Num.OptFileManager.ClearAnInputReady(), IG.Num.OptFileManager.IsAnInputReady(), and IG.Num.OptFileManager.SetAnInputReady().
MsgAnResultsReadyPath
string IG.Num.OptFileManager.MsgAnResultsReadyPath get protected set
File path of the analysis results ready flag file. Setter takes only pure file name, without path information. If set to null then path is set to null and will be recalculated when getter is called.
Definition at line 461 of file OptFileManager.cs.
Referenced by IG.Num.OptFileManager.ClearAnResultsReady(), IG.Num.OptFileManager.IsAnResultsReady(), and IG.Num.OptFileManager.SetAnResultsReady().
MsgOptBusyPath
string IG.Num.OptFileManager.MsgOptBusyPath get protected set
File path of the optimization busy flag file. Setter takes only pure file name, without path information. If set to null then path is set to null and will be recalculated when getter is called.
Definition at line 487 of file OptFileManager.cs.
MsgOptInputReadyPath
string IG.Num.OptFileManager.MsgOptInputReadyPath get protected set
File path of the optimization input data ready flag file. Setter takes only pure file name, without path information. If set to null then path is set to null and will be recalculated when getter is called.
Definition at line 513 of file OptFileManager.cs.
MsgOptResultsReadyPath
string IG.Num.OptFileManager.MsgOptResultsReadyPath get protected set
File path of the optimization resutlts ready flag file. Setter takes only pure file name, without path information. If set to null then path is set to null and will be recalculated when getter is called.
Definition at line 539 of file OptFileManager.cs.
InvOptCommandPath
string IG.Num.OptFileManager.InvOptCommandPath get protected set
File path of the optimization command file for program Inverse (Inverse interface). Setter takes only pure file name, without path information. If set to null then path is set to null and will be recalculated when getter is called.
Definition at line 568 of file OptFileManager.cs.
InvAnCommandFilePath
string IG.Num.OptFileManager.InvAnCommandFilePath get protected set
File path of the analysis command file for program Inverse (Inverse interface). Setter takes only pure file name, without path information. If set to null then path is set to null and will be recalculated when getter is called.
Definition at line 594 of file OptFileManager.cs.
SerializerJson
ISerializer IG.Num.OptFileManager.SerializerJson get protected
Serializer for JSON format.
Definition at line 633 of file OptFileManager.cs.
AnFormatMath
bool IG.Num.OptFileManager.AnFormatMath get set
Gets or sets the flag indicating whether analysis input and output is written Math format.
Definition at line 645 of file OptFileManager.cs.
Referenced by IG.Num.OptFileManager.ClientReadAnOutput(), IG.Num.OptFileManager.ClientWriteAnInput(), and IG.Num.OptFileManager.ServerAnalyse().
AnFormatJson
bool IG.Num.OptFileManager.AnFormatJson get set
Gets or sets the flag indicating whether analysis input and output is written JSON format.
Definition at line 649 of file OptFileManager.cs.
Referenced by IG.Num.OptFileManager.ClientReadAnOutput(), IG.Num.OptFileManager.ClientWriteAnInput(), and IG.Num.OptFileManager.ServerAnalyse().
AnFormatXml
bool IG.Num.OptFileManager.AnFormatXml get set
Gets or sets the flag indicating whether analysis input and output is written XML format.
Definition at line 653 of file OptFileManager.cs.
Referenced by IG.Num.OptFileManager.ClientReadAnOutput(), IG.Num.OptFileManager.ClientWriteAnInput(), and IG.Num.OptFileManager.ServerAnalyse().
AnResults
AnalysisResults IG.Num.OptFileManager.AnResults get protected
Analysis reaults whae analysis request data and analysis results ar stored.
Definition at line 660 of file OptFileManager.cs.
Referenced by IG.Num.OptFileManager.ServerAnalyse().
Analysis
virtual IAnalysis IG.Num.OptFileManager.Analysis get set
Definition at line 1224 of file OptFileManager.cs.
Referenced by IG.Num.OptFileManager.ServerAnalyse().
The documentation for this class was generated from the following file:
iglib/igbase/optimization/fileserver/OptFileManager.cs