Doc: IGLib with source files: IGLib.Core.Tests.CollectionTypeConverterTests Class Reference
IGLib.Core.Tests.CollectionTypeConverterTests Class Reference
Tests of the basic type converter (BasicTypeConverter, implementation of the ITypeConverter interface).
Public Member Functions
CollectionTypeConverterTests (ITestOutputHelper output)
Public Member Functions inherited from IGLib.Core.Tests.BasicTypeConverterTests
BasicTypeConverterTests (ITestOutputHelper output)
Calling base constructor initializes things like TestBase<TestClass>.Output and TestBase<TestClass>.Output properties that enable writing on tests' output.
Public Member Functions inherited from IGLib.Core.Tests.TypeConverterTestsBase< BasicTypeConverterTests >
TypeConverterTestsBase (ITestOutputHelper output)
Calling base constructor initializes things like TestBase<TestClass>.Output and TestBase<TestClass>.Output properties that enable writing on tests' output.
Protected Member Functions
virtual void SpecificTypeConverter_CollectionRoundTripConversion_IntIListToIntIEnumerableObjectToIntArray ()
virtual void SpecificTypeConverter_CollectionRoundTripConversion_IntArrayToIntIEnumerableObjectToIntIList ()
virtual void SpecificTypeConverter_CollectionRoundTripConversion_IntIListToIntArrayObjectToIntIList ()
virtual void SpecificTypeConverter_CollectionRoundTripConversion_IntIEnumerableToIntListObjectToIntArray ()
virtual void SpecificTypeConverter_CollectionRoundTripConversion_IntIEnumerableToIntArrayObjectToIntList ()
virtual void SpecificTypeConverter_CollectionRoundTripConversion_IntIListToIntArrayObjectToIntList ()
virtual void SpecificTypeConverter_CollectionRoundTripConversion_IntArrayToIntListObjectToIntArray ()
virtual void SpecificTypeConverter_CollectionRoundTripConversion_IntArrayToIntIListObjectToIntArray ()
virtual void SpecificTypeConverter_CollectionRoundTripConversion_IntArray2DToIntArrayObjectToIntList ()
virtual void SpecificTypeConverter_CollectionRoundTripConversion_IntArray3DToIntIListObjectToIntArray ()
virtual void SpecificTypeConverter_CollectionRoundTripConversion_IntArray3DToIntListObjectToIntArray ()
virtual void SpecificTypeConverter_CollectionRoundTripConversion_IntArray3DToIntIEnumerableObjectToIntArray ()
virtual void SpecificTypeConverter_CollectionRoundTripConversion_IntArray2DToIntArray2DObjectToIntArray2D ()
virtual void SpecificTypeConverter_CollectionRoundTripConversion_IntArray3DToIntArray3DObjectToIntArray3D ()
virtual void SpecificTypeConverter_CollectionRoundTripConversion_IntJaggedArrayNonrectangular2DToIntArrayObjectToIntList ()
virtual void SpecificTypeConverter_CollectionRoundTripConversion_IntJaggedArrayNonrectangular3DToIntIListObjectToIntArray ()
virtual void SpecificTypeConverter_CollectionRoundTripConversion_IntJaggedArrayNonrectangular3DToIntIEnumerableObjectToIntArray ()
virtual void SpecificTypeConverter_CollectionRoundTripConversion_IntJaggedArray2DToIntJaggedArray2DObjectToIntJaggedArray2D ()
virtual void SpecificTypeConverter_CollectionRoundTripConversion_IntJaggedArray3DToIntJaggedArray3DObjectToIntJaggedArray3D ()
virtual void SpecificTypeConverter_CollectionRoundTripConversion_IntJaggedArray3DToIntArray3DObjectToIntJaggedArray3D ()
virtual void SpecificTypeConverter_CollectionRoundTripConversion_IntArray3DToIntJaggedArray3DObjectToIntArray3D ()
Protected Member Functions inherited from IGLib.Core.Tests.BasicTypeConverterTests
virtual void SpecificTypeConverter_RoundTripConversion_IntToIntObjectToInt_IsCorrect ()
virtual void SpecificTypeConverter_RoundTripConversion_IntToDoubleObjectToDouble_IsCorrect ()
virtual void SpecificTypeConverter_RoundTripConversion_IntToDoubleObjectToInt_IsCorrect ()
virtual void SpecificTypeConverter_RoundTripConversion_DoubleToDoubleObjectToDouble_IsCorrect ()
virtual void SpecificTypeConverter_RoundTripConversion_IntegerDoubleToIntObjectToInt_IsCorrect ()
virtual void SpecificTypeConverter_RoundTripConversion_NonintegerDoubleToIntObjectToInt_IsCorrect ()
virtual void SpecificTypeConverter_RoundTripConversion_OwerflowDoubleToIntObjectToInt_IsCorrect ()
virtual void SpecificTypeConverter_RoundTripConversion_NonintegerDoubleToIntObjectToDouble_IsCorrect ()
virtual void SpecificTypeConverter_RoundTripConversion_DoubleToStringObjectToDouble_IsCorrect ()
virtual void SpecificTypeConverter_RoundTripConversion_StringToDoubleObjectToString_IsCorrect ()
virtual void SpecificTypeConverter_RoundTripConversion_StringWithUnderscoresToDoubleObjectToDouble_IsCorrect ()
virtual void SpecificTypeConverter_RoundTripConversion_DoubleStringToDoubleObjectToInt_IsCorrect ()
virtual void SpecificTypeConverter_RoundTripConversion_DoubleToStringObjectToString_IsCorrect ()
virtual void SpecificTypeConverter_RoundTripConversion_ClassToClassObjectToClass_IsCorrect ()
virtual void SpecificTypeConverter_RoundTripConversion_DerivedClassToBaseClassObjectToBaseClass_IsCorrect ()
virtual void SpecificTypeConverter_Speed_RoundTripConversion_IntToIntObjectToInt_IsCorrect ()
virtual void SpecificTypeConverter_Speed_RoundTripConversion_IntToDoubleObjectToInt_IsCorrect ()
virtual void SpecificTypeConverter_Speed_RoundTripConversion_DoubleToIntObjectToDouble_IsCorrect ()
virtual void SpecificTypeConverter_Speed_RoundTripConversion_DoubleToStringObjectToDouble_IsCorrect ()
virtual void SpecificTypeConverter_Speed_RoundTripConversion_DerivedClassToBaseClassObjectToBaseClass_IsCorrect ()
Protected Member Functions inherited from IGLib.Core.Tests.TypeConverterTestsBase< BasicTypeConverterTests >
void TypeConverter_Speed_ConversionToObjectAndBackTest< OriginalType > (ITypeConverter typeConverter, int numExecutions, double minExecutionsPerSecond, OriginalType original, bool restoreObjectBackToValue=true, bool doOutputInReferenceTest=false)
Like TypeConverter_Speed_ConversionToObjectAndBackTest<OriginalType, TargetType, RestoredType>(ITypeConverter, int, double, OriginalType, TargetType, RestoredType, bool), but with target type and the type of restored variable both equal to type of the original variable, and also the expected assiged object value and the restored value being equal to the original value.
Properties
override ITypeConverter TypeConverter = new CollectionTypeConverter() [get]
The type converter that is under test.
Properties inherited from IGLib.Core.Tests.BasicTypeConverterTests
virtual ITypeConverter TypeConverter = new BasicTypeConverter() [get]
The type converter that is under test.
virtual int NumExecutions = 1_000 [get]
Number of executions in speed tests.
virtual double MinPerSecond = 10_000 [get]
Minimum required number of executions per second in speed tests.
Additional Inherited Members
Protected Attributes inherited from IGLib.Core.Tests.TypeConverterTestsBase< BasicTypeConverterTests >
CommonType Coverted
Like TypeConverter_ConversionToObjectAndBackTest<OriginalType, TargetType, RestoredType>(OriginalType, RestoredType), but with target type and the type of restored variable both equal to type of the original variable, and also the expected assigned object value and the expected restored value being equal to the original value.
TargetType Converted
Performs test of conversion via ITypeConverter from a value of type OriginalType to a value of the target type TargetType to be assigned to a variable of type object, and then converts this value to type RestoredType and copies (restores) it to a variable of that type.
Detailed Description
Tests of the basic type converter (BasicTypeConverter, implementation of the ITypeConverter interface).
Definition at line 22 of file CollectionTypeConverterTests .cs.
Constructor & Destructor Documentation
CollectionTypeConverterTests()
IGLib.Core.Tests.CollectionTypeConverterTests.CollectionTypeConverterTests (ITestOutputHelper output) inline
Definition at line 25 of file CollectionTypeConverterTests .cs.
Member Function Documentation
SpecificTypeConverter_CollectionRoundTripConversion_IntIListToIntIEnumerableObjectToIntArray()
virtual void IGLib.Core.Tests.CollectionTypeConverterTests.SpecificTypeConverter_CollectionRoundTripConversion_IntIListToIntIEnumerableObjectToIntArray () inline protected virtual
Currently, conversions to IEnumerable{T} are not possible. Instead, conversions to List{T} can be used.
Definition at line 39 of file CollectionTypeConverterTests .cs.
References IGLib.Core.Tests.CollectionTypeConverterTests.TypeConverter.
SpecificTypeConverter_CollectionRoundTripConversion_IntArrayToIntIEnumerableObjectToIntIList()
virtual void IGLib.Core.Tests.CollectionTypeConverterTests.SpecificTypeConverter_CollectionRoundTripConversion_IntArrayToIntIEnumerableObjectToIntIList () inline protected virtual
Currently, conversions to IEnumerable{T} are not possible. Instead, conversions to List{T} can be used.
Definition at line 51 of file CollectionTypeConverterTests .cs.
References IGLib.Core.Tests.CollectionTypeConverterTests.TypeConverter.
SpecificTypeConverter_CollectionRoundTripConversion_IntIListToIntArrayObjectToIntIList()
virtual void IGLib.Core.Tests.CollectionTypeConverterTests.SpecificTypeConverter_CollectionRoundTripConversion_IntIListToIntArrayObjectToIntIList () inline protected virtual
Definition at line 62 of file CollectionTypeConverterTests .cs.
References IGLib.Core.Tests.CollectionTypeConverterTests.TypeConverter.
SpecificTypeConverter_CollectionRoundTripConversion_IntIEnumerableToIntListObjectToIntArray()
virtual void IGLib.Core.Tests.CollectionTypeConverterTests.SpecificTypeConverter_CollectionRoundTripConversion_IntIEnumerableToIntListObjectToIntArray () inline protected virtual
Definition at line 95 of file CollectionTypeConverterTests .cs.
References IGLib.Core.Tests.CollectionTypeConverterTests.TypeConverter.
SpecificTypeConverter_CollectionRoundTripConversion_IntIEnumerableToIntArrayObjectToIntList()
virtual void IGLib.Core.Tests.CollectionTypeConverterTests.SpecificTypeConverter_CollectionRoundTripConversion_IntIEnumerableToIntArrayObjectToIntList () inline protected virtual
Definition at line 126 of file CollectionTypeConverterTests .cs.
References IGLib.Core.Tests.CollectionTypeConverterTests.TypeConverter.
SpecificTypeConverter_CollectionRoundTripConversion_IntIListToIntArrayObjectToIntList()
virtual void IGLib.Core.Tests.CollectionTypeConverterTests.SpecificTypeConverter_CollectionRoundTripConversion_IntIListToIntArrayObjectToIntList () inline protected virtual
Definition at line 159 of file CollectionTypeConverterTests .cs.
References IGLib.Core.Tests.CollectionTypeConverterTests.TypeConverter.
SpecificTypeConverter_CollectionRoundTripConversion_IntArrayToIntListObjectToIntArray()
virtual void IGLib.Core.Tests.CollectionTypeConverterTests.SpecificTypeConverter_CollectionRoundTripConversion_IntArrayToIntListObjectToIntArray () inline protected virtual
Definition at line 193 of file CollectionTypeConverterTests .cs.
References IGLib.Core.Tests.CollectionTypeConverterTests.TypeConverter.
SpecificTypeConverter_CollectionRoundTripConversion_IntArrayToIntIListObjectToIntArray()
virtual void IGLib.Core.Tests.CollectionTypeConverterTests.SpecificTypeConverter_CollectionRoundTripConversion_IntArrayToIntIListObjectToIntArray () inline protected virtual
Currently, conversions to IEnumerable{T} are not possible. Instead, conversions to List{T} or T[] can be used.
Definition at line 226 of file CollectionTypeConverterTests .cs.
References IGLib.Core.Tests.CollectionTypeConverterTests.TypeConverter.
SpecificTypeConverter_CollectionRoundTripConversion_IntArray2DToIntArrayObjectToIntList()
virtual void IGLib.Core.Tests.CollectionTypeConverterTests.SpecificTypeConverter_CollectionRoundTripConversion_IntArray2DToIntArrayObjectToIntList () inline protected virtual
Definition at line 261 of file CollectionTypeConverterTests .cs.
References IGLib.Core.Tests.CollectionTypeConverterTests.TypeConverter.
SpecificTypeConverter_CollectionRoundTripConversion_IntArray3DToIntIListObjectToIntArray()
virtual void IGLib.Core.Tests.CollectionTypeConverterTests.SpecificTypeConverter_CollectionRoundTripConversion_IntArray3DToIntIListObjectToIntArray () inline protected virtual
Definition at line 298 of file CollectionTypeConverterTests .cs.
References IGLib.Core.Tests.CollectionTypeConverterTests.TypeConverter.
SpecificTypeConverter_CollectionRoundTripConversion_IntArray3DToIntListObjectToIntArray()
virtual void IGLib.Core.Tests.CollectionTypeConverterTests.SpecificTypeConverter_CollectionRoundTripConversion_IntArray3DToIntListObjectToIntArray () inline protected virtual
Definition at line 335 of file CollectionTypeConverterTests .cs.
References IGLib.Core.Tests.CollectionTypeConverterTests.TypeConverter.
SpecificTypeConverter_CollectionRoundTripConversion_IntArray3DToIntIEnumerableObjectToIntArray()
virtual void IGLib.Core.Tests.CollectionTypeConverterTests.SpecificTypeConverter_CollectionRoundTripConversion_IntArray3DToIntIEnumerableObjectToIntArray () inline protected virtual
Definition at line 372 of file CollectionTypeConverterTests .cs.
References IGLib.Core.Tests.CollectionTypeConverterTests.TypeConverter.
SpecificTypeConverter_CollectionRoundTripConversion_IntArray2DToIntArray2DObjectToIntArray2D()
virtual void IGLib.Core.Tests.CollectionTypeConverterTests.SpecificTypeConverter_CollectionRoundTripConversion_IntArray2DToIntArray2DObjectToIntArray2D () inline protected virtual
Definition at line 415 of file CollectionTypeConverterTests .cs.
References IGLib.Core.Tests.CollectionTypeConverterTests.TypeConverter.
SpecificTypeConverter_CollectionRoundTripConversion_IntArray3DToIntArray3DObjectToIntArray3D()
virtual void IGLib.Core.Tests.CollectionTypeConverterTests.SpecificTypeConverter_CollectionRoundTripConversion_IntArray3DToIntArray3DObjectToIntArray3D () inline protected virtual
Definition at line 450 of file CollectionTypeConverterTests .cs.
References IGLib.Core.Tests.CollectionTypeConverterTests.TypeConverter.
SpecificTypeConverter_CollectionRoundTripConversion_IntJaggedArrayNonrectangular2DToIntArrayObjectToIntList()
virtual void IGLib.Core.Tests.CollectionTypeConverterTests.SpecificTypeConverter_CollectionRoundTripConversion_IntJaggedArrayNonrectangular2DToIntArrayObjectToIntList () inline protected virtual
Definition at line 504 of file CollectionTypeConverterTests .cs.
References IGLib.Core.Tests.CollectionTypeConverterTests.TypeConverter.
SpecificTypeConverter_CollectionRoundTripConversion_IntJaggedArrayNonrectangular3DToIntIListObjectToIntArray()
virtual void IGLib.Core.Tests.CollectionTypeConverterTests.SpecificTypeConverter_CollectionRoundTripConversion_IntJaggedArrayNonrectangular3DToIntIListObjectToIntArray () inline protected virtual
Definition at line 547 of file CollectionTypeConverterTests .cs.
References IGLib.Core.Tests.CollectionTypeConverterTests.TypeConverter.
SpecificTypeConverter_CollectionRoundTripConversion_IntJaggedArrayNonrectangular3DToIntIEnumerableObjectToIntArray()
virtual void IGLib.Core.Tests.CollectionTypeConverterTests.SpecificTypeConverter_CollectionRoundTripConversion_IntJaggedArrayNonrectangular3DToIntIEnumerableObjectToIntArray () inline protected virtual
Definition at line 593 of file CollectionTypeConverterTests .cs.
References IGLib.Core.Tests.CollectionTypeConverterTests.TypeConverter.
SpecificTypeConverter_CollectionRoundTripConversion_IntJaggedArray2DToIntJaggedArray2DObjectToIntJaggedArray2D()
virtual void IGLib.Core.Tests.CollectionTypeConverterTests.SpecificTypeConverter_CollectionRoundTripConversion_IntJaggedArray2DToIntJaggedArray2DObjectToIntJaggedArray2D () inline protected virtual
Definition at line 643 of file CollectionTypeConverterTests .cs.
References IGLib.Core.Tests.CollectionTypeConverterTests.TypeConverter.
SpecificTypeConverter_CollectionRoundTripConversion_IntJaggedArray3DToIntJaggedArray3DObjectToIntJaggedArray3D()
virtual void IGLib.Core.Tests.CollectionTypeConverterTests.SpecificTypeConverter_CollectionRoundTripConversion_IntJaggedArray3DToIntJaggedArray3DObjectToIntJaggedArray3D () inline protected virtual
Definition at line 684 of file CollectionTypeConverterTests .cs.
References IGLib.Core.Tests.CollectionTypeConverterTests.TypeConverter.
SpecificTypeConverter_CollectionRoundTripConversion_IntJaggedArray3DToIntArray3DObjectToIntJaggedArray3D()
virtual void IGLib.Core.Tests.CollectionTypeConverterTests.SpecificTypeConverter_CollectionRoundTripConversion_IntJaggedArray3DToIntArray3DObjectToIntJaggedArray3D () inline protected virtual
Definition at line 752 of file CollectionTypeConverterTests .cs.
References IGLib.Core.Tests.CollectionTypeConverterTests.TypeConverter.
SpecificTypeConverter_CollectionRoundTripConversion_IntArray3DToIntJaggedArray3DObjectToIntArray3D()
virtual void IGLib.Core.Tests.CollectionTypeConverterTests.SpecificTypeConverter_CollectionRoundTripConversion_IntArray3DToIntJaggedArray3DObjectToIntArray3D () inline protected virtual
Definition at line 831 of file CollectionTypeConverterTests .cs.
References IGLib.Core.Tests.CollectionTypeConverterTests.TypeConverter.
Property Documentation
TypeConverter
override ITypeConverter IGLib.Core.Tests.CollectionTypeConverterTests.TypeConverter = new CollectionTypeConverter() get protected
The type converter that is under test.
Definition at line 30 of file CollectionTypeConverterTests .cs.
Referenced by IGLib.Core.Tests.CollectionTypeConverterTests.SpecificTypeConverter_CollectionRoundTripConversion_IntArray2DToIntArray2DObjectToIntArray2D(), IGLib.Core.Tests.CollectionTypeConverterTests.SpecificTypeConverter_CollectionRoundTripConversion_IntArray2DToIntArrayObjectToIntList(), IGLib.Core.Tests.CollectionTypeConverterTests.SpecificTypeConverter_CollectionRoundTripConversion_IntArray3DToIntArray3DObjectToIntArray3D(), IGLib.Core.Tests.CollectionTypeConverterTests.SpecificTypeConverter_CollectionRoundTripConversion_IntArray3DToIntIEnumerableObjectToIntArray(), IGLib.Core.Tests.CollectionTypeConverterTests.SpecificTypeConverter_CollectionRoundTripConversion_IntArray3DToIntIListObjectToIntArray(), IGLib.Core.Tests.CollectionTypeConverterTests.SpecificTypeConverter_CollectionRoundTripConversion_IntArray3DToIntJaggedArray3DObjectToIntArray3D(), IGLib.Core.Tests.CollectionTypeConverterTests.SpecificTypeConverter_CollectionRoundTripConversion_IntArray3DToIntListObjectToIntArray(), IGLib.Core.Tests.CollectionTypeConverterTests.SpecificTypeConverter_CollectionRoundTripConversion_IntArrayToIntIEnumerableObjectToIntIList(), IGLib.Core.Tests.CollectionTypeConverterTests.SpecificTypeConverter_CollectionRoundTripConversion_IntArrayToIntIListObjectToIntArray(), IGLib.Core.Tests.CollectionTypeConverterTests.SpecificTypeConverter_CollectionRoundTripConversion_IntArrayToIntListObjectToIntArray(), IGLib.Core.Tests.CollectionTypeConverterTests.SpecificTypeConverter_CollectionRoundTripConversion_IntIEnumerableToIntArrayObjectToIntList(), IGLib.Core.Tests.CollectionTypeConverterTests.SpecificTypeConverter_CollectionRoundTripConversion_IntIEnumerableToIntListObjectToIntArray(), IGLib.Core.Tests.CollectionTypeConverterTests.SpecificTypeConverter_CollectionRoundTripConversion_IntIListToIntArrayObjectToIntIList(), IGLib.Core.Tests.CollectionTypeConverterTests.SpecificTypeConverter_CollectionRoundTripConversion_IntIListToIntArrayObjectToIntList(), IGLib.Core.Tests.CollectionTypeConverterTests.SpecificTypeConverter_CollectionRoundTripConversion_IntIListToIntIEnumerableObjectToIntArray(), IGLib.Core.Tests.CollectionTypeConverterTests.SpecificTypeConverter_CollectionRoundTripConversion_IntJaggedArray2DToIntJaggedArray2DObjectToIntJaggedArray2D(), IGLib.Core.Tests.CollectionTypeConverterTests.SpecificTypeConverter_CollectionRoundTripConversion_IntJaggedArray3DToIntArray3DObjectToIntJaggedArray3D(), IGLib.Core.Tests.CollectionTypeConverterTests.SpecificTypeConverter_CollectionRoundTripConversion_IntJaggedArray3DToIntJaggedArray3DObjectToIntJaggedArray3D(), IGLib.Core.Tests.CollectionTypeConverterTests.SpecificTypeConverter_CollectionRoundTripConversion_IntJaggedArrayNonrectangular2DToIntArrayObjectToIntList(), IGLib.Core.Tests.CollectionTypeConverterTests.SpecificTypeConverter_CollectionRoundTripConversion_IntJaggedArrayNonrectangular3DToIntIEnumerableObjectToIntArray(), and IGLib.Core.Tests.CollectionTypeConverterTests.SpecificTypeConverter_CollectionRoundTripConversion_IntJaggedArrayNonrectangular3DToIntIListObjectToIntArray().
The documentation for this class was generated from the following file:
IGLibGraphics3D/tests/IGLib.Graphics3D.Tests/other/TypeConversion/CollectionTypeConverterTests .cs