Doc: IGLib with source files: IG.Lib.IWaitCondition Interface Reference
IG.Lib.IWaitCondition Interface Reference
Interface for classes that implement blocking until a specified condition is met.
Public Member Functions
bool Condition ()
Returns true if unblocking condition is satisfied, and false otherwise.
void CancelOne ()
Cancels the current waiting for the condition (if one is going on) on one thread and unblocks the thread on which waiting was called (possibly with some latency).
void CancelAll ()
Cancel the current waiting for the condition on all threads.
void Wait ()
Blocks until the specified condition gets satisfied. See class description for details.
Properties
bool IsWaiting [get]
Returns true if waiting for unblocking condition is currently performed, and false otherwise. Setting should only be done within the waiting function.
Properties inherited from IG.Lib.ILockable
object Lock [get]
Detailed Description
Interface for classes that implement blocking until a specified condition is met.
$A Igor Jun10;
Definition at line 18 of file WaitCondition.cs.
Member Function Documentation
Condition()
bool IG.Lib.IWaitCondition.Condition ()
Returns true if unblocking condition is satisfied, and false otherwise.
Implemented in IG.Lib.WaitDirectoryRemovalLatence, IG.Lib.WaitDirectoryCreationLatence, IG.Lib.WaitFileRemovalLatence, IG.Lib.WaitFileCreationLatence, IG.Lib.WaitFileEventLatenceBase, IG.Lib.WaitFileEventBaseByProxyLatence, IG.Lib.WaitDirectoryRemoval, IG.Lib.WaitDirectoryCreation, IG.Lib.WaitFileRemoval, IG.Lib.WaitFileCreation, IG.Lib.WaitFileEventBase, IG.Lib.WaitCondition, and IG.Lib.WaitConditionBase.
CancelOne()
void IG.Lib.IWaitCondition.CancelOne ()
Cancels the current waiting for the condition (if one is going on) on one thread and unblocks the thread on which waiting was called (possibly with some latency).
Implemented in IG.Lib.WaitFileEventBaseByProxyLatence, IG.Lib.WaitFileEventBase, and IG.Lib.WaitConditionBase.
Referenced by IG.Lib.WaitFileEventLatenceBase.ExampleLatence.AlternateCreateRemoveExample().
CancelAll()
void IG.Lib.IWaitCondition.CancelAll ()
Cancel the current waiting for the condition on all threads.
Implemented in IG.Lib.WaitFileEventBase, and IG.Lib.WaitConditionBase.
Wait()
void IG.Lib.IWaitCondition.Wait ()
Blocks until the specified condition gets satisfied. See class description for details.
This method will normally not be overridden, except with intention to change the condition check time plan. When overriding, use the original method as template.
Implemented in IG.Lib.WaitFileEventBaseByProxyLatence, IG.Lib.WaitDirectoryRemoval, IG.Lib.WaitDirectoryCreation, IG.Lib.WaitFileRemoval, IG.Lib.WaitFileCreation, IG.Lib.WaitFileEventBase, IG.Lib.WaitCondition, and IG.Lib.WaitConditionBase.
Referenced by IG.Lib.WaitFileEventLatenceBase.ExampleLatence.ExampleBlockCreateRemove(), and IG.Lib.WaitFileEventLatenceBase.ExampleLatence.TestSpeedBlockCreateRemove().
Property Documentation
IsWaiting
bool IG.Lib.IWaitCondition.IsWaiting get
Returns true if waiting for unblocking condition is currently performed, and false otherwise. Setting should only be done within the waiting function.
Definition at line 26 of file WaitCondition.cs.
Referenced by IG.Lib.WaitCondition.ToString(), and IG.Lib.WaitCondition.Wait().
The documentation for this interface was generated from the following file:
iglib/igbase/0unsorted/WaitCondition.cs