Doc: IGLib with source files: IG.Lib.SerializationDtoBase< Type, BaseType > Class Template Reference
IG.Lib.SerializationDtoBase< Type, BaseType > Class Template Reference abstract
Generic base class for Data Transfer Objects (DTO). This class is used as template for producing concrete DTO classes. Such DTOs are used for serialization and deserialization of state of various kinds of objects that need to be transfered between applications, across platforms, or simply stored in files for future use. WARNING: In most cases ISerializationDto type will be used. Different BaseType and Type are used only in relatively rare cases where different derived types all have the same data that is copied to DTO. Otherwise the advantage of this can not be used because of single inheritance.
Public Member Functions
SerializationDtoBase ()
virtual bool GetNull ()
Returns a flag indicating whether the object represented by the current DTO is null.
virtual void SetNull (bool isNull)
Sets a flag indicating whether the object represented by the current DTO is null.
abstract Type CreateObject ()
Creates and returns a new object of the type whose data is represented by the current DTO (Data Transfer Object). WARNING: Implement thread locking in overriding functions!
virtual void CopyFromBase (BaseType obj)
Copies data to the current DTO from an object of type BaseType.
virtual void CopyToBase (ref BaseType obj)
Copies data from the current DTO to an object of the base type. Object is created anew if necessary by using the CreateObject() method.
virtual void CopyFrom (Type obj)
Copies data to the current DTO from an object of type Type.
virtual void CopyTo (ref Type obj)
Copies data from the current DTO to an object of type Type. Object is created anew if necessary by using the CreateObject() method.
virtual void CopyFromObject (object obj)
Copies data to the current DTO from an object of type object. The necessary casts are performed.
virtual void CopyToObject (ref object obj)
Copies data from the current DTO to an object of type object. Object is created anew if necessary by using the CreateObject() method. The necessary casts are performed.
override string ToString ()
Creates and returns string representation of the current DTO (data transfer object).
Protected Member Functions
abstract void CopyFromPlain (BaseType obj)
Copies contents of the specified object to the current DTO (Data Transfer Object).
abstract void CopyToPlain (ref BaseType obj)
Copies contents of the current DTO (Data Transfer Object) to the specified object.
Protected Attributes
bool _isNull = false
Properties
object Lock [get]
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
Properties inherited from IG.Lib.ILockable
object Lock [get]
Private Attributes
object _mainLock = new object()
Detailed Description
Generic base class for Data Transfer Objects (DTO). This class is used as template for producing concrete DTO classes. Such DTOs are used for serialization and deserialization of state of various kinds of objects that need to be transfered between applications, across platforms, or simply stored in files for future use. WARNING: In most cases ISerializationDto type will be used. Different BaseType and Type are used only in relatively rare cases where different derived types all have the same data that is copied to DTO. Otherwise the advantage of this can not be used because of single inheritance.
Template Parameters
Type Type for which DTO is used.
BaseType Base type of the type for which DTO is used, and on which copy operations will be defined. In this way, we can avoid defining these operations for each specific type, but only define them for a specific type, since operations may be similar for all derived types.
There is an agreement that all derived classes must have a public argument-less (default) constructor. Generic classes are usually not used for serialization/deserialization. Only derived types where both type parameters are fixed are normally used for this purpos. IMPORTANT: Base type is used just for being able to define copying operations only once - for the base type - and using it for different derived types. In many occasions this will not be needed, and in these occasions one should just use the derived type that does not have base type as type parameter.
$A Igor Jun09;
Type Constraints
BaseType : class
Type : class
Type : BaseType
Definition at line 461 of file SerializationDtoBase.cs.
Constructor & Destructor Documentation
SerializationDtoBase()
IG.Lib.SerializationDtoBase< Type, BaseType >.SerializationDtoBase () inline
Definition at line 466 of file SerializationDtoBase.cs.
Member Function Documentation
GetNull()
virtual bool IG.Lib.SerializationDtoBase< Type, BaseType >.GetNull () inline virtual
Returns a flag indicating whether the object represented by the current DTO is null.
Returns
Flag indicating whether the object represented by the current DTO is null.
Implementing this as a function rather than a property prevents serialization of the flag, since the flag isn't meant to contain data, but to instruct operations that the object represented by the current DTO is null. This is useful in some scenarios where non-null DTOs are needed for null objects.
Definition at line 479 of file SerializationDtoBase.cs.
Referenced by IG.Lib.SerializationDtoBase< ElementType[], ElementType[]>.CopyTo(), IG.Lib.SerializationDtoBase< ElementType[], ElementType[]>.CopyToBase(), and IG.Lib.SerializationDtoBase< ElementType[], ElementType[]>.CopyToObject().
SetNull()
virtual void IG.Lib.SerializationDtoBase< Type, BaseType >.SetNull (bool isNull) inline virtual
Sets a flag indicating whether the object represented by the current DTO is null.
Parameters
isNull If true, this flag indicates that the object represented by the current DTO is null, although the DTO itself is not null.
Implementing this as a function rather than a property prevents serialization of the flag, since the flag isn't meant to contain data, but to instruct operations that the object represented by the current DTO is null. This is useful in some scenarios where non-null DTOs are needed for null objects.
Definition at line 491 of file SerializationDtoBase.cs.
Referenced by IG.Lib.SerializationDtoBase< ElementType[], ElementType[]>.CopyFromBase().
CreateObject()
abstract Type IG.Lib.SerializationDtoBase< Type, BaseType >.CreateObject () pure virtual
Creates and returns a new object of the type whose data is represented by the current DTO (Data Transfer Object). WARNING: Implement thread locking in overriding functions!
Therad locking should be performed in overriding functions!
Implemented in IG.Num.NeuralApproximatorDtoBase< Type >, IG.Num.InputOutputElementDefinitionDto< ElementType >, IG.Num.VectorFunctionScriptDtoBase< FunctionControllerType, ScalarFunctionControllerType, ScalarFunctionDtoType >, IG.Lib.MatrixDtoBase< MatrixType >, IG.Lib.VectorDtoBase< VectorType >, IG.Num.ScalarFunctionScriptDtoBase< FunctionControllerType >, IG.Num.AnalysisRequestDto, IG.Lib.BoundingBoxDtoBase< BoxType >, IG.Lib.ArrayDto< ElementType, ElementBaseType, ElementDtoType >, IG.Num.VectorFunctionRequestDTO, and IG.Neural.MapNeuralImputOutputElementDefinitionDto< ElementType >.
Referenced by IG.Lib.SerializationDtoBase< ElementType[], ElementType[]>.CopyToBase(), and IG.Lib.SerializationDtoBase< ElementType[], ElementType[]>.CopyToObject().
CopyFromPlain()
abstract void IG.Lib.SerializationDtoBase< Type, BaseType >.CopyFromPlain (BaseType obj) protected pure virtual
Copies contents of the specified object to the current DTO (Data Transfer Object).
Parameters
obj Object whose data is copied.
If the specified object is null then the _isNull property of the current DTO is set to true. Therad locking is usually not needed in overriding functions because it is normally implemeted in calling functions.
Referenced by IG.Lib.SerializationDtoBase< ElementType[], ElementType[]>.CopyFrom(), and IG.Lib.SerializationDtoBase< ElementType[], ElementType[]>.CopyFromBase().
CopyToPlain()
abstract void IG.Lib.SerializationDtoBase< Type, BaseType >.CopyToPlain (ref BaseType obj) protected pure virtual
Copies contents of the current DTO (Data Transfer Object) to the specified object.
Parameters
obj Object that data is copied to.
If _isNull property of the current DTO is set to true then the object becomes null. Therad locking is usually not needed in overriding functions because it is normally implemeted in calling functions.
Referenced by IG.Lib.SerializationDtoBase< ElementType[], ElementType[]>.CopyToBase().
CopyFromBase()
virtual void IG.Lib.SerializationDtoBase< Type, BaseType >.CopyFromBase (BaseType obj) inline virtual
Copies data to the current DTO from an object of type BaseType.
Parameters
obj Object whose data is copied to the current DTO.
Definition at line 532 of file SerializationDtoBase.cs.
Referenced by IG.Lib.SerializationDtoBase< ElementType[], ElementType[]>.CopyFromObject().
CopyToBase()
virtual void IG.Lib.SerializationDtoBase< Type, BaseType >.CopyToBase (ref BaseType obj) inline virtual
Copies data from the current DTO to an object of the base type. Object is created anew if necessary by using the CreateObject() method.
Parameters
obj Object to which data is copied.
Definition at line 549 of file SerializationDtoBase.cs.
Referenced by IG.Lib.SerializationDtoBase< ElementType[], ElementType[]>.CopyTo(), and IG.Lib.SerializationDtoBase< ElementType[], ElementType[]>.CopyToObject().
CopyFrom()
virtual void IG.Lib.SerializationDtoBase< Type, BaseType >.CopyFrom (Type obj) inline virtual
Copies data to the current DTO from an object of type Type.
Parameters
obj Object whose data is copied to the current DTO.
Definition at line 567 of file SerializationDtoBase.cs.
Referenced by IG.Num.SampledDataElementDto.CopyFromPlain(), IG.Num.VectorFunctionRequestDTO.CopyFromPlain(), IG.Num.AnalysisRequestDto.CopyFromPlain(), IG.Num.VectorFunctionResultsDto.CopyFromPlain(), IG.Num.NeuralApproximatorDtoBase< NeuralApproximatorAforgeFake >.CopyFromPlain(), IG.Num.AnalysisResultsDto.CopyFromPlain(), IG.Num.NeuralTrainingParametersDto.CopyFromPlain(), IG.Num.NeuralTrainingLimitsDto.CopyFromPlain(), IG.Num.NeuralApproximatorBase.ExampleSaveNetwork(), IG.Num.AnalysisResults.SaveJson(), IG.Num.NeuralApproximatorBase.SaveJson(), IG.Num.VectorBase.SaveJson(), IG.Num.MatrixBase.SaveJson(), IG.Num.AnalysisResults.SaveRequestJson(), IG.Num.OptFileManager.WriteAnalysisInputJson(), and IG.Num.OptFileManager.WriteAnalysisOutputJson().
CopyTo()
virtual void IG.Lib.SerializationDtoBase< Type, BaseType >.CopyTo (ref Type obj) inline virtual
Copies data from the current DTO to an object of type Type. Object is created anew if necessary by using the CreateObject() method.
Parameters
obj Object to which data is copied.
Definition at line 578 of file SerializationDtoBase.cs.
Referenced by IG.Num.SampledDataElementDto.CopyToPlain(), IG.Num.VectorFunctionRequestDTO.CopyToPlain(), IG.Num.AnalysisRequestDto.CopyToPlain(), IG.Num.VectorFunctionResultsDto.CopyToPlain(), IG.Num.NeuralApproximatorDtoBase< NeuralApproximatorAforgeFake >.CopyToPlain(), IG.Num.AnalysisResultsDto.CopyToPlain(), IG.Num.NeuralTrainingParametersDto.CopyToPlain(), IG.Num.NeuralTrainingLimitsDto.CopyToPlain(), IG.Num.AnalysisResults.LoadJson(), IG.Num.NeuralApproximatorBase.LoadJson(), IG.Num.VectorBase.LoadJson(), IG.Num.MatrixBase.LoadJson(), IG.Num.AnalysisResults.LoadRequestJson(), IG.Num.OptFileManager.ReadAnalysisInputJson(), IG.Num.OptFileManager.ReadAnalysisOutputJson(), and IG.Lib.SerializationDtoBase< ElementType[], ElementType[]>.ToString().
CopyFromObject()
virtual void IG.Lib.SerializationDtoBase< Type, BaseType >.CopyFromObject (object obj) inline virtual
Copies data to the current DTO from an object of type object. The necessary casts are performed.
Parameters
obj Object whose data is copied to the current DTO.
Definition at line 593 of file SerializationDtoBase.cs.
CopyToObject()
virtual void IG.Lib.SerializationDtoBase< Type, BaseType >.CopyToObject (ref object obj) inline virtual
Copies data from the current DTO to an object of type object. Object is created anew if necessary by using the CreateObject() method. The necessary casts are performed.
Parameters
obj Object to which data is copied.
Definition at line 603 of file SerializationDtoBase.cs.
ToString()
override string IG.Lib.SerializationDtoBase< Type, BaseType >.ToString () inline
Creates and returns string representation of the current DTO (data transfer object).
This is a generic method that first copies DTO to an object that it represents, and then calls the ToString() method of that object. This solution is slow, but this method usually does not need to be faster because ToString() method is usually only used for tests of this kind of classes.
Definition at line 706 of file SerializationDtoBase.cs.
Member Data Documentation
_isNull
bool IG.Lib.SerializationDtoBase< Type, BaseType >._isNull = false protected
Definition at line 471 of file SerializationDtoBase.cs.
Referenced by IG.Lib.SerializationDtoBase< ElementType[], ElementType[]>.GetNull().
_mainLock
object IG.Lib.SerializationDtoBase< Type, BaseType >._mainLock = new object() private
Definition at line 498 of file SerializationDtoBase.cs.
Property Documentation
Lock
object IG.Lib.SerializationDtoBase< Type, BaseType >.Lock get
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
Definition at line 503 of file SerializationDtoBase.cs.
Referenced by IG.Lib.SerializationDtoBase< ElementType[], ElementType[]>.CopyFrom(), IG.Lib.SerializationDtoBase< ElementType[], ElementType[]>.CopyFromBase(), IG.Lib.SerializationDtoBase< ElementType[], ElementType[]>.CopyToBase(), IG.Lib.SerializationDtoBase< ElementType[], ElementType[]>.CopyToObject(), IG.Lib.SerializationDtoBase< ElementType[], ElementType[]>.GetNull(), and IG.Lib.SerializationDtoBase< ElementType[], ElementType[]>.SetNull().
The documentation for this class was generated from the following file:
iglib/igbase/data/serialization/SerializationDtoBase.cs