Doc: IGLib with source files: IG.Lib.WaitFileEventLatenceBase.ExampleLatence Class Reference
IG.Lib.WaitFileEventLatenceBase.ExampleLatence Class Reference
Class containing examples for
Public Member Functions
void ExampleBlockCreateRemove (string filePath)
Monitors the specified file and successively blocks until it is created and then until it is removed. This procedure is repeated twice.
void ExampleBlockCreateRemove (string filePath, int numSwitches)
Monitors the specified file and successively blocks until it is created and then until it is removed.
void ExampleBlockCreateRemove (string filePath, int numSwitches, bool waitDirectory)
Monitors the specified file and successively blocks until it is created and then until it is removed.
void TestSpeedBlockCreateRemove (string filePath)
Test of speed of reaction of file/directory creation and removal blocking waits. A specified number of alternate creations and removals are perfomed in a parallel thread, with specified delay between them. In the main thread, blocking waits are performed waiting for creation/removal in an infinite loop, and it is counted how many events are captured and how many are missed.
void TestSpeedBlockCreateRemove (string filePath, int numSwitches, int sleepMs)
Test of speed of reaction of file/directory creation and removal blocking waits. A specified number of alternate creations and removals are perfomed in a parallel thread, with specified delay between them. In the main thread, blocking waits are performed waiting for creation/removal in an infinite loop, and it is counted how many events are captured and how many are missed.
void TestSpeedBlockCreateRemove (string filePath, int numSwitches, int sleepMs, bool waitDirectory)
Test of speed of reaction of file/directory creation and removal blocking waits. A specified number of alternate creations and removals are perfomed in a parallel thread, with specified delay between them. In the main thread, blocking waits are performed waiting for creation/removal in an infinite loop, and it is counted how many events are captured and how many are missed.
Protected Attributes
IWaitFileEvent _creation = null
string ExamplePath
bool IsDirectory
bool TthreadStopped
int NumIterations
int SleepTimeMs
double TestTime
object fileOperationLock = new object()
Lock for file creation and removal operations.
Properties
virtual IWaitFileEvent Creation [get]
virtual IWaitFileEvent Removal [get]
Private Member Functions
void AlternateCreateRemoveExample ()
Alternately creates and removes the specified file or directory in its own thread.
Private Attributes
object lockExample = new object()
IWaitFileEvent _removal = null
Detailed Description
Class containing examples for
Definition at line 1117 of file WaitConditionFile.cs.
Member Function Documentation
ExampleBlockCreateRemove() [1/3]
void IG.Lib.WaitFileEventLatenceBase.ExampleLatence.ExampleBlockCreateRemove (string filePath) inline
Monitors the specified file and successively blocks until it is created and then until it is removed. This procedure is repeated twice.
Parameters
filePath File whose creation and removal is monitored.
Definition at line 1177 of file WaitConditionFile.cs.
References IG.Lib.WaitFileEventLatenceBase.ExampleLatence.lockExample.
Referenced by IG.Lib.WaitFileEventBase.ExampleBlockCreateRemove(), IG.Lib.WaitFileEventLatenceBase.ExampleLatence.ExampleBlockCreateRemove(), and IG.Lib.WaitFileEventLatenceBase.ExampleBlockCreateRemoveLatence().
ExampleBlockCreateRemove() [2/3]
void IG.Lib.WaitFileEventLatenceBase.ExampleLatence.ExampleBlockCreateRemove (string filePath, int numSwitches) inline
Monitors the specified file and successively blocks until it is created and then until it is removed.
Parameters
filePath File whose creation and removal is monitored.
numSwitches Number of iterations (creation/removal waits).
Definition at line 1189 of file WaitConditionFile.cs.
References IG.Lib.WaitFileEventLatenceBase.ExampleLatence.ExampleBlockCreateRemove(), and IG.Lib.WaitFileEventLatenceBase.ExampleLatence.lockExample.
ExampleBlockCreateRemove() [3/3]
void IG.Lib.WaitFileEventLatenceBase.ExampleLatence.ExampleBlockCreateRemove (string filePath, int numSwitches, bool waitDirectory) inline
Monitors the specified file and successively blocks until it is created and then until it is removed.
Parameters
filePath File whose creation and removal is monitored.
numSwitches Number of iterations (creation/removal waits).
waitDirectory If true then creation/removal of a directory is waiting.
Definition at line 1202 of file WaitConditionFile.cs.
References IG.Lib.WaitFileEventLatenceBase.ExampleLatence.Creation, IG.Lib.WaitFileEventLatenceBase.ExampleLatence.lockExample, IG.Lib.WaitFileEventLatenceBase.ExampleLatence.Removal, and IG.Lib.IWaitCondition.Wait().
AlternateCreateRemoveExample()
void IG.Lib.WaitFileEventLatenceBase.ExampleLatence.AlternateCreateRemoveExample () inline private
Alternately creates and removes the specified file or directory in its own thread.
Definition at line 1252 of file WaitConditionFile.cs.
References IG.Lib.IWaitCondition.CancelOne(), IG.Lib.WaitFileEventLatenceBase.ExampleLatence.Creation, IG.Lib.WaitFileEventLatenceBase.ExampleLatence.ExamplePath, IG.Lib.WaitFileEventLatenceBase.ExampleLatence.fileOperationLock, IG.Lib.WaitFileEventLatenceBase.ExampleLatence.IsDirectory, IG.Lib.WaitFileEventLatenceBase.ExampleLatence.NumIterations, IG.Lib.WaitFileEventLatenceBase.ExampleLatence.Removal, IG.Lib.StopWatch1.Reset(), IG.Lib.WaitFileEventLatenceBase.ExampleLatence.SleepTimeMs, IG.Lib.StopWatch1.Start(), IG.Lib.StopWatch1.Stop(), IG.Lib.WaitFileEventLatenceBase.ExampleLatence.TestTime, and IG.Lib.StopWatch1.Time.
Referenced by IG.Lib.WaitFileEventLatenceBase.ExampleLatence.TestSpeedBlockCreateRemove().
TestSpeedBlockCreateRemove() [1/3]
void IG.Lib.WaitFileEventLatenceBase.ExampleLatence.TestSpeedBlockCreateRemove (string filePath) inline
Test of speed of reaction of file/directory creation and removal blocking waits. A specified number of alternate creations and removals are perfomed in a parallel thread, with specified delay between them. In the main thread, blocking waits are performed waiting for creation/removal in an infinite loop, and it is counted how many events are captured and how many are missed.
Parameters
filePath File whose creation and removal is monitored.
Definition at line 1303 of file WaitConditionFile.cs.
Referenced by IG.Lib.WaitFileEventBase.TestSpeedBlockCreateRemove(), IG.Lib.WaitFileEventLatenceBase.ExampleLatence.TestSpeedBlockCreateRemove(), and IG.Lib.WaitFileEventLatenceBase.TestSpeedBlockCreateRemoveLatence().
TestSpeedBlockCreateRemove() [2/3]
void IG.Lib.WaitFileEventLatenceBase.ExampleLatence.TestSpeedBlockCreateRemove (string filePath, int numSwitches, int sleepMs) inline
Test of speed of reaction of file/directory creation and removal blocking waits. A specified number of alternate creations and removals are perfomed in a parallel thread, with specified delay between them. In the main thread, blocking waits are performed waiting for creation/removal in an infinite loop, and it is counted how many events are captured and how many are missed.
Parameters
filePath File whose creation and removal is monitored.
numSwitches Number of iterations (creation/removal waits).
sleepMs Number of milliseconds to sleep between examples.
Definition at line 1316 of file WaitConditionFile.cs.
References IG.Lib.WaitFileEventLatenceBase.ExampleLatence.TestSpeedBlockCreateRemove().
TestSpeedBlockCreateRemove() [3/3]
void IG.Lib.WaitFileEventLatenceBase.ExampleLatence.TestSpeedBlockCreateRemove (string filePath, int numSwitches, int sleepMs, bool waitDirectory) inline
Test of speed of reaction of file/directory creation and removal blocking waits. A specified number of alternate creations and removals are perfomed in a parallel thread, with specified delay between them. In the main thread, blocking waits are performed waiting for creation/removal in an infinite loop, and it is counted how many events are captured and how many are missed.
Parameters
filePath File whose creation and removal is monitored.
numSwitches Number of iterations (creation/removal waits).
sleepMs Number of milliseconds to sleep between examples.
waitDirectory If true then creation/removal of a directory is waiting.
Definition at line 1331 of file WaitConditionFile.cs.
References IG.Lib.WaitFileEventLatenceBase.ExampleLatence.AlternateCreateRemoveExample(), IG.Lib.WaitFileEventLatenceBase.ExampleLatence.Creation, IG.Lib.WaitFileEventLatenceBase.ExampleLatence.fileOperationLock, IG.Lib.WaitFileEventLatenceBase.ExampleLatence.lockExample, IG.Lib.WaitFileEventLatenceBase.ExampleLatence.Removal, IG.Lib.WaitFileEventLatenceBase.ExampleLatence.SleepTimeMs, IG.Lib.WaitFileEventLatenceBase.ExampleLatence.TestTime, and IG.Lib.IWaitCondition.Wait().
Member Data Documentation
lockExample
object IG.Lib.WaitFileEventLatenceBase.ExampleLatence.lockExample = new object() private
Definition at line 1122 of file WaitConditionFile.cs.
Referenced by IG.Lib.WaitFileEventLatenceBase.ExampleLatence.ExampleBlockCreateRemove(), and IG.Lib.WaitFileEventLatenceBase.ExampleLatence.TestSpeedBlockCreateRemove().
_creation
IWaitFileEvent IG.Lib.WaitFileEventLatenceBase.ExampleLatence._creation = null protected
Definition at line 1124 of file WaitConditionFile.cs.
_removal
IWaitFileEvent IG.Lib.WaitFileEventLatenceBase.ExampleLatence._removal = null private
Definition at line 1124 of file WaitConditionFile.cs.
ExamplePath
string IG.Lib.WaitFileEventLatenceBase.ExampleLatence.ExamplePath protected
Definition at line 1155 of file WaitConditionFile.cs.
Referenced by IG.Lib.WaitFileEventLatenceBase.ExampleLatence.AlternateCreateRemoveExample().
IsDirectory
bool IG.Lib.WaitFileEventLatenceBase.ExampleLatence.IsDirectory protected
Definition at line 1158 of file WaitConditionFile.cs.
Referenced by IG.Lib.WaitFileEventLatenceBase.ExampleLatence.AlternateCreateRemoveExample().
TthreadStopped
bool IG.Lib.WaitFileEventLatenceBase.ExampleLatence.TthreadStopped protected
Definition at line 1161 of file WaitConditionFile.cs.
NumIterations
int IG.Lib.WaitFileEventLatenceBase.ExampleLatence.NumIterations protected
Definition at line 1164 of file WaitConditionFile.cs.
Referenced by IG.Lib.WaitFileEventLatenceBase.ExampleLatence.AlternateCreateRemoveExample().
SleepTimeMs
int IG.Lib.WaitFileEventLatenceBase.ExampleLatence.SleepTimeMs protected
Definition at line 1167 of file WaitConditionFile.cs.
Referenced by IG.Lib.WaitFileEventLatenceBase.ExampleLatence.AlternateCreateRemoveExample(), and IG.Lib.WaitFileEventLatenceBase.ExampleLatence.TestSpeedBlockCreateRemove().
TestTime
double IG.Lib.WaitFileEventLatenceBase.ExampleLatence.TestTime protected
Definition at line 1169 of file WaitConditionFile.cs.
Referenced by IG.Lib.WaitFileEventLatenceBase.ExampleLatence.AlternateCreateRemoveExample(), and IG.Lib.WaitFileEventLatenceBase.ExampleLatence.TestSpeedBlockCreateRemove().
fileOperationLock
object IG.Lib.WaitFileEventLatenceBase.ExampleLatence.fileOperationLock = new object() protected
Lock for file creation and removal operations.
Definition at line 1248 of file WaitConditionFile.cs.
Referenced by IG.Lib.WaitFileEventLatenceBase.ExampleLatence.AlternateCreateRemoveExample(), and IG.Lib.WaitFileEventLatenceBase.ExampleLatence.TestSpeedBlockCreateRemove().
Property Documentation
Creation
virtual IWaitFileEvent IG.Lib.WaitFileEventLatenceBase.ExampleLatence.Creation get protected
Definition at line 1127 of file WaitConditionFile.cs.
Referenced by IG.Lib.WaitFileEventLatenceBase.ExampleLatence.AlternateCreateRemoveExample(), IG.Lib.WaitFileEventLatenceBase.ExampleLatence.ExampleBlockCreateRemove(), and IG.Lib.WaitFileEventLatenceBase.ExampleLatence.TestSpeedBlockCreateRemove().
Removal
virtual IWaitFileEvent IG.Lib.WaitFileEventLatenceBase.ExampleLatence.Removal get protected
Definition at line 1140 of file WaitConditionFile.cs.
Referenced by IG.Lib.WaitFileEventLatenceBase.ExampleLatence.AlternateCreateRemoveExample(), IG.Lib.WaitFileEventLatenceBase.ExampleLatence.ExampleBlockCreateRemove(), and IG.Lib.WaitFileEventLatenceBase.ExampleLatence.TestSpeedBlockCreateRemove().
The documentation for this class was generated from the following file:
iglib/igbase/0unsorted/WaitConditionFile.cs