Doc: IGLib with source files: IG.Script.AppBase Class Reference
IG.Script.AppBase Class Reference
Base cls. for application scripts that can also be used on its own.
Public Member Functions
AppBase ()
override void Script_AddCommands (ICommandLineApplicationInterpreter interpreter, SortedList< string, string > helpStrings)
Adds commands to the internal interpreter.
virtual string AppCustom (string[] arguments)
Runs one of the custom embedded applications.
Public Member Functions inherited from IG.Script.ScriptAppBase
void Script_AddCommands1 (ICommandLineApplicationInterpreter interpreter, SortedList< string, string > helpStrings)
Adds commands to the internal interpreter.
ScriptAppBase ()
override void Script_AddCommands (ICommandLineApplicationInterpreter interpreter, SortedList< string, string > helpStrings)
Adds commands to the internal interpreter.
virtual string RunFileByScript (string filePath)
Runs all commands that are written in a file. Each line of a file is interpreted as a single command, consisting of command name followed by arguments.
virtual void ReportError (string errorString)
new string AppMyTest (string[] arguments)
Test action.
override string AppCustomApp (string[] arguments)
Custom application.
virtual string AppNumerics (string[] arguments)
Runs one of the numerics - related embedded applications.
virtual string AppFile (string[] arguments)
Runs one of the file system - related embedded applications.
virtual string AppCrypto (string[] arguments)
Runs one of the cryptography - related embedded applications.
virtual string AppSystem (string[] arguments)
Runs one of the file system - related embedded applications.
virtual string AppAssembly (string[] arguments)
Runs one of the file assembly - related embedded applications.
virtual string AppProcess (string[] arguments)
Runs one of the process - related embedded applications.
virtual string AppDataStructures (string[] arguments)
Runs one of the data structures demo - related embedded applications.
Public Member Functions inherited from IG.Lib.ILoadableScript
string Run (string[] arguments)
Runs the executable method of the object.
void Initialize (string[] arguments)
Initializes the current object.
Static Public Attributes
const string ConstCustom = "Custom"
Name of the command for a group of custom applications.
const string ConstHelpCustom = "Custom application group."
const string FileTestArguments = "PrintArguments"
const string CustomPrintArguments = "PrintArguments"
Static Public Attributes inherited from IG.Script.ScriptAppBase
const string DataStructuresTestCsvApp = "TestCsv"
const string DataStructuresTestCsvWriteDefinitionAndData = "CsvWriteDefinitionAndData"
const string DataStructuresTestCsvReadDefinitionAndData = "CsvReadDefinitionAndData"
const new string ConstMyTest = "MyTest"
Name of the command that performs my custom test.
const new string ConstHelpMyTest = "Custom test function."
const new string ConstCustomApp = "CustomApp"
Name of the command for custom test.
const new string ConstHelpCustomApp = "Custom aplication."
const string ConstSystem = "System"
Name of the command for the system-related embedded applications.
const string ConstHelpSystem = "Various system-related embedded applications. Run with ? argument to see which applications are available."
const string ConstAssembly = "Assembly"
Name of the command for the assemblies-related embedded applications.
const string ConstHelpAssembly = "Various assemblies-related embedded applications. Run with ? argument to see which applications are available."
const string ConstNumerics = "Numerics"
Name of the command for the numerics-related embedded applications.
const string ConstHelpNumerics = "Various numerics-related embedded applications. Run with ? argument to see which applications are available."
const string ConstFile = "File"
Name of the command for the file system-related embedded applications.
const string ConstHelpFile = "Various file system-related embedded applications. Run with ? argument to see which applications are available."
const string ConstCrypto1 = "Crypto"
Name of the command for the cryptography-related embedded applications.
const string ConstHelpCrypto = "Various cryptography-related embedded applications. Run with ? argument to see which applications are available."
const string ConstProcess = "Process"
Name of the command for the process-related embedded applications.
const string ConstHelpProcess = "Various process-related embedded applications. Run with ? argument to see which applications are available."
const string ConstDataStructures = "DataStructures"
Name of the command for the data structures-related embedded applications.
const string ConstHelpDataStructures
const string ConstRunFile = "RunFileByScript"
Name of the command that runs (interprets) the specified command file by the script's interpreter.
const string ConstHelpRunFile
const string NumericsScriptScalarFunction = "ScriptScalarFunction"
const string FileLogEvents = "LogEvents"
const string FileWaitCreation = "WaitCreation"
const string FileRelativePath = "RelativePath"
const string FileStandardPath = "StandardPath"
const string FileCurrentDirectory = "CurrentDirectory"
const string FileCurrentDirectory1 = "SetCurrentDirectory"
const string CryptoGetFileHash = "GetFileHash"
const string CryptoCheckSum = "CheckSum"
const string CryptoEncryptBasic = "EncryptBasic"
const string CryptoDecryptBasic = "DecryptBasic"
const string CryptoEncryptPlain = "EncryptPlain"
const string CryptoDecryptPlain = "DecryptPlain"
const string CryptoGetKey = "GetKey"
const string CryptoGetInitializationVector = "GetInitializationVector"
const string CryptoGetInitializationVector1 = "GetIV"
const string CryptoGetSalt = "GetSalt"
const string CryptoTimeKeyGeneration = "TimeKeyGeneration"
const string CryptoConvert = "Convert"
const string CryptoAsymKeyInfo = "AsymKeyInfo"
const string CryptoCertStoreInfo = "CertStoreInfo"
const string CryptoCertInfo = "CertInfo"
const string CryptoAddCertificate = "AddCertificate"
const string CryptoRemoveCertificate = "RemoveCertificate"
const string CryptoAsymTest = "AsymTest"
const string CryptoCleanFiles = "CleanFiles"
const string SystemRuntimeVersion = "RuntimeVersion"
const string SystemComputerName = "ComputerName"
const string SystemDomainName = "DomainName"
const string SystemIpAddress = "IpAddress"
const string SystemUserName = "UserName"
const string SystemSystemInfo = "Info"
const string SystemMACAddress = "MACAddress"
const string AssemblyInfo = "Info"
const string AssemblyInfo1 = "AssemblyInfo"
const string AssemblyResources = "Resources"
const string AssemblyResources1 = "ResourceInfo"
const string AssemblyResourcesEmbedded = "ResourcesEmbedded"
const string AssemblyResourcesResx = "ResourcesResx"
const string AssemblyReferenced = "ReferencedAssemblies"
const string AssemblyReferenced1 = "Referenced"
const string AssemblyLoaded = "LoadedAssemblies"
const string AssemblyLoaded1 = "Loaded"
const string AssemblyLoad = "LoadAssemblies"
const string AssemblyLoad1 = "Load"
const string AssemblyInfoLoad = "InfoLoadAssemblies"
const string AssemblyInfoLoad1 = "InfoLoad"
const string ProcessListProcesses = "ListProcesses"
const string ProcessListApplications = "ListApplications"
const string ProcessListApplicationsByWindow = "ListApplicationsByWindow"
const string ProcessKillProcesses = "KillProcesses"
const string ProcessKillApplications = "KillApplications"
const string ProcessKillApplicationsByWindow = "KillApplicationsByWindow"
Protected Member Functions
override void InitAppFile ()
Initializes commands for file system related utilities (embedded applications).
virtual string FileFunctionTestArguments (string appName, string[] args)
Executes embedded application that just prints arguments passed to the application to a console.
void AddCustomCommand (string appName, CommandMethod appMethod, string appHelp)
Adds a new file system - related embedded application's command (added as sub-command of the base command named ScriptAppBase.ConstFile).
virtual string CustomFunctionPrintArguments (string appName, string[] args)
Executes embedded application - writing to the console information about file events for the specified file or directory.
virtual void InitAppCustom ()
Initializes commands for file system related utilities (embedded applications).
virtual string RunAppCustom (string[] args)
Runs a file system related utility (embedded application) according to arguments.
Protected Member Functions inherited from IG.Script.ScriptAppBase
virtual void InitAppDataStructuresPartial ()
Initializes commands for form demo related utilities (embedded applications).
virtual string DataStructuresFunctionTestCsvApp (string appName, string[] args)
Executes embedded application - demo application for demonstration of work with CSVs.
virtual string DataStructuresFunctionTestCsvWriteDefinitionAndData (string appName, string[] args)
Executes embedded application - test of writing sampled data definition and data in CSV format.
virtual string DataStructuresFunctionTestCsvReadDefinitionAndData (string appName, string[] appArgs)
Executes embedded application - test of writing sampled data definition and data in CSV format.
override void InitializeThis (string[] arguments)
Initializes the current object.
override string RunThis (string[] arguments)
Runs action of the current object.
void Script_AddRunFileByScriptCommand (ICommandLineApplicationInterpreter interpreter, SortedList< string, string > helpStrings)
Adds the Run comand to the script's interpreter and performs the necessary additional tasks.
void Script_RemoveRunFileByScriptCommand (ICommandLineApplicationInterpreter interpreter, SortedList< string, string > helpStrings)
Removes the Run comand from the script's interpreter and performs the necessary accompanying tasks.
virtual string AppRunFileByScript (string[] args)
Execution method that Runs the specified command file by the script's interpreter.
void AddNumericsCommand (string appName, CommandMethod appMethod, string appHelp)
Adds a new numerics - related embedded application's command (added as sub-command of the base command named ConstNumerics).
virtual string NumericsFunctionScriptScalarFuncitons (string appName, string[] args)
Executes embedded application - testing of definition of scalar function objects through expressions.
virtual void InitAppNumerics ()
Initializes commands for numerics related utilities (embedded applications).
virtual string RunAppNumerics (string[] args)
Runs a numerics related utility (embedded application) according to arguments.
void AddFileCommand (string appName, CommandMethod appMethod, string appHelp)
Adds a new file system - related embedded application's command (added as sub-command of the base command named ConstFile).
virtual string FileFunctionLogEvents (string appName, string[] args)
Executes embedded application - writing to the console information about file events for the specified file or directory.
virtual string FileFunctionWaitCreation (string appName, string[] args)
Executes embedded application - waiting for creation of the specified file.
virtual string FileFunctionRelativePath (string appName, string[] args)
Executes embedded application - writing to the console information about file events for the specified file or directory.
virtual string FileFunctionStandardPath (string appName, string[] args)
Executes embedded application - writing to the console information about file events for the specified file or directory.
virtual string FileFunctionCurrentDirectory (string appName, string[] args)
Executes embedded application - writing to the console information about file events for the specified file or directory.
virtual string RunAppFile (string[] args)
Runs a file system related utility (embedded application) according to arguments.
void AddCryptoCommand (string appName, CommandMethod appMethod, string appHelp)
Adds a new cryptography - related embedded application's command (added as sub-command of the base command named ConstCrypto1).
virtual string CryptoFunctionGetFileHash (string appName, string[] args)
Executes embedded application - calculation of various hash values of a file.
virtual string CryptoFunctionCheckSum (string appName, string[] args)
Executes embedded application - calculation AND verification of various hash values of a file or a string.
virtual string CryptoFunctionEncryptBasic (string appName, string[] args)
Executes embedded application - symmetric encryption of files, strings, or byte fields by using the BASIC class of methods.
virtual string CryptoFunctionDecryptBasic (string appName, string[] args)
Executes embedded application - symmetric decryption of files, strings, or byte fields by using the BASIC class of methods.
virtual string CryptoFunctionEncryptPlain (string appName, string[] args)
Executes embedded application - symmetric encryption of files, strings, or byte fields by using the PLAIN class of methods.
virtual string CryptoFunctionDecryptPlain (string appName, string[] args)
Executes embedded application - symmetric decryption of files, strings, or byte fields by using the PLAIN class of methods.
virtual string CryptoFunctionGetKey (string appName, string[] args)
Executes embedded application - generation of secret keys for encryption.
virtual string CryptoFunctionGetInitializationVector (string appName, string[] args)
Executes embedded application - generation of initialization vectors for encryption.
virtual string CryptoFunctionGetSalt (string appName, string[] args)
Executes embedded application - generation of salts for encryption.
virtual string CryptoFunctionTimeKeyGeneration (string appName, string[] args)
Executes embedded application - measuring time of password generaton utilities.
virtual string CryptoFunctionConvert (string appName, string[] args)
Executes embedded application - conversion between different representations of data.
virtual string CryptoFunctionAsymKeyInfo (string appName, string[] args)
Executes embedded application - printing infomration about the specified asymmetric key.
virtual string CryptoFunctionCertStoreInfo (string appName, string[] args)
Executes embedded application - printing infomration about the specified certificate store.
virtual string CryptoFunctionCertInfo (string appName, string[] args)
Executes embedded application - printing infomration about the specified certificate.
virtual string CryptoFunctionAddCertificate (string appName, string[] args)
Executes embedded application - adding the specified certificate to the specified certificate store.
virtual string CryptoFunctionRemoveCertificate (string appName, string[] args)
Executes embedded application - removing the certificate from certificate store.
virtual string CryptoFunctionAsymTest (string appName, string[] args)
Executes embedded application - test of asymmetric encrypton.
virtual string CryptoFunctionCleanFiles (string appName, string[] args)
Executes embedded application - conversion between different representations of data.
virtual void InitAppCrypto ()
Initializes commands for cryptography related utilities (embedded applications).
virtual string RunAppCrypto (string[] args)
Runs a cryptography related utility (embedded application) according to arguments.
virtual string CryptoFunctionGetFileHash_OLD_TO_DELETE (string appName, string[] args)
Executes embedded application - calculation of various hash values of a file.
virtual string CryptoFunctionCheckSum_OLD_TO_DELETE_LATER (string appName, string[] args)
Executes embedded application - calculation AND verification of various hash values of a file.
virtual string CryptoFunctionTimeKeyGeneration_OLD_TO_DELETE_LATER (string appName, string[] args)
Executes embedded application - symmetric encryption of files, strings, or byte fields.
virtual string CryptoFunctionConvert_OLD_TO_DELETE (string appName, string[] args)
Executes embedded application - symmetric encryption of files, strings, or byte fields.
void AddSystemCommand (string appName, CommandMethod appMethod, string appHelp)
Adds a new system - related embedded application's command (added as sub-command of the base command named ConstSystem).
virtual string SystemFunctionRuntimeVersion (string appName, string[] args)
Executes embedded application - writing to the console and returning version of the runtime that application runs on.
virtual string SystemFunctionComputerName (string appName, string[] args)
Executes embedded application - writing to the console and returning the current computer name.
virtual string SystemFunctionDomainName (string appName, string[] args)
Executes embedded application - writing to the console and returning the current domain name.
virtual string SystemFunctionIpAddress (string appName, string[] args)
Executes embedded application - writing to the console and returning the current IP address.
virtual string SystemFunctionUserName (string appName, string[] args)
Executes embedded application - writing to the console and returning the current user name.
virtual string SystemFunctionSystemInfo (string appName, string[] args)
Executes embedded application - writing to the console and returning the system info.
virtual string SystemFunctionMACAddress (string appName, string[] args)
Executes embedded application - writing to the console and returning the current domain name.
virtual void InitAppSystem ()
Initializes commands for file system related utilities (embedded applications).
virtual string RunAppSystem (string[] args)
Runs a file system related utility (embedded application) according to arguments.
void AddAssemblyCommand (string appName, CommandMethod appMethod, string appHelp)
Adds a new assembly - related embedded application's command (added as sub-command of the base command named ConstSystem).
virtual string AssemblyFunctionInfo (string appName, string[] args)
Executes embedded application - writing to the console information about the specified assembly.
virtual string AssemblyFunctionResourcesEmbedded (string appName, string[] args)
Executes embedded application - writing to the console information about the specified assembly's embedded resources.
virtual string AssemblyFunctionResourcesResx (string appName, string[] args)
Executes embedded application - writing to the console information about the specified assembly's resources included through .resx files.
virtual string AssemblyFunctionResources (string appName, string[] args)
Executes embedded application - writing to the console information about the specified assembly's resources.
virtual string AssemblyFunctionResources (string appName, string[] args, bool includeEmbedded, bool includeResx)
Executes embedded application - writing to the console information about the specified assembly's resources.
virtual string AssemblyFunctionReferenced (string appName, string[] args)
Executes embedded application - writing to the console list of referenced assemblies.
virtual string AssemblyFunctionLoaded (string appName, string[] args)
Executes embedded application - writing to the console list of loaded assemblies.
virtual string AssemblyFunctionLoadAssemblies (string appName, string[] args)
Executes embedded application - loading the specified assemblies to the application domain.
virtual string AssemblyFunctionInfoLoadAssemblies (string appName, string[] args)
Executes embedded application - loading the specified assemblies for inspection only (can not be executed).
virtual string AssemblyFunctionLoadAssemblies (int outputLevel, bool reflectionOnly, string appName, string[] args)
Executes embedded application - loading the specified assemblies to the application domain.
virtual void InitAppAssembly ()
Initializes commands for assembly related utilities (embedded applications).
virtual string RunAppAssembly (string[] args)
Runs a file assembly related utility (embedded application) according to arguments.
void AddProcessCommand (string appName, CommandMethod appMethod, string appHelp)
Adds a new process - related embedded application's command (added as sub-command of the base command named ConstProcess).
virtual string ProcessFunctionListProcesses (string appName, string[] args)
Embedded application - lists all processes that satisfy the specified conditions.
virtual string ProcessFunctionListApplications (string appName, string[] args)
Embedded application. Lists all running applications sarisfyin specified conditions.
virtual string ProcessFunctionListApplicationsByWindow (string appName, string[] args)
Embedded application. Lists all running applications sarisfyin specified conditions.
virtual string ProcessFunctionKillProcesses (string appName, string[] args)
Embedded application - kills all processes that satisfy the specified conditions.
virtual string ProcessFunctionKillApplications (string appName, string[] args)
Embedded application. Kills all running applications sarisfyin specified conditions.
virtual string ProcessFunctionKillApplicationsByWindow (string appName, string[] args)
Embedded application. Kills all running applications sarisfyin specified conditions.
virtual void InitAppProcess ()
Initializes commands for process - related utilities (embedded applications).
virtual string RunAppProcess (string[] args)
Runs a process - related utility (embedded application) according to arguments.
void AddDataStructuresCommand (string appName, CommandMethod appMethod, string appHelp)
Adds a new data structure- related embedded demo application's command (added as a sub-command of the base command named ConstDataStructures).
virtual void InitAppDataStructures ()
Initializes commands for form demo related utilities (embedded applications).
virtual string RunAppDataStructures (string[] args)
Runs a data structures demo - related utility (embedded application) according to arguments.
Protected Attributes
List< string > AppCustomNames = new List<string>()
List of installed file command names.
List< string > AppCustomHelpStrings = new List<string>()
List of help strings corresponding to installed file commands.
List< CommandMethod > AppCustomMethods = new List<CommandMethod>()
List of methods used to perform file commmands.
bool _appCustomCommandsInitialized = false
Protected Attributes inherited from IG.Script.ScriptAppBase
bool _isAddRunFileByScriptCommand = true
List< string > AppNumericsNames = new List<string>()
List of installed numerics command names.
List< string > AppNumericsHelpStrings = new List<string>()
List of help strings corresponding to installed numerics-related commands.
List< CommandMethod > AppNumericsMethods = new List<CommandMethod>()
List of methods used to perform numerics-related commmands.
bool _appNumericsCommandsInitialized = false
List< string > AppFileNames = new List<string>()
List of installed file command names.
List< string > AppFileHelpStrings = new List<string>()
List of help strings corresponding to installed file commands.
List< CommandMethod > AppFileMethods = new List<CommandMethod>()
List of methods used to perform file commmands.
bool _appFileCommandsInitialized = false
List< string > AppCryptoNames = new List<string>()
List of installed cryptographic command names.
List< string > AppCryptoHelpStrings = new List<string>()
List of help strings corresponding to installed cryptographic commands.
List< CommandMethod > AppCryptoMethods = new List<CommandMethod>()
List of methods used to perform cryptographic commmands.
bool _appCryptoCommandsInitialized = false
List< string > AppSystemNames = new List<string>()
List of installed system related command names.
List< string > AppSystemHelpStrings = new List<string>()
List of help strings corresponding to installed system related commands.
List< CommandMethod > AppSystemMethods = new List<CommandMethod>()
List of methods used to perform system related commmands.
bool _appSystemCommandsInitialized = false
List< string > AppAssemblyNames = new List<string>()
List of installed assemblies related command names.
List< string > AppAssemblyHelpStrings = new List<string>()
List of help strings corresponding to installed assembly related commands.
List< CommandMethod > AppAssemblyMethods = new List<CommandMethod>()
List of methods used to perform assembly related commmands.
bool _appAssemblyCommandsInitialized = false
List< string > AppProcessNames = new List<string>()
List of installed process-related command names.
List< string > AppProcessHelpStrings = new List<string>()
List of help strings corresponding to installed process commands.
List< CommandMethod > AppProcessMethods = new List<CommandMethod>()
List of methods used to perform process-related commmands.
bool _appProcessCommandsInitialized = false
List< string > AppDataStructuresNames = new List<string>()
List of installed data structure - related demo command names.
List< string > AppDataStructuresHelpStrings = new List<string>()
List of help strings corresponding to the installed data structure - related demo commands.
List< CommandMethod > AppDataStructuresMethods = new List<CommandMethod>()
List of methods used to perform data structure - related demo commmands.
bool _appDataStructuresCommandsInitialized = false
Static Protected Attributes
const string CustomHelpPrintArguments = CustomPrintArguments + " arg1 arg2 ... : Prints out the arguments of the command."
Static Protected Attributes inherited from IG.Script.ScriptAppBase
const string DataStructuresHelpTestCsvApp = DataStructuresTestCsvApp + " : Runs the CSV simple demo application."
const string DataStructuresHelpTestCsvWriteDefinitionAndData
const string DataStructuresHelpTestCsvReadDefinitionAndData
const string NumericsHelpScriptScalarFunction = NumericsScriptScalarFunction + " : Definition of scalar functions by expressions."
const string FileHelpLogEvents = FileLogEvents + " FileOrDirectory MaxEvents : Logs file events for the specified file or directory."
const string FileHelpWaitCreation = NumericsScriptScalarFunction + " FilePath <ReturnIfExists> : Waits until file is created."
const string FileHelpRelativePath
const string FileHelpStandardPath
const string FileHelpCurrentDirectory
const string FileHelpCurrentDirectory1
const string CryptoHelpGetFileHash
const string CryptoHelpCheckSum
const string CryptoHelpDecryptBasic = CryptoDecryptBasic + CryptoHelpEncryptBasicPart
const string CryptoHelpEncryptBasic = CryptoEncryptBasic + CryptoHelpEncryptBasicPart
const string CryptoHelpDecryptPlain = CryptoDecryptPlain + CryptoHelpEncryptBasicPart
const string CryptoHelpEncryptPlain = CryptoEncryptPlain + CryptoHelpEncryptBasicPart
const string CryptoHelpEncryptBasicPart
const string CryptoHelpGetKey = CryptoGetKey + CryptoHelpGetKeyLastPart
const string CryptoHelpGetInitializationVector = CryptoGetInitializationVector + CryptoHelpGetKeyLastPart
const string CryptoHelpGetInitializationVector1 = CryptoGetInitializationVector1 + CryptoHelpGetKeyLastPart
const string CryptoHelpGetSalt = CryptoGetSalt + CryptoHelpGetKeyLastPart
const string CryptoHelpGetKeyLastPart
const string CryptoHelpTimeKeyGeneration
const string CryptoHelpConvert
const string CryptoHelpAsymKeyInfo
const string CryptoHelpCertStoreInfo
const string CryptoHelpCertInfo
const string CryptoHelpAddCertificate
const string CryptoHelpRemoveCertificate
const string CryptoHelpAsymTest
const string CryptoHelpCleanFiles
const string SystemHelpRuntimeVersion = SystemRuntimeVersion + " : Prints version of the runtime environment that application runs on."
const string SystemHelpComputerName = SystemComputerName + " : Prints and returns the current computer name."
const string SystemHelpDomainName = SystemDomainName + " : Prints and returns the current domain name."
const string SystemHelpIpAddress = SystemIpAddress + " : Prints and returns IP address of the current computer."
const string SystemHelpUserName = SystemUserName + " : Prints and returns the current user name."
const string SystemHelpSystemInfo = SystemSystemInfo + " : Prints and returns basic system info."
const string SystemHelpMACAddress = SystemMACAddress + " : Prints and returns the current domain name."
const string AssemblyHelpInfo
const string AssemblyHelpInfo1
const string AssemblyHelpResources
const string AssemblyHelpResources1
const string AssemblyHelpResourcesEmbedded
const string AssemblyHelpResourcesResx
const string AssemblyHelpReferenced
const string AssemblyHelpReferenced1 = AssemblyHelpReferenced
const string AssemblyHelpLoaded = AssemblyLoaded + @" : Prints all loaded assemblies."
const string AssemblyHelpLoaded1 = AssemblyHelpLoaded
const string AssemblyHelpLoad
const string AssemblyHelpLoad1 = AssemblyHelpLoad
const string AssemblyHelpInfoLoad
const string AssemblyHelpInfoLoad1 = AssemblyHelpInfoLoad
const string ProcessHelpListProcesses
const string ProcessHelpListApplications
const string ProcessHelpListApplicationsByWindow
const string ProcessHelpKillProcesses
const string ProcessHelpKillApplications
const string ProcessHelpKillApplicationsByWindow
Static Private Attributes
const string FileHelpTestArguments = FileTestArguments + " arg1 arg2 ... : Prints out the arguments of the command."
Additional Inherited Members
Properties inherited from IG.Script.ScriptAppBase
virtual bool IsAddRunFileByScriptCommand [get, set]
Whether or not the Run command is installed on the script's interpreter.
Properties inherited from IG.Lib.ILoadableScript
string EmbeddedCommandName [get, set]
Command that was used to launch the current embedded application script.
string[] InitializationArguments [get, set]
Arguments used by the initialization method.
bool IsInitialized [get]
Whether the object has been initialized or not.
Detailed Description
Base cls. for application scripts that can also be used on its own.
The cls.es derived from this cls. are usually used as internal scripts and provide a set of embedded utiliy applications within an application that is based on an command-line interpreter.
Applications will typically extend this cls. by their own specific cls. that is used in its place for providing various embedded utility applications. The base library itself provides the AppBase cls. derived from this cls., which is used because its shorter name. See that cls. for an example how to prepare a derived cls. that will provide as set of embedded applications.
In applications that have the command-line interpreter, embedded applications from this cls. can typically be run in the following way:
AppName Internal IG.Script.AppBase CommandName arg1 arg2 ...
where AppName is the application name, IG.Script.AppBase is the full name of the script cls. that contains embedded applications, CommandName is name of the command thar launches embedded application, and arg1, arg2, etc. are command arguments for the embedded application.
See also
ScriptAppBase
$A Igor xx May09 Jun15;
Definition at line 39 of file ScriptAppBase.cs.
Constructor & Destructor Documentation
AppBase()
IG.Script.AppBase.AppBase () inline
Definition at line 42 of file ScriptAppBase.cs.
Member Function Documentation
Script_AddCommands()
override void IG.Script.AppBase.Script_AddCommands (ICommandLineApplicationInterpreter interpreter, SortedList< string, string > helpStrings) inline
Adds commands to the internal interpreter.
Definition at line 54 of file ScriptAppBase.cs.
References IG.Script.AppBase.AppCustom(), IG.Script.AppBase.ConstCustom, and IG.Script.AppBase.ConstHelpCustom.
InitAppFile()
override void IG.Script.AppBase.InitAppFile () inline protected virtual
Initializes commands for file system related utilities (embedded applications).
Reimplemented from IG.Script.ScriptAppBase.
Definition at line 69 of file ScriptAppBase.cs.
References IG.Script.ScriptAppBase._appFileCommandsInitialized, IG.Script.ScriptAppBase.AddFileCommand(), IG.Script.AppBase.FileFunctionTestArguments(), IG.Script.AppBase.FileHelpTestArguments, and IG.Script.AppBase.FileTestArguments.
FileFunctionTestArguments()
virtual string IG.Script.AppBase.FileFunctionTestArguments (string appName, string[] args) inline protected virtual
Executes embedded application that just prints arguments passed to the application to a console.
Parameters
appName Name of the embedded application.
args Arguments fo the embedded application's command.
Returns
Number of arguments passed.
Definition at line 90 of file ScriptAppBase.cs.
Referenced by IG.Script.AppBase.CustomFunctionPrintArguments(), and IG.Script.AppBase.InitAppFile().
AddCustomCommand()
void IG.Script.AppBase.AddCustomCommand (string appName, CommandMethod appMethod, string appHelp) inline protected
Adds a new file system - related embedded application's command (added as sub-command of the base command named ScriptAppBase.ConstFile).
Parameters
appName Application name.
appMethod Method used to perform the application.
appHelp Eventual help string for the application.
Definition at line 136 of file ScriptAppBase.cs.
References IG.Script.AppBase.AppCustomHelpStrings, IG.Script.AppBase.AppCustomMethods, and IG.Script.AppBase.AppCustomNames.
Referenced by IG.Script.AppBase.InitAppCustom().
CustomFunctionPrintArguments()
virtual string IG.Script.AppBase.CustomFunctionPrintArguments (string appName, string[] args) inline protected virtual
Executes embedded application - writing to the console information about file events for the specified file or directory.
Parameters
appName Name of the embedded application.
args Arguments fo the embedded application's command.
Returns
Number of arguments passed.
Definition at line 156 of file ScriptAppBase.cs.
References IG.Script.AppBase.FileFunctionTestArguments().
Referenced by IG.Script.AppBase.InitAppCustom().
InitAppCustom()
virtual void IG.Script.AppBase.InitAppCustom () inline protected virtual
Initializes commands for file system related utilities (embedded applications).
Definition at line 168 of file ScriptAppBase.cs.
References IG.Script.AppBase._appCustomCommandsInitialized, IG.Script.AppBase.AddCustomCommand(), IG.Script.AppBase.CustomFunctionPrintArguments(), IG.Script.AppBase.CustomHelpPrintArguments, and IG.Script.AppBase.CustomPrintArguments.
Referenced by IG.Script.AppBase.RunAppCustom().
RunAppCustom()
virtual string IG.Script.AppBase.RunAppCustom (string[] args) inline protected virtual
Runs a file system related utility (embedded application) according to arguments.
Parameters
args Arguments. 0-th argument is the base command name, 1st argument is the embedded application name, and teh rest arguments are arguments that are used by the embedded application.
Definition at line 185 of file ScriptAppBase.cs.
References IG.Script.AppBase.AppCustomHelpStrings, IG.Script.AppBase.AppCustomMethods, IG.Script.AppBase.AppCustomNames, and IG.Script.AppBase.InitAppCustom().
Referenced by IG.Script.AppBase.AppCustom().
AppCustom()
virtual string IG.Script.AppBase.AppCustom (string[] arguments) inline virtual
Runs one of the custom embedded applications.
Parameters
arguments Array containing the base command name, application command name and arguments.
Definition at line 245 of file ScriptAppBase.cs.
References IG.Script.AppBase.RunAppCustom().
Referenced by IG.Script.AppBase.Script_AddCommands().
Member Data Documentation
ConstCustom
const string IG.Script.AppBase.ConstCustom = "Custom" static
Name of the command for a group of custom applications.
Definition at line 49 of file ScriptAppBase.cs.
Referenced by IG.Script.AppBase.Script_AddCommands().
ConstHelpCustom
const string IG.Script.AppBase.ConstHelpCustom = "Custom application group." static
Definition at line 50 of file ScriptAppBase.cs.
Referenced by IG.Script.AppBase.Script_AddCommands().
FileTestArguments
const string IG.Script.AppBase.FileTestArguments = "PrintArguments" static
Definition at line 82 of file ScriptAppBase.cs.
Referenced by IG.Script.AppBase.InitAppFile().
FileHelpTestArguments
const string IG.Script.AppBase.FileHelpTestArguments = FileTestArguments + " arg1 arg2 ... : Prints out the arguments of the command." static private
Definition at line 84 of file ScriptAppBase.cs.
Referenced by IG.Script.AppBase.InitAppFile().
AppCustomNames
List<string> IG.Script.AppBase.AppCustomNames = new List<string>() protected
List of installed file command names.
Definition at line 124 of file ScriptAppBase.cs.
Referenced by IG.Script.AppBase.AddCustomCommand(), and IG.Script.AppBase.RunAppCustom().
AppCustomHelpStrings
List<string> IG.Script.AppBase.AppCustomHelpStrings = new List<string>() protected
List of help strings corresponding to installed file commands.
Definition at line 127 of file ScriptAppBase.cs.
Referenced by IG.Script.AppBase.AddCustomCommand(), and IG.Script.AppBase.RunAppCustom().
AppCustomMethods
List<CommandMethod> IG.Script.AppBase.AppCustomMethods = new List<CommandMethod>() protected
List of methods used to perform file commmands.
Definition at line 130 of file ScriptAppBase.cs.
Referenced by IG.Script.AppBase.AddCustomCommand(), and IG.Script.AppBase.RunAppCustom().
CustomPrintArguments
const string IG.Script.AppBase.CustomPrintArguments = "PrintArguments" static
Definition at line 148 of file ScriptAppBase.cs.
Referenced by IG.Script.AppBase.InitAppCustom().
CustomHelpPrintArguments
const string IG.Script.AppBase.CustomHelpPrintArguments = CustomPrintArguments + " arg1 arg2 ... : Prints out the arguments of the command." static protected
Definition at line 150 of file ScriptAppBase.cs.
Referenced by IG.Script.AppBase.InitAppCustom().
_appCustomCommandsInitialized
bool IG.Script.AppBase._appCustomCommandsInitialized = false protected
Definition at line 165 of file ScriptAppBase.cs.
Referenced by IG.Script.AppBase.InitAppCustom().
The documentation for this class was generated from the following file:
iglib/igbase/interpreters/scriptloader/scripts/ScriptAppBase.cs