Doc: IGLib with source files: IGLib.Tests.UtilSpeedTesting Class Reference
IGLib.Tests.UtilSpeedTesting Class Reference
Contains speed testng utilities, mainly as static methods. These usually perform calculations whose execution is deterministic and take the same number of operations every time, such that execution times provide some information of how fast the host computer is in comparison with other computers.
Classes
class ConstGeom
class ConstGeomBase
Constants for standard tests based on numerical calculation of finite geometric series.
class ConstGeomDirect
class ConstMachineHpLaptop24
Ajgor's HP laptop, acquired in 2024.
Static Public Member Functions
static double ArithmeticSeriesAnalytical (int n, double a0, double d)
Analytically calculates and returns the specified finite arythmetic series (from the sequence: a_i = a0 + (i-1) * d).
static double ArithmeticSeriesNumerical (int n, double a0, double d)
Analytically calculates and returns the specified finite arythmetic series (from the sequence: a_i = a0 + (i-1) * d).
static double GeometricSeriesAnalytical (int n, double a0, double k)
Analytically calculates and returns the specified finite geometric series (from the geometric sequence: a_i = a0 * k^(i-1)).
static double GeometricSeriesNumerical (int n, double a0, double k)
Numerically calculates and returns the specified finite geometric series (from the geometric sequence: a_i = a0 * k^(i-1)).
static double GeometricSeriesNumerical_DirectElementCalculation (int n, double a0, double k)
Numerically calculates and returns the specified finite geometric series by calculating each term of the series directly, rather than accumulate it during iteration. (from the geometric sequence: a_i = a0 * k^(i-1)).
static double StandardSpeedTestGeometricSeries_HpLaptop24 (out SpeedTestInfo info, bool writeToConsole=DefaultWriteToConsole_StandardTests)
Performs the standard speed test - calculation of a finite geometric series with specific parameters, and with reference results from the machine represented by ConstMachineHpLaptop24.
static double StandardSpeedTestGeometricSeries_HpLaptop24 (bool writeToConsole=true)
Similar as StandardSpeedTestGeometricSeries_HpLaptop24(out SpeedTestInfo, bool), which it calls to do the job, except that it dos not store test information and results, but only retuns the final speed factor calculated.
static double StandardSpeedTestGeometricSeries_DirectElementCalculation_HpLaptop24 (out SpeedTestInfo info, bool writeToConsole=DefaultWriteToConsole_StandardTests)
Performs the standard speed test - calculation of a finite geometric series with specific parameters, with direct calculation of elements of geometric sequence, and with reference results from the machine represented by ConstMachineHpLaptop24.
static double StandardSpeedTestGeometricSeries_DirectElementCalculation_HpLaptop24 (bool writeToConsole=true)
Similar as StandardSpeedTestGeometricSeries_HpLaptop24(out SpeedTestInfo, bool), which it calls to do the job, except that it dos not store test information and results, but only retuns the final speed factor calculated.
Static Public Attributes
const bool DefaultWriteToConsole_StandardTests = true
Default value for the parameter specifying whether results of standad speed tests are written to Console.
Detailed Description
Contains speed testng utilities, mainly as static methods. These usually perform calculations whose execution is deterministic and take the same number of operations every time, such that execution times provide some information of how fast the host computer is in comparison with other computers.
Implementation of tests' algorithms can be external or provided by this class. For examle, GeometricSeriesNumerical(int, double, double) provides implementations of numerically calculating a finite geometric series, which is used in tests like StandardSpeedTestGeometricSeries_HpLaptop24(out SpeedTestInfo, bool). In this case, analytical calculation of the result for verification is also provided by GeometricSeriesAnalytical(int, double, double).
Standard tests take the same parameters of the underlying algorithms in every execution. These parameters are defined as constants in the corresponding sub-classes of the current class. Beside test parameters, the execution time on a reference machine (or differentt machines) are provided. For example, class ConstGeom provided sonstants for the standard test using finite geometric series, StandardSpeedTestGeometricSeries_HpLaptop24(bool)., and property ConstGeom.RefExecutionsPerSecond_HpLaptop24 provides execution time on the machine whose parameters are stored in
When largee inputs are required for tests (such as matrices and vectors), the inputs for standard tests may be generated by a random generator, but the generator should be seeded with a constant value, such that inputs are always the same.
Standard tests have a variant where test execution parameters and results are stored in a SpeedTestInfo object (number of executions or iterations, execution time, ID of the reference machine where reference speed for calculation of speed factor was obtained etc.). The simplified variant just returns the final speed factor and doesn't provide more detailed information. Examples are StandardSpeedTestGeometricSeries_HpLaptop24(out SpeedTestInfo, bool) and StandardSpeedTestGeometricSeries_HpLaptop24(bool).
Machines that are used for obtaining reference test results (used in calculation of speed factors) have their information listed in subclasses' constants, such as ConstMachineHpLaptop24.
Classes providing constants should use standard names for those constants that have a common meaning across different tests or machines. Beside such constants, standard tests will also rely on test-specific constants that define parameters of the algorithm, and these will be named according to usual naminng in the context of specific algorithms (e.g., parameters specific to geometric series ConstGeomBase.a0 and ConstGeomBase.k, while parameters ConstGeomBase.NumExecutions and ConstGeomBase.Tolerance are standard accross a number of tests).
Utilities of this class are tested in the "UtilSpeedTestingTests class". Actual speed tests are performed in the "SpeedTests" class.
Definition at line 47 of file UtilSpeedTesting.cs.
Member Function Documentation
ArithmeticSeriesAnalytical()
static double IGLib.Tests.UtilSpeedTesting.ArithmeticSeriesAnalytical (int n, double a0, double d) inline static
Analytically calculates and returns the specified finite arythmetic series (from the sequence: a_i = a0 + (i-1) * d).
This is mainly used to verify the results of ArithmeticSeriesNumerical(int, double, double), which is used for simple speed tests on the host computer.
Parameters
n Number of terms in the series to be summed.
a0 The first element of the arithmetic sequence.
d Difference between successive elements of the sequence (next - current).
Returns
The sum of elements of the sequence, calculated analytically.
Definition at line 58 of file UtilSpeedTesting.cs.
Referenced by IGLib.Testing.Tests.UtilSpeedTestingTests.UtilSpeedTesting_ArithmeticSeriesAnalyticalMethodIsCorrect(), and IGLib.Testing.Tests.UtilSpeedTestingTests.UtilSpeedTesting_ArithmeticSeriesNumericalMatchesAnalyticalResult().
ArithmeticSeriesNumerical()
static double IGLib.Tests.UtilSpeedTesting.ArithmeticSeriesNumerical (int n, double a0, double d) inline static
Analytically calculates and returns the specified finite arythmetic series (from the sequence: a_i = a0 + (i-1) * d).
This method is mainly used for simple speed tests on the host computer.
Parameters
n Number of terms in the series to be summed.
a0 The first element of the arithmetic sequence.
d Difference between successive elements of the sequence (next - current).
Returns
Thee sum of elements of the sequence, calculated analytically.
Definition at line 70 of file UtilSpeedTesting.cs.
Referenced by IGLib.Testing.Tests.UtilSpeedTestingTests.UtilSpeedTesting_ArithmeticSeriesNumericalMatchesAnalyticalResult().
GeometricSeriesAnalytical()
static double IGLib.Tests.UtilSpeedTesting.GeometricSeriesAnalytical (int n, double a0, double k) inline static
Analytically calculates and returns the specified finite geometric series (from the geometric sequence: a_i = a0 * k^(i-1)).
This is mainly used to verify the results of GeometricSeriesNumerical(int, double, double), which is used for simple speed tests on the host computer.
Parameters
n Number of terms in the series to be summed.
a0 The first element of the geometric sequence.
k Quotient between successive elements of the sequence (next / current).
Returns
The sum of elements of the sequence, calculated analytically.
Definition at line 92 of file UtilSpeedTesting.cs.
Referenced by IGLib.Testing.Tests.SpeedTests.Legacy_StandardSpeedTestGeometricSeries_DirectElementCalculation_OLD(), IGLib.Testing.Tests.SpeedTests.Legacy_StandardSpeedTestGeometricSeries_OLD(), IGLib.Testing.Tests.UtilSpeedTestingTests.StandardSpeedTestPreparationGeometric_ComparingDifferentNumbersOfExecutioin(), IGLib.Testing.Tests.UtilSpeedTestingTests.UtilSpeedTesting_GeometricSeriesAnalyticalMethodIsCorrect(), IGLib.Testing.Tests.UtilSpeedTestingTests.UtilSpeedTesting_GeometricSeriesNumerical_DirectElementCalculation_MatchesAnalyticalResult(), and IGLib.Testing.Tests.UtilSpeedTestingTests.UtilSpeedTesting_GeometricSeriesNumericalMatchesAnalyticalResult().
GeometricSeriesNumerical()
static double IGLib.Tests.UtilSpeedTesting.GeometricSeriesNumerical (int n, double a0, double k) inline static
Numerically calculates and returns the specified finite geometric series (from the geometric sequence: a_i = a0 * k^(i-1)).
This method is mainly used for simple speed tests on the host computer.
Parameters
n Number of terms in the series to be summed.
a0 The first element of the geometric sequence.
k Quotient between successive elements of the sequence (next / current).
Returns
Thee sum of elements of the sequence, calculated numerically.
Definition at line 108 of file UtilSpeedTesting.cs.
Referenced by IGLib.Testing.Tests.SpeedTests.Legacy_StandardSpeedTestGeometricSeries_OLD(), IGLib.Tests.UtilSpeedTesting.StandardSpeedTestGeometricSeries_HpLaptop24(), IGLib.Testing.Tests.UtilSpeedTestingTests.StandardSpeedTestPreparationGeometric_ComparingDifferentNumbersOfExecutioin(), and IGLib.Testing.Tests.UtilSpeedTestingTests.UtilSpeedTesting_GeometricSeriesNumericalMatchesAnalyticalResult().
GeometricSeriesNumerical_DirectElementCalculation()
static double IGLib.Tests.UtilSpeedTesting.GeometricSeriesNumerical_DirectElementCalculation (int n, double a0, double k) inline static
Numerically calculates and returns the specified finite geometric series by calculating each term of the series directly, rather than accumulate it during iteration. (from the geometric sequence: a_i = a0 * k^(i-1)).
This method is mainly used for simple speed tests on the host computer.
Parameters
n Number of terms in the series to be summed.
a0 The first element of the geometric sequence.
k Quotient between successive elements of the sequence (next / current).
Returns
Thee sum of elements of the sequence, calculated numerically.
Definition at line 128 of file UtilSpeedTesting.cs.
Referenced by IGLib.Testing.Tests.SpeedTests.Legacy_StandardSpeedTestGeometricSeries_DirectElementCalculation_OLD(), IGLib.Tests.UtilSpeedTesting.StandardSpeedTestGeometricSeries_DirectElementCalculation_HpLaptop24(), and IGLib.Testing.Tests.UtilSpeedTestingTests.UtilSpeedTesting_GeometricSeriesNumerical_DirectElementCalculation_MatchesAnalyticalResult().
StandardSpeedTestGeometricSeries_HpLaptop24() [1/2]
static double IGLib.Tests.UtilSpeedTesting.StandardSpeedTestGeometricSeries_HpLaptop24 (out SpeedTestInfo info, bool writeToConsole = DefaultWriteToConsole_StandardTests) inline static
Performs the standard speed test - calculation of a finite geometric series with specific parameters, and with reference results from the machine represented by ConstMachineHpLaptop24.
Standard parameters of the test:
ConstGeom.n - number of iterations performed (elemnts of the geometric sequence that are summed).
ConstGeom.a0 - first element of the geometric sequence whose elements are summed.
ConstGeom.k - quotient between subsequent elements of the geometric series.
ConstGeom.Tolerance - tolerance, the allowed absolute discrepancy between the numeric and analytic reault (if out of tolerance, exception is thrown in the test method).
Parameters
info Reference to a SpeedTestInfo object where information about the performed test is stored (parameters, IDs, reference result and machine on which it was produced, test duration, etc.).
writeToConsole Whether results are printed to console. Default is DefaultWriteToConsole_StandardTests.
Returns
The speed factor - speed relative to the reference machine, ConstMachineHpLaptop24.
Exceptions
InvalidOperationException
Definition at line 267 of file UtilSpeedTesting.cs.
References IGLib.Tests.UtilSpeedTesting.ConstGeomBase.a0, IGLib.Tests.UtilSpeedTesting.ConstGeomBase.AnalyticResult, IGLib.Tests.UtilSpeedTesting.GeometricSeriesNumerical(), IGLib.Tests.UtilSpeedTesting.ConstGeomBase.k, IGLib.Tests.UtilSpeedTesting.ConstMachineHpLaptop24.MachineId, IGLib.Tests.UtilSpeedTesting.ConstGeomBase.NumExecutions, IGLib.Tests.UtilSpeedTesting.ConstGeom.RefExecutionsPerSecond_HpLaptop24, IGLib.Tests.UtilSpeedTesting.ConstGeom.TestId, and IGLib.Tests.UtilSpeedTesting.ConstGeomBase.Tolerance.
Referenced by IGLib.Testing.Tests.SpeedTests.StandardSpeedTestGeometricSeries_HpLaptop24(), and IGLib.Tests.UtilSpeedTesting.StandardSpeedTestGeometricSeries_HpLaptop24().
StandardSpeedTestGeometricSeries_HpLaptop24() [2/2]
static double IGLib.Tests.UtilSpeedTesting.StandardSpeedTestGeometricSeries_HpLaptop24 (bool writeToConsole = true) inline static
Similar as StandardSpeedTestGeometricSeries_HpLaptop24(out SpeedTestInfo, bool), which it calls to do the job, except that it dos not store test information and results, but only retuns the final speed factor calculated.
Parameters
writeToConsole Whether information about test execution (parameters and results) are written to Console.
Returns
The speed factor obtained by the test, i.e., the ratio between the numbers of iterations per second performed in the current test execution, divided by the average obtained on the reference machine.
Definition at line 343 of file UtilSpeedTesting.cs.
References IGLib.Tests.UtilSpeedTesting.StandardSpeedTestGeometricSeries_HpLaptop24().
StandardSpeedTestGeometricSeries_DirectElementCalculation_HpLaptop24() [1/2]
static double IGLib.Tests.UtilSpeedTesting.StandardSpeedTestGeometricSeries_DirectElementCalculation_HpLaptop24 (out SpeedTestInfo info, bool writeToConsole = DefaultWriteToConsole_StandardTests) inline static
Performs the standard speed test - calculation of a finite geometric series with specific parameters, with direct calculation of elements of geometric sequence, and with reference results from the machine represented by ConstMachineHpLaptop24.
This speed test is almost identical to StandardSpeedTestGeometricSeries_HpLaptop24(out SpeedTestInfo, bool), except that elements of the geometric
Definition at line 357 of file UtilSpeedTesting.cs.
References IGLib.Tests.UtilSpeedTesting.ConstGeomBase.a0, IGLib.Tests.UtilSpeedTesting.ConstGeomBase.AnalyticResult, IGLib.Tests.UtilSpeedTesting.GeometricSeriesNumerical_DirectElementCalculation(), IGLib.Tests.UtilSpeedTesting.ConstGeomBase.k, IGLib.Tests.UtilSpeedTesting.ConstMachineHpLaptop24.MachineId, IGLib.Tests.UtilSpeedTesting.ConstGeomBase.NumExecutions, IGLib.Tests.UtilSpeedTesting.ConstGeomDirect.RefExecutionsPerSecond_HpLaptop24, IGLib.Tests.UtilSpeedTesting.ConstGeomDirect.TestId, and IGLib.Tests.UtilSpeedTesting.ConstGeomBase.Tolerance.
Referenced by IGLib.Testing.Tests.SpeedTests.StandardSpeedTestGeometricSeries_DirectElementCalculation_HpLaptop24(), and IGLib.Tests.UtilSpeedTesting.StandardSpeedTestGeometricSeries_DirectElementCalculation_HpLaptop24().
StandardSpeedTestGeometricSeries_DirectElementCalculation_HpLaptop24() [2/2]
static double IGLib.Tests.UtilSpeedTesting.StandardSpeedTestGeometricSeries_DirectElementCalculation_HpLaptop24 (bool writeToConsole = true) inline static
Similar as StandardSpeedTestGeometricSeries_HpLaptop24(out SpeedTestInfo, bool), which it calls to do the job, except that it dos not store test information and results, but only retuns the final speed factor calculated.
Parameters
writeToConsole Whether information about test execution (parameters and results) are written to Console.
Returns
The speed factor obtained by the test, i.e., the ratio between the numbers of iterations per second performed in the current test execution, divided by the average obtained on the reference machine.
Definition at line 435 of file UtilSpeedTesting.cs.
References IGLib.Tests.UtilSpeedTesting.StandardSpeedTestGeometricSeries_DirectElementCalculation_HpLaptop24().
Member Data Documentation
DefaultWriteToConsole_StandardTests
const bool IGLib.Tests.UtilSpeedTesting.DefaultWriteToConsole_StandardTests = true static
Default value for the parameter specifying whether results of standad speed tests are written to Console.
Definition at line 245 of file UtilSpeedTesting.cs.
The documentation for this class was generated from the following file:
IGLibCore/src/IGLib.Core/Testing/UtilSpeedTesting.cs