Doc: IGLib with source files: IGLib.Gr3D.ColorMap Class Reference
IGLib.Gr3D.ColorMap Class Reference
Maps scalar values [0, 1] to RGBA colors using predefined color maps.
Static Public Member Functions
static ColorRGBA Map (double u, ColorMapType type)
Gets a color for a normalized scalar input u ∈ [0, 1].
static ColorRGBA Heat (double u)
static ColorRGBA CoolWarm (double u)
static ColorRGBA Grayscale (double u)
static ColorRGBA Jet (double u)
static double Clamp (double value, double min, double max)
Static Private Member Functions
static ColorRGBA Rainbow (double u)
Detailed Description
Maps scalar values [0, 1] to RGBA colors using predefined color maps.
Definition at line 18 of file ColorMap.cs.
Member Function Documentation
Map()
static ColorRGBA IGLib.Gr3D.ColorMap.Map (double u, ColorMapType type) inline static
Gets a color for a normalized scalar input u ∈ [0, 1].
Definition at line 24 of file ColorMap.cs.
References IGLib.Gr3D.ColorMap.Clamp(), IGLib.Gr3D.ColorMap.CoolWarm(), IGLib.Gr3D.ColorMap.Grayscale(), IGLib.Gr3D.ColorMap.Heat(), IGLib.Gr3D.ColorMap.Jet(), and IGLib.Gr3D.ColorMap.Rainbow().
Rainbow()
static ColorRGBA IGLib.Gr3D.ColorMap.Rainbow (double u) inline static private
Definition at line 39 of file ColorMap.cs.
Referenced by IGLib.Gr3D.ColorMap.Map().
Heat()
static ColorRGBA IGLib.Gr3D.ColorMap.Heat (double u) inline static
Definition at line 57 of file ColorMap.cs.
Referenced by IGLib.Gr3D.ColorMap.Map().
CoolWarm()
static ColorRGBA IGLib.Gr3D.ColorMap.CoolWarm (double u) inline static
Definition at line 65 of file ColorMap.cs.
Referenced by IGLib.Gr3D.ColorMap.Map().
Grayscale()
static ColorRGBA IGLib.Gr3D.ColorMap.Grayscale (double u) inline static
Definition at line 73 of file ColorMap.cs.
Referenced by IGLib.Gr3D.ColorMap.Map().
Jet()
static ColorRGBA IGLib.Gr3D.ColorMap.Jet (double u) inline static
Definition at line 79 of file ColorMap.cs.
References IGLib.Gr3D.ColorMap.Clamp().
Referenced by IGLib.Gr3D.ColorMap.Map().
Clamp()
static double IGLib.Gr3D.ColorMap.Clamp (double value, double min, double max) inline static
Definition at line 87 of file ColorMap.cs.
Referenced by IGLib.Gr3D.ColorMap.Jet(), and IGLib.Gr3D.ColorMap.Map().
The documentation for this class was generated from the following file:
IGLibGraphics3D/src/IGLib.Graphics3D/other/Graphics/ColorMap.cs