Doc: IGLib with source files: JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategies.OpenBracketStrategy Class Reference
JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategies.OpenBracketStrategy Class Reference
Public Member Functions
void ExecutePrintyPrint (JsonPPStrategyContext context)
Static Private Member Functions
static bool IsBeginningOfNewLineAndIndentionLevel (JsonPPStrategyContext context)
Additional Inherited Members
Properties inherited from JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.ICharacterStrategy
char ForWhichCharacter [get]
Detailed Description
Definition at line 8 of file OpenBracketStrategy.cs.
Member Function Documentation
ExecutePrintyPrint()
void JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategies.OpenBracketStrategy.ExecutePrintyPrint (JsonPPStrategyContext context) inline
Implements JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.ICharacterStrategy.
Definition at line 10 of file OpenBracketStrategy.cs.
References JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.AppendCurrentChar(), JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.BuildContextIndents(), JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.EnterObjectScope(), JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategies.OpenBracketStrategy.IsBeginningOfNewLineAndIndentionLevel(), and JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.IsProcessingString.
IsBeginningOfNewLineAndIndentionLevel()
static bool JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategies.OpenBracketStrategy.IsBeginningOfNewLineAndIndentionLevel (JsonPPStrategyContext context) inline static private
Definition at line 26 of file OpenBracketStrategy.cs.
References JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.IsInArrayScope, JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.IsProcessingVariableAssignment, and JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.IsStart.
Referenced by JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategies.OpenBracketStrategy.ExecutePrintyPrint().
The documentation for this class was generated from the following file:
iglib/igbase/data/serialization/json/JsonPrettyPrinterInternals/JsonPPStrategies/OpenBracketStrategy.cs