Doc: IGLib with source files: IG.Lib.WaitFileEventBaseByProxyLatence Class Reference
IG.Lib.WaitFileEventBaseByProxyLatence Class Reference
Base class for classes that provide blocking until a file or directory is created/removed. This clas uses a proxy class for performing its basic operation.
Public Member Functions
override bool Condition ()
Returns true if unblocking condition is satisfied, and false otherwise.
override void CancelOne ()
Cancels the current waiting for the condition (if one is going on) and unblocks the thread on which waiting was called (possibly with some latency).
override void Wait ()
Blocks until the specified condition gets satisfied. See class description for details.
override string ToString ()
Public Member Functions inherited from IG.Lib.WaitConditionBase
virtual void CancelAll ()
Cancel the current waiting for the condition on all threads.
Protected Member Functions
WaitFileEventBaseByProxyLatence ()
Protected Attributes
WaitFileEventLatenceBase _waiterLatence
Proxy object that actually performs operations for derived classes of this class.
Properties
virtual string Path [get, set]
Path of the file or directory on which the particular event is waited for. Can be specified as relative path, but is internally stored as fully qualified path.
override bool IsWaiting [get]
Returns true if waiting for unblocking condition is currently performed, and false otherwise. Setting should only be done within the waiting function.
override bool CancelFlag [get, set]
If this flag is set then the current waiting (if one is going on) will be cancelled.
Properties inherited from IG.Lib.WaitConditionBase
object Lock [get]
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
object InternalLock [get]
Used internally for locking access to internal fields.
object WaitLock [get]
Must be used only for locking waiting the Waiting() block (since it is potentially time consuming).
virtual bool IsWaiting [get, protected set]
True if waiting for unblocking condition is currently performed, and false otherwise. Setting should only be done within the waiting function.
virtual bool CancelFlag [get, set]
If this flag is set then the current waiting (if one is going on) will be cancelled.
Properties inherited from IG.Lib.IWaitCondition
bool IsWaiting [get]
Returns true if waiting for unblocking condition is currently performed, and false otherwise. Setting should only be done within the waiting function.
Properties inherited from IG.Lib.ILockable
object Lock [get]
Properties inherited from IG.Lib.IWaitFileEvent
string Path [get, set]
Path of the file or directory on which the particular event is waited for. Can be specified as relative path, but is internally stored as fully qualified path.
Detailed Description
Base class for classes that provide blocking until a file or directory is created/removed. This clas uses a proxy class for performing its basic operation.
$A Igor Jun10; TODO: implement non-latence vaiting (via file events)!
Definition at line 844 of file WaitConditionFile.cs.
Constructor & Destructor Documentation
WaitFileEventBaseByProxyLatence()
IG.Lib.WaitFileEventBaseByProxyLatence.WaitFileEventBaseByProxyLatence () inline protected
Definition at line 846 of file WaitConditionFile.cs.
Member Function Documentation
Condition()
override bool IG.Lib.WaitFileEventBaseByProxyLatence.Condition () inline virtual
Returns true if unblocking condition is satisfied, and false otherwise.
Implements IG.Lib.WaitConditionBase.
Definition at line 858 of file WaitConditionFile.cs.
References IG.Lib.WaitFileEventBaseByProxyLatence._waiterLatence, and IG.Lib.WaitFileEventLatenceBase.Condition().
CancelOne()
override void IG.Lib.WaitFileEventBaseByProxyLatence.CancelOne () inline virtual
Cancels the current waiting for the condition (if one is going on) and unblocks the thread on which waiting was called (possibly with some latency).
Reimplemented from IG.Lib.WaitConditionBase.
Definition at line 880 of file WaitConditionFile.cs.
References IG.Lib.WaitFileEventBaseByProxyLatence._waiterLatence, and IG.Lib.WaitConditionBase.CancelOne().
Wait()
override void IG.Lib.WaitFileEventBaseByProxyLatence.Wait () inline virtual
Blocks until the specified condition gets satisfied. See class description for details.
This method will normally not be overridden, except with intention to change the condition check time plan. When overriding, use the original method as template.
Implements IG.Lib.WaitConditionBase.
Definition at line 888 of file WaitConditionFile.cs.
References IG.Lib.WaitFileEventBaseByProxyLatence._waiterLatence, and IG.Lib.WaitCondition.Wait().
ToString()
override string IG.Lib.WaitFileEventBaseByProxyLatence.ToString () inline
Definition at line 893 of file WaitConditionFile.cs.
References IG.Lib.WaitFileEventBaseByProxyLatence._waiterLatence, and IG.Lib.WaitCondition.ToString().
Member Data Documentation
_waiterLatence
WaitFileEventLatenceBase IG.Lib.WaitFileEventBaseByProxyLatence._waiterLatence protected
Proxy object that actually performs operations for derived classes of this class.
Definition at line 849 of file WaitConditionFile.cs.
Referenced by IG.Lib.WaitFileEventBaseByProxyLatence.CancelOne(), IG.Lib.WaitFileEventBaseByProxyLatence.Condition(), IG.Lib.WaitFileEventBaseByProxyLatence.ToString(), IG.Lib.WaitFileEventBaseByProxyLatence.Wait(), IG.Lib.WaitDirectoryCreationByProxy.WaitDirectoryCreationByProxy(), IG.Lib.WaitDirectoryRemovalByProxy.WaitDirectoryRemovalByProxy(), IG.Lib.WaitFileCreationByProxy.WaitFileCreationByProxy(), and IG.Lib.WaitFileRemovalByProxy.WaitFileRemovalByProxy().
Property Documentation
Path
virtual string IG.Lib.WaitFileEventBaseByProxyLatence.Path get set
Path of the file or directory on which the particular event is waited for. Can be specified as relative path, but is internally stored as fully qualified path.
Definition at line 855 of file WaitConditionFile.cs.
IsWaiting
override bool IG.Lib.WaitFileEventBaseByProxyLatence.IsWaiting get
Returns true if waiting for unblocking condition is currently performed, and false otherwise. Setting should only be done within the waiting function.
Definition at line 867 of file WaitConditionFile.cs.
CancelFlag
override bool IG.Lib.WaitFileEventBaseByProxyLatence.CancelFlag get set protected
If this flag is set then the current waiting (if one is going on) will be cancelled.
Definition at line 873 of file WaitConditionFile.cs.
The documentation for this class was generated from the following file:
iglib/igbase/0unsorted/WaitConditionFile.cs