Doc: IGLib with source files: IG.Lib.ExpressionEvaluatorCompiled Class Reference
IG.Lib.ExpressionEvaluatorCompiled Class Reference abstract
Base class for expression evaluators that utilize the functionality of CodeDomProvider class.
Public Member Functions
ExpressionEvaluatorCompiled ()
Initializes ID and calls the main initialization method (which will typically be overridden in every subclass).
virtual object EvalToObject (string code)
Evaluates JavaScript code and returns result as object.
virtual int EvalToInteger (string code)
Evaluates (interprets) JavaScript code and returns integer result of evaluation. Code must be such that result of evaluation can be interpreted as integer.
virtual double EvalToDouble (string code)
Evaluates (interprets) JavaScript code and returns double result of evaluation. Code must be such that result of evaluation can be interpreted as double.
virtual string EvalToString (string code)
Evaluates (interprets) JavaScript code and returns string result of evaluation. Code must be such that result of evaluation can be interpreted as string.
string GetRepairedCommand (string command)
Repairs the specified command and returns the repaired command string.
virtual void RepairCommand (ref string command)
Repairs the specified command and returns the repaired command string.
virtual string Execute (string inputCode)
Executes the specified code and returns the result. Throws exception if errors occur when interpreting code. After execution, the code is appended to the complete code that has been executed up to this point.
virtual string Compile (string inputDefinitions)
Recompiles the basic script where evaluation is plugged in, with added definitions. Throws exceptions if errors occur when compiling code. After execution, user definitions are added to the base script if compilatin is successful, so that they can be used in subsequent evaluations of code.
void Reset ()
Resets the code evaluator (clears variable definitions, etc.).
virtual void PrintHelpCommandLine ()
Prints help for the command-line JavaScript interpreter to the standard output.
virtual void PrintDefinitions ()
Prints all definitions (preinstalled and user defined).
virtual void PrintCompleteCode ()
Prints the complete code that has been input up to now to the console.
virtual void SaveCompleteCode (string filePath, bool append)
Prints the complete code inserter up to this moment.
virtual void UserSaveCompleteCode (bool append)
Saves or appends the complete code evaluated up to now to a file specified by the user. User is promped for the file to which code is saved.
virtual void SaveUserDefinitions (string filePath, bool append)
Saves or appends to the specified file all valid user definitions added to the evaluator up to this point.
virtual void UserSaveUserDefinitions (bool append)
Saves or appends the all valid user definitions added to the evaluator up to this point. User is promped for the file to which definitions are saved.
virtual void CommandLine ()
Command-line utility where user can successively enter JavaScrit expressions or general portions of code, and evaluates them. Displays prompt to instruct the user, and result of operations.
Static Public Attributes
static int DefaultOutputLevel = 0
Protected Member Functions
abstract void InitExpressionEvaluator ()
virtual string CompileBase ()
Compiles the base script where evaluation is plugged in, and loads the generated assembly and necessary objects.
virtual string CompileBase (string inputDefinitions)
Compiles the base script where evaluation is plugged in, and loads the generated assembly and necessary objects.
virtual string ExecuteUser (string command)
Executes the code, prints results and reports eventual errors. Also appends the code to the complete valid code that has been interpreted up to now.
virtual string CompileUser (string inputDefinitions)
Compiles the specified new definitions. If compilation is successful, the definitions are added to existing definitinos and user is notified through console. Otherwise, error is reported on console.
virtual string ExecuteUser (ref string inpDefinitions, ref string inpCode)
Compiles definitions, if any specified, and executes code, if any specified. Eventual results and errors are reported in console. After execution, code and definitions are set to null.
Protected Attributes
int _outputLevel = DefaultOutputLevel
Default level of output for some of the interpreters' functionality (e.g. asynchronous command execution).
string _language = "unknown"
string _packageName = "Evaluator"
string _className = "EvaluatorClass"
string _evaluationFunctionName = "Eval"
string _inputMark = "Calc> "
char _multiLineCharacter = '\\'
string _commandLineHead
string _commandLineStopNote
string _helpCommandLineHeading
string _helpCommandLine
Properties
int Id [get]
Returns object's Id that is unique within a given type.
int OutputLevel [get, set]
Level of output for some of the interpreter's functionality (e.g. asynchronous command execution).
object Lock [get]
Used for locking internal fields.
virtual string Language [get, protected set]
Programming language in use.
virtual string PackageName [get, protected set]
Name of the JavaScript package in which evaluated code is executed.
virtual string ClassName [get, protected set]
Name of the JavaScript class that is compiled to execute the evaluated code.
virtual string EvaluationFunctionName [get, protected set]
Name of the function used for evaluation of expressions.
virtual string BaseDefinitions [get, protected set]
A set of pre-defined definitions that can be used in the evaluated code.
string CompleteCode [get, protected set]
All valid user code inserted up to this point. Only code that compiled and executed without errors is taken into account.
virtual string UserDefinitions [get, protected set]
A set of definitions inserted by users.
virtual string NewUserDefinitions [get, set]
New user definitions that are added temporarily for testing.
virtual string Definitions [get]
All definitions (pre-defined and user-defined) that can be used in the evaluated code.
abstract string ScriptBase [get]
Container for interpreted code.
virtual string HelpCommandLine [get]
Returns textual help for JavaScript command-line interpreter.
Properties inherited from IG.Lib.ILockable
object Lock [get]
Properties inherited from IG.Lib.IIdentifiable
int Id [get]
Returns unique ID (in the scope of a given type) of the current object.
Private Attributes
int _id = -1
object _lock = new object()
string _baseDefinitions = ""
string _userDefinitions = ""
string _newUserDefinitions = ""
string _completeCode = ""
object _evaluator = null
Type _evaluatorType = null
string _definitionsMark = "Def> "
string _multilineMark = "Calc ml> "
string _resultMark = " = "
string _helpCommand = "?"
string _printDefinitionsCommand = "/pd"
string _printDefinitionsCommand1 = "/printdefinitions"
string _printCodeCommand = "/pc"
string _printCodeCommand1 = "/printcode"
string _evaluationCommand = "/e"
string _evaluationCommand1 = "/evaluate"
string _definitionsCommand = "/d"
string _definitionsCommand1 = "/def"
string _multilineCommand = "/m"
string _multilineCommand1 = "/multiline"
string _saveCodeCommand = "/sc"
string _appendCodeCommand = "/ac"
string _saveDefinitionsComand = "/sd"
string _appendDefinitionsComand = "/ad"
string _resetCommand = "/reset"
string _quitCommand = "/exit"
string _quitCommand1 = "/q"
string _quitCommand2 = "/quit"
char _commandCharacter = '/'
Static Private Attributes
static int _lastId = 0
static object _idLock = new object()
Detailed Description
Base class for expression evaluators that utilize the functionality of CodeDomProvider class.
Definition at line 23 of file ExpressionEvaluatorCompiled.cs.
Constructor & Destructor Documentation
ExpressionEvaluatorCompiled()
IG.Lib.ExpressionEvaluatorCompiled.ExpressionEvaluatorCompiled () inline
Initializes ID and calls the main initialization method (which will typically be overridden in every subclass).
Definition at line 28 of file ExpressionEvaluatorCompiled.cs.
References IG.Lib.ExpressionEvaluatorCompiled._id, IG.Lib.ExpressionEvaluatorCompiled._idLock, IG.Lib.ExpressionEvaluatorCompiled._lastId, and IG.Lib.ExpressionEvaluatorCompiled.InitExpressionEvaluator().
Member Function Documentation
InitExpressionEvaluator()
abstract void IG.Lib.ExpressionEvaluatorCompiled.InitExpressionEvaluator () protected pure virtual
Implemented in IG.Lib.ExpressionEvaluatorJint, and IG.Lib.ExpressionEvaluatorJs.
Referenced by IG.Lib.ExpressionEvaluatorCompiled.ExpressionEvaluatorCompiled().
CompileBase() [1/2]
virtual string IG.Lib.ExpressionEvaluatorCompiled.CompileBase () inline protected virtual
Compiles the base script where evaluation is plugged in, and loads the generated assembly and necessary objects.
Returns
Eventual compilation results.
Definition at line 178 of file ExpressionEvaluatorCompiled.cs.
Referenced by IG.Lib.ExpressionEvaluatorCompiled.Compile(), and IG.Lib.ExpressionEvaluatorJs.InitExpressionEvaluator().
CompileBase() [2/2]
virtual string IG.Lib.ExpressionEvaluatorCompiled.CompileBase (string inputDefinitions) inline protected virtual
Compiles the base script where evaluation is plugged in, and loads the generated assembly and necessary objects.
Parameters
inputDefinitions New definitions that are added to the base script and will not yet be part of permanent definitions (but will become part of them if compilation is successful).
Definition at line 192 of file ExpressionEvaluatorCompiled.cs.
References IG.Lib.ExpressionEvaluatorCompiled._evaluator, IG.Lib.ExpressionEvaluatorCompiled._evaluatorType, IG.Lib.ExpressionEvaluatorCompiled.ClassName, IG.Lib.ExpressionEvaluatorCompiled.Language, IG.Lib.ExpressionEvaluatorCompiled.NewUserDefinitions, IG.Lib.ExpressionEvaluatorCompiled.PackageName, and IG.Lib.ExpressionEvaluatorCompiled.ScriptBase.
EvalToObject()
virtual object IG.Lib.ExpressionEvaluatorCompiled.EvalToObject (string code) inline virtual
Evaluates JavaScript code and returns result as object.
Parameters
code JavaScript code to be evaluated.
Returns
Object that is result of evaluaton of code.
Reimplemented in IG.Lib.ExpressionEvaluatorJint.
Definition at line 217 of file ExpressionEvaluatorCompiled.cs.
References IG.Lib.ExpressionEvaluatorCompiled._evaluator, IG.Lib.ExpressionEvaluatorCompiled._evaluatorType, and IG.Lib.ExpressionEvaluatorCompiled.EvaluationFunctionName.
Referenced by IG.Lib.ExpressionEvaluatorCompiled.EvalToString().
EvalToInteger()
virtual int IG.Lib.ExpressionEvaluatorCompiled.EvalToInteger (string code) inline virtual
Evaluates (interprets) JavaScript code and returns integer result of evaluation. Code must be such that result of evaluation can be interpreted as integer.
Parameters
code Code that is evaluated.
Returns
Definition at line 232 of file ExpressionEvaluatorCompiled.cs.
References IG.Lib.ExpressionEvaluatorCompiled.EvalToString().
EvalToDouble()
virtual double IG.Lib.ExpressionEvaluatorCompiled.EvalToDouble (string code) inline virtual
Evaluates (interprets) JavaScript code and returns double result of evaluation. Code must be such that result of evaluation can be interpreted as double.
Parameters
code Code that is evaluated.
Returns
Definition at line 242 of file ExpressionEvaluatorCompiled.cs.
References IG.Lib.ExpressionEvaluatorCompiled.EvalToString().
EvalToString()
virtual string IG.Lib.ExpressionEvaluatorCompiled.EvalToString (string code) inline virtual
Evaluates (interprets) JavaScript code and returns string result of evaluation. Code must be such that result of evaluation can be interpreted as string.
Parameters
code Code that is evaluated.
Returns
Reimplemented in IG.Lib.ExpressionEvaluatorJint.
Definition at line 252 of file ExpressionEvaluatorCompiled.cs.
References IG.Lib.ExpressionEvaluatorCompiled.EvalToObject().
Referenced by IG.Lib.ExpressionEvaluatorCompiled.EvalToDouble(), IG.Lib.ExpressionEvaluatorCompiled.EvalToInteger(), and IG.Lib.ExpressionEvaluatorCompiled.Execute().
GetRepairedCommand()
string IG.Lib.ExpressionEvaluatorCompiled.GetRepairedCommand (string command) inline
Repairs the specified command and returns the repaired command string.
Reparations serve for easier insertion of commands and for addition of syntactic cookies.
Parameters
command Command to be repaired.
Definition at line 262 of file ExpressionEvaluatorCompiled.cs.
References IG.Lib.ExpressionEvaluatorCompiled.RepairCommand().
Referenced by IG.Lib.ExpressionEvaluatorJint.Execute(), and IG.Lib.ExpressionEvaluatorCompiled.Execute().
RepairCommand()
virtual void IG.Lib.ExpressionEvaluatorCompiled.RepairCommand (ref string command) inline virtual
Repairs the specified command and returns the repaired command string.
Reparations serve for easier insertion of commands and for addition of syntactic cookies.
Parameters
command Command to be repaired.
Reimplemented in IG.Lib.ExpressionEvaluatorJs.
Definition at line 272 of file ExpressionEvaluatorCompiled.cs.
Referenced by IG.Lib.ExpressionEvaluatorCompiled.GetRepairedCommand().
Execute()
virtual string IG.Lib.ExpressionEvaluatorCompiled.Execute (string inputCode) inline virtual
Executes the specified code and returns the result. Throws exception if errors occur when interpreting code. After execution, the code is appended to the complete code that has been executed up to this point.
Parameters
inputCode Code that is exected by the JavaScript interpreter.
Returns
Result of code execution as string.
Reimplemented in IG.Lib.ExpressionEvaluatorJint.
Definition at line 280 of file ExpressionEvaluatorCompiled.cs.
References IG.Lib.ExpressionEvaluatorCompiled.CompleteCode, IG.Lib.ExpressionEvaluatorCompiled.EvalToString(), IG.Lib.ExpressionEvaluatorCompiled.GetRepairedCommand(), and IG.Lib.ExpressionEvaluatorCompiled.OutputLevel.
Referenced by IG.Lib.CommandLineApplicationInterpreter.EvaluateJs(), and IG.Lib.ExpressionEvaluatorCompiled.ExecuteUser().
Compile()
virtual string IG.Lib.ExpressionEvaluatorCompiled.Compile (string inputDefinitions) inline virtual
Recompiles the basic script where evaluation is plugged in, with added definitions. Throws exceptions if errors occur when compiling code. After execution, user definitions are added to the base script if compilatin is successful, so that they can be used in subsequent evaluations of code.
Parameters
inputDefinitions User definitions that are compiled and added to the code.
Returns
Definition at line 307 of file ExpressionEvaluatorCompiled.cs.
References IG.Lib.ExpressionEvaluatorCompiled.CompileBase(), and IG.Lib.ExpressionEvaluatorCompiled.UserDefinitions.
Referenced by IG.Lib.ExpressionEvaluatorCompiled.CompileUser(), and IG.Lib.ExpressionEvaluatorCompiled.Reset().
Reset()
void IG.Lib.ExpressionEvaluatorCompiled.Reset () inline
Resets the code evaluator (clears variable definitions, etc.).
Definition at line 317 of file ExpressionEvaluatorCompiled.cs.
References IG.Lib.ExpressionEvaluatorCompiled.Compile(), IG.Lib.ExpressionEvaluatorCompiled.CompleteCode, and IG.Lib.ExpressionEvaluatorCompiled.UserDefinitions.
Referenced by IG.Lib.ExpressionEvaluatorCompiled.CommandLine().
PrintHelpCommandLine()
virtual void IG.Lib.ExpressionEvaluatorCompiled.PrintHelpCommandLine () inline virtual
Prints help for the command-line JavaScript interpreter to the standard output.
Definition at line 416 of file ExpressionEvaluatorCompiled.cs.
References IG.Lib.ExpressionEvaluatorCompiled.HelpCommandLine.
Referenced by IG.Lib.ExpressionEvaluatorCompiled.CommandLine().
PrintDefinitions()
virtual void IG.Lib.ExpressionEvaluatorCompiled.PrintDefinitions () inline virtual
Prints all definitions (preinstalled and user defined).
Definition at line 420 of file ExpressionEvaluatorCompiled.cs.
References IG.Lib.ExpressionEvaluatorCompiled.Definitions.
Referenced by IG.Lib.ExpressionEvaluatorCompiled.CommandLine().
PrintCompleteCode()
virtual void IG.Lib.ExpressionEvaluatorCompiled.PrintCompleteCode () inline virtual
Prints the complete code that has been input up to now to the console.
Definition at line 427 of file ExpressionEvaluatorCompiled.cs.
References IG.Lib.ExpressionEvaluatorCompiled.CompleteCode.
Referenced by IG.Lib.ExpressionEvaluatorCompiled.CommandLine().
SaveCompleteCode()
virtual void IG.Lib.ExpressionEvaluatorCompiled.SaveCompleteCode (string filePath, bool append) inline virtual
Prints the complete code inserter up to this moment.
Parameters
filePath
append
Definition at line 436 of file ExpressionEvaluatorCompiled.cs.
References IG.Lib.ExpressionEvaluatorCompiled.CompleteCode.
Referenced by IG.Lib.ExpressionEvaluatorCompiled.UserSaveCompleteCode().
UserSaveCompleteCode()
virtual void IG.Lib.ExpressionEvaluatorCompiled.UserSaveCompleteCode (bool append) inline virtual
Saves or appends the complete code evaluated up to now to a file specified by the user. User is promped for the file to which code is saved.
Parameters
append
Definition at line 448 of file ExpressionEvaluatorCompiled.cs.
References IG.Lib.ExpressionEvaluatorCompiled.SaveCompleteCode().
Referenced by IG.Lib.ExpressionEvaluatorCompiled.CommandLine().
SaveUserDefinitions()
virtual void IG.Lib.ExpressionEvaluatorCompiled.SaveUserDefinitions (string filePath, bool append) inline virtual
Saves or appends to the specified file all valid user definitions added to the evaluator up to this point.
Parameters
filePath Path to the file that definitions saved to.
append If true then definitions are appended to the file (old content is preserved).
Definition at line 473 of file ExpressionEvaluatorCompiled.cs.
References IG.Lib.ExpressionEvaluatorCompiled.UserDefinitions.
Referenced by IG.Lib.ExpressionEvaluatorCompiled.UserSaveUserDefinitions().
UserSaveUserDefinitions()
virtual void IG.Lib.ExpressionEvaluatorCompiled.UserSaveUserDefinitions (bool append) inline virtual
Saves or appends the all valid user definitions added to the evaluator up to this point. User is promped for the file to which definitions are saved.
Parameters
append If true then definitions are appended to the file (old content is preserved).
Definition at line 485 of file ExpressionEvaluatorCompiled.cs.
References IG.Lib.ExpressionEvaluatorCompiled.SaveUserDefinitions().
ExecuteUser() [1/2]
virtual string IG.Lib.ExpressionEvaluatorCompiled.ExecuteUser (string command) inline protected virtual
Executes the code, prints results and reports eventual errors. Also appends the code to the complete valid code that has been interpreted up to now.
Parameters
command Command to be executed.
Returns
Definition at line 514 of file ExpressionEvaluatorCompiled.cs.
References IG.Lib.ExpressionEvaluatorCompiled._resultMark, and IG.Lib.ExpressionEvaluatorCompiled.Execute().
Referenced by IG.Lib.ExpressionEvaluatorCompiled.CommandLine(), and IG.Lib.ExpressionEvaluatorCompiled.ExecuteUser().
CompileUser()
virtual string IG.Lib.ExpressionEvaluatorCompiled.CompileUser (string inputDefinitions) inline protected virtual
Compiles the specified new definitions. If compilation is successful, the definitions are added to existing definitinos and user is notified through console. Otherwise, error is reported on console.
Parameters
inputDefinitions User definitions to be added and compiled.
Returns
Eventual results of compilation.
Definition at line 548 of file ExpressionEvaluatorCompiled.cs.
References IG.Lib.ExpressionEvaluatorCompiled.Compile().
Referenced by IG.Lib.ExpressionEvaluatorCompiled.ExecuteUser().
ExecuteUser() [2/2]
virtual string IG.Lib.ExpressionEvaluatorCompiled.ExecuteUser (ref string inpDefinitions, ref string inpCode) inline protected virtual
Compiles definitions, if any specified, and executes code, if any specified. Eventual results and errors are reported in console. After execution, code and definitions are set to null.
Parameters
inpDefinitions User definitions that must be added to existing definitions. If specified then the evaluation code is re-compiled.
inpCode User code that is evaluated.
Returns
Eventual results of evaluation.
Definition at line 574 of file ExpressionEvaluatorCompiled.cs.
References IG.Lib.ExpressionEvaluatorCompiled.CompileUser(), and IG.Lib.ExpressionEvaluatorCompiled.ExecuteUser().
CommandLine()
virtual void IG.Lib.ExpressionEvaluatorCompiled.CommandLine () inline virtual
Command-line utility where user can successively enter JavaScrit expressions or general portions of code, and evaluates them. Displays prompt to instruct the user, and result of operations.
Definition at line 595 of file ExpressionEvaluatorCompiled.cs.
References IG.Lib.ExpressionEvaluatorCompiled._appendCodeCommand, IG.Lib.ExpressionEvaluatorCompiled._commandCharacter, IG.Lib.ExpressionEvaluatorCompiled._commandLineHead, IG.Lib.ExpressionEvaluatorCompiled._commandLineStopNote, IG.Lib.ExpressionEvaluatorCompiled._definitionsCommand, IG.Lib.ExpressionEvaluatorCompiled._definitionsCommand1, IG.Lib.ExpressionEvaluatorCompiled._definitionsMark, IG.Lib.ExpressionEvaluatorCompiled._evaluationCommand, IG.Lib.ExpressionEvaluatorCompiled._evaluationCommand1, IG.Lib.ExpressionEvaluatorCompiled._helpCommand, IG.Lib.ExpressionEvaluatorCompiled._inputMark, IG.Lib.ExpressionEvaluatorCompiled._multiLineCharacter, IG.Lib.ExpressionEvaluatorCompiled._multilineCommand, IG.Lib.ExpressionEvaluatorCompiled._multilineCommand1, IG.Lib.ExpressionEvaluatorCompiled._multilineMark, IG.Lib.ExpressionEvaluatorCompiled._printCodeCommand, IG.Lib.ExpressionEvaluatorCompiled._printCodeCommand1, IG.Lib.ExpressionEvaluatorCompiled._printDefinitionsCommand, IG.Lib.ExpressionEvaluatorCompiled._printDefinitionsCommand1, IG.Lib.ExpressionEvaluatorCompiled._quitCommand, IG.Lib.ExpressionEvaluatorCompiled._quitCommand1, IG.Lib.ExpressionEvaluatorCompiled._quitCommand2, IG.Lib.ExpressionEvaluatorCompiled._resetCommand, IG.Lib.ExpressionEvaluatorCompiled._saveCodeCommand, IG.Lib.ExpressionEvaluatorCompiled.ExecuteUser(), IG.Lib.ExpressionEvaluatorCompiled.PrintCompleteCode(), IG.Lib.ExpressionEvaluatorCompiled.PrintDefinitions(), IG.Lib.ExpressionEvaluatorCompiled.PrintHelpCommandLine(), IG.Lib.ExpressionEvaluatorCompiled.Reset(), and IG.Lib.ExpressionEvaluatorCompiled.UserSaveCompleteCode().
Referenced by IG.Lib.CommandLineApplicationInterpreter.EvaluateJsInteractive(), and IG.Lib.ExpressionEvaluatorJs.ExampleCommandLine().
Member Data Documentation
_lastId
int IG.Lib.ExpressionEvaluatorCompiled._lastId = 0 static private
Definition at line 43 of file ExpressionEvaluatorCompiled.cs.
Referenced by IG.Lib.ExpressionEvaluatorCompiled.ExpressionEvaluatorCompiled().
_idLock
object IG.Lib.ExpressionEvaluatorCompiled._idLock = new object() static private
Definition at line 44 of file ExpressionEvaluatorCompiled.cs.
Referenced by IG.Lib.ExpressionEvaluatorCompiled.ExpressionEvaluatorCompiled().
_id
int IG.Lib.ExpressionEvaluatorCompiled._id = -1 private
Definition at line 45 of file ExpressionEvaluatorCompiled.cs.
Referenced by IG.Lib.ExpressionEvaluatorCompiled.ExpressionEvaluatorCompiled().
DefaultOutputLevel
int IG.Lib.ExpressionEvaluatorCompiled.DefaultOutputLevel = 0 static
Definition at line 55 of file ExpressionEvaluatorCompiled.cs.
_outputLevel
int IG.Lib.ExpressionEvaluatorCompiled._outputLevel = DefaultOutputLevel protected
Default level of output for some of the interpreters' functionality (e.g. asynchronous command execution).
Definition at line 58 of file ExpressionEvaluatorCompiled.cs.
_lock
object IG.Lib.ExpressionEvaluatorCompiled._lock = new object() private
Definition at line 70 of file ExpressionEvaluatorCompiled.cs.
_language
string IG.Lib.ExpressionEvaluatorCompiled._language = "unknown" protected
Definition at line 79 of file ExpressionEvaluatorCompiled.cs.
_packageName
string IG.Lib.ExpressionEvaluatorCompiled._packageName = "Evaluator" protected
Definition at line 80 of file ExpressionEvaluatorCompiled.cs.
_className
string IG.Lib.ExpressionEvaluatorCompiled._className = "EvaluatorClass" protected
Definition at line 81 of file ExpressionEvaluatorCompiled.cs.
_evaluationFunctionName
string IG.Lib.ExpressionEvaluatorCompiled._evaluationFunctionName = "Eval" protected
Definition at line 82 of file ExpressionEvaluatorCompiled.cs.
_baseDefinitions
string IG.Lib.ExpressionEvaluatorCompiled._baseDefinitions = "" private
Definition at line 115 of file ExpressionEvaluatorCompiled.cs.
_userDefinitions
string IG.Lib.ExpressionEvaluatorCompiled._userDefinitions = "" private
Definition at line 116 of file ExpressionEvaluatorCompiled.cs.
_newUserDefinitions
string IG.Lib.ExpressionEvaluatorCompiled._newUserDefinitions = "" private
Definition at line 117 of file ExpressionEvaluatorCompiled.cs.
_completeCode
string IG.Lib.ExpressionEvaluatorCompiled._completeCode = "" private
Definition at line 118 of file ExpressionEvaluatorCompiled.cs.
_evaluator
object IG.Lib.ExpressionEvaluatorCompiled._evaluator = null private
Definition at line 183 of file ExpressionEvaluatorCompiled.cs.
Referenced by IG.Lib.ExpressionEvaluatorCompiled.CompileBase(), and IG.Lib.ExpressionEvaluatorCompiled.EvalToObject().
_evaluatorType
Type IG.Lib.ExpressionEvaluatorCompiled._evaluatorType = null private
Definition at line 185 of file ExpressionEvaluatorCompiled.cs.
Referenced by IG.Lib.ExpressionEvaluatorCompiled.CompileBase(), and IG.Lib.ExpressionEvaluatorCompiled.EvalToObject().
_inputMark
string IG.Lib.ExpressionEvaluatorCompiled._inputMark = "Calc> " protected
Definition at line 329 of file ExpressionEvaluatorCompiled.cs.
Referenced by IG.Lib.ExpressionEvaluatorCompiled.CommandLine(), IG.Lib.ExpressionEvaluatorJs.InitExpressionEvaluator(), and IG.Lib.ExpressionEvaluatorJint.InitExpressionEvaluator().
_definitionsMark
string IG.Lib.ExpressionEvaluatorCompiled._definitionsMark = "Def> " private
Definition at line 330 of file ExpressionEvaluatorCompiled.cs.
Referenced by IG.Lib.ExpressionEvaluatorCompiled.CommandLine(), IG.Lib.ExpressionEvaluatorJs.InitExpressionEvaluator(), and IG.Lib.ExpressionEvaluatorJint.InitExpressionEvaluator().
_multilineMark
string IG.Lib.ExpressionEvaluatorCompiled._multilineMark = "Calc ml> " private
Definition at line 331 of file ExpressionEvaluatorCompiled.cs.
Referenced by IG.Lib.ExpressionEvaluatorCompiled.CommandLine(), IG.Lib.ExpressionEvaluatorJs.InitExpressionEvaluator(), and IG.Lib.ExpressionEvaluatorJint.InitExpressionEvaluator().
_resultMark
string IG.Lib.ExpressionEvaluatorCompiled._resultMark = " = " private
Definition at line 332 of file ExpressionEvaluatorCompiled.cs.
Referenced by IG.Lib.ExpressionEvaluatorCompiled.ExecuteUser(), and IG.Lib.ExpressionEvaluatorJs.InitExpressionEvaluator().
_helpCommand
string IG.Lib.ExpressionEvaluatorCompiled._helpCommand = "?" private
Definition at line 334 of file ExpressionEvaluatorCompiled.cs.
Referenced by IG.Lib.ExpressionEvaluatorCompiled.CommandLine().
_printDefinitionsCommand
string IG.Lib.ExpressionEvaluatorCompiled._printDefinitionsCommand = "/pd" private
Definition at line 335 of file ExpressionEvaluatorCompiled.cs.
Referenced by IG.Lib.ExpressionEvaluatorCompiled.CommandLine().
_printDefinitionsCommand1
string IG.Lib.ExpressionEvaluatorCompiled._printDefinitionsCommand1 = "/printdefinitions" private
Definition at line 336 of file ExpressionEvaluatorCompiled.cs.
Referenced by IG.Lib.ExpressionEvaluatorCompiled.CommandLine().
_printCodeCommand
string IG.Lib.ExpressionEvaluatorCompiled._printCodeCommand = "/pc" private
Definition at line 337 of file ExpressionEvaluatorCompiled.cs.
Referenced by IG.Lib.ExpressionEvaluatorCompiled.CommandLine().
_printCodeCommand1
string IG.Lib.ExpressionEvaluatorCompiled._printCodeCommand1 = "/printcode" private
Definition at line 338 of file ExpressionEvaluatorCompiled.cs.
Referenced by IG.Lib.ExpressionEvaluatorCompiled.CommandLine().
_evaluationCommand
string IG.Lib.ExpressionEvaluatorCompiled._evaluationCommand = "/e" private
Definition at line 339 of file ExpressionEvaluatorCompiled.cs.
Referenced by IG.Lib.ExpressionEvaluatorCompiled.CommandLine().
_evaluationCommand1
string IG.Lib.ExpressionEvaluatorCompiled._evaluationCommand1 = "/evaluate" private
Definition at line 340 of file ExpressionEvaluatorCompiled.cs.
Referenced by IG.Lib.ExpressionEvaluatorCompiled.CommandLine().
_definitionsCommand
string IG.Lib.ExpressionEvaluatorCompiled._definitionsCommand = "/d" private
Definition at line 341 of file ExpressionEvaluatorCompiled.cs.
Referenced by IG.Lib.ExpressionEvaluatorCompiled.CommandLine().
_definitionsCommand1
string IG.Lib.ExpressionEvaluatorCompiled._definitionsCommand1 = "/def" private
Definition at line 342 of file ExpressionEvaluatorCompiled.cs.
Referenced by IG.Lib.ExpressionEvaluatorCompiled.CommandLine().
_multilineCommand
string IG.Lib.ExpressionEvaluatorCompiled._multilineCommand = "/m" private
Definition at line 343 of file ExpressionEvaluatorCompiled.cs.
Referenced by IG.Lib.ExpressionEvaluatorCompiled.CommandLine().
_multilineCommand1
string IG.Lib.ExpressionEvaluatorCompiled._multilineCommand1 = "/multiline" private
Definition at line 344 of file ExpressionEvaluatorCompiled.cs.
Referenced by IG.Lib.ExpressionEvaluatorCompiled.CommandLine().
_saveCodeCommand
string IG.Lib.ExpressionEvaluatorCompiled._saveCodeCommand = "/sc" private
Definition at line 346 of file ExpressionEvaluatorCompiled.cs.
Referenced by IG.Lib.ExpressionEvaluatorCompiled.CommandLine().
_appendCodeCommand
string IG.Lib.ExpressionEvaluatorCompiled._appendCodeCommand = "/ac" private
Definition at line 347 of file ExpressionEvaluatorCompiled.cs.
Referenced by IG.Lib.ExpressionEvaluatorCompiled.CommandLine().
_saveDefinitionsComand
string IG.Lib.ExpressionEvaluatorCompiled._saveDefinitionsComand = "/sd" private
Definition at line 348 of file ExpressionEvaluatorCompiled.cs.
_appendDefinitionsComand
string IG.Lib.ExpressionEvaluatorCompiled._appendDefinitionsComand = "/ad" private
Definition at line 349 of file ExpressionEvaluatorCompiled.cs.
_resetCommand
string IG.Lib.ExpressionEvaluatorCompiled._resetCommand = "/reset" private
Definition at line 350 of file ExpressionEvaluatorCompiled.cs.
Referenced by IG.Lib.ExpressionEvaluatorCompiled.CommandLine().
_quitCommand
string IG.Lib.ExpressionEvaluatorCompiled._quitCommand = "/exit" private
Definition at line 351 of file ExpressionEvaluatorCompiled.cs.
Referenced by IG.Lib.ExpressionEvaluatorCompiled.CommandLine().
_quitCommand1
string IG.Lib.ExpressionEvaluatorCompiled._quitCommand1 = "/q" private
Definition at line 352 of file ExpressionEvaluatorCompiled.cs.
Referenced by IG.Lib.ExpressionEvaluatorCompiled.CommandLine().
_quitCommand2
string IG.Lib.ExpressionEvaluatorCompiled._quitCommand2 = "/quit" private
Definition at line 353 of file ExpressionEvaluatorCompiled.cs.
Referenced by IG.Lib.ExpressionEvaluatorCompiled.CommandLine().
_multiLineCharacter
char IG.Lib.ExpressionEvaluatorCompiled._multiLineCharacter = '\\' protected
Definition at line 356 of file ExpressionEvaluatorCompiled.cs.
Referenced by IG.Lib.ExpressionEvaluatorCompiled.CommandLine().
_commandCharacter
char IG.Lib.ExpressionEvaluatorCompiled._commandCharacter = '/' private
Definition at line 357 of file ExpressionEvaluatorCompiled.cs.
Referenced by IG.Lib.ExpressionEvaluatorCompiled.CommandLine().
_commandLineHead
string IG.Lib.ExpressionEvaluatorCompiled._commandLineHead protected
Initial value:
= @"
Command-line Calculator:
Insert expressions or commands!
/m for multiline mode, /d for definitions, /e to evaluate, /q to exit!
End line with '\\' to input multiline code, ? for help!
"
Definition at line 360 of file ExpressionEvaluatorCompiled.cs.
Referenced by IG.Lib.ExpressionEvaluatorCompiled.CommandLine(), and IG.Lib.ExpressionEvaluatorJs.InitExpressionEvaluator().
_commandLineStopNote
string IG.Lib.ExpressionEvaluatorCompiled._commandLineStopNote protected
Initial value:
= @"
Command-line calculator stopped.
"
Definition at line 370 of file ExpressionEvaluatorCompiled.cs.
Referenced by IG.Lib.ExpressionEvaluatorCompiled.CommandLine(), and IG.Lib.ExpressionEvaluatorJs.InitExpressionEvaluator().
_helpCommandLineHeading
string IG.Lib.ExpressionEvaluatorCompiled._helpCommandLineHeading protected
Initial value:
= @"
Command-line Expression Evaluator Help:
Insert valid code or special commands one line after another!
Quit with '\q' ."
Definition at line 376 of file ExpressionEvaluatorCompiled.cs.
Referenced by IG.Lib.ExpressionEvaluatorJs.InitExpressionEvaluator().
_helpCommandLine
string IG.Lib.ExpressionEvaluatorCompiled._helpCommandLine protected
Initial value:
= @"
Special commands must be inserted without leading spaces.
End lines with '\\' in order to insert multiline code.
List of commands:
  ? : prints this help
  /e or /evaluate : insertion and evaluation of code
  /m or /multiline : insertion and evaluation of multiple lines
  /d or /def : insertion of definitions (multiline)
  /pc or /printcode: prints the current code contained in the buffer
  /pd or /printdefinitions: prints definitions (user and predefined)
  /sc : saves the evaluated code to a file (file path prompted)
  /ac : appends the evaluated code to a file (file path prompted)
  /sd : saves all added definitions to a file (file path prompted)
  /ad : appends all added definitons to a file (file path prompted)
  /reset : resets the evaluator
  /q or /quit or /exit : exits command-line evaluator
Syntactic specifics:
Automatic variable declaration does not work.
    All variables must be declared with 'var'.
Invalid code is ignored (with error report launched).
    This enables you to re-enter corrected code.
The last valid result will be returned.
The last expression does not need to (but it can) end with semicolon.
"
Definition at line 381 of file ExpressionEvaluatorCompiled.cs.
Property Documentation
Id
int IG.Lib.ExpressionEvaluatorCompiled.Id get
Returns object's Id that is unique within a given type.
Definition at line 48 of file ExpressionEvaluatorCompiled.cs.
OutputLevel
int IG.Lib.ExpressionEvaluatorCompiled.OutputLevel get set
Level of output for some of the interpreter's functionality (e.g. asynchronous command execution).
Definition at line 62 of file ExpressionEvaluatorCompiled.cs.
Referenced by IG.Lib.CommandLineApplicationInterpreter.CmdOutputLevelCalc(), IG.Lib.ExpressionEvaluatorJint.Execute(), and IG.Lib.ExpressionEvaluatorCompiled.Execute().
Lock
object IG.Lib.ExpressionEvaluatorCompiled.Lock get
Used for locking internal fields.
Definition at line 73 of file ExpressionEvaluatorCompiled.cs.
Language
virtual string IG.Lib.ExpressionEvaluatorCompiled.Language get protected set
Programming language in use.
Definition at line 86 of file ExpressionEvaluatorCompiled.cs.
Referenced by IG.Lib.ExpressionEvaluatorCompiled.CompileBase(), IG.Lib.ExpressionEvaluatorJs.InitExpressionEvaluator(), and IG.Lib.ExpressionEvaluatorJint.InitExpressionEvaluator().
PackageName
virtual string IG.Lib.ExpressionEvaluatorCompiled.PackageName get protected set
Name of the JavaScript package in which evaluated code is executed.
Definition at line 93 of file ExpressionEvaluatorCompiled.cs.
Referenced by IG.Lib.ExpressionEvaluatorCompiled.CompileBase(), IG.Lib.ExpressionEvaluatorJs.InitExpressionEvaluator(), and IG.Lib.ExpressionEvaluatorJint.InitExpressionEvaluator().
ClassName
virtual string IG.Lib.ExpressionEvaluatorCompiled.ClassName get protected set
Name of the JavaScript class that is compiled to execute the evaluated code.
Definition at line 100 of file ExpressionEvaluatorCompiled.cs.
Referenced by IG.Lib.ExpressionEvaluatorCompiled.CompileBase(), IG.Lib.ExpressionEvaluatorJs.InitExpressionEvaluator(), and IG.Lib.ExpressionEvaluatorJint.InitExpressionEvaluator().
EvaluationFunctionName
virtual string IG.Lib.ExpressionEvaluatorCompiled.EvaluationFunctionName get protected set
Name of the function used for evaluation of expressions.
Definition at line 107 of file ExpressionEvaluatorCompiled.cs.
Referenced by IG.Lib.ExpressionEvaluatorCompiled.EvalToObject().
BaseDefinitions
virtual string IG.Lib.ExpressionEvaluatorCompiled.BaseDefinitions get protected set
A set of pre-defined definitions that can be used in the evaluated code.
Definition at line 122 of file ExpressionEvaluatorCompiled.cs.
CompleteCode
string IG.Lib.ExpressionEvaluatorCompiled.CompleteCode get protected set
All valid user code inserted up to this point. Only code that compiled and executed without errors is taken into account.
Definition at line 130 of file ExpressionEvaluatorCompiled.cs.
Referenced by IG.Lib.ExpressionEvaluatorJint.Execute(), IG.Lib.ExpressionEvaluatorCompiled.Execute(), IG.Lib.ExpressionEvaluatorCompiled.PrintCompleteCode(), IG.Lib.ExpressionEvaluatorCompiled.Reset(), and IG.Lib.ExpressionEvaluatorCompiled.SaveCompleteCode().
UserDefinitions
virtual string IG.Lib.ExpressionEvaluatorCompiled.UserDefinitions get protected set
A set of definitions inserted by users.
Definition at line 138 of file ExpressionEvaluatorCompiled.cs.
Referenced by IG.Lib.ExpressionEvaluatorCompiled.Compile(), IG.Lib.ExpressionEvaluatorCompiled.Reset(), and IG.Lib.ExpressionEvaluatorCompiled.SaveUserDefinitions().
NewUserDefinitions
virtual string IG.Lib.ExpressionEvaluatorCompiled.NewUserDefinitions get set protected
New user definitions that are added temporarily for testing.
Definition at line 145 of file ExpressionEvaluatorCompiled.cs.
Referenced by IG.Lib.ExpressionEvaluatorCompiled.CompileBase().
Definitions
virtual string IG.Lib.ExpressionEvaluatorCompiled.Definitions get
All definitions (pre-defined and user-defined) that can be used in the evaluated code.
Definition at line 152 of file ExpressionEvaluatorCompiled.cs.
Referenced by IG.Lib.ExpressionEvaluatorCompiled.PrintDefinitions().
ScriptBase
abstract string IG.Lib.ExpressionEvaluatorCompiled.ScriptBase get protected
Container for interpreted code.
When overridden in subclasses, this property will be dynamic (i.e. each get accessor will generate the value anew), and the value will depend on current values of the package, class and function name as well as additonal definitions input by user.
Definition at line 165 of file ExpressionEvaluatorCompiled.cs.
Referenced by IG.Lib.ExpressionEvaluatorCompiled.CompileBase().
HelpCommandLine
virtual string IG.Lib.ExpressionEvaluatorCompiled.HelpCommandLine get
Returns textual help for JavaScript command-line interpreter.
Returns
Definition at line 411 of file ExpressionEvaluatorCompiled.cs.
Referenced by IG.Lib.ExpressionEvaluatorCompiled.PrintHelpCommandLine().
The documentation for this class was generated from the following file:
iglib/igbase/interpreters/ExpressionEvaluatorCompiled.cs