Doc: IGLib with source files: IG.Neural.DataMapperIdentity Class Reference
IG.Neural.DataMapperIdentity Class Reference
Public Member Functions
DataMapperIdentity ()
virtual void MapInput (IVector reducedInput, ref IVector originalInput)
Transfers elemts of reducedInput vector in the originalInput vector.
virtual void MapOutput (IVector originalOutput, ref IVector reducedOutput)
Transfers elemts of originalOutput vector in the reducedOutput vector.
Detailed Description
Definition at line 955 of file NeuralMapData.cs.
Constructor & Destructor Documentation
DataMapperIdentity()
IG.Neural.DataMapperIdentity.DataMapperIdentity () inline
Definition at line 958 of file NeuralMapData.cs.
Member Function Documentation
MapInput()
virtual void IG.Neural.DataMapperIdentity.MapInput (IVector reducedInput, ref IVector originalInput) inline virtual
Transfers elemts of reducedInput vector in the originalInput vector.
Parameters
reducedInput reducedInput elements.
originalInput originalInput elements.
$A Igor Jul 19; tako78 Jul 19
Implements IG.Neural.IDataMapper.
Reimplemented in IG.Neural.DataMapperSimple.
Definition at line 966 of file NeuralMapData.cs.
References IG.Num.VectorBase.Copy().
Referenced by IG.Neural.MappingApproximationFileManager.ClientTestCalculateMappingApproximation(), and IG.Neural.MappingApproximationFileManager.ServerCalculateMappingApproximation().
MapOutput()
virtual void IG.Neural.DataMapperIdentity.MapOutput (IVector originalOutput, ref IVector reducedOutput) inline virtual
Transfers elemts of originalOutput vector in the reducedOutput vector.
Parameters
originalOutput originalOutput elements.
reducedOutput reducedOutput elements.
$A Igor Jul 19; tako78 Jul 19
Implements IG.Neural.IDataMapper.
Reimplemented in IG.Neural.DataMapperSimple.
Definition at line 976 of file NeuralMapData.cs.
References IG.Num.VectorBase.Copy().
Referenced by IG.Neural.MappingApproximationFileManager.ClientTestCalculateMappingApproximation(), and IG.Neural.MappingApproximationFileManager.ServerCalculateMappingApproximation().
The documentation for this class was generated from the following file:
iglib/igbase/numeric/approximation/neural/testneural/NeuralMapData.cs