Doc: IGLib with source files: IGLib.Core.FromStringTypeConverterViaParseReflection Class Reference
IGLib.Core.FromStringTypeConverterViaParseReflection Class Reference
Converts from string to a specific type using TryParse or Parse methods via reflection. Uses invariant culture to ensure consistent behavior across environments.
Public Member Functions
TargetType ConvertTyped< TargetType > (string source)
bool TryConvertTyped< TargetType > (string source, out TargetType target)
object Convert (object source, Type targetType)
bool TryConvert (object source, out object target, Type targetType)
Public Member Functions inherited from IGLib.Core.ISingleSourceTypeConverter< string >
TargetType ConvertTyped< TargetType > (SourceType source)
bool TryConvertTyped< TargetType > (SourceType source, out TargetType target)
object Convert (object source, Type targetType)
bool TryConvert (object source, out object target, Type targetType)
Public Attributes
Type SourceType => typeof(string)
Additional Inherited Members
Properties inherited from IGLib.Core.ISingleSourceTypeConverter< string >
Type SourceType [get]
Detailed Description
Converts from string to a specific type using TryParse or Parse methods via reflection. Uses invariant culture to ensure consistent behavior across environments.
Definition at line 11 of file FromStringTypeConverterViaParseReflection.cs.
Member Function Documentation
ConvertTyped< TargetType >()
TargetType IGLib.Core.FromStringTypeConverterViaParseReflection.ConvertTyped< TargetType > (string source) inline
Definition at line 17 of file FromStringTypeConverterViaParseReflection.cs.
References IGLib.Core.FromStringTypeConverterViaParseReflection.TryConvertTyped< TargetType >().
TryConvertTyped< TargetType >()
bool IGLib.Core.FromStringTypeConverterViaParseReflection.TryConvertTyped< TargetType > (string source, out TargetType target) inline
Definition at line 26 of file FromStringTypeConverterViaParseReflection.cs.
Referenced by IGLib.Core.FromStringTypeConverterViaParseReflection.ConvertTyped< TargetType >().
Convert()
object IGLib.Core.FromStringTypeConverterViaParseReflection.Convert (object source, Type targetType) inline
Definition at line 74 of file FromStringTypeConverterViaParseReflection.cs.
References IGLib.Core.FromStringTypeConverterViaParseReflection.TryConvert().
TryConvert()
bool IGLib.Core.FromStringTypeConverterViaParseReflection.TryConvert (object source, out object target, Type targetType) inline
Definition at line 83 of file FromStringTypeConverterViaParseReflection.cs.
Referenced by IGLib.Core.FromStringTypeConverterViaParseReflection.Convert().
Member Data Documentation
SourceType
Type IGLib.Core.FromStringTypeConverterViaParseReflection.SourceType => typeof(string)
Definition at line 14 of file FromStringTypeConverterViaParseReflection.cs.
The documentation for this class was generated from the following file:
IGLibGraphics3D/src/IGLib.Graphics3D/other/TypeConversionExtended/SingleConverters/SpecificConverters/FromStringTypeConverterViaParseReflection.cs