Doc: IGLib with source files: IG.Lib.CommandStackFrameBase Class Reference
IG.Lib.CommandStackFrameBase Class Reference abstract
Base class for classes of type CommandStackFrame{InterpreterType, ThreadType}see cref=""/>. Contains everyting that does not depend on specific type of generic parameters.
Public Member Functions
CommandStackFrameBase ()
abstract ICommandLineApplicationInterpreter GetInterpreterBase ()
Returns the commans-line interpreter to which the current command thread belongs.
abstract CommandThreadBase GetThreadBase ()
Returns the stack frame of the specified level for the current thread.
void AddBlockEnterCommands (params string[] commands)
Adds the specified strings to the list of commands that can enter the current kind of the code block.
void AddBlockExitCommands (params string[] commands)
Adds the specified strings to the list of commands that can exit the current kind of the code block.
void AddBlockExitCommandsNoLevelEffect (params string[] commands)
Adds the specified strings to the list of commands that can exit the current kind of the code block, but don't affect the quiet entry/exit level.
string[] GetBlockEnterCommands ()
Returns the array of commands that can enter the current kind of code block.
string[] GetBlockExitCommands ()
Returns the array of commands that can exit the current kind of code block.
string[] GetBlockExitCommandsNoLevelEffect ()
Returns the array of commands that can exit the current kind of code block but have no level effect.
bool IsEventualBlockEnterCommand (string commandLine, bool isOnlyCommandName=false)
Returns true if the specified commandline can eventually represent one of the commands contained in the list of possible block enter commands for the current kind of code block.
bool IsEventualBlockExitCommand (string commandLine, bool isOnlyCommandName=false)
Returns true if the specified commandline can eventually represent one of the commands contained in the list of possible block exit commands for the current kind of code block.
bool IsEventualBlockExitCommandNoLevelEffect (string commandLine, bool isOnlyCommandName=false)
Returns true if the specified commandline can eventually represent one of the commands contained in the list of possible block exit commands that do not affect quiet entry/exit level, for the current kind of code block.
bool CheckForBlockEnterOrExitCommand (string commandLine, bool justCheck=false, bool isOnlyCommandName=false)
Inspects the specified commandline and checks whether it can represent a block enter or a block exit command for the currennt code block.
bool IsBlockExitQuietCommand (string commandLine, bool isOnlyCommandName=false)
Returns true if the specified command should be executed as block exit command, in spite of the fact that commannd execution is currently switched off on the current code block.
bool IsVariableDefined (string varName)
Returns true if the specified variable is defined, false if it is not.
bool IsVariableDefinedLocked (string varName)
Returns true if the specified variable is defined, false if it is not.
InterpreterVariable GetVariableDef (string varName)
Returns variable object (definition) for the variable with specified name.
string GetVariableValue (string varName)
Returns value of the specified variable.
string GetVariableValueLocked (string varName)
Gets the variable within lock on the Lock property and returns it.
void SetVariableValue (string varName, string varValue, VariableFlags flags=VariableFlags.Default)
Sets value of the specified variable.
void SetVariableValueLocked (string varName, string varValue, VariableFlags flags=VariableFlags.Default)
Sets the variable within lock on the property.
void RemoveVariable (string varName)
Removes the specified variable.
void RemoveVariableLocked (string varName)
Removes the specified variable within lock on the property.
string ToStringVariableNames ()
string ToStringVariableValues ()
virtual string ToString (bool includeThreadInfo=true, bool includeLocalVariables=true, bool includeGlobalVariables=true)
Returns a string containing information about the current command thread.
override string ToString ()
Returns string representation of the current object.
Protected Member Functions
bool IsEventualListedCommand (string commandLine, List< string > commands, bool isOnlyCommandName=false)
Returns true if the specified commandline can eventually represent one of the commands contained in the specified list of commands.
Protected Attributes
int _quietBlockLevel = 0
SortedDictionary< string, InterpreterVariable > _variables = new SortedDictionary<string, InterpreterVariable>()
Local variables.
List< string > _auxVarNames = null
Properties
object Lock [get]
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
int StackLevel [get, protected set]
List< string > BlockEnterCommands [get]
A list of commands that can enter the type of the current code block.
List< string > BlockExitCommands [get]
A list of commands that can exit the type of the current code block.
List< string > BlockExitCommandsNoLevelEffect [get]
A list of commands that can exit the type of the current code block, but willl nnot have effect on the quet wxit/entry level.
int QuietBlockEntryLevel [get, protected set]
Indicates the quiet entry/exit level of the current kind of block when commands are not executed.
CodeBlockType BlockType [get, protected set]
Type of the code block represented by the current stack frame.
bool DoExecuteCommands [get, set]
Whether commands are executed in the current code block.
bool WasBranchAlreadyExecuted [get, set]
Whether a branch has already been executed.
int NumExitLevels [get, set]
int LoopCount [get, set]
Whether commands are executed in the current code block.
bool SuppressInteractive [get, set]
Indicates that the interactive mode is temporarily represset.
string ConditionExpression [get, set]
For loopig and branching blocks, this property contains the condition expression of the block, which was a part of the block command (such as While, If, or ElseIf).
string BlockCommanddLine [get, set]
Commandline that started the current block. It may have been saved when the current block of code was entered, in order to be used within the block (e.g. for inspection and debugging) or when the block exits. Typical use is in blocks with deferred evaluation, such as in While block, where commandlines within the block are stored first, and then repeatedly evaluated until the condition from the While block entering command is fulfilled.
bool DoSaveCommands [get, set]
Whether commands are saved to the command store in the current code block.
List< string > CommandLines [get]
string LastCommandLine [get, set]
string ReturnedValue [get, set]
Value returned from the last executed command.
string[] VariableNames [get]
Gets names of all variables that are defined on the current stack frame.
string[] VariableValueStrings [get]
Gets names of all variables that are defined on the current stack frame.
InterpreterVariable this[string variableName] [get, set]
Gets or sets value of the variable with the specified name.
Private Attributes
object _mainLock = new object()
int _stackLevel = 0
List< string > _blockEnterCommands = null
List< string > _blockExitCommands = null
List< string > _blockExitCommandsNoLevelffect = null
CodeBlockType _blockType = CodeBlockType.None
bool _doExecute = true
bool _isBranchExecuted = false
int _numExitLevels = 0
int _loopCount = 0
bool _suppressInteractive = false
string _conditionExpression = null
string _blockCommandLine = null
bool _doSave = false
List< string > _commandLines = null
string _lastCommandLine = null
string _returnedValue = null
Detailed Description
Base class for classes of type CommandStackFrame{InterpreterType, ThreadType}see cref=""/>. Contains everyting that does not depend on specific type of generic parameters.
Definition at line 896 of file CommandlineApplicationInterpreterBase.cs.
Constructor & Destructor Documentation
CommandStackFrameBase()
IG.Lib.CommandStackFrameBase.CommandStackFrameBase () inline
Definition at line 899 of file CommandlineApplicationInterpreterBase.cs.
Member Function Documentation
GetInterpreterBase()
abstract ICommandLineApplicationInterpreter IG.Lib.CommandStackFrameBase.GetInterpreterBase () pure virtual
Returns the commans-line interpreter to which the current command thread belongs.
WARNING: This method is intended for use in the base classes; use more specific (type dependent) methods in derived classes.
Implemented in IG.Lib.CommandStackFrame< InterpreterType, ThreadType >.
Referenced by IG.Lib.CommandStackFrameBase.ToString().
GetThreadBase()
abstract CommandThreadBase IG.Lib.CommandStackFrameBase.GetThreadBase () pure virtual
Returns the stack frame of the specified level for the current thread.
WARNING: This method is intended for use in the base classes; use more specific (type dependent) methods in derived classes.
Command thread (if not replicated for another one) begins executon at stack level 0, then each command block or function call increments the stack level by creating a new stack frame.
Implemented in IG.Lib.CommandStackFrame< InterpreterType, ThreadType >.
Referenced by IG.Lib.CommandStackFrameBase.ToString().
AddBlockEnterCommands()
void IG.Lib.CommandStackFrameBase.AddBlockEnterCommands (params string[] commands) inline
Adds the specified strings to the list of commands that can enter the current kind of the code block.
Warnig: Kind of the code block is not defined by the CodeBlockType in this context, because each type listed in the enumeration can refer to several customly defined subtypes of code blocks.
This list is used as list of commands to be monitored when in the non-executable mode (where commands are not actually executed) in order to know when the command is hit that will end the block, and therefore exit the block that is in non-executable more.
Parameters
commands Commands that are added to the list of commands that can enter the current kind of block.
Definition at line 990 of file CommandlineApplicationInterpreterBase.cs.
References IG.Lib.CommandStackFrameBase.BlockEnterCommands.
AddBlockExitCommands()
void IG.Lib.CommandStackFrameBase.AddBlockExitCommands (params string[] commands) inline
Adds the specified strings to the list of commands that can exit the current kind of the code block.
Warnig: Kind of the code block is not defined by the CodeBlockType in this context, because each type listed in the enumeration can refer to several customly defined subtypes of code blocks.
This list is used as list of commands to be monitored when in the non-executable mode (where commands are not actually executed) in order to know when the command is hit that will end the block, and therefore exit the block that is in non-executable more.
Parameters
commands Commands that are added to the list of commands that can enter the current kind of block.
Definition at line 1004 of file CommandlineApplicationInterpreterBase.cs.
References IG.Lib.CommandStackFrameBase.BlockExitCommands.
AddBlockExitCommandsNoLevelEffect()
void IG.Lib.CommandStackFrameBase.AddBlockExitCommandsNoLevelEffect (params string[] commands) inline
Adds the specified strings to the list of commands that can exit the current kind of the code block, but don't affect the quiet entry/exit level.
Warnig: Kind of the code block is not defined by the CodeBlockType in this context, because each type listed in the enumeration can refer to several customly defined subtypes of code blocks.
This list is used as list of commands to be monitored when in the non-executable mode (where commands are not actually executed) in order to know when the command is hit that will end the block, and therefore exit the block that is in non-executable more.
Example is If/Else/Endif blocks. Both Else and Endif can exit the If block, but in quiet mode, only Endif should decrease the quiet entry/exit level (becauee only If increases it, and If always have the cottesponding EndIf).
Parameters
commands Commands that are added to the list of commands that can enter the current kind of block.
Definition at line 1023 of file CommandlineApplicationInterpreterBase.cs.
References IG.Lib.CommandStackFrameBase.BlockExitCommandsNoLevelEffect.
GetBlockEnterCommands()
string [] IG.Lib.CommandStackFrameBase.GetBlockEnterCommands () inline
Returns the array of commands that can enter the current kind of code block.
Definition at line 1031 of file CommandlineApplicationInterpreterBase.cs.
References IG.Lib.CommandStackFrameBase.BlockEnterCommands.
GetBlockExitCommands()
string [] IG.Lib.CommandStackFrameBase.GetBlockExitCommands () inline
Returns the array of commands that can exit the current kind of code block.
Definition at line 1035 of file CommandlineApplicationInterpreterBase.cs.
References IG.Lib.CommandStackFrameBase.BlockExitCommands.
GetBlockExitCommandsNoLevelEffect()
string [] IG.Lib.CommandStackFrameBase.GetBlockExitCommandsNoLevelEffect () inline
Returns the array of commands that can exit the current kind of code block but have no level effect.
Definition at line 1039 of file CommandlineApplicationInterpreterBase.cs.
References IG.Lib.CommandStackFrameBase.BlockExitCommandsNoLevelEffect.
IsEventualListedCommand()
bool IG.Lib.CommandStackFrameBase.IsEventualListedCommand (string commandLine, List< string > commands, bool isOnlyCommandName = false) inline protected
Returns true if the specified commandline can eventually represent one of the commands contained in the specified list of commands.
The conclusion returned is not definitive because it does not take into account whether the interpreter is case sensitive or not. It does check, however, that the command name is the first non-whitespace substring appearing in the command, and that it is separate by whitespace characters from eventual subsequeent parts of the string.
Parameters
commandLine Command lne that is check for whetherr it can represent one of the commands listed.
commands A list of command names that are checked.
isOnlyCommandName If true then commandLine represents only the command name (stripped off eventual arguments and whitespace).
Definition at line 1051 of file CommandlineApplicationInterpreterBase.cs.
References IG.Lib.UtilStr.GetArgumentsArray().
Referenced by IG.Lib.CommandStackFrameBase.IsEventualBlockEnterCommand(), IG.Lib.CommandStackFrameBase.IsEventualBlockExitCommand(), and IG.Lib.CommandStackFrameBase.IsEventualBlockExitCommandNoLevelEffect().
IsEventualBlockEnterCommand()
bool IG.Lib.CommandStackFrameBase.IsEventualBlockEnterCommand (string commandLine, bool isOnlyCommandName = false) inline
Returns true if the specified commandline can eventually represent one of the commands contained in the list of possible block enter commands for the current kind of code block.
The conclusion returned is not definitive because it does not take into account whether the interpreter is case sensitive or not. It does check, however, that the command name is the first non-whitespace substring appearing in the command, and that it is separate by whitespace characters from eventual subsequeent parts of the string.
Parameters
commandLine Command lne that is check for whetherr it can represent one of the commands listed.
isOnlyCommandName If true then commandLine represents only the command name (stripped off eventual arguments and whitespace).
Definition at line 1093 of file CommandlineApplicationInterpreterBase.cs.
References IG.Lib.CommandStackFrameBase.BlockEnterCommands, and IG.Lib.CommandStackFrameBase.IsEventualListedCommand().
Referenced by IG.Lib.CommandStackFrameBase.CheckForBlockEnterOrExitCommand().
IsEventualBlockExitCommand()
bool IG.Lib.CommandStackFrameBase.IsEventualBlockExitCommand (string commandLine, bool isOnlyCommandName = false) inline
Returns true if the specified commandline can eventually represent one of the commands contained in the list of possible block exit commands for the current kind of code block.
The conclusion returned is not definitive because it does not take into account whether the interpreter is case sensitive or not. It does check, however, that the command name is the first non-whitespace substring appearing in the command, and that it is separate by whitespace characters from eventual subsequeent parts of the string.
Parameters
commandLine Command lne that is check for whetherr it can represent one of the commands listed.
isOnlyCommandName If true then commandLine represents only the command name (stripped off eventual arguments and whitespace).
Definition at line 1106 of file CommandlineApplicationInterpreterBase.cs.
References IG.Lib.CommandStackFrameBase.BlockExitCommands, and IG.Lib.CommandStackFrameBase.IsEventualListedCommand().
Referenced by IG.Lib.CommandStackFrameBase.CheckForBlockEnterOrExitCommand(), and IG.Lib.CommandStackFrameBase.IsBlockExitQuietCommand().
IsEventualBlockExitCommandNoLevelEffect()
bool IG.Lib.CommandStackFrameBase.IsEventualBlockExitCommandNoLevelEffect (string commandLine, bool isOnlyCommandName = false) inline
Returns true if the specified commandline can eventually represent one of the commands contained in the list of possible block exit commands that do not affect quiet entry/exit level, for the current kind of code block.
The conclusion returned is not definitive because it does not take into account whether the interpreter is case sensitive or not. It does check, however, that the command name is the first non-whitespace substring appearing in the command, and that it is separate by whitespace characters from eventual subsequeent parts of the string.
Parameters
commandLine Command lne that is check for whetherr it can represent one of the commands listed.
isOnlyCommandName If true then commandLine represents only the command name (stripped off eventual arguments and whitespace).
Definition at line 1119 of file CommandlineApplicationInterpreterBase.cs.
References IG.Lib.CommandStackFrameBase.BlockExitCommandsNoLevelEffect, and IG.Lib.CommandStackFrameBase.IsEventualListedCommand().
Referenced by IG.Lib.CommandStackFrameBase.CheckForBlockEnterOrExitCommand(), and IG.Lib.CommandStackFrameBase.IsBlockExitQuietCommand().
CheckForBlockEnterOrExitCommand()
bool IG.Lib.CommandStackFrameBase.CheckForBlockEnterOrExitCommand (string commandLine, bool justCheck = false, bool isOnlyCommandName = false) inline
Inspects the specified commandline and checks whether it can represent a block enter or a block exit command for the currennt code block.
Parameters
commandLine Commandline to be checked.
justCheck If true then the function only performs the check, but does not increment or decrement the level of encountered current block entries/exits. Default is false.
isOnlyCommandName If true then commandLine
is treated as command name, i.e. it should not contain additional arguments and / or whitespaces.
Returns
True if the specfied commandline can eventually represent the current non-executing code block entry or exit command.
Definition at line 1142 of file CommandlineApplicationInterpreterBase.cs.
References IG.Lib.CommandStackFrameBase.DoExecuteCommands, IG.Lib.CommandStackFrameBase.IsEventualBlockEnterCommand(), IG.Lib.CommandStackFrameBase.IsEventualBlockExitCommand(), IG.Lib.CommandStackFrameBase.IsEventualBlockExitCommandNoLevelEffect(), and IG.Lib.CommandStackFrameBase.QuietBlockEntryLevel.
IsBlockExitQuietCommand()
bool IG.Lib.CommandStackFrameBase.IsBlockExitQuietCommand (string commandLine, bool isOnlyCommandName = false) inline
Returns true if the specified command should be executed as block exit command, in spite of the fact that commannd execution is currently switched off on the current code block.
This makes possible to hit the block exit command for code blocks that have been entered, but command execution was then switched off (e.g. in order to defer command evaluation after all commands are known).
This method only perfomrs checks and does not increase or decrease the quied block entry/exit level.
If command execution is switched on then the method returnes false (in order to save time for actual checks).
Parameters
commandLine Commadline that is checked.
isOnlyCommandName If true then commandLine is treated as just the command name, i.e. it must not contain eventual whitespaces or parameters.
Definition at line 1184 of file CommandlineApplicationInterpreterBase.cs.
References IG.Lib.CommandStackFrameBase.DoExecuteCommands, IG.Lib.CommandStackFrameBase.IsEventualBlockExitCommand(), IG.Lib.CommandStackFrameBase.IsEventualBlockExitCommandNoLevelEffect(), and IG.Lib.CommandStackFrameBase.QuietBlockEntryLevel.
IsVariableDefined()
bool IG.Lib.CommandStackFrameBase.IsVariableDefined (string varName) inline
Returns true if the specified variable is defined, false if it is not.
Parameters
varName Name of the variable that is queried.
Definition at line 1363 of file CommandlineApplicationInterpreterBase.cs.
References IG.Lib.CommandStackFrameBase._variables.
Referenced by IG.Lib.CommandStackFrameBase.SetVariableValue(), and IG.Lib.CommandStackFrameBase.SetVariableValueLocked().
IsVariableDefinedLocked()
bool IG.Lib.CommandStackFrameBase.IsVariableDefinedLocked (string varName) inline
Returns true if the specified variable is defined, false if it is not.
Thread safe variant, lock is aquired on Lock.
Parameters
varName Name of the variable that is queried.
Definition at line 1371 of file CommandlineApplicationInterpreterBase.cs.
References IG.Lib.CommandStackFrameBase._variables, and IG.Lib.CommandStackFrameBase.Lock.
GetVariableDef()
InterpreterVariable IG.Lib.CommandStackFrameBase.GetVariableDef (string varName) inline
Returns variable object (definition) for the variable with specified name.
null is returned if the variable does not exist.
Parameters
varName Name of the variable.
Definition at line 1382 of file CommandlineApplicationInterpreterBase.cs.
GetVariableValue()
string IG.Lib.CommandStackFrameBase.GetVariableValue (string varName) inline
Returns value of the specified variable.
Parameters
varName Name of the variable.
Definition at line 1389 of file CommandlineApplicationInterpreterBase.cs.
GetVariableValueLocked()
string IG.Lib.CommandStackFrameBase.GetVariableValueLocked (string varName) inline
Gets the variable within lock on the Lock property and returns it.
Thread safe variant, lock is aquired on Lock.
Parameters
varName Name of the variable whose value is to be reurned.
Definition at line 1397 of file CommandlineApplicationInterpreterBase.cs.
References IG.Lib.CommandStackFrameBase.Lock.
SetVariableValue()
void IG.Lib.CommandStackFrameBase.SetVariableValue (string varName, string varValue, VariableFlags flags = VariableFlags.Default) inline
Sets value of the specified variable.
Parameters
varName Name of the variable to be set.
varValue Value to be assigned to the specified variable.
flags Variable flags (optional).
Definition at line 1410 of file CommandlineApplicationInterpreterBase.cs.
References IG.Lib.InterpreterVariable.Flags, IG.Lib.CommandStackFrameBase.IsVariableDefined(), IG.Lib.CommandStackFrameBase.StackLevel, and IG.Lib.InterpreterVariable.StringValue.
SetVariableValueLocked()
void IG.Lib.CommandStackFrameBase.SetVariableValueLocked (string varName, string varValue, VariableFlags flags = VariableFlags.Default) inline
Sets the variable within lock on the property.
Thread safe variant, lock is aquired on Lock.
Parameters
varName Name of the variable whose value is to be set.
varValue Value to be assigned to the variable.
flags Variable flags (optional).
Definition at line 1429 of file CommandlineApplicationInterpreterBase.cs.
References IG.Lib.InterpreterVariable.Flags, IG.Lib.CommandStackFrameBase.IsVariableDefined(), IG.Lib.CommandStackFrameBase.Lock, IG.Lib.CommandStackFrameBase.StackLevel, and IG.Lib.InterpreterVariable.StringValue.
RemoveVariable()
void IG.Lib.CommandStackFrameBase.RemoveVariable (string varName) inline
Removes the specified variable.
Parameters
varName Name of the variable to be removed.
Definition at line 1449 of file CommandlineApplicationInterpreterBase.cs.
References IG.Lib.CommandStackFrameBase._variables.
RemoveVariableLocked()
void IG.Lib.CommandStackFrameBase.RemoveVariableLocked (string varName) inline
Removes the specified variable within lock on the property.
Thread safe variant, lock is aquired on Lock.
Parameters
varName Name of the variable whose value is to be set.
Definition at line 1457 of file CommandlineApplicationInterpreterBase.cs.
References IG.Lib.CommandStackFrameBase._variables, and IG.Lib.CommandStackFrameBase.Lock.
ToStringVariableNames()
string IG.Lib.CommandStackFrameBase.ToStringVariableNames () inline
Definition at line 1470 of file CommandlineApplicationInterpreterBase.cs.
References IG.Lib.CommandStackFrameBase.VariableNames.
Referenced by IG.Lib.CommandStackFrameBase.ToString().
ToStringVariableValues()
string IG.Lib.CommandStackFrameBase.ToStringVariableValues () inline
Definition at line 1475 of file CommandlineApplicationInterpreterBase.cs.
References IG.Lib.CommandStackFrameBase.VariableValueStrings.
Referenced by IG.Lib.CommandStackFrameBase.ToString().
ToString() [1/2]
virtual string IG.Lib.CommandStackFrameBase.ToString (bool includeThreadInfo = true, bool includeLocalVariables = true, bool includeGlobalVariables = true) inline virtual
Returns a string containing information about the current command thread.
Definition at line 1481 of file CommandlineApplicationInterpreterBase.cs.
References IG.Lib.CommandStackFrameBase.BlockCommanddLine, IG.Lib.CommandStackFrameBase.BlockType, IG.Lib.CommandStackFrameBase.CommandLines, IG.Lib.CommandStackFrameBase.ConditionExpression, IG.Lib.CommandStackFrameBase.DoExecuteCommands, IG.Lib.CommandStackFrameBase.DoSaveCommands, IG.Lib.CommandStackFrameBase.GetInterpreterBase(), IG.Lib.CommandThreadBase.GetStackFrameBase(), IG.Lib.CommandStackFrameBase.GetThreadBase(), IG.Lib.ICommandLineApplicationInterpreter.GlobalFrame, IG.Lib.CommandStackFrameBase.LastCommandLine, IG.Lib.CommandStackFrameBase.LoopCount, IG.Lib.CommandStackFrameBase.StackLevel, IG.Lib.CommandStackFrameBase.ToString(), IG.Lib.CommandStackFrameBase.ToStringVariableNames(), and IG.Lib.CommandStackFrameBase.ToStringVariableValues().
ToString() [2/2]
override string IG.Lib.CommandStackFrameBase.ToString () inline
Returns string representation of the current object.
Definition at line 1582 of file CommandlineApplicationInterpreterBase.cs.
Referenced by IG.Lib.CommandStackFrameBase.ToString().
Member Data Documentation
_mainLock
object IG.Lib.CommandStackFrameBase._mainLock = new object() private
Definition at line 921 of file CommandlineApplicationInterpreterBase.cs.
_stackLevel
int IG.Lib.CommandStackFrameBase._stackLevel = 0 private
Definition at line 931 of file CommandlineApplicationInterpreterBase.cs.
_blockEnterCommands
List<string> IG.Lib.CommandStackFrameBase._blockEnterCommands = null private
Definition at line 940 of file CommandlineApplicationInterpreterBase.cs.
_blockExitCommands
List<string> IG.Lib.CommandStackFrameBase._blockExitCommands = null private
Definition at line 942 of file CommandlineApplicationInterpreterBase.cs.
_blockExitCommandsNoLevelffect
List<string> IG.Lib.CommandStackFrameBase._blockExitCommandsNoLevelffect = null private
Definition at line 944 of file CommandlineApplicationInterpreterBase.cs.
_quietBlockLevel
int IG.Lib.CommandStackFrameBase._quietBlockLevel = 0 protected
Definition at line 1125 of file CommandlineApplicationInterpreterBase.cs.
_blockType
CodeBlockType IG.Lib.CommandStackFrameBase._blockType = CodeBlockType.None private
Definition at line 1199 of file CommandlineApplicationInterpreterBase.cs.
_doExecute
bool IG.Lib.CommandStackFrameBase._doExecute = true private
Definition at line 1208 of file CommandlineApplicationInterpreterBase.cs.
_isBranchExecuted
bool IG.Lib.CommandStackFrameBase._isBranchExecuted = false private
Definition at line 1213 of file CommandlineApplicationInterpreterBase.cs.
_numExitLevels
int IG.Lib.CommandStackFrameBase._numExitLevels = 0 private
Definition at line 1218 of file CommandlineApplicationInterpreterBase.cs.
_loopCount
int IG.Lib.CommandStackFrameBase._loopCount = 0 private
Definition at line 1222 of file CommandlineApplicationInterpreterBase.cs.
_suppressInteractive
bool IG.Lib.CommandStackFrameBase._suppressInteractive = false private
Definition at line 1227 of file CommandlineApplicationInterpreterBase.cs.
_conditionExpression
string IG.Lib.CommandStackFrameBase._conditionExpression = null private
Definition at line 1236 of file CommandlineApplicationInterpreterBase.cs.
_blockCommandLine
string IG.Lib.CommandStackFrameBase._blockCommandLine = null private
Definition at line 1246 of file CommandlineApplicationInterpreterBase.cs.
_doSave
bool IG.Lib.CommandStackFrameBase._doSave = false private
Definition at line 1263 of file CommandlineApplicationInterpreterBase.cs.
_commandLines
List<string> IG.Lib.CommandStackFrameBase._commandLines = null private
Definition at line 1268 of file CommandlineApplicationInterpreterBase.cs.
_lastCommandLine
string IG.Lib.CommandStackFrameBase._lastCommandLine = null private
Definition at line 1286 of file CommandlineApplicationInterpreterBase.cs.
_variables
SortedDictionary<string, InterpreterVariable> IG.Lib.CommandStackFrameBase._variables = new SortedDictionary<string, InterpreterVariable>() protected
Local variables.
Definition at line 1291 of file CommandlineApplicationInterpreterBase.cs.
Referenced by IG.Lib.CommandStackFrameBase.IsVariableDefined(), IG.Lib.CommandStackFrameBase.IsVariableDefinedLocked(), IG.Lib.CommandStackFrameBase.RemoveVariable(), and IG.Lib.CommandStackFrameBase.RemoveVariableLocked().
_returnedValue
string IG.Lib.CommandStackFrameBase._returnedValue = null private
Definition at line 1293 of file CommandlineApplicationInterpreterBase.cs.
_auxVarNames
List<string> IG.Lib.CommandStackFrameBase._auxVarNames = null protected
Definition at line 1305 of file CommandlineApplicationInterpreterBase.cs.
Property Documentation
Lock
object IG.Lib.CommandStackFrameBase.Lock get
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
Definition at line 926 of file CommandlineApplicationInterpreterBase.cs.
Referenced by IG.Lib.CommandStackFrameBase.GetVariableValueLocked(), IG.Lib.CommandStackFrameBase.IsVariableDefinedLocked(), IG.Lib.CommandStackFrameBase.RemoveVariableLocked(), and IG.Lib.CommandStackFrameBase.SetVariableValueLocked().
StackLevel
int IG.Lib.CommandStackFrameBase.StackLevel get protected set
Definition at line 934 of file CommandlineApplicationInterpreterBase.cs.
Referenced by IG.Lib.CommandStackFrame< InterpreterType, ThreadType >.CommandStackFrame(), IG.Lib.CommandStackFrame< InterpreterType, ThreadType >.GetParentStackFrame(), IG.Lib.CommandThreadBase.RestorePreviousNumStoredParameters(), IG.Lib.CommandStackFrameBase.SetVariableValue(), IG.Lib.CommandStackFrameBase.SetVariableValueLocked(), and IG.Lib.CommandStackFrameBase.ToString().
BlockEnterCommands
List<string> IG.Lib.CommandStackFrameBase.BlockEnterCommands get protected
A list of commands that can enter the type of the current code block.
Definition at line 948 of file CommandlineApplicationInterpreterBase.cs.
Referenced by IG.Lib.CommandStackFrameBase.AddBlockEnterCommands(), IG.Lib.CommandStackFrameBase.GetBlockEnterCommands(), and IG.Lib.CommandStackFrameBase.IsEventualBlockEnterCommand().
BlockExitCommands
List<string> IG.Lib.CommandStackFrameBase.BlockExitCommands get protected
A list of commands that can exit the type of the current code block.
Definition at line 959 of file CommandlineApplicationInterpreterBase.cs.
Referenced by IG.Lib.CommandStackFrameBase.AddBlockExitCommands(), IG.Lib.CommandStackFrameBase.GetBlockExitCommands(), and IG.Lib.CommandStackFrameBase.IsEventualBlockExitCommand().
BlockExitCommandsNoLevelEffect
List<string> IG.Lib.CommandStackFrameBase.BlockExitCommandsNoLevelEffect get protected
A list of commands that can exit the type of the current code block, but willl nnot have effect on the quet wxit/entry level.
Example is If/Else/Endif blocks. Both Else and Endif can exit the If block, but in quiet mode, only Endif should decrease the quiet entry/exit level (becauee only If increases it, and If always have the cottesponding EndIf).
Definition at line 974 of file CommandlineApplicationInterpreterBase.cs.
Referenced by IG.Lib.CommandStackFrameBase.AddBlockExitCommandsNoLevelEffect(), IG.Lib.CommandStackFrameBase.GetBlockExitCommandsNoLevelEffect(), and IG.Lib.CommandStackFrameBase.IsEventualBlockExitCommandNoLevelEffect().
QuietBlockEntryLevel
int IG.Lib.CommandStackFrameBase.QuietBlockEntryLevel get protected set
Indicates the quiet entry/exit level of the current kind of block when commands are not executed.
The level is obtained by counting the block entry and block exit commands encountered (which were, nonetheless, not executed, because command execution is switched off)
Definition at line 1130 of file CommandlineApplicationInterpreterBase.cs.
Referenced by IG.Lib.CommandStackFrameBase.CheckForBlockEnterOrExitCommand(), and IG.Lib.CommandStackFrameBase.IsBlockExitQuietCommand().
BlockType
CodeBlockType IG.Lib.CommandStackFrameBase.BlockType get protected set
Type of the code block represented by the current stack frame.
Definition at line 1203 of file CommandlineApplicationInterpreterBase.cs.
Referenced by IG.Lib.CommandStackFrame< InterpreterType, ThreadType >.CommandStackFrame(), and IG.Lib.CommandStackFrameBase.ToString().
DoExecuteCommands
bool IG.Lib.CommandStackFrameBase.DoExecuteCommands get set
Whether commands are executed in the current code block.
Definition at line 1211 of file CommandlineApplicationInterpreterBase.cs.
Referenced by IG.Lib.CommandStackFrameBase.CheckForBlockEnterOrExitCommand(), IG.Lib.CommandStackFrameBase.IsBlockExitQuietCommand(), and IG.Lib.CommandStackFrameBase.ToString().
WasBranchAlreadyExecuted
bool IG.Lib.CommandStackFrameBase.WasBranchAlreadyExecuted get set
Whether a branch has already been executed.
Definition at line 1216 of file CommandlineApplicationInterpreterBase.cs.
NumExitLevels
int IG.Lib.CommandStackFrameBase.NumExitLevels get set
Definition at line 1220 of file CommandlineApplicationInterpreterBase.cs.
LoopCount
int IG.Lib.CommandStackFrameBase.LoopCount get set
Whether commands are executed in the current code block.
Definition at line 1225 of file CommandlineApplicationInterpreterBase.cs.
Referenced by IG.Lib.CommandStackFrameBase.ToString().
SuppressInteractive
bool IG.Lib.CommandStackFrameBase.SuppressInteractive get set
Indicates that the interactive mode is temporarily represset.
Definition at line 1231 of file CommandlineApplicationInterpreterBase.cs.
ConditionExpression
string IG.Lib.CommandStackFrameBase.ConditionExpression get set
For loopig and branching blocks, this property contains the condition expression of the block, which was a part of the block command (such as While, If, or ElseIf).
Definition at line 1241 of file CommandlineApplicationInterpreterBase.cs.
Referenced by IG.Lib.CommandStackFrameBase.ToString().
BlockCommanddLine
string IG.Lib.CommandStackFrameBase.BlockCommanddLine get set
Commandline that started the current block. It may have been saved when the current block of code was entered, in order to be used within the block (e.g. for inspection and debugging) or when the block exits. Typical use is in blocks with deferred evaluation, such as in While block, where commandlines within the block are stored first, and then repeatedly evaluated until the condition from the While block entering command is fulfilled.
Definition at line 1253 of file CommandlineApplicationInterpreterBase.cs.
Referenced by IG.Lib.CommandStackFrameBase.ToString().
DoSaveCommands
bool IG.Lib.CommandStackFrameBase.DoSaveCommands get set
Whether commands are saved to the command store in the current code block.
Definition at line 1266 of file CommandlineApplicationInterpreterBase.cs.
Referenced by IG.Lib.CommandStackFrameBase.ToString().
CommandLines
List<string> IG.Lib.CommandStackFrameBase.CommandLines get
Definition at line 1271 of file CommandlineApplicationInterpreterBase.cs.
Referenced by IG.Lib.CommandStackFrameBase.ToString().
LastCommandLine
string IG.Lib.CommandStackFrameBase.LastCommandLine get set
Definition at line 1288 of file CommandlineApplicationInterpreterBase.cs.
Referenced by IG.Lib.CommandStackFrameBase.ToString().
ReturnedValue
string IG.Lib.CommandStackFrameBase.ReturnedValue get set
Value returned from the last executed command.
Definition at line 1297 of file CommandlineApplicationInterpreterBase.cs.
VariableNames
string [] IG.Lib.CommandStackFrameBase.VariableNames get
Gets names of all variables that are defined on the current stack frame.
Operation is locked.
Definition at line 1310 of file CommandlineApplicationInterpreterBase.cs.
Referenced by IG.Lib.CommandStackFrameBase.ToStringVariableNames().
VariableValueStrings
string [] IG.Lib.CommandStackFrameBase.VariableValueStrings get
Gets names of all variables that are defined on the current stack frame.
Operation is locked.
Definition at line 1331 of file CommandlineApplicationInterpreterBase.cs.
Referenced by IG.Lib.CommandStackFrameBase.ToStringVariableValues().
this[string variableName]
InterpreterVariable IG.Lib.CommandStackFrameBase.this[string variableName] get set
Gets or sets value of the variable with the specified name.
Parameters
variableName Name of the variable to be set or retrieved.
Definition at line 1356 of file CommandlineApplicationInterpreterBase.cs.
The documentation for this class was generated from the following file:
iglib/igbase/interpreters/CommandlineApplicationInterpreterBase.cs