Doc: IGLib with source files: IGLib.Gr3D.ExampesGraphics3D Class Reference
IGLib.Gr3D.ExampesGraphics3D Class Reference
Static Public Member Functions
static void ExportHelixTubularMeshToGLTF ()
static ColorRGBA GetColorFromT (double t, double tMin, double tMax)
Returns RGBA color for a normalized parameter t. Gradient: blue → green → red.
Detailed Description
Definition at line 11 of file ExampesGraphics3D.cs.
Member Function Documentation
ExportHelixTubularMeshToGLTF()
static void IGLib.Gr3D.ExampesGraphics3D.ExportHelixTubularMeshToGLTF () inline static
Definition at line 14 of file ExampesGraphics3D.cs.
References IGLib.Gr3D.TubularMeshGenerator.GenerateMesh(), IGLib.Gr3D.ExampesGraphics3D.GetColorFromT(), IGLib.Gr3D.TubularMeshGenerator.Global, and IGLib.Gr3D.StructuredSurfaceMesh3D.VertexColors.
GetColorFromT()
static ColorRGBA IGLib.Gr3D.ExampesGraphics3D.GetColorFromT (double t, double tMin, double tMax) inline static
Returns RGBA color for a normalized parameter t. Gradient: blue → green → red.
Definition at line 74 of file ExampesGraphics3D.cs.
Referenced by IGLib.Gr3D.ExampesGraphics3D.ExportHelixTubularMeshToGLTF().
The documentation for this class was generated from the following file:
IGLibGraphics3D/src/IGLib.Graphics3D/Graphics3D/ExampesGraphics3D.cs