Doc: IGLib with source files: IG.Num.vec2 Struct Reference
IG.Num.vec2 Struct Reference
Struct representing a 3D vector.
Public Member Functions
vec2 (double x, double y)
Constructor, initializes vecto components with provided values.
vec3 Cross (vec2 v2)
Cross product of the current vector with another vector (in this order); Calls Cross(vec2, vec2) to do the job.
vec2 Normalize (double epsilon=1e-15)
Returns the normalized current vector.
vec2 (vec2 v)
Copy constructor. Initializes components of a 2D vector with components of the specified vector.
vec2 (double x, double y)
Initializes components of a 2D vector with the specified values.
vec2 (double comp)
Initializes all component of a 2D vector with the specified value.
void Zero ()
Sets components of the vector to 0.0.
void Set (double comp)
Sets components of the vector to the specified value.
override int GetHashCode ()
Returns the hash code (hash function) of the current vector.
override bool Equals (Object obj)
Returns a value indicating whether the specified object is equal to the current vector.
vec2 Normalized ()
Returns normalized this 2D vector.
vec2 Normalized1 ()
Returns normalized this 2D vector in 1 norm.
vec2 Normalized2 ()
Returns normalized this 2D vector in 2 norm.
vec2 NormalizedInfinity ()
Returns normalized this 2D vector in infinity norm.
double ScalarProduct (vec2 v)
Returns scalar product of the current and the specified vector.
vec3 VectorProduct (vec2 v)
Returns vector product of the current and the specified vector.
vec3 CrossProduct (vec2 v)
Returns vector product of the current and the specified vector.
vec3 Cross (vec2 v)
Returns vector product of the current and the specified vector.
mat2 DyadicProduct (vec2 v)
Returns dyadic product of the current and the specified vector.
vec2 Multiply (double k)
Returns the current vector multiplied by the specified scalar.
vec2 Add (vec2 a)
Returns sum of the current vector and the specified vector.
vec2 Subtract (vec2 a)
Returns difference between the current vector and the specified vector.
override string ToString ()
Returns string representation of the 2D vector.
void Read ()
Reads 2D vector components from a console.
void Read (string name)
Reads 2D vector components from a console.
Static Public Member Functions
static vec2 operator+ (vec2 a, vec2 b)
Vector addition.
static vec2 operator- (vec2 a, vec2 b)
Vector Subtraction.
static vec2 operator* (double scalar, vec2 v)
Multiplication of vector by scalar.
static vec2 operator* (vec2 v, double scalar)
Multiplication of vector by scalar where scalar is the first parameter.
static double Dot (vec2 a, vec2 b)
Dot Product (scalar product).
static vec3 Cross (vec2 a, vec2 b)
Cross Product of 2D vectors (vec2), results in a 3D vector in the direction of the 3rd coordinate axis (Z).
static vec2 Copy (vec2 v)
Returns a copy of the specified 2D vector.
static void Negate (vec2 v, ref vec2 res)
Negates the specified vector and stores its copy in the resulting vector.
static vec2 operator+ (vec2 v)
Unary plus, returns the operand.
static vec2 operator- (vec2 v)
Unary negation, returns the negative operand.
static vec2 operator+ (vec2 a, vec2 b)
Vector addition.
static vec2 operator- (vec2 a, vec2 b)
Vector subtraction.
static double operator* (vec2 a, vec2 b)
Scalar product of two 2D vectors.
static vec2 operator* (vec2 a, double b)
Product of a 2D vector by a scalar.
static vec2 operator* (double a, vec2 b)
Product of a 2D vector by a scalar.
static vec2 operator/ (vec2 a, double b)
Vector subtraction.
static bool operator== (vec2 a, vec2 b)
Vector comparison.
static bool operator!= (vec2 a, vec2 b)
Vector comparison, returns true if vectors are different.
Public Attributes
double x
The first component of the vector.
double y
The second component of the vector.
Static Public Attributes
const double DefaulltEpsilon = 1e-15
Properties
double this[int i] [get, set]
Index operator.
double Norm [get]
Gets a 2 norm of the current 2D vector.
double Norm2 [get]
Gets a 2 norm of the current 2D vector.
double Norm1 [get]
Gets an 1 norm of the current 2D vector - sum of absolute values of components.
double NormInf [get]
Gets an infinity norm of the current 2D vector - maximal absolute component value.
Detailed Description
Struct representing a 3D vector.
2D vector, struct implementation.
Name of this struct is not in line with conventions. This is intentional in order to prevent mistaking struct implementation for class interpretation.
$A Igor Jul08; Oct10;
Definition at line 9 of file vec2.cs.
Constructor & Destructor Documentation
vec2() [1/4]
IG.Num.vec2.vec2 (double x, double y) inline
Constructor, initializes vecto components with provided values.
Parameters
x First component of the vector.
y Second component of the vector.
Definition at line 22 of file vec2.cs.
References IG.Num.vec2.x, and IG.Num.vec2.y.
Referenced by IG.Num.vec2.Add(), IG.Num.vec2.Copy(), IG.Num.vec2.Multiply(), IG.Num.vec2.Normalize(), IG.Num.vec2.operator-(), IG.Num.vec2.operator/(), and IG.Num.vec2.Subtract().
vec2() [2/4]
IG.Num.vec2.vec2 (vec2 v) inline
Copy constructor. Initializes components of a 2D vector with components of the specified vector.
Parameters
v Vectr whose components are copied to the initialized vector.
Definition at line 28 of file Matrix2D.cs.
References IG.Num.vec2.x, and IG.Num.vec2.y.
vec2() [3/4]
IG.Num.vec2.vec2 (double x, double y) inline
Initializes components of a 2D vector with the specified values.
Parameters
x Value assigned to the first component.
y Value assigned to the second component.
Definition at line 36 of file Matrix2D.cs.
References IG.Num.vec2.x, and IG.Num.vec2.y.
vec2() [4/4]
IG.Num.vec2.vec2 (double comp) inline
Initializes all component of a 2D vector with the specified value.
Parameters
comp Value assigned to all vector components.
Definition at line 43 of file Matrix2D.cs.
References IG.Num.vec2.x, and IG.Num.vec2.y.
Member Function Documentation
operator+() [1/3]
static vec2 IG.Num.vec2.operator+ (vec2 a, vec2 b) static
Vector addition.
Returns
operator-() [1/3]
static vec2 IG.Num.vec2.operator- (vec2 a, vec2 b) static
Vector Subtraction.
operator*() [1/5]
static vec2 IG.Num.vec2.operator* (double scalar, vec2 v) static
Multiplication of vector by scalar.
operator*() [2/5]
static vec2 IG.Num.vec2.operator* (vec2 v, double scalar) static
Multiplication of vector by scalar where scalar is the first parameter.
Dot()
static double IG.Num.vec2.Dot (vec2 a, vec2 b) static
Dot Product (scalar product).
Cross() [1/3]
static vec3 IG.Num.vec2.Cross (vec2 a, vec2 b) static
Cross Product of 2D vectors (vec2), results in a 3D vector in the direction of the 3rd coordinate axis (Z).
Referenced by IG.Num.vec2.Cross().
Cross() [2/3]
vec3 IG.Num.vec2.Cross (vec2 v2) inline
Cross product of the current vector with another vector (in this order); Calls Cross(vec2, vec2) to do the job.
Definition at line 53 of file vec2.cs.
References IG.Num.vec2.Cross().
Normalize()
vec2 IG.Num.vec2.Normalize (double epsilon = 1e-15) inline
Returns the normalized current vector.
Parameters
epsilon If calculated length of the vector is below this value, vector [0, 0] is returned in order to avoid division with very small numbers. Default:
Returns
Definition at line 64 of file vec2.cs.
References IG.Num.vec2.DefaulltEpsilon, IG.Num.vec2.vec2(), IG.Num.vec2.x, and IG.Num.vec2.y.
Zero()
void IG.Num.vec2.Zero () inline
Sets components of the vector to 0.0.
Definition at line 49 of file Matrix2D.cs.
References IG.Num.vec2.x, and IG.Num.vec2.y.
Set()
void IG.Num.vec2.Set (double comp) inline
Sets components of the vector to the specified value.
Definition at line 53 of file Matrix2D.cs.
References IG.Num.vec2.x, and IG.Num.vec2.y.
GetHashCode()
override int IG.Num.vec2.GetHashCode () inline
Returns the hash code (hash function) of the current vector.
This method should be consistent with the VectorBase.GetHashCode() method, which is standard for implementations of the IVector interface.
Two vectors that have equal all elements will produce the same hash codes.
Probability that two different vectors will produce the same hash code is small but it exists.
Overrides the object.GetHashCode method.
Definition at line 99 of file Matrix2D.cs.
References IG.Num.vec2.x, and IG.Num.vec2.y.
Equals()
override bool IG.Num.vec2.Equals (Object obj) inline
Returns a value indicating whether the specified object is equal to the current vector.
True is returned if the object of type vec2) and has equal elements as the current vector.
Overrides the object.Equals(object) method.
Definition at line 110 of file Matrix2D.cs.
Normalized()
vec2 IG.Num.vec2.Normalized () inline
Returns normalized this 2D vector.
Definition at line 148 of file Matrix2D.cs.
References IG.Num.vec2.Multiply(), and IG.Num.vec2.Norm.
Referenced by IG.Num.Vector2d.Normalized().
Normalized1()
vec2 IG.Num.vec2.Normalized1 () inline
Returns normalized this 2D vector in 1 norm.
Definition at line 152 of file Matrix2D.cs.
References IG.Num.vec2.Multiply(), and IG.Num.vec2.Norm1.
Referenced by IG.Num.Vector2d.Normalized1().
Normalized2()
vec2 IG.Num.vec2.Normalized2 () inline
Returns normalized this 2D vector in 2 norm.
Definition at line 156 of file Matrix2D.cs.
References IG.Num.vec2.Multiply(), and IG.Num.vec2.Norm2.
Referenced by IG.Num.Vector2d.Normalized2().
NormalizedInfinity()
vec2 IG.Num.vec2.NormalizedInfinity () inline
Returns normalized this 2D vector in infinity norm.
Definition at line 160 of file Matrix2D.cs.
References IG.Num.vec2.Multiply(), and IG.Num.vec2.NormInf.
Referenced by IG.Num.Vector2d.NormalizedInfinity().
ScalarProduct()
double IG.Num.vec2.ScalarProduct (vec2 v) inline
Returns scalar product of the current and the specified vector.
Definition at line 165 of file Matrix2D.cs.
References IG.Num.vec2.x, and IG.Num.vec2.y.
Referenced by IG.Num.Vector2d.ScalarProduct(), and IG.Num.Vector2d.VectorProduct().
VectorProduct()
vec3 IG.Num.vec2.VectorProduct (vec2 v) inline
Returns vector product of the current and the specified vector.
Definition at line 171 of file Matrix2D.cs.
References IG.Num.vec2.x, and IG.Num.vec2.y.
Referenced by IG.Num.vec2.Cross(), and IG.Num.vec2.CrossProduct().
CrossProduct()
vec3 IG.Num.vec2.CrossProduct (vec2 v) inline
Returns vector product of the current and the specified vector.
Definition at line 181 of file Matrix2D.cs.
References IG.Num.vec2.VectorProduct().
Cross() [3/3]
vec3 IG.Num.vec2.Cross (vec2 v) inline
Returns vector product of the current and the specified vector.
Definition at line 185 of file Matrix2D.cs.
References IG.Num.vec2.VectorProduct().
DyadicProduct()
mat2 IG.Num.vec2.DyadicProduct (vec2 v) inline
Returns dyadic product of the current and the specified vector.
Definition at line 189 of file Matrix2D.cs.
References IG.Num.vec2.x, and IG.Num.vec2.y.
Referenced by IG.Num.Vector2d.DyadicProduct().
Multiply()
vec2 IG.Num.vec2.Multiply (double k) inline
Returns the current vector multiplied by the specified scalar.
Parameters
k Factor by which the current vector is multiplied.
Definition at line 200 of file Matrix2D.cs.
References IG.Num.vec2.vec2(), IG.Num.vec2.x, and IG.Num.vec2.y.
Referenced by IG.Num.Vector2d.Multiply(), IG.Num.vec2.Normalized(), IG.Num.vec2.Normalized1(), IG.Num.vec2.Normalized2(), and IG.Num.vec2.NormalizedInfinity().
Add()
vec2 IG.Num.vec2.Add (vec2 a) inline
Returns sum of the current vector and the specified vector.
Definition at line 206 of file Matrix2D.cs.
References IG.Num.vec2.vec2(), IG.Num.vec2.x, and IG.Num.vec2.y.
Referenced by IG.Num.Vector2d.Add().
Subtract()
vec2 IG.Num.vec2.Subtract (vec2 a) inline
Returns difference between the current vector and the specified vector.
Definition at line 212 of file Matrix2D.cs.
References IG.Num.vec2.vec2(), IG.Num.vec2.x, and IG.Num.vec2.y.
Referenced by IG.Num.Vector2d.Subtract().
Copy()
static vec2 IG.Num.vec2.Copy (vec2 v) inline static
Returns a copy of the specified 2D vector.
Parameters
v Vector whose copy is returned.
Definition at line 225 of file Matrix2D.cs.
References IG.Num.vec2.vec2().
Referenced by IG.Num.vec2.operator+().
Negate()
static void IG.Num.vec2.Negate (vec2 v, ref vec2 res) inline static
Negates the specified vector and stores its copy in the resulting vector.
Parameters
v Vectr to be negated.
res Vector where the result is stored.
Definition at line 233 of file Matrix2D.cs.
operator+() [2/3]
static vec2 IG.Num.vec2.operator+ (vec2 v) inline static
Unary plus, returns the operand.
Definition at line 244 of file Matrix2D.cs.
References IG.Num.vec2.Copy().
operator-() [2/3]
static vec2 IG.Num.vec2.operator- (vec2 v) inline static
Unary negation, returns the negative operand.
Definition at line 250 of file Matrix2D.cs.
References IG.Num.vec2.vec2().
operator+() [3/3]
static vec2 IG.Num.vec2.operator+ (vec2 a, vec2 b) inline static
Vector addition.
Definition at line 256 of file Matrix2D.cs.
operator-() [3/3]
static vec2 IG.Num.vec2.operator- (vec2 a, vec2 b) inline static
Vector subtraction.
Definition at line 263 of file Matrix2D.cs.
operator*() [3/5]
static double IG.Num.vec2.operator* (vec2 a, vec2 b) inline static
Scalar product of two 2D vectors.
Definition at line 270 of file Matrix2D.cs.
operator*() [4/5]
static vec2 IG.Num.vec2.operator* (vec2 a, double b) inline static
Product of a 2D vector by a scalar.
Definition at line 276 of file Matrix2D.cs.
operator*() [5/5]
static vec2 IG.Num.vec2.operator* (double a, vec2 b) inline static
Product of a 2D vector by a scalar.
Definition at line 282 of file Matrix2D.cs.
operator/()
static vec2 IG.Num.vec2.operator/ (vec2 a, double b) inline static
Vector subtraction.
Definition at line 288 of file Matrix2D.cs.
References IG.Num.vec2.vec2().
operator==()
static bool IG.Num.vec2.operator== (vec2 a, vec2 b) inline static
Vector comparison.
Definition at line 299 of file Matrix2D.cs.
operator!=()
static bool IG.Num.vec2.operator!= (vec2 a, vec2 b) inline static
Vector comparison, returns true if vectors are different.
Definition at line 305 of file Matrix2D.cs.
ToString()
override string IG.Num.vec2.ToString () inline
Returns string representation of the 2D vector.
Definition at line 317 of file Matrix2D.cs.
References IG.Num.vec2.x, and IG.Num.vec2.y.
Referenced by IG.Num.Vector2d.ToString().
Read() [1/2]
void IG.Num.vec2.Read () inline
Reads 2D vector components from a console.
Definition at line 324 of file Matrix2D.cs.
Referenced by IG.Num.Vector2d.Read().
Read() [2/2]
void IG.Num.vec2.Read (string name) inline
Reads 2D vector components from a console.
Parameters
name Name of the vector to be read; it is written as orientation to the user and can be null.
Definition at line 333 of file Matrix2D.cs.
References IG.Lib.UtilConsole.Read(), IG.Num.vec2.x, and IG.Num.vec2.y.
Member Data Documentation
x
double IG.Num.vec2.x
The first component of the vector.
Definition at line 13 of file vec2.cs.
Referenced by IG.Num.vec2.Add(), IG.Num.vec2.DyadicProduct(), IG.Num.vec2.GetHashCode(), IG.Num.Func2dBase.Gradient(), IG.Num.Func2dVectorFormBase.Gradient(), IG.Num.Func2dBasePlain_ToConsider.Gradient(), IG.Num.Func3d2dBase.Gradient1(), IG.Num.Func3d2dBase.Gradient2(), IG.Num.Func3d2dBase.Gradient3(), IG.Num.Func2dBase.Hessian(), IG.Num.Func2dBasePlain_ToConsider.Hessian(), IG.Num.Func3d2dBase.Hessian1(), IG.Num.Func3d2dBase.Hessian2(), IG.Num.Func3d2dBase.Hessian3(), IG.Num.Field< TCoord >.MapCoordinates1dPlain(), IG.Num.vec2.Multiply(), IG.Num.vec2.Normalize(), IG.Num.vec2.Read(), IG.Num.vec2.ScalarProduct(), IG.Num.vec2.Set(), IG.Num.vec2.Subtract(), IG.Num.vec2.ToString(), IG.Num.BoundingBox2d.Update(), IG.Num.Field< TCoord >.UpdateBounds(), IG.Num.Func2dBase.Value(), IG.Num.Func2dBasePlain_ToConsider.Value(), IG.Num.Func3d2dBase.Value1(), IG.Num.Func3d2dBase.Value2(), IG.Num.Func3d2dBase.Value3(), IG.Num.vec2.vec2(), IG.Num.Vector2d.Vector2d(), IG.Num.vec2.VectorProduct(), and IG.Num.vec2.Zero().
y
double IG.Num.vec2.y
The second component of the vector.
Definition at line 16 of file vec2.cs.
Referenced by IG.Num.vec2.Add(), IG.Num.vec2.DyadicProduct(), IG.Num.vec2.GetHashCode(), IG.Num.Func2dBase.Gradient(), IG.Num.Func2dVectorFormBase.Gradient(), IG.Num.Func2dBasePlain_ToConsider.Gradient(), IG.Num.Func3d2dBase.Gradient1(), IG.Num.Func3d2dBase.Gradient2(), IG.Num.Func3d2dBase.Gradient3(), IG.Num.Func2dBase.Hessian(), IG.Num.Func2dBasePlain_ToConsider.Hessian(), IG.Num.Func3d2dBase.Hessian1(), IG.Num.Func3d2dBase.Hessian2(), IG.Num.Func3d2dBase.Hessian3(), IG.Num.vec2.Multiply(), IG.Num.vec2.Normalize(), IG.Num.vec2.Read(), IG.Num.vec2.ScalarProduct(), IG.Num.vec2.Set(), IG.Num.vec2.Subtract(), IG.Num.vec2.ToString(), IG.Num.BoundingBox2d.Update(), IG.Num.Field< TCoord >.UpdateBounds(), IG.Num.Func2dBase.Value(), IG.Num.Func2dBasePlain_ToConsider.Value(), IG.Num.Func3d2dBase.Value1(), IG.Num.Func3d2dBase.Value2(), IG.Num.Func3d2dBase.Value3(), IG.Num.vec2.vec2(), IG.Num.Vector2d.Vector2d(), IG.Num.vec2.VectorProduct(), and IG.Num.vec2.Zero().
DefaulltEpsilon
const double IG.Num.vec2.DefaulltEpsilon = 1e-15 static
Definition at line 58 of file vec2.cs.
Referenced by IG.Num.vec2.Normalize().
Property Documentation
this[int i]
double IG.Num.vec2.this[int i] get set
Index operator.
Parameters
i Component index.
Returns
The specified component of a 2D vector.
Definition at line 65 of file Matrix2D.cs.
Norm
double IG.Num.vec2.Norm get
Gets a 2 norm of the current 2D vector.
Definition at line 125 of file Matrix2D.cs.
Referenced by IG.Num.vec2.Normalized().
Norm2
double IG.Num.vec2.Norm2 get
Gets a 2 norm of the current 2D vector.
Definition at line 128 of file Matrix2D.cs.
Referenced by IG.Num.vec2.Normalized2().
Norm1
double IG.Num.vec2.Norm1 get
Gets an 1 norm of the current 2D vector - sum of absolute values of components.
Definition at line 132 of file Matrix2D.cs.
Referenced by IG.Num.vec2.Normalized1().
NormInf
double IG.Num.vec2.NormInf get
Gets an infinity norm of the current 2D vector - maximal absolute component value.
Definition at line 137 of file Matrix2D.cs.
Referenced by IG.Num.vec2.NormalizedInfinity().
The documentation for this struct was generated from the following files:
IGLibGraphics3D/src/IGLib.Graphics3D/other/vec2.cs
iglib/igbase/numeric/geometry/Matrix2D.cs