Doc: IGLib with source files: IG.Num.UnstructuredMesh1d3d Class Reference
IG.Num.UnstructuredMesh1d3d Class Reference
Unstructured mesh in 1D embedded in 3D space.
Public Member Functions
UnstructuredMesh1d3d ()
Constructs a new empty 1D (unconnected) unstructured grid (no elements contained) with no name and no description.
UnstructuredMesh1d3d (int length)
Constructs a new 1D (unconnected) unstructured grid with the specified size, name and description. Array of elements is allocated.
UnstructuredMesh1d3d (int length, string fieldName)
Constructs a new 1D (unconnected) unstructured grid with the specified size, name and description. Array of elements is allocated.
UnstructuredMesh1d3d (int length, string fieldName, string fieldDescription)
Constructs a new 1D (unconnected) unstructured grid with the specified size, name and description. Array of elements is allocated.
UnstructuredMesh1d3d (int dimx, int dimy, string fieldName, string fieldDescription, double minx, double maxx, double miny, double maxy)
Constructs a (unconnected) unstructured grid based on 1D regular grid with grid direction parallel to coordinate axes, with specified name and description. Array of elements is allocated.
UnstructuredMesh1d3d (int dimx, string fieldName, string fieldDescription, double minxRef, double maxxRef, IRealFunction fx, IRealFunction fy, IRealFunction fz)
Constructs an (unconnected) unstructured grid of nodes based on 1D structured grid obtained by transformation of co-ordinates of a regular equidistant grid. Array of elements is allocated.
void GenerateCoordinates (int dimx, double minxRef, double maxxRef)
Generates an (unconnected) unstructured grid of nodes based on a 1D regular grid with grid directions parallel to coordinate axes and equidistant nodes in all directions.
void GenerateCoordinates (int dimx, double minxRef, double maxxRef, IRealFunction fx, IRealFunction fy, IRealFunction fz)
Generates coordinates of an (unconnected) unstructured grid of points based on coordinates of a structured mesh for a parametric volume according to functions specifying the x, y, and z coordinates in terms of three scalar functions of 3 variables.
Public Member Functions inherited from IG.Num.UnstructuredMesh1d< vec3, Field< int >, int, Field< double >, double, Field< vec3 >, vec3, Field< mat3 >, mat3 >
UnstructuredMesh1d ()
Constructs a new empty unstructured mesh (no elements contained) with no name and no description.
UnstructuredMesh1d (int numElements)
Creates a new unstructured mesh with the specified number of elements.
UnstructuredMesh1d (int numElements, string fieldName)
Constructs a new unstructured mesh with the specified number of nodes and name.
UnstructuredMesh1d (int numElements, string fieldName, string fieldDescription)
Constructs a new unstructured mesh with the specified number of nodes, name and description. Table of elements is allocated.
TIndexField GetIndexField (string name)
Returns index field with the specified name.
TIndexField GetIndexField (int index)
Returns the index field with the specified index.
virtual TIndexField CreateIndexField (string fieldName, string fieldDescription)
Creates and returns a new index field of dimensions that match dimensions of the current structured mesh, and with specified name and description.
void AddIndexField (string fieldName, string fieldDescription)
Creates a new index field of dimensions that match dimensions of the current 1D structuredmesh, and specified with name and description, and adds it to the current collection.
void AddIndexField (TIndexField field, string name)
Adds the specified index field to the collection of index fields under the specified name.
void AddIndexField (TIndexField field)
Adds the specified index field to the collection of index fields.
void RemoveIndexField (string fieldName)
Removed the field with the specified name from the current field collection.
TScalarField GetScalarField (string name)
Returns scalar field with the specified name.
TScalarField GetScalarField (int index)
Returns the scalar field with the specified index.
virtual TScalarField CreateScalarField (string fieldName, string fieldDescription)
Creates and returns a new scalar field of dimensions that match dimensions of the current structured mesh, and with specified name and description.
TScalarField AddScalarField (string fieldName, string fieldDescription)
Creates and returns a new scalar field of dimensions that match dimensions of the current 1D structuredmesh, and specified with name and description, and adds it to the current collection.
void AddScalarField (TScalarField field, string name)
Adds the specified scalar field to the collection of scalar fields under the specified name.
void AddScalarField (TScalarField field)
Adds the specified scalar field to the collection of scalar fields.
void RemoveScalarField (string fieldName)
Removed the field with the specified name from the current field collection.
TVectorField GetVectorField (string name)
Returns vector field with the specified name.
TVectorField GetVectorField (int index)
Returns the vector field with the specified index.
virtual TVectorField CreateVectorField (string fieldName, string fieldDescription)
Creates and returns a new vector field of dimensions that match dimensions of the current structured mesh, and with specified name and description.
TVectorField AddVectorField (string fieldName, string fieldDescription)
Creates and returns a new vector field of dimensions that match dimensions of the current 1D structuredmesh, and specified with name and description, and adds it to the current collection.
void AddVectorField (TVectorField field, string name)
Adds the specified vector field to the collection of vector fields under the specified name.
void AddVectorField (TVectorField field)
Adds the specified vector field to the collection of vector fields.
void RemoveVectorField (string fieldName)
Removed the field with the specified name from the current field collection.
TTensorField GetTensorField (string name)
Returns tensor field with the specified name.
TTensorField GetTensorField (int index)
Returns the tensor field with the specified index.
virtual TTensorField CreateTensorField (string fieldName, string fieldDescription)
Creates and returns a new tensor field of dimensions that match dimensions of the current structured mesh, and with specified name and description.
TTensorField AddTensorField (string fieldName, string fieldDescription)
Creates a new tensor field of dimensions that match dimensions of the current 1D structuredmesh, and specified with name and description, and adds it to the current collection.
void AddTensorField (TTensorField field, string name)
Adds the specified tensor field to the collection of tensor fields under the specified name.
void AddTensorField (TTensorField field)
Adds the specified tensor field to the collection of tensor fields.
void RemoveTensorField (string fieldName)
Removed the field with the specified name from the current field collection.
Additional Inherited Members
Properties inherited from IG.Num.UnstructuredMesh1d< vec3, Field< int >, int, Field< double >, double, Field< vec3 >, vec3, Field< mat3 >, mat3 >
FieldCollection< TIndexField, TIndex > IndexFields [get]
Gets the collection of index fields of the current mesh.
TIndexField ActiveIndexField [get, protected set]
Gets active index field. Has protected setter.
string ActiveIndexFieldName [get, set]
Gets or sets name of the currently active index field. This determines the currently active index field.
int NumIndexFields [get]
Gets the number of index fields.
FieldCollection< TScalarField, TScalar > ScalarFields [get]
Gets the collection of scalar fields of the current mesh.
TScalarField ActiveScalarField [get, protected set]
Gets active scalar field. Has protected setter.
string ActiveScalarFieldName [get, set]
Gets or sets name of the currently active scalar field. This determines the currently active scalar field.
int NumScalarFields [get]
Gets the number of scalar fields.
FieldCollection< TVectorField, TVector > VectorFields [get]
Gets the collection of vector fields of the current mesh.
TVectorField ActiveVectorField [get, protected set]
Gets active vector field. Has protected setter.
string ActiveVectorFieldName [get, set]
Gets or sets name of the currently active vector field. This determines the currently active vector field.
int NumVectorFields [get]
Gets the number of vector fields.
FieldCollection< TTensorField, TTensor > TensorFields [get]
Gets the collection of tensor fields of the current mesh.
TTensorField ActiveTensorField [get, protected set]
Gets active tensor field. Has protected setter.
string ActiveTensorFieldName [get, set]
Gets or sets name of the currently active tensor field. This determines the currently active tensor field.
int NumTensorFields [get]
Gets the number of tensor fields.
Detailed Description
Unstructured mesh in 1D embedded in 3D space.
Used e.g. for representation of curves in 3D.
Type used for co-ordinates is vec3.
Contains collections of collections of index, scalar, vector and tensor fields that are created on demand.
$A Igor Jan08 Mar09;
Definition at line 18 of file UnstructuredMesh1d3d.cs.
Constructor & Destructor Documentation
UnstructuredMesh1d3d() [1/6]
IG.Num.UnstructuredMesh1d3d.UnstructuredMesh1d3d () inline
Constructs a new empty 1D (unconnected) unstructured grid (no elements contained) with no name and no description.
Definition at line 28 of file UnstructuredMesh1d3d.cs.
UnstructuredMesh1d3d() [2/6]
IG.Num.UnstructuredMesh1d3d.UnstructuredMesh1d3d (int length) inline
Constructs a new 1D (unconnected) unstructured grid with the specified size, name and description. Array of elements is allocated.
Elements of the field are arranged in a 1D structured grid.
Parameters
length Length of the field (number of grid nodes).
Definition at line 36 of file UnstructuredMesh1d3d.cs.
UnstructuredMesh1d3d() [3/6]
IG.Num.UnstructuredMesh1d3d.UnstructuredMesh1d3d (int length, string fieldName) inline
Constructs a new 1D (unconnected) unstructured grid with the specified size, name and description. Array of elements is allocated.
Elements of the field are arranged in a 1D structured grid.
Parameters
length Length of the field (number of grid nodes).
fieldName Name of the field.
Definition at line 45 of file UnstructuredMesh1d3d.cs.
UnstructuredMesh1d3d() [4/6]
IG.Num.UnstructuredMesh1d3d.UnstructuredMesh1d3d (int length, string fieldName, string fieldDescription) inline
Constructs a new 1D (unconnected) unstructured grid with the specified size, name and description. Array of elements is allocated.
Elements of the field are arranged in a 1D structured grid.
Parameters
length Length of the field (number of grid nodes).
fieldName Name of the field.
fieldDescription Field description.
Definition at line 55 of file UnstructuredMesh1d3d.cs.
UnstructuredMesh1d3d() [5/6]
IG.Num.UnstructuredMesh1d3d.UnstructuredMesh1d3d (int dimx, int dimy, string fieldName, string fieldDescription, double minx, double maxx, double miny, double maxy) inline
Constructs a (unconnected) unstructured grid based on 1D regular grid with grid direction parallel to coordinate axes, with specified name and description. Array of elements is allocated.
Parameters
dimx First dimension of the field (number of grid nodes in the first direction).
dimy Second dimension of the field.
fieldName Name of the field.
fieldDescription Field description.
minx Minimal value of x coordinate of the generated grid.
maxx Maximal value of x coordinate of the generated grid.
miny Minimal value of y coordinate of the generated grid.
maxy Maximal value of y coordinate of the generated grid.
Definition at line 71 of file UnstructuredMesh1d3d.cs.
References IG.Num.Field< TElement >.GenerateCoordinates1dPlain().
UnstructuredMesh1d3d() [6/6]
IG.Num.UnstructuredMesh1d3d.UnstructuredMesh1d3d (int dimx, string fieldName, string fieldDescription, double minxRef, double maxxRef, IRealFunction fx, IRealFunction fy, IRealFunction fz) inline
Constructs an (unconnected) unstructured grid of nodes based on 1D structured grid obtained by transformation of co-ordinates of a regular equidistant grid. Array of elements is allocated.
Parameters
dimx First dimension of the field (number of grid nodes in the first direction).
fieldName Name of the field.
fieldDescription Field description.
minxRef Minimal value of x coordinate of the generated grid.
maxxRef Maximal value of x coordinate of the generated grid.
fx Function that maps node coordinates of the reference grid to the first node coordinates of the actual grid.
fy Function that maps node coordinates of the reference grid to the second node coordinates of the actual grid.
fz Function that maps node coordinates of the reference grid to the third node coordinates of the actual grid.
Definition at line 101 of file UnstructuredMesh1d3d.cs.
References IG.Num.Field< TElement >.GenerateCoordinates1dPlain().
Member Function Documentation
GenerateCoordinates() [1/2]
void IG.Num.UnstructuredMesh1d3d.GenerateCoordinates (int dimx, double minxRef, double maxxRef) inline
Generates an (unconnected) unstructured grid of nodes based on a 1D regular grid with grid directions parallel to coordinate axes and equidistant nodes in all directions.
Parameters
dimx Dimension (number of points) along the only direction.
minxRef Minimal value of x coordinate of the generated grid.
maxxRef Maximal value of x coordinate of the generated grid.
Definition at line 123 of file UnstructuredMesh1d3d.cs.
References IG.Num.Field< TElement >.GenerateCoordinates1dPlain().
GenerateCoordinates() [2/2]
void IG.Num.UnstructuredMesh1d3d.GenerateCoordinates (int dimx, double minxRef, double maxxRef, IRealFunction fx, IRealFunction fy, IRealFunction fz) inline
Generates coordinates of an (unconnected) unstructured grid of points based on coordinates of a structured mesh for a parametric volume according to functions specifying the x, y, and z coordinates in terms of three scalar functions of 3 variables.
Coordinates are obtained by mapping individual coordinates of a regular equidistant grid from the reference system.
Parameters
dimx Dimention (number of points) in the first direction.
minxRef Lower bound for the first parameter in the reference coordinate system.
maxxRef Upper bound for the first parameter in the reference coordinate system.
fx Function that maps node coordinates of the reference grid to the first node coordinates of the actual grid.
fy Function that maps node coordinates of the reference grid to the second node coordinates of the actual grid.
fz Function that maps node coordinates of the reference grid to the second node coordinates of the actual grid.
Definition at line 147 of file UnstructuredMesh1d3d.cs.
References IG.Num.Field< TElement >.GenerateCoordinates1dPlain().
The documentation for this class was generated from the following file:
iglib/igbase/numeric/geometry/meshing/UnstructuredMesh1d3d.cs