Doc: IGLib with source files: IG.Num.RealFunctionBase Class Reference
IG.Num.RealFunctionBase Class Reference abstract
Base class for real functions of real variable.
Public Member Functions
abstract double Value (double x)
Returns the value of this function at the specified parameter.
abstract double Derivative (double x)
Returns the first derivative of this function at the specified parameter.
abstract double Derivative (double x, int order)
Returns the derivative of the given order of this function at the specified parameter.
abstract bool HigherDerivativeDefined (int order)
Tells whether the derivative of the given order is defined for this function (by implementation, not mathematically)
abstract double SecondDerivative (double x)
Returns the second derivative of the given order of this function at the specified arameter.
abstract double Integral (double x)
Returns integral from 0 to x of the function. Throws an exception if the integral is not defined.
abstract double Inverse (double y)
Returns Inverse of the current function applied to function argument. Throws an exception if the inverse function is not defined.
void Tabulate (double from, double to, int numPoints)
Tabulates the current function and its first and second derivatives (when available) on the specified interval, in the specified number of points.
void Tabulate (double from, double to, int numPoints, bool printDerivatives)
Tabulates the current function and its first and eventually second derivatives (when available) on the specified interval, in the specified number of points.
void Tabulate (double from, double to, int numPoints, bool printDerivatives, bool printSecondDerivatives)
Tabulates the current function and eventually its first and second derivatives (when available) on the specified interval, in the specified number of points.
virtual double NumericalIntegral (double from, double to, int numintervals)
Calculates numerical integral of this function. Simpson's formula is used.
virtual double NumericalDerivative (double x, double stepsize)
Calculates numerical derivative of this function. Central difference formula is used.
virtual double NumericalSecondDerivative (double x, double stepsize)
Calculates numerical second order derivative of this function. Central difference formula is used.
virtual void Test ()
Performs numerical tests with parameters adjusted for specific function. This function can be be overridden in derived classes, however its current implementation may be relatively well suited for most weighting and basic functions.
virtual void Test (double from, double to, int numProbes, double stepSize, double tolerance)
Performs some numerical tests on the current function, such as correctness of first and second derivatives, integral and inverse of the function. Results are written to the standard output. Whenever a numerical result does not match the corresponding analytical value calculated by the function, a visible notification is written.
override string ToString ()
Static Public Member Functions
static void ExampleTests ()
Protected Attributes
string _name
string _description
Properties
virtual string Name [get, set]
Returns a short name of thecurrent function.
virtual string Description [get, set]
Returns a short description of the current function.
virtual RealFunctionBase DerivativeFunction [get]
Returns a function object that represents a derivative of this function. Returns null if this is not implemented.
virtual RealFunctionBase IntegralFunction [get]
Returns a function object that represents a definite integral of this function from 0 to 1. Returns null if not implemented.
virtual RealFunctionBase InverseFunction [get]
Returns a function object that represents an inverse function of this function. Returns null if not implemented.
abstract bool ValueDefined [get, set]
Tells whether value of the function is defined by implementation.
abstract bool DerivativeDefined [get, set]
Tells whether the first derivative is defined for this function (by implementation, not mathematically)
abstract bool SecondDerivativeDefined [get, set]
Tells whether the second derivative is defined for this function (by implementation, not mathematically)
abstract bool IntegralDefined [get, set]
Tells whether analytical itegral of the function is defined or not.
abstract bool InverseDefined [get, set]
Tells whether analytical inverse function is defined or not.
Properties inherited from IG.Num.IRealFunction
string Name [get]
Returns a short name of the function.
string Description [get]
Returns a short description of the function.
bool ValueDefined [get]
Tells whether value of the function is defined by implementation.
bool DerivativeDefined [get]
Tells whether the first derivative is defined for this function (by implementation, not mathematically)
bool SecondDerivativeDefined [get]
Tells whether the second derivative is defined for this function (by implementation, not mathematically)
bool IntegralDefined [get]
Tells whether analytical itegral of the function is defined or not.
bool InverseDefined [get]
Tells whether analytical inverse function is defined or not.
Detailed Description
Base class for real functions of real variable.
A number of predefined functions can be bound in the class Func.
$A Igor xx;
Definition at line 161 of file FunctionReal.cs.
Member Function Documentation
Value()
abstract double IG.Num.RealFunctionBase.Value (double x) pure virtual
Returns the value of this function at the specified parameter.
Implements IG.Num.IRealFunction.
Implemented in IG.Num.RealFunction.
Referenced by IG.Num.RealFunctionBase.NumericalDerivative(), IG.Num.RealFunctionBase.NumericalIntegral(), IG.Num.RealFunctionBase.NumericalSecondDerivative(), IG.Num.RealFunctionBase.Tabulate(), and IG.Num.RealFunctionBase.Test().
Derivative() [1/2]
abstract double IG.Num.RealFunctionBase.Derivative (double x) pure virtual
Returns the first derivative of this function at the specified parameter.
Implements IG.Num.IRealFunction.
Implemented in IG.Num.RealFunction.
Referenced by IG.Num.RealFunctionBase.Tabulate(), and IG.Num.RealFunctionBase.Test().
Derivative() [2/2]
abstract double IG.Num.RealFunctionBase.Derivative (double x, int order) pure virtual
Returns the derivative of the given order of this function at the specified parameter.
Implements IG.Num.IRealFunction.
Implemented in IG.Num.RealFunction, IG.Num.Func.Constant, and IG.Num.Func.Identity.
HigherDerivativeDefined()
abstract bool IG.Num.RealFunctionBase.HigherDerivativeDefined (int order) pure virtual
Tells whether the derivative of the given order is defined for this function (by implementation, not mathematically)
Implements IG.Num.IRealFunction.
Implemented in IG.Num.Func.Cubic, IG.Num.FunctionPolynomial, IG.Num.Func.WeightPol7, IG.Num.RealFunction, IG.Num.Func.WeightPol5, IG.Num.Func.WeightPol4, IG.Num.Func.Quadratic, IG.Num.Func.Constant, IG.Num.Func.WeightPol3, IG.Num.Func.Identity, IG.Num.Func.WeightReciprocalPower, IG.Num.Func.PenaltyPower, IG.Num.Func.ReciprocalPower, IG.Num.Func.Linear, IG.Lib.LoadableRealFunctionBase, IG.Num.Func.WeightGauss, and IG.Num.Func.Exp.
SecondDerivative()
abstract double IG.Num.RealFunctionBase.SecondDerivative (double x) pure virtual
Returns the second derivative of the given order of this function at the specified arameter.
Implements IG.Num.IRealFunction.
Implemented in IG.Num.RealFunction.
Referenced by IG.Num.RealFunctionBase.Tabulate(), and IG.Num.RealFunctionBase.Test().
Integral()
abstract double IG.Num.RealFunctionBase.Integral (double x) pure virtual
Returns integral from 0 to x of the function. Throws an exception if the integral is not defined.
Parameters
x Upper bound of the integral.
Implements IG.Num.IRealFunction.
Implemented in IG.Num.RealFunction.
Referenced by IG.Num.RealFunctionBase.Test().
Inverse()
abstract double IG.Num.RealFunctionBase.Inverse (double y) pure virtual
Returns Inverse of the current function applied to function argument. Throws an exception if the inverse function is not defined.
Implements IG.Num.IRealFunction.
Implemented in IG.Num.RealFunction.
Referenced by IG.Num.RealFunctionBase.Test().
Tabulate() [1/3]
void IG.Num.RealFunctionBase.Tabulate (double from, double to, int numPoints) inline
Tabulates the current function and its first and second derivatives (when available) on the specified interval, in the specified number of points.
Parameters
from Left interval bound.
to Right interval bound.
numPoints Number of points in which the function is calculated.
Implements IG.Num.IRealFunction.
Definition at line 278 of file FunctionReal.cs.
Referenced by IG.Num.RealFunctionBase.Tabulate().
Tabulate() [2/3]
void IG.Num.RealFunctionBase.Tabulate (double from, double to, int numPoints, bool printDerivatives) inline
Tabulates the current function and its first and eventually second derivatives (when available) on the specified interval, in the specified number of points.
Parameters
from Left interval bound.
to Right interval bound.
numPoints Number of points in which the function is calculated.
printDerivatives Whether to print the derivatives.
Implements IG.Num.IRealFunction.
Definition at line 289 of file FunctionReal.cs.
References IG.Num.RealFunctionBase.Tabulate().
Tabulate() [3/3]
void IG.Num.RealFunctionBase.Tabulate (double from, double to, int numPoints, bool printDerivatives, bool printSecondDerivatives) inline
Tabulates the current function and eventually its first and second derivatives (when available) on the specified interval, in the specified number of points.
Parameters
from Left interval bound.
to Right interval bound.
numPoints Number of points in which the function is calculated.
printDerivatives Whether to print the derivatives.
printSecondDerivatives Whether to print the second derivatives.
Implements IG.Num.IRealFunction.
Definition at line 301 of file FunctionReal.cs.
References IG.Num.RealFunctionBase.Derivative(), IG.Num.RealFunctionBase.DerivativeDefined, IG.Num.RealFunctionBase.SecondDerivative(), IG.Num.RealFunctionBase.SecondDerivativeDefined, IG.Num.RealFunctionBase.ToString(), IG.Num.RealFunctionBase.Value(), and IG.Num.RealFunctionBase.ValueDefined.
NumericalIntegral()
virtual double IG.Num.RealFunctionBase.NumericalIntegral (double from, double to, int numintervals) inline virtual
Calculates numerical integral of this function. Simpson's formula is used.
Parameters
from Lower integral limit.
to Upper integral limit.
numintervals Number of subintervals (1 less thatn the number of evaluation points)
Returns
Numerical integral.
Implements IG.Num.IRealFunction.
Definition at line 358 of file FunctionReal.cs.
References IG.Num.Numeric.IntegralSimpson(), and IG.Num.RealFunctionBase.Value().
Referenced by IG.Num.RealFunctionBase.Test().
NumericalDerivative()
virtual double IG.Num.RealFunctionBase.NumericalDerivative (double x, double stepsize) inline virtual
Calculates numerical derivative of this function. Central difference formula is used.
Parameters
x Point at which derivative is calculated.
stepsize Step size.
Returns
Numerical derivative.
Implements IG.Num.IRealFunction.
Definition at line 367 of file FunctionReal.cs.
References IG.Num.Numeric.DerivativeCD(), and IG.Num.RealFunctionBase.Value().
Referenced by IG.Num.RealFunctionBase.Test().
NumericalSecondDerivative()
virtual double IG.Num.RealFunctionBase.NumericalSecondDerivative (double x, double stepsize) inline virtual
Calculates numerical second order derivative of this function. Central difference formula is used.
Parameters
x Point at which second order derivative is calculated.
stepsize Step size.
Returns
Numerical derivative.
Implements IG.Num.IRealFunction.
Definition at line 376 of file FunctionReal.cs.
References IG.Num.Numeric.SecondDerivativeCD(), and IG.Num.RealFunctionBase.Value().
Referenced by IG.Num.RealFunctionBase.Test().
Test() [1/2]
virtual void IG.Num.RealFunctionBase.Test () inline virtual
Performs numerical tests with parameters adjusted for specific function. This function can be be overridden in derived classes, however its current implementation may be relatively well suited for most weighting and basic functions.
Definition at line 389 of file FunctionReal.cs.
Referenced by IG.Num.RealFunctionBase.ExampleTests().
Test() [2/2]
virtual void IG.Num.RealFunctionBase.Test (double from, double to, int numProbes, double stepSize, double tolerance) inline virtual
Performs some numerical tests on the current function, such as correctness of first and second derivatives, integral and inverse of the function. Results are written to the standard output. Whenever a numerical result does not match the corresponding analytical value calculated by the function, a visible notification is written.
Parameters
from Lower bound of the interval where tests are performed.
to Upper bound of the interval where tests are performed.
numProbes Number of points for which evaluations and comparisons are performed.
stepSize Step size used for numerical integration and differentiation.
tolerance Absolute tolarence for match between analytical and numeriacl values (visible notification is launched whenever difference is larger than tolerance).
Definition at line 405 of file FunctionReal.cs.
References IG.Num.RealFunctionBase.Derivative(), IG.Num.RealFunctionBase.DerivativeDefined, IG.Num.RealFunctionBase.Integral(), IG.Num.RealFunctionBase.IntegralDefined, IG.Num.RealFunctionBase.Inverse(), IG.Num.RealFunctionBase.InverseDefined, IG.Num.RealFunctionBase.Name, IG.Num.RealFunctionBase.NumericalDerivative(), IG.Num.RealFunctionBase.NumericalIntegral(), IG.Num.RealFunctionBase.NumericalSecondDerivative(), IG.Num.RealFunctionBase.SecondDerivative(), IG.Num.RealFunctionBase.SecondDerivativeDefined, and IG.Num.RealFunctionBase.Value().
ExampleTests()
static void IG.Num.RealFunctionBase.ExampleTests () inline static
Definition at line 504 of file FunctionReal.cs.
References IG.Num.Func.GetWeightGauss(), and IG.Num.RealFunctionBase.Test().
ToString()
override string IG.Num.RealFunctionBase.ToString () inline
Definition at line 554 of file FunctionReal.cs.
References IG.Num.RealFunctionBase.Name.
Referenced by IG.Num.RealFunctionBase.Tabulate().
Member Data Documentation
_name
string IG.Num.RealFunctionBase._name protected
Definition at line 176 of file FunctionReal.cs.
_description
string IG.Num.RealFunctionBase._description protected
Definition at line 178 of file FunctionReal.cs.
Property Documentation
Name
virtual string IG.Num.RealFunctionBase.Name get set
Returns a short name of thecurrent function.
Definition at line 183 of file FunctionReal.cs.
Referenced by IG.Num.RealFunctionBase.Test(), and IG.Num.RealFunctionBase.ToString().
Description
virtual string IG.Num.RealFunctionBase.Description get set
Returns a short description of the current function.
Definition at line 195 of file FunctionReal.cs.
DerivativeFunction
virtual RealFunctionBase IG.Num.RealFunctionBase.DerivativeFunction get
Returns a function object that represents a derivative of this function. Returns null if this is not implemented.
Definition at line 208 of file FunctionReal.cs.
IntegralFunction
virtual RealFunctionBase IG.Num.RealFunctionBase.IntegralFunction get
Returns a function object that represents a definite integral of this function from 0 to 1. Returns null if not implemented.
Definition at line 213 of file FunctionReal.cs.
InverseFunction
virtual RealFunctionBase IG.Num.RealFunctionBase.InverseFunction get
Returns a function object that represents an inverse function of this function. Returns null if not implemented.
Definition at line 218 of file FunctionReal.cs.
ValueDefined
abstract bool IG.Num.RealFunctionBase.ValueDefined get set
Tells whether value of the function is defined by implementation.
Definition at line 229 of file FunctionReal.cs.
Referenced by IG.Num.RealFunctionBase.Tabulate().
DerivativeDefined
abstract bool IG.Num.RealFunctionBase.DerivativeDefined get set
Tells whether the first derivative is defined for this function (by implementation, not mathematically)
Definition at line 236 of file FunctionReal.cs.
Referenced by IG.Num.RealFunctionBase.Tabulate(), and IG.Num.RealFunctionBase.Test().
SecondDerivativeDefined
abstract bool IG.Num.RealFunctionBase.SecondDerivativeDefined get set
Tells whether the second derivative is defined for this function (by implementation, not mathematically)
Definition at line 250 of file FunctionReal.cs.
Referenced by IG.Num.RealFunctionBase.Tabulate(), and IG.Num.RealFunctionBase.Test().
IntegralDefined
abstract bool IG.Num.RealFunctionBase.IntegralDefined get set
Tells whether analytical itegral of the function is defined or not.
Definition at line 259 of file FunctionReal.cs.
Referenced by IG.Num.RealFunctionBase.Test().
InverseDefined
abstract bool IG.Num.RealFunctionBase.InverseDefined get set
Tells whether analytical inverse function is defined or not.
Definition at line 267 of file FunctionReal.cs.
Referenced by IG.Num.RealFunctionBase.Test().
The documentation for this class was generated from the following file:
iglib/igbase/numeric/FunctionReal.cs