Doc: IGLib with source files: IG.Lib.LogRecord Class Reference
IG.Lib.LogRecord Class Reference
Single record for temporary logging.
Public Member Functions
LogRecord (ReportType messagetype, string location, string message, Exception ex)
LogRecord (ReportType messagetype, string message, Exception ex)
Launches a report. Predominantly for error and warning reports.
LogRecord (ReportType messagetype, Exception ex, string location)
Launches a report. Predominantly for error and warning reports.
LogRecord (ReportType messagetype, Exception ex)
Launches a report. Predominantly for error and warning reports.
LogRecord (ReportType messagetype, string location, string message)
Launches a report.
LogRecord (ReportType messagetype, string message)
Launches a report.
LogRecord Create (ReportType messagetype, string location, string message, Exception ex)
Creates and returns a log record initialized according to parameters.
LogRecord Create (ReportType messagetype, string message, Exception ex)
Creates and returns a log record initialized according to parameters.
LogRecord Create (ReportType messagetype, Exception ex, string location)
Creates and returns a log record initialized according to parameters.
LogRecord Create (ReportType messagetype, Exception ex)
Creates and returns a log record initialized according to parameters.
LogRecord Create (ReportType messagetype, string location, string message)
Creates and returns a log record initialized according to parameters.
LogRecord Create (ReportType messagetype, string message)
Creates and returns a log record initialized according to parameters.
LogRecord CreateError (string location, string message, Exception ex)
Creates and returns an error log record initialized according to parameters.
LogRecord CreateError (string message, Exception ex)
Creates and returns an error log record initialized according to parameters.
LogRecord CreateError (Exception ex, string location)
Creates and returns an error log record initialized according to parameters.
LogRecord CreateError (Exception ex)
Creates and returns an error log record initialized according to parameters.
LogRecord CreateError (string location, string message)
Creates and returns an error log record initialized according to parameters.
LogRecord CreateError (string message)
Creates and returns an error log record initialized according to parameters.
LogRecord CreateWarning (string location, string message, Exception ex)
Creates and returns a warning log record initialized according to parameters.
LogRecord CreateWarning (string message, Exception ex)
Creates and returns a warning log record initialized according to parameters.
LogRecord CreateWarning (Exception ex, string location)
Creates and returns a warning log record initialized according to parameters.
LogRecord CreateWarning (Exception ex)
Creates and returns a warning log record initialized according to parameters.
LogRecord CreateWarning (string location, string message)
Creates and returns a warning log record initialized according to parameters.
LogRecord CreateWarning (string message)
Creates and returns a warning log record initialized according to parameters.
LogRecord CreateInfo (string location, string message)
Creates and returns an info log record initialized according to parameters.
LogRecord CreateInfo (string message)
Creates and returns an info log record initialized according to parameters.
Static Public Attributes
static bool LogToConsole = false
If true then every creation of a new LogRecord is logged to console.
Properties
ReportType Type [get, protected set]
Type of the logged message.
string Location [get, set]
Location where message cause occurred.
string Message [get, set]
Message string.
Exception Ex [get, protected set]
Eventual exception that caused the message to be logged.
Private Attributes
ReportType _type = ReportType.Info
string _location = null
string _message = null
Exception _ex = null
Detailed Description
Single record for temporary logging.
$A Igor Jun10;
Definition at line 16 of file LoggerMsg.cs.
Constructor & Destructor Documentation
LogRecord() [1/6]
IG.Lib.LogRecord.LogRecord (ReportType messagetype, string location, string message, Exception ex) inline
Definition at line 24 of file LoggerMsg.cs.
References IG.Lib.LogRecord.Ex, IG.Lib.LogRecord.Location, IG.Lib.LogRecord.LogToConsole, IG.Lib.LogRecord.Message, and IG.Lib.LogRecord.Type.
Referenced by IG.Lib.LogRecord.Create().
LogRecord() [2/6]
IG.Lib.LogRecord.LogRecord (ReportType messagetype, string message, Exception ex) inline
Launches a report. Predominantly for error and warning reports.
Parameters
messagetype Level of the message (Error, Warnind, etc.).
message User-provided description of error.
ex Exception that is the cause for launching the report (and from which additional information is extracted).
Definition at line 54 of file LoggerMsg.cs.
LogRecord() [3/6]
IG.Lib.LogRecord.LogRecord (ReportType messagetype, Exception ex, string location) inline
Launches a report. Predominantly for error and warning reports.
Parameters
messagetype Level of the message (Error, Warnind, etc.).
ex Exception that is the cause for launching the report (and from which additional information is extracted).
location User-provided description of error location.
Definition at line 62 of file LoggerMsg.cs.
LogRecord() [4/6]
IG.Lib.LogRecord.LogRecord (ReportType messagetype, Exception ex) inline
Launches a report. Predominantly for error and warning reports.
Parameters
messagetype Level of the message (Error, Warnind, etc.).
ex Exception that is the cause for launching the report (and from which additional information is extracted).
Definition at line 69 of file LoggerMsg.cs.
LogRecord() [5/6]
IG.Lib.LogRecord.LogRecord (ReportType messagetype, string location, string message) inline
Launches a report.
Parameters
messagetype Level of the message (Error, Warnind, etc.).
location User provided description of the location where report was triggered.
message User provided message included in the report.
Definition at line 77 of file LoggerMsg.cs.
LogRecord() [6/6]
IG.Lib.LogRecord.LogRecord (ReportType messagetype, string message) inline
Launches a report.
Parameters
messagetype Level of the message (Error, Warnind, etc.).
message User provided message included in the report.
Definition at line 84 of file LoggerMsg.cs.
Member Function Documentation
Create() [1/6]
LogRecord IG.Lib.LogRecord.Create (ReportType messagetype, string location, string message, Exception ex) inline
Creates and returns a log record initialized according to parameters.
Parameters
messagetype Type of the logged record.
location Description of location where logging occurred.
message Message (or additional explanation) to be logged.
ex Exception that caused creation of log record.
Definition at line 138 of file LoggerMsg.cs.
References IG.Lib.LogRecord.LogRecord().
Referenced by IG.Lib.LogRecord.CreateError(), IG.Lib.LogRecord.CreateInfo(), and IG.Lib.LogRecord.CreateWarning().
Create() [2/6]
LogRecord IG.Lib.LogRecord.Create (ReportType messagetype, string message, Exception ex) inline
Creates and returns a log record initialized according to parameters.
Parameters
messagetype Type of the logged record.
message Message (or additional explanation) to be logged.
ex Exception that caused creation of log record.
Definition at line 149 of file LoggerMsg.cs.
References IG.Lib.LogRecord.LogRecord().
Create() [3/6]
LogRecord IG.Lib.LogRecord.Create (ReportType messagetype, Exception ex, string location) inline
Creates and returns a log record initialized according to parameters.
Parameters
messagetype Type of the logged record.
ex Exception that caused creation of log record.
location Description of location where logging occurred.
Definition at line 158 of file LoggerMsg.cs.
References IG.Lib.LogRecord.LogRecord().
Create() [4/6]
LogRecord IG.Lib.LogRecord.Create (ReportType messagetype, Exception ex) inline
Creates and returns a log record initialized according to parameters.
Parameters
messagetype Type of the logged record.
ex Exception that caused creation of log record.
Definition at line 166 of file LoggerMsg.cs.
References IG.Lib.LogRecord.LogRecord().
Create() [5/6]
LogRecord IG.Lib.LogRecord.Create (ReportType messagetype, string location, string message) inline
Creates and returns a log record initialized according to parameters.
Parameters
messagetype Type of the logged record.
location Description of location where logging occurred.
message Message (or additional explanation) to be logged.
Definition at line 175 of file LoggerMsg.cs.
References IG.Lib.LogRecord.LogRecord().
Create() [6/6]
LogRecord IG.Lib.LogRecord.Create (ReportType messagetype, string message) inline
Creates and returns a log record initialized according to parameters.
Parameters
messagetype Type of the logged record.
message Message (or additional explanation) to be logged.
Definition at line 183 of file LoggerMsg.cs.
References IG.Lib.LogRecord.LogRecord().
CreateError() [1/6]
LogRecord IG.Lib.LogRecord.CreateError (string location, string message, Exception ex) inline
Creates and returns an error log record initialized according to parameters.
Parameters
location Description of location where logging occurred.
message Message (or additional explanation) to be logged.
ex Exception that caused creation of log record.
Definition at line 197 of file LoggerMsg.cs.
References IG.Lib.LogRecord.Create().
CreateError() [2/6]
LogRecord IG.Lib.LogRecord.CreateError (string message, Exception ex) inline
Creates and returns an error log record initialized according to parameters.
Parameters
message Message (or additional explanation) to be logged.
ex Exception that caused creation of log record.
Definition at line 207 of file LoggerMsg.cs.
References IG.Lib.LogRecord.Create().
CreateError() [3/6]
LogRecord IG.Lib.LogRecord.CreateError (Exception ex, string location) inline
Creates and returns an error log record initialized according to parameters.
Parameters
ex Exception that caused creation of log record.
location Description of location where logging occurred.
Definition at line 215 of file LoggerMsg.cs.
References IG.Lib.LogRecord.Create().
CreateError() [4/6]
LogRecord IG.Lib.LogRecord.CreateError (Exception ex) inline
Creates and returns an error log record initialized according to parameters.
Parameters
ex Exception that caused creation of log record.
Definition at line 222 of file LoggerMsg.cs.
References IG.Lib.LogRecord.Create().
CreateError() [5/6]
LogRecord IG.Lib.LogRecord.CreateError (string location, string message) inline
Creates and returns an error log record initialized according to parameters.
Parameters
location Description of location where logging occurred.
message Message (or additional explanation) to be logged.
Definition at line 230 of file LoggerMsg.cs.
References IG.Lib.LogRecord.Create().
CreateError() [6/6]
LogRecord IG.Lib.LogRecord.CreateError (string message) inline
Creates and returns an error log record initialized according to parameters.
Parameters
message Message (or additional explanation) to be logged.
Definition at line 237 of file LoggerMsg.cs.
References IG.Lib.LogRecord.Create().
CreateWarning() [1/6]
LogRecord IG.Lib.LogRecord.CreateWarning (string location, string message, Exception ex) inline
Creates and returns a warning log record initialized according to parameters.
Parameters
location Description of location where logging occurred.
message Message (or additional explanation) to be logged.
ex Exception that caused creation of log record.
Definition at line 250 of file LoggerMsg.cs.
References IG.Lib.LogRecord.Create().
CreateWarning() [2/6]
LogRecord IG.Lib.LogRecord.CreateWarning (string message, Exception ex) inline
Creates and returns a warning log record initialized according to parameters.
Parameters
message Message (or additional explanation) to be logged.
ex Exception that caused creation of log record.
Definition at line 260 of file LoggerMsg.cs.
References IG.Lib.LogRecord.Create().
CreateWarning() [3/6]
LogRecord IG.Lib.LogRecord.CreateWarning (Exception ex, string location) inline
Creates and returns a warning log record initialized according to parameters.
Parameters
ex Exception that caused creation of log record.
location Description of location where logging occurred.
Definition at line 268 of file LoggerMsg.cs.
References IG.Lib.LogRecord.Create().
CreateWarning() [4/6]
LogRecord IG.Lib.LogRecord.CreateWarning (Exception ex) inline
Creates and returns a warning log record initialized according to parameters.
Parameters
ex Exception that caused creation of log record.
Definition at line 275 of file LoggerMsg.cs.
References IG.Lib.LogRecord.Create().
CreateWarning() [5/6]
LogRecord IG.Lib.LogRecord.CreateWarning (string location, string message) inline
Creates and returns a warning log record initialized according to parameters.
Parameters
location Description of location where logging occurred.
message Message (or additional explanation) to be logged.
Definition at line 283 of file LoggerMsg.cs.
References IG.Lib.LogRecord.Create().
CreateWarning() [6/6]
LogRecord IG.Lib.LogRecord.CreateWarning (string message) inline
Creates and returns a warning log record initialized according to parameters.
Parameters
message Message (or additional explanation) to be logged.
Definition at line 290 of file LoggerMsg.cs.
References IG.Lib.LogRecord.Create().
CreateInfo() [1/2]
LogRecord IG.Lib.LogRecord.CreateInfo (string location, string message) inline
Creates and returns an info log record initialized according to parameters.
Parameters
location Description of location where logging occurred.
message Message (or additional explanation) to be logged.
Definition at line 303 of file LoggerMsg.cs.
References IG.Lib.LogRecord.Create().
CreateInfo() [2/2]
LogRecord IG.Lib.LogRecord.CreateInfo (string message) inline
Creates and returns an info log record initialized according to parameters.
Parameters
message Message (or additional explanation) to be logged.
Definition at line 310 of file LoggerMsg.cs.
References IG.Lib.LogRecord.Create().
Member Data Documentation
LogToConsole
bool IG.Lib.LogRecord.LogToConsole = false static
If true then every creation of a new LogRecord is logged to console.
Definition at line 20 of file LoggerMsg.cs.
Referenced by IG.Lib.LogRecord.LogRecord().
_type
ReportType IG.Lib.LogRecord._type = ReportType.Info private
Definition at line 93 of file LoggerMsg.cs.
_location
string IG.Lib.LogRecord._location = null private
Definition at line 101 of file LoggerMsg.cs.
_message
string IG.Lib.LogRecord._message = null private
Definition at line 101 of file LoggerMsg.cs.
_ex
Exception IG.Lib.LogRecord._ex = null private
Definition at line 117 of file LoggerMsg.cs.
Property Documentation
Type
ReportType IG.Lib.LogRecord.Type get protected set
Type of the logged message.
Definition at line 96 of file LoggerMsg.cs.
Referenced by IG.Lib.Logger.GetErrorsReport(), IG.Lib.Logger.GetInfosReport(), IG.Lib.Logger.GetReport(), IG.Lib.Logger.GetWarningsReport(), IG.Lib.Logger.HasLogs(), IG.Lib.LogRecord.LogRecord(), IG.Lib.Logger.NumLogs(), IG.Lib.Logger.PrintReport(), and IG.Lib.Logger.Report().
Location
string IG.Lib.LogRecord.Location get set
Location where message cause occurred.
Definition at line 105 of file LoggerMsg.cs.
Referenced by IG.Lib.LogRecord.LogRecord(), IG.Lib.Logger.PrintReport(), and IG.Lib.Logger.Report().
Message
string IG.Lib.LogRecord.Message get set
Message string.
Definition at line 112 of file LoggerMsg.cs.
Referenced by IG.Lib.LogRecord.LogRecord(), IG.Lib.Logger.PrintReport(), and IG.Lib.Logger.Report().
Ex
Exception IG.Lib.LogRecord.Ex get protected set
Eventual exception that caused the message to be logged.
Definition at line 121 of file LoggerMsg.cs.
Referenced by IG.Lib.LogRecord.LogRecord(), IG.Lib.Logger.PrintReport(), and IG.Lib.Logger.Report().
The documentation for this class was generated from the following file:
iglib/igbase/reporter/LoggerMsg.cs