Doc: IGLib with source files: IG.Lib.SettingsReaderBase Class Reference
IG.Lib.SettingsReaderBase Class Reference abstract
Public Member Functions
abstract string GetSetting (string settingname)
Retrieves the specified setting from the current settings source.
virtual bool GetBooleanSetting (string settingname)
Retrieves the specified boolean setting from the current settings source.
virtual long GetIntegerSetting (string settingname)
Retrieves the specified integer setting from the current settings source. If the specific setting is not specified in the configuration then 0 is returned.
virtual long GetIntegerSetting (string settingname, long defaultvalue)
Retrieves the specified integer setting from the current settings source.
Protected Attributes
bool _expandEnv = true
Properties
object Lock [get]
ILockable.Lock, gets a public lock for the current object.
virtual bool ExpandEnvironmentVariables [get, set]
Properties inherited from IG.Lib.ILockable
object Lock [get]
Static Private Member Functions
static ISettingsRreader FromAppConfig ()
Private Attributes
object lockobj = new object()
Detailed Description
Definition at line 30 of file SettingsRreader.cs.
Member Function Documentation
GetSetting()
abstract string IG.Lib.SettingsReaderBase.GetSetting (string settingname) pure virtual
Retrieves the specified setting from the current settings source.
Parameters
settingname Setting name.
Implemented in IG.Lib.SettingsReaderAppConfig.
Referenced by IG.Lib.SettingsReaderBase.GetBooleanSetting(), and IG.Lib.SettingsReaderBase.GetIntegerSetting().
GetBooleanSetting()
virtual bool IG.Lib.SettingsReaderBase.GetBooleanSetting (string settingname) inline virtual
Retrieves the specified boolean setting from the current settings source.
Parameters
settingname Setting name.
Definition at line 58 of file SettingsRreader.cs.
References IG.Lib.SettingsReaderBase.GetSetting(), and IG.Lib.UtilStr.ToBoolean().
GetIntegerSetting() [1/2]
virtual long IG.Lib.SettingsReaderBase.GetIntegerSetting (string settingname) inline virtual
Retrieves the specified integer setting from the current settings source. If the specific setting is not specified in the configuration then 0 is returned.
Parameters
settingname Setting name.
Definition at line 66 of file SettingsRreader.cs.
References IG.Lib.SettingsReaderBase.GetSetting(), and IG.Lib.UtilStr.ToInt().
GetIntegerSetting() [2/2]
virtual long IG.Lib.SettingsReaderBase.GetIntegerSetting (string settingname, long defaultvalue) inline virtual
Retrieves the specified integer setting from the current settings source.
Parameters
settingname Setting name.
defaultvalue Value returned in the case that the correspondig setting is not defined.
Definition at line 74 of file SettingsRreader.cs.
References IG.Lib.SettingsReaderBase.GetSetting(), and IG.Lib.UtilStr.ToInt().
FromAppConfig()
static ISettingsRreader IG.Lib.SettingsReaderBase.FromAppConfig () inline static private
Definition at line 155 of file SettingsRreader.cs.
Member Data Documentation
lockobj
object IG.Lib.SettingsReaderBase.lockobj = new object() private
Definition at line 33 of file SettingsRreader.cs.
_expandEnv
bool IG.Lib.SettingsReaderBase._expandEnv = true protected
Definition at line 42 of file SettingsRreader.cs.
Property Documentation
Lock
object IG.Lib.SettingsReaderBase.Lock get
ILockable.Lock, gets a public lock for the current object.
Definition at line 37 of file SettingsRreader.cs.
ExpandEnvironmentVariables
virtual bool IG.Lib.SettingsReaderBase.ExpandEnvironmentVariables get set
Definition at line 45 of file SettingsRreader.cs.
The documentation for this class was generated from the following file:
iglib/igbase/application/SettingsRreader.cs