Doc: IGLib with source files: IGLib.Core.BasicTypeConverter Class Reference
IGLib.Core.BasicTypeConverter Class Reference
Provides basic type conversion functionality using IConvertible and nullable handling.
Public Member Functions
virtual object ConvertToType (object value, Type targetType)
Converts the specified value to the specified target type.
T ConvertToType< T > (object value)
Converts the specified value to the specified target type.
void ConvertToType< T > (object value, out T result)
Converts the specified value to the specified target type.
Static Public Member Functions
static bool IsNullableType (Type type)
Determines whether the specified type is nullable.
Static Public Attributes
const bool DefaultOutputFullTypeNames = false
Default value of OutputFullTypeNames.
const string NullTypeString = "[[null type]]"
Protected Member Functions
string TypeName (Type type)
Returns name of the specified type type , dependent on the property OutputFullTypeNames: if it is true then the full type name is returned (obtained by Type.FullName), otherwise the short name is returned (obtained by Type.Name).
Properties
bool OutputFullTypeNames = DefaultOutputFullTypeNames [get, set]
Whether to take full type names in exception messages and elsewhere.
Detailed Description
Provides basic type conversion functionality using IConvertible and nullable handling.
To include array-like conversion, use the CollectionTypeConverter class.
Definition at line 8 of file BasicTypeConverter.cs.
Member Function Documentation
ConvertToType()
virtual object IGLib.Core.BasicTypeConverter.ConvertToType (object value, Type targetType) inline virtual
Converts the specified value to the specified target type.
Parameters
value The value to convert.
targetType The type to convert the value to.
Returns
The converted value.
Implements IGLib.Core.ITypeConverter.
Reimplemented in IGLib.CoreExtended.ReflectionTypeConverter, and IGLib.Core.CollectionTypeConverter.
Definition at line 17 of file BasicTypeConverter.cs.
References IGLib.Core.BasicTypeConverter.IsNullableType().
Referenced by IGLib.Core.BasicTypeConverter.ConvertToType< T >().
ConvertToType< T >() [1/2]
T IGLib.Core.BasicTypeConverter.ConvertToType< T > (object value) inline
Converts the specified value to the specified target type.
Template Parameters
T The type to convert the value to.
Parameters
value The value to convert.
Returns
The converted value.
Implements IGLib.Core.ITypeConverter.
Definition at line 57 of file BasicTypeConverter.cs.
References IGLib.Core.BasicTypeConverter.ConvertToType().
Referenced by IGLib.Core.BasicTypeConverter.ConvertToType< T >().
ConvertToType< T >() [2/2]
void IGLib.Core.BasicTypeConverter.ConvertToType< T > (object value, out T result) inline
Converts the specified value to the specified target type.
Template Parameters
T The type to convert the value to.
Parameters
value The value to convert.
result When this method returns, contains the converted value.
Implements IGLib.Core.ITypeConverter.
Definition at line 68 of file BasicTypeConverter.cs.
References IGLib.Core.BasicTypeConverter.ConvertToType< T >().
IsNullableType()
static bool IGLib.Core.BasicTypeConverter.IsNullableType (Type type) inline static
Determines whether the specified type is nullable.
Parameters
type The type to check.
Returns
true if the type is nullable; otherwise, false.
Definition at line 78 of file BasicTypeConverter.cs.
Referenced by IGLib.Core.BasicTypeConverter.ConvertToType().
TypeName()
string IGLib.Core.BasicTypeConverter.TypeName (Type type) inline protected
Returns name of the specified type type , dependent on the property OutputFullTypeNames: if it is true then the full type name is returned (obtained by Type.FullName), otherwise the short name is returned (obtained by Type.Name).
Parameters
type Type whose name is to be returned. If null then NullTypeString is returned.
Returns
The name of the type type : full name if OutputFullTypeNames is true, short name if it is false, or NullTypeString if type is null.
Definition at line 100 of file BasicTypeConverter.cs.
References IGLib.Core.BasicTypeConverter.NullTypeString, and IGLib.Core.BasicTypeConverter.OutputFullTypeNames.
Member Data Documentation
DefaultOutputFullTypeNames
const bool IGLib.Core.BasicTypeConverter.DefaultOutputFullTypeNames = false static
Default value of OutputFullTypeNames.
Definition at line 84 of file BasicTypeConverter.cs.
NullTypeString
const string IGLib.Core.BasicTypeConverter.NullTypeString = "[[null type]]" static
Definition at line 90 of file BasicTypeConverter.cs.
Referenced by IGLib.Core.BasicTypeConverter.TypeName().
Property Documentation
OutputFullTypeNames
bool IGLib.Core.BasicTypeConverter.OutputFullTypeNames = DefaultOutputFullTypeNames get set
Whether to take full type names in exception messages and elsewhere.
Default is DefaultOutputFullTypeNames.
Definition at line 88 of file BasicTypeConverter.cs.
Referenced by IGLib.Core.BasicTypeConverter.TypeName().
The documentation for this class was generated from the following file:
IGLibGraphics3D/src/IGLib.Graphics3D/other/TypeConversion/BasicTypeConverter.cs