Doc: IGLib with source files: IG.Lib.WaitCondition Class Reference
IG.Lib.WaitCondition Class Reference
Provides a framework for blocking execution until the specified condition becomes satisfied. Function Wait() does that. The function continuously check the unblocking condition until it becomes satisfied, sleeping a certain amount of time between consecutive checks. Time plan of checks (i.e. the amount of sleepin time between them) can be adjusted by public properties SleepFirst, MinSleepMs, MaxSleepMs, and MaxRelativeLatency. These properties can be adjusted while waiting. Blocking condition is evaluated by the (public) function Condition() and can be adjusted in one of the following ways:
Public Member Functions
WaitCondition ()
Creates event waiter with properties initialized to default values.
WaitCondition (int minSleepMs, double maxRelativeLatency)
Creates event waiter with properties initialized to specified values (or to default valuse for those parameters that are not specified).
WaitCondition (int minSleepMs, int maxSleepMs, double maxRelativeLatency, bool sleepFirst)
Creates event waiter with properties initialized to specified values (or to default valuse for those parameters that are not specified).
override bool Condition ()
Function that returns true if unblocking condition is satisfied, and false otherwise. If the condition delegate is set then the delegate is used to evaluate the condition, otherwise the protected method ConditionFunction() is used. The condition can therefore be adjusted in one of the following ways:
override void Wait ()
Blocks until the specified condition gets satisfied. See class description for details.
override string ToString ()
Public Member Functions inherited from IG.Lib.WaitConditionBase
virtual void CancelOne ()
Cancels the current waiting for the condition (if one is going on) and unblocks the thread on which waiting was called (possibly with some latency).
virtual void CancelAll ()
Cancel the current waiting for the condition on all threads.
Protected Member Functions
virtual void InitWaitCondition ()
Initializes object properties with default values.
virtual void InitWaitCondition (int minSleepMs, double maxRelativeLatency)
Initializes blocking parameters to the specified values (or to default values for those parameters that are not specified).
virtual void InitWaitCondition (int minSleepMs, int maxSleepMs, double maxRelativeLatency, bool sleepFirst)
Initializes blocking parameters.
virtual bool ConditionFunction ()
Evaluates blocking condition in the case that the condition delegate is not specified.
Protected Attributes
ConditionDelegateBase _conditionDelegate = null
int _minSleepMs = 1
StopWatch1 _timer = null
Properties
virtual ConditionDelegateBase ConditionDelegate [protected get, set]
Contains function that is called to evaluate the unblocking condition. If this delegate is set and Condition() is not overridden then the delegate is used to check whether the unblocking condition is satisfied.
virtual int MinSleepMs [get, set]
Minimal sleeping time, in milliseconds, between successive condition checks. If less than 0 then minimal sleeping time is not specified, so there may be no sleeping.
virtual int MaxSleepMs [get, set]
Maximal sleeping time, in milliseconds, between successive condition checks. If less than 0 then maximal sleeping time is not specified and sleeping interval is not bounded above. If set to 0 then no sleeping will be performed between successive checks (max. sleeping time overrides the minimal sleeping time).
virtual double MaxRelativeLatency [get, set]
Maximal relative latency of waiting procedure. Sleeping time chosen between two successive condition check willl be chosen smaller or equal to total elapsed waiting time multiplied by this number. If less than 0 then maximal relative latency is not specified. If minimal sleeping time is specified then it overrides the sleeping time calculated according to this parameter.
virtual bool SleepFirst [get, set]
If true and if minimal sleeping time is larger than 0, then sleep for minimal sleeping time will be performed before the first check for unblocking condition.
StopWatch1 Timer [get]
Timer that measures the total time elapsed when waiting for fulfillment of unblocking condition. Used to evaluate appropriate sleeping times that will not cause too much latency.
Properties inherited from IG.Lib.WaitConditionBase
object Lock [get]
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
object InternalLock [get]
Used internally for locking access to internal fields.
object WaitLock [get]
Must be used only for locking waiting the Waiting() block (since it is potentially time consuming).
virtual bool IsWaiting [get, protected set]
True if waiting for unblocking condition is currently performed, and false otherwise. Setting should only be done within the waiting function.
virtual bool CancelFlag [get, set]
If this flag is set then the current waiting (if one is going on) will be cancelled.
Properties inherited from IG.Lib.IWaitCondition
bool IsWaiting [get]
Returns true if waiting for unblocking condition is currently performed, and false otherwise. Setting should only be done within the waiting function.
Properties inherited from IG.Lib.ILockable
object Lock [get]
Private Attributes
int _maxSleepMs = -1
double _maxRelativeLatency = 0.05
bool _sleepFirst = false
Detailed Description
Provides a framework for blocking execution until the specified condition becomes satisfied. Function Wait() does that. The function continuously check the unblocking condition until it becomes satisfied, sleeping a certain amount of time between consecutive checks. Time plan of checks (i.e. the amount of sleepin time between them) can be adjusted by public properties SleepFirst, MinSleepMs, MaxSleepMs, and MaxRelativeLatency. These properties can be adjusted while waiting. Blocking condition is evaluated by the (public) function Condition() and can be adjusted in one of the following ways:
by setting the delegate ConditionDelegate.
by overriding the protected ConditionFunction() in a derived class and setting ConditionDelegate to null.
by overriding the Condition() function itself.
$A Igor Jun10;
Definition at line 133 of file WaitCondition.cs.
Constructor & Destructor Documentation
WaitCondition() [1/3]
IG.Lib.WaitCondition.WaitCondition () inline
Creates event waiter with properties initialized to default values.
Definition at line 139 of file WaitCondition.cs.
References IG.Lib.WaitCondition.InitWaitCondition().
WaitCondition() [2/3]
IG.Lib.WaitCondition.WaitCondition (int minSleepMs, double maxRelativeLatency) inline
Creates event waiter with properties initialized to specified values (or to default valuse for those parameters that are not specified).
Definition at line 146 of file WaitCondition.cs.
References IG.Lib.WaitCondition.InitWaitCondition(), and IG.Lib.WaitCondition.MaxSleepMs.
WaitCondition() [3/3]
IG.Lib.WaitCondition.WaitCondition (int minSleepMs, int maxSleepMs, double maxRelativeLatency, bool sleepFirst) inline
Creates event waiter with properties initialized to specified values (or to default valuse for those parameters that are not specified).
Definition at line 153 of file WaitCondition.cs.
References IG.Lib.WaitCondition.InitWaitCondition().
Member Function Documentation
InitWaitCondition() [1/3]
virtual void IG.Lib.WaitCondition.InitWaitCondition () inline protected virtual
Initializes object properties with default values.
Definition at line 163 of file WaitCondition.cs.
References IG.Lib.WaitCondition.MaxRelativeLatency, IG.Lib.WaitCondition.MaxSleepMs, IG.Lib.WaitCondition.MinSleepMs, and IG.Lib.WaitCondition.SleepFirst.
Referenced by IG.Lib.WaitCondition.InitWaitCondition(), and IG.Lib.WaitCondition.WaitCondition().
InitWaitCondition() [2/3]
virtual void IG.Lib.WaitCondition.InitWaitCondition (int minSleepMs, double maxRelativeLatency) inline protected virtual
Initializes blocking parameters to the specified values (or to default values for those parameters that are not specified).
Definition at line 173 of file WaitCondition.cs.
References IG.Lib.WaitCondition.InitWaitCondition(), IG.Lib.WaitCondition.MaxRelativeLatency, and IG.Lib.WaitCondition.MinSleepMs.
InitWaitCondition() [3/3]
virtual void IG.Lib.WaitCondition.InitWaitCondition (int minSleepMs, int maxSleepMs, double maxRelativeLatency, bool sleepFirst) inline protected virtual
Initializes blocking parameters.
Definition at line 183 of file WaitCondition.cs.
References IG.Lib.WaitCondition.InitWaitCondition(), IG.Lib.WaitCondition.MaxRelativeLatency, IG.Lib.WaitCondition.MaxSleepMs, IG.Lib.WaitCondition.MinSleepMs, and IG.Lib.WaitCondition.SleepFirst.
Condition()
override bool IG.Lib.WaitCondition.Condition () inline
Function that returns true if unblocking condition is satisfied, and false otherwise. If the condition delegate is set then the delegate is used to evaluate the condition, otherwise the protected method ConditionFunction() is used. The condition can therefore be adjusted in one of the following ways:
by setting the ConditionDelegate field
by overriding the ConditionFunction and leaving ConditionDelegate null.
Implements IG.Lib.IWaitCondition.
Definition at line 206 of file WaitCondition.cs.
References IG.Lib.WaitCondition.ConditionDelegate, IG.Lib.WaitCondition.ConditionFunction(), and IG.Lib.WaitConditionBase.InternalLock.
Referenced by IG.Lib.WaitCondition.Wait().
ConditionFunction()
virtual bool IG.Lib.WaitCondition.ConditionFunction () inline protected virtual
Evaluates blocking condition in the case that the condition delegate is not specified.
Returns
True if the unblocking condition is satisfied (such that the thread will continue with execution) after the condition is being evaluated.
Reimplemented in IG.Lib.WaitFileEventLatenceBase.
Definition at line 231 of file WaitCondition.cs.
Referenced by IG.Lib.WaitCondition.Condition().
Wait()
override void IG.Lib.WaitCondition.Wait () inline
Blocks until the specified condition gets satisfied. See class description for details.
This method will normally not be overridden, except with intention to change the condition check time plan. When overriding, use the original method as template.
Implements IG.Lib.IWaitCondition.
Definition at line 309 of file WaitCondition.cs.
References IG.Lib.WaitConditionBase.CancelFlag, IG.Lib.WaitCondition.Condition(), IG.Lib.WaitConditionBase.InternalLock, IG.Lib.IWaitCondition.IsWaiting, IG.Lib.WaitCondition.MaxRelativeLatency, IG.Lib.WaitCondition.MaxSleepMs, IG.Lib.WaitCondition.MinSleepMs, IG.Lib.StopWatch1.Reset(), IG.Lib.WaitCondition.SleepFirst, IG.Lib.StopWatch1.Start(), IG.Lib.StopWatch1.Time, and IG.Lib.WaitCondition.Timer.
Referenced by IG.Lib.WaitFileEventBaseByProxyLatence.Wait().
ToString()
override string IG.Lib.WaitCondition.ToString () inline
Definition at line 375 of file WaitCondition.cs.
References IG.Lib.IWaitCondition.IsWaiting, IG.Lib.WaitCondition.MaxRelativeLatency, IG.Lib.WaitCondition.MaxSleepMs, IG.Lib.WaitCondition.MinSleepMs, and IG.Lib.WaitCondition.SleepFirst.
Referenced by IG.Lib.WaitFileEventBaseByProxyLatence.ToString().
Member Data Documentation
_conditionDelegate
ConditionDelegateBase IG.Lib.WaitCondition._conditionDelegate = null protected
Definition at line 217 of file WaitCondition.cs.
_minSleepMs
int IG.Lib.WaitCondition._minSleepMs = 1 protected
Definition at line 243 of file WaitCondition.cs.
_maxSleepMs
int IG.Lib.WaitCondition._maxSleepMs = -1 private
Definition at line 244 of file WaitCondition.cs.
_maxRelativeLatency
double IG.Lib.WaitCondition._maxRelativeLatency = 0.05 private
Definition at line 247 of file WaitCondition.cs.
_sleepFirst
bool IG.Lib.WaitCondition._sleepFirst = false private
Definition at line 249 of file WaitCondition.cs.
_timer
StopWatch1 IG.Lib.WaitCondition._timer = null protected
Definition at line 292 of file WaitCondition.cs.
Property Documentation
ConditionDelegate
virtual ConditionDelegateBase IG.Lib.WaitCondition.ConditionDelegate protected get set
Contains function that is called to evaluate the unblocking condition. If this delegate is set and Condition() is not overridden then the delegate is used to check whether the unblocking condition is satisfied.
Definition at line 223 of file WaitCondition.cs.
Referenced by IG.Lib.WaitCondition.Condition().
MinSleepMs
virtual int IG.Lib.WaitCondition.MinSleepMs get set
Minimal sleeping time, in milliseconds, between successive condition checks. If less than 0 then minimal sleeping time is not specified, so there may be no sleeping.
Definition at line 254 of file WaitCondition.cs.
Referenced by IG.Lib.WaitCondition.InitWaitCondition(), IG.Lib.WaitCondition.ToString(), and IG.Lib.WaitCondition.Wait().
MaxSleepMs
virtual int IG.Lib.WaitCondition.MaxSleepMs get set
Maximal sleeping time, in milliseconds, between successive condition checks. If less than 0 then maximal sleeping time is not specified and sleeping interval is not bounded above. If set to 0 then no sleeping will be performed between successive checks (max. sleeping time overrides the minimal sleeping time).
Definition at line 264 of file WaitCondition.cs.
Referenced by IG.Lib.WaitCondition.InitWaitCondition(), IG.Lib.WaitCondition.ToString(), IG.Lib.WaitCondition.Wait(), and IG.Lib.WaitCondition.WaitCondition().
MaxRelativeLatency
virtual double IG.Lib.WaitCondition.MaxRelativeLatency get set
Maximal relative latency of waiting procedure. Sleeping time chosen between two successive condition check willl be chosen smaller or equal to total elapsed waiting time multiplied by this number. If less than 0 then maximal relative latency is not specified. If minimal sleeping time is specified then it overrides the sleeping time calculated according to this parameter.
Definition at line 274 of file WaitCondition.cs.
Referenced by IG.Lib.WaitCondition.InitWaitCondition(), IG.Lib.WaitCondition.ToString(), and IG.Lib.WaitCondition.Wait().
SleepFirst
virtual bool IG.Lib.WaitCondition.SleepFirst get set
If true and if minimal sleeping time is larger than 0, then sleep for minimal sleeping time will be performed before the first check for unblocking condition.
Definition at line 282 of file WaitCondition.cs.
Referenced by IG.Lib.WaitCondition.InitWaitCondition(), IG.Lib.WaitCondition.ToString(), and IG.Lib.WaitCondition.Wait().
Timer
StopWatch1 IG.Lib.WaitCondition.Timer get protected
Timer that measures the total time elapsed when waiting for fulfillment of unblocking condition. Used to evaluate appropriate sleeping times that will not cause too much latency.
Definition at line 297 of file WaitCondition.cs.
Referenced by IG.Lib.WaitCondition.Wait().
The documentation for this class was generated from the following file:
iglib/igbase/0unsorted/WaitCondition.cs