Doc: IGLib with source files: IG.Lib.KeyValueSortable< Tkey, Tvalue >.ComparerBase Class Reference
IG.Lib.KeyValueSortable< Tkey, Tvalue >.ComparerBase Class Reference abstract
Base class for different IComparer classes.
Public Member Functions
int Compare (KeyValueSortable< Tkey, Tvalue > keyValue1, KeyValueSortable< Tkey, Tvalue > keyValue2)
Protected Member Functions
ComparerBase (bool twoStage, bool strict)
abstract IComparable GetFirstStageCompared (KeyValueSortable< Tkey, Tvalue > keyValue)
Extracts the object used in the first level of comparison from the argument.
abstract IComparable GetSecondStageCompared (KeyValueSortable< Tkey, Tvalue > keyValue)
Extracts the object used in the second level of comparison from the argument.
Protected Attributes
bool _twoStage = false
bool _strict = false
Properties
bool TwoStage [get]
bool Strict [get]
Detailed Description
Base class for different IComparer classes.
Definition at line 3186 of file Utils.cs.
Constructor & Destructor Documentation
ComparerBase()
IG.Lib.KeyValueSortable< Tkey, Tvalue >.ComparerBase.ComparerBase (bool twoStage, bool strict) inline protected
Definition at line 3188 of file Utils.cs.
References IG.Lib.KeyValueSortable< Tkey, Tvalue >.ComparerBase._strict, IG.Lib.KeyValueSortable< Tkey, Tvalue >.ComparerBase._twoStage, and IG.Lib.KeyValueSortable< Tkey, Tvalue >.ComparerBase.Strict.
Member Function Documentation
GetFirstStageCompared()
abstract IComparable IG.Lib.KeyValueSortable< Tkey, Tvalue >.ComparerBase.GetFirstStageCompared (KeyValueSortable< Tkey, Tvalue > keyValue) protected pure virtual
Extracts the object used in the first level of comparison from the argument.
Implemented in IG.Lib.KeyValueSortable< Tkey, Tvalue >.ComparerValueBase, and IG.Lib.KeyValueSortable< Tkey, Tvalue >.ComparerKeyBase.
Referenced by IG.Lib.KeyValueSortable< Tkey, Tvalue >.ComparerBase.Compare().
GetSecondStageCompared()
abstract IComparable IG.Lib.KeyValueSortable< Tkey, Tvalue >.ComparerBase.GetSecondStageCompared (KeyValueSortable< Tkey, Tvalue > keyValue) protected pure virtual
Extracts the object used in the second level of comparison from the argument.
Implemented in IG.Lib.KeyValueSortable< Tkey, Tvalue >.ComparerValueBase, and IG.Lib.KeyValueSortable< Tkey, Tvalue >.ComparerKeyBase.
Referenced by IG.Lib.KeyValueSortable< Tkey, Tvalue >.ComparerBase.Compare().
Compare()
int IG.Lib.KeyValueSortable< Tkey, Tvalue >.ComparerBase.Compare (KeyValueSortable< Tkey, Tvalue > keyValue1, KeyValueSortable< Tkey, Tvalue > keyValue2) inline
Definition at line 3209 of file Utils.cs.
References IG.Lib.KeyValueSortable< Tkey, Tvalue >.ComparerBase.GetFirstStageCompared(), IG.Lib.KeyValueSortable< Tkey, Tvalue >.ComparerBase.GetSecondStageCompared(), IG.Lib.KeyValueSortable< Tkey, Tvalue >.OrderParameter, IG.Lib.KeyValueSortable< Tkey, Tvalue >.ComparerBase.Strict, and IG.Lib.KeyValueSortable< Tkey, Tvalue >.ComparerBase.TwoStage.
Member Data Documentation
_twoStage
bool IG.Lib.KeyValueSortable< Tkey, Tvalue >.ComparerBase._twoStage = false protected
Definition at line 3200 of file Utils.cs.
Referenced by IG.Lib.KeyValueSortable< Tkey, Tvalue >.ComparerBase.ComparerBase().
_strict
bool IG.Lib.KeyValueSortable< Tkey, Tvalue >.ComparerBase._strict = false protected
Definition at line 3201 of file Utils.cs.
Referenced by IG.Lib.KeyValueSortable< Tkey, Tvalue >.ComparerBase.ComparerBase().
Property Documentation
TwoStage
bool IG.Lib.KeyValueSortable< Tkey, Tvalue >.ComparerBase.TwoStage get
Definition at line 3204 of file Utils.cs.
Referenced by IG.Lib.KeyValueSortable< Tkey, Tvalue >.ComparerBase.Compare().
Strict
bool IG.Lib.KeyValueSortable< Tkey, Tvalue >.ComparerBase.Strict get
Definition at line 3207 of file Utils.cs.
Referenced by IG.Lib.KeyValueSortable< Tkey, Tvalue >.ComparerBase.Compare(), and IG.Lib.KeyValueSortable< Tkey, Tvalue >.ComparerBase.ComparerBase().
The documentation for this class was generated from the following file:
iglib/igbase/utilities/Utils.cs