Doc: IGLib with source files: IG.Reflection.SerializationBinderCascadedImmutable Class Reference
IG.Reflection.SerializationBinderCascadedImmutable Class Reference
A cascaded SerializationBinder class that maps the assembly and type information of the serialized objects into classes into which objects shoulld be deserialized, based on definitions from a collection of the contained elementary ISerializationBinder classes. For each pair of assembly name / type name presented to this object by calling the BindToType(string, string) method (see also method description), the call is forwarded to the same method of each contained serialization binder object until one of them returns a mapped type. Else (if all calls return null), null is returned as the mapped type, meaning that there is no user-defined mapping from assembly and type name to a type, in which case deserializer provides the default binding.
Public Member Functions
SerializationBinderCascadedImmutable (params SerializationBinderBase[] binders)
Constructs the serialization bider with all the specified binders added.
SerializationBinderCascadedImmutable (IEnumerable< SerializationBinderBase > binders)
Constructs the serialization bider with all the specified binders added.
override Type BindToType (string assemblyName, string typeName)
Specifies the mapping of assemblyName and typeName of the serialized object into a type of an object into which it deserializes. This mapping is defined by a collection of elementary ISerializationBinder objects derived from SerializationBinderBase class, each of which defines its own mapping. The overall mapping is defined by this method in such a way that it iterates (in order of elements) over all serialization binders on the ContainedBindersPrivate, and returns as target type the first non-null Type object returned by the ISerializationBinder.BindToType(string, string) method returned by any of the objects contained in ContainedBindersPrivate called with the same parameters assemblyName and typeName .
Protected Member Functions
void AddBindersInternal (params SerializationBinderBase[] binders)
Adds the specified binders at the end of the ordered set of contained binders (ContainedBindersPrivate, accessible via ContainedBinders).
void AddBindersInternal (IEnumerable< SerializationBinderBase > binders)
Adds the specified binders at the end of the ordered set of contained binders (ContainedBindersPrivate, accessible via ContainedBinders).
Properties
List< SerializationBinderBase > ContainedBindersPrivate = new List<SerializationBinderBase>() [get]
List of contained serialization binders.
IEnumerable< SerializationBinder > ContainedBinders [get]
Enumerable that enables iteration over contained serialization binders (elements of ContainedBindersPrivate).
Detailed Description
A cascaded SerializationBinder class that maps the assembly and type information of the serialized objects into classes into which objects shoulld be deserialized, based on definitions from a collection of the contained elementary ISerializationBinder classes. For each pair of assembly name / type name presented to this object by calling the BindToType(string, string) method (see also method description), the call is forwarded to the same method of each contained serialization binder object until one of them returns a mapped type. Else (if all calls return null), null is returned as the mapped type, meaning that there is no user-defined mapping from assembly and type name to a type, in which case deserializer provides the default binding.
This serialization binder can contain other cascaded binders, allowing for arbitrary tree-like cascading of binders. Orter in which binders are added specifies the order in which the contained binders are tested whether they canb provide the type for given assembly name / type name combination.
New binders cannot be added after construction. To avoid this limitation, use the SerializationBinderCascaded class.
Definition at line 73 of file SerializationBinderCascaded.cs.
Constructor & Destructor Documentation
SerializationBinderCascadedImmutable() [1/2]
IG.Reflection.SerializationBinderCascadedImmutable.SerializationBinderCascadedImmutable (params SerializationBinderBase[] binders) inline
Constructs the serialization bider with all the specified binders added.
Parameters
binders Serialization binders (of type SerializationBinderBase) that will be contained in the constructed serialization binder (can be stated as an array, as comma-separated arguments of variable number, or as enoty argument to include no builders).
Definition at line 80 of file SerializationBinderCascaded.cs.
References IG.Reflection.SerializationBinderCascadedImmutable.AddBindersInternal().
SerializationBinderCascadedImmutable() [2/2]
IG.Reflection.SerializationBinderCascadedImmutable.SerializationBinderCascadedImmutable (IEnumerable< SerializationBinderBase > binders) inline
Constructs the serialization bider with all the specified binders added.
Parameters
binders Collection of serialization binders (of type SerializationBinderBase) that will be contained in the constructed serialization binder.
Definition at line 88 of file SerializationBinderCascaded.cs.
References IG.Reflection.SerializationBinderCascadedImmutable.AddBindersInternal().
Member Function Documentation
AddBindersInternal() [1/2]
void IG.Reflection.SerializationBinderCascadedImmutable.AddBindersInternal (params SerializationBinderBase[] binders) inline protected
Adds the specified binders at the end of the ordered set of contained binders (ContainedBindersPrivate, accessible via ContainedBinders).
Parameters
binders Serialization binders (of type SerializationBinderBase) that will be contained in the constructed serialization binder (can be stated as an array, as comma-separated arguments of variable number, or as enoty argument to include no builders).
Definition at line 105 of file SerializationBinderCascaded.cs.
References IG.Reflection.SerializationBinderCascadedImmutable.ContainedBindersPrivate.
Referenced by IG.Reflection.SerializationBinderCascaded.Add(), and IG.Reflection.SerializationBinderCascadedImmutable.SerializationBinderCascadedImmutable().
AddBindersInternal() [2/2]
void IG.Reflection.SerializationBinderCascadedImmutable.AddBindersInternal (IEnumerable< SerializationBinderBase > binders) inline protected
Adds the specified binders at the end of the ordered set of contained binders (ContainedBindersPrivate, accessible via ContainedBinders).
Parameters
binders Collection of serialization binders (of type SerializationBinderBase) that will be contained in the constructed serialization binder.
Definition at line 120 of file SerializationBinderCascaded.cs.
References IG.Reflection.SerializationBinderCascadedImmutable.ContainedBindersPrivate.
BindToType()
override Type IG.Reflection.SerializationBinderCascadedImmutable.BindToType (string assemblyName, string typeName) inline
Specifies the mapping of assemblyName and typeName of the serialized object into a type of an object into which it deserializes. This mapping is defined by a collection of elementary ISerializationBinder objects derived from SerializationBinderBase class, each of which defines its own mapping. The overall mapping is defined by this method in such a way that it iterates (in order of elements) over all serialization binders on the ContainedBindersPrivate, and returns as target type the first non-null Type object returned by the ISerializationBinder.BindToType(string, string) method returned by any of the objects contained in ContainedBindersPrivate called with the same parameters assemblyName and typeName .
Parameters
assemblyName Assembly name of the serialized object that is matched and combined with typeName in order
typeName Type name of the deserialized object that is matched and combined with assemblyName in order to determine the type of object into which the given serialized object deseriallies.
Returns
The type into which the serialized oject with the specified assemblyName and typeName shoulld deserialize.
Implements IG.Reflection.ISerializationBinder.
Definition at line 146 of file SerializationBinderCascaded.cs.
References IG.Reflection.ISerializationBinder.BindToType(), and IG.Reflection.SerializationBinderCascadedImmutable.ContainedBinders.
Property Documentation
ContainedBindersPrivate
List<SerializationBinderBase> IG.Reflection.SerializationBinderCascadedImmutable.ContainedBindersPrivate = new List<SerializationBinderBase>() get private
List of contained serialization binders.
Definition at line 95 of file SerializationBinderCascaded.cs.
Referenced by IG.Reflection.SerializationBinderCascadedImmutable.AddBindersInternal().
ContainedBinders
IEnumerable<SerializationBinder> IG.Reflection.SerializationBinderCascadedImmutable.ContainedBinders get protected
Enumerable that enables iteration over contained serialization binders (elements of ContainedBindersPrivate).
Definition at line 98 of file SerializationBinderCascaded.cs.
Referenced by IG.Reflection.SerializationBinderCascadedImmutable.BindToType().
The documentation for this class was generated from the following file:
iglib/igbase/types_reflection/SerializationBinders/SerializationBinderCascaded.cs