Doc: IGLib with source files: IG.Num.vec3 Struct Reference
IG.Num.vec3 Struct Reference
3D vector, struct implementation.
Public Member Functions
vec3 (double x, double y, double z)
vec3 Cross (vec3 v2)
vec3 Normalize ()
vec3 (vec3 v)
Copy constructor. Initializes components of a 3D vector with components of the specified vector.
vec3 (double x, double y, double z)
Initializes components of a 3D vector with the specified values.
vec3 (double comp)
Initializes all component of a 3D vector with the specified value.
void Zero ()
Sets components of the vector to 0.0.
void Set (double comp)
Sets components of the vector to the specified value.
override int GetHashCode ()
Returns the hash code (hash function) of the current vector.
override bool Equals (Object obj)
Returns a value indicating whether the specified object is equal to the current vector.
vec3 Normalized ()
Returns normalized this 3D vector.
vec3 Normalized1 ()
Returns normalized this 3D vector in 1 norm.
vec3 Normalized2 ()
Returns normalized this 3D vector in 2 norm.
vec3 NormalizedInfinity ()
Returns normalized this 3D vector in infinity norm.
double ScalarProduct (vec3 v)
Returns scalar product of the current and the specified vector.
vec3 VectorProduct (vec3 v)
Returns vector product of the current and the specified vector.
vec3 CrossProduct (vec3 v)
Returns vector product of the current and the specified vector.
vec3 Cross (vec3 v)
Returns vector product of the current and the specified vector.
mat3 DyadicProduct (vec3 v)
Returns dyadic product of the current and the specified vector.
double MixedProduct (vec3 b, vec3 c)
Returns mixed product of the current and two other specified vectors. This equals the volume of the parallelepiped spanned by these vectors.
vec3 Multiply (double k)
Returns the current vector multiplied by the specified scalar.
vec3 Add (vec3 a)
Returns sum of the current vector and the specified vector.
vec3 Subtract (vec3 a)
Returns difference between the current vector and the specified vector.
override string ToString ()
Returns string representation of the 3D vector.
void Read ()
Reads 3D vector components from a console.
void Read (string name)
Reads 3D vector components from a console.
Static Public Member Functions
static vec3 operator+ (vec3 a, vec3 b)
static vec3 operator- (vec3 a, vec3 b)
static vec3 operator* (double scalar, vec3 v)
static vec3 operator* (vec3 v, double scalar)
static double Dot (vec3 a, vec3 b)
static vec3 Cross (vec3 a, vec3 b)
static vec3 Copy (vec3 v)
Returns a copy of the specified 3D vector.
static void Negate (vec3 v, ref vec3 res)
Negates the specified vector and stores its copy in the resulting vector.
static vec3 operator+ (vec3 v)
Unary plus, returns the operand.
static vec3 operator- (vec3 v)
Unary negation, returns the negative operand.
static vec3 operator+ (vec3 a, vec3 b)
Vector addition.
static vec3 operator- (vec3 a, vec3 b)
Vector subtraction.
static double operator* (vec3 a, vec3 b)
Scalar product of two 3D vectors.
static vec3 operator* (vec3 a, double b)
Product of a 3D vector by a scalar.
static vec3 operator* (double a, vec3 b)
Product of a 3D vector by a scalar.
static vec3 operator/ (vec3 a, double b)
Vector subtraction.
static bool operator== (vec3 a, vec3 b)
Vector comparison.
static bool operator!= (vec3 a, vec3 b)
Vector comparison, returns true if vectors are different.
Public Attributes
double x
double y
double z
Properties
double this[int i] [get, set]
Index operator.
double Norm [get]
Gets a 2 norm of the current 3D vector.
double Norm2 [get]
Gets a 2 norm of the current 3D vector.
double Norm1 [get]
Gets an 1 norm of the current 3D vector - sum of absolute values of components.
double NormInf [get]
Gets an infinity norm of the current 3D vector - maximal absolute component value.
Detailed Description
3D vector, struct implementation.
Name of this struct is not in line with conventions. This is intentional in order to prevent mistaking struct implementation for class interpretation.
$A Igor Jul08; Oct10;
Definition at line 9 of file vec3.cs.
Constructor & Destructor Documentation
vec3() [1/4]
IG.Num.vec3.vec3 (double x, double y, double z) inline
Definition at line 13 of file vec3.cs.
References IG.Num.vec3.x, IG.Num.vec3.y, and IG.Num.vec3.z.
Referenced by IG.Num.vec3.Add(), IG.Num.vec3.Copy(), IG.Num.vec3.Multiply(), IG.Num.vec3.Normalize(), IG.Num.vec3.operator-(), IG.Num.vec3.operator/(), IG.Num.vec3.Subtract(), and IG.Num.vec3.VectorProduct().
vec3() [2/4]
IG.Num.vec3.vec3 (vec3 v) inline
Copy constructor. Initializes components of a 3D vector with components of the specified vector.
Parameters
v Vectr whose components are copied to the initialized vector.
Definition at line 36 of file Matrix3D.cs.
References IG.Num.vec3.x, IG.Num.vec3.y, and IG.Num.vec3.z.
vec3() [3/4]
IG.Num.vec3.vec3 (double x, double y, double z) inline
Initializes components of a 3D vector with the specified values.
Parameters
x Value to be assigned to the 1st element of the vector.
y Value to be assigned to the 2nd element of the vector.
z Value to be assigned to the 3rd element of the vector.
Definition at line 45 of file Matrix3D.cs.
References IG.Num.vec3.x, IG.Num.vec3.y, and IG.Num.vec3.z.
vec3() [4/4]
IG.Num.vec3.vec3 (double comp) inline
Initializes all component of a 3D vector with the specified value.
Parameters
comp Value assigned to all vector elements.
Definition at line 52 of file Matrix3D.cs.
References IG.Num.vec3.x, IG.Num.vec3.y, and IG.Num.vec3.z.
Member Function Documentation
operator+() [1/3]
static vec3 IG.Num.vec3.operator+ (vec3 a, vec3 b) static
operator-() [1/3]
static vec3 IG.Num.vec3.operator- (vec3 a, vec3 b) static
operator*() [1/5]
static vec3 IG.Num.vec3.operator* (double scalar, vec3 v) static
operator*() [2/5]
static vec3 IG.Num.vec3.operator* (vec3 v, double scalar) static
Dot()
static double IG.Num.vec3.Dot (vec3 a, vec3 b) static
Referenced by IGLib.Gr3D.TubularSurface_01.ComputeFrames(), IGLib.Gr3D.TubularMeshGenerator_02.ComputeFrames(), IGLib.Gr3D.TubularMeshGenerator_06.GenerateMesh(), IGLib.Gr3D.TubularMeshGenerator.GenerateMesh(), IGLib.Gr3D.TubularMeshGenerator_06.GenerateMeshByFrenet(), and IGLib.Gr3D.TubularMeshGenerator.GenerateMeshByFrenet().
Cross() [1/3]
static vec3 IG.Num.vec3.Cross (vec3 a, vec3 b) static
Referenced by IGLib.Gr3D.TubularSurface_01.ComputeFrames(), IGLib.Gr3D.TubularMeshGenerator_02.ComputeFrames(), IG.Num.vec3.Cross(), IGLib.Gr3D.TubularMeshGenerator_04.Generate(), IGLib.Gr3D.TubularMeshGenerator_05.Generate(), IGLib.Gr3D.TubularMeshGenerator_03.Generate(), IGLib.Gr3D.IGLib.Gr3D.ParametricSurfaceMeshGenerator.GenerateMesh(), IGLib.Gr3D.TubularMeshGenerator_06.GenerateMesh(), IGLib.Gr3D.TubularMeshGenerator.GenerateMesh(), IGLib.Gr3D.TubularMeshGenerator_06.GenerateMeshByFrenet(), IGLib.Gr3D.TubularMeshGenerator.GenerateMeshByFrenet(), IGLib.Gr3D.MeshExportExtensions.WriteFacet(), and IGLib.Gr3D.MeshExportExtensions_02.WriteTriangle().
Cross() [2/3]
vec3 IG.Num.vec3.Cross (vec3 v2) inline
Definition at line 41 of file vec3.cs.
References IG.Num.vec3.Cross().
Normalize()
vec3 IG.Num.vec3.Normalize () inline
Definition at line 47 of file vec3.cs.
References IG.Num.vec3.vec3(), IG.Num.vec3.x, IG.Num.vec3.y, and IG.Num.vec3.z.
Referenced by IGLib.Gr3D.TubularSurface_01.ComputeFrames(), IGLib.Gr3D.TubularMeshGenerator_05.Generate(), IGLib.Gr3D.TubularMeshGenerator_03.Generate(), IGLib.Gr3D.TubularMeshGenerator_04.Generate(), IGLib.Gr3D.IGLib.Gr3D.ParametricSurfaceMeshGenerator.GenerateMesh(), IGLib.Gr3D.TubularMeshGenerator_06.GenerateMesh(), IGLib.Gr3D.TubularMeshGenerator.GenerateMesh(), IGLib.Gr3D.TubularMeshGenerator_06.GenerateMeshByFrenet(), IGLib.Gr3D.TubularMeshGenerator.GenerateMeshByFrenet(), IGLib.Gr3D.MeshExportExtensions.WriteFacet(), and IGLib.Gr3D.MeshExportExtensions_02.WriteTriangle().
Zero()
void IG.Num.vec3.Zero () inline
Sets components of the vector to 0.0.
Definition at line 58 of file Matrix3D.cs.
References IG.Num.vec3.x, IG.Num.vec3.y, and IG.Num.vec3.z.
Set()
void IG.Num.vec3.Set (double comp) inline
Sets components of the vector to the specified value.
Definition at line 62 of file Matrix3D.cs.
References IG.Num.vec3.x, IG.Num.vec3.y, and IG.Num.vec3.z.
GetHashCode()
override int IG.Num.vec3.GetHashCode () inline
Returns the hash code (hash function) of the current vector.
This method should be consistent with the VectorBase.GetHashCode() method, which is standard for implementations of the IVector interface.
Two vectors that have equal all elements will produce the same hash codes.
Probability that two different vectors will produce the same hash code is small but it exists.
Overrides the object.GetHashCode method.
Definition at line 112 of file Matrix3D.cs.
References IG.Num.vec3.x, IG.Num.vec3.y, and IG.Num.vec3.z.
Equals()
override bool IG.Num.vec3.Equals (Object obj) inline
Returns a value indicating whether the specified object is equal to the current vector.
True is returned if the object is of type vec3) and has equal elements as the current vector.
Overrides the object.Equals(object) method.
Definition at line 125 of file Matrix3D.cs.
Normalized()
vec3 IG.Num.vec3.Normalized () inline
Returns normalized this 3D vector.
Definition at line 162 of file Matrix3D.cs.
References IG.Num.vec3.Multiply(), and IG.Num.vec3.Norm.
Referenced by IG.Num.Vector3d.Normalized().
Normalized1()
vec3 IG.Num.vec3.Normalized1 () inline
Returns normalized this 3D vector in 1 norm.
Definition at line 166 of file Matrix3D.cs.
References IG.Num.vec3.Multiply(), and IG.Num.vec3.Norm1.
Referenced by IG.Num.Vector3d.Normalized1().
Normalized2()
vec3 IG.Num.vec3.Normalized2 () inline
Returns normalized this 3D vector in 2 norm.
Definition at line 170 of file Matrix3D.cs.
References IG.Num.vec3.Multiply(), and IG.Num.vec3.Norm2.
Referenced by IG.Num.Vector3d.Normalized2().
NormalizedInfinity()
vec3 IG.Num.vec3.NormalizedInfinity () inline
Returns normalized this 3D vector in infinity norm.
Definition at line 174 of file Matrix3D.cs.
References IG.Num.vec3.Multiply(), and IG.Num.vec3.NormInf.
Referenced by IG.Num.Vector3d.NormalizedInfinity().
ScalarProduct()
double IG.Num.vec3.ScalarProduct (vec3 v) inline
Returns scalar product of the current and the specified vector.
Definition at line 179 of file Matrix3D.cs.
References IG.Num.vec3.x, IG.Num.vec3.y, and IG.Num.vec3.z.
Referenced by IG.Num.Vector3d.ScalarProduct(), and IG.Num.Vector3d.VectorProduct().
VectorProduct()
vec3 IG.Num.vec3.VectorProduct (vec3 v) inline
Returns vector product of the current and the specified vector.
Definition at line 185 of file Matrix3D.cs.
References IG.Num.vec3.vec3(), IG.Num.vec3.x, IG.Num.vec3.y, and IG.Num.vec3.z.
Referenced by IG.Num.vec3.Cross(), and IG.Num.vec3.CrossProduct().
CrossProduct()
vec3 IG.Num.vec3.CrossProduct (vec3 v) inline
Returns vector product of the current and the specified vector.
Definition at line 195 of file Matrix3D.cs.
References IG.Num.vec3.VectorProduct().
Cross() [3/3]
vec3 IG.Num.vec3.Cross (vec3 v) inline
Returns vector product of the current and the specified vector.
Definition at line 199 of file Matrix3D.cs.
References IG.Num.vec3.VectorProduct().
DyadicProduct()
mat3 IG.Num.vec3.DyadicProduct (vec3 v) inline
Returns dyadic product of the current and the specified vector.
Definition at line 203 of file Matrix3D.cs.
References IG.Num.vec3.x, IG.Num.vec3.y, and IG.Num.vec3.z.
Referenced by IG.Num.Vector3d.DyadicProduct().
MixedProduct()
double IG.Num.vec3.MixedProduct (vec3 b, vec3 c) inline
Returns mixed product of the current and two other specified vectors. This equals the volume of the parallelepiped spanned by these vectors.
Definition at line 214 of file Matrix3D.cs.
References IG.Num.vec3.x, IG.Num.vec3.y, and IG.Num.vec3.z.
Referenced by IG.Num.Vector3d.MixedProduct().
Multiply()
vec3 IG.Num.vec3.Multiply (double k) inline
Returns the current vector multiplied by the specified scalar.
Parameters
k Factor by which the current vector is multiplied.
Definition at line 224 of file Matrix3D.cs.
References IG.Num.vec3.vec3(), IG.Num.vec3.x, IG.Num.vec3.y, and IG.Num.vec3.z.
Referenced by IG.Num.Vector3d.Multiply(), IG.Num.vec3.Normalized(), IG.Num.vec3.Normalized1(), IG.Num.vec3.Normalized2(), and IG.Num.vec3.NormalizedInfinity().
Add()
vec3 IG.Num.vec3.Add (vec3 a) inline
Returns sum of the current vector and the specified vector.
Definition at line 230 of file Matrix3D.cs.
References IG.Num.vec3.vec3(), IG.Num.vec3.x, IG.Num.vec3.y, and IG.Num.vec3.z.
Referenced by IG.Num.Vector3d.Add(), IGLib.Gr3D.TubularSurface_01.ComputeFrames(), IGLib.Gr3D.TubularMeshGenerator_02.ComputeFrames(), IGLib.Gr3D.TubularSurfaceExamples.Example_01(), and IGLib.Gr3D.MeshExportExtensions.ExportToGltf().
Subtract()
vec3 IG.Num.vec3.Subtract (vec3 a) inline
Returns difference between the current vector and the specified vector.
Definition at line 236 of file Matrix3D.cs.
References IG.Num.vec3.vec3(), IG.Num.vec3.x, IG.Num.vec3.y, and IG.Num.vec3.z.
Referenced by IG.Num.Vector3d.Subtract().
Copy()
static vec3 IG.Num.vec3.Copy (vec3 v) inline static
Returns a copy of the specified 3D vector.
Parameters
v Vector whose copy is returned.
Definition at line 250 of file Matrix3D.cs.
References IG.Num.vec3.vec3().
Referenced by IG.Num.vec3.operator+().
Negate()
static void IG.Num.vec3.Negate (vec3 v, ref vec3 res) inline static
Negates the specified vector and stores its copy in the resulting vector.
Parameters
v Vectr to be negated.
res Vector where the result is stored.
Definition at line 258 of file Matrix3D.cs.
operator+() [2/3]
static vec3 IG.Num.vec3.operator+ (vec3 v) inline static
Unary plus, returns the operand.
Definition at line 269 of file Matrix3D.cs.
References IG.Num.vec3.Copy().
operator-() [2/3]
static vec3 IG.Num.vec3.operator- (vec3 v) inline static
Unary negation, returns the negative operand.
Definition at line 275 of file Matrix3D.cs.
References IG.Num.vec3.vec3().
operator+() [3/3]
static vec3 IG.Num.vec3.operator+ (vec3 a, vec3 b) inline static
Vector addition.
Definition at line 281 of file Matrix3D.cs.
operator-() [3/3]
static vec3 IG.Num.vec3.operator- (vec3 a, vec3 b) inline static
Vector subtraction.
Definition at line 288 of file Matrix3D.cs.
operator*() [3/5]
static double IG.Num.vec3.operator* (vec3 a, vec3 b) inline static
Scalar product of two 3D vectors.
Definition at line 295 of file Matrix3D.cs.
operator*() [4/5]
static vec3 IG.Num.vec3.operator* (vec3 a, double b) inline static
Product of a 3D vector by a scalar.
Definition at line 301 of file Matrix3D.cs.
operator*() [5/5]
static vec3 IG.Num.vec3.operator* (double a, vec3 b) inline static
Product of a 3D vector by a scalar.
Definition at line 307 of file Matrix3D.cs.
operator/()
static vec3 IG.Num.vec3.operator/ (vec3 a, double b) inline static
Vector subtraction.
Definition at line 313 of file Matrix3D.cs.
References IG.Num.vec3.vec3().
operator==()
static bool IG.Num.vec3.operator== (vec3 a, vec3 b) inline static
Vector comparison.
Definition at line 324 of file Matrix3D.cs.
operator!=()
static bool IG.Num.vec3.operator!= (vec3 a, vec3 b) inline static
Vector comparison, returns true if vectors are different.
Definition at line 330 of file Matrix3D.cs.
ToString()
override string IG.Num.vec3.ToString () inline
Returns string representation of the 3D vector.
Definition at line 342 of file Matrix3D.cs.
References IG.Num.vec3.x, IG.Num.vec3.y, and IG.Num.vec3.z.
Referenced by IG.Num.Vector3d.ToString().
Read() [1/2]
void IG.Num.vec3.Read () inline
Reads 3D vector components from a console.
Definition at line 349 of file Matrix3D.cs.
Referenced by IG.Num.Vector3d.Read().
Read() [2/2]
void IG.Num.vec3.Read (string name) inline
Reads 3D vector components from a console.
Parameters
name Name of the vector to be read; it is written as orientation to the user and can be null.
Definition at line 358 of file Matrix3D.cs.
References IG.Lib.UtilConsole.Read(), IG.Num.vec3.x, IG.Num.vec3.y, and IG.Num.vec3.z.
Member Data Documentation
x
double IG.Num.vec3.x
Definition at line 11 of file vec3.cs.
Referenced by IG.Num.vec3.Add(), IGLib.Gr3D.ConicalCurve3DParameterizationFromPolarWithBounds.Curve(), IG.Num.vec3.DyadicProduct(), IG.Num.vec3.GetHashCode(), IG.Num.Func3dBase.Gradient(), IG.Num.Func3dVectorFormBase.Gradient(), IG.Num.Func3dBase.Hessian(), IG.Num.Field< TCoord >.MapCoordinates1dPlain(), IG.Num.StructuredField2d< TCoord >.MapCoordinatesReferencePlain(), IG.Num.vec3.MixedProduct(), IG.Num.vec3.Multiply(), IG.Num.vec3.Normalize(), IG.Num.vec3.Read(), IG.Num.vec3.ScalarProduct(), IG.Num.vec3.Set(), IG.Num.vec3.Subtract(), IG.Num.vec3.ToString(), IG.Num.BoundingBox3d.Update(), IG.Num.Field< TCoord >.UpdateBounds(), IG.Num.Func3dBase.Value(), IG.Num.vec3.vec3(), IG.Num.Vector3d.Vector3d(), IG.Num.vec3.VectorProduct(), IGLib.Gr3D.MeshExportExtensions_02.WriteTriangle(), and IG.Num.vec3.Zero().
y
double IG.Num.vec3.y
Definition at line 11 of file vec3.cs.
Referenced by IG.Num.vec3.Add(), IGLib.Gr3D.ConicalCurve3DParameterizationFromPolarWithBounds.Curve(), IG.Num.vec3.DyadicProduct(), IG.Num.vec3.GetHashCode(), IG.Num.Func3dBase.Gradient(), IG.Num.Func3dVectorFormBase.Gradient(), IG.Num.Func3dBase.Hessian(), IG.Num.StructuredField2d< TCoord >.MapCoordinatesReferencePlain(), IG.Num.vec3.MixedProduct(), IG.Num.vec3.Multiply(), IG.Num.vec3.Normalize(), IG.Num.vec3.Read(), IG.Num.vec3.ScalarProduct(), IG.Num.vec3.Set(), IG.Num.vec3.Subtract(), IG.Num.vec3.ToString(), IG.Num.BoundingBox3d.Update(), IG.Num.Field< TCoord >.UpdateBounds(), IG.Num.Func3dBase.Value(), IG.Num.vec3.vec3(), IG.Num.Vector3d.Vector3d(), IG.Num.vec3.VectorProduct(), IGLib.Gr3D.MeshExportExtensions_02.WriteTriangle(), and IG.Num.vec3.Zero().
z
double IG.Num.vec3.z
Definition at line 11 of file vec3.cs.
Referenced by IG.Num.vec3.Add(), IGLib.Gr3D.ConicalCurve3DParameterizationFromPolarWithBounds.Curve(), IG.Num.vec3.DyadicProduct(), IGLib.Gr3D.TubularMeshGenerator_03.Generate(), IGLib.Gr3D.TubularMeshGenerator_04.Generate(), IGLib.Gr3D.TubularMeshGenerator_05.Generate(), IG.Num.vec3.GetHashCode(), IG.Num.Func3dBase.Gradient(), IG.Num.Func3dVectorFormBase.Gradient(), IG.Num.Func3dBase.Hessian(), IG.Num.vec3.MixedProduct(), IG.Num.vec3.Multiply(), IG.Num.vec3.Normalize(), IG.Num.vec3.Read(), IG.Num.vec3.ScalarProduct(), IG.Num.vec3.Set(), IG.Num.vec3.Subtract(), IG.Num.vec3.ToString(), IG.Num.BoundingBox3d.Update(), IG.Num.Field< TCoord >.UpdateBounds(), IG.Num.Func3dBase.Value(), IG.Num.vec3.vec3(), IG.Num.Vector3d.Vector3d(), IG.Num.vec3.VectorProduct(), IGLib.Gr3D.MeshExportExtensions_02.WriteTriangle(), and IG.Num.vec3.Zero().
Property Documentation
this[int i]
double IG.Num.vec3.this[int i] get set
Index operator.
Parameters
i Component index.
Returns
The specified component of a 3D vector.
Definition at line 74 of file Matrix3D.cs.
Norm
double IG.Num.vec3.Norm get
Gets a 2 norm of the current 3D vector.
Definition at line 140 of file Matrix3D.cs.
Referenced by IG.Num.vec3.Normalized().
Norm2
double IG.Num.vec3.Norm2 get
Gets a 2 norm of the current 3D vector.
Definition at line 143 of file Matrix3D.cs.
Referenced by IG.Num.vec3.Normalized2().
Norm1
double IG.Num.vec3.Norm1 get
Gets an 1 norm of the current 3D vector - sum of absolute values of components.
Definition at line 147 of file Matrix3D.cs.
Referenced by IG.Num.vec3.Normalized1().
NormInf
double IG.Num.vec3.NormInf get
Gets an infinity norm of the current 3D vector - maximal absolute component value.
Definition at line 151 of file Matrix3D.cs.
Referenced by IG.Num.vec3.NormalizedInfinity().
The documentation for this struct was generated from the following files:
IGLibGraphics3D/src/IGLib.Graphics3D/other/vec3.cs
iglib/igbase/numeric/geometry/Matrix3D.cs