Doc: IGLib with source files: IG.Tests.IGLibCoreReflectionTests Class Reference
IG.Tests.IGLibCoreReflectionTests Class Reference
Public Member Functions
void IEnumerableElementTypeRetriavalProducesNullForTypesThatAreNotEnumerable ()
void IEnumerableElementTypeRetriavalProducesNullForNullArgument ()
void IEnumerableElementTypeIsRetrievedCorrectlyForIEnumerableOfDifferentTypes ()
void CheckRetrievedElementTypeForIEnumerable< ElementType > ()
void IEnumerableElementTypeIsRetrievedCorrectlyForGenericCollections ()
void IEnumerableElementTypeIsRetrievedCorrectlyForGenericCollectionInterfaces ()
void IEnumerableElementTypeIsRetrievedCorrectlyForArrays ()
void CheckRetrievedElementTypeForGenericCollectionOrArray< CollectionType, ElementType > ()
void IEnumerableElementTypeIsRetrievedCorrectlyForNestedGenericCollections ()
void IEnumerableElementTypeIsRetrievedCorrectlyForNestedArrays ()
void IEnumerableElementTypeIsRetrievedCorrectlyForNestedGenericCollectionsOfArrays ()
void IEnumerableElementTypeIsRetrievedCorrectlyForNestedArraysOfGenericCollections ()
void CheckRetrievedElementTypeForNestedGenericCollectionOrArray< CollectionType, ElementType > ()
Detailed Description
Definition at line 17 of file IGLibCoreReflectionTests.cs.
Member Function Documentation
IEnumerableElementTypeRetriavalProducesNullForTypesThatAreNotEnumerable()
void IG.Tests.IGLibCoreReflectionTests.IEnumerableElementTypeRetriavalProducesNullForTypesThatAreNotEnumerable () inline
Definition at line 21 of file IGLibCoreReflectionTests.cs.
References IGLib.CoreExtended.UtilReflectionCore.GetEnumerableType().
IEnumerableElementTypeRetriavalProducesNullForNullArgument()
void IG.Tests.IGLibCoreReflectionTests.IEnumerableElementTypeRetriavalProducesNullForNullArgument () inline
Definition at line 29 of file IGLibCoreReflectionTests.cs.
References IGLib.CoreExtended.UtilReflectionCore.GetEnumerableType().
IEnumerableElementTypeIsRetrievedCorrectlyForIEnumerableOfDifferentTypes()
void IG.Tests.IGLibCoreReflectionTests.IEnumerableElementTypeIsRetrievedCorrectlyForIEnumerableOfDifferentTypes () inline
Definition at line 35 of file IGLibCoreReflectionTests.cs.
CheckRetrievedElementTypeForIEnumerable< ElementType >()
void IG.Tests.IGLibCoreReflectionTests.CheckRetrievedElementTypeForIEnumerable< ElementType > () inline
Definition at line 49 of file IGLibCoreReflectionTests.cs.
References IGLib.CoreExtended.UtilReflectionCore.GetEnumerableType().
IEnumerableElementTypeIsRetrievedCorrectlyForGenericCollections()
void IG.Tests.IGLibCoreReflectionTests.IEnumerableElementTypeIsRetrievedCorrectlyForGenericCollections () inline
Definition at line 59 of file IGLibCoreReflectionTests.cs.
IEnumerableElementTypeIsRetrievedCorrectlyForGenericCollectionInterfaces()
void IG.Tests.IGLibCoreReflectionTests.IEnumerableElementTypeIsRetrievedCorrectlyForGenericCollectionInterfaces () inline
Definition at line 73 of file IGLibCoreReflectionTests.cs.
IEnumerableElementTypeIsRetrievedCorrectlyForArrays()
void IG.Tests.IGLibCoreReflectionTests.IEnumerableElementTypeIsRetrievedCorrectlyForArrays () inline
Definition at line 93 of file IGLibCoreReflectionTests.cs.
CheckRetrievedElementTypeForGenericCollectionOrArray< CollectionType, ElementType >()
void IG.Tests.IGLibCoreReflectionTests.CheckRetrievedElementTypeForGenericCollectionOrArray< CollectionType, ElementType > () inline
Definition at line 104 of file IGLibCoreReflectionTests.cs.
References IGLib.CoreExtended.UtilReflectionCore.GetEnumerableType().
IEnumerableElementTypeIsRetrievedCorrectlyForNestedGenericCollections()
void IG.Tests.IGLibCoreReflectionTests.IEnumerableElementTypeIsRetrievedCorrectlyForNestedGenericCollections () inline
Definition at line 115 of file IGLibCoreReflectionTests.cs.
IEnumerableElementTypeIsRetrievedCorrectlyForNestedArrays()
void IG.Tests.IGLibCoreReflectionTests.IEnumerableElementTypeIsRetrievedCorrectlyForNestedArrays () inline
Definition at line 124 of file IGLibCoreReflectionTests.cs.
IEnumerableElementTypeIsRetrievedCorrectlyForNestedGenericCollectionsOfArrays()
void IG.Tests.IGLibCoreReflectionTests.IEnumerableElementTypeIsRetrievedCorrectlyForNestedGenericCollectionsOfArrays () inline
Definition at line 132 of file IGLibCoreReflectionTests.cs.
IEnumerableElementTypeIsRetrievedCorrectlyForNestedArraysOfGenericCollections()
void IG.Tests.IGLibCoreReflectionTests.IEnumerableElementTypeIsRetrievedCorrectlyForNestedArraysOfGenericCollections () inline
Definition at line 139 of file IGLibCoreReflectionTests.cs.
CheckRetrievedElementTypeForNestedGenericCollectionOrArray< CollectionType, ElementType >()
void IG.Tests.IGLibCoreReflectionTests.CheckRetrievedElementTypeForNestedGenericCollectionOrArray< CollectionType, ElementType > () inline
Definition at line 145 of file IGLibCoreReflectionTests.cs.
References IGLib.CoreExtended.UtilReflectionCore.GetEnumerableType().
The documentation for this class was generated from the following file:
IGLibCore/tests/IGLib.Core.Tests/IGLibCoreReflectionTests.cs