Doc: IGLib with source files: IG.Lib.LoadableScriptInterpreterBase Class Reference
IG.Lib.LoadableScriptInterpreterBase Class Reference
Interpreter that can install commands from dynamically loaded (compiled) scripts and run them. Script loader object of a type is accessed through a property that can be overridden in derived classes, such that a different script loader is used. This is importand because different libraries will be required for compilation in different contexts. Script loader property creates a new script loader on first access.
Public Member Functions
LoadableScriptInterpreterBase ()
string RunCommand (string commandName, string[] commandArguments)
Runs command with the specified name that is loaded on the current object.
void AddCommandFromCode (string commandName, string code, string className, string[] initializationArguments)
Adds a new command whose execution is perfomed by an instance of a class that is dynamically compiled from the specified script code.
void AddCommandFromCode (string commandName, string code, string[] initializationArguments)
Adds a new command whose execution is perfomed by an instance of a class that is dynamically compiled from the specified script code. Name of the class is extracted from the script code.
void AddCommandFromFile (string commandName, string filePath, string className, string[] initializationArguments)
Adds a new command whose execution is perfomed by an instance of a class that is dynamically compiled from the script code contained in the specified file.
void AddCommandFromFile (string commandName, string filePath, string[] initializationArguments)
Adds a new command whose execution is perfomed by an instance of a class that is dynamically compiled from the script code contained in the specified file. Name of the class is extracted from the script code.
Protected Attributes
ScriptLoaderBase _scriptLoader
Properties
object Lock [get]
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
virtual ScriptLoaderBase ScriptLoader [get, set]
Script loader that is used to load loadable script classes that will be used for execution of commands.
SortedList< string, ILoadableScript > Commands [get]
Sorted list that contains commands as key-value pairs where the key is command name and the corresponding value is a loadable script object of type that can be executd.
ILoadableScript this[string commandName] [get, set]
Properties inherited from IG.Lib.ILockable
object Lock [get]
Private Attributes
object _mainLock = new object()
SortedList< string, ILoadableScript > _commands = new SortedList<string, ILoadableScript>()
Detailed Description
Interpreter that can install commands from dynamically loaded (compiled) scripts and run them. Script loader object of a type is accessed through a property that can be overridden in derived classes, such that a different script loader is used. This is importand because different libraries will be required for compilation in different contexts. Script loader property creates a new script loader on first access.
$A Igor Oct09;
Definition at line 27 of file LoadableScriptInterpreter.cs.
Constructor & Destructor Documentation
LoadableScriptInterpreterBase()
IG.Lib.LoadableScriptInterpreterBase.LoadableScriptInterpreterBase () inline
Definition at line 33 of file LoadableScriptInterpreter.cs.
Member Function Documentation
RunCommand()
string IG.Lib.LoadableScriptInterpreterBase.RunCommand (string commandName, string[] commandArguments) inline
Runs command with the specified name that is loaded on the current object.
Parameters
commandName Name of the command.
commandArguments Command arguments.
Returns
Result of the command.
Definition at line 116 of file LoadableScriptInterpreter.cs.
References IG.Lib.LoadableScriptInterpreterBase.Commands, and IG.Lib.ILoadableScript.Run().
Referenced by IG.Lib.CommandLineApplicationInterpreter.CmdRunLoadedScript(), and IG.Lib.CommandLineApplicationInterpreter.RunLoadedScript().
AddCommandFromCode() [1/2]
void IG.Lib.LoadableScriptInterpreterBase.AddCommandFromCode (string commandName, string code, string className, string[] initializationArguments) inline
Adds a new command whose execution is perfomed by an instance of a class that is dynamically compiled from the specified script code.
Parameters
commandName Interpreter's name of the command; added command is installed under this name on the current interpreter.
code Script code containing definition of the loadable class that contains executable code of the command.
className Name of the class containing loadable script code.
initializationArguments Initialization arguments for the created object that will perform execution of the added command.
Definition at line 132 of file LoadableScriptInterpreter.cs.
References IG.Lib.ScriptLoaderBase.CreateObjectFromCode(), and IG.Lib.LoadableScriptInterpreterBase.ScriptLoader.
AddCommandFromCode() [2/2]
void IG.Lib.LoadableScriptInterpreterBase.AddCommandFromCode (string commandName, string code, string[] initializationArguments) inline
Adds a new command whose execution is perfomed by an instance of a class that is dynamically compiled from the specified script code. Name of the class is extracted from the script code.
Parameters
commandName Interpreter's name of the command; added command is installed under this name on the current interpreter.
code Script code containing definition of the loadable class that contains executable code of the command.
initializationArguments Initialization arguments for the created object that will perform execution of the added command.
Definition at line 144 of file LoadableScriptInterpreter.cs.
References IG.Lib.ScriptLoaderBase.CreateObjectFromCode(), and IG.Lib.LoadableScriptInterpreterBase.ScriptLoader.
AddCommandFromFile() [1/2]
void IG.Lib.LoadableScriptInterpreterBase.AddCommandFromFile (string commandName, string filePath, string className, string[] initializationArguments) inline
Adds a new command whose execution is perfomed by an instance of a class that is dynamically compiled from the script code contained in the specified file.
Parameters
commandName Interpreter's name of the command; added command is installed under this name on the current interpreter.
filePath Path to the file containing script code containing definition of the loadable class that contains executable code of the command.
className Name of the class containing loadable script code.
initializationArguments Initialization arguments for the created object that will perform execution of the added command.
Definition at line 158 of file LoadableScriptInterpreter.cs.
References IG.Lib.ScriptLoaderBase.CreateObjectFromFile(), and IG.Lib.LoadableScriptInterpreterBase.ScriptLoader.
Referenced by IG.Lib.CommandLineApplicationInterpreter.LoadScript().
AddCommandFromFile() [2/2]
void IG.Lib.LoadableScriptInterpreterBase.AddCommandFromFile (string commandName, string filePath, string[] initializationArguments) inline
Adds a new command whose execution is perfomed by an instance of a class that is dynamically compiled from the script code contained in the specified file. Name of the class is extracted from the script code.
Parameters
commandName Interpreter's name of the command; added command is installed under this name on the current interpreter.
filePath Path to the file containing script code containing definition of the loadable class that contains executable code of the command.
initializationArguments Initialization arguments for the created object that will perform execution of the added command.
Definition at line 173 of file LoadableScriptInterpreter.cs.
References IG.Lib.ScriptLoaderBase.CreateObjectFromFile(), and IG.Lib.LoadableScriptInterpreterBase.ScriptLoader.
Member Data Documentation
_mainLock
object IG.Lib.LoadableScriptInterpreterBase._mainLock = new object() private
Definition at line 41 of file LoadableScriptInterpreter.cs.
_scriptLoader
ScriptLoaderBase IG.Lib.LoadableScriptInterpreterBase._scriptLoader protected
Definition at line 53 of file LoadableScriptInterpreter.cs.
_commands
SortedList<string, ILoadableScript> IG.Lib.LoadableScriptInterpreterBase._commands = new SortedList<string, ILoadableScript>() private
Definition at line 80 of file LoadableScriptInterpreter.cs.
Property Documentation
Lock
object IG.Lib.LoadableScriptInterpreterBase.Lock get
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
Definition at line 46 of file LoadableScriptInterpreter.cs.
ScriptLoader
virtual ScriptLoaderBase IG.Lib.LoadableScriptInterpreterBase.ScriptLoader get set
Script loader that is used to load loadable script classes that will be used for execution of commands.
Definition at line 60 of file LoadableScriptInterpreter.cs.
Referenced by IG.Lib.LoadableScriptInterpreterBase.AddCommandFromCode(), IG.Lib.LoadableScriptInterpreterBase.AddCommandFromFile(), IG.Lib.CommandLineApplicationInterpreter.GetLoadableScriptReferencedAssemblies(), and IG.Lib.CommandLineApplicationInterpreter.RunScriptFile().
Commands
SortedList<string, ILoadableScript> IG.Lib.LoadableScriptInterpreterBase.Commands get
Sorted list that contains commands as key-value pairs where the key is command name and the corresponding value is a loadable script object of type that can be executd.
Definition at line 86 of file LoadableScriptInterpreter.cs.
Referenced by IG.Lib.LoadableScriptInterpreterBase.RunCommand().
this[string commandName]
ILoadableScript IG.Lib.LoadableScriptInterpreterBase.this[string commandName] get set
Definition at line 89 of file LoadableScriptInterpreter.cs.
The documentation for this class was generated from the following file:
iglib/igbase/interpreters/scriptloader/LoadableScriptInterpreter.cs