Doc: IGLib with source files: IG.Num.ParallelJobDispatcherBase< JobContainerType > Class Template Reference
IG.Num.ParallelJobDispatcherBase< JobContainerType > Class Template Reference
Parallel job dispatcher. Accepts job requests and dispatches jobs to parallel job servers when available and redy to run a job.
Public Member Functions
ParallelJobDispatcherBase ()
void AddServer (ParallelJobServerBase< JobContainerType > server)
Adds the specified server to the current dispatcher.
void RemoveServer (ParallelJobServerBase< JobContainerType > server)
Removes the specified server to the current dispatcher.
void SetServersSleepTimeMs (int sleepTimeMs)
Sets sleeping time in milliseconds on all servers assigned to the current parallel job dispatcher.
void SetServersOutputLevel (int outputLevel)
Sets output level on all servers assigned to the current parallel job dispatcher.
void SetServersIsServer (bool isServer)
Sets the server flag on all servers assigned to the current parallel job dispatcher.
bool SendJob (JobContainerType jobData)
Enqueues job for execution, and returns a flag indicating whether a job has been started immediately.
void SendJob (JobContainerType jobData, out bool startedImmediately)
Enqueues job for execution.
void WaitAllJobsCompleted ()
Waits for job completion.
bool WaitAllJobsCompleted (double timeoutInSeconds)
Wait until all jobs that weer sent to the current dispatcher object complete, or timeout occurs (timeout specified in seconds), and returns a flag indicating whether the jobs have actually completed (i.e. stop was not due to timeout).
void StopServer ()
Sends to the server thread command that it has to stop.
bool StopServerWhenAllJobsDone ()
Waits until all jobs are completed, and then stops the server.
bool StopServerWhenAllJobsDone (double timeoutInSeconds)
Waits until all jobs are completed or timeout occurs, and then stops the server. Returns a flag indicating whether all jobs are actually completed before server was ordered to stop.
void KillDispatcherThread ()
Forces the working thread to stop. To let the working thread finish its current jobs and then stop, call StopServer
void KillServerThreads ()
Forces all the server threads to stop, even if in the middle of eecution of a job. To let the working thread finish its current jobs and then stop, call StopServer
void KillThreads ()
Forces all the server threads to stop, even if in the middle of eecution of a job. To let the working thread finish its current jobs and then stop, call StopServer
void RegisterSystemPriorityUpdating ()
Registers the UpdateThreadPriorityFromSystem method as "event handler" for system priority changes. After registration, this method will be called every time the value of the UtilSystem.ThreadPriority property changes.
void UnregisterSystemPriorityUpdating ()
Unregisters the UpdateThreadPriorityFromSystem method as "event handler" for system priority changes.
void StartServer ()
Starts the queue server.
void NotifyJobStarted (ParallelJobServerBase< JobContainerType > server, JobContainerType job)
Notifies the current dispatched that the specified job has started on the specified server.
void NotifyJobFinished (ParallelJobServerBase< JobContainerType > server, JobContainerType job)
Notifies the current dispatched that the specified job has started on the specified server.
void NotifyJobAborted (ParallelJobServerBase< JobContainerType > server, JobContainerType job)
Notifies the current dispatched that the specified job has started on the specified server.
void NotifyServerIdle (ParallelJobServerBase< JobContainerType > server)
Notifies the current parallel job dispatcher that the specified server has become idle.
override string ToString ()
Returns a string representation of the current job dispatcher, which contains relevent data about the server state.
void IncrementNumSentJobs ()
Increments by one the number of sent jobs (all jobs sent to the current dispatcher for execution).
void IncrementNumStartedJobs ()
Increments by one the number of started by the dispatcher up to this point.
void IncrementNumFinishedJobs ()
Increments by one the number of finished jobs (of those handled by the current dispatcher) up to this point.
void IncrementNumAbortedJobs ()
Increments by one the number of aborted jobs (of those handled by the current dispatcher) up to this point.
Protected Member Functions
void AddIdleServer (ParallelJobServerBase< JobContainerType > server)
Adds the specified parallel job server to the idle list.
void RemoveIdleServer (ParallelJobServerBase< JobContainerType > server)
Removes the specified parallel job server from the idle list.
ParallelJobServerBase< JobContainerType > GetFirstIdleServer ()
Returns the first idle server (last on the list of idle servers) and removes it from the idle servers list, or returns null if there are no idle servers.
void EnqueueJob (JobContainerType jobData)
Adds the specified job container to the execution queue.
JobContainerType DequeueJob ()
Removes the last job from the execution queue and returns it, or returns null if there are no jobs on the queue.
virtual void UpdateThreadPriorityFromSystem ()
Updates thread priority (property ThreadPriority) to the current global thread priority (the UtilSystem.ThreadPriority property).
void Serve ()
Method executed in the queue server thread. Excecutes eventual enqueued jobs as job servers become idle.
void ResetNumIdleJobServers ()
Resets number of idle job servers to 0.
Static Protected Member Functions
static int GetNextId ()
Returns another ID that is unique for objects of the containing class its and derived classes.
Protected Attributes
readonly List< ParallelJobServerBase< JobContainerType > > _jobServers
List of job servers contained by the current dispatcher.
readonly List< ParallelJobServerBase< JobContainerType > > _idleJobServers
List of idle job servers dispatched by teh current dispatcher.
Queue< JobContainerType > _jobQueue = new Queue<JobContainerType>()
Queue of jobs that could not be immediately served, scheduled for later execution.
bool _commandStopServing = false
bool _systemPriorityUpdatesRegistered = false
Whether the "event" handler for system priprity changes has already been registered.
ThreadPriority _threadPriority = UtilSystem.ThreadPriority
Thread _workingThread
bool _isServerRunning = false
readonly object ServersLock = new object()
Lock that is usef for locking code that can be run from servers.
volatile int _outputLevel = ParallelJobContainerBase.DefaultOutputLevel
Output level for objects of this class.
bool _isTestMode = ParallelJobContainerBase.DefaultIsTestMode
int _sleepTimeMs = DefaultSleepTimeMs
int _numSentJobs = 0
Properties
int NumEnqueuedJobs [get]
Gets the number of enqueued jobs.
int NumJobServers [get]
number of job cervers that are currently asigned to hte dispatcher.
int NumActiveJobServers [get]
Gets number of active job servers assigned to the dispatcher.
int NumExecutingJobs [get]
Gets number of currently executing jobs.
bool CommandStopServing [get, protected set]
Flag indicating whether the server should be stopped. If set to true and server thread is runing, then the server thread stops when the currently run job completes (or stops immediately if there is no job running).
ThreadPriority ThreadPriority [get, set]
Priority of the dispatcher and contained server threads.
object Lock [get]
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
static int DefaultOutputLevel [get, set]
Default output level for objects of this and derived types.
int OutputLevel [get, set]
Output level the current object.
static bool DefaultIsTestMode [get, set]
Default value of test mode flag.
bool IsTestMode [get, set]
Whether the current job data conntainer is in test mode. In this mode, delays specified by internal variables are automatically added in job execution.
int Id [get]
Unique ID for objects of the currnet and derived classes.
static int DefaultSleepTimeMs [get, set]
Default sleeping time, in milliseconds, used by parallel job data objects when waiting for fulfillment of some condition in a loop that includes sleeping when condition is not met.
int SleepTimeMs [get, set]
Sleeping time, in milliseconds, used by the current object when waiting for fulfillment of some condition in a loop that includes sleeping when condition is not met.
int NumIdleJobServers [get]
Gets the number of idle job servers that are currently available on the dispatcher.
int NumSentJobs [get]
Gets the number of sent jobs (all jobs sent to the current dispatcher for execution).
int NumStartedJobs [get]
Gets the number of jobs started by the dispatcher up to this point.
int NumFinishedJobs [get]
Gets the number of finished jobs (of those handled by the current dispatcher) up to this point.
int NumAbortedJobs [get]
Gets the number of aborted jobs (of those handled by the current dispatcher) up to this point.
int NumUncompletedJobs [get]
Gets the number of idle job runners that are currently available on the dispatcher.
Properties inherited from IG.Lib.ILockable
object Lock [get]
Properties inherited from IG.Lib.IIdentifiable
int Id [get]
Returns unique ID (in the scope of a given type) of the current object.
Private Attributes
readonly object _mainLock = new object()
int _id = GetNextId()
int _nextJobId = 0
int _numIdleJobServers = 0
int _numStartedJobs = 0
int _numFinishedJobs = 0
int _numAbortedJobs = 0
Static Private Attributes
static int _nextId = 0
static int _defaultSleepTimeMs = 2
Detailed Description
Parallel job dispatcher. Accepts job requests and dispatches jobs to parallel job servers when available and redy to run a job.
Base class for parallel job dispatchers. Accepts job requests and dispatches jobs to parallel job servers when available and redy to run a job.
Template Parameters
JobContainerType Type of the container that holds data for the job (input and output).
This dispatcher object contains a list of parallel server objects (ParallelJobServerBase and its subclasses), and sends requested jobs to these objects.
If a job is requested and no servers are in idle state, the job is enqueued and waits for execution until a server becomes available.
Notes for developers:
Dispatcher should be steer synchronization with servers.
In order to avoid deadlocks, server may not call any dispatcher's code its own lock! All dispatcher's code must be called out out of code blocks locked on server's lock.
History note:
This implementation has been transfered in June 2012 from the IOptLib.Net library and adapted to current needs in IGLib. Some features were omitted and some implementatinon details changed. Implementations will be unified in the future, therefore the class may be subject to larger changes. What is currently exposed should remain more or less the same, so users of the class should not be affected.
$A Igor Aug08 Jun12;
Template Parameters
DataContainerType Type of the container that holds data for the job (input and output).
A non-generic class is defined in order to be used in the job data container class (ParallelJobContainerBase).
$A Igor Aug08;
Type Constraints
JobContainerType : ParallelJobContainerBase
Definition at line 39 of file ParallerJobDispatcherBase.cs.
Constructor & Destructor Documentation
ParallelJobDispatcherBase()
IG.Num.ParallelJobDispatcherBase< JobContainerType >.ParallelJobDispatcherBase () inline
Definition at line 45 of file ParallerJobDispatcherBase.cs.
References IG.Num.ParallelJobDispatcherBase< JobContainerType >.StartServer().
Member Function Documentation
AddServer()
void IG.Num.ParallelJobDispatcherBase< JobContainerType >.AddServer (ParallelJobServerBase< JobContainerType > server) inline
Adds the specified server to the current dispatcher.
Parameters
server Server to be added.
Definition at line 72 of file ParallerJobDispatcherBase.cs.
References IG.Num.ParallelJobDispatcherBase< JobContainerType >._jobServers, IG.Num.ParallelJobDispatcherBase< JobContainerType >._outputLevel, IG.Num.ParallelJobDispatcherBase< JobContainerType >.AddIdleServer(), IG.Num.ParallelJobServerBase< JobContainerType >.Dispatcher, IG.Num.ParallelJobServerBase< JobContainerType >.Id, IG.Num.ParallelJobDispatcherBase< JobContainerType >.Id, IG.Num.ParallelJobServerBase< JobContainerType >.IsIdle, and IG.Num.ParallelJobDispatcherBase< JobContainerType >.Lock.
RemoveServer()
void IG.Num.ParallelJobDispatcherBase< JobContainerType >.RemoveServer (ParallelJobServerBase< JobContainerType > server) inline
Removes the specified server to the current dispatcher.
Parameters
server Server to be removed.
Definition at line 97 of file ParallerJobDispatcherBase.cs.
References IG.Num.ParallelJobDispatcherBase< JobContainerType >._jobServers, IG.Num.ParallelJobDispatcherBase< JobContainerType >._outputLevel, IG.Num.ParallelJobServerBase< JobContainerType >.Dispatcher, IG.Num.ParallelJobServerBase< JobContainerType >.Id, IG.Num.ParallelJobDispatcherBase< JobContainerType >.Id, IG.Num.ParallelJobServerBase< JobContainerType >.Lock, IG.Num.ParallelJobDispatcherBase< JobContainerType >.Lock, and IG.Num.ParallelJobDispatcherBase< JobContainerType >.RemoveIdleServer().
AddIdleServer()
void IG.Num.ParallelJobDispatcherBase< JobContainerType >.AddIdleServer (ParallelJobServerBase< JobContainerType > server) inline protected
Adds the specified parallel job server to the idle list.
Parameters
server Server to be added to the list.
Definition at line 126 of file ParallerJobDispatcherBase.cs.
References IG.Num.ParallelJobDispatcherBase< JobContainerType >._idleJobServers, and IG.Num.ParallelJobDispatcherBase< JobContainerType >.ServersLock.
Referenced by IG.Num.ParallelJobDispatcherBase< JobContainerType >.AddServer(), and IG.Num.ParallelJobDispatcherBase< JobContainerType >.GetFirstIdleServer().
RemoveIdleServer()
void IG.Num.ParallelJobDispatcherBase< JobContainerType >.RemoveIdleServer (ParallelJobServerBase< JobContainerType > server) inline protected
Removes the specified parallel job server from the idle list.
If the specified server is not on the list then nothing happens.
Parameters
server Server to be removed from the list.
Definition at line 141 of file ParallerJobDispatcherBase.cs.
References IG.Num.ParallelJobDispatcherBase< JobContainerType >._idleJobServers, and IG.Num.ParallelJobDispatcherBase< JobContainerType >.ServersLock.
Referenced by IG.Num.ParallelJobDispatcherBase< JobContainerType >.RemoveServer().
SetServersSleepTimeMs()
void IG.Num.ParallelJobDispatcherBase< JobContainerType >.SetServersSleepTimeMs (int sleepTimeMs) inline
Sets sleeping time in milliseconds on all servers assigned to the current parallel job dispatcher.
Parameters
sleepTimeMs The sleeping time in milliseconds to be set on servers.
Definition at line 157 of file ParallerJobDispatcherBase.cs.
References IG.Num.ParallelJobDispatcherBase< JobContainerType >._jobServers, IG.Num.ParallelJobDispatcherBase< JobContainerType >.Id, IG.Num.ParallelJobDispatcherBase< JobContainerType >.Lock, and IG.Num.ParallelJobServerBase< JobContainerType >.SleepTimeMs.
SetServersOutputLevel()
void IG.Num.ParallelJobDispatcherBase< JobContainerType >.SetServersOutputLevel (int outputLevel) inline
Sets output level on all servers assigned to the current parallel job dispatcher.
Parameters
outputLevel The output level to be set on servers.
Definition at line 180 of file ParallerJobDispatcherBase.cs.
References IG.Num.ParallelJobDispatcherBase< JobContainerType >._jobServers, IG.Num.ParallelJobDispatcherBase< JobContainerType >.Id, IG.Num.ParallelJobDispatcherBase< JobContainerType >.Lock, and IG.Num.ParallelJobServerBase< JobContainerType >.OutputLevel.
SetServersIsServer()
void IG.Num.ParallelJobDispatcherBase< JobContainerType >.SetServersIsServer (bool isServer) inline
Sets the server flag on all servers assigned to the current parallel job dispatcher.
Parameters
isServer The server flag value to be set on servers.
Specified whether the server acts as server (true) or runs every job in a new thread.
Definition at line 204 of file ParallerJobDispatcherBase.cs.
References IG.Num.ParallelJobDispatcherBase< JobContainerType >._jobServers, IG.Num.ParallelJobDispatcherBase< JobContainerType >.Id, IG.Num.ParallelJobServerBase< JobContainerType >.IsServer, and IG.Num.ParallelJobDispatcherBase< JobContainerType >.Lock.
GetFirstIdleServer()
ParallelJobServerBase<JobContainerType> IG.Num.ParallelJobDispatcherBase< JobContainerType >.GetFirstIdleServer () inline protected
Returns the first idle server (last on the list of idle servers) and removes it from the idle servers list, or returns null if there are no idle servers.
Returns
The first idle job server available.
Definition at line 285 of file ParallerJobDispatcherBase.cs.
References IG.Num.ParallelJobDispatcherBase< JobContainerType >._idleJobServers, IG.Num.ParallelJobDispatcherBase< JobContainerType >._jobServers, IG.Num.ParallelJobDispatcherBase< JobContainerType >._outputLevel, IG.Num.ParallelJobDispatcherBase< JobContainerType >.AddIdleServer(), IG.Num.ParallelJobServerBase< JobContainerType >.Id, IG.Num.ParallelJobDispatcherBase< JobContainerType >.Id, IG.Num.ParallelJobServerBase< JobContainerType >.IsIdle, IG.Num.ParallelJobDispatcherBase< JobContainerType >.Lock, IG.Num.ParallelJobDispatcherBase< JobContainerType >.NumIdleJobServers, IG.Num.ParallelJobDispatcherBase< JobContainerType >.ResetNumIdleJobServers(), and IG.Num.ParallelJobDispatcherBase< JobContainerType >.ServersLock.
Referenced by IG.Num.ParallelJobDispatcherBase< JobContainerType >.Serve().
EnqueueJob()
void IG.Num.ParallelJobDispatcherBase< JobContainerType >.EnqueueJob (JobContainerType jobData) inline protected
Adds the specified job container to the execution queue.
Parameters
jobData Job container of the job that is enqueued.
Definition at line 358 of file ParallerJobDispatcherBase.cs.
References IG.Num.ParallelJobDispatcherBase< JobContainerType >._jobQueue.
Referenced by IG.Num.ParallelJobDispatcherBase< JobContainerType >.SendJob().
DequeueJob()
JobContainerType IG.Num.ParallelJobDispatcherBase< JobContainerType >.DequeueJob () inline protected
Removes the last job from the execution queue and returns it, or returns null if there are no jobs on the queue.
Parameters
jobData Job container of the job that is removed from the queue, or null if there are no jobs in the queue.
Definition at line 369 of file ParallerJobDispatcherBase.cs.
References IG.Num.ParallelJobDispatcherBase< JobContainerType >._jobQueue.
SendJob() [1/2]
bool IG.Num.ParallelJobDispatcherBase< JobContainerType >.SendJob (JobContainerType jobData) inline
Enqueues job for execution, and returns a flag indicating whether a job has been started immediately.
Parameters
jobData Job data.
Definition at line 382 of file ParallerJobDispatcherBase.cs.
SendJob() [2/2]
void IG.Num.ParallelJobDispatcherBase< JobContainerType >.SendJob (JobContainerType jobData, out bool startedImmediately) inline
Enqueues job for execution.
Parameters
jobData Job data.
startedImmediately Output flag, set to true if the job has been started by some server immediately, false othwrwise.
Definition at line 393 of file ParallerJobDispatcherBase.cs.
References IG.Num.ParallelJobDispatcherBase< JobContainerType >._isServerRunning, IG.Num.ParallelJobDispatcherBase< JobContainerType >._outputLevel, IG.Num.ParallelJobDispatcherBase< JobContainerType >.EnqueueJob(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.Id, IG.Num.ParallelJobDispatcherBase< JobContainerType >.IncrementNumSentJobs(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.Lock, and IG.Num.ParallelJobDispatcherBase< JobContainerType >.StartServer().
WaitAllJobsCompleted() [1/2]
void IG.Num.ParallelJobDispatcherBase< JobContainerType >.WaitAllJobsCompleted () inline
Waits for job completion.
Definition at line 444 of file ParallerJobDispatcherBase.cs.
Referenced by IG.Num.ParallelJobDispatcherBase< JobContainerType >.StopServerWhenAllJobsDone().
WaitAllJobsCompleted() [2/2]
bool IG.Num.ParallelJobDispatcherBase< JobContainerType >.WaitAllJobsCompleted (double timeoutInSeconds) inline
Wait until all jobs that weer sent to the current dispatcher object complete, or timeout occurs (timeout specified in seconds), and returns a flag indicating whether the jobs have actually completed (i.e. stop was not due to timeout).
Parameters
timeoutInSeconds Timeot in seconds. Less or equal to 0 means no timeout (waiting for condition fulfilled indefinitely).
Returns
A flag indicating whether the job was actually completed when the function returned. If false is returned then timeout occurred.
Definition at line 456 of file ParallerJobDispatcherBase.cs.
References IG.Num.ParallelJobDispatcherBase< JobContainerType >._outputLevel, IG.Num.ParallelJobDispatcherBase< JobContainerType >.Id, IG.Num.ParallelJobDispatcherBase< JobContainerType >.NumUncompletedJobs, IG.Num.ParallelJobDispatcherBase< JobContainerType >.OutputLevel, and IG.Num.ParallelJobDispatcherBase< JobContainerType >.SleepTimeMs.
StopServer()
void IG.Num.ParallelJobDispatcherBase< JobContainerType >.StopServer () inline
Sends to the server thread command that it has to stop.
If new jobs are sent after the server has been stopped, the server is restarted automatically.
Definition at line 516 of file ParallerJobDispatcherBase.cs.
References IG.Num.ParallelJobDispatcherBase< JobContainerType >.CommandStopServing.
StopServerWhenAllJobsDone() [1/2]
bool IG.Num.ParallelJobDispatcherBase< JobContainerType >.StopServerWhenAllJobsDone () inline
Waits until all jobs are completed, and then stops the server.
If new jobs are sent after the server has been stopped, the server is restarted automatically.
Definition at line 525 of file ParallerJobDispatcherBase.cs.
StopServerWhenAllJobsDone() [2/2]
bool IG.Num.ParallelJobDispatcherBase< JobContainerType >.StopServerWhenAllJobsDone (double timeoutInSeconds) inline
Waits until all jobs are completed or timeout occurs, and then stops the server. Returns a flag indicating whether all jobs are actually completed before server was ordered to stop.
Parameters
timeoutInSeconds Timeot in seconds. Less or equal to 0 means no timeout defined (waiting for condition fulfilled indefinitely).
If new jobs are sent after the server has been stopped, the server is restarted automatically.
Definition at line 537 of file ParallerJobDispatcherBase.cs.
References IG.Num.ParallelJobDispatcherBase< JobContainerType >.CommandStopServing, and IG.Num.ParallelJobDispatcherBase< JobContainerType >.WaitAllJobsCompleted().
KillDispatcherThread()
void IG.Num.ParallelJobDispatcherBase< JobContainerType >.KillDispatcherThread () inline
Forces the working thread to stop. To let the working thread finish its current jobs and then stop, call StopServer
Definition at line 547 of file ParallerJobDispatcherBase.cs.
References IG.Num.ParallelJobDispatcherBase< JobContainerType >._workingThread, and IG.Num.ParallelJobDispatcherBase< JobContainerType >.Lock.
Referenced by IG.Num.ParallelJobDispatcherBase< JobContainerType >.KillThreads().
KillServerThreads()
void IG.Num.ParallelJobDispatcherBase< JobContainerType >.KillServerThreads () inline
Forces all the server threads to stop, even if in the middle of eecution of a job. To let the working thread finish its current jobs and then stop, call StopServer
Definition at line 576 of file ParallerJobDispatcherBase.cs.
References IG.Num.ParallelJobDispatcherBase< JobContainerType >._jobServers, IG.Num.ParallelJobServerBase< JobContainerType >.KillServerThread(), and IG.Num.ParallelJobDispatcherBase< JobContainerType >.Lock.
Referenced by IG.Num.ParallelJobDispatcherBase< JobContainerType >.KillThreads().
KillThreads()
void IG.Num.ParallelJobDispatcherBase< JobContainerType >.KillThreads () inline
Forces all the server threads to stop, even if in the middle of eecution of a job. To let the working thread finish its current jobs and then stop, call StopServer
Definition at line 594 of file ParallerJobDispatcherBase.cs.
References IG.Num.ParallelJobDispatcherBase< JobContainerType >.KillDispatcherThread(), and IG.Num.ParallelJobDispatcherBase< JobContainerType >.KillServerThreads().
UpdateThreadPriorityFromSystem()
virtual void IG.Num.ParallelJobDispatcherBase< JobContainerType >.UpdateThreadPriorityFromSystem () inline protected virtual
Updates thread priority (property ThreadPriority) to the current global thread priority (the UtilSystem.ThreadPriority property).
Definition at line 603 of file ParallerJobDispatcherBase.cs.
References IG.Num.ParallelJobDispatcherBase< JobContainerType >.ThreadPriority, and IG.Lib.UtilSystem.ThreadPriority.
Referenced by IG.Num.ParallelJobDispatcherBase< JobContainerType >.RegisterSystemPriorityUpdating(), and IG.Num.ParallelJobDispatcherBase< JobContainerType >.UnregisterSystemPriorityUpdating().
RegisterSystemPriorityUpdating()
void IG.Num.ParallelJobDispatcherBase< JobContainerType >.RegisterSystemPriorityUpdating () inline
Registers the UpdateThreadPriorityFromSystem method as "event handler" for system priority changes. After registration, this method will be called every time the value of the UtilSystem.ThreadPriority property changes.
Definition at line 614 of file ParallerJobDispatcherBase.cs.
References IG.Num.ParallelJobDispatcherBase< JobContainerType >._systemPriorityUpdatesRegistered, IG.Lib.UtilSystem.AddOnThreadPriorityChange(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.Lock, and IG.Num.ParallelJobDispatcherBase< JobContainerType >.UpdateThreadPriorityFromSystem().
UnregisterSystemPriorityUpdating()
void IG.Num.ParallelJobDispatcherBase< JobContainerType >.UnregisterSystemPriorityUpdating () inline
Unregisters the UpdateThreadPriorityFromSystem method as "event handler" for system priority changes.
See also
RegisterSystemPriorityUpdating
Definition at line 635 of file ParallerJobDispatcherBase.cs.
References IG.Num.ParallelJobDispatcherBase< JobContainerType >._systemPriorityUpdatesRegistered, IG.Num.ParallelJobDispatcherBase< JobContainerType >.Lock, IG.Lib.UtilSystem.RemoveOnThreadPriorityChange(), and IG.Num.ParallelJobDispatcherBase< JobContainerType >.UpdateThreadPriorityFromSystem().
Serve()
void IG.Num.ParallelJobDispatcherBase< JobContainerType >.Serve () inline protected
Method executed in the queue server thread. Excecutes eventual enqueued jobs as job servers become idle.
Definition at line 694 of file ParallerJobDispatcherBase.cs.
References IG.Num.ParallelJobDispatcherBase< JobContainerType >._isServerRunning, IG.Num.ParallelJobDispatcherBase< JobContainerType >._jobQueue, IG.Num.ParallelJobDispatcherBase< JobContainerType >._outputLevel, IG.Num.ParallelJobDispatcherBase< JobContainerType >._workingThread, IG.Num.ParallelJobDispatcherBase< JobContainerType >.CommandStopServing, IG.Num.ParallelJobDispatcherBase< JobContainerType >.GetFirstIdleServer(), IG.Num.ParallelJobServerBase< JobContainerType >.Id, IG.Num.ParallelJobDispatcherBase< JobContainerType >.Id, IG.Num.ParallelJobDispatcherBase< JobContainerType >.Lock, IG.Num.ParallelJobDispatcherBase< JobContainerType >.SleepTimeMs, and IG.Num.ParallelJobServerBase< JobContainerType >.StartJob().
Referenced by IG.Num.ParallelJobDispatcherBase< JobContainerType >.StartServer().
StartServer()
void IG.Num.ParallelJobDispatcherBase< JobContainerType >.StartServer () inline
Starts the queue server.
Definition at line 782 of file ParallerJobDispatcherBase.cs.
References IG.Num.ParallelJobDispatcherBase< JobContainerType >._isServerRunning, IG.Num.ParallelJobDispatcherBase< JobContainerType >._outputLevel, IG.Num.ParallelJobDispatcherBase< JobContainerType >._workingThread, IG.Num.ParallelJobDispatcherBase< JobContainerType >.Id, IG.Num.ParallelJobDispatcherBase< JobContainerType >.Lock, IG.Num.ParallelJobDispatcherBase< JobContainerType >.Serve(), and IG.Num.ParallelJobDispatcherBase< JobContainerType >.ThreadPriority.
Referenced by IG.Num.ParallelJobDispatcherBase< JobContainerType >.ParallelJobDispatcherBase(), and IG.Num.ParallelJobDispatcherBase< JobContainerType >.SendJob().
NotifyJobStarted()
void IG.Num.ParallelJobDispatcherBase< JobContainerType >.NotifyJobStarted (ParallelJobServerBase< JobContainerType > server, JobContainerType job) inline
Notifies the current dispatched that the specified job has started on the specified server.
Parameters
server Server to which the job is assigned.
job The job in question.
This functionality is currently not implemented and is prepared in advanced e.g. for the ability of pulsing.
Definition at line 811 of file ParallerJobDispatcherBase.cs.
References IG.Num.ParallelJobDispatcherBase< JobContainerType >._outputLevel, IG.Num.ParallelJobDispatcherBase< JobContainerType >.Id, and IG.Num.ParallelJobDispatcherBase< JobContainerType >.IncrementNumStartedJobs().
Referenced by IG.Num.ParallelJobServerBase< JobContainerType >.NotifyJobStarted().
NotifyJobFinished()
void IG.Num.ParallelJobDispatcherBase< JobContainerType >.NotifyJobFinished (ParallelJobServerBase< JobContainerType > server, JobContainerType job) inline
Notifies the current dispatched that the specified job has started on the specified server.
Parameters
server Server to which the job is assigned.
job The job in question.
This functionality is currently not implemented and is prepared in advanced e.g. for the ability of pulsing.
Definition at line 827 of file ParallerJobDispatcherBase.cs.
References IG.Num.ParallelJobDispatcherBase< JobContainerType >._outputLevel, IG.Num.ParallelJobDispatcherBase< JobContainerType >.Id, and IG.Num.ParallelJobDispatcherBase< JobContainerType >.IncrementNumFinishedJobs().
NotifyJobAborted()
void IG.Num.ParallelJobDispatcherBase< JobContainerType >.NotifyJobAborted (ParallelJobServerBase< JobContainerType > server, JobContainerType job) inline
Notifies the current dispatched that the specified job has started on the specified server.
Parameters
server Server to which the job is assigned.
job The job in question.
This functionality is currently not implemented and is prepared in advanced e.g. for the ability of pulsing.
Definition at line 842 of file ParallerJobDispatcherBase.cs.
References IG.Num.ParallelJobDispatcherBase< JobContainerType >._outputLevel, IG.Num.ParallelJobDispatcherBase< JobContainerType >.Id, and IG.Num.ParallelJobDispatcherBase< JobContainerType >.IncrementNumAbortedJobs().
NotifyServerIdle()
void IG.Num.ParallelJobDispatcherBase< JobContainerType >.NotifyServerIdle (ParallelJobServerBase< JobContainerType > server) inline
Notifies the current parallel job dispatcher that the specified server has become idle.
This increases the number of idle servers and puts the server to the list of idle serves.
When an idle server is requested, it is still checked on the server whether it is actually idle or not.
Parameters
server Server that has become idle.
Definition at line 856 of file ParallerJobDispatcherBase.cs.
References IG.Num.ParallelJobDispatcherBase< JobContainerType >._idleJobServers, IG.Num.ParallelJobDispatcherBase< JobContainerType >._outputLevel, IG.Num.ParallelJobServerBase< JobContainerType >.Id, IG.Num.ParallelJobDispatcherBase< JobContainerType >.Id, and IG.Num.ParallelJobDispatcherBase< JobContainerType >.ServersLock.
Referenced by IG.Num.ParallelJobServerBase< JobContainerType >.NotifyServerIdle().
ToString()
override string IG.Num.ParallelJobDispatcherBase< JobContainerType >.ToString () inline
Returns a string representation of the current job dispatcher, which contains relevent data about the server state.
Definition at line 909 of file ParallerJobDispatcherBase.cs.
References IG.Num.ParallelJobDispatcherBase< JobContainerType >._isServerRunning, IG.Num.ParallelJobDispatcherBase< JobContainerType >._jobServers, IG.Num.ParallelJobDispatcherBase< JobContainerType >._workingThread, IG.Num.ParallelJobServerBase< JobContainerType >.Id, IG.Num.ParallelJobDispatcherBase< JobContainerType >.Id, IG.Num.ParallelJobDispatcherBase< JobContainerType >.Lock, IG.Num.ParallelJobDispatcherBase< JobContainerType >.NumAbortedJobs, IG.Num.ParallelJobDispatcherBase< JobContainerType >.NumActiveJobServers, IG.Num.ParallelJobDispatcherBase< JobContainerType >.NumEnqueuedJobs, IG.Num.ParallelJobDispatcherBase< JobContainerType >.NumExecutingJobs, IG.Num.ParallelJobDispatcherBase< JobContainerType >.NumFinishedJobs, IG.Num.ParallelJobDispatcherBase< JobContainerType >.NumIdleJobServers, IG.Num.ParallelJobDispatcherBase< JobContainerType >.NumJobServers, IG.Num.ParallelJobDispatcherBase< JobContainerType >.NumSentJobs, IG.Num.ParallelJobDispatcherBase< JobContainerType >.NumStartedJobs, IG.Num.ParallelJobDispatcherBase< JobContainerType >.NumUncompletedJobs, IG.Num.ParallelJobDispatcherBase< JobContainerType >.OutputLevel, and IG.Num.ParallelJobServerBase< JobContainerType >.ToString().
GetNextId()
static int IG.Num.ParallelJobDispatcherBase< JobContainerType >.GetNextId () inline static protected
Returns another ID that is unique for objects of the containing class its and derived classes.
Definition at line 1061 of file ParallerJobDispatcherBase.cs.
References IG.Num.ParallelJobDispatcherBase< JobContainerType >._nextId, and IG.Num.ParallelJobContainerBase.LockId.
ResetNumIdleJobServers()
void IG.Num.ParallelJobDispatcherBase< JobContainerType >.ResetNumIdleJobServers () inline protected
Resets number of idle job servers to 0.
Definition at line 1123 of file ParallerJobDispatcherBase.cs.
References IG.Num.ParallelJobDispatcherBase< JobContainerType >._numIdleJobServers, and IG.Num.ParallelJobDispatcherBase< JobContainerType >.ServersLock.
Referenced by IG.Num.ParallelJobDispatcherBase< JobContainerType >.GetFirstIdleServer().
IncrementNumSentJobs()
void IG.Num.ParallelJobDispatcherBase< JobContainerType >.IncrementNumSentJobs () inline
Increments by one the number of sent jobs (all jobs sent to the current dispatcher for execution).
Definition at line 1159 of file ParallerJobDispatcherBase.cs.
References IG.Num.ParallelJobDispatcherBase< JobContainerType >._numSentJobs, and IG.Num.ParallelJobDispatcherBase< JobContainerType >.Lock.
Referenced by IG.Num.ParallelJobDispatcherBase< JobContainerType >.SendJob().
IncrementNumStartedJobs()
void IG.Num.ParallelJobDispatcherBase< JobContainerType >.IncrementNumStartedJobs () inline
Increments by one the number of started by the dispatcher up to this point.
Definition at line 1176 of file ParallerJobDispatcherBase.cs.
References IG.Num.ParallelJobDispatcherBase< JobContainerType >._numStartedJobs, and IG.Num.ParallelJobDispatcherBase< JobContainerType >.ServersLock.
Referenced by IG.Num.ParallelJobDispatcherBase< JobContainerType >.NotifyJobStarted().
IncrementNumFinishedJobs()
void IG.Num.ParallelJobDispatcherBase< JobContainerType >.IncrementNumFinishedJobs () inline
Increments by one the number of finished jobs (of those handled by the current dispatcher) up to this point.
Definition at line 1194 of file ParallerJobDispatcherBase.cs.
References IG.Num.ParallelJobDispatcherBase< JobContainerType >._numFinishedJobs, and IG.Num.ParallelJobDispatcherBase< JobContainerType >.ServersLock.
Referenced by IG.Num.ParallelJobDispatcherBase< JobContainerType >.NotifyJobFinished().
IncrementNumAbortedJobs()
void IG.Num.ParallelJobDispatcherBase< JobContainerType >.IncrementNumAbortedJobs () inline
Increments by one the number of aborted jobs (of those handled by the current dispatcher) up to this point.
Definition at line 1211 of file ParallerJobDispatcherBase.cs.
References IG.Num.ParallelJobDispatcherBase< JobContainerType >._numAbortedJobs, and IG.Num.ParallelJobDispatcherBase< JobContainerType >.ServersLock.
Referenced by IG.Num.ParallelJobDispatcherBase< JobContainerType >.NotifyJobAborted().
Member Data Documentation
_jobServers
readonly List<ParallelJobServerBase<JobContainerType> > IG.Num.ParallelJobDispatcherBase< JobContainerType >._jobServers protected
Initial value:
=
            new List<ParallelJobServerBase<JobContainerType>>()
List of job servers contained by the current dispatcher.
Definition at line 62 of file ParallerJobDispatcherBase.cs.
Referenced by IG.Num.ParallelJobDispatcherBase< JobContainerType >.AddServer(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.GetFirstIdleServer(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.KillServerThreads(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.RemoveServer(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.SetServersIsServer(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.SetServersOutputLevel(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.SetServersSleepTimeMs(), and IG.Num.ParallelJobDispatcherBase< JobContainerType >.ToString().
_idleJobServers
readonly List<ParallelJobServerBase<JobContainerType> > IG.Num.ParallelJobDispatcherBase< JobContainerType >._idleJobServers protected
Initial value:
=
            new List<ParallelJobServerBase<JobContainerType>>()
List of idle job servers dispatched by teh current dispatcher.
Definition at line 66 of file ParallerJobDispatcherBase.cs.
Referenced by IG.Num.ParallelJobDispatcherBase< JobContainerType >.AddIdleServer(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.GetFirstIdleServer(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.NotifyServerIdle(), and IG.Num.ParallelJobDispatcherBase< JobContainerType >.RemoveIdleServer().
_jobQueue
Queue<JobContainerType> IG.Num.ParallelJobDispatcherBase< JobContainerType >._jobQueue = new Queue<JobContainerType>() protected
Queue of jobs that could not be immediately served, scheduled for later execution.
Definition at line 274 of file ParallerJobDispatcherBase.cs.
Referenced by IG.Num.ParallelJobDispatcherBase< JobContainerType >.DequeueJob(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.EnqueueJob(), and IG.Num.ParallelJobDispatcherBase< JobContainerType >.Serve().
_commandStopServing
bool IG.Num.ParallelJobDispatcherBase< JobContainerType >._commandStopServing = false protected
Definition at line 501 of file ParallerJobDispatcherBase.cs.
_systemPriorityUpdatesRegistered
bool IG.Num.ParallelJobDispatcherBase< JobContainerType >._systemPriorityUpdatesRegistered = false protected
Whether the "event" handler for system priprity changes has already been registered.
Definition at line 609 of file ParallerJobDispatcherBase.cs.
Referenced by IG.Num.ParallelJobDispatcherBase< JobContainerType >.RegisterSystemPriorityUpdating(), and IG.Num.ParallelJobDispatcherBase< JobContainerType >.UnregisterSystemPriorityUpdating().
_threadPriority
ThreadPriority IG.Num.ParallelJobDispatcherBase< JobContainerType >._threadPriority = UtilSystem.ThreadPriority protected
Definition at line 649 of file ParallerJobDispatcherBase.cs.
_workingThread
Thread IG.Num.ParallelJobDispatcherBase< JobContainerType >._workingThread protected
Definition at line 687 of file ParallerJobDispatcherBase.cs.
Referenced by IG.Num.ParallelJobDispatcherBase< JobContainerType >.KillDispatcherThread(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.Serve(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.StartServer(), and IG.Num.ParallelJobDispatcherBase< JobContainerType >.ToString().
_isServerRunning
bool IG.Num.ParallelJobDispatcherBase< JobContainerType >._isServerRunning = false protected
Definition at line 689 of file ParallerJobDispatcherBase.cs.
Referenced by IG.Num.ParallelJobDispatcherBase< JobContainerType >.SendJob(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.Serve(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.StartServer(), and IG.Num.ParallelJobDispatcherBase< JobContainerType >.ToString().
_mainLock
readonly object IG.Num.ParallelJobDispatcherBase< JobContainerType >._mainLock = new object() private
Definition at line 988 of file ParallerJobDispatcherBase.cs.
ServersLock
readonly object IG.Num.ParallelJobDispatcherBase< JobContainerType >.ServersLock = new object() protected
Lock that is usef for locking code that can be run from servers.
List of idle servers is locked by this lock, as well as various data that is accessed on job start, abort or finished events on servers, such as number of started jobs.
Definition at line 998 of file ParallerJobDispatcherBase.cs.
Referenced by IG.Num.ParallelJobDispatcherBase< JobContainerType >.AddIdleServer(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.GetFirstIdleServer(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.IncrementNumAbortedJobs(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.IncrementNumFinishedJobs(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.IncrementNumStartedJobs(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.NotifyServerIdle(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.RemoveIdleServer(), and IG.Num.ParallelJobDispatcherBase< JobContainerType >.ResetNumIdleJobServers().
_outputLevel
volatile int IG.Num.ParallelJobDispatcherBase< JobContainerType >._outputLevel = ParallelJobContainerBase.DefaultOutputLevel protected
Output level for objects of this class.
Specifies how much output is printed to console during operation.
Definition at line 1016 of file ParallerJobDispatcherBase.cs.
Referenced by IG.Num.ParallelJobDispatcherBase< JobContainerType >.AddServer(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.GetFirstIdleServer(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.NotifyJobAborted(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.NotifyJobFinished(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.NotifyJobStarted(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.NotifyServerIdle(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.RemoveServer(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.SendJob(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.Serve(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.StartServer(), and IG.Num.ParallelJobDispatcherBase< JobContainerType >.WaitAllJobsCompleted().
_isTestMode
bool IG.Num.ParallelJobDispatcherBase< JobContainerType >._isTestMode = ParallelJobContainerBase.DefaultIsTestMode protected
Definition at line 1034 of file ParallerJobDispatcherBase.cs.
_nextId
int IG.Num.ParallelJobDispatcherBase< JobContainerType >._nextId = 0 static private
Definition at line 1057 of file ParallerJobDispatcherBase.cs.
Referenced by IG.Num.ParallelJobDispatcherBase< JobContainerType >.GetNextId().
_id
int IG.Num.ParallelJobDispatcherBase< JobContainerType >._id = GetNextId() private
Definition at line 1070 of file ParallerJobDispatcherBase.cs.
_defaultSleepTimeMs
int IG.Num.ParallelJobDispatcherBase< JobContainerType >._defaultSleepTimeMs = 2 static private
Definition at line 1079 of file ParallerJobDispatcherBase.cs.
_sleepTimeMs
int IG.Num.ParallelJobDispatcherBase< JobContainerType >._sleepTimeMs = DefaultSleepTimeMs protected
Definition at line 1089 of file ParallerJobDispatcherBase.cs.
_nextJobId
int IG.Num.ParallelJobDispatcherBase< JobContainerType >._nextJobId = 0 private
Definition at line 1101 of file ParallerJobDispatcherBase.cs.
_numIdleJobServers
int IG.Num.ParallelJobDispatcherBase< JobContainerType >._numIdleJobServers = 0 private
Definition at line 1114 of file ParallerJobDispatcherBase.cs.
Referenced by IG.Num.ParallelJobDispatcherBase< JobContainerType >.ResetNumIdleJobServers().
_numSentJobs
int IG.Num.ParallelJobDispatcherBase< JobContainerType >._numSentJobs = 0 protected
Definition at line 1150 of file ParallerJobDispatcherBase.cs.
Referenced by IG.Num.ParallelJobDispatcherBase< JobContainerType >.IncrementNumSentJobs().
_numStartedJobs
int IG.Num.ParallelJobDispatcherBase< JobContainerType >._numStartedJobs = 0 private
Definition at line 1167 of file ParallerJobDispatcherBase.cs.
Referenced by IG.Num.ParallelJobDispatcherBase< JobContainerType >.IncrementNumStartedJobs().
_numFinishedJobs
int IG.Num.ParallelJobDispatcherBase< JobContainerType >._numFinishedJobs = 0 private
Definition at line 1185 of file ParallerJobDispatcherBase.cs.
Referenced by IG.Num.ParallelJobDispatcherBase< JobContainerType >.IncrementNumFinishedJobs().
_numAbortedJobs
int IG.Num.ParallelJobDispatcherBase< JobContainerType >._numAbortedJobs = 0 private
Definition at line 1202 of file ParallerJobDispatcherBase.cs.
Referenced by IG.Num.ParallelJobDispatcherBase< JobContainerType >.IncrementNumAbortedJobs().
Property Documentation
NumEnqueuedJobs
int IG.Num.ParallelJobDispatcherBase< JobContainerType >.NumEnqueuedJobs get
Gets the number of enqueued jobs.
Definition at line 57 of file ParallerJobDispatcherBase.cs.
Referenced by IG.Num.ParallelJobDispatcherBase< JobContainerType >.ToString().
NumJobServers
int IG.Num.ParallelJobDispatcherBase< JobContainerType >.NumJobServers get
number of job cervers that are currently asigned to hte dispatcher.
Definition at line 227 of file ParallerJobDispatcherBase.cs.
Referenced by IG.Num.ParallelJobDispatcherBase< JobContainerType >.ToString().
NumActiveJobServers
int IG.Num.ParallelJobDispatcherBase< JobContainerType >.NumActiveJobServers get
Gets number of active job servers assigned to the dispatcher.
These are servers capable of serving jobs, but which may be busy at the moment.
Definition at line 232 of file ParallerJobDispatcherBase.cs.
Referenced by IG.Num.ParallelJobDispatcherBase< JobContainerType >.ToString().
NumExecutingJobs
int IG.Num.ParallelJobDispatcherBase< JobContainerType >.NumExecutingJobs get
Gets number of currently executing jobs.
The number is obtained by counting assigned job servers that are in the state of job execution.
Definition at line 254 of file ParallerJobDispatcherBase.cs.
Referenced by IG.Num.ParallelJobDispatcherBase< JobContainerType >.ToString().
CommandStopServing
bool IG.Num.ParallelJobDispatcherBase< JobContainerType >.CommandStopServing get protected set
Flag indicating whether the server should be stopped. If set to true and server thread is runing, then the server thread stops when the currently run job completes (or stops immediately if there is no job running).
Definition at line 507 of file ParallerJobDispatcherBase.cs.
Referenced by IG.Num.ParallelJobDispatcherBase< JobContainerType >.Serve(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.StopServer(), and IG.Num.ParallelJobDispatcherBase< JobContainerType >.StopServerWhenAllJobsDone().
ThreadPriority
ThreadPriority IG.Num.ParallelJobDispatcherBase< JobContainerType >.ThreadPriority get set
Priority of the dispatcher and contained server threads.
Setting priority changes priority of the dispatcher thread and all server threads.
When threads are created, they will adopt the priority.
Definition at line 655 of file ParallerJobDispatcherBase.cs.
Referenced by IG.Num.ParallelJobDispatcherBase< JobContainerType >.StartServer(), and IG.Num.ParallelJobDispatcherBase< JobContainerType >.UpdateThreadPriorityFromSystem().
Lock
object IG.Num.ParallelJobDispatcherBase< JobContainerType >.Lock get
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
Definition at line 993 of file ParallerJobDispatcherBase.cs.
Referenced by IG.Num.ParallelJobDispatcherBase< JobContainerType >.AddServer(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.GetFirstIdleServer(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.IncrementNumSentJobs(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.KillDispatcherThread(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.KillServerThreads(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.RegisterSystemPriorityUpdating(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.RemoveServer(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.SendJob(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.Serve(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.SetServersIsServer(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.SetServersOutputLevel(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.SetServersSleepTimeMs(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.StartServer(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.ToString(), and IG.Num.ParallelJobDispatcherBase< JobContainerType >.UnregisterSystemPriorityUpdating().
DefaultOutputLevel
int IG.Num.ParallelJobDispatcherBase< JobContainerType >.DefaultOutputLevel static get set
Default output level for objects of this and derived types.
Just aliases the ParallelJobContainerBase.DefaultOutputLevel.
Definition at line 1009 of file ParallerJobDispatcherBase.cs.
OutputLevel
int IG.Num.ParallelJobDispatcherBase< JobContainerType >.OutputLevel get set
Output level the current object.
Specifies how much output is printed to console during operation.
Definition at line 1021 of file ParallerJobDispatcherBase.cs.
Referenced by IG.Num.ParallelJobDispatcherBase< JobContainerType >.ToString(), and IG.Num.ParallelJobDispatcherBase< JobContainerType >.WaitAllJobsCompleted().
DefaultIsTestMode
bool IG.Num.ParallelJobDispatcherBase< JobContainerType >.DefaultIsTestMode static get set
Default value of test mode flag.
Just aliases the ParallelJobContainerBase.DefaultOutputLevel.
Definition at line 1029 of file ParallerJobDispatcherBase.cs.
IsTestMode
bool IG.Num.ParallelJobDispatcherBase< JobContainerType >.IsTestMode get set
Whether the current job data conntainer is in test mode. In this mode, delays specified by internal variables are automatically added in job execution.
Definition at line 1039 of file ParallerJobDispatcherBase.cs.
Id
int IG.Num.ParallelJobDispatcherBase< JobContainerType >.Id get
Unique ID for objects of the currnet and derived classes.
Definition at line 1074 of file ParallerJobDispatcherBase.cs.
Referenced by IG.Num.ParallelJobDispatcherBase< JobContainerType >.AddServer(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.GetFirstIdleServer(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.NotifyJobAborted(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.NotifyJobFinished(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.NotifyJobStarted(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.NotifyServerIdle(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.RemoveServer(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.SendJob(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.Serve(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.SetServersIsServer(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.SetServersOutputLevel(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.SetServersSleepTimeMs(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.StartServer(), IG.Num.ParallelJobDispatcherBase< JobContainerType >.ToString(), and IG.Num.ParallelJobDispatcherBase< JobContainerType >.WaitAllJobsCompleted().
DefaultSleepTimeMs
int IG.Num.ParallelJobDispatcherBase< JobContainerType >.DefaultSleepTimeMs static get set
Default sleeping time, in milliseconds, used by parallel job data objects when waiting for fulfillment of some condition in a loop that includes sleeping when condition is not met.
Definition at line 1084 of file ParallerJobDispatcherBase.cs.
SleepTimeMs
int IG.Num.ParallelJobDispatcherBase< JobContainerType >.SleepTimeMs get set
Sleeping time, in milliseconds, used by the current object when waiting for fulfillment of some condition in a loop that includes sleeping when condition is not met.
DefaultSleepTimeMs specifies the default value that is set when object is created.
Definition at line 1095 of file ParallerJobDispatcherBase.cs.
Referenced by IG.Num.ParallelJobDispatcherBase< JobContainerType >.Serve(), and IG.Num.ParallelJobDispatcherBase< JobContainerType >.WaitAllJobsCompleted().
NumIdleJobServers
int IG.Num.ParallelJobDispatcherBase< JobContainerType >.NumIdleJobServers get
Gets the number of idle job servers that are currently available on the dispatcher.
Definition at line 1118 of file ParallerJobDispatcherBase.cs.
Referenced by IG.Num.ParallelJobDispatcherBase< JobContainerType >.GetFirstIdleServer(), and IG.Num.ParallelJobDispatcherBase< JobContainerType >.ToString().
NumSentJobs
int IG.Num.ParallelJobDispatcherBase< JobContainerType >.NumSentJobs get
Gets the number of sent jobs (all jobs sent to the current dispatcher for execution).
Definition at line 1154 of file ParallerJobDispatcherBase.cs.
Referenced by IG.Num.ParallelJobDispatcherBase< JobContainerType >.ToString().
NumStartedJobs
int IG.Num.ParallelJobDispatcherBase< JobContainerType >.NumStartedJobs get
Gets the number of jobs started by the dispatcher up to this point.
Definition at line 1171 of file ParallerJobDispatcherBase.cs.
Referenced by IG.Num.ParallelJobDispatcherBase< JobContainerType >.ToString().
NumFinishedJobs
int IG.Num.ParallelJobDispatcherBase< JobContainerType >.NumFinishedJobs get
Gets the number of finished jobs (of those handled by the current dispatcher) up to this point.
Definition at line 1189 of file ParallerJobDispatcherBase.cs.
Referenced by IG.Num.ParallelJobDispatcherBase< JobContainerType >.ToString().
NumAbortedJobs
int IG.Num.ParallelJobDispatcherBase< JobContainerType >.NumAbortedJobs get
Gets the number of aborted jobs (of those handled by the current dispatcher) up to this point.
Definition at line 1206 of file ParallerJobDispatcherBase.cs.
Referenced by IG.Num.ParallelJobDispatcherBase< JobContainerType >.ToString().
NumUncompletedJobs
int IG.Num.ParallelJobDispatcherBase< JobContainerType >.NumUncompletedJobs get
Gets the number of idle job runners that are currently available on the dispatcher.
Definition at line 1221 of file ParallerJobDispatcherBase.cs.
Referenced by IG.Num.ParallelJobDispatcherBase< JobContainerType >.ToString(), and IG.Num.ParallelJobDispatcherBase< JobContainerType >.WaitAllJobsCompleted().
The documentation for this class was generated from the following file:
iglib/igbase/numeric/parallel/ParallerJobDispatcherBase.cs