Doc: IGLib with source files: IGLib.Core.ToStringTypeConverterViaParseReflection Class Reference
IGLib.Core.ToStringTypeConverterViaParseReflection Class Reference
Converts a value to its string representation using invariant culture, only if it can be parsed back using TryParse or Parse methods.
Public Member Functions
string ConvertTyped< SourceType > (SourceType source)
bool TryConvertTyped< SourceType > (SourceType source, out string target)
object Convert (object source)
bool TryConvert (object source, out object target)
Public Member Functions inherited from IGLib.Core.ISingleTargetTypeConverter< string >
TargetType ConvertTyped< SourceType > (SourceType source)
bool TryConvertTyped< SourceType > (SourceType source, out TargetType target)
object Convert (object source)
bool TryConvert (object source, out object target)
Public Attributes
Type TargetType => typeof(string)
Private Member Functions
bool IsRoundTripConvertible (Type type)
Determines whether a type supports round-trip conversion using TryParse or Parse with InvariantCulture.
Additional Inherited Members
Properties inherited from IGLib.Core.ISingleTargetTypeConverter< string >
Type TargetType [get]
Detailed Description
Converts a value to its string representation using invariant culture, only if it can be parsed back using TryParse or Parse methods.
Definition at line 12 of file ToStringTypeConverterViaParseReflection.cs.
Member Function Documentation
ConvertTyped< SourceType >()
string IGLib.Core.ToStringTypeConverterViaParseReflection.ConvertTyped< SourceType > (SourceType source) inline
Definition at line 18 of file ToStringTypeConverterViaParseReflection.cs.
TryConvertTyped< SourceType >()
bool IGLib.Core.ToStringTypeConverterViaParseReflection.TryConvertTyped< SourceType > (SourceType source, out string target) inline
Definition at line 27 of file ToStringTypeConverterViaParseReflection.cs.
References IGLib.Core.ToStringTypeConverterViaParseReflection.IsRoundTripConvertible().
Convert()
object IGLib.Core.ToStringTypeConverterViaParseReflection.Convert (object source) inline
Definition at line 49 of file ToStringTypeConverterViaParseReflection.cs.
References IGLib.Core.ToStringTypeConverterViaParseReflection.TryConvert().
TryConvert()
bool IGLib.Core.ToStringTypeConverterViaParseReflection.TryConvert (object source, out object target) inline
Definition at line 58 of file ToStringTypeConverterViaParseReflection.cs.
References IGLib.Core.ToStringTypeConverterViaParseReflection.IsRoundTripConvertible().
Referenced by IGLib.Core.ToStringTypeConverterViaParseReflection.Convert().
IsRoundTripConvertible()
bool IGLib.Core.ToStringTypeConverterViaParseReflection.IsRoundTripConvertible (Type type) inline private
Determines whether a type supports round-trip conversion using TryParse or Parse with InvariantCulture.
Definition at line 88 of file ToStringTypeConverterViaParseReflection.cs.
Referenced by IGLib.Core.ToStringTypeConverterViaParseReflection.TryConvert(), and IGLib.Core.ToStringTypeConverterViaParseReflection.TryConvertTyped< SourceType >().
Member Data Documentation
TargetType
Type IGLib.Core.ToStringTypeConverterViaParseReflection.TargetType => typeof(string)
Definition at line 15 of file ToStringTypeConverterViaParseReflection.cs.
The documentation for this class was generated from the following file:
IGLibGraphics3D/src/IGLib.Graphics3D/other/TypeConversionExtended/SingleConverters/SpecificConverters/ToStringTypeConverterViaParseReflection.cs