Doc: IGLib with source files: IG.Num.SingularValueDecomposition Class Reference
IG.Num.SingularValueDecomposition Class Reference
Singular value decomposition of a matrix.
Public Member Functions
SingularValueDecomposition (Matrix_MathNetNumerics A)
Constructor.
SingularValueDecomposition (Matrix A)
Constructor.
void GetProduct (ref IMatrix product)
Calculates the product (i.e. the original matrix of coefficients of a linear system of equations) of the current decomposition, and stores it to the specified matrix.
IMatrix GetProduct ()
Calculates and returns the product (i.e. the original matrix of coefficients of a linear system of equations) of the current decomposition.
void Inverse (ref IMatrix inv)
Calculates inverse of the decomposed matrix represented by the current object, and stores it in the specified matrix.
IMatrix Inverse ()
Calculates and returns inverse of the decomposed matrix represented by the current object.
Public Member Functions inherited from IG.Num.LinearSolverBase
virtual void Solve (IMatrix B, ref IMatrix X)
Solves A*X = B (a set of linear systems of equations), where B is the matrix whose colums are right-hand sides of equations to be solved. Solutions are stored to the specified matrix.
IMatrix Solve (IMatrix B)
Solves A*X = B (a set of linear systems of equations), where B is the matrix whose colums are right-hand sides of equations to be solved, and returns a matrix whose columns are solutions of the specified systems of equations.
virtual void Solve (IVector b, ref IVector x)
Solves a system of linear equations A*x=b, and stores the solution in the specified vector.
IVector Solve (IVector b)
Solves a system of linear equations A*x=b, and returns the solution.
Public Member Functions inherited from IG.Num.ILinearSolver
void Solve (IMatrix B, ref IMatrix X)
Solves A*X = B (a set of linear systems of equations), where B is the matrix whose colums are right-hand sides of equations to be solved. Solutions are stored to the specified matrix.
IMatrix Solve (IMatrix B)
Solves A*X = B (a set of linear systems of equations), where B is the matrix whose colums are right-hand sides of equations to be solved, and returns a matrix whose columns are solutions of the specified systems of equations.
void Solve (IVector b, ref IVector x)
Solves a system of linear equations A*x=b, and stores the solution in the specified vector.
IVector Solve (IVector b)
Solves a system of linear equations A*x=b, and returns the solution.
Protected Member Functions
override MatrixBase_MathNetNumerics SolveMathNetNumerics (IMatrix righthandSides)
Solves systems of linear equations with the specified right-hand sides and the current matrix decomposition by using the Math.Net Numerics library, and returns the result in Math.Net matrix form.
override VectorBase_MathNetNumerics SolveMathNetNumerics (IVector rightHandSides)
Solves the system of linear equations with the specified right-hand sides and the current matrix decomposition by using the Math.Net Numerics library, and returns the result in Math.Net matrix form.
Protected Attributes
double _determinant
bool _determinantCalculated = false
Protected Attributes inherited from IG.Num.LinearSolverBase
MatrixBase_MathNetNumerics _matrixSolution_MathNetNumerics
Matrix_MathNetNumerics _matrixRighthandSides_MathNetNumerics
VectorBase_MathNetNumerics _vectorSolution_MathNetNumerics
Vector_MathNetNumerics _vectorRighthandSides_MathNetNumerics
IVector auxB = null
IVector auxX = null
Properties
bool IsNonSingular [get]
Indicates whether the matrix of coefficients of a linear system is nonsingular.
Matrix LeftSingularVectors [get]
Returns the left singular vectors.
Vector SingularValues [get]
Returns the singular values.
Matrix RightSingularVectors [get]
Returns the right singular vectors.
double Determinant [get]
Returns the determinant.
Properties inherited from IG.Num.LinearSolverBase
object Lock [get]
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
Properties inherited from IG.Num.ILinearSolver
bool IsNonSingular [get]
Indicates whether the matrix of coefficients of a linear system represented by the current decomposition object, is nonsingular.
Properties inherited from IG.Lib.ILockable
object Lock [get]
Private Attributes
MatrixBase_MathNetNumerics _inverse
Detailed Description
Singular value decomposition of a matrix.
Calculates eigenvectors and eigenvalues of a real matrix.
Objects of this class are immutable. Decomposition is calculated at initialization, and the decomposed matrix can not be replaced later.
Suppose M is an m-by-n matrix whose entries are real numbers. Then there exists a factorization of the form M = UΣVT where:
U is an m-by-m unitary matrix;
Σ is m-by-n diagonal matrix with nonnegative real numbers on the diagonal;
VT denotes transpose of V, an n-by-n unitary matrix; Such a factorization is called a singular-value decomposition of M. A common convention is to order the diagonal entries Σ(i,i) in descending order. In this case, the diagonal matrix Σ is uniquely determined by M (though the matrices U and V are not). The diagonal entries of Σ are known as the singular values of M.
$A Igor Feb09;
Definition at line 1410 of file MatrixDecompositions.cs.
Constructor & Destructor Documentation
SingularValueDecomposition() [1/2]
IG.Num.SingularValueDecomposition.SingularValueDecomposition (Matrix_MathNetNumerics A) inline
Constructor.
Parameters
A Matrix to be decomposed.
Definition at line 1422 of file MatrixDecompositions.cs.
References IG.Num.LinearSolverBase._columnCount, IG.Num.A, and IG.Lib.Base.
SingularValueDecomposition() [2/2]
IG.Num.SingularValueDecomposition.SingularValueDecomposition (Matrix A) inline
Constructor.
Parameters
A Matrix to be decomposed.
Definition at line 1435 of file MatrixDecompositions.cs.
References IG.Num.A.
Member Function Documentation
GetProduct() [1/2]
void IG.Num.SingularValueDecomposition.GetProduct (ref IMatrix product) inline
Calculates the product (i.e. the original matrix of coefficients of a linear system of equations) of the current decomposition, and stores it to the specified matrix.
Parameters
product Matrix where re-calculated product of the decomposed matrix is stored.
Implements IG.Num.ILinearSolver.
Definition at line 1496 of file MatrixDecompositions.cs.
References IG.Lib.Base, and IG.Num.Matrix.Copy().
GetProduct() [2/2]
IMatrix IG.Num.SingularValueDecomposition.GetProduct () inline
Calculates and returns the product (i.e. the original matrix of coefficients of a linear system of equations) of the current decomposition.
Implements IG.Num.ILinearSolver.
Definition at line 1504 of file MatrixDecompositions.cs.
Inverse() [1/2]
void IG.Num.SingularValueDecomposition.Inverse (ref IMatrix inv) inline
Calculates inverse of the decomposed matrix represented by the current object, and stores it in the specified matrix.
Parameters
inv Matrix where calculated inverse is stored.
Implements IG.Num.ILinearSolver.
Definition at line 1541 of file MatrixDecompositions.cs.
References IG.Num.LinearSolverBase._columnCount, IG.Num.SingularValueDecomposition._inverse, IG.Lib.Base, IG.Num.Matrix.Copy(), and IG.Lib.ILockable.Lock.
Inverse() [2/2]
IMatrix IG.Num.SingularValueDecomposition.Inverse () inline
Calculates and returns inverse of the decomposed matrix represented by the current object.
Implements IG.Num.ILinearSolver.
Definition at line 1568 of file MatrixDecompositions.cs.
SolveMathNetNumerics() [1/2]
override MatrixBase_MathNetNumerics IG.Num.SingularValueDecomposition.SolveMathNetNumerics (IMatrix righthandSides) inline protected virtual
Solves systems of linear equations with the specified right-hand sides and the current matrix decomposition by using the Math.Net Numerics library, and returns the result in Math.Net matrix form.
Parameters
righthandSides Matrix that contains right-hand sides of the linear equations to be solved as its columns.
Returns
The Math.Net Numerics matrix whose columns contains solutions to the systems of linear equations whose right-hand sides are specified by yhe righthandSides parameter.
Reimplemented from IG.Num.LinearSolverBase.
Definition at line 1582 of file MatrixDecompositions.cs.
References IG.Num.LinearSolverBase._matrixRighthandSides_MathNetNumerics, IG.Num.LinearSolverBase._matrixSolution_MathNetNumerics, IG.Lib.Base, IG.Num.IMatrix< ComponentType >.ColumnCount, IG.Num.Matrix.Copy(), IG.Lib.ILockable.Lock, and IG.Num.IMatrix< ComponentType >.RowCount.
SolveMathNetNumerics() [2/2]
override VectorBase_MathNetNumerics IG.Num.SingularValueDecomposition.SolveMathNetNumerics (IVector rightHandSides) inline protected virtual
Solves the system of linear equations with the specified right-hand sides and the current matrix decomposition by using the Math.Net Numerics library, and returns the result in Math.Net matrix form.
Parameters
rightHandSides Vector of right-hand sides of the linear equations to be solved.
Returns
The Math.Net Numerics vector whose columns contains solutions to the systems of linear equations whose right-hand sides are specified by yhe rightHandSides parameter.
Reimplemented from IG.Num.LinearSolverBase.
Definition at line 1607 of file MatrixDecompositions.cs.
References IG.Num.LinearSolverBase._vectorRighthandSides_MathNetNumerics, IG.Num.LinearSolverBase._vectorSolution_MathNetNumerics, IG.Lib.Base, IG.Num.VectorBase.Copy(), IG.Num.IVector< T >.Length, and IG.Lib.ILockable.Lock.
Member Data Documentation
_determinant
double IG.Num.SingularValueDecomposition._determinant protected
Definition at line 1511 of file MatrixDecompositions.cs.
_determinantCalculated
bool IG.Num.SingularValueDecomposition._determinantCalculated = false protected
Definition at line 1513 of file MatrixDecompositions.cs.
_inverse
MatrixBase_MathNetNumerics IG.Num.SingularValueDecomposition._inverse private
Definition at line 1536 of file MatrixDecompositions.cs.
Referenced by IG.Num.SingularValueDecomposition.Inverse().
Property Documentation
IsNonSingular
bool IG.Num.SingularValueDecomposition.IsNonSingular get
Indicates whether the matrix of coefficients of a linear system is nonsingular.
Returns
true if U, and hence A, is nonsingular.
Definition at line 1445 of file MatrixDecompositions.cs.
LeftSingularVectors
Matrix IG.Num.SingularValueDecomposition.LeftSingularVectors get
Returns the left singular vectors.
Definition at line 1458 of file MatrixDecompositions.cs.
SingularValues
Vector IG.Num.SingularValueDecomposition.SingularValues get
Returns the singular values.
Definition at line 1470 of file MatrixDecompositions.cs.
RightSingularVectors
Matrix IG.Num.SingularValueDecomposition.RightSingularVectors get
Returns the right singular vectors.
Definition at line 1482 of file MatrixDecompositions.cs.
Determinant
double IG.Num.SingularValueDecomposition.Determinant get
Returns the determinant.
Returns
det(A)
Exceptions
System.ArgumentException Matrix must be square.
Definition at line 1519 of file MatrixDecompositions.cs.
The documentation for this class was generated from the following file:
iglib/igbase/numeric/MatrixDecompositions.cs