Doc: IGLib with source files: IG.Lib.TrackedThread Class Reference
IG.Lib.TrackedThread Class Reference
Tracked thread object that wraps a single created thread and enables that all active wrapped threads are are tracked (i.e. a list of all active tracked threads can be obtained at any time).
Public Member Functions
TrackedThread (ParameterizedThreadStart start)
Creates a new tracked thread with the specified parameterized thread start delegate.
TrackedThread (ThreadStart start)
Creates a new tracked thread with the specified thread start delegate.
TrackedThread (ParameterizedThreadStart start, int maxStackSize)
Creates a new tracked thread with the specified parameterized thread start delegate and the specified maximal stack size.
TrackedThread (ThreadStart start, int maxStackSize)
Creates a new tracked thread with the specified thread start delegate and the specified maximal stack size.
Static Public Member Functions
static void Test ()
Tests and demonstrates the TrackedThread class.
Protected Member Functions
void StartThreadParameterized (object obj)
The parameterized start method of the current tracked thread. Calls the delegate that has been passed at creation.
void StartThread ()
The parameterized start method of the current tracked thread. Calls the delegate that has been passed at creation.
Protected Attributes
readonly Thread _thread
readonly ParameterizedThreadStart _startParameterized
Parameterized start delegate, executed on the thread when it starts.
readonly ThreadStart _start
Start delegate (nonparameterized), executed on the thread when it starts.
Static Protected Attributes
static readonly object _lockThreadList = new object()
Object for locking the list of active traced threads.
static readonly List< TrackedThread > _threadList = new List<TrackedThread>()
The list of active traced threads.
Properties
Thread Thread [get]
Gets the thread that is uses in this object.
bool IsParameterizedStart [get]
Gets the flag indicating whether the current traced thread uses a parameterized thread start.
static TrackedThread[] Threads [get]
Returns the array of all active tracked threads of type TrackedThread.
static int Count [get]
Gets the current number of active traced threads.
Static Private Member Functions
static void DoNothingForFiveSeconds ()
static void DoNothingForTenSeconds ()
static void DoNothingForSomeTime (object seconds)
Detailed Description
Tracked thread object that wraps a single created thread and enables that all active wrapped threads are are tracked (i.e. a list of all active tracked threads can be obtained at any time).
Starting and manipulatin of the wrapped thread is done through the TrackedThread.Thread property.
The TrackedThread.IsParameterizedStart property can be used if the wrapped thread was created with the parameterized thread start delegate.
The static TrackedThread.Threads property returns an array of all TrackedThread objects that have ever been created and wrap active threads (threads that complete are removed from the list).
$A Igor xx;
Definition at line 23 of file TracedThread.cs.
Constructor & Destructor Documentation
TrackedThread() [1/4]
IG.Lib.TrackedThread.TrackedThread (ParameterizedThreadStart start) inline
Creates a new tracked thread with the specified parameterized thread start delegate.
Parameters
start The ParameterizedThreadStart delegate that is called on thread start.
Definition at line 30 of file TracedThread.cs.
References IG.Lib.TrackedThread._lockThreadList, IG.Lib.TrackedThread._startParameterized, IG.Lib.TrackedThread._thread, IG.Lib.TrackedThread._threadList, IG.Lib.TrackedThread.StartThreadParameterized(), and IG.Lib.TrackedThread.Thread.
Referenced by IG.Lib.TrackedThread.Test().
TrackedThread() [2/4]
IG.Lib.TrackedThread.TrackedThread (ThreadStart start) inline
Creates a new tracked thread with the specified thread start delegate.
Parameters
start The ThreadStart delegate that is called on thread start.
Definition at line 42 of file TracedThread.cs.
References IG.Lib.TrackedThread._lockThreadList, IG.Lib.TrackedThread._start, IG.Lib.TrackedThread._thread, IG.Lib.TrackedThread._threadList, IG.Lib.TrackedThread.StartThread(), and IG.Lib.TrackedThread.Thread.
TrackedThread() [3/4]
IG.Lib.TrackedThread.TrackedThread (ParameterizedThreadStart start, int maxStackSize) inline
Creates a new tracked thread with the specified parameterized thread start delegate and the specified maximal stack size.
Parameters
start The ParameterizedThreadStart delegate that is called on thread start.
maxStackSize Maximal stack size of the thread.
Definition at line 56 of file TracedThread.cs.
References IG.Lib.TrackedThread._lockThreadList, IG.Lib.TrackedThread._startParameterized, IG.Lib.TrackedThread._thread, IG.Lib.TrackedThread._threadList, IG.Lib.TrackedThread.StartThreadParameterized(), and IG.Lib.TrackedThread.Thread.
TrackedThread() [4/4]
IG.Lib.TrackedThread.TrackedThread (ThreadStart start, int maxStackSize) inline
Creates a new tracked thread with the specified thread start delegate and the specified maximal stack size.
Parameters
start The ThreadStart delegate that is called on thread start.
maxStackSize Maximal stack size of the thread.
Definition at line 70 of file TracedThread.cs.
References IG.Lib.TrackedThread._lockThreadList, IG.Lib.TrackedThread._start, IG.Lib.TrackedThread._thread, IG.Lib.TrackedThread._threadList, IG.Lib.TrackedThread.StartThread(), and IG.Lib.TrackedThread.Thread.
Member Function Documentation
StartThreadParameterized()
void IG.Lib.TrackedThread.StartThreadParameterized (object obj) inline protected
The parameterized start method of the current tracked thread. Calls the delegate that has been passed at creation.
Parameters
obj Object that is passed as argument to the delegate that is called on thread start.
Definition at line 115 of file TracedThread.cs.
References IG.Lib.TrackedThread._lockThreadList, IG.Lib.TrackedThread._startParameterized, and IG.Lib.TrackedThread._threadList.
Referenced by IG.Lib.TrackedThread.TrackedThread().
StartThread()
void IG.Lib.TrackedThread.StartThread () inline protected
The parameterized start method of the current tracked thread. Calls the delegate that has been passed at creation.
Definition at line 138 of file TracedThread.cs.
References IG.Lib.TrackedThread._lockThreadList, IG.Lib.TrackedThread._start, and IG.Lib.TrackedThread._threadList.
Referenced by IG.Lib.TrackedThread.TrackedThread().
Test()
static void IG.Lib.TrackedThread.Test () inline static
Tests and demonstrates the TrackedThread class.
Definition at line 212 of file TracedThread.cs.
References IG.Lib.TrackedThread.Count, IG.Lib.TrackedThread.DoNothingForFiveSeconds(), IG.Lib.TrackedThread.DoNothingForSomeTime(), IG.Lib.TrackedThread.DoNothingForTenSeconds(), IG.Lib.TrackedThread.Thread, and IG.Lib.TrackedThread.TrackedThread().
DoNothingForFiveSeconds()
static void IG.Lib.TrackedThread.DoNothingForFiveSeconds () inline static private
Definition at line 229 of file TracedThread.cs.
References IG.Lib.TrackedThread.Thread.
Referenced by IG.Lib.TrackedThread.Test().
DoNothingForTenSeconds()
static void IG.Lib.TrackedThread.DoNothingForTenSeconds () inline static private
Definition at line 234 of file TracedThread.cs.
References IG.Lib.TrackedThread.Thread.
Referenced by IG.Lib.TrackedThread.Test().
DoNothingForSomeTime()
static void IG.Lib.TrackedThread.DoNothingForSomeTime (object seconds) inline static private
Definition at line 239 of file TracedThread.cs.
References IG.Lib.TrackedThread.Thread.
Referenced by IG.Lib.TrackedThread.Test().
Member Data Documentation
_thread
readonly Thread IG.Lib.TrackedThread._thread protected
Definition at line 85 of file TracedThread.cs.
Referenced by IG.Lib.TrackedThread.TrackedThread().
_startParameterized
readonly ParameterizedThreadStart IG.Lib.TrackedThread._startParameterized protected
Parameterized start delegate, executed on the thread when it starts.
Definition at line 97 of file TracedThread.cs.
Referenced by IG.Lib.TrackedThread.StartThreadParameterized(), and IG.Lib.TrackedThread.TrackedThread().
_start
readonly ThreadStart IG.Lib.TrackedThread._start protected
Start delegate (nonparameterized), executed on the thread when it starts.
Definition at line 100 of file TracedThread.cs.
Referenced by IG.Lib.TrackedThread.StartThread(), and IG.Lib.TrackedThread.TrackedThread().
_lockThreadList
readonly object IG.Lib.TrackedThread._lockThreadList = new object() static protected
Object for locking the list of active traced threads.
Definition at line 160 of file TracedThread.cs.
Referenced by IG.Lib.TrackedThread.StartThread(), IG.Lib.TrackedThread.StartThreadParameterized(), and IG.Lib.TrackedThread.TrackedThread().
_threadList
readonly List<TrackedThread> IG.Lib.TrackedThread._threadList = new List<TrackedThread>() static protected
The list of active traced threads.
Definition at line 163 of file TracedThread.cs.
Referenced by IG.Lib.TrackedThread.StartThread(), IG.Lib.TrackedThread.StartThreadParameterized(), and IG.Lib.TrackedThread.TrackedThread().
Property Documentation
Thread
Thread IG.Lib.TrackedThread.Thread get
Gets the thread that is uses in this object.
Definition at line 89 of file TracedThread.cs.
Referenced by IG.Lib.TrackedThread.DoNothingForFiveSeconds(), IG.Lib.TrackedThread.DoNothingForSomeTime(), IG.Lib.TrackedThread.DoNothingForTenSeconds(), IG.Lib.TrackedThread.Test(), and IG.Lib.TrackedThread.TrackedThread().
IsParameterizedStart
bool IG.Lib.TrackedThread.IsParameterizedStart get
Gets the flag indicating whether the current traced thread uses a parameterized thread start.
Definition at line 105 of file TracedThread.cs.
Threads
TrackedThread [] IG.Lib.TrackedThread.Threads static get
Returns the array of all active tracked threads of type TrackedThread.
Use the TrackedThread.Thread property on the elements of the returned array in order to manipulate individual tracked threads.
Definition at line 169 of file TracedThread.cs.
Count
int IG.Lib.TrackedThread.Count static get
Gets the current number of active traced threads.
Definition at line 194 of file TracedThread.cs.
Referenced by IG.Lib.TrackedThread.Test().
The documentation for this class was generated from the following file:
iglib/igbase/numeric/parallel/threadutils/TracedThread.cs