Doc: IGLib with source files: IG.Num.Vector Class Reference
IG.Num.Vector Class Reference
Real vector class.
Public Member Functions
Vector (IVector vec)
Constructs a vector from aanother array.
Vector (int n)
Constructs an n-dimensional vector of zeros.
Vector (int n, int which)
Constructs an n-dimensional unit vector for i'th coordinate.
Vector (int n, double value)
Constructs an n-dimensional constant vector with all components initialized to the specified value.
Vector (IList< double > components)
Constructs a vector from a list of elements by copying its elements.
Vector (double[] components, bool copyElements=true)
Constructs a vector from a 1-D array, either by directly using the array or by copying its elements.
Vector (params double[] components)
Constructs a vector from a 1-D array or from listed variable number of components.
Vector GetCopyThis ()
Creates and returns a copy of the current vector, which is of the same type as the current vector.
override VectorBase GetCopyBase ()
Creates and returns a copy of the current vector, which is of the same type as the current vector.
Vector GetNewThis (int length)
Creates and returns a new vector of the specified dimension in such a way that the type of the returned vector is the same as that of the current vector.
override VectorBase GetNewBase (int length)
Creates and returns a new vector of the specified dimension in such a way that the type of the returned vector is the same as that of the current vector.
Vector GetNewThis ()
Creates and returns a new vector with the same dimension and of the same type as the current vector.
override VectorBase GetNewBase ()
Creates and returns a new vector with the same dimension and of the same type as the current vector.
virtual Matrix GetNewMatrixThis (int rowCount, int columnCount)
Creates and returns a new matrix with the specified dimensona, and of a type that is consistent with the type of the current vector.
override MatrixBase GetNewMatrixBase (int rowCount, int columnCount)
Creates and returns a new matrix with the specified dimensona, and of a type that is consistent with the type of the current vector.
Matrix GetNewMatrixThis ()
Creates and returns a new matrix of a type that is consistent with the type of the current vector, and with both dimensions equal to the dimension of the current vector.
override MatrixBase GetNewMatrixBase ()
Creates and returns a new matrix of a type that is consistent with the type of the current vector, and with both dimensions equal to the dimension of the current vector.
override int GetHashCode ()
Returns the hash code (hash function) of the current vector.
override bool Equals (Object obj)
Returns a value indicating whether the specified object is equal to the current vector.
Public Member Functions inherited from IG.Num.VectorBase
virtual double[] ToArray ()
Copies the current vector to an array.
virtual IVector GetCopy ()
Returns a deep copy of the current object.
virtual IVector GetNew (int length)
Creates and returns a new vector with the specified dimension, and of the same type as the current vector.
virtual IVector GetNew ()
Creates and returns a new vector with the same dimension and of the same type as the current vector.
virtual IMatrix GetNewMatrix (int rowCount, int columnCount)
Creates and returns a new matrix with the specified dimensona, and of a type that is consistent with the type of the current vector.
virtual IMatrix GetNewMatrix ()
Creates and returns a new matrix of a type that is consistent with the type of the current vector, and with both dimensions equal to the dimension of the current vector.
virtual void SetZero ()
Sets all components of the current vector to 0.
virtual void SetConstant (double elementValue)
Sets all components of the current vector to the specified value.
virtual void SetUnit (int which)
Sets the current vector to the specific unit vector (one component equals 1, others are 0).
virtual void SetRandom ()
Sets the current vector such that it contains random elements on the interval (0,1].
virtual void SetRandom (IRandomGenerator rnd)
Sets the current vector such that it contains random elements on the interval (0,1].
virtual double NormP (double p)
p-norm, p-th root of sum of absolute values of components raised to the power of p.
IVector Normalized ()
Returns a vector that equals a normalized current vector.
void Normalize ()
Normalizes the current vector.
void Negate ()
Changes the sign of the current vector.
override int GetHashCode ()
Returns the hash code (hash function) of the current vector.
override bool Equals (Object obj)
Returns a value indicating whether the specified object is equal to the current vector.
int GetHashFunctionInt ()
Returns an integer valued hash function of the current vector object.
string GetHashFunctionString ()
Returns a string valued hash function of the current vector object.
override string ToString ()
Returns a string representation of this vector in a standard IGLib form.
virtual string ToStringMath ()
Returns a string representation of this vector in a standard IGLib form (Mathematica-like format but with C representation of numbers).
virtual string ToString (string elementFormat)
Returns a string representation of the current vector in a standard IGLib form, with the specified
format for elements of the vector.
virtual string ToStringMath (string elementFormat)
Returns a string representation of the current vector in a standard IGLib form (Mathematica-like format but with C representation of numbers), with the specified
format for elements of the vector.
Static Public Member Functions
static Vector Create (double[] components)
Constructs a vector from a 1-D array.
static Vector Create (IVector vec)
Constructs a vector as a copy of another Vector object.
static Vector Random (int n, IRandomGenerator rand=null)
Generates vector with random elements uniformly distributed on [0, 1).
static Vector Ones (int n)
Generates an d2-dimensional vector filled with 1.
static Vector Zeros (int n)
Generates an d2-dimensional vector filled with 0.
static Vector BasisVector (int n, int i)
Generates an d2-dimensional unit vector for i-th coordinate.
Static Public Member Functions inherited from IG.Num.VectorBase
static double NormPlain (IVector a)
Returns Euclidean norm of the specified vector.
static double NormStatic (IVector a)
Returns Euclidean norm of the specified vector.
static double Norm2Plain (IVector a)
Returns Euclidean norm of the specified vector.
static double Norm2Static (IVector a)
Returns Euclidean norm of the specified vector.
static double Norm1Plain (Vector a)
Returns the 1-norm (Manhattan or Taxicab norm, sum of element absolute values) of the specified vector.
static double Norm1Static (IVector a)
Returns the 1-norm (Manhattan or Taxicab norm, sum of element absolute values) of the specified vector.
static double NormPPlain (Vector a, double p)
Returns the p-norm (p-th root of sum of absolute values of components raised to the power of p) of the specified vector.
static double NormPStatic (IVector a, double p)
Returns the p-norm (p-th root of sum of absolute values of components raised to the power of p) of the specified vector.
static double NormInfPlain (Vector a)
Returns the Infinity-norm (maximum absolute value of any element) of the specified vector.
static double NormInfStatic (IVector a)
Returns the Infinity-norm (maximum absolute value of any element) of the specified vector.
static double DistancePlain (IVector a, IVector b)
Returns Euqlidean distance between the specified two vectors.
static double Distance (IVector a, IVector b)
Returns Euqlidean distance between the specified two vectors.
static double DistanceWeightedPlain (IVector a, IVector b, IVector characteristicLengths)
Returns distance between the specified two vectors where vector elements are weighted by elements of another vector, which represent intervals of equal importance (thus the weighted sum is divided by their squares).
static double DistanceWeighted (IVector a, IVector b, IVector characteristicLengths)
Returns distance between the specified two vectors where vector elements are weighted by elements of another vector, which represent intervals of equal importance (thus the weighted sum is divided by their squares).
static double NormWeightedPlain (IVector a, IVector characteristicLengths)
Returns weighted Euclidean norm of the specified vector.
static double NormWeighted (IVector a, IVector characteristicLengths)
Returns weighted Euclidean norm of the specified vector.
static void SetZero (IVector vec)
Sets all components of the current vector to 0.
static void SetConstant (IVector vec, double elementValue)
Sets all components of the current vector to the specified value.
static void SetUnit (IVector vec, int which)
Sets the current vector to the specific unit vector (one component equals 1, others are 0).
static void SetRandom (IVector vec)
Sets the current vector such that it contains random elements on the interval (0,1].
static void SetRandom (IVector vec, IRandomGenerator rnd)
Sets the current vector such that it contains random elements on the interval (0,1].
static int Compare (IVector v1, IVector v2)
Compares two vectors and returns -1 if the first vector is smaller than the second one, 0 if vectors are equal, and 1 if the first vector is greater. Vector that is null is considered smaller than a vector that is not null. Two null vectors are considered equal. Vector with smaller dimension is considered smaller than a vector with greater dimension. Vectors with equal dimensions ar compared by elements. The first element that is different decides which vector is considered greater.
static void Resize (ref IVector vec, IVector template, int dimension)
Resizes, if necessary, the specified vector according to the required dimension. If the vector is initially null then a new vector is created. If in this case a template vector is specified then the newly created vector will be of the same type as that template vector, because it is created by the GetNew() method on that vector. If dimension of the initial vector does not match the required dim., then vector is resized. If the specified vector dimension is less or equal to 0 then vector is resized with the same dimension as that of the template vector. If in this case the template vector is null, an exception is thrown. WARNINGS: Components are NOT preserved and have in general undefined values after operation is performed. If vector and template are null then the type of nawly created vector is Vector.
static void Resize (ref IVector vec, int dimension)
Resizes, if necessary, the specified vector according to the required dimension. If the vector is initially null then a new vector is created. If dimension of the initial vector does not match the required dimension, then vector is resized. Components are NOT preserved and have in general undefined values after operation is performed. WARNING: If the vector is initially null then the type of the newly created vector is Vector.
static void Resize (ref IVector vec, IVector template)
Resizes, if necessary, the specified vector according to the dimension of the specified template vector. If the vector is initially null then a new vector is created. In this case the newly created vector will be of the same type as that template vector, because it is created by the GetNew() method on that vector. If dimension of the initial vector does not match the dimension of the template vector, then vector is resized. If the template vector is null, then an exception is thrown. WARNINGS: Components are NOT preserved and have in general undefined values after operation is performed. If vector and template are null then the type of newly created vector is Vector.
static void CopyPlain (IVector a, IVector result)
Copies components of a vector to another vector. This is a plain version that does not perform any dimension checks. WARNING: dimensions of the copied vector and result vector must match.
static void Copy (IVector a, IVector result)
Copies components of a vector to another vector. WARNING: dimensions of the copied vector and result vector must match.
static void Copy (IVector a, ref IVector result)
Copies components of a vectr to another vector. Resulting vector is allocated or reallocated if necessary.
static void CopyPlain (VectorBase_MathNetNumerics a, IVector result)
Copies components of a vector to another vector. This is a plain version that does not perform any dimension checks. WARNING: dimensions of the copied vector and result vector must match.
static void Copy (VectorBase_MathNetNumerics a, IVector result)
Copies components of a vector to another vector. WARNING: dimensions of the copied vector and result vector must match.
static void Copy (VectorBase_MathNetNumerics a, ref IVector result)
Copies components of a vectr to another vector. Resulting vector is allocated or reallocated if necessary.
static void CopyPlain (IVector a, Vector_MathNetNumerics result)
Copies components of a vector to another vector. This is a plain version that does not perform any dimension checks. WARNING: dimensions of the copied vector and result vector must match.
static void Copy (IVector a, Vector_MathNetNumerics result)
Copies components of a vector to another vector. WARNING: dimensions of the copied vector and result vector must match.
static void Copy (IVector a, ref Vector_MathNetNumerics result)
Copies components of a vectr to another vector. Resulting vector is allocated or reallocated if necessary.
static void NegatePlain (IVector a, IVector result)
Stores a negative vector of the specified vector to another vector. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions of the copied vector and result vector must match.
static void Negate (IVector a, IVector result)
Stores a negative vector of the specified vector to another vector. WARNING: dimensions of the copied vector and result vector must match.
static void Negate (IVector a, ref IVector result)
Stores a negative vector of the specified vector to another vector. Resulting vector is allocated or reallocated if necessary.
static void AddPlain (IVector a, IVector b, IVector result)
Sums two vectors and stores the result in the specified result vector. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions of vectors must match, otherwise an exception is thrown.
static void Add (IVector a, IVector b, IVector result)
Sums two vectors and stores the result in the specified result vector. WARNING: dimensions of vectors must match, otherwise an exception is thrown.
static void Add (IVector a, IVector b, ref IVector result)
Sums two vectors and stores the result in the specified result vector. WARNING: dimensions of operands must match, otherwise an exception is thrown. If dimensions of the result do not match then teh result is re-allocated.
static void SubtractPlain (IVector a, IVector b, IVector result)
Subtracts two vectors (a - b) and stores the result in the specified result vector. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions of vectors must match, otherwise an exception is thrown.
static void Subtract (IVector a, IVector b, IVector result)
Subtracts two vectors (a - b) and stores the result in the specified result vector. WARNING: dimensions of vectors must match, otherwise an exception is thrown.
static void Subtract (IVector a, IVector b, ref IVector result)
Subtracts two vectors (a - b) and stores the result in the specified result vector. WARNING: dimensions of operands must match, otherwise an exception is thrown. If dimensions of the result do not match then teh result is re-allocated.
static void OrthogonalProjectionPlain (IVector original, IVector onWhich, double onWhichProductSelf, IVector result, double tolerance=0.0)
Calculates orthogonal projection of the original vector on the specified vector, and stores the projection in the specified result, where the inner project of the vector to which projection is performed is specified.
static void OrthogonalProjectionPlain (IVector original, IVector onWhich, IVector result, double tolerance=0.0)
Calculates orthogonal projection of the original vector on the specified vector, and stores the projection in the specified result.
static void OrthogonalProjection (IVector original, IVector onWhich, double onWhichProductSelf, ref IVector result, double tolerance=0.0)
Calculates orthogonal projection of the original vector on the specified vector, and stores the projection in the specified result, where the inner project of the vector to which projection is performed is specified.
static void OrthogonalProjection (IVector original, IVector onWhich, ref IVector result, double tolerance=0.0)
Calculates orthogonal projection of the original vector on the specified vector, and stores the projection in the specified result.
static void ArrayAddPlain (IVector a, double scal, IVector result)
Addition of a scalar to all components of a vector. This is a plain version of the method that does not perform any consistency checks. Vector operand must be defined (non-null).
static void ArrayAdd (IVector a, double scal, IVector result)
Addition of a scalar to all components of a vector. Vector operand must be defined (non-null).
static void ArrayAdd (IVector a, double scal, ref IVector result)
Addition of a scalar to all components of a vector. Vector operand must be defined (non-null).
static void ArraySubtractPlain (IVector a, double scal, IVector result)
Subtraction of a scalar from all components of a vector. This is a plain version of the method that does not perform any consistency checks. Vector operand must be defined (non-null).
static void ArraySubtract (IVector a, double scal, IVector result)
Subtraction of a scalar from all components of a vector. Vector operand must be defined (non-null).
static void ArraySubtract (IVector a, double scal, ref IVector result)
Subtraction of a scalar to all components of a vector. Vector operand must be defined (non-null).
static void MultiplyPlain (IVector a, double scal, IVector result)
Multiplication of a vector by a scalar. This is a plain version of the method that does not perform any consistency checks. Vector operand must be defined (non-null).
static void Multiply (IVector a, double scal, IVector result)
Multiplication of a vector by a scalar. Vector operand must be defined (non-null).
static void Multiply (IVector a, double scal, ref IVector result)
Multiplication of a vector by a scalar. Vector operand must be defined (non-null).
static void ScalePlain (IVector a, double scal, IVector result)
Multiplication of a vector by a scalar. This is a plain version of the method that does not perform any consistency checks. Vector operand must be defined (non-null).
static void Scale (IVector a, double scal, IVector result)
Multiplication of a vector by a scalar. Vector operand must be defined (non-null).
static void Scale (IVector a, double scal, ref IVector result)
Multiplication of a vector by a scalar. Vector operand must be defined (non-null).
static void DividePlain (IVector a, double scal, IVector result)
Division of a vector by a scalar. This is a plain version of the method that does not perform any consistency checks. Vector operand must be defined (non-null).
static void Divide (IVector a, double scal, IVector result)
Division of a vector by a scalar. Vector operand must be defined (non-null).
static void Divide (IVector a, double scal, ref IVector result)
Division of a vector by a scalar. Vector operand must be defined (non-null).
static double ScalarProductPlain (IVector a, IVector b)
Scalar product of teo vectors. This is a plain version of the method that does not perform any consistency checks.
static double ScalarProduct (IVector a, IVector b)
Scalar product of teo vectors.
static void DyadicProductPlain (IVector a, IVector b, IMatrix result)
Calculates dyadic product of two vectors and stores the result in the specified result matrix. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions must match, otherwise an exception is thrown.
static void DyadicProduct (IVector a, IVector b, IMatrix result)
Calculates dyadic product of two vectors and stores the result in the specified result matrix. WARNING: dimensions must match, otherwise an exception is thrown.
static void DyadicProduct (IVector a, IVector b, ref IMatrix result)
Calculates dyadic product of two vectors and stores the result in the specified result matrix. WARNING: dimensions of operands must match, otherwise an exception is thrown. If dimensions of the result do not match then teh result is re-allocated.
static void CrossProductPlain (IVector a, IVector b, IVector result)
Calculates a vector product (cross product) of two vectors and stores the result in the specified result vector. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions of all vectors must be 3, otherwise an exception is thrown.
static void CrossProduct (IVector a, IVector b, IVector result)
Calculates a vector product (cross product) of two vectors and stores the result in the specified result vector. WARNING: dimensions of all vectors must be 3, otherwise an exception is thrown.
static void CrossProduct (IVector a, IVector b, ref IVector result)
Calculates a vector product (cross product) of two vectors and stores the result in the specified result vector. WARNING: dimensions of operands must match, otherwise an exception is thrown. If dimensions of the result do not match then teh result is re-allocated.
static void VectorProductPlain (IVector a, IVector b, IVector result)
Calculates a vector product (cross product) of two vectors and stores the result in the specified result vector. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions of all vectors must be 3, otherwise an exception is thrown.
static void VectorProduct (IVector a, IVector b, IVector result)
Calculates a vector product (cross product) of two vectors and stores the result in the specified result vector. WARNING: dimensions of all vectors must be 3, otherwise an exception is thrown.
static void VectorProduct (IVector a, IVector b, ref IVector result)
Calculates a vector product (cross product) of two vectors and stores the result in the specified result vector. WARNING: dimensions of operands must match, otherwise an exception is thrown. If dimensions of the result do not match then teh result is re-allocated.
static void ArrayProductPlain (IVector a, IVector b, IVector result)
Calculates array product (element-by-element product) of two vectors and stores the result in the specified result vector. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions of all vectors must be 3, otherwise an exception is thrown.
static void ArrayProduct (IVector a, IVector b, IVector result)
Calculates array product (element-by-element product) of two vectors and stores the result in the specified result vector. WARNING: dimensions of all vectors must be 3, otherwise an exception is thrown.
static void ArrayProduct (IVector a, IVector b, ref IVector result)
Calculates array product (element-by-element product) of two vectors and stores the result in the specified result vector. WARNING: dimensions of operands must match, otherwise an exception is thrown. If dimensions of the result do not match then teh result is re-allocated.
static void ArrayQuotientPlain (IVector a, IVector b, IVector result)
Calculates array quotient (element-by-element division) of two vectors and stores the result in the specified result vector. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions of all vectors must be 3, otherwise an exception is thrown.
static void ArrayQuotient (IVector a, IVector b, IVector result)
Calculates array quotient (element-by-element division) of two vectors and stores the result in the specified result vector. WARNING: dimensions of all vectors must be 3, otherwise an exception is thrown.
static void ArrayQuotient (IVector a, IVector b, ref IVector result)
Calculates array quotient (element-by-element division) of two vectors and stores the result in the specified result vector. WARNING: dimensions of operands must match, otherwise an exception is thrown. If dimensions of the result do not match then teh result is re-allocated.
static int GetHashCode (IVector vec)
Returns hash code of the specified vector.
static bool Equals (IVector v1, IVector v2)
Returns true if the specified vectors are equal, false if not.
static int GetHashFunctionInt (IVector vec)
Returns an integer valued hash function of the specified vector object.
static string GetHashFunctionString (IVector vec)
Returns a string valued hash function of the specified vector object.
static void OrthoNormalizeGramSchmidt (IList< IVector > original, ref IList< IVector > resOrthogonal, ref IVector resNorms, ref IVector auxProjection, double tolDependent=1e-10, bool normalize=false, int numRequestedVectors=0, IRandomGenerator rand=null, int maxExcessGenerated=5)
Performs the Gramm-Schmidt orthogonalization procedure in order to calculate a set of orthonormal vectors from the specified set of arbitrary independent vectors.
static int OrthogonalizeGramSchmidt (IList< IVector > original, ref IList< IVector > resOrthogonal, ref IVector resNorms, ref IVector auxProjection, double tolDependent=1e-10, bool normalize=false, int numRequestedVectors=0, IRandomGenerator rand=null, int maxExcessGenerated=5)
Performs the Gramm-Schmidt orthogonalization procedure in order to calculate a set of orthogonall vectors from the specified set of arbitrary independent vectors.
static void OrthoNormalizeGramSchmidtNonRobust (IList< IVector > original, ref IList< IVector > resOrthogonal, ref IVector resNorms, ref IVector auxProjection, double tolSize=0, bool normalize=false, bool modifiedGrammSchmidt=true)
Performs the Gramm-Schmidt orthogonalization procedure in order to calculate a set of orthonormal vectors from the specified set of arbitrary independent vectors.
static void OrthogonalizeGramSchmidtNonRobust (IList< IVector > original, ref IList< IVector > resOrthogonal, ref IVector resNorms, ref IVector auxProjection, double tolSize=0, bool normalize=false, bool modifiedGrammSchmidt=true)
Performs the Gramm-Schmidt orthogonalization procedure in order to calculate a set of orthogonall vectors from the specified set of arbitrary independent vectors.
static bool TestGramSchmidtOrthogonalization (int dim, int numRepetitions=1, double tol=1e-8, int outputLevel=0, IRandomGenerator randomGenerator=null, bool normalize=false, bool modifiedGrammSchmidt=true, bool nonRobust=false)
Performs a test of Gramm-Schmidt orthogonalization on a set of random vectors.
static VectorBase operator+ (VectorBase v)
Unary plus, returns the operand.
static VectorBase operator- (VectorBase v)
Unary negation, returns the negative operand.
static VectorBase operator+ (VectorBase a, VectorBase b)
Vector addition.
static VectorBase operator- (VectorBase a, VectorBase b)
Vector subtraction.
static double operator* (VectorBase a, VectorBase b)
Scalar product of two vectors.
static VectorBase operator* (VectorBase a, double b)
Product of a vector by a scalar.
static VectorBase operator* (double a, VectorBase b)
Product of a vector by a scalar.
static VectorBase operator/ (VectorBase a, double b)
Vector subtraction.
static string ToString (IVector vec)
Returns a string representation of the specified vector in a standard IGLib form.
static string ToStringMath (IVector vec)
Returns a string representation of the specified vector in a standard IGLib form (Mathematica-like format but with C representation of numbers).
static string ToString (IVector vec, string elementFormat)
Returns a string representation of the specified vector in a standard IGLib form, with the specified
format for elements of the vector.
static string ToStringMath (IVector vec, string elementFormat)
Returns a string representation of the specified vector in a standard IGLib form (Mathematica-like format but with C representation of numbers), with the specified
format for elements of the vector.
static void SaveJson (IVector vec, string filePath)
Saves (serializes) the specified vector to the specified JSON file. File is owerwritten if it exists.
static void SaveJson (IVector vec, string filePath, bool append)
Saves (serializes) the specified vector to the specified JSON file. If the file already exists, contents either overwrites the file or is appended at the end, dependent on the value of the append flag.
static void LoadJson (string filePath, ref IVector vecRestored)
Restores (deserializes) a vector from the specified file in JSON format.
static void SaveCsv (IVector vec, string filePath)
Saves the specified vector to a CSV file. It the specified file already exists then it is overwritten. Constant UtilCsv.DefaultCsvSeparator is used as separator.
static void SaveCsv (IVector vec, string filePath, string separator)
Saves the specified vector to a CSV file. It the specified file already exists then it is overwritten.
static void SaveCsv (IVector vec, string filePath, bool append)
Saves the specified vector to a CSV file. Constant UtilCsv.DefaultCsvSeparator is used as separator in CSV.
static void SaveCsv (IVector vec, string filePath, string separator, bool append)
Saves the specified vector to a CSV file.
static void LoadCsv (string filePath, ref IVector vecRestored)
Reads a vector from a CSV file. Constant UtilCsv.DefaultCsvSeparator is used as separator in CSV file. If there are no components then a null vector is returned by this method (no exceptions thrown). If there are more than one rows in the CSV file then vector is read from the first row.
static void LoadCsv (string filePath, string separator, ref IVector vecRestored)
Reads a vector written in CSV format from a file. If there are no components then a null vector is returned by this method (no exceptions thrown). If there are more than one rows in the CSV file then vector is read from the first row.
static void LoadCsv (string filePath, int rowNum, ref IVector vecRestored)
Reads a vector from the specified row of a CSV file. Constant UtilCsv.DefaultCsvSeparator is used as CSV separator. If the specified row does not exisist in the file then exception is thrown.
static void LoadCsv (string filePath, int rowNum, string separator, ref IVector vecRestored)
Reads a vector from the specified row of a CSV file. If the specified row does not exisist in the file then exception is thrown.
Protected Member Functions
void CopyFromMatNetNumericsVector (Vector_MathNetNumerics v)
Copies values from the specified MathNet Numerics vector.
Protected Attributes
double[] _elements
int _length
Vector_MathNetNumerics _copyMathNetNumerics
bool _mathNetNumericsConsistent = false
Properties
override int Length [get]
Gets dimension of the vector.
virtual int LengthSetter [set]
Sets the dimension of the current vector. This setter must be used very restrictively - only in setters that can change vector dimension. Setter is defined separately from getter because the base class' property does not define a getter.
override double this[int i] [get, set]
Gets or sets the element indexed by i in the Vector.
virtual bool IsCopyMathNetNumericsConsistent [get, protected set]
Tells whether the internal MathNet Numerics representation of the current vector is consistent with the current vector. The MathNet Numerics representation is used for operations that are used from that library such as different kinds of decompositions.
Properties inherited from IG.Num.VectorBase
abstract int Length [get]
Gets dimension of the vector.
abstract double this[int i] [get, set]
Gets or sets the element indexed by i in the Vector.
virtual double Norm [get]
Gets Euclidean norm of the vector.
virtual double Norm2 [get]
Gets Euclidean norm of the vector.
virtual double NormEuclidean [get]
Gets Euclidean norm of the vector.
virtual double SquaredNorm [get]
Squared Euclidean norm, sum of squared components.
virtual double Norm1 [get]
1-norm (Manhattan norm or Taxicab norm), sum of absolute values of components.
virtual double NormInf [get]
Infinity-norm, maximum absolute value of any component.
static VectorStore VectorStore [get]
Gets the matrix store for recycling auxiliary matrices.
Properties inherited from IG.Num.IVector< T >
int Length [get]
Gets the number of rows.
T this[int i] [get, set]
Gets or set the element indexed by i in the Vector.
double Norm [get]
Gets Euclidean norm of the vector.
double Norm2 [get]
Gets Euclidean norm of the vector.
double NormEuclidean [get]
Gets Euclidean norm of the vector.
double SquaredNorm [get]
Squared Euclidean norm, sum of squared components.
double Norm1 [get]
1-norm (Manhattan norm or Taxicab norm), sum of absolute values of components.
double NormInf [get]
Infinity-norm, maximum absolute value of any component.
Private Member Functions
object ICloneable. Clone ()
Returns a deep copy of a vector.
Detailed Description
Real vector class.
$A Igor Jan08 Jul10 Nov10;
Definition at line 23 of file Vector.cs.
Constructor & Destructor Documentation
Vector() [1/7]
IG.Num.Vector.Vector (IVector vec) inline
Constructs a vector from aanother array.
Parameters
vec Vector whose components are copied to the current vector.
See also
Create(double[])
Definition at line 42 of file Vector.cs.
References IG.Num.Vector._elements, IG.Num.Vector._length, and IG.Num.IVector< T >.Length.
Vector() [2/7]
IG.Num.Vector.Vector (int n) inline
Constructs an n-dimensional vector of zeros.
Parameters
n Dimensionality of vector.
Definition at line 57 of file Vector.cs.
References IG.Num.Vector._elements, and IG.Num.Vector._length.
Vector() [3/7]
IG.Num.Vector.Vector (int n, int which) inline
Constructs an n-dimensional unit vector for i'th coordinate.
Parameters
n Dimensionality of vector.
which Specifies which unit vector is constructed (which components equals one).
Definition at line 71 of file Vector.cs.
References IG.Num.Vector._elements, and IG.Num.Vector._length.
Vector() [4/7]
IG.Num.Vector.Vector (int n, double value) inline
Constructs an n-dimensional constant vector with all components initialized to the specified value.
Parameters
n Dimensionality of vector.
value Value to which all components are set.
Definition at line 89 of file Vector.cs.
References IG.Num.Vector._elements, and IG.Num.Vector._length.
Vector() [5/7]
IG.Num.Vector.Vector (IList< double > components) inline
Constructs a vector from a list of elements by copying its elements.
Parameters
components Object implementing IList interface that contains vector elements.
Definition at line 103 of file Vector.cs.
References IG.Num.Vector._elements, and IG.Num.Vector._length.
Vector() [6/7]
IG.Num.Vector.Vector (double[] components, bool copyElements = true) inline
Constructs a vector from a 1-D array, either by directly using the array or by copying its elements.
Parameters
components One-dimensional array of vector elements.
copyElements If true then elements of the provided array are copied (default), otherwise the array is directly used as internal structure containing elementts.
Definition at line 120 of file Vector.cs.
References IG.Num.Vector._elements, and IG.Num.Vector._length.
Vector() [7/7]
IG.Num.Vector.Vector (params double[] components) inline
Constructs a vector from a 1-D array or from listed variable number of components.
Elements of array are copied.
Parameters
components One-dimensional array of vector elements.
See also
Create(double[])
Definition at line 144 of file Vector.cs.
References IG.Num.Vector._elements, and IG.Num.Vector._length.
Member Function Documentation
Create() [1/2]
static Vector IG.Num.Vector.Create (double[] components) inline static
Constructs a vector from a 1-D array.
Definition at line 177 of file Vector.cs.
Create() [2/2]
static Vector IG.Num.Vector.Create (IVector vec) inline static
Constructs a vector as a copy of another Vector object.
Parameters
vec Vector whose elements are used for the newly created vector.
Definition at line 201 of file Vector.cs.
Random()
static Vector IG.Num.Vector.Random (int n, IRandomGenerator rand = null) inline static
Generates vector with random elements uniformly distributed on [0, 1).
Parameters
n Dimensionality of vector.
rand Random number generator used to generate vector elements. If null then a global generator is taken.
Returns
An n-dimensional vector with uniformly distributedrandom elements in [0, 1) interval.
Definition at line 212 of file Vector.cs.
References IG.Num.RandomGenerator.Global, and IG.Num.VectorBase.SetRandom().
Referenced by IG.Num.SpeedTestCpu.TestComputationalTimesCholesky_Base(), IG.Num.SpeedTestCpu.TestComputationalTimesCholesky_IGLib(), IG.Num.SpeedTestCpu.TestComputationalTimesLdlt_Base(), IG.Num.SpeedTestCpu.TestComputationalTimesLU_Base(), IG.Num.SpeedTestCpu.TestComputationalTimesLU_IGLib(), IG.Num.SpeedTestCpu.TestComputationalTimesQR_IGLib(), and IG.Num.VectorBase.TestGramSchmidtOrthogonalization().
Ones()
static Vector IG.Num.Vector.Ones (int n) inline static
Generates an d2-dimensional vector filled with 1.
Parameters
n Dimensionality of vector.
Definition at line 223 of file Vector.cs.
Zeros()
static Vector IG.Num.Vector.Zeros (int n) inline static
Generates an d2-dimensional vector filled with 0.
Parameters
n Dimensionality of vector.
Definition at line 230 of file Vector.cs.
BasisVector()
static Vector IG.Num.Vector.BasisVector (int n, int i) inline static
Generates an d2-dimensional unit vector for i-th coordinate.
Parameters
n Dimensionality of vector.
i Coordinate index.
Definition at line 238 of file Vector.cs.
CopyFromMatNetNumericsVector()
void IG.Num.Vector.CopyFromMatNetNumericsVector (Vector_MathNetNumerics v) inline protected
Copies values from the specified MathNet Numerics vector.
Parameters
v Vector from which elements are copied.
Definition at line 399 of file Vector.cs.
References IG.Num.Vector._elements, and IG.Num.Vector._length.
GetCopyThis()
Vector IG.Num.Vector.GetCopyThis () inline
Creates and returns a copy of the current vector, which is of the same type as the current vector.
Definition at line 447 of file Vector.cs.
References IG.Num.Vector.Length.
Referenced by IG.Num.Vector.Clone(), and IG.Num.Vector.GetCopyBase().
GetCopyBase()
override VectorBase IG.Num.Vector.GetCopyBase () inline virtual
Creates and returns a copy of the current vector, which is of the same type as the current vector.
Implements IG.Num.VectorBase.
Definition at line 457 of file Vector.cs.
References IG.Num.Vector.GetCopyThis().
GetNewThis() [1/2]
Vector IG.Num.Vector.GetNewThis (int length) inline
Creates and returns a new vector of the specified dimension in such a way that the type of the returned vector is the same as that of the current vector.
Parameters
length Dimension of the returned vector.
Definition at line 466 of file Vector.cs.
GetNewBase() [1/2]
override VectorBase IG.Num.Vector.GetNewBase (int length) inline virtual
Creates and returns a new vector of the specified dimension in such a way that the type of the returned vector is the same as that of the current vector.
Parameters
length Dimension of the returned vector.
Implements IG.Num.VectorBase.
Definition at line 474 of file Vector.cs.
GetNewThis() [2/2]
Vector IG.Num.Vector.GetNewThis () inline
Creates and returns a new vector with the same dimension and of the same type as the current vector.
Definition at line 482 of file Vector.cs.
References IG.Num.Vector.Length.
GetNewBase() [2/2]
override VectorBase IG.Num.Vector.GetNewBase () inline virtual
Creates and returns a new vector with the same dimension and of the same type as the current vector.
Implements IG.Num.VectorBase.
Definition at line 489 of file Vector.cs.
References IG.Num.Vector.Length.
GetNewMatrixThis() [1/2]
virtual Matrix IG.Num.Vector.GetNewMatrixThis (int rowCount, int columnCount) inline virtual
Creates and returns a new matrix with the specified dimensona, and of a type that is consistent with the type of the current vector.
Parameters
rowCount Number of rows of the returned matrix.
columnCount Number of rows of the returned matrix.
Returns
A matrix with specified dimensions, whose type is consistent with the type of the current vector.
Definition at line 500 of file Vector.cs.
GetNewMatrixBase() [1/2]
override MatrixBase IG.Num.Vector.GetNewMatrixBase (int rowCount, int columnCount) inline virtual
Creates and returns a new matrix with the specified dimensona, and of a type that is consistent with the type of the current vector.
Parameters
rowCount Number of rows of the returned matrix.
columnCount Number of rows of the returned matrix.
Returns
A matrix with specified dimensions, whose type is consistent with the type of the current vector.
Implements IG.Num.VectorBase.
Definition at line 510 of file Vector.cs.
GetNewMatrixThis() [2/2]
Matrix IG.Num.Vector.GetNewMatrixThis () inline
Creates and returns a new matrix of a type that is consistent with the type of the current vector, and with both dimensions equal to the dimension of the current vector.
Definition at line 518 of file Vector.cs.
References IG.Num.Vector.Length.
GetNewMatrixBase() [2/2]
override MatrixBase IG.Num.Vector.GetNewMatrixBase () inline virtual
Creates and returns a new matrix of a type that is consistent with the type of the current vector, and with both dimensions equal to the dimension of the current vector.
Implements IG.Num.VectorBase.
Definition at line 525 of file Vector.cs.
References IG.Num.Vector.Length.
Clone()
object ICloneable. IG.Num.Vector.Clone () inline private
Returns a deep copy of a vector.
Definition at line 532 of file Vector.cs.
References IG.Num.Vector.GetCopyThis().
GetHashCode()
override int IG.Num.Vector.GetHashCode () inline
Returns the hash code (hash function) of the current vector.
This method calls the VectorBase.GetHashCode() to calculate the hash code, which is standard for all implementations of the IVector interface.
Two vectors that have the same dimensions and equal elements will produce the same hash codes.
Probability that two different vectors will produce the same hash code is small but it exists.
Overrides the object.GetHashCode method.
Definition at line 642 of file Vector.cs.
References IG.Num.VectorBase.GetHashCode().
Equals()
override bool IG.Num.Vector.Equals (Object obj) inline
Returns a value indicating whether the specified object is equal to the current vector.
True is returned if the object is a non-null vector (i.e. it implements the IVector interface), and has the same dimension and equal elements as the current vector.
This method calls the VectorBase.Equals(object) to obtain the returned value, which is standard for all implementations of the IVector interface.
Overrides the object.Equals(object) method.
Definition at line 653 of file Vector.cs.
References IG.Num.VectorBase.Equals().
Member Data Documentation
_elements
double [] IG.Num.Vector._elements protected
Definition at line 250 of file Vector.cs.
Referenced by IG.Num.Vector.CopyFromMatNetNumericsVector(), and IG.Num.Vector.Vector().
_length
int IG.Num.Vector._length protected
Definition at line 252 of file Vector.cs.
Referenced by IG.Num.Vector.CopyFromMatNetNumericsVector(), and IG.Num.Vector.Vector().
_copyMathNetNumerics
Vector_MathNetNumerics IG.Num.Vector._copyMathNetNumerics protected
Definition at line 362 of file Vector.cs.
_mathNetNumericsConsistent
bool IG.Num.Vector._mathNetNumericsConsistent = false protected
Definition at line 364 of file Vector.cs.
Property Documentation
Length
override int IG.Num.Vector.Length get
Gets dimension of the vector.
Definition at line 256 of file Vector.cs.
Referenced by IG.Num.AffineTransformationSquare.AffineTransformationSquare(), IG.Num.Vector.GetCopyThis(), IG.Num.Vector.GetNewBase(), IG.Num.Vector.GetNewMatrixBase(), IG.Num.Vector.GetNewMatrixThis(), IG.Num.Vector.GetNewThis(), IG.Num.AffineTransformationSquare.InitAuxVec(), IG.Num.VectorBase.Norm1Plain(), IG.Num.VectorBase.NormInfPlain(), and IG.Num.VectorBase.NormPPlain().
LengthSetter
virtual int IG.Num.Vector.LengthSetter set protected
Sets the dimension of the current vector. This setter must be used very restrictively - only in setters that can change vector dimension. Setter is defined separately from getter because the base class' property does not define a getter.
Definition at line 263 of file Vector.cs.
this[int i]
override double IG.Num.Vector.this[int i] get set
Gets or sets the element indexed by i in the Vector.
Parameters
i Element index, 0 - based.
Definition at line 268 of file Vector.cs.
IsCopyMathNetNumericsConsistent
virtual bool IG.Num.Vector.IsCopyMathNetNumericsConsistent get protected set
Tells whether the internal MathNet Numerics representation of the current vector is consistent with the current vector. The MathNet Numerics representation is used for operations that are used from that library such as different kinds of decompositions.
Currrently, an internal flag indicating consistency of the MathNet matrix is not used. Every time this property is required, the consistence is actually verified by comparing values. There may be derived matrix classes where the falg is actually used. These must keep track when anything in the matrix changes and invalidate the flag on each such event.
Definition at line 374 of file Vector.cs.
The documentation for this class was generated from the following file:
iglib/igbase/numeric/Vector.cs