Doc: IGLib with source files: IG.Lib.Copy.ServerStreamBase Class Reference
IG.Lib.Copy.ServerStreamBase Class Reference abstract
Server that creates a named pipe, listens on its input stream, and sends responses to the client.
Public Member Functions
abstract bool IsServerPipelineConnected ()
Returns true if server pipe is connected, .
override void CloseInput ()
Closes the inpt stream.
override void CloseOutput ()
Closes the outut stream.
abstract void SendDummyRequest ()
virtual void StopServer ()
virtual string GetResponse (string request)
Returns response string for given request string.
void ThreadServe ()
Launches a named pipe server in a new thread.
void AbortWorkingThread (double timeoutSeconds=0)
Aborts the working thread.
override void ClearData ()
Clears all the data related to servig requests (i.e. request and response strings, error flags, exceptions, etc.).
Public Member Functions inherited from IG.Lib.Copy.ClientServerStreamBase2
virtual bool IsErrorResponse (string responseString)
Returns true if the specified response string represents an error response (exception), false if not.
virtual string GetErrorMessage (string responseString)
Returns error message that corresponds to the specified response string.
abstract void ClosePipe ()
Closes the pipe and streams that depend on it.
Public Member Functions inherited from IG.Lib.Copy.ClienServerStreamBase
delegate string ResponseDelegate (string request)
Provides an answer string to the specified request string.
void SetMessagePreix (string messagePrefix)
Changes message prefix for the current object.
void SetMessageSeparator (char messageSeparator)
Changes message separator for the current object.
void SetMessageFalseSeparator (char messageFalseSeparator)
Changes message false separator for the current object.
string CreateMessage (string messageName, string[] messageArguments)
Creates a built-in message (possibly with arguments) that is to be interpreted directly by the receiver (stream client or server) and is not executed via ordinary path.
string createResponseOrRequestString (string originalResponseOrRequestString)
Generates request and response string in such a way that it can not be mixed up with a message.
void GetRequestOrResponse (ref string responseOrRequestString, out bool isMessage, out string messageOrCommandName, out string[] messageArguments)
Returns the (eventually decoded) request or response string corresponding to the stirng that is read form the communication pipeline, and also parameters that specify whether the request string represents a message or not. Eventual command or message parameters are also returned.
Protected Member Functions
abstract void WaitForConnection ()
Waits until a client connects to the specified server pipe.
abstract void NullifyServerPipeLine ()
Closes connection of the server pype.
virtual string GetErrorMessage (Exception ex)
Returns error message corresponding to the specified exception.
virtual string ReadRequest ()
Reads the next request from the pipe.
virtual void SendResponse (string responseString)
Sends the specified response string back to the server.
virtual void SendResponse ()
Sends the response (i.e., the ClientServerStreamBase2.ResponseString) back to the client.
virtual void RespondToRequest ()
Reads a single request from the client and sends back the response.
virtual void ServeInCurrentThread ()
Enters the serving loop.
Static Protected Member Functions
static string DefaultResponseMethod (string request)
The deefault method that returns response to the specified request.
Protected Attributes
ThreadPriority _threadPriority = UtilSystem.ThreadPriority
Protected Attributes inherited from IG.Lib.Copy.ClienServerStreamBase
object _lock = new object()
Properties
bool IsResponseSent [get, protected set]
Auxiliary flag telling whether response to a request has already been sent to the client. Used for synchronization of diffeeent parts of the response generation process, which enables e.g special handling of Exceptions.
bool StopServe [get, protected set]
Whether the pipe should be closed.
bool IsServerRunning [get, protected set]
Flag telling whether the server is currently running.
virtual ResponseDelegate ResponseMethod [get, set]
Delegate that calculates response to given request.
ThreadPriority ThreadPriority [get, set]
Priority of the server thread.
Properties inherited from IG.Lib.Copy.ClientServerStreamBase2
abstract string Name [get, set]
static string DefaultPipeName [get, set]
Default pipe name.
static bool DefaultIsMultilineRequest [get]
Default pipe name.
static string DefaultRequestEnd [get]
Default string (line) that ends any multiline request.
static bool DefaultIsMultilineResponse [get]
Default pipe name.
static string DefaultResponseEnd [get]
Default string (line) that ends any multiline response.
virtual bool IsMultilineRequest [get, protected set]
Whether or not multi line requests are allowed.
string RequestEnd [get, protected set]
virtual bool IsMultilineResponse [get, protected set]
Whether or not multi line responses are allowed.
string ResponseEnd [get, protected set]
static string DefaultErrorBegin [get]
Default string that begins an error report.
string ErrorBegin [get, protected set]
abstract StreamReader InputStream [get, protected set]
Input stream writer of the server's named pipe.
abstract StreamWriter OutputStream [get, protected set]
Output stream reader of the server's named pipe.
bool IsError [get, protected set]
string RequestString [get, protected set]
The last request string that was read from the pipe.
string ResponseString [get, protected set]
The last answer string that was written to the pipe.
static string DefaultStopRequest [get, set]
Default stop request string - request string that will stop the server.
string StopRequest [get, set]
Request that causes the server stop listening and closing the pipe.
static string DefaultGenericResponse [get, set]
Default generic response (sent in absence of any other method to generate the response).
string GenericResponse [get, protected set]
Generic response that is sent back to the client in abscence of any method generating responses to specific requests.
static string DefaultStoppedResponse [get, set]
Default stopped response (sent after the srver has sttopped on request).
string StoppedResponse [get, protected set]
Stopped response that is sent back to the client after the server stops on its request.
Exception LastException [get, protected set]
Returns the last exception thrown when serving request.
string LastErrorMessage [get, protected set]
Returns the last error message.
string LastRequestString [get, protected set]
Returns the last request string.
string LastResponseString [get, protected set]
Returns the last response string.
Properties inherited from IG.Lib.Copy.ClienServerStreamBase
object Lock [get]
Objectt for locking the current object.
static object LockGlobal [get]
Static lock object used by all instances of this class (and possibly by other classes).
static string DefaultMessagePrefix [get, set]
static char DefaultMessageSeparator [get, set]
static char DefaultMessageFalseSeparator [get, set]
string MessagePrefix [get, protected set]
char MessageSeparator [get, protected set]
char MessageFalseSeparator [get, protected set]
string MessagePrefixWithSeparator [get, protected set]
Gets the mesage prefix with separator. If some string is a message, everything that follows this string until the first separator is a message name.
StringBuilder StringBuilderInternal [get]
static int DefaultOutputLevel [get, set]
Default level of output for this kind of class.
virtual int OutputLevel [get, set]
Level of output generated by operatins.
Properties inherited from IG.Lib.ILockable
object Lock [get]
Private Attributes
bool _stopServe = false
bool _isServerRunning = false
ResponseDelegate _responseMethod = DefaultResponseMethod
Thread _workingThread = null
Additional Inherited Members
Static Public Attributes inherited from IG.Lib.Copy.ClienServerStreamBase
const int MinimalMessagePreffixLength = 3
Detailed Description
Server that creates a named pipe, listens on its input stream, and sends responses to the client.
$A Igor xx Mar14;
Definition at line 478 of file ClientServerStreamBase2_Copy.cs.
Member Function Documentation
WaitForConnection()
abstract void IG.Lib.Copy.ServerStreamBase.WaitForConnection () protected pure virtual
Waits until a client connects to the specified server pipe.
Implemented in IG.Lib.Copy.NamedPipeServerBase.
Referenced by IG.Lib.Copy.ServerStreamBase.ServeInCurrentThread().
NullifyServerPipeLine()
abstract void IG.Lib.Copy.ServerStreamBase.NullifyServerPipeLine () protected pure virtual
Closes connection of the server pype.
Implemented in IG.Lib.Copy.NamedPipeServerBase.
Referenced by IG.Lib.Copy.ServerStreamBase.AbortWorkingThread().
IsServerPipelineConnected()
abstract bool IG.Lib.Copy.ServerStreamBase.IsServerPipelineConnected () pure virtual
Returns true if server pipe is connected, .
Implemented in IG.Lib.Copy.NamedPipeServerBase.
Referenced by IG.Lib.Copy.ServerStreamBase.ServeInCurrentThread().
CloseInput()
override void IG.Lib.Copy.ServerStreamBase.CloseInput () inline virtual
Closes the inpt stream.
Implements IG.Lib.Copy.ClientServerStreamBase2.
Definition at line 497 of file ClientServerStreamBase2_Copy.cs.
References IG.Lib.Copy.ClientServerStreamBase2.InputStream.
CloseOutput()
override void IG.Lib.Copy.ServerStreamBase.CloseOutput () inline virtual
Closes the outut stream.
Implements IG.Lib.Copy.ClientServerStreamBase2.
Definition at line 503 of file ClientServerStreamBase2_Copy.cs.
References IG.Lib.Copy.ClientServerStreamBase2.OutputStream.
SendDummyRequest()
abstract void IG.Lib.Copy.ServerStreamBase.SendDummyRequest () pure virtual
Implemented in IG.Lib.Copy.NamedPipeServerBase.
Referenced by IG.Lib.Copy.ServerStreamBase.StopServer().
StopServer()
virtual void IG.Lib.Copy.ServerStreamBase.StopServer () inline virtual
Definition at line 546 of file ClientServerStreamBase2_Copy.cs.
References IG.Lib.ILockable.Lock, IG.Lib.Copy.ServerStreamBase.SendDummyRequest(), and IG.Lib.Copy.ServerStreamBase.StopServe.
DefaultResponseMethod()
static string IG.Lib.Copy.ServerStreamBase.DefaultResponseMethod (string request) inline static protected
The deefault method that returns response to the specified request.
Just returns a string that tells which was the request string.
Parameters
request
Definition at line 564 of file ClientServerStreamBase2_Copy.cs.
GetResponse()
virtual string IG.Lib.Copy.ServerStreamBase.GetResponse (string request) inline virtual
Returns response string for given request string.
This method will generally be overridden in derived classes.
Parameters
request The request string.
Returns
Response to the request string.
Definition at line 583 of file ClientServerStreamBase2_Copy.cs.
References IG.Lib.Copy.ServerStreamBase.ResponseMethod.
Referenced by IG.Lib.Copy.ServerStreamBase.RespondToRequest().
GetErrorMessage()
virtual string IG.Lib.Copy.ServerStreamBase.GetErrorMessage (Exception ex) inline protected virtual
Returns error message corresponding to the specified exception.
Parameters
ex
Definition at line 598 of file ClientServerStreamBase2_Copy.cs.
Referenced by IG.Lib.Copy.ServerStreamBase.ServeInCurrentThread().
ReadRequest()
virtual string IG.Lib.Copy.ServerStreamBase.ReadRequest () inline protected virtual
Reads the next request from the pipe.
Definition at line 612 of file ClientServerStreamBase2_Copy.cs.
References IG.Lib.Copy.ClientServerStreamBase2.InputStream, IG.Lib.Copy.ClientServerStreamBase2.IsError, IG.Lib.Copy.ClientServerStreamBase2.IsMultilineRequest, IG.Lib.Copy.ServerStreamBase.IsResponseSent, IG.Lib.Copy.ClientServerStreamBase2.LastErrorMessage, IG.Lib.Copy.ClientServerStreamBase2.LastException, IG.Lib.Copy.ClientServerStreamBase2.LastRequestString, IG.Lib.ILockable.Lock, IG.Lib.Copy.ClienServerStreamBase.OutputLevel, IG.Lib.Copy.ClientServerStreamBase2.RequestEnd, IG.Lib.Copy.ClientServerStreamBase2.RequestString, IG.Lib.Copy.ClientServerStreamBase2.ResponseString, and IG.Lib.Copy.ClienServerStreamBase.StringBuilderInternal.
Referenced by IG.Lib.Copy.ServerStreamBase.ServeInCurrentThread().
SendResponse() [1/2]
virtual void IG.Lib.Copy.ServerStreamBase.SendResponse (string responseString) inline protected virtual
Sends the specified response string back to the server.
Parameters
responseString
Definition at line 686 of file ClientServerStreamBase2_Copy.cs.
References IG.Lib.Copy.ClientServerStreamBase2.IsMultilineResponse, IG.Lib.Copy.ServerStreamBase.IsResponseSent, IG.Lib.Copy.ClientServerStreamBase2.LastResponseString, IG.Lib.ILockable.Lock, IG.Lib.Copy.ClienServerStreamBase.OutputLevel, IG.Lib.Copy.ClientServerStreamBase2.OutputStream, and IG.Lib.Copy.ClientServerStreamBase2.ResponseEnd.
SendResponse() [2/2]
virtual void IG.Lib.Copy.ServerStreamBase.SendResponse () inline protected virtual
Sends the response (i.e., the ClientServerStreamBase2.ResponseString) back to the client.
Definition at line 727 of file ClientServerStreamBase2_Copy.cs.
References IG.Lib.Copy.ClientServerStreamBase2.ResponseString.
Referenced by IG.Lib.Copy.ServerStreamBase.RespondToRequest(), and IG.Lib.Copy.ServerStreamBase.ServeInCurrentThread().
RespondToRequest()
virtual void IG.Lib.Copy.ServerStreamBase.RespondToRequest () inline protected virtual
Reads a single request from the client and sends back the response.
Definition at line 733 of file ClientServerStreamBase2_Copy.cs.
References IG.Lib.Copy.ServerStreamBase.GetResponse(), IG.Lib.ILockable.Lock, IG.Lib.Copy.ClienServerStreamBase.OutputLevel, IG.Lib.Copy.ClientServerStreamBase2.RequestString, IG.Lib.Copy.ClientServerStreamBase2.ResponseString, IG.Lib.Copy.ServerStreamBase.SendResponse(), IG.Lib.Copy.ClientServerStreamBase2.StoppedResponse, IG.Lib.Copy.ClientServerStreamBase2.StopRequest, and IG.Lib.Copy.ServerStreamBase.StopServe.
Referenced by IG.Lib.Copy.ServerStreamBase.ServeInCurrentThread().
ServeInCurrentThread()
virtual void IG.Lib.Copy.ServerStreamBase.ServeInCurrentThread () inline protected virtual
Enters the serving loop.
Within the loop, only ReadRequest() and RespondToRequest() are executed. The latter must handle things like stopping requests.
Definition at line 777 of file ClientServerStreamBase2_Copy.cs.
References IG.Lib.Copy.ClienServerStreamBase._lock, IG.Lib.Copy.ServerStreamBase.ClearData(), IG.Lib.Copy.ClientServerStreamBase2.ErrorBegin, IG.Lib.Copy.ServerStreamBase.GetErrorMessage(), IG.Lib.Copy.ClientServerStreamBase2.IsError, IG.Lib.Copy.ServerStreamBase.IsServerPipelineConnected(), IG.Lib.Copy.ServerStreamBase.IsServerRunning, IG.Lib.Copy.ClientServerStreamBase2.LastErrorMessage, IG.Lib.Copy.ClientServerStreamBase2.LastException, IG.Lib.ILockable.Lock, IG.Lib.Copy.ClienServerStreamBase.OutputLevel, IG.Lib.Copy.ServerStreamBase.ReadRequest(), IG.Lib.Copy.ServerStreamBase.RespondToRequest(), IG.Lib.Copy.ServerStreamBase.SendResponse(), IG.Lib.Copy.ServerStreamBase.StopServe, and IG.Lib.Copy.ServerStreamBase.WaitForConnection().
Referenced by IG.Lib.Copy.ServerStreamBase.ThreadServe().
ThreadServe()
void IG.Lib.Copy.ServerStreamBase.ThreadServe () inline
Launches a named pipe server in a new thread.
Definition at line 866 of file ClientServerStreamBase2_Copy.cs.
References IG.Lib.Copy.ServerStreamBase._workingThread, IG.Lib.Copy.ServerStreamBase.AbortWorkingThread(), IG.Lib.Copy.ServerStreamBase.IsServerRunning, IG.Lib.ILockable.Lock, IG.Lib.Copy.ClientServerStreamBase2.Name, IG.Lib.Copy.ServerStreamBase.ServeInCurrentThread(), and IG.Lib.Copy.ServerStreamBase.ThreadPriority.
Referenced by IG.Lib.Copy.NamedPipeServerBase.NamedPipeServerBase().
AbortWorkingThread()
void IG.Lib.Copy.ServerStreamBase.AbortWorkingThread (double timeoutSeconds = 0) inline
Aborts the working thread.
Parameters
timeoutSeconds
Definition at line 888 of file ClientServerStreamBase2_Copy.cs.
References IG.Lib.Copy.ServerStreamBase._workingThread, and IG.Lib.Copy.ServerStreamBase.NullifyServerPipeLine().
Referenced by IG.Lib.Copy.ServerStreamBase.ThreadServe().
ClearData()
override void IG.Lib.Copy.ServerStreamBase.ClearData () inline virtual
Clears all the data related to servig requests (i.e. request and response strings, error flags, exceptions, etc.).
Implements IG.Lib.Copy.ClientServerStreamBase2.
Definition at line 919 of file ClientServerStreamBase2_Copy.cs.
References IG.Lib.Copy.ClientServerStreamBase2.IsError, IG.Lib.Copy.ServerStreamBase.IsResponseSent, IG.Lib.Copy.ClientServerStreamBase2.LastErrorMessage, IG.Lib.Copy.ClientServerStreamBase2.LastException, IG.Lib.Copy.ClientServerStreamBase2.LastRequestString, IG.Lib.Copy.ClientServerStreamBase2.LastResponseString, IG.Lib.ILockable.Lock, IG.Lib.Copy.ClientServerStreamBase2.RequestString, and IG.Lib.Copy.ClientServerStreamBase2.ResponseString.
Referenced by IG.Lib.Copy.ServerStreamBase.ServeInCurrentThread().
Member Data Documentation
_stopServe
bool IG.Lib.Copy.ServerStreamBase._stopServe = false private
Definition at line 526 of file ClientServerStreamBase2_Copy.cs.
_isServerRunning
bool IG.Lib.Copy.ServerStreamBase._isServerRunning = false private
Definition at line 533 of file ClientServerStreamBase2_Copy.cs.
_responseMethod
ResponseDelegate IG.Lib.Copy.ServerStreamBase._responseMethod = DefaultResponseMethod private
Definition at line 569 of file ClientServerStreamBase2_Copy.cs.
_workingThread
Thread IG.Lib.Copy.ServerStreamBase._workingThread = null private
Definition at line 842 of file ClientServerStreamBase2_Copy.cs.
Referenced by IG.Lib.Copy.ServerStreamBase.AbortWorkingThread(), and IG.Lib.Copy.ServerStreamBase.ThreadServe().
_threadPriority
ThreadPriority IG.Lib.Copy.ServerStreamBase._threadPriority = UtilSystem.ThreadPriority protected
Definition at line 844 of file ClientServerStreamBase2_Copy.cs.
Property Documentation
IsResponseSent
bool IG.Lib.Copy.ServerStreamBase.IsResponseSent get protected set
Auxiliary flag telling whether response to a request has already been sent to the client. Used for synchronization of diffeeent parts of the response generation process, which enables e.g special handling of Exceptions.
Definition at line 520 of file ClientServerStreamBase2_Copy.cs.
Referenced by IG.Lib.Copy.ServerStreamBase.ClearData(), IG.Lib.Copy.ServerStreamBase.ReadRequest(), and IG.Lib.Copy.ServerStreamBase.SendResponse().
StopServe
bool IG.Lib.Copy.ServerStreamBase.StopServe get protected set
Whether the pipe should be closed.
Definition at line 530 of file ClientServerStreamBase2_Copy.cs.
Referenced by IG.Lib.Copy.ServerStreamBase.RespondToRequest(), IG.Lib.Copy.ServerStreamBase.ServeInCurrentThread(), and IG.Lib.Copy.ServerStreamBase.StopServer().
IsServerRunning
bool IG.Lib.Copy.ServerStreamBase.IsServerRunning get protected set
Flag telling whether the server is currently running.
Definition at line 537 of file ClientServerStreamBase2_Copy.cs.
Referenced by IG.Lib.Copy.ServerStreamBase.ServeInCurrentThread(), IG.Lib.Copy.ServerStreamBase.ThreadServe(), and IG.Lib.Copy.NamedPipeServerBase.ToString().
ResponseMethod
virtual ResponseDelegate IG.Lib.Copy.ServerStreamBase.ResponseMethod get set
Delegate that calculates response to given request.
Definition at line 573 of file ClientServerStreamBase2_Copy.cs.
Referenced by IG.Lib.Copy.ServerStreamBase.GetResponse().
ThreadPriority
ThreadPriority IG.Lib.Copy.ServerStreamBase.ThreadPriority get set
Priority of the server thread.
Setting priority changes priority of the server thread if it exists.
Definition at line 849 of file ClientServerStreamBase2_Copy.cs.
Referenced by IG.Lib.Copy.ServerStreamBase.ThreadServe().
The documentation for this class was generated from the following file:
iglib/igbase/data/streams/streams_copy/ClientServerStreamBase2_Copy.cs