Doc: IGLib with source files: IG.Gr.GraphicSetBase Class Reference
IG.Gr.GraphicSetBase Class Reference
Base class for graphic sets that contain groups of graphic primitives.
Public Member Functions
IGraphicSet GetChildSet (int i)
Returns the specified child graphic set contained in the current graphic set.
IGraphicPrimitive GetChildPrimitive (int i)
Returns the specified child graphic primitive contained in the current graphic set.
virtual void ReCalculateBounds (bool recursive)
Recalculates the bounding box of the current graphic set.
virtual void RecalculateBounds ()
Properties
IGraphicSet Parent [get, protected set]
int NumGraphicSets [get]
Gets number of child graphic sets directly contained in the current graphic set.
int NumGraphicPrimitives [get]
Gets number of child graphic primitives directly contained in the current graphic set.
IBoundingBox Bounds [get]
Private Attributes
IGraphicSet _parent
List< IGraphicSet > _childSets = new List<IGraphicSet>()
List< IGraphicPrimitive > _childPrimitives = new List<IGraphicPrimitive>()
BoundingBox3d _bounds = new BoundingBox3d()
Detailed Description
Base class for graphic sets that contain groups of graphic primitives.
$A Igor Mar10 Nov10;
Definition at line 22 of file GraphicalObjectsBase.cs.
Member Function Documentation
GetChildSet()
IGraphicSet IG.Gr.GraphicSetBase.GetChildSet (int i) inline
Returns the specified child graphic set contained in the current graphic set.
Parameters
i Index of the child graphic set.
Definition at line 44 of file GraphicalObjectsBase.cs.
References IG.Gr.GraphicSetBase._childSets.
GetChildPrimitive()
IGraphicPrimitive IG.Gr.GraphicSetBase.GetChildPrimitive (int i) inline
Returns the specified child graphic primitive contained in the current graphic set.
Parameters
i Index of the child graphic primitive.
Definition at line 59 of file GraphicalObjectsBase.cs.
References IG.Gr.GraphicSetBase._childPrimitives.
ReCalculateBounds()
virtual void IG.Gr.GraphicSetBase.ReCalculateBounds (bool recursive) inline virtual
Recalculates the bounding box of the current graphic set.
Parameters
recursive If true then bounds of sub-sets are re-calculated recursively.
Definition at line 87 of file GraphicalObjectsBase.cs.
References IG.Gr.GraphicSetBase.NumGraphicPrimitives.
Referenced by IG.Gr.GraphicSetBase.RecalculateBounds().
RecalculateBounds()
virtual void IG.Gr.GraphicSetBase.RecalculateBounds () inline virtual
Definition at line 97 of file GraphicalObjectsBase.cs.
References IG.Gr.GraphicSetBase.ReCalculateBounds().
Member Data Documentation
_parent
IGraphicSet IG.Gr.GraphicSetBase._parent private
Definition at line 25 of file GraphicalObjectsBase.cs.
_childSets
List<IGraphicSet> IG.Gr.GraphicSetBase._childSets = new List<IGraphicSet>() private
Definition at line 40 of file GraphicalObjectsBase.cs.
Referenced by IG.Gr.GraphicSetBase.GetChildSet().
_childPrimitives
List<IGraphicPrimitive> IG.Gr.GraphicSetBase._childPrimitives = new List<IGraphicPrimitive>() private
Definition at line 49 of file GraphicalObjectsBase.cs.
Referenced by IG.Gr.GraphicSetBase.GetChildPrimitive().
_bounds
BoundingBox3d IG.Gr.GraphicSetBase._bounds = new BoundingBox3d() private
Definition at line 65 of file GraphicalObjectsBase.cs.
Property Documentation
Parent
IGraphicSet IG.Gr.GraphicSetBase.Parent get protected set
Definition at line 28 of file GraphicalObjectsBase.cs.
NumGraphicSets
int IG.Gr.GraphicSetBase.NumGraphicSets get
Gets number of child graphic sets directly contained in the current graphic set.
Definition at line 36 of file GraphicalObjectsBase.cs.
NumGraphicPrimitives
int IG.Gr.GraphicSetBase.NumGraphicPrimitives get
Gets number of child graphic primitives directly contained in the current graphic set.
Definition at line 53 of file GraphicalObjectsBase.cs.
Referenced by IG.Gr.GraphicSetBase.ReCalculateBounds().
Bounds
IBoundingBox IG.Gr.GraphicSetBase.Bounds get private
Definition at line 69 of file GraphicalObjectsBase.cs.
The documentation for this class was generated from the following file:
iglib/igbase/graphics/grobjects/GraphicalObjectsBase.cs