Doc: IGLib with source files: IG.Net.PortScanner2 Class Reference
IG.Net.PortScanner2 Class Reference
A TCP port scanner, multi-threaded.
Classes
class isTcpPortOpen
class PortList2
Public Member Functions
PortScanner2 (string host, int portStart, int portStop, int timeout)
void start (int threadCounter)
void RunScanTcp ()
TcpClient Connect (string hostName, int port, int timeout)
string BannerGrab (string hostName, int port, int timeout)
Static Public Member Functions
static void Run (string[] args)
A Console type Multi Port TCP Scanner Author : Philip Murray
Public Attributes
int tcpTimeout
Private Member Functions
void AsyncCallback (IAsyncResult asyncResult)
Static Private Member Functions
static string GetPageTitle (string link)
Private Attributes
string host
PortList2 portList
bool turnOff = true
int count = 0
Detailed Description
A TCP port scanner, multi-threaded.
Basic idea taken from this project: https://github.com/PhilipMur/C-Sharp-Multi-Threaded-Port-Scanner
by Philip Murray (MIT license, see LICENSE.txt).
$A Philip_Murray xx; Igor Apr18;
Definition at line 16 of file PortScanner.cs.
Constructor & Destructor Documentation
PortScanner2()
IG.Net.PortScanner2.PortScanner2 (string host, int portStart, int portStop, int timeout) inline
Definition at line 32 of file PortScanner.cs.
References IG.Net.PortScanner2.host, IG.Net.PortScanner2.portList, and IG.Net.PortScanner2.tcpTimeout.
Member Function Documentation
start()
void IG.Net.PortScanner2.start (int threadCounter) inline
Definition at line 40 of file PortScanner.cs.
References IG.Net.PortScanner2.RunScanTcp().
Referenced by IG.Net.PortScanner2.Run().
RunScanTcp()
void IG.Net.PortScanner2.RunScanTcp () inline
Definition at line 52 of file PortScanner.cs.
References IG.Net.PortScanner2.BannerGrab(), IG.Net.PortScanner2.Connect(), IG.Net.PortScanner2.count, IG.Net.PortScanner2.GetPageTitle(), IG.Net.PortScanner2.host, IG.Net.PortScanner2.PortList2.NextPort(), IG.Net.PortScanner2.portList, IG.Net.PortScanner2.tcpTimeout, and IG.Net.PortScanner2.turnOff.
Referenced by IG.Net.PortScanner2.start().
Connect()
TcpClient IG.Net.PortScanner2.Connect (string hostName, int port, int timeout) inline
Definition at line 129 of file PortScanner.cs.
References IG.Net.PortScanner2.AsyncCallback(), and IG.Net.PortScanner2.isTcpPortOpen.tcpOpen.
Referenced by IG.Net.PortScanner2.RunScanTcp().
BannerGrab()
string IG.Net.PortScanner2.BannerGrab (string hostName, int port, int timeout) inline
Definition at line 151 of file PortScanner.cs.
Referenced by IG.Net.PortScanner2.RunScanTcp().
AsyncCallback()
void IG.Net.PortScanner2.AsyncCallback (IAsyncResult asyncResult) inline private
Definition at line 177 of file PortScanner.cs.
Referenced by IG.Net.PortScanner2.Connect().
GetPageTitle()
static string IG.Net.PortScanner2.GetPageTitle (string link) inline static private
Definition at line 199 of file PortScanner.cs.
Referenced by IG.Net.PortScanner2.RunScanTcp().
Run()
static void IG.Net.PortScanner2.Run (string[] args) inline static
A Console type Multi Port TCP Scanner Author : Philip Murray
Definition at line 230 of file PortScanner.cs.
References IG.Net.PortScanner2.start().
Member Data Documentation
host
string IG.Net.PortScanner2.host private
Definition at line 19 of file PortScanner.cs.
Referenced by IG.Net.PortScanner2.PortScanner2(), and IG.Net.PortScanner2.RunScanTcp().
portList
PortList2 IG.Net.PortScanner2.portList private
Definition at line 20 of file PortScanner.cs.
Referenced by IG.Net.PortScanner2.PortScanner2(), and IG.Net.PortScanner2.RunScanTcp().
turnOff
bool IG.Net.PortScanner2.turnOff = true private
Definition at line 21 of file PortScanner.cs.
Referenced by IG.Net.PortScanner2.RunScanTcp().
count
int IG.Net.PortScanner2.count = 0 private
Definition at line 22 of file PortScanner.cs.
Referenced by IG.Net.PortScanner2.RunScanTcp().
tcpTimeout
int IG.Net.PortScanner2.tcpTimeout
Definition at line 23 of file PortScanner.cs.
Referenced by IG.Net.PortScanner2.PortScanner2(), and IG.Net.PortScanner2.RunScanTcp().
The documentation for this class was generated from the following file:
iglib/igbase/utilities/networking/PortScannerComplex/PortScanner.cs