Doc: IGLib with source files: IGLib.Gr3D.TubularMeshGenerator_06 Class Reference
IGLib.Gr3D.TubularMeshGenerator_06 Class Reference
Generates tubular surface meshes around space curves using Frenet or Parallel Transport Frames.
Public Member Functions
vec3 NumericalDerivative (Func< double, vec3 > curve, double t, double tMin, double tMax, double h, bool restrictToInterval)
Numerically computes the derivative of a curve using central differences.
StructuredSurfaceMesh3D GenerateMesh (Func< double, vec3 > curve, double tStart, double tEnd, double radius, int numCurvePoints, int numCirclePoints, double hrel=1e-2, double eps=0.1, bool normalizeFromPrevious=false, bool restrictToInterval=false)
Generates a tubular mesh using the Parallel Transport Frame (PTF) and numerical tangent vectors.
StructuredSurfaceMesh3D GenerateMesh (Func< double, vec3 > curve, Func< double, vec3 > tangent, double tStart, double tEnd, double radius, int numCurvePoints, int numCirclePoints, double eps=0.1, bool normalizeFromPrevious=false)
Generates a tubular mesh using the Parallel Transport Frame (PTF) and analytical tangent vectors.
StructuredSurfaceMesh3D GenerateFrenet (Func< double, vec3 > curve, double tStart, double tEnd, double radius, int numCurvePoints, int numCirclePoints, double hrel=1e-3, bool restrictToInterval=false)
Generates a tubular mesh from the specified parametric curve using the Frenet frame and numerically calculated tangent vector.
StructuredSurfaceMesh3D GenerateMeshByFrenet (Func< double, vec3 > curve, Func< double, vec3 > tangent, double tStart, double tEnd, double radius, int numCurvePoints, int numCirclePoints, double h=1e-3)
Generates a tubular mesh using the Frenet frame and analytical or fallback tangent function.
Properties
static TubularMeshGenerator_06 Global = new TubularMeshGenerator_06() [get]
Global lazy-initialized instance of the mesh generator.
Detailed Description
Generates tubular surface meshes around space curves using Frenet or Parallel Transport Frames.
Definition at line 14 of file TubularMeshGenerator_06.cs.
Member Function Documentation
NumericalDerivative()
vec3 IGLib.Gr3D.TubularMeshGenerator_06.NumericalDerivative (Func< double, vec3 > curve, double t, double tMin, double tMax, double h, bool restrictToInterval) inline
Numerically computes the derivative of a curve using central differences.
Definition at line 24 of file TubularMeshGenerator_06.cs.
Referenced by IGLib.Gr3D.TubularMeshGenerator_06.GenerateFrenet(), IGLib.Gr3D.TubularMeshGenerator_06.GenerateMesh(), and IGLib.Gr3D.TubularMeshGenerator_06.GenerateMeshByFrenet().
GenerateMesh() [1/2]
StructuredSurfaceMesh3D IGLib.Gr3D.TubularMeshGenerator_06.GenerateMesh (Func< double, vec3 > curve, double tStart, double tEnd, double radius, int numCurvePoints, int numCirclePoints, double hrel = 1e-2, double eps = 0.1, bool normalizeFromPrevious = false, bool restrictToInterval = false) inline
Generates a tubular mesh using the Parallel Transport Frame (PTF) and numerical tangent vectors.
Parameters
curve Definition of the parametric curve used to generate the tubular surface.
tStart Starting parameter.
tEnd Ending parameter.
radius Radius of the circular tube.
numCurvePoints Number of mesh points along the curve.
numCirclePoints Number of mesh points around the circumference of the tube.
hrel Specification of step for numerical differentiation, relative to the meshing step (difference in parameter between meshing points).
eps Specifies how close to parallel to a tangent can a unit vector be at most, to still be eligible to generate the first normal to the tangent via orthogonalization. Should be less than 0.5; normally it should be less than 0.2, also 0.05 could be a good value. If scalar product of the tangential unit vector and the candidate unit vector minus 1.0 is less than eps then the candidate vector is not taken into account because it is too parallel to the tangent.
normalizeFromPrevious If true then the second normal is calculated from previous normal by orthogonalization. Otherwise, it is calculated by a vector product of the tangent and the first normal. Default is false.
restrictToInterval Whether evaluations of the curve points must be limited to the meshing interval. If true then the step for numerical differentiation must be taken in such a way that all vurve evaluations fall within the meshing interval, end ponts inclusive. Ths is useful when the function has a singularity or sidcontinuity just outside the meshing interval.
Definition at line 61 of file TubularMeshGenerator_06.cs.
References IGLib.Gr3D.TubularMeshGenerator_06.NumericalDerivative().
Referenced by IGLib.Gr3D.TubularSurfaceExamples.Example_06(), and IGLib.Gr3D.TubularMeshGenerator_06.GenerateMesh().
GenerateMesh() [2/2]
StructuredSurfaceMesh3D IGLib.Gr3D.TubularMeshGenerator_06.GenerateMesh (Func< double, vec3 > curve, Func< double, vec3 > tangent, double tStart, double tEnd, double radius, int numCurvePoints, int numCirclePoints, double eps = 0.1, bool normalizeFromPrevious = false) inline
Generates a tubular mesh using the Parallel Transport Frame (PTF) and analytical tangent vectors.
Parameters
tangent Function that defines derivative of curve with respect to parameter.
For undocumented parameters, see GenerateMesh(Func<double, vec3>, double, double, double, int, int, double, double, bool, bool).
Definition at line 87 of file TubularMeshGenerator_06.cs.
References IG.Num.vec3.Cross(), IG.Num.vec3.Dot(), IGLib.Gr3D.TubularMeshGenerator_06.GenerateMesh(), and IG.Num.vec3.Normalize().
GenerateFrenet()
StructuredSurfaceMesh3D IGLib.Gr3D.TubularMeshGenerator_06.GenerateFrenet (Func< double, vec3 > curve, double tStart, double tEnd, double radius, int numCurvePoints, int numCirclePoints, double hrel = 1e-3, bool restrictToInterval = false) inline
Generates a tubular mesh from the specified parametric curve using the Frenet frame and numerically calculated tangent vector.
This method of generating the mesh will lead to a "pinched pipe mesh" in ponts where the swcond derivative changes direction because the normals that define meshning around circumberence change direections by full angle (180 degrees).
For parameter descriprions, see GenerateMesh(Func<double, vec3>, double, double, double, int, int, double, double, bool, bool).
Definition at line 171 of file TubularMeshGenerator_06.cs.
References IGLib.Gr3D.TubularMeshGenerator_06.GenerateMeshByFrenet(), and IGLib.Gr3D.TubularMeshGenerator_06.NumericalDerivative().
Referenced by IGLib.Gr3D.TubularMeshGenerator_06.GenerateMeshByFrenet().
GenerateMeshByFrenet()
StructuredSurfaceMesh3D IGLib.Gr3D.TubularMeshGenerator_06.GenerateMeshByFrenet (Func< double, vec3 > curve, Func< double, vec3 > tangent, double tStart, double tEnd, double radius, int numCurvePoints, int numCirclePoints, double h = 1e-3) inline
Generates a tubular mesh using the Frenet frame and analytical or fallback tangent function.
The same as GenerateMeshByFrenet(Func<double, vec3>, Func<double, vec3>, double, double, double, int, int, double), except that analytical curve derivative (tangent) is used (specified by tangent) and we don't need to calculate derivatives numerically.
For parameter descriprions, see GenerateMesh(Func<double, vec3>, double, double, double, int, int, double, double, bool, bool).
Definition at line 193 of file TubularMeshGenerator_06.cs.
References IG.Num.vec3.Cross(), IG.Num.vec3.Dot(), IGLib.Gr3D.TubularMeshGenerator_06.GenerateFrenet(), IG.Num.vec3.Normalize(), and IGLib.Gr3D.TubularMeshGenerator_06.NumericalDerivative().
Referenced by IGLib.Gr3D.TubularMeshGenerator_06.GenerateFrenet().
Property Documentation
Global
TubularMeshGenerator_06 IGLib.Gr3D.TubularMeshGenerator_06.Global = new TubularMeshGenerator_06() static get
Global lazy-initialized instance of the mesh generator.
Definition at line 19 of file TubularMeshGenerator_06.cs.
Referenced by IGLib.Gr3D.TubularSurfaceExamples.Example_06().
The documentation for this class was generated from the following file:
IGLibGraphics3D/src/IGLib.Graphics3D/Graphics3D/Historical/TubularMeshGenerator_06.cs