Doc: IGLib with source files: IG.Neural.MappingApproximationFileManager Class Reference
IG.Neural.MappingApproximationFileManager Class Reference
File manager for mapping file client and server.
Public Member Functions
MappingApproximationFileManager (string directoryPath)
Constructs a new file manager for mapping approximation file client/server that operates in the specified directory.
MappingApproximationFileManager (string directoryPath, DataMapperSimple mapper)
void SetFunctionInputReady ()
Sets the falg that indicates that the reduced approximation input data is ready.
void ClearFunctionInputReady ()
Clears the falg that indicates that the reduced approximation input data is ready.
bool IsFunctionInputReady ()
Returns value of the falg that indicates whether the reduced approximation input data is ready.
void SetFunctionOutputReady ()
Sets the falg that indicates that the reduced approximation output data is ready.
void ClearFunctionOutputReady ()
Clears the falg that indicates that the reduced approximation output data is ready.
bool IsFunctionOutputReady ()
Returns value of the falg that indicates whether the reduced approximation output data is ready.
void ClearMessages ()
Clears all messages for neural approximation client and server.
virtual void ReadFunctionInput (ref IVector inputParameters)
Reads function reduced input parameters form the file at standard location.
virtual void WriteFunctionInput (IVector inputParameters)
Writes function reduced input parameters to standard location.
virtual void ReadFunctionOutput (ref IVector outputValues)
Reads Function reduced output values from the file at standard location.
virtual void WriteFunctionOutput (IVector outputValues)
Writes function reduced outut values to the file at standard location.
virtual void LoadDataDefinition (ref InputOutputDataDefiniton definitionData)
Loads the definition data from the file at standard location.
virtual void LoadMappingDefinition (ref MappingDefinition mappingDefinition)
Loads the mapping definition data from the file at standard location.
virtual void ClientTestCalculateMappingApproximation (string functionInputFilePath, string functionOutputFilePath)
Performs client-side test calculation of neural network based approximation where input parameters are read from a specified function JSON file with reduced input parameters, copies to specified JSON file with total inputs and calculated output values are written to the specified file.
virtual void ServerCalculateMappingApproximation ()
Performs neural network-based approximation at prescribed reduced input parameters and saves results. Messages are set and cleared appropriately. This method read reduced input parameters from standard location, mapps input parameters, loads trained neural network, calculates approximated outpur values, mapps output values, and stores them to the standard location.
Public Member Functions inherited from IG.Neural.NeuraApproximationFileManager
NeuraApproximationFileManager (string directoryPath)
Nonstruct a new file manager for neural approximation file client/server that operates in the specified directory.
string GetPath (string fileOrDirectoryName)
Returns full path of the file or directory with the specified relative path within the data directory of the current file server/client.
void SetNeuralBusy ()
Sets the falg that indicates that the approximation server is busy.
void ClearNeuralBusy ()
Clears the falg that indicates that the approximation server is busy.
bool IsNeuralBusy ()
Returns value of the falg that indicates whether the approximation server is busy.
void SetNeuralInputReady ()
Sets the falg that indicates that the approximation input data is ready.
void ClearNeuralInputReady ()
Clears the falg that indicates that the approximation input data is ready.
bool IsNeuralInputReady ()
Returns value of the falg that indicates whether the approximation input data is ready.
void SetNeuralOutputReady ()
Sets the falg that indicates that the approximation output data is ready.
void ClearNeuralOutputReady ()
Clears the falg that indicates that the approximation output data is ready.
bool IsNeuralOutputReady ()
Returns value of the falg that indicates whether the approximation output data is ready.
void ClearMessages ()
Clears all messages for neural approximation client and server.
virtual void ReadNeuralInput (ref IVector inputParameters)
Reads neural approximator input parameters form the file at standard location.
virtual void WriteNeuralInput (IVector inputParameters)
Writes neural approximator input parameters to standard location.
virtual void ReadNeuralOutput (ref IVector outputValues)
Reads neural approximator output values from the file at standard location.
virtual void WriteNeuralOutput (IVector outputValues)
Writes neural approximator outut values to the file at standard location.
virtual void LoadNeuralNetwork (ref INeuralApproximator trainedNetwork)
Loads the trained neural network approximator from the file at standard location.
virtual void ClientWriteNeuralInput (IVector inputParameters)
Client writes input parameters for calculation of neural network based approximated values. Messages are set nad clears appropriately.
virtual void ClientReadNeuralOutput (ref IVector outputValues)
Client reads the results of neural network-based approximation (output values). Messages are set and clears appropriately.
virtual void ClientSendRequestCalculateApproximation ()
Performs request to the server for calculation of neural network based approximated values.
virtual void ClientCalculateApproximation (IVector inputParameters, ref IVector outputValues)
Calculates approximation by using the neural network approximation server.
virtual void ClientTestCalculateApproximation (string inputFilePath, string outputFilePath)
Performs client-side test calculation of neural network based approximation where input parameters are read from a specified JSON file, and calculated output values are written to the specified file.
virtual void ServerCalculateApproximation ()
Performs neural network-based approximation at prescribed input parameters and saves results. Messages are set and cleared appropriately. This method read input parameters from standard location, loads trained neural network, calculates approximated outpur values and stores them to the standard location.
Properties
static DataMapperIdentity Aux [get]
Initialize DataMapperIdentity object for identity copying.
IDataMapper MapperDefinition [get, set]
Initialize DataMapperIdentity object for identity copying if mapper is null. Setter takes DataMapperSimple object.
string MappingDefinitionPath [get, protected set]
File path of the input and output mapping definition file. Setter takes only pure file name, without path information. If set to null then file path is set to null and will be recalculated when getter is called.
string FunctionInputPath [get, protected set]
File path of the file with reduced input parameters. Setter takes only pure file name, without path information. If set to null then file path is set to null and will be recalculated when getter is called.
string FunctionOutputPath [get, protected set]
File path of the file for storing reduced approximated output values. Setter takes only pure file name, without path information. If set to null then file path is set to null and will be recalculated when getter is called.
string MsgFunctionInputReadyPath [get, protected set]
File path of the message file indicating that reduced input data is ready to be processed. Setter takes only pure file name, without path information. If set to null then file path is set to null and will be recalculated when getter is called.
string MsgFunctionOutputReadyPath [get, protected set]
File path of the message file indicating that the reduced approximated output is ready to be read. Setter takes only pure file name, without path information. If set to null then file path is set to null and will be recalculated when getter is called.
Properties inherited from IG.Neural.NeuraApproximationFileManager
object Lock [get]
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
object InternalLock [get]
Used internally for locking access to internal fields.
string DataDirectory [get, protected set]
Directory for data and messages exchange through files.
string NeuralNetworkPath [get, protected set]
File path of the file where complete (usually trained) neural network is stored. Setter takes only pure file name, without path information. If set to null then file path is set to null and will be recalculated when getter is called.
string NeuralDataDefinitionPath [get, protected set]
File path of the input and output data definition file. Setter takes only pure file name, without path information. If set to null then file path is set to null and will be recalculated when getter is called.
string SimulationDataDefinitionPath [get, protected set]
File path of the input and output data definition file for simulator. Setter takes only pure file name, without path information. If set to null then file path is set to null and will be recalculated when getter is called.
string NeuralVerificationDataPath [get, protected set]
File path of the verification data file. Setter takes only pure file name, without path information. If set to null then file path is set to null and will be recalculated when getter is called.
string NeuralTrainingDataPath [get, protected set]
File path of the training data file. Setter takes only pure file name, without path information. If set to null then file path is set to null and will be recalculated when getter is called.
string NeuralInputPath [get, protected set]
File path of the file with input parameters. Setter takes only pure file name, without path information. If set to null then file path is set to null and will be recalculated when getter is called.
string NeuralInputXmlPath [get, protected set]
File path of the input parameters file in XML format. Setter takes only pure file name, without path information. If set to null then file path is set to null and will be recalculated when getter is called.
string NeuralOutputPath [get, protected set]
File path of the file for storing approximated output values. Setter takes only pure file name, without path information. If set to null then file path is set to null and will be recalculated when getter is called.
string NeuralOutputeXmlPath [get, protected set]
File path of the file for storing approximated output values in XML format. Setter takes only pure file name, without path information. If set to null then file path is set to null and will be recalculated when getter is called.
string MsgNeuralBusyPath [get, protected set]
File path of the message file indicating that approximator is busy by performing a job. Setter takes only pure file name, without path information. If set to null then file path is set to null and will be recalculated when getter is called.
string MsgNeuralInputReadyPath [get, protected set]
File path of the message file indicating taht input data is ready to be processed. Setter takes only pure file name, without path information. If set to null then file path is set to null and will be recalculated when getter is called.
string MsgNeuralOutputReadyPath [get, protected set]
File path of the message file indicating that the approximated output is ready to be read. Setter takes only pure file name, without path information. If set to null then file path is set to null and will be recalculated when getter is called.
Properties inherited from IG.Lib.ILockable
object Lock [get]
Private Member Functions
MappingApproximationFileManager ()
Private Attributes
string _mappingDefinitionFilename = NeuralFileConst.MappingDefinitionFilename
string _mappingDefinitionPath = null
string _functionInputFilename = NeuralFileConst.FunctionInputFilename
string _functionInputPath = null
string _functionOutputFilename = NeuralFileConst.FunctiOutputFilename
string _functionOutputPath = null
string _msgFunctionInputReadyFilename = NeuralFileConst.MsgFunctionInputReadyFilename
string _msgFunctionInputReadyPath = null
string _msgFunctionOutputReadyFilename = NeuralFileConst.MsgFunctionOutputReadyFilename
string _msgFunctionOutputReadyPath = null
IDataMapper _mapperDefinition = null
Static Private Attributes
static DataMapperIdentity _aux = null
Additional Inherited Members
Protected Attributes inherited from IG.Neural.NeuraApproximationFileManager
string _dataDirectory = null
Detailed Description
File manager for mapping file client and server.
$A tako78 Jul11; Igor Jul11;
Definition at line 799 of file NeuralFileManager.cs.
Constructor & Destructor Documentation
MappingApproximationFileManager() [1/3]
IG.Neural.MappingApproximationFileManager.MappingApproximationFileManager () inline private
Definition at line 805 of file NeuralFileManager.cs.
MappingApproximationFileManager() [2/3]
IG.Neural.MappingApproximationFileManager.MappingApproximationFileManager (string directoryPath) inline
Constructs a new file manager for mapping approximation file client/server that operates in the specified directory.
Parameters
directoryPath Operation directory for data and message exchange through files.
$A Igor Jul, tako78 Jul
Definition at line 812 of file NeuralFileManager.cs.
References IG.Neural.MappingApproximationFileManager.LoadDataDefinition(), IG.Neural.MappingApproximationFileManager.LoadMappingDefinition(), IG.Neural.MappingApproximationFileManager.MapperDefinition, IG.Neural.MappingApproximationFileManager.MappingDefinitionPath, and IG.Neural.NeuraApproximationFileManager.NeuralDataDefinitionPath.
MappingApproximationFileManager() [3/3]
IG.Neural.MappingApproximationFileManager.MappingApproximationFileManager (string directoryPath, DataMapperSimple mapper) inline
Parameters
directoryPath
mapper
$A Igor Jul, tako78 Jul
Definition at line 833 of file NeuralFileManager.cs.
References IG.Neural.MappingApproximationFileManager.MapperDefinition.
Member Function Documentation
SetFunctionInputReady()
void IG.Neural.MappingApproximationFileManager.SetFunctionInputReady () inline
Sets the falg that indicates that the reduced approximation input data is ready.
$A tako78 Jul.21
Definition at line 1069 of file NeuralFileManager.cs.
References IG.Neural.NeuraApproximationFileManager.Lock, and IG.Neural.MappingApproximationFileManager.MsgFunctionInputReadyPath.
ClearFunctionInputReady()
void IG.Neural.MappingApproximationFileManager.ClearFunctionInputReady () inline
Clears the falg that indicates that the reduced approximation input data is ready.
$A tako78 Jul.21
Definition at line 1084 of file NeuralFileManager.cs.
References IG.Neural.NeuraApproximationFileManager.Lock, and IG.Neural.MappingApproximationFileManager.MsgFunctionInputReadyPath.
Referenced by IG.Neural.MappingApproximationFileManager.ClearMessages(), and IG.Neural.MappingApproximationFileManager.ServerCalculateMappingApproximation().
IsFunctionInputReady()
bool IG.Neural.MappingApproximationFileManager.IsFunctionInputReady () inline
Returns value of the falg that indicates whether the reduced approximation input data is ready.
$A tako78 Jul.21
Definition at line 1096 of file NeuralFileManager.cs.
References IG.Neural.NeuraApproximationFileManager.Lock, and IG.Neural.MappingApproximationFileManager.MsgFunctionInputReadyPath.
Referenced by IG.Neural.MappingApproximationFileManager.ServerCalculateMappingApproximation().
SetFunctionOutputReady()
void IG.Neural.MappingApproximationFileManager.SetFunctionOutputReady () inline
Sets the falg that indicates that the reduced approximation output data is ready.
$A tako78 Jul.21
Definition at line 1110 of file NeuralFileManager.cs.
References IG.Neural.NeuraApproximationFileManager.Lock, and IG.Neural.MappingApproximationFileManager.MsgFunctionOutputReadyPath.
Referenced by IG.Neural.MappingApproximationFileManager.ServerCalculateMappingApproximation().
ClearFunctionOutputReady()
void IG.Neural.MappingApproximationFileManager.ClearFunctionOutputReady () inline
Clears the falg that indicates that the reduced approximation output data is ready.
$A tako78 Jul.21
Definition at line 1125 of file NeuralFileManager.cs.
References IG.Neural.NeuraApproximationFileManager.Lock, and IG.Neural.MappingApproximationFileManager.MsgFunctionOutputReadyPath.
Referenced by IG.Neural.MappingApproximationFileManager.ClearMessages(), and IG.Neural.MappingApproximationFileManager.ServerCalculateMappingApproximation().
IsFunctionOutputReady()
bool IG.Neural.MappingApproximationFileManager.IsFunctionOutputReady () inline
Returns value of the falg that indicates whether the reduced approximation output data is ready.
$A tako78 Jul.21
Definition at line 1137 of file NeuralFileManager.cs.
References IG.Neural.NeuraApproximationFileManager.Lock, and IG.Neural.MappingApproximationFileManager.MsgFunctionOutputReadyPath.
Referenced by IG.Neural.MappingApproximationFileManager.ServerCalculateMappingApproximation().
ClearMessages()
void IG.Neural.MappingApproximationFileManager.ClearMessages () inline
Clears all messages for neural approximation client and server.
$A tako78 Jul.21
Definition at line 1151 of file NeuralFileManager.cs.
References IG.Neural.MappingApproximationFileManager.ClearFunctionInputReady(), and IG.Neural.MappingApproximationFileManager.ClearFunctionOutputReady().
ReadFunctionInput()
virtual void IG.Neural.MappingApproximationFileManager.ReadFunctionInput (ref IVector inputParameters) inline virtual
Reads function reduced input parameters form the file at standard location.
Parameters
inputParameters Object where parameters are stored.
$A tako78 Jul.21
Definition at line 1168 of file NeuralFileManager.cs.
References IG.Neural.MappingApproximationFileManager.FunctionInputPath, and IG.Num.VectorBase.LoadJson().
Referenced by IG.Neural.MappingApproximationFileManager.ServerCalculateMappingApproximation().
WriteFunctionInput()
virtual void IG.Neural.MappingApproximationFileManager.WriteFunctionInput (IVector inputParameters) inline virtual
Writes function reduced input parameters to standard location.
Parameters
inputParameters Parameters to be written.
$A tako78 Jul.21
Definition at line 1176 of file NeuralFileManager.cs.
References IG.Neural.MappingApproximationFileManager.FunctionInputPath, and IG.Num.VectorBase.SaveJson().
ReadFunctionOutput()
virtual void IG.Neural.MappingApproximationFileManager.ReadFunctionOutput (ref IVector outputValues) inline virtual
Reads Function reduced output values from the file at standard location.
Parameters
outputValues Object where the read outut values are stored.
$A tako78 Jul.21
Definition at line 1184 of file NeuralFileManager.cs.
References IG.Neural.MappingApproximationFileManager.FunctionOutputPath, and IG.Num.VectorBase.LoadJson().
WriteFunctionOutput()
virtual void IG.Neural.MappingApproximationFileManager.WriteFunctionOutput (IVector outputValues) inline virtual
Writes function reduced outut values to the file at standard location.
Parameters
outputValues Output values that are written.
$A tako78 Jul.21
Definition at line 1192 of file NeuralFileManager.cs.
References IG.Neural.MappingApproximationFileManager.FunctionOutputPath, and IG.Num.VectorBase.SaveJson().
Referenced by IG.Neural.MappingApproximationFileManager.ClientTestCalculateMappingApproximation(), and IG.Neural.MappingApproximationFileManager.ServerCalculateMappingApproximation().
LoadDataDefinition()
virtual void IG.Neural.MappingApproximationFileManager.LoadDataDefinition (ref InputOutputDataDefiniton definitionData) inline virtual
Loads the definition data from the file at standard location.
Parameters
definitionData Object where the definition data is stored.
$A tako78 Jul.21
Definition at line 1200 of file NeuralFileManager.cs.
References IG.Num.InputOutputDataDefiniton.LoadJson(), and IG.Neural.NeuraApproximationFileManager.NeuralDataDefinitionPath.
Referenced by IG.Neural.MappingApproximationFileManager.ClientTestCalculateMappingApproximation(), IG.Neural.MappingApproximationFileManager.MappingApproximationFileManager(), and IG.Neural.MappingApproximationFileManager.ServerCalculateMappingApproximation().
LoadMappingDefinition()
virtual void IG.Neural.MappingApproximationFileManager.LoadMappingDefinition (ref MappingDefinition mappingDefinition) inline virtual
Loads the mapping definition data from the file at standard location.
Parameters
mappingDefinition Object where the mapping definition is stored.
$A tako78 Jul.21
Definition at line 1208 of file NeuralFileManager.cs.
References IG.Neural.MappingDefinition.LoadJson(), and IG.Neural.MappingApproximationFileManager.MappingDefinitionPath.
Referenced by IG.Neural.MappingApproximationFileManager.ClientTestCalculateMappingApproximation(), IG.Neural.MappingApproximationFileManager.MappingApproximationFileManager(), and IG.Neural.MappingApproximationFileManager.ServerCalculateMappingApproximation().
ClientTestCalculateMappingApproximation()
virtual void IG.Neural.MappingApproximationFileManager.ClientTestCalculateMappingApproximation (string functionInputFilePath, string functionOutputFilePath) inline virtual
Performs client-side test calculation of neural network based approximation where input parameters are read from a specified function JSON file with reduced input parameters, copies to specified JSON file with total inputs and calculated output values are written to the specified file.
Parameters
functionInputFilePath Path to the JSON file where input parameters are read from. The file pointed at must exist.
functionOutputFilePath Path of a file where the calculated approximated values are written to. It can be null or empty string, in this case parameters are not written to a file (but they are still output on console).
$A tako78 Jul;
Definition at line 1230 of file NeuralFileManager.cs.
References IG.Neural.MappingApproximationFileManager.Aux, IG.Neural.NeuraApproximationFileManager.ClientTestCalculateApproximation(), IG.Neural.MappingApproximationFileManager.FunctionOutputPath, IG.Neural.MappingApproximationFileManager.LoadDataDefinition(), IG.Num.VectorBase.LoadJson(), IG.Neural.MappingApproximationFileManager.LoadMappingDefinition(), IG.Neural.IDataMapper.MapInput(), IG.Neural.DataMapperIdentity.MapInput(), IG.Neural.IDataMapper.MapOutput(), IG.Neural.DataMapperIdentity.MapOutput(), IG.Neural.MappingApproximationFileManager.MapperDefinition, IG.Neural.MappingApproximationFileManager.MappingDefinitionPath, IG.Neural.NeuraApproximationFileManager.NeuralDataDefinitionPath, IG.Neural.NeuraApproximationFileManager.NeuralInputPath, IG.Neural.NeuraApproximationFileManager.NeuralOutputPath, IG.Neural.NeuraApproximationFileManager.ReadNeuralOutput(), IG.Neural.MappingApproximationFileManager.WriteFunctionOutput(), and IG.Neural.NeuraApproximationFileManager.WriteNeuralInput().
ServerCalculateMappingApproximation()
virtual void IG.Neural.MappingApproximationFileManager.ServerCalculateMappingApproximation () inline virtual
Performs neural network-based approximation at prescribed reduced input parameters and saves results. Messages are set and cleared appropriately. This method read reduced input parameters from standard location, mapps input parameters, loads trained neural network, calculates approximated outpur values, mapps output values, and stores them to the standard location.
$A tako78 Jul.21
Definition at line 1294 of file NeuralFileManager.cs.
References IG.Neural.MappingApproximationFileManager.Aux, IG.Neural.MappingApproximationFileManager.ClearFunctionInputReady(), IG.Neural.MappingApproximationFileManager.ClearFunctionOutputReady(), IG.Neural.MappingApproximationFileManager.IsFunctionInputReady(), IG.Neural.MappingApproximationFileManager.IsFunctionOutputReady(), IG.Neural.MappingApproximationFileManager.LoadDataDefinition(), IG.Neural.MappingApproximationFileManager.LoadMappingDefinition(), IG.Neural.IDataMapper.MapInput(), IG.Neural.DataMapperIdentity.MapInput(), IG.Neural.IDataMapper.MapOutput(), IG.Neural.DataMapperIdentity.MapOutput(), IG.Neural.MappingApproximationFileManager.MapperDefinition, IG.Neural.MappingApproximationFileManager.ReadFunctionInput(), IG.Neural.NeuraApproximationFileManager.ReadNeuralOutput(), IG.Neural.NeuraApproximationFileManager.ServerCalculateApproximation(), IG.Neural.MappingApproximationFileManager.SetFunctionOutputReady(), IG.Neural.MappingApproximationFileManager.WriteFunctionOutput(), and IG.Neural.NeuraApproximationFileManager.WriteNeuralInput().
Member Data Documentation
_mappingDefinitionFilename
string IG.Neural.MappingApproximationFileManager._mappingDefinitionFilename = NeuralFileConst.MappingDefinitionFilename private
Definition at line 853 of file NeuralFileManager.cs.
_mappingDefinitionPath
string IG.Neural.MappingApproximationFileManager._mappingDefinitionPath = null private
Definition at line 854 of file NeuralFileManager.cs.
_functionInputFilename
string IG.Neural.MappingApproximationFileManager._functionInputFilename = NeuralFileConst.FunctionInputFilename private
Definition at line 856 of file NeuralFileManager.cs.
_functionInputPath
string IG.Neural.MappingApproximationFileManager._functionInputPath = null private
Definition at line 857 of file NeuralFileManager.cs.
_functionOutputFilename
string IG.Neural.MappingApproximationFileManager._functionOutputFilename = NeuralFileConst.FunctiOutputFilename private
Definition at line 858 of file NeuralFileManager.cs.
_functionOutputPath
string IG.Neural.MappingApproximationFileManager._functionOutputPath = null private
Definition at line 859 of file NeuralFileManager.cs.
_msgFunctionInputReadyFilename
string IG.Neural.MappingApproximationFileManager._msgFunctionInputReadyFilename = NeuralFileConst.MsgFunctionInputReadyFilename private
Definition at line 865 of file NeuralFileManager.cs.
_msgFunctionInputReadyPath
string IG.Neural.MappingApproximationFileManager._msgFunctionInputReadyPath = null private
Definition at line 866 of file NeuralFileManager.cs.
_msgFunctionOutputReadyFilename
string IG.Neural.MappingApproximationFileManager._msgFunctionOutputReadyFilename = NeuralFileConst.MsgFunctionOutputReadyFilename private
Definition at line 867 of file NeuralFileManager.cs.
_msgFunctionOutputReadyPath
string IG.Neural.MappingApproximationFileManager._msgFunctionOutputReadyPath = null private
Definition at line 868 of file NeuralFileManager.cs.
_aux
DataMapperIdentity IG.Neural.MappingApproximationFileManager._aux = null static private
Definition at line 876 of file NeuralFileManager.cs.
_mapperDefinition
IDataMapper IG.Neural.MappingApproximationFileManager._mapperDefinition = null private
Definition at line 877 of file NeuralFileManager.cs.
Property Documentation
Aux
DataMapperIdentity IG.Neural.MappingApproximationFileManager.Aux static get private
Initialize DataMapperIdentity object for identity copying.
Initializing is performed only once.
$A Igor Jul, tako78 Jul
Definition at line 884 of file NeuralFileManager.cs.
Referenced by IG.Neural.MappingApproximationFileManager.ClientTestCalculateMappingApproximation(), and IG.Neural.MappingApproximationFileManager.ServerCalculateMappingApproximation().
MapperDefinition
IDataMapper IG.Neural.MappingApproximationFileManager.MapperDefinition get set
Initialize DataMapperIdentity object for identity copying if mapper is null. Setter takes DataMapperSimple object.
$A Igor Jul, tako78 Jul
Definition at line 898 of file NeuralFileManager.cs.
Referenced by IG.Neural.MappingApproximationFileManager.ClientTestCalculateMappingApproximation(), IG.Neural.MappingApproximationFileManager.MappingApproximationFileManager(), and IG.Neural.MappingApproximationFileManager.ServerCalculateMappingApproximation().
MappingDefinitionPath
string IG.Neural.MappingApproximationFileManager.MappingDefinitionPath get protected set
File path of the input and output mapping definition file. Setter takes only pure file name, without path information. If set to null then file path is set to null and will be recalculated when getter is called.
$A tako78 Jul.21
Definition at line 921 of file NeuralFileManager.cs.
Referenced by IG.Neural.MappingApproximationFileManager.ClientTestCalculateMappingApproximation(), IG.Neural.MappingApproximationFileManager.LoadMappingDefinition(), and IG.Neural.MappingApproximationFileManager.MappingApproximationFileManager().
FunctionInputPath
string IG.Neural.MappingApproximationFileManager.FunctionInputPath get protected set
File path of the file with reduced input parameters. Setter takes only pure file name, without path information. If set to null then file path is set to null and will be recalculated when getter is called.
$A tako78 Jul.21
Definition at line 951 of file NeuralFileManager.cs.
Referenced by IG.Neural.MappingApproximationFileManager.ReadFunctionInput(), and IG.Neural.MappingApproximationFileManager.WriteFunctionInput().
FunctionOutputPath
string IG.Neural.MappingApproximationFileManager.FunctionOutputPath get protected set
File path of the file for storing reduced approximated output values. Setter takes only pure file name, without path information. If set to null then file path is set to null and will be recalculated when getter is called.
$A tako78 Jul.21
Definition at line 979 of file NeuralFileManager.cs.
Referenced by IG.Neural.MappingApproximationFileManager.ClientTestCalculateMappingApproximation(), IG.Neural.MappingApproximationFileManager.ReadFunctionOutput(), and IG.Neural.MappingApproximationFileManager.WriteFunctionOutput().
MsgFunctionInputReadyPath
string IG.Neural.MappingApproximationFileManager.MsgFunctionInputReadyPath get protected set
File path of the message file indicating that reduced input data is ready to be processed. Setter takes only pure file name, without path information. If set to null then file path is set to null and will be recalculated when getter is called.
$A tako78 Jul.21
Definition at line 1009 of file NeuralFileManager.cs.
Referenced by IG.Neural.MappingApproximationFileManager.ClearFunctionInputReady(), IG.Neural.MappingApproximationFileManager.IsFunctionInputReady(), and IG.Neural.MappingApproximationFileManager.SetFunctionInputReady().
MsgFunctionOutputReadyPath
string IG.Neural.MappingApproximationFileManager.MsgFunctionOutputReadyPath get protected set
File path of the message file indicating that the reduced approximated output is ready to be read. Setter takes only pure file name, without path information. If set to null then file path is set to null and will be recalculated when getter is called.
$A tako78 Jul.21
Definition at line 1037 of file NeuralFileManager.cs.
Referenced by IG.Neural.MappingApproximationFileManager.ClearFunctionOutputReady(), IG.Neural.MappingApproximationFileManager.IsFunctionOutputReady(), and IG.Neural.MappingApproximationFileManager.SetFunctionOutputReady().
The documentation for this class was generated from the following file:
iglib/igbase/numeric/approximation/neural/testneural/NeuralFileManager.cs