Doc: IGLib with source files: IGLib.Gr3D.TubularSurfaceExamples Class Reference
IGLib.Gr3D.TubularSurfaceExamples Class Reference
Static Public Member Functions
static void Example_06 ()
static void Example_03 ()
static void Example_02 ()
static void Example_Export_02 ()
static void Example_01 ()
Detailed Description
Definition at line 12 of file TubularSurfaceExamples.cs.
Member Function Documentation
Example_06()
static void IGLib.Gr3D.TubularSurfaceExamples.Example_06 () inline static
Definition at line 16 of file TubularSurfaceExamples.cs.
References IGLib.Gr3D.TubularMeshGenerator_06.GenerateMesh(), and IGLib.Gr3D.TubularMeshGenerator_06.Global.
Example_03()
static void IGLib.Gr3D.TubularSurfaceExamples.Example_03 () inline static
Definition at line 70 of file TubularSurfaceExamples.cs.
References IGLib.Gr3D.MeshExportExtensions_03.ExportMaterial(), and IGLib.Gr3D.TubularMeshGenerator_03.Generate().
Example_02()
static void IGLib.Gr3D.TubularSurfaceExamples.Example_02 () inline static
Definition at line 90 of file TubularSurfaceExamples.cs.
References IGLib.Gr3D.TubularMeshGenerator_02.GenerateTube(), and IGLib.Gr3D.StructuredMesh3D_02.GetQuadrilateral().
Example_Export_02()
static void IGLib.Gr3D.TubularSurfaceExamples.Example_Export_02 () inline static
Definition at line 100 of file TubularSurfaceExamples.cs.
References IGLib.Gr3D.TubularMeshGenerator_02.GenerateTube().
Example_01()
static void IGLib.Gr3D.TubularSurfaceExamples.Example_01 () inline static
Definition at line 117 of file TubularSurfaceExamples.cs.
References IG.Num.vec3.Add(), IGLib.Gr3D.TubularSurface_01.ComputeFrames(), and IGLib.Gr3D.TubularSurface_01.Curve().
The documentation for this class was generated from the following file:
IGLibGraphics3D/src/IGLib.Graphics3D/Graphics3D/Historical/TubularSurfaceExamples.cs