Doc: IGLib with source files: IGLib.Core.ITypeConverter Interface Reference
IGLib.Core.ITypeConverter Interface Reference
Defines methods for converting objects to a specified type.
Public Member Functions
object ConvertToType (object value, Type targetType)
Converts the specified value to the specified target type.
T ConvertToType< T > (object value)
Converts the specified value to the specified target type.
void ConvertToType< T > (object value, out T result)
Converts the specified value to the specified target type.
Detailed Description
Defines methods for converting objects to a specified type.
Implemented by hierarchy of type converters, including BasicTypeConverter and CollectionTypeConverter. One reason for inheritance hierarchy of converters is to have layered hierarchy with increasing capability but also increasing dependencies (e.g., one policy is to keep code that requires advanced reflection (it needs System.Reflection namespace) out of lower layers of libraries such that it does not interfere with trimming, which is needed in many deployment scenarios such as Ahead of Time compilation, WebAssembly deployments like in Blazor client profiles, self-contained deployments to embedded and other resource-limited scenarios).
Definition at line 14 of file ITypeConverter.cs.
Member Function Documentation
ConvertToType()
object IGLib.Core.ITypeConverter.ConvertToType (object value, Type targetType)
Converts the specified value to the specified target type.
Parameters
value The value to convert.
targetType The type to convert the value to.
Returns
The converted value.
Implemented in IGLib.CoreExtended.ReflectionTypeConverter, IGLib.Core.CollectionTypeConverter, and IGLib.Core.BasicTypeConverter.
Referenced by IGLib.Core.Tests.ReflectionTypeConverterTests.Conversion_Fails_WhenNoOperatorExists(), IGLib.Core.Tests.ReflectionTypeConverterTests.Conversion_UsingBaseClassOperator_Works(), IGLib.Core.Tests.ReflectionTypeConverterTests.Conversion_UsingInterfaceOperator_Works_WhenAllowed(), IGLib.Core.Tests.ReflectionTypeConverterTests.ExplicitConversion_FromCelsiusToFahrenheit_Works(), IGLib.Core.Tests.ReflectionTypeConverterTests.ExplicitConversion_FromFahrenheitToCelsius_Works(), IGLib.Core.Tests.ReflectionTypeConverterTests.ImplicitConversion_FromCelsiusToDouble_Works(), IGLib.Core.Tests.TypeConverterTestsBase< CapturedVarTests >.TypeConverter_ConversionToObjectAndBackTest< OriginalType, TargetType, RestoredType >(), and IGLib.Core.Tests.TypeConverterTestsBase< CapturedVarTests >.TypeConverter_Speed_ConversionToObjectAndBackTest< OriginalType, TargetType, RestoredType >().
ConvertToType< T >() [1/2]
T IGLib.Core.ITypeConverter.ConvertToType< T > (object value)
Converts the specified value to the specified target type.
Template Parameters
T The type to convert the value to.
Parameters
value The value to convert.
Returns
The converted value.
Implemented in IGLib.Core.BasicTypeConverter.
ConvertToType< T >() [2/2]
void IGLib.Core.ITypeConverter.ConvertToType< T > (object value, out T result)
Converts the specified value to the specified target type.
Template Parameters
T The type to convert the value to.
Parameters
value The value to convert.
result When this method returns, contains the converted value.
Implemented in IGLib.Core.BasicTypeConverter.
The documentation for this interface was generated from the following file:
IGLibGraphics3D/src/IGLib.Graphics3D/other/TypeConversion/ITypeConverter.cs