Doc: IGLib with source files: IG.Num.NeuralApproximatorBase Class Reference
IG.Num.NeuralApproximatorBase Class Reference abstract
Base class for neural network approximators.
Public Member Functions
NeuralApproximatorBase ()
virtual int GetNumNeuronsInHiddenLayer (int whichLayer)
Returns the number of neurons in the specified hidden layer. Hidden layers are those not containing input or output neurons.
virtual void SetNumNeuronsInHiddenLayer (int whichLayer, int numNeurons)
Sets the number of neurons in the specified hidden layer. Hidden layers are those not containing input or output neurons.
virtual void SetHiddenLayers (params int[] numNeurons)
Sets the numbers of neurons in each hidden layer. Can be called with table of integers as argument, kor with variable number of integer parameters. Numbers are set by an array of integers in which each element contains the number of neurons in the corresponding hidden layer (indexed from 0). Hidden layers are those not containing input or output neurons.
abstract void PrepareNetwork ()
Prepares neural network for use. If networks have not yet been created accordinfg to internal data, they are created. If networks are already prepared then this method does nothing.
abstract void CreateNetwork ()
Creates the neural network anew. It the network already exists on the current object, it is discarded.
abstract void ResetNetwork ()
Resets the neural network.
abstract void DestroyNetwork ()
Destroys the neural network.
string GetNetworkFilePath (string fileOrDirectoryPath, int whichNetwork)
Returns an absolute path to the file for storing the specified neural network contained on the current object, with respect to suggested file path and index of the network. The returned path is in the same directory as suggested file path and has the same file extension (if any). If the suggested path represents a directory, then some default suggested path is assumed. If there is only one network then the returned file path is the same as the suggested one (or the same as default file name within the suggested directory, if a directory path is proposed).
void SaveNetwork (string filePath)
Saves the state of the neural network to the specified file. If the file already exists, its contents are overwritten.
void LoadNetwork (string filePath)
Restores neural network from a file where it has been stored before.
void SetTrainingAndVerificationData (SampledDataSet trainingData, SampledDataSet verificationData)
Auxiliary function, sets training and verification data for training the network.
void GetTrainingData (ref SampledDataSet trainingData)
Auxiliary function, returns network's training data.
void GetVerificationData (ref SampledDataSet veerificationData)
Auxliliary function, returns network's verification data.
void GetTrainingAndVerificationData (ref SampledDataSet trainingData, ref SampledDataSet verificationData)
Auxiliary function, obtains network's training and verification data.
void SaveTrainingDataJson (string filePath)
Saves network's training data to the specified JSON file. File is owerwritten if it exists.
void LoadTrainingDataJson (string filePath)
Restores training data from the specified file in JSON format.
void SetNeuronsInputRange (double min, double max)
Sets the neurons input range. Bounds for all input neurons are set equally.
void SetNeuronsOutputRange (double min, double max)
Sets the neurons output range. Bounds for all output neurons are set equally.
void RecalculateInputDataBounds ()
Recalculates input data bounds by taking into account the training data set of the current object.
void RecalculateOutputDataBounds ()
Recalculates output data bounds by taking into account the training data set of the current object.
void RecalculateDataBounds ()
Recalculates input and output data bounds by taking into account the training data set of the current object.
void RecalculateInputDataBounds (SampledDataSet trainingData)
Recalculates input data bounds by taking into account the specified training data set.
void RecalculateOutputDataBounds (SampledDataSet trainingData)
Recalculates output data bounds by taking into account the specified training data set.
void RecalculateDataBounds (SampledDataSet trainingData)
Recalculates input and output data bounds by taking into account the specified training data set.
void GetErrorsTrainingRms (ref IVector errors)
Calculates the RMS (root mean square) of the errors of output values for the training elements of the training set (this excludes verification points).
void GetErrorsVerificationRms (ref IVector errors)
Calculates the RMS (root mean square) of the errors of output values for the verification elements of the training set.
void GetErrorsTrainingMax (ref IVector errors)
Calculates the maximum absolute errors of output values for the training elements of the training set (this excludes verification points).
void GetErrorsVerificationMax (ref IVector errors)
Calculates the maximum absolute errors of output values for the verification elements of the training set.
void GetErrorsTrainingMeanAbs (ref IVector errors)
Calculates the mean absolute errors of output values for the training elements of the training set (this excludes verification points).
void GetErrorsVerificationMeanAbs (ref IVector errors)
Calculates the mean absolute errors of output values for the verification elements of the training set.
virtual void InvalidateTrainingDependencies ()
Invalidates all data that must be recalculated after training of the network is done. This method is called after training or additional training of the network is performed. Invalidation is achieved throughthe the appropriate flags.
virtual void InvalidateTrainingDataDependencies ()
Invalidates all data that must be re-calculated after training data changes. This method is called after training data is modified. Invalidation is achieved throughthe the appropriate flags.
virtual void InvalidateNetworkDependencies ()
Invalidates all data that must be re-calculated after the neural network itself changes. This method must be called after the internal neural network is re-defined (or are re-defined). Invalidation is achieved throughthe the appropriate flags.
void TrainNetwork (int numEpochs)
Trains neural network wiht the specified data, performing the specified number of epochs.
void TrainNetworkMultiple (int numEpochs, int numIterations)
Performs a specified number of training iterations where the specified number of epochs are run in each iteration.
void TrainNetworkMultiple (int numIterations)
Performs a specified number of training iterations where the prescribed number of epochs (contained in the EpochsInBundle property) are run in each iteration.
virtual void TrainNetwork ()
Trains neural network until stopping criteria are met (in terms of errors and number of epochs performed.
virtual bool StopTrainingCriteriaMet ()
Returns true if the stopping criteria for training is met, with respect to current settings, errors and number of epochs already performed, and false otherwise.
override double CalculateOutput (IVector input, int whichElement)
Calculates and returns the specified output by using the neural network.
override void CalculateOutput (IVector input, int[] indices, ref IVector filteredOutput)
Calculates and returns the required output values corresponding to the specified inputs, by using the current neural network(s).
override string ToString ()
Returns string describing the current neural network approximator.
void SaveTrainingDataJson_To_delete (string filePath)
Saves network's training data to the specified JSON file. File is owerwritten if it exists.
void LoadTrainingDataJson_To_Delete (string filePath)
Restores training data from the specified file in JSON format.
void TestMapping ()
Test back and forth mapping (scaling and shifting) from actual data to data prepared for training, and vice versa (checks if transformed data falls withi the prescribed ranges and if backward transformation yields the same result as forward transformation). Testing is performed on all data from the TrainingData property, including verification elements.
Public Member Functions inherited from IG.Num.VectorApproximatorBase
abstract void CalculateOutput (IVector input, ref IVector output)
Calculates and returns the approximated outputs corresponding to the specified inputs, by using the current vector function approximator.
Static Public Member Functions
static void InitType ()
Does nothing by itself, but causes call to static constructor, which causes the necessary type initializations.
static INeuralApproximator CreateApproximator (string approximatorTypeName)
Creates and returns a new instance of the neural approximator type specified by approximatorTypeName . Type regisyry NeuralApproximatorBase.TypesRegistry is utilised by this method, in order to get a Type object from the specified name (approximatorTypeName) and use it in reflection to create an object of the specified type. For this to work, registration must be performed for the given type under given name, which is done by calling the type's InitType static method, which causes calling of static constructor that performs registration.
static void CalculateErrorsRms (int dimOutput, IVector[] prescribed, IVector[] calculated, ref IVector errors)
Calculates error measures - RMS (root mean square) of the differences - for the specified arrays of prescribed and calculated output values in a set of sampling points.
static void CalculateErrorsMeanAbs (int dimOutput, IVector[] prescribed, IVector[] calculated, ref IVector errors)
Calculates error measures - mean absolute value of the differences - for the specified arrays of prescribed and calculated output values in a set of sampling points.
static void CalculateErrorsMax (int dimOutput, IVector[] prescribed, IVector[] calculated, ref IVector errors)
Calculates error measures - maximum absolute value of the differences - for the specified arrays of prescribed and calculated output values in a set of sampling points.
static void SaveJson (INeuralApproximator approximator, string filePath)
Saves a neural network approximator to a file. If the neural netwoek is trained then internal state is also saved to a file.
static void SaveJson (INeuralApproximator approximator, string filePath, bool saveInternalState)
Saves a neural network approximator to a file.
static void LoadJson (string filePath, ref INeuralApproximator approximatorRestored)
Loads network from a file.
static void ExampleSaveNetwork (string directoryPath, string fileName, string internalStateFileName)
Example of saving an entire trained neural network to a file, and then restoring it from a file. Network internal state is saved by the SaveNetwork() method that is specific to the type of the network, therefore it is saved to a separate file. The path of this file is savad with the network approximator object itself. Network is saved only once.
static void ExampleSaveNetwork (string directoryPath, string fileName, string internalStateFileName, bool saveRestored)
Example of saving an entire trained neural network to a file, and then restoring it from a file. Network internal state is saved by the SaveNetwork() method that is specific to the type of the network, therefore it is saved to a separate file. The path of this file is savad with the network approximator object itself. If the saveRestored flag parameter is true then the restored file ia saved again for comparison.
static INeuralApproximator ExampleQuadratic ()
Example demonstrating usage of the neural network approximator. A quadratic function with random coefficients is sampled with enough samples to exactly specify function coefficients, a part of samples is randomly designated as verification points, then neural network is created and trained on training samples, and it is verified how close the obtained approximation matches actual function in verification points.
static INeuralApproximator ExampleQuadratic (int inputLength, int outputLength)
Example demonstrating usage of the neural network approximator. A quadratic function with random coefficients is sampled with enough samples to exactly specify function coefficients, a part of samples is randomly designated as verification points, then neural network is created and trained on training samples, and it is verified how close the obtained approximation matches actual function in verification points.
static INeuralApproximator ExampleQuadratic (int inputLength, int outputLength, int outputLevel, int maxEpochs)
Example demonstrating usage of the neural network approximator. A quadratic function with random coefficients is sampled with enough samples to exactly specify function coefficients, a part of samples is randomly designated as verification points, then neural network is created and trained on training samples, and it is verified how close the obtained approximation matches actual function in verification points.
Protected Member Functions
void SetRmsToleranceRelstiveToRange ()
Updates the tolerances on RMS errors of outputs according to the relative tolerances (defined by ToleranceRmsRelativeToRange) and the ranges in output data (defined by OutputDataBounds), if both are defined.
void SetMaxToleranceRelstiveToRange ()
Updates the tolerances on max. abs. errors of outputs according to the relative tolerances (defined by ToleranceMaxRelativeToRange) and the ranges in output data (defined by OutputDataBounds), if both are defined.
abstract void PrepareNetworksArray ()
Prepares the networks array (allocates it if necessary) for storing all neural networks of the current object.
abstract void SaveNetworkSpecific (string filePath)
Saves the state of the neural network to the specified file. If the file already exists, its contents are overwritten.
abstract void LoadNetworkSpecific (string filePath, bool useSerializationBinderIfSpecified=true)
Restores neural network from a file where it has been stored before.
virtual double MapInput (int componentIndex, double value)
Maps (scales and shifts) and returns specific input value to the value prepared for the corresponding input neuron.
virtual double MapFromNeuralInput (int componentIndex, double value)
Inverse maps (scales and shifts) and returns specific input value back from the neural input to the actual input.
virtual void MapInput (IVector values, ref IVector mappedValues)
Maps (scales and shifts) vector of input values to the vector of neuron inputs.
virtual void MapFromNeuralInput (IVector values, ref IVector mappedValues)
Inverse maps (scales and shifts) vector of neural input values back to the vector of actual inputs.
virtual double MapOutput (int componentIndex, double value)
Maps (scales and shifts) and returns specific output value to the output value of the corresponding output neuron.
virtual double MapFromNeuralOutput (int componentIndex, double value)
Inverse maps (scales and shifts) and returns specific output value back from the neural output to the actual output.
virtual void MapOutput (IVector values, ref IVector mappedValues)
Maps (scales and shifts) vector of output values to the vector of neuron outputs.
virtual void MapFromNeuralOutput (IVector values, ref IVector mappedValues)
Inverse maps (scales and shifts) vector of neural output values back to the vector of actual outputs.
void CalculateTrainingVerificationOutputs (bool calculateTrainingOutputs, bool calculateVerificationOutputs)
Calculates outputs in training points contained in training set, either in training points, in verification points, or both.
void CalculateTrainingOutputs ()
Calculates outputs in training points of the training data set (this excludes verification points).
void CalculateVerificationOutputs ()
Calculates outputs in verification points of the training data set.
virtual void PrepareErrorData (ref int dimOutput, ref IVector[] prescribed, ref IVector[] calculated, bool takeTrainingPoints, bool takeVerificationPoints)
Prepares data for calculation of various error measures over training points or in verification points after training of the neural network(s).
abstract void PrepareInternalTrainingData ()
Prepares internal training data that is needed by the native training algorithm. When overridden, this method must set the InternalTrainingDataPrepared flag to true.
abstract void TrainNetworkSpecific (int numEpochs)
Trains neural network wiht the specified data, performing the specified number of epochs. This method must be implemented in derived classes and is specific to specific network type.
virtual void OnBundleCompleted ()
Called after completion of each bundle of training epochs (after auxiliary data is updated).
virtual void OnTrainingCompleted ()
Called after completion of training procedure (after all auxiliary data is updated, raises the TrainingCompleted event..
Protected Attributes
double _defaultNeuronMinInput = -2
double _defaultNeuronMaxInput = 2
double _defaultNeuronMinOutput = -1.0
double _defaultNeuronMaxOutput = 1.0
List< IVector > _calculatedOutputs = null
List of calculated outputs in points contained in (all) training data.
bool _calculateVerificationErrors = false
Vector _auxErrors = null
Protected Attributes inherited from IG.Num.VectorApproximatorBase
IVector _lastCalculationInputParameters
Static Protected Attributes
const string _defaultNetworkFilename = "network.dat"
Properties
static DerivedTypesRgistryBasic< INeuralApproximator > TypesRegistry = new DerivedTypesRgistryBasic<INeuralApproximator>() [get]
Registry of INeuralApproximator types, which enables to retrieve an ANN approximator type based on its name, which is important for creation of instances via reflection, which is also used when loading trained approximators from a serialized JSON file (functionality of DerivedTypesRegistryPlain<INeuralApproximator> is crucial when restoring internal state of embedded 3rd-party approximators).
SerializationBinderBase SerializationBinder [get, set]
Serialization binder used for binary deserialization of objects of the current class.
int OutputLevel [get, set]
Level of output printed to console when performing actions.
virtual bool MultipleNetworks [get, set]
Flag indicating whether multiple neural networks are used to approximate multiple outputs (one network for each output)
override int InputLength [get, set]
Gets or sets the number of input neurons.
override int OutputLength [get, set]
Gets or sets the number of output neurons.
virtual int[] NumHiddenNeurons [get, set]
Gets or sets the numbers of neurons in each hidden layer. When setting, contents of array are copied, not only a reference. Numbers are set by an array of integers in which each element contains the number of neurons in the corresponding hidden layer (indexed from 0). Hidden layers are those not containing input or output neurons.
virtual int NumHiddenLayers [get, set]
Gets or sets the number of hidden layers of the neural network (these are layers that don't contain input or output neurons).
bool NetworkPrepared [get, protected set]
Gets a flag telling whether the network is prepared for operation (training and calculation of output).
double SigmoidAlphaValue [get, set]
Alpha value specifying the shape of the activation function.
double LearningRate [get, set]
Gets or sets learning rate.
double Momentum [get, set]
Gets or sets momentum.
int EpochCount [get, protected set]
Number of learning epochs performed up to the current moment.
int MaxEpochs [get, set]
Maximal number of epochs in training.
int EpochsInBundle [get, set]
Number of epochs in a single training bundle. This number of epochs is performed at once when training, without checking convergence criteria between. Larger value means slightly more efficient training (because of less checks) but rougher criteria checks.
IVector ToleranceRms [get, set]
Tolerances on RMS errors of outputs over training points. Training will continue until error becomes below tolerance or until maximal number of epochs is reached. If less or equal than 0 then this tolerance is not taken into account.
IVector ToleranceMax [get, set]
Tolerances on maximal errors of outputs over training points. Training will continue until error becomes below tolerance or until maximal number of epochs is reached. If less or equal than 0 then this tolerance is not taken into account.
IVector ToleranceRmsRelativeToRange [get, set]
Relative tolerances on RMS errors of outputs over training points, relative to the correspoinding ranges of output data.
double ToleranceRmsRelativeToRangeScalar [get, set]
Scalar through which all components of the Relative tolerances on RMS errors of outputs can be set to the same value.
IVector ToleranceMaxRelativeToRange [get, set]
Relative tolerances on max. abs. errors of outputs over training points, relative to the correspoinding ranges of output data.
double ToleranceMaxRelativeToRangeScalar [get, set]
Scalar through which all components of the Relative tolerances on max. abs. errors of outputs can be set to the same value.
List< int > EpochNumbers [get, set]
List of epoch numbers at which convergence data was sampled. Saved after every set of epochs.
List< IVector > ConvergenceErrorsTrainingRmsList [get, set]
Convergence List of RMS errors calculated on training data. Saved after every set of epochs.
List< IVector > ConvergenceErrorsTrainingMaxList [get, set]
Convergence List of Maximum errors calculated on training data. Saved after every set of epochs.
List< IVector > ConvergenceErrorsVerificationRmsList [get, set]
Convergence List of Rms errors calculated on verification data. Saved after every set of epochs.
List< IVector > ConvergenceErrorsVerificationMaxList [get, set]
Convergence List of Maximum errors calculated on verification data. Saved after every set of epochs.
bool SaveConvergenceRms [get, set]
Flag to enable RMS error convergence colection.
string NeuralApproximatorType [get]
Gets string representation of type of the current object. This is used e.g. in deserialization in order to prevent that wrong type of internal representation would be read in.
string NetworkStateFilePath [get, set]
Path where the curren network state has been saved, or null if the current state has not been saved yet. The SaveFile methods takes care that the file path is stored when network state is saved. InvalidateTrainingDependencies() takes care that this file path is set to null if network state has changed after last save.
string NetworkStateRelativePath [get, set]
Relative path where the curren network state has been saved. Auxiliary property used in deserialization. When the whole Neural network approximator is saved to a file, tis path is updated in such a way that it points to the fiele where the network state has been saved, but relative to the path where the whole approximator is saved. This enables restore of the saved network state at a later time, even if the containing directory has moved within the file system or has even been copied to another system.
SampledDataSet TrainingData [get, set]
Gets or sets the training data.
virtual IndexList VerificationIndices [get, set]
Gets or sets indices of training data elements that are used for verification of how precise appeoximation is. These elements are excluded from training of neural network.
virtual IBoundingBox InputDataBounds [get, set]
Bounds on input data, used for scaling from actual input to input used by neural network. Scaling is performed because of the bound codomain and image of activation functions.
virtual IBoundingBox OutputDataBounds [get, set]
Bounds on output data, used for scaling from actual output to output produced by neural network. Scaling is performed because of the bound codomain and image of activation functions.
virtual double InputBoundsSafetyFactor [get, set]
Safety factor by which interval lenghts of input data bounds are enlarged after bounds are automatically determined from the range of input data in the training set. Setter re-calculated the input data bounds and therefore invalidates training data dependencies.
virtual double OutputBoundsSafetyFactor [get, set]
Safety factor by which interval lenghts of output data bounds are enlarged after bounds are automatically determined from the range of output data in the training set. Setter re-calculated the output data bounds and therefore invalidates training data dependencies.
virtual IBoundingBox InputNeuronsRange [get, protected set]
Gets the range in which data should be for input neurons, used for scaling from actual input to input used by neural network. This depends on the activation function.
virtual IBoundingBox OutputNeuronsRange [get, protected set]
Gets the range of the data output from output neurons, used for scaling from actual output to output produced by neural network. This will normally depend on the activation function.
int NumAllTrainingPoints [get]
Gets number of all training points, including verification points.
virtual int NumTrainingPoints [get]
Gets number of training points (this excludes verification points).
virtual int NumVerificationPoints [get]
Gets number of verification points.
bool TrainingOutputsCalculated [get, set]
Whether outputs have been calculated, after last training, in the training points (excluding verification points).
bool VerificationOutputsCalculated [get, set]
Whether outputs have been calculated, after last training, in the training points (excluding verification points).
bool InternalTrainingDataPrepared [get, set]
Gets or sets a flag indicating whether internal training data is prepared. This flag is used internally for signalization between methods that deal with training data.
bool NetworkTrained [get, protected set]
Whether network has been trained since the training data was set.
bool BreakTraining [get, set]
Flags that signalizes (if true) that training should be broken on external request.
bool CalculateVerificationErrors [get, set]
EventArgs CommonEventArgs [get]
Provides a commond object of type EventArgs for all events to avoid allocation each time an event is fired.
Properties inherited from IG.Num.VectorApproximatorBase
object Lock [get]
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
abstract int InputLength [get, set]
Gets or sets the number of input parameters.
abstract int OutputLength [get, set]
Gets or sets the number of output values.
Properties inherited from IG.Num.IVectorApproximator
int InputLength [get, set]
Gets or sets the number of input parameters.
int OutputLength [get, set]
Gets or sets the number of output values.
Properties inherited from IG.Lib.ILockable
object Lock [get]
Properties inherited from IG.Num.INeuralApproximator
int OutputLevel [get, set]
Level of output printed to console when performing actions.
bool MultipleNetworks [get, set]
Flag indicating whether multiple neural networks are used to approximate multiple outputs (one network for each output)
int[] NumHiddenNeurons [get, set]
Sets the numbers of neurons in each hidden layer. Numbers are set by an array of integers in which each element contains the number of neurons in the corresponding hidden layer (indexed from 0). Hidden layers are those not containing input or output neurons.
int NumHiddenLayers [get, set]
Gets or sets the number of hidden layers of the neural network (these are layers that don't contain input or output neurons).
bool NetworkPrepared [get]
Gets a flag telling whether the network is prepared for operation (training and calculation of output).
double SigmoidAlphaValue [get, set]
Alpha value specifying the shape of the activation function.
double LearningRate [get, set]
Gets or sets learning rate.
double Momentum [get, set]
Gets or sets momentum.
int EpochCount [get]
Number of learning epochs performed up to the current moment.
int MaxEpochs [get, set]
Maximal number of epochs in training.
int EpochsInBundle [get, set]
Number of epochs in a single training bundle. This number of epochs is performed at once when training, without checking convergence criteria between. Larger value means slightly more efficient training (because of less checks) but rougher criteria checks.
IVector ToleranceRms [get, set]
Tolerance over RMS error of output over training points. Training will continue until error becomes below tolerance or until maximal number of epochs is reached. If less or equal than 0 then this tolerance is not taken into account.
IVector ToleranceMax [get, set]
Tolerance on maximal error of output over training points. Training will continue until error becomes below tolerance or until maximal number of epochs is reached. If less or equal than 0 then this tolerance is not taken into account.
IVector ToleranceRmsRelativeToRange [get, set]
Relative tolerances on RMS errors of outputs over training points, relative to the correspoinding ranges of output data.
double ToleranceRmsRelativeToRangeScalar [get, set]
Scalar through which all components of the Relative tolerances on RMS errors of outputs can be set to the same value.
IVector ToleranceMaxRelativeToRange [get, set]
Relative tolerances on max. abs. errors of outputs over training points, relative to the correspoinding ranges of output data.
double ToleranceMaxRelativeToRangeScalar [get, set]
Scalar through which all components of the Relative tolerances on max. abs. errors of outputs can be set to the same value.
bool SaveConvergenceRms [get, set]
Flag to enable Rms error convergence colection. Default is false.
List< int > EpochNumbers [get, set]
List of epoch numbers at which convergence data was sampled. Saved after every set of epochs.
List< IVector > ConvergenceErrorsTrainingRmsList [get, set]
Convergence List of Rms errors calculated on training data. Saved after every set of epochs.
List< IVector > ConvergenceErrorsTrainingMaxList [get, set]
Convergence List of Maximum errors calculated on training data. Saved after every set of epochs.
List< IVector > ConvergenceErrorsVerificationRmsList [get, set]
Convergence List of Rms errors calculated on verification data. Saved after every set of epochs.
List< IVector > ConvergenceErrorsVerificationMaxList [get, set]
Convergence List of Maximum errors calculated on verification data. Saved after every set of epochs.
string NeuralApproximatorType [get]
Gets string representation of type of the current object. This is used e.g. in deserialization in order to prevent that wrong type of internal representation would be read in.
string NetworkStateFilePath [get]
Path where the curren network state has been saved, or null if the current state has not been saved yet. The SaveFile methods takes care that the file path is stored when network state is saved. InvalidateTrainingDependencies() takes care that this file path is set to null if network state has changed after last save.
string NetworkStateRelativePath [get, set]
Relative path where the curren network state has been saved. Auxiliary property used in deserialization. When the whole Neural network approximator is saved to a file, tis path is updated in such a way that it points to the fiele where the network state has been saved, but relative to the path where the whole approximator is saved. This enables restore of the saved network state at a later time, even if the containing directory has moved within the file system or has even been copied to another system.
SampledDataSet TrainingData [get, set]
Gets or sets the training data.
IndexList VerificationIndices [get, set]
Gets or sets indices of training data elements that are used for verification of how precise appeoximation is. These elements are excluded from training of neural network.
IBoundingBox InputDataBounds [get, set]
Bounds on input data, used for scaling from actual input to input used by neural network. Scaling is performed because of the bound codomain and image of activation functions.
IBoundingBox OutputDataBounds [get, set]
Bounds on output data, used for scaling from actual output to output produced by neural network. Scaling is performed because of the bound codomain and image of activation functions.
double InputBoundsSafetyFactor [get, set]
Safety factor by which interval lenghts of input data bounds are enlarged after bounds are automatically determined from the range of input data in the training set. Setter re-calculated the input data bounds and therefore invalidates training data dependencies.
double OutputBoundsSafetyFactor [get, set]
Safety factor by which interval lenghts of output data bounds are enlarged after bounds are automatically determined from the range of output data in the training set. Setter re-calculated the output data bounds and therefore invalidates training data dependencies.
IBoundingBox InputNeuronsRange [get]
Gets the range in which data should be for input neurons, used for scaling from actual input to input used by neural network. This depends on the activation function.
IBoundingBox OutputNeuronsRange [get]
Gets the range of the data output from output neurons, used for scaling from actual output to output produced by neural network. This will normally depend on the activation function.
int NumAllTrainingPoints [get]
Gets number of all training points, including verification points.
int NumTrainingPoints [get]
Gets number of training points (this excludes verification points).
int NumVerificationPoints [get]
Gets number of verification points.
bool NetworkTrained [get]
Whether network has been trained since the training data was set.
bool BreakTraining [get, set]
Flags that signalizes (if true) that training should be broken on external request.
Events
EventHandler BundleCompleted
Event that is fired after completion of each bundle of training epochs (after auxiliary data is updated). Enables e.g. following training progress to subscribers, or additional interaction with training process such as stopping when enough converged, saving state, or increasing maximal number of epochs when convergence is insufficient.
EventHandler TrainingCompleted
Event that is fired after completion of training procedure (after auxiliary data is updated).
Events inherited from IG.Num.INeuralApproximator
EventHandler BundleCompleted
Event that is fired after completion of each bundle of training epochs (after auxiliary data is updated). Enables e.g. following training progress to subscribers, or additional interaction with training process such as stopping when enough converged, saving state, or increasing maximal number of epochs when convergence is insufficient.
EventHandler TrainingCompleted
Event that is fired after completion of training procedure (after auxiliary data is updated).
Static Private Member Functions
static NeuralApproximatorBase ()
Static constructor. Ensures registration of neural approximator type, which makes possible to construct an approximator based on its registered type name because name can resolve to type object used by Activator to construcht the object.
Private Attributes
object _mainLock = new object()
int _outputLevel = Util.OutputLevel
int _inputLength
int _outputLength
int[] _numHiddenNeurons
bool _multipleNetworks = true
bool _networkPrepared = false
double _sigmoidAlphaValue = NeuralTrainingParameters.DefaultSigmoidAlphaValue
double _learningRate = NeuralTrainingParameters.DefaultLearningRate
double _momentum = NeuralTrainingParameters.DefaultMomentum
int _epochCount = 0
bool _convergenceRmsEnabled = false
int _maxEpochs = NeuralTrainingParameters.DefaultMaxEpochs
int _epochsInBundle = NeuralTrainingParameters.DefaultEpochsInBundle
List< int > _epochNumbers = null
List< IVector > _convergenceErrorsTrainingRmsList = null
List< IVector > _convergenceErrorsTrainingMaxList = null
List< IVector > _convergenceErrorsVerificationRmsList = null
List< IVector > _convergenceErrorsVerificationMaxList = null
IVector _toleranceRms = null
IVector _toleranceMax = null
IVector _tolRmsRelative
Auxiliary properties for defining tolerances in a relative way:
double _tolRmsRelativeScalar
IVector _tolMaxRelative
double _tolMaxRelativeScalar
string _networkFilePath = null
string _networkRelativePath = null
SampledDataSet _trainingData
IndexList _verificationIndices
IBoundingBox _inputDataBounds
IBoundingBox _outputDataBounds
IBoundingBox _inputNeuronRange
IBoundingBox _outputNeuronsRange
double _inputBoundsSafetyFactor = 1.5
double _outputBoundsSafetyFactor = 2.0
bool _internalTrainingDataPrepared = false
bool _trainingOutputsCalculated = false
bool _verificationOutputsCalculated = false
bool _networkTrained
List< IVector > _prescribed = null
List< IVector > _calculated = null
bool _breakTraining = false
EventArgs _commonEventArgs
IVector _output = null
IVector _outputFiltered1 = null
Detailed Description
Base class for neural network approximators.
$A Igor Mar11;
Definition at line 531 of file NeuralApproximatorBase.cs.
Constructor & Destructor Documentation
NeuralApproximatorBase() [1/2]
IG.Num.NeuralApproximatorBase.NeuralApproximatorBase () inline
Definition at line 536 of file NeuralApproximatorBase.cs.
NeuralApproximatorBase() [2/2]
static IG.Num.NeuralApproximatorBase.NeuralApproximatorBase () inline static private
Static constructor. Ensures registration of neural approximator type, which makes possible to construct an approximator based on its registered type name because name can resolve to type object used by Activator to construcht the object.
Definition at line 548 of file NeuralApproximatorBase.cs.
Member Function Documentation
InitType()
static void IG.Num.NeuralApproximatorBase.InitType () inline static
Does nothing by itself, but causes call to static constructor, which causes the necessary type initializations.
Definition at line 555 of file NeuralApproximatorBase.cs.
CreateApproximator()
static INeuralApproximator IG.Num.NeuralApproximatorBase.CreateApproximator (string approximatorTypeName) inline static
Creates and returns a new instance of the neural approximator type specified by approximatorTypeName . Type regisyry NeuralApproximatorBase.TypesRegistry is utilised by this method, in order to get a Type object from the specified name (approximatorTypeName) and use it in reflection to create an object of the specified type. For this to work, registration must be performed for the given type under given name, which is done by calling the type's InitType static method, which causes calling of static constructor that performs registration.
Parameters
approximatorTypeName
Definition at line 564 of file NeuralApproximatorBase.cs.
References IG.Num.NeuralApproximatorBase.TypesRegistry.
Referenced by IG.Num.NeuralApproximatorDtoBase< NeuralApproximatorAforgeFake >.CreateObject().
GetNumNeuronsInHiddenLayer()
virtual int IG.Num.NeuralApproximatorBase.GetNumNeuronsInHiddenLayer (int whichLayer) inline virtual
Returns the number of neurons in the specified hidden layer. Hidden layers are those not containing input or output neurons.
Parameters
whichLayer Index of the hidden layer for which number of neurons is returned.
Implements IG.Num.INeuralApproximator.
Definition at line 791 of file NeuralApproximatorBase.cs.
References IG.Lib.ILockable.Lock, and IG.Num.NeuralApproximatorBase.NumHiddenNeurons.
SetNumNeuronsInHiddenLayer()
virtual void IG.Num.NeuralApproximatorBase.SetNumNeuronsInHiddenLayer (int whichLayer, int numNeurons) inline virtual
Sets the number of neurons in the specified hidden layer. Hidden layers are those not containing input or output neurons.
Parameters
whichLayer Index of the hidden layer for which number of neurons is returned.
numNeurons Prescribed number of neurons in the specified layer.
Implements IG.Num.INeuralApproximator.
Definition at line 810 of file NeuralApproximatorBase.cs.
References IG.Lib.ILockable.Lock, and IG.Num.NeuralApproximatorBase.NumHiddenNeurons.
Referenced by IG.Num.NeuralTrainingParameters.CopyTo().
SetHiddenLayers()
virtual void IG.Num.NeuralApproximatorBase.SetHiddenLayers (params int[] numNeurons) inline virtual
Sets the numbers of neurons in each hidden layer. Can be called with table of integers as argument, kor with variable number of integer parameters. Numbers are set by an array of integers in which each element contains the number of neurons in the corresponding hidden layer (indexed from 0). Hidden layers are those not containing input or output neurons.
Parameters
numNeurons Array containing the prescribed numbers of neurons in each hidden layer. Instead of array, a variable number of integer parameters can be specified.
Implements IG.Num.INeuralApproximator.
Definition at line 832 of file NeuralApproximatorBase.cs.
References IG.Num.NeuralApproximatorBase.NumHiddenNeurons.
Referenced by IG.Num.NeuralApproximatorBase.ExampleQuadratic().
SetRmsToleranceRelstiveToRange()
void IG.Num.NeuralApproximatorBase.SetRmsToleranceRelstiveToRange () inline protected
Updates the tolerances on RMS errors of outputs according to the relative tolerances (defined by ToleranceRmsRelativeToRange) and the ranges in output data (defined by OutputDataBounds), if both are defined.
Definition at line 1035 of file NeuralApproximatorBase.cs.
References IG.Num.NeuralApproximatorBase._outputDataBounds, IG.Num.NeuralApproximatorBase._outputLength, IG.Num.NeuralApproximatorBase._tolRmsRelative, IG.Num.NeuralApproximatorBase._tolRmsRelativeScalar, IG.Num.VectorBase.ArrayProductPlain(), IG.Num.IBoundingBox.Dimension, IG.Num.IBoundingBox.GetIntervalLengths(), IG.Num.IVector< T >.Length, IG.Lib.ILockable.Lock, IG.Num.NeuralApproximatorBase.ToleranceRms, IG.Num.NeuralApproximatorBase.ToleranceRmsRelativeToRange, and IG.Num.NeuralApproximatorBase.ToleranceRmsRelativeToRangeScalar.
SetMaxToleranceRelstiveToRange()
void IG.Num.NeuralApproximatorBase.SetMaxToleranceRelstiveToRange () inline protected
Updates the tolerances on max. abs. errors of outputs according to the relative tolerances (defined by ToleranceMaxRelativeToRange) and the ranges in output data (defined by OutputDataBounds), if both are defined.
Definition at line 1134 of file NeuralApproximatorBase.cs.
References IG.Num.NeuralApproximatorBase._outputDataBounds, IG.Num.NeuralApproximatorBase._outputLength, IG.Num.NeuralApproximatorBase._tolMaxRelative, IG.Num.NeuralApproximatorBase._tolMaxRelativeScalar, IG.Num.VectorBase.ArrayProductPlain(), IG.Num.IBoundingBox.Dimension, IG.Num.IBoundingBox.GetIntervalLengths(), IG.Num.IVector< T >.Length, IG.Lib.ILockable.Lock, IG.Num.NeuralApproximatorBase.ToleranceMax, IG.Num.NeuralApproximatorBase.ToleranceMaxRelativeToRange, and IG.Num.NeuralApproximatorBase.ToleranceMaxRelativeToRangeScalar.
PrepareNetworksArray()
abstract void IG.Num.NeuralApproximatorBase.PrepareNetworksArray () protected pure virtual
Prepares the networks array (allocates it if necessary) for storing all neural networks of the current object.
Implemented in IG.Num.NeuralApproximatorAforgeFake.
PrepareNetwork()
abstract void IG.Num.NeuralApproximatorBase.PrepareNetwork () pure virtual
Prepares neural network for use. If networks have not yet been created accordinfg to internal data, they are created. If networks are already prepared then this method does nothing.
Some things suc as creation of a neural network follow the pattern of lazy evaluation.
Implements IG.Num.INeuralApproximator.
Implemented in IG.Num.NeuralApproximatorAforgeFake.
CreateNetwork()
abstract void IG.Num.NeuralApproximatorBase.CreateNetwork () pure virtual
Creates the neural network anew. It the network already exists on the current object, it is discarded.
Implements IG.Num.INeuralApproximator.
Implemented in IG.Num.NeuralApproximatorAforgeFake.
ResetNetwork()
abstract void IG.Num.NeuralApproximatorBase.ResetNetwork () pure virtual
Resets the neural network.
Implements IG.Num.INeuralApproximator.
Implemented in IG.Num.NeuralApproximatorAforgeFake.
DestroyNetwork()
abstract void IG.Num.NeuralApproximatorBase.DestroyNetwork () pure virtual
Destroys the neural network.
Implements IG.Num.INeuralApproximator.
Implemented in IG.Num.NeuralApproximatorAforgeFake.
GetNetworkFilePath()
string IG.Num.NeuralApproximatorBase.GetNetworkFilePath (string fileOrDirectoryPath, int whichNetwork) inline
Returns an absolute path to the file for storing the specified neural network contained on the current object, with respect to suggested file path and index of the network. The returned path is in the same directory as suggested file path and has the same file extension (if any). If the suggested path represents a directory, then some default suggested path is assumed. If there is only one network then the returned file path is the same as the suggested one (or the same as default file name within the suggested directory, if a directory path is proposed).
Parameters
fileOrDirectoryPath Suggested file or directory path, can be a relative path.
whichNetwork Index of the network for which path of the file to store the network is returned.
Returns
Implements IG.Num.INeuralApproximator.
Definition at line 1253 of file NeuralApproximatorBase.cs.
References IG.Num.NeuralApproximatorBase._defaultNetworkFilename, and IG.Num.NeuralApproximatorBase.MultipleNetworks.
SaveNetwork()
void IG.Num.NeuralApproximatorBase.SaveNetwork (string filePath) inline
Saves the state of the neural network to the specified file. If the file already exists, its contents are overwritten.
Parameters
filePath Path to the file into which the network is saved.
Implements IG.Num.INeuralApproximator.
Definition at line 1383 of file NeuralApproximatorBase.cs.
References IG.Num.NeuralApproximatorBase.NetworkStateFilePath, and IG.Num.NeuralApproximatorBase.SaveNetworkSpecific().
LoadNetwork()
void IG.Num.NeuralApproximatorBase.LoadNetwork (string filePath) inline
Restores neural network from a file where it has been stored before.
Parameters
filePath Path to the file from which the neural network is read.
Implements IG.Num.INeuralApproximator.
Definition at line 1395 of file NeuralApproximatorBase.cs.
References IG.Num.NeuralApproximatorBase.LoadNetworkSpecific(), IG.Num.NeuralApproximatorBase.NetworkStateFilePath, and IG.Num.NeuralApproximatorBase.NetworkTrained.
SaveNetworkSpecific()
abstract void IG.Num.NeuralApproximatorBase.SaveNetworkSpecific (string filePath) protected pure virtual
Saves the state of the neural network to the specified file. If the file already exists, its contents are overwritten.
Parameters
filePath Path to the file into which the network is saved.
Implemented in IG.Num.NeuralApproximatorAforgeFake.
Referenced by IG.Num.NeuralApproximatorBase.SaveNetwork().
LoadNetworkSpecific()
abstract void IG.Num.NeuralApproximatorBase.LoadNetworkSpecific (string filePath, bool useSerializationBinderIfSpecified = true) protected pure virtual
Restores neural network from a file where it has been stored before.
Parameters
filePath Path to the file from which the neural network is read.
useSerializationBinderIfSpecified Whether the SerializationBinder should be used when specified.
Implemented in IG.Num.NeuralApproximatorAforgeFake.
Referenced by IG.Num.NeuralApproximatorBase.LoadNetwork().
SetTrainingAndVerificationData()
void IG.Num.NeuralApproximatorBase.SetTrainingAndVerificationData (SampledDataSet trainingData, SampledDataSet verificationData) inline
Auxiliary function, sets training and verification data for training the network.
Parameters
trainingData Training data.
verificationData Verification data.
Implements IG.Num.INeuralApproximator.
Definition at line 1480 of file NeuralApproximatorBase.cs.
References IG.Num.NeuralApproximatorBase._trainingData, IG.Lib.SortedUniqueItemList< Type >.Add(), IG.Num.SampledDataSet.Add(), IG.Num.SampledDataSet.Clear(), IG.Num.SampledDataSet.Length, IG.Lib.ILockable.Lock, and IG.Num.NeuralApproximatorBase.VerificationIndices.
GetTrainingData()
void IG.Num.NeuralApproximatorBase.GetTrainingData (ref SampledDataSet trainingData) inline
Auxiliary function, returns network's training data.
Parameters
trainingData
Implements IG.Num.INeuralApproximator.
Definition at line 1501 of file NeuralApproximatorBase.cs.
References IG.Num.NeuralApproximatorBase._trainingData, IG.Lib.SortedUniqueItemList< Type >.Contains(), IG.Num.SampledDataSet.Length, and IG.Num.NeuralApproximatorBase.VerificationIndices.
Referenced by IG.Num.NeuralApproximatorBase.GetTrainingAndVerificationData().
GetVerificationData()
void IG.Num.NeuralApproximatorBase.GetVerificationData (ref SampledDataSet veerificationData) inline
Auxliliary function, returns network's verification data.
Parameters
veerificationData
Implements IG.Num.INeuralApproximator.
Definition at line 1516 of file NeuralApproximatorBase.cs.
References IG.Num.NeuralApproximatorBase._trainingData, IG.Lib.SortedUniqueItemList< Type >.Contains(), IG.Num.SampledDataSet.Length, and IG.Num.NeuralApproximatorBase.VerificationIndices.
Referenced by IG.Num.NeuralApproximatorBase.GetTrainingAndVerificationData().
GetTrainingAndVerificationData()
void IG.Num.NeuralApproximatorBase.GetTrainingAndVerificationData (ref SampledDataSet trainingData, ref SampledDataSet verificationData) inline
Auxiliary function, obtains network's training and verification data.
Parameters
trainingData Variable where training data is stored.
verificationData Variable where verificatio data is stored.
Implements IG.Num.INeuralApproximator.
Definition at line 1532 of file NeuralApproximatorBase.cs.
References IG.Num.NeuralApproximatorBase.GetTrainingData(), and IG.Num.NeuralApproximatorBase.GetVerificationData().
SaveTrainingDataJson()
void IG.Num.NeuralApproximatorBase.SaveTrainingDataJson (string filePath) inline
Saves network's training data to the specified JSON file. File is owerwritten if it exists.
Parameters
filePath Path to the file where training data is saved.
Implements IG.Num.INeuralApproximator.
Definition at line 1542 of file NeuralApproximatorBase.cs.
References IG.Lib.ILockable.Lock, and IG.Num.NeuralApproximatorBase.TrainingData.
LoadTrainingDataJson()
void IG.Num.NeuralApproximatorBase.LoadTrainingDataJson (string filePath) inline
Restores training data from the specified file in JSON format.
Parameters
filePath File from which training data is restored.
Implements IG.Num.INeuralApproximator.
Definition at line 1555 of file NeuralApproximatorBase.cs.
References IG.Lib.ILockable.Lock, and IG.Num.NeuralApproximatorBase.TrainingData.
SetNeuronsInputRange()
void IG.Num.NeuralApproximatorBase.SetNeuronsInputRange (double min, double max) inline
Sets the neurons input range. Bounds for all input neurons are set equally.
Parameters
min Lower bound for all input neurons.
max Upper bound for all input neurons.
Implements IG.Num.INeuralApproximator.
Definition at line 1706 of file NeuralApproximatorBase.cs.
References IG.Num.NeuralApproximatorBase.InputLength, IG.Num.NeuralApproximatorBase.InputNeuronsRange, IG.Num.NeuralApproximatorBase.InvalidateTrainingDataDependencies(), IG.Lib.ILockable.Lock, IG.Num.IBoundingBox.SetDimensionAndReset(), and IG.Num.IBoundingBox.Update().
SetNeuronsOutputRange()
void IG.Num.NeuralApproximatorBase.SetNeuronsOutputRange (double min, double max) inline
Sets the neurons output range. Bounds for all output neurons are set equally.
Parameters
min Lower bound for all output neurons.
max Upper bound for all output neurons.
Implements IG.Num.INeuralApproximator.
Definition at line 1723 of file NeuralApproximatorBase.cs.
References IG.Num.NeuralApproximatorBase.InvalidateTrainingDataDependencies(), IG.Lib.ILockable.Lock, IG.Num.NeuralApproximatorBase.OutputLength, IG.Num.NeuralApproximatorBase.OutputNeuronsRange, IG.Num.IBoundingBox.SetDimensionAndReset(), and IG.Num.IBoundingBox.Update().
RecalculateInputDataBounds() [1/2]
void IG.Num.NeuralApproximatorBase.RecalculateInputDataBounds () inline
Recalculates input data bounds by taking into account the training data set of the current object.
Training data dependencies are invalidated by this method because setting bounds invalidates them.
Implements IG.Num.INeuralApproximator.
Definition at line 1740 of file NeuralApproximatorBase.cs.
References IG.Num.NeuralApproximatorBase.TrainingData.
Referenced by IG.Num.NeuralApproximatorBase.RecalculateDataBounds().
RecalculateOutputDataBounds() [1/2]
void IG.Num.NeuralApproximatorBase.RecalculateOutputDataBounds () inline
Recalculates output data bounds by taking into account the training data set of the current object.
Training data dependencies are invalidated by this method because setting bounds invalidates them.
Implements IG.Num.INeuralApproximator.
Definition at line 1747 of file NeuralApproximatorBase.cs.
References IG.Num.NeuralApproximatorBase.TrainingData.
Referenced by IG.Num.NeuralApproximatorBase.RecalculateDataBounds().
RecalculateDataBounds() [1/2]
void IG.Num.NeuralApproximatorBase.RecalculateDataBounds () inline
Recalculates input and output data bounds by taking into account the training data set of the current object.
Training data dependencies are invalidated by this method because setting bounds invalidates them.
Implements IG.Num.INeuralApproximator.
Definition at line 1754 of file NeuralApproximatorBase.cs.
References IG.Num.NeuralApproximatorBase.TrainingData.
RecalculateInputDataBounds() [2/2]
void IG.Num.NeuralApproximatorBase.RecalculateInputDataBounds (SampledDataSet trainingData) inline
Recalculates input data bounds by taking into account the specified training data set.
Parameters
trainingData Training data set accourding to which input bounds are adjusted.
Training data dependencies are invalidated by this method because setting bounds invalidates them.
Implements IG.Num.INeuralApproximator.
Definition at line 1762 of file NeuralApproximatorBase.cs.
References IG.Num.SampledDataSet.GetInputRange(), IG.Num.NeuralApproximatorBase.InputBoundsSafetyFactor, IG.Num.NeuralApproximatorBase.InputDataBounds, and IG.Lib.ILockable.Lock.
RecalculateOutputDataBounds() [2/2]
void IG.Num.NeuralApproximatorBase.RecalculateOutputDataBounds (SampledDataSet trainingData) inline
Recalculates output data bounds by taking into account the specified training data set.
Parameters
trainingData Training data set accourding to which output bounds are adjusted.
Training data dependencies are invalidated by this method because setting bounds invalidates them.
Implements IG.Num.INeuralApproximator.
Definition at line 1785 of file NeuralApproximatorBase.cs.
References IG.Num.SampledDataSet.GetOutputRange(), IG.Lib.ILockable.Lock, IG.Num.NeuralApproximatorBase.OutputBoundsSafetyFactor, and IG.Num.NeuralApproximatorBase.OutputDataBounds.
RecalculateDataBounds() [2/2]
void IG.Num.NeuralApproximatorBase.RecalculateDataBounds (SampledDataSet trainingData) inline
Recalculates input and output data bounds by taking into account the specified training data set.
Parameters
trainingData Training data set accourding to which input and output bounds are adjusted.
Training data dependencies are invalidated by this method because setting bounds invalidates them.
Implements IG.Num.INeuralApproximator.
Definition at line 1808 of file NeuralApproximatorBase.cs.
References IG.Lib.ILockable.Lock, IG.Num.NeuralApproximatorBase.RecalculateInputDataBounds(), and IG.Num.NeuralApproximatorBase.RecalculateOutputDataBounds().
MapInput() [1/2]
virtual double IG.Num.NeuralApproximatorBase.MapInput (int componentIndex, double value) inline protected virtual
Maps (scales and shifts) and returns specific input value to the value prepared for the corresponding input neuron.
Parameters
componentIndex Index of the input value within the input vector.
value Value that is mapped.
Returns
Input value mapped for the input to neural network.
Definition at line 1823 of file NeuralApproximatorBase.cs.
References IG.Num.NeuralApproximatorBase.InputDataBounds, IG.Num.NeuralApproximatorBase.InputNeuronsRange, and IG.Num.BoundingBoxBase.Map().
Referenced by IG.Num.NeuralApproximatorBase.TestMapping().
MapFromNeuralInput() [1/2]
virtual double IG.Num.NeuralApproximatorBase.MapFromNeuralInput (int componentIndex, double value) inline protected virtual
Inverse maps (scales and shifts) and returns specific input value back from the neural input to the actual input.
Parameters
componentIndex Index of the input value within the input vector.
value Value that is mapped back from neural input.
Returns
Input value mapped back from the neural input.
Definition at line 1842 of file NeuralApproximatorBase.cs.
References IG.Num.NeuralApproximatorBase.InputDataBounds, IG.Num.NeuralApproximatorBase.InputNeuronsRange, and IG.Num.BoundingBoxBase.Map().
Referenced by IG.Num.NeuralApproximatorBase.TestMapping().
MapInput() [2/2]
virtual void IG.Num.NeuralApproximatorBase.MapInput (IVector values, ref IVector mappedValues) inline protected virtual
Maps (scales and shifts) vector of input values to the vector of neuron inputs.
Parameters
values Vector of input values to be mapped.
mappedValues Vector where mapped values are stored.
Definition at line 1860 of file NeuralApproximatorBase.cs.
References IG.Num.NeuralApproximatorBase.InputDataBounds, IG.Num.NeuralApproximatorBase.InputNeuronsRange, and IG.Num.BoundingBoxBase.Map().
MapFromNeuralInput() [2/2]
virtual void IG.Num.NeuralApproximatorBase.MapFromNeuralInput (IVector values, ref IVector mappedValues) inline protected virtual
Inverse maps (scales and shifts) vector of neural input values back to the vector of actual inputs.
Parameters
values Vector of neural inputs to be mapped.
mappedValues Vector where inverse mapped values are stored.
Definition at line 1879 of file NeuralApproximatorBase.cs.
References IG.Num.NeuralApproximatorBase.InputDataBounds, IG.Num.NeuralApproximatorBase.InputNeuronsRange, and IG.Num.BoundingBoxBase.Map().
MapOutput() [1/2]
virtual double IG.Num.NeuralApproximatorBase.MapOutput (int componentIndex, double value) inline protected virtual
Maps (scales and shifts) and returns specific output value to the output value of the corresponding output neuron.
Parameters
componentIndex Index of the output value within the output vector.
value Value that is mapped.
Returns
Output value mapped for the output to neural network.
Definition at line 1900 of file NeuralApproximatorBase.cs.
References IG.Num.BoundingBoxBase.Map(), IG.Num.NeuralApproximatorBase.OutputDataBounds, and IG.Num.NeuralApproximatorBase.OutputNeuronsRange.
Referenced by IG.Num.NeuralApproximatorBase.TestMapping().
MapFromNeuralOutput() [1/2]
virtual double IG.Num.NeuralApproximatorBase.MapFromNeuralOutput (int componentIndex, double value) inline protected virtual
Inverse maps (scales and shifts) and returns specific output value back from the neural output to the actual output.
Parameters
componentIndex Index of the output value within the output vector.
value Value that is mapped back from neural output.
Returns
Output value mapped back from the neural output.
Definition at line 1919 of file NeuralApproximatorBase.cs.
References IG.Num.BoundingBoxBase.Map(), IG.Num.NeuralApproximatorBase.OutputDataBounds, and IG.Num.NeuralApproximatorBase.OutputNeuronsRange.
Referenced by IG.Num.NeuralApproximatorBase.TestMapping().
MapOutput() [2/2]
virtual void IG.Num.NeuralApproximatorBase.MapOutput (IVector values, ref IVector mappedValues) inline protected virtual
Maps (scales and shifts) vector of output values to the vector of neuron outputs.
Parameters
values Vector of output values to be mapped.
mappedValues Vector where mapped values are stored.
Definition at line 1937 of file NeuralApproximatorBase.cs.
References IG.Num.BoundingBoxBase.Map(), IG.Num.NeuralApproximatorBase.OutputDataBounds, and IG.Num.NeuralApproximatorBase.OutputNeuronsRange.
MapFromNeuralOutput() [2/2]
virtual void IG.Num.NeuralApproximatorBase.MapFromNeuralOutput (IVector values, ref IVector mappedValues) inline protected virtual
Inverse maps (scales and shifts) vector of neural output values back to the vector of actual outputs.
Parameters
values Vector of neural outputs to be mapped.
mappedValues Vector where inverse mapped values are stored.
Definition at line 1956 of file NeuralApproximatorBase.cs.
References IG.Num.BoundingBoxBase.Map(), IG.Num.NeuralApproximatorBase.OutputDataBounds, and IG.Num.NeuralApproximatorBase.OutputNeuronsRange.
CalculateTrainingVerificationOutputs()
void IG.Num.NeuralApproximatorBase.CalculateTrainingVerificationOutputs (bool calculateTrainingOutputs, bool calculateVerificationOutputs) inline protected
Calculates outputs in training points contained in training set, either in training points, in verification points, or both.
Parameters
calculateTrainingOutputs Whether outputs are calculated in training points.
calculateVerificationOutputs Whether outputs are calculated in verification points.
Definition at line 2035 of file NeuralApproximatorBase.cs.
References IG.Num.NeuralApproximatorBase._calculatedOutputs, IG.Num.NeuralApproximatorBase.CalculateOutput(), IG.Lib.SortedUniqueItemList< Type >.Contains(), IG.Num.SampledDataElement.InputParameters, IG.Num.SampledDataSet.Length, IG.Lib.ILockable.Lock, IG.Num.NeuralApproximatorBase.TrainingData, IG.Num.NeuralApproximatorBase.TrainingOutputsCalculated, IG.Num.NeuralApproximatorBase.VerificationIndices, and IG.Num.NeuralApproximatorBase.VerificationOutputsCalculated.
Referenced by IG.Num.NeuralApproximatorBase.CalculateTrainingOutputs(), IG.Num.NeuralApproximatorBase.CalculateVerificationOutputs(), and IG.Num.NeuralApproximatorBase.PrepareErrorData().
CalculateTrainingOutputs()
void IG.Num.NeuralApproximatorBase.CalculateTrainingOutputs () inline protected
Calculates outputs in training points of the training data set (this excludes verification points).
Definition at line 2085 of file NeuralApproximatorBase.cs.
References IG.Num.NeuralApproximatorBase.CalculateTrainingVerificationOutputs().
CalculateVerificationOutputs()
void IG.Num.NeuralApproximatorBase.CalculateVerificationOutputs () inline protected
Calculates outputs in verification points of the training data set.
Definition at line 2091 of file NeuralApproximatorBase.cs.
References IG.Num.NeuralApproximatorBase.CalculateTrainingVerificationOutputs().
CalculateErrorsRms()
static void IG.Num.NeuralApproximatorBase.CalculateErrorsRms (int dimOutput, IVector[] prescribed, IVector[] calculated, ref IVector errors) inline static
Calculates error measures - RMS (root mean square) of the differences - for the specified arrays of prescribed and calculated output values in a set of sampling points.
Parameters
dimOutput Dimension of output values.
prescribed Array of prescribed output values (e.g. from training data, measurements, etc.).
calculated Array of calculated output values (e.g. by a trained neural network).
errors Vector where error measures for each indivitual output value are stored.
Definition at line 2103 of file NeuralApproximatorBase.cs.
References IG.Num.IVector< T >.Length, and IG.Num.VectorBase.Resize().
Referenced by IG.Num.NeuralApproximatorBase.GetErrorsTrainingRms(), and IG.Num.NeuralApproximatorBase.GetErrorsVerificationRms().
CalculateErrorsMeanAbs()
static void IG.Num.NeuralApproximatorBase.CalculateErrorsMeanAbs (int dimOutput, IVector[] prescribed, IVector[] calculated, ref IVector errors) inline static
Calculates error measures - mean absolute value of the differences - for the specified arrays of prescribed and calculated output values in a set of sampling points.
Parameters
dimOutput Dimension of output values.
prescribed Array of prescribed output values (e.g. from training data, measurements, etc.).
calculated Array of calculated output values (e.g. by a trained neural network).
errors Vector where error measures for each indivitual output value are stored.
Definition at line 2161 of file NeuralApproximatorBase.cs.
References IG.Num.IVector< T >.Length, and IG.Num.VectorBase.Resize().
Referenced by IG.Num.NeuralApproximatorBase.GetErrorsTrainingMeanAbs(), and IG.Num.NeuralApproximatorBase.GetErrorsVerificationMeanAbs().
CalculateErrorsMax()
static void IG.Num.NeuralApproximatorBase.CalculateErrorsMax (int dimOutput, IVector[] prescribed, IVector[] calculated, ref IVector errors) inline static
Calculates error measures - maximum absolute value of the differences - for the specified arrays of prescribed and calculated output values in a set of sampling points.
Parameters
dimOutput Dimension of output values.
prescribed Array of prescribed output values (e.g. from training data, measurements, etc.).
calculated Array of calculated output values (e.g. by a trained neural network).
errors Vector where error measures for each indivitual output value are stored.
Definition at line 2217 of file NeuralApproximatorBase.cs.
References IG.Num.IVector< T >.Length, and IG.Num.VectorBase.Resize().
Referenced by IG.Num.NeuralApproximatorBase.GetErrorsTrainingMax(), and IG.Num.NeuralApproximatorBase.GetErrorsVerificationMax().
PrepareErrorData()
virtual void IG.Num.NeuralApproximatorBase.PrepareErrorData (ref int dimOutput, ref IVector[] prescribed, ref IVector[] calculated, bool takeTrainingPoints, bool takeVerificationPoints) inline protected virtual
Prepares data for calculation of various error measures over training points or in verification points after training of the neural network(s).
Parameters
dimOutput Location where number (dimension) of output values is stored.
prescribed Array where prescribed values from the training set are stored.
calculated Array where calculated values in the corresponding points from the training set are stored.
takeTrainingPoints Specifies whether training points (i.e., excludingverification points) are taken from the training set to constitute the output data.
takeVerificationPoints Specifies whether verification points are taken from the training set.
Definition at line 2277 of file NeuralApproximatorBase.cs.
References IG.Num.NeuralApproximatorBase._calculated, IG.Num.NeuralApproximatorBase._calculatedOutputs, IG.Num.NeuralApproximatorBase._prescribed, IG.Num.NeuralApproximatorBase.CalculateTrainingVerificationOutputs(), IG.Lib.SortedUniqueItemList< Type >.Contains(), IG.Num.SampledDataSet.GetOutputValues(), IG.Num.SampledDataSet.Length, IG.Lib.ILockable.Lock, IG.Num.NeuralApproximatorBase.OutputLength, IG.Num.NeuralApproximatorBase.TrainingData, IG.Num.NeuralApproximatorBase.TrainingOutputsCalculated, IG.Num.NeuralApproximatorBase.VerificationIndices, and IG.Num.NeuralApproximatorBase.VerificationOutputsCalculated.
Referenced by IG.Num.NeuralApproximatorBase.GetErrorsTrainingMax(), IG.Num.NeuralApproximatorBase.GetErrorsTrainingMeanAbs(), IG.Num.NeuralApproximatorBase.GetErrorsTrainingRms(), IG.Num.NeuralApproximatorBase.GetErrorsVerificationMax(), IG.Num.NeuralApproximatorBase.GetErrorsVerificationMeanAbs(), and IG.Num.NeuralApproximatorBase.GetErrorsVerificationRms().
GetErrorsTrainingRms()
void IG.Num.NeuralApproximatorBase.GetErrorsTrainingRms (ref IVector errors) inline
Calculates the RMS (root mean square) of the errors of output values for the training elements of the training set (this excludes verification points).
Parameters
errors
Implements IG.Num.INeuralApproximator.
Definition at line 2320 of file NeuralApproximatorBase.cs.
References IG.Num.NeuralApproximatorBase.CalculateErrorsRms(), and IG.Num.NeuralApproximatorBase.PrepareErrorData().
Referenced by IG.Num.NeuralTrainingParameters.CopyResultsFrom(), IG.Num.NeuralApproximatorBase.StopTrainingCriteriaMet(), and IG.Num.NeuralApproximatorBase.TrainNetwork().
GetErrorsVerificationRms()
void IG.Num.NeuralApproximatorBase.GetErrorsVerificationRms (ref IVector errors) inline
Calculates the RMS (root mean square) of the errors of output values for the verification elements of the training set.
Parameters
errors
Implements IG.Num.INeuralApproximator.
Definition at line 2335 of file NeuralApproximatorBase.cs.
References IG.Num.NeuralApproximatorBase.CalculateErrorsRms(), and IG.Num.NeuralApproximatorBase.PrepareErrorData().
Referenced by IG.Num.NeuralTrainingParameters.CopyResultsFrom(), and IG.Num.NeuralApproximatorBase.TrainNetwork().
GetErrorsTrainingMax()
void IG.Num.NeuralApproximatorBase.GetErrorsTrainingMax (ref IVector errors) inline
Calculates the maximum absolute errors of output values for the training elements of the training set (this excludes verification points).
Parameters
errors
Implements IG.Num.INeuralApproximator.
Definition at line 2349 of file NeuralApproximatorBase.cs.
References IG.Num.NeuralApproximatorBase.CalculateErrorsMax(), and IG.Num.NeuralApproximatorBase.PrepareErrorData().
Referenced by IG.Num.NeuralTrainingParameters.CopyResultsFrom(), IG.Num.NeuralApproximatorBase.StopTrainingCriteriaMet(), and IG.Num.NeuralApproximatorBase.TrainNetwork().
GetErrorsVerificationMax()
void IG.Num.NeuralApproximatorBase.GetErrorsVerificationMax (ref IVector errors) inline
Calculates the maximum absolute errors of output values for the verification elements of the training set.
Parameters
errors
Implements IG.Num.INeuralApproximator.
Definition at line 2364 of file NeuralApproximatorBase.cs.
References IG.Num.NeuralApproximatorBase.CalculateErrorsMax(), and IG.Num.NeuralApproximatorBase.PrepareErrorData().
Referenced by IG.Num.NeuralTrainingParameters.CopyResultsFrom(), and IG.Num.NeuralApproximatorBase.TrainNetwork().
GetErrorsTrainingMeanAbs()
void IG.Num.NeuralApproximatorBase.GetErrorsTrainingMeanAbs (ref IVector errors) inline
Calculates the mean absolute errors of output values for the training elements of the training set (this excludes verification points).
Parameters
errors
Implements IG.Num.INeuralApproximator.
Definition at line 2378 of file NeuralApproximatorBase.cs.
References IG.Num.NeuralApproximatorBase.CalculateErrorsMeanAbs(), and IG.Num.NeuralApproximatorBase.PrepareErrorData().
Referenced by IG.Num.NeuralTrainingParameters.CopyResultsFrom().
GetErrorsVerificationMeanAbs()
void IG.Num.NeuralApproximatorBase.GetErrorsVerificationMeanAbs (ref IVector errors) inline
Calculates the mean absolute errors of output values for the verification elements of the training set.
Parameters
errors
Implements IG.Num.INeuralApproximator.
Definition at line 2393 of file NeuralApproximatorBase.cs.
References IG.Num.NeuralApproximatorBase.CalculateErrorsMeanAbs(), and IG.Num.NeuralApproximatorBase.PrepareErrorData().
Referenced by IG.Num.NeuralTrainingParameters.CopyResultsFrom().
PrepareInternalTrainingData()
abstract void IG.Num.NeuralApproximatorBase.PrepareInternalTrainingData () protected pure virtual
Prepares internal training data that is needed by the native training algorithm. When overridden, this method must set the InternalTrainingDataPrepared flag to true.
Implemented in IG.Num.NeuralApproximatorAforgeFake.
InvalidateTrainingDependencies()
virtual void IG.Num.NeuralApproximatorBase.InvalidateTrainingDependencies () inline virtual
Invalidates all data that must be recalculated after training of the network is done. This method is called after training or additional training of the network is performed. Invalidation is achieved throughthe the appropriate flags.
Implements IG.Num.INeuralApproximator.
Definition at line 2440 of file NeuralApproximatorBase.cs.
References IG.Num.NeuralApproximatorBase.NetworkStateFilePath, IG.Num.NeuralApproximatorBase.TrainingOutputsCalculated, and IG.Num.NeuralApproximatorBase.VerificationOutputsCalculated.
Referenced by IG.Num.NeuralApproximatorBase.InvalidateTrainingDataDependencies().
InvalidateTrainingDataDependencies()
virtual void IG.Num.NeuralApproximatorBase.InvalidateTrainingDataDependencies () inline virtual
Invalidates all data that must be re-calculated after training data changes. This method is called after training data is modified. Invalidation is achieved throughthe the appropriate flags.
Implements IG.Num.INeuralApproximator.
Definition at line 2450 of file NeuralApproximatorBase.cs.
References IG.Num.NeuralApproximatorBase.EpochCount, IG.Num.NeuralApproximatorBase.InternalTrainingDataPrepared, IG.Num.NeuralApproximatorBase.InvalidateTrainingDependencies(), and IG.Num.NeuralApproximatorBase.NetworkTrained.
Referenced by IG.Num.NeuralApproximatorBase.InvalidateNetworkDependencies(), IG.Num.NeuralApproximatorBase.SetNeuronsInputRange(), and IG.Num.NeuralApproximatorBase.SetNeuronsOutputRange().
InvalidateNetworkDependencies()
virtual void IG.Num.NeuralApproximatorBase.InvalidateNetworkDependencies () inline virtual
Invalidates all data that must be re-calculated after the neural network itself changes. This method must be called after the internal neural network is re-defined (or are re-defined). Invalidation is achieved throughthe the appropriate flags.
Implements IG.Num.INeuralApproximator.
Definition at line 2461 of file NeuralApproximatorBase.cs.
References IG.Num.NeuralApproximatorBase.InvalidateTrainingDataDependencies(), and IG.Num.NeuralApproximatorBase.NetworkPrepared.
TrainNetwork() [1/2]
void IG.Num.NeuralApproximatorBase.TrainNetwork (int numEpochs) inline
Trains neural network wiht the specified data, performing the specified number of epochs.
Parameters
numEpochs Number of epochs used in training of the network.
Implements IG.Num.INeuralApproximator.
Definition at line 2487 of file NeuralApproximatorBase.cs.
References IG.Num.NeuralApproximatorBase.ConvergenceErrorsTrainingMaxList, IG.Num.NeuralApproximatorBase.ConvergenceErrorsTrainingRmsList, IG.Num.NeuralApproximatorBase.ConvergenceErrorsVerificationMaxList, IG.Num.NeuralApproximatorBase.ConvergenceErrorsVerificationRmsList, IG.Num.NeuralApproximatorBase.EpochCount, IG.Num.NeuralApproximatorBase.EpochNumbers, IG.Num.NeuralApproximatorBase.GetErrorsTrainingMax(), IG.Num.NeuralApproximatorBase.GetErrorsTrainingRms(), IG.Num.NeuralApproximatorBase.GetErrorsVerificationMax(), IG.Num.NeuralApproximatorBase.GetErrorsVerificationRms(), IG.Num.NeuralApproximatorBase.OutputLength, IG.Num.NeuralApproximatorBase.SaveConvergenceRms, and IG.Num.NeuralApproximatorBase.TrainNetworkSpecific().
Referenced by IG.Num.NeuralApproximatorBase.ExampleQuadratic().
TrainNetworkSpecific()
abstract void IG.Num.NeuralApproximatorBase.TrainNetworkSpecific (int numEpochs) protected pure virtual
Trains neural network wiht the specified data, performing the specified number of epochs. This method must be implemented in derived classes and is specific to specific network type.
Parameters
numEpochs Number of epochs used in training of the network.
Implemented in IG.Num.NeuralApproximatorAforgeFake.
Referenced by IG.Num.NeuralApproximatorBase.TrainNetwork(), and IG.Num.NeuralApproximatorBase.TrainNetworkMultiple().
TrainNetworkMultiple() [1/2]
void IG.Num.NeuralApproximatorBase.TrainNetworkMultiple (int numEpochs, int numIterations) inline
Performs a specified number of training iterations where the specified number of epochs are run in each iteration.
Parameters
numEpochs Number of epochs run in each iteration.
numIterations Number of iterations.
Definition at line 2545 of file NeuralApproximatorBase.cs.
References IG.Num.NeuralApproximatorBase.BreakTraining, and IG.Num.NeuralApproximatorBase.TrainNetworkSpecific().
Referenced by IG.Num.NeuralApproximatorBase.TrainNetworkMultiple().
TrainNetworkMultiple() [2/2]
void IG.Num.NeuralApproximatorBase.TrainNetworkMultiple (int numIterations) inline
Performs a specified number of training iterations where the prescribed number of epochs (contained in the EpochsInBundle property) are run in each iteration.
Parameters
numIterations Number of iterations.
Definition at line 2559 of file NeuralApproximatorBase.cs.
References IG.Num.NeuralApproximatorBase.BreakTraining, IG.Num.NeuralApproximatorBase.EpochsInBundle, and IG.Num.NeuralApproximatorBase.TrainNetworkMultiple().
TrainNetwork() [2/2]
virtual void IG.Num.NeuralApproximatorBase.TrainNetwork () inline virtual
Trains neural network until stopping criteria are met (in terms of errors and number of epochs performed.
Implements IG.Num.INeuralApproximator.
Definition at line 2567 of file NeuralApproximatorBase.cs.
References IG.Num.NeuralApproximatorBase.BreakTraining, IG.Num.NeuralApproximatorBase.ConvergenceErrorsTrainingMaxList, IG.Num.NeuralApproximatorBase.ConvergenceErrorsTrainingRmsList, IG.Num.NeuralApproximatorBase.ConvergenceErrorsVerificationMaxList, IG.Num.NeuralApproximatorBase.ConvergenceErrorsVerificationRmsList, IG.Num.NeuralApproximatorBase.EpochCount, IG.Num.NeuralApproximatorBase.EpochNumbers, IG.Num.NeuralApproximatorBase.EpochsInBundle, IG.Num.NeuralApproximatorBase.GetErrorsTrainingMax(), IG.Num.NeuralApproximatorBase.GetErrorsTrainingRms(), IG.Num.NeuralApproximatorBase.GetErrorsVerificationMax(), IG.Num.NeuralApproximatorBase.GetErrorsVerificationRms(), IG.Lib.ILockable.Lock, IG.Num.NeuralApproximatorBase.OnBundleCompleted(), IG.Num.NeuralApproximatorBase.OnTrainingCompleted(), IG.Num.NeuralApproximatorBase.OutputLength, IG.Num.NeuralApproximatorBase.SaveConvergenceRms, IG.Num.NeuralApproximatorBase.StopTrainingCriteriaMet(), and IG.Num.NeuralApproximatorBase.TrainNetworkSpecific().
StopTrainingCriteriaMet()
virtual bool IG.Num.NeuralApproximatorBase.StopTrainingCriteriaMet () inline virtual
Returns true if the stopping criteria for training is met, with respect to current settings, errors and number of epochs already performed, and false otherwise.
Implements IG.Num.INeuralApproximator.
Definition at line 2633 of file NeuralApproximatorBase.cs.
References IG.Num.NeuralApproximatorBase._auxErrors, IG.Num.NeuralApproximatorBase.EpochCount, IG.Num.NeuralApproximatorBase.GetErrorsTrainingMax(), IG.Num.NeuralApproximatorBase.GetErrorsTrainingRms(), IG.Lib.ILockable.Lock, IG.Num.NeuralApproximatorBase.MaxEpochs, IG.Num.NeuralApproximatorBase.OutputLength, IG.Num.NeuralApproximatorBase.ToleranceMax, and IG.Num.NeuralApproximatorBase.ToleranceRms.
Referenced by IG.Num.NeuralApproximatorBase.TrainNetwork().
OnBundleCompleted()
virtual void IG.Num.NeuralApproximatorBase.OnBundleCompleted () inline protected virtual
Called after completion of each bundle of training epochs (after auxiliary data is updated).
Definition at line 2739 of file NeuralApproximatorBase.cs.
References IG.Num.NeuralApproximatorBase.BundleCompleted, IG.Num.NeuralApproximatorBase.CommonEventArgs, IG.Num.NeuralApproximatorBase.EpochCount, IG.Num.NeuralApproximatorBase.MaxEpochs, and IG.Num.NeuralApproximatorBase.OutputLevel.
Referenced by IG.Num.NeuralApproximatorBase.TrainNetwork().
OnTrainingCompleted()
virtual void IG.Num.NeuralApproximatorBase.OnTrainingCompleted () inline protected virtual
Called after completion of training procedure (after all auxiliary data is updated, raises the TrainingCompleted event..
Definition at line 2768 of file NeuralApproximatorBase.cs.
References IG.Num.NeuralApproximatorBase.CommonEventArgs, IG.Num.NeuralApproximatorBase.EpochCount, IG.Num.NeuralApproximatorBase.MaxEpochs, IG.Num.NeuralApproximatorBase.OutputLevel, and IG.Num.NeuralApproximatorBase.TrainingCompleted.
Referenced by IG.Num.NeuralApproximatorBase.TrainNetwork().
CalculateOutput() [1/2]
override double IG.Num.NeuralApproximatorBase.CalculateOutput (IVector input, int whichElement) inline
Calculates and returns the specified output by using the neural network.
Implements IG.Num.IVectorApproximator.
Definition at line 2814 of file NeuralApproximatorBase.cs.
References IG.Num.NeuralApproximatorBase._outputFiltered1, IG.Num.IVector< T >.Length, and IG.Lib.ILockable.Lock.
Referenced by IG.Num.NeuralApproximatorBase.CalculateOutput(), IG.Num.NeuralApproximatorBase.CalculateTrainingVerificationOutputs(), and IG.Num.NeuralApproximatorBase.ExampleQuadratic().
CalculateOutput() [2/2]
override void IG.Num.NeuralApproximatorBase.CalculateOutput (IVector input, int[] indices, ref IVector filteredOutput) inline
Calculates and returns the required output values corresponding to the specified inputs, by using the current neural network(s).
Parameters
input Input parameters for which output values are calculated.
indices Array of indices of the output values to be returned.
filteredOutput Vector where filtered output values are stored.
Implements IG.Num.IVectorApproximator.
Definition at line 2836 of file NeuralApproximatorBase.cs.
References IG.Num.NeuralApproximatorBase._output, IG.Num.NeuralApproximatorBase.CalculateOutput(), IG.Num.IVector< T >.Length, IG.Lib.ILockable.Lock, IG.Num.NeuralApproximatorBase.OutputLength, and IG.Num.VectorBase.Resize().
ToString()
override string IG.Num.NeuralApproximatorBase.ToString () inline
Returns string describing the current neural network approximator.
Definition at line 2878 of file NeuralApproximatorBase.cs.
References IG.Num.NeuralApproximatorBase.InputBoundsSafetyFactor, IG.Num.NeuralApproximatorBase.InputDataBounds, IG.Num.NeuralApproximatorBase.InputNeuronsRange, IG.Num.NeuralApproximatorBase.LearningRate, IG.Num.NeuralApproximatorBase.MaxEpochs, IG.Num.NeuralApproximatorBase.Momentum, IG.Num.NeuralApproximatorBase.OutputBoundsSafetyFactor, IG.Num.NeuralApproximatorBase.OutputDataBounds, IG.Num.NeuralApproximatorBase.OutputNeuronsRange, IG.Num.NeuralApproximatorBase.SigmoidAlphaValue, IG.Num.NeuralApproximatorBase.ToleranceMax, and IG.Num.NeuralApproximatorBase.ToleranceRms.
Referenced by IG.Num.NeuralApproximatorBase.ExampleQuadratic().
SaveJson() [1/2]
static void IG.Num.NeuralApproximatorBase.SaveJson (INeuralApproximator approximator, string filePath) inline static
Saves a neural network approximator to a file. If the neural netwoek is trained then internal state is also saved to a file.
Parameters
approximator Neural network approximator to be saved.
filePath Path to the file where approximator is saved.
Definition at line 2914 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralApproximatorBase.ExampleSaveNetwork().
SaveJson() [2/2]
static void IG.Num.NeuralApproximatorBase.SaveJson (INeuralApproximator approximator, string filePath, bool saveInternalState) inline static
Saves a neural network approximator to a file.
Parameters
approximator Neural network approximator to be saved.
filePath Path to the file where approximator is saved.
saveInternalState Specifies whether internal state should be saved, too (only in the case that network is trained).
Definition at line 2923 of file NeuralApproximatorBase.cs.
References IG.Lib.SerializationDtoBase< Type, BaseType >.CopyFrom(), IG.Lib.UtilSystem.GetRelativePath(), IG.Num.INeuralApproximator.NetworkStateFilePath, IG.Num.INeuralApproximator.NetworkStateRelativePath, IG.Num.INeuralApproximator.NetworkTrained, and IG.Num.INeuralApproximator.SaveNetwork().
LoadJson()
static void IG.Num.NeuralApproximatorBase.LoadJson (string filePath, ref INeuralApproximator approximatorRestored) inline static
Loads network from a file.
Parameters
filePath Path to the file.
approximatorRestored Neural approximator that is produced by deserialization.
Definition at line 2951 of file NeuralApproximatorBase.cs.
References IG.Lib.SerializationDtoBase< Type, BaseType >.CopyTo().
Referenced by IG.Num.NeuralApproximatorBase.ExampleSaveNetwork(), and IG.Neural.NeuraApproximationFileManager.LoadNeuralNetwork().
SaveTrainingDataJson_To_delete()
void IG.Num.NeuralApproximatorBase.SaveTrainingDataJson_To_delete (string filePath) inline
Saves network's training data to the specified JSON file. File is owerwritten if it exists.
Parameters
filePath Path to the file where training data is saved.
Definition at line 2983 of file NeuralApproximatorBase.cs.
References IG.Lib.ILockable.Lock, and IG.Num.NeuralApproximatorBase.TrainingData.
LoadTrainingDataJson_To_Delete()
void IG.Num.NeuralApproximatorBase.LoadTrainingDataJson_To_Delete (string filePath) inline
Restores training data from the specified file in JSON format.
Parameters
filePath File from which training data is restored.
Definition at line 2996 of file NeuralApproximatorBase.cs.
References IG.Lib.ILockable.Lock, and IG.Num.NeuralApproximatorBase.TrainingData.
TestMapping()
void IG.Num.NeuralApproximatorBase.TestMapping () inline
Test back and forth mapping (scaling and shifting) from actual data to data prepared for training, and vice versa (checks if transformed data falls withi the prescribed ranges and if backward transformation yields the same result as forward transformation). Testing is performed on all data from the TrainingData property, including verification elements.
Definition at line 3019 of file NeuralApproximatorBase.cs.
References IG.Lib.SortedUniqueItemList< Type >.Contains(), IG.Num.SampledDataSet.ExtractInputs(), IG.Num.SampledDataSet.ExtractOutputs(), IG.Num.SampledDataSet.GetInputParameters(), IG.Num.SampledDataSet.GetOutputValues(), IG.Num.SampledDataSet.InputLength, IG.Num.NeuralApproximatorBase.InputLength, IG.Num.NeuralApproximatorBase.InputNeuronsRange, IG.Num.SampledDataSet.Length, IG.Num.IBoundingBox.LiesOutside(), IG.Num.NeuralApproximatorBase.MapFromNeuralInput(), IG.Num.NeuralApproximatorBase.MapFromNeuralOutput(), IG.Num.NeuralApproximatorBase.MapInput(), IG.Num.NeuralApproximatorBase.MapOutput(), IG.Num.IBoundingBox.Max, IG.Num.IBoundingBox.Min, IG.Num.SampledDataSet.OutputLength, IG.Num.NeuralApproximatorBase.OutputLength, IG.Num.NeuralApproximatorBase.OutputNeuronsRange, IG.Num.VectorBase.Subtract(), IG.Num.BoundingBoxBase.ToString(), IG.Num.NeuralApproximatorBase.TrainingData, IG.Num.BoundingBoxBase.Update(), and IG.Num.NeuralApproximatorBase.VerificationIndices.
Referenced by IG.Num.NeuralApproximatorBase.ExampleQuadratic().
ExampleSaveNetwork() [1/2]
static void IG.Num.NeuralApproximatorBase.ExampleSaveNetwork (string directoryPath, string fileName, string internalStateFileName) inline static
Example of saving an entire trained neural network to a file, and then restoring it from a file. Network internal state is saved by the SaveNetwork() method that is specific to the type of the network, therefore it is saved to a separate file. The path of this file is savad with the network approximator object itself. Network is saved only once.
Parameters
directoryPath Directory where the neural network is saved.
fileName Name o the file into which the network is saved.
internalStateFileName Name of the file where the state of the trained network (internal representation) is stored.
Definition at line 3179 of file NeuralApproximatorBase.cs.
ExampleSaveNetwork() [2/2]
static void IG.Num.NeuralApproximatorBase.ExampleSaveNetwork (string directoryPath, string fileName, string internalStateFileName, bool saveRestored) inline static
Example of saving an entire trained neural network to a file, and then restoring it from a file. Network internal state is saved by the SaveNetwork() method that is specific to the type of the network, therefore it is saved to a separate file. The path of this file is savad with the network approximator object itself. If the saveRestored flag parameter is true then the restored file ia saved again for comparison.
Parameters
directoryPath Directory where the neural network is saved.
fileName Name o the file into which the network is saved.
internalStateFileName Name of the file where the state of the trained network (internal representation) is stored.
saveRestored If true then the restored neural network is saved again for comparison with the file where original was saved.
Definition at line 3194 of file NeuralApproximatorBase.cs.
References IG.Lib.SerializationDtoBase< Type, BaseType >.CopyFrom(), IG.Num.NeuralApproximatorBase.ExampleQuadratic(), IG.Num.INeuralApproximator.GetErrorsTrainingRms(), IG.Num.INeuralApproximator.GetErrorsVerificationRms(), IG.Num.NeuralApproximatorBase.LoadJson(), IG.Num.INeuralApproximator.NetworkStateFilePath, IG.Num.IVectorApproximator.OutputLength, IG.Num.NeuralApproximatorBase.SaveJson(), IG.Num.INeuralApproximator.SaveNetwork(), IG.Num.VectorBase.Subtract(), and IG.Num.INeuralApproximator.TrainNetwork().
ExampleQuadratic() [1/3]
static INeuralApproximator IG.Num.NeuralApproximatorBase.ExampleQuadratic () inline static
Example demonstrating usage of the neural network approximator. A quadratic function with random coefficients is sampled with enough samples to exactly specify function coefficients, a part of samples is randomly designated as verification points, then neural network is created and trained on training samples, and it is verified how close the obtained approximation matches actual function in verification points.
Returns
The trained neural network approximator that includes the training data, and can be saved to a file and used at a later time.
Definition at line 3365 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralApproximatorBase.ExampleQuadratic(), and IG.Num.NeuralApproximatorBase.ExampleSaveNetwork().
ExampleQuadratic() [2/3]
static INeuralApproximator IG.Num.NeuralApproximatorBase.ExampleQuadratic (int inputLength, int outputLength) inline static
Example demonstrating usage of the neural network approximator. A quadratic function with random coefficients is sampled with enough samples to exactly specify function coefficients, a part of samples is randomly designated as verification points, then neural network is created and trained on training samples, and it is verified how close the obtained approximation matches actual function in verification points.
Parameters
inputLength Number of input parameters of the neural network.
outputLength Number of approximated output values of the neural network.
Returns
The trained neural network approximator that includes the training data, and can be saved to a file and used at a later time.
Definition at line 3380 of file NeuralApproximatorBase.cs.
References IG.Num.NeuralApproximatorBase.ExampleQuadratic().
ExampleQuadratic() [3/3]
static INeuralApproximator IG.Num.NeuralApproximatorBase.ExampleQuadratic (int inputLength, int outputLength, int outputLevel, int maxEpochs) inline static
Example demonstrating usage of the neural network approximator. A quadratic function with random coefficients is sampled with enough samples to exactly specify function coefficients, a part of samples is randomly designated as verification points, then neural network is created and trained on training samples, and it is verified how close the obtained approximation matches actual function in verification points.
Parameters
inputLength Number of input parameters of the neural network.
outputLength Number of approximated output values of the neural network.
outputLevel Level of output written to console (0 - no output).
maxEpochs If greater than 0 then this is the maximal number of epochs used for training.
Returns
The trained neural network approximator that includes the training data, and can be saved to a file and used at a later time.
Definition at line 3397 of file NeuralApproximatorBase.cs.
References IG.Num.NeuralApproximatorBase.CalculateOutput(), IG.Lib.SortedUniqueItemList< Type >.Contains(), IG.Num.SampledDataSet.CreateExampleQuadratic(), IG.Lib.IndexList.CreateRandom(), IG.Num.NeuralApproximatorBase.EpochsInBundle, IG.Num.SampledDataSet.GetInputParameters(), IG.Num.SampledDataSet.GetOutputValues(), IG.Num.NeuralApproximatorBase.InputBoundsSafetyFactor, IG.Num.NeuralApproximatorBase.InputLength, IG.Num.NeuralApproximatorBase.InputNeuronsRange, IG.Num.NeuralApproximatorBase.LearningRate, IG.Num.VectorApproximatorBase.Lock, IG.Num.NeuralApproximatorBase.MaxEpochs, IG.Num.NeuralApproximatorBase.Momentum, IG.Num.NeuralApproximatorBase.MultipleNetworks, IG.Num.NeuralApproximatorBase.OutputBoundsSafetyFactor, IG.Num.NeuralApproximatorBase.OutputLength, IG.Num.NeuralApproximatorBase.OutputLevel, IG.Num.NeuralApproximatorBase.OutputNeuronsRange, IG.Num.IBoundingBox.Reset(), IG.Num.NeuralApproximatorBase.SetHiddenLayers(), IG.Num.NeuralApproximatorBase.SigmoidAlphaValue, IG.Num.VectorBase.Subtract(), IG.Num.NeuralApproximatorBase.TestMapping(), IG.Num.NeuralApproximatorBase.ToleranceRms, IG.Num.IVector< T >.ToString(), IG.Num.NeuralApproximatorBase.ToString(), IG.Num.NeuralApproximatorBase.TrainingData, IG.Num.NeuralApproximatorBase.TrainNetwork(), IG.Num.IBoundingBox.UpdateAll(), and IG.Num.NeuralApproximatorBase.VerificationIndices.
Member Data Documentation
_mainLock
object IG.Num.NeuralApproximatorBase._mainLock = new object() private
Definition at line 582 of file NeuralApproximatorBase.cs.
_outputLevel
int IG.Num.NeuralApproximatorBase._outputLevel = Util.OutputLevel private
Definition at line 594 of file NeuralApproximatorBase.cs.
_inputLength
int IG.Num.NeuralApproximatorBase._inputLength private
Definition at line 596 of file NeuralApproximatorBase.cs.
_outputLength
int IG.Num.NeuralApproximatorBase._outputLength private
Definition at line 597 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralApproximatorBase.SetMaxToleranceRelstiveToRange(), and IG.Num.NeuralApproximatorBase.SetRmsToleranceRelstiveToRange().
_numHiddenNeurons
int [] IG.Num.NeuralApproximatorBase._numHiddenNeurons private
Definition at line 598 of file NeuralApproximatorBase.cs.
_multipleNetworks
bool IG.Num.NeuralApproximatorBase._multipleNetworks = true private
Definition at line 599 of file NeuralApproximatorBase.cs.
_networkPrepared
bool IG.Num.NeuralApproximatorBase._networkPrepared = false private
Definition at line 601 of file NeuralApproximatorBase.cs.
_sigmoidAlphaValue
double IG.Num.NeuralApproximatorBase._sigmoidAlphaValue = NeuralTrainingParameters.DefaultSigmoidAlphaValue private
Definition at line 602 of file NeuralApproximatorBase.cs.
_learningRate
double IG.Num.NeuralApproximatorBase._learningRate = NeuralTrainingParameters.DefaultLearningRate private
Definition at line 603 of file NeuralApproximatorBase.cs.
_momentum
double IG.Num.NeuralApproximatorBase._momentum = NeuralTrainingParameters.DefaultMomentum private
Definition at line 604 of file NeuralApproximatorBase.cs.
_epochCount
int IG.Num.NeuralApproximatorBase._epochCount = 0 private
Definition at line 606 of file NeuralApproximatorBase.cs.
_convergenceRmsEnabled
bool IG.Num.NeuralApproximatorBase._convergenceRmsEnabled = false private
Definition at line 608 of file NeuralApproximatorBase.cs.
_maxEpochs
int IG.Num.NeuralApproximatorBase._maxEpochs = NeuralTrainingParameters.DefaultMaxEpochs private
Definition at line 612 of file NeuralApproximatorBase.cs.
_epochsInBundle
int IG.Num.NeuralApproximatorBase._epochsInBundle = NeuralTrainingParameters.DefaultEpochsInBundle private
Definition at line 614 of file NeuralApproximatorBase.cs.
_epochNumbers
List<int> IG.Num.NeuralApproximatorBase._epochNumbers = null private
Definition at line 618 of file NeuralApproximatorBase.cs.
_convergenceErrorsTrainingRmsList
List<IVector> IG.Num.NeuralApproximatorBase._convergenceErrorsTrainingRmsList = null private
Definition at line 619 of file NeuralApproximatorBase.cs.
_convergenceErrorsTrainingMaxList
List<IVector> IG.Num.NeuralApproximatorBase._convergenceErrorsTrainingMaxList = null private
Definition at line 620 of file NeuralApproximatorBase.cs.
_convergenceErrorsVerificationRmsList
List<IVector> IG.Num.NeuralApproximatorBase._convergenceErrorsVerificationRmsList = null private
Definition at line 621 of file NeuralApproximatorBase.cs.
_convergenceErrorsVerificationMaxList
List<IVector> IG.Num.NeuralApproximatorBase._convergenceErrorsVerificationMaxList = null private
Definition at line 622 of file NeuralApproximatorBase.cs.
_toleranceRms
IVector IG.Num.NeuralApproximatorBase._toleranceRms = null private
Definition at line 902 of file NeuralApproximatorBase.cs.
_toleranceMax
IVector IG.Num.NeuralApproximatorBase._toleranceMax = null private
Definition at line 932 of file NeuralApproximatorBase.cs.
_tolRmsRelative
IVector IG.Num.NeuralApproximatorBase._tolRmsRelative private
Auxiliary properties for defining tolerances in a relative way:
Definition at line 965 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralApproximatorBase.SetRmsToleranceRelstiveToRange().
_tolRmsRelativeScalar
double IG.Num.NeuralApproximatorBase._tolRmsRelativeScalar private
Definition at line 1006 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralApproximatorBase.SetRmsToleranceRelstiveToRange().
_tolMaxRelative
IVector IG.Num.NeuralApproximatorBase._tolMaxRelative private
Definition at line 1061 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralApproximatorBase.SetMaxToleranceRelstiveToRange().
_tolMaxRelativeScalar
double IG.Num.NeuralApproximatorBase._tolMaxRelativeScalar private
Definition at line 1105 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralApproximatorBase.SetMaxToleranceRelstiveToRange().
_defaultNetworkFilename
const string IG.Num.NeuralApproximatorBase._defaultNetworkFilename = "network.dat" static protected
Definition at line 1242 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralApproximatorBase.GetNetworkFilePath().
_networkFilePath
string IG.Num.NeuralApproximatorBase._networkFilePath = null private
Definition at line 1284 of file NeuralApproximatorBase.cs.
_networkRelativePath
string IG.Num.NeuralApproximatorBase._networkRelativePath = null private
Definition at line 1286 of file NeuralApproximatorBase.cs.
_trainingData
SampledDataSet IG.Num.NeuralApproximatorBase._trainingData private
Definition at line 1416 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralApproximatorBase.GetTrainingData(), IG.Num.NeuralApproximatorBase.GetVerificationData(), and IG.Num.NeuralApproximatorBase.SetTrainingAndVerificationData().
_verificationIndices
IndexList IG.Num.NeuralApproximatorBase._verificationIndices private
Definition at line 1418 of file NeuralApproximatorBase.cs.
_inputDataBounds
IBoundingBox IG.Num.NeuralApproximatorBase._inputDataBounds private
Definition at line 1420 of file NeuralApproximatorBase.cs.
_outputDataBounds
IBoundingBox IG.Num.NeuralApproximatorBase._outputDataBounds private
Definition at line 1422 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralApproximatorBase.SetMaxToleranceRelstiveToRange(), and IG.Num.NeuralApproximatorBase.SetRmsToleranceRelstiveToRange().
_inputNeuronRange
IBoundingBox IG.Num.NeuralApproximatorBase._inputNeuronRange private
Definition at line 1424 of file NeuralApproximatorBase.cs.
_outputNeuronsRange
IBoundingBox IG.Num.NeuralApproximatorBase._outputNeuronsRange private
Definition at line 1426 of file NeuralApproximatorBase.cs.
_inputBoundsSafetyFactor
double IG.Num.NeuralApproximatorBase._inputBoundsSafetyFactor = 1.5 private
Definition at line 1429 of file NeuralApproximatorBase.cs.
_outputBoundsSafetyFactor
double IG.Num.NeuralApproximatorBase._outputBoundsSafetyFactor = 2.0 private
Definition at line 1430 of file NeuralApproximatorBase.cs.
_defaultNeuronMinInput
double IG.Num.NeuralApproximatorBase._defaultNeuronMinInput = -2 protected
Definition at line 1432 of file NeuralApproximatorBase.cs.
_defaultNeuronMaxInput
double IG.Num.NeuralApproximatorBase._defaultNeuronMaxInput = 2 protected
Definition at line 1433 of file NeuralApproximatorBase.cs.
_defaultNeuronMinOutput
double IG.Num.NeuralApproximatorBase._defaultNeuronMinOutput = -1.0 protected
Definition at line 1434 of file NeuralApproximatorBase.cs.
_defaultNeuronMaxOutput
double IG.Num.NeuralApproximatorBase._defaultNeuronMaxOutput = 1.0 protected
Definition at line 1435 of file NeuralApproximatorBase.cs.
_internalTrainingDataPrepared
bool IG.Num.NeuralApproximatorBase._internalTrainingDataPrepared = false private
Definition at line 1438 of file NeuralApproximatorBase.cs.
_trainingOutputsCalculated
bool IG.Num.NeuralApproximatorBase._trainingOutputsCalculated = false private
Definition at line 1440 of file NeuralApproximatorBase.cs.
_verificationOutputsCalculated
bool IG.Num.NeuralApproximatorBase._verificationOutputsCalculated = false private
Definition at line 1442 of file NeuralApproximatorBase.cs.
_networkTrained
bool IG.Num.NeuralApproximatorBase._networkTrained private
Definition at line 1444 of file NeuralApproximatorBase.cs.
_calculatedOutputs
List<IVector> IG.Num.NeuralApproximatorBase._calculatedOutputs = null protected
List of calculated outputs in points contained in (all) training data.
Definition at line 1448 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralApproximatorBase.CalculateTrainingVerificationOutputs(), and IG.Num.NeuralApproximatorBase.PrepareErrorData().
_prescribed
List<IVector> IG.Num.NeuralApproximatorBase._prescribed = null private
Definition at line 2266 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralApproximatorBase.PrepareErrorData().
_calculated
List<IVector> IG.Num.NeuralApproximatorBase._calculated = null private
Definition at line 2267 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralApproximatorBase.PrepareErrorData().
_breakTraining
bool IG.Num.NeuralApproximatorBase._breakTraining = false private
Definition at line 2468 of file NeuralApproximatorBase.cs.
_calculateVerificationErrors
bool IG.Num.NeuralApproximatorBase._calculateVerificationErrors = false protected
Definition at line 2477 of file NeuralApproximatorBase.cs.
_auxErrors
Vector IG.Num.NeuralApproximatorBase._auxErrors = null protected
Definition at line 2629 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralApproximatorBase.StopTrainingCriteriaMet().
_commonEventArgs
EventArgs IG.Num.NeuralApproximatorBase._commonEventArgs private
Definition at line 2713 of file NeuralApproximatorBase.cs.
_output
IVector IG.Num.NeuralApproximatorBase._output = null private
Definition at line 2809 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralApproximatorBase.CalculateOutput().
_outputFiltered1
IVector IG.Num.NeuralApproximatorBase._outputFiltered1 = null private
Definition at line 2811 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralApproximatorBase.CalculateOutput().
Property Documentation
TypesRegistry
DerivedTypesRgistryBasic<INeuralApproximator> IG.Num.NeuralApproximatorBase.TypesRegistry = new DerivedTypesRgistryBasic<INeuralApproximator>() static get
Registry of INeuralApproximator types, which enables to retrieve an ANN approximator type based on its name, which is important for creation of instances via reflection, which is also used when loading trained approximators from a serialized JSON file (functionality of DerivedTypesRegistryPlain<INeuralApproximator> is crucial when restoring internal state of embedded 3rd-party approximators).
Definition at line 543 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralApproximatorBase.CreateApproximator().
SerializationBinder
SerializationBinderBase IG.Num.NeuralApproximatorBase.SerializationBinder get set protected
Serialization binder used for binary deserialization of objects of the current class.
Thid serialization binder is useed wheen approximator objects of a given class may be binary-deserialized from files where objects were serialized by usiing a different assembly version and/or fully qualified type name than the current ones against which deserialiation is performed.
If null then no custom binder is used to assist binary deserialization of objects off the current class.
In types where this serialization binder is needed, it will usually be set in consructors in a hard-coded way, which will take into accont full assembly names which were eves used in serialization of objects of a given type.
Definition at line 576 of file NeuralApproximatorBase.cs.
OutputLevel
int IG.Num.NeuralApproximatorBase.OutputLevel get set
Level of output printed to console when performing actions.
Definition at line 626 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralApproximatorBase.ExampleQuadratic(), IG.Num.NeuralApproximatorBase.OnBundleCompleted(), and IG.Num.NeuralApproximatorBase.OnTrainingCompleted().
MultipleNetworks
virtual bool IG.Num.NeuralApproximatorBase.MultipleNetworks get set
Flag indicating whether multiple neural networks are used to approximate multiple outputs (one network for each output)
Definition at line 631 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralApproximatorBase.ExampleQuadratic(), and IG.Num.NeuralApproximatorBase.GetNetworkFilePath().
InputLength
override int IG.Num.NeuralApproximatorBase.InputLength get set
Gets or sets the number of input neurons.
Definition at line 646 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralTrainingParameters.CopyFrom(), IG.Num.NeuralTrainingParameters.CopyTo(), IG.Num.NeuralApproximatorBase.ExampleQuadratic(), IG.Num.NeuralApproximatorBase.SetNeuronsInputRange(), and IG.Num.NeuralApproximatorBase.TestMapping().
OutputLength
override int IG.Num.NeuralApproximatorBase.OutputLength get set
Gets or sets the number of output neurons.
Definition at line 664 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralApproximatorBase.CalculateOutput(), IG.Num.NeuralTrainingParameters.CopyFrom(), IG.Num.NeuralTrainingParameters.CopyTo(), IG.Num.NeuralApproximatorBase.ExampleQuadratic(), IG.Num.NeuralApproximatorBase.PrepareErrorData(), IG.Num.NeuralApproximatorBase.SetNeuronsOutputRange(), IG.Num.NeuralApproximatorBase.StopTrainingCriteriaMet(), IG.Num.NeuralApproximatorBase.TestMapping(), and IG.Num.NeuralApproximatorBase.TrainNetwork().
NumHiddenNeurons
virtual int [] IG.Num.NeuralApproximatorBase.NumHiddenNeurons get set
Gets or sets the numbers of neurons in each hidden layer. When setting, contents of array are copied, not only a reference. Numbers are set by an array of integers in which each element contains the number of neurons in the corresponding hidden layer (indexed from 0). Hidden layers are those not containing input or output neurons.
Getter is protected cecause we don't want users of the class to set number of neurons in individual layers.
Definition at line 708 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralTrainingParameters.CopyFrom(), IG.Num.NeuralApproximatorBase.GetNumNeuronsInHiddenLayer(), IG.Num.NeuralApproximatorBase.SetHiddenLayers(), and IG.Num.NeuralApproximatorBase.SetNumNeuronsInHiddenLayer().
NumHiddenLayers
virtual int IG.Num.NeuralApproximatorBase.NumHiddenLayers get set
Gets or sets the number of hidden layers of the neural network (these are layers that don't contain input or output neurons).
Definition at line 753 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralTrainingParameters.CopyFrom(), and IG.Num.NeuralTrainingParameters.CopyTo().
NetworkPrepared
bool IG.Num.NeuralApproximatorBase.NetworkPrepared get protected set
Gets a flag telling whether the network is prepared for operation (training and calculation of output).
Definition at line 844 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralApproximatorBase.InvalidateNetworkDependencies().
SigmoidAlphaValue
double IG.Num.NeuralApproximatorBase.SigmoidAlphaValue get set
Alpha value specifying the shape of the activation function.
Definition at line 851 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralTrainingParameters.CopyFrom(), IG.Num.NeuralTrainingParameters.CopyTo(), IG.Num.NeuralApproximatorBase.ExampleQuadratic(), and IG.Num.NeuralApproximatorBase.ToString().
LearningRate
double IG.Num.NeuralApproximatorBase.LearningRate get set
Gets or sets learning rate.
Definition at line 863 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralTrainingParameters.CopyFrom(), IG.Num.NeuralTrainingParameters.CopyTo(), IG.Num.NeuralApproximatorBase.ExampleQuadratic(), and IG.Num.NeuralApproximatorBase.ToString().
Momentum
double IG.Num.NeuralApproximatorBase.Momentum get set
Gets or sets momentum.
Definition at line 870 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralTrainingParameters.CopyFrom(), IG.Num.NeuralTrainingParameters.CopyTo(), IG.Num.NeuralApproximatorBase.ExampleQuadratic(), and IG.Num.NeuralApproximatorBase.ToString().
EpochCount
int IG.Num.NeuralApproximatorBase.EpochCount get protected set
Number of learning epochs performed up to the current moment.
Definition at line 877 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralApproximatorBase.InvalidateTrainingDataDependencies(), IG.Num.NeuralApproximatorBase.OnBundleCompleted(), IG.Num.NeuralApproximatorBase.OnTrainingCompleted(), IG.Num.NeuralApproximatorBase.StopTrainingCriteriaMet(), and IG.Num.NeuralApproximatorBase.TrainNetwork().
MaxEpochs
int IG.Num.NeuralApproximatorBase.MaxEpochs get set
Maximal number of epochs in training.
Definition at line 884 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralTrainingParameters.CopyFrom(), IG.Num.NeuralTrainingParameters.CopyTo(), IG.Num.NeuralApproximatorBase.ExampleQuadratic(), IG.Num.NeuralApproximatorBase.OnBundleCompleted(), IG.Num.NeuralApproximatorBase.OnTrainingCompleted(), IG.Num.NeuralApproximatorBase.StopTrainingCriteriaMet(), and IG.Num.NeuralApproximatorBase.ToString().
EpochsInBundle
int IG.Num.NeuralApproximatorBase.EpochsInBundle get set
Number of epochs in a single training bundle. This number of epochs is performed at once when training, without checking convergence criteria between. Larger value means slightly more efficient training (because of less checks) but rougher criteria checks.
Definition at line 894 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralTrainingParameters.CopyFrom(), IG.Num.NeuralTrainingParameters.CopyTo(), IG.Num.NeuralApproximatorBase.ExampleQuadratic(), IG.Num.NeuralApproximatorBase.TrainNetwork(), and IG.Num.NeuralApproximatorBase.TrainNetworkMultiple().
ToleranceRms
IVector IG.Num.NeuralApproximatorBase.ToleranceRms get set
Tolerances on RMS errors of outputs over training points. Training will continue until error becomes below tolerance or until maximal number of epochs is reached. If less or equal than 0 then this tolerance is not taken into account.
Definition at line 908 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralTrainingParameters.CopyFrom(), IG.Num.NeuralTrainingParameters.CopyTo(), IG.Num.NeuralApproximatorBase.ExampleQuadratic(), IG.Num.NeuralApproximatorBase.SetRmsToleranceRelstiveToRange(), IG.Num.NeuralApproximatorBase.StopTrainingCriteriaMet(), and IG.Num.NeuralApproximatorBase.ToString().
ToleranceMax
IVector IG.Num.NeuralApproximatorBase.ToleranceMax get set
Tolerances on maximal errors of outputs over training points. Training will continue until error becomes below tolerance or until maximal number of epochs is reached. If less or equal than 0 then this tolerance is not taken into account.
Definition at line 938 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralTrainingParameters.CopyFrom(), IG.Num.NeuralTrainingParameters.CopyTo(), IG.Num.NeuralApproximatorBase.SetMaxToleranceRelstiveToRange(), IG.Num.NeuralApproximatorBase.StopTrainingCriteriaMet(), and IG.Num.NeuralApproximatorBase.ToString().
ToleranceRmsRelativeToRange
IVector IG.Num.NeuralApproximatorBase.ToleranceRmsRelativeToRange get set
Relative tolerances on RMS errors of outputs over training points, relative to the correspoinding ranges of output data.
When this vector is set to a non-null value, elements of RMS tolerances vector (property ToleranceRms) are set to the specified fractions of the ranges of the corresponding output values in training parameters (defined by the property OutputDataBounds) if these are defined (otherwise this may happen when the property gets defined).
Whenever this property is defined, re-setting the property OutputDataBounds will cause recalculation of ToleranceRms according to elements of this property and the ranges of corresponding output values.
Setting this property undefines the ToleranceRmsRelativeToRangeScalar property, even if it is set to null.
If the scalar relative tolerance is set (property ToleranceRmsRelativeToRangeScalar) and this property is not set yet, the getter of this property will evaluate to a vector whose elements are equal to the scalar relative tolerance.
Definition at line 983 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralTrainingParameters.CopyFrom(), IG.Num.NeuralTrainingParameters.CopyTo(), and IG.Num.NeuralApproximatorBase.SetRmsToleranceRelstiveToRange().
ToleranceRmsRelativeToRangeScalar
double IG.Num.NeuralApproximatorBase.ToleranceRmsRelativeToRangeScalar get set
Scalar through which all components of the Relative tolerances on RMS errors of outputs can be set to the same value.
Getter returns a value greater than 0 only if the property has been previously set.
Setting a vector of relative tolerances (property ToleranceRmsRelativeToRange) sets this property to 0, even it it is set to null.
Setting the property to a value greater than 0 automatically sets the vector of relative tolerances (property ToleranceRmsRelativeToRange) in such a way that all elements are equal to this property.
Definition at line 1016 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralTrainingParameters.CopyFrom(), IG.Num.NeuralTrainingParameters.CopyTo(), and IG.Num.NeuralApproximatorBase.SetRmsToleranceRelstiveToRange().
ToleranceMaxRelativeToRange
IVector IG.Num.NeuralApproximatorBase.ToleranceMaxRelativeToRange get set
Relative tolerances on max. abs. errors of outputs over training points, relative to the correspoinding ranges of output data.
When this vector is set to a non-null value, elements of max. abs. tolerances vector (property ToleranceMax) are set to the specified fractions of the ranges of the corresponding output values in training parameters (defined by the property OutputDataBounds) if these are defined (otherwise this may happen when the property gets defined).
Whenever this property is defined, re-setting the property OutputDataBounds will cause recalculation of ToleranceMax according to elements of this property and the ranges of corresponding output values.
Setting this property undefines the ToleranceMaxRelativeToRangeScalar property, even if it is set to null.
If the scalar relative tolerance is set (property ToleranceMaxRelativeToRangeScalar) and this property is not set yet, the getter of this property will evaluate to a vector whose elements are equal to the scalar relative tolerance.
Definition at line 1079 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralTrainingParameters.CopyFrom(), IG.Num.NeuralTrainingParameters.CopyTo(), and IG.Num.NeuralApproximatorBase.SetMaxToleranceRelstiveToRange().
ToleranceMaxRelativeToRangeScalar
double IG.Num.NeuralApproximatorBase.ToleranceMaxRelativeToRangeScalar get set
Scalar through which all components of the Relative tolerances on max. abs. errors of outputs can be set to the same value.
Getter returns a value greater than 0 only if the property has been previously set.
Setting a vector of relative tolerances (property ToleranceMaxRelativeToRange) sets this property to 0, even it it is set to null.
Setting the property to a value greater than 0 automatically sets the vector of relative tolerances (property ToleranceMaxRelativeToRange) in such a way that all elements are equal to this property.
Definition at line 1115 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralTrainingParameters.CopyFrom(), IG.Num.NeuralTrainingParameters.CopyTo(), and IG.Num.NeuralApproximatorBase.SetMaxToleranceRelstiveToRange().
EpochNumbers
List<int> IG.Num.NeuralApproximatorBase.EpochNumbers get set
List of epoch numbers at which convergence data was sampled. Saved after every set of epochs.
$A Tako78 Sep12;
Definition at line 1176 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralTrainingParameters.CopyResultsFrom(), and IG.Num.NeuralApproximatorBase.TrainNetwork().
ConvergenceErrorsTrainingRmsList
List<IVector> IG.Num.NeuralApproximatorBase.ConvergenceErrorsTrainingRmsList get set
Convergence List of RMS errors calculated on training data. Saved after every set of epochs.
Definition at line 1184 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralTrainingParameters.CopyResultsFrom(), and IG.Num.NeuralApproximatorBase.TrainNetwork().
ConvergenceErrorsTrainingMaxList
List<IVector> IG.Num.NeuralApproximatorBase.ConvergenceErrorsTrainingMaxList get set
Convergence List of Maximum errors calculated on training data. Saved after every set of epochs.
Definition at line 1192 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralTrainingParameters.CopyResultsFrom(), and IG.Num.NeuralApproximatorBase.TrainNetwork().
ConvergenceErrorsVerificationRmsList
List<IVector> IG.Num.NeuralApproximatorBase.ConvergenceErrorsVerificationRmsList get set
Convergence List of Rms errors calculated on verification data. Saved after every set of epochs.
Definition at line 1200 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralTrainingParameters.CopyResultsFrom(), and IG.Num.NeuralApproximatorBase.TrainNetwork().
ConvergenceErrorsVerificationMaxList
List<IVector> IG.Num.NeuralApproximatorBase.ConvergenceErrorsVerificationMaxList get set
Convergence List of Maximum errors calculated on verification data. Saved after every set of epochs.
Definition at line 1208 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralTrainingParameters.CopyResultsFrom(), and IG.Num.NeuralApproximatorBase.TrainNetwork().
SaveConvergenceRms
bool IG.Num.NeuralApproximatorBase.SaveConvergenceRms get set
Flag to enable RMS error convergence colection.
Definition at line 1215 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralTrainingParameters.CopyResultsFrom(), IG.Num.NeuralTrainingParameters.CopyTo(), and IG.Num.NeuralApproximatorBase.TrainNetwork().
NeuralApproximatorType
string IG.Num.NeuralApproximatorBase.NeuralApproximatorType get
Gets string representation of type of the current object. This is used e.g. in deserialization in order to prevent that wrong type of internal representation would be read in.
Definition at line 1291 of file NeuralApproximatorBase.cs.
NetworkStateFilePath
string IG.Num.NeuralApproximatorBase.NetworkStateFilePath get set
Path where the curren network state has been saved, or null if the current state has not been saved yet. The SaveFile methods takes care that the file path is stored when network state is saved. InvalidateTrainingDependencies() takes care that this file path is set to null if network state has changed after last save.
Definition at line 1353 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralApproximatorBase.InvalidateTrainingDependencies(), IG.Num.NeuralApproximatorBase.LoadNetwork(), and IG.Num.NeuralApproximatorBase.SaveNetwork().
NetworkStateRelativePath
string IG.Num.NeuralApproximatorBase.NetworkStateRelativePath get set
Relative path where the curren network state has been saved. Auxiliary property used in deserialization. When the whole Neural network approximator is saved to a file, tis path is updated in such a way that it points to the fiele where the network state has been saved, but relative to the path where the whole approximator is saved. This enables restore of the saved network state at a later time, even if the containing directory has moved within the file system or has even been copied to another system.
Definition at line 1370 of file NeuralApproximatorBase.cs.
TrainingData
SampledDataSet IG.Num.NeuralApproximatorBase.TrainingData get set
Gets or sets the training data.
Definition at line 1452 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralApproximatorBase.CalculateTrainingVerificationOutputs(), IG.Num.NeuralTrainingParameters.CopyFrom(), IG.Num.NeuralApproximatorBase.ExampleQuadratic(), IG.Num.NeuralApproximatorBase.LoadTrainingDataJson(), IG.Num.NeuralApproximatorBase.LoadTrainingDataJson_To_Delete(), IG.Num.NeuralApproximatorBase.PrepareErrorData(), IG.Num.NeuralApproximatorBase.RecalculateDataBounds(), IG.Num.NeuralApproximatorBase.RecalculateInputDataBounds(), IG.Num.NeuralApproximatorBase.RecalculateOutputDataBounds(), IG.Num.NeuralApproximatorBase.SaveTrainingDataJson(), IG.Num.NeuralApproximatorBase.SaveTrainingDataJson_To_delete(), and IG.Num.NeuralApproximatorBase.TestMapping().
VerificationIndices
virtual IndexList IG.Num.NeuralApproximatorBase.VerificationIndices get set
Gets or sets indices of training data elements that are used for verification of how precise appeoximation is. These elements are excluded from training of neural network.
Object of type IndexList that contains indices of elements used for verification, always contains a sorted list of unique indices.
Definition at line 1573 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralApproximatorBase.CalculateTrainingVerificationOutputs(), IG.Num.NeuralApproximatorBase.ExampleQuadratic(), IG.Num.NeuralApproximatorBase.GetTrainingData(), IG.Num.NeuralApproximatorBase.GetVerificationData(), IG.Num.NeuralApproximatorBase.PrepareErrorData(), IG.Num.NeuralApproximatorBase.SetTrainingAndVerificationData(), and IG.Num.NeuralApproximatorBase.TestMapping().
InputDataBounds
virtual IBoundingBox IG.Num.NeuralApproximatorBase.InputDataBounds get set
Bounds on input data, used for scaling from actual input to input used by neural network. Scaling is performed because of the bound codomain and image of activation functions.
Definition at line 1603 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralApproximatorBase.MapFromNeuralInput(), IG.Num.NeuralApproximatorBase.MapInput(), IG.Num.NeuralApproximatorBase.RecalculateInputDataBounds(), and IG.Num.NeuralApproximatorBase.ToString().
OutputDataBounds
virtual IBoundingBox IG.Num.NeuralApproximatorBase.OutputDataBounds get set
Bounds on output data, used for scaling from actual output to output produced by neural network. Scaling is performed because of the bound codomain and image of activation functions.
Definition at line 1618 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralApproximatorBase.MapFromNeuralOutput(), IG.Num.NeuralApproximatorBase.MapOutput(), IG.Num.NeuralApproximatorBase.RecalculateOutputDataBounds(), and IG.Num.NeuralApproximatorBase.ToString().
InputBoundsSafetyFactor
virtual double IG.Num.NeuralApproximatorBase.InputBoundsSafetyFactor get set
Safety factor by which interval lenghts of input data bounds are enlarged after bounds are automatically determined from the range of input data in the training set. Setter re-calculated the input data bounds and therefore invalidates training data dependencies.
Definition at line 1634 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralTrainingParameters.CopyFrom(), IG.Num.NeuralTrainingParameters.CopyTo(), IG.Num.NeuralApproximatorBase.ExampleQuadratic(), IG.Num.NeuralApproximatorBase.RecalculateInputDataBounds(), and IG.Num.NeuralApproximatorBase.ToString().
OutputBoundsSafetyFactor
virtual double IG.Num.NeuralApproximatorBase.OutputBoundsSafetyFactor get set
Safety factor by which interval lenghts of output data bounds are enlarged after bounds are automatically determined from the range of output data in the training set. Setter re-calculated the output data bounds and therefore invalidates training data dependencies.
Definition at line 1653 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralTrainingParameters.CopyFrom(), IG.Num.NeuralTrainingParameters.CopyTo(), IG.Num.NeuralApproximatorBase.ExampleQuadratic(), IG.Num.NeuralApproximatorBase.RecalculateOutputDataBounds(), and IG.Num.NeuralApproximatorBase.ToString().
InputNeuronsRange
virtual IBoundingBox IG.Num.NeuralApproximatorBase.InputNeuronsRange get protected set
Gets the range in which data should be for input neurons, used for scaling from actual input to input used by neural network. This depends on the activation function.
Setter is not public.
Definition at line 1673 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralApproximatorBase.ExampleQuadratic(), IG.Num.NeuralApproximatorBase.MapFromNeuralInput(), IG.Num.NeuralApproximatorBase.MapInput(), IG.Num.NeuralApproximatorBase.SetNeuronsInputRange(), IG.Num.NeuralApproximatorBase.TestMapping(), and IG.Num.NeuralApproximatorBase.ToString().
OutputNeuronsRange
virtual IBoundingBox IG.Num.NeuralApproximatorBase.OutputNeuronsRange get protected set
Gets the range of the data output from output neurons, used for scaling from actual output to output produced by neural network. This will normally depend on the activation function.
Setter is not public.
Definition at line 1690 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralApproximatorBase.ExampleQuadratic(), IG.Num.NeuralApproximatorBase.MapFromNeuralOutput(), IG.Num.NeuralApproximatorBase.MapOutput(), IG.Num.NeuralApproximatorBase.SetNeuronsOutputRange(), IG.Num.NeuralApproximatorBase.TestMapping(), and IG.Num.NeuralApproximatorBase.ToString().
NumAllTrainingPoints
int IG.Num.NeuralApproximatorBase.NumAllTrainingPoints get
Gets number of all training points, including verification points.
Definition at line 1976 of file NeuralApproximatorBase.cs.
NumTrainingPoints
virtual int IG.Num.NeuralApproximatorBase.NumTrainingPoints get
Gets number of training points (this excludes verification points).
Definition at line 1991 of file NeuralApproximatorBase.cs.
NumVerificationPoints
virtual int IG.Num.NeuralApproximatorBase.NumVerificationPoints get
Gets number of verification points.
Definition at line 2008 of file NeuralApproximatorBase.cs.
TrainingOutputsCalculated
bool IG.Num.NeuralApproximatorBase.TrainingOutputsCalculated get set protected
Whether outputs have been calculated, after last training, in the training points (excluding verification points).
Definition at line 2023 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralApproximatorBase.CalculateTrainingVerificationOutputs(), IG.Num.NeuralApproximatorBase.InvalidateTrainingDependencies(), and IG.Num.NeuralApproximatorBase.PrepareErrorData().
VerificationOutputsCalculated
bool IG.Num.NeuralApproximatorBase.VerificationOutputsCalculated get set protected
Whether outputs have been calculated, after last training, in the training points (excluding verification points).
Definition at line 2027 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralApproximatorBase.CalculateTrainingVerificationOutputs(), IG.Num.NeuralApproximatorBase.InvalidateTrainingDependencies(), and IG.Num.NeuralApproximatorBase.PrepareErrorData().
InternalTrainingDataPrepared
bool IG.Num.NeuralApproximatorBase.InternalTrainingDataPrepared get set protected
Gets or sets a flag indicating whether internal training data is prepared. This flag is used internally for signalization between methods that deal with training data.
Definition at line 2410 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralApproximatorBase.InvalidateTrainingDataDependencies().
NetworkTrained
bool IG.Num.NeuralApproximatorBase.NetworkTrained get protected set
Whether network has been trained since the training data was set.
Definition at line 2417 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralTrainingParameters.CopyResultsFrom(), IG.Num.NeuralApproximatorBase.InvalidateTrainingDataDependencies(), and IG.Num.NeuralApproximatorBase.LoadNetwork().
BreakTraining
bool IG.Num.NeuralApproximatorBase.BreakTraining get set
Flags that signalizes (if true) that training should be broken on external request.
Definition at line 2472 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralApproximatorBase.TrainNetwork(), and IG.Num.NeuralApproximatorBase.TrainNetworkMultiple().
CalculateVerificationErrors
bool IG.Num.NeuralApproximatorBase.CalculateVerificationErrors get set
Definition at line 2480 of file NeuralApproximatorBase.cs.
CommonEventArgs
EventArgs IG.Num.NeuralApproximatorBase.CommonEventArgs get protected
Provides a commond object of type EventArgs for all events to avoid allocation each time an event is fired.
Definition at line 2718 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralApproximatorBase.OnBundleCompleted(), and IG.Num.NeuralApproximatorBase.OnTrainingCompleted().
Event Documentation
BundleCompleted
EventHandler IG.Num.NeuralApproximatorBase.BundleCompleted
Event that is fired after completion of each bundle of training epochs (after auxiliary data is updated). Enables e.g. following training progress to subscribers, or additional interaction with training process such as stopping when enough converged, saving state, or increasing maximal number of epochs when convergence is insufficient.
Definition at line 2736 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralApproximatorBase.OnBundleCompleted().
TrainingCompleted
EventHandler IG.Num.NeuralApproximatorBase.TrainingCompleted
Event that is fired after completion of training procedure (after auxiliary data is updated).
Definition at line 2764 of file NeuralApproximatorBase.cs.
Referenced by IG.Num.NeuralApproximatorBase.OnTrainingCompleted().
The documentation for this class was generated from the following file:
iglib/igbase/numeric/approximation/neural/NeuralApproximatorBase.cs