Doc: IGLib with source files: IG.Neural.NeuraApproximationFileManager Class Reference
IG.Neural.NeuraApproximationFileManager Class Reference
File manager for neural network approximation file client and server.
Public Member Functions
NeuraApproximationFileManager (string directoryPath)
Nonstruct a new file manager for neural approximation file client/server that operates in the specified directory.
string GetPath (string fileOrDirectoryName)
Returns full path of the file or directory with the specified relative path within the data directory of the current file server/client.
void SetNeuralBusy ()
Sets the falg that indicates that the approximation server is busy.
void ClearNeuralBusy ()
Clears the falg that indicates that the approximation server is busy.
bool IsNeuralBusy ()
Returns value of the falg that indicates whether the approximation server is busy.
void SetNeuralInputReady ()
Sets the falg that indicates that the approximation input data is ready.
void ClearNeuralInputReady ()
Clears the falg that indicates that the approximation input data is ready.
bool IsNeuralInputReady ()
Returns value of the falg that indicates whether the approximation input data is ready.
void SetNeuralOutputReady ()
Sets the falg that indicates that the approximation output data is ready.
void ClearNeuralOutputReady ()
Clears the falg that indicates that the approximation output data is ready.
bool IsNeuralOutputReady ()
Returns value of the falg that indicates whether the approximation output data is ready.
void ClearMessages ()
Clears all messages for neural approximation client and server.
virtual void ReadNeuralInput (ref IVector inputParameters)
Reads neural approximator input parameters form the file at standard location.
virtual void WriteNeuralInput (IVector inputParameters)
Writes neural approximator input parameters to standard location.
virtual void ReadNeuralOutput (ref IVector outputValues)
Reads neural approximator output values from the file at standard location.
virtual void WriteNeuralOutput (IVector outputValues)
Writes neural approximator outut values to the file at standard location.
virtual void LoadNeuralNetwork (ref INeuralApproximator trainedNetwork)
Loads the trained neural network approximator from the file at standard location.
virtual void ClientWriteNeuralInput (IVector inputParameters)
Client writes input parameters for calculation of neural network based approximated values. Messages are set nad clears appropriately.
virtual void ClientReadNeuralOutput (ref IVector outputValues)
Client reads the results of neural network-based approximation (output values). Messages are set and clears appropriately.
virtual void ClientSendRequestCalculateApproximation ()
Performs request to the server for calculation of neural network based approximated values.
virtual void ClientCalculateApproximation (IVector inputParameters, ref IVector outputValues)
Calculates approximation by using the neural network approximation server.
virtual void ClientTestCalculateApproximation (string inputFilePath, string outputFilePath)
Performs client-side test calculation of neural network based approximation where input parameters are read from a specified JSON file, and calculated output values are written to the specified file.
virtual void ServerCalculateApproximation ()
Performs neural network-based approximation at prescribed input parameters and saves results. Messages are set and cleared appropriately. This method read input parameters from standard location, loads trained neural network, calculates approximated outpur values and stores them to the standard location.
Protected Attributes
string _dataDirectory = null
Properties
object Lock [get]
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
object InternalLock [get]
Used internally for locking access to internal fields.
string DataDirectory [get, protected set]
Directory for data and messages exchange through files.
string NeuralNetworkPath [get, protected set]
File path of the file where complete (usually trained) neural network is stored. Setter takes only pure file name, without path information. If set to null then file path is set to null and will be recalculated when getter is called.
string NeuralDataDefinitionPath [get, protected set]
File path of the input and output data definition file. Setter takes only pure file name, without path information. If set to null then file path is set to null and will be recalculated when getter is called.
string SimulationDataDefinitionPath [get, protected set]
File path of the input and output data definition file for simulator. Setter takes only pure file name, without path information. If set to null then file path is set to null and will be recalculated when getter is called.
string NeuralVerificationDataPath [get, protected set]
File path of the verification data file. Setter takes only pure file name, without path information. If set to null then file path is set to null and will be recalculated when getter is called.
string NeuralTrainingDataPath [get, protected set]
File path of the training data file. Setter takes only pure file name, without path information. If set to null then file path is set to null and will be recalculated when getter is called.
string NeuralInputPath [get, protected set]
File path of the file with input parameters. Setter takes only pure file name, without path information. If set to null then file path is set to null and will be recalculated when getter is called.
string NeuralInputXmlPath [get, protected set]
File path of the input parameters file in XML format. Setter takes only pure file name, without path information. If set to null then file path is set to null and will be recalculated when getter is called.
string NeuralOutputPath [get, protected set]
File path of the file for storing approximated output values. Setter takes only pure file name, without path information. If set to null then file path is set to null and will be recalculated when getter is called.
string NeuralOutputeXmlPath [get, protected set]
File path of the file for storing approximated output values in XML format. Setter takes only pure file name, without path information. If set to null then file path is set to null and will be recalculated when getter is called.
string MsgNeuralBusyPath [get, protected set]
File path of the message file indicating that approximator is busy by performing a job. Setter takes only pure file name, without path information. If set to null then file path is set to null and will be recalculated when getter is called.
string MsgNeuralInputReadyPath [get, protected set]
File path of the message file indicating taht input data is ready to be processed. Setter takes only pure file name, without path information. If set to null then file path is set to null and will be recalculated when getter is called.
string MsgNeuralOutputReadyPath [get, protected set]
File path of the message file indicating that the approximated output is ready to be read. Setter takes only pure file name, without path information. If set to null then file path is set to null and will be recalculated when getter is called.
Properties inherited from IG.Lib.ILockable
object Lock [get]
Private Member Functions
NeuraApproximationFileManager ()
Private Attributes
object _mainLock = new object()
object _internalLock = new object()
string _neuralNetworkFilename = NeuralFileConst.NeuralNetworkFilename
string _neuralNetworkPath = null
string _neuralDataDefinitionFilename = NeuralFileConst.NeuralDataDefinitionFilename
string _neuralDataDefinitionPath = null
string _simulationDataDefinitionFilename = NeuralFileConst.SimulationDataDefinitionFilename
string _simulationDataDefinitionPath = null
string _neuralTrainingDataFilename = NeuralFileConst.NeuralTrainingDataFilename
string _neuralTrainingDataPath = null
string _neuralVerificationDataFilename = NeuralFileConst.NeuralVerificationDataFilename
string _neuralVerificationDataPath = null
string _neuralInputFilename = NeuralFileConst.NeuralInputFilename
string _neuralInputPath = null
string _neuralInputXmlFilename = NeuralFileConst.NeuralInputXmlFilename
string _neuralInputXmlPath = null
string _neuralOutputFilename = NeuralFileConst.NeuralOutputFilename
string _neuralOutputPath = null
string _neuralOutputXmlFilename = NeuralFileConst.NeuralOutputeXmlFilename
string _neuralOutputXmlPath = null
string _msgNeuralBusyFilename = NeuralFileConst.MsgNeuralBusyFilename
string _msgNeuralBusyPath = null
string _msgNeuralInputReadyFilename = NeuralFileConst.MsgNeuralInputReadyFilename
string _msgNeuralInputReadyPath = null
string _msgNeuralOutputReadyFilename = NeuralFileConst.MsgNeuralOutputReadyFilename
string _msgNeuralOutputReadyPath = null
Detailed Description
File manager for neural network approximation file client and server.
This class is modelled after the DragonFly optimization server.
$A Igor Apr11;
Definition at line 21 of file NeuralFileManager.cs.
Constructor & Destructor Documentation
NeuraApproximationFileManager() [1/2]
IG.Neural.NeuraApproximationFileManager.NeuraApproximationFileManager () inline private
Definition at line 27 of file NeuralFileManager.cs.
NeuraApproximationFileManager() [2/2]
IG.Neural.NeuraApproximationFileManager.NeuraApproximationFileManager (string directoryPath) inline
Nonstruct a new file manager for neural approximation file client/server that operates in the specified directory.
Parameters
directoryPath Operation directory for data and message exchange through files.
Definition at line 32 of file NeuralFileManager.cs.
References IG.Neural.NeuraApproximationFileManager.DataDirectory.
Member Function Documentation
GetPath()
string IG.Neural.NeuraApproximationFileManager.GetPath (string fileOrDirectoryName) inline
Returns full path of the file or directory with the specified relative path within the data directory of the current file server/client.
Parameters
fileOrDirectoryName Relative path (with respect to data and messages exchange directory)
Definition at line 107 of file NeuralFileManager.cs.
References IG.Neural.NeuraApproximationFileManager.DataDirectory, and IG.Neural.NeuraApproximationFileManager.Lock.
SetNeuralBusy()
void IG.Neural.NeuraApproximationFileManager.SetNeuralBusy () inline
Sets the falg that indicates that the approximation server is busy.
Definition at line 512 of file NeuralFileManager.cs.
References IG.Neural.NeuraApproximationFileManager.Lock, and IG.Neural.NeuraApproximationFileManager.MsgNeuralBusyPath.
Referenced by IG.Neural.NeuraApproximationFileManager.ClientWriteNeuralInput(), and IG.Neural.NeuraApproximationFileManager.ServerCalculateApproximation().
ClearNeuralBusy()
void IG.Neural.NeuraApproximationFileManager.ClearNeuralBusy () inline
Clears the falg that indicates that the approximation server is busy.
Definition at line 528 of file NeuralFileManager.cs.
References IG.Neural.NeuraApproximationFileManager.Lock, and IG.Neural.NeuraApproximationFileManager.MsgNeuralBusyPath.
Referenced by IG.Neural.NeuraApproximationFileManager.ClearMessages().
IsNeuralBusy()
bool IG.Neural.NeuraApproximationFileManager.IsNeuralBusy () inline
Returns value of the falg that indicates whether the approximation server is busy.
Definition at line 539 of file NeuralFileManager.cs.
References IG.Neural.NeuraApproximationFileManager.Lock, and IG.Neural.NeuraApproximationFileManager.MsgNeuralBusyPath.
Referenced by IG.Neural.NeuraApproximationFileManager.ServerCalculateApproximation().
SetNeuralInputReady()
void IG.Neural.NeuraApproximationFileManager.SetNeuralInputReady () inline
Sets the falg that indicates that the approximation input data is ready.
Definition at line 553 of file NeuralFileManager.cs.
References IG.Neural.NeuraApproximationFileManager.Lock, and IG.Neural.NeuraApproximationFileManager.MsgNeuralInputReadyPath.
Referenced by IG.Neural.NeuraApproximationFileManager.ClientWriteNeuralInput().
ClearNeuralInputReady()
void IG.Neural.NeuraApproximationFileManager.ClearNeuralInputReady () inline
Clears the falg that indicates that the approximation input data is ready.
Definition at line 567 of file NeuralFileManager.cs.
References IG.Neural.NeuraApproximationFileManager.Lock, and IG.Neural.NeuraApproximationFileManager.MsgNeuralInputReadyPath.
Referenced by IG.Neural.NeuraApproximationFileManager.ClearMessages(), IG.Neural.NeuraApproximationFileManager.ClientWriteNeuralInput(), and IG.Neural.NeuraApproximationFileManager.ServerCalculateApproximation().
IsNeuralInputReady()
bool IG.Neural.NeuraApproximationFileManager.IsNeuralInputReady () inline
Returns value of the falg that indicates whether the approximation input data is ready.
Definition at line 578 of file NeuralFileManager.cs.
References IG.Neural.NeuraApproximationFileManager.Lock, and IG.Neural.NeuraApproximationFileManager.MsgNeuralInputReadyPath.
Referenced by IG.Neural.NeuraApproximationFileManager.ServerCalculateApproximation().
SetNeuralOutputReady()
void IG.Neural.NeuraApproximationFileManager.SetNeuralOutputReady () inline
Sets the falg that indicates that the approximation output data is ready.
Definition at line 592 of file NeuralFileManager.cs.
References IG.Neural.NeuraApproximationFileManager.Lock, and IG.Neural.NeuraApproximationFileManager.MsgNeuralOutputReadyPath.
Referenced by IG.Neural.NeuraApproximationFileManager.ServerCalculateApproximation().
ClearNeuralOutputReady()
void IG.Neural.NeuraApproximationFileManager.ClearNeuralOutputReady () inline
Clears the falg that indicates that the approximation output data is ready.
Definition at line 606 of file NeuralFileManager.cs.
References IG.Neural.NeuraApproximationFileManager.Lock, and IG.Neural.NeuraApproximationFileManager.MsgNeuralOutputReadyPath.
Referenced by IG.Neural.NeuraApproximationFileManager.ClearMessages(), IG.Neural.NeuraApproximationFileManager.ClientReadNeuralOutput(), and IG.Neural.NeuraApproximationFileManager.ServerCalculateApproximation().
IsNeuralOutputReady()
bool IG.Neural.NeuraApproximationFileManager.IsNeuralOutputReady () inline
Returns value of the falg that indicates whether the approximation output data is ready.
Definition at line 617 of file NeuralFileManager.cs.
References IG.Neural.NeuraApproximationFileManager.Lock, and IG.Neural.NeuraApproximationFileManager.MsgNeuralOutputReadyPath.
Referenced by IG.Neural.NeuraApproximationFileManager.ServerCalculateApproximation().
ClearMessages()
void IG.Neural.NeuraApproximationFileManager.ClearMessages () inline
Clears all messages for neural approximation client and server.
Definition at line 630 of file NeuralFileManager.cs.
References IG.Neural.NeuraApproximationFileManager.ClearNeuralBusy(), IG.Neural.NeuraApproximationFileManager.ClearNeuralInputReady(), and IG.Neural.NeuraApproximationFileManager.ClearNeuralOutputReady().
ReadNeuralInput()
virtual void IG.Neural.NeuraApproximationFileManager.ReadNeuralInput (ref IVector inputParameters) inline virtual
Reads neural approximator input parameters form the file at standard location.
Parameters
inputParameters Object where parameters are stored.
Definition at line 645 of file NeuralFileManager.cs.
References IG.Num.VectorBase.LoadJson(), and IG.Neural.NeuraApproximationFileManager.NeuralInputPath.
Referenced by IG.Neural.NeuraApproximationFileManager.ServerCalculateApproximation().
WriteNeuralInput()
virtual void IG.Neural.NeuraApproximationFileManager.WriteNeuralInput (IVector inputParameters) inline virtual
Writes neural approximator input parameters to standard location.
Parameters
inputParameters Parameters to be written.
Definition at line 652 of file NeuralFileManager.cs.
References IG.Neural.NeuraApproximationFileManager.NeuralInputPath, and IG.Num.VectorBase.SaveJson().
Referenced by IG.Neural.MappingApproximationFileManager.ClientTestCalculateMappingApproximation(), IG.Neural.NeuraApproximationFileManager.ClientWriteNeuralInput(), and IG.Neural.MappingApproximationFileManager.ServerCalculateMappingApproximation().
ReadNeuralOutput()
virtual void IG.Neural.NeuraApproximationFileManager.ReadNeuralOutput (ref IVector outputValues) inline virtual
Reads neural approximator output values from the file at standard location.
Parameters
outputValues Object where the read outut values are stored.
Definition at line 659 of file NeuralFileManager.cs.
References IG.Num.VectorBase.LoadJson(), and IG.Neural.NeuraApproximationFileManager.NeuralOutputPath.
Referenced by IG.Neural.NeuraApproximationFileManager.ClientReadNeuralOutput(), IG.Neural.MappingApproximationFileManager.ClientTestCalculateMappingApproximation(), and IG.Neural.MappingApproximationFileManager.ServerCalculateMappingApproximation().
WriteNeuralOutput()
virtual void IG.Neural.NeuraApproximationFileManager.WriteNeuralOutput (IVector outputValues) inline virtual
Writes neural approximator outut values to the file at standard location.
Parameters
outputValues Output values that are written.
Definition at line 666 of file NeuralFileManager.cs.
References IG.Neural.NeuraApproximationFileManager.NeuralOutputPath, and IG.Num.VectorBase.SaveJson().
Referenced by IG.Neural.NeuraApproximationFileManager.ServerCalculateApproximation().
LoadNeuralNetwork()
virtual void IG.Neural.NeuraApproximationFileManager.LoadNeuralNetwork (ref INeuralApproximator trainedNetwork) inline virtual
Loads the trained neural network approximator from the file at standard location.
Parameters
trainedNetwork Object where the loaded neural network approximator is stored.
Definition at line 673 of file NeuralFileManager.cs.
References IG.Num.NeuralApproximatorBase.LoadJson(), and IG.Neural.NeuraApproximationFileManager.NeuralNetworkPath.
Referenced by IG.Neural.NeuraApproximationFileManager.ServerCalculateApproximation().
ClientWriteNeuralInput()
virtual void IG.Neural.NeuraApproximationFileManager.ClientWriteNeuralInput (IVector inputParameters) inline virtual
Client writes input parameters for calculation of neural network based approximated values. Messages are set nad clears appropriately.
Parameters
inputParameters Parameters to be written.
Definition at line 687 of file NeuralFileManager.cs.
References IG.Neural.NeuraApproximationFileManager.ClearNeuralInputReady(), IG.Neural.NeuraApproximationFileManager.SetNeuralBusy(), IG.Neural.NeuraApproximationFileManager.SetNeuralInputReady(), and IG.Neural.NeuraApproximationFileManager.WriteNeuralInput().
Referenced by IG.Neural.NeuraApproximationFileManager.ClientCalculateApproximation().
ClientReadNeuralOutput()
virtual void IG.Neural.NeuraApproximationFileManager.ClientReadNeuralOutput (ref IVector outputValues) inline virtual
Client reads the results of neural network-based approximation (output values). Messages are set and clears appropriately.
Parameters
outputValues
Definition at line 698 of file NeuralFileManager.cs.
References IG.Neural.NeuraApproximationFileManager.ClearNeuralOutputReady(), and IG.Neural.NeuraApproximationFileManager.ReadNeuralOutput().
Referenced by IG.Neural.NeuraApproximationFileManager.ClientCalculateApproximation().
ClientSendRequestCalculateApproximation()
virtual void IG.Neural.NeuraApproximationFileManager.ClientSendRequestCalculateApproximation () inline virtual
Performs request to the server for calculation of neural network based approximated values.
Definition at line 705 of file NeuralFileManager.cs.
References IG.Neural.NeuraApproximationFileManager.ServerCalculateApproximation().
Referenced by IG.Neural.NeuraApproximationFileManager.ClientCalculateApproximation().
ClientCalculateApproximation()
virtual void IG.Neural.NeuraApproximationFileManager.ClientCalculateApproximation (IVector inputParameters, ref IVector outputValues) inline virtual
Calculates approximation by using the neural network approximation server.
Parameters
inputParameters Intput parameters for which approximation is calculated.
outputValues Vector where approximation output values are stored.
Definition at line 713 of file NeuralFileManager.cs.
References IG.Neural.NeuraApproximationFileManager.ClientReadNeuralOutput(), IG.Neural.NeuraApproximationFileManager.ClientSendRequestCalculateApproximation(), and IG.Neural.NeuraApproximationFileManager.ClientWriteNeuralInput().
Referenced by IG.Neural.NeuraApproximationFileManager.ClientTestCalculateApproximation().
ClientTestCalculateApproximation()
virtual void IG.Neural.NeuraApproximationFileManager.ClientTestCalculateApproximation (string inputFilePath, string outputFilePath) inline virtual
Performs client-side test calculation of neural network based approximation where input parameters are read from a specified JSON file, and calculated output values are written to the specified file.
Parameters
inputFilePath Path to the JSON file where input parameters are read from. The file pointed at must exist.
outputFilePath Path of a file where the calculated approximated values are written to. It can be null or empty string, in this case parameters are not written to a file (but they are still output on console).
Definition at line 728 of file NeuralFileManager.cs.
References IG.Neural.NeuraApproximationFileManager.ClientCalculateApproximation(), IG.Num.VectorBase.LoadJson(), and IG.Num.VectorBase.SaveJson().
Referenced by IG.Neural.MappingApproximationFileManager.ClientTestCalculateMappingApproximation().
ServerCalculateApproximation()
virtual void IG.Neural.NeuraApproximationFileManager.ServerCalculateApproximation () inline virtual
Performs neural network-based approximation at prescribed input parameters and saves results. Messages are set and cleared appropriately. This method read input parameters from standard location, loads trained neural network, calculates approximated outpur values and stores them to the standard location.
Definition at line 764 of file NeuralFileManager.cs.
References IG.Neural.NeuraApproximationFileManager.ClearNeuralInputReady(), IG.Neural.NeuraApproximationFileManager.ClearNeuralOutputReady(), IG.Neural.NeuraApproximationFileManager.IsNeuralBusy(), IG.Neural.NeuraApproximationFileManager.IsNeuralInputReady(), IG.Neural.NeuraApproximationFileManager.IsNeuralOutputReady(), IG.Neural.NeuraApproximationFileManager.LoadNeuralNetwork(), IG.Neural.NeuraApproximationFileManager.ReadNeuralInput(), IG.Neural.NeuraApproximationFileManager.SetNeuralBusy(), IG.Neural.NeuraApproximationFileManager.SetNeuralOutputReady(), and IG.Neural.NeuraApproximationFileManager.WriteNeuralOutput().
Referenced by IG.Neural.NeuraApproximationFileManager.ClientSendRequestCalculateApproximation(), and IG.Neural.MappingApproximationFileManager.ServerCalculateMappingApproximation().
Member Data Documentation
_mainLock
object IG.Neural.NeuraApproximationFileManager._mainLock = new object() private
Definition at line 43 of file NeuralFileManager.cs.
_internalLock
object IG.Neural.NeuraApproximationFileManager._internalLock = new object() private
Definition at line 50 of file NeuralFileManager.cs.
_dataDirectory
string IG.Neural.NeuraApproximationFileManager._dataDirectory = null protected
Definition at line 68 of file NeuralFileManager.cs.
_neuralNetworkFilename
string IG.Neural.NeuraApproximationFileManager._neuralNetworkFilename = NeuralFileConst.NeuralNetworkFilename private
Definition at line 128 of file NeuralFileManager.cs.
_neuralNetworkPath
string IG.Neural.NeuraApproximationFileManager._neuralNetworkPath = null private
Definition at line 129 of file NeuralFileManager.cs.
_neuralDataDefinitionFilename
string IG.Neural.NeuraApproximationFileManager._neuralDataDefinitionFilename = NeuralFileConst.NeuralDataDefinitionFilename private
Definition at line 130 of file NeuralFileManager.cs.
_neuralDataDefinitionPath
string IG.Neural.NeuraApproximationFileManager._neuralDataDefinitionPath = null private
Definition at line 131 of file NeuralFileManager.cs.
_simulationDataDefinitionFilename
string IG.Neural.NeuraApproximationFileManager._simulationDataDefinitionFilename = NeuralFileConst.SimulationDataDefinitionFilename private
Definition at line 132 of file NeuralFileManager.cs.
_simulationDataDefinitionPath
string IG.Neural.NeuraApproximationFileManager._simulationDataDefinitionPath = null private
Definition at line 133 of file NeuralFileManager.cs.
_neuralTrainingDataFilename
string IG.Neural.NeuraApproximationFileManager._neuralTrainingDataFilename = NeuralFileConst.NeuralTrainingDataFilename private
Definition at line 134 of file NeuralFileManager.cs.
_neuralTrainingDataPath
string IG.Neural.NeuraApproximationFileManager._neuralTrainingDataPath = null private
Definition at line 135 of file NeuralFileManager.cs.
_neuralVerificationDataFilename
string IG.Neural.NeuraApproximationFileManager._neuralVerificationDataFilename = NeuralFileConst.NeuralVerificationDataFilename private
Definition at line 136 of file NeuralFileManager.cs.
_neuralVerificationDataPath
string IG.Neural.NeuraApproximationFileManager._neuralVerificationDataPath = null private
Definition at line 137 of file NeuralFileManager.cs.
_neuralInputFilename
string IG.Neural.NeuraApproximationFileManager._neuralInputFilename = NeuralFileConst.NeuralInputFilename private
Definition at line 139 of file NeuralFileManager.cs.
_neuralInputPath
string IG.Neural.NeuraApproximationFileManager._neuralInputPath = null private
Definition at line 140 of file NeuralFileManager.cs.
_neuralInputXmlFilename
string IG.Neural.NeuraApproximationFileManager._neuralInputXmlFilename = NeuralFileConst.NeuralInputXmlFilename private
Definition at line 141 of file NeuralFileManager.cs.
_neuralInputXmlPath
string IG.Neural.NeuraApproximationFileManager._neuralInputXmlPath = null private
Definition at line 142 of file NeuralFileManager.cs.
_neuralOutputFilename
string IG.Neural.NeuraApproximationFileManager._neuralOutputFilename = NeuralFileConst.NeuralOutputFilename private
Definition at line 143 of file NeuralFileManager.cs.
_neuralOutputPath
string IG.Neural.NeuraApproximationFileManager._neuralOutputPath = null private
Definition at line 144 of file NeuralFileManager.cs.
_neuralOutputXmlFilename
string IG.Neural.NeuraApproximationFileManager._neuralOutputXmlFilename = NeuralFileConst.NeuralOutputeXmlFilename private
Definition at line 145 of file NeuralFileManager.cs.
_neuralOutputXmlPath
string IG.Neural.NeuraApproximationFileManager._neuralOutputXmlPath = null private
Definition at line 146 of file NeuralFileManager.cs.
_msgNeuralBusyFilename
string IG.Neural.NeuraApproximationFileManager._msgNeuralBusyFilename = NeuralFileConst.MsgNeuralBusyFilename private
Definition at line 152 of file NeuralFileManager.cs.
_msgNeuralBusyPath
string IG.Neural.NeuraApproximationFileManager._msgNeuralBusyPath = null private
Definition at line 153 of file NeuralFileManager.cs.
_msgNeuralInputReadyFilename
string IG.Neural.NeuraApproximationFileManager._msgNeuralInputReadyFilename = NeuralFileConst.MsgNeuralInputReadyFilename private
Definition at line 154 of file NeuralFileManager.cs.
_msgNeuralInputReadyPath
string IG.Neural.NeuraApproximationFileManager._msgNeuralInputReadyPath = null private
Definition at line 155 of file NeuralFileManager.cs.
_msgNeuralOutputReadyFilename
string IG.Neural.NeuraApproximationFileManager._msgNeuralOutputReadyFilename = NeuralFileConst.MsgNeuralOutputReadyFilename private
Definition at line 156 of file NeuralFileManager.cs.
_msgNeuralOutputReadyPath
string IG.Neural.NeuraApproximationFileManager._msgNeuralOutputReadyPath = null private
Definition at line 157 of file NeuralFileManager.cs.
Property Documentation
Lock
object IG.Neural.NeuraApproximationFileManager.Lock get
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
Definition at line 48 of file NeuralFileManager.cs.
Referenced by IG.Neural.MappingApproximationFileManager.ClearFunctionInputReady(), IG.Neural.MappingApproximationFileManager.ClearFunctionOutputReady(), IG.Neural.NeuraApproximationFileManager.ClearNeuralBusy(), IG.Neural.NeuraApproximationFileManager.ClearNeuralInputReady(), IG.Neural.NeuraApproximationFileManager.ClearNeuralOutputReady(), IG.Neural.NeuraApproximationFileManager.GetPath(), IG.Neural.MappingApproximationFileManager.IsFunctionInputReady(), IG.Neural.MappingApproximationFileManager.IsFunctionOutputReady(), IG.Neural.NeuraApproximationFileManager.IsNeuralBusy(), IG.Neural.NeuraApproximationFileManager.IsNeuralInputReady(), IG.Neural.NeuraApproximationFileManager.IsNeuralOutputReady(), IG.Neural.MappingApproximationFileManager.SetFunctionInputReady(), IG.Neural.MappingApproximationFileManager.SetFunctionOutputReady(), IG.Neural.NeuraApproximationFileManager.SetNeuralBusy(), IG.Neural.NeuraApproximationFileManager.SetNeuralInputReady(), and IG.Neural.NeuraApproximationFileManager.SetNeuralOutputReady().
InternalLock
object IG.Neural.NeuraApproximationFileManager.InternalLock get protected
Used internally for locking access to internal fields.
Definition at line 53 of file NeuralFileManager.cs.
DataDirectory
string IG.Neural.NeuraApproximationFileManager.DataDirectory get protected set
Directory for data and messages exchange through files.
Definition at line 72 of file NeuralFileManager.cs.
Referenced by IG.Neural.NeuraApproximationFileManager.GetPath(), and IG.Neural.NeuraApproximationFileManager.NeuraApproximationFileManager().
NeuralNetworkPath
string IG.Neural.NeuraApproximationFileManager.NeuralNetworkPath get protected set
File path of the file where complete (usually trained) neural network is stored. Setter takes only pure file name, without path information. If set to null then file path is set to null and will be recalculated when getter is called.
Definition at line 167 of file NeuralFileManager.cs.
Referenced by IG.Neural.NeuraApproximationFileManager.LoadNeuralNetwork().
NeuralDataDefinitionPath
string IG.Neural.NeuraApproximationFileManager.NeuralDataDefinitionPath get protected set
File path of the input and output data definition file. Setter takes only pure file name, without path information. If set to null then file path is set to null and will be recalculated when getter is called.
Definition at line 195 of file NeuralFileManager.cs.
Referenced by IG.Neural.MappingApproximationFileManager.ClientTestCalculateMappingApproximation(), IG.Neural.MappingApproximationFileManager.LoadDataDefinition(), and IG.Neural.MappingApproximationFileManager.MappingApproximationFileManager().
SimulationDataDefinitionPath
string IG.Neural.NeuraApproximationFileManager.SimulationDataDefinitionPath get protected set
File path of the input and output data definition file for simulator. Setter takes only pure file name, without path information. If set to null then file path is set to null and will be recalculated when getter is called.
Definition at line 222 of file NeuralFileManager.cs.
NeuralVerificationDataPath
string IG.Neural.NeuraApproximationFileManager.NeuralVerificationDataPath get protected set
File path of the verification data file. Setter takes only pure file name, without path information. If set to null then file path is set to null and will be recalculated when getter is called.
Definition at line 249 of file NeuralFileManager.cs.
NeuralTrainingDataPath
string IG.Neural.NeuraApproximationFileManager.NeuralTrainingDataPath get protected set
File path of the training data file. Setter takes only pure file name, without path information. If set to null then file path is set to null and will be recalculated when getter is called.
Definition at line 276 of file NeuralFileManager.cs.
NeuralInputPath
string IG.Neural.NeuraApproximationFileManager.NeuralInputPath get protected set
File path of the file with input parameters. Setter takes only pure file name, without path information. If set to null then file path is set to null and will be recalculated when getter is called.
Definition at line 308 of file NeuralFileManager.cs.
Referenced by IG.Neural.MappingApproximationFileManager.ClientTestCalculateMappingApproximation(), IG.Neural.NeuraApproximationFileManager.ReadNeuralInput(), and IG.Neural.NeuraApproximationFileManager.WriteNeuralInput().
NeuralInputXmlPath
string IG.Neural.NeuraApproximationFileManager.NeuralInputXmlPath get protected set
File path of the input parameters file in XML format. Setter takes only pure file name, without path information. If set to null then file path is set to null and will be recalculated when getter is called.
Definition at line 336 of file NeuralFileManager.cs.
NeuralOutputPath
string IG.Neural.NeuraApproximationFileManager.NeuralOutputPath get protected set
File path of the file for storing approximated output values. Setter takes only pure file name, without path information. If set to null then file path is set to null and will be recalculated when getter is called.
Definition at line 364 of file NeuralFileManager.cs.
Referenced by IG.Neural.MappingApproximationFileManager.ClientTestCalculateMappingApproximation(), IG.Neural.NeuraApproximationFileManager.ReadNeuralOutput(), and IG.Neural.NeuraApproximationFileManager.WriteNeuralOutput().
NeuralOutputeXmlPath
string IG.Neural.NeuraApproximationFileManager.NeuralOutputeXmlPath get protected set
File path of the file for storing approximated output values in XML format. Setter takes only pure file name, without path information. If set to null then file path is set to null and will be recalculated when getter is called.
Definition at line 392 of file NeuralFileManager.cs.
MsgNeuralBusyPath
string IG.Neural.NeuraApproximationFileManager.MsgNeuralBusyPath get protected set
File path of the message file indicating that approximator is busy by performing a job. Setter takes only pure file name, without path information. If set to null then file path is set to null and will be recalculated when getter is called.
Definition at line 425 of file NeuralFileManager.cs.
Referenced by IG.Neural.NeuraApproximationFileManager.ClearNeuralBusy(), IG.Neural.NeuraApproximationFileManager.IsNeuralBusy(), and IG.Neural.NeuraApproximationFileManager.SetNeuralBusy().
MsgNeuralInputReadyPath
string IG.Neural.NeuraApproximationFileManager.MsgNeuralInputReadyPath get protected set
File path of the message file indicating taht input data is ready to be processed. Setter takes only pure file name, without path information. If set to null then file path is set to null and will be recalculated when getter is called.
Definition at line 453 of file NeuralFileManager.cs.
Referenced by IG.Neural.NeuraApproximationFileManager.ClearNeuralInputReady(), IG.Neural.NeuraApproximationFileManager.IsNeuralInputReady(), and IG.Neural.NeuraApproximationFileManager.SetNeuralInputReady().
MsgNeuralOutputReadyPath
string IG.Neural.NeuraApproximationFileManager.MsgNeuralOutputReadyPath get protected set
File path of the message file indicating that the approximated output is ready to be read. Setter takes only pure file name, without path information. If set to null then file path is set to null and will be recalculated when getter is called.
Definition at line 481 of file NeuralFileManager.cs.
Referenced by IG.Neural.NeuraApproximationFileManager.ClearNeuralOutputReady(), IG.Neural.NeuraApproximationFileManager.IsNeuralOutputReady(), and IG.Neural.NeuraApproximationFileManager.SetNeuralOutputReady().
The documentation for this class was generated from the following file:
iglib/igbase/numeric/approximation/neural/testneural/NeuralFileManager.cs