Doc: IGLib with source files: IGLib.Core.ModelParameterSetFixedBase< ModelParameterType > Class Template Reference
IGLib.Core.ModelParameterSetFixedBase< ModelParameterType > Class Template Reference
Contains a set of model parameters as ModelParameterType objects, accessible by string keys, and some metadata such as name, title, and description of the set.
Public Member Functions
ModelParameterSetFixedBase (string title, string description, params ModelParameterType[] parameters)
Constructor, initializes the current model parameter set, optionally providing parameter objects that are added to the set.
ModelParameterSetFixedBase (string title, string description, params(string Name, ModelParameterType Parameter)[] keysAndParameters)
Constructor, initializes the current model parameter set, optionally using tuples of names and parameter objects that are added to the set.
bool ContainsKey (string key)
Returns true if the current parameter set contains the specified key.
override string ToString ()
Static Public Member Functions
static ModelParameterSetBase< ModelParameterType > CreateExampleParameterSet2 ()
Creates a sample ModelParameterSet object, prints its content to console, and returns it.
Public Attributes
int Count => ParametersDictionaryInternal.Count
IReadOnlyList< ModelParameterType > ParameterList
Static Public Attributes
const bool DefaultCanAddParemeters = true
The default value of IModelParameterSetBaseFixed<ModelParameterType>.CanAddParameters, used for consistent initialization across different ways of initialization and accross types for which this property is not predetermined (fixed).
Protected Member Functions
void AddParameters (bool canReplaceParameter, bool isInitializing, params ModelParameterType[] parameters)
void AddParameters (bool canReplaceParameter, bool isInitializing, params(string Name, ModelParameterType Parameter)[] keysAndParameters)
void AddParameter (string parameterKey, ModelParameterType parameter, bool canReplaceParameter, bool isInitializing)
Adds the specified parameter parameter with access key parameterKey to the current parameter set. Exception is thrown if adding paremeter cannot be performed.
Properties
Dictionary< string, ModelParameterType > ParametersDictionaryInternal [get]
List< string > ParameterNamesInternal = new List<string>() [get]
string Title [get, protected set]
string Description [get, protected set]
virtual ModelParameterType this[string parameterName] [get]
virtual ModelParameterType this[int whichParameter] [get]
bool CanAddParameters = DefaultCanAddParemeters [get]
Properties inherited from IGLib.Core.IModelParameterSetBaseFixed< ModelParameterType >
string Title [get]
Title when introducing the parameter set, for example as title in documentation, as label in user interfaces where parameter set is displayed or where it could be edited, etc.
string Description [get]
Description of the parameter set, usually a short one, as it may be used in documentation describing the model or in user interfaces (e.g. as tooltip).
IReadOnlyList< ModelParameterType > ParameterList [get]
Gets a readonly list of model parameter objects, ordered in the same order in which parameters were added to the set during parameterization. This enables preservation of sequential order when this is importatnt.
int Count [get]
Number of parameters contained in the set.
ModelParameterType this[string parameterName] [get]
Index operator, gets the specific parameter by its name.
ModelParameterType this[int whichParameter] [get]
Index operator, gets the specific model parameter by its sequential order (counting from 0) in which parameters were added to the parameter set.
bool CanAddParameters [get]
Whether or not parameters can be added after the parameter set has ben created.
Detailed Description
Contains a set of model parameters as ModelParameterType objects, accessible by string keys, and some metadata such as name, title, and description of the set.
Parameters can be accessed both by string key (usually parameter name) and integer index. Parameters are indexed according to order in which they were added to the set.
In this class, parameters can only be added to the set via constructors, and cannot be removed from the set (therefore the "Fixed" suffix).
Order in which parameters are added is kept. ParameterList returns a readonly list of parameters sorted in the orded in which paremeters were specified in constructors.
Type Constraints
ModelParameterType : IModelParameter
Definition at line 17 of file ModelParameterSetFixedBase.cs.
Constructor & Destructor Documentation
ModelParameterSetFixedBase() [1/2]
IGLib.Core.ModelParameterSetFixedBase< ModelParameterType >.ModelParameterSetFixedBase (string title, string description, params ModelParameterType[] parameters) inline
Constructor, initializes the current model parameter set, optionally providing parameter objects that are added to the set.
Parameters
title Title of the parameter set, defines the Title property.
description Description of the parameter set, defines the Description property.
parameters Parameter objects to initalize the parameter set. Name of eacch paremeter object (ModelParameterType.Name) is used as access key for that parameter.
Definition at line 27 of file ModelParameterSetFixedBase.cs.
References IGLib.Core.ModelParameterSetFixedBase< ModelParameterType >.AddParameters(), IGLib.Core.ModelParameterSetFixedBase< ModelParameterType >.CanAddParameters, IGLib.Core.ModelParameterSetFixedBase< ModelParameterType >.Description, and IGLib.Core.ModelParameterSetFixedBase< ModelParameterType >.Title.
ModelParameterSetFixedBase() [2/2]
IGLib.Core.ModelParameterSetFixedBase< ModelParameterType >.ModelParameterSetFixedBase (string title, string description, params(string Name, ModelParameterType Parameter)[] keysAndParameters) inline
Constructor, initializes the current model parameter set, optionally using tuples of names and parameter objects that are added to the set.
Parameters
title Title of the parameter set, defines the Title property.
description Description of the parameter set, defines the Description property.
keysAndParameters Tuples of names (used as keys keys) and the corresponding parameter objects to initalize the parameter set.
Definition at line 43 of file ModelParameterSetFixedBase.cs.
References IGLib.Core.ModelParameterSetFixedBase< ModelParameterType >.AddParameters(), IGLib.Core.ModelParameterSetFixedBase< ModelParameterType >.CanAddParameters, IGLib.Core.ModelParameterSetFixedBase< ModelParameterType >.Description, and IGLib.Core.ModelParameterSetFixedBase< ModelParameterType >.Title.
Member Function Documentation
AddParameters() [1/2]
void IGLib.Core.ModelParameterSetFixedBase< ModelParameterType >.AddParameters (bool canReplaceParameter, bool isInitializing, params ModelParameterType[] parameters) inline protected
Definition at line 68 of file ModelParameterSetFixedBase.cs.
References IGLib.Core.ModelParameterSetFixedBase< ModelParameterType >.AddParameter().
Referenced by IGLib.Core.ModelParameterSetFixedBase< ModelParameterType >.ModelParameterSetFixedBase().
AddParameters() [2/2]
void IGLib.Core.ModelParameterSetFixedBase< ModelParameterType >.AddParameters (bool canReplaceParameter, bool isInitializing, params(string Name, ModelParameterType Parameter)[] keysAndParameters) inline protected
Definition at line 77 of file ModelParameterSetFixedBase.cs.
References IGLib.Core.ModelParameterSetFixedBase< ModelParameterType >.AddParameter().
AddParameter()
void IGLib.Core.ModelParameterSetFixedBase< ModelParameterType >.AddParameter (string parameterKey, ModelParameterType parameter, bool canReplaceParameter, bool isInitializing) inline protected
Adds the specified parameter parameter with access key parameterKey to the current parameter set. Exception is thrown if adding paremeter cannot be performed.
Parameters
parameterKey Key under which parameter is added.
Parameters
parameter Parameter that is added.
canReplaceParameter Whether or not this call is allowed to replace the paremeter that is already contained under the ket parameterKey . If this paremeter is false and parameter under the key parameterKey is already contained in the set then exception is thrown.
isInitializing Whether the object is currently initializing. This information is used to form more meaningful messages in case of exceptions.
Exceptions
ArgumentNullException When parameterKey is null.
ArgumentException When parameterKey is an empty string.
InvalidOperationException When parameter with the key parameterKey is already contained in the set and replacing is not allowed (i.e., canReplaceParameter is false)
Definition at line 104 of file ModelParameterSetFixedBase.cs.
References IGLib.Core.ModelParameterSetFixedBase< ModelParameterType >.ParameterNamesInternal, and IGLib.Core.ModelParameterSetFixedBase< ModelParameterType >.ParametersDictionaryInternal.
Referenced by IGLib.Core.ModelParameterSetFixedBase< ModelParameterType >.AddParameters().
ContainsKey()
bool IGLib.Core.ModelParameterSetFixedBase< ModelParameterType >.ContainsKey (string key) inline
Returns true if the current parameter set contains the specified key.
Implements IGLib.Core.IModelParameterSetBaseFixed< ModelParameterType >.
Definition at line 140 of file ModelParameterSetFixedBase.cs.
References IGLib.Core.ModelParameterSetFixedBase< ModelParameterType >.ParametersDictionaryInternal.
ToString()
override string IGLib.Core.ModelParameterSetFixedBase< ModelParameterType >.ToString () inline
Definition at line 172 of file ModelParameterSetFixedBase.cs.
References IGLib.Core.ModelParameterSetFixedBase< ModelParameterType >.ParameterList.
CreateExampleParameterSet2()
static ModelParameterSetBase<ModelParameterType> IGLib.Core.ModelParameterSetFixedBase< ModelParameterType >.CreateExampleParameterSet2 () inline static
Creates a sample ModelParameterSet object, prints its content to console, and returns it.
Definition at line 191 of file ModelParameterSetFixedBase.cs.
Member Data Documentation
Count
int IGLib.Core.ModelParameterSetFixedBase< ModelParameterType >.Count => ParametersDictionaryInternal.Count
Definition at line 137 of file ModelParameterSetFixedBase.cs.
ParameterList
IReadOnlyList<ModelParameterType> IGLib.Core.ModelParameterSetFixedBase< ModelParameterType >.ParameterList
Initial value:
=> ParameterNamesInternal
            .Select(name => ParametersDictionaryInternal[name]).ToList()
Definition at line 160 of file ModelParameterSetFixedBase.cs.
Referenced by IGLib.Core.ModelParameterSetFixedBase< ModelParameterType >.ToString().
DefaultCanAddParemeters
const bool IGLib.Core.ModelParameterSetFixedBase< ModelParameterType >.DefaultCanAddParemeters = true static
The default value of IModelParameterSetBaseFixed<ModelParameterType>.CanAddParameters, used for consistent initialization across different ways of initialization and accross types for which this property is not predetermined (fixed).
Definition at line 166 of file ModelParameterSetFixedBase.cs.
Property Documentation
ParametersDictionaryInternal
Dictionary<string, ModelParameterType> IGLib.Core.ModelParameterSetFixedBase< ModelParameterType >.ParametersDictionaryInternal get protected
Initial value:
=
            new Dictionary<string, ModelParameterType>()
Definition at line 63 of file ModelParameterSetFixedBase.cs.
Referenced by IGLib.Core.ModelParameterSetFixedBase< ModelParameterType >.AddParameter(), and IGLib.Core.ModelParameterSetFixedBase< ModelParameterType >.ContainsKey().
ParameterNamesInternal
List<string> IGLib.Core.ModelParameterSetFixedBase< ModelParameterType >.ParameterNamesInternal = new List<string>() get protected
Definition at line 66 of file ModelParameterSetFixedBase.cs.
Referenced by IGLib.Core.ModelParameterSetFixedBase< ModelParameterType >.AddParameter().
Title
string IGLib.Core.ModelParameterSetFixedBase< ModelParameterType >.Title get protected set
Definition at line 131 of file ModelParameterSetFixedBase.cs.
Referenced by IGLib.Core.ModelParameterSetFixedBase< ModelParameterType >.ModelParameterSetFixedBase().
Description
string IGLib.Core.ModelParameterSetFixedBase< ModelParameterType >.Description get protected set
Definition at line 134 of file ModelParameterSetFixedBase.cs.
Referenced by IGLib.Core.ModelParameterSetFixedBase< ModelParameterType >.ModelParameterSetFixedBase().
this[string parameterName]
virtual ModelParameterType IGLib.Core.ModelParameterSetFixedBase< ModelParameterType >.this[string parameterName] get
Definition at line 147 of file ModelParameterSetFixedBase.cs.
this[int whichParameter]
virtual ModelParameterType IGLib.Core.ModelParameterSetFixedBase< ModelParameterType >.this[int whichParameter] get
Definition at line 156 of file ModelParameterSetFixedBase.cs.
CanAddParameters
bool IGLib.Core.ModelParameterSetFixedBase< ModelParameterType >.CanAddParameters = DefaultCanAddParemeters get
Definition at line 168 of file ModelParameterSetFixedBase.cs.
Referenced by IGLib.Core.ModelParameterSetBase< ModelParameterType >.ModelParameterSetBase(), and IGLib.Core.ModelParameterSetFixedBase< ModelParameterType >.ModelParameterSetFixedBase().
The documentation for this class was generated from the following file:
IGLibGraphics3D/src/IGLib.Graphics3D/other/ModelParameters/ModelParameterSetFixedBase.cs