Doc: IGLib with source files: IG.Num.Field< TElement > Class Template Reference
IG.Num.Field< TElement > Class Template Reference
A generic field of values of any type. Values must be allocated at once.
Classes
class ExampleClassScalarField
Example of a field class.
Public Member Functions
Field ()
Constructs a new empty field (no elements contained) with no name and no description.
Field (int numElements)
Creates a new field with the specified number of elements.
Field (int numElements, string fieldName)
Constructs a new field with the specified number of elements and name.
Field (int numElements, string fieldName, string fieldDescription)
Constructs a new field with the specified number of elements, name and description. Table of elements is allocated.
virtual void SetLength (int newLength)
Sets the length of the current field to the specified value.
TElement GetValue (int index)
Returns element of the field at the specified index.
void SetValue (int index, TElement value)
Sets the element at the specified index to the specified value.
Static Public Member Functions
static void UpdateBounds (Field< double > field, IBoundingBox bounds, int componentIndex)
Updates the specified component of the specified bounds (object of type IBoundingBox) in such a way that all elements of the specified field will fit within the bounds.
static void UpdateBounds< TEl > (Field< TEl > field, IBoundingBox bounds)
Updates the specified bounds (object of type IBoundingBox) in such a way that all non-null vectors on the specified field will fit within the bounds.
static void UpdateBounds (Field< vec3 > field, IBoundingBox bounds)
Updates the specified bounds (object of type IBoundingBox) in such a way that all 3D vector elements of type vec3 of the specified field will fit within the bounds.
static void MapCoordinatesPlain (Field< vec3 > referenceField, Field< vec3 > targetField, IFunc3d fx, IFunc3d fy, IFunc3d fz)
Generates coordinates of a set of unstructured 3D points (point cloud) from a reference set according to 3 scalar functions of 3 variables that map coordinates of the reference points to components of the mapped points.
static void MapCoordinates (Field< vec3 > referenceField, Field< vec3 > targetField, IFunc3d fx, IFunc3d fy, IFunc3d fz)
Generates coordinates of a set of unstructured points (point cloud) from a reference set according to 3 scalar functions of 3 variables that map coordinates of the reference points to components of the mapped points.
static void MapCoordinates2dPlain (Field< vec3 > referenceField, Field< vec3 > targetField, IFunc2d fx, IFunc2d fy, IFunc2d fz)
Generates coordinates of a set of unstructured 3D points (point cloud) from a reference set according to 3 scalar functions of 2 variables that map coordinates of the reference points to components of the mapped points. Mapping functions act only on the first two coordinates of each point.
static void MapCoordinates2d (Field< vec3 > referenceField, Field< vec3 > targetField, IFunc2d fx, IFunc2d fy, IFunc2d fz)
Generates coordinates of a set of unstructured points (point cloud) from a reference set according to 3 scalar functions of 2 variables that map the first two coordinates of the reference points to components of the mapped points.
static void MapCoordinates1dPlain (Field< vec3 > referenceField, Field< vec3 > targetField, IRealFunction fx, IRealFunction fy, IRealFunction fz)
Generates coordinates of a set of unstructured 3D points (point cloud) from a reference set according to 3 functions of 1 variable that map the first coordinate of the reference points to components of the mapped points.
static void MapCoordinates1d (Field< vec3 > referenceField, Field< vec3 > targetField, IRealFunction fx, IRealFunction fy, IRealFunction fz)
Generates coordinates of a set of unstructured 3D points (point cloud) from a reference set according to 3 functions of 1 variable that map the first coordinate of the reference points to components of the mapped points.
static void MapCoordinatesToScalarsPlain (Field< vec3 > referenceField, Field< double > targetScalarField, IFunc3d scalarMap)
Generates scalar values for a 3D unstructured set fo points from the specified field of grid coordinates by a specified scalar function of 3 variables that maps coordinates to scalar values.
static void MapCoordinatesToScalars (Field< vec3 > referenceField, Field< double > targetScalarField, IFunc3d scalarMap)
Generates scalar values for a 3D unstructured set fo points from the specified field of grid coordinates by a specified scalar function of 3 variables that maps coordinates to scalar values.
static void GenerateCoordinatesPlain (Field< vec3 > field, int dimx, int dimy, int dimz, double minxRef, double maxxRef, double minyRef, double maxyRef, double minzRef, double maxzRef)
Generates coordinates of a 3D unstructured grid from a regular grid with grid directions parallel to coordinate axes and equidistantly arranged nodes in all directions.
static void GenerateCoordinates (Field< vec3 > field, int dimx, int dimy, int dimz, double minxRef, double maxxRef, double minyRef, double maxyRef, double minzRef, double maxzRef)
Generates coordinates of a 3D unstructured grid from a regular grid with grid directions parallel to coordinate axes and equidistantly arranged nodes in all directions.
static void GenerateCoordinatesPlain (Field< vec3 > field, int dimx, int dimy, int dimz, double minxRef, double maxxRef, double minyRef, double maxyRef, double minzRef, double maxzRef, IFunc3d fx, IFunc3d fy, IFunc3d fz)
Generates coordinates of a 3D unstructured grid of a parametric volume according to functions specifying the x, y, and z coordinates in terms of three scalar functions of 3 variables.
static void GenerateCoordinates (Field< vec3 > field, int dimx, int dimy, int dimz, double minxRef, double maxxRef, double minyRef, double maxyRef, double minzRef, double maxzRef, IFunc3d fx, IFunc3d fy, IFunc3d fz)
Generates coordinates of a 3D unstructured grid of a parametric volume according to functions specifying the x, y, and z coordinates in terms of three scalar functions of 3 variables.
static void UpdateBounds (Field< vec2 > field, IBoundingBox bounds)
Updates the specified bounds (object of type IBoundingBox) in such a way that all 2D vector elements of type vec2 of the specified field will fit within the bounds.
static void MapCoordinatesPlain (Field< vec2 > referenceField, Field< vec2 > targetField, IFunc2d fx, IFunc2d fy)
Generates coordinates of a set of unstructured 3D points (point cloud) from a reference set according to 2 scalar functions of 2 variables that map coordinates of the reference points to components of the mapped points.
static void MapCoordinates (Field< vec2 > referenceField, Field< vec2 > targetField, IFunc2d fx, IFunc2d fy)
Generates coordinates of a set of unstructured points (point cloud) from a reference set according to 2 scalar functions of 2 variables that map coordinates of the reference points to components of the mapped points.
static void MapCoordinates1dPlain (Field< vec2 > referenceField, Field< vec2 > targetField, IRealFunction fx, IRealFunction fy)
Generates coordinates of a set of unstructured 2D points (point cloud) from a reference set according to 2 functions of 1 variables that map the first coordinate of the reference points to components of the mapped points.
static void MapCoordinates1d (Field< vec2 > referenceField, Field< vec2 > targetField, IRealFunction fx, IRealFunction fy)
Generates coordinates of a set of unstructured 2D points (point cloud) from a reference set according to 2 functions of 1 variables that map the first coordinate of the reference points to components of the mapped points.
static void MapCoordinatesToScalarsPlain (Field< vec2 > referenceField, Field< double > targetScalarField, IFunc2d scalarMap)
Generates scalar values for a 2D unstructured set fo points from the specified field of grid coordinates by a specified scalar function of 2 variables that maps coordinates to scalar values.
static void MapCoordinatesToScalars (Field< vec2 > referenceField, Field< double > targetScalarField, IFunc2d scalarMap)
Generates scalar values for a 2D unstructured set fo points from the specified field of grid coordinates by a specified scalar function of 2 variables that maps coordinates to scalar values.
static void GenerateCoordinatesPlain (Field< vec2 > field, int dimx, int dimy, double minxRef, double maxxRef, double minyRef, double maxyRef)
Generates coordinates of a 3D unstructured grid from a regular grid with grid directions parallel to coordinate axes and equidistantly arranged nodes in all directions.
static void GenerateCoordinates (Field< vec2 > field, int dimx, int dimy, double minxRef, double maxxRef, double minyRef, double maxyRef)
Generates coordinates of a 3D unstructured grid from a regular grid with grid directions parallel to coordinate axes and equidistantly arranged nodes in all directions.
static void GenerateCoordinatesPlain (Field< vec2 > field, int dimx, int dimy, double minxRef, double maxxRef, double minyRef, double maxyRef, IFunc2d fx, IFunc2d fy)
Generates coordinates of a 3D unstructured grid of a parametric volume according to functions specifying the x, y, and z coordinates in terms of three scalar functions of 3 variables.
static void GenerateCoordinates (Field< vec2 > field, int dimx, int dimy, double minxRef, double maxxRef, double minyRef, double maxyRef, IFunc2d fx, IFunc2d fy)
Generates coordinates of a 3D unstructured grid of a parametric volume according to functions specifying the x, y, and z coordinates in terms of three scalar functions of 3 variables.
static void GenerateCoordinates2dPlain (Field< vec3 > field, int dimx, int dimy, double minxRef, double maxxRef, double minyRef, double maxyRef)
Generates coordinates of a 2D unstructured grid embedded in 3D from a regular grid with grid directions parallel to the first two coordinate axes and equidistantly arranged nodes in all directions.
static void GenerateCoordinates2d (Field< vec3 > field, int dimx, int dimy, double minxRef, double maxxRef, double minyRef, double maxyRef)
Generates coordinates of a 2D unstructured grid embedded in 3D from a regular grid with grid directions parallel to the first two coordinate axes and equidistantly arranged nodes in all directions.
static void GenerateCoordinates2dPlain (Field< vec3 > field, int dimx, int dimy, double minxRef, double maxxRef, double minyRef, double maxyRef, IFunc2d fx, IFunc2d fy, IFunc2d fz)
Generates coordinates of a 3D unstructured grid of a parametric volume according to functions specifying the x, y, and z coordinates in terms of three scalar functions of 3 variables.
static void GenerateCoordinates2d (Field< vec3 > field, int dimx, int dimy, double minxRef, double maxxRef, double minyRef, double maxyRef, IFunc2d fx, IFunc2d fy, IFunc2d fz)
Generates coordinates of a 3D unstructured grid of a parametric volume according to functions specifying the x, y, and z coordinates in terms of three scalar functions of 3 variables.
static void GenerateCoordinates1dPlain (Field< vec3 > field, int dimx, double minxRef, double maxxRef)
Generates coordinates of a 1D unstructured grid from a regular grid with grid direction parallel to X coordinate axes and equidistantly arranged nodes.
static void GenerateCoordinates1d (Field< vec3 > field, int dimx, double minxRef, double maxxRef)
Generates coordinates of a 1D unstructured grid from a regular grid with grid direction parallel to X coordinate axis and equidistantly arranged nodes.
static void GenerateCoordinates1dPlain (Field< vec3 > field, int dimx, double minxRef, double maxxRef, IRealFunction fx, IRealFunction fy, IRealFunction fz)
Generates coordinates of a 1D unstructured grid of a parametric curve according to functions specifying the x, y, and z coordinates in terms of three functions of 1 variable.
static void GenerateCoordinates1d (Field< vec3 > field, int dimx, double minxRef, double maxxRef, IRealFunction fx, IRealFunction fy, IRealFunction fz)
Generates coordinates of a 1D unstructured grid of a parametric curve according to functions specifying the x, y, and z coordinates in terms of three functions of 1 variables.
static void GenerateCoordinates1dPlain (Field< vec2 > field, int dimx, double minxRef, double maxxRef)
Generates coordinates of a 1D unstructured grid embedded in 2D space from a regular grid with grid direction parallel to X coordinate axes and equidistantly arranged nodes.
static void GenerateCoordinates (Field< vec2 > field, int dimx, double minxRef, double maxxRef)
Generates coordinates of a 1D unstructured grid embedded in 2D space from a regular grid with grid direction parallel to X coordinate axis and equidistantly arranged nodes.
static void GenerateCoordinates1dPlain (Field< vec2 > field, int dimx, double minxRef, double maxxRef, IRealFunction fx, IRealFunction fy)
Generates coordinates of a 1D unstructured grid embedded in 2D space of a parametric curve according to functions specifying the x, and y coordinates in terms of 2 functions of 1 variable.
static void GenerateCoordinates1d (Field< vec2 > field, int dimx, double minxRef, double maxxRef, IRealFunction fx, IRealFunction fy)
Generates coordinates of a 1D unstructured grid embedded in 2D space of a parametric curve according to functions specifying the x, and y coordinates in terms of 2 functions of 1 variable.
static void Example ()
Protected Attributes
TElement[] _values
Properties
string Name [get, set]
Name of the field.
string Description [get, set]
Description of the field.
virtual TElement[] Values [get, protected set]
Array of field values.
int Length [get, protected set]
Number of elements.
TElement this[int index] [get, set]
Access to elements through element index.
Private Attributes
string _name
string _description
int _length
Detailed Description
A generic field of values of any type. Values must be allocated at once.
Template Parameters
TElement Type of elements of the field.
$A Igor Jan08 Mar09;
Definition at line 14 of file FieldGeneric.cs.
Constructor & Destructor Documentation
Field() [1/4]
IG.Num.Field< TElement >.Field () inline
Constructs a new empty field (no elements contained) with no name and no description.
Definition at line 18 of file FieldGeneric.cs.
Field() [2/4]
IG.Num.Field< TElement >.Field (int numElements) inline
Creates a new field with the specified number of elements.
Parameters
numElements Number of elements of teh field.
Definition at line 24 of file FieldGeneric.cs.
Field() [3/4]
IG.Num.Field< TElement >.Field (int numElements, string fieldName) inline
Constructs a new field with the specified number of elements and name.
Parameters
numElements Number of elements.
fieldName Name of the field.
Definition at line 31 of file FieldGeneric.cs.
Field() [4/4]
IG.Num.Field< TElement >.Field (int numElements, string fieldName, string fieldDescription) inline
Constructs a new field with the specified number of elements, name and description. Table of elements is allocated.
Parameters
numElements Number of elements.
fieldName Name of the field.
fieldDescription Field description.
Definition at line 41 of file FieldGeneric.cs.
Member Function Documentation
SetLength()
virtual void IG.Num.Field< TElement >.SetLength (int newLength) inline virtual
Sets the length of the current field to the specified value.
Parameters
newLength New length (number of elements) of the field.
Definition at line 101 of file FieldGeneric.cs.
GetValue()
TElement IG.Num.Field< TElement >.GetValue (int index) inline
Returns element of the field at the specified index.
Parameters
index Index for which field element is returned.
Definition at line 116 of file FieldGeneric.cs.
SetValue()
void IG.Num.Field< TElement >.SetValue (int index, TElement value) inline
Sets the element at the specified index to the specified value.
Parameters
index Indec of the element to be set.
value Value that is assigned to the specified element.
Definition at line 124 of file FieldGeneric.cs.
UpdateBounds() [1/3]
static void IG.Num.Field< TElement >.UpdateBounds (Field< double > field, IBoundingBox bounds, int componentIndex) inline static
Updates the specified component of the specified bounds (object of type IBoundingBox) in such a way that all elements of the specified field will fit within the bounds.
Call has no effect if the field is null. Bounding box object must be allocated and of the dimension greater that the specified coordinate index.
Parameters
field Field according to whose elements the bounds are updated.
bounds Bounding box object that is updated in such a way that all elements of the field fit in it.
componentIndex Index of component of bounding box that is updated.
Definition at line 139 of file FieldGeneric.cs.
UpdateBounds< TEl >()
static void IG.Num.Field< TElement >.UpdateBounds< TEl > (Field< TEl > field, IBoundingBox bounds) inline static
Updates the specified bounds (object of type IBoundingBox) in such a way that all non-null vectors on the specified field will fit within the bounds.
Call has no effect if the field is null. Bounding box object must be allocated and of the same dimension as elements of the field.
Template Parameters
TEl Type of elements of the field, must be IVector.
Parameters
field Field according to whose elements the bounds are updated.
bounds Bounding box object that is updated in such a way that all elements of the field fit in it.
Type Constraints
TEl : IVector
Definition at line 165 of file FieldGeneric.cs.
UpdateBounds() [2/3]
static void IG.Num.Field< TElement >.UpdateBounds (Field< vec3 > field, IBoundingBox bounds) inline static
Updates the specified bounds (object of type IBoundingBox) in such a way that all 3D vector elements of type vec3 of the specified field will fit within the bounds.
Call has no effect if the field is null. Bounding box object must be allocated and of dimension 3.
Parameters
field Field according to whose 3D vector elements the bounds are updated.
bounds Bounding box object that is updated in such a way that all elements of the field fit in it. Must be of dimension 3.
Definition at line 198 of file FieldGeneric.cs.
MapCoordinatesPlain() [1/2]
static void IG.Num.Field< TElement >.MapCoordinatesPlain (Field< vec3 > referenceField, Field< vec3 > targetField, IFunc3d fx, IFunc3d fy, IFunc3d fz) inline static
Generates coordinates of a set of unstructured 3D points (point cloud) from a reference set according to 3 scalar functions of 3 variables that map coordinates of the reference points to components of the mapped points.
Target field can be the same as the reference field (in this case vectors of the reference field are overwritten one by one).
Function can be used for transformation of any nodal vector values of a set of nodes, not just for transformation of coordinates.
This is plain version of the method that does not check consistency of dimension or existence of objects.
Parameters
referenceField Field containing reference coordinates that will be mapped to actual coordinates.
Dimensions must be set and array of vector values (coordinates) must be allocated before the function is called.
Parameters
targetField Field for which coordinates are generated.
Dimensions must be set and consistent with dimensions of the reference field, and array of vector values must be allocated before the function is called.
This parameter can be the same field as referenceField .
Parameters
fx Function that maps node coordinates of the reference grid to the first node coordinates of the actual grid.
fy Function that maps node coordinates of the reference grid to the second node coordinates of the actual grid.
fz Function that maps node coordinates of the reference grid to the third node coordinates of the actual grid.
Definition at line 237 of file FieldGeneric.cs.
Referenced by IG.Num.StructuredField3d< TCoord >.GenerateCoordinatesPlain(), IG.Num.Field< TCoord >.GenerateCoordinatesPlain(), IG.Num.StructuredField2d< TCoord >.GenerateCoordinatesPlain(), IG.Num.StructuredField2d< TCoord >.MapCoordinates(), IG.Num.Field< TCoord >.MapCoordinates(), IG.Num.StructuredField3d< TCoord >.MapCoordinates(), IG.Num.StructuredField2d< TCoord >.MapCoordinatesPlain(), and IG.Num.StructuredField3d< TCoord >.MapCoordinatesPlain().
MapCoordinates() [1/2]
static void IG.Num.Field< TElement >.MapCoordinates (Field< vec3 > referenceField, Field< vec3 > targetField, IFunc3d fx, IFunc3d fy, IFunc3d fz) inline static
Generates coordinates of a set of unstructured points (point cloud) from a reference set according to 3 scalar functions of 3 variables that map coordinates of the reference points to components of the mapped points.
Target field can be the same as the reference field (in this case vectors of the reference field are overwritten one by one).
Function can be used for transformation of any nodal vector values of a set of nodes, not just for transformation of coordinates.
Consistency of dimensions and existence of objects are checked and exceptions are thrown when checks fail.
Parameters
referenceField Field containing reference coordinates that will be mapped to actual coordinates.
Dimensions must be set and array of vector values (coordinates) must be allocated before the function is called.
Parameters
targetField Field for which coordinates are generated.
Dimensions must be set and consistent with dimensions of the reference field, and array of vector values must be allocated before the function is called.
This parameter can be the same field as referenceField .
Parameters
fx Function that maps node coordinates of the reference grid to the first node coordinates of the actual grid.
fy Function that maps node coordinates of the reference grid to the second node coordinates of the actual grid.
fz Function that maps node coordinates of the reference grid to the third node coordinates of the actual grid.
Definition at line 272 of file FieldGeneric.cs.
Referenced by IG.Num.Field< TCoord >.GenerateCoordinates().
MapCoordinates2dPlain()
static void IG.Num.Field< TElement >.MapCoordinates2dPlain (Field< vec3 > referenceField, Field< vec3 > targetField, IFunc2d fx, IFunc2d fy, IFunc2d fz) inline static
Generates coordinates of a set of unstructured 3D points (point cloud) from a reference set according to 3 scalar functions of 2 variables that map coordinates of the reference points to components of the mapped points. Mapping functions act only on the first two coordinates of each point.
This function is usually used for mapping coordinates of 2D structures embedded in 3D space.
Target field can be the same as the reference field (in this case vectors of the reference field are overwritten one by one).
Function can be used for transformation of any nodal vector values of a set of nodes, not just for transformation of coordinates.
This is plain version of the method that does not check consistency of dimension or existence of objects.
Parameters
referenceField Field containing reference coordinates that will be mapped to actual coordinates.
Dimensions must be set and array of vector values (coordinates) must be allocated before the function is called.
Parameters
targetField Field for which coordinates are generated.
Dimensions must be set and consistent with dimensions of the reference field, and array of vector values must be allocated before the function is called.
This parameter can be the same field as referenceField .
Parameters
fx Function that maps node coordinates of the reference grid to the first node coordinates of the actual grid.
fy Function that maps node coordinates of the reference grid to the second node coordinates of the actual grid.
fz Function that maps node coordinates of the reference grid to the third node coordinates of the actual grid.
Definition at line 307 of file FieldGeneric.cs.
Referenced by IG.Num.Field< TCoord >.GenerateCoordinates2dPlain(), and IG.Num.Field< TCoord >.MapCoordinates2d().
MapCoordinates2d()
static void IG.Num.Field< TElement >.MapCoordinates2d (Field< vec3 > referenceField, Field< vec3 > targetField, IFunc2d fx, IFunc2d fy, IFunc2d fz) inline static
Generates coordinates of a set of unstructured points (point cloud) from a reference set according to 3 scalar functions of 2 variables that map the first two coordinates of the reference points to components of the mapped points.
This function is usually used for mapping coordinates of 2D structures embedded in 3D space.
Target field can be the same as the reference field (in this case vectors of the reference field are overwritten one by one).
Function can be used for transformation of any nodal vector values of a set of nodes, not just for transformation of coordinates.
Consistency of dimensions and existence of objects are checked and exceptions are thrown when checks fail.
Parameters
referenceField Field containing reference coordinates that will be mapped to actual coordinates.
Dimensions must be set and array of vector values (coordinates) must be allocated before the function is called.
Parameters
targetField Field for which coordinates are generated.
Dimensions must be set and consistent with dimensions of the reference field, and array of vector values must be allocated before the function is called.
This parameter can be the same field as referenceField .
Parameters
fx Function that maps node coordinates of the reference grid to the first node coordinates of the actual grid.
fy Function that maps node coordinates of the reference grid to the second node coordinates of the actual grid.
fz Function that maps node coordinates of the reference grid to the third node coordinates of the actual grid.
Definition at line 343 of file FieldGeneric.cs.
Referenced by IG.Num.Field< TCoord >.GenerateCoordinates2d().
MapCoordinates1dPlain() [1/2]
static void IG.Num.Field< TElement >.MapCoordinates1dPlain (Field< vec3 > referenceField, Field< vec3 > targetField, IRealFunction fx, IRealFunction fy, IRealFunction fz) inline static
Generates coordinates of a set of unstructured 3D points (point cloud) from a reference set according to 3 functions of 1 variable that map the first coordinate of the reference points to components of the mapped points.
This function is usually used for mapping coordinates of 1D structures embedded in 3D space.
Target field can be the same as the reference field (in this case vectors of the reference field are overwritten one by one).
Function can be used for transformation of any nodal vector values of a set of nodes, not just for transformation of coordinates.
This is plain version of the method that does not check consistency of dimension or existence of objects.
Parameters
referenceField Field containing reference coordinates that will be mapped to actual coordinates.
Dimensions must be set and array of vector values (coordinates) must be allocated before the function is called.
Parameters
targetField Field for which coordinates are generated.
Dimensions must be set and consistent with dimensions of the reference field, and array of vector values must be allocated before the function is called.
This parameter can be the same field as referenceField .
Parameters
fx Function that maps node coordinates of the reference grid to the first node coordinates of the actual grid.
fy Function that maps node coordinates of the reference grid to the second node coordinates of the actual grid.
fz Function that maps node coordinates of the reference grid to the third node coordinates of the actual grid.
Definition at line 378 of file FieldGeneric.cs.
Referenced by IG.Num.Field< TCoord >.GenerateCoordinates1dPlain(), and IG.Num.Field< TCoord >.MapCoordinates1d().
MapCoordinates1d() [1/2]
static void IG.Num.Field< TElement >.MapCoordinates1d (Field< vec3 > referenceField, Field< vec3 > targetField, IRealFunction fx, IRealFunction fy, IRealFunction fz) inline static
Generates coordinates of a set of unstructured 3D points (point cloud) from a reference set according to 3 functions of 1 variable that map the first coordinate of the reference points to components of the mapped points.
This function is usually used for mapping coordinates of 1D structures embedded in 3D space.
Target field can be the same as the reference field (in this case vectors of the reference field are overwritten one by one).
Function can be used for transformation of any nodal vector values of a set of nodes, not just for transformation of coordinates.
Consistency of dimensions and existence of objects are checked and exceptions are thrown when checks fail.
Parameters
referenceField Field containing reference coordinates that will be mapped to actual coordinates.
Dimensions must be set and array of vector values (coordinates) must be allocated before the function is called.
Parameters
targetField Field for which coordinates are generated.
Dimensions must be set and consistent with dimensions of the reference field, and array of vector values must be allocated before the function is called.
This parameter can be the same field as referenceField .
Parameters
fx Function that maps node coordinates of the reference grid to the first node coordinates of the actual grid.
fy Function that maps node coordinates of the reference grid to the second node coordinates of the actual grid.
fz Function that maps node coordinates of the reference grid to the third node coordinates of the actual grid.
Definition at line 414 of file FieldGeneric.cs.
Referenced by IG.Num.Field< TCoord >.GenerateCoordinates1d().
MapCoordinatesToScalarsPlain() [1/2]
static void IG.Num.Field< TElement >.MapCoordinatesToScalarsPlain (Field< vec3 > referenceField, Field< double > targetScalarField, IFunc3d scalarMap) inline static
Generates scalar values for a 3D unstructured set fo points from the specified field of grid coordinates by a specified scalar function of 3 variables that maps coordinates to scalar values.
Function can be used for any mapping of nodal vector values to nodal scalar values of an unstructured grid, not just for mapping of coordinates.
This is plain version of the method that does not check consistency of dimension or existence of objects.
Parameters
referenceField Field containing coordinates that will be mapped to scalar values.
Dimensions must be set and array of vector values (coordinates) must be allocated before the function is called.
Parameters
targetScalarField Field in which the mapped scalars are stored.
Dimensions must be set and consistent with dimensions of the reference field, and array of values must be allocated before the function is called.
Parameters
scalarMap Function that maps node coordinates of the reference grid to scalar values of the target grid.
Definition at line 440 of file FieldGeneric.cs.
Referenced by IG.Num.StructuredField2d< TCoord >.MapCoordinatesToScalars(), IG.Num.Field< TCoord >.MapCoordinatesToScalars(), and IG.Num.StructuredField2d< TCoord >.MapCoordinatesToScalarsPlain().
MapCoordinatesToScalars() [1/2]
static void IG.Num.Field< TElement >.MapCoordinatesToScalars (Field< vec3 > referenceField, Field< double > targetScalarField, IFunc3d scalarMap) inline static
Generates scalar values for a 3D unstructured set fo points from the specified field of grid coordinates by a specified scalar function of 3 variables that maps coordinates to scalar values.
Function can be used for any mapping of nodal vector values to nodal scalar values of an unstructured grid, not just for mapping of coordinates.
Consistency of dimensions and existence of objects are checked and exceptions are thrown when checks fail.
Parameters
referenceField Field containing coordinates that will be mapped to scalar values.
Dimensions must be set and array of vector values (coordinates) must be allocated before the function is called.
Parameters
targetScalarField Field in which the mapped scalars are stored.
Dimensions must be set and consistent with dimensions of the reference field, and array of values must be allocated before the function is called.
Parameters
scalarMap Function that maps node coordinates of the reference grid to scalar values of the target grid.
Definition at line 465 of file FieldGeneric.cs.
Referenced by IG.Num.StructuredField3d< TCoord >.MapCoordinatesToScalars(), and IG.Num.StructuredField3d< TCoord >.MapCoordinatesToScalarsPlain().
GenerateCoordinatesPlain() [1/4]
static void IG.Num.Field< TElement >.GenerateCoordinatesPlain (Field< vec3 > field, int dimx, int dimy, int dimz, double minxRef, double maxxRef, double minyRef, double maxyRef, double minzRef, double maxzRef) inline static
Generates coordinates of a 3D unstructured grid from a regular grid with grid directions parallel to coordinate axes and equidistantly arranged nodes in all directions.
This is plain version of the method that does not check consistency of dimension or existence of objects.
Parameters
field Field for which coordinates are generated. Dimensions must be set and array of vector values allocated before this function is called.
dimx Number of nodes in x direction.
dimy Number of nodes in y direction.
dimz Number of nodes in z direction.
minxRef Minimal value of x coordinate of the generated grid.
maxxRef Maximal value of x coordinate of the generated grid.
minyRef Minimal value of y coordinate of the generated grid.
maxyRef Maximal value of y coordinate of the generated grid.
minzRef Minimal value of z coordinate of the generated grid.
maxzRef Maximal value of z coordinate of the generated grid.
Definition at line 496 of file FieldGeneric.cs.
Referenced by IG.Num.UnstructuredMesh2d< TCoord, TIndexField, TIndex, TScalarField, TScalar, TVectorField, TVector, TTensorField, TTensor >.GenerateCoordinates(), IG.Num.UnstructuredMesh3d< TCoord, TIndexField, TIndex, TScalarField, TScalar, TVectorField, TVector, TTensorField, TTensor >.GenerateCoordinates(), IG.Num.Field< TCoord >.GenerateCoordinates(), IG.Num.Field< TCoord >.GenerateCoordinatesPlain(), IG.Num.UnstructuredMesh2d< TCoord, TIndexField, TIndex, TScalarField, TScalar, TVectorField, TVector, TTensorField, TTensor >.UnstructuredMesh2d(), and IG.Num.UnstructuredMesh3d< TCoord, TIndexField, TIndex, TScalarField, TScalar, TVectorField, TVector, TTensorField, TTensor >.UnstructuredMesh3d().
GenerateCoordinates() [1/5]
static void IG.Num.Field< TElement >.GenerateCoordinates (Field< vec3 > field, int dimx, int dimy, int dimz, double minxRef, double maxxRef, double minyRef, double maxyRef, double minzRef, double maxzRef) inline static
Generates coordinates of a 3D unstructured grid from a regular grid with grid directions parallel to coordinate axes and equidistantly arranged nodes in all directions.
Consistency of dimensions and existence of objects are checked and exceptions are thrown when checks fail.
Parameters
field Field for which coordinates are generated. Dimensions must be set and array of vector values allocated before this function is called.
dimx Number of nodes in x direction.
dimy Number of nodes in y direction.
dimz Number of nodes in z direction.
minxRef Minimal value of x coordinate of the generated grid.
maxxRef Maximal value of x coordinate of the generated grid.
minyRef Minimal value of y coordinate of the generated grid.
maxyRef Maximal value of y coordinate of the generated grid.
minzRef Minimal value of z coordinate of the generated grid.
maxzRef Maximal value of z coordinate of the generated grid.
Definition at line 537 of file FieldGeneric.cs.
Referenced by IG.Num.Field< TCoord >.GenerateCoordinates().
GenerateCoordinatesPlain() [2/4]
static void IG.Num.Field< TElement >.GenerateCoordinatesPlain (Field< vec3 > field, int dimx, int dimy, int dimz, double minxRef, double maxxRef, double minyRef, double maxyRef, double minzRef, double maxzRef, IFunc3d fx, IFunc3d fy, IFunc3d fz) inline static
Generates coordinates of a 3D unstructured grid of a parametric volume according to functions specifying the x, y, and z coordinates in terms of three scalar functions of 3 variables.
Coordinates are obtained by transforming individual coordinates of a regular equidistant grid from the reference system.
.
Numbers of nodes in each grid directions are specified by current dimensions of the grid.
This is plain version of the method that does not check consistency of dimension or existence of objects.
Parameters
field Field for which coordinates are generated. Dimensions must be set and array of vector values allocated before this function is called.
dimx Number of nodes in x direction.
dimy Number of nodes in y direction.
dimz Number of nodes in z direction.
minxRef Lower bound for the first parameter in the reference coordinate system.
maxxRef Upper bound for the first parameter in the reference coordinate system.
minyRef Lower bound for the second parameter in the reference coordinate system.
maxyRef Upper bound for the second parameter in the reference coordinate system.
minzRef Lower bound for the third parameter in the reference coordinate system.
maxzRef Upper bound for the third parameter in the reference coordinate system.
fx Function that maps node coordinates of the reference grid to the first node coordinates' component of the actual grid.
fy Function that maps node coordinates of the reference grid to the second node coordinates' component of the actual grid.
fz Function that maps node coordinates of the reference grid to the third node coordinates' component of the actual grid.
Definition at line 579 of file FieldGeneric.cs.
GenerateCoordinates() [2/5]
static void IG.Num.Field< TElement >.GenerateCoordinates (Field< vec3 > field, int dimx, int dimy, int dimz, double minxRef, double maxxRef, double minyRef, double maxyRef, double minzRef, double maxzRef, IFunc3d fx, IFunc3d fy, IFunc3d fz) inline static
Generates coordinates of a 3D unstructured grid of a parametric volume according to functions specifying the x, y, and z coordinates in terms of three scalar functions of 3 variables.
Coordinates are obtained by transforming individual coordinates of a regular equidistant grid from the reference system.
.
Numbers of nodes in each grid directions are specified by current dimensions of the grid.
Consistency of dimensions and existence of objects are checked and exceptions are thrown when checks fail.
Parameters
field Field for which coordinates are generated. Dimensions must be set and array of vector values allocated before this function is called.
dimx Number of nodes in x direction.
dimy Number of nodes in y direction.
dimz Number of nodes in z direction.
minxRef Lower bound for the first parameter in the reference coordinate system.
maxxRef Upper bound for the first parameter in the reference coordinate system.
minyRef Lower bound for the second parameter in the reference coordinate system.
maxyRef Upper bound for the second parameter in the reference coordinate system.
minzRef Lower bound for the third parameter in the reference coordinate system.
maxzRef Upper bound for the third parameter in the reference coordinate system.
fx Function that maps node coordinates of the reference grid to the first node coordinates' component of the actual grid.
fy Function that maps node coordinates of the reference grid to the second node coordinates' component of the actual grid.
fz Function that maps node coordinates of the reference grid to the third node coordinates' component of the actual grid.
Definition at line 613 of file FieldGeneric.cs.
UpdateBounds() [3/3]
static void IG.Num.Field< TElement >.UpdateBounds (Field< vec2 > field, IBoundingBox bounds) inline static
Updates the specified bounds (object of type IBoundingBox) in such a way that all 2D vector elements of type vec2 of the specified field will fit within the bounds.
Call has no effect if the field is null. Bounding box object must be allocated and of dimension 3.
Parameters
field Field according to whose 2D vector elements the bounds are updated.
bounds Bounding box object that is updated in such a way that all elements of the field fit in it. Must be of dimension 2.
Definition at line 635 of file FieldGeneric.cs.
MapCoordinatesPlain() [2/2]
static void IG.Num.Field< TElement >.MapCoordinatesPlain (Field< vec2 > referenceField, Field< vec2 > targetField, IFunc2d fx, IFunc2d fy) inline static
Generates coordinates of a set of unstructured 3D points (point cloud) from a reference set according to 2 scalar functions of 2 variables that map coordinates of the reference points to components of the mapped points.
Target field can be the same as the reference field (in this case vectors of the reference field are overwritten one by one).
Function can be used for transformation of any nodal vector values of a set of nodes, not just for transformation of coordinates.
This is plain version of the method that does not check consistency of dimension or existence of objects.
Parameters
referenceField Field containing reference coordinates that will be mapped to actual coordinates.
Dimensions must be set and array of vector values (coordinates) must be allocated before the function is called.
Parameters
targetField Field for which coordinates are generated.
Dimensions must be set and consistent with dimensions of the reference field, and array of vector values must be allocated before the function is called.
This parameter can be the same field as referenceField .
Parameters
fx Function that maps node coordinates of the reference grid to the first node coordinates of the actual grid.
fy Function that maps node coordinates of the reference grid to the second node coordinates of the actual grid.
Definition at line 671 of file FieldGeneric.cs.
MapCoordinates() [2/2]
static void IG.Num.Field< TElement >.MapCoordinates (Field< vec2 > referenceField, Field< vec2 > targetField, IFunc2d fx, IFunc2d fy) inline static
Generates coordinates of a set of unstructured points (point cloud) from a reference set according to 2 scalar functions of 2 variables that map coordinates of the reference points to components of the mapped points.
Target field can be the same as the reference field (in this case vectors of the reference field are overwritten one by one).
Function can be used for transformation of any nodal vector values of a set of nodes, not just for transformation of coordinates.
Consistency of dimensions and existence of objects are checked and exceptions are thrown when checks fail.
Parameters
referenceField Field containing reference coordinates that will be mapped to actual coordinates.
Dimensions must be set and array of vector values (coordinates) must be allocated before the function is called.
Parameters
targetField Field for which coordinates are generated.
Dimensions must be set and consistent with dimensions of the reference field, and array of vector values must be allocated before the function is called.
This parameter can be the same field as referenceField .
Parameters
fx Function that maps node coordinates of the reference grid to the first node coordinates of the actual grid.
fy Function that maps node coordinates of the reference grid to the second node coordinates of the actual grid.
Definition at line 703 of file FieldGeneric.cs.
MapCoordinates1dPlain() [2/2]
static void IG.Num.Field< TElement >.MapCoordinates1dPlain (Field< vec2 > referenceField, Field< vec2 > targetField, IRealFunction fx, IRealFunction fy) inline static
Generates coordinates of a set of unstructured 2D points (point cloud) from a reference set according to 2 functions of 1 variables that map the first coordinate of the reference points to components of the mapped points.
This function is usually used for mapping coordinates of 2D structures embedded in 3D.
Target field can be the same as the reference field (in this case vectors of the reference field are overwritten one by one).
Function can be used for transformation of any nodal vector values of a set of nodes, not just for transformation of coordinates.
This is plain version of the method that does not check consistency of dimension or existence of objects.
Parameters
referenceField Field containing reference coordinates that will be mapped to actual coordinates.
Dimensions must be set and array of vector values (coordinates) must be allocated before the function is called.
Parameters
targetField Field for which coordinates are generated.
Dimensions must be set and consistent with dimensions of the reference field, and array of vector values must be allocated before the function is called.
This parameter can be the same field as referenceField .
Parameters
fx Function that maps node coordinates of the reference grid to the first node coordinates of the actual grid.
fy Function that maps node coordinates of the reference grid to the second node coordinates of the actual grid.
Definition at line 736 of file FieldGeneric.cs.
MapCoordinates1d() [2/2]
static void IG.Num.Field< TElement >.MapCoordinates1d (Field< vec2 > referenceField, Field< vec2 > targetField, IRealFunction fx, IRealFunction fy) inline static
Generates coordinates of a set of unstructured 2D points (point cloud) from a reference set according to 2 functions of 1 variables that map the first coordinate of the reference points to components of the mapped points.
This function is usually used for mapping coordinates of 2D structures embedded in 3D.
Target field can be the same as the reference field (in this case vectors of the reference field are overwritten one by one).
Function can be used for transformation of any nodal vector values of a set of nodes, not just for transformation of coordinates.
Consistency of dimensions and existence of objects are checked and exceptions are thrown when checks fail.
Parameters
referenceField Field containing reference coordinates that will be mapped to actual coordinates.
Dimensions must be set and array of vector values (coordinates) must be allocated before the function is called.
Parameters
targetField Field for which coordinates are generated.
Dimensions must be set and consistent with dimensions of the reference field, and array of vector values must be allocated before the function is called.
This parameter can be the same field as referenceField .
Parameters
fx Function that maps node coordinates of the reference grid to the first node coordinates of the actual grid.
fy Function that maps node coordinates of the reference grid to the second node coordinates of the actual grid.
Definition at line 770 of file FieldGeneric.cs.
MapCoordinatesToScalarsPlain() [2/2]
static void IG.Num.Field< TElement >.MapCoordinatesToScalarsPlain (Field< vec2 > referenceField, Field< double > targetScalarField, IFunc2d scalarMap) inline static
Generates scalar values for a 2D unstructured set fo points from the specified field of grid coordinates by a specified scalar function of 2 variables that maps coordinates to scalar values.
Function can be used for any mapping of nodal vector values to nodal scalar values of an unstructured set of nodes, not just for mapping of coordinates.
This is plain version of the method that does not check consistency of dimension or existence of objects.
Parameters
referenceField Field containing coordinates that will be mapped to scalar values.
Dimensions must be set and array of vector values (coordinates) must be allocated before the function is called.
Parameters
targetScalarField Field in which the mapped scalars are stored.
Dimensions must be set and consistent with dimensions of the reference field, and array of values must be allocated before the function is called.
Parameters
scalarMap Function that maps node coordinates of the reference grid to scalar values of the target grid.
Definition at line 797 of file FieldGeneric.cs.
MapCoordinatesToScalars() [2/2]
static void IG.Num.Field< TElement >.MapCoordinatesToScalars (Field< vec2 > referenceField, Field< double > targetScalarField, IFunc2d scalarMap) inline static
Generates scalar values for a 2D unstructured set fo points from the specified field of grid coordinates by a specified scalar function of 2 variables that maps coordinates to scalar values.
Function can be used for any mapping of nodal vector values to nodal scalar values of an unstructured set of nodes, not just for mapping of coordinates.
Consistency of dimensions and existence of objects are checked and exceptions are thrown when checks fail.
Parameters
referenceField Field containing coordinates that will be mapped to scalar values.
Dimensions must be set and array of vector values (coordinates) must be allocated before the function is called.
Parameters
targetScalarField Field in which the mapped scalars are stored.
Dimensions must be set and consistent with dimensions of the reference field, and array of values must be allocated before the function is called.
Parameters
scalarMap Function that maps node coordinates of the reference grid to scalar values of the target grid.
Definition at line 822 of file FieldGeneric.cs.
GenerateCoordinatesPlain() [3/4]
static void IG.Num.Field< TElement >.GenerateCoordinatesPlain (Field< vec2 > field, int dimx, int dimy, double minxRef, double maxxRef, double minyRef, double maxyRef) inline static
Generates coordinates of a 3D unstructured grid from a regular grid with grid directions parallel to coordinate axes and equidistantly arranged nodes in all directions.
This is plain version of the method that does not check consistency of dimension or existence of objects.
Parameters
field Field for which coordinates are generated. Dimensions must be set and array of vector values allocated before this function is called.
dimx Number of nodes in x direction.
dimy Number of nodes in y direction.
minxRef Minimal value of x coordinate of the generated grid.
maxxRef Maximal value of x coordinate of the generated grid.
minyRef Minimal value of y coordinate of the generated grid.
maxyRef Maximal value of y coordinate of the generated grid.
Definition at line 851 of file FieldGeneric.cs.
GenerateCoordinates() [3/5]
static void IG.Num.Field< TElement >.GenerateCoordinates (Field< vec2 > field, int dimx, int dimy, double minxRef, double maxxRef, double minyRef, double maxyRef) inline static
Generates coordinates of a 3D unstructured grid from a regular grid with grid directions parallel to coordinate axes and equidistantly arranged nodes in all directions.
Consistency of dimensions and existence of objects are checked and exceptions are thrown when checks fail.
Parameters
field Field for which coordinates are generated. Dimensions must be set and array of vector values allocated before this function is called.
dimx Number of nodes in x direction.
dimy Number of nodes in y direction.
minxRef Minimal value of x coordinate of the generated grid.
maxxRef Maximal value of x coordinate of the generated grid.
minyRef Minimal value of y coordinate of the generated grid.
maxyRef Maximal value of y coordinate of the generated grid.
Definition at line 883 of file FieldGeneric.cs.
GenerateCoordinatesPlain() [4/4]
static void IG.Num.Field< TElement >.GenerateCoordinatesPlain (Field< vec2 > field, int dimx, int dimy, double minxRef, double maxxRef, double minyRef, double maxyRef, IFunc2d fx, IFunc2d fy) inline static
Generates coordinates of a 3D unstructured grid of a parametric volume according to functions specifying the x, y, and z coordinates in terms of three scalar functions of 3 variables.
Coordinates are obtained by transforming individual coordinates of a regular equidistant grid from the reference system.
.
Numbers of nodes in each grid directions are specified by current dimensions of the grid.
This is plain version of the method that does not check consistency of dimension or existence of objects.
Parameters
field Field for which coordinates are generated. Dimensions must be set and array of vector values allocated before this function is called.
dimx Number of nodes in x direction.
dimy Number of nodes in y direction.
minxRef Lower bound for the first parameter in the reference coordinate system.
maxxRef Upper bound for the first parameter in the reference coordinate system.
minyRef Lower bound for the second parameter in the reference coordinate system.
maxyRef Upper bound for the second parameter in the reference coordinate system.
fx Function that maps node coordinates of the reference grid to the first node coordinates' component of the actual grid.
fy Function that maps node coordinates of the reference grid to the second node coordinates' component of the actual grid.
Definition at line 918 of file FieldGeneric.cs.
GenerateCoordinates() [4/5]
static void IG.Num.Field< TElement >.GenerateCoordinates (Field< vec2 > field, int dimx, int dimy, double minxRef, double maxxRef, double minyRef, double maxyRef, IFunc2d fx, IFunc2d fy) inline static
Generates coordinates of a 3D unstructured grid of a parametric volume according to functions specifying the x, y, and z coordinates in terms of three scalar functions of 3 variables.
Coordinates are obtained by transforming individual coordinates of a regular equidistant grid from the reference system.
.
Numbers of nodes in each grid directions are specified by current dimensions of the grid.
Consistency of dimensions and existence of objects are checked and exceptions are thrown when checks fail.
Parameters
field Field for which coordinates are generated. Dimensions must be set and array of vector values allocated before this function is called.
dimx Number of nodes in x direction.
dimy Number of nodes in y direction.
minxRef Lower bound for the first parameter in the reference coordinate system.
maxxRef Upper bound for the first parameter in the reference coordinate system.
minyRef Lower bound for the second parameter in the reference coordinate system.
maxyRef Upper bound for the second parameter in the reference coordinate system.
fx Function that maps node coordinates of the reference grid to the first node coordinates' component of the actual grid.
fy Function that maps node coordinates of the reference grid to the second node coordinates' component of the actual grid.
Definition at line 946 of file FieldGeneric.cs.
GenerateCoordinates2dPlain() [1/2]
static void IG.Num.Field< TElement >.GenerateCoordinates2dPlain (Field< vec3 > field, int dimx, int dimy, double minxRef, double maxxRef, double minyRef, double maxyRef) inline static
Generates coordinates of a 2D unstructured grid embedded in 3D from a regular grid with grid directions parallel to the first two coordinate axes and equidistantly arranged nodes in all directions.
This is plain version of the method that does not check consistency of dimension or existence of objects.
Parameters
field Field for which coordinates are generated. Dimensions must be set and array of vector values allocated before this function is called.
dimx Number of nodes in x direction.
dimy Number of nodes in y direction.
minxRef Minimal value of x coordinate of the generated grid.
maxxRef Maximal value of x coordinate of the generated grid.
minyRef Minimal value of y coordinate of the generated grid.
maxyRef Maximal value of y coordinate of the generated grid.
Definition at line 972 of file FieldGeneric.cs.
Referenced by IG.Num.Field< TCoord >.GenerateCoordinates2d(), and IG.Num.Field< TCoord >.GenerateCoordinates2dPlain().
GenerateCoordinates2d() [1/2]
static void IG.Num.Field< TElement >.GenerateCoordinates2d (Field< vec3 > field, int dimx, int dimy, double minxRef, double maxxRef, double minyRef, double maxyRef) inline static
Generates coordinates of a 2D unstructured grid embedded in 3D from a regular grid with grid directions parallel to the first two coordinate axes and equidistantly arranged nodes in all directions.
Consistency of dimensions and existence of objects are checked and exceptions are thrown when checks fail.
Parameters
field Field for which coordinates are generated. Dimensions must be set and array of vector values allocated before this function is called.
dimx Number of nodes in x direction.
dimy Number of nodes in y direction.
minxRef Minimal value of x coordinate of the generated grid.
maxxRef Maximal value of x coordinate of the generated grid.
minyRef Minimal value of y coordinate of the generated grid.
maxyRef Maximal value of y coordinate of the generated grid.
Definition at line 1005 of file FieldGeneric.cs.
Referenced by IG.Num.Field< TCoord >.GenerateCoordinates2d().
GenerateCoordinates2dPlain() [2/2]
static void IG.Num.Field< TElement >.GenerateCoordinates2dPlain (Field< vec3 > field, int dimx, int dimy, double minxRef, double maxxRef, double minyRef, double maxyRef, IFunc2d fx, IFunc2d fy, IFunc2d fz) inline static
Generates coordinates of a 3D unstructured grid of a parametric volume according to functions specifying the x, y, and z coordinates in terms of three scalar functions of 3 variables.
Coordinates are obtained by transforming individual coordinates of a regular equidistant grid from the reference system.
.
Numbers of nodes in each grid directions are specified by current dimensions of the grid.
This is plain version of the method that does not check consistency of dimension or existence of objects.
Parameters
field Field for which coordinates are generated. Dimensions must be set and array of vector values allocated before this function is called.
dimx Number of nodes in x direction.
dimy Number of nodes in y direction.
minxRef Lower bound for the first parameter in the reference coordinate system.
maxxRef Upper bound for the first parameter in the reference coordinate system.
minyRef Lower bound for the second parameter in the reference coordinate system.
maxyRef Upper bound for the second parameter in the reference coordinate system.
fx Function that maps node coordinates of the reference grid to the first node coordinates' component of the actual grid.
fy Function that maps node coordinates of the reference grid to the second node coordinates' component of the actual grid.
fz Function that maps node coordinates of the reference grid to the third node coordinates' component of the actual grid.
Definition at line 1042 of file FieldGeneric.cs.
GenerateCoordinates2d() [2/2]
static void IG.Num.Field< TElement >.GenerateCoordinates2d (Field< vec3 > field, int dimx, int dimy, double minxRef, double maxxRef, double minyRef, double maxyRef, IFunc2d fx, IFunc2d fy, IFunc2d fz) inline static
Generates coordinates of a 3D unstructured grid of a parametric volume according to functions specifying the x, y, and z coordinates in terms of three scalar functions of 3 variables.
Coordinates are obtained by transforming individual coordinates of a regular equidistant grid from the reference system.
Numbers of nodes in each grid directions are specified by current dimensions of the grid.
Consistency of dimensions and existence of objects are checked and exceptions are thrown when checks fail.
Parameters
field Field for which coordinates are generated. Dimensions must be set and array of vector values allocated before this function is called.
dimx Number of nodes in x direction.
dimy Number of nodes in y direction.
minxRef Lower bound for the first parameter in the reference coordinate system.
maxxRef Upper bound for the first parameter in the reference coordinate system.
minyRef Lower bound for the second parameter in the reference coordinate system.
maxyRef Upper bound for the second parameter in the reference coordinate system.
fx Function that maps node coordinates of the reference grid to the first node coordinates' component of the actual grid.
fy Function that maps node coordinates of the reference grid to the second node coordinates' component of the actual grid.
fz Function that maps node coordinates of the reference grid to the third node coordinates' component of the actual grid.
Definition at line 1072 of file FieldGeneric.cs.
GenerateCoordinates1dPlain() [1/4]
static void IG.Num.Field< TElement >.GenerateCoordinates1dPlain (Field< vec3 > field, int dimx, double minxRef, double maxxRef) inline static
Generates coordinates of a 1D unstructured grid from a regular grid with grid direction parallel to X coordinate axes and equidistantly arranged nodes.
This is plain version of the method that does not check consistency of dimension or existence of objects.
Parameters
field Field for which coordinates are generated. Dimensions must be set and array of vector values allocated before this function is called.
dimx Number of nodes in x direction.
minxRef Minimal value of x coordinate of the generated grid.
maxxRef Maximal value of x coordinate of the generated grid.
Definition at line 1095 of file FieldGeneric.cs.
Referenced by IG.Num.UnstructuredMesh1d2d.GenerateCoordinates(), IG.Num.UnstructuredMesh1d3d.GenerateCoordinates(), IG.Num.Field< TCoord >.GenerateCoordinates(), IG.Num.Field< TCoord >.GenerateCoordinates1d(), IG.Num.Field< TCoord >.GenerateCoordinates1dPlain(), IG.Num.UnstructuredMesh1d2d.UnstructuredMesh1d2d(), and IG.Num.UnstructuredMesh1d3d.UnstructuredMesh1d3d().
GenerateCoordinates1d() [1/3]
static void IG.Num.Field< TElement >.GenerateCoordinates1d (Field< vec3 > field, int dimx, double minxRef, double maxxRef) inline static
Generates coordinates of a 1D unstructured grid from a regular grid with grid direction parallel to X coordinate axis and equidistantly arranged nodes.
Consistency of dimensions and existence of objects are checked and exceptions are thrown when checks fail.
Parameters
field Field for which coordinates are generated. Dimensions must be set and array of vector values allocated before this function is called.
dimx Number of nodes in x direction.
minxRef Minimal value of x coordinate of the generated grid.
maxxRef Maximal value of x coordinate of the generated grid.
Definition at line 1120 of file FieldGeneric.cs.
Referenced by IG.Num.Field< TCoord >.GenerateCoordinates1d().
GenerateCoordinates1dPlain() [2/4]
static void IG.Num.Field< TElement >.GenerateCoordinates1dPlain (Field< vec3 > field, int dimx, double minxRef, double maxxRef, IRealFunction fx, IRealFunction fy, IRealFunction fz) inline static
Generates coordinates of a 1D unstructured grid of a parametric curve according to functions specifying the x, y, and z coordinates in terms of three functions of 1 variable.
Coordinates are obtained by transforming individual coordinates of a regular equidistant grid from the reference system.
.
Numbers of nodes in each grid directions are specified by current dimensions of the grid.
This is plain version of the method that does not check consistency of dimension or existence of objects.
Parameters
field Field for which coordinates are generated. Dimensions must be set and array of vector values allocated before this function is called.
dimx Number of nodes in x direction.
minxRef Lower bound for the first parameter in the reference coordinate system.
maxxRef Upper bound for the first parameter in the reference coordinate system.
fx Function that maps node coordinates of the reference grid to the first node coordinates' component of the actual grid.
fy Function that maps node coordinates of the reference grid to the second node coordinates' component of the actual grid.
fz Function that maps node coordinates of the reference grid to the third node coordinates' component of the actual grid.
Definition at line 1154 of file FieldGeneric.cs.
GenerateCoordinates1d() [2/3]
static void IG.Num.Field< TElement >.GenerateCoordinates1d (Field< vec3 > field, int dimx, double minxRef, double maxxRef, IRealFunction fx, IRealFunction fy, IRealFunction fz) inline static
Generates coordinates of a 1D unstructured grid of a parametric curve according to functions specifying the x, y, and z coordinates in terms of three functions of 1 variables.
Coordinates are obtained by transforming individual coordinates of a regular equidistant grid from the reference system.
.
Numbers of nodes in each grid directions are specified by current dimensions of the grid.
Consistency of dimensions and existence of objects are checked and exceptions are thrown when checks fail.
Parameters
field Field for which coordinates are generated. Dimensions must be set and array of vector values allocated before this function is called.
dimx Number of nodes in x direction.
minxRef Lower bound for the first parameter in the reference coordinate system.
maxxRef Upper bound for the first parameter in the reference coordinate system.
fx Function that maps node coordinates of the reference grid to the first node coordinates' component of the actual grid.
fy Function that maps node coordinates of the reference grid to the second node coordinates' component of the actual grid.
fz Function that maps node coordinates of the reference grid to the third node coordinates' component of the actual grid.
Definition at line 1181 of file FieldGeneric.cs.
GenerateCoordinates1dPlain() [3/4]
static void IG.Num.Field< TElement >.GenerateCoordinates1dPlain (Field< vec2 > field, int dimx, double minxRef, double maxxRef) inline static
Generates coordinates of a 1D unstructured grid embedded in 2D space from a regular grid with grid direction parallel to X coordinate axes and equidistantly arranged nodes.
This is plain version of the method that does not check consistency of dimension or existence of objects.
Parameters
field Field for which coordinates are generated. Dimensions must be set and array of vector values allocated before this function is called.
dimx Number of nodes in x direction.
minxRef Minimal value of x coordinate of the generated grid.
maxxRef Maximal value of x coordinate of the generated grid.
Definition at line 1205 of file FieldGeneric.cs.
GenerateCoordinates() [5/5]
static void IG.Num.Field< TElement >.GenerateCoordinates (Field< vec2 > field, int dimx, double minxRef, double maxxRef) inline static
Generates coordinates of a 1D unstructured grid embedded in 2D space from a regular grid with grid direction parallel to X coordinate axis and equidistantly arranged nodes.
Consistency of dimensions and existence of objects are checked and exceptions are thrown when checks fail.
Parameters
field Field for which coordinates are generated. Dimensions must be set and array of vector values allocated before this function is called.
dimx Number of nodes in x direction.
minxRef Minimal value of x coordinate of the generated grid.
maxxRef Minimal value of x coordinate of the generated grid.
Definition at line 1230 of file FieldGeneric.cs.
GenerateCoordinates1dPlain() [4/4]
static void IG.Num.Field< TElement >.GenerateCoordinates1dPlain (Field< vec2 > field, int dimx, double minxRef, double maxxRef, IRealFunction fx, IRealFunction fy) inline static
Generates coordinates of a 1D unstructured grid embedded in 2D space of a parametric curve according to functions specifying the x, and y coordinates in terms of 2 functions of 1 variable.
Coordinates are obtained by transforming individual coordinates of a regular equidistant grid from the reference system.
.
Numbers of nodes in each grid directions are specified by current dimensions of the grid.
This is plain version of the method that does not check consistency of dimension or existence of objects.
Parameters
field Field for which coordinates are generated. Dimensions must be set and array of vector values allocated before this function is called.
dimx Number of nodes in x direction.
minxRef Lower bound for the first parameter in the reference coordinate system.
maxxRef Upper bound for the first parameter in the reference coordinate system.
fx Function that maps node coordinates of the reference grid to the first node coordinates' component of the actual grid.
fy Function that maps node coordinates of the reference grid to the second node coordinates' component of the actual grid.
Definition at line 1260 of file FieldGeneric.cs.
GenerateCoordinates1d() [3/3]
static void IG.Num.Field< TElement >.GenerateCoordinates1d (Field< vec2 > field, int dimx, double minxRef, double maxxRef, IRealFunction fx, IRealFunction fy) inline static
Generates coordinates of a 1D unstructured grid embedded in 2D space of a parametric curve according to functions specifying the x, and y coordinates in terms of 2 functions of 1 variable.
Coordinates are obtained by transforming individual coordinates of a regular equidistant grid from the reference system.
.
Numbers of nodes in each grid directions are specified by current dimensions of the grid.
Consistency of dimensions and existence of objects are checked and exceptions are thrown when checks fail.
Parameters
field Field for which coordinates are generated. Dimensions must be set and array of vector values allocated before this function is called.
dimx Number of nodes in x direction.
minxRef Lower bound for the first parameter in the reference coordinate system.
maxxRef Upper bound for the first parameter in the reference coordinate system.
fx Function that maps node coordinates of the reference grid to the first node coordinates' component of the actual grid.
fy Function that maps node coordinates of the reference grid to the second node coordinates' component of the actual grid.
Definition at line 1285 of file FieldGeneric.cs.
Example()
static void IG.Num.Field< TElement >.Example () inline static
Definition at line 1301 of file FieldGeneric.cs.
Member Data Documentation
_name
string IG.Num.Field< TElement >._name private
Definition at line 48 of file FieldGeneric.cs.
_description
string IG.Num.Field< TElement >._description private
Definition at line 57 of file FieldGeneric.cs.
_values
TElement [] IG.Num.Field< TElement >._values protected
Definition at line 66 of file FieldGeneric.cs.
Referenced by IG.Num.Field< TCoord >.GetValue(), and IG.Num.Field< TCoord >.SetValue().
_length
int IG.Num.Field< TElement >._length private
Definition at line 82 of file FieldGeneric.cs.
Property Documentation
Name
string IG.Num.Field< TElement >.Name get set
Name of the field.
Definition at line 52 of file FieldGeneric.cs.
Referenced by IG.Num.Field< TCoord >.Field().
Description
string IG.Num.Field< TElement >.Description get set
Description of the field.
Definition at line 61 of file FieldGeneric.cs.
Referenced by IG.Num.Field< TCoord >.Field().
Values
virtual TElement [] IG.Num.Field< TElement >.Values get protected set
Array of field values.
Definition at line 70 of file FieldGeneric.cs.
Referenced by IG.Num.Field< TCoord >.Field().
Length
int IG.Num.Field< TElement >.Length get protected set
Number of elements.
Definition at line 86 of file FieldGeneric.cs.
Referenced by IG.Num.Field< TCoord >.GenerateCoordinates1d(), IG.Num.Field< TCoord >.MapCoordinates(), IG.Num.Field< TCoord >.MapCoordinates1d(), IG.Num.Field< TCoord >.MapCoordinates1dPlain(), IG.Num.Field< TCoord >.MapCoordinates2d(), IG.Num.Field< TCoord >.MapCoordinates2dPlain(), IG.Num.Field< TCoord >.MapCoordinatesPlain(), IG.Num.Field< TCoord >.MapCoordinatesToScalars(), IG.Num.Field< TCoord >.MapCoordinatesToScalarsPlain(), IG.Num.StructuredField2d< TCoord >.SetDimensions(), IG.Num.StructuredField3d< TCoord >.SetDimensions(), IG.Num.Field< TCoord >.SetLength(), and IG.Num.Field< TCoord >.UpdateBounds().
this[int index]
TElement IG.Num.Field< TElement >.this[int index] get set
Access to elements through element index.
Parameters
index Index running from 0 to Length
Definition at line 109 of file FieldGeneric.cs.
The documentation for this class was generated from the following file:
iglib/igbase/numeric/geometry/meshing/FieldGeneric.cs