Doc: IGLib with source files: IG.Lib.RegisterableExamples.ExampleIRegistrable Class Reference
IG.Lib.RegisterableExamples.ExampleIRegistrable Class Reference
Example implementation of IIdentifiable interface.
Public Member Functions
ExampleIRegistrable (string str)
void Register ()
Registers the current object. Subsequent calls (after the first one) have no effect.
bool IsRegistered ()
Returns true if the current object is registered, false if not.
void Unregister ()
Unregisters the current object if it is currently registered. Can be performed several times, in this case only the first call may have effect.
override string ToString ()
Public Member Functions inherited from IG.Lib.IRegisterable< ExampleIRegistrable >
void Register ()
Registers the current object. Subsequent calls (after the first one) have no effect.
bool IsRegistered ()
Returns true if the current object is registered, false if not.
void Unregister ()
Unregisters the current object if it is currently registered. Can be performed several times, in this case only the first call may have effect.
Protected Attributes
string _msg
Properties
virtual int Id [get]
Returns unique Id (in the scope of a given type) of the current object. Method is defined as virtual so that derived class can have its own IDs by defining its own static IdentifiableGenerator object.
ObjectRegister< ExampleIRegistrable > ObjectRegister [get]
Gets object register where the current object is registered.
Properties inherited from IG.Lib.IRegisterable< ExampleIRegistrable >
ObjectRegister< T > ObjectRegister [get]
Gets the object register where the current object can be registered.
Private Attributes
IdProxy _idPproxy
Proxy object that implements the IIdentifiable interface for this object.
Static Private Attributes
static ObjectRegister< ExampleIRegistrable > _register
Static object that providees object register and generates IDs for this class:
Detailed Description
Example implementation of IIdentifiable interface.
Definition at line 302 of file UtilIdRegistration.cs.
Constructor & Destructor Documentation
ExampleIRegistrable()
IG.Lib.RegisterableExamples.ExampleIRegistrable.ExampleIRegistrable (string str) inline
Definition at line 304 of file UtilIdRegistration.cs.
References IG.Lib.RegisterableExamples.ExampleIRegistrable._msg, and IG.Lib.RegisterableExamples.ExampleIRegistrable.Register().
Member Function Documentation
Register()
void IG.Lib.RegisterableExamples.ExampleIRegistrable.Register () inline
Registers the current object. Subsequent calls (after the first one) have no effect.
Definition at line 336 of file UtilIdRegistration.cs.
References IG.Lib.RegisterableExamples.ExampleIRegistrable._register.
Referenced by IG.Lib.RegisterableExamples.ExampleIRegistrable.ExampleIRegistrable().
IsRegistered()
bool IG.Lib.RegisterableExamples.ExampleIRegistrable.IsRegistered () inline
Returns true if the current object is registered, false if not.
Returns
Definition at line 341 of file UtilIdRegistration.cs.
References IG.Lib.RegisterableExamples.ExampleIRegistrable._register.
Referenced by IG.Lib.RegisterableExamples.ExampleIRegistrable.ToString().
Unregister()
void IG.Lib.RegisterableExamples.ExampleIRegistrable.Unregister () inline
Unregisters the current object if it is currently registered. Can be performed several times, in this case only the first call may have effect.
Definition at line 346 of file UtilIdRegistration.cs.
References IG.Lib.RegisterableExamples.ExampleIRegistrable._register, and IG.Lib.RegisterableExamples.ExampleIRegistrable.Id.
Referenced by IG.Lib.RegisterableExamples.ExampleRegistrable().
ToString()
override string IG.Lib.RegisterableExamples.ExampleIRegistrable.ToString () inline
Definition at line 352 of file UtilIdRegistration.cs.
References IG.Lib.RegisterableExamples.ExampleIRegistrable._msg, IG.Lib.RegisterableExamples.ExampleIRegistrable.Id, and IG.Lib.RegisterableExamples.ExampleIRegistrable.IsRegistered().
Referenced by IG.Lib.RegisterableExamples.ExampleRegistrable().
Member Data Documentation
_msg
string IG.Lib.RegisterableExamples.ExampleIRegistrable._msg protected
Definition at line 310 of file UtilIdRegistration.cs.
Referenced by IG.Lib.RegisterableExamples.ExampleIRegistrable.ExampleIRegistrable(), and IG.Lib.RegisterableExamples.ExampleIRegistrable.ToString().
_register
ObjectRegister<ExampleIRegistrable> IG.Lib.RegisterableExamples.ExampleIRegistrable._register static private
Initial value:
=
                new ObjectRegister<ExampleIRegistrable>(1 )
Static object that providees object register and generates IDs for this class:
Definition at line 318 of file UtilIdRegistration.cs.
Referenced by IG.Lib.RegisterableExamples.ExampleIRegistrable.IsRegistered(), IG.Lib.RegisterableExamples.ExampleIRegistrable.Register(), and IG.Lib.RegisterableExamples.ExampleIRegistrable.Unregister().
_idPproxy
IdProxy IG.Lib.RegisterableExamples.ExampleIRegistrable._idPproxy private
Initial value:
=
                new IdProxy(_register)
Proxy object that implements the IIdentifiable interface for this object.
Definition at line 322 of file UtilIdRegistration.cs.
Property Documentation
Id
virtual int IG.Lib.RegisterableExamples.ExampleIRegistrable.Id get
Returns unique Id (in the scope of a given type) of the current object. Method is defined as virtual so that derived class can have its own IDs by defining its own static IdentifiableGenerator object.
Definition at line 328 of file UtilIdRegistration.cs.
Referenced by IG.Lib.RegisterableExamples.ExampleIRegistrable.ToString(), and IG.Lib.RegisterableExamples.ExampleIRegistrable.Unregister().
ObjectRegister
ObjectRegister<ExampleIRegistrable> IG.Lib.RegisterableExamples.ExampleIRegistrable.ObjectRegister get
Gets object register where the current object is registered.
Definition at line 332 of file UtilIdRegistration.cs.
Referenced by IG.Lib.RegisterableExamples.ExampleRegistrable().
The documentation for this class was generated from the following file:
iglib/igbase/utilities/UtilIdRegistration.cs