Doc: IGLib with source files: IGLib.Gr3D.TubularMeshGenerator_02 Class Reference
IGLib.Gr3D.TubularMeshGenerator_02 Class Reference
Static Public Member Functions
static StructuredMesh3D_02 GenerateTube (Func< double, vec3 > curve, double tStart, double tEnd, double radius, int numDivsT, int numDivsTheta)
Static Private Member Functions
static List<(vec3 T, vec3 N, vec3 B)> ComputeFrames (double[] tValues, Func< double, vec3 > curve)
Detailed Description
Definition at line 13 of file TubularMeshGenerator_02.cs.
Member Function Documentation
GenerateTube()
static StructuredMesh3D_02 IGLib.Gr3D.TubularMeshGenerator_02.GenerateTube (Func< double, vec3 > curve, double tStart, double tEnd, double radius, int numDivsT, int numDivsTheta) inline static
Definition at line 16 of file TubularMeshGenerator_02.cs.
References IGLib.Gr3D.TubularMeshGenerator_02.ComputeFrames(), and IGLib.Gr3D.StructuredMesh3D_02.Nodes.
Referenced by IGLib.Gr3D.TubularSurfaceExamples.Example_02(), and IGLib.Gr3D.TubularSurfaceExamples.Example_Export_02().
ComputeFrames()
static List<(vec3 T, vec3 N, vec3 B)> IGLib.Gr3D.TubularMeshGenerator_02.ComputeFrames (double[] tValues, Func< double, vec3 > curve) inline static private
Definition at line 48 of file TubularMeshGenerator_02.cs.
References IG.Num.vec3.Add(), IG.Num.vec3.Cross(), and IG.Num.vec3.Dot().
Referenced by IGLib.Gr3D.TubularMeshGenerator_02.GenerateTube().
The documentation for this class was generated from the following file:
IGLibGraphics3D/src/IGLib.Graphics3D/Graphics3D/Historical/TubularMeshGenerator_02.cs