Doc: IGLib with source files: IG.Lib.ThreadPerformanceTest Class Reference
IG.Lib.ThreadPerformanceTest Class Reference
Used to measure performance of the currend thread. A standard unit operation is provided for which number of executions per second is measured. Beside number of unit operations per second, the ratio between the CPU time and the clock time is calculated, which gives the feeling of how much the processor on which the thread executes is loaded. Measurements can be performed by specifying the requested number of cycles, but also by specifying the requested time in seconds.
Public Member Functions
ThreadPerformanceTest ()
void TestPerformanceNum (int numCycles, out ThreadPerformanceData data)
Execute performance test with specified number of standard cycles. WARNING: Usually the TestPerformance should be used which prescribes the approximate time used for the test.
void TestPerformanceNum (int numCycles, out double cyclesPerSec, out double performanceRatio)
Execute performance test with specified number of standard cycles. WARNING: Usually the TestPerformance should be used which prescribes the approximate time used for the test.
double TestPerformanceNum (int numCycles)
Execute performance test with specified number of standard cycles, and returns the measured number of standard cycles performed per second (which is the relevant performance measure). WARNING: Usually the TestPerformance should be used which prescribes the approximate time used for the test.
void TestPerformance (double requestedDuration, out ThreadPerformanceData data)
Execute performance test with specified measurement duration.
void TestPerformance (double requestedDuration, out double cyclesPerSec, out double performanceRatio)
Execute performance test with specified measurement duration.
double TestPerformance (double requestedDuration)
Execute performance test with specified measurement duration, and returns the measured number of standard cycles performed per second (which is the relevant performance measure).
override string ToString ()
Static Public Member Functions
static void StandardCycle ()
A standard unit operation that is repeated in order to measure performance.
static void CreateThreadLoads (int numThreads)
Starts the specified number of new load threads, each of which causes a full load to a CPU core until it stops. IMPORTANT: The load threads are switched off by setting ThreadPerformanceTest.PerformLoad to false. It can happen that this must be repeated several times to take effect.
static void Example ()
Examples and tests for this class.
Public Attributes
ThreadPerformanceData Last
Performance data of the last measurement performed.
Static Public Attributes
const int NumInner = 10000
Number of inner iterations. This number is chosen such that there are over 1000 outer cycles per second on medium speed modern processors.
const double RefCyclesPerSecond = 1600
A reference number of cycles per second. This can be used for orientation of how many cycles to request.
const int MinCycles = 20
Minimial number of cycles. Test never executes with less cycles because of accuracy of results.
Protected Member Functions
void StoreLast ()
Stores the last performance data.
Static Protected Member Functions
static void ThreadLoadFunction ()
Performed by load threads.
Static Protected Attributes
static bool _performLoad = false
static int _numLoadThreads = 0
Properties
object Lock [get]
List< ThreadPerformanceData > Data [get]
List of data aboud the performed tests.
static int NumLoadThreds [get, protected set]
Returns the current number of alive loading threads performing full CPU load.
static bool PerformLoad [get, set]
Specifies whether load should be performed. Setting this to false makes eventual threads to exit.
Private Attributes
object _lock = new Object()
List< ThreadPerformanceData > _data = new List<ThreadPerformanceData>()
Detailed Description
Used to measure performance of the currend thread. A standard unit operation is provided for which number of executions per second is measured. Beside number of unit operations per second, the ratio between the CPU time and the clock time is calculated, which gives the feeling of how much the processor on which the thread executes is loaded. Measurements can be performed by specifying the requested number of cycles, but also by specifying the requested time in seconds.
Definition at line 21 of file ThreadPerformanceTest.cs.
Constructor & Destructor Documentation
ThreadPerformanceTest()
IG.Lib.ThreadPerformanceTest.ThreadPerformanceTest () inline
Definition at line 24 of file ThreadPerformanceTest.cs.
References IG.Lib.ThreadPerformanceData.CyclesPerSecond, IG.Lib.ThreadPerformanceTest.Last, IG.Lib.ThreadPerformanceData.NumCycles, and IG.Lib.ThreadPerformanceData.PerformanceRatio.
Referenced by IG.Lib.ThreadPerformanceTest.Example().
Member Function Documentation
StoreLast()
void IG.Lib.ThreadPerformanceTest.StoreLast () inline protected
Stores the last performance data.
Definition at line 62 of file ThreadPerformanceTest.cs.
References IG.Lib.ThreadPerformanceTest.Data, and IG.Lib.ThreadPerformanceTest.Last.
Referenced by IG.Lib.ThreadPerformanceTest.TestPerformance(), and IG.Lib.ThreadPerformanceTest.TestPerformanceNum().
StandardCycle()
static void IG.Lib.ThreadPerformanceTest.StandardCycle () inline static
A standard unit operation that is repeated in order to measure performance.
Definition at line 69 of file ThreadPerformanceTest.cs.
References IG.Lib.ThreadPerformanceTest.NumInner.
Referenced by IG.Lib.ThreadPerformanceTest.TestPerformance(), and IG.Lib.ThreadPerformanceTest.TestPerformanceNum().
TestPerformanceNum() [1/3]
void IG.Lib.ThreadPerformanceTest.TestPerformanceNum (int numCycles, out ThreadPerformanceData data) inline
Execute performance test with specified number of standard cycles. WARNING: Usually the TestPerformance should be used which prescribes the approximate time used for the test.
Parameters
numCycles Number of standard cycles to be performed.
data Output structure that returns the performance data.
Definition at line 88 of file ThreadPerformanceTest.cs.
References IG.Lib.ThreadPerformanceData.CyclesPerSecond, IG.Lib.ThreadPerformanceTest.Last, IG.Lib.ThreadPerformanceTest.MinCycles, IG.Lib.ThreadPerformanceData.NumCycles, IG.Lib.ThreadPerformanceData.NumIterations, IG.Lib.ThreadPerformanceData.PerformanceRatio, IG.Lib.ThreadPerformanceTest.StandardCycle(), IG.Lib.StopWatch1.Start(), IG.Lib.StopWatch1.Stop(), IG.Lib.ThreadPerformanceTest.StoreLast(), IG.Lib.StopWatch1.Time, IG.Lib.ThreadPerformanceData.Time, IG.Lib.StopWatch1.TotalCpuTime, IG.Lib.StopWatch1.TotalTime, and IG.Lib.ThreadPerformanceData.TotalTime.
Referenced by IG.Lib.ThreadPerformanceTest.Example(), and IG.Lib.ThreadPerformanceTest.TestPerformanceNum().
TestPerformanceNum() [2/3]
void IG.Lib.ThreadPerformanceTest.TestPerformanceNum (int numCycles, out double cyclesPerSec, out double performanceRatio) inline
Execute performance test with specified number of standard cycles. WARNING: Usually the TestPerformance should be used which prescribes the approximate time used for the test.
Parameters
numCycles Number of standard cycles to be performed performed.
cyclesPerSec Returns number of cycles per second, which is the relevant performance measure for the current thread.
performanceRatio Returns ratio between CPU time and clock time spen for the test. This is a measure of how much the CPU is loaded (smaller the value, more it is loaded).
Definition at line 117 of file ThreadPerformanceTest.cs.
References IG.Lib.ThreadPerformanceTest.TestPerformanceNum().
TestPerformanceNum() [3/3]
double IG.Lib.ThreadPerformanceTest.TestPerformanceNum (int numCycles) inline
Execute performance test with specified number of standard cycles, and returns the measured number of standard cycles performed per second (which is the relevant performance measure). WARNING: Usually the TestPerformance should be used which prescribes the approximate time used for the test.
Parameters
numCycles Number of standard cycles to be performed.
Definition at line 133 of file ThreadPerformanceTest.cs.
References IG.Lib.ThreadPerformanceTest.TestPerformanceNum().
TestPerformance() [1/3]
void IG.Lib.ThreadPerformanceTest.TestPerformance (double requestedDuration, out ThreadPerformanceData data) inline
Execute performance test with specified measurement duration.
Parameters
requestedDuration Requested (approximate) duration of the test.
data Output structure that returns the performance data.
Definition at line 144 of file ThreadPerformanceTest.cs.
References IG.Lib.ThreadPerformanceData.CyclesPerSecond, IG.Lib.ThreadPerformanceTest.Last, IG.Lib.ThreadPerformanceTest.MinCycles, IG.Lib.ThreadPerformanceData.NumCycles, IG.Lib.ThreadPerformanceData.NumIterations, IG.Lib.ThreadPerformanceData.PerformanceRatio, IG.Lib.ThreadPerformanceTest.RefCyclesPerSecond, IG.Lib.ThreadPerformanceTest.StandardCycle(), IG.Lib.StopWatch1.Start(), IG.Lib.StopWatch1.Stop(), IG.Lib.ThreadPerformanceTest.StoreLast(), IG.Lib.StopWatch1.Time, IG.Lib.ThreadPerformanceData.Time, IG.Lib.StopWatch1.TotalCpuTime, IG.Lib.StopWatch1.TotalTime, and IG.Lib.ThreadPerformanceData.TotalTime.
Referenced by IG.Lib.ThreadPerformanceTest.Example(), and IG.Lib.ThreadPerformanceTest.TestPerformance().
TestPerformance() [2/3]
void IG.Lib.ThreadPerformanceTest.TestPerformance (double requestedDuration, out double cyclesPerSec, out double performanceRatio) inline
Execute performance test with specified measurement duration.
Parameters
requestedDuration Requested (approximate) duration of the test.
cyclesPerSec Returns number of cycles per second, which is the relevant performance measure for the current thread.
performanceRatio Returns ratio between CPU time and clock time spen for the test. This is a measure of how much the CPU is loaded (smaller the value, more it is loaded).
Definition at line 224 of file ThreadPerformanceTest.cs.
References IG.Lib.ThreadPerformanceTest.TestPerformance().
TestPerformance() [3/3]
double IG.Lib.ThreadPerformanceTest.TestPerformance (double requestedDuration) inline
Execute performance test with specified measurement duration, and returns the measured number of standard cycles performed per second (which is the relevant performance measure).
Parameters
requestedDuration Requested (approximate) duration of the test.
Definition at line 237 of file ThreadPerformanceTest.cs.
References IG.Lib.ThreadPerformanceTest.TestPerformance().
CreateThreadLoads()
static void IG.Lib.ThreadPerformanceTest.CreateThreadLoads (int numThreads) inline static
Starts the specified number of new load threads, each of which causes a full load to a CPU core until it stops. IMPORTANT: The load threads are switched off by setting ThreadPerformanceTest.PerformLoad to false. It can happen that this must be repeated several times to take effect.
Parameters
numThreads
Definition at line 277 of file ThreadPerformanceTest.cs.
References IG.Lib.ThreadPerformanceTest.PerformLoad, and IG.Lib.ThreadPerformanceTest.ThreadLoadFunction().
Referenced by IG.Lib.ThreadPerformanceTest.Example().
ThreadLoadFunction()
static void IG.Lib.ThreadPerformanceTest.ThreadLoadFunction () inline static protected
Performed by load threads.
Definition at line 289 of file ThreadPerformanceTest.cs.
References IG.Lib.ThreadPerformanceTest.NumLoadThreds, and IG.Lib.ThreadPerformanceTest.PerformLoad.
Referenced by IG.Lib.ThreadPerformanceTest.CreateThreadLoads().
ToString()
override string IG.Lib.ThreadPerformanceTest.ToString () inline
Definition at line 326 of file ThreadPerformanceTest.cs.
References IG.Lib.ThreadPerformanceTest._lock, IG.Lib.ThreadPerformanceTest.Data, IG.Lib.ThreadPerformanceTest.Last, IG.Lib.ThreadPerformanceTest.MinCycles, IG.Lib.ThreadPerformanceTest.NumInner, IG.Lib.ThreadPerformanceTest.RefCyclesPerSecond, and IG.Lib.ThreadPerformanceData.ToString().
Referenced by IG.Lib.ThreadPerformanceTest.Example().
Example()
static void IG.Lib.ThreadPerformanceTest.Example () inline static
Examples and tests for this class.
Definition at line 345 of file ThreadPerformanceTest.cs.
References IG.Lib.ThreadPerformanceTest.CreateThreadLoads(), IG.Lib.ThreadPerformanceTest.NumLoadThreds, IG.Lib.ThreadPerformanceTest.PerformLoad, IG.Lib.ThreadPerformanceTest.TestPerformance(), IG.Lib.ThreadPerformanceTest.TestPerformanceNum(), IG.Lib.ThreadPerformanceTest.ThreadPerformanceTest(), and IG.Lib.ThreadPerformanceTest.ToString().
Member Data Documentation
NumInner
const int IG.Lib.ThreadPerformanceTest.NumInner = 10000 static
Number of inner iterations. This number is chosen such that there are over 1000 outer cycles per second on medium speed modern processors.
Definition at line 34 of file ThreadPerformanceTest.cs.
Referenced by IG.Lib.ThreadPerformanceTest.StandardCycle(), and IG.Lib.ThreadPerformanceTest.ToString().
RefCyclesPerSecond
const double IG.Lib.ThreadPerformanceTest.RefCyclesPerSecond = 1600 static
A reference number of cycles per second. This can be used for orientation of how many cycles to request.
Definition at line 38 of file ThreadPerformanceTest.cs.
Referenced by IG.Lib.ThreadPerformanceTest.TestPerformance(), and IG.Lib.ThreadPerformanceTest.ToString().
MinCycles
const int IG.Lib.ThreadPerformanceTest.MinCycles = 20 static
Minimial number of cycles. Test never executes with less cycles because of accuracy of results.
Definition at line 42 of file ThreadPerformanceTest.cs.
Referenced by IG.Lib.ThreadPerformanceTest.TestPerformance(), IG.Lib.ThreadPerformanceTest.TestPerformanceNum(), and IG.Lib.ThreadPerformanceTest.ToString().
_lock
object IG.Lib.ThreadPerformanceTest._lock = new Object() private
Definition at line 44 of file ThreadPerformanceTest.cs.
Referenced by IG.Lib.ThreadPerformanceTest.ToString().
Last
ThreadPerformanceData IG.Lib.ThreadPerformanceTest.Last
Performance data of the last measurement performed.
Definition at line 51 of file ThreadPerformanceTest.cs.
Referenced by IG.Lib.ThreadPerformanceTest.StoreLast(), IG.Lib.ThreadPerformanceTest.TestPerformance(), IG.Lib.ThreadPerformanceTest.TestPerformanceNum(), IG.Lib.ThreadPerformanceTest.ThreadPerformanceTest(), and IG.Lib.ThreadPerformanceTest.ToString().
_data
List<ThreadPerformanceData> IG.Lib.ThreadPerformanceTest._data = new List<ThreadPerformanceData>() private
Definition at line 53 of file ThreadPerformanceTest.cs.
_performLoad
bool IG.Lib.ThreadPerformanceTest._performLoad = false static protected
Definition at line 245 of file ThreadPerformanceTest.cs.
_numLoadThreads
int IG.Lib.ThreadPerformanceTest._numLoadThreads = 0 static protected
Definition at line 247 of file ThreadPerformanceTest.cs.
Property Documentation
Lock
object IG.Lib.ThreadPerformanceTest.Lock get protected
Definition at line 47 of file ThreadPerformanceTest.cs.
Data
List<ThreadPerformanceData> IG.Lib.ThreadPerformanceTest.Data get
List of data aboud the performed tests.
Definition at line 57 of file ThreadPerformanceTest.cs.
Referenced by IG.Lib.ThreadPerformanceTest.StoreLast(), and IG.Lib.ThreadPerformanceTest.ToString().
NumLoadThreds
int IG.Lib.ThreadPerformanceTest.NumLoadThreds static get protected set
Returns the current number of alive loading threads performing full CPU load.
Definition at line 251 of file ThreadPerformanceTest.cs.
Referenced by IG.Lib.ThreadPerformanceTest.Example(), and IG.Lib.ThreadPerformanceTest.ThreadLoadFunction().
PerformLoad
bool IG.Lib.ThreadPerformanceTest.PerformLoad static get set
Specifies whether load should be performed. Setting this to false makes eventual threads to exit.
Definition at line 259 of file ThreadPerformanceTest.cs.
Referenced by IG.Lib.ThreadPerformanceTest.CreateThreadLoads(), IG.Lib.ThreadPerformanceTest.Example(), and IG.Lib.ThreadPerformanceTest.ThreadLoadFunction().
The documentation for this class was generated from the following file:
iglib/igbase/0unsorted/ThreadPerformanceTest.cs