Doc: IGLib with source files: IGLib.Gr3D.MeshExportExtensions Class Reference
IGLib.Gr3D.MeshExportExtensions Class Reference
Static Public Member Functions
static void ExportMeshToObj (this StructuredSurfaceMesh3D mesh, string objFilePath, string mtlFileName, bool exportSurfaces=true, bool exportWireframe=true, string surfaceMaterialName="SurfaceMaterial", string wireframeMaterialName="WireframeMaterial")
Exports a structured mesh to OBJ format, including vertex normals, surfaces, and optional wireframe.
static void ExportMeshSurfaceToObj (this StructuredSurfaceMesh3D mesh, string objFilePath, string mtlFileName, string surfaceMaterialName="SurfaceMaterial")
Exports only the surface mesh to an OBJ file.
static void ExportMeshWireframeToObj (this StructuredSurfaceMesh3D mesh, string objFilePath, string mtlFileName, string wireframeMaterialName="WireframeMaterial")
Exports only the wireframe of the mesh to an OBJ file.
static void ExportMaterial (string filePath, MaterialProperties material)
Exports a material file based on the provided material properties.
static void ExportToStl (this StructuredSurfaceMesh3D mesh, string stlFilePath)
Exports the mesh surface to an ASCII STL file.
static void ExportToGltf (this StructuredSurfaceMesh3D mesh, string gltfPath, MaterialProperties material, LightSource[] lights=null)
Exports the mesh to GLF format.
Static Private Member Functions
static void WriteFacet (StreamWriter writer, vec3 v1, vec3 v2, vec3 v3)
Auxiliary method for ExportToStl(StructuredSurfaceMesh3D, string), writes a single facet to the stream.
static byte[] ToBytes (List< float > list)
static byte[] ToBytes (List< ushort > list)
Detailed Description
Definition at line 13 of file MeshExportExtensions.cs.
Member Function Documentation
ExportMeshToObj()
static void IGLib.Gr3D.MeshExportExtensions.ExportMeshToObj (this StructuredSurfaceMesh3D mesh, string objFilePath, string mtlFileName, bool exportSurfaces = true, bool exportWireframe = true, string surfaceMaterialName = "SurfaceMaterial", string wireframeMaterialName = "WireframeMaterial") inline static
Exports a structured mesh to OBJ format, including vertex normals, surfaces, and optional wireframe.
Parameters
mesh The structured mesh to export.
objFilePath Path to the OBJ file.
mtlFileName Name of the material file referenced from the OBJ.
exportSurfaces If true, surface faces are exported.
exportWireframe If true, wireframe lines are exported.
surfaceMaterialName Material name for surfaces.
wireframeMaterialName Material name for wireframe.
Definition at line 26 of file MeshExportExtensions.cs.
References IGLib.Gr3D.StructuredSurfaceMesh3D.NumPoints1, and IGLib.Gr3D.StructuredSurfaceMesh3D.NumPoints2.
ExportMeshSurfaceToObj()
static void IGLib.Gr3D.MeshExportExtensions.ExportMeshSurfaceToObj (this StructuredSurfaceMesh3D mesh, string objFilePath, string mtlFileName, string surfaceMaterialName = "SurfaceMaterial") static
Exports only the surface mesh to an OBJ file.
ExportMeshWireframeToObj()
static void IGLib.Gr3D.MeshExportExtensions.ExportMeshWireframeToObj (this StructuredSurfaceMesh3D mesh, string objFilePath, string mtlFileName, string wireframeMaterialName = "WireframeMaterial") static
Exports only the wireframe of the mesh to an OBJ file.
ExportMaterial()
static void IGLib.Gr3D.MeshExportExtensions.ExportMaterial (string filePath, MaterialProperties material) inline static
Exports a material file based on the provided material properties.
Parameters
filePath Output file path (.mtl)
material Material properties.
Definition at line 113 of file MeshExportExtensions.cs.
References IGLib.Gr3D.MaterialProperties.SaveToMaterialFile().
Referenced by IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests.Example00_CreateAndExportTubularSurfaceTest(), IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests.Example01_ExportTrefoilKnot3DTube(), IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests.Example02_ExportHelixCurve3DTube(), IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests.Example03_ExportGrannyKnot3DTube(), IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests.Example04_ExportLissajousKnot3DTube(), IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests.Example11_1_ExportConicalSpiralArchimedian3DTube(), IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests.Example11_2_ExportConicalSpiralLogarithmic3DTube(), IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests.Example11_3_ExportConicalSpiralFermats3DTube(), IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests.Example11_4_ExportConicalSpiralHyperbolic3DTube(), IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests.Example50_ExportTorusKnot(), IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests.Example51_ExportLissajousKnot(), IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests.Example52_0_ExportCylindricalBilliardKnot(), and IGLib.Graphics3D.Tests.TubularSurfaceExportExamplesTests.Example52_1_ExportCylindricalBilliardKnot_WrongParameterization().
ExportToStl()
static void IGLib.Gr3D.MeshExportExtensions.ExportToStl (this StructuredSurfaceMesh3D mesh, string stlFilePath) inline static
Exports the mesh surface to an ASCII STL file.
Definition at line 120 of file MeshExportExtensions.cs.
References IGLib.Gr3D.StructuredSurfaceMesh3D.NumPoints1, IGLib.Gr3D.StructuredSurfaceMesh3D.NumPoints2, and IGLib.Gr3D.MeshExportExtensions.WriteFacet().
WriteFacet()
static void IGLib.Gr3D.MeshExportExtensions.WriteFacet (StreamWriter writer, vec3 v1, vec3 v2, vec3 v3) inline static private
Auxiliary method for ExportToStl(StructuredSurfaceMesh3D, string), writes a single facet to the stream.
Definition at line 143 of file MeshExportExtensions.cs.
References IG.Num.vec3.Cross(), and IG.Num.vec3.Normalize().
Referenced by IGLib.Gr3D.MeshExportExtensions.ExportToStl().
ExportToGltf()
static void IGLib.Gr3D.MeshExportExtensions.ExportToGltf (this StructuredSurfaceMesh3D mesh, string gltfPath, MaterialProperties material, LightSource[] lights = null) inline static
Exports the mesh to GLF format.
Features:
* Embedded base64 buffer (ASCII .gltf)
* Vertex positions
* Triangle indices
* Normals (optional, from VertexNormals)
* Vertex colors (optional, from VertexColors)
* Material reference
* Optional lights (LightSource)
*
*
Parameters
mesh Mesh to be exported.
gltfPath Name of the export file.
material Material to be assigned to the surface.
lights Lights used in rendering the surface, will be written to the file if specified.
Definition at line 173 of file MeshExportExtensions.cs.
References IG.Num.vec3.Add(), IGLib.Gr3D.StructuredSurfaceMesh3D.NumPoints1, IGLib.Gr3D.StructuredSurfaceMesh3D.NumPoints2, IGLib.Gr3D.MeshExportExtensions.ToBytes(), IGLib.Gr3D.StructuredSurfaceMesh3D.VertexColors, IGLib.Gr3D.StructuredSurfaceMesh3D.VertexNormals, and IGLib.Gr3D.StructuredSurfaceMesh3D.Vertices.
ToBytes() [1/2]
static byte [] IGLib.Gr3D.MeshExportExtensions.ToBytes (List< float > list) inline static private
Definition at line 305 of file MeshExportExtensions.cs.
Referenced by IGLib.Gr3D.MeshExportExtensions.ExportToGltf().
ToBytes() [2/2]
static byte [] IGLib.Gr3D.MeshExportExtensions.ToBytes (List< ushort > list) inline static private
Definition at line 312 of file MeshExportExtensions.cs.
The documentation for this class was generated from the following file:
IGLibGraphics3D/src/IGLib.Graphics3D/Graphics3D/Meshing/MeshExportExtensions.cs