Doc: IGLib with source files: IG.Num.VectorApproximatorBase Class Reference
IG.Num.VectorApproximatorBase Class Reference abstract
Base class for vector function approximators.
Public Member Functions
abstract void CalculateOutput (IVector input, ref IVector output)
Calculates and returns the approximated outputs corresponding to the specified inputs, by using the current vector function approximator.
virtual double CalculateOutput (IVector input, int whichElement)
Calculates and returns the specified output by using the current vector function approximator.
virtual void CalculateOutput (IVector input, int[] indices, ref IVector filteredOutput)
Calculates and returns the required output values corresponding to the specified inputs, by using the current vector function approximator.
Protected Attributes
IVector _lastCalculationInputParameters
Properties
object Lock [get]
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
abstract int InputLength [get, set]
Gets or sets the number of input parameters.
abstract int OutputLength [get, set]
Gets or sets the number of output values.
Properties inherited from IG.Num.IVectorApproximator
int InputLength [get, set]
Gets or sets the number of input parameters.
int OutputLength [get, set]
Gets or sets the number of output values.
Properties inherited from IG.Lib.ILockable
object Lock [get]
Private Attributes
object _mainLock = new object()
IVector _lastCalculationOutputValues
Detailed Description
Base class for vector function approximators.
Definition at line 14 of file VectorApproximatorBase.cs.
Member Function Documentation
CalculateOutput() [1/3]
abstract void IG.Num.VectorApproximatorBase.CalculateOutput (IVector input, ref IVector output) pure virtual
Calculates and returns the approximated outputs corresponding to the specified inputs, by using the current vector function approximator.
Parameters
input Input parameters.
output Vector where the calculated values are stored.
Returns
Vector of output values generated by the approximator.
Currently, only all outputs at once can be calculated. This makes no difference in the arrangement with a single network with multiple outputs, but does when several networks with single output each are used. If the implementation changes in the future then performance configuratins should be taken into account carefully, and tracking input for which input parameters the outputs have been calculated might be necessary.
Implements IG.Num.IVectorApproximator.
Implemented in IG.Num.NeuralApproximatorAforgeFake.
Referenced by IG.Num.VectorApproximatorBase.CalculateOutput().
CalculateOutput() [2/3]
virtual double IG.Num.VectorApproximatorBase.CalculateOutput (IVector input, int whichElement) inline virtual
Calculates and returns the specified output by using the current vector function approximator.
Implements IG.Num.IVectorApproximator.
Reimplemented in IG.Num.NeuralApproximatorBase, and IG.Num.NeuralApproximatorAforgeFake.
Definition at line 63 of file VectorApproximatorBase.cs.
References IG.Num.VectorApproximatorBase._lastCalculationInputParameters, IG.Num.VectorApproximatorBase._lastCalculationOutputValues, IG.Num.VectorApproximatorBase.CalculateOutput(), IG.Num.VectorBase.Compare(), IG.Num.VectorBase.Copy(), IG.Num.VectorApproximatorBase.InputLength, IG.Num.IVector< T >.Length, IG.Num.VectorApproximatorBase.Lock, and IG.Num.VectorApproximatorBase.OutputLength.
CalculateOutput() [3/3]
virtual void IG.Num.VectorApproximatorBase.CalculateOutput (IVector input, int[] indices, ref IVector filteredOutput) inline virtual
Calculates and returns the required output values corresponding to the specified inputs, by using the current vector function approximator.
Parameters
input Input parameters for which output values are calculated.
indices Array of indices of the output values to be returned.
filteredOutput Vector where filtered output values are stored.
Implements IG.Num.IVectorApproximator.
Reimplemented in IG.Num.NeuralApproximatorBase, and IG.Num.NeuralApproximatorAforgeFake.
Definition at line 92 of file VectorApproximatorBase.cs.
References IG.Num.VectorApproximatorBase._lastCalculationInputParameters, IG.Num.VectorApproximatorBase._lastCalculationOutputValues, IG.Num.VectorApproximatorBase.CalculateOutput(), IG.Num.VectorBase.Compare(), IG.Num.VectorBase.Copy(), IG.Num.VectorApproximatorBase.InputLength, IG.Num.IVector< T >.Length, IG.Num.VectorApproximatorBase.Lock, IG.Num.VectorApproximatorBase.OutputLength, and IG.Num.VectorBase.Resize().
Member Data Documentation
_mainLock
object IG.Num.VectorApproximatorBase._mainLock = new object() private
Definition at line 20 of file VectorApproximatorBase.cs.
_lastCalculationInputParameters
IVector IG.Num.VectorApproximatorBase._lastCalculationInputParameters protected
Definition at line 60 of file VectorApproximatorBase.cs.
Referenced by IG.Num.VectorApproximatorBase.CalculateOutput().
_lastCalculationOutputValues
IVector IG.Num.VectorApproximatorBase._lastCalculationOutputValues private
Definition at line 60 of file VectorApproximatorBase.cs.
Referenced by IG.Num.VectorApproximatorBase.CalculateOutput().
Property Documentation
Lock
object IG.Num.VectorApproximatorBase.Lock get
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
Definition at line 25 of file VectorApproximatorBase.cs.
Referenced by IG.Num.VectorApproximatorBase.CalculateOutput(), and IG.Num.NeuralApproximatorBase.ExampleQuadratic().
InputLength
abstract int IG.Num.VectorApproximatorBase.InputLength get set
Gets or sets the number of input parameters.
Definition at line 35 of file VectorApproximatorBase.cs.
Referenced by IG.Num.VectorApproximatorBase.CalculateOutput().
OutputLength
abstract int IG.Num.VectorApproximatorBase.OutputLength get set
Gets or sets the number of output values.
Definition at line 39 of file VectorApproximatorBase.cs.
Referenced by IG.Num.VectorApproximatorBase.CalculateOutput().
The documentation for this class was generated from the following file:
iglib/igbase/numeric/approximation/VectorApproximatorBase.cs