Doc: IGLib with source files: IG.Num.PenaltyEvaluator Class Reference
IG.Num.PenaltyEvaluator Class Reference
Evaluation of penalty functions.
Public Member Functions
PenaltyEvaluator ()
Constructs non-initialized penalty evaluator (wihout any penlaty functions). WARNING: Crated penalty evaluator is not initialized and can not be used for evaluation of penalty terms right away.
PenaltyEvaluator (double barrierLength, double barrierHeight)
Constructs penalty evaluator with penalty function (common for all constraints) initialized to the default penalty function with specified characteristic barrier length and height.
PenaltyEvaluator (double barrierLength, double barrierHeight, double maxZero)
Construct penalty evaluator with penalty function (common for all constraints) initialized to the default penalty function with specified characteristic barrier length and height and transition point where penalty function becomes non-zero.
void SetPenaltyFunction (int which, IRealFunctionPenalty function)
Sets the penalty function used for evaluation of the specified penalty term.
void SetPenaltyFunction (int which, double barrierLength, double barrierHeight)
Sets the penalty function used for evaluation of the specified penalty term.
void SetPenaltyFunction (int which, double barrierLength, double barrierHeight, double zeroEnd)
Sets the penalty function used for evaluation of the specified penalty term.
virtual bool CanSetBarrierLength (int which)
Returns a flag that tells whether characteristic barrier length can be set for the penalty function of the specified constraint.
virtual bool CansetBarrierHeight (int which)
Returns a flag that tells whether characteristic barrier height can be set for the penalty function of the specified constraint.
virtual bool CanSetMaxZero (int which)
Returns a flag that tells whether maxmal argument where function is zero can be set for the penalty function of the specified constraint.
int AddPenaltyFunction (IRealFunctionPenalty func)
Adds a new penalty function for evaluation of penalty terms to the list.
IRealFunctionPenalty GetPenaltyFunction (int which)
Returns penalty function corresonding to the specified constraint.
bool IsPenaltyValueDefined (int which)
Returns true if the penalty function value can be calculated for the specified constraint, or false otherwise.
bool IsPenaltyDerivativeDefined (int which)
Returns true if the penalty function derivative can be calculated for the specified constraint, or false otherwise.
bool IsPenaltySecodDerivativeDefined (int which)
Returns true if the penalty function's second can be calculated for the specified constraint, or false otherwise.
double PenaltyValue (int which, double constraintFunctionValue)
Returns value of the penalty function for the specified constraint at the specified value of the corresponding constraint function.
double PenaltyDerivative (int which, double constraintFunctionValue)
Returns derivative of the penalty function for the specified constraint at the specified value of the corresponding constraint function, with respect to constraint value.
double PenaltySecondDerivative (int which, double constraintFunctionValue)
Returns second derivative of the penalty function for the specified constraint at the specified value of the corresponding constraint function, with respect to constraint value.
Protected Member Functions
virtual IRealFunctionPenalty CreatePenaltyFunction (double barrierLength, double barrierHeight)
Creates a new penalty function with the specified characteristic length and height. Created function is power penalty function of power 3. This is used in order to create default penalty functions for this class, such that one does not need to create penalty functions explicitly. Subclasses can (should) override this method in orde to change the type of default penalty function.
virtual IRealFunctionPenalty CreatePenaltyFunction (double barrierLength, double barrierHeight, double zeroEnd, int power)
Creates a new penalty function with the specified characteristic length and height. Created function is power penalty function of power 3. This is used in order to create default penalty functions for this class, such that one does not need to create penalty functions explicitly. Subclasses can (should) override this method in orde to change the type of default penalty function.
Protected Attributes
object _lock = new object()
bool _allowSingleFunction = true
List< IRealFunctionPenalty > _penaltyFunctions = null
Properties
object Lock [get]
Object used for thread locking the current object.
bool AllowSingleFunction [get, set]
Whether a single function can be used for evaluating penalty terms corresponding to different constraints.
List< IRealFunctionPenalty > PenaltyFunctions [get]
Returns a list of penalty functions used to evaluate penalty terms.
Properties inherited from IG.Num.IPenaltyEvaluator
bool AllowSingleFunction [get, set]
Whether a single function can be used for evaluating penalty terms corresponding to different constraints.
List< IRealFunctionPenalty > PenaltyFunctions [get]
Returns a list of penalty functions used to evaluate penalty terms.
Properties inherited from IG.Lib.ILockable
object Lock [get]
Detailed Description
Evaluation of penalty functions.
$A Igor Jul10;
Definition at line 2345 of file AnalysisResults.cs.
Constructor & Destructor Documentation
PenaltyEvaluator() [1/3]
IG.Num.PenaltyEvaluator.PenaltyEvaluator () inline
Constructs non-initialized penalty evaluator (wihout any penlaty functions). WARNING: Crated penalty evaluator is not initialized and can not be used for evaluation of penalty terms right away.
Definition at line 2354 of file AnalysisResults.cs.
PenaltyEvaluator() [2/3]
IG.Num.PenaltyEvaluator.PenaltyEvaluator (double barrierLength, double barrierHeight) inline
Constructs penalty evaluator with penalty function (common for all constraints) initialized to the default penalty function with specified characteristic barrier length and height.
Parameters
barrierLength Characteristic barrrier length. Within this length the created penalty function grows approximately from 0 to characteristic height.
barrierHeight Characteristic barrier height.
Definition at line 2363 of file AnalysisResults.cs.
References IG.Num.PenaltyEvaluator.SetPenaltyFunction().
PenaltyEvaluator() [3/3]
IG.Num.PenaltyEvaluator.PenaltyEvaluator (double barrierLength, double barrierHeight, double maxZero) inline
Construct penalty evaluator with penalty function (common for all constraints) initialized to the default penalty function with specified characteristic barrier length and height and transition point where penalty function becomes non-zero.
Parameters
barrierLength Characteristic barrrier length. Within this length the created penalty function grows approximately from 0 to characteristic height.
barrierHeight Characteristic barrier height.
maxZero Maximal argument for which the created function is 0.
Definition at line 2375 of file AnalysisResults.cs.
References IG.Num.PenaltyEvaluator.SetPenaltyFunction().
Member Function Documentation
CreatePenaltyFunction() [1/2]
virtual IRealFunctionPenalty IG.Num.PenaltyEvaluator.CreatePenaltyFunction (double barrierLength, double barrierHeight) inline protected virtual
Creates a new penalty function with the specified characteristic length and height. Created function is power penalty function of power 3. This is used in order to create default penalty functions for this class, such that one does not need to create penalty functions explicitly. Subclasses can (should) override this method in orde to change the type of default penalty function.
Parameters
barrierLength Characteristic barrrier length. Within this length the created penalty function grows approximately from 0 to characteristic height.
barrierHeight Characteristic height.
Returns
Created penalty function.
Definition at line 2415 of file AnalysisResults.cs.
References IG.Num.Func.GetPenaltyPower().
Referenced by IG.Num.PenaltyEvaluator.SetPenaltyFunction().
CreatePenaltyFunction() [2/2]
virtual IRealFunctionPenalty IG.Num.PenaltyEvaluator.CreatePenaltyFunction (double barrierLength, double barrierHeight, double zeroEnd, int power) inline protected virtual
Creates a new penalty function with the specified characteristic length and height. Created function is power penalty function of power 3. This is used in order to create default penalty functions for this class, such that one does not need to create penalty functions explicitly. Subclasses can (should) override this method in orde to change the type of default penalty function.
Parameters
barrierLength Characteristic barrrier length. Within this length the created penalty function grows approximately from 0 to characteristic height.
barrierHeight Characteristic height.
zeroEnd Maximal argument for which the created function is 0.
power Power. Must be greater than 0. For 2 first derivative is continuous in transition points, for 3 second derivative is also continuous, etc.
Returns
Created penalty function.
Definition at line 2433 of file AnalysisResults.cs.
References IG.Num.Func.GetPenaltyPower().
SetPenaltyFunction() [1/3]
void IG.Num.PenaltyEvaluator.SetPenaltyFunction (int which, IRealFunctionPenalty function) inline
Sets the penalty function used for evaluation of the specified penalty term.
Parameters
which Specifies which conatraint the penalty function applies to (zero based). In order to use one penalty function for all constraints, just set the penalty function with index 0.
function Function to be used for evaluation of the specified penalty term.
Implements IG.Num.IPenaltyEvaluator.
Definition at line 2461 of file AnalysisResults.cs.
References IG.Num.PenaltyEvaluator._lock, and IG.Num.PenaltyEvaluator.PenaltyFunctions.
Referenced by IG.Num.PenaltyEvaluator.PenaltyEvaluator().
SetPenaltyFunction() [2/3]
void IG.Num.PenaltyEvaluator.SetPenaltyFunction (int which, double barrierLength, double barrierHeight) inline
Sets the penalty function used for evaluation of the specified penalty term.
Parameters
which Specifies which conatraint the penalty function applies to (zero based). In order to use one penalty function for all constraints, just set the penalty function with index 0.
barrierLength Characteristic barrier length of the created function. This is the length at which function grows from approximately 0 to characteristic height.
barrierHeight Characteristic barrier height of the created function.
Implements IG.Num.IPenaltyEvaluator.
Definition at line 2479 of file AnalysisResults.cs.
References IG.Num.PenaltyEvaluator._lock, IG.Num.IRealFunctionPenalty.BarrierHeight, IG.Num.IRealFunctionPenalty.BarrierLength, IG.Num.IRealFunctionPenalty.CanSetBarrierHeight, IG.Num.IRealFunctionPenalty.CanSetBarrierLength, IG.Num.PenaltyEvaluator.CreatePenaltyFunction(), and IG.Num.PenaltyEvaluator.PenaltyFunctions.
SetPenaltyFunction() [3/3]
void IG.Num.PenaltyEvaluator.SetPenaltyFunction (int which, double barrierLength, double barrierHeight, double zeroEnd) inline
Sets the penalty function used for evaluation of the specified penalty term.
Parameters
which Specifies which conatraint the penalty function applies to (zero based). In order to use one penalty function for all constraints, just set the penalty function with index 0.
barrierLength Characteristic barrier length of the created function. This is the length at which function grows from approximately 0 to characteristic height.
barrierHeight Characteristic barrier height of the created function.
zeroEnd Maximal argumet for which penalty function is still 0.
Implements IG.Num.IPenaltyEvaluator.
Definition at line 2511 of file AnalysisResults.cs.
References IG.Num.PenaltyEvaluator._lock, IG.Num.IRealFunctionPenalty.BarrierHeight, IG.Num.IRealFunctionPenalty.BarrierLength, IG.Num.IRealFunctionPenalty.CanSetBarrierHeight, IG.Num.IRealFunctionPenalty.CanSetBarrierLength, IG.Num.IRealFunctionPenalty.CanSetMaxZero, IG.Num.PenaltyEvaluator.CreatePenaltyFunction(), IG.Num.IRealFunctionPenalty.MaxZero, and IG.Num.PenaltyEvaluator.PenaltyFunctions.
CanSetBarrierLength()
virtual bool IG.Num.PenaltyEvaluator.CanSetBarrierLength (int which) inline virtual
Returns a flag that tells whether characteristic barrier length can be set for the penalty function of the specified constraint.
Parameters
which Specified the constraiint in question.
Implements IG.Num.IPenaltyEvaluator.
Definition at line 2543 of file AnalysisResults.cs.
References IG.Num.PenaltyEvaluator._lock, IG.Num.IRealFunctionPenalty.CanSetBarrierLength, IG.Num.PenaltyEvaluator.GetPenaltyFunction(), and IG.Num.PenaltyEvaluator.PenaltyFunctions.
CansetBarrierHeight()
virtual bool IG.Num.PenaltyEvaluator.CansetBarrierHeight (int which) inline virtual
Returns a flag that tells whether characteristic barrier height can be set for the penalty function of the specified constraint.
Parameters
which Specified the constraiint in question.
Implements IG.Num.IPenaltyEvaluator.
Definition at line 2560 of file AnalysisResults.cs.
References IG.Num.PenaltyEvaluator._lock, IG.Num.IRealFunctionPenalty.CanSetBarrierHeight, IG.Num.PenaltyEvaluator.GetPenaltyFunction(), and IG.Num.PenaltyEvaluator.PenaltyFunctions.
CanSetMaxZero()
virtual bool IG.Num.PenaltyEvaluator.CanSetMaxZero (int which) inline virtual
Returns a flag that tells whether maxmal argument where function is zero can be set for the penalty function of the specified constraint.
Parameters
which Specified the constraiint in question.
Implements IG.Num.IPenaltyEvaluator.
Definition at line 2577 of file AnalysisResults.cs.
References IG.Num.PenaltyEvaluator._lock, IG.Num.IRealFunctionPenalty.CanSetMaxZero, IG.Num.PenaltyEvaluator.GetPenaltyFunction(), and IG.Num.PenaltyEvaluator.PenaltyFunctions.
AddPenaltyFunction()
int IG.Num.PenaltyEvaluator.AddPenaltyFunction (IRealFunctionPenalty func) inline
Adds a new penalty function for evaluation of penalty terms to the list.
Parameters
func Function to be added.
Returns
Index of the added penalty function (0 if this is the first function on the list).
Implements IG.Num.IPenaltyEvaluator.
Definition at line 2595 of file AnalysisResults.cs.
References IG.Num.PenaltyEvaluator._lock, and IG.Num.PenaltyEvaluator.PenaltyFunctions.
GetPenaltyFunction()
IRealFunctionPenalty IG.Num.PenaltyEvaluator.GetPenaltyFunction (int which) inline
Returns penalty function corresonding to the specified constraint.
Parameters
which Index of penalty function (or the corresponding constraint).
Implements IG.Num.IPenaltyEvaluator.
Definition at line 2606 of file AnalysisResults.cs.
References IG.Num.PenaltyEvaluator._lock, IG.Num.PenaltyEvaluator.AllowSingleFunction, and IG.Num.PenaltyEvaluator.PenaltyFunctions.
Referenced by IG.Num.PenaltyEvaluator.CansetBarrierHeight(), IG.Num.PenaltyEvaluator.CanSetBarrierLength(), IG.Num.PenaltyEvaluator.CanSetMaxZero(), IG.Num.PenaltyEvaluator.IsPenaltyDerivativeDefined(), IG.Num.PenaltyEvaluator.IsPenaltySecodDerivativeDefined(), IG.Num.PenaltyEvaluator.IsPenaltyValueDefined(), IG.Num.PenaltyEvaluator.PenaltyDerivative(), IG.Num.PenaltyEvaluator.PenaltySecondDerivative(), and IG.Num.PenaltyEvaluator.PenaltyValue().
IsPenaltyValueDefined()
bool IG.Num.PenaltyEvaluator.IsPenaltyValueDefined (int which) inline
Returns true if the penalty function value can be calculated for the specified constraint, or false otherwise.
Parameters
which Specifies the constraint in question.
Implements IG.Num.IPenaltyEvaluator.
Definition at line 2630 of file AnalysisResults.cs.
References IG.Num.PenaltyEvaluator.GetPenaltyFunction(), and IG.Num.IRealFunction.ValueDefined.
IsPenaltyDerivativeDefined()
bool IG.Num.PenaltyEvaluator.IsPenaltyDerivativeDefined (int which) inline
Returns true if the penalty function derivative can be calculated for the specified constraint, or false otherwise.
Parameters
which Specifies the constraint in question.
Implements IG.Num.IPenaltyEvaluator.
Definition at line 2638 of file AnalysisResults.cs.
References IG.Num.IRealFunction.DerivativeDefined, and IG.Num.PenaltyEvaluator.GetPenaltyFunction().
IsPenaltySecodDerivativeDefined()
bool IG.Num.PenaltyEvaluator.IsPenaltySecodDerivativeDefined (int which) inline
Returns true if the penalty function's second can be calculated for the specified constraint, or false otherwise.
Parameters
which Specifies the constraint in question.
Implements IG.Num.IPenaltyEvaluator.
Definition at line 2646 of file AnalysisResults.cs.
References IG.Num.PenaltyEvaluator.GetPenaltyFunction(), and IG.Num.IRealFunction.SecondDerivativeDefined.
PenaltyValue()
double IG.Num.PenaltyEvaluator.PenaltyValue (int which, double constraintFunctionValue) inline
Returns value of the penalty function for the specified constraint at the specified value of the corresponding constraint function.
Parameters
which Specifies the constraint in question.
constraintFunctionValue Value of constraint function.
Implements IG.Num.IPenaltyEvaluator.
Definition at line 2656 of file AnalysisResults.cs.
References IG.Num.PenaltyEvaluator.GetPenaltyFunction(), and IG.Num.IRealFunction.Value().
PenaltyDerivative()
double IG.Num.PenaltyEvaluator.PenaltyDerivative (int which, double constraintFunctionValue) inline
Returns derivative of the penalty function for the specified constraint at the specified value of the corresponding constraint function, with respect to constraint value.
Parameters
which Specifies the constraint in question.
constraintFunctionValue Value of constraint function.
Implements IG.Num.IPenaltyEvaluator.
Definition at line 2665 of file AnalysisResults.cs.
References IG.Num.IRealFunction.Derivative(), and IG.Num.PenaltyEvaluator.GetPenaltyFunction().
PenaltySecondDerivative()
double IG.Num.PenaltyEvaluator.PenaltySecondDerivative (int which, double constraintFunctionValue) inline
Returns second derivative of the penalty function for the specified constraint at the specified value of the corresponding constraint function, with respect to constraint value.
Parameters
which Specifies the constraint in question.
constraintFunctionValue Value of constraint function.
Implements IG.Num.IPenaltyEvaluator.
Definition at line 2674 of file AnalysisResults.cs.
References IG.Num.PenaltyEvaluator.GetPenaltyFunction(), and IG.Num.IRealFunction.SecondDerivative().
Member Data Documentation
_lock
object IG.Num.PenaltyEvaluator._lock = new object() protected
Definition at line 2382 of file AnalysisResults.cs.
Referenced by IG.Num.PenaltyEvaluator.AddPenaltyFunction(), IG.Num.PenaltyEvaluator.CansetBarrierHeight(), IG.Num.PenaltyEvaluator.CanSetBarrierLength(), IG.Num.PenaltyEvaluator.CanSetMaxZero(), IG.Num.PenaltyEvaluator.GetPenaltyFunction(), and IG.Num.PenaltyEvaluator.SetPenaltyFunction().
_allowSingleFunction
bool IG.Num.PenaltyEvaluator._allowSingleFunction = true protected
Definition at line 2393 of file AnalysisResults.cs.
_penaltyFunctions
List<IRealFunctionPenalty> IG.Num.PenaltyEvaluator._penaltyFunctions = null protected
Definition at line 2440 of file AnalysisResults.cs.
Property Documentation
Lock
object IG.Num.PenaltyEvaluator.Lock get
Object used for thread locking the current object.
Definition at line 2386 of file AnalysisResults.cs.
AllowSingleFunction
bool IG.Num.PenaltyEvaluator.AllowSingleFunction get set
Whether a single function can be used for evaluating penalty terms corresponding to different constraints.
Definition at line 2398 of file AnalysisResults.cs.
Referenced by IG.Num.PenaltyEvaluator.GetPenaltyFunction().
PenaltyFunctions
List<IRealFunctionPenalty> IG.Num.PenaltyEvaluator.PenaltyFunctions get
Returns a list of penalty functions used to evaluate penalty terms.
Definition at line 2444 of file AnalysisResults.cs.
Referenced by IG.Num.PenaltyEvaluator.AddPenaltyFunction(), IG.Num.PenaltyEvaluator.CansetBarrierHeight(), IG.Num.PenaltyEvaluator.CanSetBarrierLength(), IG.Num.PenaltyEvaluator.CanSetMaxZero(), IG.Num.PenaltyEvaluator.GetPenaltyFunction(), and IG.Num.PenaltyEvaluator.SetPenaltyFunction().
The documentation for this class was generated from the following file:
iglib/igbase/optimization/AnalysisResults.cs