Doc: IGLib with source files: JsonPrettyPrinterPlus.JsonPrettyPrinter Class Reference
JsonPrettyPrinterPlus.JsonPrettyPrinter Class Reference
Public Member Functions
JsonPrettyPrinter (JsonPPStrategyContext context)
string PrettyPrint (string inputString)
Private Member Functions
void PrettyPrintCharacter (StringBuilder input, StringBuilder output)
Private Attributes
readonly JsonPPStrategyContext _context
Detailed Description
Definition at line 18 of file JsonPrettyPrinter.cs.
Constructor & Destructor Documentation
JsonPrettyPrinter()
JsonPrettyPrinterPlus.JsonPrettyPrinter.JsonPrettyPrinter (JsonPPStrategyContext context) inline
Definition at line 22 of file JsonPrettyPrinter.cs.
References JsonPrettyPrinterPlus.JsonPrettyPrinter._context, JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.AddCharacterStrategy(), and JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.ClearStrategies().
Member Function Documentation
PrettyPrint()
string JsonPrettyPrinterPlus.JsonPrettyPrinter.PrettyPrint (string inputString) inline
Definition at line 41 of file JsonPrettyPrinter.cs.
References JsonPrettyPrinterPlus.JsonPrettyPrinter.PrettyPrintCharacter().
Referenced by IG.Lib.JsonFormatter.Format().
PrettyPrintCharacter()
void JsonPrettyPrinterPlus.JsonPrettyPrinter.PrettyPrintCharacter (StringBuilder input, StringBuilder output) inline private
Definition at line 54 of file JsonPrettyPrinter.cs.
References JsonPrettyPrinterPlus.JsonPrettyPrinter._context, and JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.PrettyPrintCharacter().
Referenced by JsonPrettyPrinterPlus.JsonPrettyPrinter.PrettyPrint().
Member Data Documentation
_context
readonly JsonPPStrategyContext JsonPrettyPrinterPlus.JsonPrettyPrinter._context private
Definition at line 20 of file JsonPrettyPrinter.cs.
Referenced by JsonPrettyPrinterPlus.JsonPrettyPrinter.JsonPrettyPrinter(), and JsonPrettyPrinterPlus.JsonPrettyPrinter.PrettyPrintCharacter().
The documentation for this class was generated from the following file:
iglib/igbase/data/serialization/json/JsonPrettyPrinter.cs