Doc: IGLib with source files: IG.Lib.ReporterBase Class Reference
IG.Lib.ReporterBase Class Reference
Base IGlib class for reporting, tracing and logging; provides a global reporter and a basis for creation of local reporters. This class is identical to the IGLib class (copied directly). IN EFA, refer to the derived class Reporter!
Classes
class TWClass
A class for storing TextWriters and some data associated with them (such as the name of the file from which a TextWriter was created), which enables searching on basis of this data.
Public Member Functions
ReporterBase ()
Constructor. Initializes all error reporting delegates to default values and sets auxliary object to null. Auxiliary object Obj is set to null.
ReporterBase (object obj, ReportDelegate reportdelegate, ReportLocationDelegate locationdelegate, ReportMessageDelegate messagedelegate, ReserveReportErrorDelegate reservereportdelegate)
Constructor. Initializes the error reporter by the specified auxiliary object and delegates used to perform error reporting tasks. Delegates that are not specified are set to default values.
ReporterBase (object obj, ReportDelegate reportdelegate, ReportLocationDelegate locationdelegate, ReportMessageDelegate messagedelegate)
Constructor. Initializes the error reporter by the specified auxiliary object and delegates used to perform error reporting tasks. Reserve error reporting delegate is initialized to a default value. Delegates that are not specified are set to default values.
ReporterBase (object obj, ReportDelegate reportdelegate)
Constructor. Initializes the error reporter by the specified auxiliary object and the delegate to perform error reporting tasks. Reserve error reporting delegate is initialized to a default value. Delegates for assembling the error location string and error message string are set to their default values, which are adapted to console-like eror reporting systems.
ReporterBase (object obj, ReportDelegate reportdelegate, ReserveReportErrorDelegate reservereportdelegate)
Constructor. Initializes the error reporter by the specified auxiliary object and delegates used to perform error reporting tasks. Delegates for assembling the error locatin and error message string are set to their default values, which are adapted to console-like eror reporting systems.
void Init (object obj, ReportDelegate reportdelegate, ReportLocationDelegate locationdelegate, ReportMessageDelegate messagedelegate, ReserveReportErrorDelegate reservereportdelegate)
Initializes the error reporter by the specified auxiliary object and delegates used to perform error reporting tasks. Delegates that are not specified are set to default values.
void Init ()
Initializes all error reporting delegates to default values and sets auxliary object to null. Auxiliary object Obj is set to null.
void Init (object obj, ReportDelegate reportdelegate, ReportLocationDelegate locationdelegate, ReportMessageDelegate messagedelegate)
Initializes the error reporter by the specified auxiliary object and delegates used to perform error reporting tasks. Reserve error reporting delegate is initialized to a default value. Delegates that are not specified are set to default values.
void Init (object obj, ReportDelegate reportdelegate)
Initializes the error reporter by the specified auxiliary object and the delegate to perform error reporting tasks. Reserve error reporting delegate is initialized to a default value. Delegates for assembling the error location string and error message string are set to their default values, which are adapted to console-like eror reporting systems.
void Init (object obj, ReportDelegate reportdelegate, ReserveReportErrorDelegate reservereportdelegate)
Initializes the error reporter by the specified auxiliary object and delegates used to perform error reporting tasks. Delegates for assembling the error locatin and error message string are set to their default values, which are adapted to console-like eror reporting systems.
void Dispose ()
bool AppSettingsRead (string groupname)
Returns a flag that tells whether configuration settings with a given group name have already been read for this reporter.
bool AppSettingsRead ()
Returns a flag that tells whether general configuration settings (not belonging to any group) have already been read for this reporter.
void ReadAppSettings (string groupname, bool onlyonce)
Reads settings for a specified named group of reporters from the application configuration file.
void ReadAppSettings (string groupname)
Reads settings for a specified named group of reporters from the application configuration file.
void ReadAppSettings ()
Reads common reporter settings (i.e. settings that are not assigned for any named group) from the application configuration file.
void IncreaseDepth ()
Increases indentation level by 1.
void IncreaseDepth (int numlevels)
Increases indentation level by the specified number of levels (can be 0 or negative).
void DecreaseDepth ()
Decreases indentation level by 1.
void DecreaseDepth (int numlevels)
Decreases indentation level by the specified number of levels (can be 0 or negative).
void ResetLevels ()
Resets the various kinds of reporting levels to default values.
bool DoReporting (ReportType reptype)
Returns true if the report of a given type should be shown by user interface (according to ReportingLevel), and false if not.
bool DoLogging (ReportType reptype)
Returns true if the report of a given type should be logged in log files (according to ReportingLevel), and false if not.
bool DoTracing (ReportType reptype)
Returns true if the report of a given type should traced (according to ReportingLevel), and false if not.
virtual void Report (ReportType messagetype, string location, string message, Exception ex)
Basic reporting method (overloaded). Launches an error report, a warning report or other kind of report/message. Supplemental data (such as objects necessary to launch visualize the report or operation flags) are obtained from the class' instance.
void Report (ReportType messagetype, string message, Exception ex)
Launches a report. Predominantly for error and warning reports.
void Report (ReportType messagetype, Exception ex, string location)
Launches a report. Predominantly for error and warning reports.
void Report (ReportType messagetype, Exception ex)
Launches a report. Predominantly for error and warning reports.
void Report (ReportType messagetype, string location, string message)
Launches a report.
void Report (ReportType messagetype, string message)
Launches a report.
void ReportError (string location, string message, Exception ex)
Basic error reporting method (overloaded). Supplemental data (such as objects necessary to launch visualize the report or operation flags) are obtained from the class' instance.
void ReportError (string message, Exception ex)
Launches an error report.
void ReportError (Exception ex, string location)
Launches an error report.
void ReportError (Exception ex)
Launches an error report. Predominantly for error and warning reports.
void ReportError (string location, string message)
Launches an error report.
void ReportError (string message)
Launches an error report.
void ReportWarning (string location, string message, Exception ex)
Basic warning reporting method (overloaded). Supplemental data (such as objects necessary to launch visualize the report or operation flags) are obtained from the class' instance.
void ReportWarning (string message, Exception ex)
Launches a warning report.
void ReportWarning (Exception ex, string location)
Launches a warning report.
void ReportWarning (Exception ex)
Launches a warning report. Predominantly for error and warning reports.
void ReportWarning (string location, string message)
Launches a warning report.
void ReportWarning (string message)
Launches a warning report.
void ReportInfo (Exception ex)
Launches an info.
void ReportInfo (string location, string message)
Launches an info.
void ReportInfo (string message)
Launches an info.
bool SetTW (ref TextWriter tw, ref bool disptw, string filename, bool append, bool writeintro, bool disposewriter)
Creates a TextWriter upon a file and sets it as the text writer to which reporting is also performed. The caller specifies whether to overwrite the file or to append to it, and whether the introductory text is written before reporting to the file begins.
bool SetTextWriter (TextWriter writer)
Sets the text writer to which reporting is also performed.
bool SetTextWriter (TextWriter writer, bool writeintro)
Sets the basic text writer to which reporting is performed, but overrides the writeintro property by the 'writeintro' argument.
bool SetTextWriter (TextWriter writer, bool writeintro, bool disposewriter)
Sets the basic text writer to which reporting is performed, but overrides the writeintro property by the 'writeintro' argument.
bool SetTextWriter (Stream stream)
Creates a TextWriter upon the stream and sets it as the text writer to which reporting is also performed.
bool SetTextWriter (Stream stream, bool writeintro)
Creates a TextWriter upon the stream and sets it as the basic TextWriter to which reporting is performed. Overrides the writeintro property by the 'writeintro' argument.
bool SetTextWriter (Stream stream, bool writeintro, bool disposewriter)
Creates a TextWriter upon the stream and sets it as the basic TextWriter to which reporting is performed. Overrides the writeintro property by the 'writeintro' argument.
bool SetTextWriter (string filename)
Creates a TextWriter upon a file and sets it as the basic TextWriter to which reporting is also performed. The file is overwritten.
bool SetTextWriter (string filename, bool append)
Creates a TextWriter upon a file and sets it as the basic TextWriter to which reporting is also performed, where the caller specifies either to overwrite the file or to append to it.
bool SetTextWriter (string filename, bool append, bool writeintro)
Creates a TextWriter upon a file and sets it as the text writer to which reporting is also performed. The caller specifies whether to overwrite the file or to append to it, and whether the introductory text is written before reporting to the file begins.
bool SetTextWriter (string filename, bool append, bool writeintro, bool disposewriter)
Creates a TextWriter upon a file and sets it as the text writer to which reporting is also performed. The caller specifies whether to overwrite the file or to append to it, and whether the introductory text is written before reporting to the file begins.
bool AddTextWriter (TextWriter writer)
Sets the text writer to which reporting is also performed.
bool AddTextWriter (TextWriter writer, bool writeintro)
Sets the basic text writer to which reporting is performed, but overrides the writeintro property by the 'writeintro' argument.
bool AddTextWriter (TextWriter writer, bool writeintro, bool disposewriter)
Sets the basic text writer to which reporting is performed, but overrides the writeintro property by the 'writeintro' argument.
bool AddTextWriter (Stream stream)
Creates a TextWriter from the stream and adds it to the list of TextWriters on which reporting is also performed.
bool AddTextWriter (Stream stream, bool writeintro)
Creates a TextWriter from the stream and adds it to the list of TextWriters on which reporting is also performed. Overrides the writeintro property by the 'writeintro' argument.
bool AddTextWriter (Stream stream, bool writeintro, bool disposewriter)
Creates a TextWriter from the stream and adds it to the list of TextWriters on which reporting is also performed. Overrides the writeintro property by the 'writeintro' argument.
bool AddTextWriter (string filename)
Creates a TextWriter from the file name and adds it to the list of TextWriters on which reporting is also performed. The file is overwritten.
bool AddTextWriter (string filename, bool append)
Creates a TextWriter from the stream and adds it to the list of TextWriters on which reporting is also performed. The caller specifies either to overwrite the file or to append to it.
bool AddTextWriter (string filename, bool append, bool writeintro)
Creates a TextWriter from the stream and adds it to the list of TextWriters on which reporting is also performed. The caller specifies whether to overwrite the file or to append to it, and whether the introductory text is written before reporting to the file begins.
bool AddTextWriter (string filename, bool append, bool writeintro, bool disposewriter)
Creates a TextWriter from the stream and adds it to the list of TextWriters on which reporting is also performed. The caller specifies whether to overwrite the file or to append to it, and whether the introductory text is written before reporting to the file begins.
bool RemoveTextWriters ()
Removes all text writers from the TextWriter subsystem. If appropriate, the corresponding text writer is closed.
bool RemoveTextWriter ()
Removes the default text writer from the TextWriter subsystem. If appropriate, the corresponding text writer is closed.
bool RemoveTextWriter (TextWriter writer)
Removes the first object from Writers that contains the specified TextWriter. If appropriate, the corresponding text writer is closed.
bool RemoveTextWriter (Stream stream)
Removes the first object from Writers whose TextWriter has been created form the specified stream. If appropriate, the corresponding text writer is closed.
bool RemoveTextWriter (string filename)
Removes the first object from Writers whose TextWriter has been created form the file with the specified name. If appropriate, the corresponding text writer is closed.
List< TextWriter > TextWriterWriters ()
Returns a list of all text writers that are currently used by the reporter's text writer. Only text writers that are actually writable are included.
List< TextWriter > TextWriterWriters (bool writableonly)
Returns a list of all text writers that are currently used by the reporter's text writer. Warning: Beware of thread safety issues! Blocks of code where the returned list is used should be enclosed in lock(reporter.lockobj){...} block (where reporter is the object through which this method was called).
int TextWriterNumWriters ()
Returns the current number of text writers used by the reporter's text logging module. Only text writers that are actually writable are counted.
int TextWriterNumWriters (bool writableonly)
Returns the current number of TextWriters used by the reporter's text logging module.
int TextWriterFlush ()
Flushes all text writers of the Writer's TextWriter subsystem.
int TextWriterWrite (string str)
Writes a string to all text writers of the Writer's TextWriter subsystem.
int TextWriterWriteLine (string str)
Similar to TextWriterWrite(), except that a newline is added at the end of the string.
bool SetTextLogger (TextWriter writer)
Sets the text writer to which reporting is also performed.
bool SetTextLogger (TextWriter writer, bool writeintro)
Sets the basic text writer to which reporting is performed, but overrides the writeintro property by the 'writeintro' argument.
bool SetTextLogger (TextWriter writer, bool writeintro, bool disposewriter)
Sets the basic text writer to which reporting is performed, but overrides the writeintro property by the 'writeintro' argument.
bool SetTextLogger (Stream stream)
Creates a TextWriter upon the stream and sets it as the text writer to which reporting is also performed.
bool SetTextLogger (Stream stream, bool writeintro)
Creates a TextWriter upon the stream and sets it as the basic TextWriter to which reporting is performed. Overrides the writeintro property by the 'writeintro' argument.
bool SetTextLogger (Stream stream, bool writeintro, bool disposewriter)
Creates a TextWriter upon the stream and sets it as the basic TextWriter to which reporting is performed. Overrides the writeintro property by the 'writeintro' argument.
bool SetTextLogger (string filename)
Creates a TextWriter upon a file and sets it as the basic TextWriter to which reporting is also performed. The file is overwritten.
bool SetTextLogger (string filename, bool append)
Creates a TextWriter upon a file and sets it as the basic TextWriter to which reporting is also performed, where the caller specifies either to overwrite the file or to append to it.
bool SetTextLogger (string filename, bool append, bool writeintro)
Creates a TextWriter upon a file and sets it as the text writer to which reporting is also performed. The caller specifies whether to overwrite the file or to append to it, and whether the introductory text is written before reporting to the file begins.
bool SetTextLogger (string filename, bool append, bool writeintro, bool disposewriter)
Creates a TextWriter upon a file and sets it as the text writer to which reporting is also performed. The caller specifies whether to overwrite the file or to append to it, and whether the introductory text is written before reporting to the file begins.
bool AddTextLogger (TextWriter writer)
Sets the text writer to which reporting is also performed.
bool AddTextLogger (TextWriter writer, bool writeintro)
Sets the basic text writer to which reporting is performed, but overrides the writeintro property by the 'writeintro' argument.
bool AddTextLogger (TextWriter writer, bool writeintro, bool disposewriter)
Sets the basic text writer to which reporting is performed, but overrides the writeintro property by the 'writeintro' argument.
bool AddTextLogger (Stream stream)
Creates a TextWriter from the stream and adds it to the list of TextWriters on which reporting is also performed.
bool AddTextLogger (Stream stream, bool writeintro)
Creates a TextWriter from the stream and adds it to the list of TextWriters on which reporting is also performed. Overrides the writeintro property by the 'writeintro' argument.
bool AddTextLogger (Stream stream, bool writeintro, bool disposewriter)
Creates a TextWriter from the stream and adds it to the list of TextWriters on which reporting is also performed. Overrides the writeintro property by the 'writeintro' argument.
bool AddTextLogger (string filename)
Creates a TextWriter from the file name and adds it to the list of TextWriters on which reporting is also performed. The file is overwritten.
bool AddTextLogger (string filename, bool append)
Creates a TextWriter from the stream and adds it to the list of TextWriters on which reporting is also performed. The caller specifies either to overwrite the file or to append to it.
bool AddTextLogger (string filename, bool append, bool writeintro)
Creates a TextWriter from the stream and adds it to the list of TextWriters on which reporting is also performed. The caller specifies whether to overwrite the file or to append to it, and whether the introductory text is written before reporting to the file begins.
bool AddTextLogger (string filename, bool append, bool writeintro, bool disposewriter)
Creates a TextWriter from the stream and adds it to the list of TextWriters on which reporting is also performed. The caller specifies whether to overwrite the file or to append to it, and whether the introductory text is written before reporting to the file begins.
bool RemoveTextLoggers ()
Removes all text writers from the TextLogger subsystem. If appropriate, the corresponding text writer is closed.
bool RemoveTextLogger ()
Removes the default text writer from the TextLogger subsystem. If appropriate, the corresponding txt writer is closed.
bool RemoveTextLogger (TextWriter writer)
Removes the first object from Loggers that contains the specified TextWriter. If appropriate, the corresponding text writer is closed.
bool RemoveTextLogger (Stream stream)
Removes the first object from Loggers whose TextWriter has been created form the specified stream. If appropriate, the corresponding text writer is closed.
bool RemoveTextLogger (string filename)
Removes the first object from Loggers whose TextWriter has been created form the file with the specified name. If appropriate, the corresponding text writer is closed.
List< TextWriter > TextLoggerWriters ()
Returns a list of all text writers that are currently used by the reporter's text logger. Only text writers that are actually writable are included.
List< TextWriter > TextLoggerWriters (bool writableonly)
Returns a list of all text writers that are currently used by the reporter's text logger. Warning: Beware of thread safety issues! Blocks of code where the returned list is used should be enclosed in lock(reporter.lockobj){...} block (where reporter is the object through which this method was called).
int TextLoggerNumWriters ()
Returns the current number of text writers used by the reporter's text logging module. Only text writers that are actually writable are counted.
int TextLoggerNumWriters (bool writableonly)
Returns the current number of TextWriters used by the reporter's text logging module.
int TextLoggerFlush ()
Flushes all text writers of the Writer's TextLogger subsystem.
int TextLoggerWrite (string str)
Writes a string to all text writers of the Writer's TextLogger subsystem.
int TextLoggerWriteLine (string str)
Similar to TextLoggerWrite(), except that a newline is added at the end of the string.
Static Public Member Functions
static Exception ReviseException (Exception ex, string messageaddition, Type newtype, bool sametype, bool keepmessage, bool oldasinner)
Takes an existing exception and returns a modified exception based on it.
static Exception ReviseException (Exception ex, string messageaddition)
Takes an existing exception and returns a modified exception based on it. The returned exception is of the same type as the original one. Original message is appended to messageaddition . The created exception does not have an inner exception.
static Exception ReviseException (Exception ex, string messageaddition, bool keepmessage)
Takes an existing exception and returns a modified exception based on it. The returned exception is of the same type as the original one. The created exception does not have an inner exception.
static Exception ReviseException (Exception ex, string messageaddition, bool keepmessage, bool oldasinner)
Takes an existing exception and returns a modified exception based on it. The returned exception is of the same type as the original one.
static Exception ReviseException (Exception ex, string messageaddition, Type newtype)
Takes an existing exception and returns a modified exception based on it. Original message is appended to messageaddition . The created exception does not have an inner exception.
static Exception ReviseException (Exception ex, string messageaddition, Type newtype, bool keepmessage)
Takes an existing exception and returns a modified exception based on it. The created exception does not have an inner exception.
static Exception ReviseException (Exception ex, string messageaddition, Type newtype, bool keepmessage, bool oldasinner)
Takes an existing exception and returns a modified exception based on it.
static void GetAppSetting (string key, ref string value, out bool assigned)
Reads a string value from the application configuration file (e.g. app.config) and assigns it to the specified variable.
static void GetAppSetting (string key, ref char value, out bool assigned)
Reads a character value from the application configuration file and assigns it to the specified variable.
static void GetAppSetting (string key, ref List< char > value, out bool assigned)
Reads a list of characters from the application configuration file and assigns it to the specified variable.
static void GetAppSetting (string key, ref int value, out bool assigned)
Reads an integer value from the application configuration file and assigns it to the specified variable.
static void GetAppSetting (string key, ref double value, out bool assigned)
Reads a floating point value from the application configuration file and assigns it to the specified variable.
static void GetAppSetting (string key, ref bool value, out bool assigned)
Reads a boolean value from the application configuration file and assigns it to the specified variable. Numerical representation is allowed (0 for false, non-zero for true)
static void GetAppSetting (string key, ref bool value, out bool assigned, bool otherformatsallowed)
Reads a boolean value from the application configuration file and assigns it to the specified variable.
static string GetAppSettingsValue (string key)
Returns configuration value corresponding to the configuration key in AppSettings (specified by key)
static void GetAppSetting (string key, ref ReportLevel value, out bool assigned)
Reads an integer value from the application configuration file and assigns it to the specified variable.
static bool DoLaunch (ReportType reptype, ReportLevel replevel)
Returns true if the report of a given type will be launched at the given reporting level, and false if not.
static EventLogEntryType ReportType2EventLogEntryType (ReportType rt)
Returns the System.Diagnostics.EventLogEntryType value corresponding to the given ReportType. Remark: FailureAudit and SuccessAudit can not be generated because they don't have representation in ReportType.
static ReportType EventLogEntryType2ReportType (EventLogEntryType el)
Returns the ReportType value corresponding to the given System.Diagnostics.EventLogEntryType. Remark: FailureAudit and SuccessAudit do not have representation in ReportType and are mapped to Error and Warning, respectively.
static TraceLevel ReportLevel2TraceLevel (ReportLevel level)
Returns the System.Diagnostics.TraceLevel value corresponding to the given ReportLevel.
static ReportLevel TraceLevel2ReportLevel (TraceLevel tl)
Returns the ReportLevel value corresponding to the given System.Diagnostics.TraceLevel.
static string FormatLogMsgDefault (int depth, int initialindent, int indentincrement, char indentchar, ReportType type, string location, string message, ReportSource source)
Formats a one-line message for tracing output.
static string FormatTraceMsgDefault (int depth, int initialindent, int indentincrement, char indentchar, ReportType type, string location, string message, ReportSource source)
Formats a one-line message for tracing output.
static string DefaultReportStringMessageBox (ReporterBase reporter, ReportType messagetype, string errorlocation, string errormessage)
Auxiliary method that composes the complete message, including decoration, for reports launched in a message box.
static string DefaultReportStringConsole (ReporterBase reporter, ReportType messagetype, string errorlocation, string errormessage)
Auxiliary method that composes the complete message, including decoration, for reports launched in consoles.
static string DefaultReportStringConsoleTimeStamp (ReporterBase reporter, ReportType messagetype, string errorlocation, string errormessage)
Auxiliary method that composes the complete message, including decoration with a TIMESTAMP, for reports launched in consoles.
static string DefaultReportStringConsoleBas (ReporterBase reporter, ReportType messagetype, string errorlocation, string errormessage, bool timestamp)
Base method for DefaultReportStringConsole and DefaultReportStringConsoleTimeStamp.
static void DefaultReportConsole (ReporterBase reporter, ReportType messagetype, string errorlocation, string errormessage)
Default delegate for reporting. For parameter descriptions, see ReportDlg.
static string DefaultLocationString (ReporterBase reporter, ReportType messagetype, string location, Exception ex)
Default delegate for assembly of the location string when reporting on consoles. For parameter descriptions, see ReportMessageDlg.
static string DefaultMessageString (ReporterBase reporter, ReportType messagetype, string basicmessage, Exception ex)
Default delegate for message assembly of the message string when reporting on consoles. For parameter descriptions, see ReportMessageDlg.
static string DefaultReserveReportMessage (ReporterBase reporter, ReportType messagetype, string location, string message, Exception ex, Exception ex1)
Default function function for assembling reserve error reporting message. This is put outside the DefaultReserveReportError() method such that the same assembly method can be used in different systems. The method is considered bulletproof.
static void DefaultReserveReportError (ReporterBase reporter, ReportType messagetype, string location, string message, Exception ex, Exception ex1)
Default function function for reserve error reporting (called if an exception is thrown in a reporting function). Writes a report to the application's standard console (if defined) and Reporter's text writers and loggers (when defined). Writing is unconditional (e.g., even if reporter.UseTextWriter = false or reporter.ReportingLevel = Off, a message is written to the TextWriter's output streams).
static string ErrorLocationString0 (Exception ex)
Returns location string derived from ex, which includes information about the location where error occurred, specified by the source file name, function and line and column numbers.
static string ErrorLocationString0 (string location, Exception ex)
Returns Error location string derived from ex, which includes information about location of error occurrence and is prepended by additional location information (such as class name)
static string GetErorString (Exception e)
Returns an error string that concisely describes information contained in the specific exception (including location where exception was thrown, and its message).
Public Attributes
ReportDelegate ReportDlg = null
Delegate that performs error reporting. It calls delegates ReportDlg to assemble error location information and ReportMessageDlg to assemble error message. Then it uses both to assemble the final decorated error message and launches it in its own way.
ReportLocationDelegate ReportLocationDlg = null
Delegate that assembles the error location string.
ReportMessageDelegate ReportMessageDlg = null
Delegate that assembles the eror message string.
ReserveReportErrorDelegate ReserveReportErrorDlg = null
Delegate that reports an error when the error reporting function throws an exception. Functions assigned to this delegate should really be BULLETPROOF. If not assigned then the internal method of the corresponding class is called. It is highly recommended to do reporting in small steps enclosed in try/catch blocks and especially to use the error reporting object very carefully (because it may not be initialized properly, which can also be the reason that the error reporting function crashes). It is higly recommended to first call the DefaultReserveReportError() within the function assigned to this delegate, or at least to use the DefaultReserveReportMessage() method for assembly of the message shown.
bool DebugMode = false
Indicates that reporting suitable for debugging mode should be performed. A standard flag that can be used by the delegate functions.
ReportDelegate ReportDlgTextWriter = new ReportDelegate(DefaultReport_TextWriter)
Delegate that performs reporting (actually logging) via text writer.
ReportLocationDelegate ReportLocationDlgTextWriter = new ReportLocationDelegate(DefaultReportLocation_TextWriter)
Delegate that assembles the location string for reporting via TextWriter.
ReportMessageDelegate ReportMessageDlgTextWriter = new ReportMessageDelegate(DefaultReportMessage_TextWriter)
Delegate that assembles the message string for reporting via text writer.
ReportDelegate ReportDlgTextLogger = new ReportDelegate(DefaultReport_TextLogger)
Delegate that performs reporting (actually logging) via text writer.
ReportLocationDelegate ReportLocationDlgTextLogger = new ReportLocationDelegate(DefaultReportLocation_TextLogger)
Delegate that assembles the location string for reporting via text logger.
ReportMessageDelegate ReportMessageDlgTextLogger = new ReportMessageDelegate(DefaultReportMessage_TextLogger)
Delegate that assembles the message string for reporting via text writer.
ReportSource MsgSource = ReportSource.Unknown
Indicates the source of the message (such as client, server, web service, etc.)
ReportDelegate ReportDlgTrace = new ReportDelegate(DefaultReport_Trace)
Delegate that performs reporting (logging) via Pado trace mechanism. It calls delegates ReportDlg to assemble error location information and ReportMessageDlg to assemble error message. Then it uses both to assemble the final decorated error message and launches it in its own way.
ReportLocationDelegate ReportLocationDlgTrace = new ReportLocationDelegate(DefaultReportLocation_Trace)
Delegate that assembles the error location string for reporting (logging) via Pado trace mechanism.
ReportMessageDelegate ReportMessageDlgTrace = new ReportMessageDelegate(DefaultReportMessage_Trace)
Delegate that assembles the eror message string for reporting (logging) via Pado trace mechanism.
Static Public Attributes
static bool ReadGlobalAppSettings = true
Indicates whether a global Reporter (or its derived class) should read settings from the application configuration file when initialized (default is true).
Protected Member Functions
virtual void SetDefaultReportDlg ()
Sets the error reporting delegate to the default value.
virtual void SetDefaultReportLocationDlg ()
Sets the error location assembling delegate to the default value. This default delegate does not utilize the auxiliary object (and can be mixed with the delegates that do.)
virtual void SetDefaultReportMessageDlg ()
Sets the error message assembling delegate to the default value. This default delegate does not utilize the auxiliary object (and can be mixed with the delegates that do.)
virtual void SetDefaultReserveReportErrorDlg ()
Sets the reserve error reporting delegate to the default value.
virtual void InitBegin ()
Initial part of initialization. Auxiliary object is not affected because default delegates do not utilize it.
virtual void InitEnd ()
Finalizing part of initialization. Auxiliary object is not affected because default delegates do not utilize it.
virtual void Dispose (bool disposing)
void GetAppSetting (string reportername, string keyroot, ref string value, out bool assigned)
Reads a string value from the application configuration file (e.g. app.config) and assigns it to the specified parameter of the reporter.
void GetAppSetting (string reportername, string keyroot, ref char value, out bool assigned)
Reads a character value from the application configuration file (e.g. app.config) and assigns it to the specified parameter of the reporter.
void GetAppSetting (string reportername, string keyroot, ref List< char > value, out bool assigned)
Reads a list of characters from the application configuration file (e.g. app.config) and assigns it to the specified parameter of the reporter.
void GetAppSetting (string reportername, string keyroot, ref int value, out bool assigned)
Reads an integer value from the application configuration file (e.g. app.config) and assigns it to the specified parameter of the reporter.
void GetAppSetting (string reportername, string keyroot, ref double value, out bool assigned)
Reads a numeric value from the application configuration file (e.g. app.config) and assigns it to the specified parameter of the reporter.
void GetAppSetting (string reportername, string keyroot, ref bool value, out bool assigned)
Reads a boolean value from the application configuration file (e.g. app.config) and assigns it to the specified parameter of the reporter.
void GetAppSetting (string reportername, string keyroot, ref ReportLevel value, out bool assigned)
Reads a ReportLevel enumeration value from the application configuration file (e.g. app.config) and assigns it to the specified parameter of the reporter.
void AppSettingsReadWarning (string groupname)
Launches an internal warning that the configuration settings belonging tot he specified group have already been read for this reporter. The warning is launched only if the settings have actually been read and if warnings of this type are switched on.
void MarkAppSettingsRead (string groupname)
Marks a specified group of settings as been read for the current reporter.
virtual void ReadAppSettingsBasic (string groupname)
Reads settings for a specified named group of reporters from the application configuration file. In the derived classes, this method should be overridden by the method that calls the base class' method.
void SyncReportLevelWithTraceSwitch (TraceSwitch tswitch, ref ReportLevel level)
Synchronizes the value of ReportLevel enumeration variable with the state of a TraceSwitch variable. Enumeration is synchronized according to the Level property of the switch.
void SyncTraceSwitchWithReportLevel (ReportLevel level, TraceSwitch tswitch)
Synchronizes the state of a TraceSwitch object with the value of the ReportLevel enumeration.
virtual void ReserveReportErrorSpecific (ReportType messagetype, string location, string message, Exception ex, Exception ex1)
Reportinf of internal reporter errors for the specific reporter class (overridden in derived classes). This method is called for internal error reports when the delegate for this job is not defined.
void ReserveReportError (ReportType messagetype, string location, string message, Exception ex, Exception ex1)
Used to report internal errors of the reporter. Designed to be bullet proof in order to ensure that improper behavior of the reporting system does not remain unnoticed.
virtual void PrintIntro (TextWriter tw, string introtext, string programname)
Writes to a textwriter the introduction text that is usually printed before logging starts.
bool SetTW (ref TextWriter tw, ref bool disptw, TextWriter writer, bool writeintro, bool disposewriter)
Sets the basic text writer to which reporting is performed, but overrides the writeintro property by the 'writeintro' argument.
bool SetTW (ref TextWriter tw, ref bool disptw, Stream stream, bool writeintro, bool disposewriter)
Creates a TextWriter upon the stream and sets it as the basic TextWriter to which reporting is performed. Overrides the writeintro property by the 'writeintro' argument.
bool AddTW (ref List< TWClass > lwriters, TextWriter writer, bool writeintro, bool disposewriter)
Adds another TextWriter to which reporting will also be performed.
bool AddTW (ref List< TWClass > lwriters, Stream stream, bool writeintro, bool disposewriter)
Creates a TextWriter from the stream and adds it to the list of TextWriters on which reporting is also performed. Overrides the writeintro property by the 'writeintro' argument.
bool AddTW (ref List< TWClass > lwriters, string filename, bool append, bool writeintro, bool disposewriter)
Creates a TextWriter from a specific file and adds it to the list of TextWriters on which reporting is also performed. The caller specifies whether to overwrite the file or to append to it, and whether the introductory text is written before reporting to the file begins.
bool RemoveTW (List< TWClass > lwriters, TextWriter writer)
Removes the first object from a list that contains the specified TextWriter.
bool RemoveTW (List< TWClass > lwriters, Stream stream)
Removes the first object from a list whose TextWriter has been created form the specified stream.
bool RemoveTW (List< TWClass > lwriters, string filename)
Removes the first object from a list whose TextWriter has been created form the file with the specified name.
virtual void TextWriterPrintIntro (TextWriter tw)
Writes to a textwriter the introduction text that is usually printed before logging starts.
virtual void Report_TextWriter (ReportType messagetype, string location, string message, Exception ex)
Launches a report via text writers. Report is launched by using special delegates for this kind of reporting. If the corresponding delegates for error location and message are not specified then general delegates are used for this purporse, or location and message string are simple assembled by this function.
virtual void TextLoggerPrintIntro (TextWriter tw)
Writes to a textwriter the introduction text that is usually printed before logging starts.
virtual void Report_TextLogger (ReportType messagetype, string location, string message, Exception ex)
Launches a report via text logger. Report is launched by using special delegates for this kind of reporting. If the corresponding delegates for error location and message are not specified then general delegates are used for this purporse, or location and message string are simple assembled by this function.
virtual void Report_Trace (ReportType messagetype, string location, string message, Exception ex)
Launches a report via Trace. Report is launched by using special delegates for this kind of reporting. If the corresponding delegates for error location and message are not specified then general delegates are used for this purporse, or location and message string are simple assembled by this function.
Static Protected Member Functions
static string FullKey (string reportername, string keyroot)
Returns a full keyroot of a specific configuration item with a reporter name specified.
static void DefaultReport_TextWriter (ReporterBase reporter, ReportType messagetype, string location, string message)
Default delegate for launching reports (actually logging reports) via text writer.
static string DefaultReportLocation_TextWriter (ReporterBase reporter, ReportType messagetype, string location, Exception ex)
Delegate for assembling a location string for this kind of report.
static string DefaultReportMessage_TextWriter (ReporterBase reporter, ReportType messagetype, string basicmessage, Exception ex)
Delegate for assembling a report message for this kind of report.
static void DefaultReport_TextLogger (ReporterBase reporter, ReportType messagetype, string location, string message)
Default delegate for launching reports (actually logging reports) via text writer.
static string DefaultReportLocation_TextLogger (ReporterBase reporter, ReportType messagetype, string location, Exception ex)
Delegate for assembling a location string for this kind of report.
static string DefaultReportMessage_TextLogger (ReporterBase reporter, ReportType messagetype, string basicmessage, Exception ex)
Delegate for assembling a report message for this kind of report.
static void DefaultReport_Trace (ReporterBase reporter, ReportType messagetype, string location, string message)
Delegat for launching a report via Trace.
static string DefaultReportLocation_Trace (ReporterBase reporter, ReportType messagetype, string location, Exception ex)
Delegate for assembling a location string for this kind of report.
static string DefaultReportMessage_Trace (ReporterBase reporter, ReportType messagetype, string basicmessage, Exception ex)
Delegate for assembling a report message for this kind of report.
Protected Attributes
TraceSwitch _ReportingSwitch = null
object _lockobj = new Object()
Static Protected Attributes
const string KeyPrefix = "ReporterMsg"
const string KeyLevelOn = "LevelOn"
Properties
static bool GlobalInitialized [get]
Gets the value indicating whether the global reporter of this class has already been initialized.
static ReporterBase Global [get, private set]
Gets the global reporter object. This is typically used for configuring the global reporter.
bool AppSettingsWarnings [get, set]
Gets or sets the flag that specifies whether a warning message is launched when reading of application settings is attempted more than once for the same named group of settings.
bool IsGlobal [get, protected set]
Indicates whether the current reporter is used as a global reporter or not.
int Depth [get, set]
Gets or sets the current indentation level for on-line output. This should normally be done by calling IncreaseDepth() or DecreaseDepth().
int TextLoggerIndentInitial [get, set]
Gets or sets number fo initial indentation charactyers.
int TextLoggerIndentSpacing [get, set]
Gets or sets the number of indentation characters written per indentation level.
char TextLoggerIndentCharacter [get, set]
Gets or sets the indentation character.
ReportLevel ReportingLevel [get, set]
Gets or sets level of output for reporting (console output, message boxes, etc.).
ReportLevel LoggingLevel [get, set]
Gets or sets level of output for logging (writing to log files).
ReportLevel TracingLevel [get, set]
Gets or sets trace level (for external trace systems).
bool TreatError [get]
Returns a boolean value indicating whether errors are treated by the reporter in its current state.
bool TreatWarning [get]
Returns a boolean value indicating whether warnings are treated by the reporter in its current state.
bool TreatInfo [get]
Returns a boolean value indicating whether info messages are treated by the reporter in its current state.
bool TreatUndefined [get]
Returns a boolean value indicating whether undefined messages with the lowest priority are treated by the reporter in its current state.
ReportLevel Level [get, set]
Gets the level with the lowesst priority (out of reporting, logging and tracing level), or sets all levels to the assigned level.
virtual bool this[ReportLevel level] [get, set]
Indexer that returns true if messages of a given level are treated by the reporter (either by the reporting, logging or tracing part, according to the corresponding level states), or false if not (i.e. if all the levels are set lover than the index). In the case of assignment, when true is assigned, all levels that are set lower than the are set to index. Assignment with false should be used only exteptionally; but in this case all levels that are set higher or equal than the index are set one level below.
TraceSwitch ReportingSwitch [get, set]
Gets or sets the TraceSwitch that is synchronized with ReportingLevel. IMPORTANT: State of the object obtained by get accessor must not be changed unless the object is assigned back by the set accessor. If one wants that this TraceSwitch assumes values specified by the configuration file, a corresponding Traceswitch must be created and assigned to this property (otherwise the TraceSwitch will be synchronized with the ReportingLevel, which will override its settings).
TraceSwitch LoggingSwitch [get, set]
Gets or sets the TraceSwitch that is synchronized with LoggingLevel. IMPORTANT: State of the object obtained by get accessor must not be changed unless the object is assigned back by the set accessor. If one wants that this TraceSwitch assumes values specified by the configuration file, a corresponding Traceswitch must be created and assigned to this property (otherwise the TraceSwitch will be synchronized with the LoggingLevel, which will override its settings).
TraceSwitch TracingSwitch [get, set]
Gets or sets the TraceSwitch that is synchronized with TracingLevel. IMPORTANT: State of the object obtained by get accessor must not be changed unless the object is assigned back by the set accessor. If one wants that this TraceSwitch assumes values specified by the configuration file, a corresponding Traceswitch must be created and assigned to this property (otherwise the TraceSwitch will be synchronized with the TracingLevel, which will override its settings).
bool ThrowTestException [get, set]
If true then the basic reporting function will throw an exception. This is intended predominantly for testing how the reporter behaves in case of internal errors. When the exception is thrown, the value is set back to false. If we want an exception to be thrown again then the value must be set to true once again.
object Obj [get, set]
Auxiliary object used by the delegates that perform error reporting. The object is used to provide additional information used in error reporting, or to provide objects that perform some actions in error reporting tasks, or both. It is left entirely to error reporting delegates to interpret the object's contents.
virtual object lockobj [get]
Object used for locking.
bool UseTextWriter [get, set]
Gets or sets the flag specifying whether reporting using a text writer is performed or not.
bool TextWriterFlushing [get, set]
Gets or sets the flag that tells whether or not the text writers are flushed after every message that is reported through them.
string TextWriterIntroText [get, set]
Gets or sets the introduction string that is written before logging to a TextWriter begins. If this is not specified then the reporter composes its own introduction string, eventually using programname (when defined).
string TextWriterProgramName [get, set]
String denoting the name of the program or other entity that uses the Reporter for logging. When introtext is not specified, this name is used in the introduction text composed by the reporter.
bool TextWriterWriteIntro [get, set]
Specifies whether introduction text is written before logging of messages begins or not.
bool UseTextLogger [get, set]
Gets or sets the flag specifying whether reporting using a text writer is performed or not.
bool TextLoggerFlushing [get, set]
Gets or sets the flag that tells whether or not the text writers are flushed after every message that is reported through them.
string TextLoggerIntroText [get, set]
Gets or sets the introduction string that is written before logging to a TextWriter begins. If this is not specified then the reporter composes its own introduction string, eventually using programname (when defined).
string TextLoggerProgramName [get, set]
String denoting the name of the program or other entity that uses the Reporter for logging. When introtext is not specified, this name is used in the introduction text composed by the reporter.
bool TextLoggerWriteIntro [get, set]
Specifies whether introduction text is written before logging of messages begins or not.
bool UseTrace [get, set]
Gets or sets the flag specifying whether reporting using the pado trace is performed or not.
Properties inherited from IG.Lib.IReporterBase
bool AppSettingsWarnings [get, set]
Gets or sets the flag that specifies whether a warning message is launched when reading of application settings is attempted more than once for the same named group of settings.
bool IsGlobal [get]
Indicates whether the current reporter is used as a global reporter or not.
int Depth [get, set]
Gets or sets the current indentation level for on-line output. This should normally be done by calling IncreaseDepth() or DecreaseDepth().
ReportLevel ReportingLevel [get, set]
Gets or sets level of output for reporting (console output, message boxes, etc.).
ReportLevel LoggingLevel [get, set]
Gets or sets level of output for logging (writing to log files).
ReportLevel TracingLevel [get, set]
Gets or sets trace level (for external trace systems).
bool TreatError [get]
Returns a boolean value indicating whether errors are treated by the reporter in its current state.
bool TreatWarning [get]
Returns a boolean value indicating whether warnings are treated by the reporter in its current state.
bool TreatInfo [get]
Returns a boolean value indicating whether info messages are treated by the reporter in its current state.
bool TreatUndefined [get]
Returns a boolean value indicating whether undefined messages with the lowest priority are treated by the reporter in its current state.
ReportLevel Level [get, set]
Gets the level with the lowesst priority (out of reporting, logging and tracing level), or sets all levels to the assigned level.
bool this[ReportLevel level] [get, set]
Indexer that returns true if messages of a given level are treated by the reporter (either by the reporting, logging or tracing part, according to the corresponding level states), or false if not (i.e. if all the levels are set lover than the index). In the case of assignment, when true is assigned, all levels that are set lower than the are set to index. Assignment with false should be used only exteptionally; but in this case all levels that are set higher or equal than the index are set one level below.
TraceSwitch ReportingSwitch [get, set]
Gets or sets the TraceSwitch that is synchronized with ReportingLevel. IMPORTANT: State of the object obtained by get accessor must not be changed unless the object is assigned back by the set accessor. If one wants that this TraceSwitch assumes values specified by the configuration file, a corresponding Traceswitch must be created and assigned to this property (otherwise the TraceSwitch will be synchronized with the ReportingLevel, which will override its settings).
TraceSwitch LoggingSwitch [get, set]
Gets or sets the TraceSwitch that is synchronized with LoggingLevel. IMPORTANT: State of the object obtained by get accessor must not be changed unless the object is assigned back by the set accessor. If one wants that this TraceSwitch assumes values specified by the configuration file, a corresponding Traceswitch must be created and assigned to this property (otherwise the TraceSwitch will be synchronized with the LoggingLevel, which will override its settings).
TraceSwitch TracingSwitch [get, set]
Gets or sets the TraceSwitch that is synchronized with TracingLevel. IMPORTANT: State of the object obtained by get accessor must not be changed unless the object is assigned back by the set accessor. If one wants that this TraceSwitch assumes values specified by the configuration file, a corresponding Traceswitch must be created and assigned to this property (otherwise the TraceSwitch will be synchronized with the TracingLevel, which will override its settings).
object Obj [get, set]
Auxiliary object used by the delegates that perform error reporting.
object lockobj [get]
Object used for locking.
Properties inherited from IG.Lib.IReporterTextWriter
bool UseTextWriter [get, set]
Specifies whether or not TextWriter(s) are used by the Reporter to log messages.
string TextWriterIntroText [get, set]
Gets or sets the introduction string that is written before logging to a TextWriter begins. If this is not specified then the reporter composes its own introduction string, eventually using programname (when defined).
string TextWriterProgramName [get, set]
String denoting the name of the program or other entity that uses the Reporter for logging. When introtext is not specified, this name is used in the introduction text composed by the reporter.
bool TextWriterWriteIntro [get, set]
Specifies whether introduction text is written before logging of messages begins or not.
Properties inherited from IG.Lib.IReporterTextLogger
bool UseTextLogger [get, set]
Specifies whether or not TextLogger(s) are used by the Reporter to log messages.
int TextLoggerIndentInitial [get, set]
Gets or sets number fo initial indentation charactyers.
int TextLoggerIndentSpacing [get, set]
Gets or sets the number of indentation characters written per indentation level.
char TextLoggerIndentCharacter [get, set]
Gets or sets the indentation character.
string TextLoggerIntroText [get, set]
Gets or sets the introduction string that is written before logging to a TextLogger begins. If this is not specified then the reporter composes its own introduction string, eventually using programname (when defined).
string TextLoggerProgramName [get, set]
String denoting the name of the program or other entity that uses the Reporter for logging. When introtext is not specified, this name is used in the introduction text composed by the reporter.
bool TextLoggerWriteIntro [get, set]
Specifies whether introduction text is written before logging of messages begins or not.
Properties inherited from IG.Lib.IReporterTrace
bool UseTrace [get, set]
Private Member Functions
~ReporterBase ()
void SyncLevels ()
int FindTW (List< TWClass > lwriters, TextWriter writer)
Returns the first object on the list that contains a specific TextWriter.
int FindTW (List< TWClass > lwriters, Stream stream)
Returns the first object on the list whose TextWriter has been created from the specific Stream.
int FindTW (List< TWClass > lwriters, string filename)
Returns the first object on the list whose TextWriter has been created from a file with the specific name.
Static Private Member Functions
static void Test ()
Private Attributes
bool isDisposed = false
bool dispLocked = false
List< String > readconf = null
bool _AppSettingsWarnings = true
bool TextWriterAppend = false
bool TextLoggerAppend = false
bool _IsGlobal = false
int _Depth = 0
int _IndentSpacing = 2
int _InitialIndent =0
char _IndentCharacter = ' '
ReportLevel _ReportingLevel = DefaultReportingLevel
ReportLevel _LoggingLevel = DefaultLoggingLevel
ReportLevel _TracingLevel = DefaultTracingLevel
bool _TreatError
double DDD
TraceSwitch _LoggingSwitch = null
TraceSwitch _TracingSwitch = null
bool _ThrowTestException = false
object _obj = null
bool _UseTextWriter = true
bool _TextWriterFlushing = false
TextWriter Writer = null
bool DisposeWriter = false
List< TWClass > Writers = new List<TWClass>()
string _TextWriterIntroText = null
string _TextWriterProgramName = null
bool _TextWriterWriteIntro = true
bool _UseTextLogger = false
bool _TextLoggerFlushing = true
TextWriter Logger = null
bool DisposeLogger = false
List< TWClass > Loggers = new List<TWClass>()
string _TextLoggerIntroText = null
string _TextLoggerProgramName = null
bool _TextLoggerWriteIntro = true
bool _UseTrace = false
Static Private Attributes
static ReporterBase _Global = null
static bool _GlobalInitialized = false
static object GlobalLock = new object()
const string KeyLevelOff = "LevelOff"
const string KeyReportingLevel = "ReportingLevel"
const string KeyLoggingLevel = "LoggingLevel"
const string KeyTracingLevel = "TracingLevel"
const string KeyUseTextWriter = "UseTextWriter"
const string KeyUseTextLogger = "UseTextLogger"
const string KeyUseTrace = "UseTrace"
const string KeyTextWriterAppend = "TextWriterAppend"
const string KeyTextWriterFile = "TextWriterFile"
const string KeyTextWriterFile1 = "TextWriterFile1"
const string KeyTextWriterWriteIntro = "TextWriterWriteIntro"
const string KeyTextWriterProgramName = "TextWriterProgramName"
const string KeyTextWriterIntroText = "TextWriterIntroText"
const string KeyTextLoggerAppend = "TextLoggerAppend"
const string KeyTextLoggerFile = "TextLoggerFile"
const string KeyTextLoggerFile1 = "TextLoggerFile1"
const string KeyTextLoggerWriteIntro = "TextLoggerWriteIntro"
const string KeyTextLoggerProgramName = "TextLoggerProgramName"
const string KeyTextLoggerIntroText = "TextLoggerIntroText"
const string KeyTextLoggerIndentInitial = "TextLoggerIndentInitial"
const string KeyTextLoggerIndentSpacing = "TextLoggerIndentSpacing"
const string KeyTextLoggerIndentCharacter = "TextLoggerIndentCharacter"
const string KeyAppSettingsWarnings = "AppSettingsWarnings"
static int numErrIndentLevel = 0
static int maxErrIndentLevel = 3
static int numErrInitialIndent = 0
static int maxErrInitialIndent = 3
static int numErrIndentSpacing = 0
static int maxErrIndentSpacing = 3
const ReportLevel DefaultReportingLevel = ReportLevel.Warning
const ReportLevel DefaultLoggingLevel = ReportLevel.Warning
const ReportLevel DefaultTracingLevel = ReportLevel.Info
static string _newLineReplacement = " ... "
Detailed Description
Base IGlib class for reporting, tracing and logging; provides a global reporter and a basis for creation of local reporters. This class is identical to the IGLib class (copied directly). IN EFA, refer to the derived class Reporter!
Definition at line 1181 of file ReporterMsg.cs.
Constructor & Destructor Documentation
ReporterBase() [1/5]
IG.Lib.ReporterBase.ReporterBase () inline
Constructor. Initializes all error reporting delegates to default values and sets auxliary object to null. Auxiliary object Obj is set to null.
Definition at line 1219 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.Init().
ReporterBase() [2/5]
IG.Lib.ReporterBase.ReporterBase (object obj, ReportDelegate reportdelegate, ReportLocationDelegate locationdelegate, ReportMessageDelegate messagedelegate, ReserveReportErrorDelegate reservereportdelegate) inline
Constructor. Initializes the error reporter by the specified auxiliary object and delegates used to perform error reporting tasks. Delegates that are not specified are set to default values.
Parameters
obj Auxiliary object that will be passed to error reporting delegates when called in local methods.
reportdelegate Delegates that is called to launc an error report. Methods of this class will pass to this class the auxiliary object, location strings assembled by the location assembling delegate, and error message string assembled by the error message delegate.
locationdelegate Delegate that is called to assemble the error location string. The Auxiliary object this.Obj will be internally passed to this delegate any time it is called.
messagedelegate Delegate that is called to assemble the error message (without decorations). The Auxiliary object this.Obj will be internally passed to this delegate any time it is called.
reservereportdelegate Delegate that is called to report exceptions that occur within error reporting methods. In particular, this must ne as bullet proof as possible.
Definition at line 1238 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.Init().
ReporterBase() [3/5]
IG.Lib.ReporterBase.ReporterBase (object obj, ReportDelegate reportdelegate, ReportLocationDelegate locationdelegate, ReportMessageDelegate messagedelegate) inline
Constructor. Initializes the error reporter by the specified auxiliary object and delegates used to perform error reporting tasks. Reserve error reporting delegate is initialized to a default value. Delegates that are not specified are set to default values.
Definition at line 1251 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.Init().
ReporterBase() [4/5]
IG.Lib.ReporterBase.ReporterBase (object obj, ReportDelegate reportdelegate) inline
Constructor. Initializes the error reporter by the specified auxiliary object and the delegate to perform error reporting tasks. Reserve error reporting delegate is initialized to a default value. Delegates for assembling the error location string and error message string are set to their default values, which are adapted to console-like eror reporting systems.
Definition at line 1264 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.Init().
ReporterBase() [5/5]
IG.Lib.ReporterBase.ReporterBase (object obj, ReportDelegate reportdelegate, ReserveReportErrorDelegate reservereportdelegate) inline
Constructor. Initializes the error reporter by the specified auxiliary object and delegates used to perform error reporting tasks. Delegates for assembling the error locatin and error message string are set to their default values, which are adapted to console-like eror reporting systems.
Parameters
obj Auxiliary object that will be passed to error reporting delegates when called in local methods.
reportdelegate Delegates that is called to launc an error report. Methods of this class will pass to this class the auxiliary object, location strings assembled by the location assembling delegate, and error message string assembled by the error message delegate.
reservereportdelegate Delegate that is called to report exceptions that occur within error reporting methods. In particular, this must ne as bullet proof as possible.
Definition at line 1279 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.Init().
~ReporterBase()
IG.Lib.ReporterBase.~ReporterBase () inline private
Definition at line 1473 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.Dispose().
Member Function Documentation
SetDefaultReportDlg()
virtual void IG.Lib.ReporterBase.SetDefaultReportDlg () inline protected virtual
Sets the error reporting delegate to the default value.
Reimplemented in IG.Lib.ReporterConsole.
Definition at line 1295 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.ReportDlg.
Referenced by IG.Lib.ReporterBase.InitEnd().
SetDefaultReportLocationDlg()
virtual void IG.Lib.ReporterBase.SetDefaultReportLocationDlg () inline protected virtual
Sets the error location assembling delegate to the default value. This default delegate does not utilize the auxiliary object (and can be mixed with the delegates that do.)
Reimplemented in IG.Lib.ReporterConsole.
Definition at line 1303 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.DefaultLocationString(), IG.Lib.ReportLocationDelegate(), and IG.Lib.ReporterBase.ReportLocationDlg.
Referenced by IG.Lib.ReporterBase.InitEnd().
SetDefaultReportMessageDlg()
virtual void IG.Lib.ReporterBase.SetDefaultReportMessageDlg () inline protected virtual
Sets the error message assembling delegate to the default value. This default delegate does not utilize the auxiliary object (and can be mixed with the delegates that do.)
Reimplemented in IG.Lib.ReporterConsole.
Definition at line 1311 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.DefaultMessageString(), IG.Lib.ReportMessageDelegate(), and IG.Lib.ReporterBase.ReportMessageDlg.
Referenced by IG.Lib.ReporterBase.InitEnd().
SetDefaultReserveReportErrorDlg()
virtual void IG.Lib.ReporterBase.SetDefaultReserveReportErrorDlg () inline protected virtual
Sets the reserve error reporting delegate to the default value.
Reimplemented in IG.Lib.ReporterConsole.
Definition at line 1318 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.ReserveReportErrorDlg.
Referenced by IG.Lib.ReporterBase.InitEnd().
InitBegin()
virtual void IG.Lib.ReporterBase.InitBegin () inline protected virtual
Initial part of initialization. Auxiliary object is not affected because default delegates do not utilize it.
Reimplemented in IG.Lib.ReporterConsole.
Definition at line 1327 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.Obj, IG.Lib.ReporterBase.ReportDlg, IG.Lib.ReporterBase.ReportLocationDlg, IG.Lib.ReporterBase.ReportMessageDlg, and IG.Lib.ReporterBase.ReserveReportErrorDlg.
Referenced by IG.Lib.ReporterBase.Init().
InitEnd()
virtual void IG.Lib.ReporterBase.InitEnd () inline protected virtual
Finalizing part of initialization. Auxiliary object is not affected because default delegates do not utilize it.
Reimplemented in IG.Lib.ReporterConsole.
Definition at line 1343 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.ReportDlg, IG.Lib.ReporterBase.ReportLocationDlg, IG.Lib.ReporterBase.ReportMessageDlg, IG.Lib.ReporterBase.ReserveReportErrorDlg, IG.Lib.ReporterBase.SetDefaultReportDlg(), IG.Lib.ReporterBase.SetDefaultReportLocationDlg(), IG.Lib.ReporterBase.SetDefaultReportMessageDlg(), and IG.Lib.ReporterBase.SetDefaultReserveReportErrorDlg().
Referenced by IG.Lib.ReporterBase.Init().
Init() [1/5]
void IG.Lib.ReporterBase.Init (object obj, ReportDelegate reportdelegate, ReportLocationDelegate locationdelegate, ReportMessageDelegate messagedelegate, ReserveReportErrorDelegate reservereportdelegate) inline
Initializes the error reporter by the specified auxiliary object and delegates used to perform error reporting tasks. Delegates that are not specified are set to default values.
Parameters
obj Auxiliary object that will be passed to error reporting delegates when called in local methods.
reportdelegate Delegates that is called to launc an error report. Methods of this class will pass to this class the auxiliary object, location strings assembled by the location assembling delegate, and error message string assembled by the error message delegate.
locationdelegate Delegate that is called to assemble the error location string. The Auxiliary object this.Obj will be internally passed to this delegate any time it is called.
messagedelegate Delegate that is called to assemble the error message (without decorations). The Auxiliary object this.Obj will be internally passed to this delegate any time it is called.
reservereportdelegate Delegate that is called to report exceptions that occur within error reporting methods. In particular, this must ne as bullet proof as possible.
Implements IG.Lib.IReporterBase.
Definition at line 1379 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.InitBegin(), IG.Lib.ReporterBase.InitEnd(), IG.Lib.ReporterBase.lockobj, and IG.Lib.ReporterBase.Obj.
Init() [2/5]
void IG.Lib.ReporterBase.Init () inline
Initializes all error reporting delegates to default values and sets auxliary object to null. Auxiliary object Obj is set to null.
Implements IG.Lib.IReporterBase.
Definition at line 1401 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.lockobj.
Referenced by IG.Lib.ReporterBase.Init(), IG.Lib.ReporterBase.ReporterBase(), and IG.Lib.ReporterConsole.ReporterConsole().
Init() [3/5]
void IG.Lib.ReporterBase.Init (object obj, ReportDelegate reportdelegate, ReportLocationDelegate locationdelegate, ReportMessageDelegate messagedelegate) inline
Initializes the error reporter by the specified auxiliary object and delegates used to perform error reporting tasks. Reserve error reporting delegate is initialized to a default value. Delegates that are not specified are set to default values.
Implements IG.Lib.IReporterBase.
Definition at line 1414 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.Init(), and IG.Lib.ReporterBase.lockobj.
Init() [4/5]
void IG.Lib.ReporterBase.Init (object obj, ReportDelegate reportdelegate) inline
Initializes the error reporter by the specified auxiliary object and the delegate to perform error reporting tasks. Reserve error reporting delegate is initialized to a default value. Delegates for assembling the error location string and error message string are set to their default values, which are adapted to console-like eror reporting systems.
Implements IG.Lib.IReporterBase.
Definition at line 1430 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.Init(), and IG.Lib.ReporterBase.lockobj.
Init() [5/5]
void IG.Lib.ReporterBase.Init (object obj, ReportDelegate reportdelegate, ReserveReportErrorDelegate reservereportdelegate) inline
Initializes the error reporter by the specified auxiliary object and delegates used to perform error reporting tasks. Delegates for assembling the error locatin and error message string are set to their default values, which are adapted to console-like eror reporting systems.
Parameters
obj Auxiliary object that will be passed to error reporting delegates when called in local methods.
reportdelegate Delegates that is called to launc an error report. Methods of this class will pass to this class the auxiliary object, location strings assembled by the location assembling delegate, and error message string assembled by the error message delegate.
reservereportdelegate Delegate that is called to report exceptions that occur within error reporting methods. In particular, this must ne as bullet proof as possible.
Implements IG.Lib.IReporterBase.
Definition at line 1449 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.Init(), and IG.Lib.ReporterBase.lockobj.
Dispose() [1/2]
void IG.Lib.ReporterBase.Dispose () inline
Definition at line 1480 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.~ReporterBase().
Dispose() [2/2]
virtual void IG.Lib.ReporterBase.Dispose (bool disposing) inline protected virtual
Definition at line 1485 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.dispLocked, IG.Lib.ReporterBase.isDisposed, IG.Lib.ReporterBase.RemoveTextLoggers(), IG.Lib.ReporterBase.RemoveTextWriters(), IG.Lib.ReporterBase.TextLoggerFlush(), and IG.Lib.ReporterBase.TextWriterFlush().
ReviseException() [1/7]
static Exception IG.Lib.ReporterBase.ReviseException (Exception ex, string messageaddition, Type newtype, bool sametype, bool keepmessage, bool oldasinner) inline static
Takes an existing exception and returns a modified exception based on it.
Parameters
ex Exception whose revised version is created.
messageaddition String that is prepended to the old message (when keepmessage is true) or forms the new message of the exception (when keepmessage is false)
newtype The type of the new exception. Applies when sametype is false and the specified type is valid, i.e. represents Exception or a derived type. Also applies when ex is null and the specified type is valid.
sametype If true then the an exception of the same type as the original one is created.
keepmessage If true then the original message is contained in the revised exception (it is simply appended to messageaddition)
oldasinner If true then the original exception is included as inner exception.
Returns
The revised exception (the original exception modified according to parameters).
Definition at line 1619 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.ReviseException().
ReviseException() [2/7]
static Exception IG.Lib.ReporterBase.ReviseException (Exception ex, string messageaddition) inline static
Takes an existing exception and returns a modified exception based on it. The returned exception is of the same type as the original one. Original message is appended to messageaddition . The created exception does not have an inner exception.
Parameters
ex Exception whose revised version is created.
messageaddition String that is prepended to the old message.
Definition at line 1671 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.ReviseException().
ReviseException() [3/7]
static Exception IG.Lib.ReporterBase.ReviseException (Exception ex, string messageaddition, bool keepmessage) inline static
Takes an existing exception and returns a modified exception based on it. The returned exception is of the same type as the original one. The created exception does not have an inner exception.
Parameters
ex Exception whose revised version is created.
messageaddition String that is prepended to the old message (when keepmessage is true) or forms the new message of the exception (when keepmessage is false)
keepmessage If false then the original message is not kept.
Definition at line 1689 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.ReviseException().
ReviseException() [4/7]
static Exception IG.Lib.ReporterBase.ReviseException (Exception ex, string messageaddition, bool keepmessage, bool oldasinner) inline static
Takes an existing exception and returns a modified exception based on it. The returned exception is of the same type as the original one.
Parameters
ex Exception whose revised version is created.
messageaddition String that is prepended to the old message (when keepmessage is true) or forms the new message of the exception (when keepmessage is false)
keepmessage If false then the original message is not kept.
oldasinner If true then the original original exception becomes the inner exception of the returned one.
Definition at line 1710 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.ReviseException().
ReviseException() [5/7]
static Exception IG.Lib.ReporterBase.ReviseException (Exception ex, string messageaddition, Type newtype) inline static
Takes an existing exception and returns a modified exception based on it. Original message is appended to messageaddition . The created exception does not have an inner exception.
Parameters
ex Exception whose revised version is created.
messageaddition String that is prepended to the old message or forms the new message of the exception.
newtype Type of the returned exception. If the parameter is null then the type will be Exception.
Definition at line 1734 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.ReviseException().
ReviseException() [6/7]
static Exception IG.Lib.ReporterBase.ReviseException (Exception ex, string messageaddition, Type newtype, bool keepmessage) inline static
Takes an existing exception and returns a modified exception based on it. The created exception does not have an inner exception.
Parameters
ex Exception whose revised version is created.
messageaddition String that is prepended to the old message (when keepmessage is true) or forms the new message of the exception (when keepmessage is false)
newtype Type of the returned exception. If the parameter is null then the type will be Exception.
keepmessage If false then the original message is not kept.
Definition at line 1752 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.ReviseException().
ReviseException() [7/7]
static Exception IG.Lib.ReporterBase.ReviseException (Exception ex, string messageaddition, Type newtype, bool keepmessage, bool oldasinner) inline static
Takes an existing exception and returns a modified exception based on it.
Parameters
ex Exception whose revised version is created.
messageaddition String that is prepended to the old message (when keepmessage is true) or forms the new message of the exception (when keepmessage is false)
newtype Type of the returned exception. If the parameter is null then the type will be Exception.
keepmessage If false then the original message is not kept.
oldasinner If true then the original original exception becomes the inner exception of the returned one.
Definition at line 1772 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.ReviseException().
GetAppSetting() [1/15]
static void IG.Lib.ReporterBase.GetAppSetting (string key, ref string value, out bool assigned) inline static
Reads a string value from the application configuration file (e.g. app.config) and assigns it to the specified variable.
Parameters
key Key in the application configuration file.
value Reference to the variable to which the read-in value is assigned.
assigned Output parameter that indicates whether the value has been assigned or not.
Definition at line 1802 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.GetAppSettingsValue().
Referenced by IG.Lib.ReporterBase.GetAppSetting(), IG.Lib.ReporterConsole.ReadAppSettingsBasic(), and IG.Lib.ReporterBase.ReadAppSettingsBasic().
GetAppSetting() [2/15]
static void IG.Lib.ReporterBase.GetAppSetting (string key, ref char value, out bool assigned) inline static
Reads a character value from the application configuration file and assigns it to the specified variable.
Parameters
key Key in the application configuration file.
value Reference to the variable to which the read-in value is assigned.
assigned Output parameter that indicates whether the value has been assigned or not.
Exceptions
T:System.FormatException Thrown when value is not in the right format.
Definition at line 1816 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.GetAppSettingsValue().
GetAppSetting() [3/15]
static void IG.Lib.ReporterBase.GetAppSetting (string key, ref List< char > value, out bool assigned) inline static
Reads a list of characters from the application configuration file and assigns it to the specified variable.
Parameters
key Key in the application configuration file.
value Reference to the variable to which the read-in value is assigned.
assigned Output parameter that indicates whether the value has been assigned or not.
Exceptions
T:System.FormatException Thrown when value is not in the right format.
Definition at line 1837 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.GetAppSettingsValue().
GetAppSetting() [4/15]
static void IG.Lib.ReporterBase.GetAppSetting (string key, ref int value, out bool assigned) inline static
Reads an integer value from the application configuration file and assigns it to the specified variable.
Parameters
key Key in the application configuration file.
value Reference to the variable to which the read-in value is assigned.
assigned Output parameter that indicates whether the value has been assigned or not.
Exceptions
T:System.FormatException Thrown when value is not in the right format.
T:System.OverFlowException
Definition at line 1863 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.GetAppSettingsValue().
GetAppSetting() [5/15]
static void IG.Lib.ReporterBase.GetAppSetting (string key, ref double value, out bool assigned) inline static
Reads a floating point value from the application configuration file and assigns it to the specified variable.
Parameters
key Key in the application configuration file.
value Reference to the variable to which the read-in value is assigned.
assigned Output parameter that indicates whether the value has been assigned or not.
Exceptions
T:System.FormatException Thrown when value is not in the right format.
T:System.OverFlowException
Definition at line 1884 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.GetAppSettingsValue().
GetAppSetting() [6/15]
static void IG.Lib.ReporterBase.GetAppSetting (string key, ref bool value, out bool assigned) inline static
Reads a boolean value from the application configuration file and assigns it to the specified variable. Numerical representation is allowed (0 for false, non-zero for true)
Parameters
key Key in the application configuration file.
value Reference to the variable to which the read-in value is assigned.
assigned Output parameter that indicates whether the value has been assigned or not.
Exceptions
T:System.FormatException Thrown when value is not in the right format.
Definition at line 1905 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.GetAppSetting().
GetAppSetting() [7/15]
static void IG.Lib.ReporterBase.GetAppSetting (string key, ref bool value, out bool assigned, bool otherformatsallowed) inline static
Reads a boolean value from the application configuration file and assigns it to the specified variable.
Parameters
key Key in the application configuration file.
value Reference to the variable to which the read-in value is assigned.
assigned Output parameter that indicates whether the value has been assigned or not.
otherformatsallowed If true then boolean type can be specified as number - 0 for false and non-zero for true.
Exceptions
T:System.FormatException Thrown when value is not in the right format.
Definition at line 1918 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.GetAppSettingsValue().
GetAppSettingsValue()
static string IG.Lib.ReporterBase.GetAppSettingsValue (string key) inline static
Returns configuration value corresponding to the configuration key in AppSettings (specified by key)
Parameters
key The key for which the value is retrieved from AppSettings.
Exceptions
FrameworkDependencyException Thrown when code is not compiled against the .NET full framework.
Definition at line 1974 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.GetAppSetting().
GetAppSetting() [8/15]
static void IG.Lib.ReporterBase.GetAppSetting (string key, ref ReportLevel value, out bool assigned) inline static
Reads an integer value from the application configuration file and assigns it to the specified variable.
Parameters
key Key in the application configuration file.
value Reference to the variable to which the read-in value is assigned.
assigned Output parameter that indicates whether the value has been assigned or not.
Definition at line 1989 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.GetAppSettingsValue().
FullKey()
static string IG.Lib.ReporterBase.FullKey (string reportername, string keyroot) inline static protected
Returns a full keyroot of a specific configuration item with a reporter name specified.
Parameters
reportername User - defined name of a reporter where settings are set. If null then the key will apply to all reporters.
keyroot Reduced keyroot name (without decorations).
Returns
The composed as it appears in the application configuration file.
Definition at line 2028 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.KeyPrefix.
Referenced by IG.Lib.ReporterBase.GetAppSetting().
GetAppSetting() [9/15]
void IG.Lib.ReporterBase.GetAppSetting (string reportername, string keyroot, ref string value, out bool assigned) inline protected
Reads a string value from the application configuration file (e.g. app.config) and assigns it to the specified parameter of the reporter.
Parameters
reportername User - defined name of a reporter where settings are set. If null then the key will apply to all reporters.
keyroot Agreed name of the parameter to be assigned.
value Reference to the variable to which the read-in value is assigned in the case that it is defined. If the given key is not defined in the configuration file then the variable is not affected.
assigned Output parameter, tells whether the value has been assigned.
Definition at line 2049 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.FullKey(), IG.Lib.ReporterBase.GetAppSetting(), and IG.Lib.ReporterBase.ReserveReportError().
GetAppSetting() [10/15]
void IG.Lib.ReporterBase.GetAppSetting (string reportername, string keyroot, ref char value, out bool assigned) inline protected
Reads a character value from the application configuration file (e.g. app.config) and assigns it to the specified parameter of the reporter.
Parameters
reportername User - defined name of a reporter where settings are set. If null then the key will apply to all reporters.
keyroot Agreed name of the parameter to be assigned.
value Reference to the variable to which the read-in value is assigned in the case that it is defined. If the given key is not defined in the configuration file then the variable is not affected.
assigned Output parameter, tells whether the value has been assigned.
Definition at line 2072 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.FullKey(), IG.Lib.ReporterBase.GetAppSetting(), and IG.Lib.ReporterBase.ReserveReportError().
GetAppSetting() [11/15]
void IG.Lib.ReporterBase.GetAppSetting (string reportername, string keyroot, ref List< char > value, out bool assigned) inline protected
Reads a list of characters from the application configuration file (e.g. app.config) and assigns it to the specified parameter of the reporter.
Parameters
reportername User - defined name of a reporter where settings are set. If null then the key will apply to all reporters.
keyroot Agreed name of the parameter to be assigned.
value Reference to the variable to which the read-in value is assigned in the case that it is defined. If the given key is not defined in the configuration file then the variable is not affected.
assigned Output parameter, tells whether the value has been assigned.
Definition at line 2095 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.FullKey(), IG.Lib.ReporterBase.GetAppSetting(), and IG.Lib.ReporterBase.ReserveReportError().
GetAppSetting() [12/15]
void IG.Lib.ReporterBase.GetAppSetting (string reportername, string keyroot, ref int value, out bool assigned) inline protected
Reads an integer value from the application configuration file (e.g. app.config) and assigns it to the specified parameter of the reporter.
Parameters
reportername User - defined name of a reporter where settings are set. If null then the key will apply to all reporters.
keyroot Agreed name of the parameter to be assigned.
value Reference to the variable to which the read-in value is assigned in the case that it is defined. If the given key is not defined in the configuration file then the variable is not affected.
assigned Output parameter, tells whether the value has been assigned.
Definition at line 2118 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.FullKey(), IG.Lib.ReporterBase.GetAppSetting(), and IG.Lib.ReporterBase.ReserveReportError().
GetAppSetting() [13/15]
void IG.Lib.ReporterBase.GetAppSetting (string reportername, string keyroot, ref double value, out bool assigned) inline protected
Reads a numeric value from the application configuration file (e.g. app.config) and assigns it to the specified parameter of the reporter.
Parameters
reportername User - defined name of a reporter where settings are set. If null then the key will apply to all reporters.
keyroot Agreed name of the parameter to be assigned.
value Reference to the variable to which the read-in value is assigned in the case that it is defined. If the given key is not defined in the configuration file then the variable is not affected.
assigned Output parameter, tells whether the value has been assigned.
Definition at line 2141 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.FullKey(), IG.Lib.ReporterBase.GetAppSetting(), and IG.Lib.ReporterBase.ReserveReportError().
GetAppSetting() [14/15]
void IG.Lib.ReporterBase.GetAppSetting (string reportername, string keyroot, ref bool value, out bool assigned) inline protected
Reads a boolean value from the application configuration file (e.g. app.config) and assigns it to the specified parameter of the reporter.
Parameters
reportername User - defined name of a reporter where settings are set. If null then the key will apply to all reporters.
keyroot Agreed name of the parameter to be assigned.
value Reference to the variable to which the read-in value is assigned in the case that it is defined. If the given key is not defined in the configuration file then the variable is not affected.
assigned Output parameter, tells whether the value has been assigned.
Definition at line 2164 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.FullKey(), IG.Lib.ReporterBase.GetAppSetting(), and IG.Lib.ReporterBase.ReserveReportError().
GetAppSetting() [15/15]
void IG.Lib.ReporterBase.GetAppSetting (string reportername, string keyroot, ref ReportLevel value, out bool assigned) inline protected
Reads a ReportLevel enumeration value from the application configuration file (e.g. app.config) and assigns it to the specified parameter of the reporter.
Parameters
reportername User - defined name of a reporter where settings are set. If null then the key will apply to all reporters.
keyroot Agreed name of the parameter to be assigned.
value Reference to the variable to which the read-in value is assigned in the case that it is defined. If the given key is not defined in the configuration file then the variable is not affected.
assigned Output parameter, tells whether the value has been assigned.
Definition at line 2187 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.FullKey(), IG.Lib.ReporterBase.GetAppSetting(), and IG.Lib.ReporterBase.ReserveReportError().
AppSettingsRead() [1/2]
bool IG.Lib.ReporterBase.AppSettingsRead (string groupname) inline
Returns a flag that tells whether configuration settings with a given group name have already been read for this reporter.
Parameters
groupname Name of the settings group, null and "" are treated teh same (denoting the genraal group).
Returns
true if settings with the specified name have already been read for teh current reporter, false otherwise.
Implements IG.Lib.IReporterBase.
Definition at line 2212 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.lockobj, IG.Lib.ReporterBase.readconf, and IG.Lib.ReporterBase.ReserveReportError().
AppSettingsRead() [2/2]
bool IG.Lib.ReporterBase.AppSettingsRead () inline
Returns a flag that tells whether general configuration settings (not belonging to any group) have already been read for this reporter.
Returns
true if settings with the specified name have already been read for teh current reporter, false otherwise.
Implements IG.Lib.IReporterBase.
Definition at line 2239 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.AppSettingsReadWarning(), IG.Lib.ReporterBase.MarkAppSettingsRead(), and IG.Lib.ReporterBase.ReadAppSettings().
AppSettingsReadWarning()
void IG.Lib.ReporterBase.AppSettingsReadWarning (string groupname) inline protected
Launches an internal warning that the configuration settings belonging tot he specified group have already been read for this reporter. The warning is launched only if the settings have actually been read and if warnings of this type are switched on.
Parameters
groupname Name of the settings group.
Definition at line 2259 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.AppSettingsRead(), IG.Lib.ReporterBase.AppSettingsWarnings, and IG.Lib.ReporterBase.ReserveReportError().
Referenced by IG.Lib.ReporterBase.ReadAppSettings().
MarkAppSettingsRead()
void IG.Lib.ReporterBase.MarkAppSettingsRead (string groupname) inline protected
Marks a specified group of settings as been read for the current reporter.
Parameters
groupname Name of the settings group, null and "" are treated teh same (denoting the genraal group).
Definition at line 2275 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.AppSettingsRead(), IG.Lib.ReporterBase.lockobj, IG.Lib.ReporterBase.readconf, and IG.Lib.ReporterBase.ReserveReportError().
Referenced by IG.Lib.ReporterBase.ReadAppSettings().
ReadAppSettingsBasic()
virtual void IG.Lib.ReporterBase.ReadAppSettingsBasic (string groupname) inline protected virtual
Reads settings for a specified named group of reporters from the application configuration file. In the derived classes, this method should be overridden by the method that calls the base class' method.
Parameters
groupname Name of the group of reporters for which the settings apply.
Locking and try blocks are not needed in this method because they appear in the calling methods.
Reimplemented in IG.Lib.ReporterConsole.
Definition at line 2349 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.AddTextLogger(), IG.Lib.ReporterBase.AddTextWriter(), IG.Lib.ReporterBase.AppSettingsWarnings, IG.Lib.ReporterBase.GetAppSetting(), IG.Lib.ReporterBase.KeyAppSettingsWarnings, IG.Lib.ReporterBase.KeyLevelOff, IG.Lib.ReporterBase.KeyLevelOn, IG.Lib.ReporterBase.KeyLoggingLevel, IG.Lib.ReporterBase.KeyReportingLevel, IG.Lib.ReporterBase.KeyTextLoggerAppend, IG.Lib.ReporterBase.KeyTextLoggerFile, IG.Lib.ReporterBase.KeyTextLoggerFile1, IG.Lib.ReporterBase.KeyTextLoggerIndentCharacter, IG.Lib.ReporterBase.KeyTextLoggerIndentInitial, IG.Lib.ReporterBase.KeyTextLoggerIndentSpacing, IG.Lib.ReporterBase.KeyTextLoggerIntroText, IG.Lib.ReporterBase.KeyTextLoggerProgramName, IG.Lib.ReporterBase.KeyTextLoggerWriteIntro, IG.Lib.ReporterBase.KeyTextWriterAppend, IG.Lib.ReporterBase.KeyTextWriterFile, IG.Lib.ReporterBase.KeyTextWriterFile1, IG.Lib.ReporterBase.KeyTextWriterIntroText, IG.Lib.ReporterBase.KeyTextWriterProgramName, IG.Lib.ReporterBase.KeyTextWriterWriteIntro, IG.Lib.ReporterBase.KeyTracingLevel, IG.Lib.ReporterBase.KeyUseTextLogger, IG.Lib.ReporterBase.KeyUseTextWriter, IG.Lib.ReporterBase.KeyUseTrace, IG.Lib.ReporterBase.LoggingLevel, IG.Lib.ReporterBase.ReportingLevel, IG.Lib.ReporterBase.SetTextLogger(), IG.Lib.ReporterBase.SetTextWriter(), IG.Lib.ReporterBase.TextLoggerAppend, IG.Lib.ReporterBase.TextLoggerIndentCharacter, IG.Lib.ReporterBase.TextLoggerIndentInitial, IG.Lib.ReporterBase.TextLoggerIndentSpacing, IG.Lib.ReporterBase.TextLoggerIntroText, IG.Lib.ReporterBase.TextLoggerProgramName, IG.Lib.ReporterBase.TextLoggerWriteIntro, IG.Lib.ReporterBase.TextWriterAppend, IG.Lib.ReporterBase.TextWriterIntroText, IG.Lib.ReporterBase.TextWriterProgramName, IG.Lib.ReporterBase.TextWriterWriteIntro, IG.Lib.ReporterBase.TracingLevel, IG.Lib.ReporterBase.UseTextLogger, IG.Lib.ReporterBase.UseTextWriter, and IG.Lib.ReporterBase.UseTrace.
Referenced by IG.Lib.ReporterBase.ReadAppSettings().
ReadAppSettings() [1/3]
void IG.Lib.ReporterBase.ReadAppSettings (string groupname, bool onlyonce) inline
Reads settings for a specified named group of reporters from the application configuration file.
Parameters
groupname Name of the group of reporters for which the settings apply.
onlyonce If true then settings belonging to the specified group are read only once.
Implements IG.Lib.IReporterBase.
Definition at line 2418 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.AppSettingsRead(), IG.Lib.ReporterBase.AppSettingsReadWarning(), IG.Lib.ReporterBase.lockobj, IG.Lib.ReporterBase.MarkAppSettingsRead(), IG.Lib.ReporterBase.ReadAppSettingsBasic(), and IG.Lib.ReporterBase.ReserveReportError().
ReadAppSettings() [2/3]
void IG.Lib.ReporterBase.ReadAppSettings (string groupname) inline
Reads settings for a specified named group of reporters from the application configuration file.
Parameters
groupname Name of the group of reporters for which the settings apply.
Implements IG.Lib.IReporterBase.
Definition at line 2443 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.ReadAppSettings().
ReadAppSettings() [3/3]
void IG.Lib.ReporterBase.ReadAppSettings () inline
Reads common reporter settings (i.e. settings that are not assigned for any named group) from the application configuration file.
Implements IG.Lib.IReporterBase.
Definition at line 2451 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.ReadAppSettings().
IncreaseDepth() [1/2]
void IG.Lib.ReporterBase.IncreaseDepth () inline
Increases indentation level by 1.
Returns
Current indentation level.
Implements IG.Lib.IReporterBase.
Definition at line 2577 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.Depth.
IncreaseDepth() [2/2]
void IG.Lib.ReporterBase.IncreaseDepth (int numlevels) inline
Increases indentation level by the specified number of levels (can be 0 or negative).
Parameters
numlevels Number of levels by which indentation is increased.
Returns
Current intentation level.
Implements IG.Lib.IReporterBase.
Definition at line 2586 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.Depth.
DecreaseDepth() [1/2]
void IG.Lib.ReporterBase.DecreaseDepth () inline
Decreases indentation level by 1.
Returns
Current indentation level.
Implements IG.Lib.IReporterBase.
Definition at line 2593 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.Depth.
DecreaseDepth() [2/2]
void IG.Lib.ReporterBase.DecreaseDepth (int numlevels) inline
Decreases indentation level by the specified number of levels (can be 0 or negative).
Parameters
numlevels Number of levels by which indentation is decreased.
Returns
Current intentation level.
Implements IG.Lib.IReporterBase.
Definition at line 2601 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.Depth.
SyncLevels()
void IG.Lib.ReporterBase.SyncLevels () inline private
Definition at line 2629 of file ReporterMsg.cs.
References IG.Lib.ReporterBase._LoggingLevel, IG.Lib.ReporterBase._ReportingLevel, IG.Lib.ReporterBase._TracingLevel, and IG.Lib.ReporterBase._TreatError.
ResetLevels()
void IG.Lib.ReporterBase.ResetLevels () inline
Resets the various kinds of reporting levels to default values.
Implements IG.Lib.IReporterBase.
Definition at line 2642 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.LoggingLevel, IG.Lib.ReporterBase.ReportingLevel, and IG.Lib.ReporterBase.TracingLevel.
DoLaunch()
static bool IG.Lib.ReporterBase.DoLaunch (ReportType reptype, ReportLevel replevel) inline static
Returns true if the report of a given type will be launched at the given reporting level, and false if not.
Parameters
reptype Type of the report for which information is returned.
replevel True if reports of the specific type are launched, false if not.
Definition at line 2707 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.DoLogging(), IG.Lib.ReporterBase.DoReporting(), and IG.Lib.ReporterBase.DoTracing().
DoReporting()
bool IG.Lib.ReporterBase.DoReporting (ReportType reptype) inline
Returns true if the report of a given type should be shown by user interface (according to ReportingLevel), and false if not.
Parameters
reptype Type of the report for which information is returned.
Returns
True if reports of the specific type are launched, false if not.
Implements IG.Lib.IReporterBase.
Definition at line 2740 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.DoLaunch(), and IG.Lib.ReporterBase.ReportingLevel.
Referenced by IG.Lib.ReporterConsole_Base.Report(), and IG.Lib.ReporterBase.Report().
DoLogging()
bool IG.Lib.ReporterBase.DoLogging (ReportType reptype) inline
Returns true if the report of a given type should be logged in log files (according to ReportingLevel), and false if not.
Parameters
reptype Type of the report for which information is returned.
Returns
True if reports of the specific type are launched, false if not.
Implements IG.Lib.IReporterBase.
Definition at line 2749 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.DoLaunch(), and IG.Lib.ReporterBase.LoggingLevel.
Referenced by IG.Lib.ReporterBase.Report().
DoTracing()
bool IG.Lib.ReporterBase.DoTracing (ReportType reptype) inline
Returns true if the report of a given type should traced (according to ReportingLevel), and false if not.
Parameters
reptype Type of the report for which information is returned.
Returns
True if reports of the specific type are launched, false if not.
Implements IG.Lib.IReporterBase.
Definition at line 2758 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.DoLaunch(), and IG.Lib.ReporterBase.TracingLevel.
Referenced by IG.Lib.ReporterBase.Report().
ReportType2EventLogEntryType()
static EventLogEntryType IG.Lib.ReporterBase.ReportType2EventLogEntryType (ReportType rt) inline static
Returns the System.Diagnostics.EventLogEntryType value corresponding to the given ReportType. Remark: FailureAudit and SuccessAudit can not be generated because they don't have representation in ReportType.
Parameters
rt ReportType value to be converted.
Returns
Converted value of type EventLogEntryType.
Definition at line 2848 of file ReporterMsg.cs.
EventLogEntryType2ReportType()
static ReportType IG.Lib.ReporterBase.EventLogEntryType2ReportType (EventLogEntryType el) inline static
Returns the ReportType value corresponding to the given System.Diagnostics.EventLogEntryType. Remark: FailureAudit and SuccessAudit do not have representation in ReportType and are mapped to Error and Warning, respectively.
Parameters
el EventLogEntryType value to be converted.
Returns
Converted value of type ReportType.
Definition at line 2873 of file ReporterMsg.cs.
ReportLevel2TraceLevel()
static TraceLevel IG.Lib.ReporterBase.ReportLevel2TraceLevel (ReportLevel level) inline static
Returns the System.Diagnostics.TraceLevel value corresponding to the given ReportLevel.
Parameters
level ReportLevel value to be converted.
Returns
Converted value of type TraceLevel.
Definition at line 2895 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.SyncTraceSwitchWithReportLevel().
TraceLevel2ReportLevel()
static ReportLevel IG.Lib.ReporterBase.TraceLevel2ReportLevel (TraceLevel tl) inline static
Returns the ReportLevel value corresponding to the given System.Diagnostics.TraceLevel.
Parameters
tl TraceLevel value to be converted.
Returns
Converted value of type ReportLevel.
Definition at line 2918 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.SyncReportLevelWithTraceSwitch().
SyncReportLevelWithTraceSwitch()
void IG.Lib.ReporterBase.SyncReportLevelWithTraceSwitch (TraceSwitch tswitch, ref ReportLevel level) inline protected
Synchronizes the value of ReportLevel enumeration variable with the state of a TraceSwitch variable. Enumeration is synchronized according to the Level property of the switch.
Parameters
tswitch A trace switch that the ReportLevel enumeration variable will be synchronized with. If it is null or it contains a level that can not be represented by the ReportLevel enumeration then nothing happens.
level The ReportLevel variable that is synchronized; declared as ref
Definition at line 2942 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.TraceLevel2ReportLevel().
SyncTraceSwitchWithReportLevel()
void IG.Lib.ReporterBase.SyncTraceSwitchWithReportLevel (ReportLevel level, TraceSwitch tswitch) inline protected
Synchronizes the state of a TraceSwitch object with the value of the ReportLevel enumeration.
Parameters
level Value of the ReportLevel enumeration that TraceSwitch will be synchronized with
tswitch TraceSwitch taht is synchronized.
Definition at line 2951 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.ReportLevel2TraceLevel().
ReserveReportErrorSpecific()
virtual void IG.Lib.ReporterBase.ReserveReportErrorSpecific (ReportType messagetype, string location, string message, Exception ex, Exception ex1) inline protected virtual
Reportinf of internal reporter errors for the specific reporter class (overridden in derived classes). This method is called for internal error reports when the delegate for this job is not defined.
Parameters
messagetype
location
message
ex
ex1
Definition at line 3083 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.DefaultReserveReportError().
Referenced by IG.Lib.ReporterBase.ReserveReportError().
ReserveReportError()
void IG.Lib.ReporterBase.ReserveReportError (ReportType messagetype, string location, string message, Exception ex, Exception ex1) inline protected
Used to report internal errors of the reporter. Designed to be bullet proof in order to ensure that improper behavior of the reporting system does not remain unnoticed.
Parameters
messagetype
location
message
ex
ex1
Definition at line 3096 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.lockobj, IG.Lib.ReporterBase.ReserveReportErrorDlg, and IG.Lib.ReporterBase.ReserveReportErrorSpecific().
Referenced by IG.Lib.ReporterBase.AddTW(), IG.Lib.ReporterBase.AppSettingsRead(), IG.Lib.ReporterBase.AppSettingsReadWarning(), IG.Lib.ReporterBase.GetAppSetting(), IG.Lib.ReporterBase.MarkAppSettingsRead(), IG.Lib.ReporterBase.ReadAppSettings(), IG.Lib.ReporterConsole_Base.Report(), IG.Lib.ReporterBase.Report(), IG.Lib.ReporterBase.SetTW(), and IG.Lib.ReporterBase.TWClass.SetWriter().
Report() [1/6]
virtual void IG.Lib.ReporterBase.Report (ReportType messagetype, string location, string message, Exception ex) inline virtual
Basic reporting method (overloaded). Launches an error report, a warning report or other kind of report/message. Supplemental data (such as objects necessary to launch visualize the report or operation flags) are obtained from the class' instance.
Parameters
messagetype The type of the report (e.g. Error, Warning, etc.).
location User-provided description of error location.
message User-provided description of error.
ex Exception thrown when error occurred.
Implements IG.Lib.IReporterBase.
Reimplemented in IG.Lib.ReporterConsole_Base.
Definition at line 3127 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.DoLogging(), IG.Lib.ReporterBase.DoReporting(), IG.Lib.ReporterBase.DoTracing(), IG.Lib.ReporterBase.lockobj, IG.Lib.ReporterBase.Report_TextLogger(), IG.Lib.ReporterBase.Report_TextWriter(), IG.Lib.ReporterBase.Report_Trace(), IG.Lib.ReporterBase.ReportDlg, IG.Lib.ReporterBase.ReportLocationDlg, IG.Lib.ReporterBase.ReportMessageDlg, IG.Lib.ReporterBase.ReserveReportError(), IG.Lib.ReporterBase.ThrowTestException, IG.Lib.ReporterBase.UseTextLogger, IG.Lib.ReporterBase.UseTextWriter, and IG.Lib.ReporterBase.UseTrace.
Referenced by IG.Lib.ReporterBase.Report(), IG.Lib.ReporterBase.ReportError(), IG.Lib.ReporterBase.ReportInfo(), and IG.Lib.ReporterBase.ReportWarning().
Report() [2/6]
void IG.Lib.ReporterBase.Report (ReportType messagetype, string message, Exception ex) inline
Launches a report. Predominantly for error and warning reports.
Parameters
messagetype Level of the message (Error, Warnind, etc.).
message User-provided description of error.
ex Exception that is the cause for launching the report (and from which additional information is extracted).
Implements IG.Lib.IReporterBase.
Definition at line 3209 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.Report().
Report() [3/6]
void IG.Lib.ReporterBase.Report (ReportType messagetype, Exception ex, string location) inline
Launches a report. Predominantly for error and warning reports.
Parameters
messagetype Level of the message (Error, Warnind, etc.).
ex Exception that is the cause for launching the report (and from which additional information is extracted).
location User-provided description of error location.
Implements IG.Lib.IReporterBase.
Definition at line 3219 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.Report().
Report() [4/6]
void IG.Lib.ReporterBase.Report (ReportType messagetype, Exception ex) inline
Launches a report. Predominantly for error and warning reports.
Parameters
messagetype Level of the message (Error, Warnind, etc.).
ex Exception that is the cause for launching the report (and from which additional information is extracted).
Implements IG.Lib.IReporterBase.
Definition at line 3228 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.Report().
Report() [5/6]
void IG.Lib.ReporterBase.Report (ReportType messagetype, string location, string message) inline
Launches a report.
Parameters
messagetype Level of the message (Error, Warnind, etc.).
location User provided description of the location where report was triggered.
message User provided message included in the report.
Implements IG.Lib.IReporterBase.
Definition at line 3238 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.Report().
Report() [6/6]
void IG.Lib.ReporterBase.Report (ReportType messagetype, string message) inline
Launches a report.
Parameters
messagetype Level of the message (Error, Warnind, etc.).
message User provided message included in the report.
Implements IG.Lib.IReporterBase.
Definition at line 3247 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.Report().
ReportError() [1/6]
void IG.Lib.ReporterBase.ReportError (string location, string message, Exception ex) inline
Basic error reporting method (overloaded). Supplemental data (such as objects necessary to launch visualize the report or operation flags) are obtained from the class' instance.
Parameters
location User-provided description of error location.
message User-provided description of error.
ex Exception thrown when error occurred.
Implements IG.Lib.IReporterBase.
Definition at line 3264 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.Report().
ReportError() [2/6]
void IG.Lib.ReporterBase.ReportError (string message, Exception ex) inline
Launches an error report.
Parameters
message User-provided description of error.
ex Exception that is the cause for launching the report (and from which additional information is extracted).
Implements IG.Lib.IReporterBase.
Definition at line 3275 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.Report().
ReportError() [3/6]
void IG.Lib.ReporterBase.ReportError (Exception ex, string location) inline
Launches an error report.
Parameters
ex Exception that is the cause for launching the report (and from which additional information is extracted).
location User-provided description of error location.
Implements IG.Lib.IReporterBase.
Definition at line 3284 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.Report().
ReportError() [4/6]
void IG.Lib.ReporterBase.ReportError (Exception ex) inline
Launches an error report. Predominantly for error and warning reports.
Parameters
ex Exception that is the cause for launching the report (and from which additional information is extracted).
Implements IG.Lib.IReporterBase.
Definition at line 3292 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.Report().
ReportError() [5/6]
void IG.Lib.ReporterBase.ReportError (string location, string message) inline
Launches an error report.
Parameters
location User provided description of the location where report was triggered.
message User provided message included in the report.
Implements IG.Lib.IReporterBase.
Definition at line 3301 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.Report().
ReportError() [6/6]
void IG.Lib.ReporterBase.ReportError (string message) inline
Launches an error report.
Parameters
message User provided message included in the report.
Implements IG.Lib.IReporterBase.
Definition at line 3309 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.Report().
ReportWarning() [1/6]
void IG.Lib.ReporterBase.ReportWarning (string location, string message, Exception ex) inline
Basic warning reporting method (overloaded). Supplemental data (such as objects necessary to launch visualize the report or operation flags) are obtained from the class' instance.
Parameters
location User-provided description of error location.
message User-provided description of error.
ex Exception thrown when error occurred.
Implements IG.Lib.IReporterBase.
Definition at line 3326 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.Report().
ReportWarning() [2/6]
void IG.Lib.ReporterBase.ReportWarning (string message, Exception ex) inline
Launches a warning report.
Parameters
message User-provided description of error.
ex Exception that is the cause for launching the report (and from which additional information is extracted).
Implements IG.Lib.IReporterBase.
Definition at line 3337 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.Report().
ReportWarning() [3/6]
void IG.Lib.ReporterBase.ReportWarning (Exception ex, string location) inline
Launches a warning report.
Parameters
ex Exception that is the cause for launching the report (and from which additional information is extracted).
location User-provided description of error location.
Implements IG.Lib.IReporterBase.
Definition at line 3346 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.Report().
ReportWarning() [4/6]
void IG.Lib.ReporterBase.ReportWarning (Exception ex) inline
Launches a warning report. Predominantly for error and warning reports.
Parameters
ex Exception that is the cause for launching the report (and from which additional information is extracted).
Implements IG.Lib.IReporterBase.
Definition at line 3354 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.Report().
ReportWarning() [5/6]
void IG.Lib.ReporterBase.ReportWarning (string location, string message) inline
Launches a warning report.
Parameters
location User provided description of the location where report was triggered.
message User provided message included in the report.
Implements IG.Lib.IReporterBase.
Definition at line 3363 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.Report().
ReportWarning() [6/6]
void IG.Lib.ReporterBase.ReportWarning (string message) inline
Launches a warning report.
Parameters
message User provided message included in the report.
Implements IG.Lib.IReporterBase.
Definition at line 3371 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.Report().
ReportInfo() [1/3]
void IG.Lib.ReporterBase.ReportInfo (Exception ex) inline
Launches an info.
Parameters
ex Exception that is the cause for launching the report (and from which additional information is extracted).
Implements IG.Lib.IReporterBase.
Definition at line 3384 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.Report().
ReportInfo() [2/3]
void IG.Lib.ReporterBase.ReportInfo (string location, string message) inline
Launches an info.
Parameters
location User provided description of the location where report was triggered.
message User provided message included in the report.
Implements IG.Lib.IReporterBase.
Definition at line 3393 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.Report().
ReportInfo() [3/3]
void IG.Lib.ReporterBase.ReportInfo (string message) inline
Launches an info.
Parameters
message User provided message included in the report.
Implements IG.Lib.IReporterBase.
Definition at line 3401 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.Report().
PrintIntro()
virtual void IG.Lib.ReporterBase.PrintIntro (TextWriter tw, string introtext, string programname) inline protected virtual
Writes to a textwriter the introduction text that is usually printed before logging starts.
Parameters
tw The TextWriter that the text is written to.
introtext Introduction text that is printed (if null then text will be composed); additional newlines are printed.
programname Name of the program or other entity that uses the reporter.
Definition at line 3423 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.TextLoggerPrintIntro(), and IG.Lib.ReporterBase.TextWriterPrintIntro().
SetTW() [1/3]
bool IG.Lib.ReporterBase.SetTW (ref TextWriter tw, ref bool disptw, TextWriter writer, bool writeintro, bool disposewriter) inline protected
Sets the basic text writer to which reporting is performed, but overrides the writeintro property by the 'writeintro' argument.
Parameters
tw Textwriter that is updated.
disptw Reference to the dispose flag that is also remembered.
writer Textwriter to which reporting will be performed.
writeintro Overrides the class' writeintro property (if true then introductory text is printed, regardless of the value of the property). If the introductory text is printed then the standard method is used, taking into account the introtext and programname properties.
disposewriter Indicates whether the TextWriter should be disposed when not used any more. Default is false when specifying a textwriter.
Returns
True if a new writer has been successfully set and is ready to use, false otherwise.
Definition at line 3461 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.TextWriterPrintIntro().
Referenced by IG.Lib.ReporterBase.SetTextLogger(), IG.Lib.ReporterBase.SetTextWriter(), and IG.Lib.ReporterBase.SetTW().
SetTW() [2/3]
bool IG.Lib.ReporterBase.SetTW (ref TextWriter tw, ref bool disptw, Stream stream, bool writeintro, bool disposewriter) inline protected
Creates a TextWriter upon the stream and sets it as the basic TextWriter to which reporting is performed. Overrides the writeintro property by the 'writeintro' argument.
Parameters
tw Textwriter that is updated.
disptw Reference to the dispose flag that is also remembered.
stream Textwriter to which reporting will be performed.
writeintro Overrides the class' writeintro property (if true then introductory text is printed, regardless of the value of the property). If the introductory text is printed then the standard method is used, taking into account the introtext and programname properties.
disposewriter Indicates whether the TextWriter should be disposed when not used any more. Default is false when specifying a stream.
Returns
True if a new writer has been successfully set and is ready to use, false otherwise.
Definition at line 3499 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.ReserveReportError(), and IG.Lib.ReporterBase.SetTW().
SetTW() [3/3]
bool IG.Lib.ReporterBase.SetTW (ref TextWriter tw, ref bool disptw, string filename, bool append, bool writeintro, bool disposewriter) inline
Creates a TextWriter upon a file and sets it as the text writer to which reporting is also performed. The caller specifies whether to overwrite the file or to append to it, and whether the introductory text is written before reporting to the file begins.
Parameters
tw Textwriter that is updated.
disptw Reference to the dispose flag that is also remembered.
filename Name of the file to which reporting will be performed.
append If false then eventual existing contents of the file are overwritten. Otherwise, new text is appended at the end of the file.
writeintro Overrides the class' writeintro property (if true then introductory text is printed, regardless of the value of the property). If the introductory text is printed then the standard method is used, taking into account the introtext and programname properties.
disposewriter Indicates whether the TextWriter should be disposed when not used any more. Default is true when specifying a file name.
Returns
True if a new writer has been successfully set and is ready to use, false otherwise.
Definition at line 3539 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.ReserveReportError(), and IG.Lib.ReporterBase.SetTW().
AddTW() [1/3]
bool IG.Lib.ReporterBase.AddTW (ref List< TWClass > lwriters, TextWriter writer, bool writeintro, bool disposewriter) inline protected
Adds another TextWriter to which reporting will also be performed.
Parameters
lwriters List on which a TextWriter is added.
writer Textwriter to which reporting will be performed.
writeintro Overrides the class' writeintro property (if true then introductory text is printed, regardless of the value of the property). If the introductory text is printed then the standard method is used, taking into account the introtext and programname properties.
disposewriter Indicates whether the TextWriter should be disposed when not used any more. Default is false when specifying a textwriter.
Returns
True if a new writer has been successfully set and is ready to use, false otherwise.
Definition at line 3719 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.FindTW(), IG.Lib.ReporterBase.ReserveReportError(), and IG.Lib.ReporterBase.TWClass.SetWriter().
Referenced by IG.Lib.ReporterBase.AddTextLogger(), and IG.Lib.ReporterBase.AddTextWriter().
AddTW() [2/3]
bool IG.Lib.ReporterBase.AddTW (ref List< TWClass > lwriters, Stream stream, bool writeintro, bool disposewriter) inline protected
Creates a TextWriter from the stream and adds it to the list of TextWriters on which reporting is also performed. Overrides the writeintro property by the 'writeintro' argument.
Parameters
lwriters List on which a TextWriter is added.
stream Stream to which reporting will be performed.
writeintro Overrides the class' writeintro property (if true then introductory text is printed, regardless of the value of the property). If the introductory text is printed then the standard method is used, taking into account the introtext and programname properties.
disposewriter Indicates whether the TextWriter should be disposed when not used any more. Default is false when specifying a stream.
Returns
True if a new writer has been successfully set and is ready to use, false otherwise.
Definition at line 3754 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.FindTW(), IG.Lib.ReporterBase.lockobj, IG.Lib.ReporterBase.ReserveReportError(), and IG.Lib.ReporterBase.TWClass.SetWriter().
AddTW() [3/3]
bool IG.Lib.ReporterBase.AddTW (ref List< TWClass > lwriters, string filename, bool append, bool writeintro, bool disposewriter) inline protected
Creates a TextWriter from a specific file and adds it to the list of TextWriters on which reporting is also performed. The caller specifies whether to overwrite the file or to append to it, and whether the introductory text is written before reporting to the file begins.
Parameters
lwriters List on which a TextWriter is added.
filename Name of the file to which reporting will be performed.
append If false then eventual existing contents of the file are overwritten. Otherwise, new text is appended at the end of the file.
writeintro Overrides the class' writeintro property (if true then introductory text is printed, regardless of the value of the property). If the introductory text is printed then the standard method is used, taking into account the introtext and programname properties.
disposewriter Indicates whether the TextWriter should be disposed when not used any more. Default is true when specifying a file name.
Returns
True if a new writer has been successfully set and is ready to use, false otherwise.
Definition at line 3797 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.FindTW(), IG.Lib.ReporterBase.ReserveReportError(), and IG.Lib.ReporterBase.TWClass.SetWriter().
FindTW() [1/3]
int IG.Lib.ReporterBase.FindTW (List< TWClass > lwriters, TextWriter writer) inline private
Returns the first object on the list that contains a specific TextWriter.
Definition at line 3825 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.TWClass.Writer.
Referenced by IG.Lib.ReporterBase.AddTW(), and IG.Lib.ReporterBase.RemoveTW().
FindTW() [2/3]
int IG.Lib.ReporterBase.FindTW (List< TWClass > lwriters, Stream stream) inline private
Returns the first object on the list whose TextWriter has been created from the specific Stream.
Definition at line 3847 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.TWClass.stream.
FindTW() [3/3]
int IG.Lib.ReporterBase.FindTW (List< TWClass > lwriters, string filename) inline private
Returns the first object on the list whose TextWriter has been created from a file with the specific name.
Definition at line 3869 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.TWClass.filename.
RemoveTW() [1/3]
bool IG.Lib.ReporterBase.RemoveTW (List< TWClass > lwriters, TextWriter writer) inline protected
Removes the first object from a list that contains the specified TextWriter.
Returns
true if the appropriate text writer was found and successfully removed.
Definition at line 3893 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.TWClass.ClearWriter(), and IG.Lib.ReporterBase.FindTW().
Referenced by IG.Lib.ReporterBase.RemoveTextLogger(), and IG.Lib.ReporterBase.RemoveTextWriter().
RemoveTW() [2/3]
bool IG.Lib.ReporterBase.RemoveTW (List< TWClass > lwriters, Stream stream) inline protected
Removes the first object from a list whose TextWriter has been created form the specified stream.
Definition at line 3915 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.TWClass.ClearWriter(), and IG.Lib.ReporterBase.FindTW().
RemoveTW() [3/3]
bool IG.Lib.ReporterBase.RemoveTW (List< TWClass > lwriters, string filename) inline protected
Removes the first object from a list whose TextWriter has been created form the file with the specified name.
Definition at line 3937 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.TWClass.ClearWriter(), and IG.Lib.ReporterBase.FindTW().
TextWriterPrintIntro()
virtual void IG.Lib.ReporterBase.TextWriterPrintIntro (TextWriter tw) inline protected virtual
Writes to a textwriter the introduction text that is usually printed before logging starts.
Parameters
tw The TextWriter that the text is written to.
Definition at line 4005 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.PrintIntro(), IG.Lib.ReporterBase.TextWriterIntroText, and IG.Lib.ReporterBase.TextWriterProgramName.
Referenced by IG.Lib.ReporterBase.SetTW(), and IG.Lib.ReporterBase.TWClass.SetWriter().
SetTextWriter() [1/10]
bool IG.Lib.ReporterBase.SetTextWriter (TextWriter writer) inline
Sets the text writer to which reporting is also performed.
Parameters
writer Textwriter to which reporting will be performed.
Returns
True if a new writer has been successfully set and is ready to use, false otherwise.
Implements IG.Lib.IReporterTextWriter.
Definition at line 4015 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.lockobj, and IG.Lib.ReporterBase.TextWriterWriteIntro.
Referenced by IG.Lib.ReporterBase.ReadAppSettingsBasic(), and IG.Lib.ReporterBase.SetTextWriter().
SetTextWriter() [2/10]
bool IG.Lib.ReporterBase.SetTextWriter (TextWriter writer, bool writeintro) inline
Sets the basic text writer to which reporting is performed, but overrides the writeintro property by the 'writeintro' argument.
Parameters
writer Textwriter to which reporting will be performed.
writeintro Overrides the class' writeintro property (if true then introductory text is printed, regardless of the value of the property). If the introductory text is printed then the standard method is used, taking into account the introtext and programname properties.
Returns
True if a new writer has been successfully set and is ready to use, false otherwise.
Implements IG.Lib.IReporterTextWriter.
Definition at line 4031 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.lockobj, and IG.Lib.ReporterBase.SetTextWriter().
SetTextWriter() [3/10]
bool IG.Lib.ReporterBase.SetTextWriter (TextWriter writer, bool writeintro, bool disposewriter) inline
Sets the basic text writer to which reporting is performed, but overrides the writeintro property by the 'writeintro' argument.
Parameters
writer Textwriter to which reporting will be performed.
writeintro Overrides the class' writeintro property (if true then introductory text is printed, regardless of the value of the property). If the introductory text is printed then the standard method is used, taking into account the introtext and programname properties.
disposewriter Indicates whether the TextWriter should be disposed when not used any more. Default is false when specifying a textwriter.
Returns
True if a new writer has been successfully set and is ready to use, false otherwise.
Implements IG.Lib.IReporterTextWriter.
Definition at line 4049 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.DisposeWriter, IG.Lib.ReporterBase.lockobj, IG.Lib.ReporterBase.SetTW(), and IG.Lib.ReporterBase.Writer.
SetTextWriter() [4/10]
bool IG.Lib.ReporterBase.SetTextWriter (Stream stream) inline
Creates a TextWriter upon the stream and sets it as the text writer to which reporting is also performed.
Parameters
stream Stream to which reporting will be performed.
Returns
True if a new writer has been successfully set and is ready to use, false otherwise.
Implements IG.Lib.IReporterTextWriter.
Definition at line 4061 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.lockobj, IG.Lib.ReporterBase.SetTextWriter(), and IG.Lib.ReporterBase.TextWriterWriteIntro.
SetTextWriter() [5/10]
bool IG.Lib.ReporterBase.SetTextWriter (Stream stream, bool writeintro) inline
Creates a TextWriter upon the stream and sets it as the basic TextWriter to which reporting is performed. Overrides the writeintro property by the 'writeintro' argument.
Parameters
stream Textwriter to which reporting will be performed.
writeintro Overrides the class' writeintro property (if true then introductory text is printed, regardless of the value of the property). If the introductory text is printed then the standard method is used, taking into account the introtext and programname properties.
Returns
True if a new writer has been successfully set and is ready to use, false otherwise.
Implements IG.Lib.IReporterTextWriter.
Definition at line 4077 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.lockobj, and IG.Lib.ReporterBase.SetTextWriter().
SetTextWriter() [6/10]
bool IG.Lib.ReporterBase.SetTextWriter (Stream stream, bool writeintro, bool disposewriter) inline
Creates a TextWriter upon the stream and sets it as the basic TextWriter to which reporting is performed. Overrides the writeintro property by the 'writeintro' argument.
Parameters
stream Textwriter to which reporting will be performed.
writeintro Overrides the class' writeintro property (if true then introductory text is printed, regardless of the value of the property). If the introductory text is printed then the standard method is used, taking into account the introtext and programname properties.
disposewriter Indicates whether the TextWriter should be disposed when not used any more. Default is false when specifying a stream.
Returns
True if a new writer has been successfully set and is ready to use, false otherwise.
Implements IG.Lib.IReporterTextWriter.
Definition at line 4096 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.DisposeWriter, IG.Lib.ReporterBase.lockobj, IG.Lib.ReporterBase.SetTW(), and IG.Lib.ReporterBase.Writer.
SetTextWriter() [7/10]
bool IG.Lib.ReporterBase.SetTextWriter (string filename) inline
Creates a TextWriter upon a file and sets it as the basic TextWriter to which reporting is also performed. The file is overwritten.
Parameters
filename Name of the file to which reporting will be performed.
Returns
True if a new writer has been successfully set and is ready to use, false otherwise.
Implements IG.Lib.IReporterTextWriter.
Definition at line 4110 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.lockobj, IG.Lib.ReporterBase.SetTextWriter(), and IG.Lib.ReporterBase.TextWriterWriteIntro.
SetTextWriter() [8/10]
bool IG.Lib.ReporterBase.SetTextWriter (string filename, bool append) inline
Creates a TextWriter upon a file and sets it as the basic TextWriter to which reporting is also performed, where the caller specifies either to overwrite the file or to append to it.
Parameters
filename Name of the file to which reporting will be performed.
append If false then eventual existing contents of the file are overwritten. Otherwise, new text is appended at the end of the file.
Returns
True if a new writer has been successfully set and is ready to use, false otherwise.
Implements IG.Lib.IReporterTextWriter.
Definition at line 4125 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.lockobj, IG.Lib.ReporterBase.SetTextWriter(), and IG.Lib.ReporterBase.TextWriterWriteIntro.
SetTextWriter() [9/10]
bool IG.Lib.ReporterBase.SetTextWriter (string filename, bool append, bool writeintro) inline
Creates a TextWriter upon a file and sets it as the text writer to which reporting is also performed. The caller specifies whether to overwrite the file or to append to it, and whether the introductory text is written before reporting to the file begins.
Parameters
filename Name of the file to which reporting will be performed.
append If false then eventual existing contents of the file are overwritten. Otherwise, new text is appended at the end of the file.
writeintro Overrides the class' writeintro property (if true then introductory text is printed, regardless of the value of the property). If the introductory text is printed then the standard method is used, taking into account the introtext and programname properties.
Returns
True if a new writer has been successfully set and is ready to use, false otherwise.
Implements IG.Lib.IReporterTextWriter.
Definition at line 4144 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.lockobj, and IG.Lib.ReporterBase.SetTextWriter().
SetTextWriter() [10/10]
bool IG.Lib.ReporterBase.SetTextWriter (string filename, bool append, bool writeintro, bool disposewriter) inline
Creates a TextWriter upon a file and sets it as the text writer to which reporting is also performed. The caller specifies whether to overwrite the file or to append to it, and whether the introductory text is written before reporting to the file begins.
Parameters
filename Name of the file to which reporting will be performed.
append If false then eventual existing contents of the file are overwritten. Otherwise, new text is appended at the end of the file.
writeintro Overrides the class' writeintro property (if true then introductory text is printed, regardless of the value of the property). If the introductory text is printed then the standard method is used, taking into account the introtext and programname properties.
disposewriter Indicates whether the TextWriter should be disposed when not used any more. Default is true when specifying a file name.
Returns
True if a new writer has been successfully set and is ready to use, false otherwise.
Implements IG.Lib.IReporterTextWriter.
Definition at line 4165 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.DisposeWriter, IG.Lib.ReporterBase.lockobj, IG.Lib.ReporterBase.SetTW(), and IG.Lib.ReporterBase.Writer.
AddTextWriter() [1/10]
bool IG.Lib.ReporterBase.AddTextWriter (TextWriter writer) inline
Sets the text writer to which reporting is also performed.
Parameters
writer Textwriter to which reporting will be performed.
Returns
True if a new writer has been successfully set and is ready to use, false otherwise.
Implements IG.Lib.IReporterTextWriter.
Definition at line 4180 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.lockobj, and IG.Lib.ReporterBase.TextWriterWriteIntro.
Referenced by IG.Lib.ReporterBase.AddTextWriter(), and IG.Lib.ReporterBase.ReadAppSettingsBasic().
AddTextWriter() [2/10]
bool IG.Lib.ReporterBase.AddTextWriter (TextWriter writer, bool writeintro) inline
Sets the basic text writer to which reporting is performed, but overrides the writeintro property by the 'writeintro' argument.
Parameters
writer Textwriter to which reporting will be performed.
writeintro Overrides the class' writeintro property (if true then introductory text is printed, regardless of the value of the property). If the introductory text is printed then the standard method is used, taking into account the introtext and programname properties.
Returns
True if a new writer has been successfully set and is ready to use, false otherwise.
Implements IG.Lib.IReporterTextWriter.
Definition at line 4196 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.AddTextWriter(), and IG.Lib.ReporterBase.lockobj.
AddTextWriter() [3/10]
bool IG.Lib.ReporterBase.AddTextWriter (TextWriter writer, bool writeintro, bool disposewriter) inline
Sets the basic text writer to which reporting is performed, but overrides the writeintro property by the 'writeintro' argument.
Parameters
writer Textwriter to which reporting will be performed.
writeintro Overrides the class' writeintro property (if true then introductory text is printed, regardless of the value of the property). If the introductory text is printed then the standard method is used, taking into account the introtext and programname properties.
disposewriter Indicates whether the TextWriter should be disposed when not used any more. Default is false when specifying a textwriter.
Returns
True if a new writer has been successfully set and is ready to use, false otherwise.
Implements IG.Lib.IReporterTextWriter.
Definition at line 4214 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.AddTW(), IG.Lib.ReporterBase.lockobj, and IG.Lib.ReporterBase.Writers.
AddTextWriter() [4/10]
bool IG.Lib.ReporterBase.AddTextWriter (Stream stream) inline
Creates a TextWriter from the stream and adds it to the list of TextWriters on which reporting is also performed.
Parameters
stream Stream to which reporting will be performed.
Returns
True if a new writer has been successfully set and is ready to use, false otherwise.
Implements IG.Lib.IReporterTextWriter.
Definition at line 4228 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.AddTextWriter(), IG.Lib.ReporterBase.lockobj, and IG.Lib.ReporterBase.TextWriterWriteIntro.
AddTextWriter() [5/10]
bool IG.Lib.ReporterBase.AddTextWriter (Stream stream, bool writeintro) inline
Creates a TextWriter from the stream and adds it to the list of TextWriters on which reporting is also performed. Overrides the writeintro property by the 'writeintro' argument.
Parameters
stream Textwriter to which reporting will be performed.
writeintro Overrides the class' writeintro property (if true then introductory text is printed, regardless of the value of the property). If the introductory text is printed then the standard method is used, taking into account the introtext and programname properties.
Returns
True if a new writer has been successfully set and is ready to use, false otherwise.
Implements IG.Lib.IReporterTextWriter.
Definition at line 4244 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.AddTextWriter(), and IG.Lib.ReporterBase.lockobj.
AddTextWriter() [6/10]
bool IG.Lib.ReporterBase.AddTextWriter (Stream stream, bool writeintro, bool disposewriter) inline
Creates a TextWriter from the stream and adds it to the list of TextWriters on which reporting is also performed. Overrides the writeintro property by the 'writeintro' argument.
Parameters
stream Textwriter to which reporting will be performed.
writeintro Overrides the class' writeintro property (if true then introductory text is printed, regardless of the value of the property). If the introductory text is printed then the standard method is used, taking into account the introtext and programname properties.
disposewriter Indicates whether the TextWriter should be disposed when not used any more. Default is false when specifying a stream.
Returns
True if a new writer has been successfully set and is ready to use, false otherwise.
Implements IG.Lib.IReporterTextWriter.
Definition at line 4262 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.AddTW(), IG.Lib.ReporterBase.lockobj, and IG.Lib.ReporterBase.Writers.
AddTextWriter() [7/10]
bool IG.Lib.ReporterBase.AddTextWriter (string filename) inline
Creates a TextWriter from the file name and adds it to the list of TextWriters on which reporting is also performed. The file is overwritten.
Parameters
filename Name of the file to which reporting will be performed.
Returns
True if a new writer has been successfully set and is ready to use, false otherwise.
Implements IG.Lib.IReporterTextWriter.
Definition at line 4276 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.AddTextWriter(), and IG.Lib.ReporterBase.TextWriterWriteIntro.
AddTextWriter() [8/10]
bool IG.Lib.ReporterBase.AddTextWriter (string filename, bool append) inline
Creates a TextWriter from the stream and adds it to the list of TextWriters on which reporting is also performed. The caller specifies either to overwrite the file or to append to it.
Parameters
filename Name of the file to which reporting will be performed.
append If false then eventual existing contents of the file are overwritten. Otherwise, new text is appended at the end of the file.
Returns
True if a new writer has been successfully set and is ready to use, false otherwise.
Implements IG.Lib.IReporterTextWriter.
Definition at line 4288 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.AddTextWriter(), and IG.Lib.ReporterBase.TextWriterWriteIntro.
AddTextWriter() [9/10]
bool IG.Lib.ReporterBase.AddTextWriter (string filename, bool append, bool writeintro) inline
Creates a TextWriter from the stream and adds it to the list of TextWriters on which reporting is also performed. The caller specifies whether to overwrite the file or to append to it, and whether the introductory text is written before reporting to the file begins.
Parameters
filename Name of the file to which reporting will be performed.
append If false then eventual existing contents of the file are overwritten. Otherwise, new text is appended at the end of the file.
writeintro Overrides the class' writeintro property (if true then introductory text is printed, regardless of the value of the property). If the introductory text is printed then the standard method is used, taking into account the introtext and programname properties.
Returns
True if a new writer has been successfully set and is ready to use, false otherwise.
Implements IG.Lib.IReporterTextWriter.
Definition at line 4305 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.AddTextWriter(), and IG.Lib.ReporterBase.lockobj.
AddTextWriter() [10/10]
bool IG.Lib.ReporterBase.AddTextWriter (string filename, bool append, bool writeintro, bool disposewriter) inline
Creates a TextWriter from the stream and adds it to the list of TextWriters on which reporting is also performed. The caller specifies whether to overwrite the file or to append to it, and whether the introductory text is written before reporting to the file begins.
Parameters
filename Name of the file to which reporting will be performed.
append If false then eventual existing contents of the file are overwritten. Otherwise, new text is appended at the end of the file.
writeintro Overrides the class' writeintro property (if true then introductory text is printed, regardless of the value of the property). If the introductory text is printed then the standard method is used, taking into account the introtext and programname properties.
disposewriter Indicates whether the TextWriter should be disposed when not used any more. Default is true when specifying a file name.
Returns
True if a new writer has been successfully set and is ready to use, false otherwise.
Implements IG.Lib.IReporterTextWriter.
Definition at line 4326 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.AddTW(), IG.Lib.ReporterBase.lockobj, and IG.Lib.ReporterBase.Writers.
RemoveTextWriters()
bool IG.Lib.ReporterBase.RemoveTextWriters () inline
Removes all text writers from the TextWriter subsystem. If appropriate, the corresponding text writer is closed.
Returns
true if al text writers were successfully removed, false if there were problems.
Implements IG.Lib.IReporterTextWriter.
Definition at line 4339 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.TWClass.ClearWriter(), IG.Lib.ReporterBase.DisposeWriter, IG.Lib.ReporterBase.lockobj, IG.Lib.ReporterBase.RemoveTextWriter(), IG.Lib.ReporterBase.Writer, and IG.Lib.ReporterBase.Writers.
Referenced by IG.Lib.ReporterBase.Dispose().
RemoveTextWriter() [1/4]
bool IG.Lib.ReporterBase.RemoveTextWriter () inline
Removes the default text writer from the TextWriter subsystem. If appropriate, the corresponding text writer is closed.
Returns
true if the text writer was successfully removed, false otherwise (also if there is no writer installed)
Implements IG.Lib.IReporterTextWriter.
Definition at line 4384 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.DisposeWriter, IG.Lib.ReporterBase.lockobj, and IG.Lib.ReporterBase.Writer.
Referenced by IG.Lib.ReporterBase.RemoveTextWriters().
RemoveTextWriter() [2/4]
bool IG.Lib.ReporterBase.RemoveTextWriter (TextWriter writer) inline
Removes the first object from Writers that contains the specified TextWriter. If appropriate, the corresponding text writer is closed.
Returns
true if the text writer was successfully removed, false otherwise (also if there is no writer installed corresponding the argument)
Implements IG.Lib.IReporterTextWriter.
Definition at line 4411 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.lockobj, IG.Lib.ReporterBase.RemoveTW(), and IG.Lib.ReporterBase.Writers.
RemoveTextWriter() [3/4]
bool IG.Lib.ReporterBase.RemoveTextWriter (Stream stream) inline
Removes the first object from Writers whose TextWriter has been created form the specified stream. If appropriate, the corresponding text writer is closed.
Returns
true if the text writer was successfully removed, false otherwise (also if there is no writer installed corresponding the argument)
Implements IG.Lib.IReporterTextWriter.
Definition at line 4424 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.lockobj, IG.Lib.ReporterBase.RemoveTW(), and IG.Lib.ReporterBase.Writers.
RemoveTextWriter() [4/4]
bool IG.Lib.ReporterBase.RemoveTextWriter (string filename) inline
Removes the first object from Writers whose TextWriter has been created form the file with the specified name. If appropriate, the corresponding text writer is closed.
Returns
true if the text writer was successfully removed, false otherwise (also if there is no writer installed corresponding the argument)
Implements IG.Lib.IReporterTextWriter.
Definition at line 4437 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.lockobj, IG.Lib.ReporterBase.RemoveTW(), and IG.Lib.ReporterBase.Writers.
TextWriterWriters() [1/2]
List<TextWriter> IG.Lib.ReporterBase.TextWriterWriters () inline
Returns a list of all text writers that are currently used by the reporter's text writer. Only text writers that are actually writable are included.
Returns
List of text writers that are currently used by the reporter's text writer (only those that are actually writable are included).
Implements IG.Lib.IReporterTextWriter.
Definition at line 4457 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.TextWriterFlush().
TextWriterWriters() [2/2]
List<TextWriter> IG.Lib.ReporterBase.TextWriterWriters (bool writableonly) inline
Returns a list of all text writers that are currently used by the reporter's text writer. Warning: Beware of thread safety issues! Blocks of code where the returned list is used should be enclosed in lock(reporter.lockobj){...} block (where reporter is the object through which this method was called).
Parameters
writableonly If true then only those text writers are listed that are actually writable. If false then all text writers are listed.
Returns
List of text writers that are currently used by the reporter's text writer.
Implements IG.Lib.IReporterTextWriter.
Definition at line 4470 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.lockobj, IG.Lib.ReporterBase.Writer, and IG.Lib.ReporterBase.Writers.
TextWriterNumWriters() [1/2]
int IG.Lib.ReporterBase.TextWriterNumWriters () inline
Returns the current number of text writers used by the reporter's text logging module. Only text writers that are actually writable are counted.
Returns
The current number of text writers used by the reporter's text logging module (only those that are actually writable are counted).
Implements IG.Lib.IReporterTextWriter.
Definition at line 4519 of file ReporterMsg.cs.
TextWriterNumWriters() [2/2]
int IG.Lib.ReporterBase.TextWriterNumWriters (bool writableonly) inline
Returns the current number of TextWriters used by the reporter's text logging module.
Parameters
writableonly If true then only those text writers are counted that are actually writable. If false then all text writers are returned.
Returns
The current number of text writers used by the reporter's text logging module.
Implements IG.Lib.IReporterTextWriter.
Definition at line 4529 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.lockobj, IG.Lib.ReporterBase.Writer, and IG.Lib.ReporterBase.Writers.
TextWriterFlush()
int IG.Lib.ReporterBase.TextWriterFlush () inline
Flushes all text writers of the Writer's TextWriter subsystem.
Returns
Number of writers that has actually been flushed.
Implements IG.Lib.IReporterTextWriter.
Definition at line 4576 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.lockobj, IG.Lib.ReporterBase.TextWriterFlushing, and IG.Lib.ReporterBase.TextWriterWriters().
Referenced by IG.Lib.ReporterBase.Dispose().
TextWriterWrite()
int IG.Lib.ReporterBase.TextWriterWrite (string str) inline
Writes a string to all text writers of the Writer's TextWriter subsystem.
Parameters
str String to be written.
Returns
Number of writers that the string has actually been written to.
Implements IG.Lib.IReporterTextWriter.
Definition at line 4605 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.lockobj, IG.Lib.ReporterBase.TextWriterFlushing, IG.Lib.ReporterBase.Writer, and IG.Lib.ReporterBase.Writers.
Referenced by IG.Lib.ReporterBase.DefaultReserveReportError(), and IG.Lib.ReporterBase.TextWriterWriteLine().
TextWriterWriteLine()
int IG.Lib.ReporterBase.TextWriterWriteLine (string str) inline
Similar to TextWriterWrite(), except that a newline is added at the end of the string.
Implements IG.Lib.IReporterTextWriter.
Definition at line 4656 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.TextWriterWrite().
Referenced by IG.Lib.ReporterBase.DefaultReport_TextWriter().
DefaultReport_TextWriter()
static void IG.Lib.ReporterBase.DefaultReport_TextWriter (ReporterBase reporter, ReportType messagetype, string location, string message) inline static protected
Default delegate for launching reports (actually logging reports) via text writer.
Parameters
reporter Reporter object where additional information can be found.
messagetype Type of the report(Error, Warning, Info...).
location Short string desctribing location where report was triggered.
message Message of the report.
Definition at line 4685 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.DefaultReportStringConsoleTimeStamp(), and IG.Lib.ReporterBase.TextWriterWriteLine().
DefaultReportLocation_TextWriter()
static string IG.Lib.ReporterBase.DefaultReportLocation_TextWriter (ReporterBase reporter, ReportType messagetype, string location, Exception ex) inline static protected
Delegate for assembling a location string for this kind of report.
Parameters
reporter Reporter object where additional information can be found.
messagetype Type of the report(Error, Warning, Info...).
location User provided location string.
ex Exception that triggered reporting.
Returns
Location string that can be used in a report.
Definition at line 4705 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.DefaultLocationString().
DefaultReportMessage_TextWriter()
static string IG.Lib.ReporterBase.DefaultReportMessage_TextWriter (ReporterBase reporter, ReportType messagetype, string basicmessage, Exception ex) inline static protected
Delegate for assembling a report message for this kind of report.
Parameters
reporter Reporter object where additional information can be found.
messagetype Type of the report(Error, Warning, Info...).
basicmessage User provided message string.
ex Exception that triggered reporting.
Returns
Message string that can be used in a report.
Definition at line 4718 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.DefaultMessageString().
Report_TextWriter()
virtual void IG.Lib.ReporterBase.Report_TextWriter (ReportType messagetype, string location, string message, Exception ex) inline protected virtual
Launches a report via text writers. Report is launched by using special delegates for this kind of reporting. If the corresponding delegates for error location and message are not specified then general delegates are used for this purporse, or location and message string are simple assembled by this function.
Parameters
messagetype Type of the report(Error, Warning, Info...).
location User provided location string.
message User provided message string.
ex Exception that triggered reporting.
Definition at line 4737 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.lockobj, IG.Lib.ReporterBase.ReportDlgTextWriter, IG.Lib.ReporterBase.ReportLocationDlg, IG.Lib.ReporterBase.ReportLocationDlgTextWriter, IG.Lib.ReporterBase.ReportMessageDlg, and IG.Lib.ReporterBase.ReportMessageDlgTextWriter.
Referenced by IG.Lib.ReporterBase.Report().
TextLoggerPrintIntro()
virtual void IG.Lib.ReporterBase.TextLoggerPrintIntro (TextWriter tw) inline protected virtual
Writes to a textwriter the introduction text that is usually printed before logging starts.
Parameters
tw The TextWriter that the text is written to.
Definition at line 4826 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.PrintIntro(), IG.Lib.ReporterBase.TextLoggerIntroText, and IG.Lib.ReporterBase.TextLoggerProgramName.
SetTextLogger() [1/10]
bool IG.Lib.ReporterBase.SetTextLogger (TextWriter writer) inline
Sets the text writer to which reporting is also performed.
Parameters
writer Textwriter to which reporting will be performed.
Returns
True if a new writer has been successfully set and is ready to use, false otherwise.
Implements IG.Lib.IReporterTextLogger.
Definition at line 4837 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.lockobj, and IG.Lib.ReporterBase.TextLoggerWriteIntro.
Referenced by IG.Lib.ReporterBase.ReadAppSettingsBasic(), and IG.Lib.ReporterBase.SetTextLogger().
SetTextLogger() [2/10]
bool IG.Lib.ReporterBase.SetTextLogger (TextWriter writer, bool writeintro) inline
Sets the basic text writer to which reporting is performed, but overrides the writeintro property by the 'writeintro' argument.
Parameters
writer Textwriter to which reporting will be performed.
writeintro Overrides the class' writeintro property (if true then introductory text is printed, regardless of the value of the property). If the introductory text is printed then the standard method is used, taking into account the introtext and programname properties.
Returns
True if a new writer has been successfully set and is ready to use, false otherwise.
Implements IG.Lib.IReporterTextLogger.
Definition at line 4853 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.lockobj, and IG.Lib.ReporterBase.SetTextLogger().
SetTextLogger() [3/10]
bool IG.Lib.ReporterBase.SetTextLogger (TextWriter writer, bool writeintro, bool disposewriter) inline
Sets the basic text writer to which reporting is performed, but overrides the writeintro property by the 'writeintro' argument.
Parameters
writer Textwriter to which reporting will be performed.
writeintro Overrides the class' writeintro property (if true then introductory text is printed, regardless of the value of the property). If the introductory text is printed then the standard method is used, taking into account the introtext and programname properties.
disposewriter Indicates whether the TextWriter should be disposed when not used any more. Default is false when specifying a textwriter.
Returns
True if a new writer has been successfully set and is ready to use, false otherwise.
Implements IG.Lib.IReporterTextLogger.
Definition at line 4871 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.DisposeLogger, IG.Lib.ReporterBase.lockobj, and IG.Lib.ReporterBase.SetTW().
SetTextLogger() [4/10]
bool IG.Lib.ReporterBase.SetTextLogger (Stream stream) inline
Creates a TextWriter upon the stream and sets it as the text writer to which reporting is also performed.
Parameters
stream Stream to which reporting will be performed.
Returns
True if a new writer has been successfully set and is ready to use, false otherwise.
Implements IG.Lib.IReporterTextLogger.
Definition at line 4883 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.lockobj, IG.Lib.ReporterBase.SetTextLogger(), and IG.Lib.ReporterBase.TextLoggerWriteIntro.
SetTextLogger() [5/10]
bool IG.Lib.ReporterBase.SetTextLogger (Stream stream, bool writeintro) inline
Creates a TextWriter upon the stream and sets it as the basic TextWriter to which reporting is performed. Overrides the writeintro property by the 'writeintro' argument.
Parameters
stream Textwriter to which reporting will be performed.
writeintro Overrides the class' writeintro property (if true then introductory text is printed, regardless of the value of the property). If the introductory text is printed then the standard method is used, taking into account the introtext and programname properties.
Returns
True if a new writer has been successfully set and is ready to use, false otherwise.
Implements IG.Lib.IReporterTextLogger.
Definition at line 4899 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.lockobj, and IG.Lib.ReporterBase.SetTextLogger().
SetTextLogger() [6/10]
bool IG.Lib.ReporterBase.SetTextLogger (Stream stream, bool writeintro, bool disposewriter) inline
Creates a TextWriter upon the stream and sets it as the basic TextWriter to which reporting is performed. Overrides the writeintro property by the 'writeintro' argument.
Parameters
stream Textwriter to which reporting will be performed.
writeintro Overrides the class' writeintro property (if true then introductory text is printed, regardless of the value of the property). If the introductory text is printed then the standard method is used, taking into account the introtext and programname properties.
disposewriter Indicates whether the TextWriter should be disposed when not used any more. Default is false when specifying a stream.
Returns
True if a new writer has been successfully set and is ready to use, false otherwise.
Implements IG.Lib.IReporterTextLogger.
Definition at line 4919 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.DisposeLogger, IG.Lib.ReporterBase.lockobj, and IG.Lib.ReporterBase.SetTW().
SetTextLogger() [7/10]
bool IG.Lib.ReporterBase.SetTextLogger (string filename) inline
Creates a TextWriter upon a file and sets it as the basic TextWriter to which reporting is also performed. The file is overwritten.
Parameters
filename Name of the file to which reporting will be performed.
Returns
True if a new writer has been successfully set and is ready to use, false otherwise.
Implements IG.Lib.IReporterTextLogger.
Definition at line 4933 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.lockobj, IG.Lib.ReporterBase.SetTextLogger(), and IG.Lib.ReporterBase.TextLoggerWriteIntro.
SetTextLogger() [8/10]
bool IG.Lib.ReporterBase.SetTextLogger (string filename, bool append) inline
Creates a TextWriter upon a file and sets it as the basic TextWriter to which reporting is also performed, where the caller specifies either to overwrite the file or to append to it.
Parameters
filename Name of the file to which reporting will be performed.
append If false then eventual existing contents of the file are overwritten. Otherwise, new text is appended at the end of the file.
Returns
True if a new writer has been successfully set and is ready to use, false otherwise.
Implements IG.Lib.IReporterTextLogger.
Definition at line 4948 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.lockobj, IG.Lib.ReporterBase.SetTextLogger(), and IG.Lib.ReporterBase.TextLoggerWriteIntro.
SetTextLogger() [9/10]
bool IG.Lib.ReporterBase.SetTextLogger (string filename, bool append, bool writeintro) inline
Creates a TextWriter upon a file and sets it as the text writer to which reporting is also performed. The caller specifies whether to overwrite the file or to append to it, and whether the introductory text is written before reporting to the file begins.
Parameters
filename Name of the file to which reporting will be performed.
append If false then eventual existing contents of the file are overwritten. Otherwise, new text is appended at the end of the file.
writeintro Overrides the class' writeintro property (if true then introductory text is printed, regardless of the value of the property). If the introductory text is printed then the standard method is used, taking into account the introtext and programname properties.
Returns
True if a new writer has been successfully set and is ready to use, false otherwise.
Implements IG.Lib.IReporterTextLogger.
Definition at line 4967 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.lockobj, and IG.Lib.ReporterBase.SetTextLogger().
SetTextLogger() [10/10]
bool IG.Lib.ReporterBase.SetTextLogger (string filename, bool append, bool writeintro, bool disposewriter) inline
Creates a TextWriter upon a file and sets it as the text writer to which reporting is also performed. The caller specifies whether to overwrite the file or to append to it, and whether the introductory text is written before reporting to the file begins.
Parameters
filename Name of the file to which reporting will be performed.
append If false then eventual existing contents of the file are overwritten. Otherwise, new text is appended at the end of the file.
writeintro Overrides the class' writeintro property (if true then introductory text is printed, regardless of the value of the property). If the introductory text is printed then the standard method is used, taking into account the introtext and programname properties.
disposewriter Indicates whether the TextWriter should be disposed when not used any more. Default is true when specifying a file name.
Returns
True if a new writer has been successfully set and is ready to use, false otherwise.
Implements IG.Lib.IReporterTextLogger.
Definition at line 4988 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.DisposeLogger, IG.Lib.ReporterBase.lockobj, and IG.Lib.ReporterBase.SetTW().
AddTextLogger() [1/10]
bool IG.Lib.ReporterBase.AddTextLogger (TextWriter writer) inline
Sets the text writer to which reporting is also performed.
Parameters
writer Textwriter to which reporting will be performed.
Returns
True if a new writer has been successfully set and is ready to use, false otherwise.
Implements IG.Lib.IReporterTextLogger.
Definition at line 5004 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.lockobj, and IG.Lib.ReporterBase.TextLoggerWriteIntro.
Referenced by IG.Lib.ReporterBase.AddTextLogger(), and IG.Lib.ReporterBase.ReadAppSettingsBasic().
AddTextLogger() [2/10]
bool IG.Lib.ReporterBase.AddTextLogger (TextWriter writer, bool writeintro) inline
Sets the basic text writer to which reporting is performed, but overrides the writeintro property by the 'writeintro' argument.
Parameters
writer Textwriter to which reporting will be performed.
writeintro Overrides the class' writeintro property (if true then introductory text is printed, regardless of the value of the property). If the introductory text is printed then the standard method is used, taking into account the introtext and programname properties.
Returns
True if a new writer has been successfully set and is ready to use, false otherwise.
Implements IG.Lib.IReporterTextLogger.
Definition at line 5020 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.AddTextLogger(), and IG.Lib.ReporterBase.lockobj.
AddTextLogger() [3/10]
bool IG.Lib.ReporterBase.AddTextLogger (TextWriter writer, bool writeintro, bool disposewriter) inline
Sets the basic text writer to which reporting is performed, but overrides the writeintro property by the 'writeintro' argument.
Parameters
writer Textwriter to which reporting will be performed.
writeintro Overrides the class' writeintro property (if true then introductory text is printed, regardless of the value of the property). If the introductory text is printed then the standard method is used, taking into account the introtext and programname properties.
disposewriter Indicates whether the TextWriter should be disposed when not used any more. Default is false when specifying a textwriter.
Returns
True if a new writer has been successfully set and is ready to use, false otherwise.
Implements IG.Lib.IReporterTextLogger.
Definition at line 5038 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.AddTW(), IG.Lib.ReporterBase.lockobj, and IG.Lib.ReporterBase.Loggers.
AddTextLogger() [4/10]
bool IG.Lib.ReporterBase.AddTextLogger (Stream stream) inline
Creates a TextWriter from the stream and adds it to the list of TextWriters on which reporting is also performed.
Parameters
stream Stream to which reporting will be performed.
Returns
True if a new writer has been successfully set and is ready to use, false otherwise.
Implements IG.Lib.IReporterTextLogger.
Definition at line 5052 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.AddTextLogger(), IG.Lib.ReporterBase.lockobj, and IG.Lib.ReporterBase.TextLoggerWriteIntro.
AddTextLogger() [5/10]
bool IG.Lib.ReporterBase.AddTextLogger (Stream stream, bool writeintro) inline
Creates a TextWriter from the stream and adds it to the list of TextWriters on which reporting is also performed. Overrides the writeintro property by the 'writeintro' argument.
Parameters
stream Textwriter to which reporting will be performed.
writeintro Overrides the class' writeintro property (if true then introductory text is printed, regardless of the value of the property). If the introductory text is printed then the standard method is used, taking into account the introtext and programname properties.
Returns
True if a new writer has been successfully set and is ready to use, false otherwise.
Implements IG.Lib.IReporterTextLogger.
Definition at line 5068 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.AddTextLogger(), and IG.Lib.ReporterBase.lockobj.
AddTextLogger() [6/10]
bool IG.Lib.ReporterBase.AddTextLogger (Stream stream, bool writeintro, bool disposewriter) inline
Creates a TextWriter from the stream and adds it to the list of TextWriters on which reporting is also performed. Overrides the writeintro property by the 'writeintro' argument.
Parameters
stream Textwriter to which reporting will be performed.
writeintro Overrides the class' writeintro property (if true then introductory text is printed, regardless of the value of the property). If the introductory text is printed then the standard method is used, taking into account the introtext and programname properties.
disposewriter Indicates whether the TextWriter should be disposed when not used any more. Default is false when specifying a stream.
Returns
True if a new writer has been successfully set and is ready to use, false otherwise.
Implements IG.Lib.IReporterTextLogger.
Definition at line 5086 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.AddTW(), IG.Lib.ReporterBase.lockobj, and IG.Lib.ReporterBase.Loggers.
AddTextLogger() [7/10]
bool IG.Lib.ReporterBase.AddTextLogger (string filename) inline
Creates a TextWriter from the file name and adds it to the list of TextWriters on which reporting is also performed. The file is overwritten.
Parameters
filename Name of the file to which reporting will be performed.
Returns
True if a new writer has been successfully set and is ready to use, false otherwise.
Implements IG.Lib.IReporterTextLogger.
Definition at line 5100 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.AddTextLogger(), and IG.Lib.ReporterBase.TextLoggerWriteIntro.
AddTextLogger() [8/10]
bool IG.Lib.ReporterBase.AddTextLogger (string filename, bool append) inline
Creates a TextWriter from the stream and adds it to the list of TextWriters on which reporting is also performed. The caller specifies either to overwrite the file or to append to it.
Parameters
filename Name of the file to which reporting will be performed.
append If false then eventual existing contents of the file are overwritten. Otherwise, new text is appended at the end of the file.
Returns
True if a new writer has been successfully set and is ready to use, false otherwise.
Implements IG.Lib.IReporterTextLogger.
Definition at line 5112 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.AddTextLogger(), and IG.Lib.ReporterBase.TextLoggerWriteIntro.
AddTextLogger() [9/10]
bool IG.Lib.ReporterBase.AddTextLogger (string filename, bool append, bool writeintro) inline
Creates a TextWriter from the stream and adds it to the list of TextWriters on which reporting is also performed. The caller specifies whether to overwrite the file or to append to it, and whether the introductory text is written before reporting to the file begins.
Parameters
filename Name of the file to which reporting will be performed.
append If false then eventual existing contents of the file are overwritten. Otherwise, new text is appended at the end of the file.
writeintro Overrides the class' writeintro property (if true then introductory text is printed, regardless of the value of the property). If the introductory text is printed then the standard method is used, taking into account the introtext and programname properties.
Returns
True if a new writer has been successfully set and is ready to use, false otherwise.
Implements IG.Lib.IReporterTextLogger.
Definition at line 5129 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.AddTextLogger(), and IG.Lib.ReporterBase.lockobj.
AddTextLogger() [10/10]
bool IG.Lib.ReporterBase.AddTextLogger (string filename, bool append, bool writeintro, bool disposewriter) inline
Creates a TextWriter from the stream and adds it to the list of TextWriters on which reporting is also performed. The caller specifies whether to overwrite the file or to append to it, and whether the introductory text is written before reporting to the file begins.
Parameters
filename Name of the file to which reporting will be performed.
append If false then eventual existing contents of the file are overwritten. Otherwise, new text is appended at the end of the file.
writeintro Overrides the class' writeintro property (if true then introductory text is printed, regardless of the value of the property). If the introductory text is printed then the standard method is used, taking into account the introtext and programname properties.
disposewriter Indicates whether the TextWriter should be disposed when not used any more. Default is true when specifying a file name.
Returns
True if a new writer has been successfully set and is ready to use, false otherwise.
Implements IG.Lib.IReporterTextLogger.
Definition at line 5150 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.AddTW(), IG.Lib.ReporterBase.lockobj, and IG.Lib.ReporterBase.Loggers.
RemoveTextLoggers()
bool IG.Lib.ReporterBase.RemoveTextLoggers () inline
Removes all text writers from the TextLogger subsystem. If appropriate, the corresponding text writer is closed.
Returns
true if al text writers were successfully removed, false if there were problems.
Implements IG.Lib.IReporterTextLogger.
Definition at line 5164 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.TWClass.ClearWriter(), IG.Lib.ReporterBase.DisposeLogger, IG.Lib.ReporterBase.lockobj, IG.Lib.ReporterBase.Loggers, and IG.Lib.ReporterBase.RemoveTextLogger().
Referenced by IG.Lib.ReporterBase.Dispose().
RemoveTextLogger() [1/4]
bool IG.Lib.ReporterBase.RemoveTextLogger () inline
Removes the default text writer from the TextLogger subsystem. If appropriate, the corresponding txt writer is closed.
Returns
true if the text writer was successfully removed, false otherwise (also if there is no writer installed)
Implements IG.Lib.IReporterTextLogger.
Definition at line 5209 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.DisposeLogger, and IG.Lib.ReporterBase.lockobj.
Referenced by IG.Lib.ReporterBase.RemoveTextLoggers().
RemoveTextLogger() [2/4]
bool IG.Lib.ReporterBase.RemoveTextLogger (TextWriter writer) inline
Removes the first object from Loggers that contains the specified TextWriter. If appropriate, the corresponding text writer is closed.
Returns
true if the text writer was successfully removed, false otherwise (also if there is no writer installed corresponding the argument)
Implements IG.Lib.IReporterTextLogger.
Definition at line 5236 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.lockobj, IG.Lib.ReporterBase.Loggers, and IG.Lib.ReporterBase.RemoveTW().
RemoveTextLogger() [3/4]
bool IG.Lib.ReporterBase.RemoveTextLogger (Stream stream) inline
Removes the first object from Loggers whose TextWriter has been created form the specified stream. If appropriate, the corresponding text writer is closed.
Returns
true if the text writer was successfully removed, false otherwise (also if there is no writer installed corresponding the argument)
Implements IG.Lib.IReporterTextLogger.
Definition at line 5250 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.lockobj, IG.Lib.ReporterBase.Loggers, and IG.Lib.ReporterBase.RemoveTW().
RemoveTextLogger() [4/4]
bool IG.Lib.ReporterBase.RemoveTextLogger (string filename) inline
Removes the first object from Loggers whose TextWriter has been created form the file with the specified name. If appropriate, the corresponding text writer is closed.
Returns
true if the text writer was successfully removed, false otherwise (also if there is no writer installed corresponding the argument)
Implements IG.Lib.IReporterTextLogger.
Definition at line 5263 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.lockobj, IG.Lib.ReporterBase.Loggers, and IG.Lib.ReporterBase.RemoveTW().
TextLoggerWriters() [1/2]
List<TextWriter> IG.Lib.ReporterBase.TextLoggerWriters () inline
Returns a list of all text writers that are currently used by the reporter's text logger. Only text writers that are actually writable are included.
Returns
List of text writers that are currently used by the reporter's text logger (only those that are actually writable are included).
Implements IG.Lib.IReporterTextLogger.
Definition at line 5283 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.TextLoggerFlush().
TextLoggerWriters() [2/2]
List<TextWriter> IG.Lib.ReporterBase.TextLoggerWriters (bool writableonly) inline
Returns a list of all text writers that are currently used by the reporter's text logger. Warning: Beware of thread safety issues! Blocks of code where the returned list is used should be enclosed in lock(reporter.lockobj){...} block (where reporter is the object through which this method was called).
Parameters
writableonly If true then only those text writers are listed that are actually writable. If false then all text writers are listed.
Returns
List of text writers that are currently used by the reporter's text logger.
Implements IG.Lib.IReporterTextLogger.
Definition at line 5296 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.lockobj, IG.Lib.ReporterBase.Logger, and IG.Lib.ReporterBase.Loggers.
TextLoggerNumWriters() [1/2]
int IG.Lib.ReporterBase.TextLoggerNumWriters () inline
Returns the current number of text writers used by the reporter's text logging module. Only text writers that are actually writable are counted.
Returns
The current number of text writers used by the reporter's text logging module (only those that are actually writable are counted).
Implements IG.Lib.IReporterTextLogger.
Definition at line 5345 of file ReporterMsg.cs.
TextLoggerNumWriters() [2/2]
int IG.Lib.ReporterBase.TextLoggerNumWriters (bool writableonly) inline
Returns the current number of TextWriters used by the reporter's text logging module.
Parameters
writableonly If true then only those text writers are counted that are actually writable. If false then all text writers are returned.
Returns
The current number of text writers used by the reporter's text logging module.
Implements IG.Lib.IReporterTextLogger.
Definition at line 5355 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.lockobj, IG.Lib.ReporterBase.Logger, and IG.Lib.ReporterBase.Loggers.
TextLoggerFlush()
int IG.Lib.ReporterBase.TextLoggerFlush () inline
Flushes all text writers of the Writer's TextLogger subsystem.
Returns
Number of writers that has actually been flushed.
Implements IG.Lib.IReporterTextLogger.
Definition at line 5402 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.lockobj, IG.Lib.ReporterBase.TextLoggerFlushing, and IG.Lib.ReporterBase.TextLoggerWriters().
Referenced by IG.Lib.ReporterBase.Dispose().
TextLoggerWrite()
int IG.Lib.ReporterBase.TextLoggerWrite (string str) inline
Writes a string to all text writers of the Writer's TextLogger subsystem.
Parameters
str String to be written.
Returns
Number of writers that the string has actually been written to.
Implements IG.Lib.IReporterTextLogger.
Definition at line 5431 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.lockobj, IG.Lib.ReporterBase.Loggers, and IG.Lib.ReporterBase.TextLoggerFlushing.
Referenced by IG.Lib.ReporterBase.DefaultReserveReportError(), and IG.Lib.ReporterBase.TextLoggerWriteLine().
TextLoggerWriteLine()
int IG.Lib.ReporterBase.TextLoggerWriteLine (string str) inline
Similar to TextLoggerWrite(), except that a newline is added at the end of the string.
Implements IG.Lib.IReporterTextLogger.
Definition at line 5482 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.TextLoggerWrite().
Referenced by IG.Lib.ReporterBase.DefaultReport_TextLogger().
FormatLogMsgDefault()
static string IG.Lib.ReporterBase.FormatLogMsgDefault (int depth, int initialindent, int indentincrement, char indentchar, ReportType type, string location, string message, ReportSource source) inline static
Formats a one-line message for tracing output.
Parameters
depth Indentation level.
initialindent Initial indentation.
indentincrement Indentation spacing.
indentchar Indentation character.
type Type of the message.
location String denoting location of the message.
message Message to be output.
source Indication of message source.
Returns
String taht is output as the one-line message.
Definition at line 5514 of file ReporterMsg.cs.
References IG.Lib.ReporterBase._newLineReplacement.
Referenced by IG.Lib.ReporterBase.DefaultReport_TextLogger().
DefaultReport_TextLogger()
static void IG.Lib.ReporterBase.DefaultReport_TextLogger (ReporterBase reporter, ReportType messagetype, string location, string message) inline static protected
Default delegate for launching reports (actually logging reports) via text writer.
Parameters
reporter Reporter object where additional information can be found.
messagetype Type of the report(Error, Warning, Info...).
location Short string desctribing location where report was triggered.
message Message of the report.
Definition at line 5564 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.Depth, IG.Lib.ReporterBase.FormatLogMsgDefault(), IG.Lib.ReporterBase.MsgSource, IG.Lib.ReporterBase.TextLoggerIndentCharacter, IG.Lib.ReporterBase.TextLoggerIndentInitial, IG.Lib.ReporterBase.TextLoggerIndentSpacing, and IG.Lib.ReporterBase.TextLoggerWriteLine().
DefaultReportLocation_TextLogger()
static string IG.Lib.ReporterBase.DefaultReportLocation_TextLogger (ReporterBase reporter, ReportType messagetype, string location, Exception ex) inline static protected
Delegate for assembling a location string for this kind of report.
Parameters
reporter Reporter object where additional information can be found.
messagetype Type of the report(Error, Warning, Info...).
location User provided location string.
ex Exception that triggered reporting.
Returns
Location string that can be used in a report.
Definition at line 5585 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.DefaultLocationString().
DefaultReportMessage_TextLogger()
static string IG.Lib.ReporterBase.DefaultReportMessage_TextLogger (ReporterBase reporter, ReportType messagetype, string basicmessage, Exception ex) inline static protected
Delegate for assembling a report message for this kind of report.
Parameters
reporter Reporter object where additional information can be found.
messagetype Type of the report(Error, Warning, Info...).
basicmessage User provided message string.
ex Exception that triggered reporting.
Returns
Message string that can be used in a report.
Definition at line 5598 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.DefaultMessageString().
Report_TextLogger()
virtual void IG.Lib.ReporterBase.Report_TextLogger (ReportType messagetype, string location, string message, Exception ex) inline protected virtual
Launches a report via text logger. Report is launched by using special delegates for this kind of reporting. If the corresponding delegates for error location and message are not specified then general delegates are used for this purporse, or location and message string are simple assembled by this function.
Parameters
messagetype Type of the report(Error, Warning, Info...).
location User provided location string.
message User provided message string.
ex Exception that triggered reporting.
Definition at line 5617 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.lockobj, IG.Lib.ReporterBase.ReportDlgTextLogger, IG.Lib.ReporterBase.ReportLocationDlg, IG.Lib.ReporterBase.ReportLocationDlgTextLogger, IG.Lib.ReporterBase.ReportMessageDlg, and IG.Lib.ReporterBase.ReportMessageDlgTextLogger.
Referenced by IG.Lib.ReporterBase.Report().
FormatTraceMsgDefault()
static string IG.Lib.ReporterBase.FormatTraceMsgDefault (int depth, int initialindent, int indentincrement, char indentchar, ReportType type, string location, string message, ReportSource source) inline static
Formats a one-line message for tracing output.
Parameters
depth Indentation level.
initialindent Initial indent.
indentincrement Indentation spacing.
indentchar Indentation character.
type Type of the message.
location String denoting location of the message.
message Message to be output.
source Indication of message source.
Returns
String taht is output as the one-line message.
Definition at line 5708 of file ReporterMsg.cs.
References IG.Lib.ReporterBase._newLineReplacement.
Referenced by IG.Lib.ReporterBase.DefaultReport_Trace().
DefaultReport_Trace()
static void IG.Lib.ReporterBase.DefaultReport_Trace (ReporterBase reporter, ReportType messagetype, string location, string message) inline static protected
Delegat for launching a report via Trace.
Parameters
reporter Reporter object where additional information can be found.
messagetype Type of the report(Error, Warning, Info...).
location Short string desctribing location where report was triggered.
message Message of the report.
Definition at line 5757 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.Depth, IG.Lib.ReporterBase.FormatTraceMsgDefault(), IG.Lib.ReporterBase.MsgSource, IG.Lib.ReporterBase.TextLoggerIndentCharacter, IG.Lib.ReporterBase.TextLoggerIndentInitial, and IG.Lib.ReporterBase.TextLoggerIndentSpacing.
DefaultReportLocation_Trace()
static string IG.Lib.ReporterBase.DefaultReportLocation_Trace (ReporterBase reporter, ReportType messagetype, string location, Exception ex) inline static protected
Delegate for assembling a location string for this kind of report.
Parameters
reporter Reporter object where additional information can be found.
messagetype Type of the report(Error, Warning, Info...).
location User provided location string.
ex Exception that triggered reporting.
Returns
Location string that can be used in a report.
Definition at line 5775 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.DefaultLocationString().
DefaultReportMessage_Trace()
static string IG.Lib.ReporterBase.DefaultReportMessage_Trace (ReporterBase reporter, ReportType messagetype, string basicmessage, Exception ex) inline static protected
Delegate for assembling a report message for this kind of report.
Parameters
reporter Reporter object where additional information can be found.
messagetype Type of the report(Error, Warning, Info...).
basicmessage User provided message string.
ex Exception that triggered reporting.
Returns
Message string that can be used in a report.
Definition at line 5788 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.DefaultMessageString().
Report_Trace()
virtual void IG.Lib.ReporterBase.Report_Trace (ReportType messagetype, string location, string message, Exception ex) inline protected virtual
Launches a report via Trace. Report is launched by using special delegates for this kind of reporting. If the corresponding delegates for error location and message are not specified then general delegates are used for this purporse, or location and message string are simple assembled by this function.
Parameters
messagetype Type of the report(Error, Warning, Info...).
location User provided location string.
message User provided message string.
ex Exception that triggered reporting.
Definition at line 5804 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.ReportDlgTrace, IG.Lib.ReporterBase.ReportLocationDlg, IG.Lib.ReporterBase.ReportLocationDlgTrace, IG.Lib.ReporterBase.ReportMessageDlg, and IG.Lib.ReporterBase.ReportMessageDlgTrace.
Referenced by IG.Lib.ReporterBase.Report().
DefaultReportStringMessageBox()
static string IG.Lib.ReporterBase.DefaultReportStringMessageBox (ReporterBase reporter, ReportType messagetype, string errorlocation, string errormessage) inline static
Auxiliary method that composes the complete message, including decoration, for reports launched in a message box.
Parameters
reporter Reporter object used for reporting.
messagetype Level of the message that is reported (Error, Warning, ...)
errorlocation User description of location that caused the report.
errormessage User defined message.
Returns
String that is output by the report.
Definition at line 5862 of file ReporterMsg.cs.
DefaultReportStringConsole()
static string IG.Lib.ReporterBase.DefaultReportStringConsole (ReporterBase reporter, ReportType messagetype, string errorlocation, string errormessage) inline static
Auxiliary method that composes the complete message, including decoration, for reports launched in consoles.
Parameters
reporter Reporter object used for reporting.
messagetype Level of the message that is reported (Error, Warning, ...)
errorlocation User description of location that caused the report.
errormessage User defined message.
Returns
String that is output by the report.
Definition at line 5902 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.DefaultReportStringConsoleBas().
DefaultReportStringConsoleTimeStamp()
static string IG.Lib.ReporterBase.DefaultReportStringConsoleTimeStamp (ReporterBase reporter, ReportType messagetype, string errorlocation, string errormessage) inline static
Auxiliary method that composes the complete message, including decoration with a TIMESTAMP, for reports launched in consoles.
Parameters
reporter Reporter object used for reporting.
messagetype Level of the message that is reported (Error, Warning, ...)
errorlocation User description of location that caused the report.
errormessage User defined message.
Returns
String that is output by the report.
Definition at line 5916 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.DefaultReportStringConsoleBas().
Referenced by IG.Lib.ReporterBase.DefaultReport_TextWriter(), and IG.Lib.ReporterBase.DefaultReportConsole().
DefaultReportStringConsoleBas()
static string IG.Lib.ReporterBase.DefaultReportStringConsoleBas (ReporterBase reporter, ReportType messagetype, string errorlocation, string errormessage, bool timestamp) inline static
Base method for DefaultReportStringConsole and DefaultReportStringConsoleTimeStamp.
Parameters
reporter Reporter object used for reporting.
messagetype Level of the message that is reported (Error, Warning, ...)
errorlocation User description of location that caused the report.
errormessage User defined message.
timestamp Specifies whether to include a time stamp in the message.
Returns
String that is output by the report.
Definition at line 5930 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.DefaultReportStringConsole(), and IG.Lib.ReporterBase.DefaultReportStringConsoleTimeStamp().
DefaultReportConsole()
static void IG.Lib.ReporterBase.DefaultReportConsole (ReporterBase reporter, ReportType messagetype, string errorlocation, string errormessage) inline static
Default delegate for reporting. For parameter descriptions, see ReportDlg.
Definition at line 5973 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.DefaultReportStringConsoleTimeStamp().
Referenced by IG.Lib.ReporterConsole_Base.DefaultReport_Console().
DefaultLocationString()
static string IG.Lib.ReporterBase.DefaultLocationString (ReporterBase reporter, ReportType messagetype, string location, Exception ex) inline static
Default delegate for assembly of the location string when reporting on consoles. For parameter descriptions, see ReportMessageDlg.
Definition at line 5984 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.ErrorLocationString0().
Referenced by IG.Lib.ReporterConsole_Base.DefaultReportLocation_Console(), IG.Lib.ReporterBase.DefaultReportLocation_TextLogger(), IG.Lib.ReporterBase.DefaultReportLocation_TextWriter(), IG.Lib.ReporterBase.DefaultReportLocation_Trace(), IG.Lib.ReporterConsole.SetDefaultReportLocationDlg(), and IG.Lib.ReporterBase.SetDefaultReportLocationDlg().
DefaultMessageString()
static string IG.Lib.ReporterBase.DefaultMessageString (ReporterBase reporter, ReportType messagetype, string basicmessage, Exception ex) inline static
Default delegate for message assembly of the message string when reporting on consoles. For parameter descriptions, see ReportMessageDlg.
Definition at line 6007 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterConsole_Base.DefaultReportMessage_Console(), IG.Lib.ReporterBase.DefaultReportMessage_TextLogger(), IG.Lib.ReporterBase.DefaultReportMessage_TextWriter(), IG.Lib.ReporterBase.DefaultReportMessage_Trace(), IG.Lib.ReporterConsole.SetDefaultReportMessageDlg(), and IG.Lib.ReporterBase.SetDefaultReportMessageDlg().
DefaultReserveReportMessage()
static string IG.Lib.ReporterBase.DefaultReserveReportMessage (ReporterBase reporter, ReportType messagetype, string location, string message, Exception ex, Exception ex1) inline static
Default function function for assembling reserve error reporting message. This is put outside the DefaultReserveReportError() method such that the same assembly method can be used in different systems. The method is considered bulletproof.
Parameters
reporter Rporter to which message is passed.
messagetype Level of the message (Error, Warning,Info, etc.)
location Location string as passed to the error reporting function that has thrown an exception.
message Error message string as passed to the error reporting function that has thrown an exception.
ex Original exception that was being reported when the error reporting function threw an exception.
ex1 Exception thrown by the error reporting function.
Definition at line 6051 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.DefaultReserveReportError().
DefaultReserveReportError()
static void IG.Lib.ReporterBase.DefaultReserveReportError (ReporterBase reporter, ReportType messagetype, string location, string message, Exception ex, Exception ex1) inline static
Default function function for reserve error reporting (called if an exception is thrown in a reporting function). Writes a report to the application's standard console (if defined) and Reporter's text writers and loggers (when defined). Writing is unconditional (e.g., even if reporter.UseTextWriter = false or reporter.ReportingLevel = Off, a message is written to the TextWriter's output streams).
Parameters
reporter Reporter object whre the method can get additional information.
messagetype Level of the message (Error, Warning,Info, etc.)
location Location string as passed to the error reporting function that has thrown an exception.
message Error message string as passed to the error reporting function that has thrown an exception.
ex Original exception that was being reported when the error reporting function threw an exception.
ex1 Exception thrown by the error reporting function.
Definition at line 6148 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.DefaultReserveReportMessage(), IG.Lib.ReporterBase.TextLoggerWrite(), and IG.Lib.ReporterBase.TextWriterWrite().
Referenced by IG.Lib.ReporterBase.ReserveReportErrorSpecific().
ErrorLocationString0() [1/2]
static string IG.Lib.ReporterBase.ErrorLocationString0 (Exception ex) inline static
Returns location string derived from ex, which includes information about the location where error occurred, specified by the source file name, function and line and column numbers.
Parameters
ex
Returns
Definition at line 6209 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.DefaultLocationString(), and IG.Lib.ReporterBase.ErrorLocationString0().
ErrorLocationString0() [2/2]
static string IG.Lib.ReporterBase.ErrorLocationString0 (string location, Exception ex) inline static
Returns Error location string derived from ex, which includes information about location of error occurrence and is prepended by additional location information (such as class name)
Parameters
location
ex
Returns
Definition at line 6252 of file ReporterMsg.cs.
References IG.Lib.ReporterBase.ErrorLocationString0().
GetErorString()
static string IG.Lib.ReporterBase.GetErorString (Exception e) inline static
Returns an error string that concisely describes information contained in the specific exception (including location where exception was thrown, and its message).
Parameters
e Exception from which information is extracted and represented as string.
Definition at line 6282 of file ReporterMsg.cs.
Test()
static void IG.Lib.ReporterBase.Test () inline static private
Definition at line 6704 of file ReporterMsg.cs.
Member Data Documentation
ReportDlg
ReportDelegate IG.Lib.ReporterBase.ReportDlg = null
Delegate that performs error reporting. It calls delegates ReportDlg to assemble error location information and ReportMessageDlg to assemble error message. Then it uses both to assemble the final decorated error message and launches it in its own way.
Definition at line 1193 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.InitBegin(), IG.Lib.ReporterBase.InitEnd(), IG.Lib.ReporterBase.Report(), IG.Lib.ReporterConsole.SetDefaultReportDlg(), and IG.Lib.ReporterBase.SetDefaultReportDlg().
ReportLocationDlg
ReportLocationDelegate IG.Lib.ReporterBase.ReportLocationDlg = null
Delegate that assembles the error location string.
Definition at line 1196 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.InitBegin(), IG.Lib.ReporterBase.InitEnd(), IG.Lib.ReporterBase.Report(), IG.Lib.ReporterConsole_Base.Report_Console(), IG.Lib.ReporterBase.Report_TextLogger(), IG.Lib.ReporterBase.Report_TextWriter(), IG.Lib.ReporterBase.Report_Trace(), IG.Lib.ReporterConsole.SetDefaultReportLocationDlg(), and IG.Lib.ReporterBase.SetDefaultReportLocationDlg().
ReportMessageDlg
ReportMessageDelegate IG.Lib.ReporterBase.ReportMessageDlg = null
Delegate that assembles the eror message string.
Definition at line 1199 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.InitBegin(), IG.Lib.ReporterBase.InitEnd(), IG.Lib.ReporterBase.Report(), IG.Lib.ReporterConsole_Base.Report_Console(), IG.Lib.ReporterBase.Report_TextLogger(), IG.Lib.ReporterBase.Report_TextWriter(), IG.Lib.ReporterBase.Report_Trace(), IG.Lib.ReporterConsole.SetDefaultReportMessageDlg(), and IG.Lib.ReporterBase.SetDefaultReportMessageDlg().
ReserveReportErrorDlg
ReserveReportErrorDelegate IG.Lib.ReporterBase.ReserveReportErrorDlg = null
Delegate that reports an error when the error reporting function throws an exception. Functions assigned to this delegate should really be BULLETPROOF. If not assigned then the internal method of the corresponding class is called. It is highly recommended to do reporting in small steps enclosed in try/catch blocks and especially to use the error reporting object very carefully (because it may not be initialized properly, which can also be the reason that the error reporting function crashes). It is higly recommended to first call the DefaultReserveReportError() within the function assigned to this delegate, or at least to use the DefaultReserveReportMessage() method for assembly of the message shown.
Definition at line 1209 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.InitBegin(), IG.Lib.ReporterBase.InitEnd(), IG.Lib.ReporterBase.ReserveReportError(), IG.Lib.ReporterConsole.SetDefaultReserveReportErrorDlg(), and IG.Lib.ReporterBase.SetDefaultReserveReportErrorDlg().
isDisposed
bool IG.Lib.ReporterBase.isDisposed = false private
Definition at line 1478 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.Dispose().
dispLocked
bool IG.Lib.ReporterBase.dispLocked = false private
Definition at line 1478 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.Dispose().
_Global
ReporterBase IG.Lib.ReporterBase._Global = null static private
Definition at line 1548 of file ReporterMsg.cs.
_GlobalInitialized
bool IG.Lib.ReporterBase._GlobalInitialized = false static private
Definition at line 1549 of file ReporterMsg.cs.
GlobalLock
object IG.Lib.ReporterBase.GlobalLock = new object() static private
Definition at line 1550 of file ReporterMsg.cs.
ReadGlobalAppSettings
bool IG.Lib.ReporterBase.ReadGlobalAppSettings = true static
Indicates whether a global Reporter (or its derived class) should read settings from the application configuration file when initialized (default is true).
Definition at line 1560 of file ReporterMsg.cs.
KeyPrefix
const string IG.Lib.ReporterBase.KeyPrefix = "ReporterMsg" static protected
Definition at line 2021 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.FullKey().
readconf
List<String> IG.Lib.ReporterBase.readconf = null private
Definition at line 2206 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.AppSettingsRead(), and IG.Lib.ReporterBase.MarkAppSettingsRead().
_AppSettingsWarnings
bool IG.Lib.ReporterBase._AppSettingsWarnings = true private
Definition at line 2244 of file ReporterMsg.cs.
KeyLevelOn
const string IG.Lib.ReporterBase.KeyLevelOn = "LevelOn" static protected
Definition at line 2304 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.ReadAppSettingsBasic().
KeyLevelOff
const string IG.Lib.ReporterBase.KeyLevelOff = "LevelOff" static private
Definition at line 2305 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.ReadAppSettingsBasic().
KeyReportingLevel
const string IG.Lib.ReporterBase.KeyReportingLevel = "ReportingLevel" static private
Definition at line 2306 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.ReadAppSettingsBasic().
KeyLoggingLevel
const string IG.Lib.ReporterBase.KeyLoggingLevel = "LoggingLevel" static private
Definition at line 2307 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.ReadAppSettingsBasic().
KeyTracingLevel
const string IG.Lib.ReporterBase.KeyTracingLevel = "TracingLevel" static private
Definition at line 2308 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.ReadAppSettingsBasic().
KeyUseTextWriter
const string IG.Lib.ReporterBase.KeyUseTextWriter = "UseTextWriter" static private
Definition at line 2310 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.ReadAppSettingsBasic().
KeyUseTextLogger
const string IG.Lib.ReporterBase.KeyUseTextLogger = "UseTextLogger" static private
Definition at line 2311 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.ReadAppSettingsBasic().
KeyUseTrace
const string IG.Lib.ReporterBase.KeyUseTrace = "UseTrace" static private
Definition at line 2312 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.ReadAppSettingsBasic().
KeyTextWriterAppend
const string IG.Lib.ReporterBase.KeyTextWriterAppend = "TextWriterAppend" static private
Definition at line 2314 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.ReadAppSettingsBasic().
KeyTextWriterFile
const string IG.Lib.ReporterBase.KeyTextWriterFile = "TextWriterFile" static private
Definition at line 2316 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.ReadAppSettingsBasic().
KeyTextWriterFile1
const string IG.Lib.ReporterBase.KeyTextWriterFile1 = "TextWriterFile1" static private
Definition at line 2318 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.ReadAppSettingsBasic().
KeyTextWriterWriteIntro
const string IG.Lib.ReporterBase.KeyTextWriterWriteIntro = "TextWriterWriteIntro" static private
Definition at line 2320 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.ReadAppSettingsBasic().
KeyTextWriterProgramName
const string IG.Lib.ReporterBase.KeyTextWriterProgramName = "TextWriterProgramName" static private
Definition at line 2321 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.ReadAppSettingsBasic().
KeyTextWriterIntroText
const string IG.Lib.ReporterBase.KeyTextWriterIntroText = "TextWriterIntroText" static private
Definition at line 2322 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.ReadAppSettingsBasic().
KeyTextLoggerAppend
const string IG.Lib.ReporterBase.KeyTextLoggerAppend = "TextLoggerAppend" static private
Definition at line 2324 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.ReadAppSettingsBasic().
KeyTextLoggerFile
const string IG.Lib.ReporterBase.KeyTextLoggerFile = "TextLoggerFile" static private
Definition at line 2326 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.ReadAppSettingsBasic().
KeyTextLoggerFile1
const string IG.Lib.ReporterBase.KeyTextLoggerFile1 = "TextLoggerFile1" static private
Definition at line 2328 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.ReadAppSettingsBasic().
KeyTextLoggerWriteIntro
const string IG.Lib.ReporterBase.KeyTextLoggerWriteIntro = "TextLoggerWriteIntro" static private
Definition at line 2330 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.ReadAppSettingsBasic().
KeyTextLoggerProgramName
const string IG.Lib.ReporterBase.KeyTextLoggerProgramName = "TextLoggerProgramName" static private
Definition at line 2331 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.ReadAppSettingsBasic().
KeyTextLoggerIntroText
const string IG.Lib.ReporterBase.KeyTextLoggerIntroText = "TextLoggerIntroText" static private
Definition at line 2332 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.ReadAppSettingsBasic().
KeyTextLoggerIndentInitial
const string IG.Lib.ReporterBase.KeyTextLoggerIndentInitial = "TextLoggerIndentInitial" static private
Definition at line 2333 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.ReadAppSettingsBasic().
KeyTextLoggerIndentSpacing
const string IG.Lib.ReporterBase.KeyTextLoggerIndentSpacing = "TextLoggerIndentSpacing" static private
Definition at line 2334 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.ReadAppSettingsBasic().
KeyTextLoggerIndentCharacter
const string IG.Lib.ReporterBase.KeyTextLoggerIndentCharacter = "TextLoggerIndentCharacter" static private
Definition at line 2335 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.ReadAppSettingsBasic().
KeyAppSettingsWarnings
const string IG.Lib.ReporterBase.KeyAppSettingsWarnings = "AppSettingsWarnings" static private
Definition at line 2337 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.ReadAppSettingsBasic().
TextWriterAppend
bool IG.Lib.ReporterBase.TextWriterAppend = false private
Definition at line 2342 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.ReadAppSettingsBasic().
TextLoggerAppend
bool IG.Lib.ReporterBase.TextLoggerAppend = false private
Definition at line 2343 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.ReadAppSettingsBasic().
DebugMode
bool IG.Lib.ReporterBase.DebugMode = false
Indicates that reporting suitable for debugging mode should be performed. A standard flag that can be used by the delegate functions.
Definition at line 2465 of file ReporterMsg.cs.
_IsGlobal
bool IG.Lib.ReporterBase._IsGlobal = false private
Definition at line 2468 of file ReporterMsg.cs.
_Depth
int IG.Lib.ReporterBase._Depth = 0 private
Definition at line 2481 of file ReporterMsg.cs.
_IndentSpacing
int IG.Lib.ReporterBase._IndentSpacing = 2 private
Definition at line 2481 of file ReporterMsg.cs.
_InitialIndent
int IG.Lib.ReporterBase._InitialIndent =0 private
Definition at line 2481 of file ReporterMsg.cs.
_IndentCharacter
char IG.Lib.ReporterBase._IndentCharacter = ' ' private
Definition at line 2482 of file ReporterMsg.cs.
numErrIndentLevel
int IG.Lib.ReporterBase.numErrIndentLevel = 0 static private
Definition at line 2485 of file ReporterMsg.cs.
maxErrIndentLevel
int IG.Lib.ReporterBase.maxErrIndentLevel = 3 static private
Definition at line 2485 of file ReporterMsg.cs.
numErrInitialIndent
int IG.Lib.ReporterBase.numErrInitialIndent = 0 static private
Definition at line 2510 of file ReporterMsg.cs.
maxErrInitialIndent
int IG.Lib.ReporterBase.maxErrInitialIndent = 3 static private
Definition at line 2510 of file ReporterMsg.cs.
numErrIndentSpacing
int IG.Lib.ReporterBase.numErrIndentSpacing = 0 static private
Definition at line 2536 of file ReporterMsg.cs.
maxErrIndentSpacing
int IG.Lib.ReporterBase.maxErrIndentSpacing = 3 static private
Definition at line 2536 of file ReporterMsg.cs.
DefaultReportingLevel
const ReportLevel IG.Lib.ReporterBase.DefaultReportingLevel = ReportLevel.Warning static private
Definition at line 2611 of file ReporterMsg.cs.
DefaultLoggingLevel
const ReportLevel IG.Lib.ReporterBase.DefaultLoggingLevel = ReportLevel.Warning static private
Definition at line 2612 of file ReporterMsg.cs.
DefaultTracingLevel
const ReportLevel IG.Lib.ReporterBase.DefaultTracingLevel = ReportLevel.Info static private
Definition at line 2613 of file ReporterMsg.cs.
_ReportingLevel
ReportLevel IG.Lib.ReporterBase._ReportingLevel = DefaultReportingLevel private
Definition at line 2616 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.SyncLevels().
_LoggingLevel
ReportLevel IG.Lib.ReporterBase._LoggingLevel = DefaultLoggingLevel private
Definition at line 2617 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.SyncLevels().
_TracingLevel
ReportLevel IG.Lib.ReporterBase._TracingLevel = DefaultTracingLevel private
Definition at line 2618 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.SyncLevels().
_TreatError
bool IG.Lib.ReporterBase._TreatError private
Initial value:
= DefaultReportingLevel >= ReportLevel.Error || DefaultLoggingLevel >= ReportLevel.Error ||
                    DefaultTracingLevel>=ReportLevel.Error,
            _TreatWarning   = DefaultReportingLevel >= ReportLevel.Warning || DefaultLoggingLevel >= ReportLevel.Warning ||
                    DefaultTracingLevel >= ReportLevel.Warning,
            _TreatInfo      = DefaultReportingLevel >= ReportLevel.Info || DefaultLoggingLevel >= ReportLevel.Info ||
                    DefaultTracingLevel >= ReportLevel.Info,
            _TreatUndefined = DefaultReportingLevel >= ReportLevel.Verbose || DefaultLoggingLevel >= ReportLevel.Verbose || DefaultTracingLevel >= ReportLevel.Verbose
Definition at line 2621 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.SyncLevels().
DDD
double IG.Lib.ReporterBase.DDD private
Definition at line 2841 of file ReporterMsg.cs.
_ReportingSwitch
TraceSwitch IG.Lib.ReporterBase._ReportingSwitch = null protected
Definition at line 2960 of file ReporterMsg.cs.
_LoggingSwitch
TraceSwitch IG.Lib.ReporterBase._LoggingSwitch = null private
Definition at line 2961 of file ReporterMsg.cs.
_TracingSwitch
TraceSwitch IG.Lib.ReporterBase._TracingSwitch = null private
Definition at line 2962 of file ReporterMsg.cs.
_ThrowTestException
bool IG.Lib.ReporterBase._ThrowTestException = false private
Definition at line 3046 of file ReporterMsg.cs.
_obj
object IG.Lib.ReporterBase._obj = null private
Definition at line 3053 of file ReporterMsg.cs.
_lockobj
object IG.Lib.ReporterBase._lockobj = new Object() protected
Definition at line 3055 of file ReporterMsg.cs.
_UseTextWriter
bool IG.Lib.ReporterBase._UseTextWriter = true private
Definition at line 3967 of file ReporterMsg.cs.
_TextWriterFlushing
bool IG.Lib.ReporterBase._TextWriterFlushing = false private
Definition at line 3972 of file ReporterMsg.cs.
Writer
TextWriter IG.Lib.ReporterBase.Writer = null private
Definition at line 3979 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.RemoveTextWriter(), IG.Lib.ReporterBase.RemoveTextWriters(), IG.Lib.ReporterBase.SetTextWriter(), IG.Lib.ReporterBase.TextWriterNumWriters(), IG.Lib.ReporterBase.TextWriterWrite(), and IG.Lib.ReporterBase.TextWriterWriters().
DisposeWriter
bool IG.Lib.ReporterBase.DisposeWriter = false private
Definition at line 3980 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.RemoveTextWriter(), IG.Lib.ReporterBase.RemoveTextWriters(), and IG.Lib.ReporterBase.SetTextWriter().
Writers
List<TWClass> IG.Lib.ReporterBase.Writers = new List<TWClass>() private
Definition at line 3982 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.AddTextWriter(), IG.Lib.ReporterBase.RemoveTextWriter(), IG.Lib.ReporterBase.RemoveTextWriters(), IG.Lib.ReporterBase.TextWriterNumWriters(), IG.Lib.ReporterBase.TextWriterWrite(), and IG.Lib.ReporterBase.TextWriterWriters().
_TextWriterIntroText
string IG.Lib.ReporterBase._TextWriterIntroText = null private
Definition at line 3987 of file ReporterMsg.cs.
_TextWriterProgramName
string IG.Lib.ReporterBase._TextWriterProgramName = null private
Definition at line 3988 of file ReporterMsg.cs.
_TextWriterWriteIntro
bool IG.Lib.ReporterBase._TextWriterWriteIntro = true private
Definition at line 3989 of file ReporterMsg.cs.
ReportDlgTextWriter
ReportDelegate IG.Lib.ReporterBase.ReportDlgTextWriter = new ReportDelegate(DefaultReport_TextWriter)
Delegate that performs reporting (actually logging) via text writer.
Definition at line 4668 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.Report_TextWriter().
ReportLocationDlgTextWriter
ReportLocationDelegate IG.Lib.ReporterBase.ReportLocationDlgTextWriter = new ReportLocationDelegate(DefaultReportLocation_TextWriter)
Delegate that assembles the location string for reporting via TextWriter.
Definition at line 4671 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.Report_TextWriter().
ReportMessageDlgTextWriter
ReportMessageDelegate IG.Lib.ReporterBase.ReportMessageDlgTextWriter = new ReportMessageDelegate(DefaultReportMessage_TextWriter)
Delegate that assembles the message string for reporting via text writer.
Definition at line 4674 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.Report_TextWriter().
_UseTextLogger
bool IG.Lib.ReporterBase._UseTextLogger = false private
Definition at line 4787 of file ReporterMsg.cs.
_TextLoggerFlushing
bool IG.Lib.ReporterBase._TextLoggerFlushing = true private
Definition at line 4792 of file ReporterMsg.cs.
Logger
TextWriter IG.Lib.ReporterBase.Logger = null private
Definition at line 4800 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.TextLoggerNumWriters(), and IG.Lib.ReporterBase.TextLoggerWriters().
DisposeLogger
bool IG.Lib.ReporterBase.DisposeLogger = false private
Definition at line 4801 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.RemoveTextLogger(), IG.Lib.ReporterBase.RemoveTextLoggers(), and IG.Lib.ReporterBase.SetTextLogger().
Loggers
List<TWClass> IG.Lib.ReporterBase.Loggers = new List<TWClass>() private
Definition at line 4803 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.AddTextLogger(), IG.Lib.ReporterBase.RemoveTextLogger(), IG.Lib.ReporterBase.RemoveTextLoggers(), IG.Lib.ReporterBase.TextLoggerNumWriters(), IG.Lib.ReporterBase.TextLoggerWrite(), and IG.Lib.ReporterBase.TextLoggerWriters().
_TextLoggerIntroText
string IG.Lib.ReporterBase._TextLoggerIntroText = null private
Definition at line 4808 of file ReporterMsg.cs.
_TextLoggerProgramName
string IG.Lib.ReporterBase._TextLoggerProgramName = null private
Definition at line 4809 of file ReporterMsg.cs.
_TextLoggerWriteIntro
bool IG.Lib.ReporterBase._TextLoggerWriteIntro = true private
Definition at line 4810 of file ReporterMsg.cs.
ReportDlgTextLogger
ReportDelegate IG.Lib.ReporterBase.ReportDlgTextLogger = new ReportDelegate(DefaultReport_TextLogger)
Delegate that performs reporting (actually logging) via text writer.
Definition at line 5493 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.Report_TextLogger().
ReportLocationDlgTextLogger
ReportLocationDelegate IG.Lib.ReporterBase.ReportLocationDlgTextLogger = new ReportLocationDelegate(DefaultReportLocation_TextLogger)
Delegate that assembles the location string for reporting via text logger.
Definition at line 5496 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.Report_TextLogger().
ReportMessageDlgTextLogger
ReportMessageDelegate IG.Lib.ReporterBase.ReportMessageDlgTextLogger = new ReportMessageDelegate(DefaultReportMessage_TextLogger)
Delegate that assembles the message string for reporting via text writer.
Definition at line 5499 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.Report_TextLogger().
_UseTrace
bool IG.Lib.ReporterBase._UseTrace = false private
Definition at line 5669 of file ReporterMsg.cs.
MsgSource
ReportSource IG.Lib.ReporterBase.MsgSource = ReportSource.Unknown
Indicates the source of the message (such as client, server, web service, etc.)
Definition at line 5677 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.DefaultReport_TextLogger(), and IG.Lib.ReporterBase.DefaultReport_Trace().
ReportDlgTrace
ReportDelegate IG.Lib.ReporterBase.ReportDlgTrace = new ReportDelegate(DefaultReport_Trace)
Delegate that performs reporting (logging) via Pado trace mechanism. It calls delegates ReportDlg to assemble error location information and ReportMessageDlg to assemble error message. Then it uses both to assemble the final decorated error message and launches it in its own way.
Definition at line 5686 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.Report_Trace().
ReportLocationDlgTrace
ReportLocationDelegate IG.Lib.ReporterBase.ReportLocationDlgTrace = new ReportLocationDelegate(DefaultReportLocation_Trace)
Delegate that assembles the error location string for reporting (logging) via Pado trace mechanism.
Definition at line 5689 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.Report_Trace().
ReportMessageDlgTrace
ReportMessageDelegate IG.Lib.ReporterBase.ReportMessageDlgTrace = new ReportMessageDelegate(DefaultReportMessage_Trace)
Delegate that assembles the eror message string for reporting (logging) via Pado trace mechanism.
Definition at line 5692 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.Report_Trace().
_newLineReplacement
string IG.Lib.ReporterBase._newLineReplacement = " ... " static private
Definition at line 5696 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.FormatLogMsgDefault(), and IG.Lib.ReporterBase.FormatTraceMsgDefault().
Property Documentation
GlobalInitialized
bool IG.Lib.ReporterBase.GlobalInitialized static get
Gets the value indicating whether the global reporter of this class has already been initialized.
Definition at line 1554 of file ReporterMsg.cs.
Global
ReporterBase IG.Lib.ReporterBase.Global static get private set
Gets the global reporter object. This is typically used for configuring the global reporter.
Definition at line 1566 of file ReporterMsg.cs.
AppSettingsWarnings
bool IG.Lib.ReporterBase.AppSettingsWarnings get set
Gets or sets the flag that specifies whether a warning message is launched when reading of application settings is attempted more than once for the same named group of settings.
Definition at line 2249 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.AppSettingsReadWarning(), and IG.Lib.ReporterBase.ReadAppSettingsBasic().
IsGlobal
bool IG.Lib.ReporterBase.IsGlobal get protected set
Indicates whether the current reporter is used as a global reporter or not.
This flag is set when the global reporter is initialized.
Definition at line 2473 of file ReporterMsg.cs.
Depth
int IG.Lib.ReporterBase.Depth get set
Gets or sets the current indentation level for on-line output. This should normally be done by calling IncreaseDepth() or DecreaseDepth().
Definition at line 2490 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.DecreaseDepth(), IG.Lib.ReporterBase.DefaultReport_TextLogger(), IG.Lib.ReporterBase.DefaultReport_Trace(), and IG.Lib.ReporterBase.IncreaseDepth().
TextLoggerIndentInitial
int IG.Lib.ReporterBase.TextLoggerIndentInitial get set
Gets or sets number fo initial indentation charactyers.
Definition at line 2515 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.DefaultReport_TextLogger(), IG.Lib.ReporterBase.DefaultReport_Trace(), and IG.Lib.ReporterBase.ReadAppSettingsBasic().
TextLoggerIndentSpacing
int IG.Lib.ReporterBase.TextLoggerIndentSpacing get set
Gets or sets the number of indentation characters written per indentation level.
Definition at line 2541 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.DefaultReport_TextLogger(), IG.Lib.ReporterBase.DefaultReport_Trace(), and IG.Lib.ReporterBase.ReadAppSettingsBasic().
TextLoggerIndentCharacter
char IG.Lib.ReporterBase.TextLoggerIndentCharacter get set
Gets or sets the indentation character.
Definition at line 2567 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.DefaultReport_TextLogger(), IG.Lib.ReporterBase.DefaultReport_Trace(), and IG.Lib.ReporterBase.ReadAppSettingsBasic().
ReportingLevel
ReportLevel IG.Lib.ReporterBase.ReportingLevel get set
Gets or sets level of output for reporting (console output, message boxes, etc.).
Definition at line 2651 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.DoReporting(), IG.Lib.ReporterBase.ReadAppSettingsBasic(), and IG.Lib.ReporterBase.ResetLevels().
LoggingLevel
ReportLevel IG.Lib.ReporterBase.LoggingLevel get set
Gets or sets level of output for logging (writing to log files).
Definition at line 2663 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.DoLogging(), IG.Lib.ReporterBase.ReadAppSettingsBasic(), and IG.Lib.ReporterBase.ResetLevels().
TracingLevel
ReportLevel IG.Lib.ReporterBase.TracingLevel get set
Gets or sets trace level (for external trace systems).
Definition at line 2675 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.DoTracing(), IG.Lib.ReporterBase.ReadAppSettingsBasic(), and IG.Lib.ReporterBase.ResetLevels().
TreatError
bool IG.Lib.ReporterBase.TreatError get
Returns a boolean value indicating whether errors are treated by the reporter in its current state.
Definition at line 2689 of file ReporterMsg.cs.
TreatWarning
bool IG.Lib.ReporterBase.TreatWarning get
Returns a boolean value indicating whether warnings are treated by the reporter in its current state.
Definition at line 2693 of file ReporterMsg.cs.
TreatInfo
bool IG.Lib.ReporterBase.TreatInfo get
Returns a boolean value indicating whether info messages are treated by the reporter in its current state.
Definition at line 2697 of file ReporterMsg.cs.
TreatUndefined
bool IG.Lib.ReporterBase.TreatUndefined get
Returns a boolean value indicating whether undefined messages with the lowest priority are treated by the reporter in its current state.
Definition at line 2701 of file ReporterMsg.cs.
Level
ReportLevel IG.Lib.ReporterBase.Level get set
Gets the level with the lowesst priority (out of reporting, logging and tracing level), or sets all levels to the assigned level.
Definition at line 2768 of file ReporterMsg.cs.
this[ReportLevel level]
virtual bool IG.Lib.ReporterBase.this[ReportLevel level] get set
Indexer that returns true if messages of a given level are treated by the reporter (either by the reporting, logging or tracing part, according to the corresponding level states), or false if not (i.e. if all the levels are set lover than the index). In the case of assignment, when true is assigned, all levels that are set lower than the are set to index. Assignment with false should be used only exteptionally; but in this case all levels that are set higher or equal than the index are set one level below.
Parameters
level Level for which we are interested whether it is treated.
Returns
True if a specific level (stated as index) is treated, false if not (i.e. if all of the reporting, logging)
Definition at line 2794 of file ReporterMsg.cs.
ReportingSwitch
TraceSwitch IG.Lib.ReporterBase.ReportingSwitch get set
Gets or sets the TraceSwitch that is synchronized with ReportingLevel. IMPORTANT: State of the object obtained by get accessor must not be changed unless the object is assigned back by the set accessor. If one wants that this TraceSwitch assumes values specified by the configuration file, a corresponding Traceswitch must be created and assigned to this property (otherwise the TraceSwitch will be synchronized with the ReportingLevel, which will override its settings).
Definition at line 2970 of file ReporterMsg.cs.
LoggingSwitch
TraceSwitch IG.Lib.ReporterBase.LoggingSwitch get set
Gets or sets the TraceSwitch that is synchronized with LoggingLevel. IMPORTANT: State of the object obtained by get accessor must not be changed unless the object is assigned back by the set accessor. If one wants that this TraceSwitch assumes values specified by the configuration file, a corresponding Traceswitch must be created and assigned to this property (otherwise the TraceSwitch will be synchronized with the LoggingLevel, which will override its settings).
Definition at line 2994 of file ReporterMsg.cs.
TracingSwitch
TraceSwitch IG.Lib.ReporterBase.TracingSwitch get set
Gets or sets the TraceSwitch that is synchronized with TracingLevel. IMPORTANT: State of the object obtained by get accessor must not be changed unless the object is assigned back by the set accessor. If one wants that this TraceSwitch assumes values specified by the configuration file, a corresponding Traceswitch must be created and assigned to this property (otherwise the TraceSwitch will be synchronized with the TracingLevel, which will override its settings).
Definition at line 3018 of file ReporterMsg.cs.
ThrowTestException
bool IG.Lib.ReporterBase.ThrowTestException get set
If true then the basic reporting function will throw an exception. This is intended predominantly for testing how the reporter behaves in case of internal errors. When the exception is thrown, the value is set back to false. If we want an exception to be thrown again then the value must be set to true once again.
Definition at line 3045 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterConsole_Base.Report(), and IG.Lib.ReporterBase.Report().
Obj
object IG.Lib.ReporterBase.Obj get set
Auxiliary object used by the delegates that perform error reporting. The object is used to provide additional information used in error reporting, or to provide objects that perform some actions in error reporting tasks, or both. It is left entirely to error reporting delegates to interpret the object's contents.
Definition at line 3052 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.Init(), and IG.Lib.ReporterBase.InitBegin().
lockobj
virtual object IG.Lib.ReporterBase.lockobj get
Object used for locking.
Definition at line 3059 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.AddTextLogger(), IG.Lib.ReporterBase.AddTextWriter(), IG.Lib.ReporterBase.AddTW(), IG.Lib.ReporterBase.AppSettingsRead(), IG.Lib.ReporterBase.Init(), IG.Lib.ReporterBase.MarkAppSettingsRead(), IG.Lib.ReporterBase.ReadAppSettings(), IG.Lib.ReporterBase.RemoveTextLogger(), IG.Lib.ReporterBase.RemoveTextLoggers(), IG.Lib.ReporterBase.RemoveTextWriter(), IG.Lib.ReporterBase.RemoveTextWriters(), IG.Lib.ReporterConsole_Base.Report(), IG.Lib.ReporterBase.Report(), IG.Lib.ReporterBase.Report_TextLogger(), IG.Lib.ReporterBase.Report_TextWriter(), IG.Lib.ReporterBase.ReserveReportError(), IG.Lib.ReporterBase.SetTextLogger(), IG.Lib.ReporterBase.SetTextWriter(), IG.Lib.ReporterBase.TextLoggerFlush(), IG.Lib.ReporterBase.TextLoggerNumWriters(), IG.Lib.ReporterBase.TextLoggerWrite(), IG.Lib.ReporterBase.TextLoggerWriters(), IG.Lib.ReporterBase.TextWriterFlush(), IG.Lib.ReporterBase.TextWriterNumWriters(), IG.Lib.ReporterBase.TextWriterWrite(), and IG.Lib.ReporterBase.TextWriterWriters().
UseTextWriter
bool IG.Lib.ReporterBase.UseTextWriter get set
Gets or sets the flag specifying whether reporting using a text writer is performed or not.
Definition at line 3970 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterConsole.InitEnd(), IG.Lib.ReporterBase.ReadAppSettingsBasic(), and IG.Lib.ReporterBase.Report().
TextWriterFlushing
bool IG.Lib.ReporterBase.TextWriterFlushing get set
Gets or sets the flag that tells whether or not the text writers are flushed after every message that is reported through them.
Definition at line 3976 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.TextWriterFlush(), and IG.Lib.ReporterBase.TextWriterWrite().
TextWriterIntroText
string IG.Lib.ReporterBase.TextWriterIntroText get set
Gets or sets the introduction string that is written before logging to a TextWriter begins. If this is not specified then the reporter composes its own introduction string, eventually using programname (when defined).
Definition at line 3994 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.ReadAppSettingsBasic(), and IG.Lib.ReporterBase.TextWriterPrintIntro().
TextWriterProgramName
string IG.Lib.ReporterBase.TextWriterProgramName get set
String denoting the name of the program or other entity that uses the Reporter for logging. When introtext is not specified, this name is used in the introduction text composed by the reporter.
Definition at line 3998 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.ReadAppSettingsBasic(), and IG.Lib.ReporterBase.TextWriterPrintIntro().
TextWriterWriteIntro
bool IG.Lib.ReporterBase.TextWriterWriteIntro get set
Specifies whether introduction text is written before logging of messages begins or not.
Definition at line 4001 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.AddTextWriter(), IG.Lib.ReporterBase.ReadAppSettingsBasic(), and IG.Lib.ReporterBase.SetTextWriter().
UseTextLogger
bool IG.Lib.ReporterBase.UseTextLogger get set
Gets or sets the flag specifying whether reporting using a text writer is performed or not.
Definition at line 4790 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterConsole.InitEnd(), IG.Lib.ReporterBase.ReadAppSettingsBasic(), and IG.Lib.ReporterBase.Report().
TextLoggerFlushing
bool IG.Lib.ReporterBase.TextLoggerFlushing get set
Gets or sets the flag that tells whether or not the text writers are flushed after every message that is reported through them.
Definition at line 4796 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.TextLoggerFlush(), and IG.Lib.ReporterBase.TextLoggerWrite().
TextLoggerIntroText
string IG.Lib.ReporterBase.TextLoggerIntroText get set
Gets or sets the introduction string that is written before logging to a TextWriter begins. If this is not specified then the reporter composes its own introduction string, eventually using programname (when defined).
Definition at line 4815 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.ReadAppSettingsBasic(), and IG.Lib.ReporterBase.TextLoggerPrintIntro().
TextLoggerProgramName
string IG.Lib.ReporterBase.TextLoggerProgramName get set
String denoting the name of the program or other entity that uses the Reporter for logging. When introtext is not specified, this name is used in the introduction text composed by the reporter.
Definition at line 4819 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.ReadAppSettingsBasic(), and IG.Lib.ReporterBase.TextLoggerPrintIntro().
TextLoggerWriteIntro
bool IG.Lib.ReporterBase.TextLoggerWriteIntro get set
Specifies whether introduction text is written before logging of messages begins or not.
Definition at line 4822 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterBase.AddTextLogger(), IG.Lib.ReporterBase.ReadAppSettingsBasic(), and IG.Lib.ReporterBase.SetTextLogger().
UseTrace
bool IG.Lib.ReporterBase.UseTrace get set
Gets or sets the flag specifying whether reporting using the pado trace is performed or not.
Definition at line 5672 of file ReporterMsg.cs.
Referenced by IG.Lib.ReporterConsole.InitEnd(), IG.Lib.ReporterBase.ReadAppSettingsBasic(), and IG.Lib.ReporterBase.Report().
The documentation for this class was generated from the following file:
iglib/igbase/reporter/ReporterMsg.cs