Doc: IGLib with source files: IG.Num.Func2dBase Class Reference
IG.Num.Func2dBase Class Reference abstract
Base class for scalar functions of 2 variables (base for implementation of IFunc2d interface).
Public Member Functions
Func2dBase ()
abstract double Value (double x, double y)
Calculates and returns value of the current 2D scalar function.
virtual double Value (vec2 parameters)
Calculates and returns value of the current 2D scalar function.
abstract void Gradient (double x, double y, out double gradx, out double grady)
Calculates gradient of the current 2D scalar function and returns its components through the specified output variables.
virtual vec2 Gradient (vec2 parameters)
Calculates and returns gradient of the current 2D scalar function.
abstract void Hessian (double x, double y, out double dxx, out double dyy, out double dxy)
Calculates Hessian of the current 2D scalar function and returns its component through the specified output variables.
virtual mat2 Hessian (vec2 parameters)
Calculates and returns Hessian of the current 2D scalar function and returns it (in the form of a mat2 struct).
override double Value (IVector parameters)
Returns the value of the current function at the specified parameters.
override void GradientPlain (IVector parameters, IVector gradient)
Calculates first order derivatives (gradient) of this function at the specified parameters. WARNING: Plain function, does not check consistency of arguments.
override void HessianPlain (IVector parameters, IMatrix hessian)
Calculates the second derivative (Hessian matrix) of this function at the specified parameters. WARNING: Plain function, does not check consistency of arguments.
Public Member Functions inherited from IG.Num.ScalarFunctionUntransformedBase
virtual void Evaluate (IScalarFunctionResults data)
Evaluates whatever needs to be evaluated and stores the results on the specified storage object.
virtual void Gradient (IVector parameters, ref IVector gradient)
Calculates first order derivatives (gradient) of this function at the specified parameters.
virtual void Hessian (IVector parameters, ref IMatrix hessian)
Calculates the second derivative (Hessian matrix) of this function at the specified parameters.
virtual void NumericalGradientForwardPlain (IVector x, IVector stepSizes, IVector gradient)
Calculates numerical derivatives (gradient) of this function. Forward difference formula is normally used.
void NumericalGradientForward (IVector x, IVector stepSizes, ref IVector gradient)
Calculates numerical derivatives (gradient) of this function. Forward difference formula is normally used.
void NumericalGradientForward (IVector x, double stepSize, ref IVector gradient)
Calculates numerical derivatives (gradient) of this function. Forward difference formula is used.
virtual void NumericalGradientCentralPlain (IVector x, IVector stepSizes, IVector gradient)
Calculates numerical derivatives (gradient) of this function. Forward difference formula is normally used.
void NumericalGradientCentral (IVector x, IVector stepSizes, ref IVector gradient)
Calculates numerical derivatives (gradient) of this function. Forward difference formula is normally used.
void NumericalGradientCentral (IVector x, double stepSize, ref IVector gradient)
Calculates numerical derivatives (gradient) of this function. Forward difference formula is normally used.
virtual void NumericalHessianForwardPlain (IVector x, IVector stepSizes, IVector aux, IMatrix hessian)
Calculates numerical second derivatives (Hessian) of this function. Forward difference formula is normally used. WARNING: Dimensions of vector arguments must match. This function does not check for consistency of argument dimensions. REMARK: Vector x is changed during operation, but is set to initial value before function returns (unless an exception is thrown).
virtual void NumericalHessianForward (IVector x, IVector stepSizes, ref IVector aux, ref IMatrix hessian)
Calculates numerical second derivatives (Hessian) of this function. Forward difference formula is normally used. REMARK: if auxiliary vector or result matrix don't have correct dimensions or they are not allocated, then allocation is performed first. REMARK: Vector x is changed during operation, but is set to initial value before function returns (unless an exception is thrown).
virtual void NumericalHessianForward (IVector x, double stepSize, ref IVector aux, ref IMatrix hessian)
Calculates numerical second derivatives (Hessian) of this function. Forward difference formula is normally used. REMARK: if auxiliary vector or result matrix don't have correct dimensions or they are not allocated, then allocation is performed first. REMARK: Vector x is changed during operation, but is set to initial value before function returns (unless an exception is thrown).
virtual void NumericalHessianCentralPlain (IVector x, IVector stepSizes, IVector aux1, IVector aux2, IMatrix hessian)
Calculates numerical second derivatives (Hessian) of this function. Forward difference formula is normally used. WARNING: Dimensions of vector arguments must match. This function does not check for consistency of argument dimensions. REMARK: Vector x is changed during operation, but is set to initial value before function returns (unless an exception is thrown).
virtual void NumericalHessianCentral (IVector x, IVector stepSizes, ref IVector aux1, ref IVector aux2, ref IMatrix hessian)
Calculates numerical second derivatives (Hessian) of this function. Forward difference formula is normally used. REMARK: if auxiliary vector or result matrix don't have correct dimensions or they are not allocated, then allocation is performed first. REMARK: Vector x is changed during operation, but is set to initial value before function returns (unless an exception is thrown).
virtual void NumericalHessianCentral (IVector x, double stepSize, ref IVector aux1, ref IVector aux2, ref IMatrix hessian)
Calculates numerical second derivatives (Hessian) of this function. Forward difference formula is normally used. REMARK: if auxiliary vector or result matrix don't have correct dimensions or they are not allocated, then allocation is performed first. REMARK: Vector x is changed during operation, but is set to initial value before function returns (unless an exception is thrown).
virtual void NumericalHessianCentralPlain (IVector x, IVector stepSizes, IVector aux1, IVector aux2, IMatrix hessian, bool useAnalyticalGradient)
Calculates numerical second derivatives (Hessian) of this function by the central difference formula. WARNING: Dimensions of vector arguments must match. This function does not check for consistency of argument dimensions. REMARK: Vector x is changed during operation, but is set to initial value before function returns (unless an exception is thrown).
virtual void NumericalHessianCentral (IVector x, IVector stepSizes, ref IVector aux1, ref IVector aux2, ref IMatrix hessian, bool useAnalyticalGradient)
Calculates numerical second derivatives (Hessian) of this function by the central difference formula. REMARK: if auxiliary vector or result matrix don't have correct dimensions or they are not allocated, then allocation is performed first. REMARK: Vector x is changed during operation, but is set to initial value before function returns (unless an exception is thrown).
virtual void NumericalHessianCentral (IVector x, double stepSize, ref IVector aux1, ref IVector aux2, ref IMatrix hessian, bool useAnalyticalGradient)
Calculates numerical second derivatives (Hessian) of this function. Forward difference formula is normally used. REMARK: if auxiliary vector or result matrix don't have correct dimensions or they are not allocated, then allocation is performed first. REMARK: Vector x is changed during operation, but is set to initial value before function returns (unless an exception is thrown).
void TestSpeed (IVector parameters, int numEvaluations, bool randomPerturbations, double relativePerturbationSize, bool calcValue, bool calcGradient, bool calcHessian, bool writeLastResult)
Tests speed of evaluation of the current scalar function and writes results to the console.
void TestGradient (IVector parameters, IVector stepSizes, int stepReductionFactor, int numStepReductions, bool checkNumerical, bool writeErrorComponents, bool writeGradientComponents)
Tests the calculation of gradients of the current scalar function.
void TestGradient (IVector parameters, IVector stepSizes, int stepReductionFactor, int numStepReductions, bool checkNumerical, bool writeErrorComponents, bool writeGradientComponents, bool useCentralDifference)
Tests the calculation of gradients of the current scalar function.
void TestHessian (IVector parameters, IVector stepSizes, int stepReductionFactor, int numStepReductions, bool checkNumerical, bool writeErrorComponents, bool writeHessianComponents)
Tests the calculation of Hessians of the current scalar function.
void TestHessian (IVector parameters, IVector stepSizes, int stepReductionFactor, int numStepReductions, bool checkNumerical, bool writeErrorComponents, bool writeHessianComponents, bool useCentralDifference)
Tests the calculation of Hessians of the current scalar function.
void Test (IVector from, IVector to, int numProbes, IVector stepSizes, double tolerance, bool testDerivatives, bool testSecondDerivatives, bool printDifferences, bool printResults)
Performs numerical tests on the function, with output written to the console. Derivatives and second derivatives are tested and compared to numerical derivatives.
void Test (IVector from, IVector to, int numProbes, IVector stepSizes, double tolerance)
Performs numerical tests on the function, with output written to the console. Derivatives and second derivatives are tested and compared to numerical derivatives. This method tests first and second order derivatives, prints differences between analytical and numerical values to the console, and prints reports where absolute differences exceed rolerance.
void Test (IVector from, IVector to, int numProbes, double stepSize, double tolerance, bool testDerivatives, bool testSecondDerivatives, bool printDifferences, bool printResults)
Performs numerical tests on the function, with output written to the console. Derivatives and second derivatives are tested and compared to numerical derivatives.
void Test (IVector from, IVector to, int numProbes, double stepSize, double tolerance)
Performs numerical tests on the function, with output written to the console. Derivatives and second derivatives are tested and compared to numerical derivatives.
Static Public Member Functions
static void Example ()
Example of use of a 2D function.
Static Protected Member Functions
static void TestFunction (IFunc2d f)
Demonstrates use of a 2D function by printing to the console 5 values and gradients of the function on the line connecting the two points (0, 0, 0) and (1, 1, 1).
static void TestFunction (IFunc2d f, double xmin, double xmax, double ymin, double ymax, int numPoints)
Demonstrates use of a 2D function by printing to the console some values and gradients of the function on the line connecting the two specified points.
Properties
override bool ValueDefined [get, protected set]
Whether calculation of function value is defined. Defaulet is true.
override bool GradientDefined [get, protected set]
Whether calculation of functio ngradient is defined. Default is false.
override bool HessianDefined [get, protected set]
Whether calculation of function Hessian is defined. Default is false.
int NumParam [get]
Gets number of parameters.
Properties inherited from IG.Num.ScalarFunctionUntransformedBase
virtual string Name [get, set]
Returns a short name of thecurrent function.
virtual string Description [get, set]
Returns a short description of the current function.
abstract bool ValueDefined [get, protected set]
Tells whether value of the function is defined by implementation.
abstract bool GradientDefined [get, protected set]
Tells whether the first derivative is defined for this function (by implementation, not mathematically)
abstract bool HessianDefined [get, protected set]
Tells whether the second derivative is defined for this function (by implementation, not mathematically)
Properties inherited from IG.Num.IScalarFunctionUntransformed
string Name [get]
Returns a short name of the function.
string Description [get]
Returns a short description of the function.
bool ValueDefined [get]
Tells whether value of the function is defined by implementation.
bool GradientDefined [get]
Tells whether the first derivative is defined for this function (by implementation, not mathematically)
bool HessianDefined [get]
Tells whether the second derivative is defined for this function (by implementation, not mathematically)
Properties inherited from IG.Num.IFunc2d
bool ValueDefined [get]
Whether calculation of function value is defined.
bool GradientDefined [get]
Whether calculation of function ngradient is defined.
bool HessianDefined [get]
Whether calculation of function Hessian is defined.
Private Attributes
bool _valueDefined = true
bool _gradientDefined = false
bool _hessianDefined = false
Additional Inherited Members
Protected Attributes inherited from IG.Num.ScalarFunctionUntransformedBase
string _name
string _description
Detailed Description
Base class for scalar functions of 2 variables (base for implementation of IFunc2d interface).
Beside the IFunc2d
interface, this class also implements the IScalarFunction
interface. This does not affect efficiency but adds the functionality for using objects as general (untransformed) scalar functions.
$A Igor Apr09;
Definition at line 119 of file Function2d.cs.
Constructor & Destructor Documentation
Func2dBase()
IG.Num.Func2dBase.Func2dBase () inline
Definition at line 122 of file Function2d.cs.
Member Function Documentation
Value() [1/3]
abstract double IG.Num.Func2dBase.Value (double x, double y) pure virtual
Calculates and returns value of the current 2D scalar function.
Parameters
x First parameter.
y Second parameter.
Implements IG.Num.IFunc2d.
Implemented in IG.Num.Func2dExamples.Func2dXY, IG.Num.Func3d2dBase.ComponentFunction3, IG.Num.Func3d2dBase.ComponentFunction2, IG.Num.Func3d2dBase.ComponentFunction1, and IG.Num.Func2dVectorFormBase.
Referenced by IG.Num.Func2dBase.Value().
Value() [2/3]
virtual double IG.Num.Func2dBase.Value (vec2 parameters) inline virtual
Calculates and returns value of the current 2D scalar function.
Parameters
parameters Vector of function parameters (in form of the Value) struct.
Returns
Function value.
Implements IG.Num.IFunc2d.
Reimplemented in IG.Num.Func2dQuadratic, IG.Num.Func2dLinear, and IG.Num.Func2dVectorFormBase.
Definition at line 168 of file Function2d.cs.
References IG.Num.Func2dBase.Value(), IG.Num.vec2.x, and IG.Num.vec2.y.
Gradient() [1/2]
abstract void IG.Num.Func2dBase.Gradient (double x, double y, out double gradx, out double grady) pure virtual
Calculates gradient of the current 2D scalar function and returns its components through the specified output variables.
Parameters
x First parameter.
y Second parameter.
gradx First component of the returned gradient.
grady Second component of the returned gradient.
Implements IG.Num.IFunc2d.
Implemented in IG.Num.Func2dExamples.Func2dXY, IG.Num.Func3d2dBase.ComponentFunction3, IG.Num.Func3d2dBase.ComponentFunction2, IG.Num.Func3d2dBase.ComponentFunction1, IG.Num.Func2dVectorFormBase, and IG.Num.Func2dBaseNoGradient.
Referenced by IG.Num.Func2dBase.Gradient(), and IG.Num.Func2dBase.GradientPlain().
Gradient() [2/2]
virtual vec2 IG.Num.Func2dBase.Gradient (vec2 parameters) inline virtual
Calculates and returns gradient of the current 2D scalar function.
Parameters
parameters Vector of parameters (in form of the vec2 struct)
<returnreturns>Gradient of the current 2D scalar function (in form of the vec2 struct)</returnreturns>
Implements IG.Num.IFunc2d.
Reimplemented in IG.Num.Func2dQuadratic, IG.Num.Func2dLinear, and IG.Num.Func2dVectorFormBase.
Definition at line 184 of file Function2d.cs.
References IG.Num.Func2dBase.Gradient(), IG.Num.vec2.x, and IG.Num.vec2.y.
Hessian() [1/2]
abstract void IG.Num.Func2dBase.Hessian (double x, double y, out double dxx, out double dyy, out double dxy) pure virtual
Calculates Hessian of the current 2D scalar function and returns its component through the specified output variables.
Parameters
x First parameter.
y Second parameter.
dxx Component 1-1 of the calculated Hessian.
dyy Component 2-2 of the calculated Hessian.
dxy Component 1-2 of the calculated Hessian.
Implements IG.Num.IFunc2d.
Implemented in IG.Num.Func3d2dBase.ComponentFunction3, IG.Num.Func3d2dBase.ComponentFunction2, IG.Num.Func3d2dBase.ComponentFunction1, IG.Num.Func2dVectorFormBase, IG.Num.Func2dBaseNoGradient, and IG.Num.Func2dBaseNoHessian.
Referenced by IG.Num.Func2dBase.Hessian(), and IG.Num.Func2dBase.HessianPlain().
Hessian() [2/2]
virtual mat2 IG.Num.Func2dBase.Hessian (vec2 parameters) inline virtual
Calculates and returns Hessian of the current 2D scalar function and returns it (in the form of a mat2 struct).
Implements IG.Num.IFunc2d.
Reimplemented in IG.Num.Func2dQuadratic, IG.Num.Func2dLinear, and IG.Num.Func2dVectorFormBase.
Definition at line 203 of file Function2d.cs.
References IG.Num.Func2dBase.Hessian(), IG.Num.vec2.x, and IG.Num.vec2.y.
Value() [3/3]
override double IG.Num.Func2dBase.Value (IVector parameters) inline
Returns the value of the current function at the specified parameters.
Parameters
parameters Vector of parameters for which value is evaluated. Its dimension must be equal to 2.
Implements IG.Num.IScalarFunctionUntransformed.
Definition at line 225 of file Function2d.cs.
References IG.Num.IVector< T >.Length, IG.Num.Func2dBase.NumParam, and IG.Num.Func2dBase.Value().
GradientPlain()
override void IG.Num.Func2dBase.GradientPlain (IVector parameters, IVector gradient) inline
Calculates first order derivatives (gradient) of this function at the specified parameters. WARNING: Plain function, does not check consistency of arguments.
Parameters
parameters Vector of parameters where derivatives are evaluated.
gradient Vector where first order derivatives (the gradient) are stored.
Implements IG.Num.IScalarFunctionUntransformed.
Definition at line 237 of file Function2d.cs.
References IG.Num.Func2dBase.Gradient(), IG.Num.IVector< T >.Length, and IG.Num.Func2dBase.NumParam.
HessianPlain()
override void IG.Num.Func2dBase.HessianPlain (IVector parameters, IMatrix hessian) inline
Calculates the second derivative (Hessian matrix) of this function at the specified parameters. WARNING: Plain function, does not check consistency of arguments.
Parameters
parameters Vector of parameters where derivatives are evaluated.
hessian Matrix where second derivatives (Hessian matrix) are stored.
Implements IG.Num.IScalarFunctionUntransformed.
Definition at line 252 of file Function2d.cs.
References IG.Num.Func2dBase.Hessian(), IG.Num.IVector< T >.Length, and IG.Num.Func2dBase.NumParam.
TestFunction() [1/2]
static void IG.Num.Func2dBase.TestFunction (IFunc2d f) inline static protected
Demonstrates use of a 2D function by printing to the console 5 values and gradients of the function on the line connecting the two points (0, 0, 0) and (1, 1, 1).
Parameters
f Function whose values and gradients are evaluated and printed.
Definition at line 271 of file Function2d.cs.
Referenced by IG.Num.Func2dBase.Example().
TestFunction() [2/2]
static void IG.Num.Func2dBase.TestFunction (IFunc2d f, double xmin, double xmax, double ymin, double ymax, int numPoints) inline static protected
Demonstrates use of a 2D function by printing to the console some values and gradients of the function on the line connecting the two specified points.
Parameters
f Function whose values and gradients are evaluated and printed.
xmin Min. x.
xmax Max. x.
ymin Min. y.
ymax Max. y.
numPoints Number of points in which function values and gradients are printed.
Definition at line 289 of file Function2d.cs.
References IG.Num.IFunc2d.Gradient(), IG.Num.IFunc2d.GradientDefined, IG.Num.IFunc2d.Value(), and IG.Num.IFunc2d.ValueDefined.
Example()
static void IG.Num.Func2dBase.Example () inline static
Example of use of a 2D function.
Definition at line 315 of file Function2d.cs.
References IG.Num.Func2dBase.TestFunction().
Member Data Documentation
_valueDefined
bool IG.Num.Func2dBase._valueDefined = true private
Definition at line 129 of file Function2d.cs.
_gradientDefined
bool IG.Num.Func2dBase._gradientDefined = false private
Definition at line 139 of file Function2d.cs.
_hessianDefined
bool IG.Num.Func2dBase._hessianDefined = false private
Definition at line 149 of file Function2d.cs.
Property Documentation
ValueDefined
override bool IG.Num.Func2dBase.ValueDefined get protected set
Whether calculation of function value is defined. Defaulet is true.
Definition at line 134 of file Function2d.cs.
GradientDefined
override bool IG.Num.Func2dBase.GradientDefined get protected set
Whether calculation of functio ngradient is defined. Default is false.
Definition at line 144 of file Function2d.cs.
HessianDefined
override bool IG.Num.Func2dBase.HessianDefined get protected set
Whether calculation of function Hessian is defined. Default is false.
Definition at line 153 of file Function2d.cs.
NumParam
int IG.Num.Func2dBase.NumParam get
Gets number of parameters.
Definition at line 220 of file Function2d.cs.
Referenced by IG.Num.Func2dBase.GradientPlain(), IG.Num.Func2dBase.HessianPlain(), and IG.Num.Func2dBase.Value().
The documentation for this class was generated from the following file:
iglib/igbase/numeric/geometry/Function2d.cs