Doc: IGLib with source files: IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests Class Reference
IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests Class Reference
Tests of the basic type converter (BasicTypeConverter, implementation of the ITypeConverter interface).
Public Member Functions
CollectionTypeConverterTests_DifferentElementTests (ITestOutputHelper output)
Public Member Functions inherited from IGLib.Core.Tests.BasicTypeConverterTests
BasicTypeConverterTests (ITestOutputHelper output)
Calling base constructor initializes things like TestBase<TestClass>.Output and TestBase<TestClass>.Output properties that enable writing on tests' output.
Public Member Functions inherited from IGLib.Core.Tests.TypeConverterTestsBase< BasicTypeConverterTests >
TypeConverterTestsBase (ITestOutputHelper output)
Calling base constructor initializes things like TestBase<TestClass>.Output and TestBase<TestClass>.Output properties that enable writing on tests' output.
Protected Member Functions
virtual void SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntIListToStringIEnumerableObjectToIntArray ()
virtual void SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntArrayToDoubleIEnumerableObjectToIntIList ()
virtual void SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntIListToStringArrayObjectToIntIList ()
virtual void SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntIEnumerableToStringListObjectToIntArray ()
virtual void SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntIEnumerableToStringArrayObjectToIntList ()
virtual void SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntIListToStringArrayObjectToIntList ()
virtual void SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntArrayToStringListObjectToIntArray ()
virtual void SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntArrayToStringIListObjectToIntArray ()
virtual void SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntArray2DToStringArrayObjectToIntList ()
virtual void SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntArray3DToStringIListObjectToIntArray ()
virtual void SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntArray3DToStringListObjectToIntArray ()
virtual void SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntArray3DToStringIEnumerableObjectToIntArray ()
virtual void SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntArray2DToStringArray2DObjectToIntArray2D ()
virtual void SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntArray3DToStringArray3DObjectToIntArray3D ()
virtual void SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntJaggedArrayNonrectangular2DToStringArrayObjectToIntList ()
virtual void SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntJaggedArrayNonrectangular3DToStringIListObjectToIntArray ()
virtual void SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntJaggedArrayNonrectangular3DToStringIEnumerableObjectToIntArray ()
virtual void SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntJaggedArray2DToIntJaggedArray2DObjectToIntJaggedArray2D__ComparativeToDelete_ ()
virtual void SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntJaggedArray2DToStringJaggedArray2DObjectToIntJaggedArray2D ()
virtual void SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntJaggedArray3DToStringJaggedArray3DObjectToIntJaggedArray3D__ComparativeToDelete_ ()
virtual void SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntJaggedArray3DToStringJaggedArray3DObjectToIntJaggedArray3D ()
virtual void SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntJaggedArray3DToStringArray3DObjectToIntJaggedArray3D ()
virtual void SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntArray3DToStringJaggedArray3DObjectToIntArray3D ()
Protected Member Functions inherited from IGLib.Core.Tests.BasicTypeConverterTests
virtual void SpecificTypeConverter_RoundTripConversion_IntToIntObjectToInt_IsCorrect ()
virtual void SpecificTypeConverter_RoundTripConversion_IntToDoubleObjectToDouble_IsCorrect ()
virtual void SpecificTypeConverter_RoundTripConversion_IntToDoubleObjectToInt_IsCorrect ()
virtual void SpecificTypeConverter_RoundTripConversion_DoubleToDoubleObjectToDouble_IsCorrect ()
virtual void SpecificTypeConverter_RoundTripConversion_IntegerDoubleToIntObjectToInt_IsCorrect ()
virtual void SpecificTypeConverter_RoundTripConversion_NonintegerDoubleToIntObjectToInt_IsCorrect ()
virtual void SpecificTypeConverter_RoundTripConversion_OwerflowDoubleToIntObjectToInt_IsCorrect ()
virtual void SpecificTypeConverter_RoundTripConversion_NonintegerDoubleToIntObjectToDouble_IsCorrect ()
virtual void SpecificTypeConverter_RoundTripConversion_DoubleToStringObjectToDouble_IsCorrect ()
virtual void SpecificTypeConverter_RoundTripConversion_StringToDoubleObjectToString_IsCorrect ()
virtual void SpecificTypeConverter_RoundTripConversion_StringWithUnderscoresToDoubleObjectToDouble_IsCorrect ()
virtual void SpecificTypeConverter_RoundTripConversion_DoubleStringToDoubleObjectToInt_IsCorrect ()
virtual void SpecificTypeConverter_RoundTripConversion_DoubleToStringObjectToString_IsCorrect ()
virtual void SpecificTypeConverter_RoundTripConversion_ClassToClassObjectToClass_IsCorrect ()
virtual void SpecificTypeConverter_RoundTripConversion_DerivedClassToBaseClassObjectToBaseClass_IsCorrect ()
virtual void SpecificTypeConverter_Speed_RoundTripConversion_IntToIntObjectToInt_IsCorrect ()
virtual void SpecificTypeConverter_Speed_RoundTripConversion_IntToDoubleObjectToInt_IsCorrect ()
virtual void SpecificTypeConverter_Speed_RoundTripConversion_DoubleToIntObjectToDouble_IsCorrect ()
virtual void SpecificTypeConverter_Speed_RoundTripConversion_DoubleToStringObjectToDouble_IsCorrect ()
virtual void SpecificTypeConverter_Speed_RoundTripConversion_DerivedClassToBaseClassObjectToBaseClass_IsCorrect ()
Protected Member Functions inherited from IGLib.Core.Tests.TypeConverterTestsBase< BasicTypeConverterTests >
void TypeConverter_Speed_ConversionToObjectAndBackTest< OriginalType > (ITypeConverter typeConverter, int numExecutions, double minExecutionsPerSecond, OriginalType original, bool restoreObjectBackToValue=true, bool doOutputInReferenceTest=false)
Like TypeConverter_Speed_ConversionToObjectAndBackTest<OriginalType, TargetType, RestoredType>(ITypeConverter, int, double, OriginalType, TargetType, RestoredType, bool), but with target type and the type of restored variable both equal to type of the original variable, and also the expected assiged object value and the restored value being equal to the original value.
Properties
override ITypeConverter TypeConverter = new CollectionTypeConverter() [get]
The type converter that is under test.
Properties inherited from IGLib.Core.Tests.BasicTypeConverterTests
virtual ITypeConverter TypeConverter = new BasicTypeConverter() [get]
The type converter that is under test.
virtual int NumExecutions = 1_000 [get]
Number of executions in speed tests.
virtual double MinPerSecond = 10_000 [get]
Minimum required number of executions per second in speed tests.
Additional Inherited Members
Protected Attributes inherited from IGLib.Core.Tests.TypeConverterTestsBase< BasicTypeConverterTests >
CommonType Coverted
Like TypeConverter_ConversionToObjectAndBackTest<OriginalType, TargetType, RestoredType>(OriginalType, RestoredType), but with target type and the type of restored variable both equal to type of the original variable, and also the expected assigned object value and the expected restored value being equal to the original value.
TargetType Converted
Performs test of conversion via ITypeConverter from a value of type OriginalType to a value of the target type TargetType to be assigned to a variable of type object, and then converts this value to type RestoredType and copies (restores) it to a variable of that type.
Detailed Description
Tests of the basic type converter (BasicTypeConverter, implementation of the ITypeConverter interface).
Definition at line 23 of file CollectionTypeConverterTests_DifferentElementTypes.cs.
Constructor & Destructor Documentation
CollectionTypeConverterTests_DifferentElementTests()
IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.CollectionTypeConverterTests_DifferentElementTests (ITestOutputHelper output) inline
Definition at line 26 of file CollectionTypeConverterTests_DifferentElementTypes.cs.
Member Function Documentation
SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntIListToStringIEnumerableObjectToIntArray()
virtual void IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntIListToStringIEnumerableObjectToIntArray () inline protected virtual
Currently, conversions to IEnumerable{T} are not possible. Instead, conversions to List{T} can be used.
Definition at line 40 of file CollectionTypeConverterTests_DifferentElementTypes.cs.
References IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.TypeConverter.
SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntArrayToDoubleIEnumerableObjectToIntIList()
virtual void IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntArrayToDoubleIEnumerableObjectToIntIList () inline protected virtual
Currently, conversions to IEnumerable{T} are not possible. Instead, conversions to List{T} can be used.
Definition at line 52 of file CollectionTypeConverterTests_DifferentElementTypes.cs.
References IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.TypeConverter.
SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntIListToStringArrayObjectToIntIList()
virtual void IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntIListToStringArrayObjectToIntIList () inline protected virtual
Definition at line 63 of file CollectionTypeConverterTests_DifferentElementTypes.cs.
References IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.TypeConverter.
SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntIEnumerableToStringListObjectToIntArray()
virtual void IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntIEnumerableToStringListObjectToIntArray () inline protected virtual
Definition at line 96 of file CollectionTypeConverterTests_DifferentElementTypes.cs.
References IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.TypeConverter.
SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntIEnumerableToStringArrayObjectToIntList()
virtual void IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntIEnumerableToStringArrayObjectToIntList () inline protected virtual
Definition at line 127 of file CollectionTypeConverterTests_DifferentElementTypes.cs.
References IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.TypeConverter.
SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntIListToStringArrayObjectToIntList()
virtual void IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntIListToStringArrayObjectToIntList () inline protected virtual
Definition at line 160 of file CollectionTypeConverterTests_DifferentElementTypes.cs.
References IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.TypeConverter.
SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntArrayToStringListObjectToIntArray()
virtual void IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntArrayToStringListObjectToIntArray () inline protected virtual
Definition at line 194 of file CollectionTypeConverterTests_DifferentElementTypes.cs.
References IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.TypeConverter.
SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntArrayToStringIListObjectToIntArray()
virtual void IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntArrayToStringIListObjectToIntArray () inline protected virtual
Definition at line 226 of file CollectionTypeConverterTests_DifferentElementTypes.cs.
References IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.TypeConverter.
SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntArray2DToStringArrayObjectToIntList()
virtual void IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntArray2DToStringArrayObjectToIntList () inline protected virtual
Definition at line 261 of file CollectionTypeConverterTests_DifferentElementTypes.cs.
References IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.TypeConverter.
SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntArray3DToStringIListObjectToIntArray()
virtual void IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntArray3DToStringIListObjectToIntArray () inline protected virtual
Definition at line 298 of file CollectionTypeConverterTests_DifferentElementTypes.cs.
References IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.TypeConverter.
SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntArray3DToStringListObjectToIntArray()
virtual void IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntArray3DToStringListObjectToIntArray () inline protected virtual
Definition at line 337 of file CollectionTypeConverterTests_DifferentElementTypes.cs.
References IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.TypeConverter.
SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntArray3DToStringIEnumerableObjectToIntArray()
virtual void IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntArray3DToStringIEnumerableObjectToIntArray () inline protected virtual
Definition at line 376 of file CollectionTypeConverterTests_DifferentElementTypes.cs.
References IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.TypeConverter.
SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntArray2DToStringArray2DObjectToIntArray2D()
virtual void IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntArray2DToStringArray2DObjectToIntArray2D () inline protected virtual
Definition at line 419 of file CollectionTypeConverterTests_DifferentElementTypes.cs.
References IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.TypeConverter.
SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntArray3DToStringArray3DObjectToIntArray3D()
virtual void IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntArray3DToStringArray3DObjectToIntArray3D () inline protected virtual
Definition at line 463 of file CollectionTypeConverterTests_DifferentElementTypes.cs.
References IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.TypeConverter.
SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntJaggedArrayNonrectangular2DToStringArrayObjectToIntList()
virtual void IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntJaggedArrayNonrectangular2DToStringArrayObjectToIntList () inline protected virtual
Definition at line 531 of file CollectionTypeConverterTests_DifferentElementTypes.cs.
References IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.TypeConverter.
SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntJaggedArrayNonrectangular3DToStringIListObjectToIntArray()
virtual void IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntJaggedArrayNonrectangular3DToStringIListObjectToIntArray () inline protected virtual
Definition at line 574 of file CollectionTypeConverterTests_DifferentElementTypes.cs.
References IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.TypeConverter.
SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntJaggedArrayNonrectangular3DToStringIEnumerableObjectToIntArray()
virtual void IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntJaggedArrayNonrectangular3DToStringIEnumerableObjectToIntArray () inline protected virtual
Definition at line 620 of file CollectionTypeConverterTests_DifferentElementTypes.cs.
References IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.TypeConverter.
SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntJaggedArray2DToIntJaggedArray2DObjectToIntJaggedArray2D__ComparativeToDelete_()
virtual void IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntJaggedArray2DToIntJaggedArray2DObjectToIntJaggedArray2D__ComparativeToDelete_ () inline protected virtual
Definition at line 671 of file CollectionTypeConverterTests_DifferentElementTypes.cs.
References IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.TypeConverter.
SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntJaggedArray2DToStringJaggedArray2DObjectToIntJaggedArray2D()
virtual void IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntJaggedArray2DToStringJaggedArray2DObjectToIntJaggedArray2D () inline protected virtual
Definition at line 714 of file CollectionTypeConverterTests_DifferentElementTypes.cs.
References IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.TypeConverter.
SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntJaggedArray3DToStringJaggedArray3DObjectToIntJaggedArray3D__ComparativeToDelete_()
virtual void IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntJaggedArray3DToStringJaggedArray3DObjectToIntJaggedArray3D__ComparativeToDelete_ () inline protected virtual
Definition at line 757 of file CollectionTypeConverterTests_DifferentElementTypes.cs.
References IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.TypeConverter.
SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntJaggedArray3DToStringJaggedArray3DObjectToIntJaggedArray3D()
virtual void IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntJaggedArray3DToStringJaggedArray3DObjectToIntJaggedArray3D () inline protected virtual
Definition at line 819 of file CollectionTypeConverterTests_DifferentElementTypes.cs.
References IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.TypeConverter.
SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntJaggedArray3DToStringArray3DObjectToIntJaggedArray3D()
virtual void IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntJaggedArray3DToStringArray3DObjectToIntJaggedArray3D () inline protected virtual
Definition at line 888 of file CollectionTypeConverterTests_DifferentElementTypes.cs.
References IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.TypeConverter.
SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntArray3DToStringJaggedArray3DObjectToIntArray3D()
virtual void IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntArray3DToStringJaggedArray3DObjectToIntArray3D () inline protected virtual
Definition at line 965 of file CollectionTypeConverterTests_DifferentElementTypes.cs.
References IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.TypeConverter.
Property Documentation
TypeConverter
override ITypeConverter IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.TypeConverter = new CollectionTypeConverter() get protected
The type converter that is under test.
Definition at line 31 of file CollectionTypeConverterTests_DifferentElementTypes.cs.
Referenced by IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntArray2DToStringArray2DObjectToIntArray2D(), IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntArray2DToStringArrayObjectToIntList(), IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntArray3DToStringArray3DObjectToIntArray3D(), IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntArray3DToStringIEnumerableObjectToIntArray(), IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntArray3DToStringIListObjectToIntArray(), IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntArray3DToStringJaggedArray3DObjectToIntArray3D(), IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntArray3DToStringListObjectToIntArray(), IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntArrayToDoubleIEnumerableObjectToIntIList(), IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntArrayToStringIListObjectToIntArray(), IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntArrayToStringListObjectToIntArray(), IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntIEnumerableToStringArrayObjectToIntList(), IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntIEnumerableToStringListObjectToIntArray(), IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntIListToStringArrayObjectToIntIList(), IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntIListToStringArrayObjectToIntList(), IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntIListToStringIEnumerableObjectToIntArray(), IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntJaggedArray2DToIntJaggedArray2DObjectToIntJaggedArray2D__ComparativeToDelete_(), IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntJaggedArray2DToStringJaggedArray2DObjectToIntJaggedArray2D(), IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntJaggedArray3DToStringArray3DObjectToIntJaggedArray3D(), IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntJaggedArray3DToStringJaggedArray3DObjectToIntJaggedArray3D(), IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntJaggedArray3DToStringJaggedArray3DObjectToIntJaggedArray3D__ComparativeToDelete_(), IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntJaggedArrayNonrectangular2DToStringArrayObjectToIntList(), IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntJaggedArrayNonrectangular3DToStringIEnumerableObjectToIntArray(), and IGLib.Core.Tests.CollectionTypeConverterTests_DifferentElementTests.SpecificTypeConverter_CollectionDifferentTypesRoundTripConversion_IntJaggedArrayNonrectangular3DToStringIListObjectToIntArray().
The documentation for this class was generated from the following file:
IGLibGraphics3D/tests/IGLib.Graphics3D.Tests/other/TypeConversion/CollectionTypeConverterTests_DifferentElementTypes.cs