Doc: IGLib with source files: IG.Num.VectorBase Class Reference
IG.Num.VectorBase Class Reference abstract
Base class for real vectors.
Public Member Functions
virtual double[] ToArray ()
Copies the current vector to an array.
abstract VectorBase GetCopyBase ()
Creates and returns a copy of the current vector. WARNING: This method should be overridden in the derived classes in such a way that the returned vector is of the same type as the current vector.
abstract VectorBase GetNewBase (int length)
Creates and returns a new vector of the specified dimension in such a way that the type of the returned vector is the same as of the current vector. WARNING: This method should be overridden in all derived classes such that the returned vector type is the same as the type of the current vector.
abstract VectorBase GetNewBase ()
Creates and returns a new vector with the same dimension and of the same type as the current vector.
abstract MatrixBase GetNewMatrixBase (int rowCount, int columnCount)
Creates and returns a new matrix with the specified dimensona, and of a type that is consistent with the type of the current vector.
abstract MatrixBase GetNewMatrixBase ()
Creates and returns a new matrix of a type that is consistent with the type of the current vector, and with both dimensions equal to the dimension of the current vector.
virtual IVector GetCopy ()
Returns a deep copy of the current object.
virtual IVector GetNew (int length)
Creates and returns a new vector with the specified dimension, and of the same type as the current vector.
virtual IVector GetNew ()
Creates and returns a new vector with the same dimension and of the same type as the current vector.
virtual IMatrix GetNewMatrix (int rowCount, int columnCount)
Creates and returns a new matrix with the specified dimensona, and of a type that is consistent with the type of the current vector.
virtual IMatrix GetNewMatrix ()
Creates and returns a new matrix of a type that is consistent with the type of the current vector, and with both dimensions equal to the dimension of the current vector.
virtual void SetZero ()
Sets all components of the current vector to 0.
virtual void SetConstant (double elementValue)
Sets all components of the current vector to the specified value.
virtual void SetUnit (int which)
Sets the current vector to the specific unit vector (one component equals 1, others are 0).
virtual void SetRandom ()
Sets the current vector such that it contains random elements on the interval (0,1].
virtual void SetRandom (IRandomGenerator rnd)
Sets the current vector such that it contains random elements on the interval (0,1].
virtual double NormP (double p)
p-norm, p-th root of sum of absolute values of components raised to the power of p.
IVector Normalized ()
Returns a vector that equals a normalized current vector.
void Normalize ()
Normalizes the current vector.
void Negate ()
Changes the sign of the current vector.
override int GetHashCode ()
Returns the hash code (hash function) of the current vector.
override bool Equals (Object obj)
Returns a value indicating whether the specified object is equal to the current vector.
int GetHashFunctionInt ()
Returns an integer valued hash function of the current vector object.
string GetHashFunctionString ()
Returns a string valued hash function of the current vector object.
override string ToString ()
Returns a string representation of this vector in a standard IGLib form.
virtual string ToStringMath ()
Returns a string representation of this vector in a standard IGLib form (Mathematica-like format but with C representation of numbers).
virtual string ToString (string elementFormat)
Returns a string representation of the current vector in a standard IGLib form, with the specified
format for elements of the vector.
virtual string ToStringMath (string elementFormat)
Returns a string representation of the current vector in a standard IGLib form (Mathematica-like format but with C representation of numbers), with the specified
format for elements of the vector.
Static Public Member Functions
static double NormPlain (IVector a)
Returns Euclidean norm of the specified vector.
static double NormStatic (IVector a)
Returns Euclidean norm of the specified vector.
static double Norm2Plain (IVector a)
Returns Euclidean norm of the specified vector.
static double Norm2Static (IVector a)
Returns Euclidean norm of the specified vector.
static double Norm1Plain (Vector a)
Returns the 1-norm (Manhattan or Taxicab norm, sum of element absolute values) of the specified vector.
static double Norm1Static (IVector a)
Returns the 1-norm (Manhattan or Taxicab norm, sum of element absolute values) of the specified vector.
static double NormPPlain (Vector a, double p)
Returns the p-norm (p-th root of sum of absolute values of components raised to the power of p) of the specified vector.
static double NormPStatic (IVector a, double p)
Returns the p-norm (p-th root of sum of absolute values of components raised to the power of p) of the specified vector.
static double NormInfPlain (Vector a)
Returns the Infinity-norm (maximum absolute value of any element) of the specified vector.
static double NormInfStatic (IVector a)
Returns the Infinity-norm (maximum absolute value of any element) of the specified vector.
static double DistancePlain (IVector a, IVector b)
Returns Euqlidean distance between the specified two vectors.
static double Distance (IVector a, IVector b)
Returns Euqlidean distance between the specified two vectors.
static double DistanceWeightedPlain (IVector a, IVector b, IVector characteristicLengths)
Returns distance between the specified two vectors where vector elements are weighted by elements of another vector, which represent intervals of equal importance (thus the weighted sum is divided by their squares).
static double DistanceWeighted (IVector a, IVector b, IVector characteristicLengths)
Returns distance between the specified two vectors where vector elements are weighted by elements of another vector, which represent intervals of equal importance (thus the weighted sum is divided by their squares).
static double NormWeightedPlain (IVector a, IVector characteristicLengths)
Returns weighted Euclidean norm of the specified vector.
static double NormWeighted (IVector a, IVector characteristicLengths)
Returns weighted Euclidean norm of the specified vector.
static void SetZero (IVector vec)
Sets all components of the current vector to 0.
static void SetConstant (IVector vec, double elementValue)
Sets all components of the current vector to the specified value.
static void SetUnit (IVector vec, int which)
Sets the current vector to the specific unit vector (one component equals 1, others are 0).
static void SetRandom (IVector vec)
Sets the current vector such that it contains random elements on the interval (0,1].
static void SetRandom (IVector vec, IRandomGenerator rnd)
Sets the current vector such that it contains random elements on the interval (0,1].
static int Compare (IVector v1, IVector v2)
Compares two vectors and returns -1 if the first vector is smaller than the second one, 0 if vectors are equal, and 1 if the first vector is greater. Vector that is null is considered smaller than a vector that is not null. Two null vectors are considered equal. Vector with smaller dimension is considered smaller than a vector with greater dimension. Vectors with equal dimensions ar compared by elements. The first element that is different decides which vector is considered greater.
static void Resize (ref IVector vec, IVector template, int dimension)
Resizes, if necessary, the specified vector according to the required dimension. If the vector is initially null then a new vector is created. If in this case a template vector is specified then the newly created vector will be of the same type as that template vector, because it is created by the GetNew() method on that vector. If dimension of the initial vector does not match the required dim., then vector is resized. If the specified vector dimension is less or equal to 0 then vector is resized with the same dimension as that of the template vector. If in this case the template vector is null, an exception is thrown. WARNINGS: Components are NOT preserved and have in general undefined values after operation is performed. If vector and template are null then the type of nawly created vector is Vector.
static void Resize (ref IVector vec, int dimension)
Resizes, if necessary, the specified vector according to the required dimension. If the vector is initially null then a new vector is created. If dimension of the initial vector does not match the required dimension, then vector is resized. Components are NOT preserved and have in general undefined values after operation is performed. WARNING: If the vector is initially null then the type of the newly created vector is Vector.
static void Resize (ref IVector vec, IVector template)
Resizes, if necessary, the specified vector according to the dimension of the specified template vector. If the vector is initially null then a new vector is created. In this case the newly created vector will be of the same type as that template vector, because it is created by the GetNew() method on that vector. If dimension of the initial vector does not match the dimension of the template vector, then vector is resized. If the template vector is null, then an exception is thrown. WARNINGS: Components are NOT preserved and have in general undefined values after operation is performed. If vector and template are null then the type of newly created vector is Vector.
static void CopyPlain (IVector a, IVector result)
Copies components of a vector to another vector. This is a plain version that does not perform any dimension checks. WARNING: dimensions of the copied vector and result vector must match.
static void Copy (IVector a, IVector result)
Copies components of a vector to another vector. WARNING: dimensions of the copied vector and result vector must match.
static void Copy (IVector a, ref IVector result)
Copies components of a vectr to another vector. Resulting vector is allocated or reallocated if necessary.
static void CopyPlain (VectorBase_MathNetNumerics a, IVector result)
Copies components of a vector to another vector. This is a plain version that does not perform any dimension checks. WARNING: dimensions of the copied vector and result vector must match.
static void Copy (VectorBase_MathNetNumerics a, IVector result)
Copies components of a vector to another vector. WARNING: dimensions of the copied vector and result vector must match.
static void Copy (VectorBase_MathNetNumerics a, ref IVector result)
Copies components of a vectr to another vector. Resulting vector is allocated or reallocated if necessary.
static void CopyPlain (IVector a, Vector_MathNetNumerics result)
Copies components of a vector to another vector. This is a plain version that does not perform any dimension checks. WARNING: dimensions of the copied vector and result vector must match.
static void Copy (IVector a, Vector_MathNetNumerics result)
Copies components of a vector to another vector. WARNING: dimensions of the copied vector and result vector must match.
static void Copy (IVector a, ref Vector_MathNetNumerics result)
Copies components of a vectr to another vector. Resulting vector is allocated or reallocated if necessary.
static void NegatePlain (IVector a, IVector result)
Stores a negative vector of the specified vector to another vector. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions of the copied vector and result vector must match.
static void Negate (IVector a, IVector result)
Stores a negative vector of the specified vector to another vector. WARNING: dimensions of the copied vector and result vector must match.
static void Negate (IVector a, ref IVector result)
Stores a negative vector of the specified vector to another vector. Resulting vector is allocated or reallocated if necessary.
static void AddPlain (IVector a, IVector b, IVector result)
Sums two vectors and stores the result in the specified result vector. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions of vectors must match, otherwise an exception is thrown.
static void Add (IVector a, IVector b, IVector result)
Sums two vectors and stores the result in the specified result vector. WARNING: dimensions of vectors must match, otherwise an exception is thrown.
static void Add (IVector a, IVector b, ref IVector result)
Sums two vectors and stores the result in the specified result vector. WARNING: dimensions of operands must match, otherwise an exception is thrown. If dimensions of the result do not match then teh result is re-allocated.
static void SubtractPlain (IVector a, IVector b, IVector result)
Subtracts two vectors (a - b) and stores the result in the specified result vector. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions of vectors must match, otherwise an exception is thrown.
static void Subtract (IVector a, IVector b, IVector result)
Subtracts two vectors (a - b) and stores the result in the specified result vector. WARNING: dimensions of vectors must match, otherwise an exception is thrown.
static void Subtract (IVector a, IVector b, ref IVector result)
Subtracts two vectors (a - b) and stores the result in the specified result vector. WARNING: dimensions of operands must match, otherwise an exception is thrown. If dimensions of the result do not match then teh result is re-allocated.
static void OrthogonalProjectionPlain (IVector original, IVector onWhich, double onWhichProductSelf, IVector result, double tolerance=0.0)
Calculates orthogonal projection of the original vector on the specified vector, and stores the projection in the specified result, where the inner project of the vector to which projection is performed is specified.
static void OrthogonalProjectionPlain (IVector original, IVector onWhich, IVector result, double tolerance=0.0)
Calculates orthogonal projection of the original vector on the specified vector, and stores the projection in the specified result.
static void OrthogonalProjection (IVector original, IVector onWhich, double onWhichProductSelf, ref IVector result, double tolerance=0.0)
Calculates orthogonal projection of the original vector on the specified vector, and stores the projection in the specified result, where the inner project of the vector to which projection is performed is specified.
static void OrthogonalProjection (IVector original, IVector onWhich, ref IVector result, double tolerance=0.0)
Calculates orthogonal projection of the original vector on the specified vector, and stores the projection in the specified result.
static void ArrayAddPlain (IVector a, double scal, IVector result)
Addition of a scalar to all components of a vector. This is a plain version of the method that does not perform any consistency checks. Vector operand must be defined (non-null).
static void ArrayAdd (IVector a, double scal, IVector result)
Addition of a scalar to all components of a vector. Vector operand must be defined (non-null).
static void ArrayAdd (IVector a, double scal, ref IVector result)
Addition of a scalar to all components of a vector. Vector operand must be defined (non-null).
static void ArraySubtractPlain (IVector a, double scal, IVector result)
Subtraction of a scalar from all components of a vector. This is a plain version of the method that does not perform any consistency checks. Vector operand must be defined (non-null).
static void ArraySubtract (IVector a, double scal, IVector result)
Subtraction of a scalar from all components of a vector. Vector operand must be defined (non-null).
static void ArraySubtract (IVector a, double scal, ref IVector result)
Subtraction of a scalar to all components of a vector. Vector operand must be defined (non-null).
static void MultiplyPlain (IVector a, double scal, IVector result)
Multiplication of a vector by a scalar. This is a plain version of the method that does not perform any consistency checks. Vector operand must be defined (non-null).
static void Multiply (IVector a, double scal, IVector result)
Multiplication of a vector by a scalar. Vector operand must be defined (non-null).
static void Multiply (IVector a, double scal, ref IVector result)
Multiplication of a vector by a scalar. Vector operand must be defined (non-null).
static void ScalePlain (IVector a, double scal, IVector result)
Multiplication of a vector by a scalar. This is a plain version of the method that does not perform any consistency checks. Vector operand must be defined (non-null).
static void Scale (IVector a, double scal, IVector result)
Multiplication of a vector by a scalar. Vector operand must be defined (non-null).
static void Scale (IVector a, double scal, ref IVector result)
Multiplication of a vector by a scalar. Vector operand must be defined (non-null).
static void DividePlain (IVector a, double scal, IVector result)
Division of a vector by a scalar. This is a plain version of the method that does not perform any consistency checks. Vector operand must be defined (non-null).
static void Divide (IVector a, double scal, IVector result)
Division of a vector by a scalar. Vector operand must be defined (non-null).
static void Divide (IVector a, double scal, ref IVector result)
Division of a vector by a scalar. Vector operand must be defined (non-null).
static double ScalarProductPlain (IVector a, IVector b)
Scalar product of teo vectors. This is a plain version of the method that does not perform any consistency checks.
static double ScalarProduct (IVector a, IVector b)
Scalar product of teo vectors.
static void DyadicProductPlain (IVector a, IVector b, IMatrix result)
Calculates dyadic product of two vectors and stores the result in the specified result matrix. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions must match, otherwise an exception is thrown.
static void DyadicProduct (IVector a, IVector b, IMatrix result)
Calculates dyadic product of two vectors and stores the result in the specified result matrix. WARNING: dimensions must match, otherwise an exception is thrown.
static void DyadicProduct (IVector a, IVector b, ref IMatrix result)
Calculates dyadic product of two vectors and stores the result in the specified result matrix. WARNING: dimensions of operands must match, otherwise an exception is thrown. If dimensions of the result do not match then teh result is re-allocated.
static void CrossProductPlain (IVector a, IVector b, IVector result)
Calculates a vector product (cross product) of two vectors and stores the result in the specified result vector. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions of all vectors must be 3, otherwise an exception is thrown.
static void CrossProduct (IVector a, IVector b, IVector result)
Calculates a vector product (cross product) of two vectors and stores the result in the specified result vector. WARNING: dimensions of all vectors must be 3, otherwise an exception is thrown.
static void CrossProduct (IVector a, IVector b, ref IVector result)
Calculates a vector product (cross product) of two vectors and stores the result in the specified result vector. WARNING: dimensions of operands must match, otherwise an exception is thrown. If dimensions of the result do not match then teh result is re-allocated.
static void VectorProductPlain (IVector a, IVector b, IVector result)
Calculates a vector product (cross product) of two vectors and stores the result in the specified result vector. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions of all vectors must be 3, otherwise an exception is thrown.
static void VectorProduct (IVector a, IVector b, IVector result)
Calculates a vector product (cross product) of two vectors and stores the result in the specified result vector. WARNING: dimensions of all vectors must be 3, otherwise an exception is thrown.
static void VectorProduct (IVector a, IVector b, ref IVector result)
Calculates a vector product (cross product) of two vectors and stores the result in the specified result vector. WARNING: dimensions of operands must match, otherwise an exception is thrown. If dimensions of the result do not match then teh result is re-allocated.
static void ArrayProductPlain (IVector a, IVector b, IVector result)
Calculates array product (element-by-element product) of two vectors and stores the result in the specified result vector. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions of all vectors must be 3, otherwise an exception is thrown.
static void ArrayProduct (IVector a, IVector b, IVector result)
Calculates array product (element-by-element product) of two vectors and stores the result in the specified result vector. WARNING: dimensions of all vectors must be 3, otherwise an exception is thrown.
static void ArrayProduct (IVector a, IVector b, ref IVector result)
Calculates array product (element-by-element product) of two vectors and stores the result in the specified result vector. WARNING: dimensions of operands must match, otherwise an exception is thrown. If dimensions of the result do not match then teh result is re-allocated.
static void ArrayQuotientPlain (IVector a, IVector b, IVector result)
Calculates array quotient (element-by-element division) of two vectors and stores the result in the specified result vector. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions of all vectors must be 3, otherwise an exception is thrown.
static void ArrayQuotient (IVector a, IVector b, IVector result)
Calculates array quotient (element-by-element division) of two vectors and stores the result in the specified result vector. WARNING: dimensions of all vectors must be 3, otherwise an exception is thrown.
static void ArrayQuotient (IVector a, IVector b, ref IVector result)
Calculates array quotient (element-by-element division) of two vectors and stores the result in the specified result vector. WARNING: dimensions of operands must match, otherwise an exception is thrown. If dimensions of the result do not match then teh result is re-allocated.
static int GetHashCode (IVector vec)
Returns hash code of the specified vector.
static bool Equals (IVector v1, IVector v2)
Returns true if the specified vectors are equal, false if not.
static int GetHashFunctionInt (IVector vec)
Returns an integer valued hash function of the specified vector object.
static string GetHashFunctionString (IVector vec)
Returns a string valued hash function of the specified vector object.
static void OrthoNormalizeGramSchmidt (IList< IVector > original, ref IList< IVector > resOrthogonal, ref IVector resNorms, ref IVector auxProjection, double tolDependent=1e-10, bool normalize=false, int numRequestedVectors=0, IRandomGenerator rand=null, int maxExcessGenerated=5)
Performs the Gramm-Schmidt orthogonalization procedure in order to calculate a set of orthonormal vectors from the specified set of arbitrary independent vectors.
static int OrthogonalizeGramSchmidt (IList< IVector > original, ref IList< IVector > resOrthogonal, ref IVector resNorms, ref IVector auxProjection, double tolDependent=1e-10, bool normalize=false, int numRequestedVectors=0, IRandomGenerator rand=null, int maxExcessGenerated=5)
Performs the Gramm-Schmidt orthogonalization procedure in order to calculate a set of orthogonall vectors from the specified set of arbitrary independent vectors.
static void OrthoNormalizeGramSchmidtNonRobust (IList< IVector > original, ref IList< IVector > resOrthogonal, ref IVector resNorms, ref IVector auxProjection, double tolSize=0, bool normalize=false, bool modifiedGrammSchmidt=true)
Performs the Gramm-Schmidt orthogonalization procedure in order to calculate a set of orthonormal vectors from the specified set of arbitrary independent vectors.
static void OrthogonalizeGramSchmidtNonRobust (IList< IVector > original, ref IList< IVector > resOrthogonal, ref IVector resNorms, ref IVector auxProjection, double tolSize=0, bool normalize=false, bool modifiedGrammSchmidt=true)
Performs the Gramm-Schmidt orthogonalization procedure in order to calculate a set of orthogonall vectors from the specified set of arbitrary independent vectors.
static bool TestGramSchmidtOrthogonalization (int dim, int numRepetitions=1, double tol=1e-8, int outputLevel=0, IRandomGenerator randomGenerator=null, bool normalize=false, bool modifiedGrammSchmidt=true, bool nonRobust=false)
Performs a test of Gramm-Schmidt orthogonalization on a set of random vectors.
static VectorBase operator+ (VectorBase v)
Unary plus, returns the operand.
static VectorBase operator- (VectorBase v)
Unary negation, returns the negative operand.
static VectorBase operator+ (VectorBase a, VectorBase b)
Vector addition.
static VectorBase operator- (VectorBase a, VectorBase b)
Vector subtraction.
static double operator* (VectorBase a, VectorBase b)
Scalar product of two vectors.
static VectorBase operator* (VectorBase a, double b)
Product of a vector by a scalar.
static VectorBase operator* (double a, VectorBase b)
Product of a vector by a scalar.
static VectorBase operator/ (VectorBase a, double b)
Vector subtraction.
static string ToString (IVector vec)
Returns a string representation of the specified vector in a standard IGLib form.
static string ToStringMath (IVector vec)
Returns a string representation of the specified vector in a standard IGLib form (Mathematica-like format but with C representation of numbers).
static string ToString (IVector vec, string elementFormat)
Returns a string representation of the specified vector in a standard IGLib form, with the specified
format for elements of the vector.
static string ToStringMath (IVector vec, string elementFormat)
Returns a string representation of the specified vector in a standard IGLib form (Mathematica-like format but with C representation of numbers), with the specified
format for elements of the vector.
static void SaveJson (IVector vec, string filePath)
Saves (serializes) the specified vector to the specified JSON file. File is owerwritten if it exists.
static void SaveJson (IVector vec, string filePath, bool append)
Saves (serializes) the specified vector to the specified JSON file. If the file already exists, contents either overwrites the file or is appended at the end, dependent on the value of the append flag.
static void LoadJson (string filePath, ref IVector vecRestored)
Restores (deserializes) a vector from the specified file in JSON format.
static void SaveCsv (IVector vec, string filePath)
Saves the specified vector to a CSV file. It the specified file already exists then it is overwritten. Constant UtilCsv.DefaultCsvSeparator is used as separator.
static void SaveCsv (IVector vec, string filePath, string separator)
Saves the specified vector to a CSV file. It the specified file already exists then it is overwritten.
static void SaveCsv (IVector vec, string filePath, bool append)
Saves the specified vector to a CSV file. Constant UtilCsv.DefaultCsvSeparator is used as separator in CSV.
static void SaveCsv (IVector vec, string filePath, string separator, bool append)
Saves the specified vector to a CSV file.
static void LoadCsv (string filePath, ref IVector vecRestored)
Reads a vector from a CSV file. Constant UtilCsv.DefaultCsvSeparator is used as separator in CSV file. If there are no components then a null vector is returned by this method (no exceptions thrown). If there are more than one rows in the CSV file then vector is read from the first row.
static void LoadCsv (string filePath, string separator, ref IVector vecRestored)
Reads a vector written in CSV format from a file. If there are no components then a null vector is returned by this method (no exceptions thrown). If there are more than one rows in the CSV file then vector is read from the first row.
static void LoadCsv (string filePath, int rowNum, ref IVector vecRestored)
Reads a vector from the specified row of a CSV file. Constant UtilCsv.DefaultCsvSeparator is used as CSV separator. If the specified row does not exisist in the file then exception is thrown.
static void LoadCsv (string filePath, int rowNum, string separator, ref IVector vecRestored)
Reads a vector from the specified row of a CSV file. If the specified row does not exisist in the file then exception is thrown.
Properties
abstract int Length [get]
Gets dimension of the vector.
abstract double this[int i] [get, set]
Gets or sets the element indexed by i in the Vector.
virtual double Norm [get]
Gets Euclidean norm of the vector.
virtual double Norm2 [get]
Gets Euclidean norm of the vector.
virtual double NormEuclidean [get]
Gets Euclidean norm of the vector.
virtual double SquaredNorm [get]
Squared Euclidean norm, sum of squared components.
virtual double Norm1 [get]
1-norm (Manhattan norm or Taxicab norm), sum of absolute values of components.
virtual double NormInf [get]
Infinity-norm, maximum absolute value of any component.
static VectorStore VectorStore [get]
Gets the matrix store for recycling auxiliary matrices.
Properties inherited from IG.Num.IVector< T >
int Length [get]
Gets the number of rows.
T this[int i] [get, set]
Gets or set the element indexed by i in the Vector.
double Norm [get]
Gets Euclidean norm of the vector.
double Norm2 [get]
Gets Euclidean norm of the vector.
double NormEuclidean [get]
Gets Euclidean norm of the vector.
double SquaredNorm [get]
Squared Euclidean norm, sum of squared components.
double Norm1 [get]
1-norm (Manhattan norm or Taxicab norm), sum of absolute values of components.
double NormInf [get]
Infinity-norm, maximum absolute value of any component.
Static Private Attributes
static VectorStore _matrixStore
Detailed Description
Base class for real vectors.
$A Igor Jan08 Jul10 Nov10;
Definition at line 267 of file VectorBase.cs.
Member Function Documentation
ToArray()
virtual double [] IG.Num.VectorBase.ToArray () inline virtual
Copies the current vector to an array.
Implements IG.Num.IVector< T >.
Definition at line 284 of file VectorBase.cs.
References IG.Num.VectorBase.Length.
GetCopyBase()
abstract VectorBase IG.Num.VectorBase.GetCopyBase () pure virtual
Creates and returns a copy of the current vector. WARNING: This method should be overridden in the derived classes in such a way that the returned vector is of the same type as the current vector.
Implemented in IG.Num.Vector, IG.Num.Vector3d, and IG.Num.Vector2d.
Referenced by IG.Num.VectorBase.GetCopy(), IG.Num.VectorBase.Normalized(), IG.Num.VectorBase.operator+(), and IG.Num.VectorBase.operator-().
GetNewBase() [1/2]
abstract VectorBase IG.Num.VectorBase.GetNewBase (int length) pure virtual
Creates and returns a new vector of the specified dimension in such a way that the type of the returned vector is the same as of the current vector. WARNING: This method should be overridden in all derived classes such that the returned vector type is the same as the type of the current vector.
Parameters
length Dimension of the returned vector.
Implemented in IG.Num.Vector, IG.Num.Vector3d, and IG.Num.Vector2d.
Referenced by IG.Num.VectorBase.operator*(), IG.Num.MatrixBase.operator*(), IG.Num.VectorBase.operator+(), IG.Num.VectorBase.operator-(), and IG.Num.VectorBase.operator/().
GetNewBase() [2/2]
abstract VectorBase IG.Num.VectorBase.GetNewBase () pure virtual
Creates and returns a new vector with the same dimension and of the same type as the current vector.
Implemented in IG.Num.Vector, IG.Num.Vector3d, and IG.Num.Vector2d.
Referenced by IG.Num.VectorBase.GetNew().
GetNewMatrixBase() [1/2]
abstract MatrixBase IG.Num.VectorBase.GetNewMatrixBase (int rowCount, int columnCount) pure virtual
Creates and returns a new matrix with the specified dimensona, and of a type that is consistent with the type of the current vector.
Parameters
rowCount Number of rows of the returned matrix.
columnCount Number of rows of the returned matrix.
Returns
A matrix with specified dimensions, whose type is consistent with the type of the current vector.
Implemented in IG.Num.Vector, IG.Num.Vector3d, and IG.Num.Vector2d.
GetNewMatrixBase() [2/2]
abstract MatrixBase IG.Num.VectorBase.GetNewMatrixBase () pure virtual
Creates and returns a new matrix of a type that is consistent with the type of the current vector, and with both dimensions equal to the dimension of the current vector.
Implemented in IG.Num.Vector, IG.Num.Vector2d, and IG.Num.Vector3d.
Referenced by IG.Num.VectorBase.GetNewMatrix().
GetCopy()
virtual IVector IG.Num.VectorBase.GetCopy () inline virtual
Returns a deep copy of the current object.
Implements IG.Num.IVector< T >.
Definition at line 324 of file VectorBase.cs.
References IG.Num.VectorBase.GetCopyBase().
GetNew() [1/2]
virtual IVector IG.Num.VectorBase.GetNew (int length) inline virtual
Creates and returns a new vector with the specified dimension, and of the same type as the current vector.
Parameters
length Dimension of the newly created vector.
Returns
A newly created vector of the specified dimension and of the same type as the current vector.
Implements IG.Num.IVector< T >.
Definition at line 331 of file VectorBase.cs.
References IG.Num.VectorBase.GetNewBase().
GetNew() [2/2]
virtual IVector IG.Num.VectorBase.GetNew () inline virtual
Creates and returns a new vector with the same dimension and of the same type as the current vector.
Implements IG.Num.IVector< T >.
Definition at line 336 of file VectorBase.cs.
References IG.Num.VectorBase.GetNewBase().
GetNewMatrix() [1/2]
virtual IMatrix IG.Num.VectorBase.GetNewMatrix (int rowCount, int columnCount) inline virtual
Creates and returns a new matrix with the specified dimensona, and of a type that is consistent with the type of the current vector.
Parameters
rowCount Number of rows of the returned matrix.
columnCount Number of rows of the returned matrix.
Returns
A matrix with specified dimensions, whose type is consistent with the type of the current vector.
Implements IG.Num.IVector< T >.
Definition at line 344 of file VectorBase.cs.
References IG.Num.VectorBase.GetNewMatrixBase().
GetNewMatrix() [2/2]
virtual IMatrix IG.Num.VectorBase.GetNewMatrix () inline virtual
Creates and returns a new matrix of a type that is consistent with the type of the current vector, and with both dimensions equal to the dimension of the current vector.
Implements IG.Num.IVector< T >.
Definition at line 350 of file VectorBase.cs.
References IG.Num.VectorBase.GetNewMatrixBase().
SetZero() [1/2]
virtual void IG.Num.VectorBase.SetZero () inline virtual
Sets all components of the current vector to 0.
Implements IG.Num.IVector< T >.
Definition at line 362 of file VectorBase.cs.
References IG.Num.VectorBase.Length.
SetConstant() [1/2]
virtual void IG.Num.VectorBase.SetConstant (double elementValue) inline virtual
Sets all components of the current vector to the specified value.
Parameters
elementValue Value to which vector elements are set.
Implements IG.Num.IVector< T >.
Definition at line 371 of file VectorBase.cs.
References IG.Num.VectorBase.Length.
SetUnit() [1/2]
virtual void IG.Num.VectorBase.SetUnit (int which) inline virtual
Sets the current vector to the specific unit vector (one component equals 1, others are 0).
Parameters
which Specifies which unit vector is set (i.e., which component equals 1).
Implements IG.Num.IVector< T >.
Definition at line 379 of file VectorBase.cs.
References IG.Num.VectorBase.Length.
SetRandom() [1/4]
virtual void IG.Num.VectorBase.SetRandom () inline virtual
Sets the current vector such that it contains random elements on the interval (0,1].
Implements IG.Num.IVector< T >.
Definition at line 387 of file VectorBase.cs.
Referenced by IG.Num.VectorBase.OrthogonalizeGramSchmidt(), IG.Num.Vector.Random(), IG.Num.Vector3d.Random(), IG.Num.Vector2d.Random(), IG.Num.VectorBase.SetRandom(), IG.Num.MatrixBase.TestCholeskyDecomposition(), IG.Num.MatrixBase.TestLdltDecomposition(), and IG.Num.MatrixBase.TestLuDecomposition().
SetRandom() [2/4]
virtual void IG.Num.VectorBase.SetRandom (IRandomGenerator rnd) inline virtual
Sets the current vector such that it contains random elements on the interval (0,1].
Parameters
rnd Random generator used to generate vector elements.
Implements IG.Num.IVector< T >.
Definition at line 394 of file VectorBase.cs.
References IG.Num.VectorBase.SetRandom().
NormP()
virtual double IG.Num.VectorBase.NormP (double p) inline virtual
p-norm, p-th root of sum of absolute values of components raised to the power of p.
Parameters
p Power of the norm, must be greater or equal to 1.
For p = 1, we obtain taxicab norm, for p = 2 we obtain Euclidean norm, and as p approaches infinity, the result approaches the infinity norm (but beware of large numbers and numerical stability).
Exceptions
ArgumentException If p is less than 1.0.
Implements IG.Num.IVector< T >.
Definition at line 465 of file VectorBase.cs.
References IG.Num.VectorBase.Length.
NormPlain()
static double IG.Num.VectorBase.NormPlain (IVector a) inline static
Returns Euclidean norm of the specified vector.
Vector can NOT be null (inthis case, exception is thrown).
Definition at line 494 of file VectorBase.cs.
NormStatic()
static double IG.Num.VectorBase.NormStatic (IVector a) inline static
Returns Euclidean norm of the specified vector.
Vector can be null (0 is returned in this case).
Definition at line 510 of file VectorBase.cs.
Norm2Plain()
static double IG.Num.VectorBase.Norm2Plain (IVector a) inline static
Returns Euclidean norm of the specified vector.
Vector can NOT be null (inthis case, exception is thrown).
Definition at line 528 of file VectorBase.cs.
Referenced by IG.Num.VectorBase.OrthogonalizeGramSchmidt(), and IG.Num.VectorBase.OrthogonalizeGramSchmidtNonRobust().
Norm2Static()
static double IG.Num.VectorBase.Norm2Static (IVector a) inline static
Returns Euclidean norm of the specified vector.
Vector can be null (0 is returned in this case).
Definition at line 543 of file VectorBase.cs.
Norm1Plain()
static double IG.Num.VectorBase.Norm1Plain (Vector a) inline static
Returns the 1-norm (Manhattan or Taxicab norm, sum of element absolute values) of the specified vector.
Vector can NOT be null (inthis case, exception is thrown).
Definition at line 561 of file VectorBase.cs.
References IG.Num.Vector.Length.
Norm1Static()
static double IG.Num.VectorBase.Norm1Static (IVector a) inline static
Returns the 1-norm (Manhattan or Taxicab norm, sum of element absolute values) of the specified vector.
Vector can be null (0 is returned in this case).
Definition at line 574 of file VectorBase.cs.
NormPPlain()
static double IG.Num.VectorBase.NormPPlain (Vector a, double p) inline static
Returns the p-norm (p-th root of sum of absolute values of components raised to the power of p) of the specified vector.
Vector can NOT be null (inthis case, exception is thrown).
Parameters
a Vector whose norm is calculated.
p Power of the norm, must be greater or equal to 1.
For p = 1, we obtain taxicab norm, for p = 2 we obtain Euclidean norm, and as p approaches infinity, the result approaches the infinity norm (but beware of large numbers and numerical stability).
Exceptions
ArgumentException If p is less than 1.0.
Definition at line 596 of file VectorBase.cs.
References IG.Num.Vector.Length.
NormPStatic()
static double IG.Num.VectorBase.NormPStatic (IVector a, double p) inline static
Returns the p-norm (p-th root of sum of absolute values of components raised to the power of p) of the specified vector.
Vector can be null (0 is returned in this case).
Parameters
a Vector whose norm is calculated.
p Power of the norm, must be greater or equal to 1.
For p = 1, we obtain taxicab norm, for p = 2 we obtain Euclidean norm, and as p approaches infinity, the result approaches the infinity norm (but beware of large numbers and numerical stability).
Exceptions
ArgumentException If p is less than 1.0.
Definition at line 618 of file VectorBase.cs.
NormInfPlain()
static double IG.Num.VectorBase.NormInfPlain (Vector a) inline static
Returns the Infinity-norm (maximum absolute value of any element) of the specified vector.
Vector can NOT be null (inthis case, exception is thrown).
Definition at line 638 of file VectorBase.cs.
References IG.Num.Vector.Length.
NormInfStatic()
static double IG.Num.VectorBase.NormInfStatic (IVector a) inline static
Returns the Infinity-norm (maximum absolute value of any element) of the specified vector.
Vector can be null (0 is returned in this case).
Definition at line 653 of file VectorBase.cs.
DistancePlain()
static double IG.Num.VectorBase.DistancePlain (IVector a, IVector b) inline static
Returns Euqlidean distance between the specified two vectors.
WARNING: This is a plain version of the method that does not perform any consistency checks.
Parameters
a First vector.
b Second vector.
Definition at line 674 of file VectorBase.cs.
Referenced by IG.Num.DistanceComparer< PointContainerSampledDataElement, SampledDataElement >.DefaultDistanceFunction(), and IG.Num.DistanceComparer< PointContainerSampledDataElement, SampledDataElement >.OutputDistance().
Distance()
static double IG.Num.VectorBase.Distance (IVector a, IVector b) inline static
Returns Euqlidean distance between the specified two vectors.
WARNING: Dimensions must match, otherwise exception is thrown..
Parameters
a First vector.
b Second vector.
Definition at line 690 of file VectorBase.cs.
Referenced by IG.Num.SampledDataSet.ComparerInputDistance.ComparerInputDistance(), IG.Num.SampledDataSet.ComparerOutputDistance.ComparerOutputDistance(), and IG.Num.PointCloud< PointLinkType, PointContainerType, PointType >.ExampleClosestPointsDummy().
DistanceWeightedPlain()
static double IG.Num.VectorBase.DistanceWeightedPlain (IVector a, IVector b, IVector characteristicLengths) inline static
Returns distance between the specified two vectors where vector elements are weighted by elements of another vector, which represent intervals of equal importance (thus the weighted sum is divided by their squares).
Dw=Sqrt(Sum(((a_i-b_i)/l_i)^2))
WARNING: This is a plain version of the method that does not perform any consistency checks. It assumes that all vector prarameters are allocated and of hte same dimension, and that all elements of characteristic lengths vector are non-zero.
Parameters
a First vector.
b Second vector.
characteristicLengths Vector whose elements represent interval lenhth of equal importance in different coordinate direction. Used for calculation of weighted sum (terms are divided by squares of vector elements).
Definition at line 720 of file VectorBase.cs.
Referenced by IG.Num.DistanceComparer< PointContainerSampledDataElement, SampledDataElement >.DefaultDistanceFunction(), and IG.Num.DistanceComparer< PointContainerSampledDataElement, SampledDataElement >.OutputDistance().
DistanceWeighted()
static double IG.Num.VectorBase.DistanceWeighted (IVector a, IVector b, IVector characteristicLengths) inline static
Returns distance between the specified two vectors where vector elements are weighted by elements of another vector, which represent intervals of equal importance (thus the weighted sum is divided by their squares).
Dw=Sqrt(Sum(((a_i-b_i)/l_i)^2))
WARNING: Dimensions of vector arguments must match, otherwise exceptin is thrown. Also if any element of characteristic lengths vector is zero, an exception is thrown, too.
Parameters
a First vector.
b Second vector.
characteristicLengths Vector whose elements represent interval lenhth of equal importance in different coordinate direction. Used for calculation of weighted sum (terms are divided by squares of vector elements).
Definition at line 745 of file VectorBase.cs.
NormWeightedPlain()
static double IG.Num.VectorBase.NormWeightedPlain (IVector a, IVector characteristicLengths) inline static
Returns weighted Euclidean norm of the specified vector.
Parameters
a Vector whose weighter Euclidean norm is returned.
characteristicLengths Vector whose elements represent interval lenhth of equal importance in different coordinate direction. Used for calculation of weighted sum (terms are divided by squares of vector elements).
Definition at line 781 of file VectorBase.cs.
Referenced by IG.Num.NeuralTrainingParameters.ComparerBase.OutputNorm().
NormWeighted()
static double IG.Num.VectorBase.NormWeighted (IVector a, IVector characteristicLengths) inline static
Returns weighted Euclidean norm of the specified vector.
Parameters
a Vector whose weighter Euclidean norm is returned.
characteristicLengths Vector whose elements represent interval lengths of equal importance in different coordinate direction. Used for calculation of weighted sum (terms are divided by squares of vector elements).
Definition at line 800 of file VectorBase.cs.
Referenced by IG.Num.NeuralTrainingParameters.ErrorAverageCalc().
Normalized()
IVector IG.Num.VectorBase.Normalized () inline
Returns a vector that equals a normalized current vector.
Implements IG.Num.IVector< T >.
Definition at line 833 of file VectorBase.cs.
References IG.Num.VectorBase.Divide(), IG.Num.VectorBase.GetCopyBase(), and IG.Num.VectorBase.Norm.
Normalize()
void IG.Num.VectorBase.Normalize () inline
Normalizes the current vector.
Returns
Implements IG.Num.IVector< T >.
Definition at line 848 of file VectorBase.cs.
References IG.Num.VectorBase.Divide(), and IG.Num.VectorBase.Norm.
Negate() [1/3]
void IG.Num.VectorBase.Negate () inline
Changes the sign of the current vector.
Returns
Implements IG.Num.IVector< T >.
Definition at line 858 of file VectorBase.cs.
Referenced by IG.Num.VectorBase.operator-().
GetHashCode() [1/2]
override int IG.Num.VectorBase.GetHashCode () inline
Returns the hash code (hash function) of the current vector.
This method calls the VectorBase.GetHashCode() to calculate the hash code, which is standard for all implementations of the IVector interface.
Two vectors that have the same dimensions and equal elements will produce the same hash codes.
Probability that two different vectors will produce the same hash code is small but it exists.
Overrides the object.GetHashCode method.
Definition at line 873 of file VectorBase.cs.
References IG.Num.VectorBase.GetHashCode().
Referenced by IG.Num.Vector2d.GetHashCode(), IG.Num.Vector3d.GetHashCode(), IG.Num.Vector.GetHashCode(), and IG.Num.VectorBase.GetHashCode().
Equals() [1/2]
override bool IG.Num.VectorBase.Equals (Object obj) inline
Returns a value indicating whether the specified object is equal to the current vector.
True is returned if the object is a non-null vector (i.e. it implements the IVector interface), and has the same dimension and equal elements as the current vector.
This method calls the VectorBase.Equals(object) to obtain the returned value, which is standard for all implementations of the IVector interface.
Overrides the object.Equals(object) method.
Definition at line 884 of file VectorBase.cs.
References IG.Num.VectorBase.Equals().
Referenced by IG.Num.Vector2d.Equals(), IG.Num.Vector3d.Equals(), IG.Num.Vector.Equals(), and IG.Num.VectorBase.Equals().
GetHashFunctionInt() [1/2]
int IG.Num.VectorBase.GetHashFunctionInt () inline
Returns an integer valued hash function of the current vector object.
The returned value is calculated by the Util.GetHashFunctionInt method.
See also
Util.GetHashFunctionInt
Implements IG.Num.IVector< T >.
Definition at line 892 of file VectorBase.cs.
References IG.Lib.Util.GetHashFunctionInt().
GetHashFunctionString() [1/2]
string IG.Num.VectorBase.GetHashFunctionString () inline
Returns a string valued hash function of the current vector object.
The returned value is calculated by the Util.GetHashFunctionString method.
The returned string is always on the same length, and is based on the ToString() method. Therefore it is convenient for use in file or directory names that have one part related to a specific vector.
See also
Util.GetHashFunctionString
Implements IG.Num.IVector< T >.
Definition at line 902 of file VectorBase.cs.
References IG.Lib.Util.GetHashFunctionString().
SetZero() [2/2]
static void IG.Num.VectorBase.SetZero (IVector vec) inline static
Sets all components of the current vector to 0.
Parameters
vec Vector whose components are set.
Definition at line 940 of file VectorBase.cs.
SetConstant() [2/2]
static void IG.Num.VectorBase.SetConstant (IVector vec, double elementValue) inline static
Sets all components of the current vector to the specified value.
Parameters
vec Vector whose components are set.
elementValue Value to which vector elements are set.
Definition at line 952 of file VectorBase.cs.
SetUnit() [2/2]
static void IG.Num.VectorBase.SetUnit (IVector vec, int which) inline static
Sets the current vector to the specific unit vector (one component equals 1, others are 0).
Parameters
vec Vector whose components are set.
which Specifies which unit vector is set (i.e., which component equals 1).
Definition at line 963 of file VectorBase.cs.
SetRandom() [3/4]
static void IG.Num.VectorBase.SetRandom (IVector vec) inline static
Sets the current vector such that it contains random elements on the interval (0,1].
Parameters
vec Vector whose components are set.
Definition at line 974 of file VectorBase.cs.
References IG.Num.IRandomGenerator.NextDouble().
SetRandom() [4/4]
static void IG.Num.VectorBase.SetRandom (IVector vec, IRandomGenerator rnd) inline static
Sets the current vector such that it contains random elements on the interval (0,1].
Parameters
vec Vector whose components are set.
rnd Random generator used to generate vector elements.
Definition at line 992 of file VectorBase.cs.
References IG.Num.IRandomGenerator.NextDouble().
Compare()
static int IG.Num.VectorBase.Compare (IVector v1, IVector v2) inline static
Compares two vectors and returns -1 if the first vector is smaller than the second one, 0 if vectors are equal, and 1 if the first vector is greater. Vector that is null is considered smaller than a vector that is not null. Two null vectors are considered equal. Vector with smaller dimension is considered smaller than a vector with greater dimension. Vectors with equal dimensions ar compared by elements. The first element that is different decides which vector is considered greater.
Parameters
v1 First vector to be compared.
v2 Second vector to be compared.
Returns
-1 if the first vector is smaller than the second one, 0 if vectors are equal, and 1 if the second is greater.
This comparison does not have any mathematical meaning. It is just used for sotting of vectors in data structures.
Definition at line 1021 of file VectorBase.cs.
Referenced by IG.Num.VectorApproximatorBase.CalculateOutput(), IG.Num.SampledDataSet.GetNumInputDuplicates(), and IG.Num.SampledDataSet.RemoveInputDuplicates().
Resize() [1/3]
static void IG.Num.VectorBase.Resize (ref IVector vec, IVector template, int dimension) inline static
Resizes, if necessary, the specified vector according to the required dimension. If the vector is initially null then a new vector is created. If in this case a template vector is specified then the newly created vector will be of the same type as that template vector, because it is created by the GetNew() method on that vector. If dimension of the initial vector does not match the required dim., then vector is resized. If the specified vector dimension is less or equal to 0 then vector is resized with the same dimension as that of the template vector. If in this case the template vector is null, an exception is thrown. WARNINGS: Components are NOT preserved and have in general undefined values after operation is performed. If vector and template are null then the type of nawly created vector is Vector.
Parameters
vec Vector that is resized.
template Vector that is taken as template (for type of a newly created vector or for dimension if it is not specified).
dimension If greater than 0 then it specifies the dimension to which vector is resized.
Definition at line 1068 of file VectorBase.cs.
Referenced by IG.Num.NeuralApproximatorBase.CalculateErrorsMax(), IG.Num.NeuralApproximatorBase.CalculateErrorsMeanAbs(), IG.Num.NeuralApproximatorBase.CalculateErrorsRms(), IG.Num.VectorApproximatorBase.CalculateOutput(), IG.Num.NeuralApproximatorBase.CalculateOutput(), IG.Num.InputOutputDataDefiniton.CopyDefaultInputTo(), IG.Num.BoundingBoxBase.GetAbsoluteCoordinates(), IG.Num.BoundingBoxBase.GetIntervalLengths(), IG.Num.BoundingBoxBase.GetMax(), IG.Num.BoundingBoxBase.GetMin(), IG.Num.BoundingBoxBase.GetRandomPoint(), IG.Num.BoundingBoxBase.GetRelativeCoordinates(), IG.Num.VectorBase.LoadCsv(), IG.Num.BoundingBoxBase.Map(), IG.Num.VectorBase.OrthogonalizeGramSchmidt(), IG.Num.VectorBase.OrthogonalizeGramSchmidtNonRobust(), IG.Num.VectorBase.OrthogonalProjection(), IG.Num.AnalysisResults.PrepareResultStorage(), IG.Lib.UtilConsole.Read(), and IG.Num.SimKosecFileManagerBase.ReadInputParameters().
Resize() [2/3]
static void IG.Num.VectorBase.Resize (ref IVector vec, int dimension) inline static
Resizes, if necessary, the specified vector according to the required dimension. If the vector is initially null then a new vector is created. If dimension of the initial vector does not match the required dimension, then vector is resized. Components are NOT preserved and have in general undefined values after operation is performed. WARNING: If the vector is initially null then the type of the newly created vector is Vector.
Parameters
vec Vector that is resized.
dimension Dimension to which vector is resized (if less or equal to 0 then exception is thrown).
Definition at line 1098 of file VectorBase.cs.
Resize() [3/3]
static void IG.Num.VectorBase.Resize (ref IVector vec, IVector template) inline static
Resizes, if necessary, the specified vector according to the dimension of the specified template vector. If the vector is initially null then a new vector is created. In this case the newly created vector will be of the same type as that template vector, because it is created by the GetNew() method on that vector. If dimension of the initial vector does not match the dimension of the template vector, then vector is resized. If the template vector is null, then an exception is thrown. WARNINGS: Components are NOT preserved and have in general undefined values after operation is performed. If vector and template are null then the type of newly created vector is Vector.
Parameters
vec Vector that is resized.
template Vector that is taken as template (for type of a newly created vector or for dimension).
Definition at line 1119 of file VectorBase.cs.
CopyPlain() [1/3]
static void IG.Num.VectorBase.CopyPlain (IVector a, IVector result) inline static
Copies components of a vector to another vector. This is a plain version that does not perform any dimension checks. WARNING: dimensions of the copied vector and result vector must match.
Parameters
a Original vector.
result Vector where copy will be stored. Dimensions must match dimensions of original.
Definition at line 1144 of file VectorBase.cs.
Referenced by IG.Num.ScalarFunctionRadialUntransformed.GradientPlain(), IG.Num.MatrixBase.LuSolveNoPermutationsPlain(), IG.Num.ScalarFunctionRadial.ReferenceGradientPlain(), IG.Num.AffineTransformationSquare.TransformBackCoordinatesPlain(), IG.Num.AffineTransformationSquare.TransformBackGradientPlain(), IG.Num.AffineTransformationSquare.TransformCoordinatesPlain(), and IG.Num.AffineTransformationSquare.TransformGradientPlain().
Copy() [1/6]
static void IG.Num.VectorBase.Copy (IVector a, IVector result) inline static
Copies components of a vector to another vector. WARNING: dimensions of the copied vector and result vector must match.
Parameters
a Original vector.
result Vector where copy will be stored. Dimensions must match dimensions of original.
Definition at line 1156 of file VectorBase.cs.
Referenced by IG.Num.VectorApproximatorBase.CalculateOutput(), IG.Num.MatrixBase.CholeskySolve(), IG.Num.NeuralTrainingParameters.CopyFrom(), IG.Num.NeuralTrainingParameters.CopyResultsFrom(), IG.Num.NeuralTrainingParameters.CopyTo(), IG.Num.SampledDataSet.ExtractFilteredData(), IG.Num.NeuralTrainingLimits.IterateThroughMultidimensionalTable(), IG.Num.MatrixBase.LdltSolve(), IG.Num.BoundingBoxBase.Map(), IG.Neural.DataMapperIdentity.MapInput(), IG.Neural.DataMapperIdentity.MapOutput(), IG.Num.VectorBase.OrthogonalizeGramSchmidt(), IG.Num.VectorBase.OrthogonalizeGramSchmidtNonRobust(), IG.Num.LinearSolverBase.Solve(), IG.Num.LinearSolverBase.SolveMathNetNumerics(), IG.Num.LUDecomposition.SolveMathNetNumerics(), IG.Num.QRDecomposition.SolveMathNetNumerics(), IG.Num.CholeskyDecomposition.SolveMathNetNumerics(), IG.Num.EigenValueDecomposition.SolveMathNetNumerics(), IG.Num.SingularValueDecomposition.SolveMathNetNumerics(), and IG.Num.ScalarFunctionUntransformedBase.Test().
Copy() [2/6]
static void IG.Num.VectorBase.Copy (IVector a, ref IVector result) inline static
Copies components of a vectr to another vector. Resulting vector is allocated or reallocated if necessary.
Parameters
a Original vector.
result Vector where copy will be stored.
Definition at line 1176 of file VectorBase.cs.
CopyPlain() [2/3]
static void IG.Num.VectorBase.CopyPlain (VectorBase_MathNetNumerics a, IVector result) inline static
Copies components of a vector to another vector. This is a plain version that does not perform any dimension checks. WARNING: dimensions of the copied vector and result vector must match.
Parameters
a Original vector.
result Vector where copy will be stored. Dimensions must match dimensions of original.
Definition at line 1199 of file VectorBase.cs.
Copy() [3/6]
static void IG.Num.VectorBase.Copy (VectorBase_MathNetNumerics a, IVector result) inline static
Copies components of a vector to another vector. WARNING: dimensions of the copied vector and result vector must match.
Parameters
a Original vector.
result Vector where copy will be stored. Dimensions must match dimensions of original.
Definition at line 1211 of file VectorBase.cs.
Copy() [4/6]
static void IG.Num.VectorBase.Copy (VectorBase_MathNetNumerics a, ref IVector result) inline static
Copies components of a vectr to another vector. Resulting vector is allocated or reallocated if necessary.
Parameters
a Original vector.
result Vector where copy will be stored.
Definition at line 1231 of file VectorBase.cs.
CopyPlain() [3/3]
static void IG.Num.VectorBase.CopyPlain (IVector a, Vector_MathNetNumerics result) inline static
Copies components of a vector to another vector. This is a plain version that does not perform any dimension checks. WARNING: dimensions of the copied vector and result vector must match.
Parameters
a Original vector.
result Vector where copy will be stored. Dimensions must match dimensions of original.
Definition at line 1253 of file VectorBase.cs.
Copy() [5/6]
static void IG.Num.VectorBase.Copy (IVector a, Vector_MathNetNumerics result) inline static
Copies components of a vector to another vector. WARNING: dimensions of the copied vector and result vector must match.
Parameters
a Original vector.
result Vector where copy will be stored. Dimensions must match dimensions of original.
Definition at line 1265 of file VectorBase.cs.
Copy() [6/6]
static void IG.Num.VectorBase.Copy (IVector a, ref Vector_MathNetNumerics result) inline static
Copies components of a vectr to another vector. Resulting vector is allocated or reallocated if necessary.
Parameters
a Original vector.
result Vector where copy will be stored.
Definition at line 1285 of file VectorBase.cs.
NegatePlain()
static void IG.Num.VectorBase.NegatePlain (IVector a, IVector result) inline static
Stores a negative vector of the specified vector to another vector. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions of the copied vector and result vector must match.
Parameters
a Original vector.
result Vector where result is be stored. Dimensions must match dimensions of original.
Definition at line 1307 of file VectorBase.cs.
Negate() [2/3]
static void IG.Num.VectorBase.Negate (IVector a, IVector result) inline static
Stores a negative vector of the specified vector to another vector. WARNING: dimensions of the copied vector and result vector must match.
Parameters
a Original vector.
result Vector where result is be stored. Dimensions must match dimensions of original.
Definition at line 1318 of file VectorBase.cs.
Negate() [3/3]
static void IG.Num.VectorBase.Negate (IVector a, ref IVector result) inline static
Stores a negative vector of the specified vector to another vector. Resulting vector is allocated or reallocated if necessary.
Parameters
a Original vector.
result Vector where result is be stored.
Definition at line 1337 of file VectorBase.cs.
AddPlain()
static void IG.Num.VectorBase.AddPlain (IVector a, IVector b, IVector result) inline static
Sums two vectors and stores the result in the specified result vector. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions of vectors must match, otherwise an exception is thrown.
Parameters
a First operand.
b Second operand.
result Vector where result is stored. Dimension must match dimensions of operands.
Definition at line 1360 of file VectorBase.cs.
Referenced by IG.Num.AffineTransformationSquare.TransformCoordinatesPlain().
Add() [1/2]
static void IG.Num.VectorBase.Add (IVector a, IVector b, IVector result) inline static
Sums two vectors and stores the result in the specified result vector. WARNING: dimensions of vectors must match, otherwise an exception is thrown.
Parameters
a First operand.
b Second operand.
result Vector where result is stored. Dimension must match dimensions of operands.
Definition at line 1372 of file VectorBase.cs.
Referenced by IG.Num.AnalysisResults.CreateExample(), IG.Num.ScalarFunctionLinear.GradientPlain(), IG.Num.ScalarFunctionQuadratic.GradientPlain(), IG.Num.VectorBase.operator+(), IG.Num.ScalarFunctionUntransformedBase.Test(), and IG.Num.VectorBase.TestGramSchmidtOrthogonalization().
Add() [2/2]
static void IG.Num.VectorBase.Add (IVector a, IVector b, ref IVector result) inline static
Sums two vectors and stores the result in the specified result vector. WARNING: dimensions of operands must match, otherwise an exception is thrown. If dimensions of the result do not match then teh result is re-allocated.
Parameters
a First operand.
b Second operand.
result Vector where copy will be stored.
Definition at line 1395 of file VectorBase.cs.
SubtractPlain()
static void IG.Num.VectorBase.SubtractPlain (IVector a, IVector b, IVector result) inline static
Subtracts two vectors (a - b) and stores the result in the specified result vector. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions of vectors must match, otherwise an exception is thrown.
Parameters
a First operand.
b Second operand.
result Vector where result is stored. Dimension must match dimensions of operands.
Definition at line 1419 of file VectorBase.cs.
Referenced by IG.Num.VectorBase.OrthogonalizeGramSchmidt(), IG.Num.VectorBase.OrthogonalizeGramSchmidtNonRobust(), and IG.Num.AffineTransformationSquare.TransformBackCoordinatesPlain().
Subtract() [1/2]
static void IG.Num.VectorBase.Subtract (IVector a, IVector b, IVector result) inline static
Subtracts two vectors (a - b) and stores the result in the specified result vector. WARNING: dimensions of vectors must match, otherwise an exception is thrown.
Parameters
a First operand.
b Second operand.
result Vector where result is stored. Dimension must match dimensions of operands.
Definition at line 1431 of file VectorBase.cs.
Referenced by IG.Num.MatrixBase.CheckTestResult(), IG.Num.NeuralApproximatorBase.ExampleQuadratic(), IG.Num.NeuralApproximatorBase.ExampleSaveNetwork(), IG.Num.VectorBase.operator-(), IG.Num.ScalarFunctionUntransformedBase.Test(), IG.Num.MatrixBase.TestCholeskyDecomposition(), IG.Num.PointCloud< PointLinkType, PointContainerType, PointType >.TestClosestPoints(), IG.Num.PointCloud< PointLinkType, PointContainerType, PointType >.TestClosestPointsWithOutputs(), IG.Num.SpeedTestCpu.TestComputationalTimesCholesky_Base(), IG.Num.SpeedTestCpu.TestComputationalTimesCholesky_IGLib(), IG.Num.SpeedTestCpu.TestComputationalTimesLdlt_Base(), IG.Num.SpeedTestCpu.TestComputationalTimesLU_Base(), IG.Num.SpeedTestCpu.TestComputationalTimesLU_IGLib(), IG.Num.SpeedTestCpu.TestComputationalTimesQR_IGLib(), IG.Num.ScalarFunctionUntransformedBase.TestGradient(), IG.Num.MatrixBase.TestLdltDecomposition(), IG.Num.MatrixBase.TestLuDecomposition(), and IG.Num.NeuralApproximatorBase.TestMapping().
Subtract() [2/2]
static void IG.Num.VectorBase.Subtract (IVector a, IVector b, ref IVector result) inline static
Subtracts two vectors (a - b) and stores the result in the specified result vector. WARNING: dimensions of operands must match, otherwise an exception is thrown. If dimensions of the result do not match then teh result is re-allocated.
Parameters
a First operand.
b Second operand.
result Vector where copy will be stored.
Definition at line 1453 of file VectorBase.cs.
OrthogonalProjectionPlain() [1/2]
static void IG.Num.VectorBase.OrthogonalProjectionPlain (IVector original, IVector onWhich, double onWhichProductSelf, IVector result, double tolerance = 0.0) inline static
Calculates orthogonal projection of the original vector on the specified vector, and stores the projection in the specified result, where the inner project of the vector to which projection is performed is specified.
The dot product is used as inner product of the vector space.
No checks are performed (e.g. dimension checks or whether references are non-null).
Parameters
original The vector that is orthogonally projected to another vector.
onWhich Vector on which the original vector is projected. It must be allocated with the same dimension as original .
onWhichProductSelf The specified inner product of onWhich by itself.
WARNING: this is square of the norm of vector corresponding to the specified dot product.
Parameters
result Vector where result is storeb. It must be allocated with the same dimension as input vectors.
tolerance Tolerance for the projust of projection vector by itself. Shoulld be greater or equal to 0.
Definition at line 1484 of file VectorBase.cs.
Referenced by IG.Num.VectorBase.OrthogonalizeGramSchmidt(), IG.Num.VectorBase.OrthogonalizeGramSchmidtNonRobust(), and IG.Num.VectorBase.OrthogonalProjectionPlain().
OrthogonalProjectionPlain() [2/2]
static void IG.Num.VectorBase.OrthogonalProjectionPlain (IVector original, IVector onWhich, IVector result, double tolerance = 0.0) inline static
Calculates orthogonal projection of the original vector on the specified vector, and stores the projection in the specified result.
The dot product is used as inner product of the vector space.
No checks are performed (e.g. dimension checks or whether references are non-null).
Parameters
original The vector that is orthogonally projected to another vector.
onWhich Vector on which the original vector is projected. It must be allocated with the same dimension as original .
result Vector where result is storeb. It must be allocated with the same dimension as input vectors.
tolerance Tolerance for the projust of projection vector by itself. Shoulld be greater or equal to 0.
Definition at line 1514 of file VectorBase.cs.
References IG.Num.VectorBase.OrthogonalProjectionPlain().
OrthogonalProjection() [1/2]
static void IG.Num.VectorBase.OrthogonalProjection (IVector original, IVector onWhich, double onWhichProductSelf, ref IVector result, double tolerance = 0.0) inline static
Calculates orthogonal projection of the original vector on the specified vector, and stores the projection in the specified result, where the inner project of the vector to which projection is performed is specified.
The dot product is used as inner product of the vector space.
No checks are performed (e.g. dimension checks or whether references are non-null).
Parameters
original The vector that is orthogonally projected to another vector.
onWhich Vector on which the original vector is projected. It must be allocated with the same dimension as original .
onWhichProductSelf The specified inner product of onWhich by itself.
result Vector where result is storeb. It must be allocated with the same dimension as input vectors.
tolerance Tolerance for the projust of projection vector by itself. Shoulld be greater or equal to 0.
Definition at line 1539 of file VectorBase.cs.
References IG.Num.VectorBase.Resize().
Referenced by IG.Num.VectorBase.OrthogonalProjection().
OrthogonalProjection() [2/2]
static void IG.Num.VectorBase.OrthogonalProjection (IVector original, IVector onWhich, ref IVector result, double tolerance = 0.0) inline static
Calculates orthogonal projection of the original vector on the specified vector, and stores the projection in the specified result.
The dot product is used as inner product of the vector space.
No checks are performed (e.g. dimension checks or whether references are non-null).
Parameters
original The vector that is orthogonally projected to another vector.
onWhich Vector on which the original vector is projected. It must be allocated with the same dimension as original .
result Vector where result is storeb. It must be allocated with the same dimension as input vectors.
tolerance Tolerance for the projust of projection vector by itself. Shoulld be greater or equal to 0.
Definition at line 1580 of file VectorBase.cs.
References IG.Num.VectorBase.OrthogonalProjection(), and IG.Num.VectorBase.Resize().
ArrayAddPlain()
static void IG.Num.VectorBase.ArrayAddPlain (IVector a, double scal, IVector result) inline static
Addition of a scalar to all components of a vector. This is a plain version of the method that does not perform any consistency checks. Vector operand must be defined (non-null).
Parameters
a First operand (vector).
scal Second operand (scalar to be added).
result Result.
Definition at line 1614 of file VectorBase.cs.
ArrayAdd() [1/2]
static void IG.Num.VectorBase.ArrayAdd (IVector a, double scal, IVector result) inline static
Addition of a scalar to all components of a vector. Vector operand must be defined (non-null).
Parameters
a First operand (vector).
scal Second operand (scalar to be added).
result Result.
Definition at line 1626 of file VectorBase.cs.
ArrayAdd() [2/2]
static void IG.Num.VectorBase.ArrayAdd (IVector a, double scal, ref IVector result) inline static
Addition of a scalar to all components of a vector. Vector operand must be defined (non-null).
Parameters
a First operand (vector).
scal Second operand (scalar).
result Result.
Definition at line 1646 of file VectorBase.cs.
ArraySubtractPlain()
static void IG.Num.VectorBase.ArraySubtractPlain (IVector a, double scal, IVector result) inline static
Subtraction of a scalar from all components of a vector. This is a plain version of the method that does not perform any consistency checks. Vector operand must be defined (non-null).
Parameters
a First operand (vector).
scal Second operand (scalar).
result Result.
Definition at line 1665 of file VectorBase.cs.
ArraySubtract() [1/2]
static void IG.Num.VectorBase.ArraySubtract (IVector a, double scal, IVector result) inline static
Subtraction of a scalar from all components of a vector. Vector operand must be defined (non-null).
Parameters
a First operand (vector).
scal Second operand (scalar).
result Result.
Definition at line 1677 of file VectorBase.cs.
ArraySubtract() [2/2]
static void IG.Num.VectorBase.ArraySubtract (IVector a, double scal, ref IVector result) inline static
Subtraction of a scalar to all components of a vector. Vector operand must be defined (non-null).
Parameters
a First operand (vector).
scal Second operand (scalar).
result Result.
Definition at line 1697 of file VectorBase.cs.
MultiplyPlain()
static void IG.Num.VectorBase.MultiplyPlain (IVector a, double scal, IVector result) inline static
Multiplication of a vector by a scalar. This is a plain version of the method that does not perform any consistency checks. Vector operand must be defined (non-null).
Parameters
a First operand (vector).
scal Second operand (scalar).
result Result.
Definition at line 1716 of file VectorBase.cs.
Referenced by IG.Num.ScalarFunctionRadialUntransformed.GradientPlain(), IG.Num.VectorBase.OrthogonalizeGramSchmidt(), IG.Num.VectorBase.OrthogonalizeGramSchmidtNonRobust(), and IG.Num.ScalarFunctionRadial.ReferenceGradientPlain().
Multiply() [1/2]
static void IG.Num.VectorBase.Multiply (IVector a, double scal, IVector result) inline static
Multiplication of a vector by a scalar. Vector operand must be defined (non-null).
Parameters
a First operand (vector).
scal Second operand (scalar).
result Result.
Definition at line 1728 of file VectorBase.cs.
Referenced by IG.Num.VectorBase.operator*(), IG.Num.ScalarFunctionUntransformedBase.Test(), IG.Num.ScalarFunctionUntransformedBase.TestGradient(), IG.Num.ScalarFunctionUntransformedBase.TestHessian(), and IG.Num.ScalarFunctionUntransformedBase.TestSpeed().
Multiply() [2/2]
static void IG.Num.VectorBase.Multiply (IVector a, double scal, ref IVector result) inline static
Multiplication of a vector by a scalar. Vector operand must be defined (non-null).
Parameters
a First operand (vector).
scal Second operand (scalar).
result Result.
Definition at line 1748 of file VectorBase.cs.
ScalePlain()
static void IG.Num.VectorBase.ScalePlain (IVector a, double scal, IVector result) inline static
Multiplication of a vector by a scalar. This is a plain version of the method that does not perform any consistency checks. Vector operand must be defined (non-null).
Parameters
a First operand (vector).
scal Second operand (scalar).
result Result.
Definition at line 1767 of file VectorBase.cs.
Scale() [1/2]
static void IG.Num.VectorBase.Scale (IVector a, double scal, IVector result) inline static
Multiplication of a vector by a scalar. Vector operand must be defined (non-null).
Parameters
a First operand (vector).
scal Second operand (scalar).
result Result.
Definition at line 1779 of file VectorBase.cs.
Scale() [2/2]
static void IG.Num.VectorBase.Scale (IVector a, double scal, ref IVector result) inline static
Multiplication of a vector by a scalar. Vector operand must be defined (non-null).
Parameters
a First operand (vector).
scal Second operand (scalar).
result Result.
Definition at line 1799 of file VectorBase.cs.
DividePlain()
static void IG.Num.VectorBase.DividePlain (IVector a, double scal, IVector result) inline static
Division of a vector by a scalar. This is a plain version of the method that does not perform any consistency checks. Vector operand must be defined (non-null).
Parameters
a First operand (vector).
scal Second operand (scalar).
result Result.
Definition at line 1818 of file VectorBase.cs.
Divide() [1/2]
static void IG.Num.VectorBase.Divide (IVector a, double scal, IVector result) inline static
Division of a vector by a scalar. Vector operand must be defined (non-null).
Parameters
a First operand (vector).
scal Second operand (scalar).
result Result.
Definition at line 1830 of file VectorBase.cs.
Referenced by IG.Num.VectorBase.Normalize(), IG.Num.VectorBase.Normalized(), IG.Num.VectorBase.operator/(), and IG.Num.ScalarFunctionUntransformedBase.Test().
Divide() [2/2]
static void IG.Num.VectorBase.Divide (IVector a, double scal, ref IVector result) inline static
Division of a vector by a scalar. Vector operand must be defined (non-null).
Parameters
a First operand (vector).
scal Second operand (scalar).
result Result.
Definition at line 1850 of file VectorBase.cs.
ScalarProductPlain()
static double IG.Num.VectorBase.ScalarProductPlain (IVector a, IVector b) inline static
Scalar product of teo vectors. This is a plain version of the method that does not perform any consistency checks.
Parameters
a First operand (vector).
b Second operand (vector).
Returns
Scalar product of operands.
Definition at line 1874 of file VectorBase.cs.
ScalarProduct()
static double IG.Num.VectorBase.ScalarProduct (IVector a, IVector b) inline static
Scalar product of teo vectors.
Parameters
a First operand (vector).
b Second operand (vector).
Returns
Scalar product of operands.
Definition at line 1887 of file VectorBase.cs.
Referenced by IG.Num.VectorBase.operator*(), IG.Num.VectorBase.TestGramSchmidtOrthogonalization(), IG.Num.ScalarFunctionLinear.Value(), and IG.Num.ScalarFunctionQuadratic.Value().
DyadicProductPlain()
static void IG.Num.VectorBase.DyadicProductPlain (IVector a, IVector b, IMatrix result) inline static
Calculates dyadic product of two vectors and stores the result in the specified result matrix. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions must match, otherwise an exception is thrown.
Parameters
a First operand.
b Second operand.
result Matrix where result is stored. Dimension must match dimensions of operands.
Definition at line 1910 of file VectorBase.cs.
DyadicProduct() [1/2]
static void IG.Num.VectorBase.DyadicProduct (IVector a, IVector b, IMatrix result) inline static
Calculates dyadic product of two vectors and stores the result in the specified result matrix. WARNING: dimensions must match, otherwise an exception is thrown.
Parameters
a First operand.
b Second operand.
result Matrix where result is stored. Dimension must match dimensions of operands.
Definition at line 1927 of file VectorBase.cs.
References IG.Num.IMatrix< ComponentType >.ColumnCount, and IG.Num.IMatrix< ComponentType >.RowCount.
DyadicProduct() [2/2]
static void IG.Num.VectorBase.DyadicProduct (IVector a, IVector b, ref IMatrix result) inline static
Calculates dyadic product of two vectors and stores the result in the specified result matrix. WARNING: dimensions of operands must match, otherwise an exception is thrown. If dimensions of the result do not match then teh result is re-allocated.
Parameters
a First operand.
b Second operand.
result Matrix where copy will be stored.
Definition at line 1954 of file VectorBase.cs.
CrossProductPlain()
static void IG.Num.VectorBase.CrossProductPlain (IVector a, IVector b, IVector result) inline static
Calculates a vector product (cross product) of two vectors and stores the result in the specified result vector. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions of all vectors must be 3, otherwise an exception is thrown.
Parameters
a First operand.
b Second operand.
result Vector where result is stored. Dimension must match dimensions of operands.
Definition at line 1980 of file VectorBase.cs.
CrossProduct() [1/2]
static void IG.Num.VectorBase.CrossProduct (IVector a, IVector b, IVector result) inline static
Calculates a vector product (cross product) of two vectors and stores the result in the specified result vector. WARNING: dimensions of all vectors must be 3, otherwise an exception is thrown.
Parameters
a First operand.
b Second operand.
result Vector where result is stored. Dimension must match dimensions of operands.
Definition at line 1992 of file VectorBase.cs.
Referenced by IG.Num.VectorBase.VectorProduct().
CrossProduct() [2/2]
static void IG.Num.VectorBase.CrossProduct (IVector a, IVector b, ref IVector result) inline static
Calculates a vector product (cross product) of two vectors and stores the result in the specified result vector. WARNING: dimensions of operands must match, otherwise an exception is thrown. If dimensions of the result do not match then teh result is re-allocated.
Parameters
a First operand.
b Second operand.
result Vector where copy will be stored.
Definition at line 2014 of file VectorBase.cs.
VectorProductPlain()
static void IG.Num.VectorBase.VectorProductPlain (IVector a, IVector b, IVector result) inline static
Calculates a vector product (cross product) of two vectors and stores the result in the specified result vector. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions of all vectors must be 3, otherwise an exception is thrown.
Parameters
a First operand.
b Second operand.
result Vector where result is stored. Dimension must match dimensions of operands.
Definition at line 2038 of file VectorBase.cs.
VectorProduct() [1/2]
static void IG.Num.VectorBase.VectorProduct (IVector a, IVector b, IVector result) inline static
Calculates a vector product (cross product) of two vectors and stores the result in the specified result vector. WARNING: dimensions of all vectors must be 3, otherwise an exception is thrown.
Parameters
a First operand.
b Second operand.
result Vector where result is stored. Dimension must match dimensions of operands.
Definition at line 2050 of file VectorBase.cs.
References IG.Num.VectorBase.CrossProduct().
VectorProduct() [2/2]
static void IG.Num.VectorBase.VectorProduct (IVector a, IVector b, ref IVector result) inline static
Calculates a vector product (cross product) of two vectors and stores the result in the specified result vector. WARNING: dimensions of operands must match, otherwise an exception is thrown. If dimensions of the result do not match then teh result is re-allocated.
Parameters
a First operand.
b Second operand.
result Vector where copy will be stored.
Definition at line 2061 of file VectorBase.cs.
References IG.Num.VectorBase.CrossProduct().
ArrayProductPlain()
static void IG.Num.VectorBase.ArrayProductPlain (IVector a, IVector b, IVector result) inline static
Calculates array product (element-by-element product) of two vectors and stores the result in the specified result vector. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions of all vectors must be 3, otherwise an exception is thrown.
Parameters
a First operand.
b Second operand.
result Vector where result is stored. Dimension must match dimensions of operands.
Definition at line 2074 of file VectorBase.cs.
Referenced by IG.Num.VectorBase.ArrayProduct(), IG.Num.NeuralApproximatorBase.SetMaxToleranceRelstiveToRange(), and IG.Num.NeuralApproximatorBase.SetRmsToleranceRelstiveToRange().
ArrayProduct() [1/2]
static void IG.Num.VectorBase.ArrayProduct (IVector a, IVector b, IVector result) inline static
Calculates array product (element-by-element product) of two vectors and stores the result in the specified result vector. WARNING: dimensions of all vectors must be 3, otherwise an exception is thrown.
Parameters
a First operand.
b Second operand.
result Vector where result is stored. Dimension must match dimensions of operands.
Definition at line 2086 of file VectorBase.cs.
ArrayProduct() [2/2]
static void IG.Num.VectorBase.ArrayProduct (IVector a, IVector b, ref IVector result) inline static
Calculates array product (element-by-element product) of two vectors and stores the result in the specified result vector. WARNING: dimensions of operands must match, otherwise an exception is thrown. If dimensions of the result do not match then teh result is re-allocated.
Parameters
a First operand.
b Second operand.
result Vector where copy will be stored.
Definition at line 2108 of file VectorBase.cs.
References IG.Num.VectorBase.ArrayProductPlain().
ArrayQuotientPlain()
static void IG.Num.VectorBase.ArrayQuotientPlain (IVector a, IVector b, IVector result) inline static
Calculates array quotient (element-by-element division) of two vectors and stores the result in the specified result vector. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions of all vectors must be 3, otherwise an exception is thrown.
Parameters
a First operand.
b Second operand.
result Vector where result is stored. Dimension must match dimensions of operands.
Definition at line 2130 of file VectorBase.cs.
ArrayQuotient() [1/2]
static void IG.Num.VectorBase.ArrayQuotient (IVector a, IVector b, IVector result) inline static
Calculates array quotient (element-by-element division) of two vectors and stores the result in the specified result vector. WARNING: dimensions of all vectors must be 3, otherwise an exception is thrown.
Parameters
a First operand.
b Second operand.
result Vector where result is stored. Dimension must match dimensions of operands.
Definition at line 2142 of file VectorBase.cs.
ArrayQuotient() [2/2]
static void IG.Num.VectorBase.ArrayQuotient (IVector a, IVector b, ref IVector result) inline static
Calculates array quotient (element-by-element division) of two vectors and stores the result in the specified result vector. WARNING: dimensions of operands must match, otherwise an exception is thrown. If dimensions of the result do not match then teh result is re-allocated.
Parameters
a First operand.
b Second operand.
result Vector where copy will be stored.
Definition at line 2164 of file VectorBase.cs.
GetHashCode() [2/2]
static int IG.Num.VectorBase.GetHashCode (IVector vec) inline static
Returns hash code of the specified vector.
Parameters
vec Vector whose hath code is returned.
This method should be used when overriding the GetHashCode() in vector classes, in order to unify equality check over different vector classes.
Definition at line 2191 of file VectorBase.cs.
Equals() [2/2]
static bool IG.Num.VectorBase.Equals (IVector v1, IVector v2) inline static
Returns true if the specified vectors are equal, false if not.
Parameters
v1 The first of the two vectors that are checked for equality.
v2 The second of the two vectors that are checked for equality.
This method should be used when overriding the Equals() method in vector classes, in order to unify calculation of hash code over different vector classes.
If both vectors are nulll or both have dimension less than 1 then vectors are considered equal.
This method is consistent with the VectorBase.Compare method, i.e. it returns the same value as the expression VectorBase.Compare(v1 , v2 ==0).
Definition at line 2216 of file VectorBase.cs.
GetHashFunctionInt() [2/2]
static int IG.Num.VectorBase.GetHashFunctionInt (IVector vec) inline static
Returns an integer valued hash function of the specified vector object.
The returned value is calculated by the Util.GetHashFunctionInt method.
<vec>Vector object whose hash function is calculated and returned.</vec>
See also
Util.GetHashFunctionInt
Definition at line 2246 of file VectorBase.cs.
References IG.Lib.Util.GetHashFunctionInt().
GetHashFunctionString() [2/2]
static string IG.Num.VectorBase.GetHashFunctionString (IVector vec) inline static
Returns a string valued hash function of the specified vector object.
The returned value is calculated by the Util.GetHashFunctionString method.
<vec>Vector object whose hash function is calculated and returned.</vec>
See also
Util.GetHashFunctionString
Definition at line 2255 of file VectorBase.cs.
References IG.Lib.Util.GetHashFunctionString().
OrthoNormalizeGramSchmidt()
static void IG.Num.VectorBase.OrthoNormalizeGramSchmidt (IList< IVector > original, ref IList< IVector > resOrthogonal, ref IVector resNorms, ref IVector auxProjection, double tolDependent = 1e-10, bool normalize = false, int numRequestedVectors = 0, IRandomGenerator rand = null, int maxExcessGenerated = 5) inline static
Performs the Gramm-Schmidt orthogonalization procedure in order to calculate a set of orthonormal vectors from the specified set of arbitrary independent vectors.
This method is robust, it fails if input vectors are almost linearly dependent (limited by tolerance).
Parameters
original A set of original vectors, must be of the same dimensiions.
resOrthogonal Resulting list where a set of orthogonal vectors is stored.
resNorms A vector where norms of the resulting orthogonal vectors are stored. Its dimension must be at least equal to the number of original vectors, otherwise it is resized to the dimension of the original vectors.
auxProjection Auxiliary vector used in computatioin.
tolDependent Tolerance on the size of the vector after subtracting all projections, divided by original size.
normalize If true then the resulting vectors are normalized, otherwise they are not.
numRequestedVectors Number of requested normal vectors. If 0 then the number is the same as vector dimension.
rand Random number generator used for generation of random original vectors when this is necessary (i.e., when the number of provided linnearly independent original vector is smaller than the requested number of calculated vectors). If not specified then the global random number generator is taken.
maxExcessGenerated Maximal number of excessive original vectors that are randomly generated, to compensate for linearly dependent input vectors. This is the number of randomly generated input vectors above those eventually needed because of linear dependency or insufficient number of provided input vectors.
If 0 then only the minimal number of generated vectors is allowed in order to compensate for insufficient number of procided input vectors (i.e. less than the number of requested v.) o for linear dependency upon them. If any generated input vector is dependent on input and previously generated vectors then the operation will fail with exception thrown.
If -1 then generation of additional input vectors is not allowed at all, and in the case of insufficiency of input vectors (too few linearly independent vectors) operation will fail with exception thrown.
If positive, this number tells how many additional input vectors can be generated because other generated vectors (including the necessary ones - due to insufficiency of input vectors) suffered for linear dependency.
Returns
The number of orthogonal vectors that were actually calculated from the specified original vectors. This coincides with the dimension of the space spanned by the provided original vectors.
Definition at line 2299 of file VectorBase.cs.
References IG.Num.VectorBase.OrthogonalizeGramSchmidt().
OrthogonalizeGramSchmidt()
static int IG.Num.VectorBase.OrthogonalizeGramSchmidt (IList< IVector > original, ref IList< IVector > resOrthogonal, ref IVector resNorms, ref IVector auxProjection, double tolDependent = 1e-10, bool normalize = false, int numRequestedVectors = 0, IRandomGenerator rand = null, int maxExcessGenerated = 5) inline static
Performs the Gramm-Schmidt orthogonalization procedure in order to calculate a set of orthogonall vectors from the specified set of arbitrary independent vectors.
This method is robust, if input vectors are almost linearly dependent (limited by tolerance) then random iput vectors are generated and replace the original ones, until the orthogonal set is finally created..
Parameters
original A set of original vectors, must be of the same dimensiions.
resOrthogonal Resulting list where a set of orthogonal vectors is stored.
resNorms A vector where norms of the resulting orthogonal vectors are stored. Its dimension must be at least equal to the number of original vectors, otherwise it is resized to the dimension of the original vectors.
auxProjection Auxiliary vector used in computatiioin.
tolDependent Tolerance on the size of the vector after subtracting all projections, divided by original size..
normalize If true then the resulting vectors are normalized, otherwise they are not.
numRequestedVectors Number of orthogonal vectors to be calculated. If 0 then the number is the same as vector dimension. If larger than dimension then exception is thrown.
rand Random number generator used for generation of random original vectors when this is necessary (i.e., when the number of provided linnearly independent original vector is smaller than the requested number of calculated vectors). If not specified then the global random number generator is taken.
maxExcessGenerated Maximal number of excessive original vectors that are randomly generated, to compensate for linearly dependent input vectors. This is the number of randomly generated input vectors above those eventually needed because of linear dependency or insufficient number of provided input vectors.
If 0 then only the minimal number of generated vectors is allowed in order to compensate for insufficient number of procided input vectors (i.e. less than the number of requested v.) o for linear dependency upon them. If any generated input vector is dependent on input and previously generated vectors then the operation will fail with exception thrown.
If -1 then generation of additional input vectors is not allowed at all, and in the case of insufficiency of input vectors (too few linearly independent vectors) operation will fail with exception thrown. This effectively means that the we have nonrobust procedure.
If positive, this number tells how many additional input vectors can be generated because other generated vectors (including the necessary ones - due to insufficiency of input vectors) suffered for linear dependency.
Returns
The number of orthogonal vectors that were actually calculated from the specified original vectors. This coincides with the dimension of the space spanned by the provided original vectors.
Definition at line 2338 of file VectorBase.cs.
References IG.Num.VectorBase.Copy(), IG.Num.RandomGenerator.Global, IG.Num.VectorBase.MultiplyPlain(), IG.Num.VectorBase.Norm2Plain(), IG.Num.VectorBase.OrthogonalProjectionPlain(), IG.Num.VectorBase.Resize(), IG.Num.VectorBase.SetRandom(), and IG.Num.VectorBase.SubtractPlain().
Referenced by IG.Num.VectorBase.OrthoNormalizeGramSchmidt(), and IG.Num.VectorBase.TestGramSchmidtOrthogonalization().
OrthoNormalizeGramSchmidtNonRobust()
static void IG.Num.VectorBase.OrthoNormalizeGramSchmidtNonRobust (IList< IVector > original, ref IList< IVector > resOrthogonal, ref IVector resNorms, ref IVector auxProjection, double tolSize = 0, bool normalize = false, bool modifiedGrammSchmidt = true) inline static
Performs the Gramm-Schmidt orthogonalization procedure in order to calculate a set of orthonormal vectors from the specified set of arbitrary independent vectors.
This method is not robust, it fails if input vectors are almost linearly dependent (limited by tolerance).
Parameters
original A set of original vectors, must be of the same dimensiions.
resOrthogonal Resulting list where a set of orthogonal vectors is stored.
resNorms A vector where norms of the resulting orthogonal vectors are stored. Its dimension must be at least equal to the number of original vectors, otherwise it is resized to the dimension of the original vectors.
auxProjection Auxiliary vector used in computatioin.
tolSize Tolerance on the size of the vector after subtracting all projections.
normalize If true then the resulting vectors are normalized, otherwise they are not.
modifiedGrammSchmidt If true (which is default) then a more stable modification is used.
Definition at line 2544 of file VectorBase.cs.
References IG.Num.VectorBase.OrthogonalizeGramSchmidtNonRobust().
OrthogonalizeGramSchmidtNonRobust()
static void IG.Num.VectorBase.OrthogonalizeGramSchmidtNonRobust (IList< IVector > original, ref IList< IVector > resOrthogonal, ref IVector resNorms, ref IVector auxProjection, double tolSize = 0, bool normalize = false, bool modifiedGrammSchmidt = true) inline static
Performs the Gramm-Schmidt orthogonalization procedure in order to calculate a set of orthogonall vectors from the specified set of arbitrary independent vectors.
This method is not robust, it fails if input vectors are almost linearly dependent (limited by tolerance).
Parameters
original A set of original vectors, must be of the same dimensiions.
resOrthogonal Resulting list where a set of orthogonal vectors is stored.
resNorms A vector where norms of the resulting orthogonal vectors are stored. Its dimension must be at least equal to the number of original vectors, otherwise it is resized to the dimension of the original vectors.
auxProjection Auxiliary vector used in computatiioin.
tolSize Tolerance on the size of the vector after subtracting all projections.
normalize If true then the resulting vectors are normalized, otherwise they are not.
modifiedGrammSchmidt If true (which is default) then a more stable modification is used.
Definition at line 2564 of file VectorBase.cs.
References IG.Num.VectorBase.Copy(), IG.Num.VectorBase.MultiplyPlain(), IG.Num.VectorBase.Norm2Plain(), IG.Num.VectorBase.OrthogonalProjectionPlain(), IG.Num.VectorBase.Resize(), and IG.Num.VectorBase.SubtractPlain().
Referenced by IG.Num.VectorBase.OrthoNormalizeGramSchmidtNonRobust(), and IG.Num.VectorBase.TestGramSchmidtOrthogonalization().
TestGramSchmidtOrthogonalization()
static bool IG.Num.VectorBase.TestGramSchmidtOrthogonalization (int dim, int numRepetitions = 1, double tol = 1e-8, int outputLevel = 0, IRandomGenerator randomGenerator = null, bool normalize = false, bool modifiedGrammSchmidt = true, bool nonRobust = false) inline static
Performs a test of Gramm-Schmidt orthogonalization on a set of random vectors.
Parameters
dim dimension of vectors to be orthogonalized.
numRepetitions Nomber of repetitions (how many times the procedure is repeated).
tol Tolerance for zero length of resulting vectors.
outputLevel Level of output.
randomGenerator Random generator used.
normalize Whether resulting vectors are normalized.
modifiedGrammSchmidt Whether a modified gramm-schmidt algorithm is used.
nonRobust If true then non - robust algorithm is tested. Otherwise, the default robust algorithm is tested (which produces the required number of orthogonal vectors even if the dimension of the subspace spanned by the original vectors is smaller than dimension of the original vector space).
Returns
True if the test completes successfully, false otherwise.
Definition at line 2677 of file VectorBase.cs.
References IG.Num.VectorBase.Add(), IG.Lib.StopWatch1.CpuTime, IG.Num.RandomGenerator.Global, IG.Num.VectorBase.OrthogonalizeGramSchmidt(), IG.Num.VectorBase.OrthogonalizeGramSchmidtNonRobust(), IG.Num.Vector.Random(), IG.Num.VectorBase.ScalarProduct(), IG.Lib.StopWatch1.Start(), IG.Lib.StopWatch1.Stop(), IG.Lib.StopWatch1.Time, and IG.Num.VectorBase.ToStringMath().
operator+() [1/2]
static VectorBase IG.Num.VectorBase.operator+ (VectorBase v) inline static
Unary plus, returns the operand.
Definition at line 2831 of file VectorBase.cs.
References IG.Num.VectorBase.GetCopyBase().
operator-() [1/2]
static VectorBase IG.Num.VectorBase.operator- (VectorBase v) inline static
Unary negation, returns the negative operand.
Definition at line 2838 of file VectorBase.cs.
References IG.Num.VectorBase.GetCopyBase(), and IG.Num.VectorBase.Negate().
operator+() [2/2]
static VectorBase IG.Num.VectorBase.operator+ (VectorBase a, VectorBase b) inline static
Vector addition.
Definition at line 2846 of file VectorBase.cs.
References IG.Num.VectorBase.Add(), and IG.Num.VectorBase.GetNewBase().
operator-() [2/2]
static VectorBase IG.Num.VectorBase.operator- (VectorBase a, VectorBase b) inline static
Vector subtraction.
Definition at line 2855 of file VectorBase.cs.
References IG.Num.VectorBase.GetNewBase(), and IG.Num.VectorBase.Subtract().
operator*() [1/3]
static double IG.Num.VectorBase.operator* (VectorBase a, VectorBase b) inline static
Scalar product of two vectors.
Definition at line 2864 of file VectorBase.cs.
References IG.Num.VectorBase.ScalarProduct().
operator*() [2/3]
static VectorBase IG.Num.VectorBase.operator* (VectorBase a, double b) inline static
Product of a vector by a scalar.
Definition at line 2870 of file VectorBase.cs.
References IG.Num.VectorBase.GetNewBase(), and IG.Num.VectorBase.Multiply().
operator*() [3/3]
static VectorBase IG.Num.VectorBase.operator* (double a, VectorBase b) inline static
Product of a vector by a scalar.
Definition at line 2878 of file VectorBase.cs.
References IG.Num.VectorBase.GetNewBase(), and IG.Num.VectorBase.Multiply().
operator/()
static VectorBase IG.Num.VectorBase.operator/ (VectorBase a, double b) inline static
Vector subtraction.
Definition at line 2886 of file VectorBase.cs.
References IG.Num.VectorBase.Divide(), and IG.Num.VectorBase.GetNewBase().
ToString() [1/4]
static string IG.Num.VectorBase.ToString (IVector vec) inline static
Returns a string representation of the specified vector in a standard IGLib form.
Parameters
vec Vector whose string representation is returned.
Definition at line 2906 of file VectorBase.cs.
References IG.Lib.Util.NullRepresentationString, and IG.Num.VectorBase.ToStringMath().
Referenced by IG.Num.VectorExtensions.ToString().
ToStringMath() [1/4]
static string IG.Num.VectorBase.ToStringMath (IVector vec) inline static
Returns a string representation of the specified vector in a standard IGLib form (Mathematica-like format but with C representation of numbers).
Parameters
vec Vector whose string representation is returned.
Definition at line 2917 of file VectorBase.cs.
References IG.Num.VectorBase.ToString().
Referenced by IG.Num.VectorBase.TestGramSchmidtOrthogonalization(), IG.Num.VectorExtensions.ToStringMath(), IG.Num.AnalysisResults.ToStringMath(), and IG.Num.AnalysisResults.ToStringRequestMath().
ToString() [2/4]
static string IG.Num.VectorBase.ToString (IVector vec, string elementFormat) inline static
Returns a string representation of the specified vector in a standard IGLib form, with the specified
format for elements of the vector.
Parameters
vec Vector whose string representation is returned.
elementFormat Format specification for printing individual element.
Definition at line 2941 of file VectorBase.cs.
References IG.Lib.Util.NullRepresentationString, and IG.Num.VectorBase.ToStringMath().
ToStringMath() [2/4]
static string IG.Num.VectorBase.ToStringMath (IVector vec, string elementFormat) inline static
Returns a string representation of the specified vector in a standard IGLib form (Mathematica-like format but with C representation of numbers), with the specified
format for elements of the vector.
Parameters
vec Vector whose string representation is returned.
elementFormat Format specification for printing individual element.
Definition at line 2953 of file VectorBase.cs.
References IG.Num.VectorBase.ToString().
SaveJson() [1/2]
static void IG.Num.VectorBase.SaveJson (IVector vec, string filePath) inline static
Saves (serializes) the specified vector to the specified JSON file. File is owerwritten if it exists.
Parameters
vec Object that is saved to a file.
filePath Path to the file in which object is is saved.
Definition at line 2978 of file VectorBase.cs.
Referenced by IG.Neural.NeuraApproximationFileManager.ClientTestCalculateApproximation(), IG.Neural.MappingApproximationFileManager.WriteFunctionInput(), IG.Neural.MappingApproximationFileManager.WriteFunctionOutput(), IG.Neural.NeuraApproximationFileManager.WriteNeuralInput(), and IG.Neural.NeuraApproximationFileManager.WriteNeuralOutput().
SaveJson() [2/2]
static void IG.Num.VectorBase.SaveJson (IVector vec, string filePath, bool append) inline static
Saves (serializes) the specified vector to the specified JSON file. If the file already exists, contents either overwrites the file or is appended at the end, dependent on the value of the append flag.
Parameters
vec Object that is saved to a file.
filePath Path to the file in which object is saved.
append Specifies whether serialized data is appended at the end of the file in the case that the file already exists.
Definition at line 2990 of file VectorBase.cs.
References IG.Lib.SerializationDtoBase< Type, BaseType >.CopyFrom().
LoadJson()
static void IG.Num.VectorBase.LoadJson (string filePath, ref IVector vecRestored) inline static
Restores (deserializes) a vector from the specified file in JSON format.
Parameters
filePath File from which object is restored.
vecRestored Object that is restored by deserialization.
Definition at line 3001 of file VectorBase.cs.
References IG.Lib.SerializationDtoBase< Type, BaseType >.CopyTo().
Referenced by IG.Num.OptFileManager.ClientTestCalculateAnalysisResults(), IG.Neural.NeuraApproximationFileManager.ClientTestCalculateApproximation(), IG.Neural.MappingApproximationFileManager.ClientTestCalculateMappingApproximation(), IG.Neural.MappingApproximationFileManager.ReadFunctionInput(), IG.Neural.MappingApproximationFileManager.ReadFunctionOutput(), IG.Neural.NeuraApproximationFileManager.ReadNeuralInput(), and IG.Neural.NeuraApproximationFileManager.ReadNeuralOutput().
SaveCsv() [1/4]
static void IG.Num.VectorBase.SaveCsv (IVector vec, string filePath) inline static
Saves the specified vector to a CSV file. It the specified file already exists then it is overwritten. Constant UtilCsv.DefaultCsvSeparator is used as separator.
Parameters
vec Vector to be stored to a file.
filePath Path of the file to which vector is stored.
Definition at line 3014 of file VectorBase.cs.
References IG.Lib.UtilCsv.DefaultCsvSeparator.
Referenced by IG.Num.VectorBase.SaveCsv(), and IG.Num.SimKosecFileManagerBase.WriteOutputValues().
SaveCsv() [2/4]
static void IG.Num.VectorBase.SaveCsv (IVector vec, string filePath, string separator) inline static
Saves the specified vector to a CSV file. It the specified file already exists then it is overwritten.
Parameters
vec Vector to be stored to a file.
filePath Path of the file to which vector is stored.
separator Separator used in the CSV file.
Definition at line 3024 of file VectorBase.cs.
References IG.Num.VectorBase.SaveCsv().
SaveCsv() [3/4]
static void IG.Num.VectorBase.SaveCsv (IVector vec, string filePath, bool append) inline static
Saves the specified vector to a CSV file. Constant UtilCsv.DefaultCsvSeparator is used as separator in CSV.
Parameters
vec Vector to be stored to a file.
filePath Path of the file to which vector is stored.
append Specifies whether the data is appended at the end of the file in the case that the ifle already exists.
Definition at line 3035 of file VectorBase.cs.
References IG.Lib.UtilCsv.DefaultCsvSeparator, and IG.Num.VectorBase.SaveCsv().
SaveCsv() [4/4]
static void IG.Num.VectorBase.SaveCsv (IVector vec, string filePath, string separator, bool append) inline static
Saves the specified vector to a CSV file.
Parameters
vec Vector to be stored to a file.
filePath Path of the file to which vector is stored.
separator Separator used in the CSV file.
append Specifies whether the data is appended at the end of the file in the case that the ifle already exists.
Definition at line 3046 of file VectorBase.cs.
References IG.Lib.UtilCsv.SaveCsv(), and IG.Num.VectorBase.ToString().
LoadCsv() [1/4]
static void IG.Num.VectorBase.LoadCsv (string filePath, ref IVector vecRestored) inline static
Reads a vector from a CSV file. Constant UtilCsv.DefaultCsvSeparator is used as separator in CSV file. If there are no components then a null vector is returned by this method (no exceptions thrown). If there are more than one rows in the CSV file then vector is read from the first row.
Parameters
filePath Path to the file that contains a vector in CSV format.
vecRestored Vector object where the read-in vector is stored.
Definition at line 3066 of file VectorBase.cs.
References IG.Lib.UtilCsv.DefaultCsvSeparator.
Referenced by IG.Num.VectorBase.LoadCsv(), and IG.Num.SimKosecFileManagerBase.ReadOutputValues().
LoadCsv() [2/4]
static void IG.Num.VectorBase.LoadCsv (string filePath, string separator, ref IVector vecRestored) inline static
Reads a vector written in CSV format from a file. If there are no components then a null vector is returned by this method (no exceptions thrown). If there are more than one rows in the CSV file then vector is read from the first row.
Parameters
filePath Path to the file that contains a vector in CSV format.
separator Separator that is used to separate values in a row in the CSV file.
vecRestored Vector object where the read-in vector is stored.
Definition at line 3077 of file VectorBase.cs.
References IG.Lib.UtilCsv.LoadCsv(), and IG.Num.VectorBase.Resize().
LoadCsv() [3/4]
static void IG.Num.VectorBase.LoadCsv (string filePath, int rowNum, ref IVector vecRestored) inline static
Reads a vector from the specified row of a CSV file. Constant UtilCsv.DefaultCsvSeparator is used as CSV separator. If the specified row does not exisist in the file then exception is thrown.
Parameters
filePath Path to the file that contains a vector in CSV format.
rowNum Number of the row from which the vector is read.
vecRestored Vector object where the read-in vector is stored.
Definition at line 3111 of file VectorBase.cs.
References IG.Lib.UtilCsv.DefaultCsvSeparator, and IG.Num.VectorBase.LoadCsv().
LoadCsv() [4/4]
static void IG.Num.VectorBase.LoadCsv (string filePath, int rowNum, string separator, ref IVector vecRestored) inline static
Reads a vector from the specified row of a CSV file. If the specified row does not exisist in the file then exception is thrown.
Parameters
filePath Path to the file that contains a vector in CSV format.
rowNum Number of the row from which the vector is read.
separator Separator that is used to separate values in a row in the CSV file.
vecRestored Vector object where the read-in vector is stored.
Definition at line 3122 of file VectorBase.cs.
References IG.Lib.UtilCsv.LoadCsv(), and IG.Num.VectorBase.Resize().
ToString() [3/4]
override string IG.Num.VectorBase.ToString () inline
Returns a string representation of this vector in a standard IGLib form.
Implements IG.Num.IVector< T >.
Definition at line 3156 of file VectorBase.cs.
Referenced by IG.Num.VectorBase.SaveCsv(), IG.Num.VectorBase.ToString(), and IG.Num.VectorBase.ToStringMath().
ToStringMath() [3/4]
virtual string IG.Num.VectorBase.ToStringMath () inline virtual
Returns a string representation of this vector in a standard IGLib form (Mathematica-like format but with C representation of numbers).
Implements IG.Num.IVector< T >.
Definition at line 3163 of file VectorBase.cs.
Referenced by IG.Num.VectorBase.ToString(), and IG.Num.VectorBase.ToStringMath().
ToString() [4/4]
virtual string IG.Num.VectorBase.ToString (string elementFormat) inline virtual
Returns a string representation of the current vector in a standard IGLib form, with the specified
format for elements of the vector.
Parameters
elementFormat Format specification for printing individual element.
Implements IG.Num.IVector< T >.
Definition at line 3172 of file VectorBase.cs.
References IG.Num.VectorBase.ToString().
ToStringMath() [4/4]
virtual string IG.Num.VectorBase.ToStringMath (string elementFormat) inline virtual
Returns a string representation of the current vector in a standard IGLib form (Mathematica-like format but with C representation of numbers), with the specified
format for elements of the vector.
Parameters
elementFormat Format specification for printing individual element.
Implements IG.Num.IVector< T >.
Definition at line 3181 of file VectorBase.cs.
References IG.Num.VectorBase.ToStringMath().
Member Data Documentation
_matrixStore
VectorStore IG.Num.VectorBase._matrixStore static private
Definition at line 915 of file VectorBase.cs.
Property Documentation
Length
abstract int IG.Num.VectorBase.Length get
Gets dimension of the vector.
Definition at line 274 of file VectorBase.cs.
Referenced by IG.Num.VectorBase.NormP(), IG.Num.VectorBase.SetConstant(), IG.Num.VectorBase.SetUnit(), IG.Num.VectorBase.SetZero(), and IG.Num.VectorBase.ToArray().
this[int i]
abstract double IG.Num.VectorBase.this[int i] get set
Gets or sets the element indexed by i in the Vector.
Parameters
i Element index, 0 - based.
Definition at line 280 of file VectorBase.cs.
Norm
virtual double IG.Num.VectorBase.Norm get
Gets Euclidean norm of the vector.
Definition at line 405 of file VectorBase.cs.
Referenced by IG.Num.VectorBase.Normalize(), and IG.Num.VectorBase.Normalized().
Norm2
virtual double IG.Num.VectorBase.Norm2 get
Gets Euclidean norm of the vector.
Definition at line 417 of file VectorBase.cs.
NormEuclidean
virtual double IG.Num.VectorBase.NormEuclidean get
Gets Euclidean norm of the vector.
Definition at line 426 of file VectorBase.cs.
SquaredNorm
virtual double IG.Num.VectorBase.SquaredNorm get
Squared Euclidean norm, sum of squared components.
Definition at line 435 of file VectorBase.cs.
Norm1
virtual double IG.Num.VectorBase.Norm1 get
1-norm (Manhattan norm or Taxicab norm), sum of absolute values of components.
Definition at line 448 of file VectorBase.cs.
NormInf
virtual double IG.Num.VectorBase.NormInf get
Infinity-norm, maximum absolute value of any component.
Definition at line 476 of file VectorBase.cs.
VectorStore
VectorStore IG.Num.VectorBase.VectorStore static get
Gets the matrix store for recycling auxiliary matrices.
Matrix store is created only once, on the first access.
Definition at line 920 of file VectorBase.cs.
The documentation for this class was generated from the following file:
iglib/igbase/numeric/VectorBase.cs