Doc: IGLib with source files: IG.Lib.ObjectStore< T > Class Template Reference
IG.Lib.ObjectStore< T > Class Template Reference
Object store. Objects of the specified type can be stored here for later reuse (efficiency improvement). IMPORTANT: Override IsEligible(), NotEligibleMessage() and TryGetNew() and possibly TryStore() methods in derived classes when applicable.
Public Member Functions
virtual bool IsEligible (T obj)
Returns true if the specified object is eligible for storing in this object storage, false if it is not.
virtual bool TryStore (T obj)
Stores the specified object if the object is eligible for storage in this store and if The maximal number of stored object will not be exceeded.
bool StoreEligible (T obj)
Stores the specified object in the store. WARNING: Throws ArgumentException if the specified object is not eligible for storing in this store. If the maximum number of objects would be exceeded then nothing happens.
T TryGet ()
Returns an object from this object store, or null if it is not possible to provide an eligible object. If the store contains no objects, it tries to create and return a new eligible object. Should not throw an exception.
T TryGetStored ()
Returns the last object from this object store, or null if there are no objects on it. Dose not attempt to create a new object.
T GetEligible ()
Returns a non-null object that is eligible for storing in this object store. If the store itself does not contain any objects, an object is created anew, or exception is thrown if this is not possible. IMPORTANT: TryGet returns an object or null if the object can not be returned (does not throw an exception), and TryGetStored returns an eligible object only if any are stored, otherwise returns null.
Protected Member Functions
virtual void ClearIneligible ()
Removes ineligible obects from the list.
virtual String NotEligibleMessage (object obj)
Returns a message indicating why the specified object is not eligible for storage in the current store.
virtual T TryGetNew ()
Returns a newly created object eligible for storage, or null if such an object can not be created. This method should not throw an exception.
T GetNew ()
Returns a newly xreated object eligible for storage in this object store. Exception is thrown if such an object can not be created.
Protected Attributes
object _lock = new object()
List< T > _objects = new List<T>()
Properties
object Lock [get]
int Count [get, protected set]
Gets the current number of objects.
int MaxCount [get, set]
Gets or sets the maximal number of objects that can be stored by this object store.
Properties inherited from IG.Lib.IObjectStore< T >
int Count [get]
Gets the current number of objects.
int MaxCount [get, set]
Gets or sets the maximal number of objects that can be stored by this object store.
Properties inherited from IG.Lib.ILockable
object Lock [get]
Private Attributes
int _maxCount = 0
Detailed Description
Object store. Objects of the specified type can be stored here for later reuse (efficiency improvement). IMPORTANT: Override IsEligible(), NotEligibleMessage() and TryGetNew() and possibly TryStore() methods in derived classes when applicable.
Template Parameters
T Type of objects to be stored, must be a reference type.
Type Constraints
T : class
Definition at line 69 of file UtilObjectStore.cs.
Member Function Documentation
IsEligible()
virtual bool IG.Lib.ObjectStore< T >.IsEligible (T obj) inline virtual
Returns true if the specified object is eligible for storing in this object storage, false if it is not.
Implements IG.Lib.IObjectStore< T >.
Reimplemented in IG.Num.VectorStore< T >, and IG.Num.MatrixStore< T >.
Definition at line 111 of file UtilObjectStore.cs.
Referenced by IG.Lib.ObjectStore< IVectorFunctionResults >.ClearIneligible(), IG.Lib.ObjectStore< IVectorFunctionResults >.StoreEligible(), and IG.Lib.ObjectStore< IVectorFunctionResults >.TryStore().
ClearIneligible()
virtual void IG.Lib.ObjectStore< T >.ClearIneligible () inline protected virtual
Removes ineligible obects from the list.
Definition at line 115 of file UtilObjectStore.cs.
NotEligibleMessage()
virtual String IG.Lib.ObjectStore< T >.NotEligibleMessage (object obj) inline protected virtual
Returns a message indicating why the specified object is not eligible for storage in the current store.
Definition at line 139 of file UtilObjectStore.cs.
Referenced by IG.Lib.ObjectStore< IVectorFunctionResults >.StoreEligible().
TryStore()
virtual bool IG.Lib.ObjectStore< T >.TryStore (T obj) inline virtual
Stores the specified object if the object is eligible for storage in this store and if The maximal number of stored object will not be exceeded.
Parameters
obj Object to be stored.
Returns
true if the object has actually been stored, false if not.
Implements IG.Lib.IObjectStore< T >.
Definition at line 151 of file UtilObjectStore.cs.
Referenced by IG.Num.MatrixBase.SetRandomSymmetricPositiveDefinite(), and IG.Lib.ObjectStore< IVectorFunctionResults >.StoreEligible().
StoreEligible()
bool IG.Lib.ObjectStore< T >.StoreEligible (T obj) inline
Stores the specified object in the store. WARNING: Throws ArgumentException if the specified object is not eligible for storing in this store. If the maximum number of objects would be exceeded then nothing happens.
Returns
true if the object has actually been stored, false if not.
Implements IG.Lib.IObjectStore< T >.
Definition at line 172 of file UtilObjectStore.cs.
TryGet()
T IG.Lib.ObjectStore< T >.TryGet () inline
Returns an object from this object store, or null if it is not possible to provide an eligible object. If the store contains no objects, it tries to create and return a new eligible object. Should not throw an exception.
Implements IG.Lib.IObjectStore< T >.
Definition at line 194 of file UtilObjectStore.cs.
Referenced by IG.Lib.ObjectStore< IVectorFunctionResults >.GetEligible(), and IG.Num.MatrixBase.SetRandomSymmetricPositiveDefinite().
TryGetStored()
T IG.Lib.ObjectStore< T >.TryGetStored () inline
Returns the last object from this object store, or null if there are no objects on it. Dose not attempt to create a new object.
Implements IG.Lib.IObjectStore< T >.
Definition at line 215 of file UtilObjectStore.cs.
GetEligible()
T IG.Lib.ObjectStore< T >.GetEligible () inline
Returns a non-null object that is eligible for storing in this object store. If the store itself does not contain any objects, an object is created anew, or exception is thrown if this is not possible. IMPORTANT: TryGet returns an object or null if the object can not be returned (does not throw an exception), and TryGetStored returns an eligible object only if any are stored, otherwise returns null.
Implements IG.Lib.IObjectStore< T >.
Definition at line 238 of file UtilObjectStore.cs.
TryGetNew()
virtual T IG.Lib.ObjectStore< T >.TryGetNew () inline protected virtual
Returns a newly created object eligible for storage, or null if such an object can not be created. This method should not throw an exception.
Reimplemented in IG.Num.MatrixStore< T >, IG.Num.VectorStore< T >, and IG.Num.VectorFunctionBaseGeneral.ObjectStoreResults.
Definition at line 254 of file UtilObjectStore.cs.
Referenced by IG.Lib.ObjectStore< IVectorFunctionResults >.GetNew(), and IG.Lib.ObjectStore< IVectorFunctionResults >.TryGet().
GetNew()
T IG.Lib.ObjectStore< T >.GetNew () inline protected
Returns a newly xreated object eligible for storage in this object store. Exception is thrown if such an object can not be created.
Definition at line 262 of file UtilObjectStore.cs.
Referenced by IG.Lib.ObjectStore< IVectorFunctionResults >.GetEligible().
Member Data Documentation
_lock
object IG.Lib.ObjectStore< T >._lock = new object() protected
Definition at line 72 of file UtilObjectStore.cs.
Referenced by IG.Lib.ObjectStore< IVectorFunctionResults >.GetEligible(), IG.Lib.ObjectStore< IVectorFunctionResults >.StoreEligible(), IG.Lib.ObjectStore< IVectorFunctionResults >.TryGet(), IG.Lib.ObjectStore< IVectorFunctionResults >.TryGetStored(), and IG.Lib.ObjectStore< IVectorFunctionResults >.TryStore().
_objects
List<T> IG.Lib.ObjectStore< T >._objects = new List<T>() protected
Definition at line 76 of file UtilObjectStore.cs.
Referenced by IG.Lib.ObjectStore< IVectorFunctionResults >.ClearIneligible(), IG.Lib.ObjectStore< IVectorFunctionResults >.TryGet(), IG.Lib.ObjectStore< IVectorFunctionResults >.TryGetStored(), and IG.Lib.ObjectStore< IVectorFunctionResults >.TryStore().
_maxCount
int IG.Lib.ObjectStore< T >._maxCount = 0 private
Definition at line 88 of file UtilObjectStore.cs.
Property Documentation
Lock
object IG.Lib.ObjectStore< T >.Lock get
Definition at line 74 of file UtilObjectStore.cs.
Count
int IG.Lib.ObjectStore< T >.Count get protected set
Gets the current number of objects.
Definition at line 80 of file UtilObjectStore.cs.
Referenced by IG.Lib.ObjectStore< IVectorFunctionResults >.ClearIneligible(), IG.Lib.ObjectStore< IVectorFunctionResults >.StoreEligible(), IG.Lib.ObjectStore< IVectorFunctionResults >.TryGet(), IG.Lib.ObjectStore< IVectorFunctionResults >.TryGetStored(), and IG.Lib.ObjectStore< IVectorFunctionResults >.TryStore().
MaxCount
int IG.Lib.ObjectStore< T >.MaxCount get set
Gets or sets the maximal number of objects that can be stored by this object store.
Definition at line 92 of file UtilObjectStore.cs.
Referenced by IG.Lib.ObjectStore< IVectorFunctionResults >.StoreEligible(), and IG.Lib.ObjectStore< IVectorFunctionResults >.TryStore().
The documentation for this class was generated from the following file:
iglib/igbase/utilities/UtilObjectStore.cs