Doc: IGLib with source files: IG.Num.ExampleMathClass.Nested Class Reference
IG.Num.ExampleMathClass.Nested Class Reference
A nested class that does not derive from the M class, but still statidc functions from that class can be used because it is embedded in that class.
Public Member Functions
double f (double x)
Method in which comfortable mathematic functions form the base class M are used.
double f (double x)
Method in which comfortable mathematic functions form the base class M are used.
Detailed Description
A nested class that does not derive from the M class, but still statidc functions from that class can be used because it is embedded in that class.
Definition at line 46 of file UtilMath.cs.
Member Function Documentation
f() [1/2]
double IG.Num.ExampleMathClass.Nested.f (double x) inline
Method in which comfortable mathematic functions form the base class M are used.
Parameters
x Argument of a real-valued function.
Returns
Some function of the argument.
Definition at line 52 of file UtilMath.cs.
References IG.Num.M.e, IG.Num.M.pow(), IG.Num.M.sin(), and IG.Num.M.zero.
f() [2/2]
double IG.Num.ExampleMathClass.Nested.f (double x) inline
Method in which comfortable mathematic functions form the base class M are used.
Parameters
x Argument of a real-valued function.
Returns
Some function of the argument.
Definition at line 46 of file UtilMath.cs.
References IG.Num.M.e, IG.Num.M.pow(), IG.Num.M.sin(), and IG.Num.M.zero.
The documentation for this class was generated from the following file:
IGLibCore/src/IGLib.Core/MathUtils/UtilMath.cs