Doc: IGLib with source files: IG.Lib.ObjectRegister< T > Class Template Reference
IG.Lib.ObjectRegister< T > Class Template Reference
Provides implementation of register of objects of the specified type. Also generates unique IDs for objects of this type. This class utilizes implementation of IIdentifiable and IRegisterable interfaces. Implementation notes for IRegistable: For implementation, use a static instance of this class, and an a nonstatic instance of the IdProcy class (to generate and hold object's unique ID). subclass of this clas, initialized by that static instance. Example implementation can be found in the ExampleInterfaceImplementation subclass of this class.
Public Member Functions
ObjectRegister ()
Creates an object that generates unique IDs (in the scope of the current instance) and provides registration of objects of the given type.
ObjectRegister (int startId)
Creates an object that generates unique IDs (in the scope of the current instance) with the specified first ID generated, and provides registration of objects of the given type.
void Register (T obj)
Adds the specified object to the register, using its Id property. If the object is already registered (i.e. the register already contains its Id) then
bool IsRegistered (int id)
Returns true if object with the specified ID is already registered with the current object, false otherwise.
bool IsRegistered (T obj)
Returns true if the specified object is registered with the current object, false otherwise.
T GetRegisteredInstance (int id)
Returns object that is registered with this object with the specified id, or null if such an object is not registered.
void Unregister (int id)
Unregisters object with the specified ID. WARNING: This method should only be used in finalization methods of objects that implement the IRegisterable interface.
Public Member Functions inherited from IG.Lib.IdGenerator
IdGenerator ()
Creates a new ID generator. The first ID generated will be 0. Subsequent IDs are generated by obtained by incrementing the last generated ID.
IdGenerator (int firstId)
Created a new ID generator with the specified ID generated first. Subsequent IDs are generated by obtained by incrementing the last generated ID.
int GetNewId ()
Returns a new unique command ID (process-unique over all objects of this type and its subtypes).
Protected Attributes
SortedDictionary< int, T > _register = new SortedDictionary<int, T>()
object _internalLock = new object()
Private Member Functions
void Register (int id, T obj)
Registers the specified object with the specified key (ID). Warning: this method does not check whether the specified key actually corresponds to object's ID that is obtained by the object's IIdentifiable.Id property. Therefore it is private.
Additional Inherited Members
Properties inherited from IG.Lib.IdGenerator
object Lock [get]
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
Properties inherited from IG.Lib.ILockable
object Lock [get]
Detailed Description
Provides implementation of register of objects of the specified type. Also generates unique IDs for objects of this type. This class utilizes implementation of IIdentifiable and IRegisterable interfaces. Implementation notes for IRegistable: For implementation, use a static instance of this class, and an a nonstatic instance of the IdProcy class (to generate and hold object's unique ID). subclass of this clas, initialized by that static instance. Example implementation can be found in the ExampleInterfaceImplementation subclass of this class.
Type Constraints
T : class
T : IIdentifiable
Definition at line 19 of file ObjectRegister.cs.
Constructor & Destructor Documentation
ObjectRegister() [1/2]
IG.Lib.ObjectRegister< T >.ObjectRegister () inline
Creates an object that generates unique IDs (in the scope of the current instance) and provides registration of objects of the given type.
Definition at line 26 of file ObjectRegister.cs.
ObjectRegister() [2/2]
IG.Lib.ObjectRegister< T >.ObjectRegister (int startId) inline
Creates an object that generates unique IDs (in the scope of the current instance) with the specified first ID generated, and provides registration of objects of the given type.
Parameters
startId The first ID that will be generated with this object's GetNewId() method.
Definition at line 33 of file ObjectRegister.cs.
Member Function Documentation
Register() [1/2]
void IG.Lib.ObjectRegister< T >.Register (int id, T obj) inline private
Registers the specified object with the specified key (ID). Warning: this method does not check whether the specified key actually corresponds to object's ID that is obtained by the object's IIdentifiable.Id property. Therefore it is private.
Parameters
id
obj
Definition at line 47 of file ObjectRegister.cs.
References IG.Lib.ObjectRegister< T >._internalLock, IG.Lib.ObjectRegister< T >._register, and IG.Lib.ObjectRegister< T >.IsRegistered().
Referenced by IG.Lib.ObjectRegister< T >.Register().
Register() [2/2]
void IG.Lib.ObjectRegister< T >.Register (T obj) inline
Adds the specified object to the register, using its Id property. If the object is already registered (i.e. the register already contains its Id) then
Definition at line 60 of file ObjectRegister.cs.
References IG.Lib.ObjectRegister< T >._internalLock, and IG.Lib.ObjectRegister< T >.Register().
IsRegistered() [1/2]
bool IG.Lib.ObjectRegister< T >.IsRegistered (int id) inline
Returns true if object with the specified ID is already registered with the current object, false otherwise.
Parameters
id IIdentifiable object's ID, obtained by its ID property.
Definition at line 73 of file ObjectRegister.cs.
References IG.Lib.ObjectRegister< T >._internalLock, and IG.Lib.ObjectRegister< T >._register.
Referenced by IG.Lib.ObjectRegister< T >.GetRegisteredInstance(), IG.Lib.ObjectRegister< T >.Register(), and IG.Lib.ObjectRegister< T >.Unregister().
IsRegistered() [2/2]
bool IG.Lib.ObjectRegister< T >.IsRegistered (T obj) inline
Returns true if the specified object is registered with the current object, false otherwise.
Definition at line 80 of file ObjectRegister.cs.
References IG.Lib.ObjectRegister< T >._internalLock, and IG.Lib.ObjectRegister< T >._register.
GetRegisteredInstance()
T IG.Lib.ObjectRegister< T >.GetRegisteredInstance (int id) inline
Returns object that is registered with this object with the specified id, or null if such an object is not registered.
Definition at line 93 of file ObjectRegister.cs.
References IG.Lib.ObjectRegister< T >._internalLock, IG.Lib.ObjectRegister< T >._register, and IG.Lib.ObjectRegister< T >.IsRegistered().
Unregister()
void IG.Lib.ObjectRegister< T >.Unregister (int id) inline
Unregisters object with the specified ID. WARNING: This method should only be used in finalization methods of objects that implement the IRegisterable interface.
Parameters
id
Returns
Reference of the object that has been
Definition at line 109 of file ObjectRegister.cs.
References IG.Lib.ObjectRegister< T >._internalLock, IG.Lib.ObjectRegister< T >._register, and IG.Lib.ObjectRegister< T >.IsRegistered().
Member Data Documentation
_register
SortedDictionary<int, T> IG.Lib.ObjectRegister< T >._register = new SortedDictionary<int, T>() protected
Definition at line 37 of file ObjectRegister.cs.
Referenced by IG.Lib.ObjectRegister< T >.GetRegisteredInstance(), IG.Lib.ObjectRegister< T >.IsRegistered(), IG.Lib.ObjectRegister< T >.Register(), and IG.Lib.ObjectRegister< T >.Unregister().
_internalLock
object IG.Lib.ObjectRegister< T >._internalLock = new object() protected
Definition at line 39 of file ObjectRegister.cs.
Referenced by IG.Lib.ObjectRegister< T >.GetRegisteredInstance(), IG.Lib.ObjectRegister< T >.IsRegistered(), IG.Lib.ObjectRegister< T >.Register(), and IG.Lib.ObjectRegister< T >.Unregister().
The documentation for this class was generated from the following file:
IGLibCore/src/IGLib.Core/BasicUtils/ObjectRegister.cs