Doc: IGLib with source files: IGLib.Gr3D.IGLib.Gr3D.ParametricSurfaceMeshGenerator Class Reference
IGLib.Gr3D.IGLib.Gr3D.ParametricSurfaceMeshGenerator Class Reference
Generates regular structured meshes of parametric surfaces in 3D space.
Public Member Functions
StructuredSurfaceMesh3D GenerateMesh (Func< double, double, vec3 > surface, double tStart1, double tEnd1, double tStart2, double tEnd2, int numPoints1, int numPoints2, double hrel1=1e-2, bool restrictToInterval=false)
StructuredSurfaceMesh3D GenerateMesh (Func< double, double, vec3 > surface, Func< double, double, vec3 > tangent1, Func< double, double, vec3 > tangent2, double tStart1, double tEnd1, double tStart2, double tEnd2, int numPoints1, int numPoints2)
Static Public Attributes
static ParametricSurfaceMeshGenerator Global => _global.Value
Global lazily initialized instance of the mesh generator.
Protected Member Functions
vec3 NumericalDerivative (Func< double, double, vec3 > f, double u, double v, double h, bool respectFirst, double uMin, double uMax, double vMin, double vMax, bool restrictToInterval)
Numerically computes the partial derivative of a 3D function with respect to a parameter.
Static Protected Attributes
static Lazy< ParametricSurfaceMeshGenerator > _global = new Lazy<ParametricSurfaceMeshGenerator>(() => new ParametricSurfaceMeshGenerator())
Detailed Description
Generates regular structured meshes of parametric surfaces in 3D space.
Definition at line 18 of file ParametricSurfaceMeshGenerator.cs.
Member Function Documentation
NumericalDerivative()
vec3 IGLib.Gr3D.IGLib.Gr3D.ParametricSurfaceMeshGenerator.NumericalDerivative (Func< double, double, vec3 > f, double u, double v, double h, bool respectFirst, double uMin, double uMax, double vMin, double vMax, bool restrictToInterval) inline protected
Numerically computes the partial derivative of a 3D function with respect to a parameter.
Definition at line 28 of file ParametricSurfaceMeshGenerator.cs.
GenerateMesh() [1/2]
StructuredSurfaceMesh3D IGLib.Gr3D.IGLib.Gr3D.ParametricSurfaceMeshGenerator.GenerateMesh (Func< double, double, vec3 > surface, double tStart1, double tEnd1, double tStart2, double tEnd2, int numPoints1, int numPoints2, double hrel1 = 1e-2, bool restrictToInterval = false) inline
Implements IGLib.Gr3D.IParametricSurfaceMeshGenerator.
Definition at line 53 of file ParametricSurfaceMeshGenerator.cs.
References IG.Num.vec3.Cross(), and IG.Num.vec3.Normalize().
GenerateMesh() [2/2]
StructuredSurfaceMesh3D IGLib.Gr3D.IGLib.Gr3D.ParametricSurfaceMeshGenerator.GenerateMesh (Func< double, double, vec3 > surface, Func< double, double, vec3 > tangent1, Func< double, double, vec3 > tangent2, double tStart1, double tEnd1, double tStart2, double tEnd2, int numPoints1, int numPoints2) inline
Implements IGLib.Gr3D.IParametricSurfaceMeshGenerator.
Definition at line 95 of file ParametricSurfaceMeshGenerator.cs.
References IG.Num.vec3.Cross(), and IG.Num.vec3.Normalize().
Member Data Documentation
_global
Lazy<ParametricSurfaceMeshGenerator> IGLib.Gr3D.IGLib.Gr3D.ParametricSurfaceMeshGenerator._global = new Lazy<ParametricSurfaceMeshGenerator>(() => new ParametricSurfaceMeshGenerator()) static protected
Definition at line 20 of file ParametricSurfaceMeshGenerator.cs.
Global
ParametricSurfaceMeshGenerator IGLib.Gr3D.IGLib.Gr3D.ParametricSurfaceMeshGenerator.Global => _global.Value static
Global lazily initialized instance of the mesh generator.
Definition at line 23 of file ParametricSurfaceMeshGenerator.cs.
The documentation for this class was generated from the following file:
IGLibGraphics3D/src/IGLib.Graphics3D/Graphics3D/Meshing/TubularSurface/ParametricSurfaceMeshGenerator.cs