Doc: IGLib with source files: IG.Num.Func2dBasePlain_ToConsider Class Reference
IG.Num.Func2dBasePlain_ToConsider Class Reference abstract
Base class for scalar functions of 2 variables.
Public Member Functions
Func2dBasePlain_ToConsider ()
Constructor.
abstract double Value (double x, double y)
Calculates and returns value of the current 2D scalar function.
virtual double Value (vec2 parameters)
Calculates and returns value of the current 2D scalar function.
abstract void Gradient (double x, double y, out double gradx, out double grady)
Calculates gradient of the current 2D scalar function and returns its components through the specified output variables.
virtual vec2 Gradient (vec2 parameters)
Calculates and returns gradient of the current 2D scalar function.
abstract void Hessian (double x, double y, out double dxx, out double dyy, out double dxy)
Calculates Hessian of the current 2D scalar function and returns its component through the specified output variables.
virtual mat2 Hessian (vec2 parameters)
Calculates and returns Hessian of the current 2D scalar function and returns it (in the form of a mat2 struct).
Properties
virtual bool ValueDefined [get, protected set]
Whether calculation of function value is defined. Defaulet is true.
virtual bool GradientDefined [get, protected set]
Whether calculation of functio ngradient is defined. Default is false.
virtual bool HessianDefined [get, protected set]
Whether calculation of function Hessian is defined. Default is false.
Properties inherited from IG.Num.IFunc2d
bool ValueDefined [get]
Whether calculation of function value is defined.
bool GradientDefined [get]
Whether calculation of function ngradient is defined.
bool HessianDefined [get]
Whether calculation of function Hessian is defined.
Private Attributes
bool _valueDefined = true
bool _gradientDefined = false
bool _hessianDefined = false
Detailed Description
Base class for scalar functions of 2 variables.
This willl be base class for most of other classes that implement the IFunc2d interface. It provides a set of useful static methods.
TODO:
Consider whether this class is really needed. Maybe Func2dBase is enough. That class contains additional methods that implement the IScalarFunctionUntransformed interface, and maybe this does not justify implementation of another class just to be simpler.
$A Igor Apr09;
Definition at line 645 of file Function2d.cs.
Constructor & Destructor Documentation
Func2dBasePlain_ToConsider()
IG.Num.Func2dBasePlain_ToConsider.Func2dBasePlain_ToConsider () inline
Constructor.
Definition at line 651 of file Function2d.cs.
Member Function Documentation
Value() [1/2]
abstract double IG.Num.Func2dBasePlain_ToConsider.Value (double x, double y) pure virtual
Calculates and returns value of the current 2D scalar function.
Parameters
x First parameter.
y Second parameter.
Implements IG.Num.IFunc2d.
Referenced by IG.Num.Func2dBasePlain_ToConsider.Value().
Value() [2/2]
virtual double IG.Num.Func2dBasePlain_ToConsider.Value (vec2 parameters) inline virtual
Calculates and returns value of the current 2D scalar function.
Parameters
parameters Vector of function parameters (in form of the Value) struct.
Returns
Function value.
Implements IG.Num.IFunc2d.
Definition at line 697 of file Function2d.cs.
References IG.Num.Func2dBasePlain_ToConsider.Value(), IG.Num.vec2.x, and IG.Num.vec2.y.
Gradient() [1/2]
abstract void IG.Num.Func2dBasePlain_ToConsider.Gradient (double x, double y, out double gradx, out double grady) pure virtual
Calculates gradient of the current 2D scalar function and returns its components through the specified output variables.
Parameters
x First parameter.
y Second parameter.
gradx First component of the returned gradient.
grady Second component of the returned gradient.
Implements IG.Num.IFunc2d.
Referenced by IG.Num.Func2dBasePlain_ToConsider.Gradient().
Gradient() [2/2]
virtual vec2 IG.Num.Func2dBasePlain_ToConsider.Gradient (vec2 parameters) inline virtual
Calculates and returns gradient of the current 2D scalar function.
Parameters
parameters Vector of parameters (in form of the vec2 struct)
<returnreturns>Gradient of the current 2D scalar function (in form of the vec2 struct)</returnreturns>
Implements IG.Num.IFunc2d.
Definition at line 713 of file Function2d.cs.
References IG.Num.Func2dBasePlain_ToConsider.Gradient(), IG.Num.vec2.x, and IG.Num.vec2.y.
Hessian() [1/2]
abstract void IG.Num.Func2dBasePlain_ToConsider.Hessian (double x, double y, out double dxx, out double dyy, out double dxy) pure virtual
Calculates Hessian of the current 2D scalar function and returns its component through the specified output variables.
Parameters
x First parameter.
y Second parameter.
dxx Component 1-1 of the calculated Hessian.
dyy Component 2-2 of the calculated Hessian.
dxy Component 1-2 of the calculated Hessian.
Implements IG.Num.IFunc2d.
Referenced by IG.Num.Func2dBasePlain_ToConsider.Hessian().
Hessian() [2/2]
virtual mat2 IG.Num.Func2dBasePlain_ToConsider.Hessian (vec2 parameters) inline virtual
Calculates and returns Hessian of the current 2D scalar function and returns it (in the form of a mat2 struct).
Implements IG.Num.IFunc2d.
Definition at line 732 of file Function2d.cs.
References IG.Num.Func2dBasePlain_ToConsider.Hessian(), IG.Num.vec2.x, and IG.Num.vec2.y.
Member Data Documentation
_valueDefined
bool IG.Num.Func2dBasePlain_ToConsider._valueDefined = true private
Definition at line 657 of file Function2d.cs.
_gradientDefined
bool IG.Num.Func2dBasePlain_ToConsider._gradientDefined = false private
Definition at line 667 of file Function2d.cs.
_hessianDefined
bool IG.Num.Func2dBasePlain_ToConsider._hessianDefined = false private
Definition at line 677 of file Function2d.cs.
Property Documentation
ValueDefined
virtual bool IG.Num.Func2dBasePlain_ToConsider.ValueDefined get protected set
Whether calculation of function value is defined. Defaulet is true.
Definition at line 662 of file Function2d.cs.
GradientDefined
virtual bool IG.Num.Func2dBasePlain_ToConsider.GradientDefined get protected set
Whether calculation of functio ngradient is defined. Default is false.
Definition at line 672 of file Function2d.cs.
HessianDefined
virtual bool IG.Num.Func2dBasePlain_ToConsider.HessianDefined get protected set
Whether calculation of function Hessian is defined. Default is false.
Definition at line 682 of file Function2d.cs.
The documentation for this class was generated from the following file:
iglib/igbase/numeric/geometry/Function2d.cs