Doc: IGLib with source files: IG.Num.ScalarFunctionQuadratic Class Reference
IG.Num.ScalarFunctionQuadratic Class Reference
Quadratic scalar function of vector variable. Function is evaluated according to q(x) = (1/2)*x^T*G*x + b^T*x + c where x is vector of parameters, G is constant Hessian matrix, b is vector of linear coefficients (gradient at x=0) and c is the scalar term (function value at x=0).
Public Member Functions
ScalarFunctionQuadratic (IMatrix hessian, IVector gradient0, double scalarTerm)
Creation of a quadratic scalar function. WARNING: Matrix argument is interpreted as Hessian, i.e. twice the matrix of quadratic coefficients.
override double Value (IVector parameters)
Returns the value of this function at the specified parameter.
override void GradientPlain (IVector parameters, IVector gradient)
Calculates first order derivatives (gradient) of this function at the specified parameters. WARNING: Plain function, does not check consistency of arguments.
override void HessianPlain (IVector parameters, IMatrix hessian)
Calculates the second derivative (Hessian matrix) of this function at the specified parameters. WARNING: Plain function, does not check consistency of arguments.
Public Member Functions inherited from IG.Num.ScalarFunctionUntransformedBase
virtual void Evaluate (IScalarFunctionResults data)
Evaluates whatever needs to be evaluated and stores the results on the specified storage object.
virtual void Gradient (IVector parameters, ref IVector gradient)
Calculates first order derivatives (gradient) of this function at the specified parameters.
virtual void Hessian (IVector parameters, ref IMatrix hessian)
Calculates the second derivative (Hessian matrix) of this function at the specified parameters.
virtual void NumericalGradientForwardPlain (IVector x, IVector stepSizes, IVector gradient)
Calculates numerical derivatives (gradient) of this function. Forward difference formula is normally used.
void NumericalGradientForward (IVector x, IVector stepSizes, ref IVector gradient)
Calculates numerical derivatives (gradient) of this function. Forward difference formula is normally used.
void NumericalGradientForward (IVector x, double stepSize, ref IVector gradient)
Calculates numerical derivatives (gradient) of this function. Forward difference formula is used.
virtual void NumericalGradientCentralPlain (IVector x, IVector stepSizes, IVector gradient)
Calculates numerical derivatives (gradient) of this function. Forward difference formula is normally used.
void NumericalGradientCentral (IVector x, IVector stepSizes, ref IVector gradient)
Calculates numerical derivatives (gradient) of this function. Forward difference formula is normally used.
void NumericalGradientCentral (IVector x, double stepSize, ref IVector gradient)
Calculates numerical derivatives (gradient) of this function. Forward difference formula is normally used.
virtual void NumericalHessianForwardPlain (IVector x, IVector stepSizes, IVector aux, IMatrix hessian)
Calculates numerical second derivatives (Hessian) of this function. Forward difference formula is normally used. WARNING: Dimensions of vector arguments must match. This function does not check for consistency of argument dimensions. REMARK: Vector x is changed during operation, but is set to initial value before function returns (unless an exception is thrown).
virtual void NumericalHessianForward (IVector x, IVector stepSizes, ref IVector aux, ref IMatrix hessian)
Calculates numerical second derivatives (Hessian) of this function. Forward difference formula is normally used. REMARK: if auxiliary vector or result matrix don't have correct dimensions or they are not allocated, then allocation is performed first. REMARK: Vector x is changed during operation, but is set to initial value before function returns (unless an exception is thrown).
virtual void NumericalHessianForward (IVector x, double stepSize, ref IVector aux, ref IMatrix hessian)
Calculates numerical second derivatives (Hessian) of this function. Forward difference formula is normally used. REMARK: if auxiliary vector or result matrix don't have correct dimensions or they are not allocated, then allocation is performed first. REMARK: Vector x is changed during operation, but is set to initial value before function returns (unless an exception is thrown).
virtual void NumericalHessianCentralPlain (IVector x, IVector stepSizes, IVector aux1, IVector aux2, IMatrix hessian)
Calculates numerical second derivatives (Hessian) of this function. Forward difference formula is normally used. WARNING: Dimensions of vector arguments must match. This function does not check for consistency of argument dimensions. REMARK: Vector x is changed during operation, but is set to initial value before function returns (unless an exception is thrown).
virtual void NumericalHessianCentral (IVector x, IVector stepSizes, ref IVector aux1, ref IVector aux2, ref IMatrix hessian)
Calculates numerical second derivatives (Hessian) of this function. Forward difference formula is normally used. REMARK: if auxiliary vector or result matrix don't have correct dimensions or they are not allocated, then allocation is performed first. REMARK: Vector x is changed during operation, but is set to initial value before function returns (unless an exception is thrown).
virtual void NumericalHessianCentral (IVector x, double stepSize, ref IVector aux1, ref IVector aux2, ref IMatrix hessian)
Calculates numerical second derivatives (Hessian) of this function. Forward difference formula is normally used. REMARK: if auxiliary vector or result matrix don't have correct dimensions or they are not allocated, then allocation is performed first. REMARK: Vector x is changed during operation, but is set to initial value before function returns (unless an exception is thrown).
virtual void NumericalHessianCentralPlain (IVector x, IVector stepSizes, IVector aux1, IVector aux2, IMatrix hessian, bool useAnalyticalGradient)
Calculates numerical second derivatives (Hessian) of this function by the central difference formula. WARNING: Dimensions of vector arguments must match. This function does not check for consistency of argument dimensions. REMARK: Vector x is changed during operation, but is set to initial value before function returns (unless an exception is thrown).
virtual void NumericalHessianCentral (IVector x, IVector stepSizes, ref IVector aux1, ref IVector aux2, ref IMatrix hessian, bool useAnalyticalGradient)
Calculates numerical second derivatives (Hessian) of this function by the central difference formula. REMARK: if auxiliary vector or result matrix don't have correct dimensions or they are not allocated, then allocation is performed first. REMARK: Vector x is changed during operation, but is set to initial value before function returns (unless an exception is thrown).
virtual void NumericalHessianCentral (IVector x, double stepSize, ref IVector aux1, ref IVector aux2, ref IMatrix hessian, bool useAnalyticalGradient)
Calculates numerical second derivatives (Hessian) of this function. Forward difference formula is normally used. REMARK: if auxiliary vector or result matrix don't have correct dimensions or they are not allocated, then allocation is performed first. REMARK: Vector x is changed during operation, but is set to initial value before function returns (unless an exception is thrown).
void TestSpeed (IVector parameters, int numEvaluations, bool randomPerturbations, double relativePerturbationSize, bool calcValue, bool calcGradient, bool calcHessian, bool writeLastResult)
Tests speed of evaluation of the current scalar function and writes results to the console.
void TestGradient (IVector parameters, IVector stepSizes, int stepReductionFactor, int numStepReductions, bool checkNumerical, bool writeErrorComponents, bool writeGradientComponents)
Tests the calculation of gradients of the current scalar function.
void TestGradient (IVector parameters, IVector stepSizes, int stepReductionFactor, int numStepReductions, bool checkNumerical, bool writeErrorComponents, bool writeGradientComponents, bool useCentralDifference)
Tests the calculation of gradients of the current scalar function.
void TestHessian (IVector parameters, IVector stepSizes, int stepReductionFactor, int numStepReductions, bool checkNumerical, bool writeErrorComponents, bool writeHessianComponents)
Tests the calculation of Hessians of the current scalar function.
void TestHessian (IVector parameters, IVector stepSizes, int stepReductionFactor, int numStepReductions, bool checkNumerical, bool writeErrorComponents, bool writeHessianComponents, bool useCentralDifference)
Tests the calculation of Hessians of the current scalar function.
void Test (IVector from, IVector to, int numProbes, IVector stepSizes, double tolerance, bool testDerivatives, bool testSecondDerivatives, bool printDifferences, bool printResults)
Performs numerical tests on the function, with output written to the console. Derivatives and second derivatives are tested and compared to numerical derivatives.
void Test (IVector from, IVector to, int numProbes, IVector stepSizes, double tolerance)
Performs numerical tests on the function, with output written to the console. Derivatives and second derivatives are tested and compared to numerical derivatives. This method tests first and second order derivatives, prints differences between analytical and numerical values to the console, and prints reports where absolute differences exceed rolerance.
void Test (IVector from, IVector to, int numProbes, double stepSize, double tolerance, bool testDerivatives, bool testSecondDerivatives, bool printDifferences, bool printResults)
Performs numerical tests on the function, with output written to the console. Derivatives and second derivatives are tested and compared to numerical derivatives.
void Test (IVector from, IVector to, int numProbes, double stepSize, double tolerance)
Performs numerical tests on the function, with output written to the console. Derivatives and second derivatives are tested and compared to numerical derivatives.
Static Public Member Functions
static ScalarFunctionQuadratic ExampleFunction2d ()
Creates and returns quadratic scalar function in 2D.
static ScalarFunctionQuadratic ExampleFunctionDiagonal2d ()
Creates and returns quadratic scalar function with diagonal Hessian.
static ScalarFunctionQuadratic ExampleFunctionPureQuadratic2d ()
Creates and returns quadratic scalar function with only quadratic terms.
static ScalarFunctionQuadratic ExampleFunctionDiagonalPureQuadratic2d ()
Creates and returns quadratic function with diagonal Hessian.
static int GetNumConstants (int dim)
Returns the number of constants that specify the quadratic function of the specified dimension.
Properties
int NumActualConstants [get]
Gets the number of constants that define the current function. If e.g. the matrix coefficient or the vector coefficient is not defined then the corresponding constants are not counted.
IMatrix HessianMatrix [get, protected set]
Twice the matrix of quadratic coefficients (Hessian matrix).
IVector Gradient0 [get, protected set]
Vector of linear coefficients (equal to gradient of the function at x=0).
double ScalarTerm [get, protected set]
Scalar additive constant.
override bool ValueDefined [get, protected set]
Tells whether value of the function is defined by implementation. Always true for this case.
override bool GradientDefined [get, protected set]
Tells whether the first derivative is defined for this function (by implementation, not mathematically)
override bool HessianDefined [get, protected set]
Tells whether the second derivative is defined for this function (by implementation, not mathematically)
Properties inherited from IG.Num.ScalarFunctionUntransformedBase
virtual string Name [get, set]
Returns a short name of thecurrent function.
virtual string Description [get, set]
Returns a short description of the current function.
abstract bool ValueDefined [get, protected set]
Tells whether value of the function is defined by implementation.
abstract bool GradientDefined [get, protected set]
Tells whether the first derivative is defined for this function (by implementation, not mathematically)
abstract bool HessianDefined [get, protected set]
Tells whether the second derivative is defined for this function (by implementation, not mathematically)
Properties inherited from IG.Num.IScalarFunctionUntransformed
string Name [get]
Returns a short name of the function.
string Description [get]
Returns a short description of the function.
bool ValueDefined [get]
Tells whether value of the function is defined by implementation.
bool GradientDefined [get]
Tells whether the first derivative is defined for this function (by implementation, not mathematically)
bool HessianDefined [get]
Tells whether the second derivative is defined for this function (by implementation, not mathematically)
Private Member Functions
ScalarFunctionQuadratic ()
Private Attributes
IMatrix _G
IVector _b
double _c
Additional Inherited Members
Protected Attributes inherited from IG.Num.ScalarFunctionUntransformedBase
string _name
string _description
Detailed Description
Quadratic scalar function of vector variable. Function is evaluated according to q(x) = (1/2)*x^T*G*x + b^T*x + c where x is vector of parameters, G is constant Hessian matrix, b is vector of linear coefficients (gradient at x=0) and c is the scalar term (function value at x=0).
When quadratic function is created or its parameters set, the Matrix parameter of the function is interpreted as Hessian, i.e. twice the matrix of quadratic coefficients.
$A Igor xx Dec10;
Definition at line 312 of file FunctionScalarExamples.cs.
Constructor & Destructor Documentation
ScalarFunctionQuadratic() [1/2]
IG.Num.ScalarFunctionQuadratic.ScalarFunctionQuadratic () inline private
Definition at line 317 of file FunctionScalarExamples.cs.
Referenced by IG.Num.ScalarFunctionQuadratic.ExampleFunction2d(), IG.Num.ScalarFunctionQuadratic.ExampleFunctionDiagonal2d(), IG.Num.ScalarFunctionQuadratic.ExampleFunctionDiagonalPureQuadratic2d(), and IG.Num.ScalarFunctionQuadratic.ExampleFunctionPureQuadratic2d().
ScalarFunctionQuadratic() [2/2]
IG.Num.ScalarFunctionQuadratic.ScalarFunctionQuadratic (IMatrix hessian, IVector gradient0, double scalarTerm) inline
Creation of a quadratic scalar function. WARNING: Matrix argument is interpreted as Hessian, i.e. twice the matrix of quadratic coefficients.
Parameters
hessian Matrix of second derivatives (Hessian). Can be null (in this case function degrades to linear function).
gradient0 Vector of linear coefficients - gradient of quadratic function at x = 0. Can be null.
scalarTerm Constant term.
Definition at line 327 of file FunctionScalarExamples.cs.
References IG.Num.ScalarFunctionQuadratic.Gradient0, IG.Num.ScalarFunctionQuadratic.HessianMatrix, and IG.Num.ScalarFunctionQuadratic.ScalarTerm.
Member Function Documentation
ExampleFunction2d()
static ScalarFunctionQuadratic IG.Num.ScalarFunctionQuadratic.ExampleFunction2d () inline static
Creates and returns quadratic scalar function in 2D.
Definition at line 339 of file FunctionScalarExamples.cs.
References IG.Num.ScalarFunctionQuadratic.ScalarFunctionQuadratic().
ExampleFunctionDiagonal2d()
static ScalarFunctionQuadratic IG.Num.ScalarFunctionQuadratic.ExampleFunctionDiagonal2d () inline static
Creates and returns quadratic scalar function with diagonal Hessian.
Returns
Definition at line 357 of file FunctionScalarExamples.cs.
References IG.Num.ScalarFunctionQuadratic.ScalarFunctionQuadratic().
ExampleFunctionPureQuadratic2d()
static ScalarFunctionQuadratic IG.Num.ScalarFunctionQuadratic.ExampleFunctionPureQuadratic2d () inline static
Creates and returns quadratic scalar function with only quadratic terms.
Returns
Definition at line 374 of file FunctionScalarExamples.cs.
References IG.Num.ScalarFunctionQuadratic.ScalarFunctionQuadratic().
ExampleFunctionDiagonalPureQuadratic2d()
static ScalarFunctionQuadratic IG.Num.ScalarFunctionQuadratic.ExampleFunctionDiagonalPureQuadratic2d () inline static
Creates and returns quadratic function with diagonal Hessian.
Returns
Definition at line 392 of file FunctionScalarExamples.cs.
References IG.Num.ScalarFunctionQuadratic.ScalarFunctionQuadratic().
GetNumConstants()
static int IG.Num.ScalarFunctionQuadratic.GetNumConstants (int dim) inline static
Returns the number of constants that specify the quadratic function of the specified dimension.
Parameters
dim Dimension of the space in which quadratic function is defined.
Definition at line 421 of file FunctionScalarExamples.cs.
Referenced by IG.Num.SampledDataSet.CreateExampleQuadratic().
Value()
override double IG.Num.ScalarFunctionQuadratic.Value (IVector parameters) inline
Returns the value of this function at the specified parameter.
Implements IG.Num.IScalarFunctionUntransformed.
Definition at line 480 of file FunctionScalarExamples.cs.
References IG.Num.ScalarFunctionQuadratic.Gradient0, IG.Num.ScalarFunctionQuadratic.HessianMatrix, IG.Num.MatrixBase.Multiply(), IG.Num.VectorBase.ScalarProduct(), and IG.Num.ScalarFunctionQuadratic.ScalarTerm.
GradientPlain()
override void IG.Num.ScalarFunctionQuadratic.GradientPlain (IVector parameters, IVector gradient) inline
Calculates first order derivatives (gradient) of this function at the specified parameters. WARNING: Plain function, does not check consistency of arguments.
Parameters
parameters Vector of parameters where derivatives are evaluated.
gradient Vector where first order derivatives (the gradient) are stored.
Implements IG.Num.IScalarFunctionUntransformed.
Definition at line 503 of file FunctionScalarExamples.cs.
References IG.Num.VectorBase.Add(), IG.Num.ScalarFunctionQuadratic.Gradient0, IG.Num.ScalarFunctionQuadratic.HessianMatrix, IG.Num.MatrixBase.MultiplyPlain(), and IG.Num.IVector< T >.SetZero().
HessianPlain()
override void IG.Num.ScalarFunctionQuadratic.HessianPlain (IVector parameters, IMatrix hessian) inline
Calculates the second derivative (Hessian matrix) of this function at the specified parameters. WARNING: Plain function, does not check consistency of arguments.
Parameters
parameters Vector of parameters where derivatives are evaluated.
hessian Matrix where second derivatives (Hessian matrix) are stored.
Implements IG.Num.IScalarFunctionUntransformed.
Definition at line 527 of file FunctionScalarExamples.cs.
References IG.Num.IMatrix< ComponentType >.ColumnCount, IG.Num.ScalarFunctionQuadratic.HessianMatrix, and IG.Num.IMatrix< ComponentType >.RowCount.
Member Data Documentation
_G
IMatrix IG.Num.ScalarFunctionQuadratic._G private
Definition at line 411 of file FunctionScalarExamples.cs.
_b
IVector IG.Num.ScalarFunctionQuadratic._b private
Definition at line 413 of file FunctionScalarExamples.cs.
_c
double IG.Num.ScalarFunctionQuadratic._c private
Definition at line 415 of file FunctionScalarExamples.cs.
Property Documentation
NumActualConstants
int IG.Num.ScalarFunctionQuadratic.NumActualConstants get
Gets the number of constants that define the current function. If e.g. the matrix coefficient or the vector coefficient is not defined then the corresponding constants are not counted.
Definition at line 430 of file FunctionScalarExamples.cs.
HessianMatrix
IMatrix IG.Num.ScalarFunctionQuadratic.HessianMatrix get protected set
Twice the matrix of quadratic coefficients (Hessian matrix).
Definition at line 454 of file FunctionScalarExamples.cs.
Referenced by IG.Num.ScalarFunctionQuadratic.GradientPlain(), IG.Num.ScalarFunctionQuadratic.HessianPlain(), IG.Num.ScalarFunctionQuadratic.ScalarFunctionQuadratic(), and IG.Num.ScalarFunctionQuadratic.Value().
Gradient0
IVector IG.Num.ScalarFunctionQuadratic.Gradient0 get protected set
Vector of linear coefficients (equal to gradient of the function at x=0).
Definition at line 461 of file FunctionScalarExamples.cs.
Referenced by IG.Num.ScalarFunctionQuadratic.GradientPlain(), IG.Num.ScalarFunctionQuadratic.ScalarFunctionQuadratic(), and IG.Num.ScalarFunctionQuadratic.Value().
ScalarTerm
double IG.Num.ScalarFunctionQuadratic.ScalarTerm get protected set
Scalar additive constant.
Definition at line 468 of file FunctionScalarExamples.cs.
Referenced by IG.Num.ScalarFunctionQuadratic.ScalarFunctionQuadratic(), and IG.Num.ScalarFunctionQuadratic.Value().
ValueDefined
override bool IG.Num.ScalarFunctionQuadratic.ValueDefined get protected set
Tells whether value of the function is defined by implementation. Always true for this case.
Definition at line 494 of file FunctionScalarExamples.cs.
GradientDefined
override bool IG.Num.ScalarFunctionQuadratic.GradientDefined get protected set
Tells whether the first derivative is defined for this function (by implementation, not mathematically)
Definition at line 517 of file FunctionScalarExamples.cs.
HessianDefined
override bool IG.Num.ScalarFunctionQuadratic.HessianDefined get protected set
Tells whether the second derivative is defined for this function (by implementation, not mathematically)
Definition at line 546 of file FunctionScalarExamples.cs.
The documentation for this class was generated from the following file:
iglib/igbase/numeric/FunctionScalarExamples.cs