Doc: IGLib with source files: IGLib.Core.FromStringTypeConverterViaIConvertible Class Reference
IGLib.Core.FromStringTypeConverterViaIConvertible Class Reference
Converts a string to a specific type using IConvertible and invariant culture. Only works with types that implement IConvertible.
Public Member Functions
TargetType ConvertTyped< TargetType > (string source)
bool TryConvertTyped< TargetType > (string source, out TargetType target)
object Convert (object source, Type targetType)
bool TryConvert (object source, out object target, Type targetType)
Public Member Functions inherited from IGLib.Core.ISingleSourceTypeConverter< string >
TargetType ConvertTyped< TargetType > (SourceType source)
bool TryConvertTyped< TargetType > (SourceType source, out TargetType target)
object Convert (object source, Type targetType)
bool TryConvert (object source, out object target, Type targetType)
Public Attributes
Type SourceType => typeof(string)
Additional Inherited Members
Properties inherited from IGLib.Core.ISingleSourceTypeConverter< string >
Type SourceType [get]
Detailed Description
Converts a string to a specific type using IConvertible and invariant culture. Only works with types that implement IConvertible.
Definition at line 11 of file FromStringTypeConverterViaIConvertible.cs.
Member Function Documentation
ConvertTyped< TargetType >()
TargetType IGLib.Core.FromStringTypeConverterViaIConvertible.ConvertTyped< TargetType > (string source) inline
Definition at line 15 of file FromStringTypeConverterViaIConvertible.cs.
References IGLib.Core.FromStringTypeConverterViaIConvertible.TryConvertTyped< TargetType >().
TryConvertTyped< TargetType >()
bool IGLib.Core.FromStringTypeConverterViaIConvertible.TryConvertTyped< TargetType > (string source, out TargetType target) inline
Definition at line 23 of file FromStringTypeConverterViaIConvertible.cs.
Referenced by IGLib.Core.FromStringTypeConverterViaIConvertible.ConvertTyped< TargetType >().
Convert()
object IGLib.Core.FromStringTypeConverterViaIConvertible.Convert (object source, Type targetType) inline
Definition at line 40 of file FromStringTypeConverterViaIConvertible.cs.
References IGLib.Core.FromStringTypeConverterViaIConvertible.TryConvert().
TryConvert()
bool IGLib.Core.FromStringTypeConverterViaIConvertible.TryConvert (object source, out object target, Type targetType) inline
Definition at line 48 of file FromStringTypeConverterViaIConvertible.cs.
Referenced by IGLib.Core.FromStringTypeConverterViaIConvertible.Convert().
Member Data Documentation
SourceType
Type IGLib.Core.FromStringTypeConverterViaIConvertible.SourceType => typeof(string)
Definition at line 13 of file FromStringTypeConverterViaIConvertible.cs.
The documentation for this class was generated from the following file:
IGLibGraphics3D/src/IGLib.Graphics3D/other/TypeConversion/SingleConverters/SpecificConverters/FromStringTypeConverterViaIConvertible.cs