Doc: IGLib with source files: IG.Num.FunctionPolynomial Class Reference
IG.Num.FunctionPolynomial Class Reference
Polynomial real functions of one variable.
Public Member Functions
override bool HigherDerivativeDefined (int order)
Tells whether the derivative of the given order is defined for this function (by implementation, not mathematically)
Public Member Functions inherited from IG.Num.RealFunction
RealFunction (DlgFunctionValue valueDelegate)
Constructs a new function where delegates are provided for calculation of function valu.
RealFunction (DlgFunctionValue valueDelegate, DlgFunctionValue derivativeDelegate)
Constructs a new function where delegates are provided for calculation of function valu and first derivative.
RealFunction (DlgFunctionValue valueDelegate, DlgFunctionValue derivativeDelegate, DlgFunctionValue secondDerivativeDelegate)
RealFunction (DlgFunctionValue valueDelegate, DlgFunctionValue derivativeDelegate, DlgFunctionValue secondDerivativeDelegate, DlgFunctionValue integralDelegate)
Constructs a new function where delegates are provided for calculation of function value, derivatives and integral.
RealFunction (DlgFunctionValue valueDelegate, DlgFunctionValue derivativeDelegate, DlgFunctionValue secondDerivativeDelegate, DlgFunctionValue integralDelegate, DlgFunctionValue inverseDelegate)
Constructs a new function where delegates are provided for calculation of function value, derivatives, integral and inverse.
RealFunction (DlgFunctionValue valueDelegate, DlgFunctionValue derivativeDelegate, DlgFunctionValue secondDerivativeDelegate, DlgFunctionHigherDerivative higherDerivativeDelegate, DlgFunctionValue integralDelegate, DlgFunctionValue inverseDelegate)
Constructs a new function where delegates are provided for calculation of function value, derivatives, integral and inverse.
RealFunction CloneFunction ()
object Clone ()
double TransformedArgument (double t)
double InverseTransformedArgument (double x)
virtual void SetTransformationParameters (double kx, double sx, double ky, double sy)
Sets parameters of the affine transformation parameters for both co-ordinates.
virtual void SetXTransformationParameters (double kx, double sx)
Sets parameters of the affine transformation parameters for independent variable.
override double Value (double x)
Returns the value of this function at the specified parameter.
override double Derivative (double x)
Returns the first derivative of this function at the specified parameter.
override double Derivative (double x, int order)
Returns the derivative of the given order of this function at the specified parameter.
override bool HigherDerivativeDefined (int order)
Tells whether the derivative of the given order is defined for this function (by implementation, not mathematically). Returns true if either the internal variable indicates true or the appropriate delegate is non-null.
override double SecondDerivative (double x)
Returns the second derivative of the given order of this function at the specified arameter.
override double Integral (double x)
Returns definite integral of the current function from 0 to the function argument.
override double Inverse (double y)
Returns value of the inverse of the current function at the specified value of dependent variable.
Public Member Functions inherited from IG.Num.RealFunctionBase
void Tabulate (double from, double to, int numPoints)
Tabulates the current function and its first and second derivatives (when available) on the specified interval, in the specified number of points.
void Tabulate (double from, double to, int numPoints, bool printDerivatives)
Tabulates the current function and its first and eventually second derivatives (when available) on the specified interval, in the specified number of points.
void Tabulate (double from, double to, int numPoints, bool printDerivatives, bool printSecondDerivatives)
Tabulates the current function and eventually its first and second derivatives (when available) on the specified interval, in the specified number of points.
virtual double NumericalIntegral (double from, double to, int numintervals)
Calculates numerical integral of this function. Simpson's formula is used.
virtual double NumericalDerivative (double x, double stepsize)
Calculates numerical derivative of this function. Central difference formula is used.
virtual double NumericalSecondDerivative (double x, double stepsize)
Calculates numerical second order derivative of this function. Central difference formula is used.
virtual void Test ()
Performs numerical tests with parameters adjusted for specific function. This function can be be overridden in derived classes, however its current implementation may be relatively well suited for most weighting and basic functions.
virtual void Test (double from, double to, int numProbes, double stepSize, double tolerance)
Performs some numerical tests on the current function, such as correctness of first and second derivatives, integral and inverse of the function. Results are written to the standard output. Whenever a numerical result does not match the corresponding analytical value calculated by the function, a visible notification is written.
override string ToString ()
Properties
int Order [get]
Returns order of the polynomial.
override bool ValueDefined [get]
override bool DerivativeDefined [get]
override bool SecondDerivativeDefined [get]
override bool IntegralDefined [get]
override bool InverseDefined [get]
Properties inherited from IG.Num.RealFunction
override RealFunctionBase DerivativeFunction [get]
Returns a function that represents a derivative of the current function.
override RealFunctionBase InverseFunction [get]
Returns a function that represents inverse of the current function.
override RealFunctionBase IntegralFunction [get]
Returns a function that represents definite integral of the current function from 0 to function argument.
bool DoTransform [get, private set]
Whether or not transformation (stretch/shift) is applied to the reference function, either in x or to y. Setter sets value both for transformation in X and Y direction.
bool TransformX [get, private set]
Whether or not reference function is stretched/shifted in x direction.
bool TransformY [get, private set]
Whether or not reference function is stretched/shifted in x direction.
double ScaleX [get, set]
Gets or sets the scaling factor for independent variable.
double ShiftX [get, set]
Gets or sets the shift of independent variable.
double ScaleY [get, set]
Gets or sets the scaling factor for function value.
double ShiftY [get, set]
Gets or sets the shift for function value.
override bool ValueDefined [get, set]
Tells whether value of the function is defined by implementation. Getter returns true if internal flag is set OR appropriate delegate is defined. Setter sets the internal flag (i.e. delegate must also be set to null if getter should return false).
override bool DerivativeDefined [get, set]
Tells whether the first derivative is defined for this function (by implementation, not mathematically). Getter returns true if internal flag is set OR appropriate delegate is defined. Setter sets the internal flag (i.e. delegate must also be set to null if getter should return false).
override bool SecondDerivativeDefined [get, set]
Tells whether the second derivative is defined for this function (by implementation, not mathematically). Getter returns true if internal flag is set OR appropriate delegate is defined. Setter sets the internal flag (i.e. delegate must also be set to null if getter should return false).
override bool IntegralDefined [get, set]
Indicates whether integral is defined for this function (w.r. implementation). Getter returns true if internal flag is set OR appropriate delegate is defined. Setter sets the internal flag (i.e. delegate must also be set to null if getter should return false).
override bool InverseDefined [get, set]
Indicates whether inverse is defined for this function (w.r. implementation). Getter returns true if internal flag is set OR appropriate delegate is defined. Setter sets the internal flag (i.e. delegate must also be set to null if getter should return false).
Properties inherited from IG.Num.RealFunctionBase
virtual string Name [get, set]
Returns a short name of thecurrent function.
virtual string Description [get, set]
Returns a short description of the current function.
virtual RealFunctionBase DerivativeFunction [get]
Returns a function object that represents a derivative of this function. Returns null if this is not implemented.
virtual RealFunctionBase IntegralFunction [get]
Returns a function object that represents a definite integral of this function from 0 to 1. Returns null if not implemented.
virtual RealFunctionBase InverseFunction [get]
Returns a function object that represents an inverse function of this function. Returns null if not implemented.
abstract bool ValueDefined [get, set]
Tells whether value of the function is defined by implementation.
abstract bool DerivativeDefined [get, set]
Tells whether the first derivative is defined for this function (by implementation, not mathematically)
abstract bool SecondDerivativeDefined [get, set]
Tells whether the second derivative is defined for this function (by implementation, not mathematically)
abstract bool IntegralDefined [get, set]
Tells whether analytical itegral of the function is defined or not.
abstract bool InverseDefined [get, set]
Tells whether analytical inverse function is defined or not.
Properties inherited from IG.Num.IRealFunction
string Name [get]
Returns a short name of the function.
string Description [get]
Returns a short description of the function.
bool ValueDefined [get]
Tells whether value of the function is defined by implementation.
bool DerivativeDefined [get]
Tells whether the first derivative is defined for this function (by implementation, not mathematically)
bool SecondDerivativeDefined [get]
Tells whether the second derivative is defined for this function (by implementation, not mathematically)
bool IntegralDefined [get]
Tells whether analytical itegral of the function is defined or not.
bool InverseDefined [get]
Tells whether analytical inverse function is defined or not.
Private Member Functions
FunctionPolynomial (double[] coefficients)
void Init ()
double ReferenceValue (double x)
double ReferencDerivative (double x)
double DerivativeMonomial (double x, int power, int order)
double ReferenceHigherDerivative (double x, int order)
double ReferenceSecondDerivative (double x)
double ReferenceIntegral (double x)
double ReferenceInverse (double y)
Private Attributes
double[] _coefficients = null
Additional Inherited Members
Static Public Member Functions inherited from IG.Num.RealFunction
static void TestSpeed ()
Compares calculation times of three ways of evaluations of exponential function: directly by Math.Exp(), through a delegate initialized by this function, and through a Function object initialized by this function. The number of repetitions is pre-defined.
static void TestSpeed (long numiterations)
Compares calculation times of three ways of evaluations of exponential function: directly by Math.Exp(), through a delegate initialized by this function, and through a Function object initialized by this function.
Static Public Member Functions inherited from IG.Num.RealFunctionBase
static void ExampleTests ()
Protected Member Functions inherited from IG.Num.RealFunction
RealFunction ()
virtual double RefValue (double x)
Returns the value of reference (untransformed) function.
virtual double RefDerivative (double x)
Returns the first derivative of reference (untransformed) function.
virtual double RefDerivative (double x, int order)
Returns the derivative of the given order of reference (untransformed) function.
virtual double RefSecondDerivative (double x)
Returns the second derivative of the given order of reference (untransformed) function.
virtual double RefIntegral (double x)
Returns definite integral of reference (untransformed) function from 0 to the function argument.
virtual double RefInverse (double y)
Returns inverse of the reference (untransformed) function.
Protected Attributes inherited from IG.Num.RealFunction
bool _valueDefined = false
bool _derivativeDefined = false
int _highestDerivativeDefined = 0
bool _secondDerivativeDefined = false
bool _integralDefined = false
bool _inverseDefined = false
Protected Attributes inherited from IG.Num.RealFunctionBase
string _name
string _description
Detailed Description
Polynomial real functions of one variable.
$A Igor xx;
Definition at line 1238 of file FunctionReal.cs.
Constructor & Destructor Documentation
FunctionPolynomial()
IG.Num.FunctionPolynomial.FunctionPolynomial (double[] coefficients) inline private
Definition at line 1244 of file FunctionReal.cs.
References IG.Num.FunctionPolynomial._coefficients, and IG.Num.FunctionPolynomial.Init().
Member Function Documentation
Init()
void IG.Num.FunctionPolynomial.Init () inline private
Definition at line 1250 of file FunctionReal.cs.
References IG.Num.FunctionPolynomial.ReferencDerivative(), IG.Num.FunctionPolynomial.ReferenceHigherDerivative(), IG.Num.FunctionPolynomial.ReferenceIntegral(), IG.Num.FunctionPolynomial.ReferenceInverse(), IG.Num.FunctionPolynomial.ReferenceSecondDerivative(), and IG.Num.FunctionPolynomial.ReferenceValue().
Referenced by IG.Num.FunctionPolynomial.FunctionPolynomial().
ReferenceValue()
double IG.Num.FunctionPolynomial.ReferenceValue (double x) inline private
Definition at line 1273 of file FunctionReal.cs.
References IG.Num.FunctionPolynomial._coefficients, and IG.Num.FunctionPolynomial.Order.
Referenced by IG.Num.FunctionPolynomial.Init().
ReferencDerivative()
double IG.Num.FunctionPolynomial.ReferencDerivative (double x) inline private
Definition at line 1286 of file FunctionReal.cs.
References IG.Num.FunctionPolynomial._coefficients, and IG.Num.FunctionPolynomial.Order.
Referenced by IG.Num.FunctionPolynomial.Init().
DerivativeMonomial()
double IG.Num.FunctionPolynomial.DerivativeMonomial (double x, int power, int order) inline private
Definition at line 1299 of file FunctionReal.cs.
Referenced by IG.Num.FunctionPolynomial.ReferenceHigherDerivative().
ReferenceHigherDerivative()
double IG.Num.FunctionPolynomial.ReferenceHigherDerivative (double x, int order) inline private
Definition at line 1316 of file FunctionReal.cs.
References IG.Num.FunctionPolynomial.DerivativeMonomial(), and IG.Num.FunctionPolynomial.Order.
Referenced by IG.Num.FunctionPolynomial.Init().
ReferenceSecondDerivative()
double IG.Num.FunctionPolynomial.ReferenceSecondDerivative (double x) inline private
Definition at line 1325 of file FunctionReal.cs.
References IG.Num.FunctionPolynomial._coefficients, and IG.Num.FunctionPolynomial.Order.
Referenced by IG.Num.FunctionPolynomial.Init().
ReferenceIntegral()
double IG.Num.FunctionPolynomial.ReferenceIntegral (double x) inline private
Definition at line 1338 of file FunctionReal.cs.
References IG.Num.FunctionPolynomial._coefficients, and IG.Num.FunctionPolynomial.Order.
Referenced by IG.Num.FunctionPolynomial.Init().
ReferenceInverse()
double IG.Num.FunctionPolynomial.ReferenceInverse (double y) inline private
Definition at line 1351 of file FunctionReal.cs.
References IG.Num.FunctionPolynomial._coefficients, and IG.Num.FunctionPolynomial.Order.
Referenced by IG.Num.FunctionPolynomial.Init().
HigherDerivativeDefined()
override bool IG.Num.FunctionPolynomial.HigherDerivativeDefined (int order) inline
Tells whether the derivative of the given order is defined for this function (by implementation, not mathematically)
Implements IG.Num.IRealFunction.
Definition at line 1367 of file FunctionReal.cs.
Member Data Documentation
_coefficients
double [] IG.Num.FunctionPolynomial._coefficients = null private
Definition at line 1264 of file FunctionReal.cs.
Referenced by IG.Num.FunctionPolynomial.FunctionPolynomial(), IG.Num.FunctionPolynomial.ReferencDerivative(), IG.Num.FunctionPolynomial.ReferenceIntegral(), IG.Num.FunctionPolynomial.ReferenceInverse(), IG.Num.FunctionPolynomial.ReferenceSecondDerivative(), and IG.Num.FunctionPolynomial.ReferenceValue().
Property Documentation
Order
int IG.Num.FunctionPolynomial.Order get
Returns order of the polynomial.
Definition at line 1268 of file FunctionReal.cs.
Referenced by IG.Num.FunctionPolynomial.ReferencDerivative(), IG.Num.FunctionPolynomial.ReferenceHigherDerivative(), IG.Num.FunctionPolynomial.ReferenceIntegral(), IG.Num.FunctionPolynomial.ReferenceInverse(), IG.Num.FunctionPolynomial.ReferenceSecondDerivative(), and IG.Num.FunctionPolynomial.ReferenceValue().
ValueDefined
override bool IG.Num.FunctionPolynomial.ValueDefined get
Definition at line 1362 of file FunctionReal.cs.
DerivativeDefined
override bool IG.Num.FunctionPolynomial.DerivativeDefined get
Definition at line 1365 of file FunctionReal.cs.
SecondDerivativeDefined
override bool IG.Num.FunctionPolynomial.SecondDerivativeDefined get
Definition at line 1371 of file FunctionReal.cs.
IntegralDefined
override bool IG.Num.FunctionPolynomial.IntegralDefined get
Definition at line 1374 of file FunctionReal.cs.
InverseDefined
override bool IG.Num.FunctionPolynomial.InverseDefined get
Definition at line 1377 of file FunctionReal.cs.
The documentation for this class was generated from the following file:
iglib/igbase/numeric/FunctionReal.cs