Doc: IGLib with source files: JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext Class Reference
JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext Class Reference
Public Member Functions
void PrettyPrintCharacter (char curChar, StringBuilder output)
void AppendCurrentChar ()
void AppendNewLine ()
void BuildContextIndents ()
void EnterObjectScope ()
void CloseCurrentScope ()
void EnterArrayScope ()
void AppendSpace ()
void ClearStrategies ()
void AddCharacterStrategy (ICharacterStrategy strategy)
Public Attributes
int SpacesPerIndent = 4
bool IsProcessingVariableAssignment
Properties
string Indent [get]
bool IsInArrayScope [get]
bool IsProcessingDoubleQuoteInitiatedString [get, set]
bool IsProcessingSingleQuoteInitiatedString [get, set]
bool IsProcessingString [get]
bool IsStart [get]
bool WasLastCharacterABackSlash [get]
Private Member Functions
void InitializeIndent ()
void AppendIndents (int indents)
Private Attributes
string _indent = string.Empty
readonly PPScopeState _scopeState = new PPScopeState()
char _previousChar
readonly IDictionary< char, ICharacterStrategy > _strategyCatalog = new Dictionary<char, ICharacterStrategy>()
StringBuilder _outputBuilder
char _currentCharacter
Static Private Attributes
const string Space = " "
Detailed Description
Definition at line 8 of file JsonPPStrategyContext.cs.
Member Function Documentation
InitializeIndent()
void JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.InitializeIndent () inline private
Definition at line 29 of file JsonPPStrategyContext.cs.
References JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext._indent, JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.Space, and JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.SpacesPerIndent.
AppendIndents()
void JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.AppendIndents (int indents) inline private
Definition at line 45 of file JsonPPStrategyContext.cs.
References JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext._outputBuilder, and JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.Indent.
Referenced by JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.BuildContextIndents().
PrettyPrintCharacter()
void JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.PrettyPrintCharacter (char curChar, StringBuilder output) inline
Definition at line 85 of file JsonPPStrategyContext.cs.
References JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext._currentCharacter, JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext._outputBuilder, JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext._previousChar, and JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext._strategyCatalog.
Referenced by JsonPrettyPrinterPlus.JsonPrettyPrinter.PrettyPrintCharacter().
AppendCurrentChar()
void JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.AppendCurrentChar () inline
Definition at line 100 of file JsonPPStrategyContext.cs.
References JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext._currentCharacter, and JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext._outputBuilder.
Referenced by JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategies.CloseBracketStrategy.ExecutePrintyPrint(), JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategies.CommaStrategy.ExecutePrintyPrint(), JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategies.SingleQuoteStrategy.ExecutePrintyPrint(), JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategies.CloseSquareBracketStrategy.ExecutePrintyPrint(), JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategies.DoubleQuoteStrategy.ExecutePrintyPrint(), JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategies.DefaultCharacterStrategy.ExecutePrintyPrint(), JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategies.OpenBracketStrategy.ExecutePrintyPrint(), JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategies.ColonCharacterStrategy.ExecutePrintyPrint(), JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategies.OpenSquareBracketStrategy.ExecutePrintyPrint(), JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategies.SkipWhileNotInStringStrategy.ExecutePrintyPrint(), and JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategies.CloseBracketStrategy.PeformNonStringPrint().
AppendNewLine()
void JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.AppendNewLine () inline
Definition at line 105 of file JsonPPStrategyContext.cs.
References JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext._outputBuilder.
Referenced by JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.BuildContextIndents().
BuildContextIndents()
void JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.BuildContextIndents () inline
Definition at line 110 of file JsonPPStrategyContext.cs.
References JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext._scopeState, JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.AppendIndents(), JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.AppendNewLine(), and JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.PPScopeState.ScopeDepth.
Referenced by JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategies.CloseSquareBracketStrategy.ExecutePrintyPrint(), JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategies.CommaStrategy.ExecutePrintyPrint(), JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategies.OpenBracketStrategy.ExecutePrintyPrint(), JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategies.OpenSquareBracketStrategy.ExecutePrintyPrint(), and JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategies.CloseBracketStrategy.PeformNonStringPrint().
EnterObjectScope()
void JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.EnterObjectScope () inline
Definition at line 116 of file JsonPPStrategyContext.cs.
References JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext._scopeState, and JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.PPScopeState.PushObjectContextOntoStack().
Referenced by JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategies.OpenBracketStrategy.ExecutePrintyPrint().
CloseCurrentScope()
void JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.CloseCurrentScope () inline
Definition at line 121 of file JsonPPStrategyContext.cs.
References JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext._scopeState, and JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.PPScopeState.PopJsonType().
Referenced by JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategies.CloseSquareBracketStrategy.ExecutePrintyPrint(), and JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategies.CloseBracketStrategy.PeformNonStringPrint().
EnterArrayScope()
void JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.EnterArrayScope () inline
Definition at line 126 of file JsonPPStrategyContext.cs.
References JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext._scopeState, and JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.PPScopeState.PushJsonArrayType().
Referenced by JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategies.OpenSquareBracketStrategy.ExecutePrintyPrint().
AppendSpace()
void JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.AppendSpace () inline
Definition at line 131 of file JsonPPStrategyContext.cs.
References JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext._outputBuilder, and JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.Space.
Referenced by JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategies.ColonCharacterStrategy.ExecutePrintyPrint().
ClearStrategies()
void JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.ClearStrategies () inline
Definition at line 136 of file JsonPPStrategyContext.cs.
References JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext._strategyCatalog.
Referenced by JsonPrettyPrinterPlus.JsonPrettyPrinter.JsonPrettyPrinter().
AddCharacterStrategy()
void JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.AddCharacterStrategy (ICharacterStrategy strategy) inline
Definition at line 141 of file JsonPPStrategyContext.cs.
References JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext._strategyCatalog, and JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.ICharacterStrategy.ForWhichCharacter.
Referenced by JsonPrettyPrinterPlus.JsonPrettyPrinter.JsonPrettyPrinter().
Member Data Documentation
Space
const string JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.Space = " " static private
Definition at line 11 of file JsonPPStrategyContext.cs.
Referenced by JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.AppendSpace(), and JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.InitializeIndent().
SpacesPerIndent
int JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.SpacesPerIndent = 4
Definition at line 12 of file JsonPPStrategyContext.cs.
Referenced by IG.Lib.JsonFormatter.Format(), and JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.InitializeIndent().
_indent
string JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext._indent = string.Empty private
Definition at line 14 of file JsonPPStrategyContext.cs.
Referenced by JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.InitializeIndent().
_scopeState
readonly PPScopeState JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext._scopeState = new PPScopeState() private
Definition at line 35 of file JsonPPStrategyContext.cs.
Referenced by JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.BuildContextIndents(), JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.CloseCurrentScope(), JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.EnterArrayScope(), and JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.EnterObjectScope().
IsProcessingVariableAssignment
bool JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.IsProcessingVariableAssignment
Definition at line 51 of file JsonPPStrategyContext.cs.
Referenced by JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategies.CommaStrategy.ExecutePrintyPrint(), JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategies.ColonCharacterStrategy.ExecutePrintyPrint(), and JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategies.OpenBracketStrategy.IsBeginningOfNewLineAndIndentionLevel().
_previousChar
char JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext._previousChar private
Definition at line 52 of file JsonPPStrategyContext.cs.
Referenced by JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.PrettyPrintCharacter().
_strategyCatalog
readonly IDictionary<char, ICharacterStrategy> JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext._strategyCatalog = new Dictionary<char, ICharacterStrategy>() private
Definition at line 80 of file JsonPPStrategyContext.cs.
Referenced by JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.AddCharacterStrategy(), JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.ClearStrategies(), and JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.PrettyPrintCharacter().
_outputBuilder
StringBuilder JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext._outputBuilder private
Definition at line 82 of file JsonPPStrategyContext.cs.
Referenced by JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.AppendCurrentChar(), JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.AppendIndents(), JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.AppendNewLine(), JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.AppendSpace(), and JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.PrettyPrintCharacter().
_currentCharacter
char JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext._currentCharacter private
Definition at line 83 of file JsonPPStrategyContext.cs.
Referenced by JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.AppendCurrentChar(), and JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.PrettyPrintCharacter().
Property Documentation
Indent
string JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.Indent get
Definition at line 16 of file JsonPPStrategyContext.cs.
Referenced by JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.AppendIndents().
IsInArrayScope
bool JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.IsInArrayScope get
Definition at line 38 of file JsonPPStrategyContext.cs.
Referenced by JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategies.OpenBracketStrategy.IsBeginningOfNewLineAndIndentionLevel().
IsProcessingDoubleQuoteInitiatedString
bool JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.IsProcessingDoubleQuoteInitiatedString get set
Definition at line 53 of file JsonPPStrategyContext.cs.
Referenced by JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategies.DoubleQuoteStrategy.ExecutePrintyPrint(), and JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategies.SingleQuoteStrategy.ExecutePrintyPrint().
IsProcessingSingleQuoteInitiatedString
bool JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.IsProcessingSingleQuoteInitiatedString get set
Definition at line 54 of file JsonPPStrategyContext.cs.
Referenced by JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategies.DoubleQuoteStrategy.ExecutePrintyPrint(), and JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategies.SingleQuoteStrategy.ExecutePrintyPrint().
IsProcessingString
bool JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.IsProcessingString get
Definition at line 57 of file JsonPPStrategyContext.cs.
Referenced by JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategies.CloseBracketStrategy.ExecutePrintyPrint(), JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategies.CloseSquareBracketStrategy.ExecutePrintyPrint(), JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategies.CommaStrategy.ExecutePrintyPrint(), JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategies.OpenBracketStrategy.ExecutePrintyPrint(), JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategies.OpenSquareBracketStrategy.ExecutePrintyPrint(), JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategies.ColonCharacterStrategy.ExecutePrintyPrint(), and JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategies.SkipWhileNotInStringStrategy.ExecutePrintyPrint().
IsStart
bool JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.IsStart get
Definition at line 65 of file JsonPPStrategyContext.cs.
Referenced by JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategies.OpenBracketStrategy.IsBeginningOfNewLineAndIndentionLevel().
WasLastCharacterABackSlash
bool JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategyContext.WasLastCharacterABackSlash get
Definition at line 73 of file JsonPPStrategyContext.cs.
Referenced by JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategies.DoubleQuoteStrategy.ExecutePrintyPrint(), and JsonPrettyPrinterPlus.JsonPrettyPrinterInternals.JsonPPStrategies.SingleQuoteStrategy.ExecutePrintyPrint().
The documentation for this class was generated from the following file:
iglib/igbase/data/serialization/json/JsonPrettyPrinterInternals/JsonPPStrategyContext.cs