Doc: IGLib with source files: IG.Num.AffineTransformationSquare Class Reference
IG.Num.AffineTransformationSquare Class Reference
Invertible Affine transformation with square transformation matrix.
Public Member Functions
AffineTransformationSquare (int dimension)
Constructs affine transformation with the specified dimensions of the original (reference) and transformed (target) space.
AffineTransformationSquare (Matrix transformationMatrix, Vector translationVector, bool inverseSpecified)
Constructs affine transformation with the specified transformation matrix and translation vector. Either of the transformation matrix or translation vector can be null, but not both.
AffineTransformationSquare (Matrix transformationMatrix, Vector translationVector)
Constructs affine transformation with the specified transformation matrix and translation vector. Either of the transformation matrix or translation vector can be null, but not both.
virtual void CopyTransformationMatrix (ref IMatrix store)
Copies transformation matrix to the specified storage matrix.
virtual void CopyInverseTransformationMatrix (ref IMatrix store)
Copies inverse transformation matrix to the specified storage matrix.
void TransformCoordinatesPlain (IVector original, IVector result)
Transforms co-ordinates from the reference to the transformed space. WARNING: This is a plain version that does not check dimensions.
void TransformCoordinates (IVector original, ref IVector result)
Transforms co-ordinates from the reference to the transformed space.
void TransformBackCoordinatesPlain (IVector transformed, IVector result)
Backward transforms co-ordinates from the transformed to the reference space.
void TransformBackCoordinates (IVector transformed, ref IVector result)
Backward transforms co-ordinates from the transformed to the reference space.
void TransformGradientPlain (IVector original, IVector result)
Transforms gradient (or other covariant vector) from the reference to the transformed space. WARNING: This is a plain version that does not check dimensions.
void TransformGradient (IVector original, ref IVector result)
Transforms gradient (or other covariant vector) from the reference to the transformed space.
void TransformBackGradientPlain (IVector transformed, IVector result)
Backward transforms gradient (or other covariant vector) from the transformed to the reference space.
void TransformBackGradient (IVector transformed, ref IVector result)
Backward transforms gradient (or other covariant vector) from the transformed to the reference space.
void TransformHessianPlain (IMatrix original, IMatrix result)
Transforms Hessian (or other covariant matrix) from the reference to the transformed space. WARNING: This is a plain version that does not check dimensions.
void TransformHessian (IMatrix original, ref IMatrix result)
Transforms Hessian (or other covariant matrix) from the reference to the transformed space.
void TransformBackHessianPlain (IMatrix transformed, IMatrix result)
Backward transforms Hessian (or other covariant matrix) from the transformed to the reference space.
void TransformBackHessian (IMatrix transformed, ref IMatrix result)
Backward transforms Hessian (or other covariant matrix) from the transformed to the reference space.
Protected Member Functions
AffineTransformationSquare ()
void InitAuxVec ()
Initializes auxiliary vector.
void InitIdentityMat ()
Initializes the auxiliary identity matrix.
void InitAuxMat ()
Initializes the auxiliary matrix.
virtual void CalculateTransformationMatrix ()
Calculates the transformation matrix from the inverse transformation matrix.
virtual void CalculateInverseTransformationMatrix ()
Calculates the inverse transformation matrix from the direct transformation matrix.
Protected Attributes
Vector _auxVec
Matrix _identityMat
Matrix _auxMat
Properties
object Lock [get]
Object used for locking of the current object (ILockable interface).
int DimensionOriginal [get, protected set]
Dimension of the original (reference) space.
int DimensionTransformed [get, protected set]
Dimension of the transformed space.
int Dimension [get, protected set]
Dimension of the original and transformed space (which are equal for this class).
bool CalculatedTransformationMatrix [get, protected set]
Flag indicating whethet the transformation matrix is calculated or not.
virtual IMatrix TransformationMatrix [get, set]
Gets or sets transformation matrix that transforms vector of co-ordinates from the original to the reference space.
bool CalculatedInverseTransformationMatrix [get, protected set]
Flag indicating whethet the transformation matrix is calculated or not.
virtual IMatrix InverseTransformationMatrix [get, set]
Gets or sets inverse of the transformation matrix that transforms vector of co-ordinates from the original to the reference space.
virtual IVector TranslationVector [get, set]
Gets or sets the translation vector of the affine transformation.
Properties inherited from IG.Num.IAffineTransformation
int DimensionOriginal [get]
int DimensionTransformed [get]
IMatrix TransformationMatrix [get, set]
Get or set the transformation matrix.
IMatrix InverseTransformationMatrix [get, set]
Gets or sets inverse transformation matrix.
IVector TranslationVector [get, set]
Gets or sets the translation vector.
Properties inherited from IG.Lib.ILockable
object Lock [get]
Private Attributes
object _lockObj = new object()
int _spaceDimension
bool _calcTransformationMatrix
IMatrix _transfMatrix
bool _calcInverseTransformationMatrix
IVector _translation
Detailed Description
Invertible Affine transformation with square transformation matrix.
$A Igor Jul10 Dec10; //TODO: implement IAffine transfoermation!
Definition at line 20 of file TransformationAffineSquare.cs.
Constructor & Destructor Documentation
AffineTransformationSquare() [1/4]
IG.Num.AffineTransformationSquare.AffineTransformationSquare () inline protected
Definition at line 25 of file TransformationAffineSquare.cs.
AffineTransformationSquare() [2/4]
IG.Num.AffineTransformationSquare.AffineTransformationSquare (int dimension) inline
Constructs affine transformation with the specified dimensions of the original (reference) and transformed (target) space.
Parameters
dimension Dimension of the original space.
Definition at line 30 of file TransformationAffineSquare.cs.
References IG.Num.AffineTransformationSquare.Dimension.
AffineTransformationSquare() [3/4]
IG.Num.AffineTransformationSquare.AffineTransformationSquare (Matrix transformationMatrix, Vector translationVector, bool inverseSpecified) inline
Constructs affine transformation with the specified transformation matrix and translation vector. Either of the transformation matrix or translation vector can be null, but not both.
Parameters
transformationMatrix Transformation matrix of the affine transformation.
translationVector Translation vector of the affine transformation.
inverseSpecified Whether inverse is specified.
Definition at line 42 of file TransformationAffineSquare.cs.
References IG.Num.Matrix.ColumnCount, IG.Num.Vector.Length, IG.Num.Matrix.RowCount, IG.Num.AffineTransformationSquare.TransformationMatrix, and IG.Num.AffineTransformationSquare.TranslationVector.
AffineTransformationSquare() [4/4]
IG.Num.AffineTransformationSquare.AffineTransformationSquare (Matrix transformationMatrix, Vector translationVector) inline
Constructs affine transformation with the specified transformation matrix and translation vector. Either of the transformation matrix or translation vector can be null, but not both.
Parameters
transformationMatrix Transformation matrix of the affine transformation.
translationVector Translation vector of the affine transformation.
Definition at line 64 of file TransformationAffineSquare.cs.
References IG.Num.Matrix.ColumnCount, IG.Num.Vector.Length, IG.Num.Matrix.RowCount, IG.Num.AffineTransformationSquare.TransformationMatrix, and IG.Num.AffineTransformationSquare.TranslationVector.
Member Function Documentation
InitAuxVec()
void IG.Num.AffineTransformationSquare.InitAuxVec () inline protected
Initializes auxiliary vector.
Definition at line 227 of file TransformationAffineSquare.cs.
References IG.Num.AffineTransformationSquare._auxVec, IG.Num.AffineTransformationSquare.Dimension, and IG.Num.Vector.Length.
Referenced by IG.Num.AffineTransformationSquare.TransformBackCoordinatesPlain().
InitIdentityMat()
void IG.Num.AffineTransformationSquare.InitIdentityMat () inline protected
Initializes the auxiliary identity matrix.
Definition at line 237 of file TransformationAffineSquare.cs.
References IG.Num.AffineTransformationSquare._identityMat, IG.Num.AffineTransformationSquare.Dimension, and IG.Num.Matrix.RowCount.
Referenced by IG.Num.AffineTransformationSquare.CalculateInverseTransformationMatrix(), and IG.Num.AffineTransformationSquare.CalculateTransformationMatrix().
InitAuxMat()
void IG.Num.AffineTransformationSquare.InitAuxMat () inline protected
Initializes the auxiliary matrix.
Definition at line 259 of file TransformationAffineSquare.cs.
References IG.Num.AffineTransformationSquare._auxMat, IG.Num.AffineTransformationSquare.Dimension, and IG.Num.Matrix.RowCount.
Referenced by IG.Num.AffineTransformationSquare.CalculateInverseTransformationMatrix(), and IG.Num.AffineTransformationSquare.CalculateTransformationMatrix().
CalculateTransformationMatrix()
virtual void IG.Num.AffineTransformationSquare.CalculateTransformationMatrix () inline protected virtual
Calculates the transformation matrix from the inverse transformation matrix.
Definition at line 274 of file TransformationAffineSquare.cs.
References IG.Num.AffineTransformationSquare._auxMat, IG.Num.AffineTransformationSquare._identityMat, IG.Num.AffineTransformationSquare.CalculatedInverseTransformationMatrix, IG.Num.AffineTransformationSquare.CalculatedTransformationMatrix, IG.Num.MatrixBase.CopyPlain(), IG.Num.AffineTransformationSquare.InitAuxMat(), IG.Num.AffineTransformationSquare.InitIdentityMat(), IG.Num.AffineTransformationSquare.InverseTransformationMatrix, IG.Num.LinearSolverBase.Solve(), and IG.Num.AffineTransformationSquare.TransformationMatrix.
CalculateInverseTransformationMatrix()
virtual void IG.Num.AffineTransformationSquare.CalculateInverseTransformationMatrix () inline protected virtual
Calculates the inverse transformation matrix from the direct transformation matrix.
Definition at line 297 of file TransformationAffineSquare.cs.
References IG.Num.AffineTransformationSquare._auxMat, IG.Num.AffineTransformationSquare._identityMat, IG.Num.AffineTransformationSquare.CalculatedInverseTransformationMatrix, IG.Num.AffineTransformationSquare.CalculatedTransformationMatrix, IG.Num.MatrixBase.CopyPlain(), IG.Num.AffineTransformationSquare.InitAuxMat(), IG.Num.AffineTransformationSquare.InitIdentityMat(), IG.Num.AffineTransformationSquare.InverseTransformationMatrix, IG.Num.LinearSolverBase.Solve(), and IG.Num.AffineTransformationSquare.TransformationMatrix.
CopyTransformationMatrix()
virtual void IG.Num.AffineTransformationSquare.CopyTransformationMatrix (ref IMatrix store) inline virtual
Copies transformation matrix to the specified storage matrix.
Parameters
store Storage matrix that transformation matrix is copied to.
Implements IG.Num.IAffineTransformation.
Definition at line 345 of file TransformationAffineSquare.cs.
References IG.Num.Matrix.Copy(), and IG.Num.AffineTransformationSquare.TransformationMatrix.
CopyInverseTransformationMatrix()
virtual void IG.Num.AffineTransformationSquare.CopyInverseTransformationMatrix (ref IMatrix store) inline virtual
Copies inverse transformation matrix to the specified storage matrix.
Parameters
store Storage matrix that inverse transformation matrix is copied to.
Implements IG.Num.IAffineTransformation.
Definition at line 353 of file TransformationAffineSquare.cs.
References IG.Num.Matrix.Copy(), and IG.Num.AffineTransformationSquare.InverseTransformationMatrix.
TransformCoordinatesPlain()
void IG.Num.AffineTransformationSquare.TransformCoordinatesPlain (IVector original, IVector result) inline
Transforms co-ordinates from the reference to the transformed space. WARNING: This is a plain version that does not check dimensions.
Parameters
original Vector of original co-ordinates.
result Vector where transformed co-ordinates are stored.
Implements IG.Num.IAffineTransformation.
Definition at line 368 of file TransformationAffineSquare.cs.
References IG.Num.VectorBase.AddPlain(), IG.Num.VectorBase.CopyPlain(), IG.Num.MatrixBase.MultiplyPlain(), IG.Num.AffineTransformationSquare.TransformationMatrix, and IG.Num.AffineTransformationSquare.TranslationVector.
Referenced by IG.Num.AffineTransformationSquare.TransformCoordinates().
TransformCoordinates()
void IG.Num.AffineTransformationSquare.TransformCoordinates (IVector original, ref IVector result) inline
Transforms co-ordinates from the reference to the transformed space.
Parameters
original Vector of original co-ordinates.
result Vector where transformed co-ordinates are stored.
Implements IG.Num.IAffineTransformation.
Definition at line 383 of file TransformationAffineSquare.cs.
References IG.Num.AffineTransformationSquare.Dimension, IG.Num.IVector< T >.GetNew(), IG.Num.IVector< T >.Length, and IG.Num.AffineTransformationSquare.TransformCoordinatesPlain().
TransformBackCoordinatesPlain()
void IG.Num.AffineTransformationSquare.TransformBackCoordinatesPlain (IVector transformed, IVector result) inline
Backward transforms co-ordinates from the transformed to the reference space.
Parameters
transformed Vector of transformed co-ordinates.
result Vector where inverse-transformed original co-ordinates are stored.
Implements IG.Num.IAffineTransformation.
Definition at line 401 of file TransformationAffineSquare.cs.
References IG.Num.AffineTransformationSquare._auxVec, IG.Num.VectorBase.CopyPlain(), IG.Num.AffineTransformationSquare.InitAuxVec(), IG.Num.AffineTransformationSquare.InverseTransformationMatrix, IG.Num.MatrixBase.MultiplyPlain(), IG.Num.VectorBase.SubtractPlain(), and IG.Num.AffineTransformationSquare.TranslationVector.
Referenced by IG.Num.AffineTransformationSquare.TransformBackCoordinates().
TransformBackCoordinates()
void IG.Num.AffineTransformationSquare.TransformBackCoordinates (IVector transformed, ref IVector result) inline
Backward transforms co-ordinates from the transformed to the reference space.
Parameters
transformed Vector of transformed co-ordinates.
result Vector where inverse-transformed original co-ordinates are stored.
Implements IG.Num.IAffineTransformation.
Definition at line 430 of file TransformationAffineSquare.cs.
References IG.Num.AffineTransformationSquare.Dimension, IG.Num.IVector< T >.GetNew(), IG.Num.IVector< T >.Length, and IG.Num.AffineTransformationSquare.TransformBackCoordinatesPlain().
TransformGradientPlain()
void IG.Num.AffineTransformationSquare.TransformGradientPlain (IVector original, IVector result) inline
Transforms gradient (or other covariant vector) from the reference to the transformed space. WARNING: This is a plain version that does not check dimensions.
Parameters
original Original gradient-like vector.
result Vector where resulting transformed vector is stored.
Implements IG.Num.IAffineTransformation.
Definition at line 453 of file TransformationAffineSquare.cs.
References IG.Num.VectorBase.CopyPlain(), IG.Num.AffineTransformationSquare.InverseTransformationMatrix, and IG.Num.MatrixBase.MultiplyTranspVecPlain().
Referenced by IG.Num.AffineTransformationSquare.TransformGradient().
TransformGradient()
void IG.Num.AffineTransformationSquare.TransformGradient (IVector original, ref IVector result) inline
Transforms gradient (or other covariant vector) from the reference to the transformed space.
Parameters
original Original gradient-like vector.
result Vector where resulting transformed vector is stored.
Implements IG.Num.IAffineTransformation.
Definition at line 466 of file TransformationAffineSquare.cs.
References IG.Num.AffineTransformationSquare.Dimension, IG.Num.IVector< T >.GetNew(), IG.Num.IVector< T >.Length, and IG.Num.AffineTransformationSquare.TransformGradientPlain().
TransformBackGradientPlain()
void IG.Num.AffineTransformationSquare.TransformBackGradientPlain (IVector transformed, IVector result) inline
Backward transforms gradient (or other covariant vector) from the transformed to the reference space.
Parameters
transformed Transformed gradient-like vector.
result Vector where resulting backward transformed vector is stored.
Implements IG.Num.IAffineTransformation.
Definition at line 483 of file TransformationAffineSquare.cs.
References IG.Num.VectorBase.CopyPlain(), IG.Num.MatrixBase.MultiplyTranspVecPlain(), and IG.Num.AffineTransformationSquare.TransformationMatrix.
Referenced by IG.Num.AffineTransformationSquare.TransformBackGradient().
TransformBackGradient()
void IG.Num.AffineTransformationSquare.TransformBackGradient (IVector transformed, ref IVector result) inline
Backward transforms gradient (or other covariant vector) from the transformed to the reference space.
Parameters
transformed Transformed gradient-like vector.
result Vector where resulting backward transformed vector is stored.
Implements IG.Num.IAffineTransformation.
Definition at line 496 of file TransformationAffineSquare.cs.
References IG.Num.AffineTransformationSquare.Dimension, IG.Num.IVector< T >.GetNew(), IG.Num.IVector< T >.Length, and IG.Num.AffineTransformationSquare.TransformBackGradientPlain().
TransformHessianPlain()
void IG.Num.AffineTransformationSquare.TransformHessianPlain (IMatrix original, IMatrix result) inline
Transforms Hessian (or other covariant matrix) from the reference to the transformed space. WARNING: This is a plain version that does not check dimensions.
Parameters
original Original matrix.
result Matrix where resulting transformed matrix is stored.
Implements IG.Num.IAffineTransformation.
Definition at line 519 of file TransformationAffineSquare.cs.
References IG.Num.MatrixBase.CopyPlain(), IG.Num.AffineTransformationSquare.InverseTransformationMatrix, and IG.Num.MatrixBase.MultiplyTranspMatMatPlain().
Referenced by IG.Num.AffineTransformationSquare.TransformHessian().
TransformHessian()
void IG.Num.AffineTransformationSquare.TransformHessian (IMatrix original, ref IMatrix result) inline
Transforms Hessian (or other covariant matrix) from the reference to the transformed space.
Parameters
original Original matrix.
result Matrix where resulting transformed matrix is stored. Allocated/reallocated if necessary.
Implements IG.Num.IAffineTransformation.
Definition at line 532 of file TransformationAffineSquare.cs.
References IG.Num.IMatrix< ComponentType >.ColumnCount, IG.Num.AffineTransformationSquare.Dimension, IG.Num.IMatrix< ComponentType >.GetNew(), IG.Num.IMatrix< ComponentType >.RowCount, and IG.Num.AffineTransformationSquare.TransformHessianPlain().
TransformBackHessianPlain()
void IG.Num.AffineTransformationSquare.TransformBackHessianPlain (IMatrix transformed, IMatrix result) inline
Backward transforms Hessian (or other covariant matrix) from the transformed to the reference space.
Parameters
transformed Matrix in transformed coordinates.
result Matrix where resulting backward-transformed matrix is stored.
Implements IG.Num.IAffineTransformation.
Definition at line 549 of file TransformationAffineSquare.cs.
References IG.Num.MatrixBase.CopyPlain(), IG.Num.MatrixBase.MultiplyTranspMatMatPlain(), and IG.Num.AffineTransformationSquare.TransformationMatrix.
Referenced by IG.Num.AffineTransformationSquare.TransformBackHessian().
TransformBackHessian()
void IG.Num.AffineTransformationSquare.TransformBackHessian (IMatrix transformed, ref IMatrix result) inline
Backward transforms Hessian (or other covariant matrix) from the transformed to the reference space.
Parameters
transformed Matrix in transformed coordinates.
result Matrix where resulting backward-transformed matrix is stored. Allocated/reallocated if necessary.
Implements IG.Num.IAffineTransformation.
Definition at line 562 of file TransformationAffineSquare.cs.
References IG.Num.IMatrix< ComponentType >.ColumnCount, IG.Num.AffineTransformationSquare.Dimension, IG.Num.IMatrix< ComponentType >.GetNew(), IG.Num.IMatrix< ComponentType >.RowCount, and IG.Num.AffineTransformationSquare.TransformBackHessianPlain().
Member Data Documentation
_lockObj
object IG.Num.AffineTransformationSquare._lockObj = new object() private
Definition at line 87 of file TransformationAffineSquare.cs.
_spaceDimension
int IG.Num.AffineTransformationSquare._spaceDimension private
Definition at line 92 of file TransformationAffineSquare.cs.
_calcTransformationMatrix
bool IG.Num.AffineTransformationSquare._calcTransformationMatrix private
Definition at line 130 of file TransformationAffineSquare.cs.
_transfMatrix
IMatrix IG.Num.AffineTransformationSquare._transfMatrix private
Definition at line 139 of file TransformationAffineSquare.cs.
_calcInverseTransformationMatrix
bool IG.Num.AffineTransformationSquare._calcInverseTransformationMatrix private
Definition at line 175 of file TransformationAffineSquare.cs.
_auxVec
Vector IG.Num.AffineTransformationSquare._auxVec protected
Definition at line 220 of file TransformationAffineSquare.cs.
Referenced by IG.Num.AffineTransformationSquare.InitAuxVec(), and IG.Num.AffineTransformationSquare.TransformBackCoordinatesPlain().
_identityMat
Matrix IG.Num.AffineTransformationSquare._identityMat protected
Definition at line 222 of file TransformationAffineSquare.cs.
Referenced by IG.Num.AffineTransformationSquare.CalculateInverseTransformationMatrix(), IG.Num.AffineTransformationSquare.CalculateTransformationMatrix(), and IG.Num.AffineTransformationSquare.InitIdentityMat().
_auxMat
Matrix IG.Num.AffineTransformationSquare._auxMat protected
Definition at line 224 of file TransformationAffineSquare.cs.
Referenced by IG.Num.AffineTransformationSquare.CalculateInverseTransformationMatrix(), IG.Num.AffineTransformationSquare.CalculateTransformationMatrix(), and IG.Num.AffineTransformationSquare.InitAuxMat().
_translation
IVector IG.Num.AffineTransformationSquare._translation private
Definition at line 320 of file TransformationAffineSquare.cs.
Property Documentation
Lock
object IG.Num.AffineTransformationSquare.Lock get
Object used for locking of the current object (ILockable interface).
Definition at line 90 of file TransformationAffineSquare.cs.
DimensionOriginal
int IG.Num.AffineTransformationSquare.DimensionOriginal get protected set
Dimension of the original (reference) space.
Definition at line 96 of file TransformationAffineSquare.cs.
DimensionTransformed
int IG.Num.AffineTransformationSquare.DimensionTransformed get protected set
Dimension of the transformed space.
Definition at line 108 of file TransformationAffineSquare.cs.
Dimension
int IG.Num.AffineTransformationSquare.Dimension get protected set
Dimension of the original and transformed space (which are equal for this class).
Definition at line 120 of file TransformationAffineSquare.cs.
Referenced by IG.Num.AffineTransformationDiagonal.AffineTransformationDiagonal(), IG.Num.AffineTransformationSquare.AffineTransformationSquare(), IG.Num.AffineTransformationSquare.InitAuxMat(), IG.Num.AffineTransformationSquare.InitAuxVec(), IG.Num.AffineTransformationSquare.InitIdentityMat(), IG.Num.AffineTransformationSquare.TransformBackCoordinates(), IG.Num.AffineTransformationSquare.TransformBackGradient(), IG.Num.AffineTransformationSquare.TransformBackHessian(), IG.Num.AffineTransformationSquare.TransformCoordinates(), IG.Num.AffineTransformationSquare.TransformGradient(), and IG.Num.AffineTransformationSquare.TransformHessian().
CalculatedTransformationMatrix
bool IG.Num.AffineTransformationSquare.CalculatedTransformationMatrix get protected set
Flag indicating whethet the transformation matrix is calculated or not.
Definition at line 134 of file TransformationAffineSquare.cs.
Referenced by IG.Num.AffineTransformationSquare.CalculateInverseTransformationMatrix(), and IG.Num.AffineTransformationSquare.CalculateTransformationMatrix().
TransformationMatrix
virtual IMatrix IG.Num.AffineTransformationSquare.TransformationMatrix get set
Gets or sets transformation matrix that transforms vector of co-ordinates from the original to the reference space.
Definition at line 144 of file TransformationAffineSquare.cs.
Referenced by IG.Num.AffineTransformationSquare.AffineTransformationSquare(), IG.Num.AffineTransformationSquare.CalculateInverseTransformationMatrix(), IG.Num.AffineTransformationSquare.CalculateTransformationMatrix(), IG.Num.AffineTransformationSquare.CopyTransformationMatrix(), IG.Num.AffineTransformationSquare.TransformBackGradientPlain(), IG.Num.AffineTransformationSquare.TransformBackHessianPlain(), and IG.Num.AffineTransformationSquare.TransformCoordinatesPlain().
CalculatedInverseTransformationMatrix
bool IG.Num.AffineTransformationSquare.CalculatedInverseTransformationMatrix get protected set
Flag indicating whethet the transformation matrix is calculated or not.
Definition at line 179 of file TransformationAffineSquare.cs.
Referenced by IG.Num.AffineTransformationSquare.CalculateInverseTransformationMatrix(), and IG.Num.AffineTransformationSquare.CalculateTransformationMatrix().
InverseTransformationMatrix
virtual IMatrix IG.Num.AffineTransformationSquare.InverseTransformationMatrix get set
Gets or sets inverse of the transformation matrix that transforms vector of co-ordinates from the original to the reference space.
Definition at line 189 of file TransformationAffineSquare.cs.
Referenced by IG.Num.AffineTransformationSquare.CalculateInverseTransformationMatrix(), IG.Num.AffineTransformationSquare.CalculateTransformationMatrix(), IG.Num.AffineTransformationSquare.CopyInverseTransformationMatrix(), IG.Num.AffineTransformationSquare.TransformBackCoordinatesPlain(), IG.Num.AffineTransformationSquare.TransformGradientPlain(), and IG.Num.AffineTransformationSquare.TransformHessianPlain().
TranslationVector
virtual IVector IG.Num.AffineTransformationSquare.TranslationVector get set
Gets or sets the translation vector of the affine transformation.
Definition at line 324 of file TransformationAffineSquare.cs.
Referenced by IG.Num.AffineTransformationSquare.AffineTransformationSquare(), IG.Num.AffineTransformationSquare.TransformBackCoordinatesPlain(), and IG.Num.AffineTransformationSquare.TransformCoordinatesPlain().
The documentation for this class was generated from the following file:
iglib/igbase/numeric/TransformationAffineSquare.cs