Doc: IGLib with source files: IG.Lib.IReporterBase Interface Reference
IG.Lib.IReporterBase Interface Reference
Interface from which all reporters inherit.
Public Member Functions
void Init ()
Initializes all error reporting delegates to default values and sets auxliary object to null. Auxiliary object Obj is set to null.
void Init (object obj, ReportDelegate reportdelegate, ReportLocationDelegate locationdelegate, ReportMessageDelegate messagedelegate, ReserveReportErrorDelegate reservereportdelegate)
Initializes the error reporter by the specified auxiliary object and delegates used to perform error reporting tasks. Delegates that are not specified are set to default values.
void Init (object obj, ReportDelegate reportdelegate, ReportLocationDelegate locationdelegate, ReportMessageDelegate messagedelegate)
Initializes the error reporter by the specified auxiliary object and delegates used to perform error reporting tasks. Reserve error reporting delegate is initialized to a default value. Delegates that are not specified are set to default values.
void Init (object obj, ReportDelegate reportdelegate)
Initializes the error reporter by the specified auxiliary object and the delegate to perform error reporting tasks. Reserve error reporting delegate is initialized to a default value. Delegates for assembling the error location string and error message string are set to their default values, which are adapted to console-like eror reporting systems.
void Init (object obj, ReportDelegate reportdelegate, ReserveReportErrorDelegate reservereportdelegate)
Initializes the error reporter by the specified auxiliary object and delegates used to perform error reporting tasks. Delegates for assembling the error locatin and error message string are set to their default values, which are adapted to console-like eror reporting systems.
void ReadAppSettings (string groupname)
Reads settings for a specified named group of reporters from the application configuration file.
void ReadAppSettings ()
Reads common reporter settings (i.e. settings that are not assigned for any named group) from the application configuration file.
void ReadAppSettings (string groupname, bool onlyonce)
Reads settings for a specified named group of reporters from the application configuration file.
bool AppSettingsRead ()
Returns a flag that tells whether general configuration settings (not belonging to any group) have already been read for this reporter.
bool AppSettingsRead (string groupname)
Returns a flag that tells whether configuration settings with a given group name have already been read for this reporter.
void IncreaseDepth ()
Increases indentation level by 1.
void IncreaseDepth (int numlevels)
Increases indentation level by the specified number of levels (can be 0 or negative).
void DecreaseDepth ()
Decreases indentation level by 1.
void DecreaseDepth (int numlevels)
Decreases indentation level by the specified number of levels (can be 0 or negative).
void ResetLevels ()
Resets the various kinds of reporting levels to default values.
bool DoReporting (ReportType reptype)
Returns true if the report of a given type should be shown by user interface (according to ReportingLevel), and false if not.
bool DoLogging (ReportType reptype)
Returns true if the report of a given type should be logged in log files (according to ReportingLevel), and false if not.
bool DoTracing (ReportType reptype)
Returns true if the report of a given type should traced (according to ReportingLevel), and false if not.
void Report (ReportType messagetype, string location, string message, Exception ex)
Basic reporting method (overloaded). Launches an error report, a warning report or other kind of report/message. Supplemental data (such as objects necessary to launch visualize the report or operation flags) are obtained from the class' instance.
void Report (ReportType messagetype, string message, Exception ex)
Launches a report. Predominantly for error and warning reports.
void Report (ReportType messagetype, Exception ex, string location)
Launches a report. Predominantly for error and warning reports.
void Report (ReportType messagetype, Exception ex)
Launches a report. Predominantly for error and warning reports.
void Report (ReportType messagetype, string location, string message)
Launches a report.
void Report (ReportType messagetype, string message)
Launches a report.
void ReportError (string location, string message, Exception ex)
Basic error reporting method (overloaded). Supplemental data (such as objects necessary to launch visualize the report or operation flags) are obtained from the class' instance.
void ReportError (string message, Exception ex)
Launches an error report.
void ReportError (Exception ex, string location)
Launches an error report.
void ReportError (Exception ex)
Launches an error report. Predominantly for error and warning reports.
void ReportError (string location, string message)
Launches an error report.
void ReportError (string message)
Launches an error report.
void ReportWarning (string location, string message, Exception ex)
Basic warning reporting method (overloaded). Supplemental data (such as objects necessary to launch visualize the report or operation flags) are obtained from the class' instance.
void ReportWarning (string message, Exception ex)
Launches a warning report.
void ReportWarning (Exception ex, string location)
Launches a warning report.
void ReportWarning (Exception ex)
Launches a warning report. Predominantly for error and warning reports.
void ReportWarning (string location, string message)
Launches a warning report.
void ReportWarning (string message)
Launches a warning report.
void ReportInfo (Exception ex)
Launches an info.
void ReportInfo (string location, string message)
Launches an info.
void ReportInfo (string message)
Launches an info.
Properties
bool AppSettingsWarnings [get, set]
Gets or sets the flag that specifies whether a warning message is launched when reading of application settings is attempted more than once for the same named group of settings.
bool IsGlobal [get]
Indicates whether the current reporter is used as a global reporter or not.
int Depth [get, set]
Gets or sets the current indentation level for on-line output. This should normally be done by calling IncreaseDepth() or DecreaseDepth().
ReportLevel ReportingLevel [get, set]
Gets or sets level of output for reporting (console output, message boxes, etc.).
ReportLevel LoggingLevel [get, set]
Gets or sets level of output for logging (writing to log files).
ReportLevel TracingLevel [get, set]
Gets or sets trace level (for external trace systems).
bool TreatError [get]
Returns a boolean value indicating whether errors are treated by the reporter in its current state.
bool TreatWarning [get]
Returns a boolean value indicating whether warnings are treated by the reporter in its current state.
bool TreatInfo [get]
Returns a boolean value indicating whether info messages are treated by the reporter in its current state.
bool TreatUndefined [get]
Returns a boolean value indicating whether undefined messages with the lowest priority are treated by the reporter in its current state.
ReportLevel Level [get, set]
Gets the level with the lowesst priority (out of reporting, logging and tracing level), or sets all levels to the assigned level.
bool this[ReportLevel level] [get, set]
Indexer that returns true if messages of a given level are treated by the reporter (either by the reporting, logging or tracing part, according to the corresponding level states), or false if not (i.e. if all the levels are set lover than the index). In the case of assignment, when true is assigned, all levels that are set lower than the are set to index. Assignment with false should be used only exteptionally; but in this case all levels that are set higher or equal than the index are set one level below.
TraceSwitch ReportingSwitch [get, set]
Gets or sets the TraceSwitch that is synchronized with ReportingLevel. IMPORTANT: State of the object obtained by get accessor must not be changed unless the object is assigned back by the set accessor. If one wants that this TraceSwitch assumes values specified by the configuration file, a corresponding Traceswitch must be created and assigned to this property (otherwise the TraceSwitch will be synchronized with the ReportingLevel, which will override its settings).
TraceSwitch LoggingSwitch [get, set]
Gets or sets the TraceSwitch that is synchronized with LoggingLevel. IMPORTANT: State of the object obtained by get accessor must not be changed unless the object is assigned back by the set accessor. If one wants that this TraceSwitch assumes values specified by the configuration file, a corresponding Traceswitch must be created and assigned to this property (otherwise the TraceSwitch will be synchronized with the LoggingLevel, which will override its settings).
TraceSwitch TracingSwitch [get, set]
Gets or sets the TraceSwitch that is synchronized with TracingLevel. IMPORTANT: State of the object obtained by get accessor must not be changed unless the object is assigned back by the set accessor. If one wants that this TraceSwitch assumes values specified by the configuration file, a corresponding Traceswitch must be created and assigned to this property (otherwise the TraceSwitch will be synchronized with the TracingLevel, which will override its settings).
object Obj [get, set]
Auxiliary object used by the delegates that perform error reporting.
object lockobj [get]
Object used for locking.
Detailed Description
Interface from which all reporters inherit.
Definition at line 759 of file ReporterMsg.cs.
Member Function Documentation
Init() [1/5]
void IG.Lib.IReporterBase.Init ()
Initializes all error reporting delegates to default values and sets auxliary object to null. Auxiliary object Obj is set to null.
Implemented in IG.Lib.ReporterBase.
Init() [2/5]
void IG.Lib.IReporterBase.Init (object obj, ReportDelegate reportdelegate, ReportLocationDelegate locationdelegate, ReportMessageDelegate messagedelegate, ReserveReportErrorDelegate reservereportdelegate)
Initializes the error reporter by the specified auxiliary object and delegates used to perform error reporting tasks. Delegates that are not specified are set to default values.
Parameters
obj Auxiliary object that will be passed to error reporting delegates when called in local methods.
reportdelegate Delegates that is called to launc an error report. Methods of this class will pass to this class the auxiliary object, location strings assembled by the location assembling delegate, and error message string assembled by the error message delegate.
locationdelegate Delegate that is called to assemble the error location string. The Auxiliary object this.Obj will be internally passed to this delegate any time it is called.
messagedelegate Delegate that is called to assemble the error message (without decorations). The Auxiliary object this.Obj will be internally passed to this delegate any time it is called.
reservereportdelegate Delegate that is called to report exceptions that occur within error reporting methods. In particular, this must ne as bullet proof as possible.
Implemented in IG.Lib.ReporterBase.
Init() [3/5]
void IG.Lib.IReporterBase.Init (object obj, ReportDelegate reportdelegate, ReportLocationDelegate locationdelegate, ReportMessageDelegate messagedelegate)
Initializes the error reporter by the specified auxiliary object and delegates used to perform error reporting tasks. Reserve error reporting delegate is initialized to a default value. Delegates that are not specified are set to default values.
Implemented in IG.Lib.ReporterBase.
Init() [4/5]
void IG.Lib.IReporterBase.Init (object obj, ReportDelegate reportdelegate)
Initializes the error reporter by the specified auxiliary object and the delegate to perform error reporting tasks. Reserve error reporting delegate is initialized to a default value. Delegates for assembling the error location string and error message string are set to their default values, which are adapted to console-like eror reporting systems.
Implemented in IG.Lib.ReporterBase.
Init() [5/5]
void IG.Lib.IReporterBase.Init (object obj, ReportDelegate reportdelegate, ReserveReportErrorDelegate reservereportdelegate)
Initializes the error reporter by the specified auxiliary object and delegates used to perform error reporting tasks. Delegates for assembling the error locatin and error message string are set to their default values, which are adapted to console-like eror reporting systems.
Parameters
obj Auxiliary object that will be passed to error reporting delegates when called in local methods.
reportdelegate Delegates that is called to launc an error report. Methods of this class will pass to this class the auxiliary object, location strings assembled by the location assembling delegate, and error message string assembled by the error message delegate.
reservereportdelegate Delegate that is called to report exceptions that occur within error reporting methods. In particular, this must ne as bullet proof as possible.
Implemented in IG.Lib.ReporterBase.
ReadAppSettings() [1/3]
void IG.Lib.IReporterBase.ReadAppSettings (string groupname)
Reads settings for a specified named group of reporters from the application configuration file.
Parameters
groupname Name of the group of reporters for which the settings apply.
Implemented in IG.Lib.ReporterBase.
ReadAppSettings() [2/3]
void IG.Lib.IReporterBase.ReadAppSettings ()
Reads common reporter settings (i.e. settings that are not assigned for any named group) from the application configuration file.
Implemented in IG.Lib.ReporterBase.
ReadAppSettings() [3/3]
void IG.Lib.IReporterBase.ReadAppSettings (string groupname, bool onlyonce)
Reads settings for a specified named group of reporters from the application configuration file.
Parameters
groupname Name of the group of reporters for which the settings apply.
onlyonce If true then settings belonging to the specified group are read only once, otherwise the settings for this group can be read several times (this is seldom used).
Implemented in IG.Lib.ReporterBase.
AppSettingsRead() [1/2]
bool IG.Lib.IReporterBase.AppSettingsRead ()
Returns a flag that tells whether general configuration settings (not belonging to any group) have already been read for this reporter.
Returns
true if settings with the specified name have already been read for teh current reporter, false otherwise.
Implemented in IG.Lib.ReporterBase.
AppSettingsRead() [2/2]
bool IG.Lib.IReporterBase.AppSettingsRead (string groupname)
Returns a flag that tells whether configuration settings with a given group name have already been read for this reporter.
Parameters
groupname Name of the settings group, null and "" are treated teh same (denoting the genraal group).
Returns
true if settings with the specified name have already been read for teh current reporter, false otherwise.
Implemented in IG.Lib.ReporterBase.
IncreaseDepth() [1/2]
void IG.Lib.IReporterBase.IncreaseDepth ()
Increases indentation level by 1.
Returns
Current indentation level.
Implemented in IG.Lib.ReporterBase.
IncreaseDepth() [2/2]
void IG.Lib.IReporterBase.IncreaseDepth (int numlevels)
Increases indentation level by the specified number of levels (can be 0 or negative).
Parameters
numlevels Number of levels by which indentation is increased.
Returns
Current intentation level.
Implemented in IG.Lib.ReporterBase.
DecreaseDepth() [1/2]
void IG.Lib.IReporterBase.DecreaseDepth ()
Decreases indentation level by 1.
Returns
Current indentation level.
Implemented in IG.Lib.ReporterBase.
DecreaseDepth() [2/2]
void IG.Lib.IReporterBase.DecreaseDepth (int numlevels)
Decreases indentation level by the specified number of levels (can be 0 or negative).
Parameters
numlevels Number of levels by which indentation is decreased.
Returns
Current intentation level.
Implemented in IG.Lib.ReporterBase.
ResetLevels()
void IG.Lib.IReporterBase.ResetLevels ()
Resets the various kinds of reporting levels to default values.
Implemented in IG.Lib.ReporterBase.
DoReporting()
bool IG.Lib.IReporterBase.DoReporting (ReportType reptype)
Returns true if the report of a given type should be shown by user interface (according to ReportingLevel), and false if not.
Parameters
reptype Type of the report for which information is returned.
Returns
True if reports of the specific type are launched, false if not.
Implemented in IG.Lib.ReporterBase.
DoLogging()
bool IG.Lib.IReporterBase.DoLogging (ReportType reptype)
Returns true if the report of a given type should be logged in log files (according to ReportingLevel), and false if not.
Parameters
reptype Type of the report for which information is returned.
Returns
True if reports of the specific type are launched, false if not.
Implemented in IG.Lib.ReporterBase.
DoTracing()
bool IG.Lib.IReporterBase.DoTracing (ReportType reptype)
Returns true if the report of a given type should traced (according to ReportingLevel), and false if not.
Parameters
reptype Type of the report for which information is returned.
Returns
True if reports of the specific type are launched, false if not.
Implemented in IG.Lib.ReporterBase.
Report() [1/6]
void IG.Lib.IReporterBase.Report (ReportType messagetype, string location, string message, Exception ex)
Basic reporting method (overloaded). Launches an error report, a warning report or other kind of report/message. Supplemental data (such as objects necessary to launch visualize the report or operation flags) are obtained from the class' instance.
Parameters
messagetype The type of the report (e.g. Error, Warning, etc.).
location User-provided description of error location.
message User-provided description of error.
ex Exception thrown when error occurred.
Implemented in IG.Lib.ReporterBase, and IG.Lib.ReporterConsole_Base.
Report() [2/6]
void IG.Lib.IReporterBase.Report (ReportType messagetype, string message, Exception ex)
Launches a report. Predominantly for error and warning reports.
Parameters
messagetype Level of the message (Error, Warnind, etc.).
message User-provided description of error.
ex Exception that is the cause for launching the report (and from which additional information is extracted).
Implemented in IG.Lib.ReporterBase.
Report() [3/6]
void IG.Lib.IReporterBase.Report (ReportType messagetype, Exception ex, string location)
Launches a report. Predominantly for error and warning reports.
Parameters
messagetype Level of the message (Error, Warnind, etc.).
ex Exception that is the cause for launching the report (and from which additional information is extracted).
location User-provided description of error location.
Implemented in IG.Lib.ReporterBase.
Report() [4/6]
void IG.Lib.IReporterBase.Report (ReportType messagetype, Exception ex)
Launches a report. Predominantly for error and warning reports.
Parameters
messagetype Level of the message (Error, Warnind, etc.).
ex Exception that is the cause for launching the report (and from which additional information is extracted).
Implemented in IG.Lib.ReporterBase.
Report() [5/6]
void IG.Lib.IReporterBase.Report (ReportType messagetype, string location, string message)
Launches a report.
Parameters
messagetype Level of the message (Error, Warnind, etc.).
location User provided description of the location where report was triggered.
message User provided message included in the report.
Implemented in IG.Lib.ReporterBase.
Report() [6/6]
void IG.Lib.IReporterBase.Report (ReportType messagetype, string message)
Launches a report.
Parameters
messagetype Level of the message (Error, Warnind, etc.).
message User provided message included in the report.
Implemented in IG.Lib.ReporterBase.
ReportError() [1/6]
void IG.Lib.IReporterBase.ReportError (string location, string message, Exception ex)
Basic error reporting method (overloaded). Supplemental data (such as objects necessary to launch visualize the report or operation flags) are obtained from the class' instance.
Parameters
location User-provided description of error location.
message User-provided description of error.
ex Exception thrown when error occurred.
Implemented in IG.Lib.ReporterBase.
Referenced by IG.Lib.XmlBuilder.AppendChild(), IG.Lib.XmlBuilder.CreateNode(), IG.Lib.XmlBuilder.InsertAfter(), IG.Lib.XmlBuilder.InsertBefore(), IG.Lib.XmlParser.MoveTo(), IG.Lib.XmlBuilder.PrependChild(), IG.Lib.XmlBuilder.RemoveNode(), IG.Lib.XmlBuilder.SetAttribute(), IG.Lib.XmlBuilder.SetInnerText(), IG.Lib.XmlParser.SetMark(), and IG.Lib.XmlBuilder.SetValue().
ReportError() [2/6]
void IG.Lib.IReporterBase.ReportError (string message, Exception ex)
Launches an error report.
Parameters
message User-provided description of error.
ex Exception that is the cause for launching the report (and from which additional information is extracted).
Implemented in IG.Lib.ReporterBase.
ReportError() [3/6]
void IG.Lib.IReporterBase.ReportError (Exception ex, string location)
Launches an error report.
Parameters
ex Exception that is the cause for launching the report (and from which additional information is extracted).
location User-provided description of error location.
Implemented in IG.Lib.ReporterBase.
ReportError() [4/6]
void IG.Lib.IReporterBase.ReportError (Exception ex)
Launches an error report. Predominantly for error and warning reports.
Parameters
ex Exception that is the cause for launching the report (and from which additional information is extracted).
Implemented in IG.Lib.ReporterBase.
ReportError() [5/6]
void IG.Lib.IReporterBase.ReportError (string location, string message)
Launches an error report.
Parameters
location User provided description of the location where report was triggered.
message User provided message included in the report.
Implemented in IG.Lib.ReporterBase.
ReportError() [6/6]
void IG.Lib.IReporterBase.ReportError (string message)
Launches an error report.
Parameters
message User provided message included in the report.
Implemented in IG.Lib.ReporterBase.
ReportWarning() [1/6]
void IG.Lib.IReporterBase.ReportWarning (string location, string message, Exception ex)
Basic warning reporting method (overloaded). Supplemental data (such as objects necessary to launch visualize the report or operation flags) are obtained from the class' instance.
Parameters
location User-provided description of error location.
message User-provided description of error.
ex Exception thrown when error occurred.
Implemented in IG.Lib.ReporterBase.
ReportWarning() [2/6]
void IG.Lib.IReporterBase.ReportWarning (string message, Exception ex)
Launches a warning report.
Parameters
message User-provided description of error.
ex Exception that is the cause for launching the report (and from which additional information is extracted).
Implemented in IG.Lib.ReporterBase.
ReportWarning() [3/6]
void IG.Lib.IReporterBase.ReportWarning (Exception ex, string location)
Launches a warning report.
Parameters
ex Exception that is the cause for launching the report (and from which additional information is extracted).
location User-provided description of error location.
Implemented in IG.Lib.ReporterBase.
ReportWarning() [4/6]
void IG.Lib.IReporterBase.ReportWarning (Exception ex)
Launches a warning report. Predominantly for error and warning reports.
Parameters
ex Exception that is the cause for launching the report (and from which additional information is extracted).
Implemented in IG.Lib.ReporterBase.
ReportWarning() [5/6]
void IG.Lib.IReporterBase.ReportWarning (string location, string message)
Launches a warning report.
Parameters
location User provided description of the location where report was triggered.
message User provided message included in the report.
Implemented in IG.Lib.ReporterBase.
ReportWarning() [6/6]
void IG.Lib.IReporterBase.ReportWarning (string message)
Launches a warning report.
Parameters
message User provided message included in the report.
Implemented in IG.Lib.ReporterBase.
ReportInfo() [1/3]
void IG.Lib.IReporterBase.ReportInfo (Exception ex)
Launches an info.
Parameters
ex Exception that is the cause for launching the report (and from which additional information is extracted).
Implemented in IG.Lib.ReporterBase.
Referenced by IG.Lib.XmlUtilityBase.Load(), and IG.Lib.XmlUtilityBase.LoadXml().
ReportInfo() [2/3]
void IG.Lib.IReporterBase.ReportInfo (string location, string message)
Launches an info.
Parameters
location User provided description of the location where report was triggered.
message User provided message included in the report.
Implemented in IG.Lib.ReporterBase.
ReportInfo() [3/3]
void IG.Lib.IReporterBase.ReportInfo (string message)
Launches an info.
Parameters
message User provided message included in the report.
Implemented in IG.Lib.ReporterBase.
Property Documentation
AppSettingsWarnings
bool IG.Lib.IReporterBase.AppSettingsWarnings get set
Gets or sets the flag that specifies whether a warning message is launched when reading of application settings is attempted more than once for the same named group of settings.
Definition at line 854 of file ReporterMsg.cs.
IsGlobal
bool IG.Lib.IReporterBase.IsGlobal get
Indicates whether the current reporter is used as a global reporter or not.
This flag is set when the global reporter is initialized.
Definition at line 863 of file ReporterMsg.cs.
Depth
int IG.Lib.IReporterBase.Depth get set
Gets or sets the current indentation level for on-line output. This should normally be done by calling IncreaseDepth() or DecreaseDepth().
Definition at line 870 of file ReporterMsg.cs.
Referenced by IG.Lib.XmlUtilityBase.Load(), and IG.Lib.XmlUtilityBase.LoadXml().
ReportingLevel
ReportLevel IG.Lib.IReporterBase.ReportingLevel get set
Gets or sets level of output for reporting (console output, message boxes, etc.).
Definition at line 897 of file ReporterMsg.cs.
LoggingLevel
ReportLevel IG.Lib.IReporterBase.LoggingLevel get set
Gets or sets level of output for logging (writing to log files).
Definition at line 900 of file ReporterMsg.cs.
TracingLevel
ReportLevel IG.Lib.IReporterBase.TracingLevel get set
Gets or sets trace level (for external trace systems).
Definition at line 903 of file ReporterMsg.cs.
TreatError
bool IG.Lib.IReporterBase.TreatError get
Returns a boolean value indicating whether errors are treated by the reporter in its current state.
Definition at line 909 of file ReporterMsg.cs.
TreatWarning
bool IG.Lib.IReporterBase.TreatWarning get
Returns a boolean value indicating whether warnings are treated by the reporter in its current state.
Definition at line 912 of file ReporterMsg.cs.
TreatInfo
bool IG.Lib.IReporterBase.TreatInfo get
Returns a boolean value indicating whether info messages are treated by the reporter in its current state.
Definition at line 916 of file ReporterMsg.cs.
Referenced by IG.Lib.XmlUtilityBase.Load(), and IG.Lib.XmlUtilityBase.LoadXml().
TreatUndefined
bool IG.Lib.IReporterBase.TreatUndefined get
Returns a boolean value indicating whether undefined messages with the lowest priority are treated by the reporter in its current state.
Definition at line 919 of file ReporterMsg.cs.
Level
ReportLevel IG.Lib.IReporterBase.Level get set
Gets the level with the lowesst priority (out of reporting, logging and tracing level), or sets all levels to the assigned level.
Definition at line 943 of file ReporterMsg.cs.
this[ReportLevel level]
bool IG.Lib.IReporterBase.this[ReportLevel level] get set
Indexer that returns true if messages of a given level are treated by the reporter (either by the reporting, logging or tracing part, according to the corresponding level states), or false if not (i.e. if all the levels are set lover than the index). In the case of assignment, when true is assigned, all levels that are set lower than the are set to index. Assignment with false should be used only exteptionally; but in this case all levels that are set higher or equal than the index are set one level below.
Parameters
level Level for which we are interested whether it is treated.
Returns
True if a specific level (stated as index) is treated, false if not (i.e. if all of the reporting, logging)
Definition at line 954 of file ReporterMsg.cs.
ReportingSwitch
TraceSwitch IG.Lib.IReporterBase.ReportingSwitch get set
Gets or sets the TraceSwitch that is synchronized with ReportingLevel. IMPORTANT: State of the object obtained by get accessor must not be changed unless the object is assigned back by the set accessor. If one wants that this TraceSwitch assumes values specified by the configuration file, a corresponding Traceswitch must be created and assigned to this property (otherwise the TraceSwitch will be synchronized with the ReportingLevel, which will override its settings).
Definition at line 992 of file ReporterMsg.cs.
LoggingSwitch
TraceSwitch IG.Lib.IReporterBase.LoggingSwitch get set
Gets or sets the TraceSwitch that is synchronized with LoggingLevel. IMPORTANT: State of the object obtained by get accessor must not be changed unless the object is assigned back by the set accessor. If one wants that this TraceSwitch assumes values specified by the configuration file, a corresponding Traceswitch must be created and assigned to this property (otherwise the TraceSwitch will be synchronized with the LoggingLevel, which will override its settings).
Definition at line 999 of file ReporterMsg.cs.
TracingSwitch
TraceSwitch IG.Lib.IReporterBase.TracingSwitch get set
Gets or sets the TraceSwitch that is synchronized with TracingLevel. IMPORTANT: State of the object obtained by get accessor must not be changed unless the object is assigned back by the set accessor. If one wants that this TraceSwitch assumes values specified by the configuration file, a corresponding Traceswitch must be created and assigned to this property (otherwise the TraceSwitch will be synchronized with the TracingLevel, which will override its settings).
Definition at line 1006 of file ReporterMsg.cs.
Obj
object IG.Lib.IReporterBase.Obj get set
Auxiliary object used by the delegates that perform error reporting.
The object is used to provide additional information used in error reporting, or to provide objects that perform some actions in error reporting tasks, or both. It is left entirely to error reporting delegates to interpret the object's contents.
Definition at line 1018 of file ReporterMsg.cs.
lockobj
object IG.Lib.IReporterBase.lockobj get
Object used for locking.
Definition at line 1021 of file ReporterMsg.cs.
The documentation for this interface was generated from the following file:
iglib/igbase/reporter/ReporterMsg.cs