Doc: IGLib with source files: IG.Num.SampledDataElementDto Class Reference
IG.Num.SampledDataElementDto Class Reference
DTO (data transfer object) for sampled data element (one point with vectors of input and output parameters).
Public Member Functions
SampledDataElementDto ()
override SampledDataElement CreateObject ()
Creates and returns an object consistent with current contents of the vector.
Public Attributes
int Index
Idex of the element in arrays or list (or in SampledDataSet objects), auxiliary information that facilitates identification and access to specific data chunk out of those that are worked out.
Protected Member Functions
override void CopyFromPlain (SampledDataElement obj)
override void CopyToPlain (ref SampledDataElement obj)
Protected Attributes
VectorDtoBase _inputParameters
VectorDtoBase _outputValues
Properties
virtual VectorDtoBase InputParameters [get, set]
Vector of input parameters of a single data element.
virtual VectorDtoBase OutputValues [get, set]
Vector of input parameters of a single data element.
Detailed Description
DTO (data transfer object) for sampled data element (one point with vectors of input and output parameters).
$A Igor Mar11;
Definition at line 18 of file SampledDataDto.cs.
Constructor & Destructor Documentation
SampledDataElementDto()
IG.Num.SampledDataElementDto.SampledDataElementDto () inline
Definition at line 21 of file SampledDataDto.cs.
Member Function Documentation
CreateObject()
override SampledDataElement IG.Num.SampledDataElementDto.CreateObject () inline
Creates and returns an object consistent with current contents of the vector.
Definition at line 50 of file SampledDataDto.cs.
Referenced by IG.Num.SampledDataElementDto.CopyToPlain().
CopyFromPlain()
override void IG.Num.SampledDataElementDto.CopyFromPlain (SampledDataElement obj) inline protected
Definition at line 57 of file SampledDataDto.cs.
References IG.Lib.SerializationDtoBase< Type, BaseType >.CopyFrom(), IG.Num.SampledDataElement.Index, IG.Num.SampledDataElementDto.InputParameters, IG.Num.SampledDataElement.InputParameters, IG.Num.SampledDataElementDto.OutputValues, and IG.Num.SampledDataElement.OutputValues.
CopyToPlain()
override void IG.Num.SampledDataElementDto.CopyToPlain (ref SampledDataElement obj) inline protected
Definition at line 76 of file SampledDataDto.cs.
References IG.Lib.SerializationDtoBase< Type, BaseType >.CopyTo(), IG.Num.SampledDataElementDto.CreateObject(), IG.Num.SampledDataElementDto.Index, IG.Num.SampledDataElementDto.InputParameters, and IG.Num.SampledDataElementDto.OutputValues.
Member Data Documentation
Index
int IG.Num.SampledDataElementDto.Index
Idex of the element in arrays or list (or in SampledDataSet objects), auxiliary information that facilitates identification and access to specific data chunk out of those that are worked out.
Definition at line 31 of file SampledDataDto.cs.
Referenced by IG.Num.SampledDataElementDto.CopyToPlain().
_inputParameters
VectorDtoBase IG.Num.SampledDataElementDto._inputParameters protected
Definition at line 33 of file SampledDataDto.cs.
_outputValues
VectorDtoBase IG.Num.SampledDataElementDto._outputValues protected
Definition at line 35 of file SampledDataDto.cs.
Property Documentation
InputParameters
virtual VectorDtoBase IG.Num.SampledDataElementDto.InputParameters get set
Vector of input parameters of a single data element.
Definition at line 39 of file SampledDataDto.cs.
Referenced by IG.Num.SampledDataElementDto.CopyFromPlain(), and IG.Num.SampledDataElementDto.CopyToPlain().
OutputValues
virtual VectorDtoBase IG.Num.SampledDataElementDto.OutputValues get set
Vector of input parameters of a single data element.
Definition at line 43 of file SampledDataDto.cs.
Referenced by IG.Num.SampledDataElementDto.CopyFromPlain(), and IG.Num.SampledDataElementDto.CopyToPlain().
The documentation for this class was generated from the following file:
iglib/igbase/numeric/approximation/sampleddata/SampledDataDto.cs