Doc: IGLib with source files: IGLib.Parsing.ParsableBase< CharType > Class Template Reference
IGLib.Parsing.ParsableBase< CharType > Class Template Reference abstract
Public Member Functions
abstract bool AreEqual (CharType ch1, CharType ch2)
Returns true if the specified characters are equal, false otherwise.
virtual IEnumerable< CharType > SubString (int startIndex, int length)
Returns a substring of Parsable starting at startIndex and of length length
IEnumerable< CharType > SubString (int startIndex)
virtual bool IsAt (int position, CharType ch)
Returns true if the specified character is at the specified position of the parsable.
virtual bool IsAt (int position, Func< CharType, bool > characterMatcher)
virtual bool IsAt (int position, IEnumerable< CharType > str)
virtual bool IsAt (int position, Func< IEnumerable< CharType >, bool > stringMatcher, int stringLength)
Properties
abstract int Length [get]
abstract CharType this[int i] [get]
Properties inherited from IGLib.Parsing.IParsable< CharType >
int Length [get]
CharType this[int i] [get]
Detailed Description
Type Constraints
CharType : struct
Definition at line 11 of file ParsableBase.cs.
Member Function Documentation
AreEqual()
abstract bool IGLib.Parsing.ParsableBase< CharType >.AreEqual (CharType ch1, CharType ch2) pure virtual
Returns true if the specified characters are equal, false otherwise.
Parameters
ch1 The first character to be compared.
ch2 The second character to be compared.
Returns
Referenced by IGLib.Parsing.ParsableBase< char >.IsAt().
SubString() [1/2]
virtual IEnumerable<CharType> IGLib.Parsing.ParsableBase< CharType >.SubString (int startIndex, int length) inline virtual
Returns a substring of Parsable starting at startIndex and of length length
Parameters
startIndex Starting position at which sub-string is taken.
length Number of characters in the returned substring.
Returns
The substring corresponding to parameters.
Implements IGLib.Parsing.IParsable< CharType >.
Definition at line 35 of file ParsableBase.cs.
Referenced by IGLib.Parsing.ParsableBase< char >.IsAt(), and IGLib.Parsing.ParsableBase< char >.SubString().
SubString() [2/2]
IEnumerable<CharType> IGLib.Parsing.ParsableBase< CharType >.SubString (int startIndex) inline
Implements IGLib.Parsing.IParsable< CharType >.
Definition at line 60 of file ParsableBase.cs.
IsAt() [1/4]
virtual bool IGLib.Parsing.ParsableBase< CharType >.IsAt (int position, CharType ch) inline virtual
Returns true if the specified character is at the specified position of the parsable.
Parameters
position Positio ofr which character is verified.
ch Character that is expected at position
Returns
Implements IGLib.Parsing.IParsable< CharType >.
Definition at line 70 of file ParsableBase.cs.
IsAt() [2/4]
virtual bool IGLib.Parsing.ParsableBase< CharType >.IsAt (int position, Func< CharType, bool > characterMatcher) inline virtual
Implements IGLib.Parsing.IParsable< CharType >.
Definition at line 85 of file ParsableBase.cs.
IsAt() [3/4]
virtual bool IGLib.Parsing.ParsableBase< CharType >.IsAt (int position, IEnumerable< CharType > str) inline virtual
Implements IGLib.Parsing.IParsable< CharType >.
Definition at line 100 of file ParsableBase.cs.
IsAt() [4/4]
virtual bool IGLib.Parsing.ParsableBase< CharType >.IsAt (int position, Func< IEnumerable< CharType >, bool > stringMatcher, int stringLength) inline virtual
Implements IGLib.Parsing.IParsable< CharType >.
Definition at line 116 of file ParsableBase.cs.
Property Documentation
Length
abstract int IGLib.Parsing.ParsableBase< CharType >.Length get
Definition at line 23 of file ParsableBase.cs.
Referenced by IGLib.Parsing.ParsableBase< char >.IsAt(), and IGLib.Parsing.ParsableBase< char >.SubString().
this[int i]
abstract CharType IGLib.Parsing.ParsableBase< CharType >.this[int i] get
Definition at line 27 of file ParsableBase.cs.
The documentation for this class was generated from the following file:
IGLibCore/src/IGLib.Core/Parsing/GenericParser/ParsableBase.cs