Doc: IGLib with source files: IG.Reflection.DerivedTypesRegistry< BaseType, InfoType > Class Template Reference
IG.Reflection.DerivedTypesRegistry< BaseType, InfoType > Class Template Reference
Registry of type data for types derived from BaseType .
Public Member Functions
DerivedTypesRegistry ()
virtual void Register (string typeName, InfoType typeData)
Registers the type information typeData under the name typeName .
virtual void Register (InfoType typeData)
Registeers the specified type information (typeData) under the registered type's (TypeInfoBase.ClassType) simple, fully qualidfied and assembly qualified names by calling the Register(string, InfoType)
virtual InfoType GetTypeData (string typeName, bool throwIfCannotCreate=true)
Tries to resolve and return the type data object that corresponds to the specified type name (typeName).
virtual Type GetType (string derivedTypeName, bool tryGetIfNotRegistered=false, bool throwIfCannotResolve=true)
Tries to resolve and return the type that corresponds to the specified type name (derivedTypeName).
virtual BaseType CreateInstance (string derivedTypeName, bool throwIfCannotCreate=true)
Attempts to create and return an instance of the type specified by its name (derivedTypeName). It first calls GetType(string, bool, bool) to get the type corresponding to derivedTypeName , then it uses reflection to invoke parameter-less constructor to create an instance. If parameterless constructor is also defined on the type then the method fails.
Properties
virtual object Lock = new object() [get]
Dictionary< string, InfoType > DerivedTypeNames = new Dictionary<string, InfoType>() [get]
Properties inherited from IG.Lib.ILockable
object Lock [get]
Detailed Description
Registry of type data for types derived from BaseType .
For each type in the registry, an InfoType object is registered that contains data and eventually some utilities related to that type, including the corresponding Type object.
Type can be registered under one or more type names, representing access key to the correspongding type info.
The registry of types provides services such as registration of type data under the specified type name(s), conversion of registered type names to the appropriate Type objects (such that they can be used in reflection, e.g. for creation of object instances), creation of object instances for types with parameterless constructor, etc.
Typically, a registry will be implemented as static property in some base class.
Template Parameters
BaseType Base type of the types that can be registered in the current registry.
InfoType Type of objects that hold information on the registered type and eventually some utilities for that type. Must derive from TypeInfoBase.
Type Constraints
InfoType : TypeInfoBase
Definition at line 28 of file DerivedTypesRegistry.cs.
Constructor & Destructor Documentation
DerivedTypesRegistry()
IG.Reflection.DerivedTypesRegistry< BaseType, InfoType >.DerivedTypesRegistry () inline
Definition at line 32 of file DerivedTypesRegistry.cs.
Member Function Documentation
Register() [1/2]
virtual void IG.Reflection.DerivedTypesRegistry< BaseType, InfoType >.Register (string typeName, InfoType typeData) inline virtual
Registers the type information typeData under the name typeName .
Type (TypeInfoBase.ClassType) must be derived from (or equal to) BaseType . Each specific type can be registered with several type names.
It is preeferable to use Register(InfoType) for type registration because this method registers the type under its actual names (simple, fully qualified and assembly qualified).
Parameters
typeName Name under which the type info is registered, case-sensitive. Any type can be registered under several names.
typeData Type information that is registered. It must be assissignable to typeData .
Definition at line 47 of file DerivedTypesRegistry.cs.
Referenced by IG.Reflection.DerivedTypesRegistry< BaseType, TypeInfoBase >.Register().
Register() [2/2]
virtual void IG.Reflection.DerivedTypesRegistry< BaseType, InfoType >.Register (InfoType typeData) inline virtual
Registeers the specified type information (typeData) under the registered type's (TypeInfoBase.ClassType) simple, fully qualidfied and assembly qualified names by calling the Register(string, InfoType)
Parameters
typeData Type data that is registered.
Definition at line 69 of file DerivedTypesRegistry.cs.
GetTypeData()
virtual InfoType IG.Reflection.DerivedTypesRegistry< BaseType, InfoType >.GetTypeData (string typeName, bool throwIfCannotCreate = true) inline virtual
Tries to resolve and return the type data object that corresponds to the specified type name (typeName).
The method tries to establish the type corresponding to its name by looking into registered types in the DerivedTypeNames registry. If not successful, it attempts to use reflection (Type.GetType(string)).
Parameters
typeName Tape name.
throwIfCannotCreate If true then exception is thrown when the type cannot be resolved. If false then nulll is returned instead. Default is true.
Returns
The type that corresponds to the specified type name.
Definition at line 92 of file DerivedTypesRegistry.cs.
Referenced by IG.Reflection.DerivedTypesRegistry< BaseType, TypeInfoBase >.GetType().
GetType()
virtual Type IG.Reflection.DerivedTypesRegistry< BaseType, InfoType >.GetType (string derivedTypeName, bool tryGetIfNotRegistered = false, bool throwIfCannotResolve = true) inline virtual
Tries to resolve and return the type that corresponds to the specified type name (derivedTypeName).
The method first tries to establish the type corresponding to the specified name by looking into registered types in the DerivedTypeNames registry. If not successful, it attempts to use reflection (Type.GetType(string)).
Parameters
derivedTypeName Name of the type for which a corresponding Type object is looked for. Default is true.
tryGetIfNotRegistered If true then the method tries to infer the type from the specified derivedTypeName even if the type information is not registered under derivedTypeName .
Returns
The type that corresponds to the specified type name.
Parameters
throwIfCannotResolve If true then exception is thrown when the type name cannot be resolved. If false then nulll is returned instead.
Definition at line 111 of file DerivedTypesRegistry.cs.
Referenced by IG.Reflection.DerivedTypesRegistry< BaseType, TypeInfoBase >.CreateInstance().
CreateInstance()
virtual BaseType IG.Reflection.DerivedTypesRegistry< BaseType, InfoType >.CreateInstance (string derivedTypeName, bool throwIfCannotCreate = true) inline virtual
Attempts to create and return an instance of the type specified by its name (derivedTypeName). It first calls GetType(string, bool, bool) to get the type corresponding to derivedTypeName , then it uses reflection to invoke parameter-less constructor to create an instance. If parameterless constructor is also defined on the type then the method fails.
Parameters
derivedTypeName Name of the type whose instance should be created and returned.
throwIfCannotCreate If true then exception is thrown when the object of the specified type cannot be resolved. If false then nulll is returned instead. Default is true.
Returns
Instance of the type whose name is provided, if successful. If not, either null is returned or exception thrown, dependent on the value of throwIfCannotCreate
Definition at line 154 of file DerivedTypesRegistry.cs.
Property Documentation
Lock
virtual object IG.Reflection.DerivedTypesRegistry< BaseType, InfoType >.Lock = new object() get
Definition at line 35 of file DerivedTypesRegistry.cs.
Referenced by IG.Reflection.DerivedTypesRegistry< BaseType, TypeInfoBase >.Register().
DerivedTypeNames
Dictionary<string, InfoType> IG.Reflection.DerivedTypesRegistry< BaseType, InfoType >.DerivedTypeNames = new Dictionary<string, InfoType>() get private
Definition at line 37 of file DerivedTypesRegistry.cs.
Referenced by IG.Reflection.DerivedTypesRegistry< BaseType, TypeInfoBase >.GetTypeData(), and IG.Reflection.DerivedTypesRegistry< BaseType, TypeInfoBase >.Register().
The documentation for this class was generated from the following file:
iglib/igbase/types_reflection/TypeRegistry/DerivedTypesRegistry.cs