Doc: IGLib with source files: IG.Lib.InterfaceInterpreterBase Class Reference
IG.Lib.InterfaceInterpreterBase Class Reference
Base class for interfaces with interpreters.
Public Member Functions
InterfaceInterpreterBase ()
InterfaceInterpreterBase (string commandFileName)
InterfaceInterpreterBase (string workingDirctory, string commandFileName)
Constructor.
InterfaceInterpreterBase (string commandDirectory, string startDirectory, string commandFileName)
Constructor.
virtual void ResetCommands ()
virtual void Append (string str)
Appends a literal string to the contents of the command file plus a newline character.
virtual void AppendLine (string str)
Appends a literal string to the contents of the command file.
virtual void AppendLine ()
virtual void AppendIndent ()
Appends indentation to the contents of the command file.
virtual void AppendComment (string str, bool withNewlines)
Appends a vomment to the contents of the command file.
virtual void StartCodeBlock ()
Starts a new code block in the interpreter command file contents.
virtual void EndCodeBlock ()
Ends a code block in the interpreter command file contents.
virtual void StartCommand (string commandName)
Starts a new command in the interpreter command file contents.
virtual void EndCommand ()
Ends (finalizes) a command in the interpreter command file contents.
virtual void AppendCommandArgumentSeparatorIfNecessary ()
Appends a command line separator to the interpreter command file contents, if necessary (i.e. if any arguments have already been written to the command file contents).
virtual void AppendValue (int value)
Appends an integer value to the interpreter command file contents.
virtual void AppendValue (double value)
Appends a double value to the interpreter command file contents.
virtual void AppendValue (bool value)
Appends a boolean value to the interpreter command file contents.
virtual void AppendValue (string value)
Appends a string value to the interpreter command file contents.
virtual void AppendValue (IVector value)
Appends a vector value to the interpreter command file contents.
virtual void AppendValue (IMatrix value)
Appends a matrix value to the interpreter command file contents.
virtual void AppendCommandArgumentVariableReference (string variableName)
Appends a variable reference to the current argument block.
virtual void AppendCommandArgument (int value)
Appends an integer argument to the command argument block of the interpreter command file.
virtual void AppendCommandArgument (double value)
Appends a double argument to the command argument block of the interpreter command file.
virtual void AppendCommandArgument (bool value)
Appends a boolean argument to the command argument block of the interpreter command file.
virtual void AppendCommandArgument (string value)
Appends a string argument to the command argument block of the interpreter command file.
virtual void AppendCommandArgumentPlain (string value)
Appends a plain string argument (without decoration such as double quotes) to the command argument block of the interpreter command file.
virtual void AppendCommandArgument (IVector value)
Appends a vector argument to the command argument block of the interpreter command file.
virtual void AppendCommandArgument (IMatrix value)
Appends a matrix argument to the command argument block of the interpreter command file.
virtual void WriteCommandFile ()
Writes the current contents of the interpreter command file to the physical file. If the file exists then it is overwritten. After this method is called, ResetCommands() should be called if the object will be further used.
virtual void WriteAppendToCommandFile ()
Appends the current contents of the interpreter command file to the physical file. After this method is called, ResetCommands() should be called if the object will be further used.
virtual void WriteAndRunCommandFile ()
Writes interpreter command file and runs it. After this method is called, ResetCommands() should be called if the object will be further used.
Protected Member Functions
virtual void AppendCommandVariableReference (string variableName)
Appends a variable reference to the contents of the interpreter command file.
virtual void WriteCommandFile (bool appendContents)
Writes the current contents of the interpreter command file to the physical file. After this method is called, ResetCommands() should be called if the object will be further used.
virtual void RunCommandFile ()
Runs the interpreter command file.
Properties
object Lock [get]
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
virtual StringBuilder CommandBuilder [get, protected set]
Command builder.
virtual string CommandFileString [get]
Gets current state of commands as stirng.
virtual string InterpreterCommand [get, protected set]
Gets or sets the command that invokes the interpreter. This may be a full path to the executable, or only executable name if the executable is located in a directory included in path.
virtual string CommandDirectory [get, protected set]
Gets or sets the directory where command file will be located.
virtual string DefaultCommandFileName [get]
Gets the default command file name for the current interpreter.
virtual string CommandFileName [get, protected set]
Gets or sets the command file name where interpreter commands will be written.
virtual string CommandFilePath [get]
Gets path to command file.
virtual string StartingDirectory [get, protected set]
Gets or sets the command that invokes the interpreter.
virtual string CommandIntroduction [get, protected set]
String that introduces a new command (and is written before the command name in the command file). Usually a newline.
virtual string CommandArgumentBlockBegin [get, protected set]
String that begins command arguments block.
virtual string CommandArgumentBlockEnd [get, protected set]
String that ends command argument block.
virtual string CommandArgumentSeparator [get, protected set]
String that begins command arguments block.
virtual bool CommandArgumentsInNewLines [get, set]
Whether command arguments are listed in separate lines or not.
virtual int CommandArgumentCount [get, protected set]
The number of current argument.
virtual bool IsWithinArgumentBlock [get, protected set]
The number of current argument.
virtual string CodeBlockBegin [get, protected set]
String that begins a code block in interpreted files.
virtual string CodeBlockEnd [get, protected set]
String that ends a code block in interpreted files.
virtual string VariableReferenceBegin [get, protected set]
String that begins a code block in interpreted files.
virtual string VariableReferenceEnd [get, protected set]
String that ends a code block in interpreted files.
virtual string IndentationString [get, set]
String used for indentation of code.
virtual int IndentationLevel [get, protected set]
Indentation level - how many indentation strings are added before each new row.
virtual string CommentBegin [get, protected set]
String that begins a comment.
virtual string CommentEnd [get, protected set]
String that ends a comment.
Properties inherited from IG.Lib.ILockable
object Lock [get]
Private Attributes
object _mainLock = new object()
StringBuilder _commandBuilder = new StringBuilder()
string _interpreterCommand
string _commandDirectory
string _startingDirectory
string _commandFileName
string _commandIndroduction = Environment.NewLine
string _commandArgumentBlockBegin = " (" + Environment.NewLine + " "
string _commandArgumentBlockEnd = ") " + Environment.NewLine
string _commandArgumentSeparator = ", "
bool _commandArgumentsInNewLines = true
int _commandArgumentCount = 0
bool _isWithinArgumentBlock = false
string _codeBlockBegin = Environment.NewLine + "{" + Environment.NewLine
string _codeBlockEnd = Environment.NewLine + "}" + Environment.NewLine
string _variableReferenceBegin = "$"
string _variableReferenceEnd = ""
string _indentationString = " "
int _indentationLevel = 0
string _commentBegin = "/* "
string _commentEnd = " */ "
Detailed Description
Base class for interfaces with interpreters.
$A Igor Jul09;
Definition at line 20 of file InterfaceInterpreterBase.cs.
Constructor & Destructor Documentation
InterfaceInterpreterBase() [1/4]
IG.Lib.InterfaceInterpreterBase.InterfaceInterpreterBase () inline
Definition at line 25 of file InterfaceInterpreterBase.cs.
References IG.Lib.InterfaceInterpreterBase.CommandFileName, and IG.Lib.InterfaceInterpreterBase.DefaultCommandFileName.
InterfaceInterpreterBase() [2/4]
IG.Lib.InterfaceInterpreterBase.InterfaceInterpreterBase (string commandFileName) inline
Definition at line 29 of file InterfaceInterpreterBase.cs.
InterfaceInterpreterBase() [3/4]
IG.Lib.InterfaceInterpreterBase.InterfaceInterpreterBase (string workingDirctory, string commandFileName) inline
Constructor.
Parameters
workingDirctory Directory whre command file is written to and working directory for interpreter's application. Relative or absolute path.
commandFileName Name of the command file to which commands are written and which is interpreted by the interpreter.
Definition at line 38 of file InterfaceInterpreterBase.cs.
InterfaceInterpreterBase() [4/4]
IG.Lib.InterfaceInterpreterBase.InterfaceInterpreterBase (string commandDirectory, string startDirectory, string commandFileName) inline
Constructor.
Parameters
commandDirectory Directory whre command file is written to. Relative or absolute path.
startDirectory Directory in which interpreter application is started. Relative or absolute path.
commandFileName Name of the command file to which commands are written and which is interpreted by the interpreter.
Definition at line 47 of file InterfaceInterpreterBase.cs.
References IG.Lib.InterfaceInterpreterBase.CodeBlockBegin, IG.Lib.InterfaceInterpreterBase.CodeBlockEnd, IG.Lib.InterfaceInterpreterBase.CommandArgumentBlockBegin, IG.Lib.InterfaceInterpreterBase.CommandArgumentBlockEnd, IG.Lib.InterfaceInterpreterBase.CommandArgumentSeparator, IG.Lib.InterfaceInterpreterBase.CommandArgumentsInNewLines, IG.Lib.InterfaceInterpreterBase.CommandDirectory, IG.Lib.InterfaceInterpreterBase.CommandFileName, IG.Lib.InterfaceInterpreterBase.CommandIntroduction, IG.Lib.InterfaceInterpreterBase.CommentBegin, IG.Lib.InterfaceInterpreterBase.CommentEnd, IG.Lib.InterfaceInterpreterBase.IndentationString, IG.Lib.InterfaceInterpreterBase.StartingDirectory, IG.Lib.InterfaceInterpreterBase.VariableReferenceBegin, and IG.Lib.InterfaceInterpreterBase.VariableReferenceEnd.
Member Function Documentation
ResetCommands()
virtual void IG.Lib.InterfaceInterpreterBase.ResetCommands () inline virtual
Definition at line 338 of file InterfaceInterpreterBase.cs.
References IG.Lib.InterfaceInterpreterBase.CommandBuilder.
Append()
virtual void IG.Lib.InterfaceInterpreterBase.Append (string str) inline virtual
Appends a literal string to the contents of the command file plus a newline character.
Parameters
str String to be appended.
Definition at line 345 of file InterfaceInterpreterBase.cs.
References IG.Lib.InterfaceInterpreterBase.CommandBuilder, and IG.Lib.InterfaceInterpreterBase.Lock.
Referenced by IG.Lib.InterfaceInterpreterBase.AppendCommandArgumentPlain(), IG.Lib.InterfaceInterpreterBase.AppendCommandArgumentSeparatorIfNecessary(), IG.Lib.InterfaceInterpreterBase.AppendCommandVariableReference(), IG.Lib.InterfaceInterpreterBase.AppendComment(), IG.Lib.InterfaceInterpreterBase.AppendIndent(), IG.Lib.InterfaceInterpreterBase.AppendLine(), IG.Lib.InterfaceInverse.AppendValue(), IG.Lib.InterfaceInterpreterBase.AppendValue(), IG.Lib.InterfaceInterpreterBase.EndCodeBlock(), IG.Lib.InterfaceInterpreterBase.EndCommand(), IG.Lib.InterfaceInverse.SetVariable(), IG.Lib.InterfaceInverse.StartAnalysisBlock(), IG.Lib.InterfaceInterpreterBase.StartCodeBlock(), and IG.Lib.InterfaceInterpreterBase.StartCommand().
AppendLine() [1/2]
virtual void IG.Lib.InterfaceInterpreterBase.AppendLine (string str) inline virtual
Appends a literal string to the contents of the command file.
Parameters
str String to be appended.
Definition at line 355 of file InterfaceInterpreterBase.cs.
References IG.Lib.InterfaceInterpreterBase.Append().
AppendLine() [2/2]
virtual void IG.Lib.InterfaceInterpreterBase.AppendLine () inline virtual
Definition at line 360 of file InterfaceInterpreterBase.cs.
References IG.Lib.InterfaceInterpreterBase.Append().
Referenced by IG.Lib.InterfaceInterpreterBase.AppendCommandArgumentSeparatorIfNecessary(), IG.Lib.InterfaceInterpreterBase.AppendComment(), IG.Lib.InterfaceInverse.AppendValue(), IG.Lib.InterfaceInverse.EndAnalysisBlock(), IG.Lib.InterfaceInterpreterBase.EndCodeBlock(), IG.Lib.InterfaceInterpreterBase.EndCommand(), IG.Lib.InterfaceInverse.StartAnalysisBlock(), IG.Lib.InterfaceInterpreterBase.StartCodeBlock(), and IG.Lib.InterfaceInterpreterBase.StartCommand().
AppendIndent()
virtual void IG.Lib.InterfaceInterpreterBase.AppendIndent () inline virtual
Appends indentation to the contents of the command file.
Definition at line 366 of file InterfaceInterpreterBase.cs.
References IG.Lib.InterfaceInterpreterBase.Append(), IG.Lib.InterfaceInterpreterBase.IndentationLevel, IG.Lib.InterfaceInterpreterBase.IndentationString, and IG.Lib.InterfaceInterpreterBase.Lock.
Referenced by IG.Lib.InterfaceInterpreterBase.AppendCommandArgumentSeparatorIfNecessary(), IG.Lib.InterfaceInterpreterBase.AppendComment(), IG.Lib.InterfaceInverse.AppendValue(), IG.Lib.InterfaceInterpreterBase.EndCodeBlock(), IG.Lib.InterfaceInterpreterBase.EndCommand(), IG.Lib.InterfaceInverse.StartAnalysisBlock(), IG.Lib.InterfaceInterpreterBase.StartCodeBlock(), and IG.Lib.InterfaceInterpreterBase.StartCommand().
AppendComment()
virtual void IG.Lib.InterfaceInterpreterBase.AppendComment (string str, bool withNewlines) inline virtual
Appends a vomment to the contents of the command file.
Parameters
str Comment text.
withNewlines Whether comment is appended in a separate line.
Definition at line 378 of file InterfaceInterpreterBase.cs.
References IG.Lib.InterfaceInterpreterBase.Append(), IG.Lib.InterfaceInterpreterBase.AppendIndent(), IG.Lib.InterfaceInterpreterBase.AppendLine(), IG.Lib.InterfaceInterpreterBase.CommentBegin, IG.Lib.InterfaceInterpreterBase.CommentEnd, and IG.Lib.InterfaceInterpreterBase.Lock.
StartCodeBlock()
virtual void IG.Lib.InterfaceInterpreterBase.StartCodeBlock () inline virtual
Starts a new code block in the interpreter command file contents.
Definition at line 398 of file InterfaceInterpreterBase.cs.
References IG.Lib.InterfaceInterpreterBase.Append(), IG.Lib.InterfaceInterpreterBase.AppendIndent(), IG.Lib.InterfaceInterpreterBase.AppendLine(), IG.Lib.InterfaceInterpreterBase.CodeBlockBegin, IG.Lib.InterfaceInterpreterBase.IndentationLevel, and IG.Lib.InterfaceInterpreterBase.Lock.
Referenced by IG.Lib.InterfaceInverse.StartAnalysisBlock().
EndCodeBlock()
virtual void IG.Lib.InterfaceInterpreterBase.EndCodeBlock () inline virtual
Ends a code block in the interpreter command file contents.
Definition at line 411 of file InterfaceInterpreterBase.cs.
References IG.Lib.InterfaceInterpreterBase.Append(), IG.Lib.InterfaceInterpreterBase.AppendIndent(), IG.Lib.InterfaceInterpreterBase.AppendLine(), IG.Lib.InterfaceInterpreterBase.CodeBlockEnd, IG.Lib.InterfaceInterpreterBase.IndentationLevel, and IG.Lib.InterfaceInterpreterBase.Lock.
Referenced by IG.Lib.InterfaceInverse.EndAnalysisBlock().
StartCommand()
virtual void IG.Lib.InterfaceInterpreterBase.StartCommand (string commandName) inline virtual
Starts a new command in the interpreter command file contents.
Parameters
commandName Name of the command.
Definition at line 425 of file InterfaceInterpreterBase.cs.
References IG.Lib.InterfaceInterpreterBase.Append(), IG.Lib.InterfaceInterpreterBase.AppendIndent(), IG.Lib.InterfaceInterpreterBase.AppendLine(), IG.Lib.InterfaceInterpreterBase.CommandArgumentBlockBegin, IG.Lib.InterfaceInterpreterBase.CommandArgumentCount, IG.Lib.InterfaceInterpreterBase.CommandArgumentsInNewLines, IG.Lib.InterfaceInterpreterBase.CommandIntroduction, IG.Lib.InterfaceInterpreterBase.IndentationLevel, IG.Lib.InterfaceInterpreterBase.IsWithinArgumentBlock, and IG.Lib.InterfaceInterpreterBase.Lock.
Referenced by IG.Lib.InterfaceInverse.Analyse(), IG.Lib.InterfaceInverse.FileAnalysis(), IG.Lib.InterfaceInverse.Interactive(), IG.Lib.InterfaceInverse.Interpret(), IG.Lib.InterfaceInverse.MinSimplex(), IG.Lib.InterfaceInverse.NlpSimplex(), IG.Lib.InterfaceInverse.NlpSimplexBoundConstr(), IG.Lib.InterfaceInverse.SetVariable(), IG.Lib.InterfaceInverse.TabAn1d(), and IG.Lib.InterfaceInverse.TabAn2d().
EndCommand()
virtual void IG.Lib.InterfaceInterpreterBase.EndCommand () inline virtual
Ends (finalizes) a command in the interpreter command file contents.
Definition at line 455 of file InterfaceInterpreterBase.cs.
References IG.Lib.InterfaceInterpreterBase.Append(), IG.Lib.InterfaceInterpreterBase.AppendIndent(), IG.Lib.InterfaceInterpreterBase.AppendLine(), IG.Lib.InterfaceInterpreterBase.CommandArgumentBlockEnd, IG.Lib.InterfaceInterpreterBase.CommandArgumentCount, IG.Lib.InterfaceInterpreterBase.CommandArgumentsInNewLines, IG.Lib.InterfaceInterpreterBase.IndentationLevel, IG.Lib.InterfaceInterpreterBase.IsWithinArgumentBlock, and IG.Lib.InterfaceInterpreterBase.Lock.
Referenced by IG.Lib.InterfaceInverse.Analyse(), IG.Lib.InterfaceInverse.FileAnalysis(), IG.Lib.InterfaceInverse.Interactive(), IG.Lib.InterfaceInverse.Interpret(), IG.Lib.InterfaceInverse.MinSimplex(), IG.Lib.InterfaceInverse.NlpSimplex(), IG.Lib.InterfaceInverse.NlpSimplexBoundConstr(), IG.Lib.InterfaceInverse.SetVariable(), IG.Lib.InterfaceInverse.TabAn1d(), and IG.Lib.InterfaceInverse.TabAn2d().
AppendCommandArgumentSeparatorIfNecessary()
virtual void IG.Lib.InterfaceInterpreterBase.AppendCommandArgumentSeparatorIfNecessary () inline virtual
Appends a command line separator to the interpreter command file contents, if necessary (i.e. if any arguments have already been written to the command file contents).
Definition at line 483 of file InterfaceInterpreterBase.cs.
References IG.Lib.InterfaceInterpreterBase.Append(), IG.Lib.InterfaceInterpreterBase.AppendIndent(), IG.Lib.InterfaceInterpreterBase.AppendLine(), IG.Lib.InterfaceInterpreterBase.CommandArgumentCount, IG.Lib.InterfaceInterpreterBase.CommandArgumentSeparator, IG.Lib.InterfaceInterpreterBase.CommandArgumentsInNewLines, IG.Lib.InterfaceInterpreterBase.IsWithinArgumentBlock, and IG.Lib.InterfaceInterpreterBase.Lock.
Referenced by IG.Lib.InterfaceInterpreterBase.AppendCommandArgument(), IG.Lib.InterfaceInterpreterBase.AppendCommandArgumentPlain(), IG.Lib.InterfaceInterpreterBase.AppendCommandArgumentVariableReference(), and IG.Lib.InterfaceInverse.SetVariable().
AppendValue() [1/6]
virtual void IG.Lib.InterfaceInterpreterBase.AppendValue (int value) inline virtual
Appends an integer value to the interpreter command file contents.
Parameters
value Value to be appended.
Definition at line 501 of file InterfaceInterpreterBase.cs.
References IG.Lib.InterfaceInterpreterBase.Append().
Referenced by IG.Lib.InterfaceInterpreterBase.AppendCommandArgument().
AppendValue() [2/6]
virtual void IG.Lib.InterfaceInterpreterBase.AppendValue (double value) inline virtual
Appends a double value to the interpreter command file contents.
Parameters
value Value to be appended.
Definition at line 508 of file InterfaceInterpreterBase.cs.
References IG.Lib.InterfaceInterpreterBase.Append().
AppendValue() [3/6]
virtual void IG.Lib.InterfaceInterpreterBase.AppendValue (bool value) inline virtual
Appends a boolean value to the interpreter command file contents.
Parameters
value Value to be appended.
Reimplemented in IG.Lib.InterfaceInverse.
Definition at line 515 of file InterfaceInterpreterBase.cs.
References IG.Lib.InterfaceInterpreterBase.Append().
AppendValue() [4/6]
virtual void IG.Lib.InterfaceInterpreterBase.AppendValue (string value) inline virtual
Appends a string value to the interpreter command file contents.
Parameters
value Value to be appended.
Reimplemented in IG.Lib.InterfaceInverse.
Definition at line 522 of file InterfaceInterpreterBase.cs.
References IG.Lib.InterfaceInterpreterBase.Append().
AppendValue() [5/6]
virtual void IG.Lib.InterfaceInterpreterBase.AppendValue (IVector value) inline virtual
Appends a vector value to the interpreter command file contents.
Parameters
value Value to be appended.
Reimplemented in IG.Lib.InterfaceInverse.
Definition at line 529 of file InterfaceInterpreterBase.cs.
AppendValue() [6/6]
virtual void IG.Lib.InterfaceInterpreterBase.AppendValue (IMatrix value) inline virtual
Appends a matrix value to the interpreter command file contents.
Parameters
value Value to be appended.
Reimplemented in IG.Lib.InterfaceInverse.
Definition at line 537 of file InterfaceInterpreterBase.cs.
AppendCommandVariableReference()
virtual void IG.Lib.InterfaceInterpreterBase.AppendCommandVariableReference (string variableName) inline protected virtual
Appends a variable reference to the contents of the interpreter command file.
Parameters
variableName Name of the variable whose reference is appended.
Definition at line 546 of file InterfaceInterpreterBase.cs.
References IG.Lib.InterfaceInterpreterBase.Append(), IG.Lib.InterfaceInterpreterBase.Lock, IG.Lib.InterfaceInterpreterBase.VariableReferenceBegin, and IG.Lib.InterfaceInterpreterBase.VariableReferenceEnd.
Referenced by IG.Lib.InterfaceInterpreterBase.AppendCommandArgumentVariableReference().
AppendCommandArgumentVariableReference()
virtual void IG.Lib.InterfaceInterpreterBase.AppendCommandArgumentVariableReference (string variableName) inline virtual
Appends a variable reference to the current argument block.
Parameters
variableName Name of the variable whose reference is appended.
Definition at line 558 of file InterfaceInterpreterBase.cs.
References IG.Lib.InterfaceInterpreterBase.AppendCommandArgumentSeparatorIfNecessary(), IG.Lib.InterfaceInterpreterBase.AppendCommandVariableReference(), and IG.Lib.InterfaceInterpreterBase.Lock.
AppendCommandArgument() [1/6]
virtual void IG.Lib.InterfaceInterpreterBase.AppendCommandArgument (int value) inline virtual
Appends an integer argument to the command argument block of the interpreter command file.
Parameters
value Value of the argument that is appended.
Definition at line 569 of file InterfaceInterpreterBase.cs.
References IG.Lib.InterfaceInterpreterBase.AppendCommandArgumentSeparatorIfNecessary(), IG.Lib.InterfaceInterpreterBase.AppendValue(), IG.Lib.InterfaceInterpreterBase.IsWithinArgumentBlock, and IG.Lib.InterfaceInterpreterBase.Lock.
Referenced by IG.Lib.InterfaceInverse.Analyse(), IG.Lib.InterfaceInverse.FileAnalysis(), IG.Lib.InterfaceInverse.Interactive(), IG.Lib.InterfaceInverse.Interpret(), IG.Lib.InterfaceInverse.MinSimplex(), IG.Lib.InterfaceInverse.NlpSimplex(), IG.Lib.InterfaceInverse.NlpSimplexBoundConstr(), IG.Lib.InterfaceInverse.SetVariable(), IG.Lib.InterfaceInverse.TabAn1d(), and IG.Lib.InterfaceInverse.TabAn2d().
AppendCommandArgument() [2/6]
virtual void IG.Lib.InterfaceInterpreterBase.AppendCommandArgument (double value) inline virtual
Appends a double argument to the command argument block of the interpreter command file.
Parameters
value Value of the argument that is appended.
Definition at line 583 of file InterfaceInterpreterBase.cs.
References IG.Lib.InterfaceInterpreterBase.AppendCommandArgumentSeparatorIfNecessary(), IG.Lib.InterfaceInterpreterBase.AppendValue(), IG.Lib.InterfaceInterpreterBase.IsWithinArgumentBlock, and IG.Lib.InterfaceInterpreterBase.Lock.
AppendCommandArgument() [3/6]
virtual void IG.Lib.InterfaceInterpreterBase.AppendCommandArgument (bool value) inline virtual
Appends a boolean argument to the command argument block of the interpreter command file.
Parameters
value Value of the argument that is appended.
Definition at line 596 of file InterfaceInterpreterBase.cs.
References IG.Lib.InterfaceInterpreterBase.AppendCommandArgumentSeparatorIfNecessary(), IG.Lib.InterfaceInterpreterBase.AppendValue(), IG.Lib.InterfaceInterpreterBase.IsWithinArgumentBlock, and IG.Lib.InterfaceInterpreterBase.Lock.
AppendCommandArgument() [4/6]
virtual void IG.Lib.InterfaceInterpreterBase.AppendCommandArgument (string value) inline virtual
Appends a string argument to the command argument block of the interpreter command file.
Parameters
value Value of the argument that is appended.
Definition at line 609 of file InterfaceInterpreterBase.cs.
References IG.Lib.InterfaceInterpreterBase.AppendCommandArgumentSeparatorIfNecessary(), IG.Lib.InterfaceInterpreterBase.AppendValue(), IG.Lib.InterfaceInterpreterBase.IsWithinArgumentBlock, and IG.Lib.InterfaceInterpreterBase.Lock.
AppendCommandArgumentPlain()
virtual void IG.Lib.InterfaceInterpreterBase.AppendCommandArgumentPlain (string value) inline virtual
Appends a plain string argument (without decoration such as double quotes) to the command argument block of the interpreter command file.
Parameters
value Value of the argument that is appended.
Definition at line 622 of file InterfaceInterpreterBase.cs.
References IG.Lib.InterfaceInterpreterBase.Append(), IG.Lib.InterfaceInterpreterBase.AppendCommandArgumentSeparatorIfNecessary(), IG.Lib.InterfaceInterpreterBase.IsWithinArgumentBlock, and IG.Lib.InterfaceInterpreterBase.Lock.
AppendCommandArgument() [5/6]
virtual void IG.Lib.InterfaceInterpreterBase.AppendCommandArgument (IVector value) inline virtual
Appends a vector argument to the command argument block of the interpreter command file.
Parameters
value Value of the argument that is appended.
Definition at line 635 of file InterfaceInterpreterBase.cs.
References IG.Lib.InterfaceInterpreterBase.AppendCommandArgumentSeparatorIfNecessary(), IG.Lib.InterfaceInterpreterBase.AppendValue(), IG.Lib.InterfaceInterpreterBase.IsWithinArgumentBlock, and IG.Lib.InterfaceInterpreterBase.Lock.
AppendCommandArgument() [6/6]
virtual void IG.Lib.InterfaceInterpreterBase.AppendCommandArgument (IMatrix value) inline virtual
Appends a matrix argument to the command argument block of the interpreter command file.
Parameters
value Value of the argument that is appended.
Definition at line 648 of file InterfaceInterpreterBase.cs.
References IG.Lib.InterfaceInterpreterBase.AppendCommandArgumentSeparatorIfNecessary(), IG.Lib.InterfaceInterpreterBase.AppendValue(), IG.Lib.InterfaceInterpreterBase.IsWithinArgumentBlock, and IG.Lib.InterfaceInterpreterBase.Lock.
WriteCommandFile() [1/2]
virtual void IG.Lib.InterfaceInterpreterBase.WriteCommandFile (bool appendContents) inline protected virtual
Writes the current contents of the interpreter command file to the physical file. After this method is called, ResetCommands() should be called if the object will be further used.
Parameters
appendContents Whether file contents are appended.
Definition at line 665 of file InterfaceInterpreterBase.cs.
References IG.Lib.InterfaceInterpreterBase.CommandFilePath, IG.Lib.InterfaceInterpreterBase.CommandFileString, and IG.Lib.InterfaceInterpreterBase.Lock.
WriteCommandFile() [2/2]
virtual void IG.Lib.InterfaceInterpreterBase.WriteCommandFile () inline virtual
Writes the current contents of the interpreter command file to the physical file. If the file exists then it is overwritten. After this method is called, ResetCommands() should be called if the object will be further used.
Definition at line 679 of file InterfaceInterpreterBase.cs.
Referenced by IG.Lib.InterfaceInterpreterBase.WriteAndRunCommandFile(), and IG.Lib.InterfaceInterpreterBase.WriteAppendToCommandFile().
WriteAppendToCommandFile()
virtual void IG.Lib.InterfaceInterpreterBase.WriteAppendToCommandFile () inline virtual
Appends the current contents of the interpreter command file to the physical file. After this method is called, ResetCommands() should be called if the object will be further used.
Definition at line 686 of file InterfaceInterpreterBase.cs.
References IG.Lib.InterfaceInterpreterBase.WriteCommandFile().
RunCommandFile()
virtual void IG.Lib.InterfaceInterpreterBase.RunCommandFile () inline protected virtual
Runs the interpreter command file.
Definition at line 692 of file InterfaceInterpreterBase.cs.
References IG.Lib.InterfaceInterpreterBase.CommandFilePath, IG.Lib.InterfaceInterpreterBase.InterpreterCommand, and IG.Lib.InterfaceInterpreterBase.Lock.
Referenced by IG.Lib.InterfaceInterpreterBase.WriteAndRunCommandFile().
WriteAndRunCommandFile()
virtual void IG.Lib.InterfaceInterpreterBase.WriteAndRunCommandFile () inline virtual
Writes interpreter command file and runs it. After this method is called, ResetCommands() should be called if the object will be further used.
Definition at line 728 of file InterfaceInterpreterBase.cs.
References IG.Lib.InterfaceInterpreterBase.Lock, IG.Lib.InterfaceInterpreterBase.RunCommandFile(), and IG.Lib.InterfaceInterpreterBase.WriteCommandFile().
Member Data Documentation
_mainLock
object IG.Lib.InterfaceInterpreterBase._mainLock = new object() private
Definition at line 73 of file InterfaceInterpreterBase.cs.
_commandBuilder
StringBuilder IG.Lib.InterfaceInterpreterBase._commandBuilder = new StringBuilder() private
Definition at line 84 of file InterfaceInterpreterBase.cs.
_interpreterCommand
string IG.Lib.InterfaceInterpreterBase._interpreterCommand private
Definition at line 86 of file InterfaceInterpreterBase.cs.
_commandDirectory
string IG.Lib.InterfaceInterpreterBase._commandDirectory private
Definition at line 88 of file InterfaceInterpreterBase.cs.
_startingDirectory
string IG.Lib.InterfaceInterpreterBase._startingDirectory private
Definition at line 90 of file InterfaceInterpreterBase.cs.
_commandFileName
string IG.Lib.InterfaceInterpreterBase._commandFileName private
Definition at line 92 of file InterfaceInterpreterBase.cs.
_commandIndroduction
string IG.Lib.InterfaceInterpreterBase._commandIndroduction = Environment.NewLine private
Definition at line 96 of file InterfaceInterpreterBase.cs.
_commandArgumentBlockBegin
string IG.Lib.InterfaceInterpreterBase._commandArgumentBlockBegin = " (" + Environment.NewLine + " " private
Definition at line 97 of file InterfaceInterpreterBase.cs.
_commandArgumentBlockEnd
string IG.Lib.InterfaceInterpreterBase._commandArgumentBlockEnd = ") " + Environment.NewLine private
Definition at line 98 of file InterfaceInterpreterBase.cs.
_commandArgumentSeparator
string IG.Lib.InterfaceInterpreterBase._commandArgumentSeparator = ", " private
Definition at line 99 of file InterfaceInterpreterBase.cs.
_commandArgumentsInNewLines
bool IG.Lib.InterfaceInterpreterBase._commandArgumentsInNewLines = true private
Definition at line 100 of file InterfaceInterpreterBase.cs.
_commandArgumentCount
int IG.Lib.InterfaceInterpreterBase._commandArgumentCount = 0 private
Definition at line 101 of file InterfaceInterpreterBase.cs.
_isWithinArgumentBlock
bool IG.Lib.InterfaceInterpreterBase._isWithinArgumentBlock = false private
Definition at line 102 of file InterfaceInterpreterBase.cs.
_codeBlockBegin
string IG.Lib.InterfaceInterpreterBase._codeBlockBegin = Environment.NewLine + "{" + Environment.NewLine private
Definition at line 103 of file InterfaceInterpreterBase.cs.
_codeBlockEnd
string IG.Lib.InterfaceInterpreterBase._codeBlockEnd = Environment.NewLine + "}" + Environment.NewLine private
Definition at line 104 of file InterfaceInterpreterBase.cs.
_variableReferenceBegin
string IG.Lib.InterfaceInterpreterBase._variableReferenceBegin = "$" private
Definition at line 105 of file InterfaceInterpreterBase.cs.
_variableReferenceEnd
string IG.Lib.InterfaceInterpreterBase._variableReferenceEnd = "" private
Definition at line 106 of file InterfaceInterpreterBase.cs.
_indentationString
string IG.Lib.InterfaceInterpreterBase._indentationString = " " private
Definition at line 107 of file InterfaceInterpreterBase.cs.
_indentationLevel
int IG.Lib.InterfaceInterpreterBase._indentationLevel = 0 private
Definition at line 108 of file InterfaceInterpreterBase.cs.
_commentBegin
string IG.Lib.InterfaceInterpreterBase._commentBegin = "/* " private
Definition at line 109 of file InterfaceInterpreterBase.cs.
_commentEnd
string IG.Lib.InterfaceInterpreterBase._commentEnd = " */ " private
Definition at line 110 of file InterfaceInterpreterBase.cs.
Property Documentation
Lock
object IG.Lib.InterfaceInterpreterBase.Lock get
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
Definition at line 78 of file InterfaceInterpreterBase.cs.
Referenced by IG.Lib.InterfaceInterpreterBase.Append(), IG.Lib.InterfaceInterpreterBase.AppendCommandArgument(), IG.Lib.InterfaceInterpreterBase.AppendCommandArgumentPlain(), IG.Lib.InterfaceInterpreterBase.AppendCommandArgumentSeparatorIfNecessary(), IG.Lib.InterfaceInterpreterBase.AppendCommandArgumentVariableReference(), IG.Lib.InterfaceInterpreterBase.AppendCommandVariableReference(), IG.Lib.InterfaceInterpreterBase.AppendComment(), IG.Lib.InterfaceInterpreterBase.AppendIndent(), IG.Lib.InterfaceInterpreterBase.EndCodeBlock(), IG.Lib.InterfaceInterpreterBase.EndCommand(), IG.Lib.InterfaceInterpreterBase.RunCommandFile(), IG.Lib.InterfaceInterpreterBase.StartCodeBlock(), IG.Lib.InterfaceInterpreterBase.StartCommand(), IG.Lib.InterfaceInterpreterBase.WriteAndRunCommandFile(), and IG.Lib.InterfaceInterpreterBase.WriteCommandFile().
CommandBuilder
virtual StringBuilder IG.Lib.InterfaceInterpreterBase.CommandBuilder get protected set
Command builder.
Definition at line 114 of file InterfaceInterpreterBase.cs.
Referenced by IG.Lib.InterfaceInterpreterBase.Append(), and IG.Lib.InterfaceInterpreterBase.ResetCommands().
CommandFileString
virtual string IG.Lib.InterfaceInterpreterBase.CommandFileString get
Gets current state of commands as stirng.
Definition at line 129 of file InterfaceInterpreterBase.cs.
Referenced by IG.Lib.InterfaceInterpreterBase.WriteCommandFile().
InterpreterCommand
virtual string IG.Lib.InterfaceInterpreterBase.InterpreterCommand get protected set
Gets or sets the command that invokes the interpreter. This may be a full path to the executable, or only executable name if the executable is located in a directory included in path.
Definition at line 138 of file InterfaceInterpreterBase.cs.
Referenced by IG.Lib.InterfaceInterpreterBase.RunCommandFile().
CommandDirectory
virtual string IG.Lib.InterfaceInterpreterBase.CommandDirectory get protected set
Gets or sets the directory where command file will be located.
Definition at line 154 of file InterfaceInterpreterBase.cs.
Referenced by IG.Lib.InterfaceInterpreterBase.InterfaceInterpreterBase(), and IG.Lib.InterfaceInverse.InterfaceInverse().
DefaultCommandFileName
virtual string IG.Lib.InterfaceInterpreterBase.DefaultCommandFileName get
Gets the default command file name for the current interpreter.
Definition at line 171 of file InterfaceInterpreterBase.cs.
Referenced by IG.Lib.InterfaceInterpreterBase.InterfaceInterpreterBase(), and IG.Lib.InterfaceInverse.InterfaceInverse().
CommandFileName
virtual string IG.Lib.InterfaceInterpreterBase.CommandFileName get protected set
Gets or sets the command file name where interpreter commands will be written.
Definition at line 177 of file InterfaceInterpreterBase.cs.
Referenced by IG.Lib.InterfaceInterpreterBase.InterfaceInterpreterBase(), and IG.Lib.InterfaceInverse.InterfaceInverse().
CommandFilePath
virtual string IG.Lib.InterfaceInterpreterBase.CommandFilePath get
Gets path to command file.
Definition at line 192 of file InterfaceInterpreterBase.cs.
Referenced by IG.Lib.InterfaceInterpreterBase.RunCommandFile(), and IG.Lib.InterfaceInterpreterBase.WriteCommandFile().
StartingDirectory
virtual string IG.Lib.InterfaceInterpreterBase.StartingDirectory get protected set
Gets or sets the command that invokes the interpreter.
Definition at line 206 of file InterfaceInterpreterBase.cs.
Referenced by IG.Lib.InterfaceInterpreterBase.InterfaceInterpreterBase(), and IG.Lib.InterfaceInverse.InterfaceInverse().
CommandIntroduction
virtual string IG.Lib.InterfaceInterpreterBase.CommandIntroduction get protected set
String that introduces a new command (and is written before the command name in the command file). Usually a newline.
Definition at line 224 of file InterfaceInterpreterBase.cs.
Referenced by IG.Lib.InterfaceInterpreterBase.InterfaceInterpreterBase(), IG.Lib.InterfaceInverse.InterfaceInverse(), and IG.Lib.InterfaceInterpreterBase.StartCommand().
CommandArgumentBlockBegin
virtual string IG.Lib.InterfaceInterpreterBase.CommandArgumentBlockBegin get protected set
String that begins command arguments block.
Definition at line 232 of file InterfaceInterpreterBase.cs.
Referenced by IG.Lib.InterfaceInterpreterBase.InterfaceInterpreterBase(), IG.Lib.InterfaceInverse.InterfaceInverse(), and IG.Lib.InterfaceInterpreterBase.StartCommand().
CommandArgumentBlockEnd
virtual string IG.Lib.InterfaceInterpreterBase.CommandArgumentBlockEnd get protected set
String that ends command argument block.
Definition at line 239 of file InterfaceInterpreterBase.cs.
Referenced by IG.Lib.InterfaceInterpreterBase.EndCommand(), IG.Lib.InterfaceInterpreterBase.InterfaceInterpreterBase(), and IG.Lib.InterfaceInverse.InterfaceInverse().
CommandArgumentSeparator
virtual string IG.Lib.InterfaceInterpreterBase.CommandArgumentSeparator get protected set
String that begins command arguments block.
Definition at line 246 of file InterfaceInterpreterBase.cs.
Referenced by IG.Lib.InterfaceInterpreterBase.AppendCommandArgumentSeparatorIfNecessary(), IG.Lib.InterfaceInterpreterBase.InterfaceInterpreterBase(), and IG.Lib.InterfaceInverse.InterfaceInverse().
CommandArgumentsInNewLines
virtual bool IG.Lib.InterfaceInterpreterBase.CommandArgumentsInNewLines get set
Whether command arguments are listed in separate lines or not.
Definition at line 253 of file InterfaceInterpreterBase.cs.
Referenced by IG.Lib.InterfaceInterpreterBase.AppendCommandArgumentSeparatorIfNecessary(), IG.Lib.InterfaceInterpreterBase.EndCommand(), IG.Lib.InterfaceInterpreterBase.InterfaceInterpreterBase(), IG.Lib.InterfaceInverse.InterfaceInverse(), and IG.Lib.InterfaceInterpreterBase.StartCommand().
CommandArgumentCount
virtual int IG.Lib.InterfaceInterpreterBase.CommandArgumentCount get protected set
The number of current argument.
Definition at line 261 of file InterfaceInterpreterBase.cs.
Referenced by IG.Lib.InterfaceInterpreterBase.AppendCommandArgumentSeparatorIfNecessary(), IG.Lib.InterfaceInterpreterBase.EndCommand(), and IG.Lib.InterfaceInterpreterBase.StartCommand().
IsWithinArgumentBlock
virtual bool IG.Lib.InterfaceInterpreterBase.IsWithinArgumentBlock get protected set
The number of current argument.
Definition at line 268 of file InterfaceInterpreterBase.cs.
Referenced by IG.Lib.InterfaceInterpreterBase.AppendCommandArgument(), IG.Lib.InterfaceInterpreterBase.AppendCommandArgumentPlain(), IG.Lib.InterfaceInterpreterBase.AppendCommandArgumentSeparatorIfNecessary(), IG.Lib.InterfaceInterpreterBase.EndCommand(), and IG.Lib.InterfaceInterpreterBase.StartCommand().
CodeBlockBegin
virtual string IG.Lib.InterfaceInterpreterBase.CodeBlockBegin get protected set
String that begins a code block in interpreted files.
Definition at line 275 of file InterfaceInterpreterBase.cs.
Referenced by IG.Lib.InterfaceInterpreterBase.InterfaceInterpreterBase(), IG.Lib.InterfaceInverse.InterfaceInverse(), and IG.Lib.InterfaceInterpreterBase.StartCodeBlock().
CodeBlockEnd
virtual string IG.Lib.InterfaceInterpreterBase.CodeBlockEnd get protected set
String that ends a code block in interpreted files.
Definition at line 282 of file InterfaceInterpreterBase.cs.
Referenced by IG.Lib.InterfaceInterpreterBase.EndCodeBlock(), IG.Lib.InterfaceInterpreterBase.InterfaceInterpreterBase(), and IG.Lib.InterfaceInverse.InterfaceInverse().
VariableReferenceBegin
virtual string IG.Lib.InterfaceInterpreterBase.VariableReferenceBegin get protected set
String that begins a code block in interpreted files.
Definition at line 289 of file InterfaceInterpreterBase.cs.
Referenced by IG.Lib.InterfaceInterpreterBase.AppendCommandVariableReference(), IG.Lib.InterfaceInterpreterBase.InterfaceInterpreterBase(), and IG.Lib.InterfaceInverse.InterfaceInverse().
VariableReferenceEnd
virtual string IG.Lib.InterfaceInterpreterBase.VariableReferenceEnd get protected set
String that ends a code block in interpreted files.
Definition at line 296 of file InterfaceInterpreterBase.cs.
Referenced by IG.Lib.InterfaceInterpreterBase.AppendCommandVariableReference(), IG.Lib.InterfaceInterpreterBase.InterfaceInterpreterBase(), and IG.Lib.InterfaceInverse.InterfaceInverse().
IndentationString
virtual string IG.Lib.InterfaceInterpreterBase.IndentationString get set
String used for indentation of code.
Definition at line 303 of file InterfaceInterpreterBase.cs.
Referenced by IG.Lib.InterfaceInterpreterBase.AppendIndent(), IG.Lib.InterfaceInterpreterBase.InterfaceInterpreterBase(), and IG.Lib.InterfaceInverse.InterfaceInverse().
IndentationLevel
virtual int IG.Lib.InterfaceInterpreterBase.IndentationLevel get protected set
Indentation level - how many indentation strings are added before each new row.
Definition at line 310 of file InterfaceInterpreterBase.cs.
Referenced by IG.Lib.InterfaceInterpreterBase.AppendIndent(), IG.Lib.InterfaceInterpreterBase.EndCodeBlock(), IG.Lib.InterfaceInterpreterBase.EndCommand(), IG.Lib.InterfaceInterpreterBase.StartCodeBlock(), and IG.Lib.InterfaceInterpreterBase.StartCommand().
CommentBegin
virtual string IG.Lib.InterfaceInterpreterBase.CommentBegin get protected set
String that begins a comment.
Definition at line 317 of file InterfaceInterpreterBase.cs.
Referenced by IG.Lib.InterfaceInterpreterBase.AppendComment(), IG.Lib.InterfaceInterpreterBase.InterfaceInterpreterBase(), and IG.Lib.InterfaceInverse.InterfaceInverse().
CommentEnd
virtual string IG.Lib.InterfaceInterpreterBase.CommentEnd get protected set
String that ends a comment.
Definition at line 324 of file InterfaceInterpreterBase.cs.
Referenced by IG.Lib.InterfaceInterpreterBase.AppendComment(), IG.Lib.InterfaceInterpreterBase.InterfaceInterpreterBase(), and IG.Lib.InterfaceInverse.InterfaceInverse().
The documentation for this class was generated from the following file:
iglib/igbase/interpreters/interfaces/InterfaceInterpreterBase.cs