Doc: IGLib with source files: IGLib.Base.HashCodeHelper Class Reference
IGLib.Base.HashCodeHelper Class Reference
Contains methods that combines hashes of multipe objects into a single hash.
Static Public Member Functions
static int Combine< T1 > (T1 value1)
static int Combine< T1, T2 > (T1 value1, T2 value2)
static int Combine< T1, T2, T3 > (T1 value1, T2 value2, T3 value3)
static int Combine< T1 > (T1 value1)
static int Combine< T1, T2 > (T1 value1, T2 value2)
static int Combine< T1, T2, T3 > (T1 value1, T2 value2, T3 value3)
Static Private Member Functions
static int CombineHashes (params int[] hashes)
static int CombineHashes (params int[] hashes)
Detailed Description
Contains methods that combines hashes of multipe objects into a single hash.
In .NET 8 or greater, this just calls HashCode.Combine{T1}(T1), but for lower versions (including .NET Framework), the class provides its own implementation.
Definition at line 44 of file HashCodeHelper.cs.
Member Function Documentation
Combine< T1 >() [1/2]
static int IGLib.Base.HashCodeHelper.Combine< T1 > (T1 value1) inline static
Definition at line 46 of file HashCodeHelper.cs.
Combine< T1, T2 >() [1/2]
static int IGLib.Base.HashCodeHelper.Combine< T1, T2 > (T1 value1, T2 value2) inline static
Definition at line 51 of file HashCodeHelper.cs.
References IGLib.Base.HashCodeHelper.CombineHashes().
Combine< T1, T2, T3 >() [1/2]
static int IGLib.Base.HashCodeHelper.Combine< T1, T2, T3 > (T1 value1, T2 value2, T3 value3) inline static
Definition at line 59 of file HashCodeHelper.cs.
References IGLib.Base.HashCodeHelper.CombineHashes().
CombineHashes() [1/2]
static int IGLib.Base.HashCodeHelper.CombineHashes (params int[] hashes) inline static private
Definition at line 70 of file HashCodeHelper.cs.
Referenced by IGLib.Base.HashCodeHelper.Combine< T1, T2 >(), and IGLib.Base.HashCodeHelper.Combine< T1, T2, T3 >().
Combine< T1 >() [2/2]
static int IGLib.Base.HashCodeHelper.Combine< T1 > (T1 value1) inline static
Definition at line 46 of file HashCodeHelper.cs.
Combine< T1, T2 >() [2/2]
static int IGLib.Base.HashCodeHelper.Combine< T1, T2 > (T1 value1, T2 value2) inline static
Definition at line 51 of file HashCodeHelper.cs.
References IGLib.Base.HashCodeHelper.CombineHashes().
Combine< T1, T2, T3 >() [2/2]
static int IGLib.Base.HashCodeHelper.Combine< T1, T2, T3 > (T1 value1, T2 value2, T3 value3) inline static
Definition at line 59 of file HashCodeHelper.cs.
References IGLib.Base.HashCodeHelper.CombineHashes().
CombineHashes() [2/2]
static int IGLib.Base.HashCodeHelper.CombineHashes (params int[] hashes) inline static private
Definition at line 70 of file HashCodeHelper.cs.
The documentation for this class was generated from the following file:
IGLibCore/tests/IGLib.TestBase/00_Fixes/HashCodeHelper.cs