Doc: IGLib with source files: IGLib.Core.SingleTypeConverterBase< TSource, TTarget > Class Template Reference
IGLib.Core.SingleTypeConverterBase< TSource, TTarget > Class Template Reference
Abstract base implementation of ISingleTypeConverter<TSource, TTarget>. Sets SourceType and TargetType properties according to generic type parameters TSource and TTarget , respectively, and implements all methods by calling their counterparts. Implementatkion based on this base class must override and properly implement either the TryConvertTyped(TSource, out TTarget) or the ConvertTyped(TSource) method.
Public Member Functions
virtual object Convert (object source)
Converts the value (object) source of type SourceType to a value (object) of type TargetType and returns it.Throws an exception (normally, an InvalidCastException or InvalidOperationException) if the conversion cannot be performed (also in some cases ArgumentException or ArgumentNullException when the type of source is incorrct or its value is null).
virtual bool TryConvert (object source, out object target)
Converts the value source of type SourceType to a value of type TargetType and stores the converted value (object) in target .Returns true if the conversion could be performed successfully, and false if not. It shoould normally not throw exceptions, because success of conversion is communicated to the caller via returned value.
virtual TTarget ConvertTyped (TSource source)
Converts the parameter source to the target type (TTarget , or equivalently, TargetType), and returns the converted value.Normally, throws an exception if the conversion cannot be performed.
virtual bool TryConvertTyped (TSource source, out TTarget target)
Converts the parameter source to the target type (TTarget , or equivalently, TargetType), and stores the converted value (object) in target . Returns true if conversion was successful, or false if it could not be performed.Normally, it huld not throw exceptions because eventual failure to perform type conversion is communicated to the caller via return value.
Properties
Type SourceType = typeof(TSource) [get]
Type TargetType = typeof(TTarget) [get]
Properties inherited from IGLib.Core.ISingleTypeConverter< TSource, TTarget >
new Type SourceType [get]
Source type, the type of values FROM which the current converter converts. Should correspond to TSource .
new Type TargetType [get]
Target type, the type of values TO which the current converter converts. Should correspond to TTarget .
Type SourceType [get]
Source type, the type of values FROM which the current converter converts.
Type TargetType [get]
Target type, the type of values TO which the current converter converts.
Private Attributes
int numCalls = 0
Counter of calls to prevent infinite recursion, which would occur if none of the methods are overridden and properly implemented (because all method in the class are implemented by calling another method of the class, such that derived classes can implement either of the typed methods).
Detailed Description
Abstract base implementation of ISingleTypeConverter<TSource, TTarget>. Sets SourceType and TargetType properties according to generic type parameters TSource and TTarget , respectively, and implements all methods by calling their counterparts. Implementatkion based on this base class must override and properly implement either the TryConvertTyped(TSource, out TTarget) or the ConvertTyped(TSource) method.
Template Parameters
TSource Type of the objects that can be converted to TTarget by the current converter.
TTarget Type to which source object of type TSource are converted by the current converter.
Definition at line 17 of file SingleTypeConverterBaseGeneric.cs.
Member Function Documentation
Convert()
virtual object IGLib.Core.SingleTypeConverterBase< TSource, TTarget >.Convert (object source) inline virtual
Converts the value (object) source of type SourceType to a value (object) of type TargetType and returns it.Throws an exception (normally, an InvalidCastException or InvalidOperationException) if the conversion cannot be performed (also in some cases ArgumentException or ArgumentNullException when the type of source is incorrct or its value is null).
Implements IGLib.Core.ISingleTypeConverter< TSource, TTarget >.
Definition at line 32 of file SingleTypeConverterBaseGeneric.cs.
TryConvert()
virtual bool IGLib.Core.SingleTypeConverterBase< TSource, TTarget >.TryConvert (object source, out object target) inline virtual
Converts the value source of type SourceType to a value of type TargetType and stores the converted value (object) in target .Returns true if the conversion could be performed successfully, and false if not. It shoould normally not throw exceptions, because success of conversion is communicated to the caller via returned value.
Implements IGLib.Core.ISingleTypeConverter< TSource, TTarget >.
Definition at line 42 of file SingleTypeConverterBaseGeneric.cs.
ConvertTyped()
virtual TTarget IGLib.Core.SingleTypeConverterBase< TSource, TTarget >.ConvertTyped (TSource source) inline virtual
Converts the parameter source to the target type (TTarget , or equivalently, TargetType), and returns the converted value.Normally, throws an exception if the conversion cannot be performed.
Implements IGLib.Core.ISingleTypeConverter< TSource, TTarget >.
Reimplemented in IGLib.Core.SingleTypeConverterFromDelegate< TSource, TTarget >.
Definition at line 63 of file SingleTypeConverterBaseGeneric.cs.
Referenced by IGLib.Core.SingleTypeConverterBase< int[], string >.Convert(), and IGLib.Core.SingleTypeConverterBase< int[], string >.TryConvertTyped().
TryConvertTyped()
virtual bool IGLib.Core.SingleTypeConverterBase< TSource, TTarget >.TryConvertTyped (TSource source, out TTarget target) inline virtual
Converts the parameter source to the target type (TTarget , or equivalently, TargetType), and stores the converted value (object) in target . Returns true if conversion was successful, or false if it could not be performed.Normally, it huld not throw exceptions because eventual failure to perform type conversion is communicated to the caller via return value.
Implements IGLib.Core.ISingleTypeConverter< TSource, TTarget >.
Definition at line 83 of file SingleTypeConverterBaseGeneric.cs.
Referenced by IGLib.Core.SingleTypeConverterBase< int[], string >.ConvertTyped(), and IGLib.Core.SingleTypeConverterBase< int[], string >.TryConvert().
Member Data Documentation
numCalls
int IGLib.Core.SingleTypeConverterBase< TSource, TTarget >.numCalls = 0 private
Counter of calls to prevent infinite recursion, which would occur if none of the methods are overridden and properly implemented (because all method in the class are implemented by calling another method of the class, such that derived classes can implement either of the typed methods).
Definition at line 29 of file SingleTypeConverterBaseGeneric.cs.
Referenced by IGLib.Core.SingleTypeConverterBase< int[], string >.Convert(), IGLib.Core.SingleTypeConverterBase< int[], string >.ConvertTyped(), IGLib.Core.SingleTypeConverterBase< int[], string >.TryConvert(), and IGLib.Core.SingleTypeConverterBase< int[], string >.TryConvertTyped().
Property Documentation
SourceType
Type IGLib.Core.SingleTypeConverterBase< TSource, TTarget >.SourceType = typeof(TSource) get
Definition at line 21 of file SingleTypeConverterBaseGeneric.cs.
TargetType
Type IGLib.Core.SingleTypeConverterBase< TSource, TTarget >.TargetType = typeof(TTarget) get
Definition at line 24 of file SingleTypeConverterBaseGeneric.cs.
The documentation for this class was generated from the following file:
IGLibGraphics3D/src/IGLib.Graphics3D/other/TypeConversion/SingleConverters/SingleTypeConverterBaseGeneric.cs