Doc: IGLib with source files: IG.Num.VectorExtensions Class Reference
IG.Num.VectorExtensions Class Reference
Extension methods for vector classes.
Static Public Member Functions
static string ToString (this IVector vec)
Returns a string representation of the current vector in a standard IGLib form. Extension method for IVector interface.
static string ToStringMath (IVector vec)
Returns a string representation of the current vector in a standard IGLib form (Mathematica-like format but with C representation of numbers). Extension method for IVector interface.
static string ToString (this IVector vec, string elementFormat)
Returns a string representation of the current vector in a standard IGLib form, with the specified
format for elements of the vector. Extension method for IVector interface.
static string ToStringMath (IVector vec, string elementFormat)
Returns a string representation of the current vector in a standard IGLib form (Mathematica-like format but with C representation of numbers), with the specified
format for elements of the vector. Extension method for IVector interface.
Detailed Description
Extension methods for vector classes.
$A Igor Apr11;
Definition at line 219 of file VectorBase.cs.
Member Function Documentation
ToString() [1/2]
static string IG.Num.VectorExtensions.ToString (this IVector vec) inline static
Returns a string representation of the current vector in a standard IGLib form. Extension method for IVector interface.
Parameters
vec Vector whose string representation is returned.
Definition at line 225 of file VectorBase.cs.
References IG.Num.VectorBase.ToString().
ToStringMath() [1/2]
static string IG.Num.VectorExtensions.ToStringMath (IVector vec) inline static
Returns a string representation of the current vector in a standard IGLib form (Mathematica-like format but with C representation of numbers). Extension method for IVector interface.
Parameters
vec Vector whose string representation is returned.
Definition at line 234 of file VectorBase.cs.
References IG.Num.VectorBase.ToStringMath().
ToString() [2/2]
static string IG.Num.VectorExtensions.ToString (this IVector vec, string elementFormat) inline static
Returns a string representation of the current vector in a standard IGLib form, with the specified
format for elements of the vector. Extension method for IVector interface.
Parameters
vec Vector whose string representation is returned.
elementFormat Format specification for printing individual element.
Definition at line 244 of file VectorBase.cs.
References IG.Num.VectorBase.ToString().
ToStringMath() [2/2]
static string IG.Num.VectorExtensions.ToStringMath (IVector vec, string elementFormat) inline static
Returns a string representation of the current vector in a standard IGLib form (Mathematica-like format but with C representation of numbers), with the specified
format for elements of the vector. Extension method for IVector interface.
Parameters
vec Vector whose string representation is returned.
elementFormat Format specification for printing individual element.
Definition at line 255 of file VectorBase.cs.
References IG.Num.VectorBase.ToStringMath().
The documentation for this class was generated from the following file:
iglib/igbase/numeric/VectorBase.cs