Doc: IGLib with source files: IGLib.Gr3D.Curve3DParameterizationFromCylindricalWithBounds Class Reference
IGLib.Gr3D.Curve3DParameterizationFromCylindricalWithBounds Class Reference
Cartesion parameterization of a curve in 3D. Beside the Curve and (optional) CurveDerivative, it also contains bounds on parameter, StartParameter and EndParameter as part of the class.
Public Member Functions
virtual vec3 Curve (double t)
3D vector function of scalar argument, which represents a parameterization of the curve in 3D Euclidean space. Properties StartParameter and EndParameter determine the typical starting and end parameter values for use cases like plotting the curve.
virtual vec3 CurveDerivative (double t)
3D vector function of scalar argument, which represents the derivative of Curve with respect to parameter. In each point on curve (for each parameter value), this defines a tangent on the curve (or speed vector), with its size representing the velocity.You can use Derivative Calculator
Public Attributes
abstract double rho
abstract double rhoDerivative
virtual bool HasDerivative => HasDerivativeCylindrical
Public Attributes inherited from IGLib.Gr3D.ICurve3DCylindricalParameterization
double rho
3D vector function of scalar argument, which gives a 3D representation of the curve. Properties StartParameterCylindrical and EndParameterCylindrical determine the starting and ending parameter that the curve closed.
double double phi
double rhoDerivative
3D vector function of scalar argument, which represents the derivative of CurveCylindrical with respect to parameter. In each point on curve (for each parameter value), this defines a tangent on the curve (or speed vector), with its size representing the velocity.
double double phiDerivative
Properties
abstract bool HasDerivativeCylindrical [get]
abstract double StartParameter [get]
abstract double EndParameter [get]
Properties inherited from IGLib.Gr3D.ICurve3DCylindricalParameterization
bool HasDerivativeCylindrical [get]
Whether derivative is defined or not. If false then CurveDerivativeCylindrical(double) cannot be used to calculate tangents on the curve.
double StartParameter [get]
Typical starting value of the parameter of the parametric curve that represents the curve. Interval from StartParameter to EndParameter should, for mathematical knots, produce a closed curve.
double EndParameter [get]
Typical end value of the parameter of the parametric curve that represents the curve. Interval from StartParameter to EndParameter should, for mathematical knots, produce a closed curve.
Properties inherited from IGLib.Gr3D.ICurve3DParameterizationWithBounds
bool HasDerivative [get]
Whether derivative is defined or not. If false then CurveDerivative(double) cannot be used to calculate tangents on the curve.
double StartParameter [get]
Typical starting value of the parameter of the parametric curve that represents the curve. Interval from StartParameter to EndParameter should, for mathematical knots, produce a closed curve.
double EndParameter [get]
Typical end value of the parameter of the parametric curve that represents the curve. Interval from StartParameter to EndParameter should, for mathematical knots, produce a closed curve.
Private Member Functions
abstract double double double z CurveCylindrical (double t)
abstract double double double zDerivative CurveDerivativeCylindrical (double t)
Private Attributes
abstract double double phi
abstract double double phiDerivative
Detailed Description
Cartesion parameterization of a curve in 3D. Beside the Curve and (optional) CurveDerivative, it also contains bounds on parameter, StartParameter and EndParameter as part of the class.
StartParameter and EndParameter usually denote bounds on curve parameter that are used by default when the curve is tabulated, plotted, for meshes or for numerical calculations (i.e. lengths or urfaces or volumes where the curve is involved). Sometimes, these properties can also represent the range of parameter values for which the curve is defined, though rarely. More often, they represent some characteristic or natural range for the curve in question, and sometimes theey are not used at all (the convention is to set both to 0 in such cases). For mathematical knots (slosed ones), these properties are usually set to such values that the represented curves exactly closes eginning with its end when parameter runs from StartParameter and EndParameter.
Definition at line 21 of file Curve3DParameterizationFromCylindricalWithBounds.cs.
Member Function Documentation
CurveCylindrical()
abstract double double double z IGLib.Gr3D.Curve3DParameterizationFromCylindricalWithBounds.CurveCylindrical (double t) private
Implements IGLib.Gr3D.ICurve3DCylindricalParameterization.
Referenced by IGLib.Gr3D.Curve3DParameterizationFromCylindricalWithBounds.Curve(), and IGLib.Gr3D.Curve3DParameterizationFromCylindricalWithBounds.CurveDerivative().
CurveDerivativeCylindrical()
abstract double double double zDerivative IGLib.Gr3D.Curve3DParameterizationFromCylindricalWithBounds.CurveDerivativeCylindrical (double t) private
Implements IGLib.Gr3D.ICurve3DCylindricalParameterization.
Referenced by IGLib.Gr3D.Curve3DParameterizationFromCylindricalWithBounds.CurveDerivative().
Curve()
virtual vec3 IGLib.Gr3D.Curve3DParameterizationFromCylindricalWithBounds.Curve (double t) inline virtual
3D vector function of scalar argument, which represents a parameterization of the curve in 3D Euclidean space. Properties StartParameter and EndParameter determine the typical starting and end parameter values for use cases like plotting the curve.
Implements IGLib.Gr3D.ICurve3DParameterizationWithBounds.
Definition at line 48 of file Curve3DParameterizationFromCylindricalWithBounds.cs.
References IGLib.Gr3D.Curve3DParameterizationFromCylindricalWithBounds.CurveCylindrical(), IGLib.Gr3D.Curve3DParameterizationFromCylindricalWithBounds.phi, and IGLib.Gr3D.Curve3DParameterizationFromCylindricalWithBounds.rho.
CurveDerivative()
virtual vec3 IGLib.Gr3D.Curve3DParameterizationFromCylindricalWithBounds.CurveDerivative (double t) inline virtual
3D vector function of scalar argument, which represents the derivative of Curve with respect to parameter. In each point on curve (for each parameter value), this defines a tangent on the curve (or speed vector), with its size representing the velocity.You can use Derivative Calculator
Implements IGLib.Gr3D.ICurve3DParameterizationWithBounds.
Definition at line 58 of file Curve3DParameterizationFromCylindricalWithBounds.cs.
References IGLib.Gr3D.Curve3DParameterizationFromCylindricalWithBounds.CurveCylindrical(), IGLib.Gr3D.Curve3DParameterizationFromCylindricalWithBounds.CurveDerivativeCylindrical(), IGLib.Gr3D.Curve3DParameterizationFromCylindricalWithBounds.HasDerivative, IGLib.Gr3D.Curve3DParameterizationFromCylindricalWithBounds.phi, IGLib.Gr3D.Curve3DParameterizationFromCylindricalWithBounds.phiDerivative, IGLib.Gr3D.Curve3DParameterizationFromCylindricalWithBounds.rho, and IGLib.Gr3D.Curve3DParameterizationFromCylindricalWithBounds.rhoDerivative.
Member Data Documentation
rho
abstract double IGLib.Gr3D.Curve3DParameterizationFromCylindricalWithBounds.rho
Definition at line 28 of file Curve3DParameterizationFromCylindricalWithBounds.cs.
Referenced by IGLib.Gr3D.Curve3DParameterizationFromCylindricalWithBounds.Curve(), IGLib.Gr3D.Curve3DParameterizationFromCylindricalWithBounds.CurveDerivative(), IGLib.Gr3D.CylindricalBilliardKnot.override(), and IGLib.Gr3D.CylindricalBilliardKnot_WrongParameterization.override().
phi
abstract double double IGLib.Gr3D.Curve3DParameterizationFromCylindricalWithBounds.phi private
Definition at line 28 of file Curve3DParameterizationFromCylindricalWithBounds.cs.
Referenced by IGLib.Gr3D.Curve3DParameterizationFromCylindricalWithBounds.Curve(), IGLib.Gr3D.Curve3DParameterizationFromCylindricalWithBounds.CurveDerivative(), IGLib.Gr3D.CylindricalBilliardKnot.override(), and IGLib.Gr3D.CylindricalBilliardKnot_WrongParameterization.override().
rhoDerivative
abstract double IGLib.Gr3D.Curve3DParameterizationFromCylindricalWithBounds.rhoDerivative
Definition at line 31 of file Curve3DParameterizationFromCylindricalWithBounds.cs.
Referenced by IGLib.Gr3D.Curve3DParameterizationFromCylindricalWithBounds.CurveDerivative().
phiDerivative
abstract double double IGLib.Gr3D.Curve3DParameterizationFromCylindricalWithBounds.phiDerivative private
Definition at line 31 of file Curve3DParameterizationFromCylindricalWithBounds.cs.
Referenced by IGLib.Gr3D.Curve3DParameterizationFromCylindricalWithBounds.CurveDerivative().
HasDerivative
virtual bool IGLib.Gr3D.Curve3DParameterizationFromCylindricalWithBounds.HasDerivative => HasDerivativeCylindrical
Definition at line 77 of file Curve3DParameterizationFromCylindricalWithBounds.cs.
Referenced by IGLib.Gr3D.Curve3DParameterizationFromCylindricalWithBounds.CurveDerivative().
Property Documentation
HasDerivativeCylindrical
abstract bool IGLib.Gr3D.Curve3DParameterizationFromCylindricalWithBounds.HasDerivativeCylindrical get
Definition at line 34 of file Curve3DParameterizationFromCylindricalWithBounds.cs.
StartParameter
abstract double IGLib.Gr3D.Curve3DParameterizationFromCylindricalWithBounds.StartParameter get
Definition at line 37 of file Curve3DParameterizationFromCylindricalWithBounds.cs.
EndParameter
abstract double IGLib.Gr3D.Curve3DParameterizationFromCylindricalWithBounds.EndParameter get
Definition at line 40 of file Curve3DParameterizationFromCylindricalWithBounds.cs.
The documentation for this class was generated from the following file:
IGLibGraphics3D/src/IGLib.Graphics3D/Graphics3D/MathObjects/CurvesAndKnots/Curve3DParameterizationFromCylindricalWithBounds.cs