Doc: IGLib with source files: IG.Lib.ScriptLoaderBase Class Reference
IG.Lib.ScriptLoaderBase Class Reference
Dynamically compiles, loads and instantiates classes of type ILoadableScript from files or from strings.
Public Member Functions
ScriptLoaderBase ()
virtual void InitializeScriptLoader ()
Initializes the current script loader.
virtual void ClearLogger ()
Clears the logger.
virtual string GetExampleCode ()
Gets example code base (a template code for compiling) where names of classes, methods etc. are properly set.
virtual string GetExampleCode (string pureScript)
Returns a complete example code that can be loaded and run.
void CheckAndCorrectNames ()
Corrects the ClassName (if the current class name has already been used) and namespace and class name in the loaded scritp code (if they don't correspond to ClassNamespace and ClassName, respectively).
virtual string GetExecutableDirectory ()
Returns the directory containing the executable that started the current application.
virtual void AddReferencedAssembly (string assemblyFile)
Adds an additional referenced assembly by name of the assembly file. Assmebly is only added if it is not yet contained in the list of referenced assemblies and if the specified assembly file name is not null or empty string.
virtual void AddReferencedAssemblies (params string[] assemblyFiles)
Adds the specified assemblies to the list of referenced assemblies. Assemblise are added only if not yet on the list and if their names are not null or empty strings.
virtual void SetReferencedAssemblies (params string[] assemblyFiles)
Sets the list of referenced assemblies in such a way that it contains only the specified assemblies.
virtual void RemoveReferencedAssembly (string assemblyFile)
Removes the specified assembly from the list of referenced assemblies. If the specified assembly does not exist on the list or it is a null or empty string then nothing happens.
virtual void RemoveReferencedAssemblies (params string[] assemblyFiles)
Removes the specified assemblies from the list of referenced assemblies.
virtual void RemoveAllReferencedAssemblies ()
Removes all assemblies from tehe list of referenced assemblies.
virtual string[] GetReferencedAssemblies ()
Returns an array of assemblies (paths, sometimes only file names) that are currently referenced by the compiler on the current script loader.
virtual string Compile ()
Compiles the code that is currently loaded by the current loader, and returns full name of the compiled script class.
virtual void UnloadApplicationDomain ()
Unloads the application domain used by the current script loader.
virtual ILoadableScript CreateObject (string[] initializationArguments)
Creates and returns an object of the class that has been last compiled. The created object is also stored such that it can later be accessed through the CreatedObject property.
virtual ILoadableScript CreateLoadableObject (string[] initializationArguments, bool storeObject)
Creates and returns an object of the class that has been last compiled.
virtual ILoadableScript CreateLoadableObject (string[] initializationArguments, string classFullName)
Creates and returns an object of the specified loadable class.
virtual void Run (string[] initializationAndRunArguments)
Runs the object of the compiled loadable class (calls its Run() method) that is currently loaded by the current loader. Compiles the code and creates the object if necessary.
virtual void Run (string[] initializationArguments, string[] runArguments)
Runs the object of the compiled loadable class (calls its Run() method) that is currently loaded by the current loader. Compiles the code and creates the object if necessary.
void LoadCode (string code, string classFullName)
Loads code form a string.
void LoadCode (string code)
Loads code form a string. Class name is extracted from the code.
ILoadableScript CreateObjectFromCode (string code, string className, string[] initializationArguments)
Creates and returns a loadable script object form code.
ILoadableScript CreateObjectFromCode (string code, string[] initializationArguments)
Creates and returns a loadable script object form code. Class name is extracted from code.
string RunCode (string code, string className, string[] initializationArguments, string[] runArguments)
Creates and runs a loadable script object form code.
string RunCode (string code, string[] initializationArguments, string[] runArguments)
Creates and returns a loadable script object form code. Class name is extracted from code.
string RunCode (string code, string className, string[] initializationAndRunArguments)
Runs a loadable script object form code.
string RunCode (string code, string[] initializationAndRunArguments)
Creates and returns a loadable script object form code. Class name is extracted from code.
void LoadFile (string filePath, string className)
Loads loadable script code form the specified file.
void LoadFile (string filePath)
Loads loadable script code form a file. Name of the class is extracted from the file contents.
ILoadableScript CreateObjectFromFile (string filePath, string className, string[] initializationArguments)
Creates and returns a loadable script object form a file containing its code.
ILoadableScript CreateObjectFromFile (string filePath, string[] initializationArguments)
Creates and returns a loadable script object form code. Class name is extracted from code.
string RunFile (string filePath, string className, string[] initializationArguments, string[] runArguments)
Executes a loadable script form a file. The file must contain definition of the loadable script class that is used to instantiate an object and execute it.
string RunFile (string filePath, string[] initializationArguments, string[] runArguments)
Executes a loadable script form a file. The file must contain definition of the loadable script class that is used to instantiate an object and execute it. Class name is extracted from code.
string RunFile (string filePath, string className, string[] initializationAndRunArguments)
Executes a loadable script form a file. The file must contain definition of the loadable script class that is used to instantiate an object and execute it. The same arguments are taken for initialization of the loadable script object and for execution of the script.
string RunFile (string filePath, string[] initializationAndRunArguments)
Executes a loadable script form a file. The file must contain definition of the loadable script class that is used to instantiate an object and execute it. The same arguments are taken for initialization of the loadable script object and for execution of the script. Class name is extracted from code.
Static Public Member Functions
static void InitializeScripting ()
Initializes the scripting system.
static ILoadableScript GetLoadableScriptC (ILoadableScript scriptObject)
Returns the loadable script object if the script object is actually loadable, or null if it is not meant as loadable.
static byte[] LoadFileBytes (string filePath)
Copies the specified file to byte array and returns it.
static ILoadableScript CreateScriptObject (string scriptClassFullName)
Creates and returns a new script obect of the specified type.
static ILoadableScript CreateScriptObject (string scriptClassFullName, int outputLevel)
Creates and returns a new script obect of the specified type.
static void AddDefaultAssemblies (params string[] assemblies)
Add the specified assemblies (just their names) to the list of assemblies that are referenced by newly created script loaders by default.
static void RemoveDefaultAssemblies (params string[] assemblies)
Removes the specified assemblies from the list of default assemblies that are referenced by newly created script loaders.
static void ClearDefaultAssemblies ()
Clears the list of assemblies that are referenced by default by newly created script loaders.
static bool IsClassFullNameUsed (string classFillName)
Returns a flag indicating whether the specified class full name has already been used or not.
static string FindNameAfterKeyword (string code, string keyword, string allowedCharacters)
In the specified string, finds a name that follows the specified keyword, and returns it. Name must directly follow the keyword with only blank characters between them, and it end at the first character that is not alphanumeric and is also not contained in the specified string of allowed characters.
static string FindNamespace (string code)
Finds and returns the name of the first namespace that is defined in the specified C# code block. A null string is returned if the name can not be found.
static string FindClassName (string code)
Finds and returns the name of the first class that is defined in the specified C# code block. A null string is returned if the name can not be found.
static string GetFileContents (string filePath)
Returns contents of the specified file.
Protected Member Functions
void AddDefaultReferencedAssemblies ()
Add assemblies that are referenced by default to the list of assemblies that are referenced by the current script loader.
void CreateNonexistentLibraryPath ()
Modifies library path in such a way that it points to an non-existent file.
virtual void AddReferencedAssemblies (System.CodeDom.Compiler.CompilerParameters compilerParameters)
Adds referenced assemblies to the specified compiler parameters, according to current settings.
Static Protected Member Functions
static string CreateNonexistentFilePath (string originalPath)
Returns a file path that does not exist and is derived form the specified file path by adding a suffix composed of underscore and a number.
Protected Attributes
string _code = null
string _libraryFilename = null
string _originalLibraryPath = null
List< string > _referencedAssimblies = new List<string>()
bool _referenceAllLoadedAssemblies = true
Properties
bool IsScriptLoaderInitialized [get, protected set]
Whether the current script loader is initialized or not.
static bool IsScriptingInitialized [get, protected set]
Whether scripting system is initialized or not.
object Lock [get]
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
static List< string > DefaultAssemblies [get]
Gets the list of assemblies that are added to all newly created script loaders by default.
static SortedList< string, string > UsedClassFullNames [get]
Stores used class names, i.e. class names that have already been used for dynamiically loaded classes.
static ScriptLoaderBase Global [get, set]
Global script loader. Getter always returns a non-null object.
int OutputLevel [get, set]
Definbes level of output on console that is generated by some operations. 0 means that no output will be written to the console.
virtual Logger Logger [get]
Gets the logger that is used to log errors and warnings.
virtual string Code [get, set]
Gets or sets code to be compiled. Get: If not assigned explicitly then CodeBase is taken.
bool PerformNamesCorrection [get, set]
Specifies whether automatic checking and correction of the class and namespace name in the loaded code is performed. If correction is switched on, it is performed before every compilation. Correction first checks if the class name has already been used, and if this is the case, it changes the name to the one that has not yet been used. It is then checked whether the namespace and class names used in the code are the same as those set on the current script loader. If not then names are replaced. At this stage, the assumed namespace class names are the first namespace and the first class found in the code block.
virtual string LanguageName [get, protected set]
Language used by compiler.
virtual string ClassNamespace [get, protected set]
Namespace in which the compiled class is defined.
virtual string ClassInterface [get]
Interface that is implemented by the compiled class.
virtual string ClassName [get, set]
virtual string ClassFullName [get]
Name of the compiled class that contains loadable script.
virtual string AppDomainName [get, set]
Name of the application domain in which the class is loaded.
virtual string RunFunctionName [get, protected set]
Name of the method of dynamically loadable classes that contains the runnable script.
virtual string InitFunctionName [get, protected set]
Name of the initialization method of dynamically loadable classes.
virtual string ArgumentsName [get, set]
Agreed formal name of the arguments parameter. Agreement upon this name makes possible to execute scripts in which run arguments are referenced.
virtual string LibraryFilename [get, set]
virtual string LibraryDirectory [get, protected set]
Returns directory where library will be compiled, which will be the directory of the executable that started the application.
virtual string LibraryPath [get, protected set]
Path to the dll where code is compiled. We take the directory where executable is located.
virtual bool IsCodeLoaded [get, protected set]
Whether scripting code to be compiled is loaded.
virtual bool IsCompiled [get, protected set]
Whether the code is compiled.
virtual bool IsClassLoaded [get, protected set]
Whether the compiled class corresponding to the script is prepared.
virtual bool IsObjectPrepared [get, protected set]
Whether an instance of the object is prepared to be used.
virtual CompilerResults CompilerResults [get, protected set]
Results of compilation.
virtual List< String > ReferencedAssemblies [get]
List of assemblies that are referenced when compiling the code. Contains names of files containing referenced assemblies.
virtual bool ReferenceAllLoadedAssemblies [get, set]
If true then all assemblies that are currently loaded by the application are also added to the referenced assemblies when script code is compiled. This makes sure that all that is necessary is actually referenced.
virtual AppDomain ApplicationDomain [get, set]
Application domain used by the current script loader for loading assemblies.
virtual Assembly Assembly [get, protected set]
Gets or sets the assembly that has been compiled and loaded into the current application domain from the source code.
virtual ILoadableScript CreatedObject [get, protected set]
Object of the compiled class that has beeen created.
Properties inherited from IG.Lib.ILockable
object Lock [get]
Private Attributes
bool _isScriptLoaderInitialized = false
object _mainLock = new object()
int _outputLevel = Util.OutputLevel
Logger _logger = new Logger()
bool _nameCorrection = true
string _languageName = "CSharp"
string _namespace = "IG.Script"
string _interface = "IG.Lib.ILoadableScript"
string _className = "TestClass"
string _appDomainName = "NewDomain"
string _runFunctionName = "RunThis"
string _initFunctionName = "InitializeThis"
string _argumentsName = "arguments"
string _libraryPath = null
string _libraryDirectory = null
bool _isCodeLoaded = false
bool _isCompiled = false
bool _isClassLoaded = false
bool _isObjectPrepared = false
CompilerResults _compilerResults
AppDomain _applicationDomain
Assembly _assembly
ILoadableScript _runnableObject
Static Private Attributes
static bool _isScriptingInitialized = false
static List< string > _defaultAssemblies
static SortedList< string, string > _usedClassFullNames
static ScriptLoaderBase _global
Detailed Description
Dynamically compiles, loads and instantiates classes of type ILoadableScript from files or from strings.
$A Igor Jul09 Feb10;
Definition at line 59 of file Loader.cs.
Constructor & Destructor Documentation
ScriptLoaderBase()
IG.Lib.ScriptLoaderBase.ScriptLoaderBase () inline
Definition at line 64 of file Loader.cs.
References IG.Lib.ScriptLoaderBase.AddDefaultReferencedAssemblies(), IG.Lib.ScriptLoaderBase.AddReferencedAssemblies(), and IG.Lib.ScriptLoaderBase.InitializeScriptLoader().
Member Function Documentation
InitializeScriptLoader()
virtual void IG.Lib.ScriptLoaderBase.InitializeScriptLoader () inline virtual
Initializes the current script loader.
Definition at line 83 of file Loader.cs.
References IG.Lib.ScriptLoaderBase.InitializeScripting(), IG.Lib.ScriptLoaderBase.IsScriptingInitialized, and IG.Lib.ScriptLoaderBase.IsScriptLoaderInitialized.
Referenced by IG.Lib.ScriptLoaderBase.ScriptLoaderBase().
InitializeScripting()
static void IG.Lib.ScriptLoaderBase.InitializeScripting () inline static
Initializes the scripting system.
Definition at line 119 of file Loader.cs.
References IG.Lib.ScriptLoaderBase.IsScriptingInitialized.
Referenced by IG.Lib.ScriptLoaderBase.InitializeScriptLoader().
GetLoadableScriptC()
static ILoadableScript IG.Lib.ScriptLoaderBase.GetLoadableScriptC (ILoadableScript scriptObject) inline static
Returns the loadable script object if the script object is actually loadable, or null if it is not meant as loadable.
Parameters
scriptObject Script object to be returned if the object itself is loadable.
This method filters out the controllable loadable scripts (i.e. the scripts that implement the ILoadableScriptC interface) that are not loadable by property ILoadableScriptC.IsLoadable.
Definition at line 154 of file Loader.cs.
References IG.Lib.ILoadableScriptC.IsLoadable.
Referenced by IG.Lib.ScriptLoaderBase.CreateLoadableObject(), and IG.Lib.ScriptLoaderBase.CreateScriptObject().
LoadFileBytes()
static byte [] IG.Lib.ScriptLoaderBase.LoadFileBytes (string filePath) inline static
Copies the specified file to byte array and returns it.
TODO: move this to utils or something like that!
Definition at line 169 of file Loader.cs.
Referenced by IG.Lib.ScriptLoaderBase.Compile().
CreateScriptObject() [1/2]
static ILoadableScript IG.Lib.ScriptLoaderBase.CreateScriptObject (string scriptClassFullName) inline static
Creates and returns a new script obect of the specified type.
null is returned if the oject can not be created (but no exception is thrown).
Parameters
scriptClassFullName Full name of the script class whose object is created.
Definition at line 184 of file Loader.cs.
Referenced by IG.Lib.CommandLineApplicationInterpreter.CmdRunInternalScriptClass().
CreateScriptObject() [2/2]
static ILoadableScript IG.Lib.ScriptLoaderBase.CreateScriptObject (string scriptClassFullName, int outputLevel) inline static
Creates and returns a new script obect of the specified type.
null is returned if the oject can not be created (but no exception is thrown).
Parameters
scriptClassFullName Full name of the script class whose object is created.
outputLevel Level of output to console.
Definition at line 193 of file Loader.cs.
References IG.Lib.ScriptLoaderBase.Assembly, and IG.Lib.ScriptLoaderBase.GetLoadableScriptC().
AddDefaultAssemblies()
static void IG.Lib.ScriptLoaderBase.AddDefaultAssemblies (params string[] assemblies) inline static
Add the specified assemblies (just their names) to the list of assemblies that are referenced by newly created script loaders by default.
Parameters
assemblies Names of assemblies that are added to the list.
Definition at line 316 of file Loader.cs.
References IG.Lib.ScriptLoaderBase.DefaultAssemblies, and IG.Lib.Util.LockGlobal.
Referenced by IG.Lib.ApplicationCommandlineBase.AddDefaultAssemblies(), IG.Lib.ShellApplication< CommandLineApplicationInterpreter >.AddDefaultAssemblies(), IG.Lib.Module.AddDefaultAssembliesExtShellApp(), and IG.Lib.Module.AnnAdd().
RemoveDefaultAssemblies()
static void IG.Lib.ScriptLoaderBase.RemoveDefaultAssemblies (params string[] assemblies) inline static
Removes the specified assemblies from the list of default assemblies that are referenced by newly created script loaders.
Parameters
assemblies names of assemblies that are removed from the list.
Definition at line 339 of file Loader.cs.
References IG.Lib.ScriptLoaderBase.DefaultAssemblies, and IG.Lib.Util.LockGlobal.
ClearDefaultAssemblies()
static void IG.Lib.ScriptLoaderBase.ClearDefaultAssemblies () inline static
Clears the list of assemblies that are referenced by default by newly created script loaders.
Definition at line 363 of file Loader.cs.
References IG.Lib.ScriptLoaderBase.DefaultAssemblies, and IG.Lib.Util.LockGlobal.
AddDefaultReferencedAssemblies()
void IG.Lib.ScriptLoaderBase.AddDefaultReferencedAssemblies () inline protected
Add assemblies that are referenced by default to the list of assemblies that are referenced by the current script loader.
Assemblies that are referenced by default can be set by the ScriptLoaderBase.AddDefaultAssemblies method.
Definition at line 376 of file Loader.cs.
References IG.Lib.ScriptLoaderBase.AddReferencedAssemblies(), and IG.Lib.ScriptLoaderBase.DefaultAssemblies.
Referenced by IG.Lib.ScriptLoaderBase.ScriptLoaderBase().
IsClassFullNameUsed()
static bool IG.Lib.ScriptLoaderBase.IsClassFullNameUsed (string classFillName) inline static
Returns a flag indicating whether the specified class full name has already been used or not.
Parameters
classFillName Fully qualified class name (namespace and class).
Definition at line 412 of file Loader.cs.
References IG.Lib.ScriptLoaderBase.UsedClassFullNames.
Referenced by IG.Lib.ScriptLoaderBase.CheckAndCorrectNames(), and IG.Lib.ScriptLoaderBase.Compile().
ClearLogger()
virtual void IG.Lib.ScriptLoaderBase.ClearLogger () inline virtual
Clears the logger.
Definition at line 464 of file Loader.cs.
References IG.Lib.Logger.Clear(), and IG.Lib.ScriptLoaderBase.Lock.
GetExampleCode() [1/2]
virtual string IG.Lib.ScriptLoaderBase.GetExampleCode () inline virtual
Gets example code base (a template code for compiling) where names of classes, methods etc. are properly set.
Definition at line 476 of file Loader.cs.
GetExampleCode() [2/2]
virtual string IG.Lib.ScriptLoaderBase.GetExampleCode (string pureScript) inline virtual
Returns a complete example code that can be loaded and run.
<pparam name="pureScript">Code that is inserted in the LoadableScriptBase.RunThis method.</pparam>
Definition at line 487 of file Loader.cs.
References IG.Lib.ScriptLoaderBase.ArgumentsName, IG.Lib.ScriptLoaderBase.ClassInterface, IG.Lib.ScriptLoaderBase.ClassName, IG.Lib.ScriptLoaderBase.ClassNamespace, IG.Lib.ScriptLoaderBase.InitFunctionName, and IG.Lib.ScriptLoaderBase.RunFunctionName.
FindNameAfterKeyword()
static string IG.Lib.ScriptLoaderBase.FindNameAfterKeyword (string code, string keyword, string allowedCharacters) inline static
In the specified string, finds a name that follows the specified keyword, and returns it. Name must directly follow the keyword with only blank characters between them, and it end at the first character that is not alphanumeric and is also not contained in the specified string of allowed characters.
Parameters
code String in which the specified name is searched for.
keyword Keyword.
allowedCharacters Eventual string arguments that contains characters that are allowed beside the alphanumeric characters.
Returns
Name that follows the specified keyword.
This functions can be used e.g. for searching for class names or namespace names in code blocks. The method is currently not implemented very efficiently because it uses access to characters of a string through their within the string.
Definition at line 533 of file Loader.cs.
Referenced by IG.Lib.ScriptLoaderBase.FindClassName(), and IG.Lib.ScriptLoaderBase.FindNamespace().
FindNamespace()
static string IG.Lib.ScriptLoaderBase.FindNamespace (string code) inline static
Finds and returns the name of the first namespace that is defined in the specified C# code block. A null string is returned if the name can not be found.
Parameters
code Code block where namespace name is searched for.
Definition at line 582 of file Loader.cs.
References IG.Lib.ScriptLoaderBase.FindNameAfterKeyword().
Referenced by IG.Lib.ScriptLoaderBase.CheckAndCorrectNames().
FindClassName()
static string IG.Lib.ScriptLoaderBase.FindClassName (string code) inline static
Finds and returns the name of the first class that is defined in the specified C# code block. A null string is returned if the name can not be found.
Parameters
code Code block where class name is searched for.
Definition at line 590 of file Loader.cs.
References IG.Lib.ScriptLoaderBase.FindNameAfterKeyword().
Referenced by IG.Lib.ScriptLoaderBase.CheckAndCorrectNames(), and IG.Lib.ScriptLoaderBase.LoadCode().
CheckAndCorrectNames()
void IG.Lib.ScriptLoaderBase.CheckAndCorrectNames () inline
Corrects the ClassName (if the current class name has already been used) and namespace and class name in the loaded scritp code (if they don't correspond to ClassNamespace and ClassName, respectively).
Definition at line 656 of file Loader.cs.
References IG.Lib.ScriptLoaderBase.ClassFullName, IG.Lib.ScriptLoaderBase.ClassName, IG.Lib.ScriptLoaderBase.ClassNamespace, IG.Lib.ScriptLoaderBase.Code, IG.Lib.ScriptLoaderBase.FindClassName(), IG.Lib.ScriptLoaderBase.FindNamespace(), IG.Lib.ScriptLoaderBase.IsClassFullNameUsed(), IG.Lib.ScriptLoaderBase.Lock, IG.Lib.Logger.LogWarning(), and IG.Lib.ScriptLoaderBase.OutputLevel.
Referenced by IG.Lib.ScriptLoaderBase.Compile().
GetExecutableDirectory()
virtual string IG.Lib.ScriptLoaderBase.GetExecutableDirectory () inline virtual
Returns the directory containing the executable that started the current application.
Definition at line 845 of file Loader.cs.
References IG.Lib.UtilSystem.GetExecutableDirectory().
AddReferencedAssembly()
virtual void IG.Lib.ScriptLoaderBase.AddReferencedAssembly (string assemblyFile) inline virtual
Adds an additional referenced assembly by name of the assembly file. Assmebly is only added if it is not yet contained in the list of referenced assemblies and if the specified assembly file name is not null or empty string.
Parameters
assemblyFile File name of the assembly that is added to referenced assemblies.
Definition at line 1032 of file Loader.cs.
References IG.Lib.ScriptLoaderBase.Lock, and IG.Lib.ScriptLoaderBase.ReferencedAssemblies.
Referenced by IG.Lib.ScriptLoaderBase.AddReferencedAssemblies().
AddReferencedAssemblies() [1/2]
virtual void IG.Lib.ScriptLoaderBase.AddReferencedAssemblies (params string[] assemblyFiles) inline virtual
Adds the specified assemblies to the list of referenced assemblies. Assemblise are added only if not yet on the list and if their names are not null or empty strings.
Parameters
assemblyFiles A table of file names of the assemblies to be added.
Definition at line 1045 of file Loader.cs.
References IG.Lib.ScriptLoaderBase.AddReferencedAssembly(), and IG.Lib.ScriptLoaderBase.Lock.
Referenced by IG.Lib.ScriptLoaderBase.AddDefaultReferencedAssemblies(), IG.Lib.ScriptLoaderBase.Compile(), IG.Lib.ScriptLoaderBase.GetReferencedAssemblies(), IG.Lib.ScriptLoaderBase.ScriptLoaderBase(), IG.Lib.ScriptLoaderIGLib.ScriptLoaderIGLib(), IG.Lib.ScriptLoaderIGLib.ScriptLoaderTest.ScriptLoaderTest(), and IG.Lib.ScriptLoaderBase.SetReferencedAssemblies().
SetReferencedAssemblies()
virtual void IG.Lib.ScriptLoaderBase.SetReferencedAssemblies (params string[] assemblyFiles) inline virtual
Sets the list of referenced assemblies in such a way that it contains only the specified assemblies.
Parameters
assemblyFiles Array of file names of the assemblies to be contained in the list.
Definition at line 1060 of file Loader.cs.
References IG.Lib.ScriptLoaderBase.AddReferencedAssemblies(), IG.Lib.ScriptLoaderBase.Lock, and IG.Lib.ScriptLoaderBase.ReferencedAssemblies.
RemoveReferencedAssembly()
virtual void IG.Lib.ScriptLoaderBase.RemoveReferencedAssembly (string assemblyFile) inline virtual
Removes the specified assembly from the list of referenced assemblies. If the specified assembly does not exist on the list or it is a null or empty string then nothing happens.
Parameters
assemblyFile File name of the assembly to be removed.
Definition at line 1072 of file Loader.cs.
References IG.Lib.ScriptLoaderBase.Lock, and IG.Lib.ScriptLoaderBase.ReferencedAssemblies.
Referenced by IG.Lib.ScriptLoaderBase.RemoveReferencedAssemblies().
RemoveReferencedAssemblies()
virtual void IG.Lib.ScriptLoaderBase.RemoveReferencedAssemblies (params string[] assemblyFiles) inline virtual
Removes the specified assemblies from the list of referenced assemblies.
Parameters
assemblyFiles Array of file names of the assemblies to be removed from the list.
Definition at line 1083 of file Loader.cs.
References IG.Lib.ScriptLoaderBase.Lock, and IG.Lib.ScriptLoaderBase.RemoveReferencedAssembly().
RemoveAllReferencedAssemblies()
virtual void IG.Lib.ScriptLoaderBase.RemoveAllReferencedAssemblies () inline virtual
Removes all assemblies from tehe list of referenced assemblies.
Definition at line 1096 of file Loader.cs.
References IG.Lib.ScriptLoaderBase.Lock, and IG.Lib.ScriptLoaderBase.ReferencedAssemblies.
CreateNonexistentFilePath()
static string IG.Lib.ScriptLoaderBase.CreateNonexistentFilePath (string originalPath) inline static protected
Returns a file path that does not exist and is derived form the specified file path by adding a suffix composed of underscore and a number.
Parameters
originalPath Original file path.
Even if the file with original path does not exist, the method finds and returns a new path.
Definition at line 1109 of file Loader.cs.
Referenced by IG.Lib.ScriptLoaderBase.Compile(), and IG.Lib.ScriptLoaderBase.CreateNonexistentLibraryPath().
CreateNonexistentLibraryPath()
void IG.Lib.ScriptLoaderBase.CreateNonexistentLibraryPath () inline protected
Modifies library path in such a way that it points to an non-existent file.
Definition at line 1128 of file Loader.cs.
References IG.Lib.ScriptLoaderBase._originalLibraryPath, IG.Lib.ScriptLoaderBase.CreateNonexistentFilePath(), IG.Lib.ScriptLoaderBase.LibraryPath, and IG.Lib.ScriptLoaderBase.Lock.
AddReferencedAssemblies() [2/2]
virtual void IG.Lib.ScriptLoaderBase.AddReferencedAssemblies (System.CodeDom.Compiler.CompilerParameters compilerParameters) inline protected virtual
Adds referenced assemblies to the specified compiler parameters, according to current settings.
Parameters
compilerParameters Compiler parameters on which referenced assemblies ar added.
Definition at line 1142 of file Loader.cs.
References IG.Lib.ScriptLoaderBase.Assembly, IG.Lib.ScriptLoaderBase.LibraryDirectory, IG.Lib.Logger.LogWarning(), IG.Lib.ScriptLoaderBase.OutputLevel, IG.Lib.ScriptLoaderBase.ReferenceAllLoadedAssemblies, and IG.Lib.ScriptLoaderBase.ReferencedAssemblies.
GetReferencedAssemblies()
virtual string [] IG.Lib.ScriptLoaderBase.GetReferencedAssemblies () inline virtual
Returns an array of assemblies (paths, sometimes only file names) that are currently referenced by the compiler on the current script loader.
Definition at line 1228 of file Loader.cs.
References IG.Lib.ScriptLoaderBase.AddReferencedAssemblies().
Referenced by IG.Lib.CommandLineApplicationInterpreter.GetLoadableScriptReferencedAssemblies().
Compile()
virtual string IG.Lib.ScriptLoaderBase.Compile () inline virtual
Compiles the code that is currently loaded by the current loader, and returns full name of the compiled script class.
Returns
Full name of the class implementing teh ILoadableScript interface that has been compiled.
Definition at line 1243 of file Loader.cs.
References IG.Lib.ScriptLoaderBase.AddReferencedAssemblies(), IG.Lib.ScriptLoaderBase.AppDomainName, IG.Lib.ScriptLoaderBase.ApplicationDomain, IG.Lib.ScriptLoaderBase.Assembly, IG.Lib.ScriptLoaderBase.CheckAndCorrectNames(), IG.Lib.ScriptLoaderBase.ClassFullName, IG.Lib.ScriptLoaderBase.Code, IG.Lib.ScriptLoaderBase.CompilerResults, IG.Lib.ScriptLoaderBase.CreateNonexistentFilePath(), IG.Lib.Logger.GetErrorsReport(), IG.Lib.ScriptLoaderBase.IsClassFullNameUsed(), IG.Lib.ScriptLoaderBase.IsCompiled, IG.Lib.ScriptLoaderBase.LanguageName, IG.Lib.ScriptLoaderBase.LibraryPath, IG.Lib.ScriptLoaderBase.LoadFileBytes(), IG.Lib.ScriptLoaderBase.Lock, IG.Lib.Logger.LogError(), IG.Lib.Logger.LogInfo(), IG.Lib.Logger.LogWarning(), IG.Lib.ScriptLoaderBase.OutputLevel, IG.Lib.ScriptLoaderBase.PerformNamesCorrection, and IG.Lib.ScriptLoaderBase.UsedClassFullNames.
Referenced by IG.Lib.RealFunctionLoader.Compile(), IG.Lib.ScalarFunctionLoader.Compile(), IG.Lib.ScriptLoaderBase.CreateLoadableObject(), and IG.Lib.ScriptLoaderBase.Run().
UnloadApplicationDomain()
virtual void IG.Lib.ScriptLoaderBase.UnloadApplicationDomain () inline virtual
Unloads the application domain used by the current script loader.
Definition at line 1400 of file Loader.cs.
References IG.Lib.ScriptLoaderBase.ApplicationDomain, and IG.Lib.ScriptLoaderBase.Lock.
CreateObject()
virtual ILoadableScript IG.Lib.ScriptLoaderBase.CreateObject (string[] initializationArguments) inline virtual
Creates and returns an object of the class that has been last compiled. The created object is also stored such that it can later be accessed through the CreatedObject property.
Parameters
initializationArguments Initialization arguments.
Definition at line 1453 of file Loader.cs.
References IG.Lib.ScriptLoaderBase.CreateLoadableObject().
Referenced by IG.Lib.ScriptLoaderBase.CreateObjectFromCode(), IG.Lib.ScriptLoaderBase.CreateObjectFromFile(), IG.Lib.ScriptLoaderBase.Run(), IG.Lib.ScriptLoaderBase.RunCode(), and IG.Lib.ScriptLoaderBase.RunFile().
CreateLoadableObject() [1/2]
virtual ILoadableScript IG.Lib.ScriptLoaderBase.CreateLoadableObject (string[] initializationArguments, bool storeObject) inline virtual
Creates and returns an object of the class that has been last compiled.
Parameters
initializationArguments Initialization arguments.
storeObject If true then the created object is stored such that it can be accessed via CreatedObject property.
Definition at line 1462 of file Loader.cs.
References IG.Lib.ScriptLoaderBase.ClassFullName, IG.Lib.ScriptLoaderBase.Compile(), IG.Lib.ScriptLoaderBase.CreatedObject, and IG.Lib.ScriptLoaderBase.IsCompiled.
Referenced by IG.Lib.ScriptLoaderBase.CreateObject().
CreateLoadableObject() [2/2]
virtual ILoadableScript IG.Lib.ScriptLoaderBase.CreateLoadableObject (string[] initializationArguments, string classFullName) inline virtual
Creates and returns an object of the specified loadable class.
Parameters
initializationArguments Initialization arguments.
classFullName Full name of the class that is instantiated.
Definition at line 1475 of file Loader.cs.
References IG.Lib.ScriptLoaderBase.Assembly, IG.Lib.ScriptLoaderBase.GetLoadableScriptC(), and IG.Lib.ILoadableScript.InitializationArguments.
Run() [1/2]
virtual void IG.Lib.ScriptLoaderBase.Run (string[] initializationAndRunArguments) inline virtual
Runs the object of the compiled loadable class (calls its Run() method) that is currently loaded by the current loader. Compiles the code and creates the object if necessary.
Parameters
initializationAndRunArguments Arguments used both for initialization and running of the object.
Definition at line 1491 of file Loader.cs.
Run() [2/2]
virtual void IG.Lib.ScriptLoaderBase.Run (string[] initializationArguments, string[] runArguments) inline virtual
Runs the object of the compiled loadable class (calls its Run() method) that is currently loaded by the current loader. Compiles the code and creates the object if necessary.
Parameters
initializationArguments Argumets used for initialization of the object.
runArguments Arguments used to run the object.
Definition at line 1501 of file Loader.cs.
References IG.Lib.ScriptLoaderBase.Compile(), IG.Lib.ScriptLoaderBase.CreatedObject, IG.Lib.ScriptLoaderBase.CreateObject(), IG.Lib.ScriptLoaderBase.IsClassLoaded, IG.Lib.ScriptLoaderBase.IsObjectPrepared, IG.Lib.ScriptLoaderBase.Lock, and IG.Lib.ILoadableScript.Run().
LoadCode() [1/2]
void IG.Lib.ScriptLoaderBase.LoadCode (string code, string classFullName) inline
Loads code form a string.
Parameters
code String containing script code that is loaded.
classFullName Name of the class that is contained in the code and contains loadable script that can be executed.
Definition at line 1528 of file Loader.cs.
References IG.Lib.ScriptLoaderBase.ClassName, IG.Lib.ScriptLoaderBase.Code, IG.Lib.ScriptLoaderBase.FindClassName(), and IG.Lib.ScriptLoaderBase.Lock.
Referenced by IG.Lib.ScriptLoaderBase.CreateObjectFromCode(), IG.Lib.ScriptLoaderBase.CreateObjectFromFile(), IG.Lib.ScriptLoaderBase.LoadCode(), IG.Lib.ScriptLoaderBase.LoadFile(), IG.Lib.ScriptLoaderBase.RunCode(), and IG.Lib.ScriptLoaderBase.RunFile().
LoadCode() [2/2]
void IG.Lib.ScriptLoaderBase.LoadCode (string code) inline
Loads code form a string. Class name is extracted from the code.
Parameters
code String containing script code that is loaded.
Definition at line 1547 of file Loader.cs.
References IG.Lib.ScriptLoaderBase.LoadCode().
CreateObjectFromCode() [1/2]
ILoadableScript IG.Lib.ScriptLoaderBase.CreateObjectFromCode (string code, string className, string[] initializationArguments) inline
Creates and returns a loadable script object form code.
Parameters
code Code that contains class definition and is dynamically compiled.
className Name of the class containing loadable script code.
initializationArguments Initialization arguments for the created object.
Definition at line 1556 of file Loader.cs.
References IG.Lib.ScriptLoaderBase.CreateObject(), IG.Lib.ScriptLoaderBase.LoadCode(), and IG.Lib.ScriptLoaderBase.Lock.
Referenced by IG.Lib.LoadableScriptInterpreterBase.AddCommandFromCode().
CreateObjectFromCode() [2/2]
ILoadableScript IG.Lib.ScriptLoaderBase.CreateObjectFromCode (string code, string[] initializationArguments) inline
Creates and returns a loadable script object form code. Class name is extracted from code.
Parameters
code Code that contains class definition and is dynamically compiled.
initializationArguments Initialization arguments for the created object.
Definition at line 1569 of file Loader.cs.
References IG.Lib.ScriptLoaderBase.CreateObject(), IG.Lib.ScriptLoaderBase.LoadCode(), and IG.Lib.ScriptLoaderBase.Lock.
RunCode() [1/4]
string IG.Lib.ScriptLoaderBase.RunCode (string code, string className, string[] initializationArguments, string[] runArguments) inline
Creates and runs a loadable script object form code.
Parameters
code Code that contains class definition and is dynamically compiled.
className Name of the class containing loadable script code.
initializationArguments Initialization arguments for the created object.
runArguments Arguments passed to the execution method of the loadable script.
Definition at line 1584 of file Loader.cs.
References IG.Lib.ScriptLoaderBase.CreateObject(), IG.Lib.ScriptLoaderBase.LoadCode(), IG.Lib.ScriptLoaderBase.Lock, and IG.Lib.ILoadableScript.Run().
RunCode() [2/4]
string IG.Lib.ScriptLoaderBase.RunCode (string code, string[] initializationArguments, string[] runArguments) inline
Creates and returns a loadable script object form code. Class name is extracted from code.
Parameters
code Code that contains class definition and is dynamically compiled.
initializationArguments Initialization arguments for the created object.
runArguments Arguments passed to the execution mathod of the loadable script.
Definition at line 1599 of file Loader.cs.
References IG.Lib.ScriptLoaderBase.CreateObject(), IG.Lib.ScriptLoaderBase.LoadCode(), IG.Lib.ScriptLoaderBase.Lock, and IG.Lib.ILoadableScript.Run().
RunCode() [3/4]
string IG.Lib.ScriptLoaderBase.RunCode (string code, string className, string[] initializationAndRunArguments) inline
Runs a loadable script object form code.
Parameters
code Code that contains class definition and is dynamically compiled.
className Name of the class containing loadable script code.
initializationAndRunArguments Arguments used both for initialization of the loadable script object and as parameters of the executable method..
Definition at line 1613 of file Loader.cs.
References IG.Lib.ScriptLoaderBase.CreateObject(), IG.Lib.ScriptLoaderBase.LoadCode(), IG.Lib.ScriptLoaderBase.Lock, and IG.Lib.ILoadableScript.Run().
RunCode() [4/4]
string IG.Lib.ScriptLoaderBase.RunCode (string code, string[] initializationAndRunArguments) inline
Creates and returns a loadable script object form code. Class name is extracted from code.
Parameters
code Code that contains class definition and is dynamically compiled.
initializationAndRunArguments Arguments used both for initialization of the loadable script object and as parameters of the executable method..
Definition at line 1628 of file Loader.cs.
References IG.Lib.ScriptLoaderBase.CreateObject(), IG.Lib.ScriptLoaderBase.LoadCode(), IG.Lib.ScriptLoaderBase.Lock, and IG.Lib.ILoadableScript.Run().
GetFileContents()
static string IG.Lib.ScriptLoaderBase.GetFileContents (string filePath) inline static
Returns contents of the specified file.
Parameters
filePath Path to the file.
Returns
Full contents of the file as string.
Definition at line 1643 of file Loader.cs.
Referenced by IG.Lib.ScriptLoaderBase.CreateObjectFromFile(), IG.Lib.ScriptLoaderBase.LoadFile(), and IG.Lib.ScriptLoaderBase.RunFile().
LoadFile() [1/2]
void IG.Lib.ScriptLoaderBase.LoadFile (string filePath, string className) inline
Loads loadable script code form the specified file.
Parameters
filePath Path to the file that contains script code.
className Name of the class that is contained in the code and embeds loadable script that can be executed.
Definition at line 1661 of file Loader.cs.
References IG.Lib.ScriptLoaderBase.GetFileContents(), and IG.Lib.ScriptLoaderBase.LoadCode().
LoadFile() [2/2]
void IG.Lib.ScriptLoaderBase.LoadFile (string filePath) inline
Loads loadable script code form a file. Name of the class is extracted from the file contents.
Parameters
filePath Path to the file that contains script code.
Definition at line 1670 of file Loader.cs.
References IG.Lib.ScriptLoaderBase.GetFileContents(), and IG.Lib.ScriptLoaderBase.LoadCode().
CreateObjectFromFile() [1/2]
ILoadableScript IG.Lib.ScriptLoaderBase.CreateObjectFromFile (string filePath, string className, string[] initializationArguments) inline
Creates and returns a loadable script object form a file containing its code.
Parameters
filePath Path to the file that contains script code.
className Name of the class containing class definition for loadable script objects.
initializationArguments Initialization arguments for the created object.
Definition at line 1680 of file Loader.cs.
References IG.Lib.ScriptLoaderBase.CreateObject(), IG.Lib.ScriptLoaderBase.GetFileContents(), IG.Lib.ScriptLoaderBase.LoadCode(), and IG.Lib.ScriptLoaderBase.Lock.
Referenced by IG.Lib.LoadableScriptInterpreterBase.AddCommandFromFile().
CreateObjectFromFile() [2/2]
ILoadableScript IG.Lib.ScriptLoaderBase.CreateObjectFromFile (string filePath, string[] initializationArguments) inline
Creates and returns a loadable script object form code. Class name is extracted from code.
Parameters
filePath Path to the file that contains script code.
initializationArguments Initialization arguments for the created object.
Definition at line 1694 of file Loader.cs.
References IG.Lib.ScriptLoaderBase.CreateObject(), IG.Lib.ScriptLoaderBase.GetFileContents(), IG.Lib.ScriptLoaderBase.LoadCode(), and IG.Lib.ScriptLoaderBase.Lock.
RunFile() [1/4]
string IG.Lib.ScriptLoaderBase.RunFile (string filePath, string className, string[] initializationArguments, string[] runArguments) inline
Executes a loadable script form a file. The file must contain definition of the loadable script class that is used to instantiate an object and execute it.
Parameters
filePath Path to the file that contains script code.
className Name of the class containing loadable script code.
initializationArguments Initialization arguments for the created object.
runArguments Arguments passed to the execution mathod of the loadable script.
Definition at line 1711 of file Loader.cs.
References IG.Lib.ScriptLoaderBase.CreateObject(), IG.Lib.ScriptLoaderBase.GetFileContents(), IG.Lib.ScriptLoaderBase.LoadCode(), IG.Lib.ScriptLoaderBase.Lock, and IG.Lib.ILoadableScript.Run().
Referenced by IG.Lib.CommandLineApplicationInterpreter.RunScriptFile().
RunFile() [2/4]
string IG.Lib.ScriptLoaderBase.RunFile (string filePath, string[] initializationArguments, string[] runArguments) inline
Executes a loadable script form a file. The file must contain definition of the loadable script class that is used to instantiate an object and execute it. Class name is extracted from code.
Parameters
filePath Path to the file that contains script code.
initializationArguments Initialization arguments for the created object.
runArguments Arguments passed to the execution mathod of the loadable script.
Definition at line 1728 of file Loader.cs.
References IG.Lib.ScriptLoaderBase.CreateObject(), IG.Lib.ScriptLoaderBase.GetFileContents(), IG.Lib.ScriptLoaderBase.LoadCode(), IG.Lib.ScriptLoaderBase.Lock, and IG.Lib.ILoadableScript.Run().
RunFile() [3/4]
string IG.Lib.ScriptLoaderBase.RunFile (string filePath, string className, string[] initializationAndRunArguments) inline
Executes a loadable script form a file. The file must contain definition of the loadable script class that is used to instantiate an object and execute it. The same arguments are taken for initialization of the loadable script object and for execution of the script.
Parameters
filePath Path to the file that contains script code.
className Name of the class containing loadable script code.
initializationAndRunArguments Arguments used both for initialization of the loadable script object and as parameters of the executable method.
Definition at line 1746 of file Loader.cs.
References IG.Lib.ScriptLoaderBase.CreateObject(), IG.Lib.ScriptLoaderBase.GetFileContents(), IG.Lib.ScriptLoaderBase.LoadCode(), IG.Lib.ScriptLoaderBase.Lock, and IG.Lib.ILoadableScript.Run().
RunFile() [4/4]
string IG.Lib.ScriptLoaderBase.RunFile (string filePath, string[] initializationAndRunArguments) inline
Executes a loadable script form a file. The file must contain definition of the loadable script class that is used to instantiate an object and execute it. The same arguments are taken for initialization of the loadable script object and for execution of the script. Class name is extracted from code.
Parameters
filePath Path to the file that contains script code.
initializationAndRunArguments Arguments used both for initialization of the loadable script object and as parameters of the executable method.
Definition at line 1765 of file Loader.cs.
References IG.Lib.ScriptLoaderBase.CreateObject(), IG.Lib.ScriptLoaderBase.GetFileContents(), IG.Lib.ScriptLoaderBase.LoadCode(), IG.Lib.ScriptLoaderBase.Lock, and IG.Lib.ILoadableScript.Run().
Member Data Documentation
_isScriptLoaderInitialized
bool IG.Lib.ScriptLoaderBase._isScriptLoaderInitialized = false private
Definition at line 73 of file Loader.cs.
_isScriptingInitialized
bool IG.Lib.ScriptLoaderBase._isScriptingInitialized = false static private
Definition at line 109 of file Loader.cs.
_mainLock
object IG.Lib.ScriptLoaderBase._mainLock = new object() private
Definition at line 135 of file Loader.cs.
_defaultAssemblies
List<string> IG.Lib.ScriptLoaderBase._defaultAssemblies static private
Definition at line 297 of file Loader.cs.
_usedClassFullNames
SortedList<string, string> IG.Lib.ScriptLoaderBase._usedClassFullNames static private
Definition at line 389 of file Loader.cs.
_global
ScriptLoaderBase IG.Lib.ScriptLoaderBase._global static private
Definition at line 415 of file Loader.cs.
_outputLevel
int IG.Lib.ScriptLoaderBase._outputLevel = Util.OutputLevel private
Definition at line 448 of file Loader.cs.
_logger
Logger IG.Lib.ScriptLoaderBase._logger = new Logger() private
Definition at line 455 of file Loader.cs.
_code
string IG.Lib.ScriptLoaderBase._code = null protected
Definition at line 518 of file Loader.cs.
_nameCorrection
bool IG.Lib.ScriptLoaderBase._nameCorrection = true private
Definition at line 629 of file Loader.cs.
_languageName
string IG.Lib.ScriptLoaderBase._languageName = "CSharp" private
Definition at line 631 of file Loader.cs.
_namespace
string IG.Lib.ScriptLoaderBase._namespace = "IG.Script" private
Definition at line 632 of file Loader.cs.
_interface
string IG.Lib.ScriptLoaderBase._interface = "IG.Lib.ILoadableScript" private
Definition at line 633 of file Loader.cs.
_className
string IG.Lib.ScriptLoaderBase._className = "TestClass" private
Definition at line 634 of file Loader.cs.
_appDomainName
string IG.Lib.ScriptLoaderBase._appDomainName = "NewDomain" private
Definition at line 635 of file Loader.cs.
_runFunctionName
string IG.Lib.ScriptLoaderBase._runFunctionName = "RunThis" private
Definition at line 637 of file Loader.cs.
_initFunctionName
string IG.Lib.ScriptLoaderBase._initFunctionName = "InitializeThis" private
Definition at line 638 of file Loader.cs.
_argumentsName
string IG.Lib.ScriptLoaderBase._argumentsName = "arguments" private
Definition at line 639 of file Loader.cs.
_libraryFilename
string IG.Lib.ScriptLoaderBase._libraryFilename = null protected
Definition at line 837 of file Loader.cs.
_libraryPath
string IG.Lib.ScriptLoaderBase._libraryPath = null private
Definition at line 838 of file Loader.cs.
_originalLibraryPath
string IG.Lib.ScriptLoaderBase._originalLibraryPath = null protected
Definition at line 839 of file Loader.cs.
Referenced by IG.Lib.ScriptLoaderBase.CreateNonexistentLibraryPath().
_libraryDirectory
string IG.Lib.ScriptLoaderBase._libraryDirectory = null private
Definition at line 840 of file Loader.cs.
_isCodeLoaded
bool IG.Lib.ScriptLoaderBase._isCodeLoaded = false private
Definition at line 922 of file Loader.cs.
_isCompiled
bool IG.Lib.ScriptLoaderBase._isCompiled = false private
Definition at line 923 of file Loader.cs.
_isClassLoaded
bool IG.Lib.ScriptLoaderBase._isClassLoaded = false private
Definition at line 924 of file Loader.cs.
_isObjectPrepared
bool IG.Lib.ScriptLoaderBase._isObjectPrepared = false private
Definition at line 925 of file Loader.cs.
_compilerResults
CompilerResults IG.Lib.ScriptLoaderBase._compilerResults private
Definition at line 997 of file Loader.cs.
_referencedAssimblies
List<string> IG.Lib.ScriptLoaderBase._referencedAssimblies = new List<string>() protected
Definition at line 1008 of file Loader.cs.
_referenceAllLoadedAssemblies
bool IG.Lib.ScriptLoaderBase._referenceAllLoadedAssemblies = true protected
Definition at line 1010 of file Loader.cs.
_applicationDomain
AppDomain IG.Lib.ScriptLoaderBase._applicationDomain private
Definition at line 1379 of file Loader.cs.
_assembly
Assembly IG.Lib.ScriptLoaderBase._assembly private
Definition at line 1380 of file Loader.cs.
_runnableObject
ILoadableScript IG.Lib.ScriptLoaderBase._runnableObject private
Definition at line 1381 of file Loader.cs.
Property Documentation
IsScriptLoaderInitialized
bool IG.Lib.ScriptLoaderBase.IsScriptLoaderInitialized get protected set
Whether the current script loader is initialized or not.
Definition at line 77 of file Loader.cs.
Referenced by IG.Lib.ScriptLoaderBase.InitializeScriptLoader().
IsScriptingInitialized
bool IG.Lib.ScriptLoaderBase.IsScriptingInitialized static get protected set
Whether scripting system is initialized or not.
Definition at line 113 of file Loader.cs.
Referenced by IG.Lib.ScriptLoaderBase.InitializeScripting(), and IG.Lib.ScriptLoaderBase.InitializeScriptLoader().
Lock
object IG.Lib.ScriptLoaderBase.Lock get
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
Definition at line 140 of file Loader.cs.
Referenced by IG.Lib.ScriptLoaderBase.AddReferencedAssemblies(), IG.Lib.ScriptLoaderBase.AddReferencedAssembly(), IG.Lib.ScriptLoaderBase.CheckAndCorrectNames(), IG.Lib.ScriptLoaderBase.ClearLogger(), IG.Lib.ScriptLoaderBase.Compile(), IG.Lib.ScriptLoaderBase.CreateNonexistentLibraryPath(), IG.Lib.ScriptLoaderBase.CreateObjectFromCode(), IG.Lib.ScriptLoaderBase.CreateObjectFromFile(), IG.Lib.ScriptLoaderBase.LoadCode(), IG.Lib.ScriptLoaderBase.RemoveAllReferencedAssemblies(), IG.Lib.ScriptLoaderBase.RemoveReferencedAssemblies(), IG.Lib.ScriptLoaderBase.RemoveReferencedAssembly(), IG.Lib.ScriptLoaderBase.Run(), IG.Lib.ScriptLoaderBase.RunCode(), IG.Lib.ScriptLoaderBase.RunFile(), IG.Lib.ScriptLoaderBase.SetReferencedAssemblies(), and IG.Lib.ScriptLoaderBase.UnloadApplicationDomain().
DefaultAssemblies
List<string> IG.Lib.ScriptLoaderBase.DefaultAssemblies static get protected
Gets the list of assemblies that are added to all newly created script loaders by default.
Definition at line 301 of file Loader.cs.
Referenced by IG.Lib.ScriptLoaderBase.AddDefaultAssemblies(), IG.Lib.ScriptLoaderBase.AddDefaultReferencedAssemblies(), IG.Lib.ScriptLoaderBase.ClearDefaultAssemblies(), and IG.Lib.ScriptLoaderBase.RemoveDefaultAssemblies().
UsedClassFullNames
SortedList<string, string> IG.Lib.ScriptLoaderBase.UsedClassFullNames static get protected
Stores used class names, i.e. class names that have already been used for dynamiically loaded classes.
Every time a new class is dynamically loaded, its full name is added to this list.
Definition at line 395 of file Loader.cs.
Referenced by IG.Lib.ScriptLoaderBase.Compile(), and IG.Lib.ScriptLoaderBase.IsClassFullNameUsed().
Global
ScriptLoaderBase IG.Lib.ScriptLoaderBase.Global static get set
Global script loader. Getter always returns a non-null object.
Definition at line 420 of file Loader.cs.
OutputLevel
int IG.Lib.ScriptLoaderBase.OutputLevel get set
Definbes level of output on console that is generated by some operations. 0 means that no output will be written to the console.
Definition at line 453 of file Loader.cs.
Referenced by IG.Lib.ScriptLoaderBase.AddReferencedAssemblies(), IG.Lib.ScriptLoaderBase.CheckAndCorrectNames(), and IG.Lib.ScriptLoaderBase.Compile().
Logger
virtual Logger IG.Lib.ScriptLoaderBase.Logger get
Gets the logger that is used to log errors and warnings.
Definition at line 459 of file Loader.cs.
Code
virtual string IG.Lib.ScriptLoaderBase.Code get set
Gets or sets code to be compiled. Get: If not assigned explicitly then CodeBase is taken.
Definition at line 599 of file Loader.cs.
Referenced by IG.Lib.ScriptLoaderBase.CheckAndCorrectNames(), IG.Lib.RealFunctionLoader.Compile(), IG.Lib.ScalarFunctionLoader.Compile(), IG.Lib.ScriptLoaderBase.Compile(), and IG.Lib.ScriptLoaderBase.LoadCode().
PerformNamesCorrection
bool IG.Lib.ScriptLoaderBase.PerformNamesCorrection get set
Specifies whether automatic checking and correction of the class and namespace name in the loaded code is performed. If correction is switched on, it is performed before every compilation. Correction first checks if the class name has already been used, and if this is the case, it changes the name to the one that has not yet been used. It is then checked whether the namespace and class names used in the code are the same as those set on the current script loader. If not then names are replaced. At this stage, the assumed namespace class names are the first namespace and the first class found in the code block.
Definition at line 651 of file Loader.cs.
Referenced by IG.Lib.ScriptLoaderBase.Compile().
LanguageName
virtual string IG.Lib.ScriptLoaderBase.LanguageName get protected set
Language used by compiler.
Definition at line 719 of file Loader.cs.
Referenced by IG.Lib.ScriptLoaderBase.Compile().
ClassNamespace
virtual string IG.Lib.ScriptLoaderBase.ClassNamespace get protected set
Namespace in which the compiled class is defined.
Definition at line 734 of file Loader.cs.
Referenced by IG.Lib.ScriptLoaderBase.CheckAndCorrectNames(), and IG.Lib.ScriptLoaderBase.GetExampleCode().
ClassInterface
virtual string IG.Lib.ScriptLoaderBase.ClassInterface get
Interface that is implemented by the compiled class.
Definition at line 749 of file Loader.cs.
Referenced by IG.Lib.ScriptLoaderBase.GetExampleCode().
ClassName
virtual string IG.Lib.ScriptLoaderBase.ClassName get set
Definition at line 755 of file Loader.cs.
Referenced by IG.Lib.ScriptLoaderBase.CheckAndCorrectNames(), IG.Lib.ScriptLoaderBase.GetExampleCode(), and IG.Lib.ScriptLoaderBase.LoadCode().
ClassFullName
virtual string IG.Lib.ScriptLoaderBase.ClassFullName get
Name of the compiled class that contains loadable script.
Definition at line 778 of file Loader.cs.
Referenced by IG.Lib.ScriptLoaderBase.CheckAndCorrectNames(), IG.Lib.ScriptLoaderBase.Compile(), and IG.Lib.ScriptLoaderBase.CreateLoadableObject().
AppDomainName
virtual string IG.Lib.ScriptLoaderBase.AppDomainName get set
Name of the application domain in which the class is loaded.
Definition at line 784 of file Loader.cs.
Referenced by IG.Lib.ScriptLoaderBase.Compile().
RunFunctionName
virtual string IG.Lib.ScriptLoaderBase.RunFunctionName get protected set
Name of the method of dynamically loadable classes that contains the runnable script.
Definition at line 799 of file Loader.cs.
Referenced by IG.Lib.ScriptLoaderBase.GetExampleCode().
InitFunctionName
virtual string IG.Lib.ScriptLoaderBase.InitFunctionName get protected set
Name of the initialization method of dynamically loadable classes.
Definition at line 814 of file Loader.cs.
Referenced by IG.Lib.ScriptLoaderBase.GetExampleCode().
ArgumentsName
virtual string IG.Lib.ScriptLoaderBase.ArgumentsName get set
Agreed formal name of the arguments parameter. Agreement upon this name makes possible to execute scripts in which run arguments are referenced.
Definition at line 830 of file Loader.cs.
Referenced by IG.Lib.ScriptLoaderBase.GetExampleCode().
LibraryFilename
virtual string IG.Lib.ScriptLoaderBase.LibraryFilename get set
Definition at line 851 of file Loader.cs.
LibraryDirectory
virtual string IG.Lib.ScriptLoaderBase.LibraryDirectory get protected set
Returns directory where library will be compiled, which will be the directory of the executable that started the application.
Definition at line 871 of file Loader.cs.
Referenced by IG.Lib.ScriptLoaderBase.AddReferencedAssemblies().
LibraryPath
virtual string IG.Lib.ScriptLoaderBase.LibraryPath get protected set
Path to the dll where code is compiled. We take the directory where executable is located.
Definition at line 898 of file Loader.cs.
Referenced by IG.Lib.ScriptLoaderBase.Compile(), and IG.Lib.ScriptLoaderBase.CreateNonexistentLibraryPath().
IsCodeLoaded
virtual bool IG.Lib.ScriptLoaderBase.IsCodeLoaded get protected set
Whether scripting code to be compiled is loaded.
Definition at line 930 of file Loader.cs.
IsCompiled
virtual bool IG.Lib.ScriptLoaderBase.IsCompiled get protected set
Whether the code is compiled.
Definition at line 945 of file Loader.cs.
Referenced by IG.Lib.ScriptLoaderBase.Compile(), and IG.Lib.ScriptLoaderBase.CreateLoadableObject().
IsClassLoaded
virtual bool IG.Lib.ScriptLoaderBase.IsClassLoaded get protected set
Whether the compiled class corresponding to the script is prepared.
Definition at line 960 of file Loader.cs.
Referenced by IG.Lib.ScriptLoaderBase.Run().
IsObjectPrepared
virtual bool IG.Lib.ScriptLoaderBase.IsObjectPrepared get protected set
Whether an instance of the object is prepared to be used.
Definition at line 976 of file Loader.cs.
Referenced by IG.Lib.ScriptLoaderBase.Run().
CompilerResults
virtual CompilerResults IG.Lib.ScriptLoaderBase.CompilerResults get protected set
Results of compilation.
Definition at line 1002 of file Loader.cs.
Referenced by IG.Lib.ScriptLoaderBase.Compile().
ReferencedAssemblies
virtual List<String> IG.Lib.ScriptLoaderBase.ReferencedAssemblies get
List of assemblies that are referenced when compiling the code. Contains names of files containing referenced assemblies.
Definition at line 1015 of file Loader.cs.
Referenced by IG.Lib.ScriptLoaderBase.AddReferencedAssemblies(), IG.Lib.ScriptLoaderBase.AddReferencedAssembly(), IG.Lib.ScriptLoaderBase.RemoveAllReferencedAssemblies(), IG.Lib.ScriptLoaderBase.RemoveReferencedAssembly(), and IG.Lib.ScriptLoaderBase.SetReferencedAssemblies().
ReferenceAllLoadedAssemblies
virtual bool IG.Lib.ScriptLoaderBase.ReferenceAllLoadedAssemblies get set
If true then all assemblies that are currently loaded by the application are also added to the referenced assemblies when script code is compiled. This makes sure that all that is necessary is actually referenced.
Definition at line 1023 of file Loader.cs.
Referenced by IG.Lib.ScriptLoaderBase.AddReferencedAssemblies().
ApplicationDomain
virtual AppDomain IG.Lib.ScriptLoaderBase.ApplicationDomain get set protected
Application domain used by the current script loader for loading assemblies.
Definition at line 1385 of file Loader.cs.
Referenced by IG.Lib.ScriptLoaderBase.Compile(), and IG.Lib.ScriptLoaderBase.UnloadApplicationDomain().
Assembly
virtual Assembly IG.Lib.ScriptLoaderBase.Assembly get protected set
Gets or sets the assembly that has been compiled and loaded into the current application domain from the source code.
Setter is protected.
Definition at line 1413 of file Loader.cs.
Referenced by IG.Lib.ScriptLoaderBase.AddReferencedAssemblies(), IG.Lib.ScriptLoaderBase.Compile(), IG.Lib.ScriptLoaderBase.CreateLoadableObject(), and IG.Lib.ScriptLoaderBase.CreateScriptObject().
CreatedObject
virtual ILoadableScript IG.Lib.ScriptLoaderBase.CreatedObject get protected set
Object of the compiled class that has beeen created.
Definition at line 1432 of file Loader.cs.
Referenced by IG.Lib.ScriptLoaderBase.CreateLoadableObject(), and IG.Lib.ScriptLoaderBase.Run().
The documentation for this class was generated from the following file:
iglib/igbase/interpreters/scriptloader/Loader.cs