Doc: IGLib with source files: IGLib.Gr3D.MaterialProperties Class Reference
IGLib.Gr3D.MaterialProperties Class Reference
Public Member Functions
override string ToString ()
Just calls ToStringMtl.
virtual string ToStringMtl (string materialName=null)
Converts material properties to a .mtl file string.
void SaveToMaterialFile (string filePath, string materialName=null)
Saves the material properties to a .mtl file.
Properties
string Name = "DefaultMaterial" [get, set]
Name of the material. This is used to reference the material in an .obj file.
vec3 AmbientColor = new vec3(0.2f, 0.2f, 0.2f) [get, set]
Ambient color (Ka) - Defines how the material reflects ambient light. Typical values range from (0,0,0) (black) to (1,1,1) (white).
vec3 DiffuseColor = new vec3(0.8f, 0.8f, 0.8f) [get, set]
Diffuse color (Kd) - The main color of the material under direct lighting.
vec3 SpecularColor = new vec3(1.0f, 1.0f, 1.0f) [get, set]
Specular color (Ks) - Defines the shininess of the material. A higher value makes the surface appear glossier.
float Shininess = 50.0f [get, set]
Specular exponent (Ns) - Controls the sharpness of specular highlights. Typical values range from 0 (matte) to 1000 (very shiny).
float Transparency = 1.0f [get, set]
Transparency (d) - Ranges from 1.0 (fully opaque) to 0.0 (fully transparent).
vec3 EmissionColor = new vec3(0.0f, 0.0f, 0.0f) [get, set]
Emission color (Ke) - Defines how much the material glows.
string DiffuseTexture = null [get, set]
Texture map file path for the diffuse color (map_Kd). This is an image file (e.g., JPG, PNG).
string BumpMap = null [get, set]
Bump map file path (map_Bump or bump). This is an image file used to simulate surface roughness.
Detailed Description
Definition at line 14 of file MaterialProperties.cs.
Member Function Documentation
ToString()
override string IGLib.Gr3D.MaterialProperties.ToString () inline
Just calls ToStringMtl.
Returns
Definition at line 69 of file MaterialProperties.cs.
References IGLib.Gr3D.MaterialProperties.ToStringMtl().
ToStringMtl()
virtual string IGLib.Gr3D.MaterialProperties.ToStringMtl (string materialName = null) inline virtual
Converts material properties to a .mtl file string.
Parameters
materialName Name of the material when exported to a material file (.mtl). If not specified (null or empty string) then null is taken.
Definition at line 77 of file MaterialProperties.cs.
References IGLib.Gr3D.MaterialProperties.BumpMap, IGLib.Gr3D.MaterialProperties.DiffuseTexture, and IGLib.Gr3D.MaterialProperties.Name.
Referenced by IGLib.Gr3D.MaterialProperties.SaveToMaterialFile(), and IGLib.Gr3D.MaterialProperties.ToString().
SaveToMaterialFile()
void IGLib.Gr3D.MaterialProperties.SaveToMaterialFile (string filePath, string materialName = null) inline
Saves the material properties to a .mtl file.
Definition at line 108 of file MaterialProperties.cs.
References IGLib.Gr3D.MaterialProperties.ToStringMtl().
Referenced by IGLib.Gr3D.MaterialPropertiesExamples.Example_SaveMaterialProperrties(), IGLib.Gr3D.MeshExportExtensions_06.ExportMaterial(), and IGLib.Gr3D.MeshExportExtensions.ExportMaterial().
Property Documentation
Name
string IGLib.Gr3D.MaterialProperties.Name = "DefaultMaterial" get set
Name of the material. This is used to reference the material in an .obj file.
Definition at line 20 of file MaterialProperties.cs.
Referenced by IGLib.Gr3D.MaterialProperties.ToStringMtl().
AmbientColor
vec3 IGLib.Gr3D.MaterialProperties.AmbientColor = new vec3(0.2f, 0.2f, 0.2f) get set
Ambient color (Ka) - Defines how the material reflects ambient light. Typical values range from (0,0,0) (black) to (1,1,1) (white).
Definition at line 26 of file MaterialProperties.cs.
DiffuseColor
vec3 IGLib.Gr3D.MaterialProperties.DiffuseColor = new vec3(0.8f, 0.8f, 0.8f) get set
Diffuse color (Kd) - The main color of the material under direct lighting.
Definition at line 31 of file MaterialProperties.cs.
SpecularColor
vec3 IGLib.Gr3D.MaterialProperties.SpecularColor = new vec3(1.0f, 1.0f, 1.0f) get set
Specular color (Ks) - Defines the shininess of the material. A higher value makes the surface appear glossier.
Definition at line 37 of file MaterialProperties.cs.
Shininess
float IGLib.Gr3D.MaterialProperties.Shininess = 50.0f get set
Specular exponent (Ns) - Controls the sharpness of specular highlights. Typical values range from 0 (matte) to 1000 (very shiny).
Definition at line 43 of file MaterialProperties.cs.
Transparency
float IGLib.Gr3D.MaterialProperties.Transparency = 1.0f get set
Transparency (d) - Ranges from 1.0 (fully opaque) to 0.0 (fully transparent).
Definition at line 48 of file MaterialProperties.cs.
EmissionColor
vec3 IGLib.Gr3D.MaterialProperties.EmissionColor = new vec3(0.0f, 0.0f, 0.0f) get set
Emission color (Ke) - Defines how much the material glows.
Definition at line 53 of file MaterialProperties.cs.
DiffuseTexture
string IGLib.Gr3D.MaterialProperties.DiffuseTexture = null get set
Texture map file path for the diffuse color (map_Kd). This is an image file (e.g., JPG, PNG).
Definition at line 59 of file MaterialProperties.cs.
Referenced by IGLib.Gr3D.MaterialProperties.ToStringMtl().
BumpMap
string IGLib.Gr3D.MaterialProperties.BumpMap = null get set
Bump map file path (map_Bump or bump). This is an image file used to simulate surface roughness.
Definition at line 65 of file MaterialProperties.cs.
Referenced by IGLib.Gr3D.MaterialProperties.ToStringMtl().
The documentation for this class was generated from the following file:
IGLibGraphics3D/src/IGLib.Graphics3D/Graphics3D/Materials/MaterialProperties.cs