Doc: IGLib with source files: IGLib.Core.CollectionExtensions.CollectionExtensions Class Reference
IGLib.Core.CollectionExtensions.CollectionExtensions Class Reference
Various extension methods for collections. In particular, conversion for readable strings, which produce readable outputs in application or assist in testing.
Static Public Member Functions
static string ToJsonString< T > (this T obj, bool indent=false)
Extension method to serialize an object to a JSON string with optional indentation
static string ToReadableString (this object o, string indentation=ArrayIndentation, string openBracket=ArrayBracketOpen, string closedBracket=ArrayBracketClosed, string separator=ArraySeparator)
Converts the specified object o to a readable string.
static string ToReadableString (this string str)
Converts a string to a readable string.
Static Public Attributes
const string ArrayBracketOpen = "{"
Open bracket used in the string representation of array-like objects.
const string ArrayBracketClosed = "}"
Closed bracket used in the string representation of array-like objects.
const string ArraySeparator = ","
Array element separator used in the string representation of array-like objects.
const string ArrayIndentation = DefaultIndentationString
Default indentation used in the string representation of array-like objects. Corresponds to DefaultIndentationString.
const string NullString = "null"
String that is used to output null objects.
const string DefaultIndentationString = " "
Defines the default indentation string used in string representations of structured data that extends over multiple lines.
Static Private Member Functions
static string CastAndCallToReadableString (Array array, string indentation=ArrayIndentation, string openBracket=ArrayBracketOpen, string closedBracket=ArrayBracketClosed, string separator=ArraySeparator)
static string HandleJaggedArray (Array jaggedArray, int indentLevel=0, string indentation=ArrayIndentation, string openBracket=ArrayBracketOpen, string closedBracket=ArrayBracketClosed, string separator=ArraySeparator)
A helper method to handle jagged arrays dynamically.
Detailed Description
Various extension methods for collections. In particular, conversion for readable strings, which produce readable outputs in application or assist in testing.
ToReadableString (ToReadableString(object, string, string, string, string) and similar):
\
Conversions of various array-like objects to readable strings. Various types of collections have their own overloads, which are statically dispatched (e.g. IList<T>, IEnumerable<T>, T[], rectangular arrays T[,], T[,,], jagged arrays T[][], T[][][]).
There is also the method that detects the type of array-like objects dynamically, ToReadableString(object, string, string, string, string), and produces, according to the actual type of the argument, a similar output for array-like type of objects than the corresponding statically typed counterparts.
The ToreadableString(...) type of methods are meant to be used as static extension methods, but certain formatting aspects are parameterized by static properties ArrayBracketOpen, ArrayBracketClosed, ArraySeparator and ArrayIndentation. Each of these methods has a set of optional parameters where these formatting parameters can be customized at will, and the mentioned properties represent default values for these parameters. This increases reusibility, and if necessary, the equivalent instance classes whose instances are injectable could easily be created from the current class.
Definition at line 35 of file CollectionExtensions.cs.
Member Function Documentation
ToJsonString< T >()
static string IGLib.Core.CollectionExtensions.CollectionExtensions.ToJsonString< T > (this T obj, bool indent = false) inline static
Extension method to serialize an object to a JSON string with optional indentation
Template Parameters
T Type of the object. ost of the time, type parameters can be inferred and does not need to be stated when calling this method. Even if the declared type of obj is object, the conversion to JSON should be take into account its actual type and should be correct.
Parameters
obj The object to be serialized to a JSON string that is returned.
indent If true then the returned JSON string is indented. If not, the JSON string is as short as possible, without the unnecessary whitespace. Default is false.
Returns
The JSON-serialized string corresponding to obj . The string will not contain private objects.
Definition at line 71 of file CollectionExtensions.cs.
ToReadableString() [1/2]
static string IGLib.Core.CollectionExtensions.CollectionExtensions.ToReadableString (this object o, string indentation = ArrayIndentation, string openBracket = ArrayBracketOpen, string closedBracket = ArrayBracketClosed, string separator = ArraySeparator) inline static
Converts the specified object o to a readable string.
This method dynamically checks the actual type of o . If the object is an array, 2 or 3 dimensional rectangular array, 2 or 3 dimensional ljagged array, a list (it implements the IList interface) or enumerable (it implements the IEnumerable interface, then the appropriate method is called to produce the string representation suitable for array-like objects.
Parameters
o Object to be converted to a readable string.
Returns
Ths string containing a representation of the o , indentation String used for single indentation; default is ArrayIndentation openBracket String used as open bracket in array representation; default is ArrayBracketOpen closedBracket String used as closed bracket in array representation; default is ArrayBracketClosed separator String used as separator in array representation; default is ArraySeparator which is also nicely structured and readable for objects of array-like types.
Definition at line 97 of file CollectionExtensions.cs.
References IGLib.Core.CollectionExtensions.CollectionExtensions.CastAndCallToReadableString(), IGLib.Core.CollectionExtensions.CollectionExtensions.HandleJaggedArray(), and IGLib.Core.CollectionExtensions.CollectionExtensions.NullString.
CastAndCallToReadableString()
static string IGLib.Core.CollectionExtensions.CollectionExtensions.CastAndCallToReadableString (Array array, string indentation = ArrayIndentation, string openBracket = ArrayBracketOpen, string closedBracket = ArrayBracketClosed, string separator = ArraySeparator) inline static private
Definition at line 159 of file CollectionExtensions.cs.
References IGLib.Core.CollectionExtensions.CollectionExtensions.NullString.
Referenced by IGLib.Core.CollectionExtensions.CollectionExtensions.ToReadableString().
HandleJaggedArray()
static string IGLib.Core.CollectionExtensions.CollectionExtensions.HandleJaggedArray (Array jaggedArray, int indentLevel = 0, string indentation = ArrayIndentation, string openBracket = ArrayBracketOpen, string closedBracket = ArrayBracketClosed, string separator = ArraySeparator) inline static private
A helper method to handle jagged arrays dynamically.
Parameters
jaggedArray The jagged array whose string representation should be returned.
Returns
String representation of the specified jagged array.
Definition at line 190 of file CollectionExtensions.cs.
References IGLib.Core.CollectionExtensions.CollectionExtensions.NullString.
Referenced by IGLib.Core.CollectionExtensions.CollectionExtensions.ToReadableString().
ToReadableString() [2/2]
static string IGLib.Core.CollectionExtensions.CollectionExtensions.ToReadableString (this string str) inline static
Converts a string to a readable string.
The returned string is in double quotes, and all double quotes (but not other characters) within the string are scaped with backslash.
Parameters
array String to be converted.
Definition at line 237 of file CollectionExtensions.cs.
References IGLib.Core.CollectionExtensions.CollectionExtensions.NullString.
Member Data Documentation
ArrayBracketOpen
const string IGLib.Core.CollectionExtensions.CollectionExtensions.ArrayBracketOpen = "{" static
Open bracket used in the string representation of array-like objects.
Definition at line 39 of file CollectionExtensions.cs.
ArrayBracketClosed
const string IGLib.Core.CollectionExtensions.CollectionExtensions.ArrayBracketClosed = "}" static
Closed bracket used in the string representation of array-like objects.
Definition at line 42 of file CollectionExtensions.cs.
ArraySeparator
const string IGLib.Core.CollectionExtensions.CollectionExtensions.ArraySeparator = "," static
Array element separator used in the string representation of array-like objects.
Definition at line 45 of file CollectionExtensions.cs.
ArrayIndentation
const string IGLib.Core.CollectionExtensions.CollectionExtensions.ArrayIndentation = DefaultIndentationString static
Default indentation used in the string representation of array-like objects. Corresponds to DefaultIndentationString.
Definition at line 49 of file CollectionExtensions.cs.
NullString
const string IGLib.Core.CollectionExtensions.CollectionExtensions.NullString = "null" static
String that is used to output null objects.
Definition at line 52 of file CollectionExtensions.cs.
Referenced by IGLib.Core.CollectionExtensions.CollectionExtensions.CastAndCallToReadableString(), IGLib.Core.CollectionExtensions.CollectionExtensions.HandleJaggedArray(), and IGLib.Core.CollectionExtensions.CollectionExtensions.ToReadableString().
DefaultIndentationString
const string IGLib.Core.CollectionExtensions.CollectionExtensions.DefaultIndentationString = " " static
Defines the default indentation string used in string representations of structured data that extends over multiple lines.
Definition at line 56 of file CollectionExtensions.cs.
The documentation for this class was generated from the following file:
IGLibGraphics3D/src/IGLib.Graphics3D/other/TypeConversion/CollectionExtensions.cs