Doc: IGLib with source files: LearnCs.Lib.Complex Struct Reference
LearnCs.Lib.Complex Struct Reference
Represents a complex number (https://en.wikipedia.org/wiki/Complex_number).
Public Member Functions
Complex (double realPart, double imaginaryPart)
Creates a complex number from the specified real and imaginary part.
Complex (double realNumber)
Creates a complex number from a real number. Real numbers are subset of complex numbers that don't have imaginary part.
Complex ((double, double) complexTuple)
Creates a complex number from a 2-value tuple of doubles. The first value represents the real and the second value represents the imaginary part.
bool IsApproximatelyReal (double tolerance=0.0)
Returns true if the current complex number is approximately a real number (i.e., its imaginary part is less or equal to the specified tolerance).
bool IsApproximatelyInteger (double tolerance=0.0)
Returns true if the current complex number is approximately an integer (within tolerance) and can be approximately converted to long.
bool IsApproximatelyInt (double tolerance=0.0)
Similar to IsApproximatelyInteger(double), except that the real part Re must also be within the range of the type int.
double ToReal (double tolerance=0.0)
double ToDouble (double tolerance=0.0)
long ToInteger (double tolerance=0.0)
long ToLong (double tolerance=0.0)
long ToInt (double tolerance=0.0)
Complex Add (Complex c)
Ads c to the current complex number and returns the result.
Complex Subtract (Complex c)
Subtracts c from the curret complex number and returns the result.
Complex Multiply (Complex c)
Multiplies the current complex number by c and returns the result.
Complex Divide (Complex c)
Divides the current complex number by c and returns the result.
Complex GetPositive ()
Returns (positive) value of the current complex number.
Complex GetNegative ()
Returns negative value of the current complex number.
Complex GetConjugate ()
Returns negative value of the current complex number.
Complex AreEqual ()
Returns boolean value, true or false, from comparison equality between two complex numbers.
Complex AreNotEqual ()
Returns boolean value, true or false, from comparison inequality between two complex numbers.
Complex Exp ()
Complex Ln ()
Complex Pow (int power)
Complex Pow (int n, int rootIndex)
Complex Pow (Complex z)
Complex Sin ()
Complex Cos ()
Complex Tan ()
Complex Cot ()
Complex Atan ()
Complex Sinh ()
Complex Cosh ()
Complex Tanh ()
Complex Coth ()
override bool Equals (object obj)
Overrides object.equals method. Returns true if obj is also Complex and it has the same value, otherwise it returns false.
override int GetHashCode ()
Override of object.GetHashCode() suitable for complex numbers;
override string ToString ()
string ToStringShort ()
Returns a short form string representation of a complex number.
Static Public Member Functions
static Complex FromPolarCoordinates (double r, double phi)
Returns a complex number initialized by polar coordinates.
static implicit operator Complex (double d)
Implicit conversion from double to complex.
static implicit operator Complex ((double, double) doubleTuple)
Implicit conversion from a tuple of two numbers of type double to a complex number.
static operator Complex (double[] components)
Explicit conversion of double[] to a complex number. Used in particular in parameterized test methods that have collections of complex numbers as parameters.
static operator double (Complex c)
Explicit conversoin from complex to double. Will need cast operator.
static operator (double, double)(Complex c)
Explicit conversion from complex to (double, double). Will need a cast operator.
static operator double[] (Complex c)
Explicit conversion from complex to double[]. Will need a cast operator.
static Complex Add (Complex c1, Complex c2)
Ads two complex numbers and returns the result.
static Complex Subtract (Complex c1, Complex c2)
Subtracts c2 from c1 and returns the result.
static Complex Multiply (Complex c1, Complex c2)
Multiplies c1 by c2 and returns the result.
static Complex Divide (Complex c1, Complex c2)
Divides c1 by c2 and returns the result.
static Complex GetPositive (Complex c)
Returns positive value of c .
static Complex GetNegative (Complex c)
Returns negative value of c .
static Complex GetConjugate (Complex c)
Returns complex conjugate of c .
static bool AreNotEqual (Complex a, Complex b)
static Complex operator+ (Complex c1, Complex c2)
Defines the binary operator + for summation of two complex numbers.
static Complex operator- (Complex c1, Complex c2)
Defines the binary operator - for subtraction of two complex numbers.
static Complex operator* (Complex c1, Complex c2)
Complex multiplication.
static Complex operator/ (Complex c1, Complex c2)
Complex division (quotient of thow complex numbers).
static Complex operator+ (Complex a)
Defines the unary + operator (just returns the same complex number).
static Complex operator- (Complex a)
Defines the unary - operator for changing sign of a complex number.
static bool operator== (Complex a, Complex b)
Complex comparison.
static bool operator!= (Complex a, Complex b)
Complex comparison.
static Complex Exp (Complex x)
returns exponential function (where exponent is the Euler's number, base of natural logarithm). Defined for all complex numbers.
static Complex Ln (Complex x)
Returns natural (base e) logarithm of the complex number x .
static Complex Log (Complex x)
Returns logarithm base 10 of the complex number x .
static Complex Log2 (Complex x)
Returns logarithm base 2 of the complex number x .
static Complex Pow (Complex x, int power)
static Complex Pow (Complex x, int power, int rootIndex)
static Complex Pow (Complex x, Complex power)
static Complex Root (Complex x, int n)
Returns the root with index n of a complex number x .
static Complex Sqrt (Complex x)
Returns square root of x .
static Complex CubicRoot (Complex x)
Returns cubic root of x .
static Complex Sin (Complex x)
static Complex Cos (Complex x)
static Complex Tan (Complex x)
static Complex Cot (Complex x)
static Complex Sinh (Complex x)
static Complex Cosh (Complex x)
static Complex Tanh (Complex x)
static Complex Coth (Complex x)
static bool TryParse (string s, out Complex result)
Parses complex number from its string representation.
static Complex ParseRobust (string s)
Parses complex number from its string representation.
static bool TryParseRobust (string s, out Complex result)
Parses a complex number (of type Complex) from the string s , stores the result in result , and returns true if parsing was successful and false if not. This metthod calls ParseRobust(string) to do the job, therefore parsing is the same, just that this method does not throw an exception if parsing does not succeed, but rather returns a value indicating success or failure. See documentation for ParseRobust(string) for formats that can be parsed.
static Complex Parse (string s)
Parses complex number from its string representation and returns it. Exception is thrown if the value cannot be parsed from the string.
Public Attributes
double AbsoluteValue
Gets absolute value (or magnitude) of the current complex number.
double R => Math.Sqrt(Re * Re + Im * Im)
Gets the modulus (or magnitude, or absolute value) of the current complex number. This is the radius of the polar form of a complex number.
double Phi => (Math.Atan2(Im, Re))
Gets the argument of the current complex number. This is the angle parameter of the polar coordinates of a complex number.
double Magnitude => R
Alias for the property R.
double Modulus => R
Alias of the property R.
double Argument => Phi
Alias for the property Phi. Avoid using this alias.
double Fi => Phi
Please do not use, this property might be deprecated in the future.
Complex Negative => new Complex(-Re, -Im)
Gets the negative value of the current complex number.
Complex Conjugate => new Complex(Re, -Im)
Gets the complex conjugate of the current complex number.
bool IsReal => Im == 0
True if the current complex number is a real number (i.e., it can be converted to double, i.e., its imaginary part is 0). False otherwise.
bool IsInteger
True if the current complex number is an integer number (it can be converted to long, i.e., its imaginary part is 0, its real par does not have the decimal part but only the integer part, and it is within the range of long).
bool IsInt
True if the current complex number is an integer number that fits into int (it can be converted to int, i.e., its imaginary part is 0, its real par does not have the decimal part but only the integer part, and it is within the range of int).
Static Public Attributes
const double ConstZero = 0
Double constant 0.0.
const double ConstOne = 1
Double constant 1.0.
const double ConstPI = Math.PI
Double constant Pi, the ratio of circumference and diameter of the circle (the same as Math.PI).
const double ConstE = Math.E
Double constant E, the basis of natural logarithm (the same as Math.E).
Properties
double Re [get, set]
Gets the real part of the complex number.
double Im [get, set]
Gets the imaginary part of the current complex number.
static Complex Zero = (0, 0) [get]
Gets the complex 0 (a constant).
static Complex One = (1.0, 0) [get]
Gets the complex 1 (a constant).
static Complex PI = (Math.PI, 0) [get]
Gets the real-valued constant Pi (= Math.PI), the ratio of circumference and diameter of a circle, as complex number.
static Complex E = (Math.E, 0) [get]
Gets the real-valued constant E (= Math.E), the basis of natural logarithm, as complex number.
static Complex I = new Complex(0, 1) [get]
Gets the imaginary unit i.
Private Member Functions
int Get_HashCode1 ()
A candidate for object.GetHashCode() override. See also:
int Get_HashCode2 ()
A candidate for object.GetHashCode() override.
int Get_HashCode3 ()
A candidate for object.GetHashCode() override.
int Get_HashCode5 ()
A candidate for object.GetHashCode() override. Leverages framework's implementation for tuples.
Private Attributes
double _re
Underlying field for the property Re
double _im
Underlying field for the property Im
Detailed Description
Represents a complex number (https://en.wikipedia.org/wiki/Complex_number).
Definition at line 20 of file Complex.cs.
Constructor & Destructor Documentation
Complex() [1/3]
LearnCs.Lib.Complex.Complex (double realPart, double imaginaryPart) inline
Creates a complex number from the specified real and imaginary part.
Parameters
realPart Real part of the complex number.
imaginaryPart Imaginary part of the complex number.
Definition at line 28 of file Complex.cs.
References LearnCs.Lib.Complex.Im, and LearnCs.Lib.Complex.Re.
Referenced by LearnCs.Lib.Complex.Add(), LearnCs.Lib.Complex.Cos(), LearnCs.Lib.Complex.Divide(), LearnCs.Lib.Complex.Equals(), LearnCs.Lib.Complex.Exp(), LearnCs.Lib.Complex.FromPolarCoordinates(), LearnCs.Lib.Complex.GetConjugate(), LearnCs.Lib.Complex.GetNegative(), LearnCs.Lib.Complex.Ln(), LearnCs.Lib.Complex.Multiply(), LearnCs.Lib.Complex.operator Complex(), LearnCs.Lib.Complex.operator*(), LearnCs.Lib.Complex.operator+(), LearnCs.Lib.Complex.operator-(), LearnCs.Lib.Complex.operator/(), LearnCs.Lib.Complex.ParseRobust(), LearnCs.Lib.Complex.Sin(), LearnCs.Lib.Complex.Subtract(), and LearnCs.Lib.Complex.TryParse().
Complex() [2/3]
LearnCs.Lib.Complex.Complex (double realNumber) inline
Creates a complex number from a real number. Real numbers are subset of complex numbers that don't have imaginary part.
Parameters
realNumber The real number from which the current complex number is constructed.
Definition at line 47 of file Complex.cs.
References LearnCs.Lib.Complex.Im, and LearnCs.Lib.Complex.Re.
Complex() [3/3]
LearnCs.Lib.Complex.Complex ((double, double) complexTuple) inline
Creates a complex number from a 2-value tuple of doubles. The first value represents the real and the second value represents the imaginary part.
Parameters
complexTuple
Definition at line 56 of file Complex.cs.
References LearnCs.Lib.Complex.Im, and LearnCs.Lib.Complex.Re.
Member Function Documentation
FromPolarCoordinates()
static Complex LearnCs.Lib.Complex.FromPolarCoordinates (double r, double phi) inline static
Returns a complex number initialized by polar coordinates.
Parameters
r The absolute number of the complex number, or its radius in polar coordinates.
phi The argument (or angle) of the complex number in polar coordinates.
Definition at line 65 of file Complex.cs.
References LearnCs.Lib.Complex.Complex().
Referenced by LearnCs.Lib.Complex.Pow(), LearnCs.Lib.Complex.Root(), and LearnCs.Lib.Complex.Sqrt().
operator Complex() [1/3]
static implicit LearnCs.Lib.Complex.operator Complex (double d) inline static
Implicit conversion from double to complex.
Parameters
d Number of type double that is converted to complex.
Definition at line 78 of file Complex.cs.
References LearnCs.Lib.Complex.Complex().
operator Complex() [2/3]
static implicit LearnCs.Lib.Complex.operator Complex ((double, double) doubleTuple) inline static
Implicit conversion from a tuple of two numbers of type double to a complex number.
Parameters
doubleTuple Tuple of two double numbers that is converted to complex.
Definition at line 85 of file Complex.cs.
References LearnCs.Lib.Complex.Complex().
operator Complex() [3/3]
static LearnCs.Lib.Complex.operator Complex (double[] components) inline explicit static
Explicit conversion of double[] to a complex number. Used in particular in parameterized test methods that have collections of complex numbers as parameters.
Parameters
components
Definition at line 93 of file Complex.cs.
References LearnCs.Lib.Complex.Complex().
operator double()
static LearnCs.Lib.Complex.operator double (Complex c) inline explicit static
Explicit conversoin from complex to double. Will need cast operator.
Conversion cannot be done in all cases (i.e., when imaginary part is nonzero, complex number can not be represented by double)
Parameters
c Complex number that is converted to type double.
Exceptions
InvalidOperationException When imaginary part is different than zero.
Definition at line 120 of file Complex.cs.
References LearnCs.Lib.Complex.Im, and LearnCs.Lib.Complex.Re.
operator()
static LearnCs.Lib.Complex.operator (double , double) inline explicit static
Explicit conversion from complex to (double, double). Will need a cast operator.
The first item of the tuple becomes the real part and the second item becomes the imaginary part of c .
Parameters
c Complex number that is converted to a (double, double) tuple.
Definition at line 133 of file Complex.cs.
operator double[]()
static LearnCs.Lib.Complex.operator double[] (Complex c) inline explicit static
Explicit conversion from complex to double[]. Will need a cast operator.
Element 0 of the array becomes the real part and the element 1 becomes the imaginary part of c .
Parameters
c Complex number that is converted to array of type double.
Definition at line 142 of file Complex.cs.
IsApproximatelyReal()
bool LearnCs.Lib.Complex.IsApproximatelyReal (double tolerance = 0.0) inline
Returns true if the current complex number is approximately a real number (i.e., its imaginary part is less or equal to the specified tolerance).
Parameters
tolerance Tolerance, must be less than 0.05. The number is regarded approximately a real number if the absolute the absolute value of its imaginary part is less or equal to tolerance.
Returns
True if the current complex number is approximately a real number (meaning that its imaginary part is negligible), within tolerance .
Exceptions
ArgumentException When the specified tolerance is negative or it is not less than 0.05.
Definition at line 273 of file Complex.cs.
References LearnCs.Lib.Complex.Im.
Referenced by LearnCs.Lib.Complex.ToReal().
IsApproximatelyInteger()
bool LearnCs.Lib.Complex.IsApproximatelyInteger (double tolerance = 0.0) inline
Returns true if the current complex number is approximately an integer (within tolerance) and can be approximately converted to long.
Parameters
tolerance Tolerance, must be less than 0.05. The number is regarded approximately an integer if the absolute difference between its real part Re and the nearest integer is less than tolerance, and if the absolute value of the imaginary part is less than tolerance.
Returns
True if the current complex number is approximately an integer, within tolerance .
Exceptions
ArgumentException When the specified tolerance is negative or it is not less than 0.05.
Definition at line 292 of file Complex.cs.
References LearnCs.Lib.Complex.Im, and LearnCs.Lib.Complex.Re.
Referenced by LearnCs.Lib.Complex.ToInteger().
IsApproximatelyInt()
bool LearnCs.Lib.Complex.IsApproximatelyInt (double tolerance = 0.0) inline
Similar to IsApproximatelyInteger(double), except that the real part Re must also be within the range of the type int.
Parameters
tolerance
Returns
Exceptions
ArgumentException
Definition at line 311 of file Complex.cs.
References LearnCs.Lib.Complex.Im, and LearnCs.Lib.Complex.Re.
Referenced by LearnCs.Lib.Complex.ToInt().
ToReal()
double LearnCs.Lib.Complex.ToReal (double tolerance = 0.0) inline
Definition at line 326 of file Complex.cs.
References LearnCs.Lib.Complex.IsApproximatelyReal(), and LearnCs.Lib.Complex.Re.
ToDouble()
double LearnCs.Lib.Complex.ToDouble (double tolerance = 0.0)
ToInteger()
long LearnCs.Lib.Complex.ToInteger (double tolerance = 0.0) inline
Definition at line 339 of file Complex.cs.
References LearnCs.Lib.Complex.IsApproximatelyInteger(), and LearnCs.Lib.Complex.Re.
ToLong()
long LearnCs.Lib.Complex.ToLong (double tolerance = 0.0)
ToInt()
long LearnCs.Lib.Complex.ToInt (double tolerance = 0.0) inline
Definition at line 352 of file Complex.cs.
References LearnCs.Lib.Complex.IsApproximatelyInt(), and LearnCs.Lib.Complex.Re.
Add() [1/2]
static Complex LearnCs.Lib.Complex.Add (Complex c1, Complex c2) inline static
Ads two complex numbers and returns the result.
Definition at line 410 of file Complex.cs.
References LearnCs.Lib.Complex.Complex(), LearnCs.Lib.Complex.Im, and LearnCs.Lib.Complex.Re.
Referenced by LearnCs.Lib.Complex.Add().
Subtract() [1/2]
static Complex LearnCs.Lib.Complex.Subtract (Complex c1, Complex c2) inline static
Subtracts c2 from c1 and returns the result.
Definition at line 416 of file Complex.cs.
References LearnCs.Lib.Complex.Complex(), LearnCs.Lib.Complex.Im, and LearnCs.Lib.Complex.Re.
Referenced by LearnCs.Lib.Complex.Subtract().
Multiply() [1/2]
static Complex LearnCs.Lib.Complex.Multiply (Complex c1, Complex c2) inline static
Multiplies c1 by c2 and returns the result.
Definition at line 422 of file Complex.cs.
References LearnCs.Lib.Complex.Complex(), LearnCs.Lib.Complex.Im, and LearnCs.Lib.Complex.Re.
Referenced by LearnCs.Lib.Complex.Multiply().
Divide() [1/2]
static Complex LearnCs.Lib.Complex.Divide (Complex c1, Complex c2) inline static
Divides c1 by c2 and returns the result.
!!
Definition at line 431 of file Complex.cs.
References LearnCs.Lib.Complex.Complex(), LearnCs.Lib.Complex.Im, and LearnCs.Lib.Complex.Re.
Referenced by LearnCs.Lib.Complex.Divide().
GetPositive() [1/2]
static Complex LearnCs.Lib.Complex.GetPositive (Complex c) inline static
Returns positive value of c .
Definition at line 440 of file Complex.cs.
GetNegative() [1/2]
static Complex LearnCs.Lib.Complex.GetNegative (Complex c) inline static
Returns negative value of c .
Definition at line 446 of file Complex.cs.
References LearnCs.Lib.Complex.Complex(), LearnCs.Lib.Complex.Im, and LearnCs.Lib.Complex.Re.
GetConjugate() [1/2]
static Complex LearnCs.Lib.Complex.GetConjugate (Complex c) inline static
Returns complex conjugate of c .
Definition at line 452 of file Complex.cs.
References LearnCs.Lib.Complex.Complex(), LearnCs.Lib.Complex.Im, and LearnCs.Lib.Complex.Re.
AreNotEqual() [1/2]
static bool LearnCs.Lib.Complex.AreNotEqual (Complex a, Complex b) inline static
Definition at line 464 of file Complex.cs.
References LearnCs.Lib.Complex.Im, and LearnCs.Lib.Complex.Re.
Add() [2/2]
Complex LearnCs.Lib.Complex.Add (Complex c) inline
Ads c to the current complex number and returns the result.
Definition at line 475 of file Complex.cs.
References LearnCs.Lib.Complex.Add().
Subtract() [2/2]
Complex LearnCs.Lib.Complex.Subtract (Complex c) inline
Subtracts c from the curret complex number and returns the result.
Definition at line 482 of file Complex.cs.
References LearnCs.Lib.Complex.Subtract().
Multiply() [2/2]
Complex LearnCs.Lib.Complex.Multiply (Complex c) inline
Multiplies the current complex number by c and returns the result.
Definition at line 489 of file Complex.cs.
References LearnCs.Lib.Complex.Multiply().
Divide() [2/2]
Complex LearnCs.Lib.Complex.Divide (Complex c) inline
Divides the current complex number by c and returns the result.
Definition at line 495 of file Complex.cs.
References LearnCs.Lib.Complex.Divide().
GetPositive() [2/2]
Complex LearnCs.Lib.Complex.GetPositive () inline
Returns (positive) value of the current complex number.
Definition at line 501 of file Complex.cs.
GetNegative() [2/2]
Complex LearnCs.Lib.Complex.GetNegative () inline
Returns negative value of the current complex number.
Definition at line 507 of file Complex.cs.
GetConjugate() [2/2]
Complex LearnCs.Lib.Complex.GetConjugate () inline
Returns negative value of the current complex number.
Definition at line 513 of file Complex.cs.
AreEqual()
Complex LearnCs.Lib.Complex.AreEqual () inline
Returns boolean value, true or false, from comparison equality between two complex numbers.
// !!!
Definition at line 520 of file Complex.cs.
AreNotEqual() [2/2]
Complex LearnCs.Lib.Complex.AreNotEqual () inline
Returns boolean value, true or false, from comparison inequality between two complex numbers.
//!!!
Definition at line 527 of file Complex.cs.
operator+() [1/2]
static Complex LearnCs.Lib.Complex.operator+ (Complex c1, Complex c2) inline static
Defines the binary operator + for summation of two complex numbers.
Definition at line 539 of file Complex.cs.
References LearnCs.Lib.Complex.Complex(), LearnCs.Lib.Complex.Im, and LearnCs.Lib.Complex.Re.
operator-() [1/2]
static Complex LearnCs.Lib.Complex.operator- (Complex c1, Complex c2) inline static
Defines the binary operator - for subtraction of two complex numbers.
Definition at line 549 of file Complex.cs.
References LearnCs.Lib.Complex.Complex(), LearnCs.Lib.Complex.Im, and LearnCs.Lib.Complex.Re.
operator*()
static Complex LearnCs.Lib.Complex.operator* (Complex c1, Complex c2) inline static
Complex multiplication.
Definition at line 558 of file Complex.cs.
References LearnCs.Lib.Complex.Complex(), LearnCs.Lib.Complex.Im, and LearnCs.Lib.Complex.Re.
operator/()
static Complex LearnCs.Lib.Complex.operator/ (Complex c1, Complex c2) inline static
Complex division (quotient of thow complex numbers).
Definition at line 565 of file Complex.cs.
References LearnCs.Lib.Complex.Complex(), LearnCs.Lib.Complex.Im, and LearnCs.Lib.Complex.Re.
operator+() [2/2]
static Complex LearnCs.Lib.Complex.operator+ (Complex a) inline static
Defines the unary + operator (just returns the same complex number).
Definition at line 573 of file Complex.cs.
References LearnCs.Lib.Complex.Complex(), LearnCs.Lib.Complex.Im, and LearnCs.Lib.Complex.Re.
operator-() [2/2]
static Complex LearnCs.Lib.Complex.operator- (Complex a) inline static
Defines the unary - operator for changing sign of a complex number.
Definition at line 579 of file Complex.cs.
References LearnCs.Lib.Complex.Complex(), LearnCs.Lib.Complex.Im, and LearnCs.Lib.Complex.Re.
operator==()
static bool LearnCs.Lib.Complex.operator== (Complex a, Complex b) inline static
Complex comparison.
Definition at line 585 of file Complex.cs.
References LearnCs.Lib.Complex.Im, and LearnCs.Lib.Complex.Re.
operator!=()
static bool LearnCs.Lib.Complex.operator!= (Complex a, Complex b) inline static
Complex comparison.
Definition at line 591 of file Complex.cs.
References LearnCs.Lib.Complex.Im, and LearnCs.Lib.Complex.Re.
Exp() [1/2]
static Complex LearnCs.Lib.Complex.Exp (Complex x) inline static
returns exponential function (where exponent is the Euler's number, base of natural logarithm). Defined for all complex numbers.
Definition at line 603 of file Complex.cs.
References LearnCs.Lib.Complex.Complex(), LearnCs.Lib.Complex.Exp(), LearnCs.Lib.Complex.Im, and LearnCs.Lib.Complex.Re.
Referenced by LearnCs.Lib.Complex.Exp().
Ln() [1/2]
static Complex LearnCs.Lib.Complex.Ln (Complex x) inline static
Returns natural (base e) logarithm of the complex number x .
Natural logarithm is a multivalued function. Principal branch is taken here.
Definition at line 611 of file Complex.cs.
References LearnCs.Lib.Complex.AbsoluteValue, LearnCs.Lib.Complex.Argument, and LearnCs.Lib.Complex.Complex().
Referenced by LearnCs.Lib.Complex.Ln().
Log()
static Complex LearnCs.Lib.Complex.Log (Complex x) inline static
Returns logarithm base 10 of the complex number x .
Note: logarithm is a multivalued function. Principal branch is taken here.
Definition at line 619 of file Complex.cs.
References LearnCs.Lib.Complex.Ln().
Log2()
static Complex LearnCs.Lib.Complex.Log2 (Complex x) inline static
Returns logarithm base 2 of the complex number x .
Note: logarithm is a multivalued function. Principal branch is taken here.
Definition at line 628 of file Complex.cs.
References LearnCs.Lib.Complex.Ln().
Pow() [1/6]
static Complex LearnCs.Lib.Complex.Pow (Complex x, int power) inline static
Definition at line 634 of file Complex.cs.
References LearnCs.Lib.Complex.FromPolarCoordinates(), LearnCs.Lib.Complex.Phi, LearnCs.Lib.Complex.Pow(), and LearnCs.Lib.Complex.R.
Referenced by LearnCs.Lib.NumberOperationsComplex.Pow(), LearnCs.Lib.Complex.Pow(), LearnCs.Lib.NumberOperationsComplex.Root(), and LearnCs.Lib.NumberOperationsComplex.Sqrt().
Pow() [2/6]
static Complex LearnCs.Lib.Complex.Pow (Complex x, int power, int rootIndex) inline static
Definition at line 641 of file Complex.cs.
References LearnCs.Lib.Complex.FromPolarCoordinates(), LearnCs.Lib.Complex.Phi, LearnCs.Lib.Complex.Pow(), and LearnCs.Lib.Complex.R.
Pow() [3/6]
static Complex LearnCs.Lib.Complex.Pow (Complex x, Complex power) inline static
Definition at line 647 of file Complex.cs.
References LearnCs.Lib.Complex.Exp(), and LearnCs.Lib.Complex.Ln().
Root()
static Complex LearnCs.Lib.Complex.Root (Complex x, int n) inline static
Returns the root with index n of a complex number x .
Parameters
x Complex number whose n-th root is returned.
n Root index (e.g. 2 for square root, 3 for cubic root, etc.).
Returns
Definition at line 656 of file Complex.cs.
References LearnCs.Lib.Complex.FromPolarCoordinates(), LearnCs.Lib.Complex.Phi, and LearnCs.Lib.Complex.R.
Referenced by LearnCs.Lib.Complex.CubicRoot().
Sqrt()
static Complex LearnCs.Lib.Complex.Sqrt (Complex x) inline static
Returns square root of x .
Definition at line 662 of file Complex.cs.
References LearnCs.Lib.Complex.FromPolarCoordinates(), LearnCs.Lib.Complex.Phi, and LearnCs.Lib.Complex.R.
CubicRoot()
static Complex LearnCs.Lib.Complex.CubicRoot (Complex x) inline static
Returns cubic root of x .
Definition at line 669 of file Complex.cs.
References LearnCs.Lib.Complex.Root().
Sin() [1/2]
static Complex LearnCs.Lib.Complex.Sin (Complex x) inline static
Definition at line 674 of file Complex.cs.
References LearnCs.Lib.Complex.Complex(), LearnCs.Lib.Complex.Im, and LearnCs.Lib.Complex.Re.
Referenced by LearnCs.Lib.Complex.Sin().
Cos() [1/2]
static Complex LearnCs.Lib.Complex.Cos (Complex x) inline static
Definition at line 682 of file Complex.cs.
References LearnCs.Lib.Complex.Complex(), LearnCs.Lib.Complex.Im, and LearnCs.Lib.Complex.Re.
Tan() [1/2]
static Complex LearnCs.Lib.Complex.Tan (Complex x) inline static
Definition at line 690 of file Complex.cs.
References LearnCs.Lib.Complex.Cos(), and LearnCs.Lib.Complex.Sin().
Cot() [1/2]
static Complex LearnCs.Lib.Complex.Cot (Complex x) inline static
Definition at line 695 of file Complex.cs.
References LearnCs.Lib.Complex.Cos(), and LearnCs.Lib.Complex.Sin().
Sinh() [1/2]
static Complex LearnCs.Lib.Complex.Sinh (Complex x) inline static
Definition at line 700 of file Complex.cs.
References LearnCs.Lib.Complex.Exp().
Cosh() [1/2]
static Complex LearnCs.Lib.Complex.Cosh (Complex x) inline static
Definition at line 705 of file Complex.cs.
References LearnCs.Lib.Complex.Exp().
Tanh() [1/2]
static Complex LearnCs.Lib.Complex.Tanh (Complex x) inline static
Definition at line 710 of file Complex.cs.
References LearnCs.Lib.Complex.Cosh(), and LearnCs.Lib.Complex.Sinh().
Coth() [1/2]
static Complex LearnCs.Lib.Complex.Coth (Complex x) inline static
Definition at line 715 of file Complex.cs.
References LearnCs.Lib.Complex.Cosh(), and LearnCs.Lib.Complex.Sinh().
Exp() [2/2]
Complex LearnCs.Lib.Complex.Exp () inline
Definition at line 727 of file Complex.cs.
References LearnCs.Lib.Complex.Exp().
Referenced by LearnCs.Lib.Complex.Cosh(), LearnCs.Lib.Complex.Pow(), and LearnCs.Lib.Complex.Sinh().
Ln() [2/2]
Complex LearnCs.Lib.Complex.Ln () inline
Definition at line 734 of file Complex.cs.
References LearnCs.Lib.Complex.Ln().
Referenced by LearnCs.Lib.Complex.Log(), LearnCs.Lib.Complex.Log2(), and LearnCs.Lib.Complex.Pow().
Pow() [4/6]
Complex LearnCs.Lib.Complex.Pow (int power) inline
Definition at line 746 of file Complex.cs.
References LearnCs.Lib.Complex.Pow().
Pow() [5/6]
Complex LearnCs.Lib.Complex.Pow (int n, int rootIndex) inline
Definition at line 755 of file Complex.cs.
References LearnCs.Lib.Complex.Pow().
Pow() [6/6]
Complex LearnCs.Lib.Complex.Pow (Complex z) inline
Definition at line 760 of file Complex.cs.
References LearnCs.Lib.Complex.Pow().
Sin() [2/2]
Complex LearnCs.Lib.Complex.Sin () inline
Definition at line 765 of file Complex.cs.
References LearnCs.Lib.Complex.Sin().
Referenced by LearnCs.Lib.Complex.Cot(), and LearnCs.Lib.Complex.Tan().
Cos() [2/2]
Complex LearnCs.Lib.Complex.Cos () inline
Definition at line 770 of file Complex.cs.
Referenced by LearnCs.Lib.Complex.Cot(), and LearnCs.Lib.Complex.Tan().
Tan() [2/2]
Complex LearnCs.Lib.Complex.Tan () inline
Definition at line 776 of file Complex.cs.
Cot() [2/2]
Complex LearnCs.Lib.Complex.Cot () inline
Definition at line 782 of file Complex.cs.
Atan()
Complex LearnCs.Lib.Complex.Atan () inline
Definition at line 788 of file Complex.cs.
Sinh() [2/2]
Complex LearnCs.Lib.Complex.Sinh () inline
Definition at line 794 of file Complex.cs.
Referenced by LearnCs.Lib.Complex.Coth(), and LearnCs.Lib.Complex.Tanh().
Cosh() [2/2]
Complex LearnCs.Lib.Complex.Cosh () inline
Definition at line 800 of file Complex.cs.
Referenced by LearnCs.Lib.Complex.Coth(), and LearnCs.Lib.Complex.Tanh().
Tanh() [2/2]
Complex LearnCs.Lib.Complex.Tanh () inline
Definition at line 806 of file Complex.cs.
Coth() [2/2]
Complex LearnCs.Lib.Complex.Coth () inline
Definition at line 812 of file Complex.cs.
Equals()
override bool LearnCs.Lib.Complex.Equals (object obj) inline
Overrides object.equals method. Returns true if obj is also Complex and it has the same value, otherwise it returns false.
Parameters
obj Object that is compared with the current complex number for equality.
Returns
Definition at line 829 of file Complex.cs.
References LearnCs.Lib.Complex.Complex(), LearnCs.Lib.Complex.Im, and LearnCs.Lib.Complex.Re.
GetHashCode()
override int LearnCs.Lib.Complex.GetHashCode () inline
Override of object.GetHashCode() suitable for complex numbers;
Returns
An integer hash code of the current complex number, suitable for use in hash tables.
Definition at line 841 of file Complex.cs.
References LearnCs.Lib.Complex.Im, and LearnCs.Lib.Complex.Re.
Get_HashCode1()
int LearnCs.Lib.Complex.Get_HashCode1 () inline private
A candidate for object.GetHashCode() override. See also:
https://stackoverflow.com/questions/1646807/quick-and-simple-hash-code-combinations
https://stackoverflow.com/questions/638761/gethashcode-override-of-object-containing-generic-array
https://stackoverflow.com/questions/299304/why-does-javas-hashcode-in-string-use-31-as-a-multiplier
Returns
Definition at line 851 of file Complex.cs.
References LearnCs.Lib.Complex.Im, and LearnCs.Lib.Complex.Re.
Get_HashCode2()
int LearnCs.Lib.Complex.Get_HashCode2 () inline private
A candidate for object.GetHashCode() override.
See: https://stackoverflow.com/questions/1646807/quick-and-simple-hash-code-combinations
Definition at line 864 of file Complex.cs.
References LearnCs.Lib.Complex.Im, and LearnCs.Lib.Complex.Re.
Get_HashCode3()
int LearnCs.Lib.Complex.Get_HashCode3 () inline private
A candidate for object.GetHashCode() override.
See: https://stackoverflow.com/questions/1646807/quick-and-simple-hash-code-combinations
Definition at line 871 of file Complex.cs.
Get_HashCode5()
int LearnCs.Lib.Complex.Get_HashCode5 () inline private
A candidate for object.GetHashCode() override. Leverages framework's implementation for tuples.
Definition at line 882 of file Complex.cs.
References LearnCs.Lib.Complex.Im, and LearnCs.Lib.Complex.Re.
ToString()
override string LearnCs.Lib.Complex.ToString () inline
Definition at line 918 of file Complex.cs.
ToStringShort()
string LearnCs.Lib.Complex.ToStringShort () inline
Returns a short form string representation of a complex number.
Definition at line 924 of file Complex.cs.
References LearnCs.Lib.Complex.Im, and LearnCs.Lib.Complex.Re.
TryParse()
static bool LearnCs.Lib.Complex.TryParse (string s, out Complex result) inline static
Parses complex number from its string representation.
String representaition must be in form "(Re + Im)", e.g.:
"(2.5 , 4.21)", "(12.5 , -1.22)", "(5.4 , -2.5)", "(3, 35)", "(12, -4.56)"
Whitespace characters don't matter. The following forms are also legitimate:
" (2.5 , 4.21) ", "(12.5, -1.22)", "(5.4, -2.5)", " (3.3, 88)", "(12, 45)"
Parameters
s String to be parsed.
result The variable where the result will be stored. (0 , 0) is stored if not successful.
Returns
True if parsing was successful and meaningful value is writen to result , false if not (in which case (0 , 0) is written to result).
Definition at line 952 of file Complex.cs.
References LearnCs.Lib.Complex.Complex().
Referenced by LearnCs.Lib.Complex.Parse().
ParseRobust()
static Complex LearnCs.Lib.Complex.ParseRobust (string s) inline static
Parses complex number from its string representation.
String representation of various forms are allowed and whitespaces are ignored.
Basic representations (Re and Im are for real and imaginary values and can be replaced by any number representation understood by double.Parse(string); minimal spaces are included except where space contributes to readability):
"Re" - just the real part, no brackets around it (parsable by double.Parse(string)), e.g. " -2.3e6 "
"(Re)" - just the real part with brackets around it, e.g. " (-2.3e6) "
"Im i" - just the imaginary part followed by "i", no brackets around it, e.g. "-2.3e6i", " -2.3e6 i ", "-2.3e6i "
"Im*i" - just the imaginary part followed by "*i", no brackets around it (parsable by double.Parse(string)), e.g. "-2.3e6 i"
Remark: cannot omit "i" when there is only the imaginary part.
"(Im i)" - just the imaginary part followed by "i" with brackets around it, e. g. " (-2.3e6i)", " (-2.3e6 i) ", "(-2.3e6i) "
Remark: cannot omit "i" when there is only the imaginary part.
"(Im*i)" - just the imaginary part followed by "*i", inside brackets, e. g. " (-2.3e6*i)", " (-2.3e6 * i) ", "(-2.3e6 *i) "
"Re, Im" - comma separated real and imaginary part, e.g. " -2.3e6, 7.48 ", "-2.3e6,7.48 "
"Re, Im i" - comma separated real part and imaginary part followed by "i", e.g. " -2.3e6, 7.48i ", "-2.3e6,7.48 i"
"Re, Im*i" - comma separated real part and imaginary part followed by "*i", e.g. " -2.3e6, 7.48*i ", "-2.3e6,7.48 * i"
"(Re, Im i)" - comma separated real and imaginary part, inside brackets, e.g. " (-2.3e6, 7.48i) ", "(-2.3e6,7.48 i)"
"Re+Im i" - + separated real part and imaginary part followed by "i", e.g. " -2.3e6+ 7.48i ", " -2.3e6 + 7.48 i "
"Re+Im*i" - + separated real part and imaginary part followed by "*i", e.g. " -2.3e6+ 7.48*i ", " -2.3e6 +7.48 * i"
"Re-Im i" - - separated real part and imaginary part followed by "i", e.g. " -2.3e6- -7.48i ", " -2.3e6 --7.48 i ", " -2.3e6 - -7.48 i"
"Re-Im*i" - - separated real part and imaginary part followed by "*i", e.g. " -2.3e6- -7.48*i ", " -2.3e6 --7.48 *i ", " -2.3e6 - -7.48 * i"
"(Re+Im i)" - + separated real part and imaginary part followed by "i", inside brackets, e.g. " (-2.3e6+ 7.48i) ", "(-2.3e6 + 7.48 i)"
"(Re+Im*i)" - + separated real part and imaginary part followed by "*i", inside brackets, e.g. "(-2.3e6+7.48*i)", " (-2.3e6 +7.48 * i)"
"(Re+Im i)" - - separated real part and imaginary part followed by "i", inside brackets, e.g. "(-2.3e6- -7.48i)", "(-2.3e6 --7.48 i)", " (-2.3e6 - -7.48 i)"
"(Re+Im*i)" - - separated real part and imaginary part followed by "*i", inside brackets, e.g. " (-2.3e6- -7.48*i) ", "(-2.3e6 --7.48 *i)", "(-2.3e6 - -7.48 * i)"
Practical examples of different representations:
Comma separated real and imaginary part, with or without round brackets, with or without 'i' for imaginary unit (optionally following *'):
"(Re, Im)": "(2.5 , 4.21)", "(12.5,-1.22)", "(5.4,-2.5)", "(3, 35)", "(12e-5, -4.56e-10)"
"Re, Im ": "2.5 , 4.21", " 12.5,-1.22 ", " 5.4,-2.5", " 3, 35 ", "12e-5, -4.56e-10"
"(Re, Im i)": "(2.5 , 4.21 i)", "(12.5,-1.22i)", "(5.4,-2.5 * i)", "(3, 35 *i)", "(12e-5, -4.56e-10*i)"
"Re, Im i": "2.5 , 4.21 i", " 12.5,-1.22 *i ", " 5.4,-2.5i", " 3, 35 * i", "12e-5, -4.56e-10*i"
Purely real numbers:
" (2.5) ", "(12.5)", "(5.4)", " (3.3)", "(12.3e4)", "(0.1e-6)"
" 2.5 ", "12.5", "5.4", " 3.3 ", "12.3e4", " 0.1e-6 "
Purely imaginary numbers:
" (2.5 i) ", "(12.5i)", "(5.4 * i)", " (3.3* i)", "(12.3e4*i)", "(0.1e-6 * i)"
" 2.5 i ", "12.5i", "5.4" * i" 3.3* i", "12.3e4*i", " 0.1e-6 * i "
Parameters
s String to be parsed.
Returns
If parsing was successful, the complex number represented by s . Otherwise, InvalidOleVariantTypeException is thrown.
Exceptions
FormatException When the string is not formatted according to rules and a complex number could not be successfully inferred from the intended string representation.
Definition at line 1038 of file Complex.cs.
References LearnCs.Lib.Complex.Complex().
Referenced by LearnCs.Lib.Complex.TryParseRobust().
TryParseRobust()
static bool LearnCs.Lib.Complex.TryParseRobust (string s, out Complex result) inline static
Parses a complex number (of type Complex) from the string s , stores the result in result , and returns true if parsing was successful and false if not. This metthod calls ParseRobust(string) to do the job, therefore parsing is the same, just that this method does not throw an exception if parsing does not succeed, but rather returns a value indicating success or failure. See documentation for ParseRobust(string) for formats that can be parsed.
Parameters
s The string from which a complex number is parsed.
result Variable where the parsed complex number is tored. 0 + 0 i is stored if parsig is not successful.
Returns
True if parsing is successful, false if not (i.i., the string does not contain a meaningful representation of a complx number in a supported forms).
Definition at line 1247 of file Complex.cs.
References LearnCs.Lib.Complex.ParseRobust().
Parse()
static Complex LearnCs.Lib.Complex.Parse (string s) inline static
Parses complex number from its string representation and returns it. Exception is thrown if the value cannot be parsed from the string.
Parameters
s String representation of the complex number from which the value will be parsed.
Returns
The complex number whose value has been parsed from the string.s .
Exceptions
FormatException When the string s does not contain a known representation of a complex number that could be parsed. Use TryParse(string, out Complex) to avoid thrown an exception, and provide success information in the returned value instead.
Definition at line 1270 of file Complex.cs.
References LearnCs.Lib.Complex.TryParse().
Member Data Documentation
_re
double LearnCs.Lib.Complex._re private
Underlying field for the property Re
Definition at line 157 of file Complex.cs.
_im
double LearnCs.Lib.Complex._im private
Underlying field for the property Im
Definition at line 160 of file Complex.cs.
AbsoluteValue
double LearnCs.Lib.Complex.AbsoluteValue
Initial value:
=>
            Math.Sqrt(Re * Re + Im * Im)
Gets absolute value (or magnitude) of the current complex number.
Definition at line 184 of file Complex.cs.
Referenced by LearnCs.Lib.NumberOperationsComplex.Absolute(), and LearnCs.Lib.Complex.Ln().
R
double LearnCs.Lib.Complex.R => Math.Sqrt(Re * Re + Im * Im)
Gets the modulus (or magnitude, or absolute value) of the current complex number. This is the radius of the polar form of a complex number.
Definition at line 191 of file Complex.cs.
Referenced by LearnCs.Lib.Complex.Pow(), LearnCs.Lib.Complex.Root(), and LearnCs.Lib.Complex.Sqrt().
Phi
double LearnCs.Lib.Complex.Phi => (Math.Atan2(Im, Re))
Gets the argument of the current complex number. This is the angle parameter of the polar coordinates of a complex number.
Definition at line 203 of file Complex.cs.
Referenced by LearnCs.Lib.Complex.Pow(), LearnCs.Lib.Complex.Root(), and LearnCs.Lib.Complex.Sqrt().
Magnitude
double LearnCs.Lib.Complex.Magnitude => R
Alias for the property R.
Definition at line 210 of file Complex.cs.
Modulus
double LearnCs.Lib.Complex.Modulus => R
Alias of the property R.
Definition at line 214 of file Complex.cs.
Argument
double LearnCs.Lib.Complex.Argument => Phi
Alias for the property Phi. Avoid using this alias.
Definition at line 218 of file Complex.cs.
Referenced by LearnCs.Lib.Complex.Ln().
Fi
double LearnCs.Lib.Complex.Fi => Phi
Please do not use, this property might be deprecated in the future.
Alias for the property Phi.
Definition at line 223 of file Complex.cs.
Negative
Complex LearnCs.Lib.Complex.Negative => new Complex(-Re, -Im)
Gets the negative value of the current complex number.
Definition at line 227 of file Complex.cs.
Conjugate
Complex LearnCs.Lib.Complex.Conjugate => new Complex(Re, -Im)
Gets the complex conjugate of the current complex number.
Definition at line 231 of file Complex.cs.
Referenced by LearnCs.Lib.NumberOperationsComplex.ConjugateNumber().
IsReal
bool LearnCs.Lib.Complex.IsReal => Im == 0
True if the current complex number is a real number (i.e., it can be converted to double, i.e., its imaginary part is 0). False otherwise.
Definition at line 239 of file Complex.cs.
IsInteger
bool LearnCs.Lib.Complex.IsInteger
Initial value:
=> IsReal && Math.Round(Re) == Re
            && Re >= long.MinValue && Re <= long.MaxValue
True if the current complex number is an integer number (it can be converted to long, i.e., its imaginary part is 0, its real par does not have the decimal part but only the integer part, and it is within the range of long).
Definition at line 248 of file Complex.cs.
IsInt
bool LearnCs.Lib.Complex.IsInt
Initial value:
=> IsReal && Math.Round(Re) == Re
            && Re >= int.MinValue && Re <= int.MaxValue
True if the current complex number is an integer number that fits into int (it can be converted to int, i.e., its imaginary part is 0, its real par does not have the decimal part but only the integer part, and it is within the range of int).
Definition at line 259 of file Complex.cs.
ConstZero
const double LearnCs.Lib.Complex.ConstZero = 0 static
Double constant 0.0.
Note there is an implicit conversion from double to Complex.
Definition at line 389 of file Complex.cs.
ConstOne
const double LearnCs.Lib.Complex.ConstOne = 1 static
Double constant 1.0.
Note there is an implicit conversion from double to Complex.
Definition at line 393 of file Complex.cs.
ConstPI
const double LearnCs.Lib.Complex.ConstPI = Math.PI static
Double constant Pi, the ratio of circumference and diameter of the circle (the same as Math.PI).
Note there is an implicit conversion from double to Complex.
Definition at line 398 of file Complex.cs.
ConstE
const double LearnCs.Lib.Complex.ConstE = Math.E static
Double constant E, the basis of natural logarithm (the same as Math.E).
Note there is an implicit conversion from double to Complex.
Definition at line 402 of file Complex.cs.
Property Documentation
Re
double LearnCs.Lib.Complex.Re get set
Gets the real part of the complex number.
This property is read only because we want type Complex to be immutable (after assignment, we cannot modify content).
WARNING:
If Re is defined without the underlying field (field added implicitly by the compiler) then it is not serialized, and serialization/deserialization will not work, even if it is equipped with the JsonIncludeAttribute.
Definition at line 167 of file Complex.cs.
Referenced by LearnCs.Lib.Complex.Add(), LearnCs.Lib.Complex.AreNotEqual(), LearnCs.Lib.Complex.Complex(), LearnCs.Lib.Complex.Cos(), LearnCs.Lib.Complex.Divide(), LearnCs.Lib.Complex.Equals(), LearnCs.Lib.Complex.Exp(), LearnCs.Lib.Complex.Get_HashCode1(), LearnCs.Lib.Complex.Get_HashCode2(), LearnCs.Lib.Complex.Get_HashCode5(), LearnCs.Lib.Complex.GetConjugate(), LearnCs.Lib.Complex.GetHashCode(), LearnCs.Lib.Complex.GetNegative(), LearnCs.Lib.Complex.IsApproximatelyInt(), LearnCs.Lib.Complex.IsApproximatelyInteger(), LearnCs.Lib.Complex.Multiply(), LearnCs.Lib.Complex.operator double(), LearnCs.Lib.Complex.operator!=(), LearnCs.Lib.Complex.operator*(), LearnCs.Lib.Complex.operator+(), LearnCs.Lib.Complex.operator-(), LearnCs.Lib.Complex.operator/(), LearnCs.Lib.Complex.operator==(), LearnCs.Lib.Complex.Sin(), LearnCs.Lib.Complex.Subtract(), LearnCs.Lib.Complex.ToInt(), LearnCs.Lib.Complex.ToInteger(), LearnCs.Lib.Complex.ToReal(), and LearnCs.Lib.Complex.ToStringShort().
Im
double LearnCs.Lib.Complex.Im get set
Gets the imaginary part of the current complex number.
This property is read only.
WARNING:
If Re is defined wighout the underlying field (field added implicitly by the compiler) then it is not serialized, and serialization/deserialization will not work, even if it is equipped with the JsonIncludeAttribute.
Definition at line 174 of file Complex.cs.
Referenced by LearnCs.Lib.Complex.Add(), LearnCs.Lib.Complex.AreNotEqual(), LearnCs.Lib.Complex.Complex(), LearnCs.Lib.Complex.Cos(), LearnCs.Lib.Complex.Divide(), LearnCs.Lib.Complex.Equals(), LearnCs.Lib.Complex.Exp(), LearnCs.Lib.Complex.Get_HashCode1(), LearnCs.Lib.Complex.Get_HashCode2(), LearnCs.Lib.Complex.Get_HashCode5(), LearnCs.Lib.Complex.GetConjugate(), LearnCs.Lib.Complex.GetHashCode(), LearnCs.Lib.Complex.GetNegative(), LearnCs.Lib.Complex.IsApproximatelyInt(), LearnCs.Lib.Complex.IsApproximatelyInteger(), LearnCs.Lib.Complex.IsApproximatelyReal(), LearnCs.Lib.Complex.Multiply(), LearnCs.Lib.Complex.operator double(), LearnCs.Lib.Complex.operator!=(), LearnCs.Lib.Complex.operator*(), LearnCs.Lib.Complex.operator+(), LearnCs.Lib.Complex.operator-(), LearnCs.Lib.Complex.operator/(), LearnCs.Lib.Complex.operator==(), LearnCs.Lib.Complex.Sin(), LearnCs.Lib.Complex.Subtract(), and LearnCs.Lib.Complex.ToStringShort().
Zero
Complex LearnCs.Lib.Complex.Zero = (0, 0) static get
Gets the complex 0 (a constant).
Definition at line 371 of file Complex.cs.
One
Complex LearnCs.Lib.Complex.One = (1.0, 0) static get
Gets the complex 1 (a constant).
Definition at line 374 of file Complex.cs.
PI
Complex LearnCs.Lib.Complex.PI = (Math.PI, 0) static get
Gets the real-valued constant Pi (= Math.PI), the ratio of circumference and diameter of a circle, as complex number.
Definition at line 378 of file Complex.cs.
E
Complex LearnCs.Lib.Complex.E = (Math.E, 0) static get
Gets the real-valued constant E (= Math.E), the basis of natural logarithm, as complex number.
Definition at line 382 of file Complex.cs.
I
Complex LearnCs.Lib.Complex.I = new Complex(0, 1) static get
Gets the imaginary unit i.
Definition at line 385 of file Complex.cs.
The documentation for this struct was generated from the following file:
IGLibCore/tests/IGLib.TestBase/SampleClasses/Complex.cs